### ISSUE TITLE
[Question]: InvalidRequestError: The model `text-davinci-003` has been deprecated, when execute the code‘’response = query_engine.query(input_text)‘’

### ISSUE THREAD

**Issue by whutxd** [run-llama/llama_index#10007]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

my code used to work well, it helped to answer questions for multiple pdfs.
today i find it does not work， and indicate【InvalidRequestError: The model `text-davinci-003` has been deprecated， learn more here: https://platform.openai.com/docs/deprecations】
![image](https://github.com/run-llama/llama_index/assets/112145594/3f47663d-ef27-4f78-be99-9a9bda5eb29f)
i find text-davinci-003 shut down on 2024-01-04，maybe because text-davinci-003 is no longger supported.
![image](https://github.com/run-llama/llama_index/assets/112145594/693560f0-2df9-4af1-ba86-7496501573ea)
anyone can help me how to solve this problem, tks a lot.

**Comment by whutxd** [comment]
llama-index==0.6.38.post1
openai==0.27.8

**Comment by logan-markewich** [comment]
Hey @whutxd -- `text-davinci-003` has been deleted by OpenAI

Newer versions of llama-index use `gpt-3.5-turbo` as the default LLM.

Alternatively, you can set the LLM in the service context to be `gpt-3.5-turbo`  

Although 0.6.38 is pretty old, I forget the process for changing the LLM. I'm going to guess it's something like

```
from llama_index.llms import OpenAI
from llama_index import ServiceContext

service_context= ServiceContext.from_defaults(llm=OpenAI(llm="gpt-3.5-turbo"))

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

# or when loading
index = load_index_from_storage(...., service_context=service_context)
```

**Comment by whutxd** [comment]
i update the version for llama-index which solve the problem
