### ISSUE TITLE
[Feature Request]: Support AzureOpenAI agent.

### ISSUE THREAD

**Issue by ishinzhang** [run-llama/llama_index#10004]
### Feature Description

I am following this tutorial to build a multi-document agent: https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html#build-retriever-enabled-openai-agent
But the endpoint I have is AzureOpenAI.
Could you please support `from llama_index.agent import AzureOpenAIAgent`?

**Comment by logan-markewich** [comment]
You can just set thr llm to be azure 

`agent = OpenAIAgent.from_tools(..., llm=AzureOpenAI(...))`

**Comment by logan-markewich** [comment]
Similar for any embeddings needed

**Comment by ishinzhang** [comment]
Yes, I did that. Thx for your confirmation of being able to change the llm. 
```
chat_llm = AzureOpenAI(
    model=chat_deployment,
    deployment_name=chat_deployment,
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)
agent = OpenAIAgent.from_tools(
        query_engine_tools,
        llm=chat_llm,
        verbose=True,
        system_prompt=f"""\
You are a specialized agent designed to answer queries about {wiki_title}.
You must ALWAYS use at least one of the tools provided when answering a question; do NOT rely on prior knowledge.\
""",
    )

```
I finally figured out my problem, fixed it by 
```
from llama_index import set_global_service_context

set_global_service_context(service_context)
```
Thx for your quick response btw!
