### ISSUE TITLE
[Feature Request]: Additional embedding fine-tuning features

### ISSUE THREAD

**Issue by austinmw** [run-llama/llama_index#10003]
### Feature Description

Hi, it seems LlamaIndex is lacking two fine-tuning features which are very easy when using the FlagEmbedding package instead:

1. Hard negative mining
2. Model merging via LM-Cocktail

### Reason

Both of these can significantly impact performance.

### Value of Feature

High!

**Comment by nerdai** [comment]
Thanks @austinmw for the request. Would the workflow then be to train these models and upload them to HF hub for example for inference?

**Comment by hatianzhang** [comment]
@austinmw seems a good feature to add. if you could help, that would be great.
otherwise, I will look into when I get time

**Comment by austinmw** [comment]
Still relevant
