### ISSUE TITLE
[Bug]: SQLDatabase max_string_length has no effect

### ISSUE THREAD

**Issue by rodrigo-pedro** [run-llama/llama_index#10013]
### Bug Description

It seems like the max_string_length parameter of the SQLDatabase class does not do anything. I've been using NLSQLTableQueryEngine, and I've noticed that long strings in the results of an SQL query are truncated. The LLM also interprets that truncated string and not the original string. 

I believe this is happening because not only is the max_string_length not used, but also because [cursor.fetch()](https://github.com/run-llama/llama_index/blob/0ffeecfb84c3d0fc1fc458b7b536def64d5444f2/llama_index/utilities/sql_wrapper.py#L200) returns a Row class. To read the non-truncated value, you need to call "result.column_name" with the correct column name. I believe this isn't being done anywhere.

As a result of this bug, long strings contain a " ... (X characters truncated) ...", regardless of max_string_length value. This variable works in Langchain, and their SQLDatabase class is very similar to llama-index's.

### Version

0.9.29

### Steps to Reproduce

1. Instantiate an SQLDatabase class. Leave the max_string_length as default. Ensure the database contains a really long string.
2. Pass that class instance to an SQL query engine, such as NLSQLTableQueryEngine.
3. Call the query engine with a question. Make sure the LLM generates a query that reads the long string.
4. The SQL results will contain a truncated string.
5. Now change the max_string_length to a large value.
6. Run the query engine again. Notice how the string is still truncated.

**Comment by logan-markewich** [comment]
@rodrigo-pedro if you are up to it, I would encourage you to submit a PR! 🙏🏻
