### ISSUE TITLE
[Feature Request]: Text to DSL (Domain specific language of Elastic Search)

### ISSUE THREAD

**Issue by bkakadiya** [run-llama/llama_index#10018]
### Feature Description

Request to have Text to Elastic search DSL feature. This is similar to Text to SQL functionality. Additionally combine it with readers/elasticsearch.py to get search result. 

- DSL Details: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl.html 
- Possible Default prompt : https://github.com/langchain-ai/langchain/blob/v0.0.303/libs/langchain/langchain/chains/elasticsearch_database/prompts.py

This is what I am thinking:
- Ask for elastic search URL and Index name
- Ask for elastic search api key having permission on that index 
- Fetch index property mapping 
- Generate prompt using index property mapping asking for JSON ES DSL as output
- Use user input along with prompt and hit chat completion API
- Check the flag dsl_only, 
-- if its true return DSL
-- if its false (default) hit elastic search and get response as well. 
 

### Reason

I was not able to find this feature. Let me know if its there. 

Note that this is different from
- Using Elastic Search as a vector store. 
- This is just to request DSL and hit that DSL to get ES documents (similar to text to sql

### Value of Feature

- Can be useful for quick DSL query generation and getting quicker response
- Actual data will not be posted to LLM, only object index schema/property mapping will be posted to LLM

**Comment by bkakadiya** [comment]
This is what I am thinking:

1. Add method in ElasticsearchReader (readers/elasticsearch.py) to get elastic search index metadata fields 

2. Create dsl_query.py in indices/struct_store

- 		It should have NLDSLQueryEngine class 

- 		NLDSLQueryEngine should expect ElasticsearchReader as an argument 
			during construction it should fetch index metadata fields (as defined in #1) and keep it cached
- 		It should have DEFAULT_DSL_TEMPLATE  similar to https://github.com/langchain-ai/langchain/blob/v0.0.303/libs/langchain/langchain/chains/elasticsearch_database/prompts.py
		
- 		It should have query(user_input:str) method 
- 		It should have clear index metadata method 
		
3. Once user invokes query 		
- 		Fetch index metadata if its not there 
- 		Invoke llm chat to get output

**Comment by jaiminee** [comment]
Hi, @bkakadiya 

I am looking for the exact feature of Text-to-ElasticSearch DSL. Could you please share some details on how you approached this issue?

Any reference documentation and code will be really helpful.

Thank You

**Comment by AylinW** [comment]
Hei there, @bkakadiya @jaiminee and @raviteja-cfx 

I am also searching for a Text-to-ElasticSearch DSL opportunity and just came across this project https://github.com/queelius/elasticsearch-lm/blob/main/test.json, maybe it is helpful for any of you guys.
I am happy for any other input as well. :)
