### ISSUE TITLE
[Bug]: OpenSearchVectorStore not compatible with OpenSearch Serverless on AWS

### ISSUE THREAD

**Issue by ecatkins** [run-llama/llama_index#10042]
### Bug Description

Running 

```
client = OpensearchVectorClient(
            endpoint, idx, 1536, embedding_field=embedding_field, text_field=text_field,
            http_auth=auth, use_ssl=True, verify_certs=True, connection_class=RequestsHttpConnection
        )
vector_store = OpensearchVectorStore(client)
vector_store.add(nodes)
```

Results in error shown below

```
`'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'Document ID is not supported in create/index operation request'}`
```

This issue appears to have been [raised & addressed](https://github.com/opensearch-project/opensearch-py/issues/600) in langchain by fixes to both the `opensearch-py` and `langchain` libraries.

I intend to raise a PR that ports the `langchain` fix to `llama-index`

### Version

0.9.30

### Steps to Reproduce

See above

**Comment by blade2005** [comment]
@ecatkins does #10043 fix this issue?

**Comment by ecatkins** [comment]
@blade2005 - Yes, closing
