### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by AI-Aether** [run-llama/llama_index#10047]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Why does making index takes so long when I use llama2 7b and another open source embedding model?

**Comment by logan-markewich** [comment]
It sounds like it's running either on CPU, or even offloading to disk. 

For local models like llama2, you need to run on a GPU for best results. Running through llama.cpp can kind of work for CPU, but it will still be too slow to be usable
