### ISSUE TITLE
TypeError: generate_qa_embedding_pairs() missing 1 required positional argument: 'llm'

### ISSUE THREAD

**Issue by tempdeltavalue** [run-llama/llama_index#10050]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I tried to run colab from these docs (llama_index version 0.9.30)
https://docs.llamaindex.ai/en/stable/examples/finetuning/embeddings/finetune_embedding.html

And I got 

TypeError                                 Traceback (most recent call last)
[<ipython-input-8-dc8aedf359c5>](https://btdvpawkp1d-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240111-060117_RC01_597566451#) in <cell line: 1>()
----> 1 train_dataset = generate_qa_embedding_pairs(train_nodes)
      2 val_dataset = generate_qa_embedding_pairs(val_nodes)
      3 
      4 train_dataset.save_json("train_dataset.json")
      5 val_dataset.save_json("val_dataset.json")

TypeError: generate_qa_embedding_pairs() missing 1 required positional argument: 'llm'

**Comment by logan-markewich** [comment]
@tempdeltavalue yea docs are slightly out of date. As the error mentions, you need to also pass an LLM object to actually generate the questions.

```
from llama_index.llms import OpenAI

llm = OpenAI(model="gpt-3.5-turbo")
train_dataset = generate_qa_embedding_pairs(train_nodes, llm)
```
