### ISSUE TITLE
[Question]: local HuggingFaceEmbedding returns "No API key found for OpenAI."

### ISSUE THREAD

**Issue by tempdeltavalue** [run-llama/llama_index#10051]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question
copy-paste of 
https://github.com/run-llama/llama_index/issues/9676

I do something like that 

```
embed_model = HuggingFaceEmbedding(MODEL_PATH)

service_context = ServiceContext.from_defaults(embed_model=embed_model)

nodes = [TextNode(id_=id_, text=text) for id_, text in corpus.items()] 
index = VectorStoreIndex(
    nodes, 
    service_context=service_context, 
    show_progress=True
)
retriever = index.as_retriever(similarity_top_k=top_k)
```

I get 

```
ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```

"But I want to use my local model, and when I pass None for LLM (Language Model), Llama starts to use some MockLLM, which is not my embedded model."

**Comment by tempdeltavalue** [comment]
please update docs accordingly )

**Comment by tempdeltavalue** [comment]
# index.storage_context.persist(persist_dir="./storage")
loaded_index = load_index_from_storage(StorageContext.from_defaults(persist_dir="./storage"), llm=None)


---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\llms\utils.py:29, in resolve_llm(llm)
     28     llm = OpenAI()
---> 29     validate_openai_api_key(llm.api_key)
     30 except ValueError as e:

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\llms\openai_utils.py:379, in validate_openai_api_key(api_key)
    378 if not openai_api_key:
--> 379     raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)

ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
Cell In[141], line 3
      1 from llama_index import load_index_from_storage
      2 from llama_index.storage.storage_context import StorageContext
----> 3 loaded_index = load_index_from_storage(StorageContext.from_defaults(persist_dir="./storage"), llm=None)

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\indices\loading.py:33, in load_index_from_storage(storage_context, index_id, **kwargs)
     30 else:
     31     index_ids = [index_id]
---> 33 indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
     35 if len(indices) == 0:
     36     raise ValueError(
     37         "No index in storage context, check if you specified the right persist_dir."
     38     )

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\indices\loading.py:78, in load_indices_from_storage(storage_context, index_ids, **kwargs)
     76     type_ = index_struct.get_type()
     77     index_cls = INDEX_STRUCT_TYPE_TO_INDEX_CLASS[type_]
---> 78     index = index_cls(
     79         index_struct=index_struct, storage_context=storage_context, **kwargs
     80     )
     81     indices.append(index)
     82 return indices

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\indices\vector_store\base.py:52, in VectorStoreIndex.__init__(self, nodes, index_struct, service_context, storage_context, use_async, store_nodes_override, insert_batch_size, show_progress, **kwargs)
     50 self._store_nodes_override = store_nodes_override
     51 self._insert_batch_size = insert_batch_size
---> 52 super().__init__(
     53     nodes=nodes,
     54     index_struct=index_struct,
     55     service_context=service_context,
     56     storage_context=storage_context,
     57     show_progress=show_progress,
     58     **kwargs,
     59 )

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\indices\base.py:62, in BaseIndex.__init__(self, nodes, index_struct, storage_context, service_context, show_progress, **kwargs)
     59     else:
     60         raise ValueError("nodes must be a list of Node objects.")
---> 62 self._service_context = service_context or ServiceContext.from_defaults()
     63 self._storage_context = storage_context or StorageContext.from_defaults()
     64 self._docstore = self._storage_context.docstore

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\service_context.py:178, in ServiceContext.from_defaults(cls, llm_predictor, llm, prompt_helper, embed_model, node_parser, text_splitter, transformations, llama_logger, callback_manager, system_prompt, query_wrapper_prompt, pydantic_program_mode, chunk_size, chunk_overlap, context_window, num_output, chunk_size_limit)
    176 if llm_predictor is not None:
    177     print("LLMPredictor is deprecated, please use LLM instead.")
--> 178 llm_predictor = llm_predictor or LLMPredictor(
    179     llm=llm, pydantic_program_mode=pydantic_program_mode
    180 )
    181 if isinstance(llm_predictor, LLMPredictor):
    182     llm_predictor.llm.callback_manager = callback_manager

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\llm_predictor\base.py:109, in LLMPredictor.__init__(self, llm, callback_manager, system_prompt, query_wrapper_prompt, pydantic_program_mode)
    100 def __init__(
    101     self,
    102     llm: Optional[LLMType] = "default",
   (...)
    106     pydantic_program_mode: PydanticProgramMode = PydanticProgramMode.DEFAULT,
    107 ) -> None:
    108     """Initialize params."""
--> 109     self._llm = resolve_llm(llm)
    111     if callback_manager:
    112         self._llm.callback_manager = callback_manager

File ~\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\llama_index\llms\utils.py:31, in resolve_llm(llm)
     29         validate_openai_api_key(llm.api_key)
     30     except ValueError as e:
---> 31         raise ValueError(
     32             "\n******\n"
     33             "Could not load OpenAI model. "
     34             "If you intended to use OpenAI, please check your OPENAI_API_KEY.\n"
     35             "Original error:\n"
     36             f"{e!s}"
     37             "\nTo disable the LLM entirely, set llm=None."
     38             "\n******"
     39         )
     41 if isinstance(llm, str):
     42     splits = llm.split(":", 1)

ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******

**Comment by tempdeltavalue** [comment]
same here
https://github.com/run-llama/llama_index/issues/8615

**Comment by DRM-Free** [comment]
[This](https://github.com/run-llama/llama_index/issues/8615#issuecomment-1791190060) is the answer

**Comment by tempdeltavalue** [comment]
@DRM-Free 

It's not an answer at all

![Screenshot 2024-01-23 182218](https://github.com/run-llama/llama_index/assets/36921178/12588d46-ef46-4cc8-8cd3-93d894f499c6)

**Comment by tempdeltavalue** [comment]
@DRM-Free 

Thank you
