### ISSUE TITLE
[Feature Request]: jaguar vector store adding text tag

### ISSUE THREAD

**Issue by fserv** [run-llama/llama_index#10056]
### Feature Description

This feature is providing a user-defined tag for documents. With a "text_tag" in **kwarg in add(), the text tag can be prepended to stored texts in the vector store.

### Reason

Often in applications, users would like to tag texts in the vector store for LLMs to analyze.  Without the user-provided tag, all text data is read from external documents which may not be associated with user's intention for analysis. Metadata is not enough or not relevant when the text is submitted to LLMs. With this tag, LLMs can combine original documents and user/analyzer provided text information.

### Value of Feature

By supplying the user-provided text tag, the LLM can gain more insights into text data and return more accurate result.

**Comment by logan-markewich** [comment]
This was merged :)
