### ISSUE TITLE
How can i remove file name from excluded_embed_metadata_keys and excluded_llm_metadata_keys?

### ISSUE THREAD

**Issue by alvarojauna** [run-llama/llama_index#10063]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am developing a RAG solution and I dont know how can I remove "file_name" from here

excluded_embed_metadata_keys=['**file_name**', 'file_type', 'file_size', 'creation_date', 'last_modified_date', 'last_accessed_date'], 
excluded_llm_metadata_keys=['**file_name**', 'file_type', 'file_size', 'creation_date', 'last_modified_date', 'last_accessed_date'],

that is from the command response.metadata["image_nodes"][1]

Its a multimodal model and I want that the filenames of images will be taken into account.

Code:
# Create a local Qdrant vector store
client = qdrant_client.QdrantClient(path="qdrant_img_15")

text_store = QdrantVectorStore(
    client=client, collection_name="text_collection"
)
image_store = QdrantVectorStore(
    client=client, collection_name="image_collection"
)
storage_context = StorageContext.from_defaults(
    vector_store=text_store, image_store=image_store
)

# Create the MultiModal index
documents = SimpleDirectoryReader("./data2/").load_data()
index = MultiModalVectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

from llama_index.prompts import PromptTemplate
from llama_index.query_engine import SimpleMultiModalQueryEngine

qa_tmpl_str = (
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information and knowing all information related to Azure architectures or Azure in general, "
    "answer the query.\n"
    "Query: {query_str}\n"
    "Answer: "
)
qa_tmpl = PromptTemplate(qa_tmpl_str)

query_engine = index.as_query_engine(
    multi_modal_llm=openai_mm_llm, text_qa_template=qa_tmpl,similarity_top_k=3
)

query_str = "Dame algun ejemplo de una arquitectura en Azure"
response = query_engine.query(query_str)

**Comment by alvarojauna** [comment]
This didnt work and I dont know how to fix it. Any idea why?



from llama_index.indices.multi_modal.base import MultiModalVectorStoreIndex
from llama_index.vector_stores import QdrantVectorStore
from llama_index import SimpleDirectoryReader, StorageContext
from typing import List

def _exclude_metadata(documents: List[Document]) -> List[Document]:
    """Exclude metadata from documents.

    Args:
        documents (List[Document]): List of documents.
    """
    for doc in documents:
        # Keep only metadata['file_path'] in both embedding and llm content
        # str, which contain extreme important context that about the chunks.
        # Dates is provided for convenience of postprocessor such as
        # TimeWeightedPostprocessor, but excluded for embedding and LLMprompts
        doc.excluded_embed_metadata_keys.extend(
            [
                "file_type",
                "file_size",
                "creation_date",
                "last_modified_date",
                "last_accessed_date",
            ]
        )
        doc.excluded_llm_metadata_keys.extend(
            [
                "file_type",
                "file_size",
                "creation_date",
                "last_modified_date",
                "last_accessed_date",
            ]
        )

    return documents


import qdrant_client
from llama_index import (
    SimpleDirectoryReader,
)


# Create a local Qdrant vector store
client = qdrant_client.QdrantClient(path="qdrant_img_19")

text_store = QdrantVectorStore(
    client=client, collection_name="text_collection"
)
image_store = QdrantVectorStore(
    client=client, collection_name="image_collection"
)
storage_context = StorageContext.from_defaults(
    vector_store=text_store, image_store=image_store
)

# Create the MultiModal index
documents = SimpleDirectoryReader("./data2/").load_data()
documents = _exclude_metadata(documents)

index = MultiModalVectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

**Comment by alvarojauna** [comment]
pls someone help

**Comment by alvarojauna** [comment]
@logan-markewich do u know why?

**Comment by logan-markewich** [comment]
Just remove the key from the list? I'm guessing this is happening on the input document objects

```
for doc in documents:
  doc.excluded_llm_metadata_keys.remove("file_name")
  doc.excluded_embed_metadata_keys.remove("file_name")
```

**Comment by alvarojauna** [comment]
> Just remove the key from the list? I'm guessing this is happening on the input document objects
> 
> ```
> for doc in documents:
>   doc.excluded_llm_metadata_keys.remove("file_name")
>   doc.excluded_embed_metadata_keys.remove("file_name")
> ```

I want to just remove file name so when doing embeddings the name of the image will be also used and not removed

**Comment by lancercat** [comment]
```
        for doc in nodes:
            doc.excluded_embed_metadata_keys.append("file_path");
```
