### ISSUE TITLE
[Question]: Llama index and mixtral 8x7B giving random results or returning garbage value ? What are the optimal recommended settings ?

### ISSUE THREAD

**Issue by timtensor** [run-llama/llama_index#10072]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi I am trying to setup document retrivel engine using llama index together with mixtral 8x7b in colab environment.  I have questions. 
a ) I am getting garbage values in terms of symbols and characters when doing a query .
b)  Sample reponses such as `response = llm.complete("Hello! Can you tell me a poem about cats and dogs?")
` result in response is something like this 'Final Response: #! ! " ▅!▅	
!  	 ▅!  #!#▅  #  !▅$ " #'

why is it so ? It seems to be working with other local llms . 
c) Very slow inference time. Is there a way to improve it ? (in colab environment) 

Setting the llm 
from llama_index.llms import LlamaCPP
```
from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt
llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    model_url = 'https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF/resolve/main/mixtral-8x7b-instruct-v0.1.Q2_K.gguf',
    #model_path = '/content/mixtral-8x7b-instruct-v0.1.Q2_K.gguf',
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    #model_path='/content/mistral-7b-instruct-v0.2.Q5_K_S.gguf',
    temperature=0.1,
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room 3900
    context_window=3900,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 15},
    #n_gpu_layers = 15 ,
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)
```
Setting up llama cpp python 
`!CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install --upgrade --force-reinstall llama-cpp-python --no-cache-dir`

Setting up the embedding 
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
#from llama_index import LangchainEmbedding, ServiceContext

```
embed_model = HuggingFaceEmbeddings(
    model_name="intfloat/multilingual-e5-large"
)
```
Service context 
```
service_context = ServiceContext.from_defaults(
    llm = llm,
    embed_model= embed_model
)
```
Query engine 
```
from llama_index.retrievers import VectorIndexRetriever

retriever = VectorIndexRetriever(
    index=index,
    similarity_top_k=2,
)
```
Query 
`response = query_engine.query("what are the summary of the documents? ")
`
Any help in this regard would be appreciated

**Comment by logan-markewich** [comment]
@timtensor the `messages_to_prompt` and `completion_to_prompt` there is specific to llama2. 

For mixtral instruct, you need to follow their format. https://huggingface.co/mistralai/Mixtral-8x7B-Instruct-v0.1#instruction-format

```
def completion_to_prompt(completion):
  return f"[INST] {completion} [/INST] "

def messages_to_prompt(messages):
  prompt = "\n".join([str(x) for x in messages])
  return completion_to_prompt(prompt)

llm = LlmaCPP(...., completion_to_prompt=completion_to_prompt, messages_to_prompt=messages_to_prompt)
```

**Comment by timtensor** [comment]
@logan-markewich thank you for the quick reply. But it should not matter for the query response right ? That should be decoded irrespectively

**Comment by logan-markewich** [comment]
@timtensor hmm good point (sorry, I jumped the gun, didn't read closely enough)

I'm not 100% sure what's happening there. We are taking the output directly from llama.cpp, so maybe it's an issue in that library?

**Comment by hatianzhang** [comment]
@timtensor could you try use other  method loading `Mixtral-8x7B-Instruct-v0.1`? do you have mistral api or using those https://github.com/search?q=repo%3Arun-llama%2Fllama_index%20Mixtral-8x7B-Instruct-v0.1&type=code

**Comment by timtensor** [comment]
@hatianzhang i dont have mixtral api unfortunately . 

I am not sure what could be the issue , i tried with the modifications that you had suggested. I think it it working in background as I get `prefix hit` message. But the output is garbage values. 

```
@logan-markewich 
def RunQuestion(questionText):
    queryQuestion = "<s>[INST] You are a technology specialist. Answer questions in a positive, helpful and empathetic way. Answer the following question: " + questionText + " [/INST]"

    response = query_engine.query(queryQuestion)

    return response
def completion_to_prompt(completion):
  return f"[INST] {completion} [/INST] "

def messages_to_prompt(messages):
  prompt = "\n".join([str(x) for x in messages])
  return completion_to_prompt(prompt)

```
Basically calling as follows 

`TestQuestions = RunQuestion("summarize the document")`

If i understand correctly it should work out of the box with llama cpp and llama index . 
Also checking the community , perhaps someone has already solved this issue ?

**Comment by timtensor** [comment]
update : it works fine with llama-cpp-python==0.2.23

**Comment by hatianzhang** [comment]
@timtensor nice! thanks
