### ISSUE TITLE
[Question]: Is there a way to receive 'cannot respond to the question' when providing an empty context?

### ISSUE THREAD

**Issue by SkanderHellal** [run-llama/llama_index#10073]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
I am working on an RAG application, and I am encountering the following issue. Specifically, I am filtering the contexts provided to the LLM for response generation. In some instances, the contexts turn out to be empty. Is there a way to use llamaindex to return 'cannot respond to this question' based on the condition that the context is empty?

Thank you.

**Comment by logan-markewich** [comment]
You could just check the response object for an empty response, and add your own message?

**Comment by SkanderHellal** [comment]
Thank you for your response. I'm still struggling to fully understand the concept. Essentially, if my contexts are empty, the Language Model (LLM) will generate an answer based on its general knowledge, which might not be suitable for my specific situation.

In this particular scenario, does llamaindex consider this situation in the RAG pipeline? For instance, does the query_engine provide a standard response if the context is empty, or does it depend on the LLM to reply with "I cannot answer this question"? Are there specific scripts that address this particular case?

**Comment by logan-markewich** [comment]
@SkanderHellal There is no standard response. You can detect the empty response and return whichever text you want

https://colab.research.google.com/drive/1qPmjjK1Pr_H4A-c1rALNb_GAWT6it6uA?usp=sharing
