### ISSUE TITLE
[Question]: Why Service_context is not used in metadata_extractors

### ISSUE THREAD

**Issue by Kirushikesh** [run-llama/llama_index#10074]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was working with some of the metadata_extractors using LangChainLLM in my project. When calling the `KeywordExtractor` api without the **llm** argument throws OpenAI api-key error, even though i `set_global_service_context` with my LangChainLLM, the KeywordExtractor class doesn't look on the `service_context` when the **llm** argument is not passed and it uses `resolve_llm('default')` function to get the OpenAI model as the llm. 

My Question is while some Classes in llama_index uses `service_context` as the class argument and fetches the llm from it, why does the metadata_extractors and other classes are not using it, can it be still modified to use `ServiceContext.from_defaults().llm ` instead of `resolve_llm("default")`.

**Comment by logan-markewich** [comment]
service context is confusing, I know. 

For now, just pass in the LLM to the extractor as a kwarg. Working on a proper global settings object and removing service context soon
