### ISSUE TITLE
[Feature Request]: Specify database index options (pgvector)

### ISSUE THREAD

**Issue by JamesHutchison** [run-llama/llama_index#10079]
### Feature Description

Looking at the documentation and reviewing the code, it appears that there isn't a way to specify the index creation options when using pgvector?

https://github.com/pgvector/pgvector?tab=readme-ov-file#index-options

If this is already possible, I would improve the documentation.

### Reason

The lack of this functionality makes things confusing. What's it using under the hood? How does this affect the retrieval options?

**Comment by logan-markewich** [comment]
Yea I think it's largely not configurable right now. The syntax is pretty confusing for most users, so the default should (hopefully?) be decent enough.

If you have ideas on how to expose this, very open to a PR. Currently, there are some hard-coded fields that need to be present for the query and add functions to work, which I think makes customization a little harder.

https://github.com/run-llama/llama_index/blob/eff5b5ded2fc2a1d23fcb428f00c365603c893d9/llama_index/vector_stores/postgres.py#L27
