### ISSUE TITLE
I now want to manually insert a node into es using TextNode, but I cannot specify ref_ Doc_ ID, document_ ID, doc_ ID, which is the node to primary ID

### ISSUE THREAD

**Issue by rzechen** [run-llama/llama_index#10088]
### Bug Description

<img width="622" alt="image" src="https://github.com/run-llama/llama_index/assets/24729413/7f1c7efc-2adc-4612-a390-50ca6d11b755">

### Version

0.8.61

### Steps to Reproduce

node1 = TextNode(id_="1", metadata={"ref_doc_id": "xxxxxxxx"}, text="文本内容1")
node2 = TextNode(id_="2", metadata={"ref_doc_id": "xxxxxxxx"}, text="文本内容2")

# set relationships
node1.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(
    node_id=node2.node_id
)
node2.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(
    node_id=node1.node_id
)
nodes = [node1, node2]

**Comment by rzechen** [comment]
<img width="1595" alt="image" src="https://github.com/run-llama/llama_index/assets/24729413/46502947-f38b-4389-afc7-1c8943d42d86">

**Comment by logan-markewich** [comment]
@rzechen ref doc id is not set by the metadata. It's actually a relationship 

You'll want to do something like this
```
from llama_index.schema import NodeRelationship, RelatedNodeInfo


node.relationships[NodeRelationship.PARENT] = RelatedNodeInfo(
    node_id=ref_doc_id, metadata={}
)
```
