### ISSUE TITLE
[Question]:  LlamaCPP's answer always returns #######.....

### ISSUE THREAD

**Issue by nttng207** [run-llama/llama_index#10085]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have the code below: 
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])
model_url = "https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/resolve/main/mistral-7b-instruct-v0.1.Q4_K_S.gguf?download=true"

llm = LlamaCPP(model_url=model_url, model_path=None,
    temperature=0.1,
    max_new_tokens=256,
    model_kwargs={"n_gpu_layers": 100},
    context_window=1000,
    callback_manager = callback_manager,
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose = True)
response = llm.complete("Hello! Can you tell me a poem about cats and dogs?")
print(response.text)

And it's respond "################################################################################################################################################################################################################################################################
"
Please help me fix this issue

**Comment by nttng207** [comment]
I use Colab Notebook and pip install llama-index, I have tried everything you suggest but still have issue !

**Comment by nttng207** [comment]
@dosu-bot 
I use Colab Notebook and pip install llama-index, I have tried everything you suggest but still have issue !

**Comment by nttng207** [comment]
@dosu-bot If I use an additional gpu layer, it will output "#", I used it a few days ago and it was normal without any problems. It seems there is some new update of LlamaCPP, please provide Can you give me information about this error?

**Comment by hatianzhang** [comment]
@nttng207 which version of LlamaCPP are you using

**Comment by hatianzhang** [comment]
could be somehow similar https://github.com/run-llama/llama_index/issues/10072

**Comment by nttng207** [comment]
@hatianzhang Thanks for answering my question. Issue #10072 is same for me, llama-cpp version = 0.2.23 solves this issue

**Comment by Deeds67** [comment]
I have the same issue. As a workaround, reverting from 0.2.29 to 0.2.23 resolved the issue.
