### ISSUE TITLE
[Bug]: Expected type 'VectorStore', got 'ElasticsearchStore' instead 

### ISSUE THREAD

**Issue by rzechen** [run-llama/llama_index#10082]
### Bug Description

<img width="1272" alt="image" src="https://github.com/run-llama/llama_index/assets/24729413/5c5fec36-4e1e-4f10-81bd-625840a2762f">

### Version

0.9.31 or 0.9.30

### Steps to Reproduce

        es_vector_store = ElasticsearchStore(es_url=config.MODEL_ES_URL, index_name=config.MODEL_VECTOR_INDEX,
                                             es_user=config.MODEL_ES_USER, es_password=config.MODEL_ES_PASSWORD,
                                             batch_size=500)

        self.service_context = ServiceContext.from_defaults(llm=llm, embed_model=embedding,
                                                            chunk_size=2048, chunk_overlap=50)

        self.storage_context = StorageContext.from_defaults(vector_store=es_vector_store)

        self.index = GPTVectorStoreIndex.from_vector_store(vector_store=es_vector_store,
                                                           service_context=self.service_context)

**Comment by logan-markewich** [comment]
Ah this is more of a linting error. It shouldn't actually cause issues

**Comment by logan-markewich** [comment]
Oh wait, was is `ElsaticSearchStore` ?

**Comment by logan-markewich** [comment]
Not a big deal
