### ISSUE TITLE
[Feature Request]: add elasticsearch to dev dependencies

### ISSUE THREAD

**Issue by stmtk1** [run-llama/llama_index#10092]
### Feature Description

elasticsearch is used in test for elasticsearch. So I think elasticsearch is necessary to dev group.

**Comment by logan-markewich** [comment]
Every item we add to the dev dependencies increases the time it takes to run poetry lock

Since the tests are already marked to skip if not installed, I would like to keep this out of the deps. Especially since we are re-organizing our integrations soon as well

**Comment by stmtk1** [comment]
OK. So this issue make no sense, and I will close this.

**Comment by logan-markewich** [comment]
Sorry about that, but thanks!
