### ISSUE TITLE
[Question]: ValueError: No API key found for OpenAI.

### ISSUE THREAD

**Issue by rishabhgupta93** [run-llama/llama_index#10094]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Experts,

Need your help!

I am trying to use LLMSingleSelector with non-OpenAI LLM. I have passed the info in service context as follows:

_from llama_index.selectors.pydantic_selectors import PydanticSingleSelector
from llama_index.selectors.llm_selectors import LLMSingleSelector
from llama_index.query_engine.router_query_engine import RouterQueryEngine

from llama_index.selectors.pydantic_selectors import PydanticSingleSelector
from llama_index.selectors.llm_selectors import LLMSingleSelector
from llama_index.query_engine.router_query_engine import RouterQueryEngine

query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(service_context=service_context),
    query_engine_tools=[list_tool, vector_tool]
)_

But I am still getting error related to OpenAI.

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\llms\utils.py:29, in resolve_llm(llm)
     28     llm = OpenAI()
---> 29     validate_openai_api_key(llm.api_key)
     30 except ValueError as e:

File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\llms\openai_utils.py:379, in validate_openai_api_key(api_key)
    378 if not openai_api_key:
--> 379     raise ValueError(MISSING_API_KEY_ERROR_MESSAGE)

ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

**Comment by logan-markewich** [comment]
@rishabhgupta93 pass the service context into the router as well

```
query_engine = RouterQueryEngine.from_defaults(
  [list_tool, vector_tool],
  service_context=service_context,
  selector=LLMSingleSelector.from_defaults(service_context=service_context)
)
```

**Comment by rishabhgupta93** [comment]
Thanks. it works!!
