### ISSUE TITLE
[Bug]: Unsupported operand type(s) for |: 'dict' and 'dict' in llm/gemini.py

### ISSUE THREAD

**Issue by thanh-cnguyen** [run-llama/llama_index#10101]
### Bug Description

I faced an issue related to dict merging when using Gemini. Per the research, it has conflicts with the Python version. I'm using 3.8 and it can't be upgraded at the current time.

typeerror: unsupported operand type(s) for |: 'dict' and 'dict' in llm/gemini.py

### Version

0.9.19

### Steps to Reproduce

I simply create a llm by initializing it as follows:
Gemini(
                api_key='123Ex',
                model_name='gemini-pro',
                temperature=0.0,
            )

### Relevant Logs/Tracbacks

```shell
Invalid GEMINI model: gemini-pro
Traceback (most recent call last):
  File ".../searches/chatbot.py", line 95, in get_llm
    return Gemini(
  File "/virtualenv/lib/python3.8/site-packages/llama_index/llms/gemini.py", line 96, in __init__
    final_gen_config = {"temperature": temperature} | base_gen_config
TypeError: unsupported operand type(s) for |: 'dict' and 'dict'
```

**Comment by thanh-cnguyen** [comment]
@dosu-bot, That's the internal file of Llama index, and I can't modify it

**Comment by logan-markewich** [comment]
@thanh-cnguyen yea the typing just needs to be updated to use Optional or Union typing. Easy pr (surprised CI didn't catch this)

**Comment by thanh-cnguyen** [comment]
> @thanh-cnguyen yea the typing just needs to be updated to use Optional or Union typing. Easy pr (surprised CI didn't catch this)

Please ping me when it's ready. Thank you

**Comment by thanh-cnguyen** [comment]
@logan-markewich I'm sorry for rushing; I'm at the critical phase of the company project. Due to this minor issue, I have to postpone the release date. Could you or someone fix this issue as soon as possible since you said it was supposed to be an easy PR? Thank you so much

**Comment by logan-markewich** [comment]
If it's urgent, you really could have fixed it yourself too 😉 yea I'll do it now sure

**Comment by logan-markewich** [comment]
@thanh-cnguyen its merged. You can install with `pip install git+https://github.com/run-llama/llama_index.git` -- or it will be in the next release

**Comment by thanh-cnguyen** [comment]
> If it's urgent, you really could have fixed it yourself too 😉 yea I'll do it now sure

Oh I thought it was only for people who work for Llama. @logan-markewich 😮

**Comment by logan-markewich** [comment]
@thanh-cnguyen anyone can fork the repo, make a change, and create a PR. In fact, we highly encourage it! 🚀
