### ISSUE TITLE
[Question]: How to add memory or cache into a packed query pipeline?

### ISSUE THREAD

**Issue by xjw1001002** [run-llama/llama_index#10103]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi all,

I am looking to build a RAG chatbot with advanced query pipeline. So how to add previous conversation memory into a packed query pipeline or queryengine?

**Comment by xjw1001002** [comment]
Suppose I already have the pipeline:
`
class RAGFusionPipelinePack(BaseLlamaPack):
    """RAG Fusion pipeline.

    Create a bunch of vector indexes of different chunk sizes.
    
    > Suppose the fusionRAG DB has already been created by ingest_md_fusionRAG.py
    """

    def __init__(
        self,
        #documents: List[Document],
        path: str = "Vector_DB_storage/fusionRAG",
        embed_model = None,
        llm: Optional[AzureOpenAI] = None,
        llm_new: Optional[AzureOpenAI] = None,
        chunk_sizes: Optional[List[int]] = None,
    ) -> None:
        """Init params."""
        #self.documents = documents
        self.chunk_sizes = chunk_sizes or DEFAULT_CHUNK_SIZES

        # construct index
        self.llm = llm or OpenAI(model="gpt-3.5-turbo")
        self.llm_new = llm_new or OpenAI(model="gpt-3.5-turbo")
        self.embed_model = embed_model
        self.query_engines = []
        self.retrievers = {}
        self.path = path
        for chunk_size in self.chunk_sizes:

            service_context = ServiceContext.from_defaults(llm=self.llm, embed_model = self.embed_model)
            persist_dir = os.path.join(self.path, str(chunk_size))
            storage_context = StorageContext.from_defaults(persist_dir=persist_dir)
            vector_index = load_index_from_storage(storage_context, service_context=service_context)
            self.query_engines.append(vector_index.as_query_engine())
            self.retrievers[str(chunk_size)] = vector_index.as_retriever()
            if chunk_size == max(self.chunk_sizes):
                self.retrievers["bm25"] = BM25Retriever.from_defaults(
                    docstore=vector_index.docstore, similarity_top_k=3
                )

        # define rerank component
        rerank_component = FnComponent(fn=reciprocal_rank_fusion)

        # construct query pipeline
        p = QueryPipeline(verbose = False)
        module_dict = {
            **self.retrievers,
            "input": InputComponent(),
            "summarizer": TreeSummarize(),
            # NOTE: Join args
            "join": ArgPackComponent(),
            "reranker": rerank_component,
        }
        p.add_modules(module_dict)
        # add links from input to retriever (id'ed by chunk_size)
        
        for chunk_size in self.chunk_sizes:
            p.add_link("input", str(chunk_size))
            p.add_link(str(chunk_size), "join", dest_key=str(chunk_size))

        p.add_link("input", "bm25")
        p.add_link("bm25", "join", dest_key="bm25")

        p.add_link("join", "reranker")
        p.add_link("input", "summarizer", dest_key="query_str")
        p.add_link("reranker", "summarizer", dest_key="nodes")

        self.query_pipeline = p

    def get_modules(self) -> Dict[str, Any]:
        """Get modules."""
        return {
            "llm": self.llm,
            "retrievers": self.retrievers,
            "query_engines": self.query_engines,
            "query_pipeline": self.query_pipeline,
        }

    def run(self, *args: Any, **kwargs: Any) -> Any:
        """Run the pipeline."""
        return self.query_pipeline.run(*args, **kwargs)
`

And I use it as `response_raw = pack.run(query=query)`, how can I add history to it?

**Comment by xjw1001002** [comment]
@dosu-bot Suppose I already have the pipeline:

class RAGFusionPipelinePack(BaseLlamaPack):
    """RAG Fusion pipeline.

    Create a bunch of vector indexes of different chunk sizes.
    
    > Suppose the fusionRAG DB has already been created by ingest_md_fusionRAG.py
    """

    def __init__(
        self,
        #documents: List[Document],
        path: str = "Vector_DB_storage/fusionRAG",
        embed_model = None,
        llm: Optional[AzureOpenAI] = None,
        llm_new: Optional[AzureOpenAI] = None,
        chunk_sizes: Optional[List[int]] = None,
    ) -> None:
        """Init params."""
        #self.documents = documents
        self.chunk_sizes = chunk_sizes or DEFAULT_CHUNK_SIZES

        # construct index
        self.llm = llm or OpenAI(model="gpt-3.5-turbo")
        self.llm_new = llm_new or OpenAI(model="gpt-3.5-turbo")
        self.embed_model = embed_model
        self.query_engines = []
        self.retrievers = {}
        self.path = path
        for chunk_size in self.chunk_sizes:

            service_context = ServiceContext.from_defaults(llm=self.llm, embed_model = self.embed_model)
            persist_dir = os.path.join(self.path, str(chunk_size))
            storage_context = StorageContext.from_defaults(persist_dir=persist_dir)
            vector_index = load_index_from_storage(storage_context, service_context=service_context)
            self.query_engines.append(vector_index.as_query_engine())
            self.retrievers[str(chunk_size)] = vector_index.as_retriever()
            if chunk_size == max(self.chunk_sizes):
                self.retrievers["bm25"] = BM25Retriever.from_defaults(
                    docstore=vector_index.docstore, similarity_top_k=3
                )

        # define rerank component
        rerank_component = FnComponent(fn=reciprocal_rank_fusion)

        # construct query pipeline
        p = QueryPipeline(verbose = False)
        module_dict = {
            **self.retrievers,
            "input": InputComponent(),
            "summarizer": TreeSummarize(),
            # NOTE: Join args
            "join": ArgPackComponent(),
            "reranker": rerank_component,
        }
        p.add_modules(module_dict)
        # add links from input to retriever (id'ed by chunk_size)
        
        for chunk_size in self.chunk_sizes:
            p.add_link("input", str(chunk_size))
            p.add_link(str(chunk_size), "join", dest_key=str(chunk_size))

        p.add_link("input", "bm25")
        p.add_link("bm25", "join", dest_key="bm25")

        p.add_link("join", "reranker")
        p.add_link("input", "summarizer", dest_key="query_str")
        p.add_link("reranker", "summarizer", dest_key="nodes")

        self.query_pipeline = p

    def get_modules(self) -> Dict[str, Any]:
        """Get modules."""
        return {
            "llm": self.llm,
            "retrievers": self.retrievers,
            "query_engines": self.query_engines,
            "query_pipeline": self.query_pipeline,
        }

    def run(self, *args: Any, **kwargs: Any) -> Any:
        """Run the pipeline."""
        return self.query_pipeline.run(*args, **kwargs)


And I use it as `response_raw = pack.run(query=query)`, how can I add history to it?

**Comment by logan-markewich** [comment]
@xjw1001002 it's probably helpful to think about how you would want this to work.

It's not currently supported, but I'm wondering what the flow would look like ideally here?

**Comment by logan-markewich** [comment]
(Or at least, it could be supported if you wrote a custom component)

**Comment by xjw1001002** [comment]
> (Or at least, it could be supported if you wrote a custom component)

The second part of bot reply solved my question. And for complex history, probably we can use langchain memory or counterpart modules.

**Comment by logan-markewich** [comment]
Sounds good!
