### ISSUE TITLE
[Question]: What happens if I set a chunk size greater than the sequence length of the embedding model?

### ISSUE THREAD

**Issue by terilias** [run-llama/llama_index#10119]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello!

I have a question about the chunk size and the generation of embeddings. What does LlamaIndex do when I create nodes with a chunk size shorter than the sequence length of the embedding model that I am using? I would expect an error to arise, but the procedure completes normally. For example, I can set the chunk size to 1000 and then use a BGE embedder even though it supports chunks with a size <= 512 tokens. I asked the bot of the LlamaIndex documentation but I am not sure that I got the right answer because I didn't found something on the provided sources.

**Comment by logan-markewich** [comment]
most open-source models will just truncate the text. A more interesting approach might be to average the embeddings across windows of the text, but that's not implemented currently
