### ISSUE TITLE
[Question]: not getting information source

### ISSUE THREAD

**Issue by alvarojauna** [run-llama/llama_index#10116]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a large PDF containing 20,000 pages. After receiving the prompt response, how can I identify and show the page where the information was sourced from?

**Comment by alvarojauna** [comment]
im talking about the source of information of the context (from rag) in the prompt

**Comment by logan-markewich** [comment]
@alvarojauna check the response object

`response.source_nodes` has a list of nodes used to create the response, and each node should have some helpful metadata
