### ISSUE TITLE
[Bug]: resource not found

### ISSUE THREAD

**Issue by ZiyuanLi123** [run-llama/llama_index#10110]
### Bug Description

whne I try to run the following command 
documents = SimpleDirectoryReader('/dbfs/mnt/li/sleep/').load_data()
index = VectorStoreIndex.from_documents(documents)

the error:NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
File <command-4311644350779487>, line 2
      1 documents = SimpleDirectoryReader('/dbfs/mnt/li/sleep').load_data()
----> 2 index = VectorStoreIndex.from_documents(documents,service_context=service_context)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/base.py:112, in BaseIndex.from_documents(cls, documents, storage_context, service_context, show_progress, **kwargs)
    103     docstore.set_document_hash(doc.get_doc_id(), doc.hash)
    105 nodes = run_transformations(
    106     documents,  # type: ignore
    107     service_context.transformations,
    108     show_progress=show_progress,
    109     **kwargs,
    110 )
--> 112 return cls(
    113     nodes=nodes,
    114     storage_context=storage_context,
    115     service_context=service_context,
    116     show_progress=show_progress,
    117     **kwargs,
    118 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py:53, in VectorStoreIndex.__init__(self, nodes, objects, index_struct, service_context, storage_context, use_async, store_nodes_override, insert_batch_size, show_progress, **kwargs)
     51 self._store_nodes_override = store_nodes_override
     52 self._insert_batch_size = insert_batch_size
---> 53 super().__init__(
     54     nodes=nodes,
     55     index_struct=index_struct,
     56     service_context=service_context,
     57     storage_context=storage_context,
     58     show_progress=show_progress,
     59     objects=objects,
     60     **kwargs,
     61 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/base.py:75, in BaseIndex.__init__(self, nodes, objects, index_struct, storage_context, service_context, show_progress, **kwargs)
     73 if index_struct is None:
     74     nodes = nodes or []
---> 75     index_struct = self.build_index_from_nodes(
     76         nodes + objects  # type: ignore
     77     )
     78 self._index_struct = index_struct
     79 self._storage_context.index_store.add_index_struct(self._index_struct)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py:274, in VectorStoreIndex.build_index_from_nodes(self, nodes, **insert_kwargs)
    266 if any(
    267     node.get_content(metadata_mode=MetadataMode.EMBED) == "" for node in nodes
    268 ):
    269     raise ValueError(
    270         "Cannot build index from nodes with no content. "
    271         "Please ensure all nodes have content."
    272     )
--> 274 return self._build_index_from_nodes(nodes, **insert_kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py:246, in VectorStoreIndex._build_index_from_nodes(self, nodes, **insert_kwargs)
    244     run_async_tasks(tasks)
    245 else:
--> 246     self._add_nodes_to_index(
    247         index_struct,
    248         nodes,
    249         show_progress=self._show_progress,
    250         **insert_kwargs,
    251     )
    252 return index_struct

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py:199, in VectorStoreIndex._add_nodes_to_index(self, index_struct, nodes, show_progress, **insert_kwargs)
    196     return
    198 for nodes_batch in iter_batch(nodes, self._insert_batch_size):
--> 199     nodes_batch = self._get_node_with_embedding(nodes_batch, show_progress)
    200     new_ids = self._vector_store.add(nodes_batch, **insert_kwargs)
    202     if not self._vector_store.stores_text or self._store_nodes_override:
    203         # NOTE: if the vector store doesn't store text,
    204         # we need to add the nodes to the index struct and document store

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/vector_store/base.py:107, in VectorStoreIndex._get_node_with_embedding(self, nodes, show_progress)
     96 def _get_node_with_embedding(
     97     self,
     98     nodes: Sequence[BaseNode],
     99     show_progress: bool = False,
    100 ) -> List[BaseNode]:
    101     """Get tuples of id, node, and embedding.
    102 
    103     Allows us to store these nodes in a vector store.
    104     Embeddings are called in batches.
    105 
    106     """
--> 107     id_to_embed_map = embed_nodes(
    108         nodes, self._service_context.embed_model, show_progress=show_progress
    109     )
    111     results = []
    112     for node in nodes:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/indices/utils.py:137, in embed_nodes(nodes, embed_model, show_progress)
    134     else:
    135         id_to_embed_map[node.node_id] = node.embedding
--> 137 new_embeddings = embed_model.get_text_embedding_batch(
    138     texts_to_embed, show_progress=show_progress
    139 )
    141 for new_id, text_embedding in zip(ids_to_embed, new_embeddings):
    142     id_to_embed_map[new_id] = text_embedding

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/core/embeddings/base.py:256, in BaseEmbedding.get_text_embedding_batch(self, texts, show_progress, **kwargs)
    250 if idx == len(texts) - 1 or len(cur_batch) == self.embed_batch_size:
    251     # flush
    252     with self.callback_manager.event(
    253         CBEventType.EMBEDDING,
    254         payload={EventPayload.SERIALIZED: self.to_dict()},
    255     ) as event:
--> 256         embeddings = self._get_text_embeddings(cur_batch)
    257         result_embeddings.extend(embeddings)
    258         event.on_end(
    259             payload={
    260                 EventPayload.CHUNKS: cur_batch,
    261                 EventPayload.EMBEDDINGS: embeddings,
    262             },
    263         )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/embeddings/openai.py:386, in OpenAIEmbedding._get_text_embeddings(self, texts)
    379 """Get text embeddings.
    380 
    381 By default, this is a wrapper around _get_text_embedding.
    382 Can be overridden for batch queries.
    383 
    384 """
    385 client = self._get_client()
--> 386 return get_embeddings(
    387     client,
    388     texts,
    389     engine=self._text_engine,
    390     **self.additional_kwargs,
    391 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/tenacity/__init__.py:289, in BaseRetrying.wraps.<locals>.wrapped_f(*args, **kw)
    287 @functools.wraps(f)
    288 def wrapped_f(*args: t.Any, **kw: t.Any) -> t.Any:
--> 289     return self(f, *args, **kw)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/tenacity/__init__.py:379, in Retrying.__call__(self, fn, *args, **kwargs)
    377 retry_state = RetryCallState(retry_object=self, fn=fn, args=args, kwargs=kwargs)
    378 while True:
--> 379     do = self.iter(retry_state=retry_state)
    380     if isinstance(do, DoAttempt):
    381         try:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/tenacity/__init__.py:325, in BaseRetrying.iter(self, retry_state)
    323     retry_exc = self.retry_error_cls(fut)
    324     if self.reraise:
--> 325         raise retry_exc.reraise()
    326     raise retry_exc from fut.exception()
    328 if self.wait:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/tenacity/__init__.py:158, in RetryError.reraise(self)
    156 def reraise(self) -> t.NoReturn:
    157     if self.last_attempt.failed:
--> 158         raise self.last_attempt.result()
    159     raise self

File /usr/lib/python3.10/concurrent/futures/_base.py:451, in Future.result(self, timeout)
    449     raise CancelledError()
    450 elif self._state == FINISHED:
--> 451     return self.__get_result()
    453 self._condition.wait(timeout)
    455 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /usr/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/tenacity/__init__.py:382, in Retrying.__call__(self, fn, *args, **kwargs)
    380 if isinstance(do, DoAttempt):
    381     try:
--> 382         result = fn(*args, **kwargs)
    383     except BaseException:  # noqa: B902
    384         retry_state.set_exception(sys.exc_info())  # type: ignore[arg-type]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/llama_index/embeddings/openai.py:162, in get_embeddings(client, list_of_text, engine, **kwargs)
    158 assert len(list_of_text) <= 2048, "The batch size should not be larger than 2048."
    160 list_of_text = [text.replace("\n", " ") for text in list_of_text]
--> 162 data = client.embeddings.create(input=list_of_text, model=engine, **kwargs).data
    163 return [d.embedding for d in data]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/openai/resources/embeddings.py:108, in Embeddings.create(self, input, model, encoding_format, user, extra_headers, extra_query, extra_body, timeout)
    102         embedding.embedding = np.frombuffer(  # type: ignore[no-untyped-call]
    103             base64.b64decode(data), dtype="float32"
    104         ).tolist()
    106     return obj
--> 108 return self._post(
    109     "/embeddings",
    110     body=maybe_transform(params, embedding_create_params.EmbeddingCreateParams),
    111     options=make_request_options(
    112         extra_headers=extra_headers,
    113         extra_query=extra_query,
    114         extra_body=extra_body,
    115         timeout=timeout,
    116         post_parser=parser,
    117     ),
    118     cast_to=CreateEmbeddingResponse,
    119 )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/openai/_base_client.py:1167, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1153 def post(
   1154     self,
   1155     path: str,
   (...)
   1162     stream_cls: type[_StreamT] | None = None,
   1163 ) -> ResponseT | _StreamT:
   1164     opts = FinalRequestOptions.construct(
   1165         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1166     )
-> 1167     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/openai/_base_client.py:856, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    847 def request(
    848     self,
    849     cast_to: Type[ResponseT],
   (...)
    854     stream_cls: type[_StreamT] | None = None,
    855 ) -> ResponseT | _StreamT:
--> 856     return self._request(
    857         cast_to=cast_to,
    858         options=options,
    859         stream=stream,
    860         stream_cls=stream_cls,
    861         remaining_retries=remaining_retries,
    862     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-936782d0-483e-4cc8-9466-dad28bc9fea8/lib/python3.10/site-packages/openai/_base_client.py:947, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    944         err.response.read()
    946     log.debug("Re-raising status error")
--> 947     raise self._make_status_error_from_response(err.response) from None
    949 return self._process_response(
    950     cast_to=cast_to,
    951     options=options,
   (...)
    954     stream_cls=stream_cls,
    955 )

NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

### Version

0.9.33

### Steps to Reproduce

<img width="564" alt="setup" src="https://github.com/run-llama/llama_index/assets/156987461/11da5577-6cf4-4d73-ba7d-278ed824e91d">
import os
import getpass
import openai
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_VERSION"] = "2023-07-01-preview"
os.environ["OPENAI_API_BASE"] = "base"
os.environ["OPENAI_API_KEY"] = "key"
#APIKEY = dbutils.secrets.get(scope = "akv", key = "openaikey")
os.environ["OPENAI_API_KEY"] = "key"
#os.environ["OPENAI_API_KEY"] = APIKEY
openai.api_type = "azure"
openai.api_base = "base"
openai.api_version = "2023-07-01-preview"
openai.api_key = os.getenv("OPENAI_API_KEY")
documents = SimpleDirectoryReader('/dbfs/mnt/li/sleep/').load_data()
index = VectorStoreIndex.from_documents(documents)

**Comment by logan-markewich** [comment]
Follow this guide for setting up azure:
https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html
