### ISSUE TITLE
[Question]:  Best Practice for Persisting `index_id` for Multiple Indices Retrieval

### ISSUE THREAD

**Issue by Leonschmitt** [run-llama/llama_index#10127]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I'm currently working on an application where I manage and persist multiple indices. Specifically, I plan to use the function llama_index.indices.loading.load_indices_from_storage(storage_context: StorageContext, index_ids: Optional[Sequence[str]] = None, **kwargs: Any) → List[BaseIndex] to load these indices at a later point.

To use this function effectively, I need a way to store the index_ids for each index. I'm wondering if there's a recommended method or a specific function within the llama_index package designed for the persistent storage of these index_ids?

Thanks in advance for your help!

**Comment by nerdai** [comment]
Can you just use a `dict` and json dump it?
