### ISSUE TITLE
[Feature Request]: Define allowed entity and relation types for KnowledgeGraphIndex

### ISSUE THREAD

**Issue by valentinbuc** [run-llama/llama_index#10120]
### Feature Description

Currently, [llama_index.KnowledgeGraphIndex.from_documets()](https://docs.llamaindex.ai/en/stable/api_reference/indices/kg.html#llama_index.indices.knowledge_graph.KnowledgeGraphIndex.from_documents) can be used to extract triples from documents and construct a KG index. It would be great if it would be possible to define allowed edge and relation types as input arguments, for instance `edge_types=["born_in", "educated_at", "received", "advisor_to"]`, and `entity_types = node_types=["person", "university", "degree", "award", "institution", "location"]`.

I have searched the documentation but could not find anything. Please let me know if I missed something :)

### Reason

None of the current LlamaIndex functionality currently allows  this to my knowledge. I have not yet found an easy workaround.

This feature could probably be implemented with some clever prompt engineering and rule-based output verification. Ideally, a feedback loop could be integrated such that the LLM is told if it generates an undesired relation or entity type and correct itself.

### Value of Feature

1. LlamaIndex currently extracts any kind of features the LLM considers relevant, but these are rather noisy. Imagine I have a selection of news reports and want to extract a KG focusing only on which public figures have interacted with each other. To my knowledge there is no way of doing so using LlamaIndex or any other tool at the moment.

2. Given I already have a KG with a well-defined schema, I would like to enrich it with triples extracted from documents. While doing so, I would like to only add relation and edge types from the current schema. The relations would of course also need to be called the same way, for example we would want the LLM to generate the relation `educated_at` rather than `received_education_from`.

**Comment by hatianzhang** [comment]
@valentinbuc thanks. that is great feedback. we are looking into KG improvement. Let me check whether we can add something quick for `edge_types` and `entity_types ` cc @logan-markewich

**Comment by valentinbuc** [comment]
Thank you! Note that there is also already a [discord thread]([https://discordapp.com/channels/1059199217496772688/1197533055422836796) on this, and we identified two possible workarounds:

- Using a custom `kg_triplet_extract_fn`. However, this of course requires a function that can perform the necessary task.
- Adjusting the `DEFAULT_KG_TRIPLET_EXTRACT_PROMPT` by instructing it to only focus on certain edge and entity types. However, another problem here is that GPT4 does not seem capable to follow these instructions, and does not even manage to stick to entities. This may require a more complex setup with Multi Agent LLMs to get working.

REBEL and DREEAM are other good options for triple extraction, however they are limited to a certain set of relations unless you want to annotate data and train a model yourself.
