### ISSUE TITLE
[Question]: How to create indexes using local LLM and embedding  from a local server path

### ISSUE THREAD

**Issue by Gzj369** [run-llama/llama_index#10137]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a server that is not connected to the internet. so I cannot run llama_index with download  any LLM and embedding in OpenAI or huggingface.co  website. I've noticed that all the provided sample codes require an internet connection to download LLM and embedding files, and there are no examples that read LLM and embedding files from a local server path.

Who can tell me how to create indexes using local LLM and embedding from a local server path.

**Comment by nerdai** [comment]
@Gzj369 dosu's reco on using OpenLLM seems like a good one. Does that at least cover the LLM aspect of your use case? For embeddings, would you be able to use Ollama?

**Comment by Gzj369** [comment]
> @Gzj369 dosu's reco on using OpenLLM seems like a good one. Does that at least cover the LLM aspect of your use case? For embeddings, would you be able to use Ollama?

Glad to see your answer. What I most hope is to use LLM and embeddings  on my local Linux server, because I have downloaded the corresponding model bin file offline and placed it in the local path of my server. 

I have **many  documents (More than 10,000)** to be initialized for  DocumentSummaryIndex. **Currently, I use the API to call LLM, but during initialization the API connection timeout always occurs.** What should I do @nerdai 

![image](https://github.com/run-llama/llama_index/assets/13391430/29403655-a7e3-4b0a-bccf-b493a493df54)
