### ISSUE TITLE
[Question]:  How can I implement Multi Document Agents for Open Source LLMs such as  zephyr-7B-alpha. 

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10149]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Going through the documentation : [https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html] but I would like to implement the same for Open Source LLMs

How can I use ReAct Agent for Open Source LLMs, I tried the same methods used by the guide but the Agent seems to provide me out-of-context answers. Using the query engine gives me a proper response as compared to the Agent.

`query_engine_tools = [
    QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name="vector_tool",
            description=(
                f"Useful for questions related to {document}"
            )
        )
]`

`agent =  ReActAgent.from_tools(
    query_engine_tools,
    llm=function_llm,
    verbose=True,
    system_prompt=f"""\
You are a specialized agent designed to answer queries about {document}.
You must ALWAYS use at least one of the tools provided when answering a question; do NOT rely on prior knowledge.\
""",
)`

**Comment by nerdai** [comment]
@GxTeo unfortunately at current moment using `ReActAgent` is the way to go. From our experiences, using open-source models for this has not been successful — they don't appear to be as good at following tool-use instructions as compared to their GPT counterparts.
