### ISSUE TITLE
chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536[Question]: 

### ISSUE THREAD

**Issue by lawplus** [run-llama/llama_index#10166]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`from pathlib import Path
from llama_index import SimpleDirectoryReader
from llama_index import ServiceContext, VectorStoreIndex
from llama_index.vector_stores import ChromaVectorStore
from llama_index.schema import TextNode
from llama_index import StorageContext, load_index_from_storage
from IPython.display import Markdown, display
from llama_index.llms import OpenAI
from llama_index.embeddings import OpenAIEmbedding
from llama_index.embeddings.openai import OpenAIEmbeddingMode
from llama_index.embeddings.openai import OpenAIEmbeddingModelType
#from llama_index.embeddings import HuggingFaceEmbedding
#from openai import OpenAI
from sentence_transformers import SentenceTransformer
import openai
import autogen
from autogen.agentchat.contrib.gpt_assistant_agent import GPTAssistantAgent
from autogen.agentchat.contrib.retrieve_assistant_agent import RetrieveAssistantAgent
from autogen.agentchat.contrib.retrieve_user_proxy_agent import RetrieveUserProxyAgent
import json
import sys
import os
from dotenv import load_dotenv, find_dotenv
from datetime import datetime
import asyncio
import chromadb
import chromadb.utils.embedding_functions as embedding_functions
from chromadb.config import Settings
from llama_index import ServiceContext, set_global_service_context

os.environ['OPENAI_API_KEY'] = 'sk-'
os.environ['OPENAI_API_BASE'] = 'https://api.fexxx'
print(sys.path)
openai.api_base = "https://api.fexxx"
OpenAI.api_base = 'https://api.fe8xxx'
_ = load_dotenv(find_dotenv())

# give a project name
project_name = "autodev_ktech"

# directory of source - lionagi codebase
data_dir = 'F:/workspace/java/module-medical/'

vertor_dir = "D:/llama-index-data"
collection_name = "meical"
# output dir
output_dir = "data/log/coder/"

# extension of files of interest, can be str or list[str]
reader = SimpleDirectoryReader(
    input_dir = data_dir,
    required_exts=[".java", ".sql"],
    recursive=True
)
# 打印增加时间
print(datetime.now())
print(" - load_data...")
# load documents
docs = reader.load_data()

# build index -- chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536

print(datetime.now())
print(" - vertor...")

openai_ef = embedding_functions.OpenAIEmbeddingFunction(
                api_key=os.environ['OPENAI_API_KEY'],
                #api_base=os.environ['OPENAI_API_BASE'],
                #api_type="openai",
                #api_version="YOUR_API_VERSION",
                model_name=OpenAIEmbeddingModelType.TEXT_EMBED_ADA_002
            )
#students_embeddings = openai_ef(docs)
#print(students_embeddings)
#lm = OpenAI(temperature=0.0, model="gpt-3.5-turbo-0613")# model="gpt-4-1106-preview")
### have a service context using the openai embedding model
embed_model = OpenAIEmbedding(model=OpenAIEmbeddingModelType.TEXT_EMBED_ADA_002)  #dimensionality 1536

# Generate a sample embedding
sample_embedding = embed_model.get_text_embedding("sample text")
# Print the dimension of the sample embedding
print("print test text dimension below: ")
print(len(sample_embedding))

# create client and a new collection
chroma_client = chromadb.PersistentClient(path=vertor_dir)
##chroma_client.delete_collection(name=collection_name)
chromadb_collection = chroma_client.get_or_create_collection(name=collection_name, embedding_function=openai_ef)

# define embedding function
#embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5")

# set up ChromaVectorStore and load in data

#默认： Hugging Face 的 all-MiniLM-L6-v2 模型的嵌入维度是 384
## 后续运行报错：  chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536
c_vector_store = ChromaVectorStore(chroma_collection=chromadb_collection)
storage_context = StorageContext.from_defaults(vector_store=c_vector_store)
service_context = ServiceContext.from_defaults(embed_model=embed_model)
set_global_service_context(service_context)
# 重建；save to disk
index = VectorStoreIndex.from_documents(docs, service_context=service_context, storage_context=storage_context)
###index = GPTVectorStoreIndex(docs, chromadb_collection=chromadb_collection, embed_model=embed_model)
index.set_index_id(collection_name)
index.storage_context.persist(persist_dir=vertor_dir)

## 已有，则load
#index = VectorStoreIndex.from_vector_store(     vector_store,   service_context=service_context, )

print(datetime.now())
print(" - query_engine...")
# Query Data
query_engine = index.as_query_engine()`

please help check my codes. it turns out the chroma db index data build as 384 dimension. but i need to use GPT4 openai embeddings with 1536 dimensions.

**Comment by lawplus** [comment]
hey @Disiok  the bot can't ressolve my problem

**Comment by hatianzhang** [comment]
which emb model are you using 
embed_model = OpenAIEmbedding(model=OpenAIEmbeddingModelType.TEXT_EMBED_ADA_002) #dimensionality 1536

or 
#embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5")

**Comment by hatianzhang** [comment]
could you restart your vector db and using a new collection. pls just use one emb model

**Comment by lawplus** [comment]
i use  OpenAIEmbedding   TEXT_EMBED_ADA_002
it seems i find the root cause. wait some moments..

**Comment by lawplus** [comment]
boss_aid = RetrieveUserProxyAgent(
    name="Boss_Assistant",
    is_termination_msg=termination_msg,
    system_message="Assistant who has extra content retrieval power for solving difficult problems.",
    human_input_mode="NEVER",
    max_consecutive_auto_reply=3,
    retrieve_config={
        "task": "code",
        "docs_path": "D:/AI/autocode",#"https://raw.githubusercontent.com/microsoft/FLAML/main/website/docs/Examples/Integrate%20-%20Spark.md",
        "chunk_token_size": 1000,
        "model": config_list[0]["model"],
        "client": chroma_client, #chromadb.PersistentClient(path=vertor_dir),
        "collection_name": collection_name,
        "get_or_create": True,
        #"embedding_model ": embed_model,
        #"embedding_function ": openai_ef,
    },
    code_execution_config={
        "work_dir": "coding",
        "use_docker": False, 
    }
    #code_execution_config=False,  # we don't want to execute code in this case.
)

**Comment by lawplus** [comment]
Batches: 100%|████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.02s/it]
Traceback (most recent call last):
  File "d:\AI\第二期AGI课堂课件（1-4）\autogen_test\autogen-rag-llamaindex.py", line 252, in <module>
    rag_chat()
  File "d:\AI\第二期AGI课堂课件（1-4）\autogen_test\autogen-rag-llamaindex.py", line 246, in rag_chat
    boss_aid.initiate_chat(
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 672, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\autogen\agentchat\contrib\retrieve_user_proxy_agent.py", line 429, in generate_init_message
    self.retrieve_docs(problem, n_results, search_string)
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\autogen\agentchat\contrib\retrieve_user_proxy_agent.py", line 404, in retrieve_docs
    results = query_vector_db(
    results = collection.query(
              ^^^^^^^^^^^^^^^^^
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\chromadb\api\models\Collection.py", line 345, in query
    query_results = self._client._query(
                    ^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\chromadb\api\segment.py", line 674, in _query
    self._validate_dimension(coll, len(embedding), update=False)
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\chromadb\telemetry\opentelemetry\__init__.py", line 127, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "D:\AI\第二期AGI课堂课件（1-4）\.venv\Lib\site-packages\chromadb\api\segment.py", line 814, in _validate_dimension
    raise InvalidDimensionException(
chromadb.errors.InvalidDimensionException: Embedding dimension 384 does not match collection dimensionality 1536

**Comment by lawplus** [comment]
Trying to create collection.
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: all-MiniLM-L6-v2
Load pretrained SentenceTransformer: all-MiniLM-L6-v2
INFO:autogen.retrieve_utils:Found 0 chunks.
Found 0 chunks.
WARNING:autogen.retrieve_utils:range() arg 3 must not be zero
range() arg 3 must not be zero
Batches:   0%|

**Comment by lawplus** [comment]
@hatianzhang it still not work
