### ISSUE TITLE
[Question]:  How can I retrieve the relevant/useful sources (e.g file paths /filename) of the final response by the SubQuestionQueryEngine

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10161]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am usign SubQuestionQueryEngine to query multiple documents. However, I want to find the relevant sources that provides the response.  Using `response.metadata` shows me all the metadata of all the retrieved documents but some are not relevant or useful in providing the final response.

How can I only retrieve the relevant sources that provides the final response. Thank you

**Comment by GxTeo** [comment]
@dosu-bot . How do i get the qa-pairs from the subquestion query engine?

**Comment by ravi03071991** [comment]
@GxTeo you can check in `response.source_nodes`

**Comment by ravi03071991** [comment]
@GxTeo Also it's a bit tricky to understand these `response.source_nodes`. If the `SubQuestionQueryEngine` creates two sub-queries, the first two nodes in `response.source_nodes` provides the corresponding subquery and answer for both these sub-queries. And the next set of nodes are the actual `source_nodes` for generating answer for these sub-queries. 
Let's say if `similarity_top_k` is 2, with the above process you will find 6 nodes in `response.source_nodes`. It would be intuitive if run through an example.

**Comment by GxTeo** [comment]
thanks @ravi03071991 ,  can i know from `response.source_nodes`, is it possible to determine the actual `source nodes ` that provided the final answer instead of the answer for the sub-queries.

**Comment by ravi03071991** [comment]
yes. Inspect `response.source_nodes`, you should be able to get it.

**Comment by GxTeo** [comment]
@ravi03071991 Yea, i did that, however I am thinking if there is an approach i can take to extract only the **useful/relevant** ( the ones that contribute to the final answer)`source nodes` as compared to manual inspection for every query. Is there a indicator to determine a **relevant** `source node`

**Comment by ravi03071991** [comment]
@GxTeo I guess there is no direct approach but there is a hacky way of doing it. You can follow below code.

```
num_sub_queries = sum(1 for value in response.metadata.values() if not value)
relevant_source_nodes = response.source_nodes[num_sub_queries:]
```

**Comment by GxTeo** [comment]
thank you @ravi03071991, seems like a tricky task. When i ran the code, it returns the source nodes to all the subquestions and all the answers to the subquestions. Was more inclined to the just the source node that contributed to the final answer.

An example would be 

**Doc 1:  [Person 1 who has a background in Computer Science]**
**Doc 2: [Person 2 who has a background in Aerospace Engineering]**

```
Query: Identify the [Person] who has a background in Computing

 SubQuestion[1] : "What is the background of [Doc1]?"
 SubAnswer[1]: "Person1 has a background in Computer Science"

SubQuestion[2] : "What is the background of [Doc2]?"
 SubAnswer[2]: "Person2 has a background in Aerospace"

Final Answer: "Person1 has a background in Computing"

[What I want to do is]
Final Answer:  Person1 has a background in Computing
Source: Information can be found in [Doc1, page 1]                        
```

For now the code you suggested seems to return the `source nodes` for both `SubAnswers`. I was thinking if there is a method to just retrieve the `source nodes ` where in this case `SubAnswer[1]` (The one that contributed to the final answer)

**Comment by ravi03071991** [comment]
@GxTeo got it. It's a bit tricky to find if it's only from one of the sub-answers because sometimes it might use both the sub-answers right? In those cases, you might want to show both the subanswers to the user. 

One way is to calculate the cosine similarity between the final answer and each sub-answer and choose one that has a higher similarity score if you are looking to pick one of them, if you are looking to pick multiple probably setting a threshold seems another approach to try out.

**Comment by GxTeo** [comment]
Yes, you are right! I would look into your suggestions! Thank you @ravi03071991, you have been a great help!
