### ISSUE TITLE
[Question]: Returning more source nodes 

### ISSUE THREAD

**Issue by aminolroayaXgen** [run-llama/llama_index#10160]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

with llama-index of 0.8.62, I want to use document fields from the nodes with highest scores which are retrieved and used by LLama chat engine to answer queries. However, the number of returned nodes in `response.source_nodes` is so low, about two nodes or a node consireng I have 300 nodes in total. I also passed a retriever to my chat engine with similarity top k of 20. however no change in the number of returned nodes occured. Is there any solution for returning more nodes? tnx.

**Comment by ravi03071991** [comment]
@aminolroayaXgen it's working with the following code. You can check the screenshot that it's returning 15 nodes. For debugging would be better to share your code.

```
from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.text_splitter import SentenceSplitter
from llama_index.ingestion import IngestionPipeline

# Load documents
documents = SimpleDirectoryReader(input_files=['ChatQA_Nvidia.pdf']).load_data()
# create the pipeline with transformations
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=2000, chunk_overlap=100),
    ]
)
# run the pipeline
nodes = pipeline.run(documents=documents)
# create index
index = VectorStoreIndex(nodes)

query_engine = index.as_chat_engine(chat_mode="react", similarity_top_k=15)
response = query_engine.chat("Who are the authors of paper?")
print(response)
print(len(response.source_nodes))

```

PS: I am on the latest llama-index version.
<img width="836" alt="Screenshot 2024-01-20 at 7 27 11 PM" src="https://github.com/run-llama/llama_index/assets/12198101/f4dbddb1-3659-426b-b1b8-2f79e1afb7b8">

**Comment by aminolroayaXgen** [comment]
tnx @ravi03071991 . now it retrieves the nodes, but also the response time increases in scale of 10s. Maybe it is because of I am dumping json files as documents when indexing and I dont want to chunk them. Is the a way to directly retrieve document fields instead of nodes?

**Comment by ravi03071991** [comment]
@aminolroayaXgen https://docs.llamaindex.ai/en/latest/examples/query_engine/json_query_engine.html# - did you check this? This might help. Another workaround is to create nodes by reading JSON files one after the other and use `refine` response synthesizer mode. So that each time you retrieve, you actually get topk json files.

**Comment by aminolroayaXgen** [comment]
@ravi03071991 thanks. I reindexed the data with needed meta data. Yes I saw it, but I need to chat with data using chat engines and thought you cannot chat with json query  engines. is that the case?
