### ISSUE TITLE
[Question]: load one document size > 20 M, I got the query result very slow. anyway know the reason?

### ISSUE THREAD

**Issue by Tasarinan** [run-llama/llama_index#10169]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

load one document size > 20 M, I got the query result very slow. anyway know the reason?

 response = query_engine.query("Summarise the story for me")
        # Displays the citations
        for index, node in enumerate(response.source_nodes, start=1):
            print(f"{index}/{len(response.source_nodes)}: |{node.node.metadata['file_name']}| {node.node.get_text()}")

**Comment by nerdai** [comment]
Could you kindly elaborate on your query engine. For example:
- what vector db you are using
- what llm

**Comment by Tasarinan** [comment]
> Could you kindly elaborate on your query engine. For example:
> 
> * what vector db you are using
> * what llm

Chromadb
>llamacpp

**Comment by Tasarinan** [comment]
> _🤖_
> 
> The slowness in query results when loading a document larger than 20 M in LlamaIndex could be related to the way the AstraDBVectorStore handles data.
> 
> In the `add` method of the `AstraDBVectorStore` class, the data is batched into chunks of size `MAX_INSERT_BATCH_SIZE` which is set to 20. This means that if you're trying to load a document larger than 20 M, it will be divided into multiple batches, which could slow down the process.
> 
> ```python
> MAX_INSERT_BATCH_SIZE = 20
> 
> # ...
> 
> def add(
>     self,
>     nodes: List[BaseNode],
>     **add_kwargs: Any,
> ) -> List[str]:
>     # ...
> 
>     # Iterate over the node_list in steps of MAX_INSERT_BATCH_SIZE
>     for i in range(0, len(nodes_list), MAX_INSERT_BATCH_SIZE):
>         # Append a slice of node_list to the batched_list
>         batched_list.append(nodes_list[i : i + MAX_INSERT_BATCH_SIZE])
> 
>     # Perform the bulk insert
>     for i, batch in enumerate(batched_list):
>         _logger.debug(f"Processing batch #{i + 1} of size {len(batch)}")
> 
>         # Go to astrapy to perform the bulk insert
>         self._astra_db_collection.insert_many(batch)
> ```
> 
> Additionally, the `query` method in the `AstraDBVectorStore` class uses the `vector_find` method of the `astrapy` library to find the most similar nodes. This method could be slow if the number of nodes is large, as it needs to calculate the similarity between the query and each node.
> 
> ```python
> def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
>     # ...
> 
>     # Call the vector_find method of AstraPy
>     matches = self._astra_db_collection.vector_find(
>         vector=query_embedding,
>         limit=query.similarity_top_k,
>         filter=query_metadata,
>     )
> ```
> 
> So, yes, the slowness could be related to the vector db (AstraDBVectorStore) and the way it handles large documents. You can find more details in the [llama_index/vector_stores/astra.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/astra.py) file in the LlamaIndex repository.
> 
> ## Sources
> * [llama_index/vector_stores/astra.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/astra.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

How to solve this issue? I am thinking why query so slow even I have set the stream true.
