### ISSUE TITLE
[Question]: SentenceTransformerRerank

### ISSUE THREAD

**Issue by Bearsaerker** [run-llama/llama_index#10172]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have the following problem which I didn't find a solution in the docs for. I want to move the rerank model to the cpu so that I can use a bigger llm on my gpu. I already could do that with "HuggingFaceEmbeddings" but with "SentenceTransformerRerank" I couldn't find any documentation to do that.

**Comment by ravi03071991** [comment]
@Bearsaerker dosu suggested solution should work.
