### ISSUE TITLE
[Question]: memory in ContextChatEngine isn't working

### ISSUE THREAD

**Issue by cocoza4** [run-llama/llama_index#10176]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have defined ContextChatEngine with memory as follows
```
chat_store = SimpleChatStore()
memory = ChatMemoryBuffer.from_defaults(token_limit=3000, chat_store=chat_store,)
chat_engine = ContextChatEngine.from_defaults(hybrid_retriever, service_context=service_context, memory=memory, node_postprocessors=[reranker])
```
```
q = "Tell me about recommendation engine" 
resp = self.chat_engine.stream_chat(q) # this query works
```
However, when I refer to `recommendation engine` as it, the `chat_engine` can't figure that out
```
q = "Tell me about it" 
resp = self.chat_engine.stream_chat(q) # it can't refer to it as recommendation engine
```

How to make this work?

**Comment by logan-markewich** [comment]
If the retrieved nodes are bigger than the token limit, there won't be room for the chat history. Not sure how many nodes you are returning or their size

**Comment by cocoza4** [comment]
@logan-markewich thanks for your response, it turns out to be a bug in my code.
