### ISSUE TITLE
[Question]: Use triplets directly

### ISSUE THREAD

**Issue by rickbeeloo** [run-llama/llama_index#10177]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey all!

I have text files with triplets like:
```
John, is, Male
John, is, 56
Emily, isDaugther, John
Emily, is, 16
etc.
```

Can I use that directly to build the knowledge graph index without converting it to RDF or Neo4J format?

**Comment by logan-markewich** [comment]
I mean, they need to be in some kind of format to build the index.

There's a section here that shows building it from existing triplets 
https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/KnowledgeGraphDemo.html#id1

**Comment by rickbeeloo** [comment]
Thanks @logan-markewich! What I didn't really get is this part:
`nodes = node_parser.get_nodes_from_documents(documents)` 
Is that just a file with the "node" names? and then the code you linked to established the edges for each node?

**Comment by rickbeeloo** [comment]
I namely have a knowledge graph already, nodes and their relationships, so not really documents I have to search through.
