### ISSUE TITLE
doc_id always overwritten by default_id_func

### ISSUE THREAD

**Issue by Morriz** [run-llama/llama_index#10186]
### Bug Description

Hi, according to the [docs here](https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents.html#customizing-the-id) it should be possible to assign a custom `doc_id` to documents. But when creating a list of documents with custom ids, those always get overwritten during the node creation phase.

### Version

0.9.34

### Steps to Reproduce

```py
from llama_index import Document, ServiceContext, StorageContext, VectorStoreIndex
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.retrievers import VectorIndexRetriever
from llama_index.vector_stores import ChromaVectorStore

import chromadb

db = chromadb.PersistentClient(path="./db")
chroma_collection = db.get_or_create_collection("mediabiasfactcheck.com")
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5")
service_context = ServiceContext.from_defaults(embed_model=embed_model)
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

data = ["bla", "dibla"]
documents = []
for i, text in enumerate(data):
    document = Document(doc_id=i, text=text)
    documents.append(document)
index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context, service_context=service_context
)
retriever = VectorIndexRetriever(index=index)
response = retriever.retrieve("bla")
print(response)
```

**Comment by logan-markewich** [comment]
@Morriz the original doc id should be available on `node.ref_doc_id` right? Each document is chunked into nodes, and those nodes contain references to the original parent doc

**Comment by Morriz** [comment]
@logan-markewich no, those are all overwritten with the uuid.
But you were right, we should not rely on the custom id anyway as it all gets chunkified.

I just added the external id to the metadata and got it from there...solved!
