### ISSUE TITLE
[Feature Request]: vLLM acomplete needs to be implemented

### ISSUE THREAD

**Issue by enkiid** [run-llama/llama_index#10183]
### Feature Description

Implement `acomplete` for the vLLM wrapper.

### Reason

To be able to use e.g. the reponse mode `tree_summarize` or other response modes which call `llm.apredict`, `acomplete` needs to be implemented for the vLLM model wrapper. 

Looking at the implementation of `achat`, the solution might be as simple as:
```python
@llm_completion_callback()
async def acomplete(
    self, prompt: str, formatted: bool = False, **kwargs: Any
) -> CompletionResponse:
     kwargs = kwargs if kwargs else {}
     return self.complete(prompt, **kwargs)
```

### Value of Feature

As vLLM improves the throughput of 2-4x, I would say it is super necessary that llama_index supports vLLM fully.

**Comment by nerdai** [comment]
Thanks @enkiid. Took a quick look at vLLM docs, and according to them we would need an `AsyncLLMEngine` (that wraps LLMEngine to make it async) to be able to have a proper implementation of `acomplete`. Certainly would like to have this feature. If you'd like to make a pull request for it, that'd be great.

**Comment by enkiid** [comment]
Hi @nerdai! Understand!
Looking in the vLLM docs, they seem to have a [AsyncLLMEngine](https://docs.vllm.ai/en/latest/dev/engine/async_llm_engine.html), could that be of use or does llama_index need it's own?

**Comment by nerdai** [comment]
Yeah I think that's what's ultimately needed. You'd need to have an `AsyncLLMEngine` that you'd run `generate` against, which in this case would be async. Our implementation of `complete` calls their sync `generate` method in the offline LLMEngine setting.

So to make this sync, we'd need to be working with an AsyncLLMEngine it seems.

**Comment by nerdai** [comment]
Moving this to request for contribution feature board.
