### ISSUE TITLE
[Question]: I have many documents (More than 10,000) to be initialized for DocumentSummaryIndex.  I use the API to call LLM, but during initialization the API connection timeout always occurs.

### ISSUE THREAD

**Issue by Gzj369** [run-llama/llama_index#10184]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Question]: I have many documents (More than 10,000) to be initialized for DocumentSummaryIndex.  I use the API to call LLM, but during initialization the API connection timeout always occurs. What should I do

Initialize documents as DocumentSummaryIndex. How to perform incremental initialization in batches?

![image](https://github.com/run-llama/llama_index/assets/13391430/a67e469c-1b6b-44e1-a5e5-ab12f094a434)

**Comment by nerdai** [comment]
Hey @Gzj369,

You can incrementally add Documents to your index by invoking the `insert()` method.

**Comment by Gzj369** [comment]
> Hey @Gzj369,
> 
> You can incrementally add Documents to your index by invoking the `insert()` method.

@nerdai do you mean this function
![image](https://github.com/run-llama/llama_index/assets/13391430/00c3200b-8bdd-4126-8d2a-c236de7c7fea)

In addition to the nodes parameter, are there any other parameters required, such as service_context， if need service_context, The LLM required by the parameter is assigned through the API url here. So I feel like similar problems will still occur.

Maybe I understand it wrong. Please help me explain in detail how to use the code.

**Comment by nerdai** [comment]
That's the internal, "private" method that is called by `insert` of the parent class. I think you can create your index with a subset of the documents, and then add them in using `index.insert(document)`

**Comment by Gzj369** [comment]
@nerdai yes ,thank you ! 
I just tried it and the method you provided is effective, but there is a problem about index.insert(document). How to control the language of the generated document summary. For example, when I create the index, I set SUMMARY_QUERY to Chinese, with a subset of the documents' document index being Chinese, that's OK,  but the later document index by index.insert generated will default to English . I want later also to be Chinese  for Convenient Q&A.

**Comment by Gzj369** [comment]
> @nerdai yes ,thank you ! I just tried it and the method you provided is effective, but there is a problem about index.insert(document). How to control the language of the generated document summary. For example, when I create the index, I set SUMMARY_QUERY to Chinese, with a subset of the documents' document index being Chinese, that's OK, but the later document index by index.insert generated will default to English . I want later also to be Chinese for Convenient Q&A.

I just tried it bellow , found it not OK. 
![image](https://github.com/run-llama/llama_index/assets/13391430/fd64ff89-0e6e-4e64-b637-d46216ad0338)

**Comment by nerdai** [comment]
Oh in that case you may want to opt for a more structured knowledge store, relying on metadata perhaps or even using query router.

https://docs.llamaindex.ai/en/stable/examples/query_engine/RouterQueryEngine.html

In the above you would set up a query_engine separately for the various languages, and thus store the documents in the appropriate vector store according to their language.

**Comment by Gzj369** [comment]
> Closing this issue for now, as the original question was resolved. If another thing pops up, please feel free to open a new issue.

Yes, thank you very much!
