### ISSUE TITLE
[Feature Request]: remove model dependency from servicecontext when vector store exists

### ISSUE THREAD

**Issue by Morriz** [run-llama/llama_index#10197]
### Feature Description

Hi, creating stores is expensive and only needs a model during generation. So why do the docs say we need to include the same model used for creation during load of an existing db?

I would like to rewrite the following working code (snippet):
```py
...
    embed_model = HuggingFaceEmbedding(
        model_name="BAAI/bge-base-en-v1.5", max_length=512
    )
    service_context = ServiceContext.from_defaults(embed_model=embed_model, llm=None)

    if exists:
        vector_store = FaissVectorStore.from_persist_dir(persist_dir)
        storage_context = StorageContext.from_defaults(
            vector_store=vector_store,
            persist_dir=persist_dir,
        )
        index = load_index_from_storage(
            storage_context=storage_context, service_context=service_context
        )
    else:
        dim = 768
        faiss_index = faiss.IndexFlatL2(dim)
        vector_store = FaissVectorStore(faiss_index=faiss_index)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        documents = _get_documents()
        index = VectorStoreIndex.from_documents(
            documents, storage_context=storage_context, service_context=service_context
        )
        index.storage_context.persist(persist_dir=persist_dir)
```

to something like this in order to NOT have to retrieve large models when the db is created (I will package the DB with git or prep it some other way, negating the need for any embedding model):
```py
    dim = 768
    if exists:
        vector_store = FaissVectorStore.from_persist_dir(persist_dir)
        storage_context = StorageContext.from_defaults(
            vector_store=vector_store,
            persist_dir=persist_dir,
        )
        index = load_index_from_storage(storage_context=storage_context, dim=dim)
    else:
        embed_model = HuggingFaceEmbedding(
            model_name="BAAI/bge-base-en-v1.5", max_length=512
        )
        service_context = ServiceContext.from_defaults(
            embed_model=embed_model, llm=None
        )
        faiss_index = faiss.IndexFlatL2(dim)
        vector_store = FaissVectorStore(faiss_index=faiss_index)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        documents = _get_documents()
        index = VectorStoreIndex.from_documents(
            documents, storage_context=storage_context, service_context=service_context
        )
        index.storage_context.persist(persist_dir=persist_dir)
```

I assume the only relevant fact to know up front is the dimension of the vectors, right?

### Reason

no unnecessary load

### Value of Feature

it avoids downloading large models

**Comment by logan-markewich** [comment]
If you don't load the same embedding model for both creation and querying, how will querying work? You need to embed the query string in order to retrieve

**Comment by Morriz** [comment]
What do you mean? My intuition says the data is in the db and the retriever does not need a model to get that out.

**Comment by logan-markewich** [comment]
@Morriz vector dbs work by mainly semantic search. You embed all your data.

Then you embed a query string, and retrieve the top-k most similar.

**Comment by Morriz** [comment]
Indeed. But you forgot the import part: all the vectors are in the db as well. Everything you need is in there. That is my point.
I made many rag apps btw. Telling me I need a search string for rag is not very helpful here...

**Comment by Morriz** [comment]
I hope you understand I only gave the relevant part of code here, like I mentioned in the issue.

**Comment by logan-markewich** [comment]
@Morriz just trying to understand the issue 😅 how will you use your vector db with performing semantic search? Can you explain how it should work then?

In my mind, once you have your vector db, you still need to generate query embeddings to search and retrieve a top k? Unless you are performing search with data that is already in the vector db somehow?

In any case, if you truly don't need an embedding model, you can disable it (and the llm) by using 

```
service_context = ServiceContext.from_defualts(llm=None, embed_model=None)
index = load_index_from_storage(storage_context, service_context=service_context)
```

This will load "fake" models. But again, you won't be able to properly retrieve from the index, unless you had a vector pre-computed to do top-k search.

**Comment by Morriz** [comment]
If you don't understand it, maybe you are not the one to answer this question then? Hope you don't mind but I'd rather wait for an answer from the author...sry if that comes across as arrogant which is not intended but I don't want to educate through this medium

**Comment by Morriz** [comment]
I think @jerryjliu immediately understands my concern

**Comment by Morriz** [comment]
And your suggestion does not work since the retriever expects to get the dimensions from the model

**Comment by jerryjliu** [comment]
@Morriz the way you use a vector db is that you would need to specify a query embedding, and the vector db would return the top-k most similar embeddings/documents to the query embedding.

By default, we compute the embedding for you with our vector store interface, and to do that you would need an embedding model (per @logan-markewich 's point). The other approach is that you directly provide the embedding as part of the user query, so you don't need to give us an embedding model to compute the query embedding for you.

Is the latter approach what you have in mind? That's also possible too (i think). And i think your code snippet should work too

**Comment by Morriz** [comment]
Thanks for the elaborate reply. And thanks for trying to educate me @logan-markewich (I previously thought the query to vector for search input would be created up front without using a model, but that was obviously a gap in my knowledge, and the result of overusing openai). I don't think it makes sense for me to offload vector creation to another step though. I guess I have to get used to the implications of using large local models.

**Comment by logan-markewich** [comment]
Yea no worries, glad it makes sense 👍🏻 

If you wanted, you could host embeddings on some dedicated server (i.e. using [Text Embedding Inference](https://docs.llamaindex.ai/en/stable/examples/embeddings/text_embedding_inference.html) from Huggingface, or another hosting option), so that the model is not hosted directly on your local machine.

You can see a list of all embedding integrations here, which some run locally, or some over an API, or you can even implement your own custom class
https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#list-of-supported-embeddings
