### ISSUE TITLE
[Feature Request]: Add txtai as a vector store

### ISSUE THREAD

**Issue by tnunamak** [run-llama/llama_index#10219]
### Feature Description

As [@davidmezzetti](https://www.reddit.com/r/LocalLLaMA/comments/16xwk3k/comment/k39kb7f/?utm_source=share&utm_medium=web2x&context=3) pointed out, LlamaIndex could use [txtai](https://neuml.github.io/txtai) as a vector store.

This would be useful to users like me who have an existing txtai store and want to use advanced LlamaIndex features for certain use cases in addition to my txtai-oriented application features.

### Reason

AFAIK a basic txtai interface would be straightforward to add. Any txtai features beyond the vector store would obviously be inaccessible.

### Value of Feature

It would be wonderful for users like me who have an existing txtai vector store to be able to take advantage of advanced retrieval features offered by LlamaIndex.

**Comment by MarouaneMaatouk** [comment]
Hi, can I work on this?

**Comment by logan-markewich** [comment]
@MarouaneMaatouk go for it 👍🏻

**Comment by nerdai** [comment]
(added to request for contribution board: https://github.com/orgs/run-llama/projects/2/views/1)

**Comment by tnunamak** [comment]
@MarouaneMaatouk thank you for making this happen so quickly! Cheers!
