### ISSUE TITLE
[Question]: SentenceSplitter implement details

### ISSUE THREAD

**Issue by BuxianChen** [run-llama/llama_index#10229]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm confused about the implement of [SentenceSplitter](https://github.com/run-llama/llama_index/blob/v0.9.36/llama_index/node_parser/text/sentence.py#L259):

```python
while len(splits) > 0:
    cur_split = splits[0]
    if cur_split.token_size > chunk_size:
        raise ValueError("Single token exceeded chunk size")
    if cur_chunk_len + cur_split.token_size > chunk_size and not new_chunk:
        # if adding split to current chunk exceeds chunk size: close out chunk
        close_chunk()
    else:
        if (
            cur_split.is_sentence
            or cur_chunk_len + cur_split.token_size <= chunk_size
            or new_chunk  # new chunk, always add at least one split
        ):
            # add split to chunk
            cur_chunk_len += cur_split.token_size
            cur_chunk.append((cur_split.text, cur_split.token_size))
            splits.pop(0)
            new_chunk = False
        else:
            # close out chunk
            close_chunk()
```

The condition here ` cur_split.is_sentence or cur_chunk_len + cur_split.token_size <= chunk_size or new_chunk` sames always is `True`, I'm not sure the expected behavior of this block of code.

**Comment by BuxianChen** [comment]
@dosu-bot The outer `if` statement will lead the condition I mentioned will always be `True`.

```puthon
if cur_chunk_len + cur_split.token_size > chunk_size and not new_chunk:
    # if adding split to current chunk exceeds chunk size: close out chunk
    close_chunk()
else:
    if (
        cur_split.is_sentence
        or cur_chunk_len + cur_split.token_size <= chunk_size
        or new_chunk  # new chunk, always add at least one split
    ):
```

**Comment by logan-markewich** [comment]
yea I'm not totally sure either tbh. But tbh it seems benign. Could probably just simplify the logic with

```
if cur_chunk_len + cur_split.token_size > chunk_size and not new_chunk:
        # if adding split to current chunk exceeds chunk size: close out chunk
        close_chunk()
    else:
        # add split to chunk
        cur_chunk_len += cur_split.token_size
        cur_chunk.append((cur_split.text, cur_split.token_size))
        splits.pop(0)
        new_chunk = False
```

I know we have pretty extensive tests for this splitter, so making this change would identify if its important or not pretty quickly

**Comment by BuxianChen** [comment]
Yea, the current implement is equivalent to yours, but the `is_sentence` flag will be useless, I think the flag has its purpose, but I'm not clear about that. By the way, I would like to make a PR for that, but I'm not sure the expected behavior (from the core developer's perspective), so I have no idea to make the PR.
