### ISSUE TITLE
[Bug]: Unable to update embeddings: Got a larger chunk overlap (64) than chunk size (512), should be smaller

### ISSUE THREAD

**Issue by bounaux** [run-llama/llama_index#10228]
### Bug Description

This seems to be a bug, where the chunk size and chunk overlap has switched in the node parser check size logic

### Version

0.9.36

### Steps to Reproduce

chunk_size=512

chunk_overlap=64

documents = SimpleDirectoryReader(text_mount).load_data()

node_parser = SimpleNodeParser.from_defaults(chunk_size=chunk_size,  chunk_overlap=chunk_overlap)

Exception: 

"detail": "Unable to update embeddings: Got a larger chunk overlap (64) than chunk size (512), should be smaller."

**Comment by logan-markewich** [comment]
@bounaux I'm not able to reproduce this

```python
from llama_index import SimpleDirectoryReader
from llama_index.node_parser import SimpleNodeParser

documents = SimpleDirectoryReader("docs/examples/data/paul_graham").load_data()
node_parser = SimpleNodeParser.from_defaults(chunk_size=512, chunk_overlap=64)

nodes = node_parser.get_nodes_from_documents(documents)
print(len(nodes))
>> 41
```

also FYI, `SimpleNodeParser` is deprecated, and actually an alias for `SentenceSplitter`

I would probably write this 

```python
from llama_index.node_parser import SentenceSplitter

node_parser = SentenceSplitter.from_defaults(chunk_size=512, chunk_overlap=64)
...
```

**Comment by bounaux** [comment]
Thx for the idea Logan, I'll update tht code as you suggested. I found the bug in the code - somewhere it was converting the int to string and I need to swtich it back to int to make it work, so llamaindex is good, no bug. Cheers!

**Comment by bounaux** [comment]
Not a bug, ready to close
