### ISSUE TITLE
Retrieval evaluation with and without reranking

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#10238]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I’m doing some retrieval evaluation for different pipelines, and I would like to compare the results with and without reranking. In llamaindex, reranking operates on the retrieved nodes:

```
from llama_index.postprocessor import LLMRerank
retrieved_nodes = retriever.retrieve(query_bundle)
reranker = LLMRerank(
    choice_batch_size=5,
    top_n=reranker_top_n
)
retrieved_nodes = reranker.postprocess_nodes(
    retrieved_nodes, query_bundle
)
```

but retrieval evaluation is based on a retriever object, not the nodes directly:

```
 retriever = index.as_retriever(similarity_top_k=top_k)
 qa_dataset = my_dataset
 metrics = ["mrr", "hit_rate"]
 retriever_evaluator = RetrieverEvaluator.from_metric_names(
        metrics, retriever=retriever
 )
 eval_results = await retriever_evaluator.aevaluate_dataset(qa_dataset)
```
 
Is there a way to easily test the effect of reranking on my benchmark results, or do I need to define some kind of custom RerankingRetriever() that would already integrate Reranking for that? In this case, what is the function from the doc I should get inspiration from?

**Comment by nerdai** [comment]
Great point @stephanedebove! I think perhaps the slightly more sensible way to approach this would be to extend `RetrieverEvalutor` to include not only a retriever object but as well as an optional post_processor object.

**Comment by nerdai** [comment]
Added an [entry](https://github.com/run-llama/llama_index/issues/10243) to our Request For Contributions board for this.

**Comment by KrishnaSindhur** [comment]
I can take look, if its open?

**Comment by arktrail** [comment]
Would like to work on it if no one picked it up.

**Comment by VJlaxmi** [comment]
I would like to work on this issue, if it's not picked by anyone!

**Comment by nerdai** [comment]
Sorry, this should be closed now as the associated issue on the request for contributions project board has been fulfilled.

**Comment by Shankar-Baskaran** [comment]
does anyone have a working solution/code for comparing the retrieval evaluation with and without LLM reranker?

**Comment by Shankar-Baskaran** [comment]
any solutions with the qa_dataset for the above would be greatly appreciated. Thank you in advance.
