### ISSUE TITLE
[Question]: Which model do you use to "detect" important tables in a pdf document?

### ISSUE THREAD

**Issue by SantiDianaClibrain** [run-llama/llama_index#10239]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Here](https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/multi_modal_pdf_tables.ipynb) you can find a notebook that is capable of retrieving tables that answer to a query. In the first experiment you create a qdrant database that contains information of each pdf page. Which model do you use for that? GPT4V or any embeddings model? Thanks!

**Comment by jaideep11061982** [comment]
do i need to put it inside the compelte request.post call and then pass the response to COmpleteResponse method ?
```
class OurLLM(CustomLLM):
    context_window: int = 3900
    num_output: int = 256
    model_name: str = "custom"
    dummy_response: str = "My response"

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=self.context_window,
            num_output=self.num_output,
            model_name=self.model_name,
        )

    @llm_completion_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        return CompletionResponse(text=self.dummy_response)
```
