### ISSUE TITLE
[Feature Request]: Vector store query method does not return all output fields

### ISSUE THREAD

**Issue by Anirudh181001** [run-llama/llama_index#10247]
### Feature Description

The vector store has a query method which is useful for semantic search. However, the _VectorStoreQuery_ takes in an 
_output_fields_ argument, but the query method does not actually return all the output fields that is actually requested.
This makes it a bit unintuitive to use the query method, and I think perhaps returning all the _output_fields_ is the most intuitive expected outcome... 

Code block to replicate:
`response : List[TextNode] = milvus_vector_store.query(VectorStoreQuery(embedding, output_fields=["field1", "field2", "field3"]), similarity_top_k=k)`

### Reason

Currently, the query method returns a list of TextNodes. I think if we'd want to support the feature, we might need to change the output format, which I'm not sure if it'd break other things. 
An alternative is to create another method to query _output_fields_ .

### Value of Feature

I want to query my vector database, and get more than 1 field in the response via llamaindex. Currently, I'm unable to do that. I also feel like it's a common and valuable use case.

**Comment by logan-markewich** [comment]
I would suggest putting the fields you want into the node metadata?

Or maybe a better change, the query method can take the requested fields and insert them into the metadata of each node
