### ISSUE TITLE
[Feature Request]: Extend `BaseRetrievalEvaluator` to include an optional PostProcessor

### ISSUE THREAD

**Issue by nerdai** [run-llama/llama_index#10243]
### Feature Description

- `RetrieverEvaluator` currently only accepts `BaseRetriever`
- However, there are cases where one wants to measure the impact of a post processing method applied on retrieval results
- This request is for extending `RetrieverEvaluator` to include a `Postprocessor` i.e. Re-rank that gets applied to the retrieved nodes before being evaluated.

Addresses: #10238 10238

**Comment by Izukimat** [comment]
I am interested in working on this issue.

**Comment by nerdai** [comment]
Thanks @Izukimat -- i'll assign you to the issue.
