### ISSUE TITLE
[Bug]: IngestionPipeline 0.9.36 pipline.arun to Redis Not implemented Error 

### ISSUE THREAD

**Issue by JoeSF49** [run-llama/llama_index#10248]
### Bug Description

using IngestionPipeline  with docstore=RedisDocumentStore,   then running pipline.arun to Redis Not implemented Error  get Not implemented Error using llama-index 0.9.36. Downgrade to 0.9.30 allows me to run pipline.arun.  just using simpleDirectoryRead load_data documents and passing it to run or arun.

### Version

0.9.36 llama-index

### Steps to Reproduce

install llama-index 0.9.36 
create IngestionPipeline:
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        embed_model,
    ],
    docstore=RedisDocumentStore.from_host_and_port(
        "localhost", 6379, namespace="document_store"
    ),
    vector_store=RedisVectorStore(
        index_name="redis_vector_store",
        index_prefix="vectore_store",
        redis_url="redis://localhost:6379",
    ),
    cache=IngestionCache(
        cache=RedisCache.from_host_and_port("localhost", 6379),
        collection="redis_cache",
    ),
    docstore_strategy=DocstoreStrategy.UPSERTS,
)

attempt pipline.arun to a redis vectorstore
Error "Not implemented"

Workaround:
downgrade to llama-index 0.9.30  and both pipline.arun  and pipline.run  work

**Comment by logan-markewich** [comment]
Ah yea, need to implement the async methods here
https://github.com/run-llama/llama_index/blob/773a2fdcb4ecb06ceb26ee2f8322ec38b990d344/llama_index/storage/kvstore/redis_kvstore.py#L118

**Comment by JoeSF49** [comment]
i believe it has to do with Docstore strategy in the pipeling.  i also traced it to start failing at 0.9.33.  it's works up to llama-index 0.9.32

ERROR:

---------------------------------------------------------------------------

NotImplementedError                       Traceback (most recent call last)

Cell In[18], line 2

      1 ## Async

----> 2 nodes = await pipeline.arun(documents=documents,show_progress=True)

      3 # nodes = pipeline.run(documents=documents,show_progress=True)

      4 print(f"Ingested {len(nodes)} Nodes")

 

File /opt/miniforge/envs/pytorch/lib/python3.10/site-packages/llama_index/ingestion/pipeline.py:570, in IngestionPipeline.arun(self, show_progress, documents, nodes, cache_collection, in_place, store_doc_text, num_workers, **kwargs)

    565 if self.docstore is not None and self.vector_store is not None:

    566     if self.docstore_strategy in (

    567         DocstoreStrategy.UPSERTS,

    568         DocstoreStrategy.UPSERTS_AND_DELETE,

    569     ):

--> 570         nodes_to_run = await self._ahandle_upserts(

    571             input_nodes, store_doc_text=store_doc_text

    572         )

    573     elif self.docstore_strategy == DocstoreStrategy.DUPLICATES_ONLY:

    574         nodes_to_run = await self._ahandle_duplicates(

    575             input_nodes, store_doc_text=store_doc_text

    576         )

 

File /opt/miniforge/envs/pytorch/lib/python3.10/site-packages/llama_index/ingestion/pipeline.py:513, in IngestionPipeline._ahandle_upserts(self, nodes, store_doc_text)

    509 """Handle docstore upserts by checking hashes and ids."""

    510 assert self.docstore is not None

    512 existing_doc_ids_before = set(

--> 513     (await self.docstore.aget_all_document_hashes()).values()

    514 )

    515 doc_ids_from_nodes = set()

    516 deduped_nodes_to_run = {}

 

File /opt/miniforge/envs/pytorch/lib/python3.10/site-packages/llama_index/storage/docstore/keyval_docstore.py:524, in KVDocumentStore.aget_all_document_hashes(self)

    522 """Get the stored hash for all documents."""

    523 hashes = {}

--> 524 for doc_id in await self._kvstore.aget_all(

    525     collection=self._metadata_collection

    526 ):

    527     hash = await self.aget_document_hash(doc_id)

    528     if hash is not None:

 

File /opt/miniforge/envs/pytorch/lib/python3.10/site-packages/llama_index/storage/kvstore/redis_kvstore.py:140, in RedisKVStore.aget_all(self, collection)

    138 async def aget_all(self, collection: str = DEFAULT_COLLECTION) -> Dict[str, dict]:

    139     """Get all values from the store."""

--> 140     raise NotImplementedError

 

NotImplementedError:

**Comment by JoeSF49** [comment]
As far as OSes:  i use docker workloads on an ML hardware platform
Redis-stack docker image.  redis version 7.2.3
Python env is basically ubuntu 22.04.  It's really using a nvidia/cuda-12.x-ubuntu22.04 image.  These has nvidia drivers and toolkits for hardware (GPU) passthrough.  i install mambaforge env within this workload "OS" and libs.  llama-index, langchain etc

**Comment by logan-markewich** [comment]
Yea as mentioned above, async redis docstore operations just need to be implemented

**Comment by JoeSF49** [comment]
@dosu-bot  Hi and sorry I rarely make bug so i'm new to this process.   Do I have to provided any more information or will this fix be implemented in upcoming releases?  I cannot run the pipeline without the async as it fills the GPU memory during reg ".run".  Thanks
