### ISSUE TITLE
[Feature Request]: Any plan for support the OrionStarAI/Orion-14B-Chat-RAG in huggingface?

### ISSUE THREAD

**Issue by SOSONAGI** [run-llama/llama_index#10250]
### Feature Description

Thanks for sharing this powerful tool for RAG.

I've tried to put upon the model in llama-index pipeline but, i got messages from terminal

```CLI
ValueError: Tokenizer class OrionTokenizer does not exist or is not currently imported.
```

but, huggingface support that in AutoTokenizer for that model.

I'm not sure that i've missed something or not.

Here is the code for that.

```CLI
from llama_index.llms import HuggingFaceLLM  

llm = HuggingFaceLLM(
    context_window=4096, 
    max_new_tokens=512, 
    generate_kwargs={"temperature": 0.4, "do_sample": True, "repetition_penalty": 1.2}, 
    system_prompt=system_prompt, 
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="OrionStarAI/Orion-14B-Chat-RAG", 
    model_name="OrionStarAI/Orion-14B-Chat-RAG",
    device_map="auto", 
    tokenizer_kwargs={"max_length": 1024, "padding_side": "left"}, 
    model_kwargs={"torch_dtype": torch.float16}
)
```

I highly appreciate that will be given the response from you.

Thank you again.

### Value of Feature

I've never seen RAG base model before. And if this will be supported in llama-index, it would be really great.

**Comment by logan-markewich** [comment]
@SOSONAGI it's using `AutoTokenizer` under the hood. Maybe you need to update your transformers installation?

Or worst case, you can load the model and tokenizer outside of llama-index and pass it in instead of the names

```
llm = HuggingFaceLLM(model=model, tokenizer=tokenizer, ...)
```

**Comment by logan-markewich** [comment]
Great!
