### ISSUE TITLE
[Bug]: OpenCLIPEmbeddingFunction() function is not working without openai api key in Chroma Multi-Modal llamaindex Demo

### ISSUE THREAD

**Issue by saimunikoti** [run-llama/llama_index#10256]
### Bug Description

This is about the demo at https://docs.llamaindex.ai/en/stable/examples/multi_modal/ChromaMultiModalDemo.html
OpenCLIPEmbeddingFunction() is a open source model from open_clip which doesn't require openai api key. OpenCLIPEmbeddingFunction is used to create vector database
(chroma_collection = chroma_client.create_collection(
    "multimodal_collection",
    embedding_function=OpenCLIPEmbeddingFunction(),
    data_loader=image_loader,
). 
But it is using default service_context when index is defined:
(index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)
which implies it is invoking openai models for query embedding. Ideally your embedding model for vector database creation and for retrieval (i.e., for query embedding) should be same, i.e. OpenCLIPEmbeddingFunction(). The service _context in the index should take OpenCLIPEmbeddingFunction() as embed_model which is currently not possible.

### Version

0.9.27

### Steps to Reproduce

Just follow the steps in the llamaindex tutorial page:
https://docs.llamaindex.ai/en/stable/examples/multi_modal/ChromaMultiModalDemo.html

**Comment by logan-markewich** [comment]
@saimunikoti actually, with multimodal, clip sucks at text-to-text retrieval.

What is happening here is, images are embedded and retrieved with clip, and text is embedded and retrieved with whatever other embedding model (openai in this case)

@hatianzhang is our multimodal guy, he can maybe confirm this 😁

**Comment by saimunikoti** [comment]
> @saimunikoti actually, with multimodal, clip sucks at text-to-text retrieval.
> 
> What is happening here is, images are embedded and retrieved with clip, and text is embedded and retrieved with whatever other embedding model (openai in this case)
> 
> @hatianzhang is our multimodal guy, he can maybe confirm this 😁

Thanks for responding. But even when we are trying to use different embedding models for text (i.e., BAAI/bge-large-en) and image (openclipembedding), it seems to not working. Its tightly coupled with openai api functions. Is there any workaround to skip openai functions and use open source models like BGE and openclipembedding ?

**Comment by logan-markewich** [comment]
@saimunikoti Yea, just define the service context with the embedding model you want right?

```
service_context = ServiceContext.from_defaults(llm=llm, embed_model=HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5"))
index =  VectorStoreIndex.from_documents(...., service_context=service_context)
```
