### ISSUE TITLE
[Question]: Implementing RAG with Mixtral being served over an OpenAILike API

### ISSUE THREAD

**Issue by JoshuaFurman** [run-llama/llama_index#10253]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm currently using VLLM to serve Mixtral over an OpenAILike API. I'm attempting to implement RAG with some personal documents but I'm getting some errors/hangups over how to configure the embed model for this. 

It looks like VLLMs OpenAILike API does not support the `/embeddings` endpoint which it looks like llama-index tries to hit when you omit the embed_model argument to the `ServiceContext.from_defaults()` function. 

I've also tried pointing to my local Mixtral cache by creating the following object and passing it to the embed_model parameter in the `ServiceContext.from_defaults()` function:
`embed_model = HuggingFaceEmbedding(model_name="/home/<user>/.cache/huggingface/hub/models--mistralai--Mixtral-8x7B-Instruct-v0.1/snapshots/125c431e2ff41a156b9f9076f744d2f35dd6e67a/")` 
But I receive the following error: 
`OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory`

What is my best course of action here? I understand this is partially a VLLM issue but wondering if I'm just not configuring the embed model correctly. 

Thanks!

**Comment by logan-markewich** [comment]
@JoshuaFurman you most likely do not want to use an LLM like mixtral for embeddings.

You'd want a model that was actually trained for retrieval, like `BAAI/bge-large-en-v1.5`

This can be used in that huggingface embeddings class.

If you need a production level deployment, I would use text embeddings inference from huggingface (we have an embedding class for that as well)

**Comment by JoshuaFurman** [comment]
Awesome thank you for such a quick response! I'll give that embedding model a try first thing in the morning. 

This Q might be out of the scope of this issue but should different embed models give different results for retrieval? 

Is there an easy way to reason about an answer to that?

**Comment by logan-markewich** [comment]
@JoshuaFurman yea different embedding models will retrieve different results.

Once you embed your data with a model, you need to use the same model for querying as well. (Otherwise, the embeddings are not "aligned" in the same vector space, plus dimensions might be different)

Tbh I'd say most models from the top of the mteb leaderboard is a good place to start (note not all of these models are open source/available on huggingface)
https://huggingface.co/spaces/mteb/leaderboard

BGE is a good combination of size and accuracy imo

**Comment by JoshuaFurman** [comment]
@logan-markewich ahhh i see. i wasnt thinking about this correctly. So you should be using a dedicated embed model for embedding data and retrieving then feed the retrieved context/data to a foundation model for the actual inference. 

Thank you for taking the time to answer my questions I really appreciate it

**Comment by JoshuaFurman** [comment]
Not sure if I should just open another issue for this or can continue here but i have the following code: 
`
import os

# OpenAILike
from llama_index.llms import OpenAILike
from llama_index.llms import ChatMessage
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index import ServiceContext, VectorStoreIndex, SimpleDirectoryReader

os.environ['OPENAI_API_BASE'] = "http://127.0.0.1:8000/v1"
os.environ['OPENAI_API_KEY'] = "EMPTY"

# vllm
llm = OpenAILike(
    model="mistralai/Mixtral-8x7B-Instruct-v0.1",
    api_key="EMPTY",
    api_base="http://127.0.0.1:8000/v1",
    context_window=32768,
)

# Setup docs and LLM
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-large-en-v1.5")

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)

documents = SimpleDirectoryReader(input_dir="./data", recursive=True).load_data()

index = VectorStoreIndex.from_documents(documents)
index.storage_context.persist(persist_dir="./test-storage")

query_engine = index.as_query_engine(service_context=service_context)

response = query_engine.query("How can I do an etcd backup?")

print(response)`

and its giving me the following error:
`Traceback (most recent call last):
  File "/home/silver/ranchergpt/venv/lib/python3.10/site-packages/openai/_base_client.py", line 938, in _request
    response.raise_for_status()
  File "/home/silver/ranchergpt/venv/lib/python3.10/site-packages/httpx/_models.py", line 759, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://127.0.0.1:8000/v1/embeddings'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503`

I cant understand why its trying to hit the `/embeddings` endpoint when i explicitly specify an embed model...
Am I missing something?

**Comment by JoshuaFurman** [comment]
I resolved my issue by setting:
`set_global_service_context(service_context)`

**Comment by logan-markewich** [comment]
You got it. Alternatively you could pass the service context into the vector index, but the global is a better option 👍
