### ISSUE TITLE
[Bug]: ComposableGraphQueryEngine doesn't implement PromptMixin

### ISSUE THREAD

**Issue by janaka** [run-llama/llama_index#10255]
### Bug Description

As I understand from the docs here `ComposableGraphQueryEngine` should implement `PromptMixin` such that `.get_prompts()` returns prompt templates. Calling this method currently returns `{}` and I believe its because `PromptMixin`   found in mixin.py isn't implemented.

### Version

`main` branch

### Steps to Reproduce

```python
graph = ComposableGraph.from_indices(
    SummaryIndex,
    indices,
    index_summaries=summaries,
)

custom_query_engines = {
    index.index_id: index.as_query_engine(child_branch_factor=2) for index in indices
}

query_engine = graph.as_query_engine(custom_query_engines=custom_query_engines)

prompts_dict = query_engine.get_prompts()
print( list(prompts_dict.keys()))
# prints: {}
```

**Comment by logan-markewich** [comment]
@janaka composable graph is generally unmaimtained, and will likely get removed in a future version.

I'd suggest finding an alternative approach, updating the prompts on each query engine in the graph, or making a PR to make this work

**Comment by janaka** [comment]
> @janaka composable graph is generally unmaimtained, and will likely get removed in a future version.
> 
> I'd suggest finding an alternative approach, updating the prompts on each query engine in the graph, or making a PR to make this work 

Ah. What's the technique / pattern that supersedes it?

**Comment by janaka** [comment]
Thanks - forgot about pipelines.
