### ISSUE TITLE
[Question]: Facing error with SubQuestionQueryEngine

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10261]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Facing errors when using` SubQuestionQueryEngine`. What are the possible casuses of the error? Could it be the `name` attribute in ` ToolMetadata`?

```
query_engine_tools = [
      QueryEngineTool(
          query_engine=engine,
          metadata=ToolMetadata(
              name= f"Query Engine for {document}" , description=(f"Useful tool to provide information about the candidate in {document}"),                                      
          ),
      )
      for document, engine in self.query_engines.items()
  ]
```

```
Error:  Got invalid JSON object. Error: Expecting ',' delimiter: line 74 column 10 (char 3149) while parsing a flow sequence
  in "<unicode string>", line 2, column 14:
        "items": [
                 ^
expected ',' or ']', but got '<stream end>'
  in "<unicode string>", line 74, column 10:
            }
             ^. Got JSON string: {
    "items": [
```

**Comment by GxTeo** [comment]
It seems like the json object for sub questions are not fully generated and stops/crashes

**Comment by logan-markewich** [comment]
@GxTeo the output is limited by how much context room the LLM has to generate text. The more tools/query engines, the less room it has to generate questions.

If you have 100+ documents, sticking them all into a sub-question query engine will definitely not work well (Too much data for the LLM to even read)

Probably you should have a step to retrieve tools based on the query and the corresponding tool names/descriptions, to narrow down the query engine tools to 5-10.

**Comment by GxTeo** [comment]
@logan-markewich I see, is there a better approach that supports complex queries on a K ( where K is huge) amount of documents? 

Lets say I have multiple documents of school admissions application.  And through my query, I want to rank the candidates based on their GPAs. I would need to generate `sub-questions`  that check the gpa in each application and then finally rank them. 

What would be a good/different approach to avoid overloading the LLM.

**Comment by arunnuve** [comment]
@GxTeo Does your issue resolved?

**Comment by arunnuve** [comment]
@GxTeo Does your issue has resolved.
