### ISSUE TITLE
[Bug]: AttributeError when calling agenerate_questions_from_nodes - 'LabelledRagDataset' object has no attribute 'questions'

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#10271]
### Bug Description

I am using the `RagDatasetGenerator` class to generate questions from documents. However, when calling the `agenerate_questions_from_nodes` method, I am encountering an `AttributeError` as it appears the method is trying to access a non-existent 'questions' attribute on a 'LabelledRagDataset' object.

**Minimal Working Example:**

```python
from llama_index.llama_dataset.generator import RagDatasetGenerator

dataset_generator = RagDatasetGenerator.from_documents(
    documents=documents,
    num_questions_per_chunk=2,
    service_context=service_context
)

labelled_rag_dataset = await dataset_generator.agenerate_questions_from_nodes()

```

Error is:

```
  File "llamaindex\lib\site-packages\llama_index\llama_dataset\generator.py", line 215, in agenerate_questions_from_nodes
    return dataset.questions
AttributeError: 'LabelledRagDataset' object has no attribute 'questions'
```

### Version

0.9.37

### Steps to Reproduce

from llama_index.llama_dataset.generator import RagDatasetGenerator

dataset_generator = RagDatasetGenerator.from_documents(
    documents=documents,
    num_questions_per_chunk=2,
    service_context=service_context
)

labelled_rag_dataset = await dataset_generator.agenerate_questions_from_nodes()

### Relevant Logs/Tracbacks

```shell
File "llamaindex\lib\site-packages\llama_index\llama_dataset\generator.py", line 215, in agenerate_questions_from_nodes
    return dataset.questions
AttributeError: 'LabelledRagDataset' object has no attribute 'questions'
```

**Comment by nerdai** [comment]
Thanks @stephanedebove for catching this. Should be an easy fix of changing `question` to `query`. Fix coming shortly.

**Comment by nerdai** [comment]
Okay fix is in review now, but I also noticed in your snippet that you are assigning the result to a variable called `labelled_rag_dataset` (see below). But, please note that the method `agenerate_questions_from_nodes` will only generate the questions and not the reference answers to these questions.

```python
labelled_rag_dataset = await dataset_generator.agenerate_questions_from_nodes()
```

If you indeed want a labelled dataset with reference answers (i.e the labels), then you should use `agenerate_dataset_from_nodes()` instead:


```python
labelled_rag_dataset = await dataset_generator.agenerate_dataset_from_nodes()
```
