### ISSUE TITLE
[Bug]: while loading replicate LLM using llama index got error : ReplicateError: Sorry, this version is currently disabled due to failing setupruns.

### ISSUE THREAD

**Issue by vaidikcs** [run-llama/llama_index#10286]
### Bug Description

getting this error for every llm on replicate, i have set API token to environment variable.

### Version

0.23.0

### Steps to Reproduce

from llama_index.llms import Replicate
llm_code_ = Replicate(
    model="meta/codellama-7b-instruct:7bf2629623162c0cf22ace9ec7a94b34045c1cfa2ed82586f05f3a60b1ca2da5",
    additional_kwargs={"temperature": 0.5, "max_length": 500,
                  "system_prompt": CODE_LLM_SYS_PRMPT},
)
q = " "
llm_code_.complete(q)

### Relevant Logs/Tracbacks

```shell
216 with wrapper_logic(_self) as callback_manager:
    217     event_id = callback_manager.on_event_start(
    218         CBEventType.LLM,
    219         payload={
   (...)
    223         },
    224     )
--> 226     f_return_val = f(_self, *args, **kwargs)
    227     if isinstance(f_return_val, Generator):
    228         # intercept the generator and add a callback to the end
    229         def wrapped_gen() -> CompletionResponseGen:
...
    356 def _raise_for_status(resp: httpx.Response) -> None:
    357     if 400 <= resp.status_code < 600:
--> 358         raise ReplicateError(resp.json()["detail"])

ReplicateError: Sorry, this version is currently disabled due to failing setupruns.
```

**Comment by logan-markewich** [comment]
I think this is a replicate issue, not a llama-index issue? I have no idea why replicate is returning that error :)
