### ISSUE TITLE
[Question]: Excel unstructered data

### ISSUE THREAD

**Issue by gmartini2019** [run-llama/llama_index#10283]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello all, I am having a **lot** of trouble with this. I'm trying to parsing both multi index and generally unstructered (think a child opens MS Excel and starts typing) data from excel files. the PandasExcelReader is parsing it in a way that the framework does not understand. Have you ever ran into this necessity? And if so, what can I do to overcome it?

**Comment by logan-markewich** [comment]
Probably, writing your own dataloader is probably best here, rather than relying on something off the shelf.

Creating document objects is really easy

```
from llama_index import Document
doc = Document(text=text, metadata=metadata)
```

Beyond that, you'd just need to write code to open your excel file and pull the data out in a way that makes sense

**Comment by pj7020850** [comment]
@logan-markewich Can you please elaborate and extend the code you mentioned in previous comment.
