### ISSUE TITLE
[Bug]: Chat stream active wait blocks flask request thread

### ISSUE THREAD

**Issue by Lorenzo-N** [run-llama/llama_index#10290]
### Bug Description

The method [StreamingAgentChatResponse.response_gen](https://github.com/run-llama/llama_index/blob/c01eba93051175eaa2fed4826d677aeefd75a256/llama_index/chat_engine/types.py#L163), which is designed to generate responses, currently exhibits a high CPU usage issue due to an active wait implemented within a loop. This behavior is causing significant performance degradation, especially when integrated into a Flask endpoint. The issue seems to stem from the use of block=False in self._queue.get(block=False), leading to an active wait loop that consumes 100% CPU. As a result, this prevents the openai request thread from executing properly. In my case, the problem does not manifest when running the code in a local file.

I would like to understand the initial reasoning behind the explicit use of block=False in the queue get method. Changing this to block=True with a reasonable timeout (e.g., timeout=0.1) resolves the issue by preventing active waiting, but I'm concerned there might have been specific considerations for the original implementation.

### Version

0.9.38

### Steps to Reproduce

```
def flask_endpoint():
    def generate():
        from llama_index import VectorStoreIndex
        from llama_index.llms import OpenAI
        from llama_index import ServiceContext
        import os
        os.environ["OPENAI_API_KEY"] = ""

        service_context = ServiceContext.from_defaults(llm=OpenAI(temperature=0.1, model="gpt-3.5-turbo"))
        index = VectorStoreIndex.from_documents([], service_context=service_context)
        chat_engine = index.as_chat_engine()
        resp = chat_engine.stream_chat('Hi')
        for message in resp.response_gen:
            if message is not None:
                yield str(message)

    response = Response(stream_with_context(generate()), mimetype='text/text-stream')
    response.headers['X-Accel-Buffering'] = 'no'
    return response
```

**Comment by logan-markewich** [comment]
Hmmm thanks for identifying this. I had block=False since I thought I remembered it nit working with block=True, let me check.

**Comment by jayantverma2809** [comment]
can we try adding timeout

**Comment by Sammyjroberts** [comment]
@logan-markewich 
Hey Logan I have this a quick test with the following file:
```py
import os

from llama_index.vector_stores import PineconeVectorStore
from llama_index import VectorStoreIndex

from llama_index.query_engine.retriever_query_engine import (
    RetrieverQueryEngine,
)

os.environ["OPENAI_API_KEY"] = "..."


def chat_responses():
    # Initialize the PineconeVectorStore
    vector_store = PineconeVectorStore(
        ...
    )

    index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
    chat_engine = index.as_chat_engine()
    response_stream = chat_engine.stream_chat("Hi")

    for message in response_stream.response_gen:
        if message is not None:
            yield str(message)


def __main__():
    print("hello")
    for message in chat_responses():
        print(message)


if __name__ == "__main__":
    __main__()
```

I modified `llama_index/llama_index/chat_engine/types.py:163`
```py
delta = self._queue.get(block=True, timeout=1)
```

and was getting a response that seemed good to me!

**Comment by Sammyjroberts** [comment]
@jayantverma2809 Yes, i went from ~14% usage to ~38%, which still seems a bit high, but definitely not 100%

**Comment by logan-markewich** [comment]
hmm, so CPU usage went up with the change? 

tbh I think I need to try replcating this issue myself. We've deployed agents to prod servers, and haven't observed the same behaviour (to my knowledge) 🤔

**Comment by logan-markewich** [comment]
Although I suppose the stuff I worked with before was async in fastapi, not threaded in flask

**Comment by Sammyjroberts** [comment]
@logan-markewich to be clear, I went from 14-38% during my test, compared to Lorenzo's claim of 100%. I'll retest both today and see if I can replicate the initial 100% usage.

**Comment by logan-markewich** [comment]
@Sammyjroberts I used the following code, but tbh I didn't see any crazy CPU usage on my M2 Mac


```
import time
from flask import Flask

from llama_index import VectorStoreIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader(input_files=["./README.md"]).load_data()

index = VectorStoreIndex.from_documents(documents)

chat_engine = index.as_chat_engine()

app = Flask(__name__)

@app.route("/")
def index():
    return "Hello, World!"

@app.route("/run")
def run():
    def generate():
        stream = chat_engine.stream_chat("Hello, how are you")
        for token in stream.response_gen:
            yield token
        
        my_msg = "\nCan you write me a poem about raining cats and dogs?\n"
        for token in my_msg.split(" "):
            yield token
            yield " "
            time.sleep(0.5)
        
        stream = chat_engine.stream_chat("Can you write me a poem about raining cats and dogs?")
        for token in stream.response_gen:
            yield token

    return app.response_class(generate(), mimetype="text/plain")

if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000)
```

**Comment by logan-markewich** [comment]
(@Lorenzo-N  ^^)

**Comment by Lorenzo-N** [comment]
Hello, thank you for your interest. I've conducted additional tests with the code:

```import queue
import time
from flask import Flask

from llama_index import VectorStoreIndex
index = VectorStoreIndex.from_documents([])

chat_engine = index.as_chat_engine()

app = Flask(__name__)


@app.route("/")
def index():
    return "Hello, World!"


def timeout_stream(response):
    # replace method response.response_gen:
    while not response._is_done or not response._queue.empty():
        try:
            delta = response._queue.get(block=True, timeout=0.1)
            response._unformatted_response += delta
            yield delta
        except queue.Empty:
            # Queue is empty, but we're not done yet
            continue
    response.response = response._unformatted_response.strip()


@app.route("/run")
def run():
    def generate():
        stream = chat_engine.stream_chat("Hello, how are you")
        for token in stream.response_gen:
            yield token

        my_msg = "\nCan you write me a poem about raining cats and dogs?\n"
        for token in my_msg.split(" "):
            yield token
            yield " "
            time.sleep(0.5)

        stream = chat_engine.stream_chat("Can you write me a poem about raining cats and dogs?")
        for token in stream.response_gen:
            yield token

    return app.response_class(generate(), mimetype="text/plain")


@app.route("/timeout_run")
def timeout_run():
    def generate():
        stream = chat_engine.stream_chat("Hello, how are you")
        for token in timeout_stream(stream):
            yield token

        my_msg = "\nCan you write me a poem about raining cats and dogs?\n"
        for token in my_msg.split(" "):
            yield token
            yield " "
            time.sleep(0.5)

        stream = chat_engine.stream_chat("Can you write me a poem about raining cats and dogs?")
        for token in timeout_stream(stream):
            yield token

    return app.response_class(generate(), mimetype="text/plain")


if __name__ == "__main__":
    app.run(host="127.0.0.1", port=8000)
```
and I continue to obtain the same results. The observed CPU values refer to the CPU usage of the Python process running Flask (obviously not the entire CPU of the machine, but of the process where active waiting in the response_gen method occurs).

On an **M1 Mac**:
- Calling the **/run** endpoint correctly returns the response, and the CPU usage of the Python process running Flask reaches 100% during response generation.
- Calling the **/timeout_run** endpoint correctly returns the response, with the CPU usage of the process reaching a maximum of 10%.

On a Linux server within a **Docker container**:
- Calling the **/run** endpoint doesn't generate any response, and the CPU usage of the Python process running Flask goes to 100% for a couple of minutes, after which the HTTP request fails.
- Calling the **/timeout_run** endpoint correctly returns the response, with the CPU usage of the process reaching a maximum of 15%.


I'm not sure why it's getting stuck on the server, but it's possible that the Flask process is preventing the GPT call thread from executing, leading to a deadlock. In any case, setting a timeout appears to resolve the issue in my tests.

**Comment by logan-markewich** [comment]
(This should be fixed IMO, with the PR I merged above)
