### ISSUE TITLE
[Bug]: matedata is lost

### ISSUE THREAD

**Issue by jack-gits** [run-llama/llama_index#10318]
### Bug Description

when using DocumentSummaryIndex to build the index, the matedata such as file name is lost.
you can check the code in llama_index/indices/document_summary/base.py as below:
`           summary_node_dict[doc_id] = TextNode(
                 text=summary_response.response,
                 relationships={
                     NodeRelationship.SOURCE: RelatedNodeInfo(node_id=doc_id)
                 },
             )`

### Version

0.9.36

### Steps to Reproduce

`.     service_context = ServiceContext.from_defaults()
        response_synthesizer = get_response_synthesizer(
            response_mode="tree_summarize", use_async=True
        )
        doc_summary_index = DocumentSummaryIndex.from_documents(
            docs,
            service_context=service_context,
            storage_context=self.storage_context_summary,
            response_synthesizer=response_synthesizer
        )
        return doc_summary_index`

**Comment by jack-gits** [comment]
would you fix this issue next release?

**Comment by jayantverma2809** [comment]
@jack-gits  can you please attach the full code of your use case for a better understanding
