### ISSUE TITLE
[Bug]:  llamaindex-cli unrecognized arguments: - files ./README.md

### ISSUE THREAD

**Issue by fengyunzaidushi** [run-llama/llama_index#10315]
### Bug Description

`
(base) ubuntu@ubuntu:/mnt/sda/github/01yue/llama_index$ llamaindex-cli rag - files "./README.md"
usage: llamaindex-cli [-h] {rag,download-llamapack,download-llamadataset} ...
llamaindex-cli: error: unrecognized arguments: - files ./README.md

`

`
(base) ubuntu@ubuntu:/mnt/sda/github/01yue/llama_index$ llamaindex-cli -h
usage: llamaindex-cli [-h] {rag,download-llamapack,download-llamadataset} ...

LlamaIndex CLI tool.

options:
  -h, --help            show this help message and exit

commands:
  {rag,download-llamapack,download-llamadataset}
    rag                 Ask a question to a document / a directory of documents.
    download-llamapack  Download a llama-pack
    download-llamadataset
                        Download a llama-dataset

`

### Version

0.9.39

### Steps to Reproduce

llamaindex-cli rag - files "./README.md"

**Comment by logan-markewich** [comment]
@fengyunzaidushi as the bot mentioned, please use `llamaindex-cli rag --files "./README.md"` or `llamaindex-cli rag -f "./README.md"`

**Comment by fengyunzaidushi** [comment]
> @fengyunzaidushi as the bot mentioned, please use `llamaindex-cli rag --files "./README.md"` or `llamaindex-cli rag -f "./README.md"`

thank you! 
[https://blog.llamaindex.ai/introducing-the-llamaindex-retrieval-augmented-generation-command-line-tool-a973fa519a41](https://blog.llamaindex.ai/introducing-the-llamaindex-retrieval-augmented-generation-command-line-tool-a973fa519a41)
i followed the articles above,it has some error.
![image](https://github.com/run-llama/llama_index/assets/53250064/f31569ee-868b-4a7c-92d1-0a09076d3b28)

**Comment by logan-markewich** [comment]
Hmm, seems like a weird formatting error, I'll see if we can fix it
