### ISSUE TITLE
[Question]: Getting SSL error while trying to create index in azure cognitive search

### ISSUE THREAD

**Issue by VRSupriya** [run-llama/llama_index#10310]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to index data to azure AI search using llamaindex and I am getting ConnectError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (detailed traceback is attached in error.txt file
[error.txt](https://github.com/run-llama/llama_index/files/14071969/error.txt)).   But I could run the same without llamaindex framework. 

I had uploaded the certificate from openai website and added in the pem_certificate path. It didnt work.

The openai version: 1.2.4 and the llamaindex version: 0.9.32 
I am using windows 11 and python 3.11.4

**Comment by logan-markewich** [comment]
Are you using a VPN or work laptop? That was pretty common for me in the past in that scenario. Workaround was using a different computer lol

**Comment by VRSupriya** [comment]
Closing this issue.  There was a bug in code. I was passing openai embedding instead of azureopenai embedding
