### ISSUE TITLE
[Question]: Langchain integration demo notebook

### ISSUE THREAD

**Issue by zohaibdr** [run-llama/llama_index#10334]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I am looking to integrate llama-index tool inside a langchain agent. There seems to be only 1 page in the documentation on this. But the link to the demo notebook seems to be broken. 
https://github.com/run-llama/llama_index/blob/main/examples/langchain_demo/LangchainDemo.ipynb

I also checked the github repo manually. Is this file moved or deleted?

**Comment by lehmus** [comment]
Hi, I was able to retrieve the notebook from a random branch (open-ai-key-validation):

https://github.com/run-llama/llama_index/blob/open-ai-key-validation/examples/langchain_demo/LangchainDemo.ipynb

No idea if this is the most recent version or why the notebook was deleted in the first place. :shrug:

**Comment by ryanzlu** [comment]
Looks like the notebook was deleted in https://github.com/run-llama/llama_index/pull/9954 due to `not referenced in the docs, and not maintained`

**Comment by AlbertoMQ** [comment]
So will langchain integration no longer be supported moving forward?
