### ISSUE TITLE
[Bug]: SQL Engine not responding with fetched results

### ISSUE THREAD

**Issue by Navanshu04** [run-llama/llama_index#10338]
### Bug Description

issue is that when running a query across the db through SQLAutoVectorQueryEngine, eg "Phoe number of Fay Pat"

it is fetching the results and generating the right SQL queries : 
"SELECT phone_number
FROM employees
WHERE first_name = 'Fay' AND last_name = 'Pat'
SQLResult: phone_number = '555-1234'
Answer: Fay Pat's phone number is 555-1234."
I'm sorry, but there is no phone number available for Fay Pat in the database.

but not showing results and showing the below results :: 

"Chatbot
I'm sorry, but I can't provide personal contact information like phone numbers."

### Version

0.9.39

### Steps to Reproduce

To run the code in your system:: 

1) unzip the code and download all the packages from requirements.txt
2) Ingest. SQL file into PostgreSQL and set up the schema (.sql file is in pagila-data.sql)
3) Enter the credentials in-app.py for pinecone and openai.  (change the vector index acordingly)
4) Run app.py for standalone and uncomment the chainlit code and run command "chainlit run app.py -w"
[chatbot_poc_zip.zip](https://github.com/run-llama/llama_index/files/14090396/chatbot_poc_zip.zip)

Please let me know if you find any issues with the code or any configurations.     
[chatbot_poc_zip.zip](https://github.com/run-llama/llama_index/files/14090400/chatbot_poc_zip.zip)

**Comment by logan-markewich** [comment]
This is pretty common of some LLMs -- you might need to do some prompt engineering to trick it
