### ISSUE TITLE
[Question]: Disfference between using DocumentSummaryIndex Versus using SummaryExtractor to enrich metadata? 

### ISSUE THREAD

**Issue by mw-hv** [run-llama/llama_index#10336]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, Can anyone share their experience with using DocumentSummaryIndex for indexing, versus, using SummaryExtractor to enrich metadata while creating nodes? From the description, they same to work in similar way to me, wondering if anyone notice significant performance difference using one versus another? Thanks

**Comment by mw-hv** [comment]
@dosu-bot Hi, you were comparing wrong functions, the functions I want to compare are''from llama_index.extractors import SummaryExtractor'' and ''from llama_index.indices.document_summary import DocumentSummaryIndex''

**Comment by logan-markewich** [comment]
A document summary index will generate summaries and embed them, and retrieve based on that. When they are retrieved, the summary is replaced with the content from the original document and the chunks are sent to the LLM

This is slightly different compared to adding metadata. In document/node object, a combination of the node text + summary is sent to the embedding model, and those same nodes are retrieved. Here, you lose the effect of retrieving a summary and replacing with the entire document

**Comment by mw-hv** [comment]
@logan-markewich  Thank you, Logan, for your comments, sounds like the advantage of using DocumentSummaryIndex is that it can save some tokens from providing as input to LLM compare to using SummaryExtractor, which provides summary metadata as well as original text. Considering summary is a higher level information of original text, another drawback of using SummaryExtractor I can think of is, potentially, retrieved nodes will share similar summary, and thus lead to duplicated content get provide to LLM? 

I wonder is there any use case using SummaryExtractor would be more suitable than using DocumentSummaryIndex assuming both ways have similar retrieval accuracy?

**Comment by talhalatifkhan** [comment]
How can we utlize the summaryextractor to do similarity search on that ?
