### ISSUE TITLE
[Bug]: BM25 retriever not working just with indexes

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#10344]
### Bug Description

Tried running BM25 retriever just with Index(no nodes) but this error comes up.

Code:
bm25_retriever = BM25Retriever.from_defaults(index=index1, similarity_top_k=1, )

Error:
ZeroDivisionError: division by zero

Error Explanation:
ZeroDivisionError                         Traceback (most recent call last)
[<ipython-input-74-ed4b46ca2e15>](https://localhost:8080/#) in <cell line: 5>()
      3 
      4 vector_retriever = index1.as_retriever(similarity_top_k=10)
----> 5 bm25_retriever = BM25Retriever.from_defaults(index=index1, similarity_top_k=1, )
      6 from llama_index.retrievers import BaseRetriever
      7 class HybridRetriever(BaseRetriever):

4 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/retrievers/bm25_retriever.py](https://localhost:8080/#) in from_defaults(cls, index, nodes, docstore, tokenizer, similarity_top_k, verbose)
     76 
     77         tokenizer = tokenizer or tokenize_remove_stopwords
---> 78         return cls(
     79             nodes=nodes,
     80             tokenizer=tokenizer,

[/usr/local/lib/python3.10/dist-packages/llama_index/retrievers/bm25_retriever.py](https://localhost:8080/#) in __init__(self, nodes, tokenizer, similarity_top_k, callback_manager, objects, object_map, verbose)
     43         self._similarity_top_k = similarity_top_k
     44         self._corpus = [self._tokenizer(node.get_content()) for node in self._nodes]
---> 45         self.bm25 = BM25Okapi(self._corpus)
     46         super().__init__(
     47             callback_manager=callback_manager,

[/usr/local/lib/python3.10/dist-packages/rank_bm25.py](https://localhost:8080/#) in __init__(self, corpus, tokenizer, k1, b, epsilon)
     81         self.b = b
     82         self.epsilon = epsilon
---> 83         super().__init__(corpus, tokenizer)
     84 
     85     def _calc_idf(self, nd):

[/usr/local/lib/python3.10/dist-packages/rank_bm25.py](https://localhost:8080/#) in __init__(self, corpus, tokenizer)
     25             corpus = self._tokenize_corpus(corpus)
     26 
---> 27         nd = self._initialize(corpus)
     28         self._calc_idf(nd)
     29 

[/usr/local/lib/python3.10/dist-packages/rank_bm25.py](https://localhost:8080/#) in _initialize(self, corpus)
     50             self.corpus_size += 1
     51 
---> 52         self.avgdl = num_doc / self.corpus_size
     53         return nd
     54

### Version

0.9.39

### Steps to Reproduce

bm25_retriever = BM25Retriever.from_defaults(index=index, similarity_top_k=1, )

**Comment by logan-markewich** [comment]
@arnavroh45 How did you define your index? If you are using a remote vector db, this won't work, since the nodes are stored in the vector db and there is no direct API to access them all

**Comment by arnavroh45** [comment]
Yeah, you are right. I am using a remote vector db. Is there any way to implement BM25, then?

**Comment by logan-markewich** [comment]
@arnavroh45 mmm. Really only if you did `index.as_retriever(similarity_top_k=10000)` and retrieved all the nodes, and used that tk build bm25

**Comment by arnavroh45** [comment]
I tried this too. But getting the same error. This particular line of code was mentioned in the documentation. 
bm25_retriever = BM25Retriever.from_defaults(docstore=index.docstore, similarity_top_k=1, )

**Comment by logan-markewich** [comment]
@arnavroh45 yea by default the docstore is not populated when using a vector db integration 

Try this

```
source_nodes = index.as_retriever(similarity_top_k=10000).retrieve("test")
nodes = [x.node for x in source_nodes]
bm25 = BM25Retriever.from_defaults(nodes=nodes)

```

**Comment by arnavroh45** [comment]
No, I wasn't able to use BM25. I chose a different retriever only.
