### ISSUE TITLE
[Question]: Obtain source of information with OpenAIAgent

### ISSUE THREAD

**Issue by alvarojauna** [run-llama/llama_index#10355]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I use an OpenAIAgent I cant get the source of information and I dont have any idea why:

# Build CohereRerank post retrieval processor
api_key = os.environ["COHERE_API_KEY"]=""
cohere_rerank = CohereRerank(api_key=api_key, top_n=2)

qa_tmpl_str = (
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "I am an assistant specialized in Azure and its architectures. ONLY TAKE INFORMATION FROM KNOWLEDGE OF THE CONTEXT. IF NOT TELL THAT YOU DONT KNOW"
    "answer the query.\n"
    "Query: {query_str}\n"
    "Answer: "
)
qa_tmpl = PromptTemplate(qa_tmpl_str)

#llm = OpenAI(model="gpt-3.5-turbo", temperature=0, max_tokens=256)

query_engine = index.as_query_engine(
    llm=llm, text_qa_template=qa_tmpl,similarity_top_k=10,node_postprocessors=[cohere_rerank]
)

from llama_index.agent import OpenAIAgent
from llama_index.tools import QueryEngineTool

tool = QueryEngineTool.from_defaults(query_engine, name="query", description="I am an assistant specialized in Azure and its architectures. ONLY TAKE INFORMATION FROM KNOWLEDGE OF THE CONTEXT. IF NOT TELL THAT YOU DONT KNOW")
agent = OpenAIAgent.from_tools([tool], verbose=True)
response_agen=agent.chat("Can BIM data from providers other than Autodesk Forge be used in the solution?")

response_agen

AgentChatResponse(response='Yes, the solution can work with BIM data from providers other than Autodesk Forge. The solution is designed to be flexible and can integrate with various BIM data sources. It can consume BIM data from different providers and use it to generate insights and perform analysis.', **sources=[], source_nodes=[]**)

**Comment by alvarojauna** [comment]
I want the source of the retrieved embeddings while using an openai agent

**Comment by logan-markewich** [comment]
@alvarojauna If sources/source nodes is empty, that means no tools or source were used
