### ISSUE TITLE
[Question]: why node types influence the behavior of similarity_top_k?

### ISSUE THREAD

**Issue by qiongw** [run-llama/llama_index#10356]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I used the following code to generate the nodes:
documents = SimpleWebPageReader(
    html_to_text=True
).load_data(["http://paulgraham.com/worked.html"])

document = Document(text="\n\n".join([doc.text for doc in documents]))

-------------------------- base_nodes -------------------------------------------
text_splitter = SentenceSplitter(chunk_size = 100, chunk_overlap =0)
base_nodes = text_splitter.get_nodes_from_documents([document])
-------------------------- base_nodes -------------------------------------------

-------------------------- leaf_nodes  -------------------------------------------
node_parser = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[2048, 512, 128]
)
nodes = node_parser.get_nodes_from_documents([document])
leaf_nodes = get_leaf_nodes(nodes)
-------------------------- leaf_nodes  -------------------------------------------

Then I used the following code to generate the engine 

index = VectorStoreIndex(base_nodes (or leaf_nodes ))

retriever = index .as_retriever(
    similarity_top_k=2
)

engine = RetrieverQueryEngine.from_args(
    retriever 
)

response = engine .query(
    "What did the author do growing up?"
)

response.get_formatted_sources

When I use base_nodes in VectorStoreIndex(), then response.get_formatted_sources only returns 1 node. 
When I use leaf_nodes  in VectorStoreIndex(), then response.get_formatted_sources returns 2 nodes.

I think in both cases, 2 nodes should be returned since we set  similarity_top_k=2 right?
Can anyone help? Thanks a lot.

**Comment by logan-markewich** [comment]
@qiongw is there only one base node maybe?

**Comment by qiongw** [comment]
@logan-markewich len(base_nodes) = 434. And another strange thing is when similarity_top_k equals 1 or 2, one node is returned, when similarity_top_k equals 3 or 4, two nodes are returned and so on.  It seems the number of nodes returned equals  numpy.ceil(similarity_top_k /2).

**Comment by logan-markewich** [comment]
@qiongw that's extremely strange... let me see if I can replicate this

**Comment by logan-markewich** [comment]
@qiongw small update -- there is a certain point after the top k where the nodes are de-duped according to their hash.

It seems that the webpage you used to load data loads the same text twice for whatever reason. So when you retrieve using the base nodes, two duplicate nodes are retrieved

**Comment by logan-markewich** [comment]
Seems like either an issue with the simple web page reader, or just an edge case with reading this particular webpage. Otherwise, it seems to be working as intended

**Comment by qiongw** [comment]
@logan-markewich  Thanks! I just checked, indeed the function SimpleWebPageReader() (from llama_index.readers.web import SimpleWebPageReader) loads the same text twice.
