### ISSUE TITLE
[Feature Request]: Integrate BGE-M3 Model

### ISSUE THREAD

**Issue by Ch4osMy7h** [run-llama/llama_index#10366]
### Feature Description

https://huggingface.co/BAAI/bge-m3

A powerful embedding model which supports these features:
1. dense retrieval, multi-vector retrieval, and sparse retrieval
2. multi-linguality, and up to 8192 seq length

**Comment by logan-markewich** [comment]
Am I wrong, or can this already be used with our existing HuggingFaceEmbedding class?

**Comment by Ch4osMy7h** [comment]
Like integrated BGR-Reranker node post-processor, to use this model, you
need to install FlagEmbedding, and inference by this package provided
function.

*Best Regards, *
*Zhichao Lin*


Logan ***@***.***>于2024年1月31日 周三11:34写道：

**Comment by Ch4osMy7h** [comment]
here is the FlagEmbedding implementation https://github.com/FlagOpen/FlagEmbedding/blob/master/FlagEmbedding/bge_m3.py

**Comment by logan-markewich** [comment]
We have support for flag embedding reranker 

https://github.com/run-llama/llama_index/blob/main/docs/examples/node_postprocessor/FlagEmbeddingReranker.ipynb

**Comment by logan-markewich** [comment]
But I suppose no normal embedding class for flag embedding

**Comment by juleskuehn** [comment]
Is anyone working on this? I am interested in this too.

**Comment by logan-markewich** [comment]
Nobody currently working on it. Would welcome a PR

**Comment by FWiner** [comment]
That's working for me to use 

> `HuggingFaceEmbedding(model_name="BAAI/bge-m3")`

**Comment by logan-markewich** [comment]
Yea tbh I expect that to work fine. Going to close this

**Comment by panuthept** [comment]
> That's working for me to use
> 
> > `HuggingFaceEmbedding(model_name="BAAI/bge-m3")`

This solution won't use the full functionalities of BGE-M3. the sparse and multi-vector retrieval scores of BGE-M3 will be ignored.
