### ISSUE TITLE
[Feature Request]: SyneTuneParameterTuner

### ISSUE THREAD

**Issue by austinmw** [run-llama/llama_index#10362]
### Feature Description

Similar to `RayTuneParamTuner`, a hyperparameter tuning mechanism powered by [AWS Syne Tune](https://github.com/awslabs/syne-tune?tab=readme-ov-file#syne-tune-large-scale-and-reproducible-hyperparameter-optimization).

### Reason

This would enable simple large scale HPO by distributing jobs across SageMaker training instances.

### Value of Feature

The AWS Syne Tune setup with SageMaker is less complicated than setting up Ray Tune clusters for most users.

**Comment by nerdai** [comment]
Hey @austinmw! Thanks for the request. Definitely agree it would be great to have this in our library for the reasons you mentioned. I should say that as it stands today our `param_tuner` module is still experimental. Nevertheless, would love to see this in there as another option for our users. If you want to make a PR for this, you'd be more than welcome :)

**Comment by austinmw** [comment]
Thanks, I'll see if we can make a PR for this.
