### ISSUE TITLE
[Bug]: Context length exceeded

### ISSUE THREAD

**Issue by ZiyuanLi123** [run-llama/llama_index#10368]
### Bug Description

from llama_index import SummaryIndex,ListIndex
from llama_index.node_parser import SentenceSplitter
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model,chunk_size=1024)
nodes = service_context.node_parser.get_nodes_from_documents(docs1)
list_index = ListIndex(nodes,service_context=ServiceContext)
list_query_engine = list_index.as_query_engine(
    response_mode = "tree_summarize", use_async = True
)
list_query_engine.query('give me a summary of sleep')

when I try to run above script the following errors occurs

BadRequestError                           Traceback (most recent call last)
File <command-3765235506543199>, line 1
----> 1 list_query_engine.query('give me a summary of sleep')

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/core/base_query_engine.py:40, in BaseQueryEngine.query(self, str_or_query_bundle)
     38 if isinstance(str_or_query_bundle, str):
     39     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 40 return self._query(str_or_query_bundle)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py:172, in RetrieverQueryEngine._query(self, query_bundle)
    168 with self.callback_manager.event(
    169     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    170 ) as query_event:
    171     nodes = self.retrieve(query_bundle)
--> 172     response = self._response_synthesizer.synthesize(
    173         query=query_bundle,
    174         nodes=nodes,
    175     )
    177     query_event.on_end(payload={EventPayload.RESPONSE: response})
    179 return response

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/response_synthesizers/base.py:168, in BaseSynthesizer.synthesize(self, query, nodes, additional_source_nodes, **response_kwargs)
    163     query = QueryBundle(query_str=query)
    165 with self._callback_manager.event(
    166     CBEventType.SYNTHESIZE, payload={EventPayload.QUERY_STR: query.query_str}
    167 ) as event:
--> 168     response_str = self.get_response(
    169         query_str=query.query_str,
    170         text_chunks=[
    171             n.node.get_content(metadata_mode=MetadataMode.LLM) for n in nodes
    172         ],
    173         **response_kwargs,
    174     )
    176     additional_source_nodes = additional_source_nodes or []
    177     source_nodes = list(nodes) + list(additional_source_nodes)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/response_synthesizers/tree_summarize.py:192, in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
    181 else:
    182     tasks = [
    183         self._service_context.llm.astructured_predict(
    184             self._output_cls,
   (...)
    189         for text_chunk in text_chunks
    190     ]
--> 192 summary_responses = run_async_tasks(tasks)
    194 if self._output_cls is not None:
    195     summaries = [summary.json() for summary in summary_responses]

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/async_utils.py:49, in run_async_tasks(tasks, show_progress, progress_bar_desc)
     46 async def _gather() -> List[Any]:
     47     return await asyncio.gather(*tasks_to_execute)
---> 49 outputs: List[Any] = asyncio.run(_gather())
     50 return outputs

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/nest_asyncio.py:30, in _patch_asyncio.<locals>.run(main, debug)
     28 task = asyncio.ensure_future(main)
     29 try:
---> 30     return loop.run_until_complete(task)
     31 finally:
     32     if not task.done():

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/nest_asyncio.py:98, in _patch_loop.<locals>.run_until_complete(self, future)
     95 if not f.done():
     96     raise RuntimeError(
     97         'Event loop stopped before Future completed.')
---> 98 return f.result()

File /usr/lib/python3.10/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception.with_traceback(self._exception_tb)
    202 return self._result

File /usr/lib/python3.10/asyncio/tasks.py:234, in Task.__step(***failed resolving arguments***)
    232         result = coro.send(None)
    233     else:
--> 234         result = coro.throw(exc)
    235 except StopIteration as exc:
    236     if self._must_cancel:
    237         # Task is cancelled right before coro stops.

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/async_utils.py:47, in run_async_tasks.<locals>._gather()
     46 async def _gather() -> List[Any]:
---> 47     return await asyncio.gather(*tasks_to_execute)

File /usr/lib/python3.10/asyncio/tasks.py:304, in Task.__wakeup(self, future)
    302 def __wakeup(self, future):
    303     try:
--> 304         future.result()
    305     except BaseException as exc:
    306         # This may also be a cancellation.
    307         self.__step(exc)

File /usr/lib/python3.10/asyncio/tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/llms/llm.py:280, in LLM.apredict(self, prompt, **prompt_args)
    278 if self.metadata.is_chat_model:
    279     messages = self._get_messages(prompt, **prompt_args)
--> 280     chat_response = await self.achat(messages)
    281     output = chat_response.message.content or ""
    282 else:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/llms/base.py:57, in llm_chat_callback.<locals>.wrap.<locals>.wrapped_async_llm_chat(_self, messages, **kwargs)
     47 with wrapper_logic(_self) as callback_manager:
     48     event_id = callback_manager.on_event_start(
     49         CBEventType.LLM,
     50         payload={
   (...)
     54         },
     55     )
---> 57     f_return_val = await f(_self, messages, **kwargs)
     58     if isinstance(f_return_val, AsyncGenerator):
     59         # intercept the generator and add a callback to the end
     60         async def wrapped_gen() -> ChatResponseAsyncGen:

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/llms/openai.py:494, in OpenAI.achat(self, messages, **kwargs)
    492 else:
    493     achat_fn = acompletion_to_chat_decorator(self._acomplete)
--> 494 return await achat_fn(messages, **kwargs)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/llama_index/llms/openai.py:538, in OpenAI._achat(self, messages, **kwargs)
    536 aclient = self._get_aclient()
    537 message_dicts = to_openai_message_dicts(messages)
--> 538 response = await aclient.chat.completions.create(
    539     messages=message_dicts, stream=False, **self._get_model_kwargs(**kwargs)
    540 )
    541 message_dict = response.choices[0].message
    542 message = from_openai_message(message_dict)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/openai/resources/chat/completions.py:1322, in AsyncCompletions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
   1271 @required_args(["messages", "model"], ["messages", "model", "stream"])
   1272 async def create(
   1273     self,
   (...)
   1320     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
   1321 ) -> ChatCompletion | AsyncStream[ChatCompletionChunk]:
-> 1322     return await self._post(
   1323         "/chat/completions",
   1324         body=maybe_transform(
   1325             {
   1326                 "messages": messages,
   1327                 "model": model,
   1328                 "frequency_penalty": frequency_penalty,
   1329                 "function_call": function_call,
   1330                 "functions": functions,
   1331                 "logit_bias": logit_bias,
   1332                 "logprobs": logprobs,
   1333                 "max_tokens": max_tokens,
   1334                 "n": n,
   1335                 "presence_penalty": presence_penalty,
   1336                 "response_format": response_format,
   1337                 "seed": seed,
   1338                 "stop": stop,
   1339                 "stream": stream,
   1340                 "temperature": temperature,
   1341                 "tool_choice": tool_choice,
   1342                 "tools": tools,
   1343                 "top_logprobs": top_logprobs,
   1344                 "top_p": top_p,
   1345                 "user": user,
   1346             },
   1347             completion_create_params.CompletionCreateParams,
   1348         ),
   1349         options=make_request_options(
   1350             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
   1351         ),
   1352         cast_to=ChatCompletion,
   1353         stream=stream or False,
   1354         stream_cls=AsyncStream[ChatCompletionChunk],
   1355     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/openai/_base_client.py:1705, in AsyncAPIClient.post(self, path, cast_to, body, files, options, stream, stream_cls)
   1691 async def post(
   1692     self,
   1693     path: str,
   (...)
   1700     stream_cls: type[_AsyncStreamT] | None = None,
   1701 ) -> ResponseT | _AsyncStreamT:
   1702     opts = FinalRequestOptions.construct(
   1703         method="post", url=path, json_data=body, files=await async_to_httpx_files(files), **options
   1704     )
-> 1705     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/openai/_base_client.py:1408, in AsyncAPIClient.request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1399 async def request(
   1400     self,
   1401     cast_to: Type[ResponseT],
   (...)
   1406     remaining_retries: Optional[int] = None,
   1407 ) -> ResponseT | _AsyncStreamT:
-> 1408     return await self._request(
   1409         cast_to=cast_to,
   1410         options=options,
   1411         stream=stream,
   1412         stream_cls=stream_cls,
   1413         remaining_retries=remaining_retries,
   1414     )

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-9e679887-f67a-43c9-8f51-b5be9da34c59/lib/python3.10/site-packages/openai/_base_client.py:1499, in AsyncAPIClient._request(self, cast_to, options, stream, stream_cls, remaining_retries)
   1496         await err.response.aread()
   1498     log.debug("Re-raising status error")
-> 1499     raise self._make_status_error_from_response(err.response) from None
   1501 return await self._process_response(
   1502     cast_to=cast_to,
   1503     options=options,
   (...)
   1506     stream_cls=stream_cls,
   1507 )

BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 4096 tokens. However, your messages resulted in 4266 tokens. Please reduce the length of the messages.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

### Version

llama-index 0.9.40

### Steps to Reproduce

from llama_index import SummaryIndex,ListIndex
from llama_index.node_parser import SentenceSplitter
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model,chunk_size=1024)
nodes = service_context.node_parser.get_nodes_from_documents(docs1)
list_index = ListIndex(nodes,service_context=ServiceContext)
list_query_engine = list_index.as_query_engine(
    response_mode = "tree_summarize", use_async = True
)
list_query_engine.query('give me a summary of sleep')

**Comment by nerdai** [comment]
@ZiyuanLi123 Perhaps you can try adding a node postprocessor that does prompt compression.

Here's an  example notebook of LongLLMLingua: [nb](https://github.com/microsoft/LLMLingua/blob/main/examples/RAGLlamaIndex.ipynb)

**Comment by timothyckl** [comment]
also facing a similar issue, any fixes?
