### ISSUE TITLE
[Bug]: Unable to connect to MilvusVectorStore due to SSLError

### ISSUE THREAD

**Issue by zirota** [run-llama/llama_index#10367]
### Bug Description

SSL_ERROR when using `MilvusVectorStore` to connect to Milvus running on-premises.

This is due to Milvus expecting certs fields to be provided (e.g. `server_pem_path`) which is not explicitly available when using `MilvusClient`.

As a temporary fix on my end, I added locally to https://github.com/run-llama/llama_index/blob/87b2c74c9036aba1cbef805490ffd0ad39501a03/llama_index/vector_stores/milvus.py#L137-L140

This is to allow passing of **kwargs to the pymilvus library to be used for connection

```
# Connect to Milvus instance
self.milvusclient = MilvusClient(
    uri=uri,
    token=token,
    **kwargs
)
```

Then connect with the following

```
MilvusVectorStore(
      dim=768, 
      collection_name='collection1',
      uri=<MILVUS_URI>,
      server_name=<MILVUS_SERVER_NAME>,
      server_pem_path=<MILVUS_PEM_PATH>,
      secure=True,
      user=<MILVUS_USERNAME>,
      password=<MILVUS_PASSWORD>
)
```

### Version

0.9.40

### Steps to Reproduce

Connect to MilvusVectorStore

```
MilvusVectorStore(
    dim=768, 
    collection_name='collection1',
    uri=<MILVUS_URI>,
    user=<MILVUS_USERNAME>
    password=<MILVUS_PASSWORD>
 )
```

**Comment by nerdai** [comment]
Thanks @zirota for this. Looking at Milvus' source code for `MilvusClient` (see [here](https://github.com/milvus-io/pymilvus/blob/4858eee3e2d02069343ebf581b20d82603b7a94d/pymilvus/milvus_client/milvus_client.py#L613)), they also use kwargs propagation to handle additional arguments such as tls cert paths. As such, I think this is best option for us as well.
