### ISSUE TITLE
[Bug]: chat engine with chat memory doesn't seek information from vector store

### ISSUE THREAD

**Issue by patrickporto** [run-llama/llama_index#10361]
### Bug Description

Hello

I am developing a chat engine using Redis and PG Vector; however, the contextual information is left out when I put the Redis as chat memory:

```python

OPENAI_EMBEDDING_DIMENSION = 1536

embed_model = OpenAIEmbedding()

vector_store = PGVectorStore.from_params(
    database=settings.VECTOR_DB_URI.database,
    host=settings.VECTOR_DB_URI.host,
    password=settings.VECTOR_DB_URI.password,
    port=settings.VECTOR_DB_URI.port,
    user=settings.VECTOR_DB_URI.user,
    table_name="assistant_embedding",
    embed_dim=OPENAI_EMBEDDING_DIMENSION,
)

service_context = ServiceContext.from_defaults(embed_model=embed_model)

index = VectorStoreIndex.from_vector_store(
    vector_store=vector_store,
    service_context=service_context,
)

chat_store = RedisChatStore(redis_url=settings.REDIS_CACHE_URI, ttl=60 * 60 * 24 * 7)

chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=3000,
    chat_store=chat_store,
    chat_store_key='session_id',
)
chat_engine = index.as_chat_engine(
    chat_mode=ChatMode.CONTEXT,
    memory=chat_memory
)
```

### Version

0.9.39

### Steps to Reproduce

1. Train an information about a person. 
2. You should use the previous code as a base and then ask for the previously trained information about the person.

**Comment by logan-markewich** [comment]
This particular chat mode calls `retrieve()` on every user message and inserts the retrieved context into the system prompt

It can then respond using the retrieved context, or without it.

Maybe you'd want to modify the system prompt with additional instructions 
```
chat_engine = index.as_chat_engine(
    chat_mode="context",
    memory=memory,
    system_prompt=(
        "You are a chatbot, able to have normal interactions, as well as talk"
        " about an essay discussing Paul Grahams life."
    ),
)
```

Info on other chat modes is here
https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/usage_pattern.html#available-chat-modes

**Comment by patrickporto** [comment]
@logan-markewich context chat mode is not the problem because without the memory parameter it returns the expected response, such as the following example:

```python
chat_engine = index.as_chat_engine(
    chat_mode=ChatMode.CONTEXT,
    # memory=chat_memory We need to comment this to the engine give me any response from the vector store
)
``` 

That chat engine does not return any information from the vector store when uncommenting the line about chat memory just from the conversation history.

**Comment by logan-markewich** [comment]
@patrickporto what does your service context look like?

We find the behavior to not be reproducible for me
