### ISSUE TITLE
[Question]: How to generate responses even when there is no information?

### ISSUE THREAD

**Issue by dersuchendee** [run-llama/llama_index#10378]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The system doesn't generate responses even when there is no information. I want to see if the system can deduce something basing on the information provided... How to do that? I get that no specific examples are specified and doesn't answer.

**Comment by dersuchendee** [comment]
@dosu-bot and how to use it?

**Comment by dersuchendee** [comment]
@dosu-bot 

```
aise ValueError("One of nodes or index_struct must be provided.")
ValueError: One of nodes or index_struct must be provided.
Exception ignored in: <function Driver.__del__ at 0x000002062BFC9E50>
Traceback (most recent call last):
```

**Comment by logan-markewich** [comment]
I'm not sure what the bot is going on about, but you just need to change the default prompt templates for your query engine (which it looks like you are already doing?)

https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts

**Comment by dersuchendee** [comment]
Yes, I'm trying, but I get this error:

```
Traceback (most recent call last):
  File "C:/Users/annas/PycharmProjects/untitled5/vediamoconllindex.py", line 79, in <module>
    print(query_engine(text_qa_template=text_qa_template, refine_template=refine_template).query("MYQUERY"))
TypeError: 'KnowledgeGraphQueryEngine' object is not callable
Exception ignored in: <function Driver.__del__ at 0x000001DDB6829EE0>
Traceback (most recent call last):
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\neo4j\_sync\driver.py", line 489, in __del__
  File "C:\Users\annas\AppData\Local\Programs\Python\Python38\lib\site-packages\neo4j\_meta.py", line 229, in unclosed_resource_warn
TypeError: 'NoneType' object is not callable
```
