### ISSUE TITLE
[Feature Request]: combine indexes or chat over multiple indexes

### ISSUE THREAD

**Issue by sharmaraju352** [run-llama/llama_index#10374]
### Feature Description

There no way to merge already created indexes or chat over multiple indexes.
This feature is there in python varient.

**Comment by ravi03071991** [comment]
Hi @sharmaraju352 ,

Could you please explain what you meant by combining multiple indices? Did you check [composability](https://docs.llamaindex.ai/en/stable/module_guides/indexing/composability.html)?
