### ISSUE TITLE
[Question]: How to do Multi-Document RAG with Document Summary Index?

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10389]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Using open source LLMs `zephyr-7b-alpha`, how can I do multiple document RAG especially where in my use case, there are complex queries, which may require me to decompose the query and query multiple documents and then synthesise the final response.

Tried `SubQuestionQueryEngine`, however I am limited by the number of tokens that can be generated by the LLM.

**Comment by nerdai** [comment]
I haven't tried this before, but may be worth a shot to use a prompt compression technique before synthesizing the final answer. 

[LLMLingua exmaple](https://github.com/microsoft/LLMLingua/blob/main/examples/RAGLlamaIndex.ipynb)
