### ISSUE TITLE
[Question]: Getting ORA-00933: SQL command not properly ended

### ISSUE THREAD

**Issue by rishabhgupta93** [run-llama/llama_index#10394]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Experts,

I am trying to retrieve data from Oracle DB using NLSQLTableQueryEngine. The pipeline is generating the correct SQL query. But the problem is that it is terminating the generated query with semi-colon.

Due to this semi-colon, I am getting the following error:

[NodeWithScore(node=TextNode(id_='13aaaa04-30bb-4072-990e-eec801ce3784', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={}, text="Error: (cx_Oracle.DatabaseError) ORA-00933: SQL command not properly ended\n[SQL: SELECT id, name, country, entrydate from abctable where entrydate < '2023-05-01' order by entrydate;]\n(Background on this error at: https://sqlalche.me/e/20/4xp6)", start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=None)]

The reason of that is cx_oracle library doesnt execute SQL statements ending with semi-colons. Is there any way that I can prompt to not terminate queries with semi colon or may be change something in the code to fix it.

Looking forward for your help!

Thanks in advance.

**Comment by logan-markewich** [comment]
You can try updating the text 2 sql prompt maybe, or including more instructions in your query.
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts

**Comment by huiraym** [comment]
Hi, I am getting exactly the same issue. The semicolon at the end will always fail the query and i noticed it is being added randomly. I tried making the suggested change to .\venv\Lib\site-packages\llama_index\indices\struct_store\sql_retriever.py and then recompiled the file to .pyc in the _pycache_ folder. I reran the test but the changes doesn't seem to be picked. Can you share some lights?

**Comment by socko777** [comment]
this issue still happens using llama-index 0.10.37
