### ISSUE TITLE
[Bug]: model specified is gpt-4, model returned is gpt-3.5 turbo. also temperature is false

### ISSUE THREAD

**Issue by Dyke-F** [run-llama/llama_index#10397]
### Bug Description

llm = OpenAI(temperature=0.9, model="gpt-4")
service_context = ServiceContext.from_defaults(llm=llm)
base_retriever = VectorIndexRetriever(
        index=index,
        similarity_top_k=15,
        service_context=service_context
    )

base_retriever._service_context.llm

returns: 

OpenAI(callback_manager=<llama_index.callbacks.base.CallbackManager object at 0x2c89e1ed0>, system_prompt=None, messages_to_prompt=<function messages_to_prompt at 0x138330e00>, completion_to_prompt=<function default_completion_to_prompt at 0x138365620>, output_parser=None, pydantic_program_mode=<PydanticProgramMode.DEFAULT: 'default'>, query_wrapper_prompt=None, model='gpt-3.5-turbo', temperature=0.1, ....)

### Version

0.9.39

### Steps to Reproduce

see above

**Comment by logan-markewich** [comment]
@Dyke-F the vector retriever uses the service context from the index, there's actually no way to pass it in directly right now

**Comment by logan-markewich** [comment]
So the solution here is to set the proper service context in your index

Depending on what your index is, this might look like a few things

```
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
# OR
index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)
# OR
index = load_index_from_storage(storage_context, service_context=service_context)
```

Or you could set a global default
```
from llama_index import set_global_service_context
set_global_service_context(service_context)
```
