### ISSUE TITLE
[Question]: How do I view the final received data for my model?

### ISSUE THREAD

**Issue by WhyMEliu** [run-llama/llama_index#10406]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I would like to ask how I can view the llm data that is finally returned to me. And I hope to go into debugging this way.

**Comment by logan-markewich** [comment]
@WhyMEliu You can check the response nodes to see the text that was used to create the answer

```
for node in response.source_nodes:
  print(node.text)
```

You can also enable debug logging if you want, to see the exact LLM inputs and outputs

https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html#simple-llm-inputs-outputs

**Comment by WhyMEliu** [comment]
Thank you very much for your answer！
