### ISSUE TITLE
[Bug]: FunctionTool not passing referenced objects/enums in json schema

### ISSUE THREAD

**Issue by leotronolone** [run-llama/llama_index#10401]
### Bug Description

I am no longer able to use referenced objects/enums within function call inputs on the latest version of llamaindex(0.9.40). This is caused by the referenced objects no longer being added to the json schema sent to the LLM when defining the function calls. These json schemas were being generated from the fn_schema input(which extends the BaseModel) from FunctionTool.fromDefaults() previously.

EX: 
LlamaIndex Latest version:
'{"properties": {"ask": {"description": "natural language query string", "title": "Ask", "type": "string"}, "entity_types": {"description": "The types of entities to search for answer", "items": {"$ref": "#/$defs/EntityType"}, "title": "Entity Types", "type": "array"}, "required": ["ask", "entity_types"], "type": "object"}'

LlamaIndex Old Version:
"{'$defs': {'EntityType': {'enum': ['file', 'response', 'member'], 'title': 'EntityType', 'type': 'string'}}, 'properties': {'ask': {'description': 'natural language query string', 'title': 'Ask', 'type': 'string'},  'entity_types': {'description': 'The types of entities to search for answer', 'items': {'$ref': '#/$defs/EntityType'}, 'title': 'Entity Types', 'type': 'array'}}, 'required': ['ask', 'entity_types'], 'title': 'AskQuestionGPTFunctionModel', 'type': 'object'}"

This is causing the LLM to return function call inputs that don't respect the desired json schema, causing an exception when it tries to call the function using a bad input value. 

EX: it will try calling the AskQuestion function with entity_types = ['document'] instead of one of the valid values of ["file", "response", "member"] 

This was working for me on 0.9.14. I tried updating pydantic and openai to the latest version as well but had no luck

### Version

0.9.15+

### Steps to Reproduce

Run the following example code:
```
from enum import Enum
from llama_index.llms.openai import OpenAI
from llama_index.tools import FunctionTool
from llama_index.agent import OpenAIAgent

from pydantic import BaseModel


class MATH_OPERATOR(str, Enum):
  ADD = "add"
  SUBTRACT = "subtract"


def calculate(math_operator: MATH_OPERATOR, valueA: int, valueB: int):
   return "answer"

class CalculateFunctionModel(BaseModel):
  math_operator: MATH_OPERATOR
  valueA: int
  valueB: int

def run():
  llm = OpenAI(model="gpt-4-1106-preview", temperature=0)
  calculator_tool = FunctionTool.from_defaults(
      fn=calculate,
      fn_schema=CalculateFunctionModel
    )
  agent = OpenAIAgent.from_tools(llm=llm, tools=[calculator_tool], verbose=True)
  return agent.chat("what is 2 * 2, make sure to use a tool")  

```

### Relevant Logs/Tracbacks

```shell
Added user message to memory: what is 212 * 2909, make sure to use a tool
** Messages: **
user: what is 212 * 2909, make sure to use a tool
**************************************************
** Response: **
assistant: None
**************************************************


=== Calling Function ===
Calling function: calculate with args: {"math_operator":"MULTIPLY","valueA":212,"valueB":2909}
```

**Comment by leotronolone** [comment]
FYI I was able to make a workaround where I defined the enum/object's schema in the description for the field.

```

class CalculateFunctionModel(BaseModel):
  math_operator: MATH_OPERATOR = Field(description=f"Possible MATH_OPERATOR vales: {[a.value for a in MATH_OPERATOR]}")
  valueA: int
  valueB: int

```


This workaround only works for the first layer of referenced object schemas though(which is enough for my usecase). Fixing this would still be greatly appreciated as I'm sure my usecase will need this eventually 🙏

**Comment by leotronolone** [comment]
Can we reopen this? The underlying issue has still not been resolved

**Comment by logan-markewich** [comment]
@leotronolone pretty sure this is solved in latest versions

**Comment by leotronolone** [comment]
@logan-markewich This workaround was required for 0.10.33 (latest version as of today)

**Comment by logan-markewich** [comment]
@leotronolone looks fine to me, but I think you are defining the function tool in an unexpected way

https://colab.research.google.com/drive/1GEt_dkEXnnVkygBqtwYnFfMOAvr78OKi?usp=sharing
