### ISSUE TITLE
[Question]: AnswerRelevancyEvaluator() and ContextRelevancyEvaluator() result and document are unclear. 

### ISSUE THREAD

**Issue by qiongw** [run-llama/llama_index#10410]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have some questions on AnswerRelevancyEvaluator() and ContextRelevancyEvaluator(). 

In the following link, it provide some description for AnswerRelevancyEvaluator() and ContextRelevancyEvaluator()
https://docs.llamaindex.ai/en/stable/api_reference/evaluation.html

AnswerRelevancyEvaluator():
Answer relevancy evaluator.
Evaluates the relevancy of response to a query. This evaluator considers the query string and response string.

ContextRelevancyEvaluator()
Context relevancy evaluator.
Evaluates the relevancy of retrieved contexts to a query. This evaluator considers the query string and retrieved contexts.

For both functions, they do not mention the the output score range. 

Based on the example document below, it seems the score from ContextRelevancyEvaluator() is between 0 and 1.  The score from AnswerRelevancyEvaluator() is 0, 0.5 or 1.
https://docs.llamaindex.ai/en/stable/examples/evaluation/answer_and_context_relevancy.html#evaluating-answer-and-context-relevancy-separately
Can anyone elaborate?

Issue with AnswerRelevancyEvaluator() and ContextRelevancyEvaluator() when using llama_index==0.9.41.
See one example below when using ContextRelevancyEvaluator()

Feedback: "1. The retrieved context partially matches the subject matter of the user's query. The context talks about what the author did growing up, including writing and programming. However, it does not provide a comprehensive answer to the query as it only covers a few aspects of the author's childhood activities. **(1 point)\**n\n2. The retrieved context cannot be used exclusively to provide a full answer to the user's query. While it provides some information about the author's childhood activities, it does not provide a complete picture of what the author did growing up. **(0 points)**\n\nOverall, the retrieved context is partially relevant to the user's query but does not provide a complete answer. \n\n**[RESULT] 1.0**"

Score: 0.25
Within the feedback, it contains some points. However, it is unclear what does it mean. And it is also unclear how the final score is calculated.  Is score calculated based on the points in the feedback?

See one example below when using AnswerRelevancyEvaluator()
EvaluationResult(query='What did the author do growing up?', contexts=None, response='Growing up, the author worked on writing and programming outside of school. They wrote short stories and tried writing programs on an IBM 1401 in 9th grade using an early version of Fortran. With microcomputers, the author started programming more and wrote simple games, a program to predict how high model rockets would fly, and a word processor that their father used to write at least one book.', passing=None, feedback="1. Yes, the provided response matches the subject matter of the user's query by discussing what the author did growing up.\n2. Yes, the provided response attempts to address the focus or perspective on the subject matter taken on by the user's query by discussing the author's activities related to writing and programming.\n\n[VALID] **followed by 2**", score=None, pairwise_source=None, invalid_result=True, invalid_reason='Unable to parse the output string.')

In the feedback, at the end it mentions "followed by 2", what does it mean?
Why the score is None?

**Comment by nerdai** [comment]
Hi @qiongw, both `AnswerRelevancyEvaluator` and `ContextRelevancyEvaluator` provide a "rubric" grading scheme to the LLM evaluator to pass judgement and make scores. Ultimately, provided the LLM evaluator adheres to required output format, the final score will be a score living between 0 and 1 (representing the fraction of points awarded by the Judge out of the total possible points).

Note, the rubrics for `AnswerRelevacnyEvaluator` and `ContextRelevancyEvaluator` are different and indeed have differing total number of points that can be awarded, AnswerRelevancy -> 2 Total Possible Points; ContextRelevancy -> 4 Total Possible Points.

The "rubrics" (i.e. DEFAULT_EVAL_TEMPLATE) can be viewed here:
- [AnswerRelevancyEvaluator](https://github.com/run-llama/llama_index/blob/3230669a205835c73e862011eb259914fa71ce71/llama_index/evaluation/answer_relevancy.py#L13)
- [ContextRelevancyEvaluator](https://github.com/run-llama/llama_index/blob/3230669a205835c73e862011eb259914fa71ce71/llama_index/evaluation/context_relevancy.py#L15)

Again, the final score is then computed by the formula: ( the total number of points awarded by the LLM ) / ( total possible points )

As for your second example, I don't know why the LLM would respond with "[VALID] followed by 2". And in so doing, our output parser fails to get a total points awarded to compute the final score. Thus, you see the invalid reason ="Unable to parse the output string."

May I know what LLM you are using to evaluate?

**Comment by qiongw** [comment]
@nerdai 
Thank you for your explanations. It is clear now and I will go through the links you provided. 
I am using "gpt-3.5-turbo" from Azure. 

Btw, I was also checking DeepEval following the links below:
https://docs.llamaindex.ai/en/stable/examples/evaluation/Deepeval.html
https://docs.llamaindex.ai/en/stable/examples/llm/azure_openai.html

But I got AuthenticationError: Error code: 401, maybe you know why?
