### ISSUE TITLE
[Bug]: SubquestionQueryEngine not working due to valifation Error 

### ISSUE THREAD

**Issue by JMTCoder** [run-llama/llama_index#10411]
### Bug Description

 I was basically following this tutorial https://docs.llamaindex.ai/en/latest/examples/query_engine/sub_question_query_engine.html in order to perform a subqueryEngine Query. 
When executing the `query_engine.query("my_query_as_str") `command, i would get the following error 

> 
> ValidationError: 1 validation error for SubQuestion
> __root__
>  SubQuestion expected dict not str (type=type_error)
> 

ps: i was also using the MockLLM and MockEmbedding in the `ServiceContext` provided by default.

### Version

0.9.40

### Steps to Reproduce

steps in this tutorial https://docs.llamaindex.ai/en/latest/examples/query_engine/sub_question_query_engine.html

**Comment by logan-markewich** [comment]
@JMTCoder The sub question query engine will not work with a mock llm -- it relies on the LLM to output some structured string that can be parsed.

Please set an actual LLM, or try/except that line of code if you are trying to estimate token usage.

**Comment by JMTCoder** [comment]
@logan-markewich thank you for your response.
I actually also tried using Azure OpenAI llm and embedding models, however after issuing the `query_engine.query("")` comman,  it was only performing the following two steps:
**********
Trace: query
    |_query ->  0.338631 seconds
      |_llm ->  0.0 seconds
**********

and then outputting the following error 

`NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}
`
ps: both llm and embedding models works fine with the normal query_engine.

thanks in advance

**Comment by logan-markewich** [comment]
@JMTCoder if you are using azure, make sure you are using a newer api version (at least 2023-07-preview)

**Comment by JMTCoder** [comment]
Thank you @logan-markewich for your comment, it actually now works after specifying the following api versions, I specified:

- 2023-05-15 for the embedding model
- 2023-07-01-preview for the llm model !

thanks and cheers
