### ISSUE TITLE
[Question]: How do I generate the list of sub questions when I am using a open source LLMs zephyr-7b-alpha

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10414]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I generate the list of sub questions when I am using a open source LLMs zephyr-7b-alpha?  `guidance` seem to work only for OpenAI models right? 

How can I do the same for open source LLMs? Please advise

**Comment by GxTeo** [comment]
@dosu-bot can you suggest a way to do it with open source LLMs?

**Comment by logan-markewich** [comment]
@GxTeo open-source LLMs are flakey at best for this. There is an example here using zephyr, it works most of the time
https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

In general, most open-source LLMs are quite bad at structured outputs. Someday we will improve this.

**Comment by GxTeo** [comment]
@logan-markewich , can i check would guidance work wiith zephyr on generating the list of sub questions? Or is there any other method i could try?

**Comment by GxTeo** [comment]
@logan-markewich  i see, thank you! Right now I am facing the issue that the LLM does not have enough room to generate sub-questions. 

I was thinking other than continuously increasing the` max_new_tokens `that the LLM can generate, is there a way I can split the generation of sub-questions into multiple "jobs",  in a way where for a single complex `query` where it may have to generate subquestions for each index,  the SubQuestionQueryEngine does multiple runs instead of a single LLM call.
