### ISSUE TITLE
[Bug]: validation error for NomicEmbedding

### ISSUE THREAD

**Issue by YasmineMh** [run-llama/llama_index#10420]
### Bug Description

NomicEmbedding raises a ValidationError indicating that the 'model_name' field is required but missing.

Also, the default model_name: str = "nomic-text-embed-v1" raises the following exception:

`Exception: (422, '{"detail":[{"loc":["body","model"],"msg":"value is not a valid enumeration member; permitted: \'all-MiniLM-L6-v2\', \'nomic-embed-text-v1\'","type":"type_error.enum","ctx":{"enum_values":["all-MiniLM-L6-v2","nomic-embed-text-v1"]}}]}')`

I'm gonna create a PR to fix those issues.

### Version

0.9.41

### Steps to Reproduce

Test the following notebook : https://github.com/run-llama/llama_index/blob/main/docs/examples/embeddings/nomic.ipynb

### Relevant Logs/Tracbacks

```shell
ValidationError                           Traceback (most recent call last)
<ipython-input-7-a531d1b10bd3> in <cell line: 2>()
      1 nomic_api_key = "nk-ZgBMniakwTrYXhsQS3QB9bu6qYbF7dovnlhsn6Ph1Vo"
----> 2 embed_model = NomicEmbedding(
      3     api_key=nomic_api_key,
      4     model_name="nomic-embed-text-v1",
      5     query_task_type="search_query",

1 frames
/usr/local/lib/python3.10/dist-packages/llama_index/embeddings/nomic.py in __init__(self, model_name, embed_batch_size, api_key, callback_manager, query_task_type, document_task_type, **kwargs)
     57         if api_key is not None:
     58             nomic.cli.login(api_key)
---> 59         super().__init__(
     60             embed_batch_size=embed_batch_size,
     61             callback_manager=callback_manager,

/usr/local/lib/python3.10/dist-packages/pydantic/main.cpython-310-x86_64-linux-gnu.so in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for NomicEmbedding
model_name
  field required (type=value_error.missing)
```

**Comment by logan-markewich** [comment]
Merged! Thanks @YasmineMh 💪🏻
