### ISSUE TITLE
[Question]: Find top-K nodes with a given node

### ISSUE THREAD

**Issue by MikeChu-GitHub** [run-llama/llama_index#10456]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I build an index and have it persisted in local disk. I'm able to see the embeddings in default_vector_store.json. How do I find top-K nodes with a specific node? I know I can find top-K nodes with a query. However, is it possible to achieve this with a node id instead of a query?

**Comment by ravi03071991** [comment]
@MikeChu-GitHub You can probably get text with the help of node id and use that text as query in your retriever.

**Comment by MikeChu-GitHub** [comment]
Yeah, but it will require the node content to be embedded. I'm trying to avoid this(and the fee) since this is already available in the index.

**Comment by ravi03071991** [comment]
You could probably use [get_top_k_embeddings](https://github.com/run-llama/llama_index/blob/fbf9b01fdd8dc02286680f63b8d7dc42d88cd5ed/llama_index/indices/query/embedding_utils.py#L12) function by passing the node embedding as query embedding and embedding ids as nodes ids and accordingly use it.
