### ISSUE TITLE
[Question]: How to use LLMQuestionGenerator to generate Sub-Question only (Using Zephyr-7b-beta)

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10468]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Reading the source code from `llm_generators.py` . It seems like the` SubQuestionQueryEngine` generates the sub-questions and answers together. 

Is there another function or any modifications I can make to just get the sub-questions only? The answers are not important in the meanwhile

```  
def generate(
        self, tools: Sequence[ToolMetadata], query: QueryBundle
    ) -> List[SubQuestion]:
        tools_str = build_tools_text(tools)
        query_str = query.query_str
        prediction = self._llm_predictor.predict(
            prompt=self._prompt,
            tools_str=tools_str,
            query_str=query_str,
        )

        assert self._prompt.output_parser is not None
        parse = self._prompt.output_parser.parse(prediction)
        parse = cast(StructuredOutput, parse)
        return parse.parsed_output
```

**Comment by logan-markewich** [comment]
@GxTeo if you only need the questions, you can import and use the llm question generator class directly

**Comment by erlebach** [comment]
@logan-markewich Does llm_question_generator work with Settings? Or must we use service_context? Thanks.
