### ISSUE TITLE
[Bug]: Cannot delete document from index over OpenSearch

### ISSUE THREAD

**Issue by wdeaderick** [run-llama/llama_index#10464]
### Bug Description

I cannot seem to call `index.delete_ref_doc()` on a VectorStoreIndex that I've build over a local OpenSearch index. Everything with the code below in "steps to reproduce" works fine up until the last line which throws me a `NotFoundError(404, '{"_index":"error_demo","_id":"docid1","_version":1,"result":"not_found","_shards":{"total":2,"successful":1,"failed":0},"_seq_no":4,"_primary_term":1}')` error.

### Version

0.9.44

### Steps to Reproduce

```
# Service and storage
text_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=16)
service_context = ServiceContext.from_defaults(
    embed_model=BGESmallEnEmbeddings(embed_batch_size=2),
    text_splitter=text_splitter,
    llm=Llama2LLM(),
)
client = OpensearchVectorClient(
    "http://0.0.0.0:9200", "error_demo", 384,
)
vector_store = OpensearchVectorStore(client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

# Documents
documents = [Document(text="first doc text", id_='docid1'), Document(text="second doc text", id_='docid2')]

index = VectorStoreIndex.from_documents(
    documents, service_context=service_context, storage_context=storage_context
)

# Try to delete
index.delete_ref_doc('docid1', delete_from_docstore=True)
```

**Comment by wdeaderick** [comment]
I have no idea how to do this, but I appreciate the quick response and if this becomes a high pri issue for me and I get bandwidth then I'll work on a PR!

**Comment by wdeaderick** [comment]
@logan-markewich same seems to be true with `index.update_ref_doc()`; can you confirm?

**Comment by logan-markewich** [comment]
@wdeaderick yeaaaa that function also calls delete() under the hood 😅

**Comment by wdeaderick** [comment]
@logan-markewich the following implementation worked for me:
```
def delete_doc_id(self, doc_id: str) -> None:
        """Delete a document.

        Args:
            doc_id (str): document id
        """
        body = {
            "query": {
                "match": {
                'metadata.ref_doc_id': doc_id
                }
            }
        }
        self._os_client.delete_by_query(index=self._index, body=body)
```
There seem to be 3 identical fields in the OpenSearch document object (`metadata.document_id`, `metadata.doc_id`, and `metadata.ref_doc_id`), so I chose `metadata.ref_doc_id` somewhat arbitrarily to match against the argument `doc_id (str): document id`.

Not sure what else needs to happen in this function (error handling, state updates, etc.) but I believe this is the crux of the implementation.

**Comment by logan-markewich** [comment]
Cool! I can probably add this to a PR then if it works for you

**Comment by wdeaderick** [comment]
That'd be great; thanks!

**Comment by wdeaderick** [comment]
@logan-markewich https://github.com/run-llama/llama_index/pull/11292
