### ISSUE TITLE
[Documentation]: KnowledgeGraphIndex docs is missing docs about parent class BaseIndex[KG]

### ISSUE THREAD

**Issue by louisguitton** [run-llama/llama_index#10474]
## Findings
- by searching the API docs, I find the docs for `KnowledgeGraphIndex` are  https://docs.llamaindex.ai/en/stable/api_reference/indices/kg.html#llama_index.indices.knowledge_graph.KnowledgeGraphIndex
- by reading the source code, I realise those docs are generated by the `automodule` in the `.rst` file at `docs/api_reference/indices/kg.rst`
- by following tutorials, I realise that multiple methods are missing from the API docs, like `.as_query_engine()`
- by reading the source code, I realise those methods come from the parent class `BaseIndex[KG]`

## Issue
The parent class' methods seem to not be added in the current docs setup with the `automodule` in the `.rst` files.
Yet some of those methods are very useful to understand the `llama_index` API and its usage.

## Example
For example, `KnowledgeGraphIndex.as_query_engine()` takes `**kwargs` and the current docs don't help with knowing that you could pass any of those:
- `retriever_mode`
- all kwargs from `KGTableRetriever` class
- all kwargs from `RetrieverQueryEngine` class

I'm happy to help resolving this issue with some guidance.

### Documentation Link

https://docs.llamaindex.ai/en/stable/api_reference/indices/kg.html#llama_index.indices.knowledge_graph.KnowledgeGraphIndex

**Comment by logan-markewich** [comment]
yea good point. In general, we have a large revamp of our documentation in the pipeline (especially API docs)

**Comment by louisguitton** [comment]
Yes, this issue is still relevant.

After the docs revamp, this is the status:
- the mentioned docs have moved to https://docs.llamaindex.ai/en/stable/api_reference/indices/knowledge_graph/ ✅ 
- it has a clear mention and link to [BaseIndex[KG]](https://docs.llamaindex.ai/en/stable/api_reference/indices/#llama_index.core.indices.base.BaseIndex) ✅ 
- not all base methods are documented in BaseIndex, and in particular the mentioned `as_query_engine` is missing 🔴

**Comment by logan-markewich** [comment]
For what it's worth, there really isn't much to document either as_query_engine 😅

Feel free to make a PR to update the api reference though
