### ISSUE TITLE
[Bug]: code execution vulnerability

### ISSUE THREAD

**Issue by rook1337** [run-llama/llama_index#10487]
### Bug Description

please check here https://huntr.com/bounties/d9664c41-fdd7-4d61-8e4f-c972ca68d142

### Version

latest version

### Steps to Reproduce

Check huntr.dev

**Comment by logan-markewich** [comment]
"This page is not public"

I'm guessing this is about sql or pandas query engine? There's already a ticket for it

**Comment by rook1337** [comment]
Hello team,
Its not about SQL or pandas query. Its different and it cannot be made public, you should have maintainer access on huntr.dev to access it

**Comment by rook1337** [comment]
hello @logan-markewich 
Any updates on this?

**Comment by logan-markewich** [comment]
I have not had time to even think about this. I get to it at some point. We are well aware your team has reported both known issues and other benign issues. 

Hot take, but it's an open source repo, highly recommend making a PR to solve issues as well :)
