### ISSUE TITLE
[Bug]:  How to chain multiple QueryEngines

### ISSUE THREAD

**Issue by Dyke-F** [run-llama/llama_index#10480]
### Bug Description

I need to run a complex query that requires decompositon (SubquestionQueryEngine works nicely) but also get the output with references. CitationQueryEngine works nicely as well.
however, how can i chain the output from SubquestionQueryEngine -> CitationQueryEngine as CitationQueryEngine requires a retriever as input.

My code looks like this:

    query_engine = SubQuestionQueryEngine.from_defaults(
        query_engine_tools=query_engine_tools,
        response_synthesizer=response_synthesizer,
        service_context=ServiceContext.from_defaults(llm=OpenAI(model="gpt-4-0125-preview")),
        use_async=True,
        verbose=True,
    )

    query_engine = CitationQueryEngine(
        retriever=query_engine,
        response_synthesizer=response_synthesizer,
        citation_chunk_size=citation_chunk_size,
        metadata_mode=MetadataMode.NONE,
    )

but of course this breaks on line retriever=query_engine. 

Could not find a solution in the source code, thank you

### Version

0.9.43

### Steps to Reproduce

see above

### Relevant Logs/Tracbacks

```shell
NotImplementedError: This query engine does not support retrieve, use query directly
```

**Comment by logan-markewich** [comment]
@Dyke-F chaining these two in particular is a little difficult

You might want to either create a custom query pipeline or custom query engine
https://docs.llamaindex.ai/en/stable/examples/query_engine/custom_query_engine.html
https://docs.llamaindex.ai/en/stable/module_guides/querying/pipeline/root.html
