### ISSUE TITLE
[Question]: Difference between `VectorStoreQueryMode.HYBRID` & `VectorStoreQueryMode.SEMANTIC_HYBRID`?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#10481]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the difference between `VectorStoreQueryMode.HYBRID` and `VectorStoreQueryMode.SEMANTIC_HYBRID`?  

Does `HYBRID` not using embeddings as the absence of "semantic" implies?  

If they are equivalent, then this just creates unnecessary confusion.

Relevant code: [VectorStoreQueryMode](https://github.com/run-llama/llama_index/blob/9c103a4b39d77e6febc208086847431973c9fe32/llama_index/vector_stores/types.py#L44)

**Comment by logan-markewich** [comment]
@brycecf looks like it was added specifically for `CognitiveSearchVectorStore` -- which tbh, I kind of disagree with. We can probably rename it.

But in any case, just use `HYRBID` (if the vector store supports hybrid)
https://docs.llamaindex.ai/en/stable/module_guides/storing/vector_stores.html#vector-store-options-feature-support

**Comment by PastryDoll** [comment]
@logan-markewich Hi. I was having the same question. I ran some tests and saw that on Openasearch, both DEFAULT and SEMATINC_HYBRID give same results. This made me question if the DEFAULT was using some kind of HYBRID search (that would also open the question, using which search pipeline?), or SEMANTIC_HYBRID was falling back to DEFAULT which I would assume is just good old Vector Search. Is this the right way to think ? 

1) Semantic hybrid is just a poorly chosen name for connecting to AZURE
2) Default is not hybrid search
3) If I want hybrid search I should use HYBRID and follow https://docs.llamaindex.ai/en/stable/examples/vector_stores/OpensearchDemo/ with a search pipeline.

Thank you
