### ISSUE TITLE
TypeError: Object of type datetime is not JSON serializable 

### ISSUE THREAD

**Issue by VaradDeshmukh97** [run-llama/llama_index#10494]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am building an RAG application using LlamaIndex. I am using NewsArticleReader, WholesiteReader, and SimpleWebPageReader data loaders from LlamaHub. When I run the ingestion pipeline on the documents and try to store the embeddings into the VectorStoreIndex, it gives me a TypeError saying that objects of type datetime are not JSON serializable. How do I go about solving that?

**Comment by VaradDeshmukh97** [comment]
I am web-scraping data from the internet. I am not aware of where the actual datetime objects are located to convert them before storing them. Please suggest a general approach to resolve this issue, maybe something I can put at the top of my file to get any future data working with it, too.

Here is the actual code that I have written:
--------------------------------------
news_articles = [
    r'https://www.indiatvnews.com/technology/news/meta-collaborates-with-ncmec-to-extend-take-it-down-program-for-teenagers-2024-02-07-915677'
]

reader = NewsArticleReader(use_nlp=False)

news = reader.load_data(
    news_articles
)
-------------------------------------

WholeSiteReader = download_loader('WholeSiteReader')

prefix = r'https://about.fb.com'
base_url = r'https://about.fb.com/news'
max_depth = 1

scraper = WholeSiteReader(
    prefix=prefix,
    max_depth=max_depth
)

websites = scraper.load_data(
    base_url=base_url
)
------------------------------------------------------

SimpleWebPageReader = download_loader('SimpleWebPageReader')

urls = [
    r'https://www.sec.gov/Archives/edgar/data/1326801/000132680124000012/meta-20231231.htm'
]
loader = SimpleWebPageReader()
htmls = loader.load_data(
    urls=urls
)
-----------------------------------------------------------------
documents = news + websites + htmls
----------------------------------------------------------------

splitter = SemanticSplitterNodeParser(
    buffer_size=1,
    breakpoint_percentile_threshold=95,
    embed_model=embed_model
)
-----------------------------------------------------------------
embedding = HuggingFaceEmbedding(embed_model_name)

pipeline = IngestionPipeline(
    transformations=[splitter, embedding]
)
--------------------------------------------------------------------
nodes = pipeline.run(
    documents=documents,
    in_place=False,
    show_progress=True
)
--------------------------------------------------------------------
index = VectorStoreIndex(nodes)
---------------------------------------------------------------------

This is where I am getting the error:
`TypeError: Object of type datetime is not JSON serializable`

**Comment by VaradDeshmukh97** [comment]
@dosu-bot

Here is the context that you required.
I am web-scraping data from the internet. I am not aware of where the actual datetime objects are located to convert them before storing them. Please suggest a general approach to resolve this issue, maybe something I can put at the top of my file to get any future data working with it, too.

Here is the actual code that I have written:
--------------------------------------
```
news_articles = [
    r'https://www.indiatvnews.com/technology/news/meta-collaborates-with-ncmec-to-extend-take-it-down-program-for-teenagers-2024-02-07-915677'
]

reader = NewsArticleReader(use_nlp=False)

news = reader.load_data(
    news_articles
)
```
-------------------------------------
```
WholeSiteReader = download_loader('WholeSiteReader')

prefix = r'https://about.fb.com'
base_url = r'https://about.fb.com/news'
max_depth = 1

scraper = WholeSiteReader(
    prefix=prefix,
    max_depth=max_depth
)

websites = scraper.load_data(
    base_url=base_url
)
```
------------------------------------------------------
```
SimpleWebPageReader = download_loader('SimpleWebPageReader')

urls = [
    r'https://www.sec.gov/Archives/edgar/data/1326801/000132680124000012/meta-20231231.htm'
]
loader = SimpleWebPageReader()
htmls = loader.load_data(
    urls=urls
)
```
-----------------------------------------------------------------
```
documents = news + websites + htmls
```
----------------------------------------------------------------
```
splitter = SemanticSplitterNodeParser(
    buffer_size=1,
    breakpoint_percentile_threshold=95,
    embed_model=embed_model
)
```
-----------------------------------------------------------------
```
embedding = HuggingFaceEmbedding(embed_model_name)

pipeline = IngestionPipeline(
    transformations=[splitter, embedding]
)
```
--------------------------------------------------------------------
```
nodes = pipeline.run(
    documents=documents,
    in_place=False,
    show_progress=True
)
```
--------------------------------------------------------------------
```
index = VectorStoreIndex(nodes)
```
---------------------------------------------------------------------

This is where I am getting the error:
`TypeError: Object of type datetime is not JSON serializable`

**Comment by logan-markewich** [comment]
@VaradDeshmukh97 it seems like some metadata in the loaded objects is a Datetime object

Just cast to string in your loaded documents

```
documents = <load docs>
for doc in documents:
  for key in doc.metadata.keys():
    doc.metadata[key] = str(doc.metadata[key])
```

The above is a bit naive -- you could inspect the metadata and only stringify the actual metadata field that has the datetime object

**Comment by VaradDeshmukh97** [comment]
@logan-markewich Thank you for the response. Actually I worked out the same logic yesterday night.
While going through the source code for `NewsArticleReader` from LlamaHub, I came to notice that one of the metadata keys in the metadata dictionary was `publish_date`, with the type `datetime`. This was the culprit in not allowing the JSON serialization while storing the embeddings in the `VectorStoreIndex`.
What I did is as follows:
```
# change 'publish_date' metadata to string for JSON serialization
for i in range(len(news)):
    news[i].metadata['publish_date'] = str(news[i].metadata['publish_date'])
```
This worked for me.
