### ISSUE TITLE
[Feature Request]: Don't force aggregation of embedding strings

### ISSUE THREAD

**Issue by JohnCHarrington** [run-llama/llama_index#10497]
### Feature Description

Currently if I define multiple embedding strings (using query transforms or similar), their embeddings are aggregated. Instead of this I would like the option to keep them separate and query for multiple embeddings at one time.

I have done this locally by overwriting some methods in the retriever, then added support for it to my vector store so that it queries for both and returns the combined node list from both queries.

### Reason

It can be done with some custom classes reasonably easily, but would be nicer if support was built-in.

### Value of Feature

It gives the user control over how the results of things like query transforms are used. Currently if you use e.g. HyDEQueryTransform your options are to either use just the HyDE embedding or a mean of the HyDE and the original query. This would give users the option of querying with both instead.

**Comment by logan-markewich** [comment]
In general, this is more related to supporting batch queries I think?

What is the expected way this should work from your view? Multiple embeddings means multiple retrievals. Does all this context get combined and an answer synthesized? Does each retrieval step map to its own synthesis step?

**Comment by JohnCHarrington** [comment]
So in my current set up it is multiple retrievals (retrieve top 20 matches for the query plus top 20 matches for the HyDE transformation and just concatenate those lists), followed by a combined llm reranking and synthesis.

I have actually today adjusted the multiple retrievals so that it only accesses the (SQL) database once and does a union of the relevant queries on the database side, which speeds things up.

**Comment by JohnCHarrington** [comment]
@dosu-bot I have considered a PR, but I think there is a lot more work as I have specifically implemented this for one vector store. Happy to contribute the code as a starting point if anyone is interested in the feature.
