### ISSUE TITLE
[Bug]: PandaQueryEngine response

### ISSUE THREAD

**Issue by bogdanalexandrutreica** [run-llama/llama_index#10498]
### Bug Description

When I use panda query engine to ask a question from a df using Claude (tested only with Bedrock Claude)

I get the right command from the LLM but has additional text like:

-Here is the Python code to filter the dataframe
-```python

A simple solution that i use locally is to add a regex to filter only the df command like this:

in panda_query_engine.py on line 152
pandas_response_str = re.search(r'df.*.?\]', pandas_response_str).group(0)

I am not sure if this is the best solution but this worked for me

### Version

0.9.38

### Steps to Reproduce

Bedrock Claude v1.3/v2

panda query engine

### Relevant Logs/Tracbacks

```shell
Q:["show incidents numbers with no 'Additional comments'"]
> Pandas Instructions:

 Here is the Python code to filter the dataframe to show only incident numbers with no 'Additional comments':

df[df['Additional comments'].isna()]['Number']
```
Traceback (most recent call last):
  File "/home/bugdan/.local/lib/python3.10/site-packages/llama_index/query_engine/pandas/output_parser.py", line 44, in default_output_processor
    tree = ast.parse(output)
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    Here is the Python code to filter the dataframe to show only incident numbers with no 'Additional comments':
                ^^^^^^
SyntaxError: invalid syntax
> Pandas Output: There was an error running the output as Python code. Error message: invalid syntax (<unknown>, line 1)
```

**Comment by hatianzhang** [comment]
https://github.com/run-llama/llama_index/pull/10499 here is the fix
