### ISSUE TITLE
[Feature Request]: adding AzureOpenAI option for controllable RAG agent 

### ISSUE THREAD

**Issue by pgaods** [run-llama/llama_index#10509]
### Feature Description

https://docs.llamaindex.ai/en/stable/examples/agent/agent_runner/agent_runner_rag.html

For this tutorial "Controllable Agents for RAG", can we request that llama-index add the functionality of allowing Azure OpenAI? Currently I think the step module only allows for direct OpenAI access:

![Capture](https://github.com/run-llama/llama_index/assets/89472913/9ed90c64-2304-4f02-9112-b54abd1c40ad)

### Value of Feature

This will make many codes applicable for people in corporate rather than academic research because many corporate folks tend to use Azure OpenAI

**Comment by logan-markewich** [comment]
@pgaods you can definitely use azure

There is some minor setup here for the LLM and embed model
https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html

**Comment by pgaods** [comment]
@logan-markewich  thank you for getting back so quickly. I am aware that we can connect azure openai to llamaindex. But for this particular case, it's a bit more complicated (because in the source code of step.py, they are only using OpenAI
![MicrosoftTeams-image](https://github.com/run-llama/llama_index/assets/89472913/7b42b649-10ae-4f17-9560-61570593b0a8)

**Comment by pgaods** [comment]
@logan-markewich  thank you so much for getting back to us so quickly.  I see that azure openai can be integrated with llamaindex but for this package it's a bit more complicated. The step.py file in the source code doesn't really import anything from azureopenai. So we cannot just use the azureopenai() api as an LLM call
![MicrosoftTeams-image](https://github.com/run-llama/llama_index/assets/89472913/d1827999-6f9a-4ed2-ae72-9f961d014d08)

**Comment by logan-markewich** [comment]
@pgaods it's not clear from the screemshot, but you used `from llama_index.llms import AzureOpenAI` ?

The AzureOpenAI class extends the OpenAI class, so any isinstance checks should be passing 👀

**Comment by pgaods** [comment]
@logan-markewich  i figured it out. But to answer your question, yes I did use `from llama_index.llms import AzureOpenAI`. The way I fixed it is to set the service_context as global. I think we can close this ticket.
