### ISSUE TITLE
[Question]: An error occurred: 'list' object has no attribute 'as_query_engine'

### ISSUE THREAD

**Issue by asiri77** [run-llama/llama_index#10502]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

storage_context = StorageContext.from_defaults(persist_dir="<persist_dir>")
loaded_indicies = load_indices_from_storage(storage_context , index_ids = [ "<index_id_doc>" , "<index_id_web>" ])

chat_engine = loaded_indicies.as_chat_engine(chat_mode="react", verbose=True , similarity_top_k=3 , streaming=True )

i got error = An error occurred: 'list' object has no attribute 'as_query_engine'
could not solve this issues

**Comment by logan-markewich** [comment]
Right ` load_indices_from_storage` returns a list of indexes.

Pick one from the list before using it.

If you only want to load one index

`index = load_index_from_storage(storage_context, index_id="index_id")`

**Comment by asiri77** [comment]
Thank you @logan-markewich 
is there any way to use all in index ("<index_id_doc>" , "<index_id_web>") for the chat_engine??
