### ISSUE TITLE
[Question]: Mistral 7B took a long time to finish the refinement process

### ISSUE THREAD

**Issue by jc1518** [run-llama/llama_index#10512]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am wondering if everyone experienced the same, I noticed that Mistral 7B usually took a long time to finish the answer refinement process (response mode: refine and compact). It is normally quicker with tree_summarize and simple_summarize.

**Comment by logan-markewich** [comment]
@jc1518 if you are running locally, and don't have a GPU, it will be quite slow.

If you do have a GPU, I recommend running through something like vLLM or TGI

**Comment by logan-markewich** [comment]
@jc1518 I think thats more of a model hosting issue, not llama-index?

Is the model quantized? 

LlamaIndex will send a (nearly full) context window each time. Depending on the chunk size and topk, this can also mean multiple LLM calls

The main bottleneck is the response speed from the LLM when the context window is full

**Comment by jc1518** [comment]
> @jc1518 I think thats more of a model hosting issue, not llama-index?
> 
> Is the model quantized?
> 
> LlamaIndex will send a (nearly full) context window each time. Depending on the chunk size and topk, this can also mean multiple LLM calls
> 
> The main bottleneck is the response speed from the LLM when the context window is full

Yeah, absolutely it is not caused by llama-index. I was wondering how to tackle it. Besides upsizing the EC2 instance, does any prompting optimisation we can potentially do?
