### ISSUE TITLE
[Feature Request]: Add field for document name in LabelledRagDataset

### ISSUE THREAD

**Issue by jannenev** [run-llama/llama_index#10518]
### Feature Description

Add info about document to LabelledRagDataset - from which document was each question created from.

Having an attribute `.metadata` would also allow users to add their own extra info as dictionary keys. 

There is implementation in Ragas
```
for document in documents:
    document.metadata['file_name'] = document.metadata['source']
```

https://docs.ragas.io/en/stable/getstarted/testset_generation.html#get-started-testset-generation

RagDatasetGenerator could possibly add this info when creating questions.

### Value of Feature

Knowing the source dokument for questions allows to get more detailed info, such as metrics and failed questions for individual document.  And finding the documents with lowest score.

**Comment by austinmw** [comment]
Hi, also some evaluation utilities still use `EmbeddingQAFinetuneDataset` instead of `LabelledRagDataset`, but the former cannot be created from the latter, because `LabelledRagDataset` does not retain any information about nodes once created.
