### ISSUE TITLE
[Bug]: Streaming Response is not working when used with FastAPI (even with websockets)

### ISSUE THREAD

**Issue by surya-ven** [run-llama/llama_index#10517]
### Bug Description

I've not been able to get streaming response generation to work properly with StreamingResponse in FastAPI. 

The bug is weird in that, when I print the chunk of text within the query method below, I can see that it outputs text successively in the terminal - so it doesn't seem to be an issue with the response_gen / iterator, rather, it seems to be a problem with the StreamingResponse of FastAPI not playing well with using the llama-index response_gen iterator.

I'm using ChromaDB as a vector store. I've also tried using a simple POST REST API example without the use of websockets. Print_response_stream works as expected. I've tried outputting the chunks to the command line through using curl, by printing to the command line using a python script (httpx/asyncio), and also a simple index.html containing a script to output the chunks to a paragraph tag in case there was a problem with my command line configuration. Neither of these worked.

The text is always being printed at the very end, all at once (even if I print it on a new line).

### Version

0.9.45.post1

### Steps to Reproduce

**Functions which produce the streaming output** 

Everything is setup/initialised prior to this print_response_stream() works as expected within the query method and I've also printed the output of each chunk within the iterator and each chunk is correctly printed successively. The problem therefore is likely in the FastAPI route.

Query method
```python
def query(self, query_text):
        # Query the index
        streaming_response = self.query_engine.query(query_text)
        return streaming_response.response_gen
``` 

FastAPI route
```python
@self.app.websocket("/ws/query")
        async def websocket_query(websocket: WebSocket):
            await self.connection_manager.connect(websocket)
            try:
                while True:
                    query_text = await websocket.receive_text()
                    streaming_response_gen = self.drive.query(query_text) # Your query engine here
                    for response in streaming_response_gen: # Assuming this is iterable
                        await self.connection_manager.send_personal_message(response, websocket)
            except WebSocketDisconnect:
                self.connection_manager.disconnect(websocket)
            except Exception as e:
                # Handle exceptions
                self.connection_manager.disconnect(websocket)
                print(f"Error: {str(e)}")
``` 

### Relevant Logs/Tracbacks

```shell
Note that the 200 OK response is only received at the end of the text generation.

INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     ('127.0.0.1', 56750) - "WebSocket /ws/query" [accepted]
INFO:     connection open
2024-02-08 16:35:36 - HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
HTTP Request: POST http://localhost:11434/api/chat "HTTP/1.1 200 OK"
```

**Comment by Pjamas180** [comment]
@dosu-bot it doesn't seem like --no-send is an option when running uvicorn from the code itself with uvicorn.run

**Comment by theoratkin** [comment]
I can confirm this, I experience this issue when using an async `StreamingResponse`. Switching it to synchronous makes streaming work as expected.

**Comment by surya-ven** [comment]
> I can confirm this, I experience this issue when using an async `StreamingResponse`. Switching it to synchronous makes streaming work as expected.

Great, thanks for pointing this out, at least there's a temp workaround. Still can't get this to work with websockets however.

**Comment by Tsovak** [comment]
it is just not working without FastAPI dependency

```
chain = index.as_query_engine(
            chat_mode=ChatMode.BEST,
            memory=memory,
            streaming=True,
            vector_store_query_mode=VectorStoreQueryMode.DEFAULT,
            similarity_top_k=1,
            text_qa_template=text_qa_template,
            refine_template=refine_template,
        )
        
            streaming_response = chain.query(user_input)
            for chunk in streaming_response.response_gen:
                yield f"{chunk}"
```

so response_gen sometimes returns an empty response. but blocking response is working well

**Comment by qkxie** [comment]
Check if you use GzipMiddleware. If so, the streamingRespone will not work

**Comment by PrestonBlackburn** [comment]
I was having issues streaming responses using FastAPI websockets + LlamaIndex as well. I was able to get it working by mocking some of the StreamResponse functionality and finding a few issues with my async functions.

The response generator should just be a generator so you can mock the functionality of the StreamingResponse by doing something similar below. That way, you can test the generator part without needing to call other parts of LlamaIndex, and you can isolate any issues:
 
```python
TokenGen = Generator[str, None, None]

@dataclass
class StreamingResponse:
    response_gen: TokenGen
    source_nodes: List = field(default_factory=list)
    metadata: Optional[Dict[str, Any]] = None
    response_txt: Optional[str] = None

def mock_stream() -> Generator:
    response = "Hello there! How can I assist you today?" * int(100)
    for word in response.split():
        yield word + " "

def rag_response_mock_generator(user_message:str) -> StreamingResponse:
    """
        This function is a mock of the llamaindex chat function
        It will return a mock stream of responses from the vdb.
    """
    stream_resp = StreamingResponse(
        response_gen=mock_stream(),
        source_nodes=[],
        metadata = {},
        response_txt="streaming response mock"
    )

    return stream_resp

```

To further isolate any issues, you can split out the query by using something like the base OpenAI API endpoint as well-
```python

from openai import OpenAI
client = OpenAI()

def mock_open_ai_response_generator(user_message:str)-> Generator:

    stream_resp = StreamingResponse(
        response_gen=client.chat.completions.create(
    model='gpt-3.5-turbo',
    messages=[
        {'role': 'user', 'content': user_message}
    ],
    temperature=0,
    stream=True
    ),
        source_nodes=[],
        metadata = {},
        response_txt="streaming response mock"
    )

    return stream_resp
```

Also, if the use_async option in the `index.as_query_engine` function is set to True, it will return an AsyncGenerator instead, so you'd need to mock that instead.

**Comment by Taiinguyenn139** [comment]
Hi @qkxie , can you explain why gzipmiddleware block Streaming please ???

**Comment by qkxie** [comment]
> Hi [@qkxie](https://github.com/qkxie) , can you explain why gzipmiddleware block Streaming please ???

Because it will have a buffer, the stream strings will be stored in the buffer to a limit size, then the gzip will compress the buffer and return to browser. gzip can not work on a single char or a single word. so it must have a buffer.

**Comment by Taiinguyenn139** [comment]
Thank you so much @qkxie
