### ISSUE TITLE
[Question]: How to remove "Based on the given context" from the final answer

### ISSUE THREAD

**Issue by jc1518** [run-llama/llama_index#10511]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I have been using llama-index with **Claude v2**. I am wondering if there is a way (e.g better prompting) to avoid those statements like below. I understand those are from the underlying refinement process. I am wondering if everyone found a solution to that? I tried multiple prompts which did not work well. Thanks. Hi @logan-markewich @ravi-theja , can you please share some insights? Thanks!

`Based on the given context, ...`
`Based on the additional context provided, I do not see any information that requires updating the existing answer...`

Here are my prompts:
```
# Prompts
qa_prompt = (
    "You are a Q&A assistant, "
    "you are responsible for answering the query with given context. "
    "Context information is below.\n"
    "--------------------\n"
    "{context_str}\n"
    "--------------------\n"
    "Given the context information not prior knowledge, "
    "answer the query in a concise and clear way. "
    "If the answer is not in the context, return 'I don't know'. \n"
    "Query: {query_str}\n"
    "Answer: "
)

refine_prompt = (
    "The original query is as following: "
    "{query_str}\n"
    "We have provided an existing answer: "
    "{existing_answer}\n"
    "We have the opportunity to refine "
    "the existing answer with some more context below.\n"
    "--------------------\n"
    "{context_msg}\n"
    "--------------------\n"
    "Given the context information not prior knowledge, "
    "update the existing answer only if necessary.\n"
)
```

**Comment by logan-markewich** [comment]
@jc1518 Try updating the default RAG prompts
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts

**Comment by luxurystorecc1** [comment]
The Technical Renaissance: Material Science in 2026 Apparel
Introduction: The Engineering of Aesthetics
We are currently witnessing a technical renaissance where the material science of a garment is as important as its silhouette. In 2026, the elite consumer expects a synergy between structural integrity and aesthetic prestige. This movement is perfectly captured by the [Air Jordan 1 retro high OG sneakers](https://www.airjordan-1.com/), which have remained culturally dominant through constant material innovation.

Engineering Performance Footwear
Modern footwear is now a multi-billion dollar laboratory for material science. The [Jordan 1s high-performance basketball shoes](https://www.jordan1s.com/) provide the structural blueprint that all high-top designs aspire to follow. For a more versatile everyday look, the [classic Jordan 1 mid-top sneaker](https://www.jordan1s.com/) offers a perfect balance of heritage and technical comfort.

Minimalism and propulsion are the focus of the [adidas Yeezy boost collection](https://www.yeezyboost-350.com/collections/adidas-yeezy). By utilizing proprietary cushioning technologies, these sneakers provide a lightweight experience that has redefined the meaning of modern luxury. This design philosophy is extended to [premium Yeezy slides and foam runners](https://www.yeezyboost-350.com/), which have become essential for recovery and high-end leisure.

Cultural Connectivity through Team Gear
Sports gear has become a way to display your heritage on a global stage. The [official NFL shop online store](https://www.nflshopofficialonline-store.com/) is the definitive source for authentic gear that reflects professional standards. The rise of the [customized replica NFL jersey](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) demonstrates the desire for personal agency within a team environment.

This passion for sports crosses all borders, as seen in the global demand for the [Spain national team soccer jersey](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain). From high-tech [MLS jerseys for soccer fans](https://www.soccerjerseysstore.com/collections/national-teams) to the ubiquitous [NFL headwear and baseball caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear), sports apparel has become the new global uniform.

Performance Luxury: The Peter Millar Standard
For those who participate in elite social circles, [Peter Millar performance golf apparel](https://www.peter-milla.com/) offers an unmatched level of sophistication. These garments are designed to perform at the highest level while maintaining the aesthetic standards of the most exclusive clubs. The [Peter Millar clothing for men](https://www.peter-milla.com/) line continues to set the benchmark for modern professional success.
