### ISSUE TITLE
[Bug]: Azure AI search UnkownVectorAlgorithmConfiguration

### ISSUE THREAD

**Issue by darrenwwx** [run-llama/llama_index#10522]
### Bug Description

Azure Ai search llama index set up embedding_field_key error.
![Screenshot 2024-02-08 210159](https://github.com/run-llama/llama_index/assets/101921663/3efa7121-58cd-4fbf-b8c8-9f9aa4ff7d07)
![image](https://github.com/run-llama/llama_index/assets/101921663/6457f96c-ca13-46ac-8312-0f574e8f7e3b)

https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo.html

followed this link to setup but issue persisted.

### Version

(0.9.45.post1)

### Steps to Reproduce

NIL

**Comment by darrenwwx** [comment]
@dosu-bot I get this error when i use the AzureAISearchVectorStore Function:HttpResponseError: (InvalidRequestParameter) The request is invalid. Details: definition : The field 'embedding' uses a vector search algorithm configuration '' which is not defined.
Code: InvalidRequestParameter
Message: The request is invalid. Details: definition : The field 'embedding' uses a vector search algorithm configuration '' which is not defined.
Exception Details:	(UnknownVectorAlgorithmConfiguration) The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Parameters: definition
	Code: UnknownVectorAlgorithmConfiguration
	Message: The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Parameters: definition

**Comment by ryanrib14** [comment]
> @dosu-bot I get this error when i use the AzureAISearchVectorStore Function:HttpResponseError: (InvalidRequestParameter) The request is invalid. Details: definition : The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Code: InvalidRequestParameter Message: The request is invalid. Details: definition : The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Exception Details: (UnknownVectorAlgorithmConfiguration) The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Parameters: definition Code: UnknownVectorAlgorithmConfiguration Message: The field 'embedding' uses a vector search algorithm configuration '' which is not defined. Parameters: definition

some updates about this issue? i had the same error...

**Comment by Gianlucq** [comment]
Update to the last version 0.9.46.

**Comment by darrenwwx** [comment]
still facing the same issue after updating to 0.9.46

**Comment by Gianlucq** [comment]
Ok, let me check on my notebook. What version of azure-search-documents package are you using? In my previous version I was using llama-index=0.9.39 and azure-search-documents==11.4.0b8 (pre-release). Let me do some tests with new one of llama-index and back to you! Regards

**Comment by darrenwwx** [comment]
@Gianlucq I am using azure-search-documents 11.4.0 . Cheers!

**Comment by NikhilKosare** [comment]
I am getting the same error. below are the versions of installed llama index and azure-search-documents
Name: azure-search-documents
Version: 11.4.0 and
 Name: llama-index
Version: 0.9.46

**Comment by junminyang** [comment]
Had the same issue. Changed the source code in azuresearch.py in llama_index/vector_stores as below, around line 154:
SearchField(
                 name=self._field_mapping["embedding"],
                 type=SearchFieldDataType.Collection(SearchFieldDataType.Single),
                 searchable=True,
                 vector_search_dimensions=self.embedding_dimensionality,
                 vector_search_profile_name= "myHnswProfile", # changed from "default" to "myHnswProfile"
             ),

After this change, restart the jupyter notebook kernel and worked well.

**Comment by ryanrib14** [comment]
> Had the same issue. Changed the source code in azuresearch.py in llama_index/vector_stores as below, around line 154: SearchField( name=self._field_mapping["embedding"], type=SearchFieldDataType.Collection(SearchFieldDataType.Single), searchable=True, vector_search_dimensions=self.embedding_dimensionality, vector_search_profile_name= "myHnswProfile", # changed from "default" to "myHnswProfile" ),
> 
> After this change, restart the jupyter notebook kernel and worked well.

yes, i make the same, but can be a problem change the source code, agree?

**Comment by Gianlucq** [comment]
Changing the source code this way isn't correct. For each new version of the llama-index, it's essential to remember to update the corresponding source file.

**Comment by Shaanrs7** [comment]
I've been facing the same issue and had to modify source code to index my docs. Also @NikhilKosare you would have to use azure-search-documents v11.6.0b1 as vector search is only supported in the beta release of this package.

Thank you for opening the PR @ryanrib14. It seems like it has been approved, could you please merge it? Llamaindex for Azure AI search is broken in it's current version without your fix.

**Comment by ryanrib14** [comment]
> I've been facing the same issue and had to modify source code to index my docs. Also @NikhilKosare you would have to use azure-search-documents v11.6.0b1 as vector search is only supported in the beta release of this package.
> 
> Thank you for opening the PR @ryanrib14. It seems like it has been approved, could you please merge it? Llamaindex for Azure AI search is broken in it's current version without your fix.

@Shaanrs7 i don't have write acess to repository, so i can't merge the PR. In some next release the maintainers probably will merge it.

**Comment by ryanrib14** [comment]
> I've been facing the same issue and had to modify source code to index my docs. Also @NikhilKosare you would have to use azure-search-documents v11.6.0b1 as vector search is only supported in the beta release of this package.
> 
> Thank you for opening the PR @ryanrib14. It seems like it has been approved, could you please merge it? Llamaindex for Azure AI search is broken in it's current version without your fix.

Apparently they are releasing the new version 0.10.0 which is changing a lot of things, so it's probably a good idea to wait before working

**Comment by darrenwwx** [comment]
Does it work for everyone now ?

**Comment by NikhilKosare** [comment]
I have updated the libraries to below version :

Name: llama-index
Version: 0.10.3

Name: azure-search-documents
Version: 11.6.0b1

and now i am getting the below error:

cannot import name 'AzureAISearchVectorStore' from 'llama_index.vector_stores'

**Comment by ryanrib14** [comment]
> @ryanrib14 - I have updated the libraries to below version :
> 
> Name: llama-index Version: 0.10.3
> 
> Name: azure-search-documents Version: 11.6.0b1
> 
> and now i am getting the below error:
> 
> cannot import name 'AzureAISearchVectorStore' from 'llama_index.vector_stores'

use the stable version of azure-search-documents 11.4.0

and about llama_index.vector_stores, now the vector_stores is part of "integrations" so you have to install the package like this :
pip install llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch

see the information in blog post:https://blog.llamaindex.ai/llamaindex-v0-10-838e735948f8

**Comment by xcarlosamm** [comment]
To fix the issue, I had to change my imports
from
``
from llama_index.vector_stores import CognitiveSearchVectorStore
from llama_index.vector_stores.cogsearch import IndexManagement, MetadataIndexFieldType
``
to
``
from llama_index.vector_stores.azureaisearch import AzureAISearchVectorStore, IndexManagement
``
Also, I had to (re)install the following packages:
llama-index==0.10.4
azure-search-documents==11.4.0
llama-index-vector-stores-azureaisearch==0.1.2

I hope you find it useful.
