### ISSUE TITLE
[Question]: How do I dynamically choose how many nodes to retrieve during query time?

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#10521]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I will define a term for the sake of my question:

Query Relevance Ratio(QRR) = nodes relevant to query / total nodes in index

to simplify things further, let us assume that my index contains only one document so that:

QRR = nodes relevant to query / total nodes in document

If the QRR is high, it would imply that multiple (and in some cases, all) nodes must be retrieved, but only for that particular query. How do I deal with this assuming:
1. I knew ahead of time that most of my queries have a high QRR(maybe use a Summary index)
2. I did not know ahead of time?

For instance, if I have a document with n chunks/nodes, containing a catalogue of companies and my query is:
"Please list the names of the companies mentioned and their locations"

Given that most of the n nodes contain some information that should be present in the response like the company name and location, how would I get the best results?

**Comment by gich2009** [comment]
Thanks @dosubot. The problem with explicitly setting the similarity_top_k is that the index has n nodes where n is arbitrary. Is there a way for me to query the index for the total number of nodes and then set that as the similarity_top_k? 
Also, remember that the no. of nodes to retrieve are determined by the prompt. Some prompts may have high QRR and some may have low QRR. Setting similarity_top_k to a value will optimize for one of these cases and degrade perfomance for the other case.

**Comment by hatianzhang** [comment]
@gich2009 can you try to fetch all the nodes and check the score distribution of each node.
cut off low relevance node by score

**Comment by gich2009** [comment]
Thanks @hatianzhang, let me give it a shot.
Follow up question, is there a way to set the similarity_top_k to an arbitrarily large number like n? How would I do that?
