### ISSUE TITLE
[Bug]: TypeError: object HeadApiResponse can't be used in 'await' expression

### ISSUE THREAD

**Issue by Vybhav448** [run-llama/llama_index#10548]
### Bug Description

I was able to run Elastic search's server using cloud but getting this issue when trying to run locally.

TypeError: object HeadApiResponse can't be used in 'await' expression

Versions:
llama-index==0.9.46
elasticsearch==8.8.0

### Version

0.9.46

### Steps to Reproduce

Trying to create embeddings using VectorStoreIndex.from_documents method.

### Relevant Logs/Tracbacks

```shell
TypeError                                 Traceback (most recent call last)
<ipython-input-19-4b901dfb7bfa> in <cell line: 1>()----> 1 index = VectorStoreIndex.from_documents(      2     documents, storage_context=storage_context)

/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py in _create_index_if_not_exists(self, index_name, dims_length)    244             dims_length: Length of the embedding vectors.    245         """--> 246         if await self.client.indices.exists(index=index_name):    247             logger.debug(f"Index {index_name} already exists. Skipping creation.")    248 
TypeError: object HeadApiResponse can't be used in 'await' expression
```

**Comment by sreenivasanm6** [comment]
I am also facing similar issue and the same code is working when we try to connect with elasticsearch server running in cloud but problem arises only when we do locally. Let us know if there are any issues or provide a sample code snippet which runs locally with vectorstoreIndex

**Comment by logan-markewich** [comment]
Looks like await is being called on a function that doesn't actually need it

**Comment by mpieck** [comment]
This is not a bug, use async elasticsearch client in llama-index code:

$ pip install elasticsearch[async]

then in llama-index code:

from elasticsearch import AsyncElasticsearch

client = AsyncElasticsearch(
"https://localhost:9200/", )

vector_store = ElasticsearchStore(
index_name="your_index", es_client=client
)

**Comment by allanwakes** [comment]
> This is not a bug, use async elasticsearch client in llama-index code:
> 
> $ pip install elasticsearch[async]
> 
> then in llama-index code:
> 
> from elasticsearch import AsyncElasticsearch
> 
> client = AsyncElasticsearch( "https://localhost:9200/", )
> 
> vector_store = ElasticsearchStore( index_name="your_index", es_client=client )

I tried AsyncElasticsearch, but it didn't work, the error is below:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x713d2c17bf50>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x713d48703930>, 780618.084782238)])']
connector: <aiohttp.connector.TCPConnector object at 0x713d2c2785d0>
```


My env:
ES: 8.15.3
```
python = ">=3.11,<3.12"
llama-index-core = "^0.12.0"
llama-index-embeddings-huggingface = "^0.4.0"
llama-index-llms-ollama = "^0.4.0"
llama-index-readers-file = "^0.4.0"
llama-index-vector-stores-elasticsearch = "^0.4.0"
elasticsearch = {extras = ["async"], version = "^8.16.0"}
```

Does anyone actually make ElasticsearchStore work, please?
Thank you.
