### ISSUE TITLE
Issues with response generation 

### ISSUE THREAD

**Issue by VaradDeshmukh97** [run-llama/llama_index#10545]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using the Meta Llama2-7b model by 'TheBloke' locally in a RAG application. It worked all fine till yesterday, but suddenly since today morning the model is taking too long to respond. Especially with larger prompts, it takes too much of time. It keeps repeatedly printing : 'Llama.generate: prefix-match hit'.
I tried running it for like 30min+, still it did not generate a response. Till yesterday the prompts were fine and they were generating responses in around 6-7 minutes. But suddenly it broke down. I have not made any changes to the code. All things work fine except the response generation. If I ask the model to tell me a joke based on the source documents, it does that pretty well! But not with the actual questions that I have on the data. Can somebody figure this out?

**Comment by VaradDeshmukh97** [comment]
Seems like the model responds only to the first prompt after I setup the VectorIndex and other things. For subsequent queries, it just breaks down.

**Comment by logan-markewich** [comment]
I'm not sure, llamacpp is a fickle beast. My suggestion is switching to ollama

**Comment by VaradDeshmukh97** [comment]
Hey @logan-markewich ! Thank you for your suggestion. Since I am using Windows, I'll need to configure WSL first for using Ollama. I'll try that. Till then, closing the issue!
