### ISSUE TITLE
Multimodal Retriever is not retrieving right documents with OPENclip embedding models.

### ISSUE THREAD

**Issue by NeethanShetty07** [run-llama/llama_index#10546]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

https://docs.llamaindex.ai/en/stable/examples/multi_modal/ChromaMultiModalDemo.html

I was using above code for retrieving right images from the directory of images, 
But every time i'm getting wrong images from the retriever,

My input images usually contains tables or paragraphs.
I also tried with Multimodalvector and Vector retriever , but the results are same..

So please anyone knows how to improve this , Let me know

**Comment by NeethanShetty07** [comment]
Hi , can you show me an example how to use this Multimodal embedding ? with code

**Comment by hatianzhang** [comment]
@NeethanShetty07 do you have enough images for retrieval?

**Comment by NeethanShetty07** [comment]
Hi @hatianzhang , here is the colab code which i was using.
https://colab.research.google.com/drive/1NZJXjg7q7Q4fn-kdP2VRmI2L0j8UNbcB?usp=sharing

Let me know if im doing anything wrong here.

also i have attached the image zip file, , please find it
[table_images.zip](https://github.com/run-llama/llama_index/files/14228211/table_images.zip)
