### ISSUE TITLE
[Bug]: Extension to 10548

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_index#10550]
### Bug Description

The problem mentioned in 10548 (fix) is not working. Tried with the code changes and got below error:

/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:357: RuntimeWarning: coroutine 'ElasticsearchStore._create_index_if_not_exists' was never awaited
  self._create_index_if_not_exists(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:388: RuntimeWarning: coroutine 'async_bulk' was never awaited
  async_bulk(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:392: RuntimeWarning: coroutine 'async_bulk' was never awaited
  success, failed = async_bulk(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-16-4b901dfb7bfa>](https://localhost:8080/#) in <cell line: 1>()
----> 1 index = VectorStoreIndex.from_documents(
      2     documents, storage_context=storage_context)

10 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py](https://localhost:8080/#) in async_add(self, nodes, create_index_if_not_exists, **add_kwargs)
    390         )
    391         try:
--> 392             success, failed = async_bulk(
    393                 self.client, requests, stats_only=True, refresh=True
    394             )

TypeError: cannot unpack non-iterable coroutine object

### Version

0.9.46

### Steps to Reproduce

Follow the case 10548

### Relevant Logs/Tracbacks

```shell
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:357: RuntimeWarning: coroutine 'ElasticsearchStore._create_index_if_not_exists' was never awaited
  self._create_index_if_not_exists(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:388: RuntimeWarning: coroutine 'async_bulk' was never awaited
  async_bulk(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py:392: RuntimeWarning: coroutine 'async_bulk' was never awaited
  success, failed = async_bulk(
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-16-4b901dfb7bfa> in <cell line: 1>()
----> 1 index = VectorStoreIndex.from_documents(
      2     documents, storage_context=storage_context)

10 frames
/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py in async_add(self, nodes, create_index_if_not_exists, **add_kwargs)
    390         )
    391         try:
--> 392             success, failed = async_bulk(
    393                 self.client, requests, stats_only=True, refresh=True
    394             )

TypeError: cannot unpack non-iterable coroutine object
```

**Comment by logan-markewich** [comment]
yea so this is a different error in the code :sigh: the fix I merged fixed one bug, and allowed the code to get to the next I guess

**Comment by sreenivasanm6** [comment]
Please let me know if this issue is fixed

**Comment by sreenivasanm6** [comment]
Able to get below error post to creating VectorstoreIndex:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-15-acf3f6d330d6>](https://localhost:8080/#) in <cell line: 3>()
      1 query = "What is most interesting about this essay?"
      2 query_engine = index.as_query_engine()
----> 3 answer = query_engine.query(query)
      4 
      5 print(answer.get_formatted_sources())

10 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/elasticsearch.py](https://localhost:8080/#) in aquery(self, query, custom_query, es_filter, **kwargs)
    544             logger.debug(f"Calling custom_query, Query body now: {es_query}")
    545 
--> 546         async with self.client as client:
    547             response = await client.search(
    548                 index=self.index_name,

AttributeError: __aenter__


Below is sample code:
query = "What is most interesting about this essay?"
query_engine = index.as_query_engine()
answer = query_engine.query(query)

**Comment by sreenivasanm6** [comment]
We need to remove await in the above comment also. It is working for me now. Please fix this.
