### ISSUE TITLE
[Question]: Is it possible to get the same output whenever I pass the same input?

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#10560]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it possible to get the same output whenever I pass the same input?

**Comment by logan-markewich** [comment]
@arnavroh45 if you set `temperature=0` in your LLM, it should be the same (but even then, it kind of depends, for example openai seems to be a bit more unstable?)
