### ISSUE TITLE
[Question]: ,im getting this error  WARNING:llama_index.indices.knowledge_graph.retrievers:Index was not constructed with embeddings, skipping embedding usage... Index was not constructed with embeddings, skipping embedding usage...i can see new documents in their respective form in neo4j graphdb gui but i'm not sure if its issue with llm ..im using azureopenai and not openai

### ISSUE THREAD

**Issue by Johnbathappully** [run-llama/llama_index#10565]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

john9876_ — Today at 2:32 AM
Hi,im getting this error 
WARNING:llama_index.indices.knowledge_graph.retrievers:Index was not constructed with embeddings, skipping embedding usage...
Index was not constructed with embeddings, skipping embedding usage...
Index was not constructed with embeddings, skipping embedding usage...
Index was not constructed with embeddings, skipping embedding usage...
Index was not constructed with embeddings, skipping embedding usage...

<img width="650" alt="neo2" src="https://github.com/run-llama/llama_index/assets/114779060/3f7c6656-4cb1-4599-9b77-22ab60c7d71f">
<img width="674" alt="neo1" src="https://github.com/run-llama/llama_index/assets/114779060/e63f1ed3-dcae-429a-a6c5-b8015968d8bd">
llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="gpt35",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="textexmbedding1",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embed_model,
)
i'm using neo4j:5.11-enterprise with apoc plugin

**Comment by logan-markewich** [comment]
Its more like a log thats way too verbose, not an actual issue

There is an option to use a vector store and embed triplets for vector retrieval, but if you don't enable it, then the default retrieval mode of "hybrid" changes and prints this error
