### ISSUE TITLE
[Bug]: 'BedrockEmbedding' has no attribute 'from_credentials'

### ISSUE THREAD

**Issue by nicoloboschi** [run-llama/llama_index#10575]
### Bug Description

I upgraded from version `0.9.34` to `0.9.47` and I started getting this error
`'BedrockEmbedding' has no attribute 'from_credentials'`

The culprit is this pull request: https://github.com/run-llama/llama_index/pull/10443

I know there's a workaround (e.g. using the constructor itself) but it doesn't make sense to break the public API in this way. 

### Version

0.9.47

### Steps to Reproduce

`BedrockEmbedding.from_credentials(
            model_name="amazon.titan-embed-text-v1",
            aws_region="some-region",
)`

**Comment by logan-markewich** [comment]
snuck it into v0.9.48 because I felt bad 😆

**Comment by nicoloboschi** [comment]
@logan-markewich thanks for the fix, I appreciate that. 

However the fix is still problematic as the model name is not correctly passed the constructor.
I've sent a fix: https://github.com/run-llama/llama_index/pull/10640
