### ISSUE TITLE
[Question]: How to use Azure Open AI Service with LLama Index Sub-Question?

### ISSUE THREAD

**Issue by navinkeshari** [run-llama/llama_index#10571]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Unable to find documentation or sample on usage of Llama Index Sub-Question Generation.

**Comment by JMTCoder** [comment]
hello @navinkeshari , tried it last week based on the documentation link mentioned in #10411 , and worked !

**Comment by navinkeshari** [comment]
Hi I have tried using #10411 comments, but it didnt worked. Below is the code
import os
from llama_index.llms import AzureOpenAI
from llama_index.embeddings import AzureOpenAIEmbedding
from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index import set_global_service_context
from llama_index.callbacks import CallbackManager, LlamaDebugHandler

import openai

api_key = "YOURAPIKEY"
azure_endpoint = "https://RESOURCE_NAME.openai.azure.com"
api_version = "2023-07-01-preview"
embed_api_version = "2023-05-15"


os.environ["OPENAI_API_VERSION"] = api_version
os.environ["AZURE_OPENAI_ENDPOINT"] = azure_endpoint
os.environ["AZURE_OPENAI_API_KEY"] = api_key

llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="CHAT_DEPLOYMENT_NAME",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
    temperature=0.5,
    max_new_tokens=300,
    use_azure_ad=False,
    
)
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="EMBEDDING_DEPLOYMENT_NAME",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=embed_api_version,
)

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])
service_context1 = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embed_model,
 callback_manager=callback_manager

)
set_global_service_context(service_context1)

from llama_index.tools import QueryEngineTool, ToolMetadata
from llama_index.query_engine import SubQuestionQueryEngine

# Using the LlamaDebugHandler to print the trace of the sub questions
# captured by the SUB_QUESTION callback event type

pg_essay = SimpleDirectoryReader(input_dir="./data").load_data()

# build index and query engine
vector_query_engine = VectorStoreIndex.from_documents(
    pg_essay, use_async=True, service_context=service_context1
).as_query_engine()

# setup base query engine as tool
query_engine_tools = [
    QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name="pg_essay",
            description="Paul Graham essay on What I Worked On",
        ),
    ),
]

query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context1,
    use_async=True,
)
from llama_index.question_gen.types import SubQuestion

sub_q = SubQuestion(sub_question="How was Paul Grahams life different before, during, and after YC?", tool_name="AboutPaul")
response = query_engine.query(
    sub_q.sub_question
)
print(response)


Error: openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by logan-markewich** [comment]
@navinkeshari you need to use a new API version, `2023-05-15` is too old.

`api_version = "2023-07-01-preview"` is the oldest one that I've tested

OpenAI updated their API around May, and azure has somehow not released a new stable version using the new API, but the previews work fine

**Comment by navinkeshari** [comment]
Post changing of the api version still gets the same error :
openai.NotFoundError: Error code: 404 - {'error': {'message': 'Unrecognized request argument supplied: tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by navinkeshari** [comment]
Thank @logan-markewich It worked!! after changing api version
