### ISSUE TITLE
What happens if we send new nodes to same collection using chrome vector store?

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#10579]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I have executed this code once and then run it again with different nodes. So what happens

1. does the new nodes get replaced by the older ones

2. it compares the new and older nodes and insert only those nodes that are new, keeping the older intact

3. It doesnt check and insert all the nodes(newer as well as older ones

import chromadb chroma_client = chromadb.HttpClient(host='host', port-8000,) from llama_index.vector_stores import Chroma VectorStore from llama_index.postprocessor.cohere_rerank import CohereRerank chroma_collection = chroma_client.get_or_create_collection("collection") vector_store6 = ChromaVectorStore(chroma_collection=chroma_collection) storage_context6 StorageContext.from_defaults(vector_store-vector_store6) index7 = VectorStoreIndex(nodes=nodes, storage_context=storage_contextő, service_context-service_context)

**Comment by logan-markewich** [comment]
@arnavroh45 simply calling `VectorStoreIndex(nodes=nodes, ...)` will insert the nodes, regardless of if they are already inserted. 

If you are worried about duplicates, checkout using a docstore+vector store with an ingestion pipeline
https://docs.llamaindex.ai/en/stable/examples/ingestion/document_management_pipeline.html

```
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5"),
    ],
    docstore=docstore,
    vector_store=vector_store,  # <-- adding this will automatically upsert nodes, assuming document IDs are the same
)
```
