### ISSUE TITLE
[Bug]: A recent commit removed a popular example linked across various posts

### ISSUE THREAD

**Issue by AyushExel** [run-llama/llama_index#10595]
### Bug Description

Recently, @raghavdixit99 from LanceDB team contributed a multi-modal example. [PR](https://github.com/run-llama/llama_index/pull/10530). Which was also put out on social media by llama-index handles and reshared by LanceDB. For example, here are some posts by @jerryjliu ([twitter]( https://twitter.com/jerryjliu0/status/1755762780186317162?s=56)) , [LinkedIn post by Llama-index handle](https://www.linkedin.com/posts/llamaindex_multimodal-rag-for-processing-videos-using-activity-7161525447263027201-SVKz/?utm_source=share&utm_medium=member_desktop)

Now these links go to 404s. The commit that removed this example - https://github.com/run-llama/llama_index/commit/369973f4e8c1d6928149f0904b25473faeadb116#diff-ce50012ccb4962d4ff93caf69548063d393db9c87548a8263087fd0b93ac34e4

A few users have reported this, and we think that this might have been deleted by mistake in the previous major refactoring efforts. Can we add it back asap? thanks!

### Version

0.10.1

### Steps to Reproduce

https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_video_RAG.html

**Comment by hatianzhang** [comment]
@AyushExel pls checkout https://github.com/run-llama/llama_index/pull/10598

**Comment by logan-markewich** [comment]
This has been fixed
