### ISSUE TITLE
[Bug]: Missing import `Link`.

### ISSUE THREAD

**Issue by toofanix** [run-llama/llama_index#10599]
### Bug Description

I am trying to follow the example in the most recent video posted on youtube and the associated colab notebook.

Video: https://www.youtube.com/watch?v=L1o1VPVfbb0
Colab: https://colab.research.google.com/drive/1fRkgSn2PSlXSMgLk32beldVnLMLtI1Pc?usp=sharing#scrollTo=e16e7f46-6a3f-4390-b149-51d49a255d54
Docs: https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline_pandas.html

But it seems like the import `Link` is missing

ImportError: cannot import name 'Link' from 'llama_index.core.query_pipeline' (~/miniconda3/envs/llindex/lib/python3.11/site-packages/llama_index/core/query_pipeline/__init__.py)

### Version

0.10.1

### Steps to Reproduce

from llama_index.core.query_pipeline import Link

**Comment by marcoeg** [comment]
`from llama_index.core.base.query_pipeline.query import Link`
worked for me

**Comment by toofanix** [comment]
@marcoeg Thanks that worked. 
@dosu-not The links provided by you are not valid. They give a 404 error.

**Comment by logan-markewich** [comment]
We could probably stand to make these imports a little easier (thanks @marcoeg for sharing the working import)

**Comment by logan-markewich** [comment]
The imports have since been improved

`from llama_index.core.query_pipeline import Link`
