### ISSUE TITLE
[Question]: import error

### ISSUE THREAD

**Issue by whoo9112** [run-llama/llama_index#10621]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I updated today's version to 0.10.1, and found a baffling error.

May I know what the problem is?

`from llama_index.core import VectorStoreIndex, SimpleDirectoryReader`

error msg: ImportError: cannot import name 'VectorStoreIndex' from 'llama_index.core' (unknown location)

**Comment by logan-markewich** [comment]
@whoo9112 it's critical to 
a) ensure you are using a venv if you aren't already
b) ensure its a fresh venv 

For example, I do this, and it works 

```
python -m venv venv
source venv/bin/activate 
pip install llama-index
```

**Comment by whoo9112** [comment]
> @whoo9112 it's critical to a) ensure you are using a venv if you aren't already b) ensure its a fresh venv
> 
> For example, I do this, and it works
> 
> ```
> python -m venv venv
> source venv/bin/activate 
> pip install llama-index
> ```

i'm already using conda env.  I tried a new virtual environment, but it still doesn't work.

**Comment by nerdai** [comment]
With the the new venv activate can you please run `pip freeze | grep llama-index` and share the output here?

Can you also try the import statement when using python interpreter with venv activated. Specifically:
```
source venv/bin/activate
python

# in the python interpreter
>>> from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
```

And share the output. If running a script, please ensure you are indeed running the script using the correct venv.

**Comment by logan-markewich** [comment]
@whoo9112 you followed my sample code exactly, in a fresh terminal? 

It works for me. It also works in Google colab.

If you have any existing llama-index installation, it needs to be Uninstalled

**Comment by whoo9112** [comment]
> 새로운 venv activate를 사용하여 `pip freeze | grep llama-index`여기에서 출력을 실행하고 공유할 수 있습니까?
> 
> venv가 활성화된 Python 인터프리터를 사용할 때 import 문을 사용해 볼 수도 있습니다. 구체적으로:
> 
> ```
> source venv/bin/activate
> python
> 
> # in the python interpreter
> >>> from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
> ```
> 
> 그리고 결과물을 공유해보세요. 스크립트를 실행하는 경우 실제로 올바른 venv를 사용하여 스크립트를 실행하고 있는지 확인하십시오.

![image](https://github.com/run-llama/llama_index/assets/48273456/c0dd8bbc-3fc2-448e-8d18-71bd9b3470bd)
![image](https://github.com/run-llama/llama_index/assets/48273456/703caa73-52d6-44c2-87fa-5e5acb7c3af9)

**Comment by nerdai** [comment]
Thanks for sharing. The pip list looks good...

I wonder if we're running into [conda/pip co-existing issues](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment)?

**Comment by whoo9112** [comment]
> 공유해 주셔서 감사합니다. 핍리스트는 괜찮아 보이는데...
> 
> [conda/pip 공존 문제가](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment) 발생하고 있는지 궁금합니다 .

This was not the case when I was using the previous version. Should I still check it out?

**Comment by nerdai** [comment]
Would you mind trying quickly without conda at all, and using python venv instead of conda to create your virtual env as Logan mentioned above?

**Comment by nerdai** [comment]
I know that the conda-forge version is still on v0.9.48 whereas PyPi is at v0.10.1. I'm not sure if that might be what's causing us some issues here.

**Comment by anoopshrma** [comment]
You can try this once too:


`pip3 uninstall llama-index`
`pip3 install llama-index --upgrade --no-cache-dir --force-reinstall`

**Comment by CalculusC** [comment]
Hi there, 

Perhaps it is easier to work at the new environment. For window system, I am able to import  VectorStoreIndex and SimpleDirectoryReader

```
conda create -n llama python=3.11 anaconda
conda acticate llama
pip install llama-index

python
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
```

<img width="909" alt="image" src="https://github.com/run-llama/llama_index/assets/31399298/b27fa2f1-5c87-41f8-be84-d15395b1fe88">

**Comment by whoo9112** [comment]
Thank you all for your response.
As Calculus C said, I ran it with the following code and it was resolved!
`conda create -n llama python=3.11 anaconda
conda activate llama
pip install llama-index

python
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader`

**Comment by anoopshrma** [comment]
Awesome! Do close the issue if it is resolved for you! 🙂

**Comment by nerdai** [comment]
Thanks @CalculusC for this! Adding these conda instructions to our migration guide.

**Comment by TomDeneire** [comment]
For me, what worked was `from llama_index import SimpleDirectoryReader, VectorStoreIndex`.

```
Python 3.12.1 (main, Dec 10 2023, 15:07:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_index
>>> dir(llama_index)
['BaseCallbackHandler', 'BasePromptTemplate', 'Callable', 'ChatPromptTemplate', 'ComposableGraph', 'Document', 'DocumentSummaryIndex', 'GPTDocumentSummaryIndex', 'GPTKeywordTableIndex', 'GPTKnowledgeGraphIndex', 'GPTListIndex', 'GPTRAKEKeywordTableIndex', 'GPTSimpleKeywordTableIndex', 'GPTTreeIndex', 'GPTVectorStoreIndex', 'IndexStructType', 'KeywordTableIndex', 'KnowledgeGraphIndex', 'LLMPredictor', 'ListIndex', 'MockEmbedding', 'MockLLMPredictor', 'NullHandler', 'OpenAIEmbedding', 'Optional', 'Path', 'Prompt', 'PromptHelper', 'PromptTemplate', 'QueryBundle', 'RAKEKeywordTableIndex', 'Response', 'SQLContextBuilder', 'SQLDatabase', 'SQLDocumentContextBuilder', 'SelectorPromptTemplate', 'ServiceContext', 'SimpleDirectoryReader', 'SimpleKeywordTableIndex', 'StorageContext', 'SummaryIndex', 'TreeIndex', 'VectorStoreIndex', '__all__', '__annotations__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_f', 'async_utils', 'bridge', 'callbacks', 'chat_engine', 'constants', 'core', 'data_structs', 'download', 'download_loader', 'embeddings', 'get_response_synthesizer', 'get_tokenizer', 'global_handler', 'global_service_context', 'global_tokenizer', 'graph_stores', 'indices', 'ingestion', 'llm_predictor', 'llms', 'load_graph_from_storage', 'load_index_from_storage', 'load_indices_from_storage', 'logger', 'logging', 'memory', 'multi_modal_llms', 'node_parser', 'objects', 'output_parsers', 'postprocessor', 'prompts', 'readers', 'response', 'response_synthesizers', 'schema', 'service_context', 'set_global_handler', 'set_global_service_context', 'set_global_tokenizer', 'storage', 'token_counter', 'tools', 'types', 'utilities', 'utils', 'vector_stores']
```

**Comment by logan-markewich** [comment]
@TomDeneire that's specific to non v0.10.x versions fyi

**Comment by kouskouss** [comment]
> Thank you all for your response. As Calculus C said, I ran it with the following code and it was resolved! `conda create -n llama python=3.11 anaconda conda activate llama pip install llama-index
> 
> python from llama_index.core import VectorStoreIndex, SimpleDirectoryReader`

I did exactly the same thing as I created a venv with conda, but it stills gives an Import Error.

`from llama_index.core import VectorStoreIndex, SimpleDirectoryReader`
ImportError: cannot import name 'VectorStoreIndex' from 'llama_index.core' (unknown location)

Also, with this import: 
`from llama_index.retrievers.bm25.base import BM25Retriever`
It gives back this error:

ImportError: cannot import name 'InputKeys' from partially initialized module 'llama_index.core.base.query_pipeline.query' (most likely due to a circular import) (C:\Users\konst\anaconda3\Lib\site-packages\llama_index\core\base\query_pipeline\query.py)

Do you have any explanation of why these errors persists?

**Comment by logan-markewich** [comment]
@kouskouss do you have llama-index installed globally in thr base env?

Since there was a switch to namespaced packages, any remnants of an old install will cause some issue.

Maybe try with venv instead? 

In a fresh terminal 

```
pip uninstall llama-index  # just to be sure
python -m venv venv 
source venv/bin/activate
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

**Comment by kouskouss** [comment]
@logan-markewich Thank you very much, I followed your instructions and I did not use the conda to create the new venv and it worked!
Also, yes, I had it globally too, so probably the unistallation in the beginning helped too.

**Comment by romilan24** [comment]
> You can try this once too:
> 
> `pip3 uninstall llama-index` `pip3 install llama-index --upgrade --no-cache-dir --force-reinstall`

Can confirm that this suggestion worked for me as well, thank you.

**Comment by kai-hubs** [comment]
> You can try this once too:
> 
> `pip3 uninstall llama-index` `pip3 install llama-index --upgrade --no-cache-dir --force-reinstall`

This worked for me.

**Comment by linuaries** [comment]
I met the same issue while use pip to insall llama-index and conda install pytorch. And issue solved after all were installed by pip.

**Comment by jack7143** [comment]
> pip3 install llama-index --upgrade --no-cache-dir --force-reinstall

this work
