### ISSUE TITLE
[Bug]: Error with set_global_handler("promptlayer")

### ISSUE THREAD

**Issue by med-dak** [run-llama/llama_index#10632]
### Bug Description

I tried using promptLayer, following the documentation :

```
os.environ["PROMPTLAYER_API_KEY"] = "pl_..."
from llama_index import set_global_handler
set_global_handler("promptlayer", pl_tags=["paul graham"])
```
, but I encountered this error:
`While logging your request PromptLayer had the following error: maximum recursion depth exceeded while calling a Python object`

When I use the code from the promptLayer documentation, it works. Furthermore, when I change the placement of this line : `set_global_handler("promptlayer", pl_tags=["paul graham", "essay"])`, I no longer get an error, but I don't find anything in the promptLayer dashboard.

### Version

0.10.1

### Steps to Reproduce

set_global_handler("promptlayer", pl_tags=["paul graham"])

**Comment by Jped** [comment]
@med-dak can you upgrade python and try this again? We just pushed a fix on our end for this.

**Comment by mraichur** [comment]
I am facing a similar issue as I have set my global handler for the promptlayer but not able to see any of the responses logged in my account. I tried to debug a little, and was able to see that indeed the global handler is set, but for some reason, when i invoke the llama_parse_query_engine.query it doesnt invoke any prompt tracing service from prompt layer

`<llama_index.callbacks.promptlayer.base.PromptLayerHandler object at 0x0000023D6734FEC0>
`


here is how i set the promptlayer in my fast api application: ( I have my api key set as mentioned in documentation, and yes it is active, as i tested it out in another application in js.)

`from llama_index.core import set_global_handler
set_global_handler("promptlayer", pl_tags=["test"])`


here are the versions of the packages i am currently using:
```
llama-index                             0.10.65
python                                 ^3.12
```


If you need any further information, please let me know.
