### ISSUE TITLE
[Question]: Indexing with Settings over Service context, speed and count differences. 

### ISSUE THREAD

**Issue by AbishekNairM** [run-llama/llama_index#10631]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So initially for v0.9, to create the index it took me seconds to make it for a few documents with the below code:

""" Below code took seconds to create the index"""
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index import SimpleDirectoryReader, VectorStoreIndex,  ServiceContext
documents_path="/pdfs"
embed_model_name="models/all-MiniLM-L6-v2"
embed_model = HuggingFaceEmbedding(model_name=embed_model_name)
service_context = ServiceContext.from_defaults(
            embed_model=embed_model, chunk_size=512
            , chunk_overlap=64,llm=None 
        )
documents_path="/pdfs"
documents = SimpleDirectoryReader(documents_path,recursive=True).load_data()
index = VectorStoreIndex.from_documents(
            documents, service_context=service_context
        ) 
        
        
  But when I tried setting the equivalent parameters using the deprecated version of service_context i.e Settings it uses 100 percent of the cpu as well as took 27 minutes in the same system it took seconds to give an answer. 
  
  New code:
  
  from llama_index.core import SimpleDirectoryReader, VectorStoreIndex,  ServiceContext,load_index_from_storage
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
embed_model_name="/models/all-MiniLM-L6-v2"
embed_model = HuggingFaceEmbedding(model_name=embed_model_name)
from llama_index.core import Settings

Settings.llm = None
Settings.embed_model = embed_model
#Settings.node_parser = SentenceSplitter(chunk_size=512, chunk_overlap=64)
#Settings.num_output = 512
#Settings.context_window = 3900
Settings.chunk_size=512
Settings.chunk_overlap=64
documents_path="/pdfs"
documents = SimpleDirectoryReader(documents_path,recursive=True).load_data()
index = VectorStoreIndex.from_documents(documents) 

Also with the same setting for both, i noticed that print(len(index.vector_store._data.embedding_dict)) gave 61623 for the new code and the old code with the same settings gave 162 note that the same pdfs are being fed into the index.

**Comment by logan-markewich** [comment]
> Also with the same setting for both, i noticed that print(len(index.vector_store._data.embedding_dict)) gave 61623 for the new code and the old code with the same settings gave 162 note that the same pdfs are being fed into the index.

Well, that will be the source of the issue right there. Let me see if I can replicate

**Comment by logan-markewich** [comment]
```
ls ./data
> lyft_2021.pdf 
> paul_graham_essay.txt  
> uber_10q_june_2022.pdf  
> uber_10q_march_2022.pdf  
> uber_10q_sept_2022.pdf  
> uber_2021.pdf
```

v0.10.3
```python
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex, ServiceContext,load_index_from_storage

from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model_name="sentence-transformers/all-MiniLM-L6-v2"
embed_model = HuggingFaceEmbedding(model_name=embed_model_name)

from llama_index.core import Settings

Settings.llm = None
Settings.embed_model = embed_model
#Settings.node_parser = SentenceSplitter(chunk_size=512, chunk_overlap=64)
#Settings.num_output = 512
#Settings.context_window = 3900
Settings.chunk_size = 512
Settings.chunk_overlap = 64

print("Node parser Settings", Settings.node_parser.chunk_size, Settings.node_parser.chunk_overlap)
>>> Node parser Settings 512 64

documents = SimpleDirectoryReader("./data", recursive=True).load_data()
print("Number of Input documents:", len(documents))
>>> Number of Input documents: 851

index = VectorStoreIndex.from_documents(documents)

print("Number of nodes:", len(index.docstore.docs))
>>> Number of nodes: 2161
```

v0.9.48
```python
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index import SimpleDirectoryReader, VectorStoreIndex, ServiceContext

embed_model_name = "sentence-transformers/all-MiniLM-L6-v2"
embed_model = HuggingFaceEmbedding(model_name=embed_model_name)

service_context = ServiceContext.from_defaults(
    embed_model=embed_model, chunk_size=512, chunk_overlap=64, llm=None
)
print("Node parser Settings", service_context.node_parser.chunk_size, service_context.node_parser.chunk_overlap)
>>> Node parser Settings 512 64

documents = SimpleDirectoryReader("./data", recursive=True).load_data()
print("Number of Input documents:", len(documents))
>>> Number of Input documents: 851

index = VectorStoreIndex.from_documents(documents, service_context=service_context)
print("Number of nodes:", len(index.docstore.docs))
>>> Number of nodes: 2161
```

I did make some fixes to simple directory reader, you can do `pip install -U llama-index llama-index-core` to get those fixes. Without these fixes, I seem to get similar behavior as you reported

Going to close this as fixed.

**Comment by AbishekNairM** [comment]
@logan-markewich Thank you, it matches the issue I had found when checking myself.
