### ISSUE TITLE
[Bug]: SimpleDirectoryReader - PDF reading not working

### ISSUE THREAD

**Issue by raccoonex** [run-llama/llama_index#10637]
### Bug Description

When loading PDF documents with the `SimpleDirectoryReader`, instead of extracted text, the documents contain str representation of document bytes (starting with `%PDF-1.3\n%\n3 0 obj\n<< /Filter /FlateDecode /Length...`).

After a short investigation, I gained suspicion that none of the default file readers were used.

### Version

```
llama-index==0.10.1
llama-index-agent-openai==0.1.1
llama-index-core==0.10.1
llama-index-embeddings-openai==0.1.1
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.1
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-openai==0.1.1
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.1
pypdf==4.0.1
```

### Steps to Reproduce

```python
from llama_index.core import SimpleDirectoryReader

docs = SimpleDirectoryReader(input_dir="path/to/dir").load_data()
docs[0].text == "%PDF-1.3\n%\n3 0 obj\n<< /Filter /FlateDecode /Length..."
```

**Comment by logan-markewich** [comment]
@kaiserfr @raccoonex looking into this now, will report back soon

**Comment by logan-markewich** [comment]
Figured out the issue, pushing a fix soon :)

**Comment by logan-markewich** [comment]
Merged! I have a few more fixes to make across the library, then will publish a new version

**Comment by raccoonex** [comment]
Thank you for fixing the issue so fast!

**Comment by logan-markewich** [comment]
v0.10.3 is out! `pip install -U llama-index llama-index-core`
