### ISSUE TITLE
[Bug]: cannot import name 'Response' from 'llama_index.core' (unknown location) when running upgrade script

### ISSUE THREAD

**Issue by benbenz** [run-llama/llama_index#10634]
### Bug Description

I am trying to run the upgrade script for the massive refactoring and it fails:

Traceback (most recent call last):
  File ".... /.venv/bin/llamaindex-cli", line 5, in <module>
    from llama_index.core.command_line.command_line import main
  File "... /.venv/lib/python3.11/site-packages/llama_index/core/command_line/command_line.py", line 4, in <module>
    from llama_index.core.command_line.rag import RagCLI, default_ragcli_persist_dir
  File "... /.venv/lib/python3.11/site-packages/llama_index/core/command_line/rag.py", line 9, in <module>
    from llama_index.core import (
ImportError: cannot import name 'Response' from 'llama_index.core' (unknown location)
(.venv) 

### Version

0.10.1

### Steps to Reproduce

- upgrade llamaindex to 0.10.1:
- run: llamaindex-cli upgrade YOUR_SRC_DIR

**Comment by anoopshrma** [comment]
The import should look like this:
`from llama_index.core import Response`

I think there could be some issue in the cli though

**Comment by benbenz** [comment]
Conflicts error with leftover packages ...

**Comment by benbenz** [comment]
I am having a version issue with index-storage-index-store-mongodb which only exists in 0.1.1 but llama-index-storage-docstore-mongodb only exists in 0.1.0 which makes it impossible to migrate to either 0.10.0 or 0.10.1

**Comment by logan-markewich** [comment]
@benbenz That issue should be fixed now, we had to patch+publish some versions in the pyproject.toml this morning. Let me know if you still run into issues.

I confirmed this install works in google colab: https://colab.research.google.com/drive/1e4pGlv86tdOCIROqlfxtOJv_Twizdme0?usp=sharing

**Comment by benbenz** [comment]
No more conflicts ! Thanks !!
After a fresh clean of my .env, running the CLI and importing the extra packages (v0.1.1) .. everythying worked fine.
I now have to refactor some stuff it seems but at least it installed fine.
