### ISSUE TITLE
[Bug]: from llama_index.core import global_handler

### ISSUE THREAD

**Issue by abhi12121998** [run-llama/llama_index#10647]
### Bug Description

from llama_index.core import global_handler

### Version

0.10.1

### Steps to Reproduce

from llama_index.core import global_handler

**Comment by anoopshrma** [comment]
Try importing like this: 

`from llama_index.core import set_global_handler`

Then choose the mode that you want to set and it should work!

**Comment by logan-markewich** [comment]
^ this is correct. If you are upgrading to v0.10.X, make sure you either completely uninstall previous llama-index versions, or start with a completely fresh venv

**Comment by lmyslinski** [comment]
Pardon me potentially hijacking this thread, but I've just upgraded to `0.10.x` and while this does compile & run, I cannot see any executions in promptlayer. Should I open a separate issue? Also, I'm using Azure OpenAI if that's relevant

**Comment by logan-markewich** [comment]
@lmyslinski yea promptlayer needs an update I think, there's another open issue for it. Sounds like it might be fixed 
https://github.com/run-llama/llama_index/issues/10632
