### ISSUE TITLE
[Bug]:  ModuleNotFoundError: No module named 'llama_index.core.image_retriever'

### ISSUE THREAD

**Issue by abhi12121998** [run-llama/llama_index#10644]
### Bug Description

ModuleNotFoundError: No module named 'llama_index.core.image_retriever'

### Version

0.10.1

### Steps to Reproduce

from llama_index.core.query_engine import NLSQLTableQueryEngine

**Comment by abhi12121998** [comment]
download the image_retriever file from 0.10.0 version and save it

**Comment by tlongatalaya** [comment]
Also having this issue
