### ISSUE TITLE
[Bug]: Cannot import OpensearchVectorClient - please reopen #10653

### ISSUE THREAD

**Issue by kaiserfr** [run-llama/llama_index#10658]
### Bug Description

Issue #10653 was closed although not solved. 
Please see my last comment there:

site-packages/llama_index/vector_stores/opensearch/**\_\_init\_\_.py** is lacking class OpensearchVector**Client**

### Version

0.10.1

### Steps to Reproduce

from llama_index.vector_stores.opensearch import OpenSearchVectorClient

**Comment by Jotschi** [comment]
Use
```
from llama_index.vector_stores.opensearch.base import OpensearchVectorClient
```

**Comment by kaiserfr** [comment]
Thank you Jotschi, that works.

But that is not the intended import statement - right?
I will not close the issue, because the \_\_init\_\_.py still should be fixed in my opinion.

**Comment by nerdai** [comment]
@kaiserfr closing this issue as I re-opened the original one. I just submitted a PR that adds `OpensearchVectorClient` as a top-level import for this package.
