### ISSUE TITLE
[Documentation]: fix import

### ISSUE THREAD

**Issue by ziodave** [run-llama/llama_index#10650]
### Documentation Issue Description

`from llama_index.core.embeddings import resolve_embed_model` should be `from llama_index.core.embeddings.utils import resolve_embed_model`

### Documentation Link

https://docs.llamaindex.ai/en/stable/getting_started/starter_example_local.html

**Comment by ziodave** [comment]
I made a tiny PR with the fix, https://github.com/run-llama/llama_index/pull/10651

**Comment by logan-markewich** [comment]
Turns out, we just added the shortcut import instead.

`pip install -U llama-index llama-index-core`

`from llama_index.core.embeddings import resolve_embed_model`
