### ISSUE TITLE
[Bug]: AttributeError: module 'llama_index.core' has no attribute '__version__'

### ISSUE THREAD

**Issue by navya0405** [run-llama/llama_index#10659]
### Bug Description

Getting AttributeError: module 'llama_index.core' has no attribute '__version__' when using
from llama_index.vector_stores.elasticsearch import ElasticsearchStore 
and create an ElasticsearchStore object.

### Version

llama-index==0.10.1 llama-index-agent-openai==0.1.1 llama-index-core==0.10.1 llama-index-embeddings-openai==0.1.1 llama-index-legacy==0.9.48 llama-index-llms-openai==0.1.1 llama-index-multi-modal-llms-openai==0.1.1 llama-index-program-openai==0.1.1 llama-index-question-gen-openai==0.1.1 llama-index-readers-file==0.1.1 llama-index-vector-stores-elasticsearch==0.1.1

### Steps to Reproduce

The error is coming from 
from llama_index.vector_stores.elasticsearch import ElasticsearchStore package 
and create an ElasticsearchStore object.

### Relevant Logs/Tracbacks

```shell
/venv/lib/python3.11/site-packages/llama_index/vector_stores/elasticsearch/base.py:197, in ElasticsearchStore.init(self, index_name, es_client, es_url, es_cloud_id, es_api_key, es_user, es_password, text_field, vector_field, batch_size, distance_strategy)
    193     self._client = es_client.options(
    194         headers={"user-agent": self.get_user_agent()}
    195     )
    196 elif es_url is not None or es_cloud_id is not None:
--> 197     self._client = getelasticsearchclient(
    198         esurl=es_url,
    199         username=es_user,
    200         password=es_password,
...
    230 """Get user agent for elasticsearch client."""
    231 import llama_index
--> 233 return f"llama_index-py-vs/{llama_index.core.__version}"
AttributeError: module 'llama_index.core' has no attribute '__version__'
```

**Comment by logan-markewich** [comment]
@navya0405 I just pushed a fix a few minutes ago

Please do `pip install -U llama-index-vector-stores-elasticsearch`
