### ISSUE TITLE
[Documentation]: Documentation typo with the Settings class import

### ISSUE THREAD

**Issue by csotomon** [run-llama/llama_index#10665]
### Documentation Issue Description

A lot of the 0.10.1 version documentation says that we must to import the Settings class using `from llama_index.core import Settings` but the correct way to do it is `from llama_index.core.settings import Settings`

### Documentation Link

https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/settings.html

**Comment by logan-markewich** [comment]
@csotomon both imports work for me actually

```
>>> from llama_index.core.settings import Settings
>>> from llama_index.core import Settings
>>> 
```

**Comment by Jotschi** [comment]
Maybe this is similar?

https://docs.llamaindex.ai/en/stable/getting_started/v0_10_0_migration.html#deprecated-servicecontext:~:text=Setting.chunk_size%20%3D%20512

**Comment by csotomon** [comment]
Yes, but the correct import is `from llama_index.core.settings import Settings` and not `from llama_index.core import Settings`

So, the correct documentation must be
```python
from llama_index.core.settings import Settings

Settings.llm = llm
Settings.embed_model = embed_model
Setting.chunk_size = 512
```

**Comment by csotomon** [comment]
@Jotschi  you are right.

The problem was with my notebook and the order in which the libraries were imported.
