### ISSUE TITLE
[Bug]: not able to import HuggingFaceLLM

### ISSUE THREAD

**Issue by Kulkarni-mohit** [run-llama/llama_index#10670]
### Bug Description

Not able to import HuggingFaceLLM using the command
`from llama_index.llms.huggingface import HuggingFaceLLM`
In earlier version I used to import like mentioned above.

### Version

0.10.3

### Steps to Reproduce

`from llama_index.llms.huggingface import HuggingFaceLLM`

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-34010cf255c3> in <cell line: 1>()
----> 1 from llama_index.llms.huggingface import HuggingFaceLLM

ModuleNotFoundError: No module named 'llama_index.llms.huggingface'
```

**Comment by nerdai** [comment]
Hi @Kulkarni-mohit,

We've made quite a lot of changes for v0.10. The biggest being that the library is organized into LlamaIndex Core and LlamaIndex Integrations/Packs. Each of these (there are hundreds of integrations) are their own python packages and you only install core + whatever other llama-index integration packages you need for your application.

Importantly, `llama-index` v0.10 is essentially now a bundle package that comes with core, and a few other integrations (see [here](https://github.com/run-llama/llama_index/blob/6970d9565071b1695e04f48439f2331f19947d6e/pyproject.toml#L48)). In your case, if you installed `llama-index` then it doesn't come shipped with all llms as it used to. So as the error message implies, you have to add the HuggingFace LLMs integration package. And, you do that by:

```
pip install llama-index-llms-huggingface
```

For more information on v0.10 release, I would encourage you check out the following links:

- [migration guide](https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77)
- [LlamaIndex v0.10 home](https://www.notion.so/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139)

**Comment by otchlan** [comment]
I install:
`pip install llama-index-llms-huggingface `and  `pip install llama-index-core`

but still have error

I import:
`from llama_index.embeddings.huggingface import HuggingFaceEmbedding
`

Error:
`    from llama_index.embeddings.huggingface import HuggingFaceEmbedding
ModuleNotFoundError: No module named 'llama_index.embeddings.huggingface'
`

**Comment by dipanjans16** [comment]
@otchlan 
please try this 
> pip install llama-index-llms-huggingface
> from llama_index.llms.huggingface import HuggingFaceLLM
It worked for me

**Comment by ravi03071991** [comment]
@otchlan You need to `pip install llama-index-embeddings-huggingface` for using `HuggingFaceEmbedding`.

**Comment by arybach** [comment]
cannot import name 'HuggingFaceEmbedding' from 'llama_index.llms.huggingface'
the original syntax:
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from:
https://github.com/run-llama/llama_index/blob/main/docs/examples/ingestion/document_management_pipeline.ipynb
is also not working. 
what is the correct module name to import HuggingFaceEmbedding from?

**Comment by medhsv** [comment]
I am facing the following error:

ImportError                               Traceback (most recent call last)
[<ipython-input-49-91e1a04c49ce>](https://localhost:8080/#) in <cell line: 15>()
     13 #from llama_index.prompts import SimpleInputPrompt
     14 # Import the llama index HF Wrapper
---> 15 from llama_index.llms import HuggingFaceLLM
     16 # Bring in embeddings wrapper
     17 from llama_index.embeddings import LangchainEmbedding

ImportError: cannot import name 'HuggingFaceLLM' from 'llama_index.llms' (unknown location)
