### ISSUE TITLE
[Question]: FunctionComponent?

### ISSUE THREAD

**Issue by austinmw** [run-llama/llama_index#10672]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The below video released on Youtube by LlamaIndex 3 days ago mentions `FunctionComponent`, however, I don't see this in LlamaIndex at all?

(timestamp added)
Introduction to Query Pipelines (Building Advanced RAG, Part 1):
https://youtu.be/CeDS1yvw9E4?si=imvufdilvluLW9fs&t=1583

**Comment by nerdai** [comment]
Hi @austinmw:

I believe you're referring to `FnComponent`? 

In v0.10:
`from llama_index.core.query_pipeline import FnComponent` OR
`from llama_index.core.query_pipeline.components.function import FnComponent`

In v0.9.48:
`from llama_index.query_pipeline import FnComponent` OR
`from llama_index.core.query_pipeline.components import FnComponent`

**Comment by austinmw** [comment]
Ah okay, must have been renamed since the video was recorded. Thanks!

**Comment by nerdai** [comment]
As per @logan-markewich and my discussion, here's a PR that adds `FunctionComponent` alias in case we have other users that watch that youtube video and also look for this class.

**Comment by austinmw** [comment]
Thanks, think I can close this!
