### ISSUE TITLE
[Bug]: IngestionPipeline Incompatibility with Opensearch in Llama_index

### ISSUE THREAD

**Issue by Leonschmitt** [run-llama/llama_index#10688]
### Bug Description

I encountered an issue with the IngestionPipeline in the Llama_index library when integrating it with Opensearch. Specifically, I attempted to use the OpensearchVectorStore as the vector_store for the pipeline. However, this resulted in a ValidationError.

I set up the pipeline as follows:

```
vector_store = OpensearchVectorStore(client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=25, chunk_overlap=0),
        #TokenTextSplitter(chunk_size=400,chunk_overlap=100),
        embed_model
    ],
    vector_store=vector_store,
)

# Attempt to run the pipeline
nodes = pipeline.run(documents=[Document.example()])
```
Upon execution, I received the following error:

```
ValidationError: 1 validation error for IngestionPipeline
vector_store
  value is not a valid dict (type=type_error.dict)
```

This error seems to suggest that the OpensearchVectorStore is not being recognized as a valid input for the vector_store parameter. I suspect this might be related to OpensearchVectorStore not being a BasePydanticVectorStore, as I've seen a similar issue discussed in [Issue #8954](https://github.com/run-llama/llama_index/issues/8954) on the Llama_index GitHub repository. However, I'm not entirely certain if this is the root cause.

Any insights or suggestions on how to resolve this compatibility issue would be greatly appreciated.

### Version

0.9.43

### Steps to Reproduce

```
vector_store = OpensearchVectorStore(client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=25, chunk_overlap=0),
        #TokenTextSplitter(chunk_size=400,chunk_overlap=100),
        embed_model
    ],
    vector_store=vector_store,
)

# Attempt to run the pipeline
nodes = pipeline.run(documents=[Document.example()])
```

### Relevant Logs/Tracbacks

```shell
----> 1 pipeline = IngestionPipeline(
      2     transformations=[
      3         SentenceSplitter(chunk_size=25, chunk_overlap=0),
      4         #TokenTextSplitter(chunk_size=400,chunk_overlap=100),
      5         embed_model
      6     ],
      7     vector_store=vector_store,
      8 )
     10 nodes = pipeline.run(documents=docs)
     12 # run the pipeline
 if transformations is None:
    138     transformations = self._get_default_transformations()
--> 140 super().__init__(
    141     transformations=transformations,
    142     reader=reader,
    143     documents=documents,
    144     vector_store=vector_store,
    145     cache=cache or IngestionCache(),
    146 )

/lib/python3.11/site-packages/pydantic/v1/main.py:341, in BaseModel.__init__(__pydantic_self__, **data)
    339 values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340 if validation_error:
--> 341     raise validation_error
    342 try:
    343     object_setattr(__pydantic_self__, '__dict__', values)
ValidationError: 1 validation error for IngestionPipeline
vector_store
  value is not a valid dict (type=type_error.dict)
```

**Comment by Leonschmitt** [comment]
@dosu-bot I still have the same error, even with version = Lama-Index 0.10.4

**Comment by RichmondAlake** [comment]
According to @logan-markewich, this is because the OpenSearch vector store uses the VectorStore as its base class and not the new BasePydanticVectorStore.

**Comment by josephgrigg** [comment]
I encountered the same issue using CassandraVectorSearch, which also uses VectorStore as its base class instead of BasePydanticVectorStore.

**Comment by ravi03071991** [comment]
Will change OpenSearch and CassandraVectorSearch to use BasePydanticVectorStore.

**Comment by ravi03071991** [comment]
@Leonschmitt Ingestion pipeline has support with Opensearch now. Cassandra can be tracked here - https://github.com/run-llama/llama_index/pull/11435

**Comment by ravi03071991** [comment]
@chrismgonzalez Will be updating with LanceDBVectorStore.
