### ISSUE TITLE
[Feature Request]: Be able to split text and get the ranges that originated each chunk

### ISSUE THREAD

**Issue by rafabr4** [run-llama/llama_index#10686]
### Feature Description

This feature should enable the `split_text` method of `SentenceSplitter` to optionally return a list of ranges (slices) that match each of the chunks against the original text string.

My current implementation of this feature inherits `SentenceSplitter` and overrides `_get_splits_by_fns`, `_split`, `_merge` and `_split_text`.

### Reason

Preserving metadata like the source page of a document is important for similarity search and RAG tasks. However, existing methods like `get_nodes_from_documents` from `SentenceSplitter` apply the chunking algorithm page by page, frequently resulting in truncated sentences at the start/end of some chunks, specifically for those at the start/end of pages. This goes against the purpose of the `SentenceSplitter` class where complete sentences are intended to be captured in each chunk to preserve as much meaning and coherency as possible.

Concatenating all the document pages text and using the `split_text` method is an alternative, but the page metadata is lost and is difficult to re-add it later since the resulting chunks don't match 1:1 the original text.

### Value of Feature

This feature would allow splitting the text from a page-based document without chunks stopping at page boundaries.

Having the `split_text` method return the slices of the original (concatenated) text can help to match the chunks to the source pages that they came from, thus making it easy to define the source page as metadata for each chunk.

At least one other person had already asked for a feature like this in [Stackoverflow](https://stackoverflow.com/questions/77247402/llamaindex-node-creation-how-to-keep-track-of-the-page-number-when-creating-the).

**Comment by rafabr4** [comment]
If possible, I'd like to work on this feature. This would be my first contribution to a GitHub project which gets me really excited! But any guidance and feedback on the proposal is appreciated.

**Comment by logan-markewich** [comment]
@rafabr4 just curious, the splitters already record the ranges in each node. `node.start_char_idx` and `node.end_char_idx`

This doesn't help?

**Comment by logan-markewich** [comment]
Those are fair problems. I think in general the implementation right now is a little naive, but for good reason -- actually tracking this is a pain and makes the code quite confusing haha 

You could always subclass and implement your own logic for finding start/end char idxs (usingbl fuzzy matching maybe, or something else)
