### ISSUE TITLE
[Bug]: Permission denied: '/usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache/corpora'

### ISSUE THREAD

**Issue by murthyc** [run-llama/llama_index#10681]
### Bug Description

Pytest run in Docker container on Mac Ventura 13.6.3
**Error: Permission denied: '/usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache/corpora'**

### Version

llama-index-core==0.10.3

### Steps to Reproduce

- Python- version 3.10.13
- llama-index version 0.10.3
- starting Pytest with a simple test case which successfully ran in llama_index version 0.9.34.

**packages installed**
llama-index-core==0.10.3
llama-index-embeddings-azure-openai==0.1.1
llama-index-embeddings-bedrock==0.1.2
llama-index-embeddings-huggingface==0.1.1
llama-index-embeddings-openai==0.1.1
llama-index-legacy==0.9.48
llama-index-llms-anthropic==0.1.1
llama-index-llms-azure-openai==0.1.1
llama-index-llms-bedrock==0.1.1
llama-index-llms-huggingface==0.1.1
llama-index-llms-llama-cpp==0.1.1
llama-index-llms-openai==0.1.1
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-lmformatenforcer==0.1.1
llama-index-program-openai==0.1.1
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
lm-format-enforcer==0.8.3

### Relevant Logs/Tracbacks

```shell
============================= test session starts ==============================
platform linux -- Python 3.10.13, pytest-8.0.0, pluggy-1.4.0
rootdir: /workspaces/my-app-service-utils
configfile: pytest.ini
testpaths: tests
plugins: cov-2.11.1, anyio-4.2.0, requests-mock-1.11.0, mock-3.0.0
collected 0 items / 2 errors

==================================== ERRORS ====================================
___________________ ERROR collecting tests/test_indexing.py ____________________
/usr/local/lib/python3.10/site-packages/llama_index/core/utils.py:60: in __init__
    nltk.data.find("corpora/stopwords", paths=[self._nltk_data_dir])
/usr/local/lib/python3.10/site-packages/nltk/data.py:583: in find
    raise LookupError(resource_not_found)
E   LookupError: 
E   **********************************************************************
E     Resource stopwords not found.
E     Please use the NLTK Downloader to obtain the resource:
E   
E     >>> import nltk
E     >>> nltk.download('stopwords')
E     
E     For more information see: https://www.nltk.org/data.html
E   
E     Attempted to load corpora/stopwords
E   
E     Searched in:
E       - '/usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache'
E   **********************************************************************

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1050: in _gcd_import
    ???
<frozen importlib._bootstrap>:1027: in _find_and_load
    ???
<frozen importlib._bootstrap>:1006: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:688: in _load_unlocked
    ???
/usr/local/lib/python3.10/site-packages/_pytest/assertion/rewrite.py:175: in exec_module
    exec(co, module.__dict__)
/Users/mchetty/git-my-app-service/my-app-service-utils/tests/test_indexing.py:8: in <module>
    ???
ctsutils/indexing/__init__.py:5: in <module>
    from ctsutils.indexing.index import Index
ctsutils/indexing/index.py:11: in <module>
    from llama_index.core import (
/usr/local/lib/python3.10/site-packages/llama_index/core/__init__.py:8: in <module>
    from llama_index.core.base.response.schema import Response
/usr/local/lib/python3.10/site-packages/llama_index/core/base/response/schema.py:7: in <module>
    from llama_index.core.schema import NodeWithScore
/usr/local/lib/python3.10/site-packages/llama_index/core/schema.py:14: in <module>
    from llama_index.core.utils import SAMPLE_TEXT, truncate_text
/usr/local/lib/python3.10/site-packages/llama_index/core/utils.py:89: in <module>
    globals_helper = GlobalsHelper()
/usr/local/lib/python3.10/site-packages/llama_index/core/utils.py:62: in __init__
    nltk.download("stopwords", download_dir=self._nltk_data_dir)
/usr/local/lib/python3.10/site-packages/nltk/downloader.py:777: in download
    for msg in self.incr_download(info_or_id, download_dir, force):
/usr/local/lib/python3.10/site-packages/nltk/downloader.py:642: in incr_download
    yield from self._download_package(info, download_dir, force)
/usr/local/lib/python3.10/site-packages/nltk/downloader.py:701: in _download_package
    os.makedirs(os.path.join(download_dir, info.subdir))
/usr/local/lib/python3.10/os.py:225: in makedirs
    mkdir(name, mode)
E   PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache/corpora'
------------------------------- Captured stderr --------------------------------
[nltk_data] Downloading package stopwords to
[nltk_data]     /usr/local/lib/python3.10/site-
[nltk_data]     packages/llama_index/core/_static/nltk_cache...
________________ ERROR collecting tests/test_language_model.py _________________
/usr/local/lib/python3.10/site-packages/llama_index/core/utils.py:60: in __init__
    nltk.data.find("corpora/stopwords", paths=[self._nltk_data_dir])
/usr/local/lib/python3.10/site-packages/nltk/data.py:583: in find
    raise LookupError(resource_not_found)
E   LookupError: 
E   **********************************************************************
E     Resource stopwords not found.
E     Please use the NLTK Downloader to obtain the resource:
E   
E     >>> import nltk
E     >>> nltk.download('stopwords')
E     
E     For more information see: https://www.nltk.org/data.html
E   
E     Attempted to load corpora/stopwords
E   
E     Searched in:
E       - '/usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache'
E   **********************************************************************
```

**Comment by logan-markewich** [comment]
Hmm, weird. Maybe we need to update the permissions on those folders in the repo.

As a workaround, I highly recommend using a venv instead of installing globally (yes, even in a docker image).

Either that, or throw in a chmod for the site-packages folder after installing 🤔

**Comment by murthyc** [comment]
> ```dockerfile
> /usr/local/lib/python3.10/site-packages/llama_index/core/_static/nltk_cache/corpora
> ```
Fixed the issue by adding the below to Dockerfile:
```RUN sudo chmod -R 777 /usr/local/lib/python3.10/site-packages```

**Comment by Morriz** [comment]
please set the perms on all caches to 777 as most of us who deploy to saas vendors like streamlit have no control over this.

**Comment by Morriz** [comment]
so can you reopen this @murthyc ? sometimes it is not possible to run in docker (as is the case with streamlit unfortunately).

**Comment by logan-markewich** [comment]
@Morriz will do

**Comment by arkhur** [comment]
Was working fine until yesterday. 
Requirements.txt
streamlit
openai
llama-index
nltk

Permission denied: '/home/adminuser/venv/lib/python3.9/site-packages/llama_index/core/_static/nltk_cache/corpora'

LookupError: 

**********************************************************************

  Resource stopwords not found.

  Please use the NLTK Downloader to obtain the resource:


  >>> import nltk

  >>> nltk.download('stopwords')

  

  For more information see: https://www.nltk.org/data.html


  Attempted to load corpora/stopwords


  Searched in:

    - '/home/adminuser/venv/lib/python3.9/site-packages/llama_index/core/_static/nltk_cache'

**Comment by Odrec** [comment]
I am having this issue with the latest version

ERROR - Error processing file a.pdf: [Errno 13] Permission denied: '/usr/local/lib/python3.13/site-packages/llama_index/core/_static/tiktoken_cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.4750cc24-8b40-4c24-9ff5-5ac6a2a57313.tmp'

**Comment by TKrom** [comment]
> I am having this issue with the latest version
> 
> ERROR - Error processing file a.pdf: [Errno 13] Permission denied: '/usr/local/lib/python3.13/site-packages/llama_index/core/_static/tiktoken_cache/9b5ad71b2ce5302211f9c61530b329a4922fc6a4.4750cc24-8b40-4c24-9ff5-5ac6a2a57313.tmp'

I am getting the same error.

In my case it is probably related to the fact that I run multiple containers, referencing the context of one particular container. Probably solvable by setting correct user / permissions for the containers. The thing is, that it used to work fine, and since an update of some kind rendering this Permission error out of the blue.

Did you manage to solve it already @Odrec ?

**Comment by Odrec** [comment]
Hey @TKrom I solved it by setting root permissions in the container. It was the easiest solution.
