### ISSUE TITLE
[Bug]: Unexpected Number of Questions Generated When Requesting FAQ Generation

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#10694]
### Bug Description

When attempting to generate a set of FAQ questions and answers from a document, specifying num_questions_per_chunk=1 unexpectedly results in multiple questions being generated, exceeding the specified limit.

Expected Behavior
With num_questions_per_chunk=1, I expect to generate exactly one question per document or document chunk processed.

Actual Behavior
Despite setting num_questions_per_chunk=1, multiple questions (7 in my case) are generated for a single document or document chunk, indicating that the limit is not being respected or that the document is being split in an unexpected manner.

Edit : from my LLM log (Mixtral 8x7b running on Replicate) I can see that the LLM is called 8 times even with num_questions_per_chunk=1, so the problem is probably not with the num_questions_per_chunk parameter but with the fact that the request to generate questions/answers is sent multiple times. Could this be due to how async functions work?

### Version

0.9.45

### Steps to Reproduce

Prepare a document or a list of documents to be processed.
Use the provided code snippet to generate FAQ questions and answers, ensuring num_questions_per_chunk is set to 1.
Observe that the output contains more questions than expected.

```
import asyncio
from llamaindex import RagDatasetGenerator

async def main():
    documents = SimpleDirectoryReader(input_files=["./document.txt"]).load_data()
    QUESTION_GEN_PROMPT = "Here is a text. Your job is to imagine {num_questions_per_chunk} questions that could be asked about this text."
    
    dataset_generator = RagDatasetGenerator.from_documents(
        documents=documents,
        service_context=service_context,
        question_gen_query=QUESTION_GEN_PROMPT,
        show_progress=True,
        num_questions_per_chunk=1,  # Expected to generate one question per chunk
    )
    
    labelled_rag_dataset = await dataset_generator.agenerate_dataset_from_nodes()
    for example in labelled_rag_dataset.examples:
        print("-----")
        print(f"Question: {example.query}")
        print(f"Answer: {example.reference_answer}")

if __name__ == "__main__":
    asyncio.run(main())

```

**Comment by elsatch** [comment]
Any advanced with this issue? Yesterday I discovered this bug creating a 8932 Q&A pairs from 97 chunks.
