### ISSUE TITLE
[Bug]: KnowledgeGraphIndex.as_retriever ignores 'retriever_mode' parameter

### ISSUE THREAD

**Issue by lukeherron** [run-llama/llama_index#10708]
### Bug Description

Prior to the v0.10.0 refactor, 'retriever_mode' parameter was being passed via kwargs to KGTableRetriever:
https://github.com/run-llama/llama_index/blob/3823389e3f91cab47b72e2cc2814826db9f98e32/llama-index-legacy/llama_index/legacy/indices/knowledge_graph/base.py#L105-L114

'retriever_mode' is now a non-kwargs param and is not subsequently being passed to KGTableRetriever:
https://github.com/run-llama/llama_index/blob/3823389e3f91cab47b72e2cc2814826db9f98e32/llama-index-core/llama_index/core/indices/knowledge_graph/base.py#L122-L142

The end result being retriever mode defaults to keyword and embeddings are ignored for any kg index queries.

### Version

v0.10.4

### Steps to Reproduce

1. Crete KnowledgeGraphIndex
2. 
```
query_engine = kg_index.as_query_engine(retriever_mode=KGRetrieverMode.EMBEDDING)
query_engine.query("Some query that really needs a good embedding")
```
3. Keyword query is performed, embeddings are ignored

**Comment by nerdai** [comment]
Thanks for raising @lukeherron. I believe the fix should just be to add the missing `retriever_mode` param in the construction of the `KGTableRetriever`. Just submitted a PR for this.
