### ISSUE TITLE
[Bug]: Facing this error after upgrading to llama-index and llama-index-core to v0.10.3 

### ISSUE THREAD

**Issue by GxTeo** [run-llama/llama_index#10713]
### Bug Description

Getting error from line: `from llama_index.core import Settings` 

`
OSError: No such file or directory: '/home/user/anaconda3/envs/llamaindex-gx/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache/tokenizers/punkt/PY3'`

### Version

v0.10.3

### Steps to Reproduce

`from llama_index.core import Settings` 

### Relevant Logs/Tracbacks

```shell
OSError: No such file or directory: '/home/user/anaconda3/envs/llamaindex-gx/lib/python3.11/site-packages/llama_index/core/_static/nltk_cache/tokenizers/punkt/PY3
```

**Comment by nerdai** [comment]
This should trigger a download of these files if they don't already exist. Can you try using a fresh virtual env?

It looks like you're using conda, so here's this:
```
# conda
conda create -n llama python=3.11 anaconda # can use any Python 3.9 - 3.12 
conda activate llama
pip install llama-index
```

**Comment by GxTeo** [comment]
thank you @nerdai
