### ISSUE TITLE
[Question]: Async Support for Retrievers

### ISSUE THREAD

**Issue by bwhartlove** [run-llama/llama_index#10719]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Referencing the issue found here: https://github.com/run-llama/llama_index/issues/6591 

Curious if this was ever resolved? I was noticing that my async calls using aquery on my query engine seem to block the main thread. Specifically, it appeared to block during the post processing synthesis process. Any updates would be greatly appreciated. Thanks!

**Comment by bwhartlove** [comment]
@logan-markewich Thanks for the quick reply. I am currently using FAISS and my embedding model is a HuggingFaceEmbedding model I have locally. The LLM I am using, Mixtral, is being served up with TGI.

**Comment by logan-markewich** [comment]
So both FAISS and HuggingFaceEmbedding are not possible to run async (since they are compute bound on your machine)

TGI could be async. Did you use the langchain class? Or maybe the new openai-like approach they added recently?

**Comment by logan-markewich** [comment]
Elasticsearch, qdrant, pinecone, postgres support async.

For TGI, since it's langchain, it's using the wrapper, it seems async is a TODO
https://github.com/run-llama/llama_index/blob/3111da462c9b30ab52361fe60d99d25fd1864f9c/llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/base.py#L206

Tbh I would recommend using the openai-api mode with TGI. Small blog post with llamaindex usage here (note that the example is from pre v0.10.x)
https://huggingface.co/blog/tgi-messages-api#how-to-use-with-llamaindex

**Comment by bwhartlove** [comment]
Thanks for the info. A few notes:

For the functions in that file you linked, could we simply use the `langchain` equivalent methods (i.e., apredict, astream, etc.). Is this a planned feature or something I could test out and submit a PR for?

As far as vector stores go, I tried out the Qdrant database and the regular `query` function works just fine with the query engine, but using the `aquery` function results in the following error:

  File "/home/user/venv/langserve/lib/python3.11/site-packages/llama_index/vector_stores/qdrant/base.py", line 688, in aquery
    response = await self._aclient.search(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object list can't be used in 'await' expression

I'm using the newest version of llama index and the llama index qdrant vector store. Tried to follow the instructions from https://docs.llamaindex.ai/en/stable/examples/vector_stores/QdrantIndexDemo.html#async-query-index, but was unsuccessful.

**Comment by logan-markewich** [comment]
@bwhartlove I think using the async versions is just something no one has tackled yet lol. I imagine not every LLM from langchain implements this, so we might have to try/except and default to the sync version?

For qdrant, did you setup the async client correctly?

Should be something like 

```
import qdrant_client 

client = qdrant_client.QdrantClient(...)
aclient = qdrant_client.AsyncQdrantClient(...)

vector_store = QdrantVectorStore(..., client=client, aclient=aclient)
```

**Comment by bwhartlove** [comment]
@logan-markewich Apologies for the delayed response. I have moved on to using OpenSearch instead, which seems to be a better fit for my use case. I'll need to dig into this some more. Possible that adding support for async to the Langchain LLMs would resolve the issue. I'll be looking into this more tomorrow and hopefully have a clearer picture.

**Comment by bwhartlove** [comment]
@dosu-bot Does the OpenSearchVectorStore support async?

**Comment by bwhartlove** [comment]
Are there any plans to add Async support for the OpenSearch Vector Store in the future?

**Comment by bwhartlove** [comment]
I dove into the code and I'm working on implementing the async support for OpenSearch myself. I'll push up a PR when it's done. This will be my first contribution to llama index. Is there anything I should read up on or know about?

**Comment by bwhartlove** [comment]
@logan-markewich I think the integration for opensearch appears to not have been updated with a new release after the 0.10.15 release for the main package went out on pypi: https://pypi.org/project/llama-index-vector-stores-opensearch/#description. When I installed the new version of llama index and reinstall the opensearch integration, it appears to still have the previous code.

**Comment by bwhartlove** [comment]
Made a PR to bump the version of the integration in poetry: https://github.com/run-llama/llama_index/pull/11618

**Comment by bwhartlove** [comment]
@logan-markewich Hopefully, the last piece to the puzzle. I found the issue trying to use this with FastAPI. I had to add in nest asyncio to the Opensearch Client init function:

```
self._os_client = _get_async_opensearch_client(self._endpoint, **kwargs)
not_found_error = _import_not_found_error()

+ nest_asyncio.apply()
event_loop = asyncio.get_event_loop()
```

I also had to supply `--loop asyncio` on the command line to uvicorn. Going to make a PR for this.

**Comment by logan-markewich** [comment]
Yea that's pretty common for fast api

**Comment by bwhartlove** [comment]
@logan-markewich Seem to be pretty much wrapped up with this issue. However, I did run into one thing I wanted to ask about. While trying to use the `aquery` method for my query_engine in combination with streaming, I encountered this error:

`"Streaming not supported for async"`

Is there a plan to implement this in the future? Curious as to the state of this. Thanks!

**Comment by logan-markewich** [comment]
@bwhartlove ah yes that's been a long awaited todo.

Tbh it shouldn't be that bad to implement. Will try to take a look at it

**Comment by carcaussa** [comment]
Hi I'm on llamaindex 0.10.36, and llama-index-vector-stores-opensearch 0.1.8 I'm still receiving the same error initially reported  when using Jupyter notebook on Visual Studio Code:
RuntimeError: This event loop is already running

This happens when creating the opensearch client, (my server is OpenSearch 2.11):
os_vclient = OpensearchVectorClient(
    endpoint=os_url,
    index=vs_index,
    dim=dimensions
)

Is there a workaround for my current scenario?
Thanks in advance

**Comment by logan-markewich** [comment]
@carcaussa the solution is in this thread

At the top of your code 
```
import nest_asyncio
nest_asyncio.apply()
```

**Comment by carcaussa** [comment]
Thank you, I was actually trying that but incorrectly, it works without a problem as you write it, at the beginning of the code
