### ISSUE TITLE
Settings after 0.10.4 update

### ISSUE THREAD

**Issue by JoseGHdz** [run-llama/llama_index#10728]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am having an issue when calling from llama_index.core import Settings
it just says that: cannot import name 'Settings' from 'llama_index.core'

I did a fresh install of LlamaIndex after having lots of issues. I've been able to fix all, except this one. 
One thing I tried is uninstalling all my LlamaIndex packages and reinstall LlamaIndex. 

Has anyone else ran into this issue/know how to fix this?

**Comment by logan-markewich** [comment]
Uninstalling might not be enough.

Can you try with a fresh venv? For example, I would do

```
python -m venv venv
source venv/bin/activate 
pip install llama-index
```

**Comment by JoseGHdz** [comment]
It works now, it shows up in my environment now and I do not get any errors, thanks!
