### ISSUE TITLE
[Bug]: Can't import RedisCache; missing from llama_index.core.ingestion.cache

### ISSUE THREAD

**Issue by JoeSF49** [run-llama/llama_index#10731]
### Bug Description

I'm having trouble loading RedisCache module using new llama-index environment 0.10.4

Using:
llama-index 0.10.4
llama-index-agent-openai 0.1.1
llama-index-core 0.10.3
llama-index-embeddings-huggingface 0.1.1
llama-index-embeddings-openai 0.1.1
llama-index-extractors-entity 0.1.1
llama-index-legacy 0.9.48
llama-index-llms-anyscale 0.1.1
llama-index-llms-langchain 0.1.1
llama-index-llms-openai 0.1.1
llama-index-multi-modal-llms-openai 0.1.1
llama-index-program-openai 0.1.1
llama-index-question-gen-openai 0.1.1
llama-index-readers-file 0.1.2
llama-index-storage-docstore-redis 0.1.1
llama-index-storage-kvstore-redis 0.1.1
llama-index-vector-stores-redis 0.1.1

### Version

0.10.4

### Steps to Reproduce

```python
from llama_index.core.ingestion.cache import RedisCache
```

### Relevant Logs/Tracbacks

```shell
--------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[7], line 27
     25 from llama_index.storage.docstore.redis import RedisDocumentStore
     26 from llama_index.vector_stores.redis import RedisVectorStore
---> 27 from llama_index.core.ingestion.cache import RedisCache
 
ImportError: cannot import name 'RedisCache' from 'llama_index.core.ingestion.cache' (/opt/miniforge/envs/Test/lib/python3.10/site-packages/llama_index/core/ingestion/cache.py)
```

**Comment by nerdai** [comment]
Hey @JoeSF49 thanks for raising this and sorry that you've ran into a bit of trouble moving over to v0.10.

I can confirm that I was able to reproduce the bug on a fresh virtual environment. I believe you are using a brand new virtual environment yourself, but just in case you aren't please make sure you do as we have adopted namespacing convention in v0.10 that clashes with v0.9.xx and earlier.

So what's happened here is that in 0.9.xx `RedisCache` is actually an "alias" for `RedisKVStore`.
`0.9.xx` (legacy)
```python
# old llama_index.ingestion.cache module
...
from llama_index.storage.kvstore import (
    RedisKVStore as RedisCache,
)
...
```

For `0.10`, indeed you've correctly installed the `llama-index-storage-kvstore-redis` package. We didn't carry over this alias (though, perhaps we should...), but you can import it directly

```python
from llama_index.storage.kvstore.redis import RedisKVStore as RedisCache
from llama_index.core.ingestion import IngestionCache

ingest_cache = IngestionCache(
    cache=RedisCache.from_host_and_port(host="127.0.0.1", port=6379),
    collection="my_test_cache",
)
```

The above worked for me when using a fresh venv that installed `llama-index` + the packages in the requirements.txt file shared below

```
llama-index-storage-docstore-redis
llama-index-storage-kvstore-redis
llama-index-vector-stores-redis
llama-index-llms-anyscale
llama-index-llms-langchain
llama-index-extractors-entity
llama-index-embeddings-huggingface
```

**Comment by JoeSF49** [comment]
I've confirmed it works now/  Thank you.  

I tested using 
from llama_index.storage.kvstore.redis import RedisKVStore as RedisCache

You may need to update the documentation. my original import from lama_index.core.ingestion.cache was from the current documentation. 

https://docs.llamaindex.ai/en/stable/examples/ingestion/advanced_ingestion_pipeline.html#redis-cache-setup

**Comment by ucekmez** [comment]
> I've confirmed it works now/ Thank you.
> 
> I tested using from llama_index.storage.kvstore.redis import RedisKVStore as RedisCache
> 
> You may need to update the documentation. my original import from lama_index.core.ingestion.cache was from the current documentation.
> 
> https://docs.llamaindex.ai/en/stable/examples/ingestion/advanced_ingestion_pipeline.html#redis-cache-setup

That's right, the current documentation still shows the same non-working imports

**Comment by guybartal** [comment]
It still does... why nobody updates it?
