### ISSUE TITLE
Unable to import anything!

### ISSUE THREAD

**Issue by VaradDeshmukh97** [run-llama/llama_index#10739]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am developing a RAG application using Llama2-7b. Unfortunately, I am unable to import anything since today morning! It was working fine till last night. Has the LlamaIndex structure changed by any chance?

The import statements are as follows:
```
import os
import logging
import sys
import torch
import nest_asyncio 
nest_asyncio.apply()

from llama_index.llms import LlamaCPP
from llama_index.llms.utils import (
    messages_to_prompt,
    completion_to_prompt
)

from transformers import AutoTokenizer
from llama_index.embeddings import HuggingFaceEmbedding

from llama_index import (
    ServiceContext,
    SimpleDirectoryReader,
    VectorStoreIndex,
    set_global_service_context,
    set_global_tokenizer,
    StorageContext,
    load_index_from_storage
)

from llama_index import download_loader
from llama_hub.web.news import NewsArticleReader

from llama_index.node_parser import SemanticSplitterNodeParser
from llama_index.ingestion import IngestionPipeline

from llama_index.retrievers.bm25_retriever import BM25Retriever
from llama_index.core.retrievers import (
    BaseRetriever,
    VectorIndexRetriever
)
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.postprocessor import SentenceTransformerRerank

from llama_index.core import QueryBundle
from llama_index.core.query_engine import RetrieverQueryEngine

from llama_index.core.response.notebook_utils import (
    display_response,
    display_source_node,
    display_query_and_multimodal_response
)
```

Could anybody please help me out? The errors range from being unable to import ArgPack to anything!

**Comment by logan-markewich** [comment]
Indeed there was a huge refactor. Many posts about it.

The package is now divided into core, plus additional pypi packages for integrations. I recommend creating a fresh venv, and following the either migration guide or our docs

Migration Guide: https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77

Package Registry: https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139

**Comment by VaradDeshmukh97** [comment]
Thanks @logan-markewich! I will try to work this out. Till then, closing as completed.

**Comment by logan-markewich** [comment]
There is an upgrade cli tool, which should hopefully help you migrate quickly 🙏

**Comment by VaradDeshmukh97** [comment]
It is actually awesome! I tried it on my notebooks. Amazing work by the LlamaIndex team!
@logan-markewich, I had just another question, where is the BM25Retriever now? I cannot find it anymore, even after the degradation using the cli tool.
If it is removed, could you suggest me an alternative?
Thanks for the prompt help!

**Comment by VaradDeshmukh97** [comment]
I figured it out!
```
%pip install llama-index-retrievers-bm25
from llama_index.retrievers.bm25 import BM25Retriever
```
Indeed a great work by the LlamaIndex team! Thank you @logan-markewich again!
