### ISSUE TITLE
[Bug]: ChatMessage import from token_counting.py not correct

### ISSUE THREAD

**Issue by erichare** [run-llama/llama_index#10736]
### Bug Description

```python
File ~/.pyenv/versions/3.11.6/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py:6
      1 # Modified from:
      2 # https://github.com/nyno-ai/openai-token-counter
      4 from typing import Any, Callable, Dict, List, Optional
----> 6 from llama_index.core.llms import ChatMessage, MessageRole
      7 from llama_index.core.utils import get_tokenizer
     10 class TokenCounter:

ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)
```

I believe this should be `from llama_index.core.base.llms.types import ChatMessage`

### Version

0.10.4

### Steps to Reproduce

One way, for example, is to run `from llama_index.core.node_parser import SentenceSplitter`

**Comment by nerdai** [comment]
Hey @erichare, that import statement should still work -- we reimport those classes there. 

I and others have ran into those issues before tho. What resolved it was to ensure that we use fresh virtual environments. Any lingering installation of llama-index v0.9.xx will break things.

**Comment by erichare** [comment]
Ah I'm very sorry @nerdai - i think you're right its the lingering installation. I will close and close the corresponding PR, and update my code accordingly.

**Comment by erichare** [comment]
@nerdai , yep that fixed it. I didn't realize i had a lingering older installation in my env. eek. I should have known better there haha. Sorry for the trouble!! all is well 👍

**Comment by nerdai** [comment]
Woohoo! Glad that fixed it for you as well @erichare. No apologies needed either. If anything, we're sorry that you had even an ounce of trouble during this migration. 😊
