### ISSUE TITLE
[Bug]: No module named 'llama_index.core.llms.llama_utils'

### ISSUE THREAD

**Issue by msamwelmollel** [run-llama/llama_index#10730]
### Bug Description

In v0.10.3 whenever I call 
from llama_index.core.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)

I got the erro that module doesn't exist 

### Version

0.10.3

### Steps to Reproduce

from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.core.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)

### Relevant Logs/Tracbacks

```shell
from llama_index.core.llms.llama_utils import (
ModuleNotFoundError: No module named 'llama_index.core.llms.llama_utils'
```

**Comment by logan-markewich** [comment]
@msamwelmollel 

`pip install llama-index-llms-llama-cpp`  (looks like you already did this)
`from llama_index.llms.llama_cpp.llama_utils import messages_to_prompt, completion_to_prompt`
