### ISSUE TITLE
[Bug]: llama-index requires Python >=3.8.1,<3.12

### ISSUE THREAD

**Issue by takosalad** [run-llama/llama_index#10748]
### Bug Description

I'm trying to follow this tutorial
https://betterprogramming.pub/getting-started-with-llamaindex-169bbf475a94
and it fails when I try to do
poetry add llama-index with the aforementioned error message:

The current project's supported Python range (>=3.11,<4.0) is not compatible with some of the required packages Python requirement:
  - llama-index requires Python >=3.8.1,<3.12, so it will not be satisfied for Python >=3.12,<4.0

Because no versions of llama-index match >0.10.4,<0.11.0
 and llama-index (0.10.4) requires Python >=3.8.1,<3.12, llama-index is forbidden.
So, because llama-index-demo depends on llama-index (^0.10.4), version solving failed.

### Version

"^0.10.4"

### Steps to Reproduce

Just issue
poetry new llama-index-demo
cd llama-index-demo
poetry add llama-index

**Comment by nerdai** [comment]
Hi @takosalad, what version of python are you using?

**Comment by surya-ven** [comment]
For me, it was a matter of:

1. Updating poetry's pyproject.toml python version with: `python = ">=3.10,<3.12"`. For your project, it seems like you're running python 3.11, so it would likely be `">=3.11,<3.12"` instead.
2. Run `poetry lock --no-update`
3. Run `poetry install`
4. Then `poetry add llama-index@latest`

**Comment by maxervo** [comment]
Just to double check is it expected that llama-index has now: [< 3.12 in its pyproject.toml](https://github.com/run-llama/llama_index/blob/main/pyproject.toml#L50C1-L50C25)? Before it was [fixed to be < 4.0](https://github.com/run-llama/llama_index/pull/11054) but this [commit](https://github.com/run-llama/llama_index/pull/11068/commits/f35a803982d047de6d26fd35f4d438f827494645#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711) reverted it

**Comment by surya-ven** [comment]
> Just to double check is it expected that llama-index has now: [< 3.12 in its pyproject.toml](https://github.com/run-llama/llama_index/blob/main/pyproject.toml#L50C1-L50C25)? Before it was [fixed to be < 4.0](https://github.com/run-llama/llama_index/pull/10701/commits/ff86746984348784daec3c3bf9d2c034084ac81c) and fixed [here](https://github.com/run-llama/llama_index/pull/11054) as well but this [commit](https://github.com/run-llama/llama_index/pull/11068/commits/f35a803982d047de6d26fd35f4d438f827494645#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711) reverted it

I'm not sure if it is now the expected/recommended way, but hopefully this is addressed by the maintainers.

I was just posting a (temp) fix that worked for my project.
