### ISSUE TITLE
[Bug]: Breaking changes makes it hard to work with llama_index

### ISSUE THREAD

**Issue by jobergum** [run-llama/llama_index#10747]
### Bug Description

A few months ago we did a notebook demonstrating how to connect Vespa with this [notebook](https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/scaling-personal-ai-assistants-with-streaming-mode-cloud.ipynb) and lately it started to fail because there has been a major rewrite of the project. 

I tried following the migrating guide/tooling to update the example by 

```
pip3.11 install -U llama-index llama-index-core
```

and then trying to run the converter 

```
llamaindex-cli upgrade-file scaling-personal-ai-assistants-with-streaming-mode-cloud.ipynb
Traceback (most recent call last):
  File "/opt/homebrew/bin/llamaindex-cli", line 5, in <module>
    from llama_index.core.command_line.command_line import main
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/core/command_line/command_line.py", line 4, in <module>
    from llama_index.core.command_line.rag import RagCLI, default_ragcli_persist_dir
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/core/command_line/rag.py", line 9, in <module>
    from llama_index.core import (
ImportError: cannot import name 'Response' from 'llama_index.core' (unknown location)
```
Help with this would be appreciated. 

```
pip3.11 show llama-index llama-index-core
Name: llama-index
Version: 0.10.4
Summary: Interface between LLMs and your data
Home-page: https://llamaindex.ai
Author: Jerry Liu
Author-email: jerry@llamaindex.ai
License: MIT
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: llama-index-agent-openai, llama-index-core, llama-index-embeddings-openai, llama-index-legacy, llama-index-llms-openai, llama-index-multi-modal-llms-openai, llama-index-program-openai, llama-index-question-gen-openai, llama-index-readers-file
Required-by: RAGatouille
---
Name: llama-index-core
Version: 0.10.3
Summary: Interface between LLMs and your data
Home-page: https://llamaindex.ai
Author: Jerry Liu
Author-email: jerry@llamaindex.ai
License: MIT
Location: /opt/homebrew/lib/python3.11/site-packages
Requires: aiohttp, dataclasses-json, deprecated, dirtyjson, fsspec, httpx, nest-asyncio, networkx, nltk, numpy, openai, pandas, pillow, PyYAML, requests, SQLAlchemy, tenacity, tiktoken, tqdm, typing-extensions, typing-inspect
Required-by: llama-index, llama-index-agent-openai, llama-index-embeddings-openai, llama-index-llms-openai, llama-index-multi-modal-llms-openai, llama-index-program-openai, llama-index-question-gen-openai, llama-index-readers-file
```

### Version

0.10.4

### Steps to Reproduce

https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/scaling-personal-ai-assistants-with-streaming-mode-cloud.ipynb

**Comment by logan-markewich** [comment]
@jobergum typically import errors like this are solved by starting with a fresh venv. I see you are installing packages globally, which is less recommended for python projects in general.

For example, I would do
```
python3 -m venv venv
source venv/bin/activate
pip install llama-index
```
(Or you could use poetry or conda for env management as well)

Due to switching to namespaced packages, any remnants of the previous llama-index install will cause an issue.

Thank you for understanding 🙏🏻

**Comment by jobergum** [comment]
The core problem here is all the breaking changes for a single simple abstraction (retriever). The  blog posts are outdated, notebooks are outdated (we at least notice that the notebook started to fail). Pinning to a specific 0.x version also is not very attractive.

**Comment by logan-markewich** [comment]
@jobergum the choice was made to refactor the package into several namespaced packages. Yes this is breaking, and I realize its frustrating, but going forward is

a) more scaleable (maintaining 400+ integrations in a single package is not the way to go)
b) sane dependency management (since each integration can declare its deps vs. hidden imports)
c) allows for smaller installations
d) each integration can have proper unit tests now

The notebooks in our repo have been updated. If you notice ones that don't work please do let me know, and I can update them.

Did the above venv recommendation help?

**Comment by logan-markewich** [comment]
Also, if you need complete backwards compatibility, you can replace `llama_index` with `llama_index.legacy` in every import (which will point to a legacy version pinned at v0.9.48)

**Comment by jobergum** [comment]
>The notebooks in our repo have been updated.

Yeah, but not ours. Also, this is the second breakage with the retriever abstraction since we published the notebook. I changed to the legacy and will consider removing it entirely 

![image](https://github.com/run-llama/llama_index/assets/20928528/dfbeaf23-4cda-4a44-b5cd-23d2d5db34a7)

**Comment by logan-markewich** [comment]
@jobergum we've provided all the tools we can to help others migrate. Keep in mind this library is both pre v1.0 and has really only been around for less than a year.

This was a monumental task to refactor, and I wouldn't expect something like this to happen again, if I have anything to say about it. This lays the groundwork for a more scalable and maintainable project.

As always, we are around to help with any migrations or other issues you encounter 👍🏻
