### ISSUE TITLE
[Bug]: MultiModal tutorial typo

### ISSUE THREAD

**Issue by dillonalaird** [run-llama/llama_index#10757]
### Bug Description

Following this tutorial https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal.html the line `index.as_query_engine(multi_modal_llm=openai_mm_llm, text_qa_template=qa_tmpl)` fails on an assertion error:

```
File ~/miniforge3/envs/llama/lib/python3.10/site-packages/llama_index/core/indices/multi_modal/base.py:155, in MultiModalVectorStoreIndex.as_query_engine(self, llm, **kwargs)
    152 retriever = cast(MultiModalVectorIndexRetriever, self.as_retriever(**kwargs))
    154 llm = llm or llm_from_settings_or_context(Settings, self._service_context)
--> 155 assert isinstance(llm, MultiModalLLM)
    157 return SimpleMultiModalQueryEngine(
    158     retriever,
    159     multi_modal_llm=llm,
    160     **kwargs,
    161 )

AssertionError: 
```

This line `llm = llm or llm_from_settings_or_context(Settings, self._service_context)` rebuilds the multimodal LLM as a regular LLM and then it fails the next assertion. Here's my llama-index versions:

```
llama-index                         0.10.4
llama-index-agent-openai            0.1.1
llama-index-core                    0.10.3
llama-index-embeddings-clip         0.1.1
llama-index-embeddings-openai       0.1.1
llama-index-legacy                  0.9.48
llama-index-llms-openai             0.1.1
llama-index-multi-modal-llms-openai 0.1.1
llama-index-program-openai          0.1.1
llama-index-question-gen-openai     0.1.1
llama-index-readers-file            0.1.3
llama-index-vector-stores-qdrant    0.1.1
```

### Version

llama-index  0.10.4

### Steps to Reproduce

Run the multi modal tutorial https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal.html

**Comment by dillonalaird** [comment]
Actually the issue is just a typo in the tutorial https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal.html it should be

```python
query_engine = index.as_query_engine(
    llm=mm_model, text_qa_template=qa_tmpl
)
```

not 

```python
query_engine = index.as_query_engine(
    multi_modal_llm=mm_model, text_qa_template=qa_tmpl
)
```

**Comment by kinivi** [comment]
Same here, it's a strange assertion. Why two different classes?
