### ISSUE TITLE
[Bug]: Installs wrong CLIP library

### ISSUE THREAD

**Issue by dillonalaird** [run-llama/llama_index#10756]
### Bug Description

When you install the llama-index-embeddings-clip it install the wrong CLIP library https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml#L32

it's installing this CLIP https://pypi.org/project/clip/ but should be installing it from the github link https://github.com/openai/CLIP

### Version

llama-index-embeddings-clip 0.1.1

### Steps to Reproduce

Following the multimodal tutorial https://docs.llamaindex.ai/en/stable/module_guides/models/multi_modal.html

**Comment by nerdai** [comment]
Thanks @dillonalaird for raising this. Will submit a PR fix shortly!

**Comment by dillonalaird** [comment]
Thank you!
