### ISSUE TITLE
[Question]: Why SimpleFileNodeParser only supports .md, .html and .json

### ISSUE THREAD

**Issue by qizzzh** [run-llama/llama_index#10763]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

As titled. I thought it's a generic parser based on the name and description. 

https://github.com/run-llama/llama_index/blob/b06c888d8319752429096d9a33d8a6a84cc2062a/llama-index-core/llama_index/core/node_parser/file/simple_file.py#L12

**Comment by logan-markewich** [comment]
This is a (tad outdated) object that tbh we haven't really advertised.

Only HTML, JSON, and MD are included because those are the only file-specific node parses we have written

**Comment by qizzzh** [comment]
I'm trying to support different types of files, including code files. Does it mean that I have to implement my own logic determining which parsers/splitters to use based on extensions?

**Comment by qizzzh** [comment]
It's actually advertised here as a recommended way to automatically use the best node parser for each type of content, which is apparently not the case - https://docs.llamaindex.ai/en/stable/module_guides/loading/node_parsers/modules.html#file-based-node-parsers

**Comment by logan-markewich** [comment]
@qizzzh best to implement your own logic imo.

I will make a todo to update that page
