### ISSUE TITLE
[Bug]: The distributed binaries contains bazel BUILD files

### ISSUE THREAD

**Issue by ewianda** [run-llama/llama_index#10760]
### Bug Description

The whl files are packaged with bazel BUILD files. This makes it not usable in a bazel environment. 

### Version

0.10.3

### Steps to Reproduce

* Add llama_index_core to bazel project using latest rules_python
* Execute `bazel run @pypi_llama_index_core//:rules_python_wheel_entry_point_llamaindex-cli` 

### Relevant Logs/Tracbacks

```shell
...
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_cheathman/700c4324c20fb32fe2727a1ee50af11d/execroot/benchsci/bazel-out/darwin-fastbuild/bin/external/py_deps_llama_index_core/rules_python_wheel_entry_point_llamaindex-cli.runfiles/py_deps_llama_index_core/rules_python_wheel_entry_point_llamaindex-cli.py", line 3, in <module>
    from llama_index.core.command_line.command_line import main
ModuleNotFoundError: No module named 'llama_index.core'

```
The issue is that the py_library does a glob and ingores all the source code because of the presence of a BUILD file

```
py_library(
    name = "_pkg",
    srcs = glob(
        ["site-packages/**/*.py"],
        exclude=[],
        # Empty sources are allowed to support wheels that don't have any
        # pure-Python code, e.g. pymssql, which is written in Cython.
        allow_empty = True,
    ),
    data = [] + glob(
        ["site-packages/**/*"],
        exclude=["**/* *", "**/*.py", "**/*.pyc", "**/*.pyc.*", "**/*.dist-info/RECORD"],
    ),
```
```

**Comment by logan-markewich** [comment]
@ewianda Can you suggest a fix for this? I'm not actually sure how to fix this. Probably something in the github publish action?

**Comment by ewianda** [comment]
Adding `exclude = ["**/BUILD"]`  to pyproject.toml solves the problem. 

Noot sure how all the packages are built together, but seems all the pyproject.toml files will need to be updated

**Comment by logan-markewich** [comment]
@ewianda thanks for the tip! We have a script to update and edit pyproject files and publish for every package.

Will try running this tomorrow 🙏🏻

**Comment by ewianda** [comment]
Hi @logan-markewich any progress on this
