### ISSUE TITLE
[Feature Request]: Multilingual multilingual-22-12 embedding (Cohere)

### ISSUE THREAD

**Issue by ihgumilar** [run-llama/llama_index#10771]
### Feature Description

That would be great if you could add feature where we can use multilingual embedding model by cohere. It will help translate many languages.

### Reason

So far, I have only seen this https://docs.llamaindex.ai/en/stable/examples/embeddings/cohereai.html that supports English embedding only

### Value of Feature

If we want to translate 90 languages, we don't need to have 90 models at the same time. We can just use only one multilingual-22-12 embedding (Cohere) to do that. Very helpful. No matter what the source of the documents, they can be accessed from various languages.

**Comment by ravi03071991** [comment]
You can change the embeeding model name and it should work - https://github.com/run-llama/llama_index/blob/edd941dd3c5529f0e08dee6dde283a575cdcd50f/llama-index-integrations/embeddings/llama-index-embeddings-cohere/llama_index/embeddings/cohere/base.py#L82

**Comment by ihgumilar** [comment]
Do I have to do hard coded in base.py ?

**Comment by logan-markewich** [comment]
@ihgumilar ignore dosu for now, @ravi03071991 suggested the correct thing, you can just set the model name in the constructor

**Comment by ihgumilar** [comment]
@ravi03071991 @logan-markewich Thanks a lot for your help. It works now.

Before LlamaIndex is upgraded to v.0.10.x ( v.0.10.5 for now), the above suggestion does not work. It only works with English. I have been waiting for this. Thanks a lot to guys for your help. Much appreciated.

For future reference and those who might have experienced the same issue before, kindly the code below. 

**Note** : ensure you run this first `pip install llama-index-embeddings-cohere` otherwise when you run this code `from llama_index.embeddings.cohere import CohereEmbedding`, it will throw an error. Here you go ! Happy querying with various languages :)

```
from llama_index.embeddings.cohere import CohereEmbedding
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings
from llama_index.core import VectorStoreIndex

embed_model = CohereEmbedding(
    cohere_api_key=COHERE_API_KEY,
    model_name="embed-multilingual-v3.0",
    input_type="search_document",
)

# Set up LLM and embedding with multilingual-v3.0
Settings.llm = OpenAI(model="gpt-3.5-turbo", api_key=OPENAI_API_KEY, temperature=0.1)
Settings.embed_model = embed_model

# Creating index
index = VectorStoreIndex.from_documents(documents)

```
