### ISSUE TITLE
To create private chatbot need help

### ISSUE THREAD

**Issue by lamaindex** [run-llama/llama_index#10775]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can you provide the all steps in single document to create chatbot using lamaindex, the page  is too length and bit confusing which steps is next like

**Comment by logan-markewich** [comment]
The simplest version I can think of

Download and start ollama (be sure to do `ollama pull` to download the model you want to run after the server starts)
https://ollama.com/

I might do `ollama pull starling-lm` for this example

```
pip install llama-index llama-index-llms-ollama llama-index-embeddings-huggingface
```

```
from llama_index.core import Settings
from llama_index.llms.ollama import Ollama
from llama_index.embeddings.huggingface import HuggingFaceEmbeddings

Settings.llm = Ollama(model="starling-lm", request_timeout=3000.0)
Settings.embed_model = HuggingFaceEmbeddings(model_name="BAAI/bge-small-en-v1.5")

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

documents =SimpeDirectoryReader("./data").load_data()
index = VectorStoreIndex.from_documents(documents)

chat_engine = index.as_chat_engine(chat_mode="condense_plus_context")
response = chat_engine.chat("Hello!")
print(response)
```
