### ISSUE TITLE
[Bug]: Reranker and BM25Retriever returns np.float instead of float

### ISSUE THREAD

**Issue by xingjianll** [run-llama/llama_index#10780]
### Bug Description

I find that some instances of NodeWithScore break its type contract with its score attribute during runtime. 
In NodeWithScore the type hint for the score attribute is the following (line 530 schema.py ):

```python
class NodeWithScore(BaseComponent):
    node: BaseNode
    score: Optional[float] = None
```

This is my code for BM25 retriever:

```python
self.bm25_retriever = BM25Retriever.from_defaults(
            index=None if docstore else index,
            similarity_top_k=top_k,
            docstore=docstore
        )
...
bm25_nodes = self.bm25_retriever.retrieve(query)
```

this is what happens during runtime:
<img width="388" alt="Screen Shot 2024-02-16 at 03 10 01" src="https://github.com/run-llama/llama_index/assets/49053229/73773106-9327-476c-9b83-404e3a9d2d2c">

This is my code for reranker:

```python
self.re_ranker = SentenceTransformerRerank(top_n=top_k, model="BAAI/bge-reranker-base")

...
new_nodes = self.re_ranker.postprocess_nodes(
            nodes,
            query_bundle=query,
        )
```

This is the result:
<img width="288" alt="Screen Shot 2024-02-16 at 03 05 40" src="https://github.com/run-llama/llama_index/assets/49053229/6e8812cc-8184-4609-bce0-3dd9240f9ae7">

Because of this the to_json() method doesn't work as well because object of type float32 is not JSON serializable.

### Version

0.9.34

### Steps to Reproduce

from llama_index.retrievers import BM25Retriever
from llama_index import Document

text_list = ["foobarbarfoo"]
documents = [Document(text=t) for t in text_list]

bm25_retriever = BM25Retriever.from_defaults(
    nodes=documents
)
result = bm25_retriever.retrieve("foo")
type(result[0].score)

**Comment by stevenong99** [comment]
I'm getting a similar error in the logs when using the SentenceTransformerRerank:
![image](https://github.com/run-llama/llama_index/assets/49690818/51958912-fc84-46dc-a9d9-14345c9fd838)

And I noticed in the [latest version](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/postprocessor/sbert_rerank.py) of llamaindex, the [code that fixes this problem](https://github.com/run-llama/llama_index/pull/10930/files) has been reverted:
![image](https://github.com/run-llama/llama_index/assets/49690818/fd5ad728-c677-4d67-a7eb-5cf47185671e)


My code:
```
# configure retriever
retriever = VectorIndexRetriever(
    index=index,
    similarity_top_k=7,
)

# configure response synthesizer
response_synthesizer = get_response_synthesizer(llm=self.llm)

# reranker
rerank = SentenceTransformerRerank(model="cross-encoder/ms-marco-MiniLM-L-4-v2", top_n=3)

# assemble query engine
ret_query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[rerank]
)

# Putting all the query engines together
query_engine_tools = [
    QueryEngineTool(
        query_engine=ret_query_engine,
        metadata=ToolMetadata(
            name="call_transcript",
            description="The transcript of a call between an agent and a customer",
        ),
    ),
]

query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    use_async=False
)
```

**Comment by xingjianll** [comment]
@stevenong99 

After some investigation it seems like there are two modules for sbert rerank containing almost identical code:
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/postprocessor/sbert_rerank.py

https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py


The first one is in llamaindex core, the other one is in intergrations. Check the commit history and you'll find the second module contains the v0.10.6 update that fixes the issue. I guess LLamaIndex' codebase management is not the best and after moving things around so much in the recent updates you get errors like this. #

**Comment by logan-markewich** [comment]
@xingjianll actually, the one in llama-index-core was meant to be removed (good catch). Please do use the specific integration package
