### ISSUE TITLE
[Bug]: index.insert_nodes() using QdrantVectorStore is broken.

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#10785]
### Bug Description

In previous versions, nodes could easily be inserted into the Qdrant vector store and also deleted. But this does not work anymore.
I have not yet migrated to v0.10.0 so I am not sure if the issue has been fixed but it exists in the v0.9.47

### Version

0.9.47

### Steps to Reproduce

vector_store = QdrantVectorStore(
            client=client, 
            collection_name=collection_name, 
            prefer_grpc=prefer_grpc,
            enable_hybrid=enable_hybrid
        )

index = VectorStoreIndex.from_vector_store(
            vector_store=vector_store,
            service_context=service_context
        )
index.insert_nodes(nodes=nodes)

### Relevant Logs/Tracbacks

```shell
This throws an error:
'QdrantClient' object has no attribute 'upload_points'
```

**Comment by logan-markewich** [comment]
@gich2009 I think you just need to update your qdrant client package version. This method is listed in their docs

**Comment by gich2009** [comment]
Thanks @logan-markewich. Let me try this out.

**Comment by gich2009** [comment]
Resolved @logan-markewich thanks for the tip. 
To fix this issue, if you're on qdrant-client==1.7.0 then just upgrade to v1.7.3. Not sure which version introduced the change but v1.7.3 works as expected.
