### ISSUE TITLE
[Feature Request]: Allow safety_settings to be passed into Vertex Gemini via additional_kwargs

### ISSUE THREAD

**Issue by chunyat** [run-llama/llama_index#10788]
### Feature Description

The aim is to be able to pass `safety_settings` into the Gemini Vertex LLM object via the `additional_kwargs` input parameter like such:

```python
from llama_index.llms.vertex import Vertex
from vertexai.generative_models._generative_models import (
    HarmCategory,
    HarmBlockThreshold,
)

safety_settings = {
	HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
	HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_LOW_AND_ABOVE,
}
llm = Vertex(
    model="gemini-pro",
    project=credentials.project_id,
    credentials=credentials,
    temperature=temperature,
    max_tokens=max_tokens,
    additional_kwargs={"safety_settings": safety_settings},
)
```

This is not possible right now and will throw an error because the `additional_kwargs` are all being added into Gemini's `GenerationConfig` (i.e. you will get the error `ValueError: Unknown field for GenerationConfig: safety_settings`).

### Reason

I have also tried adding the `safety_settings` later on at query time, since Gemini Vertex also only takes in the `safety_settings` parameter at generation time anyways. However, this was not possible either when I was using chat engines like `SimpleChatEngine` & `CondenseQuestionChatEngine` as they did not support `**kwargs` as input to the `.chat()` / `.stream_chat()` functions.

As opposed to modifying all the chat engines to take in `**kwargs` (since I suppose there might also be a reason why it's not accepting them in the first place), I assumed that it would be more convenient to just fix the `safety_settings` at the LLM object instance creation like in the example code I gave above.

### Value of Feature

Without this feature, it seems that there is presently no alternative way to control the `safety_settings` of a Gemini Vertex LLM.

**Comment by akumar-b6i** [comment]
@logan-markewich  Hi Logan - I am also experiencing some  unwanted safety Error (non-relevant) and would like to have this feature. Will it be okay, If I raise a PR  or should I wait for someone from Llama-index to work on this? Also, what does the label p2 means here (=priority 2)

**Comment by Th0h0** [comment]
@dosu-bot Hey, can you see that message?

**Comment by Th0h0** [comment]
@dosu Hey, can you see that message?

**Comment by logan-markewich** [comment]
This has since been fixed

**Comment by JGamboaPi** [comment]
Is this feature or an equivalent available for TS? I'm facing problems with the default safety_settings
