### ISSUE TITLE
[Bug]: Chat Engine Async Streaming Function Gets Stuck in Forever Loop with vLLM-based LLM

### ISSUE THREAD

**Issue by Thomas-AH-Heller** [run-llama/llama_index#10794]
### Bug Description

Hello, I'm trying to use the chat_engine with async streaming but it seems to get stuck somewhere, the logs of vLLM shows that the answer has been generated, but none is displayed. 

- The chat_engine functions properly with vLLM individually for streaming and asynchronous functionalities.
- However, when attempting to combine both streaming and asynchronous processing within the chat_engine, it encounters a problem where it becomes stuck. When it doesn't get stuck, it takes about 30 extra seconds to start streaming compared to synchronous streaming.
- Interestingly, when using vLLM directly without the chat_engine, it operates smoothly with both asynchronous processing and streaming concurrently.
```
resp = await llm.astreamcomplete("prompt")
async for r in resp:
    print(r, end = "", flush=True) 
``` 

- This discrepancy suggests a potential integration issue between the chat_engine and vLLM specifically concerning asynchronous streaming.

``` 
from llama_index.prompts import PromptTemplate
from llama_index.indices.postprocessor import SentenceTransformerRerank
openai_api_key = "EMPTY"
openai_api_base = "http://localhost:8000/v1"
client = OpenAI(
    api_key=openai_api_key,
    base_url=openai_api_base,
)
models = client.models.list()
model = models.data[0].id
llm = OpenAILike(
    api_key=openai_api_key,
    api_base=openai_api_base,
    model=model,
    max_tokens = 250
)
qa_prompt = PromptTemplate(
                "[INST]  \n"
                "---------------------\n"
                "{context_str}\n"
                "---------------------\n"
                "Query: {query_str}\n"
                "Answer:  [/INST]")
storage_context = StorageContext.from_defaults(persist_dir="vector-store")
embed_model = HuggingFaceEmbedding(model_name = "sentence-transformers/paraphrase-multilingual-mpnet-base-v2")
service_context = ServiceContext.from_defaults(chunk_size=256,chunk_overlap=0.2, llm=llm, embed_model = embed_model)
new_index = load_index_from_storage(storage_context,service_context = service_context)
rerank = SentenceTransformerRerank(model = "cross-encoder/ms-marco-MiniLM-L-12-v2", top_n = 3)
query_engine = new_index.as_query_engine(similarity_top_k = 15, node_postprocessors = [rerank], text_qa_template=qa_prompt,streaming=True,use_async=True)
chat_engine = new_index.as_chat_engine(streaming=True, chat_mode='condense_plus_context')
############ THIS DOESN'T WORK ############
streaming_response = await chat_engine.astream_chat("Your message here")
text = ""
async for token in streaming_response.async_response_gen():
    text += token
    print(text, end="")
############ THIS WORKS ############
streaming_response = chat_engine.stream_chat("Your message here")
for token in streaming_response.response_gen:
    print(token, end="")
############ THIS WORKS AS WELL ############
print(await chat_engine.achat("Your message here"))
```
I'm using Mistral btw.

### Version

v0.9.48

### Steps to Reproduce

Please refer to the notebook containing the steps that trigger the bug: https://colab.research.google.com/drive/1h-eHhoKUnkJQ2TTsw4HxOd0f1zVd97Ol?usp=sharing

After following the steps outlined in the file, the error should occur consistently.

**Comment by logan-markewich** [comment]
Just played around with the colab a bit more. It doesn't actually get stuck forever, but it does get a little "jittery" -- sometime it waits some time to continue looping. But two responses in a row did complete.

I'm not really sure if this is because vLLM is being hosted on the same machine, or if google colab hardware just sucks, or something else. I wish I had a CUDA machine to host on separately 😓 It seems like somehow, control of the event loop is properly being given up.

I will say `OpenAILike` is a very thin wrapper around the `OpenAI` class. So whatever is happening here doesn't really happen with OpenAI for whatever reason 🤔 I'm thinking also maybe its something in the logic for `StreamingAgentChatResponse`, but it needs some deeper testing
