### ISSUE TITLE
Error: importing VectorStoreIndex

### ISSUE THREAD

**Issue by paritadave** [run-llama/llama_index#10797]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have streamlit app that uses llama-index and after the update suddenly it shows error importing VectorStoreIndex. Is there anything I should be taking care of? I am using it on Git and hosting my app on streamlit cloud.

ImportError: cannot import name 'VectorStoreIndex' from 'llama_index' (unknown location)

**Comment by logan-markewich** [comment]
@paritadave with v0.10.X there is some migration needed. 

We have separated the repo into multiple packages, with a core package, plus packages for integration.

There is a migration guide here (with details on a script that will help auto-update!)
https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77

There is also a package registry here
https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139

**Comment by logan-markewich** [comment]
For your example given, it would be `from llama_index.core import VectorStoreIndex`, since that class is in the core package

**Comment by aaronjimv** [comment]
Hello. I have a similar problem importing `ChromaVectorStore`.

I use `from llama_index.vector_stores.chroma import ChromaVectorStore` and got `ModuleNotFoundError: No module named 'llama_index.vector_stores'`

**Comment by Bearsaerker** [comment]
@aaronjimv look into the new Doc. I was sitting the whole day on migrating it to the new llama-index (I'm a very novice coder). https://docs.llamaindex.ai/en/stable/examples/vector_stores/ChromaIndexDemo.html 
It could be that you need to install the pip dependency anew. The basic python import should be the same as far as the doc is concerned

**Comment by aaronjimv** [comment]
> @aaronjimv look into the new Doc. I was sitting the whole day on migrating it to the new llama-index (I'm a very novice coder). https://docs.llamaindex.ai/en/stable/examples/vector_stores/ChromaIndexDemo.html It could be that you need to install the pip dependency anew. The basic python import should be the same as far as the doc is concerned

Thanks.

**Comment by logan-markewich** [comment]
Yea for anyone else hitting similar-ish issues, please do create a new venv to ensure there's no lingering references to old installations :) 

I usually do

```
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-vector-stores-chroma ...
```

Or similar for poetry or condo

**Comment by paritadave** [comment]
Thanks! @logan-markewich from llama-index.legacy import VectorStoreIndex worked for me
