### ISSUE TITLE
[Question]: How to use code_interpreter tool from llama hub

### ISSUE THREAD

**Issue by acucenarodrigues1998** [run-llama/llama_index#10803]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

With the new lib update, I can't use the Code Interpreter Tool from the llama hub. It doesn't recognize the path. Does anyone know how I can solve this? 

I used this line to import 
`from llama_index.tools.code_interpreter import CodeInterpreterToolSpec`

And I got the following error:
`ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-66-ce9555b56018>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from llama_index.tools.code_interpreter import CodeInterpreterToolSpec

ModuleNotFoundError: No module named 'llama_index.tools'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.`

**Comment by logan-markewich** [comment]
@acucenarodrigues1998 can you try starting with a fresh venv?

For example, I might do

```
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-tools-code-interpreter
```

Working colab here
https://colab.research.google.com/drive/1Cfhhd2MyxLcA0biXM1FtiropKQlh1jAz?usp=sharing

**Comment by acucenarodrigues1998** [comment]
> @acucenarodrigues1998 can you try starting with a fresh venv?
> 
> For example, I might do
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install llama-index llama-index-tools-code-interpreter
> ```
> 
> Working colab here https://colab.research.google.com/drive/1Cfhhd2MyxLcA0biXM1FtiropKQlh1jAz?usp=sharing

Thanks for your help! The problem was not venv because i'm using google colab in my test here. But your code showed me where the error in my code was.
