### ISSUE TITLE
[Bug]: llama-index-agent-openai should be a requirement of llama-index-program-openai

### ISSUE THREAD

**Issue by pavelzw** [run-llama/llama_index#10810]
### Bug Description

https://github.com/run-llama/llama_index/blob/827feb1a2f07eb14eafb4d03263a71da6390acc4/llama-index-integrations/program/llama-index-program-openai/llama_index/program/openai/base.py#L4
is used in llama-index-program-openai

but llama-index-agent-openai is not specified in the dependencies
https://github.com/run-llama/llama_index/blob/827feb1a2f07eb14eafb4d03263a71da6390acc4/llama-index-integrations/program/llama-index-program-openai/pyproject.toml#L29-L32

### Version

latest on main

### Steps to Reproduce

see above

**Comment by logan-markewich** [comment]
great catch, will update

**Comment by acodercat** [comment]
same issue
