### ISSUE TITLE
[Question]: How to get vector from Node without checking the databases?

### ISSUE THREAD

**Issue by rendyfebry** [run-llama/llama_index#10919]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi2,

I'm writing a simple unit test to use our custom embedding capability, how to get the vector embedding of a node in the database?

I try to use the ` index.docstore.get_node(node_id)`, but the node doesn't seem to have any embedding, even if I can clearly see them on the databse

```python
documents = [
    Document(
        id="1",
        text="Foo Bar",
    ),
    Document(
        id="2",
        text="AI World",
    ),
]

for document in documents:
    index.insert(document)

all_docs = index.docstore.get_all_ref_doc_info()
index.storage_context.persist(persist_dir="data")

for doc_id in all_docs:
    doc = all_docs[doc_id]

    node = index.docstore.get_node(doc.node_ids[0])
    print(node.id_)
    print(node.text)
    print(node.embedding)
```

**Comment by logan-markewich** [comment]
The embedding is stored in the vector store 👀 

If you are using the base simple vector store, you can do

`embedding = index.vector_store.get(node_id)`

**Comment by rendyfebry** [comment]
Ahh, thanks @logan-markewich 

The base VectorStore class itself doesn't have `get()` function, so it didn't shown in my editor.

Thank you

**Comment by logan-markewich** [comment]
Yea, it's the only one with that method 😅 been meaning to add to the base class, but it's some work to then go and add to the children classes.

Glad it worked!
