### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.readers.web'

### ISSUE THREAD

**Issue by krishnashed** [run-llama/llama_index#10914]
### Bug Description

I have installed all necessary pip libraries needed, but i still find the error 
ModuleNotFoundError: No module named 'llama_index.readers.web'

When i try to import 
from llama_index.readers.web import TrafilaturaWebReader

### Version

0.10.5

### Steps to Reproduce

pip install llama-index

And try to import in a python file and run it
from llama_index.readers.web import TrafilaturaWebReader

**Comment by Bearsaerker** [comment]
Did you also install the pip dependency?
```
pip install llama-index-readers-web
```

**Comment by anoopshrma** [comment]
Yes, you need to install the reader package as well from v0.10.x onwards. 


Migration Guide https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77

Package registry https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139

**Comment by SaulML** [comment]
I have the same issue too!

**Comment by MorenoLabs** [comment]
same here plus the posted guides are no longer accessible

**Comment by shrijayan** [comment]
> Did you also install the pip dependency?
> 
> ```
> pip install llama-index-readers-web
> ```

If we miss something else also we can use this to install.

**Example:**
```
Traceback (most recent call last):
  File "/ragonexcel/main.py", line 3, in <module>
    from llama_index.readers.docling import DoclingReader
ModuleNotFoundError: No module named 'llama_index.readers.docling'
```

**Soluction:**
```
pip install llama-index-readers-docling
```
