### ISSUE TITLE
[Bug]: asyncio.run() error based on tutorial

### ISSUE THREAD

**Issue by JoseGHdz** [run-llama/llama_index#10927]
### Bug Description

I am following the tutorial:
https://docs.llamaindex.ai/en/stable/examples/finetuning/react_agent/react_agent_finetune.html

I am getting this error in the step where the dataset gets generated:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[23], line 1
----> 1 questions = await dataset_generator.generate_questions_from_nodes(num=20)

File [/opt/homebrew/lib/python3.11/site-packages/llama_index/core/evaluation/dataset_generation.py:328](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.11/site-packages/llama_index/core/evaluation/dataset_generation.py:328), in DatasetGenerator.generate_questions_from_nodes(self, num)
    326 def generate_questions_from_nodes(self, num: int | None = None) -> List[str]:
    327     """Generates questions for each document."""
--> 328     return asyncio.run(self.agenerate_questions_from_nodes(num=num))

File [/opt/homebrew/Cellar/python](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/Cellar/python)@3.11[/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py:186](https://file+.vscode-resource.vscode-cdn.net/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py:186), in run(main, debug)
    161 """Execute the coroutine and return the result.
    162 
    163 This function runs the passed coroutine, taking care of
   (...)
    182     asyncio.run(main())
    183 """
    184 if events._get_running_loop() is not None:
    185     # fail fast with short traceback
--> 186     raise RuntimeError(
    187         "asyncio.run() cannot be called from a running event loop")
    189 with Runner(debug=debug) as runner:
    190     return runner.run(main)

RuntimeError: asyncio.run() cannot be called from a running event loop

### Version

0.10.4

### Steps to Reproduce

Follow the complete tutorial and run the code line: questions = dataset_generator.generate_questions_from_nodes(num=20)

**Comment by logan-markewich** [comment]
Notebooks are usually a special case

Add this to the top of your code

```
import nest_asyncio
nest_asyncio.apply()
```

**Comment by logan-markewich** [comment]
Fixed in https://github.com/run-llama/llama_index/pull/10926

**Comment by JoseGHdz** [comment]
Awesome, thanks!

> Notebooks are usually a special case
> 
> Add this to the top of your code
> 
> ```
> import nest_asyncio
> nest_asyncio.apply()
> ```
