### ISSUE TITLE
[Question]: Do you foresee VERSION under llama_index.core 

### ISSUE THREAD

**Issue by Khan-Tzar** [run-llama/llama_index#10923]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

At  llama_index.legacy  you have 
with open(Path(__file__).absolute().parents[0] / "VERSION") as _f:
    __version__ = _f.read().strip()

Under llama_index.core there is no VERSION do you have any option to ad similar 
llama_index.legacy.__version__  with llama_index.core.__version__

**Comment by logan-markewich** [comment]
Probably not the version file, but we can just add it to the core `__init__`

**Comment by Khan-Tzar** [comment]
OK add it in core __init__
