### ISSUE TITLE
For better Q&A effect, I want to use the get_response_synthesizer function with using the parameter structured_answer_filtering, but an error was reported

### ISSUE THREAD

**Issue by Gzj369** [run-llama/llama_index#10938]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Referenced documents](https://docs.llamaindex.ai/en/stable/module_guides/querying/response_synthesizers/root.html#using-structured-answer-filtering)
![image](https://github.com/run-llama/llama_index/assets/13391430/3dc2ffdc-5281-4bd1-bf1c-20f11839e9fb)

My LLM is [Qwen-72B-Chat](https://github.com/QwenLM/Qwen) that support function calling, although it does not belong to [OpenAI model](https://openai.com/blog/function-calling-and-other-api-updates)

The relevant code is as follows:
![image](https://github.com/run-llama/llama_index/assets/13391430/e952d81e-324d-4aee-a9b1-20b604799db0)

The error message is below:
![image](https://github.com/run-llama/llama_index/assets/13391430/d0a5eaf9-d208-4a71-9367-958a654acce6)

Please help me how to use the parameter structured_answer_filtering

**Comment by logan-markewich** [comment]
@Gzj369 how did you configure your LLM? What class did you use?

**Comment by logan-markewich** [comment]
Does your hosted qwen model support the openai function calling api? (I kind of suspect it doesn't?)

Try setting `pydantic_program_mode="llm"` in the service context

**Comment by Gzj369** [comment]
@logan-markewich the github [links](https://github.com/QwenLM/Qwen/blob/main/examples/function_call_examples.py)  of qwen model  has mentioned support for function calling as follows:
![image](https://github.com/run-llama/llama_index/assets/13391430/93a1a84d-e178-4882-89a7-5b24d9910b9c)

let me try setting pydantic_program_mode="llm" in the service context, the next result will be told to you later.
Thank you

**Comment by Gzj369** [comment]
> Does your hosted qwen model support the openai function calling api? (I kind of suspect it doesn't?)
> 
> Try setting `pydantic_program_mode="llm"` in the service context

I just try setting as follows:
```Python
service_context = ServiceContext.from_defaults(embed_model=_hf, pydantic_program_mode="llm")
set_global_service_context(service_context)
```

The same error has still been reported
![image](https://github.com/run-llama/llama_index/assets/13391430/d8c0cfe1-46c0-42fc-8a2d-4e579a45ecd6)

**Comment by logan-markewich** [comment]
Hmm... I'm pretty stumped on this one. And no easy way to replicate either 

That doesn't even seem possible for that to still raise an error, since it should be using json output parsing instead of openai function calls... 🤔

**Comment by Gzj369** [comment]
> Hmm... I'm pretty stumped on this one. And no easy way to replicate either
> 
> That doesn't even seem possible for that to still raise an error, since it should be using json output parsing instead of openai function calls... 🤔

ok. Thank you very much nonetheless
