### ISSUE TITLE
[Documentation]: from llama_index.readers.github import GithubRepositoryReader is not in 0.10.6, where is it?

### ISSUE THREAD

**Issue by aaronjolson** [run-llama/llama_index#10943]
### Documentation Issue Description

This docs page suggests that I can get the GithubRepositoryReader class from

`from llama_index.readers.github import GithubRepositoryReader`

But does not appear to be the case in 0.10.6.

This is the `pip freeze` of my llama deps
```
llama-hub==0.0.79.post1
llama-index==0.10.6
llama-index-agent-openai==0.1.1
llama-index-core==0.10.6.post1
llama-index-embeddings-openai==0.1.1
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.2
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-openai==0.1.2
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
llamaindex-py-client==0.1.12
```

looking at llama_index structure inside of Lib/site-packages I see
llama_index/readers/file/*

but github is not there either. I would suggest a fix to the docs but I am not sure where that class lives now...

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo.html

**Comment by nerdai** [comment]
@aaronjolson I believe tbh at the first line of the notebook/doc indicates that llama-index-readers-github package needs to be installed.

**Comment by logan-markewich** [comment]
Yea, @nerdai is correct 👀 

`pip install llama-index-readers-github`

v0.10.x separated integrations into packages.

In case you missed the updates, here's a few helpful links below

A full package registry is here
https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139

The migration guide also includes tips on a helpful CLI tool to help migrate your older code and identify imports
https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77

**Comment by aaronjolson** [comment]
@logan-markewich - I see that now, thank you!
One of the big selling points of llama-index is all of the available integrations. Going forward, if these are all going to be broken out into their own packages, how will discoverability be addressed? How do developers find all of the available integrations? We can no longer just read the source code from llama-hub to find all of the available integrations...
