### ISSUE TITLE
[Question]: How to find all of the available integrations now that they have been broken out into their own packages?

### ISSUE THREAD

**Issue by aaronjolson** [run-llama/llama_index#10944]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

One of the big selling points of llama-index is all of the available integrations. In v0.10 +, the integrations are broken out into their own packages. How will the discoverability issue be addressed? How will developers find the comprehensive list of all available integrations?

I have seen this
https://pretty-sodium-5e0.notion.site/bb06981a0e29497bb9cd59094bed787a?v=e93fdabe384b4ae6bb29061a28ceac0f
Which contains a list of all of the available packages. I don't see this marketed on the llama-hub.ai page or the docs https://docs.llamaindex.ai/
Is that list the comprehensive source of truth going forward for all integrations?

**Comment by logan-markewich** [comment]
@aaronjolson that package registry is a temporary stopgap.

llamahub.ai is currently being updated to fully list everything. Just working out some kinks, but it's mostly populated there

**Comment by aaronjolson** [comment]
@logan-markewich This is frustrating and I likely spent too much time spinning in circles trying to figure out why I couldn't find the GithubRepositoryReader jumping between the llamahub site and the docs, thinking the issue must be on my end...
A little note on the hub site saying that the list there is currently incomplete, and that there is a backup list, would have saved me a few hours. But I appreciate your responsiveness to these issues here, so thank you!

**Comment by logan-markewich** [comment]
@aaronjolson yea apologies for the frustration! Definitely reach out with any questions (either here or on discord), and I'll probably respond rather quickly.

Good callout on llamhub -- we had a banner at one point, but it looks like it got removed as we started indexing more packages. Will try to get that added back
