### ISSUE TITLE
[Bug]: NLSQLTableQueryEngine wrong imports

### ISSUE THREAD

**Issue by peiwangdb** [run-llama/llama_index#10942]
### Bug Description

I called NLSQLTableQueryEngine from the legacy library it worked but did not work if I do
from llama_index.core.indices.struct_store.sql_query import NLSQLTableQueryEngine

----> 1 from llama_index.core.indices.struct_store.sql_query import NLSQLTableQueryEngine
      3 query_engine = NLSQLTableQueryEngine(
      4     sql_database=sql_database, llm=llm, tables=["cex_coin_balance"]
      5 )

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/indices/__init__.py:4
      1 """LlamaIndex data structures."""
      3 # indices
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      5 from llama_index.core.indices.document_summary import (
      6     DocumentSummaryIndex,
      7     GPTDocumentSummaryIndex,
      8 )
      9 from llama_index.core.indices.document_summary.base import DocumentSummaryIndex

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/indices/composability/__init__.py:4
      1 """This module contains all classes used for composing graphs over indices."""
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      6 __all__ = ["ComposableGraph"]

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/indices/composability/graph.py:5
      1 """Composability graphs."""
      3 from typing import Any, Dict, List, Optional, Sequence, Type, cast
----> 5 from llama_index.core.base.base_query_engine import BaseQueryEngine
      6 from llama_index.core.data_structs.data_structs import IndexStruct
      7 from llama_index.core.indices.base import BaseIndex

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py:17
     15 from llama_index.core.bridge.pydantic import Field
     16 from llama_index.core.callbacks.base import CallbackManager
---> 17 from llama_index.core.prompts.mixin import PromptDictType, PromptMixin
     18 from llama_index.core.schema import NodeWithScore, QueryBundle, QueryType
     20 logger = logging.getLogger(__name__)

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/prompts/__init__.py:4
      1 """Prompt class."""
      3 from llama_index.core.base.llms.types import ChatMessage, MessageRole
----> 4 from llama_index.core.prompts.base import (
      5     BasePromptTemplate,
      6     ChatPromptTemplate,
      7     LangchainPromptTemplate,
      8     Prompt,
      9     PromptTemplate,
     10     PromptType,
     11     SelectorPromptTemplate,
     12 )
     13 from llama_index.core.prompts.display_utils import display_prompt_dict
     15 __all__ = [
     16     "Prompt",
     17     "PromptTemplate",
   (...)
     25     "display_prompt_dict",
     26 ]

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/prompts/base.py:37
     29 from llama_index.core.base.query_pipeline.query import (
     30     ChainableMixin,
     31     InputKeys,
   (...)
     34     validate_and_convert_stringable,
     35 )
     36 from llama_index.core.bridge.pydantic import BaseModel
---> 37 from llama_index.core.llms.base import BaseLLM
     38 from llama_index.core.llms.generic_utils import (
     39     messages_to_prompt as default_messages_to_prompt,
     40 )
     41 from llama_index.core.llms.generic_utils import (
     42     prompt_to_messages,
     43 )

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/llms/base.py:21
     17 from llama_index.core.base.query_pipeline.query import (
     18     ChainableMixin,
     19 )
     20 from llama_index.core.bridge.pydantic import Field, validator
---> 21 from llama_index.core.callbacks import CallbackManager
     22 from llama_index.core.schema import BaseComponent
     25 class BaseLLM(ChainableMixin, BaseComponent):

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/callbacks/__init__.py:4
      2 from .llama_debug import LlamaDebugHandler
      3 from .schema import CBEvent, CBEventType, EventPayload
----> 4 from .token_counting import TokenCountingHandler
      5 from .utils import trace_method
      7 __all__ = [
      8     "CallbackManager",
      9     "CBEvent",
   (...)
     14     "trace_method",
     15 ]

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/callbacks/token_counting.py:6
      4 from llama_index.core.callbacks.base_handler import BaseCallbackHandler
      5 from llama_index.core.callbacks.schema import CBEventType, EventPayload
----> 6 from llama_index.core.utilities.token_counting import TokenCounter
      7 from llama_index.core.utils import get_tokenizer
     10 @dataclass
     11 class TokenCountingEvent:

File ~/miniconda3/envs/llama-index/lib/python3.11/site-packages/llama_index/core/utilities/token_counting.py:6
      1 # Modified from:
      2 # https://github.com/nyno-ai/openai-token-counter
      4 from typing import Any, Callable, Dict, List, Optional
----> 6 from llama_index.core.llms import ChatMessage, MessageRole
      7 from llama_index.core.utils import get_tokenizer
     10 class TokenCounter:

ImportError: cannot import name 'ChatMessage' from 'llama_index.core.llms' (unknown location)
Selection deleted

### Version

latest

### Steps to Reproduce

followed the text-to-sql guide https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo.html#define-sql-database

**Comment by logan-markewich** [comment]
That import is acutally correct, but I think you have some env issues.

try uninstalling and reinstalling

```
pip uninstall llama-index
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

Or installing in a fresh venv

```
<open fresh terminal>
python -m venv venv
source venv/bin/activate
pip install llama-index
```

Funny enough, while the import is correct, there is also a more logical (and shorter) import: `from llama_index.core.query_engine import NLSQLTableQueryEngine`
