### ISSUE TITLE
Ingested 0 Nodes: No nodes returned 

### ISSUE THREAD

**Issue by etetteh** [run-llama/llama_index#10948]
### Bug Description

I followed the [Building a Live RAG Pipeline over Google Drive Files](https://docs.llamaindex.ai/en/stable/examples/ingestion/ingestion_gdrive.html) to create my RAG Pipeline. 

However, I noticed that when the documents are unchanged and the pipeline is ran for the second time, no nodes are returned.

### Version

0.9.37

### Steps to Reproduce

Using the following tutorial without updating the documents:

[Building a Live RAG Pipeline over Google Drive Files](https://docs.llamaindex.ai/en/stable/examples/ingestion/ingestion_gdrive.html#building-a-live-rag-pipeline-over-google-drive-files)

**Comment by logan-markewich** [comment]
@etetteh this is by design. Since to documents have changed, there are no nodes to process. 

If a node did change, then it would be upsertted into the vector store

**Comment by etetteh** [comment]
How may I access and use my nodes, if no nodes are returned.
My main reason for using the pipeline is to utilize the `DocstoreStrategy.UPSERTS`  feature.  I need a way to automatically upsert new documents if they exist, or return existing old documents

**Comment by logan-markewich** [comment]
The nodes are already in your vector store 🤔

**Comment by logan-markewich** [comment]
If you need the nodes even though they are unchanged, you'd need to run it through an ingestion pipeline with no docstore or vector store attached

**Comment by etetteh** [comment]
Thank you so much. This is what I have done, but I notice it regenerates the embeddings which can be time and computationally inefficient:

```
db = chromadb.PersistentClient(
        path=persist_dir, 
        settings=Settings(anonymized_telemetry=False, is_persistent=True)
    )
    chroma_collection = db.get_or_create_collection(f"{persist_dir}_quickstart")
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    
    cache = IngestionCache(
        cache=ch.SimpleCache(),
        collection=f"{persist_dir}_cache"
    )
    
    docstore=ds.SimpleDocumentStore(
        namespace=f"{persist_dir}_document_store"
    )
        
    transformations=[node_parser]
    
    if use_title_extractor:
        transformations.append(
            TitleExtractor(
                llm=service_context.llm, node_template=title_template, num_workers=num_workers
            )
        )
    
    if use_summary_extractor:
        transformations.append(
            SummaryExtractor(
                llm=service_context.llm, prompt_template=summary_template, cache=cache, num_workers=num_workers
            )
        )
    
    transformations.append(service_context.embed_model)

    pipeline = IngestionPipeline(
        transformations=transformations,
        docstore=docstore,
        vector_store=vector_store,
        cache=cache,
        docstore_strategy=DocstoreStrategy.UPSERTS
    )
    
    index = VectorStoreIndex.from_vector_store(
        pipeline.vector_store,
        embed_model=service_context.embed_model,
        service_context=service_context,
    )

    nodes = pipeline.run(show_progress=True, documents=documents)
    
    if len(nodes) == 0 and pipeline.docstore is not None:
        pipeline.persist(f"{persist_dir}_pipeline")

        pipeline2 = IngestionPipeline(transformations = transformations)
        pipeline2.load(f"{persist_dir}_pipeline")
         
        nodes = pipeline2.run(show_progress=True, documents=documents)
        
    # leaf_nodes = get_leaf_nodes(nodes)

    # pipeline.docstore.add_documents(nodes)
    # pipeline.vector_store.add(leaf_nodes)
    return index, nodes

```

**Comment by logan-markewich** [comment]
You could remove the embeddings on the second run, if you don't actually need them 👍🏻  but looks good to me!

**Comment by etetteh** [comment]
I don't understand what you mean. My concern has to do with the regeneration of the embedding. I thought it would just be loaded from the persisted pipeline

**Comment by logan-markewich** [comment]
It is not -- the embeddings are in the vector store.

The by removing the docstore and vector store, the pipeline just blindly runs all the nodes. It's not aware of any vector store with existing embeddings.

You could keep the cache attached, or remove the embeddings from the transformations list.
