### ISSUE TITLE
[Bug]: postprocessor/rankGPT_rerank.py has wrong OpenAI import

### ISSUE THREAD

**Issue by philmui** [run-llama/llama_index#10964]
### Bug Description

llama_index/core/postprocessor/rankGPT_rerank.py includes this import on line 5:

> from llama_index.core.llms import LLM, ChatMessage, ChatResponse, OpenAI

For 0.10+, OpenAI should be imported from:

> from llama_index.core.llms.openai import OpenAI

### Version

0.10.6

### Steps to Reproduce

Import the following:

from llama_index.core.indices.postprocessor import SimilarityPostprocessor

Get the following error:

  File "/Users/user/anaconda3/envs/jarvis10/lib/python3.10/site-packages/llama_index/core/indices/postprocessor.py", line 19, in <module>
    from llama_index.core.postprocessor.rankGPT_rerank import RankGPTRerank
  File "/Users/user/anaconda3/envs/jarvis10/lib/python3.10/site-packages/llama_index/core/postprocessor/rankGPT_rerank.py", line 5, in <module>
    from llama_index.core.llms import LLM, ChatMessage, ChatResponse, OpenAI
ImportError: cannot import name 'OpenAI' from 'llama_index.core.llms' (/Users/user/anaconda3/envs/jarvis10/lib/python3.10/site-packages/llama_index/core/llms/__init__.py)

**Comment by logan-markewich** [comment]
@philmui actually, it seems like there is some duplicated code in `llama-index-core` -- `RankGPTRerank` should be installed from `pip install llama-index-post-processor-rankgpt-rerank`
