### ISSUE TITLE
[Bug]: Cannot create a KnowledgeGraphQueryEngine from Neo4jGraphStore

### ISSUE THREAD

**Issue by vicbotce** [run-llama/llama_index#10969]
### Bug Description

I was using a week ago the llama-index 0.9.46 and was working fine, but updated the library to use the new docs and now I can't make it work.

### Version

0.10.6

### Steps to Reproduce

!pip install llama-index
!pip install llama-index-graph-stores-neo4j

import os

from llama_index.core import StorageContext
from llama_index.graph_stores.neo4j import Neo4jGraphStore
from llama_index.core.query_engine import KnowledgeGraphQueryEngine

username=""
password=''
url=""
database=""
os.environ["OPENAI_API_KEY"] = ""

graph_store = Neo4jGraphStore(
        username=username,
        password=password,
        url=url,
        database=database,
    )

storage_context = StorageContext.from_defaults(graph_store=graph_store)

query_engine = KnowledgeGraphQueryEngine(
        storage_context=storage_context,
        llm=llm,
        verbose=True,
    )

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[10], line 1
----> 1 query_engine = KnowledgeGraphQueryEngine(
      2         storage_context=storage_context,
      3         llm=llm,
      4         verbose=True,
      5     )

File c:\Users\user\AppData\Local\anaconda3\envs\project\Lib\site-packages\llama_index\core\query_engine\knowledge_graph_query_engine.py:93, in KnowledgeGraphQueryEngine.__init__(self, llm, storage_context, graph_query_synthesis_prompt, graph_response_answer_prompt, refresh_schema, verbose, response_synthesizer, service_context, **kwargs)
     90 self._llm = llm or llm_from_settings_or_context(Settings, service_context)
     92 # Get Graph Store Type
---> 93 self._graph_store_type = GRAPH_STORE_CLASS_TO_GRAPH_STORE_TYPE[
     94     self.graph_store.__class__
     95 ]
     97 # Get Graph schema
     98 self._graph_schema = self.graph_store.get_schema(refresh=refresh_schema)

KeyError: <class 'llama_index.graph_stores.neo4j.base.Neo4jGraphStore'>
```

**Comment by vicbotce** [comment]
I want to work with the new 0.10.6 versie due that all the documentation of version 0.9.46 has been deleted so I can't continue my development with that version. I need to create a KnowledgeGraphQueryEngine with Neo4jGraphStore.

**Comment by logan-markewich** [comment]
FYI the documentation is not deleted.
