### ISSUE TITLE
[Bug]: token_counting.py has wrong imports

### ISSUE THREAD

**Issue by philmui** [run-llama/llama_index#10960]
### Bug Description

With the new 0.10 versions, line 6 imports are no longer valid.

The correct imports should be (according to the actual source in github):

from llama_index.core.llms.base import ChatMessage
from llama_index.core.base.llms.types import MessageRole

### Version

0.10.6

### Steps to Reproduce

Try to use:

>   from llama_index.llms.openai import OpenAI

One of the file that it tries to access is: 

  File "/Users/user/anaconda3/envs/jarvis/lib/python3.10/site-packages/llama_index/core/utilities/token_counting.py", line 6, in <module>
    from llama_index.core.llms.base import ChatMessage, MessageRole

**Comment by logan-markewich** [comment]
@philmui these imports work fine for me -- `from llama_index.core.llms import ChatMessage, MessageRole`

Please ensure you have a fresh venv perhaps? Any remnants of a pre-v0.10.x install will cause some issues

**Comment by logan-markewich** [comment]
Proof that a fresh venv works
https://colab.research.google.com/drive/1yv5HXWyJ00mkvsxdvHK0WMdglrfksy9x?usp=sharing

To create a new venv, I would open a new terminal and do

```
python -m venv venv
source venv/bin/activate
pip install llama-index
```
