### ISSUE TITLE
[Bug]: NameError: name 'torch' is not defined in llama-index-embeddings-clip

### ISSUE THREAD

**Issue by humpydonkey** [run-llama/llama_index#10978]
### Bug Description

Hi team,
I encountered a NameError raised from llama-index-embeddings-clip.
See the detailed stack trace here: https://github.com/run-llama/llama_index/pull/10974
Appreciate a review or alternative fix for this issue.

### Version

0.10.6

### Steps to Reproduce

Follow this tutorial: https://docs.llamaindex.ai/en/stable/examples/multi_modal/gpt4v_multi_modal_retrieval.html

### Relevant Logs/Tracbacks

```shell
https://github.com/run-llama/llama_index/pull/10974
```

**Comment by logan-markewich** [comment]
Fixed :)

**Comment by logan-markewich** [comment]
`pip install -U llama-index-embeddings-clip`
