### ISSUE TITLE
[Bug]: OpenAIEmbeddings is broken in 0.10.6

### ISSUE THREAD

**Issue by david1542** [run-llama/llama_index#10977]
### Bug Description

Hey everyone :)

I'm trying to store & embed some documents using OpenAI embeddings but the process seems to crash due to an illegal assignment to the embed_model object.

This is what I'm trying to do in my code (llama-index==0.10.6):
```python
vector_store = PineconeVectorStore(
    pinecone_index=pc_index, namespace=organization_id
)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
embed_model = OpenAiEmbedding(
    api_key=openai_api_key,
    api_base=OPENAI_API_BASE,
    api_version=OPENAI_API_VERSION,
    model="text-embedding-3-large",
    dimensions=768,
)

VectorStoreIndex.from_documents(
    documents,
    vector_store=pc_index,
    show_progress=True,
    embed_model=embed_model,
    storage_context=storage_context,
)
```

The error I'm seeing:
```
llama_index\core\embeddings\utils.py", line 134, in resolve_embed_model
    embed_model.callback_manager = callback_manager or Settings.callback_manager
TypeError: "OpenAiEmbedding" is immutable and does not support item assignment
```

It seems to be a bug in the `resolve_embed_model` function. Can anyone verify that?

### Version

0.10.6

### Steps to Reproduce

Use OpenAIEmbeddings like in the example I provided and it should crash 🐵

### Relevant Logs/Tracbacks

```shell
llama_index\core\embeddings\utils.py", line 134, in resolve_embed_model
    embed_model.callback_manager = callback_manager or Settings.callback_manager
TypeError: "OpenAiEmbedding" is immutable and does not support item assignment
```
```

**Comment by logan-markewich** [comment]
What is `OpenAiEmbedding` ? Isn't it `OpenAIEmbedding`

This works for me 

```python
>>> from llama_index.embeddings.openai import OpenAIEmbedding
>>> from llama_index.core import Document, VectorStoreIndex
>>> embed_model = OpenAIEmbedding(model="text-embedding-3-large", dimensions=768)
>>> index = VectorStoreIndex.from_documents([Document.example()], embed_model=embed_model)
```

**Comment by fearfulsteel420** [comment]
I’m also facing issues with OpenAIEmbedding. Getting a connection error every time. Increasing the timeout doesn’t seem to have any effect. Follow the code below to replicate.

```
from llama_index.embeddings.openai import OpenAIEmbedding

embed_model=OpenAIEmbedding(model="text-embedding-3-small",dimensions=256, timeout=60)

embeddings = embed_model.get_text_embedding(
    "I’ve tried increasing timeouts and max tries as well but that doesn’t seem to help"
)
```

**Comment by logan-markewich** [comment]
@fearfulsteel420  Any details on the connection error? I cannot replicate

**Comment by logan-markewich** [comment]
`LocalProtocolError: Illegal header value b'Bearer '` -- this means that there is no Bearer token, which means the API key is missing.

Probably we could catch this and give a more informative error. A PR for another day :) Gladd it works!

**Comment by david1542** [comment]
@logan-markewich Thank you so much. Seems like I imported `OpenAiEmbedding` from `llama_index_client` instead of `OpenAIEmbedding` from `llama_index`

**Comment by logan-markewich** [comment]
Glad we got that cleared up!
