### ISSUE TITLE
[Bug]: AzureOpenAI callback_manager type error

### ISSUE THREAD

**Issue by yilmazozgur** [run-llama/llama_index#10988]
### Bug Description

I am using AzureOpenAI 

```
from llama_index.legacy.llms import AzureOpenAI
llm = AzureOpenAI(
        model="gpt-35-turbo",
        ...
        ...

```

It creates the object without an error but when I try to use it with a ReactAgent and send a chat request, I get an error.

```
agent = ReActAgent.from_tools(tools, llm=llm, service_context=service_context, context=system_prompt,
                                      callback_manager=llm.callback_manager, verbose=True)
response = agent.chat(text_input)
```

Here is the error: 
`Cannot use llm_chat_callback on an instance without a callback_manager attribute.`

The type of the callback is not accepted. It expects a core CallbackManager object but it is a legacy CallbackManager object. 

### Version

0.10.7

### Steps to Reproduce

Install the latest version of Llamaindex (0.10.6 or 0.10.7)
Use AzureOpenAI LLM.
Create an agent.
Start chat.
It will throw an error about callback manager.

**Comment by logan-markewich** [comment]
@yilmazozgur either you need to use all `legacy` imports or none at all

**Comment by logan-markewich** [comment]
For non-legacy, I would just do 

```
pip install llama-index llama-index-llms-azure-openai llama-index-embeddings-azure-openai
```

```
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
```
