### ISSUE TITLE
[Feature Request]: add 'pg_trgm' search to postgres vector store

### ISSUE THREAD

**Issue by andreaw-ag** [run-llama/llama_index#10985]
### Feature Description

Hello, I am trying to implement multilingual hybrid search using llama index and the postgres vector store.
Currently, the single-language stemmer in the default implementation limits search capabilities. Leveraging pg_trgm, a trusted PostgreSQL module, would offer efficient text matching based on trigram similarity.

Even if pgroonga seems the [state-of-the-art](https://pgroonga.github.io/reference/pgroonga-versus-textsearch-and-pg-trgm.html), pg_trgm is a trusted module (https://www.postgresql.org/docs/16/pgtrgm.html) and I expect it to be easier to install and mantain 

Considering pg_trgm's ease of installation and maintenance, it provides a practical solution for expanding search functionality.

I'm eager to contribute to this improvement and willing to implement it if there's community interest.

### Reason

The current implementation works nicely when using Postgres' full text search only one language (for query/indexing/retrieval).

However, searching in multiple languages would require either to accept very simplified tokenizer ('simple') or to mantain cumbersome (concatenated) or multiple indexes.

### Value of Feature

I think this could be valuable, possibly as an option to have a better form of "hybrid multilingual search", which seems very difficult to achieve otherwise. Postgres has a very large user base and hybrid search is known for best performance.

**Comment by juleskuehn** [comment]
Yes, please do this! The Postgres text search is unusable right now.

**Comment by andreaw-ag** [comment]
Hey @juleskuehn , thanks you for the link. Saved a lot of time.
So, pg_trgm seems not a really scalable solution. I think it may even get worse for my specific use case (multilingual text + somewhat long text fields to index ranging from 1000 to 2000 chars).

What I ended up doing is using standard postgres keyword search with exact match ('simple') but - instead of running the full user query through the DB I extract relevant keyword first (e.g. "how can I learn to code in python" -> "learn code python").
This is a suboptimal (and a temporary) solution as it tends to produce a few matches of decent quality (if any): I expect good precision but bad recall. In practice, this works sufficiently well when combined with semantic search.

I expect this approach to be even better when the following will be addressed.
https://github.com/run-llama/llama_index/issues/10580


I would be super interested to hear your thoughts.

**Comment by juleskuehn** [comment]
No, I'm just evaluating options right now. I am making a CLIR test set with English and French equivalent chunks of Canadian laws. Hoping to evaluate the different Postgres options using that :)

If I run out of time I will probably do the same thing you are doing, that is, using "simple" for the language. Thanks for the tip!

There are some other interesting ideas here: https://stackoverflow.com/questions/21288591/full-text-search-index-on-a-multilingual-column

My PR which changes "AND" back to "OR" is merged in now, so hopefully you will better recall (but worse precision :P) now!
