### ISSUE TITLE
[Bug]: LlamaIndex taking too long i.e like about 20-30 minutes to bring back a response.

### ISSUE THREAD

**Issue by Stephen-Echessa** [run-llama/llama_index#10984]
### Bug Description

My RAG implementation takes about 20-30 minutes before bringing a response. Whenever I use a pdf containing 190 pages or even when I use a pdf containing 5 pages, it still takes a really long time to generate a response. I am not sure whether it is a bug or simply my laptop lacking the required requirements. When I started using LlamaCPP or Llama Index, my_query.query() function would take only like 2-5 minutes to run. However it's like with each run thereafter, it only took longer.

My laptop is a Dell Inspiron 3521 with an 8gb RAM, no dedicated GPU,an Intel 3rd Gen Core processor, core i3 with 4cores with processing power of 1.9GHz.

I would really appreciate it if someone could tell me what is wrong.

### Version

llama-index v0.10.5

### Steps to Reproduce

Running query_parser.query(question) function.

**Comment by logan-markewich** [comment]
llama.cpp in general is very slow. Especially without leveraging a GPU (I'm not sure if llama.cpp works on intel CPUs?)

I recommend using ollama for a more optimized time (or as optimized as it can be on your machine)

**Comment by jvel07** [comment]
@abhim1509 do you have any tutorials for each point you mentioned, please?

**Comment by DarshanDeloitte** [comment]
It is taking longer then expected time (more then 5mins for simple query!) with Azure env (AISearch, GPT-4o and text-embedding-ada-002)
Why is it happening, it was working smoothly few hours back and suddenly started taking time. what could be the issue and how can i solve it?
