### ISSUE TITLE
[Bug]: IMPORT ERROR

### ISSUE THREAD

**Issue by kindler-king** [run-llama/llama_index#10991]
### Bug Description

So suddenly my project stopped working complaining it could not find SimpleDirectoryReader.
I created a virtual environment , you can see the versions displayed in pip list.

Then the import statement: from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
Is throwing the error you can see below. I tried downgrading and reinstalling but I am getting this issue.

![2](https://github.com/run-llama/llama_index/assets/53633591/175560c3-cd20-474e-a222-288f75e345d8)
![1](https://github.com/run-llama/llama_index/assets/53633591/2c39c782-70aa-4d29-9996-d95703135c5b)

Any idea why this is happening? I tried this on another system and this error isn't happening but just on my system.

### Version

0.10.7

### Steps to Reproduce

Created a FRESH VIRTUAL environment.
Did a pip install llama-index

**Comment by logan-markewich** [comment]
@kindler-king did you mix legacy imports with normal imports? Need to be all legacy or all new imports (similar to pydantic v1/v2, if you ever had to deal with that)

**Comment by kindler-king** [comment]
Hello @logan-markewich , thanks for the quick response.
I was trying to upgrade my 0.9.13 to 0.1.7 the latest version and played around with different import statements, where I might have been trying to import the wrong stuff.

But currently all I want to do (as a test) is to try and import this line:
**from llama_index.core import VectorStoreIndex, SimpleDirectoryReader**

I tried this on my PC with the same exact dependencies in a virtual environment and it works, but when I reproduce the environment on my laptop, and try the above import statement, it returns that error.

**Comment by logan-markewich** [comment]
@kindler-king do you maybe have it installed globally outside of a venv?

Try this in a fresh terminal 

```
pip uninstall llama-index. # remove any global
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by kindler-king** [comment]
Hey @logan-markewich , you were right, it was a clash between legacy imports and new imports.
I set up a virtual environment, installed llama-index and then migrated to the new imports by following the docs, 1 at a time.

Most of the imports are working, however the only one I haven't been able to resolve is this one:
![image](https://github.com/run-llama/llama_index/assets/53633591/9d35608b-85b4-4f09-9a30-751e1eaa80a3)

Any idea why **from llama_index.llms.openai import OpenAI** is raising this error?
Thanks a lot :D

**Comment by logan-markewich** [comment]
Try `pip install -U llama-index-core llama-index-llms-openai llama-index-embeddings-openai`
