### ISSUE TITLE
[Bug]: Cannot authorize OpenAI API key when using KnowledgeGraphIndex

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#10993]
### Bug Description

I'm following the tutorial from https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html to create a KG index. However, the KG index keeps complaining about not able to find an API key.

Although I see ``INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"`` from the terminal when creating the index, I saw the following error once I clicked into the chat completion link so that the KG is not correctly constructed.

```
{
    "error": {
        "message": "You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.",
        "type": "invalid_request_error",
        "param": null,
        "code": null
    }
}
```

### Version

0.10.6

### Steps to Reproduce

!pip install llama-index-llms-azure-openai
!pip install llama-index-graph-stores-nebula
!pip install llama-index-llms-openai
!pip install llama-index-embeddings-azure-openai
!pip install ipython-ngql nebula3-python
!pip install llama-index==0.10.6
```
import os

os.environ["OPENAI_API_KEY"] = "<API_KEY>"

import logging
import sys

logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output


from llama_index.llms.openai import OpenAI
from llama_index.core import Settings

Settings.llm = OpenAI(temperature=0, model="gpt-3.5-turbo")
Settings.chunk_size = 512


os.environ["NEBULA_USER"] = "root"
os.environ["NEBULA_PASSWORD"] = "nebula"  # default is "nebula"
os.environ[
    "NEBULA_ADDRESS"
] = "127.0.0.1:9669"  # assumed we have NebulaGraph installed locally

space_name = "llamaindex"
edge_types, rel_prop_names = ["relationship"], [
    "relationship"
] 
tags = ["entity"] 


from llama_index.core import StorageContext
from llama_index.graph_stores.nebula import NebulaGraphStore

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

from llama_index.core import SimpleDirectoryReader

documents = SimpleDirectoryReader("./paul_graham_essay/data").load_data()

from llama_index.core import KnowledgeGraphIndex

index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=2,
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
    show_progress=True,
)
```

**Comment by nerdai** [comment]
Hey @mw19930312 are you using azure-openai or just openai?

**Comment by mw19930312** [comment]
@nerdai I'm using openai only. I've provided a minimal code snippet.

**Comment by mw19930312** [comment]
@nerdai Thanks for the reply. I think this is a red herring that if I pdb into the code, then I will see the triplets being parsed. How do I check whether the KG is correctly stored in NebularGraph? I was not able to query the graph since I always saw there is no relation found.

**Comment by logan-markewich** [comment]
@mw19930312 you'd have to query nebula in their little console, or view the graph in the UI I think? tbh I've never used nebula much haha

**Comment by nerdai** [comment]
> @nerdai I'm using openai only. I've provided a minimal code snippet.

yes sorry, my bad. Okay, and just to confirm you are filling in that value for OPENAI_API_KEY?

**Comment by mw19930312** [comment]
@logan-markewich Thanks for the reply! I think there might be some gaps between how we index and how we query the graph engine. Basically, I can check my index_struct is a well-prepared KG. However, when I tried to query, the retrieval part returns nothing with ``INFO:llama_index.core.indices.knowledge_graph.retrievers:> No relationships found, returning nodes found by keywords.`` I can also check the document nodes exist by checking ``index.storage_context.docstore.docs``. How can I verify which part went wrong?

Here are my codes:
```
import logging
import sys

logging.basicConfig(
    stream=sys.stdout, level=logging.INFO
)  # logging.DEBUG for more verbose output


# define LLM
from llama_index.llms.openai import OpenAI
from llama_index.core import Settings

Settings.llm = OpenAI(temperature=0, model="gpt-3.5-turbo")
Settings.chunk_size = 512

import os

os.environ["NEBULA_USER"] = "root"
os.environ["NEBULA_PASSWORD"] = "nebula"  # default is "nebula"
os.environ[
    "NEBULA_ADDRESS"
] = "127.0.0.1:9669"  # assumed we have NebulaGraph installed locally

space_name = "llamaindex"
edge_types, rel_prop_names = ["relationship"], [
    "relationship"
]  # default, could be omit if create from an empty kg
tags = ["entity"]  # default, could be omit if create from an empty kg


from llama_index.core import StorageContext
from llama_index.graph_stores.nebula import NebulaGraphStore

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

from llama_index.core import SimpleDirectoryReader

# documents = SimpleDirectoryReader("./paul_graham_essay/data").load_data()
documents = SimpleDirectoryReader("./TA_example").load_data()

from llama_index.core import KnowledgeGraphIndex

from llama_index.core import KnowledgeGraphIndex
from llama_index.core.node_parser import SentenceWindowNodeParser

# create the sentence window node parser w/ default settings
node_parser = SentenceWindowNodeParser.from_defaults(
    window_size=1,
    window_metadata_key="window",
    original_text_metadata_key="original_text",
)

# NOTE: can take a while!
index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=2,
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
    transformations=[node_parser],
)

import pdb; pdb.set_trace()

query_engine = index.as_query_engine()

response = query_engine.query("Tell me more about asylum seekers")
```

**Comment by mw19930312** [comment]
@logan-markewich My code pretty much calculated the graph and query it using llama_index only. If I'm understanding it correctly, the KG has not been pushed to NebularGraph store yet, right?

**Comment by mw19930312** [comment]
Closing this issue since the major question is addressed.

**Comment by logan-markewich** [comment]
@mw19930312 I thiiiink it should be pushed to nebula as soon as the index is created (admittedly again, I've hard used nebula, but it seemed to work in my short testing today)
