### ISSUE TITLE
[Bug]: GithubRepositoryReader uses re-runs event loop

### ISSUE THREAD

**Issue by david1542** [run-llama/llama_index#11009]
### Bug Description

Hey everyone,

I'm trying to use `GithubRepositoryReader` inside an async function to read some files from my repo but I get the following exception:
```bash
\.pyenv\pyenv-win\versions\3.10.5\lib\asyncio\base_events.py", line 582, in _check_running   
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```
This happens inside `GithubRepositoryReader` itself, at line 256:
```python
branch_data: GitBranchResponseModel = self._loop.run_until_complete(
    self._github_client.get_branch(
        self._owner, self._repo, branch, timeout=self._timeout
    )
)
```

Seems like the code is trying to re-run the event loop instead of using async & await and pass the control to the outer code. Can anyone verify this as well? 

Maybe we can add a separate function called `load_data_async` that will simply use async & await?

### Version

0.10.6

### Steps to Reproduce

Use `GithubRepositoryReader` inside an async code. Namely

```python
import asyncio
async def main():
    loader = GithubRepositoryReader(...)
    documents = loader.load_data(...)

if __name__ == "__main__":
    asyncio.run(main())
```

### Relevant Logs/Tracbacks

```shell
File "python/lib/site-packages/llama_index/readers/github/repository/base.py", line 296, in load_data
    return self._load_data_from_branch(branch)
File "python/lib/site-packages/llama_index/readers/github/repository/base.py", line 256, in _load_data_from_branch
    branch_data: GitBranchResponseModel = self._loop.run_until_complete(
File "python/lib/asyncio/base_events.py", line 622, in run_until_complete
    self._check_running()
File "python/lib/asyncio/base_events.py", line 582, in _check_running
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by david1542** [comment]
Okay I found a [reference](https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo.html) to using `nest_asyncio` in the docs, and it seems to workaround this issue:
```python
import nest_asyncio
nest_asyncio.apply()
```

I think a better design, though, would be to use async & wait and let the consumers control & manage the event loop. Would love to hear what you think :)

**Comment by logan-markewich** [comment]
@david1542 async introduces a lot of weird stuff for dev UX.

If any changes are made, I would prefer dedicated sync vs. async entry points.

This leads to some code-duplication, which can sometimes be ok. To avoid code duplication, some places in the codebase use `asyncio.run(async_func())` for the sync entry point.

In any case, using nest_asyncio is what I would have recommended :)

**Comment by david1542** [comment]
Hi, I wanted to re-open this issue since `nest_asyncio` doesn't seem to work with FastAPI. I still get this error:
```bash
RuntimeError: This event loop is already running
```

I tried to follow the solution proposed [here](https://stackoverflow.com/a/74071421/6025929), which is to call `nest_asyncio.apply()` before `uvicorn.run`, however I still get this error.

**Comment by rohanliston** [comment]
I've got the same error trying to use `GitHubRepositoryReader` from a [FastHTML](https://fastht.ml/) app (which I believe is very similar to FastAPI) and haven't been able to use it from within an `async` method.

I tried using `nest_asyncio`, but got `ValueError: Can't patch loop of type <class 'uvloop.Loop'>`.
