### ISSUE TITLE
[Question]: Is relation between nodes being thrown away when constructing KG using KnowledgeGraphIndex?

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#11000]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm following the tutorial of knowledge graph query engine https://docs.llamaindex.ai/en/latest/examples/query_engine/knowledge_graph_query_engine.html#. I have some questions regarding the KG index being constructed.

From this line of code
https://github.com/run-llama/llama_index/blob/fbc32773dcdc92078441e36f086e730dc62c4114/llama-index-core/llama_index/core/indices/knowledge_graph/base.py#L236, it seems that after the triplet is parsed using llm, only the subject and object are pushed to the table. Is the relation between these two nodes thrown away?

Below is a KG that I created following the tutorial.  If I'm understanding it correctly, ultimately the index_struct will be a key-node dictionary only?

```
KG(index_id='0c5db4cf-a946-4282-a762-43ff15da1bd9'
 summary=None
 table={'Reviews': {'1d8ac0c3-9b61-4748-973b-d03de8be28fe'
 '175a26a3-84cd-4cd7-82af-f7412209cffa'
 '9413d2cf-bfc9-496d-a55e-1ed06c246841'
 'e7c91a47-10ac-45b7-8106-1a2a4a6e06b0'}
 'Political preferences': {'175a26a3-84cd-4cd7-82af-f7412209cffa'}
 'Ethical differences': {'175a26a3-84cd-4cd7-82af-f7412209cffa'}
 'Travel experiences': {'67c12b5a-584b-4294-bab2-1985c2d73b40'}
 'Deeply personal': {'67c12b5a-584b-4294-bab2-1985c2d73b40'}
 'Perspectives': {'67c12b5a-584b-4294-bab2-1985c2d73b40'}
 'Commentary': {'d9864ebf-20a3-4e18-b5d0-f25bdb4ca804'}
 'Rant': {'d9864ebf-20a3-4e18-b5d0-f25bdb4ca804'}
 'Owner or employees': {'d9864ebf-20a3-4e18-b5d0-f25bdb4ca804'}
 'Experience': {'d9864ebf-20a3-4e18-b5d0-f25bdb4ca804'
 '8921abfd-cb89-4bec-b81e-b14234bf64ee'}
 'We': {'799801ff-c287-4fc0-b409-4bd7d64eeadd'
 '1df8d035-b783-4f46-8b79-d677d44c16bc'}
 'Comments and advice': {'1df8d035-b783-4f46-8b79-d677d44c16bc'}
 'Personal travel experience': {'1df8d035-b783-4f46-8b79-d677d44c16bc'}
 'Business': {'42d6667f-291f-407f-9122-724bee77e483'
 '73b73083-ba76-4b5f-85b0-c529ede03217'
 '1df8d035-b783-4f46-8b79-d677d44c16bc'
 '017cc16d-c086-4796-aef1-5f172c37b6fd'}
 'Customs': {'1df8d035-b783-4f46-8b79-d677d44c16bc'}
 'Travel': {'1df8d035-b783-4f46-8b79-d677d44c16bc'}
 'Hotel': {'376361f0-77f2-488c-b436-6e9091729695'}
 'Local laws': {'376361f0-77f2-488c-b436-6e9091729695'}
 'Owner behavior': {'376361f0-77f2-488c-b436-6e9091729695'}
 'Violence': {'27251970-a930-4354-affb-20cea08cad2f'}
 'Refugees': {'27251970-a930-4354-affb-20cea08cad2f'}
 'Terrorist activity': {'27251970-a930-4354-affb-20cea08cad2f'}
 'Asylum seekers': {'9413d2cf-bfc9-496d-a55e-1ed06c246841'}
 'Location': {'9413d2cf-bfc9-496d-a55e-1ed06c246841'}
 'Easily': {'9413d2cf-bfc9-496d-a55e-1ed06c246841'}
 'Tripadvisor': {'e50e51b1-9282-415b-88b4-7a5750de36db'}
 'Supporter of refugees': {'e50e51b1-9282-415b-88b4-7a5750de36db'}
 'Acts of violence': {'e50e51b1-9282-415b-88b4-7a5750de36db'}
 'Review': {'30a3bf4e-abd7-4577-8035-bbc6b60a6e71'
 '7c7811d9-e827-4e8f-b95a-3e2df27b65bc'
 '8921abfd-cb89-4bec-b81e-b14234bf64ee'
 'ec646e60-c14b-4bc1-88eb-e61c8c772483'}
 'Substantial information': {'7c7811d9-e827-4e8f-b95a-3e2df27b65bc'}
 'Additional information': {'7c7811d9-e827-4e8f-b95a-3e2df27b65bc'}
 'Context': {'1d8ac0c3-9b61-4748-973b-d03de8be28fe'}
 'Bubble rating': {'1d8ac0c3-9b61-4748-973b-d03de8be28fe'}
 '1 to 5': {'1d8ac0c3-9b61-4748-973b-d03de8be28fe'}
 'File_path': {'31690a2d-e5da-4b18-8312-77eee64bebba'}
 'Ta_example/example1.txt': {'31690a2d-e5da-4b18-8312-77eee64bebba'}
 'You': {'73b73083-ba76-4b5f-85b0-c529ede03217'}
 'Aspect': {'73b73083-ba76-4b5f-85b0-c529ede03217'}
 'Excessive commentary': {'8921abfd-cb89-4bec-b81e-b14234bf64ee'}
 'Owner': {'8921abfd-cb89-4bec-b81e-b14234bf64ee'}
 'Fraudulent': {'e7c91a47-10ac-45b7-8106-1a2a4a6e06b0'}
 'Information': {'e7c91a47-10ac-45b7-8106-1a2a4a6e06b0'}
 'Incidents of fraud': {'017cc16d-c086-4796-aef1-5f172c37b6fd'}
 'Email': {'017cc16d-c086-4796-aef1-5f172c37b6fd'}
 'Contentintegrity@tripadvisor.com': {'017cc16d-c086-4796-aef1-5f172c37b6fd'}
 'Contact': {'799801ff-c287-4fc0-b409-4bd7d64eeadd'}
 'Fraud-related questions': {'799801ff-c287-4fc0-b409-4bd7d64eeadd'}
 'Businesses relevant to travelers': {'799801ff-c287-4fc0-b409-4bd7d64eeadd'}
 'Property': {'c0d9c728-66fe-4412-91ff-93d46fa56adc'
 'ec646e60-c14b-4bc1-88eb-e61c8c772483'
 '22d8d519-65f1-4679-986a-340b2cfd55c6'}
 'Listed business': {'ec646e60-c14b-4bc1-88eb-e61c8c772483'}
 'Submit': {'42d6667f-291f-407f-9122-724bee77e483'}
 'New listing': {'42d6667f-291f-407f-9122-724bee77e483'}
 'Requirements': {'c0d9c728-66fe-4412-91ff-93d46fa56adc'}
 'Here': {'c0d9c728-66fe-4412-91ff-93d46fa56adc'}
 'Function': {'c0d9c728-66fe-4412-91ff-93d46fa56adc'}
 'Travelers': {'22d8d519-65f1-4679-986a-340b2cfd55c6'}
 'Helpful': {'22d8d519-65f1-4679-986a-340b2cfd55c6'}
 'Regular part': {'22d8d519-65f1-4679-986a-340b2cfd55c6'}
 'Special event parking': {'30a3bf4e-abd7-4577-8035-bbc6b60a6e71'}
 'Example': {'30a3bf4e-abd7-4577-8035-bbc6b60a6e71'}}
 rel_map={}
 embedding_dict={})
```

**Comment by logan-markewich** [comment]
subj and obj are treated as keywords for retrieval

the relationship is still in the graph store, and when triplets are retrieved, the full triplet is sent to the LLM

**Comment by mw19930312** [comment]
@logan-markewich Would you mind referring me how I can get the relationship in the graph store? I tried to use

```
query_engine = index.as_query_engine()

response = query_engine.query("Tell me more about asylum seekers")
```
However, I'm always told that there is no relationship found. I can check that ``asylum seekers`` is a keyword in the index_struct.

**Comment by logan-markewich** [comment]
Likely its not doing a great job at extracting keywords for the query

You can do `rel_map = graph_store.get_rel_map(subj_list, depth=2, limit=30)`

**Comment by mw19930312** [comment]
Thanks! I'm able to get the relations now.

How do I improve the query performance? I saw that the retrieve code is wrapped in different classes for a couple of times. Is there any attribute I can set to customize the retrieve metrics?

**Comment by logan-markewich** [comment]
I think probably using the `KnowledgeGraphRagRetriever` will give much better results

**Comment by mw19930312** [comment]
Do you have a quick code example?

**Comment by mw19930312** [comment]
OK I think I've figured out what went wrong. The default search method is based on keywords. The keyword was stored as "Asylum seekers" so that it fails to recognize "asylum seeker" as a keyword. It might be better to use embedding as a search strategy. How should I enable it? Is ``KnowledgeGraphRagRetriever `` automatically searching based on embeddings?

**Comment by logan-markewich** [comment]
KG RAG retriever:
https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html#perform-graph-rag-query


Using embeddings with the base retriever 
https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/KnowledgeGraphDemo.html#query-with-embeddings

**Comment by mw19930312** [comment]
@logan-markewich Thanks! Just an FYI, the KG RAG retriever is not retrieving the correct entities as well so that it always returns an empty response. Using embeddings with base helps finding the entities. But somehow the generation results are not satisfying enough that it does not incorporate the relations found in the KG.

**Comment by anhthyngo** [comment]
> @logan-markewich Thanks! Just an FYI, the KG RAG retriever is not retrieving the correct entities as well so that it always returns an empty response. Using embeddings with base helps finding the entities. But somehow the generation results are not satisfying enough that it does not incorporate the relations found in the KG.

I'm also having the issue where my KG RAG retriever is always returning an empty list.

Specifically doing something like this:

```
llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])
storage_context = StorageContext.from_defaults(graph_store=neo4j_graph_store)

graph_rag_retriever = KnowledgeGraphRAGRetriever(
    storage_context=storage_context,
    verbose=True,
    with_nl2graphquery=False,
    callback_manager=callback_manager
)

graph_rag_retriever.retrieve('<Question here>')
```

Did you figure out why you were getting an empty response?
