### ISSUE TITLE
[Feature Request]: keep global params where query pipeline run

### ISSUE THREAD

**Issue by dl942702882** [run-llama/llama_index#11008]
### Feature Description

i need to  keep some params in the pipeline, and output them where query finished
how can i do?

### Reason

for example:
when pipleline finish rerank, i wanna do some filtering like relevancy  threshold
so i create a post node processor. but when i filter them, i still need to remember which are filterd；
i need to output this filtered nodes to evaluate;

_No response_

**Comment by logan-markewich** [comment]
@dl942702882 I think you can create a custom node postprocessor to wrap an existing postprocessor and record any details you want

https://docs.llamaindex.ai/en/stable/module_guides/querying/node_postprocessors/root.html#id2

```
from llama_index.core import QueryBundle
from llama_index.core.postprocessor import BaseNodePostprocessor
from llama_index.core.schema import NodeWithScore


class WrappedNodePostprocessor(BaseNodePostprocessor):
    def __init__(self, node_postprocesor: BaseNodePostprocessor) -> None:
        self._postprocessor = node_postprocesor

    def _postprocess_nodes(
        self, nodes: List[NodeWithScore], query_bundle: Optional[QueryBundle]
    ) -> List[NodeWithScore]:
        <record input nodes somewhere?>
        return self._postprocessor.postprocess_nodes(nodes, query_bundle=query_bundle)
```

**Comment by dl942702882** [comment]
i finally use query_bundle, it is a request life time  object; code seems like this:
`
from dataclasses import dataclass
from typing import Optional, List

from llama_index.schema import NodeWithScore, QueryBundle

@dataclass
class QAContext(QueryBundle):
    recall_items: Optional[List[NodeWithScore]] = None

`

and i use my self-define class  as this:
`
 custom_query_bundle = QAContext(query_str=question)
 
`

and when i want to record some request level variables, the code is 

`
        if isinstance(query_bundle, QAContext):
            query_bundle.recall_items = nodes


`
