### ISSUE TITLE
[Question]: llamaindex bypasses the custom knowledge base

### ISSUE THREAD

**Issue by hyb1234hi** [run-llama/llama_index#11007]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

llamaindex bypasses the custom knowledge base, how to solve it?

**Comment by hyb1234hi** [comment]
@dosu-bot,First of all thanks for your reply, but sorry I still haven't solved the LlamaIndex bypass knowledge base issue. My code only has a few lines. Can you help me figure out what the problem is? code show as below.
import os.path
from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
)

# check if storage already exists
PERSIST_DIR = "./storage"
if not os.path.exists(PERSIST_DIR):
    # load the documents and create the index
    documents = SimpleDirectoryReader("data").load_data()
    index = VectorStoreIndex.from_documents(documents)
    # store it for later
    index.storage_context.persist(persist_dir=PERSIST_DIR)
else:
    # load the existing index
    storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR)
    index = load_index_from_storage(storage_context)

# Either way we can now query the index
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)

**Comment by logan-markewich** [comment]
@hyb1234hi this is mostly a prompt engineering thing

By default, its instructed to only use the provided context. Not every LLM follows these instructions every time

You can see here how to edit prompts
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts
