### ISSUE TITLE
[Documentation]: Llama Demo Notebook: Tool + Memory module (Notebook not available)

### ISSUE THREAD

**Issue by danialmecja** [run-llama/llama_index#11004]
### Documentation Issue Description

Looking for solutions in the docs regarding integration with Langchain agents and memory modules. Found a useful primer on the topic in the documentation. However, the notebook link for the above use case leads to a 404. Wondering if there's an actual notebook for the titled use case?

### Documentation Link

https://docs.llamaindex.ai/en/stable/community/integrations/using_with_langchain.html#/api_reference/langchain_integrations/base.rst

**Comment by logan-markewich** [comment]
The notebook got removed since it used a lot of deprecated stuff. I should remove this link :)

If you want to use llama-index with langchain, just wrap a query engine as a tool in langchain (not a langchain expert, but I think this isn't too bad to do)

**Comment by danialmecja** [comment]
Alrighty, thanks for the tip 🙏🏻
