### ISSUE TITLE
[Question]: Does it usually take a long time to construct a KG index?

### ISSUE THREAD

**Issue by SuperYG1991** [run-llama/llama_index#11006]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Problem Statement:
When I tried to construct a KG index to implement Graph RAG, but it took several hours at the constructing KG from documents step and still running. Actually, there are only 32 documents(load from 3 small PDF files). I guess it should be abnormal.

### Environment：

Python 3.10.13
GPU:NVIDIA V100 (16G)
ubuntu 22.04

**Using a local LLM and a local embedding model：**

`loader=SimpleDirectoryReader("./data")
documents=loader.load_data()

os.environ['NEBULA_USER'] = "root"
os.environ['NEBULA_PASSWORD'] = "nebula" 
os.environ['NEBULA_ADDRESS'] = "127.0.0.1:9669" 

space_name = "movies"
edge_types, rel_prop_names = ["relationship"], ["relationship"]
tags = ["entity"]
graph_store = NebulaGraphStore(space_name=space_name,
                               edge_types=edge_types,
                               rel_prop_names=rel_prop_names,
                               tags=tags)

storage_context = StorageContext.from_defaults(graph_store=graph_store)

SYSTEM_PROMPT = """You are an AI assistant that answers questions in a friendly manner, based on the given source documents. 
"""

query_wrapper_prompt = PromptTemplate(
    "[INST]<<SYS>>\n" + SYSTEM_PROMPT + "<</SYS>>\n\n{query_str}[/INST] "
)

embedding_model = HuggingFaceEmbedding(model_name= './model/bge-large-en-v1.5') 
llm = HuggingFaceLLM(
    model_name="./model/zephyr-7b-alpha",
    tokenizer_name="./model/zephyr-7b-alpha",
    query_wrapper_prompt=query_wrapper_prompt,
    context_window=3900,
    max_new_tokens=256,
    # model_kwargs={"quantization_config": quantization_config},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.7, "top_k": 50, "top_p": 0.95},
    # messages_to_prompt=messages_to_prompt,
    device_map="auto"
)`

**Stuck cell**

`gs_path = "./storage/graph_store"
kg_index = KnowledgeGraphIndex.from_documents(documents,
                                              storage_context=storage_context,
                                              max_triplets_per_chunk=5,
                                              service_context=service_context,
                                              space_name=space_name,
                                              edge_types=edge_types,
                                              rel_prop_names=rel_prop_names,
                                              tags=tags,
                                              include_embeddings=True)
kg_index.storage_context.persist(persist_dir=gs_path)`

![1708396573035](https://github.com/run-llama/llama_index/assets/34837189/a064fe99-2433-4048-bdea-eea39187ea8c)

**Comment by logan-markewich** [comment]
@SuperYG1991 nah thats about right. Extracting triplets over every chunk of data is a ton of processing for an LLM. Plus I see you are using a local LLM, which will be even slower than OpenAI 😅 

If you want faster speeds, look into using something like vLLM or TGI
