### ISSUE TITLE
[Bug]: There is no "Settings" from "llama_index.core"

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#11012]
### Bug Description

About **Example: Using a Custom LLM Model - Advanced** in https://docs.llamaindex.ai/en/latest/module_guides/models/llms/usage_custom.html，
The code `from llama_index.core import Settings` is failed.
It seems that some change occurred in `llama_index.core` that differs from the example.

### Version

0.9.39

### Steps to Reproduce

1. pip install llama-index==0.9.39
2. `from llama_index.core import Settings`

**Comment by logan-markewich** [comment]
@Hspix that import is only available in v0.10.x

If you want to upgrade
```
pip uninstall llama-index
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

Migration guide here as well
https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77
