### ISSUE TITLE
Query Engine - What should be used :  input_type="search_document". or serach_query

### ISSUE THREAD

**Issue by anantwag19** [run-llama/llama_index#11017]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

     When iam inserting in Vector db , Iam using the same Embed_model as    input_type="search_document". below Code where iam also retrieving the query engine where iam using the same embedmodel , Iam still gettting response .Should i use the  input_type="search_query"  which one is better and why ?

      embed_model = CohereEmbedding(
        cohere_api_key=cohere_api_key,
        model_name="embed-english-v3.0",
        input_type="search_document"
   
        )
        service_context = ServiceContext.from_defaults(
        llm=llm, embed_model=embed_model)

        # load storage context
        load_storage_context = StorageContext.from_defaults(persist_dir=index_persist_dir)

        # load index
        loaded_index = load_index_from_storage(
        storage_context=load_storage_context, service_context=service_context
        )

        query_engine = loaded_index.as_query_engine(
        node_postprocessors = [cohere_rerank]
        )

**Comment by logan-markewich** [comment]
search query should be used for queries, and search document for ingesting data

tbh the embedding class could maybe be doing this automatically
