### ISSUE TITLE
[Question]:  llama_index.embeddings.huggingface -> ImportError: cannot import name 'AsyncInferenceClient'

### ISSUE THREAD

**Issue by changjiale** [run-llama/llama_index#11019]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

from llama_index.embeddings.huggingface import HuggingFaceEmbedding

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[70], line 1
----> 1 from llama_index.embeddings.huggingface import HuggingFaceEmbedding

File /usr/local/anaconda3/lib/python3.10/site-packages/llama_index/embeddings/huggingface/__init__.py:1
----> 1 from llama_index.embeddings.huggingface.base import (
      2     HuggingFaceEmbedding,
      3     HuggingFaceInferenceAPIEmbedding,
      4     HuggingFaceInferenceAPIEmbeddings,
      5 )
      7 __all__ = [
      8     "HuggingFaceEmbedding",
      9     "HuggingFaceInferenceAPIEmbedding",
     10     "HuggingFaceInferenceAPIEmbeddings",
     11 ]

File /usr/local/anaconda3/lib/python3.10/site-packages/llama_index/embeddings/huggingface/base.py:5
      2 import logging
      3 from typing import TYPE_CHECKING, Any, Callable, Dict, List, Optional, Sequence, Union
----> 5 from huggingface_hub import (
      6     AsyncInferenceClient,
      7     InferenceClient,
      8     model_info,
      9 )
     10 from huggingface_hub.hf_api import ModelInfo
     11 from llama_index.core.base.embeddings.base import (
     12     DEFAULT_EMBED_BATCH_SIZE,
     13     BaseEmbedding,
     14     Embedding,
     15 )

ImportError: cannot import name 'AsyncInferenceClient' from 'huggingface_hub' (/usr/local/anaconda3/lib/python3.10/site-packages/huggingface_hub/__init__.py)

python version error?

**Comment by changjiale** [comment]
env detail:
➜  ~ pip show llama_index
Name: llama-index
Version: 0.10.7
Summary: Interface between LLMs and your data
Home-page: https://llamaindex.ai
Author: Jerry Liu
Author-email: jerry@llamaindex.ai
License: MIT
Location: /usr/local/anaconda3/lib/python3.10/site-packages
Requires: llama-index-agent-openai, llama-index-core, llama-index-embeddings-openai, llama-index-legacy, llama-index-llms-openai, llama-index-multi-modal-llms-openai, llama-index-program-openai, llama-index-question-gen-openai, llama-index-readers-file

**Comment by nerdai** [comment]
Hi @changjiale I believe this is virtual environment kind of issue. I just tried `from llama_index.embeddings.huggingface import HuggingFaceEmbedding` on a fresh virtual env that installed both `llama-index` (v0.10) and `llama-index-embeddings-huggingface` and it worked.

Can you please try using a fresh environment:

```
# venv
python -m venv venv
source venv/bin/activate
pip install llama-index

# or if using conda
conda create -n venv python=3.11 anaconda # can use any Python 3.9 - 3.12 
conda activate venv
pip install llama-index
```

OR, if not using virtual environments at all, please try to uninstall and re-install llama-index on global interpreter
```
pip uninstall llama-index
pip install llama-index --upgrade
```

(Though, we do recommend that you use a virtual env)

**Comment by logan-markewich** [comment]
(it might also be an issue with the huggingface-hub package, you may have to upgrade it)

**Comment by pwagner1000** [comment]
After updating the huggingface-hub  package end up in a pip circular dependency deadlock.  
llama-index-readers-file 0.1.6 requires pypdf<5.0.0,>=4.0.1, but you have pypdf 3.17.4 which is incompatible.
...
pymemgpt 0.3.4 requires pypdf<4.0.0,>=3.17.1, but you have pypdf 4.0.2 which is incompatible.

**Comment by logan-markewich** [comment]
You can usually ignore pip dependency issues if you are using pip directly.

Seems like the issue is not hughingface hub but pymemgpt?

**Comment by pwagner1000** [comment]
Sure, though it was run w/ the debug option, there isn't anything in the log.

**Comment by pwagner1000** [comment]
Any other thoughts on what to try?

**Comment by logan-markewich** [comment]
No idea 🤷🏻 maybe start with a new venv I guess?

**Comment by pwagner1000** [comment]
Sure, must be something else going on as I've tried that route too. :(
