### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.vector_stores'

### ISSUE THREAD

**Issue by raoofnaushad** [run-llama/llama_index#11027]
### Bug Description

I'm working on a Python project involving embeddings and vector storage, and I'm trying to integrate llama_index for its vector storage capabilities with PostgreSQL. However, I'm encountering a ModuleNotFoundError when attempting to import PGVectorStore from llama_index.vector_stores. Here's the snippet of code that's causing the issue:

`from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.vector_stores.postgres import PGVectorStore

nest_asyncio.apply()`

The error I recieve is: `ModuleNotFoundError: No module named 'llama_index.vector_stores'`

### Version

llama-index==0.10.7

### Steps to Reproduce

Install this package of llama-index
`llama-index==0.10.7
llama-index-agent-openai==0.1.1
llama-index-core==0.10.7
llama-index-embeddings-openai==0.1.3
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.2
llama-index-multi-modal-llms-openai==0.1.1
llama-index-program-openai==0.1.2
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
llamaindex-py-client==0.1.13`

And run the below code
`from llama_index.vector_stores.chroma import ChromaVectorStore
`

**Comment by raoofnaushad** [comment]
@dosu-bot Thanks

Here I again changed my import statement to `from llama_index.vector_stores import PGVectoRsStore`
Still I am getting the error: `ModuleNotFoundError: No module named 'llama_index.vector_stores'`

And I am not trying to install `pip install llama-index-vector-stores-chroma`, I want the postgres or pgvector for this.

**Comment by Isaac-AC** [comment]
Maybe this helps 

https://docs.llamaindex.ai/en/stable/examples/vector_stores/postgres.html#create-the-index

pip install llama-index-vector-stores-postgres

**Comment by raoofnaushad** [comment]
@dosu-bot 

Thanks the bug is resolved. I needed to install `pip install llama-index-vector-stores-postgres` similar to what you suggested.
