### ISSUE TITLE
[Question]: How to contribute to llamaindex?

### ISSUE THREAD

**Issue by DJC-GO-SOLO** [run-llama/llama_index#11026]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to reproduce a paper (https://arxiv.org/abs/2304.14732) using llamaindex and release it as a tool in the llamaindex library. What should I do?

**Comment by nerdai** [comment]
Awesome! Please check out our [contributing guide](https://github.com/run-llama/llama_index/blob/main/CONTRIBUTING.md), section 2 is on contributing packs is most relevant likely here. 

In short, try implementing the paper as a llama-pack, which would constitute building your own pypi package. We have a CLI tool plus some lightweight instructions in that guide to get you started!
