### ISSUE TITLE
[Bug]: AttributeError: 'NotionPageReader' object has no attribute 'token'

### ISSUE THREAD

**Issue by AggelosTh** [run-llama/llama_index#11024]
### Bug Description

When trying to load documents from Notion using the `NotionPageReader`, it throws the following error:
**AttributeError: 'NotionPageReader' object has no attribute 'token'**. 
Indeed, the `NotionPageReader` doesn't have an attribute called 'token'. Instead it has a class attribute with the name 'token' as it can clearly be seen in the code [here](https://github.com/run-llama/llama_index/blob/bad3afa8ba5d43b4b2f8d81d8e04bf7d6f52f9b0/llama-index-integrations/readers/llama-index-readers-notion/llama_index/readers/notion/base.py#L17):
![image](https://github.com/run-llama/llama_index/assets/62294403/5e7064ae-70d6-4dd8-b306-f4955ce455bb)

### Version

Version: 0.10.7

### Steps to Reproduce

The error can be easily reproduced by executing:
`pip3 install llama-index-readers-notion` in the terminal and in a python code:
``` python
from llama_index.readers.notion import NotionPageReader
documents = NotionPageReader(integration_token=integration_token).load_data(page_ids=page_ids)
```
where integration token is a string notion integration token and page_ids is a list of notion page ids.

### Relevant Logs/Tracbacks

```shell
AttributeError: 'NotionPageReader' object has no attribute 'token'
```

**Comment by logan-markewich** [comment]
Fixed in `llama-index-readers-notion=0.1.5`
