### ISSUE TITLE
[Feature Request]: Add additional metrics to METRIC_REGISTRY for Retrieval and support for different K-s

### ISSUE THREAD

**Issue by hkristof03** [run-llama/llama_index#11030]
### Feature Description

Hi, thanks for this awesome library.

I found a few (for me) inconsistencies in the evaluation across modules.

The `RetrievalEvaluator `only supports Hit Rate and MRR (and Cohere, which is paid).

https://github.com/run-llama/llama_index/blob/ccc0b85a19eba681657f2615540e5ddfd6152505/llama-index-core/llama_index/core/evaluation/retrieval/evaluator.py#L19

https://github.com/run-llama/llama_index/blob/ccc0b85a19eba681657f2615540e5ddfd6152505/llama-index-core/llama_index/core/evaluation/retrieval/metrics.py#L130

At the same time BeirEvaluator supports NDCG, MAP, Recall and Precision at different K-s.

https://github.com/run-llama/llama_index/blob/ccc0b85a19eba681657f2615540e5ddfd6152505/llama-index-core/llama_index/core/evaluation/benchmarks/beir.py#L100

Although, BEIR supports additional metrics as well.

https://github.com/beir-cellar/beir/blob/f062f038c4bfd19a8ca942a9910b1e0d218759d4/beir/retrieval/evaluation.py#L94

So my questions are:

1. For the `RetrievalEvaluator `why do you only support MRR and Hit Rate, and not NDCG, MAP, Recall and Precision, at different K-s?
2. For BEIR, why don't you support the additional metrics?
3. Are you planning to add these metrics to the `METRIC_REGISTRY` ?

Thanks!

### Reason

Only basic metrics are supported for Retrieval, independent of K retrieved documents.

### Value of Feature

Additional metrics would give greater insights to the Retrieval and Ranking.

**Comment by aoezdTchibo** [comment]
It is a pity that there are no explicit plans for the integration of further metrics like MAP@K or NDCG@K, as I now have to implement these metrics locally myself, although I would like to use the `RetrievalEvaluator` OOTB...

**Comment by hkristof03** [comment]
@aoezdTchibo I solved by getting the `"embedding_dict"` keys (node ids) and the embeddings (values) from the vector store's `".to_dict()"` method, then getting the node id - doc id map from the `"text_id_to_ref_doc_id"` from the `"embedding_dict"`, then creating my own faiss index and evaluating the retrieval using the retrieval component of [Torchmetrics](https://lightning.ai/docs/torchmetrics/stable/). Sounds complicated but not that much in implementation. Although I had to write several workarounds for this library to be able to test the RAG system Retrieval component (and its components) on several datasets. For experimentation and extensive evaluation the LlamaIndex is not yet set up.

**Comment by aoezdTchibo** [comment]
@hkristof03 Thanks for the link to Touchmetrics! I hadn't heard of this before and it looks very promising.

**Comment by AgenP** [comment]
Hey @hkristof03,

Quick note incase you are still interested

My PR was recently merged for adding a MRR@K and HitRate@K option, through usage of a "use_granular_..." attribute

So we now have more native flexibility for our evals

Hopefully you find it valuable  💪

**Comment by aoezdTchibo** [comment]
@AgenP Could you add a link to the PR? Thanks!

**Comment by DarkLight1337** [comment]
I have implemented these metrics over these PRs:

- #14100
- #14170
- #14189

The number of documents passed to the query determines the `K` value for recall, precision and NDCG. As for mAP, you can compute AP for each query and average out the results. May this help you in your endeavours!

**Comment by aclifton314** [comment]
@DarkLight1337 this is exactly what I was looking for and just in time! Thank you for your efforts and for putting this together.

Is there current documentation on how to use mAP or examples I could pull from?

**Comment by DarkLight1337** [comment]
You can find a simple example [here](https://docs.llamaindex.ai/en/stable/examples/evaluation/retrieval/retriever_eval/?h=retrieval+evaluation).
