### ISSUE TITLE
[Bug]: 'AgentChatResponse' object has no attribute 'print_response_stream'

### ISSUE THREAD

**Issue by pcisterna** [run-llama/llama_index#11031]
### Bug Description

I'm running docs/examples/customization/streaming/chat_engine_condense_question_stream_response.ipynb but response_stream.print_response_stream() get the error: 

`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[9], [line 1](vscode-notebook-cell:?execution_count=9&line=1)
----> [1](vscode-notebook-cell:?execution_count=9&line=1) response_stream.print_response_stream()

AttributeError: 'AgentChatResponse' object has no attribute 'print_response_stream'`

### Version

0.10.7

### Steps to Reproduce

run docs/examples/customization/streaming/chat_engine_condense_question_stream_response.ipynb

**Comment by nerdai** [comment]
Thanks @pcisterna for raising. Should be a quick fix. We should be using `chat_engine.stream_chat()` throughout the nb rather than just `chat_engine.chat()`. I've submitted the PR.

**Comment by pcisterna** [comment]
thank you!
