### ISSUE TITLE
[Bug]: Getting module not found error for llama_index.core.llms.generic_utils

### ISSUE THREAD

**Issue by rudrakhsha-c** [run-llama/llama_index#11036]
### Bug Description

I am getting the below error
```
Traceback (most recent call last):
  File "/home/ubuntu/rudy/openai_chat1.py", line 6, in <module>
    from llama_index.llms.openai import OpenAI
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 36, in <module>
    from llama_index.core.llms.generic_utils import (
ModuleNotFoundError: No module named 'llama_index.core.llms.generic_utils'
```
when i am using llama-index version 0.10.6 or 0.10.7 or any further versions after that.
I even tried it using a new virtual environment but an facing the same issue in the env, 
Can someone help ASAP? There seem to be multiple releases within a span of 5-10 mins.

### Version

0.10.6

### Steps to Reproduce

install llama index version 0.10.6
run some code with openai llm.
Getting the below error
Traceback (most recent call last):
  File "/home/ubuntu/rudy/openai_chat1.py", line 6, in <module>
    from llama_index.llms.openai import OpenAI
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 36, in <module>
    from llama_index.core.llms.generic_utils import (
ModuleNotFoundError: No module named 'llama_index.core.llms.generic_utils'

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/ubuntu/rudy/openai_chat1.py", line 6, in <module>
    from llama_index.llms.openai import OpenAI
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/__init__.py", line 1, in <module>
    from llama_index.llms.openai.base import AsyncOpenAI, OpenAI, SyncOpenAI, Tokenizer
  File "/home/ubuntu/anaconda3/envs/tempenv/lib/python3.11/site-packages/llama_index/llms/openai/base.py", line 36, in <module>
    from llama_index.core.llms.generic_utils import (
ModuleNotFoundError: No module named 'llama_index.core.llms.generic_utils'
```

**Comment by rudrakhsha-c** [comment]
@logan-markewich thanks!

**Comment by logan-markewich** [comment]
@rudrakhsha-c ok, I think it should be working, can you try running the above upgrade command and see if it resolves the issue?

**Comment by rudrakhsha-c** [comment]
@logan-markewich yes, its working now. Thanks a lot.

**Comment by MudassirAqeelAhmed** [comment]
I'm still getting it,

```
!pip install openai langchain langchain-openai langchain-experimental pinecone-client tiktoken unstructured pypdf semantic-router loguru pdf2image pdfminer pdfminer.six nest_asyncio -q
!pip install llama-index-core llama-index-llms-openai llama-index-embeddings-openai llama-index-embeddings-anyscale --upgrade
```

This is how I'm importing 

`from llama_index.embeddings.anyscale import AnyscaleEmbedding`


---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-17-6245d537c86e>](https://localhost:8080/#) in <cell line: 21>()
     19 from langchain_core.documents import Document
     20 from langchain.vectorstores.utils import maximal_marginal_relevance
---> 21 from llama_index.embeddings.anyscale import AnyscaleEmbedding
     22 from itertools import islice
     23 from typing import Iterable, Iterator, List, TypeVar, Dict, Tuple, Union, Optional

2 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/embeddings/anyscale/utils.py](https://localhost:8080/#) in <module>
      1 from typing import Optional, Tuple
      2 
----> 3 from llama_index.core.llms.generic_utils import get_from_param_or_env
      4 
      5 DEFAULT_ANYSCALE_API_BASE = "https://api.endpoints.anyscale.com/v1"

ModuleNotFoundError: No module named 'llama_index.core.llms.generic_utils'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by MudassirAqeelAhmed** [comment]
> !pip install llama-index-core llama-index-llms-openai llama-index-embeddings-openai llama-index-embeddings-anyscale --upgrade

!pip install llama-index-core llama-index-llms-openai llama-index-embeddings-openai llama-index-embeddings-anyscale --upgrade

this is how i am doing it, i have tried with multiple ways

**Comment by logan-markewich** [comment]
@MudassirAqeelAhmed you are missing the -U option

**Comment by logan-markewich** [comment]
@MudassirAqeelAhmed it looks like you are running in a notebook? You need to restart the runtime for env changes to take effect.
