### ISSUE TITLE
[Question]: Offline use of embed_model 

### ISSUE THREAD

**Issue by jithinmukundan** [run-llama/llama_index#11047]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it possible to download an embed model, copy that model to an offline server and then use it in the llama_index python code running there? If yes, what is to be mentioned in the service_context to point to the downloaded embed_model? I am struggling to make the offline setup as I cannot find any documentation regarding this.

**Comment by logan-markewich** [comment]
The bot is correct -- you can point the model to the cache, or download the weights yourself and give the path in the `model_name` arugment

**Comment by yslemondrops** [comment]
My error is:
ValueError: tokenizer_name is deprecated. Please remove it from the arguments.
