### ISSUE TITLE
[Bug]: unable to use gemini llm

### ISSUE THREAD

**Issue by hemanth** [run-llama/llama_index#11046]
### Bug Description

<img width="1359" alt="image" src="https://github.com/run-llama/llama_index/assets/18315/fddc5872-653d-452d-a20f-438fd4db2769">

### Version

v0.10.8

### Steps to Reproduce

```
%pip install llama-index-multi-modal-llms-gemini
%pip install llama-index-vector-stores-qdrant
%pip install llama-index-embeddings-gemini
%pip install llama-index-llms-gemini
```

```py

from llama_index.llms.gemini import Gemini

llm = Gemini()
resp = llm.stream_complete(
    "The story of Sourcrust, the bread creature, is really interesting. It all started when..."
)
```

**Comment by hatianzhang** [comment]
@hemanth hi, I just tried locally using the latest pkg. seems working fine for me
![image](https://github.com/run-llama/llama_index/assets/2142132/0d3a416b-62eb-40ea-8d34-426908f36731)

from error log it seems to be related to your account. Are you in the region Gemini open to?

**Comment by hemanth** [comment]
The issue is back. 

@hatianzhang Were you using keys generated from ai stuido or did you have a gcloud project?

**Comment by hemanth** [comment]
<img width="792" alt="image" src="https://github.com/run-llama/llama_index/assets/18315/5e3c4ab4-c462-4173-96a2-4546faf3ff1b">

**Comment by hemanth** [comment]
The API key had domain restrictions 😓
