### ISSUE TITLE
[Question]: OpenAI Authentication Error with ToolRetrieverRouterQueryEngine while using local LLM with more than 1 Query Engine Tool

### ISSUE THREAD

**Issue by dkatz123** [run-llama/llama_index#11061]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am getting some curious behavior in a query engine tool using ToolRetrieverRouterQueryEngine.

I am using a local LLM and not OpenAI, and I supply an incorrect OpenAI key to make sure OpenAI isn’t being used.  I’ve verified that my local LLM (Llama2cpp) is indeed receiving and processing my requests.

Here’s the code demonstrating the issue.  When I comment out the code corresponding to either the list_query_engine/list_tool or vector_query_engine/vector_tool, things work as expected, with no OpenAI Authentication Error.  However, when I include both of these tools, I get the Authentication Error.  Does having more than one tool trigger the OpenAI chat model, but not just having one tool?  How can I fix this so I can run multiple tools with my local LLM?

from llama_index.core import SummaryIndex
product_summary_index = SummaryIndex(nodes=product_docs,llm=myllm)
product_vector_index = VectorStoreIndex(nodes=product_docs,llm=myllm)

from llama_index.core.tools import QueryEngineTool
from llama_index.core.question_gen import LLMQuestionGenerator
question_gen = LLMQuestionGenerator.from_defaults(llm=myllm)

list_query_engine = product_summary_index.as_query_engine(
  response_mode="tree_summarize", llm=myllm, question_gen=question_gen,use_async=True
)
vector_query_engine = product_vector_index.as_query_engine(
    response_mode="tree_summarize", llm=myllm, question_gen=question_gen,use_async=True
)

list_tool = QueryEngineTool.from_defaults(
    query_engine=list_query_engine,
    description="Useful for questions asking for background on the product",
)
vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description=(
        "Useful for retrieving specific snippets about the product"
    ),
)

from llama_index.core import VectorStoreIndex
from llama_index.core.objects import ObjectIndex, SimpleToolNodeMapping

tool_mapping = SimpleToolNodeMapping.from_objects([list_tool, vector_tool])
obj_index = ObjectIndex.from_objects(
    [list_tool, vector_tool],
    #[list_tool],
    tool_mapping,
    VectorStoreIndex,
)

from llama_index.core.query_engine import ToolRetrieverRouterQueryEngine
query_engine = ToolRetrieverRouterQueryEngine(obj_index.as_retriever())

response = query_engine.query("Tell me about the product’s performance considerations.")

----------------------------------------TRACEBACK-----------------------------------
AuthenticationError                       Traceback (most recent call last)
Cell In[58], line 1
----> 1 response = query_engine.query("Tell me about the product’s performance considerations.")

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\base\base_query_engine.py:40, in BaseQueryEngine.query(self, str_or_query_bundle)
     38 if isinstance(str_or_query_bundle, str):
     39     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 40 return self._query(str_or_query_bundle)

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\query_engine\router_query_engine.py:361, in ToolRetrieverRouterQueryEngine._query(self, query_bundle)
    358     responses.append(query_engine.query(query_bundle))
    360 if len(responses) > 1:
--> 361     final_response = combine_responses(
    362         self._summarizer, responses, query_bundle
    363     )
    364 else:
    365     final_response = responses[0]

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\query_engine\router_query_engine.py:55, in combine_responses(summarizer, responses, query_bundle)
     52     source_nodes.extend(response_obj.source_nodes)
     53     response_strs.append(str(response))
---> 55 summary = summarizer.get_response(query_bundle.query_str, response_strs)
     57 if isinstance(summary, str):
     58     return Response(response=summary, source_nodes=source_nodes)

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\response_synthesizers\tree_summarize.py:166, in TreeSummarize.get_response(self, query_str, text_chunks, **response_kwargs)
    164 else:
    165     if self._output_cls is None:
--> 166         response = self._llm.predict(
    167             summary_template,
    168             context_str=text_chunks[0],
    169             **response_kwargs,
    170         )
    171     else:
    172         response = self._llm.structured_predict(
    173             self._output_cls,
    174             summary_template,
    175             context_str=text_chunks[0],
    176             **response_kwargs,
    177         )

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\llms\llm.py:239, in LLM.predict(self, prompt, **prompt_args)
    237 if self.metadata.is_chat_model:
    238     messages = self._get_messages(prompt, **prompt_args)
--> 239     chat_response = self.chat(messages)
    240     output = chat_response.message.content or ""
    241 else:

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\core\llms\callbacks.py:93, in llm_chat_callback.<locals>.wrap.<locals>.wrapped_llm_chat(_self, messages, **kwargs)
     84 with wrapper_logic(_self) as callback_manager:
     85     event_id = callback_manager.on_event_start(
     86         CBEventType.LLM,
     87         payload={
   (...)
     91         },
     92     )
---> 93     f_return_val = f(_self, messages, **kwargs)
     95     if isinstance(f_return_val, Generator):
     96         # intercept the generator and add a callback to the end
     97         def wrapped_gen() -> ChatResponseGen:

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\llms\openai\base.py:237, in OpenAI.chat(self, messages, **kwargs)
    235 else:
    236     chat_fn = completion_to_chat_decorator(self._complete)
--> 237 return chat_fn(messages, **kwargs)

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\llama_index\llms\openai\base.py:296, in OpenAI._chat(self, messages, **kwargs)
    294 client = self._get_client()
    295 message_dicts = to_openai_message_dicts(messages)
--> 296 response = client.chat.completions.create(
    297     messages=message_dicts,
    298     stream=False,
    299     **self._get_model_kwargs(**kwargs),
    300 )
    301 openai_message = response.choices[0].message
    302 message = from_openai_message(openai_message)

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\openai\_utils\_utils.py:275, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    273             msg = f"Missing required argument: {quote(missing[0])}"
    274     raise TypeError(msg)
--> 275 return func(*args, **kwargs)

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\openai\resources\chat\completions.py:663, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, presence_penalty, response_format, seed, stop, stream, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
    611 @required_args(["messages", "model"], ["messages", "model", "stream"])
    612 def create(
    613     self,
   (...)
    661     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    662 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 663     return self._post(
    664         "/chat/completions",
    665         body=maybe_transform(
    666             {
    667                 "messages": messages,
    668                 "model": model,
    669                 "frequency_penalty": frequency_penalty,
    670                 "function_call": function_call,
    671                 "functions": functions,
    672                 "logit_bias": logit_bias,
    673                 "logprobs": logprobs,
    674                 "max_tokens": max_tokens,
    675                 "n": n,
    676                 "presence_penalty": presence_penalty,
    677                 "response_format": response_format,
    678                 "seed": seed,
    679                 "stop": stop,
    680                 "stream": stream,
    681                 "temperature": temperature,
    682                 "tool_choice": tool_choice,
    683                 "tools": tools,
    684                 "top_logprobs": top_logprobs,
    685                 "top_p": top_p,
    686                 "user": user,
    687             },
    688             completion_create_params.CompletionCreateParams,
    689         ),
    690         options=make_request_options(
    691             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    692         ),
    693         cast_to=ChatCompletion,
    694         stream=stream or False,
    695         stream_cls=Stream[ChatCompletionChunk],
    696     )

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\openai\_base_client.py:1200, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1186 def post(
   1187     self,
   1188     path: str,
   (...)
   1195     stream_cls: type[_StreamT] | None = None,
   1196 ) -> ResponseT | _StreamT:
   1197     opts = FinalRequestOptions.construct(
   1198         method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1199     )
-> 1200     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\openai\_base_client.py:889, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    880 def request(
    881     self,
    882     cast_to: Type[ResponseT],
   (...)
    887     stream_cls: type[_StreamT] | None = None,
    888 ) -> ResponseT | _StreamT:
--> 889     return self._request(
    890         cast_to=cast_to,
    891         options=options,
    892         stream=stream,
    893         stream_cls=stream_cls,
    894         remaining_retries=remaining_retries,
    895     )

File ~\AppData\Local\anaconda3\envs\test\Lib\site-packages\openai\_base_client.py:980, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    977         err.response.read()
    979     log.debug("Re-raising status error")
--> 980     raise self._make_status_error_from_response(err.response) from None
    982 return self._process_response(
    983     cast_to=cast_to,
    984     options=options,
   (...)
    987     stream_cls=stream_cls,
    988 )

AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: dsf. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

**Comment by dkatz123** [comment]
Thanks, Logan -- but I actually do create these global settings earlier in the code.  I just didn't paste them in the issue:

**_embed_model = HuggingFaceEmbedding(model_name="sentence-transformers/all-mpnet-base-v2", max_length=512)
myllm=OpenAI(
               api_key="xxxx",
               api_base="http://xxx.xxx.xxx.xxx:yyyy/",  
               temperature=0,
            )
Settings.llm = myllm
Settings.embed_model=embed_model_**

And the local LLM does actually generate a response when I remove either the vector_tool or the list_tool from the definition, so that I'm only running a single tool.  But when there are both tool choices available, I get the OpenAI authentication error. Do you think dosu-bot is onto something with the async access and rate limiting?  I tried with both async=True and async=False, but both generated the authentication error. 

Regards,
David

**Comment by JSv4** [comment]
I am seeing similar behavior that may be related.

I am creating a `RouterQueryEngine` with several `RetrieverQueryEngines` as multiple `query_engine_tools` and an `LLMSingleSelector`.

This works most of the time, but, when I ask a question that would seem to invoke two query engine tools, I get this weird behavior where the library defaults to OpenAI instead of Azure (and throws an error as I have no valid key registered as I don't want to use OpenAI). 

When this behavior is triggering, here's part of the traceback that may help track this down:

```
Traceback (most recent call last):
  File "/home/jsv4/source/*/generate_index_cassette.py", line 92, in <module>
    problem_query = query_engine.query("Can you create a summary outline of all sections of the document and include "
  File "/home/jsv4/.pyenv/versions/*/lib/python3.10/site-packages/llama_index/core/base/base_query_engine.py", line 40, in query
    return self._query(str_or_query_bundle)
  File "/home/jsv4/.pyenv/versions/*/lib/python3.10/site-packages/llama_index/core/query_engine/router_query_engine.py", line 183, in _query
    final_response = combine_responses(
  File "/home/jsv4/.pyenv/versions/*/lib/python3.10/site-packages/llama_index/core/query_engine/router_query_engine.py", line 55, in combine_responses
    summary = summarizer.get_response(query_bundle.query_str, response_strs)
  File "/home/jsv4/.pyenv/versions/*/lib/python3.10/site-packages/llama_index/core/response_synthesizers/tree_summarize.py", line 166, in get_response
    response = self._llm.predict(
  File "/home/jsv4/.pyenv/versions/*/lib/python3.10/site-packages/llama_index/core/llms/llm.py", line 253, in predict
    chat_response = self.chat(messages)
    ```

I am seeing this behavior pre `v0.10.1` and post `v0.10.1`.  I notice both my traceback and the one above mention `tree_summarize.py` and I wonder if there may be some shared issue there? I found this issue by searching for that module with a description of my problem.

**Comment by JSv4** [comment]
Ok, I am closer to knowing what's up in my case, at least. So, in the RouterQueryEngine` definition, if you don't provide a value to the llm parameter (even if it's in your service context and you provide a ServiceContext), you get a TreeSummarizer with llm set to None (It _does_ get the ServiceContext, but more on this later):

https://github.com/run-llama/llama_index/blob/b4bd168cedf52e2b45e67a9badc8ee8635f817c7/llama-index-core/llama_index/core/query_engine/router_query_engine.py#L91-L126

Now, if we look further down to the `_query` method of the `RouterQueryEngine` you see this:

https://github.com/run-llama/llama_index/blob/b4bd168cedf52e2b45e67a9badc8ee8635f817c7/llama-index-core/llama_index/core/query_engine/router_query_engine.py#L163-L187

So **only if there is more than one response** (which explains why the behavior is intermittent), the engine tres to call `combine_responses(...)`, defined here:

https://github.com/run-llama/llama_index/blob/b4bd168cedf52e2b45e67a9badc8ee8635f817c7/llama-index-core/llama_index/core/query_engine/router_query_engine.py#L39-L62

Now the TreeSummarizer uses its `self._llm` attribute to prompt the LLM for a combination:

https://github.com/run-llama/llama_index/blob/b4bd168cedf52e2b45e67a9badc8ee8635f817c7/llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py#L141-L179

What is weird, though, is `self._llm` should be set if we pass a valid service context:

https://github.com/run-llama/llama_index/blob/b4bd168cedf52e2b45e67a9badc8ee8635f817c7/llama-index-core/llama_index/core/response_synthesizers/base.py#L53-L77

Nevertheless, the fix for me was providing the llm named argument to RouterQueryEngine. Based on the trace I did above, I don't think it's the intent (or wasn't pre v0.10.1) to have to provide llm if you provided a service_context argument.

**Comment by knyga** [comment]
I am getting issues with action_input:

```
from llama_index.core.tools.ondemand_loader_tool import OnDemandLoaderTool
from llama_index.readers.wikipedia import WikipediaReader
from llama_index.llms.openai import OpenAI
from langchain.agents import initialize_agent
from typing import List
from pydantic import BaseModel

llm = OpenAI(temperature=0, model_name="gpt-4", streaming=True)
reader = WikipediaReader()
tool = OnDemandLoaderTool.from_defaults(
    reader,
    name="Wikipedia Tool",
    description="A tool for loading and querying articles from Wikipedia",
)
lc_tool = tool.to_langchain_structured_tool(verbose=True)

from langchain.agents import initialize_agent
from langchain.chat_models import ChatOpenAI

llm = ChatOpenAI(temperature=0, model_name="gpt-4", streaming=True)

agent = initialize_agent(
    [lc_tool],
    llm=llm,
    agent="react-docstore",
    verbose=True,
)
agent.run("How old will the president of the United States be in February 2024?")
```

Output:
```
> Entering new AgentExecutor chain...
Thought: To answer this question, I need to know who the current president of the United States is and their birth date. I can use the Wikipedia Tool to find this information.
Action:
```
{
  "action": "Wikipedia Tool",
  "action_input": {
    "pages": ["List of presidents of the United States"]
  }
}
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[/tmp/ipykernel_53349/157342931.py](https://localhost:8080/#) in <cell line: 1>()
----> 1 agent.run("How old will the president of the United States be in February 2024?")

16 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/core/tools/ondemand_loader_tool.py](https://localhost:8080/#) in _parse_args(self, *args, **kwargs)
    119     def _parse_args(self, *args: Any, **kwargs: Any) -> Tuple[str, List[Document]]:
    120         if self._query_str_kwargs_key not in kwargs:
--> 121             raise ValueError(
    122                 "Missing query_str in kwargs with parameter name: "
    123                 f"{self._query_str_kwargs_key}"

ValueError: Missing query_str in kwargs with parameter name: query_str
```

On some queries it works fine.

**Comment by logan-markewich** [comment]
Seems like the LLM is not predicting the correct input to the tool ?
