### ISSUE TITLE
[Bug]: Cannot Install llama-index 0.10+ Docker

### ISSUE THREAD

**Issue by turit0** [run-llama/llama_index#11060]
### Bug Description

Hi, my docker was running perfectly until the last update of version 0.10. Now, when I want to build it, it throws this error:

16.71   × Preparing metadata (pyproject.toml) did not run successfully.
subprocess.CalledProcessError: Command 'cd /tmp/pip-install-cb92xvq6/pymupdf_d00dc26c49b341ad8292f14c3d052652/mupdf-1.23.10-source && XCFLAGS=-DTOFU_CJK_EXT /var/lang/bin/python3.9 ./scripts/mupdfwrap.py -d build/PyMuPDF-aarch64-shared-tesseract-release -b all && echo /tmp/pip-install-cb92xvq6/pymupdf_d00dc26c49b341ad8292f14c3d052652/mupdf-1.23.10-source/build/PyMuPDF-aarch64-shared-tesseract-release: && ls -l /tmp/pip-install-cb92xvq6/pymupdf_d00dc26c49b341ad8292f14c3d052652/mupdf-1.23.10-source/build/PyMuPDF-aarch64-shared-tesseract-release' returned non-zero exit status 1.
16.71       [end of output]
16.71   
16.71   note: This error originates from a subprocess, and is likely not a problem with pip.
16.72 error: metadata-generation-failed

Everything was going smoothly, but now I cannot seem to make it work when I want to do the pip install llama-index (also not working if I specify a version) in version 0.10 +

My Dockerfile:
# Use the official Python image for AWS Lambda
FROM public.ecr.aws/lambda/python:3.9

# Set working directory
WORKDIR /var/task

# Install PostgreSQL development package
RUN yum install -y postgresql-devel gcc

# Copy function code
COPY . .

RUN pip install --no-cache-dir -r requirements.txt -t .

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD ["answer.lambda_handler"]

### Version

0.10.9

### Steps to Reproduce

Run the docker file with llama-index in requirements

**Comment by logan-markewich** [comment]
Seems like an issue installing tesseract?

**Comment by logan-markewich** [comment]
What does your reqs file look like?

**Comment by logan-markewich** [comment]
Oh, its pymupdf actually

**Comment by logan-markewich** [comment]
If you aren't using file-based loaders, you can specify exact packages to install (and skip the pymupdf dep)

in V0.10.x, most integrations are a package

For example, you can install
```
llama-index-core 
llama-index-llms-openai 
llama-index-embeddings-openai
llama-index-program-openai
llama-index-question-gen-openai
llama-index-agent-openai
llama-index-multi-modal-llms-openai
```

**Comment by turit0** [comment]
> If you aren't using file-based loaders, you can specify exact packages to install (and skip the pymupdf dep)
> 
> in V0.10.x, most integrations are a package
> 
> For example, you can install
> 
> ```
> llama-index-core 
> llama-index-llms-openai 
> llama-index-embeddings-openai
> llama-index-program-openai
> llama-index-question-gen-openai
> llama-index-agent-openai
> llama-index-multi-modal-llms-openai
> ```

Hi logan! Thank you for the quick reply
My requirements are:
llama-index
llama-index-vector-stores-postgres
psycopg2-binary
asyncpg

The thing is, I also tried to do the separate package installation and it didn't work (although I also tried to install
llama-index-readers-file)
so maybe the problem is there

I will try again later without the readers-file and let you know if it works!

It was quite weird because I have no problem if I specify llama-index==0.9.45, but as soon as I tried 0.10+, it always threw this error.

Thank you!

**Comment by turit0** [comment]
Hi, so today I tried again installing llama-index (without doing it package by package) and it worked perfectly all of a sudden. Cheers!
