### ISSUE TITLE
multi-ServiceContext and Settings situation

### ISSUE THREAD

**Issue by jiauy** [run-llama/llama_index#11070]
### Feature Description

Now I want my different documents sets with different ServiceContext for example different chunk_size, how can I achieve that conveniently with futher deprecated ServiceContext, for now Settings seems globally.

**Comment by logan-markewich** [comment]
@jiauy you can specify all these things per-component. If not provided, the fall back to whatever is defined in global settings

```
from llama_index.core.node_parser import SentenceSplitter

splitter = SentenceSplitter(chunk_size=512, chunk_overlap=20)

index = VectorStoreIndex.from_documents(documents, embed_model=embed_model, transformations=[splitter])

query_engine = index.as_query_engine(llm=llm)

chat_engine = index.as_chat_engine(llm=llm)
```
