### ISSUE TITLE
[Feature Request]: Add batch retrieval because the current implementation is not feasible even on small datasets

### ISSUE THREAD

**Issue by hkristof03** [run-llama/llama_index#11073]
### Feature Description

Hi, thanks for this awesome library.

I am trying to benchmark the components of a RAG pipeline until the Retrieval component (chunking, embedding models, rerankers, etc.) on QUAC and SQUAD datasets, which are relatively small.

I am using the following components:

`RetrieverEvaluator`
`EmbeddingQAFinetuneDataset`
`aevaluate_dataset()`

I am also using FAISS based on this tutorial: https://docs.llamaindex.ai/en/stable/examples/vector_stores/FaissIndexDemo.html

The problem is that the retrieval implementation is inefficient, because it doesn't utilize the batch search capabilities of FAISS and instead iterates on the queries and performs the search one by one, based on your code below.

https://github.com/run-llama/llama_index/blob/da5f941662b65d2e3fe2100f2b58c3ba98d49e90/llama-index-core/llama_index/core/evaluation/retrieval/base.py#L189

Moreover, I don't find any computation speed up when I use multiple workers. The computation time is the almost the same when I use 1 and 10 workers.

For comparison and from my experience, using FAISS with a vector space cardinality ~140k, with much higher dimensionality than I tried here - 384, querying the whole vector space with itself in one batch took around ~3 minutes at most on the same hardware (commercial high-end laptop). Here, I tried with a cardinality of 3k, and it took ~10 minutes.

It is currently not feasible to use this feature even on small datasets.

### Reason

The current implementation of retrieval evaluation is not usable due to its slowness.

### Value of Feature

It would make it feasible to evaluate Retrieval components.

**Comment by hkristof03** [comment]
Hi AI bro!

I haven't mentioned `QueryFusionRetriever `.  The method `aevaluate_dataset` is a part of `BaseRetrievalEvaluator` class. The `aevaluate_dataset` expects a `dataset: EmbeddingQAFinetuneDataset` parameter. I think from the name it is clear that both the method and the dataset were designed for fine-tuning and its related evaluation. I think the design decision to retrieve nearest neighbors from the vector store one by one is not a good one, as you already confirmed that the process is unreasonably slow for evaluation. The one by one async retrieval is good when the system is deployed / streaming, but for that, you don't need an 'EmbeddingQAFinetuneDataset', nor an `aevaluate_dataset.`

The current implementation makes it unfeasible to evalaute the Retrieval component of the RAG pipeline even on small datasets. Can you recommend a feasible approach with the current version of the library, without implementing my own solution from scratch?

**Comment by jphme** [comment]
Also found there is currently no viable option to speed this up.

Didn't do detailed profiling but the pipeline is CPU bound and you can only use multiple processes efficiently when instantiating multiple retrievers (which themselves are GPU/VRAM-bound with a local embedding model?)...

**Comment by logan-markewich** [comment]
The pipeline is indeed hardware bound unless you use a remote vector store and models

remote vector stores and models support async, allowing you to run a bunch of stuff concurrently 

Going to close this out because tbh I don't see batch retrieval being supported anytime soon, especially when async exists
