### ISSUE TITLE
[Bug]: ImportError: cannot import name 'MetadataInfo' from 'llama_index.core.vector_stores' (/usr/local/lib/python3.10/dist-packages/llama_index/core/vector_stores/__init__.py)

### ISSUE THREAD

**Issue by karthikra** [run-llama/llama_index#11084]
### Bug Description

ImportError: cannot import name 'VectorStoreInfo' from 'llama_index.core.vector_stores'

### Version

0.10.10

### Steps to Reproduce

from llama_index.core.vector_stores import VectorStoreInfo

**Comment by logan-markewich** [comment]
@karthikra the bot is right, the correct import is `from llama_index.core.vector_stores.types import VectorStoreInfo`

**Comment by omnific9** [comment]
Hi, I'd like to point out that many people may be encountering this error because this is how it's advised on the API documentation: https://docs.llamaindex.ai/en/stable/examples/retrievers/vectara_auto_retriever.html
