### ISSUE TITLE
[Bug]: Llama Cloud / Parser does not recognize any tables in PDF document

### ISSUE THREAD

**Issue by wb200** [run-llama/llama_index#11083]
### Bug Description

Uploaded a quarterly stock report as a PDF to Llama Cloud and had a look at parsed MD output. Parser only created a very basic text output. It did not recognize any of the tables in the document. **Am I doing anything wrong?** I kind of expected magic out of the box. I have my own parser using Unstructured.IO and that can deal with tables. But I'm very much interested in an industrial strength solution on Llama Cloud. Please make this work!

Document link is here: https://www.metalsx.com.au/wp-content/uploads/2024/01/04_MLX_Quarterly-Report_31-December-2023-3477-8958-0586-v.3.pdf

![image](https://github.com/run-llama/llama_index/assets/45331952/d8b89fdd-daca-44fe-ad0c-1636478953c1)

### Version

0.10.4 / 0.10.10 for core

### Steps to Reproduce

Document link to parse: https://www.metalsx.com.au/wp-content/uploads/2024/01/04_MLX_Quarterly-Report_31-December-2023-3477-8958-0586-v.3.pdf

**Comment by wb200** [comment]
@dosu-bot

Thanks for the quick reply. The table embedded in the PDF document is not an image. Whether it is a standard stable, I don't know. Given the source, I think it is a simple Excel table that was inserted into a Word document and then converted to PDF for final publication. Sounds very standard to me.

I just ran a second test on Llama Cloud. I only extracted and uploaded the one page with the table. Again, the parser failed to recognize the table. I have not tried doing this workflow using Python code yet, but I would expect the drag-n-drop online tool to work as advertised. It does not.

![image](https://github.com/run-llama/llama_index/assets/45331952/770b787f-6c17-4e37-ab39-7e6440a41c68)

**Comment by logan-markewich** [comment]
@wb200 tbh I think it actually parsed fine? But I think the viewer isn't rendering line breaks properly -- if you look I'm the text, you can see a markdown table or two.

I would try with the actual api client https://github.com/run-llama/llama_parse

**Comment by wb200** [comment]
Got it. As you said, it was an issue with the online render of the MD output. Looks fine in Jupyter Notebook. Cheers!
