### ISSUE TITLE
[Bug]: AttributeError when calling partial_format on string in compact_and_refine.py

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#11087]
### Bug Description

I was trying to override the default text_qa_template when using 

`dataset_generator = RagDatasetGenerator.from_documents()
`
but an AttributeError is thrown indicating that the string object self._text_qa_template has no attribute partial_format. This issue occurs in the _make_compact_text_chunks method of compact_and_refine.py.

### Version

0.9.45

### Steps to Reproduce

Initialize a RagDatasetGenerator with the necessary documents and service context.
Call the agenerate_dataset_from_nodes() method to generate the dataset.
Observe the AttributeError that occurs during the execution.

Expected Behavior:
The TEXT_QA_TEMPLATE string should be formatted without any issues, allowing the dataset generation to proceed.

Actual Behavior:
An AttributeError is raised, suggesting that there is an attempt to call a non-existent partial_format method on a string object.

```
from llama_index.llama_dataset.generator import RagDatasetGenerator

# Assume 'documents' and 'service_context' are already defined
TEXT_QA_TEMPLATE = "Your string here with placeholders"

dataset_generator = RagDatasetGenerator.from_documents(
    documents=documents,
    service_context=service_context,
    text_qa_template=TEXT_QA_TEMPLATE,
    # other parameters
)

labelled_rag_dataset = dataset_generator.agenerate_dataset_from_nodes()

```

### Relevant Logs/Tracbacks

```shell
File "C:\Users\Stephane\miniconda3\envs\llamaclean\lib\site-packages\llama_index\response_synthesizers\compact_and_refine.py", line 48, in _make_compact_text_chunks
    text_qa_template = self._text_qa_template.partial_format(query_str=query_str)
AttributeError: 'str' object has no attribute 'partial_format'
```

**Comment by logan-markewich** [comment]
@stephanedebove the text_qa_template has to be a `BasePromptTemplate` type

`text_qa_template: Optional[BasePromptTemplate] = None,`

This will work

```
from llama_index.core.prompts import PromptTemplate

TEXT_QA_TEMPLATE = PromptTemplate("Your string here with placeholders")
```
