### ISSUE TITLE
[Question]: How to load the vector store index stored in pinecone?

### ISSUE THREAD

**Issue by rudrakhsha-c** [run-llama/llama_index#11085]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am switching my existing implementation of llama index RAG from using File system to persist my vector index to storing them in a pinecone db on cloud. 
![image](https://github.com/run-llama/llama_index/assets/152485318/3e7117ad-0944-416d-bf87-89dd0130692f)
The above image shows that I create a new vector index and persist them in a pinecone index.
I want to write the function which loads that index from pinecone so that I dont have to re index my documents everytime.
Is there any documentation on how to load an index form pinecone db where I have already created my pinecone index using the pinecone UI.

**Comment by rudrakhsha-c** [comment]
so with pinecone vector database, we have to compulsorily upsert the documents everytime we want to create the VectorStoreIndex? Is there no way of just retrieving my vector index from pinecone db?
Dont we have a similar method like load_index_from_storage was for file system?

**Comment by logan-markewich** [comment]
@rudrakhsha-c you can connect to an existing pinecone index with this

```
vector_store =  PineconeVectorStore(pinecone_index=existing_index)

index = VectorStoreIndex.from_vector_store(vector_store)
```
