### ISSUE TITLE
[Question]: Import error: KnowledgeGraphIndex, LLMPredictor and ServiceContext

### ISSUE THREAD

**Issue by MRX2005nzr** [run-llama/llama_index#11097]
### Question Validation

- [ ] I have searched both the documentation and discord for an answer.

### I try to import these modules from the llama_index but all failed
```
Python 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from llama_index import ServiceContext
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)
>>> from llama_index import KnowledgeGraphIndex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'KnowledgeGraphIndex' from 'llama_index' (unknown location)
>>> from llama_index import LLMPredictor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LLMPredictor' from 'llama_index' (unknown location)
```
They changed names or were just deprecated?

**Comment by MRX2005nzr** [comment]
the module LLMPredictor also cannot be found, why?

**Comment by logan-markewich** [comment]
@MRX2005nzr llama_index v0.10.x has changed some imports

Please refer to the latest docs, as well as our migration guide
https://docs.llamaindex.ai/en/stable/
https://pretty-sodium-5e0.notion.site/6ede431dcb8841b09ea171e7f133bd77?pvs=25

In this case, your imports would be
```
from llama_index.core import KnowledgeGraphIndex
```

Furhtermore, LLMPredictor is deprecated (and has been for some time) and so is service context recently.

See this page
https://github.com/run-llama/llama_index/blob/main/docs/module_guides/supporting_modules/service_context_migration.md

**Comment by MRX2005nzr** [comment]
@logan-markewich Thank you bro, it works for me
