### ISSUE TITLE
[Bug]: `NotionPageReader` object has no attribute 'token'

### ISSUE THREAD

**Issue by david1542** [run-llama/llama_index#11090]
### Bug Description

When I try to instantiate the `NotionPageReader`, I get an error saying
```bash
NotionPageReader object has no attribute 'token'
```
Seems like it happens when `self.token` is called inside `NotionPageReader`, at `llama_index\readers\notion\base.py` line 43:
```python
token = integration_token
headers = {
    "Authorization": "Bearer " + self.token,
    "Content-Type": "application/json",
    "Notion-Version": "2022-06-28",
}
```
Stack trace:
```bash
\llama_index\readers\notion\base.py", line 43, in __init__
    "Authorization": "Bearer " + self.token,
AttributeError: 'NotionPageReader' object has no attribute 'token'
```

Changing `self.token` to just `token` solves this bug. Should I create a PR?

### Version

0.10.6

### Steps to Reproduce

Instantiate `NotionPageReader`, like this:
```python
reader = NotionPageReader("some_token")
```

### Relevant Logs/Tracbacks

```shell
\llama_index\readers\notion\base.py", line 43, in __init__
    "Authorization": "Bearer " + self.token,
AttributeError: 'NotionPageReader' object has no attribute 'token'
```

**Comment by logan-markewich** [comment]
@david1542 please run `pip install -U llama-index-readers-notion` -- it's been fixed 👍
