### ISSUE TITLE
[Bug]:  Salesforce Integration not working

### ISSUE THREAD

**Issue by Vigneshgateai** [run-llama/llama_index#11102]
### Bug Description

No tools folder available in the directory.

Newly added :
from **llama_index.agent.openai.base** import OpenAIAgent
from **llama_index.llms.openai.base** import OpenAI

### Version

latest

### Steps to Reproduce

Install the Package - pip install llama-index llama-hub simple-salesforce opeanai
Create a python file in your editor
Copy the example (Provided by Llama index -> Salesforce)
Run it.

**Comment by Vigneshgateai** [comment]
<module>\r\n    from llama_hub.tools.salesforce import SalesforceToolSpec\r\n  File \"C:\\Users\\conve\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\llama_hub\\tools\\salesforce\\__init__.py\", line 2, in <module>\r\n    from llama_hub.tools.salesforce.base import (\r\n  File \"C:\\Users\\conve\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\llama_hub\\tools\\salesforce\\base.py\", line 1, in <module>\r\n    from llama_index.tools.tool_spec.base import BaseToolSpec\r\nModuleNotFoundError: No module named 'llama_index.tools'\r\n",

**Comment by logan-markewich** [comment]
@Vigneshgateai llama_hub as a package is deprecated.

You can install it with `pip install llama-index-tools-salesforce`

`from llama_index.tools.salesforce import SalesforceToolSpec`
