### ISSUE TITLE
ImportError: cannot import name 'Document' from 'llama_index' (unknown location)[Bug]: 

### ISSUE THREAD

**Issue by alokkrsahu** [run-llama/llama_index#11138]
### Bug Description

----> 4 from ragatouille import RAGPretrainedModel
      6 READER_MODEL_NAME = "llama-2-7b-chat-hf/"
      8 bnb_config = BitsAndBytesConfig(
      9     load_in_4bit=True,
     10     bnb_4bit_use_double_quant=True,
     11     bnb_4bit_quant_type="nf4",
     12     bnb_4bit_compute_dtype=torch.bfloat16,
     13 )

File ~/.local/lib/python3.9/site-packages/ragatouille/__init__.py:2, in <module>
      1 __version__ = "0.0.7post3"
----> 2 from .RAGPretrainedModel import RAGPretrainedModel
      3 from .RAGTrainer import RAGTrainer
      5 __all__ = ["RAGPretrainedModel", "RAGTrainer"]

File ~/.local/lib/python3.9/site-packages/ragatouille/RAGPretrainedModel.py:8, in <module>
      5 from langchain.retrievers.document_compressors.base import BaseDocumentCompressor
      6 from langchain_core.retrievers import BaseRetriever
----> 8 from ragatouille.data.corpus_processor import CorpusProcessor
      9 from ragatouille.data.preprocessors import llama_index_sentence_splitter
     10 from ragatouille.integrations import (
     11     RAGatouilleLangChainCompressor,
     12     RAGatouilleLangChainRetriever,
     13 )

File ~/.local/lib/python3.9/site-packages/ragatouille/data/__init__.py:1, in <module>
----> 1 from .corpus_processor import CorpusProcessor
      2 from .preprocessors import llama_index_sentence_splitter
      3 from .training_data_processor import TrainingDataProcessor

File ~/.local/lib/python3.9/site-packages/ragatouille/data/corpus_processor.py:4, in <module>
      1 from typing import Callable, List, Optional, Union
      2 from uuid import uuid4
----> 4 from ragatouille.data.preprocessors import llama_index_sentence_splitter
      7 class CorpusProcessor:
      8     def __init__(
      9         self,
     10         document_splitter_fn: Optional[Callable] = llama_index_sentence_splitter,
     11         preprocessing_fn: Optional[Union[Callable, list[Callable]]] = None,
     12     ):

File ~/.local/lib/python3.9/site-packages/ragatouille/data/preprocessors.py:1, in <module>
----> 1 from llama_index import Document
      2 from llama_index.text_splitter import SentenceSplitter
      5 def llama_index_sentence_splitter(
      6     documents: list[str], document_ids: list[str], chunk_size=256
      7 ):

ImportError: cannot import name 'Document' from 'llama_index' (unknown location)

### Version

llama-index==0.10.10

### Steps to Reproduce

llama-index==0.10.10
llama-index-agent-openai==0.1.5
llama-index-cli==0.1.3
llama-index-core==0.10.11.post1
llama-index-embeddings-openai==0.1.6
llama-index-indices-managed-llama-cloud==0.1.3
llama-index-legacy==0.9.48
llama-index-llms-openai==0.1.6
llama-index-multi-modal-llms-openai==0.1.4
llama-index-program-openai==0.1.4
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.5
llama-index-readers-llama-parse==0.1.3
llama-index-vector-stores-chroma==0.1.2

**Comment by logan-markewich** [comment]
@alokkrsahu v0.10.x was a larger update. The correct import is `from llama_index.core import Document`

Please see the migration guide
https://pretty-sodium-5e0.notion.site/6ede431dcb8841b09ea171e7f133bd77?pvs=25

Additionally, if you are updating from v0.9.X, I recommend starting with a fresh venv

**Comment by S1M0N38** [comment]
@logan-markewich, I came here for the same reason. Every LLM I've asked suggested using this import statement:

```python
from llama_index import Document 
```

However, that resulted in the following error:
```
ImportError: cannot import name 'Document' from 'llama_index'
```

It seems the LLMs are referencing an outdated version of the llama_index library.

Additionally, when asking Mendable on the LlamaIndex docs, it provides the same incorrect suggestion. Is Mendable using an updated version of the documentation to perform retrieval augmented generation (RAG)?

**Comment by logan-markewich** [comment]
@S1M0N38 mendable should be using the lastest version of the docs 😭 seems it may be hallucinating a bit? Will double check
