### ISSUE TITLE
[Bug]: ImportError: cannot import name 'global_handler' from 'llama_index.core' (unknown location)

### ISSUE THREAD

**Issue by abhijithneilabraham** [run-llama/llama_index#11252]
### Bug Description

I was trying to run the example here: https://docs.llamaindex.ai/en/stable/examples/llm/ollama.html

Code:
```
from llama_index.llms.ollama import Ollama
llm = Ollama(model="llama2", request_timeout=30.0)
resp = llm.complete("Who is Paul Graham?")
print(resp)
```

I am using Macos M1. 

### Version

llama-index-0.10.11

### Steps to Reproduce

```
from llama_index.llms.ollama import Ollama
llm = Ollama(model="llama2", request_timeout=30.0)
resp = llm.complete("Who is Paul Graham?")
print(resp)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/abhijithneilabraham/Documents/GitHub/headless_ai/research_scripts/ollama_with_llamaindex.py", line 2, in <module>
    llm = Ollama(model="llama2", request_timeout=30.0)
  File "/Users/abhijithneilabraham/mambaforge/envs/py/lib/python3.9/site-packages/pydantic/v1/main.py", line 339, in __init__
    values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
  File "/Users/abhijithneilabraham/mambaforge/envs/py/lib/python3.9/site-packages/pydantic/v1/main.py", line 1066, in validate_model
    value = field.get_default()
  File "/Users/abhijithneilabraham/mambaforge/envs/py/lib/python3.9/site-packages/pydantic/v1/fields.py", line 439, in get_default
    return smart_deepcopy(self.default) if self.default_factory is None else self.default_factory()
  File "/Users/abhijithneilabraham/mambaforge/envs/py/lib/python3.9/site-packages/llama_index/core/callbacks/base.py", line 54, in __init__
    from llama_index.core import global_handler
ImportError: cannot import name 'global_handler' from 'llama_index.core' (unknown location)
```
```

**Comment by bjmvercelli** [comment]
Same here. A lot of import issues in latest version **0.10.11**

**Comment by logan-markewich** [comment]
@abhijithneilabraham @bjmvercelli very important to start with a fresh venv. V0.10.x was a large structural change to split out intergrations into packages

In a new terminal, I would do
```
pip uninstall llama-index  # remove any global install
python -m venv my_venv
source my_venv/bin/activate
pip install llama-index
```

Full migration guide is here if you are coming from an older version. All the docs are updated as well
https://pretty-sodium-5e0.notion.site/6ede431dcb8841b09ea171e7f133bd77?pvs=25

All integrations/packages are listed in llama-hub
https://llamahub.ai/

**Comment by luizhsalazar** [comment]
Still getting the same error here! Even removing and upgrading the packages to the newest version (0.10.12).

**Comment by logan-markewich** [comment]
@luizhsalazar also as suggested, highly recommend a fresh venv

**Comment by xhw1** [comment]
got the same error when using llama-index-0.10.28

**Comment by logan-markewich** [comment]
@xhw1 as suggested (again) highly highly recommend to start with a fresh venv. It works fine on Google colab for example

**Comment by ceteri** [comment]
Although, Google Colab is not an option in many cases :)
This issue was closed, yet it seems to persist?

**Comment by logan-markewich** [comment]
@ceteri I'm not saying to use Google colab. Just an example that a fresh venv solves the problem. 

This is closed because it's not an issue. Start with a fresh venv and you'll be fine. Even better, remove all trace of a previous install

For example, in a fresh terminal I would do

```
pip freeze | grep llama-index | xargs pip uninstall -y
python -m venv venv
source venv/bin/activate 
pip install llama-index llama-index-llms-ollama <and whatever other packages are needed>
```
