### ISSUE TITLE
[Bug]: ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by clintg6** [run-llama/llama_index#11260]
### Bug Description

I installed llamaIndex 0.10.1 and followed the quick start tutorial, but it cannot import any modules from llama_index or llama_index.core.

ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)
Version

### Version

0.10.11

### Steps to Reproduce

from llama_index import ServiceContext

### Relevant Logs/Tracbacks

```shell
ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)
```

**Comment by logan-markewich** [comment]
@clintg6 v0.10.x was a large structural change. The proper import is `from llama_index.core import ServiceContext`

Complete migration guide here
https://pretty-sodium-5e0.notion.site/6ede431dcb8841b09ea171e7f133bd77?pvs=25

And if you are coming from v0.9.x, I highly recommend starting with a fresh venv

In a new terminal, something like
```
pip uninstall llama-index  # remove any global install
python -m venv my_venv
source my_venv/bin/activate
pip install llama-index
```

The quick start tutorial has the proper imports, as do all our docs
https://docs.llamaindex.ai/en/stable/getting_started/starter_example.html

**Comment by Armanasq** [comment]
I have the same issue here. Suddenly it stopped working, I reinstall and upgrade the llama-index but nothing changed

**Comment by clintg6** [comment]
The import locations have changed so you have to update your code as well.

**Comment by LaksLaksman** [comment]
same issue rise again https://github.com/run-llama/llama_index/issues/11074#issuecomment-2288367545
help me to solve.

**Comment by logan-markewich** [comment]
@LaksLaksman it's going to be the same solution I've posted for everyone having this issue :)

**Comment by logan-markewich** [comment]
Fresh venv is your friend. If in a notebook, make sure you restart it
