### ISSUE TITLE
[Question]: The retrieved_nodes scores between relevant query and irrelevant query are too similar. Is there any settings to make the score difference larger?

### ISSUE THREAD

**Issue by cctong-castiel** [run-llama/llama_index#11269]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using hybrid search with Azure Postgres DB followed this documentation. [https://docs.llamaindex.ai/en/latest/examples/vector_stores/postgres.html]()

The relevant query: Tell me more about TIA? TIA definition is curated and stored in the Postgres DB
The irrelevant query: Who are you?

The nodes scores for relevant query are 0.7707140905090638 and 0.7318226258860571
The nodes scores for irrelevant query are 0.726003712176438 and 0.7232235340146463

Is there any settings to make the score difference larger?

**Comment by logan-markewich** [comment]
The similarity score mostly depends on
a) your query
b) your embedding model

When using openai, I notice shorter queries tend to produce similar similarities.

You might have more luck using another embedding model, or even playing around with the embedding dimension with openais new model

```
from llama_index.embeddings.openai import OpenAIEmbedding

embed_model = OpenAIEmbedding(model="text-embedding-3-large", dimensions=512
```

**Comment by hkirdmldev** [comment]
Thank you for your reply. I would like to know why the content is retrieved from the vector store even when the question is irrelevant (eg. Who are you?).

**Comment by cctong-castiel** [comment]
Thank you very much for your reply. I would like to know why the content is retrieved from the vector store even when the question is irrelevant (eg. Who are you?)

**Comment by cctong-castiel** [comment]
ok got it. thank you
