### ISSUE TITLE
[Question]: Neo4jVectorStore with custom Embedding Model

### ISSUE THREAD

**Issue by vivekjoshi556** [run-llama/llama_index#11278]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was following the documentation for Neo4jVectorStore with some custom embedding model:
https://docs.llamaindex.ai/en/stable/examples/vector_stores/Neo4jVectorDemo.html
The embedding dimension for my model is 1024, so I tried to change the  embedding for neo4j vector store as well:
neo4j_vector = Neo4jVectorStore(username, password, url, embedding_dimension=1024)

But when I try to query, it doesn't work. I am getting error:

ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.queryNodes`: Caused by: java.lang.IllegalArgumentException: Index query vector has 1024 dimensions, but indexed vectors have 1536.}

Am I doing something wrong or am I missing something?

**Comment by logan-markewich** [comment]
@vivekjoshi556 Looks like your query code is defaulting to using openai. Make sure you are setting the embed model 

Either globally
```
from llama_index.core import Settings

Settings.embed_model = <embed_model>
```

Or passing it into your index/query_engine/retriever
```
index = VectorStoreIndex(..., embed_model=embed_model)

index.as_retriever(embed_model=embed_model)

index.as_query_engine(embed_model=embed_model)
```

**Comment by vivekjoshi556** [comment]
Hello @logan-markewich, I tried both of the approaches you mentioned above but, I am still getting the same error.

**Comment by logan-markewich** [comment]
In addition to setting the embedding model, you also set the embedding dimension properly?
https://github.com/run-llama/llama_index/blob/272685f893af84ee26ad3f536db15f4f625f7fe2/llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py#L112

If so, maybe provide some code to reproduce

**Comment by vivekjoshi556** [comment]
Yes, this is what I am doing:
embedding_dimension = 1024

neo4j_vector = Neo4jVectorStore(username, password, url, embedding_dimension)

**Comment by delicate00** [comment]
> 是的，这就是我正在做的事情：embedding_dimension = 1024
> 
> neo4j_vector = Neo4jVectorStore（用户名、密码、网址、embedding_dimension）

Hello, I have defined the parameter: embed_dim = 1024, and then created a vector database for neo4j: vector_store = Neo4jVectorStore(username, password, url, embed_dim). The error mentioned above still exists. Do you have a solution to this problem?

**Comment by delicate00** [comment]
> 除了设置嵌入模型，还正确设置了嵌入维度？
> 
> https://github.com/run-llama/llama_index/blob/272685f893af84ee26ad3f536db15f4f625f7fe2/llama-index-integrations/vector_stores/llama-index-vector-stores-neo4jvector/llama_index/vector_stores/neo4jvector/base.py#L112
> 
> 如果是这样，也许提供一些代码来重现

Hello, I have defined the parameters: embed_dim = 1024, and then created a vector database for neo4j: vector_store = Neo4jVectorStore(username, password, url, embed_dim). The code for retrieval after connecting to the vector database is as follows:
    storage_context = StorageContext.from_defaults(
        persist_dir='./storage_neo4j_Vector/nit',
        vector_store=vector_store,
        )
    vector_index = load_index_from_storage(
        service_context=service_context,
        storage_context=storage_context
    )
    vector_query_engine = vector_index.as_query_engine()
    response = vector_query_engine.query(question)

I am still getting the same error. Additionally, I have also set
from llama_index.core import Settings
Settings.embed_model = "local:D:/llamaindex_neo4j/bge-large-zh"
It still doesn't resolve. Could you please advise on what I might have forgotten to modify?
