### ISSUE TITLE
[Bug]: AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by hoangpnhat** [run-llama/llama_index#11276]
### Bug Description

I try using the llama-index-packs/table/chain-of-table. Skip about the download package is not working, I also use to package llama-index in there but it give me the bug like this
`[llama_index/llama-index-packs/llama-index-packs-tables/llama/packs/tables/chain_of_table/base.py:33], in _get_regex_parser_fn.<locals>._regex_parser(output)
     [31] output = str(output)
     [32] m = re.search(regex, output)
---> [33] args = m.group(1)
     [34] if "," in args:
     [35]     return [a.strip().strip("'\"") for a in args.split(",")]

AttributeError: 'NoneType' object has no attribute 'group'` 

### Version

0.10.10

### Steps to Reproduce

 also use to package llama-index in llama-index-packs/table

**Comment by logan-markewich** [comment]
This just means the LLM did not output the correct output. 

Tbh chain-of-table is a cool paper and concept, but not overly reliable unless you use GPT-4

**Comment by hoangpnhat** [comment]
@logan-markewich thank you a lot for the information
