### ISSUE TITLE
[Bug]: cannot import name 'VectorStoreIndex' from 'llama_index.core' (unknown location)

### ISSUE THREAD

**Issue by Ray0907** [run-llama/llama_index#11279]
### Bug Description

I encountered a problem below. I received an error.
```
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
```

got some error 
cannot import name 'VectorStoreIndex' from 'llama_index.core' (unknown location)

### Version

0.10.11

### Steps to Reproduce

When I attempted to import, I encountered an error. I suspect that not all core modules were included correctly.

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[5], line 7
      4 logging.basicConfig(stream=sys.stdout, level=logging.INFO)
      5 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
----> 7 from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
      8 from llama_index.llms.huggingface import HuggingFaceLLM
      9 from llama_index.core import Settings

ImportError: cannot import name 'VectorStoreIndex' from 'llama_index.core' (unknown location)
```

**Comment by marklysze** [comment]
I'm having the same issue (core v0.10.11)

**Comment by marklysze** [comment]
As recommended in other issues - it's preferred to create a brand new virtual environment and ```pip install llama-index```

I have just done that and I no longer get this issue and your line works for me:
```from llama_index.core import VectorStoreIndex, SimpleDirectoryReader```

**Comment by logan-markewich** [comment]
@marklysze is correct

Let me repeat some classic instructions for completeness sake 😉 

You can try

```
pip uninstall llama-index
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

Or if that doesn't work, in a new terminal

```
pip uninstall llama-index  # remove any global
python -m venv my_env
source my_env/bin/activate
pip install llama-index
```
