### ISSUE TITLE
[Bug]: FileNotFoundError: No such file or directory: 'mix_self_consistency_pack/llama_index/packs/tables/base.py'

### ISSUE THREAD

**Issue by hoangpnhat** [run-llama/llama_index#11275]
### Bug Description

I try downloading packs in llama-index-packs table but in both example notebooks has the same Error 404: Not found in the package.

### Version

0.10.10

### Steps to Reproduce

Use the llama-index folder in there

**Comment by nerdai** [comment]
Hey @hoangpnhat this [fix](https://github.com/run-llama/llama_index/pull/11272) should also address your current issue. But just in case, can you let me know which pack specifically?
