### ISSUE TITLE
[Question]: Where should I look for the historical version of the document?

### ISSUE THREAD

**Issue by STDSuperman** [run-llama/llama_index#11287]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Where should I look for the historical version of the document?

**Comment by logan-markewich** [comment]
In the bottom right of the docs, there is a "read the docs" button. Click on that, and you can view older versions
i.e.
https://docs.llamaindex.ai/en/v0.9.15.post2/

**Comment by STDSuperman** [comment]
Thank you very much!
