### ISSUE TITLE
[Bug]: Significant increase in single agent creation time for a standard Q&A multiple Documents example after migration/adoption to v 0.10

### ISSUE THREAD

**Issue by e-lop-ey** [run-llama/llama_index#11282]
### Bug Description

We are trying slightly adopted (simplified) for our purposes example https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents-v1.html  and after migration to new llamaindex we have a significant increase in time of single agent creation, and we can not figure out why.

### Version

0.10.11post1

### Steps to Reproduce

confrnt performance of standard notebook https://colab.research.google.com/github/run-llama/llama_index/blob/main/docs/examples/agent/multi_document_agents-v1.ipynb on last version of 0.9 vs 0.10.11post1

**Comment by e-lop-ey** [comment]
we have the same code example, very basic, that has significantly increased in performance time from version 0.9 to 0.10. I know it's not a great explanation, but mb can be useful with other bugs tracing.

**Comment by logan-markewich** [comment]
@e-lop-ey which part of the code specifically? If you can narrow it down, that would be very helpful
