### ISSUE TITLE
[Bug]: ContextChatEngine.from_defaults still relies on ServiceContext

### ISSUE THREAD

**Issue by spreeni** [run-llama/llama_index#11286]
### Bug Description

After updating from 0.9 to 0.10 I wanted to eliminate all occurences of the new deprecated `ServiceContext`, but noticed that if I want to specify a specific `callback_manager` or `llm` for `llama_index.core.chat_engine.ContextChatEngine` via the `from_defaults` method, this is currently only possible by passing a `ServiceContext`.

### Version

0.10.11.post1

### Steps to Reproduce

Have a look at `llama_index.core.chat_engine.ContextChatEngine.from_defaults`. It would just need to be adjusted by adding `llm` and `callback_manager` to the function arguments. If I find some time the next days, I can also submit a PR.

**Comment by logan-markewich** [comment]
Thanks! I will probably fix this today :)
