### ISSUE TITLE
[Question]:  Mapping TEXT to SOURCE while creating a Llama Index DOCUMENT

### ISSUE THREAD

**Issue by kindler-king** [run-llama/llama_index#11298]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

This is a general question which I couldn't find a direct answer to.

Let's say I have 10 DOCUMENTS on S3 Bucket.
I create a LIST of EXTRACTED TEXT from the 10 Documents & another list of SOURCE_URLS i.e. where those TEXTs BELONG to.

Now I want to use `from llama_index.core import Document` to create a LLAMA INDEX DOCUMENT but I want to make sure that the DOCUMENT created has its ID mapped to it.

ACCORDING TO THE DOCS:
[id_ (str)](https://docs.llamaindex.ai/en/stable/api/llama_index.core.schema.Document.html#llama_index.core.schema.Document.id_)

field id_: str [Optional] (alias 'doc_id')
Unique ID of the node.
This exists, But i am unsure how to map the LIST of URLS to the LIST OF TEXTs while CREATING the LLAMA INDEX DOCUMENT.

Would appreciate some help :D 
Thanks a lot :D

**Comment by kindler-king** [comment]
@dosu-bot  , let's say I have followed the previous steps, what happens then ?
How can I turn the DOCSTORE into a valid index?

Will queries to the index, also return the SOURCE URLS as ID of the SOURCE_NODES in the response?

**Comment by logan-markewich** [comment]
@kindler-king you can attach metadata to each document (like a URL) and that will be inherited to nodes created from that document 

`Document(text=text, metadata={"key": "val"})`

**Comment by kindler-king** [comment]
Thanks a lot for the help as always @logan-markewich . :D
