### ISSUE TITLE
[Bug]: cannot import name 'LLM' from 'llama_index.core.llms'

### ISSUE THREAD

**Issue by jphme** [run-llama/llama_index#11302]
### Bug Description

When trying to import via

```
from llama_index.core.indices import VectorStoreIndex
from llama_index.core.readers import SimpleDirectoryReader
from llama_index.core.storage import StorageContext
```

### Version

0.10.11

### Steps to Reproduce

install llama index in a new venv with poetry. 

I delted both `.venv` and `poetry.lock` - the error persists. 

### Relevant Logs/Tracbacks

```shell
ImportError                               Traceback (most recent call last)
Cell In[8], line 1
----> 1 from llama_index.core.indices import VectorStoreIndex
      2 from llama_index.core.readers import SimpleDirectoryReader
      3 from llama_index.core.storage import StorageContext

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/indices/__init__.py:4
      1 """LlamaIndex data structures."""
      3 # indices
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      5 from llama_index.core.indices.document_summary import (
      6     DocumentSummaryIndex,
      7     GPTDocumentSummaryIndex,
      8 )
      9 from llama_index.core.indices.document_summary.base import DocumentSummaryIndex

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/indices/composability/__init__.py:4
      1 """This module contains all classes used for composing graphs over indices."""
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      6 __all__ = ["ComposableGraph"]

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/indices/composability/graph.py:7
      5 from llama_index.core.base.base_query_engine import BaseQueryEngine
      6 from llama_index.core.data_structs.data_structs import IndexStruct
----> 7 from llama_index.core.indices.base import BaseIndex
      8 from llama_index.core.schema import (
      9     IndexNode,
     10     NodeRelationship,
     11     ObjectType,
     12     RelatedNodeInfo,
     13 )
     14 from llama_index.core.service_context import ServiceContext

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/indices/base.py:8
      5 from typing import Any, Dict, Generic, List, Optional, Sequence, Type, TypeVar
      7 from llama_index.core.base.base_query_engine import BaseQueryEngine
----> 8 from llama_index.core.base.base_retriever import BaseRetriever
      9 from llama_index.core.callbacks.base import CallbackManager
     10 from llama_index.core.chat_engine.types import BaseChatEngine, ChatMode

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py:30
     21 from llama_index.core.schema import (
     22     BaseNode,
     23     IndexNode,
   (...)
     27     TextNode,
     28 )
     29 from llama_index.core.service_context import ServiceContext
---> 30 from llama_index.core.settings import Settings
     31 from llama_index.core.utils import print_text
     34 class BaseRetriever(ChainableMixin, PromptMixin):

File ~/dev2//.venv/lib/python3.10/site-packages/llama_index/core/settings.py:12
     10 from llama_index.core.embeddings.utils import EmbedType, resolve_embed_model
     11 from llama_index.core.indices.prompt_helper import PromptHelper
---> 12 from llama_index.core.llms import LLM
     13 from llama_index.core.llms.utils import LLMType, resolve_llm
     14 from llama_index.core.node_parser import NodeParser, SentenceSplitter

ImportError: cannot import name 'LLM' from 'llama_index.core.llms' (unknown location)
```
```

**Comment by logan-markewich** [comment]
@jphme just to be extremely certain...

In a fresh terminal
```
pip uninstall llama-index  # remove any possible global install
python -m venv venv
source venv/bin/activate
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

**Comment by jphme** [comment]
> source venv/bin/activate

same error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'LLM' from 'llama_index.core.base.llms' (/Users/jph/dev2/tmp_llamaindex/venv/lib/python3.10/site-packages/llama_index/core/base/llms/__init__.py)
```

**Comment by heloisypr** [comment]
same error here

**Comment by logan-markewich** [comment]
@heloisypr @jphme it works in a fresh colab instance, so I'm fairly sure this is an env issue

https://colab.research.google.com/drive/1rfJqRTbSAIkv-aERpDcdhNOIahSCm-3x?usp=sharing

**Comment by logan-markewich** [comment]
Awesome @heloisypr 

@jphme I still think its an env issue for you 😅 A fresh colab works
https://colab.research.google.com/drive/1rfJqRTbSAIkv-aERpDcdhNOIahSCm-3x?usp=sharing

**Comment by GZL11** [comment]
Same error, how to reslove this problem?

**Comment by logan-markewich** [comment]
@GZL11 I have posted the solution above 

In a new terminal
```
pip uninstall llama-index  # remove any possible global install
python -m venv venv
source venv/bin/activate
pip install llama-index --upgrade --no-cache-dir --force-reinstall
```

**Comment by jphme** [comment]
> @GZL11 I have posted the solution above
> 
> In a new terminal
> 
> ```
> pip uninstall llama-index  # remove any possible global install
> python -m venv venv
> source venv/bin/activate
> pip install llama-index --upgrade --no-cache-dir --force-reinstall
> ```

Sorry @logan-markewich but as I wrote above, I did these exact steps (and deletet another poetry venv twice) and the error occured again. 
I don't know why it works on Colab (maybe it´s system/python dependent? Iam on Mac oSX and working with Python 3.10) , but it should be obvious (from other people having the same issue) that this is a bug. Never encountered this with any other library or previous versions of llama_index - and I know how to setup a fresh venv...

**Comment by logan-markewich** [comment]
@jphme I also have python3.10 on macos 😅 The change to namespaced packages in llama-index v0.10.x means any remnants of an old install will cause issues.

It seems like either a) llama-index==v0.9.x is installed globally somewhere, outside of a venv, or b) another package you are installing (in addition to llama-index) is installing an older version of llama-index

I really think if you run only the above steps (in a fresh terminal) and then try to execute some small script that imports llama-index, it should work fine.

I'm not really sure if I have any ideas beyond that. Its worked for every other person so far 😅

**Comment by jphme** [comment]
> @jphme I also have python3.10 on macos 😅 The change to namespaced packages in llama-index v0.10.x means any remnants of an old install will cause issues.
> 
> It seems like either a) llama-index==v0.9.x is installed globally somewhere, outside of a venv, or b) another package you are installing (in addition to llama-index) is installing an older version of llama-index
> 
> I really think if you run only the above steps (in a fresh terminal) and then try to execute some small script that imports llama-index, it should work fine.
> 
> I'm not really sure if I have any ideas beyond that. Its worked for every other person so far 😅

haha, i will do a screen capture ;-) . Honestly, will try another time; but I don't have (and never had) llama-index in my global python namespace and installed only llama-index in a fresh terminal/venv...

**Comment by a-bhattacharya** [comment]
Facing the same issue.
I do not have llama index installed globally.

```
❯ python --version
Python 3.11.4
❯ pip show llama-index
WARNING: Package(s) not found: llama-index
```

I am working on a project with a venv.

```
❯ python --version
Python 3.11.4
❯ poetry show llama-index
 name         : llama-index                          
 version      : 0.10.9                               
 description  : Interface between LLMs and your data 

dependencies
 - llama-index-agent-openai >=0.1.0,<0.2.0
 - llama-index-core >=0.10.8.post1,<0.11.0
 - llama-index-embeddings-openai >=0.1.0,<0.2.0
 - llama-index-indices-managed-llama-cloud >=0.1.0,<0.2.0
 - llama-index-legacy >=0.9.48,<0.10.0
 - llama-index-llms-openai >=0.1.0,<0.2.0
 - llama-index-multi-modal-llms-openai >=0.1.0,<0.2.0
 - llama-index-program-openai >=0.1.0,<0.2.0
 - llama-index-question-gen-openai >=0.1.0,<0.2.0
 - llama-index-readers-file >=0.1.0,<0.2.0
 - llama-index-readers-llama-parse >=0.1.0,<0.2.0
```

Additionally I have the llama-index qdrant dependency installed.

```
❯ poetry show llama-index-vector-stores-qdrant
 name         : llama-index-vector-stores-qdrant             
 version      : 0.1.3                                        
 description  : llama-index vector_stores qdrant integration 

dependencies
 - grpcio >=1.60.0,<2.0.0
 - llama-index-core >=0.10.1,<0.11.0
 - qdrant-client >=1.7.1,<2.0.0
```

**Comment by logan-markewich** [comment]
But there is an init... 

Here is the init in llama_index.core.llms

https://github.com/run-llama/llama_index/blob/b285c6f8bf640266357befcc3654f394738376f7/llama-index-core/llama_index/core/llms/__init__.py#L13

And here is the class it's importing 
https://github.com/run-llama/llama_index/blob/b285c6f8bf640266357befcc3654f394738376f7/llama-index-core/llama_index/core/llms/llm.py#L117

All paths are correct.

Installing from a fresh venv would likely resolve your issues, using the commands I posted above @a-bhattacharya

**Comment by nerdai** [comment]
@jphme do you think you could try maybe wiping the installed packages first instead of recreating the venv?

```
source venv/bin/activate
pip freeze | xargs pip uninstall -y
pip install llama-index
```

**Comment by jphme** [comment]
> from llama_index.core.storage import StorageContext



> @jphme do you think you could try maybe wiping the installed packages first instead of recreating the venv?
> 
> ```
> source venv/bin/activate
> pip freeze | xargs pip uninstall -y
> pip install llama-index
> ```

This worked. 
But probably I got it wrong before; after re-checking, the import that failed after setting up new venv ([as I wrote above](https://github.com/run-llama/llama_index/issues/11302#issuecomment-1960512978)) was `from llama_index.core.base.llms import LLM` and not `from llama_index.core.llms import LLM`.  
Huge sorry @logan-markewich, this was indeed my fault. (But it probably would make sense to add these uninstall /venv reset instructions to the docs anyway).

**Comment by rob** [comment]
This is still completely broken for me, using both `pip` and `poetry` on macOS 14.1.2.

Example using `pip` in a new environment:

```
➜  ~ mkdir -p llama_test
➜  ~ cd llama_test
➜  llama_test python3 -m venv .venv
➜  llama_test source .venv/bin/activate

(.venv) ➜  llama_test pip install --no-cache-dir llama-index

Successfully installed PyMuPDFb-1.23.22 PyYAML-6.0.1 SQLAlchemy-2.0.27 aiohttp-3.9.3 aiosignal-1.3.1 annotated-types-0.6.0 anyio-4.3.0 asgiref-3.7.2 attrs-23.2.0 backoff-2.2.1 bcrypt-4.1.2 beautifulsoup4-4.12.3 bs4-0.0.2 build-1.0.3 cachetools-5.3.3 certifi-2024.2.2 charset-normalizer-3.3.2 chroma-hnswlib-0.7.3 chromadb-0.4.23 click-8.1.7 coloredlogs-15.0.1 dataclasses-json-0.6.4 deprecated-1.2.14 dirtyjson-1.0.8 distro-1.9.0 fastapi-0.110.0 filelock-3.13.1 flatbuffers-23.5.26 frozenlist-1.4.1 fsspec-2024.2.0 google-auth-2.28.1 googleapis-common-protos-1.62.0 greenlet-3.0.3 grpcio-1.62.0 h11-0.14.0 httpcore-1.0.4 httptools-0.6.1 httpx-0.27.0 huggingface_hub-0.21.1 humanfriendly-10.0 idna-3.6 importlib-metadata-6.11.0 importlib-resources-6.1.2 joblib-1.3.2 kubernetes-29.0.0 llama-index-0.10.13.post1 llama-index-agent-openai-0.1.5 llama-index-cli-0.1.5 llama-index-core-0.10.13 llama-index-embeddings-openai-0.1.6 llama-index-indices-managed-llama-cloud-0.1.3 llama-index-legacy-0.9.48 llama-index-llms-openai-0.1.6 llama-index-multi-modal-llms-openai-0.1.4 llama-index-program-openai-0.1.4 llama-index-question-gen-openai-0.1.3 llama-index-readers-file-0.1.6 llama-index-readers-llama-parse-0.1.3 llama-index-vector-stores-chroma-0.1.4 llama-parse-0.3.4 llamaindex-py-client-0.1.13 marshmallow-3.21.0 mmh3-4.1.0 monotonic-1.6 mpmath-1.3.0 multidict-6.0.5 mypy-extensions-1.0.0 nest-asyncio-1.6.0 networkx-3.2.1 nltk-3.8.1 numpy-1.26.4 oauthlib-3.2.2 onnxruntime-1.17.1 openai-1.12.0 opentelemetry-api-1.23.0 opentelemetry-exporter-otlp-proto-common-1.23.0 opentelemetry-exporter-otlp-proto-grpc-1.23.0 opentelemetry-instrumentation-0.44b0 opentelemetry-instrumentation-asgi-0.44b0 opentelemetry-instrumentation-fastapi-0.44b0 opentelemetry-proto-1.23.0 opentelemetry-sdk-1.23.0 opentelemetry-semantic-conventions-0.44b0 opentelemetry-util-http-0.44b0 orjson-3.9.15 overrides-7.7.0 packaging-23.2 pandas-2.2.1 pillow-10.2.0 posthog-3.4.2 protobuf-4.25.3 pulsar-client-3.4.0 pyasn1-0.5.1 pyasn1-modules-0.3.0 pydantic-2.6.2 pydantic-core-2.16.3 pymupdf-1.23.25 pypdf-4.0.2 pypika-0.48.9 pyproject_hooks-1.0.0 python-dateutil-2.8.2 python-dotenv-1.0.1 pytz-2024.1 regex-2023.12.25 requests-2.31.0 requests-oauthlib-1.3.1 rsa-4.9 setuptools-69.1.1 six-1.16.0 sniffio-1.3.1 soupsieve-2.5 starlette-0.36.3 sympy-1.12 tenacity-8.2.3 tiktoken-0.6.0 tokenizers-0.15.2 tqdm-4.66.2 typer-0.9.0 typing-extensions-4.10.0 typing-inspect-0.9.0 tzdata-2024.1 urllib3-2.2.1 uvicorn-0.27.1 uvloop-0.19.0 watchfiles-0.21.0 websocket-client-1.7.0 websockets-12.0 wrapt-1.16.0 yarl-1.9.4 zipp-3.17.0

(.venv) ➜  llama_test echo "from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, Document" > run.py

(.venv) ➜  llama_test python3 run.py

Traceback (most recent call last):
  File "/Users/robgabaree/llama_test/run.py", line 1, in <module>
    from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, Document
ImportError: cannot import name 'VectorStoreIndex' from 'llama_index' (unknown location)
```

Something is obviously wrong if it's not working out of the box suddenly with a basic setup. These suggestions to re-install (e.g., `pip freeze | xargs pip uninstall -y`, `pip install llama-index --upgrade --no-cache-dir --force-reinstall`, etc) don't do anything differently.

**Comment by nerdai** [comment]
@rob your import statement is not up to date. In case you missed it, here are a few links:

- [v0.10 migration guide](https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77)
- Updated Github [README](https://github.com/run-llama/llama_index?tab=readme-ov-file#%EF%B8%8F-llamaindex-) (in particular the first section that details how we've split up the library into "core" and "integrations" (and other packages like cli, finetuning, etc.).

Please try this instead

```sh
echo "from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, Document" > run.py
python3 run.py
```

**Comment by rob** [comment]
> @rob your import statement is not up to date. In case you missed it, here are a few links:
> 
>     * [v0.10 migration guide](https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77)
> 
>     * Updated Github [README](https://github.com/run-llama/llama_index?tab=readme-ov-file#%EF%B8%8F-llamaindex-) (in particular the first section that details how we've split up the library into "core" and "integrations" (and other packages like cli, finetuning, etc.).
> 
>     * [v0.10 blog post](https://blog.llamaindex.ai/llamaindex-v0-10-838e735948f8)
> 
> 
> Please try this instead
> 
> ```shell
> echo "from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, Document" > run.py
> python3 run.py
> ```
> 
> You need to import those classes from `llama_index.core`. Your virtual env `llama_test` looks fine to me with how you've built it and installed `llama-index`.

@nerdai Apologies, I deleted my comment pretty quickly after I realized my mistake yesterday! Didn't think anybody caught it.

Yes, I completely missed the migration info! The code was a couple of months old.`llamaindex-cli upgrade .` fixed everything. :) Thanks!

**Comment by nerdai** [comment]
Hey no worries at all @rob! Glad you were able to get it resolved on you end. Cheers.

**Comment by maltelandgren** [comment]
Reinstalling llama-index and llama-index-core with Pip instead of Conda worked for me

**Comment by DanielTobi0** [comment]
Same issue in google colaboratory, disconnect and delete runtime worked for me.

**Comment by lmaddox** [comment]
> Reinstalling llama-index and llama-index-core with Pip instead of Conda worked for me

Thanks. I keep ending up back here when I forget to install `llama-index-core` in my minimal environments.
