### ISSUE TITLE
Query Pipeline Sequential Chain With Recursive Retriever : ValueError: Query id not found in either `retriever_dict` or `query_engine_dict`.

### ISSUE THREAD

**Issue by SurajitTest** [run-llama/llama_index#11304]
### Bug Description

Encountered error "ValueError: Query id not found in either `retriever_dict` or `query_engine_dict`." when trying to run a query pipeline sequential chain with recursive retriever

### Version

0.10.11

### Steps to Reproduce

#Instantiate the Large Language Model
model_path =  "C:\\user\\models\\mistral-7b-instruct-v0.2.Q2_K.gguf"

llm = LlamaCPP(
    model_url=None,
    model_path=model_path,
    temperature=0.1,
    max_new_tokens=256,
    context_window=8000,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    model_kwargs={"n_gpu_layers":-1}, 
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)

#Instantiate the embedding model
from llama_index.core.embeddings import resolve_embed_model
embed_model = resolve_embed_model("local:BAAI/bge-large-en-v1.5") ## bge-m3 embedding model

#Process Nodes
from llama_index.core.node_parser import SentenceWindowNodeParser,SimpleNodeParser
from typing import List
from llama_index.core.schema import IndexNode
import re

node_parser = SimpleNodeParser.from_defaults(paragraph_separator=r"\n●|\n-|\n",
                                             chunk_size=250,
                                             chunk_overlap=25,
                                              include_prev_next_rel=True,
                                              include_metadata=True
                                              )
split_nodes = node_parser.get_nodes_from_documents(document)

def custom_sentence_splitter(text: str) -> List[str]:
    return re.split(r'\n●|\n-|\n', text)
	
swindow_node_parser = SentenceWindowNodeParser.from_defaults(
    sentence_splitter=custom_sentence_splitter,
    window_size=3,
    include_prev_next_rel=True,
    include_metadata=True
    )

sub_node_parsers =[swindow_node_parser]

all_nodes = []
for base_node in split_nodes:
    for parser in sub_node_parsers:
        sub_nodes = parser.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)
    # also add original node to node
    original_node = IndexNode.from_text_node(base_node, base_node.node_id)
    all_nodes.append(original_node)	

all_nodes_dict = {n.node_id: n for n in all_nodes}	

#create vector store index and save it 
vector_index_chunk = VectorStoreIndex(all_nodes, embed_model=embed_model)

#Persist the vectorstore
vector_index_chunk.set_index_id("vector_index")
vector_index_chunk.storage_context.persist("C:\user\VectorIndex")

#Load the index created
from llama_index.core import StorageContext, load_index_from_storage
storage_context = StorageContext.from_defaults(persist_dir="C:\\user\\VectorIndex")
vector_index_chunk = load_index_from_storage(storage_context,index_id="vector_index",embed_model=embed_model) 
vector_retriever_chunk = vector_index_chunk.as_retriever(similarity_top_k=5)

#Instantiate Longcontext Reorder
from llama_index.core.postprocessor import LongContextReorder
lim_reorder = LongContextReorder()

#Instantiate the Reranker
from llama_index.core.postprocessor import SentenceTransformerRerank
reranker = SentenceTransformerRerank(model="cross-encoder/ms-marco-MiniLM-L-2-v2",
                                     top_n=5)

#Instantiate RecursiveRetriever
from llama_index.core.retrievers import RecursiveRetriever

retriever_chunk = RecursiveRetriever(
    "vector",
    retriever_dict={"vector": vector_retriever_chunk,"long_context":lim_reorder},
    node_dict=all_nodes_dict,
    verbose=True,
)

#Instantiate the Retriever Query Engine
from llama_index.core.query_engine import RetrieverQueryEngine

query_engine_chunk = RetrieverQueryEngine.from_args(
    retriever_chunk,#RecursiveRetriever - Using Vector Retriever Chunk (VectorStoreIndex as retriever)+ longContextReorder
    #service_context=service_context,
    verbose=True,
    response_mode="compact",
    node_postprocessors=[LongContextReorder(),reranker]
    )

#Initialize a prompt template
from llama_index.core import PromptTemplate
template = ("please answer the question : {question}\n")
prompt_tmpl = PromptTemplate(template)

q = QueryPipeline(chain=[prompt_tmpl,llm,retriever_chunk,query_engine_chunk],verbose=True)

q.run(question="What is data quality?")

### Relevant Logs/Tracbacks

> Running module 03dcc3f9-e1c2-44c2-9a2c-6de4d8411a87 with input: 
question: What is data quality?

> Running module c3ef2202-0b56-44ea-8632-e7f5071813a0 with input: 
prompt: please answer the question : What is data quality?

llama_print_timings:        load time =   56320.71 ms
llama_print_timings:      sample time =      48.15 ms /    93 runs   (    0.52 ms per token,  1931.58 tokens per second)
llama_print_timings: prompt eval time =   56320.45 ms /    73 tokens (  771.51 ms per token,     1.30 tokens per second)
llama_print_timings:        eval time =   66407.05 ms /    92 runs   (  721.82 ms per token,     1.39 tokens per second)
llama_print_timings:       total time =  123312.26 ms /   165 tokens
> Running module f7e8a565-0cdf-43f6-bfbb-803dd96231dd with input: 
input:  Data quality refers to the degree to which data is accurate, complete, consistent, and relevant for its intended use. It is important for ensuring that data is reliable and trustworthy for making inf...

Retrieving with query id None:  Data quality refers to the degree to which data is accurate, complete, consistent, and relevant for its intended use. It is important for ensuring that data is reliable and trustworthy for making informed decisions and for effective data analysis. Data quality can be influenced by various factors such as data sources, data collection methods, data processing, and data usage. Maintaining high data quality is essential for organizations to gain insights from their data and to support their business objectives.
Retrieved node with id, entering: aa54904f-12c3-452f-9e92-c43d695ffac2
Retrieving with query id aa54904f-12c3-452f-9e92-c43d695ffac2:  Data quality refers to the degree to which data is accurate, complete, consistent, and relevant for its intended use. It is important for ensuring that data is reliable and trustworthy for making informed decisions and for effective data analysis. Data quality can be influenced by various factors such as data sources, data collection methods, data processing, and data usage. Maintaining high data quality is essential for organizations to gain insights from their data and to support their business objectives.
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[38], line 1
----> 1 q.run(question="What is data quality?")

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\query_pipeline\query.py:319, in QueryPipeline.run(self, return_values_direct, callback_manager, *args, **kwargs)
    315     query_payload = json.dumps(str(kwargs))
    316 with self.callback_manager.event(
    317     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_payload}
    318 ) as query_event:
--> 319     return self._run(
    320         *args, return_values_direct=return_values_direct, **kwargs
    321     )

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\query_pipeline\query.py:442, in QueryPipeline._run(self, return_values_direct, *args, **kwargs)
    440 root_key, kwargs = self._get_root_key_and_kwargs(*args, **kwargs)
    441 # call run_multi with one root key
--> 442 result_outputs = self._run_multi({root_key: kwargs})
    443 return self._get_single_result_output(result_outputs, return_values_direct)

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\query_pipeline\query.py:544, in QueryPipeline._run_multi(self, module_input_dict)
    542 if self.verbose:
    543     print_debug_input(module_key, module_input)
--> 544 output_dict = module.run_component(**module_input)
    546 # get new nodes and is_leaf
    547 queue = self._process_component_output(
    548     queue, output_dict, module_key, all_module_inputs, result_outputs
    549 )

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\base\query_pipeline\query.py:199, in QueryComponent.run_component(self, **kwargs)
    197 kwargs.update(self.partial_dict)
    198 kwargs = self.validate_component_inputs(kwargs)
--> 199 component_outputs = self._run_component(**kwargs)
    200 return self.validate_component_outputs(component_outputs)

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\base\base_retriever.py:313, in RetrieverComponent._run_component(self, **kwargs)
    311 def _run_component(self, **kwargs: Any) -> Any:
    312     """Run component."""
--> 313     output = self.retriever.retrieve(kwargs["input"])
    314     return {"output": output}

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\base\base_retriever.py:229, in BaseRetriever.retrieve(self, str_or_query_bundle)
    224 with self.callback_manager.as_trace("query"):
    225     with self.callback_manager.event(
    226         CBEventType.RETRIEVE,
    227         payload={EventPayload.QUERY_STR: query_bundle.query_str},
    228     ) as retrieve_event:
--> 229         nodes = self._retrieve(query_bundle)
    230         nodes = self._handle_recursive_retrieval(query_bundle, nodes)
    231         retrieve_event.on_end(
    232             payload={EventPayload.NODES: nodes},
    233         )

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\retrievers\recursive_retriever.py:206, in RecursiveRetriever._retrieve(self, query_bundle)
    205 def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
--> 206     retrieved_nodes, _ = self._retrieve_rec(query_bundle, query_id=None)
    207     return retrieved_nodes

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\retrievers\recursive_retriever.py:182, in RecursiveRetriever._retrieve_rec(self, query_bundle, query_id, cur_similarity)
    179         nodes = obj.retrieve(query_bundle)
    180         event.on_end(payload={EventPayload.NODES: nodes})
--> 182     nodes_to_add, additional_nodes = self._query_retrieved_nodes(
    183         query_bundle, nodes
    184     )
    186 elif isinstance(obj, BaseQueryEngine):
    187     sub_resp = obj.query(query_bundle)

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\retrievers\recursive_retriever.py:117, in RecursiveRetriever._query_retrieved_nodes(self, query_bundle, nodes_with_score)
    112     if self._verbose:
    113         print_text(
    114             "Retrieved node with id, entering: " f"{node.index_id}\n",
    115             color="pink",
    116         )
--> 117     cur_retrieved_nodes, cur_additional_nodes = self._retrieve_rec(
    118         query_bundle,
    119         query_id=node.index_id,
    120         cur_similarity=node_with_score.score,
    121     )
    122 else:
    123     assert isinstance(node, TextNode)

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\retrievers\recursive_retriever.py:170, in RecursiveRetriever._retrieve_rec(self, query_bundle, query_id, cur_similarity)
    167 query_id = query_id or self._root_id
    168 cur_similarity = cur_similarity or 1.0
--> 170 obj = self._get_object(query_id)
    171 if isinstance(obj, BaseNode):
    172     nodes_to_add = [NodeWithScore(node=obj, score=cur_similarity)]

File ~\anaconda3\envs\llm_apps\Lib\site-packages\llama_index\core\retrievers\recursive_retriever.py:150, in RecursiveRetriever._get_object(self, query_id)
    148 if query_engine is not None:
    149     return query_engine
--> 150 raise ValueError(
    151     f"Query id {query_id} not found in either `retriever_dict` "
    152     "or `query_engine_dict`."
    153 )

ValueError: Query id aa54904f-12c3-452f-9e92-c43d695ffac2 not found in either `retriever_dict` or `query_engine_dict`.

```

**Comment by SurajitTest** [comment]
If you're still encountering this issue, could you please provide more information about how you're generating and using the query_id? This will help in identifying the root cause of the issue - I have provided details in Relevant Logs/Tracbacks. Is there any other piece of information that is required ?

**Comment by jack-gits** [comment]
I met the same issue, because program can't find the retriever by index_id.
BTW, I'm using qdrant as vector storage, seems RecursiveRetriever doesn't work for qdrant.
