### ISSUE TITLE
[Question]: If I just want to search for a specific String in a json file, what should I do?

### ISSUE THREAD

**Issue by seanxuu** [run-llama/llama_index#11310]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My scenario is: 
I have a data file: **instruction.json**. It looks like:
```json
[
    {
        "item": "search weather",
        "advice": "use a weather app"
    },
    {
        "item": "time check",
        "advice": "use a clock app"
    },
]
```
And I want to use llama-index to retrieve the whole related content from the **instruction.json**  by just giving the query:"search weather".

The pipeline looks like:
1. embed the **instruction.json**
2. input a query: search weather
3. similarity search from the embedded data and get the **"advice": "use a weather app"**
4. return the whole related json part:    
```json
{
        "item": "search weather",
        "advice": "use a weather app"
    }
```
I'm stuck on the specifics of how to do this, there are just too many APIs for the llama-index.

**Comment by ravi03071991** [comment]
@seanxuu You can create a node object out of each JSON object as string and create an index. Make index behave as retriever and then you can query it.

**Comment by seanxuu** [comment]
> 您可以将每个 JSON 对象创建为字符串的节点对象，并创建索引。使索引行为为检索器，然后您可以查询它。

thanks! but do you have the specific API names to provide?

**Comment by ravi03071991** [comment]
You can get gist of implementation by checking following docs.

https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_nodes.html - creating nodes
https://docs.llamaindex.ai/en/stable/module_guides/querying/retriever/root.html#usage-pattern - index as retriever.
