### ISSUE TITLE
[Question]: How llama-index can handle a large table?

### ISSUE THREAD

**Issue by hoangpnhat** [run-llama/llama_index#11312]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I use llama-index for the Table QA task and have some questions about that.
Case: When I use embedding table by OpenAI, my table contains about 44k tokens. But when I ask the question with function `as_query_engine()`, I analyst that my question just 40-50 tokens but in my Usage in OpenAI recognize that my question is 2000-2050 tokens. Also, I see that llama-index has `default_prompts.py`, which contains various prompt, but when I analyst my question + default_prompts ~ 2050 tokens.
Question: So how OpenAI notices my table?

**Comment by ravi03071991** [comment]
@hoangpnhat for QA on tables, you could probably use - Text2SQL approach - https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo.html

**Comment by hoangpnhat** [comment]
@ravi03071991 thank you for noice my question. But I just want to know where and how LLama-index push my table into content for LLM (in my case is OpenAI) to answer my question.

**Comment by hoangpnhat** [comment]
@dosu-bot , The token from my table is around 44000 tokens.

**Comment by ravi03071991** [comment]
@hoangpnhat You can count the tokens with the help of callback manager - https://docs.llamaindex.ai/en/stable/module_guides/observability/callbacks/token_counting_migration.html
