### ISSUE TITLE
[Feature Request]: Adding Gemma models to run locally for QA end embedding

### ISSUE THREAD

**Issue by khalilxg** [run-llama/llama_index#11316]
### Feature Description

[Feature Request]: Adding Gemma models to run locally for QA end embedding. 

Add gemma to je runned locally or through api exemples will be a brillant add to llamaindex

### Reason

Testing performance

### Value of Feature

5/5

**Comment by ravi03071991** [comment]
we already have a [cookbook](https://github.com/run-llama/llama_index/blob/2ac478fe5af81b605bd327c73de7f375ca155bbb/docs/examples/llm/ollama_gemma.ipynb) to run gemma models with ollama locally.
