### ISSUE TITLE
[Bug]: Validation Error in Bm25 Retreiver

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#11319]
### Bug Description

Getting this error
ValidationError: 1 validation error for NodeWithScore
node
  Can't instantiate abstract class BaseNode with abstract methods get_content, get_metadata_str, get_type, hash, set_content (type=type_error)

### Version

0.10.12

### Steps to Reproduce

bm25_retriever = BM25Retriever.from_defaults(docstore=index.docstore, similarity_top_k=3)
response_synthesizer = get_response_synthesizer()
bm25_query_engine = RetrieverQueryEngine(
    retriever=bm25_retriever,
    response_synthesizer=response_synthesizer,
)
bm25_query_engine.query("query").response

**Comment by ravi03071991** [comment]
@arnavroh45 It did work perfectly for me. Did you follow index creation as mentioned [here](https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever.html) ?

Otherwise I don't see any issue with the code you shared.

**Comment by arnavroh45** [comment]
I did this
s3 = s3fs.S3FileSystem()
persist_dir = "s3_directoryt"
storage_context = StorageContext.from_defaults(persist_dir=persist_dir, fs=s3)
index = load_index_from_storage(storage_context)
query_engine = index.as_query_engine()

**Comment by arnavroh45** [comment]
It is working fine with llama_index==0.9.39

**Comment by ravi03071991** [comment]
@ravi03071991 I am confused is it not working with bm25 retriever?

**Comment by logan-markewich** [comment]
@arnavroh45 in v0.10.x, there was a bit of a change to the codebase. It seems like you might have been mixing `llama_index.legacy` imports with newer imports

Either all imports are from `.legacy`, or none are
