### ISSUE TITLE
[Bug]: Base Url ignored with Ollama

### ISSUE THREAD

**Issue by KaiMildner** [run-llama/llama_index#11321]
### Bug Description

Hi

When i try to devlop inside a dev container i cannot use the ollama server from the host.
The server ist reachable via bash with curl http://192.168.2.101:11434 from inside the container.

I set the base url in the Ollama llm model:

`Settings.llm = Ollama(baseURL = "http://192.168.2.101:11434", model="mistral", request_timeout=30.0)`

I can use the vector store:

`index = VectorStoreIndex.from_documents(documents, llm=Settings.llm)`

I can get the query engine from index:

`query_engine = index.as_query_engine(llm=Settings.llm)`

But when i try to query:
`response = query_engine.query("What did the author do growing up?")`
i get:

`DEBUG:httpcore.connection:connect_tcp.started host='localhost' port=11434 local_address=None timeout=30.0 socket_options=None
connect_tcp.started host='localhost' port=11434 local_address=None timeout=30.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))
connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))`

Why does it try to connect to localhost? 
The base url in the model is set everywhere:
![image](https://github.com/run-llama/llama_index/assets/46740508/813a6818-207a-4f06-9967-c94dbda96003)

So is this a bug that it doesn't use the url instead of localhost, or have i done something wrong?

### Version

0.10.12

### Steps to Reproduce

1. Start Ollama Server with OLLAMA_HOST 0.0.0.0:11434 to listen on all devices.
2. Start a dev container with docker.
3. Inside the container try to reach ollama server http://<your_ollama_server>:11434
4. Start developing an app.
5. Use this code, replace the ip with your ollama server ip:

`from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
from llama_index.core.embeddings import resolve_embed_model
from llama_index.llms.ollama import Ollama
import logging
import sys

documents = SimpleDirectoryReader("LLama/data").load_data()
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

Settings.embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")

Settings.llm = Ollama(baseURL = "http://192.168.2.101:11434", model="mistral", request_timeout=30.0)

index = VectorStoreIndex.from_documents(
    documents, llm=Settings.llm
)

query_engine = index.as_query_engine(llm=Settings.llm)
response = query_engine.query("What did the author do growing up?")
print(response)`

This should result in 

`httpcore.connection:connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))
connect_tcp.failed exception=ConnectError(ConnectionRefusedError(111, 'Connection refused'))`

**Comment by KaiMildner** [comment]
@dosu-bot. Thank you. there was a type in my code instead of base_url i wrote baseURL. I really missed that. So thanks for your help. Its now working.

**Comment by anoopshrma** [comment]
Hey @idoru 
I think you can try this also:

Set `OLLAMA_HOST` in your env with your base_url. 

This should get picked and you can continue as earlier without using custom LLM wrapper.
