### ISSUE TITLE
save_to_disk and load_from_disk do not work for GPTSQLStructStoreIndex

### ISSUE THREAD

**Issue by jamesoutgo** [run-llama/llama_index#1132]
Hi, I used sqlalchemy to read my database, and llama-index was able to generate a correct query from my prompt. I would like to be able to save the index into a JSON so it does not have to read the whole database every time I want to submit a query. However, I keep getting an error that suggests that the `save_to_disk` and `load_to_disk` are looking for different keys.

My saving file:
```
conn_string = <connection_string>
engine = create_engine(
    conn_string
)

sql_database = SQLDatabase(
    engine,
    include_tables=[<tables>]
)

llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-002"))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)

index = GPTSQLStructStoreIndex(
    sql_database=sql_database,
    service_context=service_context,
)

index.save_to_disk(<my_path>)
```

My loading file:
```
index = GPTSQLStructStoreIndex.load_from_disk(<my_path>)

response = index.query(<my_prompt>, mode="default")
```

I always get the error:
```  File "/opt/homebrew/lib/python3.10/site-packages/llama_index/indices/base.py", line 302, in load_from_dict
    index_struct = load_index_struct_from_dict(result_dict[INDEX_STRUCT_KEY])
KeyError: 'index_struct'
```
And when I check my saved JSON, it has no `index_struct` key.

Looking at the code for GPTSQLStructStoreIndex suggests that it uses different methods than the Base Index for saving to and loading from disk. (https://github.com/jerryjliu/llama_index/blob/0bb81358f6d6e35896d64371967fedc01a9ff0bb/gpt_index/indices/struct_store/sql.py). Has anyone else had issues saving and loading SQL Indices? Is there a known workaround for what I trying to do? Thanks!

**Comment by DylanAlloy** [comment]
They don't work for anything apparently/

**Comment by sheresaidon** [comment]
i have the same issue any updates on this?

**Comment by muhammad-ahsan099** [comment]
facing same issue, any update here?
