### ISSUE TITLE
[Question]: How to set max output tokens with llama_index, Ollama and Mixtral ? 

### ISSUE THREAD

**Issue by antoinelemor** [run-llama/llama_index#11337]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to set max output tokens with llama_index, Ollama and Mixtral ? I tried this but it doesn't work. Someone can help ? 

import pandas as pd
import os
from llama_index.llms.ollama import Ollama
from transformers import AutoTokenizer
from llama_index.core import Settings

Configure the settings for the LLM
Settings.llm = Ollama(model="mixtral:8x7b-instruct-v0.1-q5_K_M", max_tokens=5)

Initialize the Ollama model with the modified settings
llm = Settings.llm

**Comment by logan-markewich** [comment]
@antoinelemor looks like that setting isn't currently exposed. Does ollama provide config for that value?

**Comment by antoinelemor** [comment]
@logan-markewich the num_predict seems to allow for that

**Comment by logan-markewich** [comment]
@antoinelemor but it's not actually telling the LLM to output more or less, it's just creating room for that amount of tokens

**Comment by antoinelemor** [comment]
@logan-markewich ok. Is there any solutions to that?

**Comment by logan-markewich** [comment]
Not sure, I think someone just needs to make a PR to allow configuring that (if ollamas api has a config for that)
