### ISSUE TITLE
[Question]: Ingestion Pipeline and KG not utilizing GPU

### ISSUE THREAD

**Issue by mohammad-yousuf** [run-llama/llama_index#11344]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have an ingestion pipeline that is supposed to process (> 15000 nodes) for metadata extraction. Here is my code:

```
from llama_index.core.node_parser import TokenTextSplitter
from llama_index.core.extractors import (
    SummaryExtractor,
    QuestionsAnsweredExtractor,
)

node_parser = TokenTextSplitter(
    separator=" ", chunk_size=256, chunk_overlap=128
)

orig_nodes = node_parser.get_nodes_from_documents(documents)

extractors_1 = [
    QuestionsAnsweredExtractor(
        questions=3, llm=llm, metadata_mode=MetadataMode.EMBED, num_workers=4
    ),
]

# process nodes with metadata extractors
pipeline = IngestionPipeline(transformations=[node_parser, *extractors_1])

nodes_1 = pipeline.run(nodes=orig_nodes, in_place=False, show_progress=True)
```

The process gets stuck even if I change extractors. I am also getting recursion error if include num_workers = x in ingestion pipeline.

Same with knowledge graphs:

```
graph_store = SimpleGraphStore()
storage_context = StorageContext.from_defaults(graph_store=graph_store)

# NOTE: can take a while!
index = KnowledgeGraphIndex.from_documents(
    documents,
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)
```

Is there a way to speed up this or specify to use CUDA as I have multiple GPUs.

LLM: "meta-llama/Llama-2-13b-chat-hf"
Embedding model: 'BAAI/bge-large-en-v1.5'

- 2x Nvidia A40 (96 GB VRAM)
- 100 GB RAM
- 18 vCPU

**Comment by ravi03071991** [comment]
@mohammad-yousuf how are you initializing LLM? A lot depends on that. You can use the device parameter in general for LLM initialization and then multi-gpu functionality will be automatically used.
