### ISSUE TITLE
[Question]: Alternatives to MultiModalVectorStoreIndex？

### ISSUE THREAD

**Issue by SnowNation101** [run-llama/llama_index#11357]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

I'm studying the chapter "Advanced Multimodal Retrieval Using GPT4V and Multimodal Indexers/Retrievers" in the official document. I want to use LLaVA to replace GPT4V to do the same things, in the step:
```python
# Create a local Qdrant vector store
client = qdrant_client.QdrantClient(path="qdrant_mm_db")

text_store = QdrantVectorStore(
    client=client, collection_name="text_collection"
)
image_store = QdrantVectorStore(
    client=client, collection_name="image_collection"
)
storage_context = StorageContext.from_defaults(
    vector_store=text_store, image_store=image_store
)

# Create the MultiModal index
documents = SimpleDirectoryReader("./mixed_wiki/").load_data()
index = MultiModalVectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)
```
1. is `MultiModalVectorStoreIndex` proper for LLaVA?
2. what VectorStoreIndex can I use if I don't have an OpenAI API key

**Comment by ravi03071991** [comment]
@SnowNation101 You can use vectorstore index with llava model on replicate. You just need to swap openai multi modal llm with replicate llava model as show in the documentation [here](https://docs.llamaindex.ai/en/stable/examples/multi_modal/replicate_multi_modal.html).

**Comment by SnowNation101** [comment]
`MultiModalVectorStoreIndex` seems to require an openai API key, what settings can I use if I dont have one?

**Comment by ravi03071991** [comment]
@SnowNation101 You can include llm in settings. 

```python
from llama_index.core import Settings

Settings.llm = <replicate_multimodal>
Settings.embed_model = <embedding_model>
```
