### ISSUE TITLE
[Question]: Using an LLM hosted using LocalAI to query documents

### ISSUE THREAD

**Issue by ManishAradwad** [run-llama/llama_index#11350]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I am trying to use a phi-2.Q2_k model hosted on my local machine with LocalAI to query documents. I have written below code for that:

```from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.llms.openai import OpenAI
import os

base_path = os.environ.get("OPENAI_API_BASE", "http://localhost:8080/v1/")
documents = SimpleDirectoryReader("resources").load_data(show_progress=True)

# define LLM
model = OpenAI(temperature=0.1, model_name="phi-2.Q2_k", openai_api_base=base_path)

# build index
index = VectorStoreIndex.from_documents(documents, llm=model)

# get response from query
query_engine = index.as_query_engine()
response = query_engine.query("some question for the doc")

print(response)
```

I'm getting an empty response as a result. When I checked, the locally hosted model is not getting the request at all. If I try to use some OpenAI model like "gpt-3.5-turbo" then I get the right response. But I want to use locally hosted models. Any help if appreciated.

**Comment by ManishAradwad** [comment]
> _🤖_
> 
> Hey there, @ManishAradwad! Great to see you diving into another challenge. Looking forward to tackling this one with you.
> 
> Based on the code you've shared, it seems like you're using the `OpenAI` class to initialize your model. However, if you're using a locally hosted model with LocalAI, you should be using the `LocalAI` class instead. The `OpenAI` class is designed to interact with models hosted on OpenAI's servers, not locally hosted models.
> 
> Here's how you can modify your code to use the `LocalAI` class:
> 
> ```python
> from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
> from llama_index.llms.localai import LocalAI
> import os
> 
> base_path = os.environ.get("OPENAI_API_BASE", "http://localhost:8080/v1/")
> documents = SimpleDirectoryReader("resources").load_data(show_progress=True)
> 
> # define LLM
> model = LocalAI(temperature=0.1, model_name="phi-2.Q2_k", api_base=base_path)
> 
> # build index
> index = VectorStoreIndex.from_documents(documents, llm=model)
> 
> # get response from query
> query_engine = index.as_query_engine()
> response = query_engine.query("some question for the doc")
> 
> print(response)
> ```
> 
> In this code, I've replaced `OpenAI` with `LocalAI`. This should allow your code to interact with your locally hosted model.
> 
> If you're still getting an empty response after making this change, it could be due to one of the following reasons:
> 
> 1. Your model is not hosted at the URL specified in `api_base`. Make sure that your model is hosted at the correct URL and that the URL is correctly specified in your code.
> 2. Your model is not configured to accept requests on the `/v1` endpoint. Check the endpoints your model is configured to accept requests on and update the `api_base` parameter accordingly.
> 3. The `globally_use_chat_completions` parameter is not set correctly. This parameter determines whether to use the `/chat/completions` or `/completions` endpoint for API calls. If it's not set, the `_is_chat_model` property will raise a `NotImplementedError`. You can set this parameter to `True` or `False` when initializing the LocalAI class, or pass the `use_chat_completions` argument in your query.
> 
> If none of these solutions work, please provide more information about your setup, such as the version of LlamaIndex you're using, the configuration of your locally hosted model, and any error messages you're seeing. This will help me better understand the issue and provide a more accurate solution.
> 
> ## Sources
> * [llama-index-integrations/llms/llama-index-llms-localai/llama_index/llms/localai/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-localai/llama_index/llms/localai/base.py?rgh-link-date=2024-02-24T06%3A57%3A15Z)
> * [llama-index-core/llama_index/core/llms/custom.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/llms/custom.py?rgh-link-date=2024-02-24T06%3A57%3A15Z)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

ModuleNotFoundError: No module named 'llama_index.llms.localai'

**Comment by anoopshrma** [comment]
Hi @ManishAradwad 
You'll have to install the package for localAI first: `pip install llama-index-llms-localai`

**Comment by ManishAradwad** [comment]
Thanks @anoopshrma!

It's working now. But I have a confusion. I'm getting the response, but not sure if it's using the LocalAI model. I saw the hosted mode wasn't getting queried.

So I did some tests. I got the response even if I don't have a model running on `http://localhost:8080/v1/`. I checked this by even changing the name of the model to some random name. It still gives me the response. Is it still using openai model??

**Comment by anoopshrma** [comment]
Do you have openai key saved in your code somewhere? Ideally it should only call your local ai instance!

**Comment by ManishAradwad** [comment]
I have it as an env variable

**Comment by anoopshrma** [comment]
Yes remove OPENAI variable and then try

**Comment by ManishAradwad** [comment]
It's happening even after removing the api key. here's the complete code I'm using:

```
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
from llama_index.llms.localai import LocalAI
import os

base_path = os.environ.get("OPENAI_API_BASE", "http://localhost:8080/v1/")
documents = SimpleDirectoryReader("resources").load_data(show_progress=True)

# define LLM
model = LocalAI(temperature=0.1, model="phi-2.Q_k", api_base=base_path)

# build index
index = VectorStoreIndex.from_documents(documents, llm=model)
# index.storage_context.persist(persist_dir="./storage")

# get response from query
query_engine = index.as_query_engine()
response = query_engine.query(
    "question"
)
print(response)
```
