### ISSUE TITLE
[Question]: Can MultiStepQueryEngine use SubQuestionQueryEngine?

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#11371]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

As the title, it mean that multi-step queries can operate based on the foundation of multi-document queries? If so, how?

**Comment by ravi03071991** [comment]
@Hspix You can use `SubQuestionQueryEngine` as a query_engine in `MultiStepQueryEngine` and that should work for you.
