### ISSUE TITLE
[Documentation]: wrong code snippet 

### ISSUE THREAD

**Issue by ml2s** [run-llama/llama_index#11382]
### Documentation Issue Description

This is from the example multi_modal_retrieval.ipynb:

> **Build a separate CLIP image embedding index under a differnt collection wikipedia_img**
> ```
> def plot_images(image_paths):
>     images_shown = 0
>     plt.figure(figsize=(16, 9))
>     for img_path in image_paths:
>         if os.path.isfile(img_path):
>             image = Image.open(img_path)
> 
>             plt.subplot(2, 3, images_shown + 1)
>             plt.imshow(image)
>             plt.xticks([])
>             plt.yticks([])
> 
>             images_shown += 1
>             if images_shown >= 9:
>                 break
> ```

The code seems to be copied and pasted from somewhere else, and has nothing to do with creating image embedding with CLIP. Can you please fix it so I could learn how to embed images? Thanks!

### Documentation Link

docs/examples/multi_modal/multi_modal_retrieval.ipynb

**Comment by ravi03071991** [comment]
@ml2s The code snippet you shared is to plot the images. While creating an index, images will be automatically embedded using CLIP Embeddings under the hood.

**Comment by ravi03071991** [comment]
@ml2s You can check the image embedding function [here](https://github.com/run-llama/llama_index/blob/cc8e1ee48c67dc26caf3e7b7a75a10ad44874dc2/llama-index-integrations/embeddings/llama-index-embeddings-clip/llama_index/embeddings/clip/base.py#L133) for reference.
