### ISSUE TITLE
[Question]: include_text parameter in index.as_query_engine method

### ISSUE THREAD

**Issue by DataNoob0723** [run-llama/llama_index#11380]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I don't quite understand the include_text parameter in index.as_query_engine method. What's the difference between when it is set to be True or False please? Thanks a lot!

**Comment by logan-markewich** [comment]
This is specific to knowledge graph indexes.

If it's true, the chunk where a matching triplet is found will also be sent to the LLM

If false, then only the matching triplets are sent to the LLM

**Comment by DataNoob0723** [comment]
> This is specific to knowledge graph indexes.
> 
> If it's true, the chunk where a matching triplet is found will also be sent to the LLM
> 
> If false, then only the matching triplets are sent to the LLM

Thanks a lot!
