### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by miteshgarg** [run-llama/llama_index#11394]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Guys, I want to use NLSQLTableQueryEngine and SQLTableRetrieverQueryEngine with local offline fine tune llm model downloaded on my system. Please suggest what is the exact implementation of the same

**Comment by miteshgarg** [comment]
How exactly you initialize your local model in below code
# Initialize your local LLM model
llm_model = ...  # Load your local LLM model here

**Comment by logan-markewich** [comment]
Try using something like `Ollama`

Download and install Ollama
Run `ollama serve`

Download the model you want to use with `ollama pull gemma:7b` or similar 

Install the ollama integration `pip install llama-index-llms-ollama`

Setup the LLM
```
from llama_index.llms.ollama import Ollama

llm = Ollama(model="gemma:7b", request_timeout=1000)
```

**Comment by miteshgarg** [comment]
> Try using something like `Ollama`
> 
> Download and install Ollama Run `ollama serve`
> 
> Download the model you want to use with `ollama pull gemma:7b` or similar
> 
> Install the ollama integration `pip install llama-index-llms-ollama`
> 
> Setup the LLM
> 
> ```
> from llama_index.llms.ollama import Ollama
> 
> llm = Ollama(model="gemma:7b", request_timeout=1000)
> ```

Hi Logan, here I have local fine-tuned model with all its weights downloaded on local machine.
I suppose Ollama will be able to pull only those models which are in it's repository.
What can i do when I have a local offline model downloaded on my machine and want to use that.

Useally when I want to use the model, I use transformers like below:
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    trust_remote_code=True,
    device_map="auto",
    use_cache=True,
    offload_folder="offload",
    torch_dtype=torch.float16,
    quantization_config=quantization_config
)

**Comment by logan-markewich** [comment]
That's fine too. You can load the model like that and pass it into HuggingFaceLLM class too, just a bit more annoying to setup since you need to worry about prompt formatting
