### ISSUE TITLE
[Question]: What do 'context_str' and ''query_str' stand for in Prompts?

### ISSUE THREAD

**Issue by Vector6662** [run-llama/llama_index#11399]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I've read Prompt Templates already, but still failed to get the points of `{context_str}`, `{query_str}` in template([link](https://docs.llamaindex.ai/en/stable/module_guides/models/prompts.html#usage-pattern)):
```python
from llama_index.core import PromptTemplate

template = (
    "We have provided context information below. \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given this information, please answer the question: {query_str}\n"
)
qa_template = PromptTemplate(template)

# you can create text prompt (for completion API)
prompt = qa_template.format(context_str=..., query_str=...)

# or easily convert to message prompts (for chat API)
messages = qa_template.format_messages(context_str=..., query_str=...)
```

My question is:

1.If I execute a query:
```python
print(
    index.as_query_engine(
        text_qa_template=text_qa_template,
        refine_template=refine_template,
        llm=llm,
    ).query("Who is Joe Biden?")
)
```
will "Who is Joe Biden?" replace `{query_str}` in the `template`?

2.As we know, there will be several `Node`(s) (which are very relevant to query "Who is Joe Biden?") be retrieved. Will these retrieved `Node's be inserted into {context_str} in the `template` string?

3.Any documents on this topic? I think I may miss some important points.🤣

Thanks!

**Comment by logan-markewich** [comment]
The bot did a great job with this answer!

**Comment by Vector6662** [comment]
Thanks for the answer, but still questions remain.

1.When willl `context_str` and `query_str` be replaced? It there any source code I can read?
2.Are `context_str` and `query_str` **fixed** parameter names? I mean, if I change `context_str` to `context`/`str_context`, will it still be replaced successfully?
3.If I introduce custom params like `{items}`, when can I replace this params?
4.I know I can use method `format()` but return value of `format()` is not template itself, which can't be used in a query: A Query Engine can update its template, but params are `PromptTemplate`, not a `str`!
```python
from llama_index.core.prompts import LangchainPromptTemplate

lc_prompt_tmpl = LangchainPromptTemplate(
    template=langchain_prompt,
    template_var_mappings={"query_str": "question", "context_str": "context"},
)
query_engine.update_prompts(
    {"response_synthesizer:text_qa_template": lc_prompt_tmpl}
)
```
So, where can I use a formated template? Is it just for demonstration?

**Comment by Vector6662** [comment]
hi @logan-markewich, can this issue be re-opened? still need answers.

**Comment by logan-markewich** [comment]
@Vector6662 they are parsmeter names. They are filled in within a response synthesizer module.

The names need to be consistent. Or it will cause issues with string formatting.

New items introduced need to be formatted before using the template in a synthesizer (of alternatively, you can create your own custom query pipeline)

Check out the source code for response synthesizers 
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/response_synthesizers/refine.py

As well as query pipeline docs
https://docs.llamaindex.ai/en/stable/module_guides/querying/pipeline/root.html

**Comment by logan-markewich** [comment]
I would recommend reaching out on discord for questions in the future -- probably faster responses
