### ISSUE TITLE
[Bug]: no DFFullProgram, DataFrame, and DataFrameRowsOnly in 'llama_index.core.program' 

### ISSUE THREAD

**Issue by IrynaKuz** [run-llama/llama_index#11402]
### Bug Description

I tried to run df_program.ipynb but getting import errors.

 DFFullProgram, DataFrame, and DataFrameRowsOnly cannot be imported from 'llama_index.core.program' (/usr/local/lib/python3.10/dist-packages/llama_index/core/program/__init__.py) because seems like they do not exist there.

### Version

v0.10.12

### Steps to Reproduce

from llama_index.core.program import (
    DFFullProgram,
    DataFrame,
    DataFrameRowsOnly,
)

**Comment by logan-markewich** [comment]
`pip install llama-index-program-evaporate`

`from llama_index.program.evaporate.df import DFFullProgram, DataFrame, and DataFrameRowsOnl`
