### ISSUE TITLE
[Question]:Using semantic router with llamaindex

### ISSUE THREAD

**Issue by reachrkr** [run-llama/llama_index#11415]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am looking for integrating [semantic router](https://github.com/aurelio-labs/semantic-router/tree/main)? Is there any way to achieve this ?

**Comment by logan-markewich** [comment]
Someone would have to contribute semantic router as an integration 

Tbh we have something very similar though 
https://docs.llamaindex.ai/en/stable/examples/query_engine/RetrieverRouterQueryEngine.html

In fact, we have a lot of routers
https://docs.llamaindex.ai/en/stable/module_guides/querying/router/root.html#routers

**Comment by reachrkr** [comment]
@logan-markewich  Thanks for your input ,  will check and comeback on this
