### ISSUE TITLE
[Bug]: PromptHelper not adjusting Context window

### ISSUE THREAD

**Issue by CHesketh76** [run-llama/llama_index#11416]
### Bug Description

I am running into issues with both the ```PromptHelper``` and ```ServiceContext``` not adjusting a large context window down to my a small 1024 token context size. 

I using a gpt2-small model which only has a max context size of 1024 tokens and is being hosted on vLLM. This is for debugging purposes, but non-adjusting context window is a huge issue and  I am surprised no one has discovered this bug.

Here is another user who asked a similar question but there was no appropriate solution provided. I used this users code and made some changes at the end to match my code. 
https://github.com/run-llama/llama_index/issues/8113

Below is some example code
```
from llama_index.llms import OpenAI
from llama_index.llms.base import ChatMessage
from llama_index.chat_engine import SimpleChatEngine
from llama_index import ServiceContext, PromptHelper
from llama_index.text_splitter import TokenTextSplitter
from llama_index.node_parser import SimpleNodeParser

import pandas as pd
import glob
import os

csv_files = glob.glob('data/csv/*.csv')
df = pd.read_csv(
    csv_files[1],
    sep='|'
)
context_comments = df['COMENTARIO'].to_list()

context_message = f"""Estos son los comentarios que los usuarios han dejado en una publicación de una empresa de supermercados en diferentes redes sociales: \n \
                                        {context_comments}. \n \
                                        Se te van a hacer preguntas sobre los comentarios de la misma, a las que deberás responder con precisión, \
                                        como si estuvieras redactando un informe para los responsables de la publicación, que quieren saber la acogida que ha tenido."""
prefix_messages = [ChatMessage(content=context_message, role="system")]

# Define the LLM
llm = AzureOpenAI(
    model=MODEL_NAME,
    engine=DEPLOYMENT_NAME,
    api_key=OPENAI_API_KEY,
    api_base=BASE_URL,
    api_type="openai"
)


  text_splitter=TokenTextSplitter(chunk_size=512, chunk_overlap_ratio=0.2)
)

# Define prompt helper
prompt_helper = PromptHelper(
  context_window=1024,
  num_output=512,
  chunk_overlap_ratio=0.2,
  separator="\n"
)

# Create the service context
service_context = ServiceContext.from_defaults(
    llm=llm,
    prompt_helper=prompt_helper,
    node_parser=node_parser,
    embed_model=None,
    chunk_size=256,
    context_window=1024,
    num_output=512
)

system_prompt = "You are a helpful chatbot."

query_engine = index.as_chat_engine(
  chat_mode = "context",
  system_prompt = (system_prompt)
)

query = ["This is a lot of context"] * 1_000 # creating a query over 1024 tokens long
query = ' '.join(query) # creating a query over 1024 tokens long

response = query_engine.chat(query)

```

### Version

0.9.36

### Steps to Reproduce

1.) load in any model into vll or use chatgpt3.5 (just make sure to create a very large query)
2.) use the code above (might need to make some edits)
3.) expected error should be token limit issue.

**Comment by logan-markewich** [comment]
I think there's a misunderstanding about where prompt helper is used.

It's only used inside the response synthesizer, which is inside a query engine.

Here, you have a context chat engine. It uses the newest user message to retrieve context, inserts that context into system prompt, and then sends that along with the current buffer of chat history to the LLM. No prompt helper involved

**Comment by CHesketh76** [comment]
@logan-markewich How do I limit the context going to and from the model then?

**Comment by CHesketh76** [comment]
I found some type of work around to prevent an error from showing up (see arrow below), but I do not like this because I have how it is being limited.
```
service_context = ServiceContext.from_defaults(
    llm=llm,
    prompt_helper=prompt_helper,
    node_parser=node_parser,
    embed_model=None,
    chunk_size=256,
    context_window=1024,
    num_output=512,
    chunk_size_limit=512 # <-- this
)
```

**Comment by logan-markewich** [comment]
The main control here is
- chunk size
- top k (default is 2]
- the token limit in the memory buffer

**Comment by CHesketh76** [comment]
Just for clarification and for future readers/reference.

- **chunk size** is in the ServiceContext class
- **top_k** You mean ```similarity_top_k``` which is a variavle in the ```index.query()``` function
- **token limit in the memory buffer** you mean the ```llama_index.core.memory.ChatMemoryBuffer``` class

**Comment by logan-markewich** [comment]
this is correct!

**Comment by CHesketh76** [comment]
@logan-markewich After applying ```chunk_size_limit=200```, ```similarity_top_k```, and ```applying a token limit to the ChatMemoryBuffer``` the issue is still present, the bug can easily be reproduced by having long chat history.

- ChatMemoryBuffer will only return an error if the token threshold goes over, it does not assist removing text from the chat history + user input + retrieved documents.
- similarity_top_k is only for the  retrieved documents which doesn't really resolve anything.
- chunk size for the ServiceContext does not appear to be trimming down any of the pulled documents after inputting a query.

After changing all of these parameter to different sizes, the number of tokens being sent over the API remains unchanged.

**Comment by logan-markewich** [comment]
@CHesketh76

So to clarify again how context chat engine works
- each user message is used to retrieve co text. The default top k is 2 and the default chunk size os 1024. This means at least 2*1024 tokens are used in the input (so yes, top k does have an effect on token usage. And so does chunk size)
- the token counting from the context above is used in the chat memory as an initial token count. Then, the chat history retrieves the last X messages such that len(context)+len(messages) is less than the token limit of the memory

For example, I might have a setup like 

```
from llama_index.core.memory import ChatMemoryBuffer

memory = ChatMemortBuffer.from_defaults(token_limit=3900)

chat_engine = index.as_chat_engine(chat_mode="context", memory=memory, similarity_top_k=2)
```

All token counting is done using tiktoken, and defaults to counting for openai models.

If you aren't using openai, then you can set a different global tokenizer
https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/settings.html#tokenizer

**Comment by logan-markewich** [comment]
Also, here's the source code for chat() in co text chat engine
https://github.com/run-llama/llama_index/blob/d95f3fda81654ac133f3754df4f23d7a0b37b43c/llama-index-core/llama_index/core/chat_engine/context.py#L154
