### ISSUE TITLE
[Question]: Validation errors for vector query spec

### ISSUE THREAD

**Issue by rishabhgupta93** [run-llama/llama_index#11421]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Experts, 

I have been getting an error while trying to retrieve using vectorindexautoretriever. Please help!!!

from llama_index.schema import TextNode
from dbaccess.SQLConnection import SQLConnection
from dbaccess.ReadSchema import ReadSchema

ps_proj_connection = SQLConnection(
    username='abc',
    pwd='abc',
    host='abc',
    port=3452,
    service='abc2023'
)
read_schema = ReadSchema(sqlconnection=ps_proj_connection)

def get_nodes_from_dataframe(df):
    nodes = list()

    for index, row in df.iterrows():
        node = TextNode(
            text=row.complete_table_description,
            metadata={
                "entity": row.entity,
                "description": row.description
            }
        )
        nodes.append(node)

    return nodes

all_nodes = get_nodes_from_dataframe(read_schema.GetAlltobeIndexedEntities)

from llama_index import VectorStoreIndex
from llama_index.llms import Ollama
from llama_index.embeddings import OllamaEmbedding
from llama_index.service_context import ServiceContext

embed_model = OllamaEmbedding(model_name='nomic-embed-text')
llm = Ollama(model='llama2', request_timeout=3000)
service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)

index = VectorStoreIndex(
    nodes=all_nodes, show_progress=True, service_context=service_context
)

from llama_index.vector_stores.types import VectorStoreInfo, MetadataInfo
vector_store_info = VectorStoreInfo(
    content_info="Stores the summary of the entity (table or view), which includes description of table, list of attributes, description of attributes and datatypes of attributes",
    metadata_info=[
        MetadataInfo(
            name="entity",
            description="Name of entity (table or view)",
            type="string"
        ),
        MetadataInfo(
            name="description",
            description="description of entity (table or view)",
            type="string"
        ),
    ],
)

from llama_index.retrievers import VectorIndexAutoRetriever

retriever = VectorIndexAutoRetriever(
    index,
    vector_store_info=vector_store_info,
    # similarity_top_k=1,
    # empty_query_top_k=10,  # if only metadata filters are specified, this is the limit
    verbose=True,
)

relevant_nodes = retriever.retrieve('Give me the all the wells with status abandoned')

print(relevant_nodes)

Getting following error:

Generating embeddings: 100%|██████████| 3/3 [00:41<00:00, 13.73s/it]
Traceback (most recent call last):
  File "F:\PyCharmProjects\sql-extract-vectorise\temp.py", line 261, in <module>
    relevant_nodes = retriever.retrieve('Give me the all the wells with status abandoned')
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\llama_index\core\base_retriever.py", line 224, in retrieve
    nodes = self._retrieve(query_bundle)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\llama_index\core\base_auto_retriever.py", line 35, in _retrieve
    retrieval_spec = self.generate_retrieval_spec(query_bundle)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\llama_index\indices\vector_store\retrievers\auto_retriever\auto_retriever.py", line 170, in generate_retrieval_spec
    return self._parse_generated_spec(output, query_bundle)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\llama_index\indices\vector_store\retrievers\auto_retriever\auto_retriever.py", line 141, in _parse_generated_spec
    StructuredOutput, self._output_parser.parse(output)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\llama_index\indices\vector_store\retrievers\auto_retriever\output_parser.py", line 12, in parse
    query_and_filters = VectorStoreQuerySpec.parse_obj(json_dict)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\pydantic\v1\main.py", line 526, in parse_obj
    return cls(**obj)
  File "F:\PyCharmProjects\sql-extract-vectorise\venv\lib\site-packages\pydantic\v1\main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for VectorStoreQuerySpec
query
  field required (type=value_error.missing)
filters
  field required (type=value_error.missing)

**Comment by logan-markewich** [comment]
This specific feature requires the LLM to output a structured JSON that is then parsed. Open-Source LLMs tend to be a little bad at this.

In this case, llama2 is not returning every required field it seems. I would try using a different LLM maybe.
