### ISSUE TITLE
[Question]: Some questions about the algorithmic aspects of similarity_top_k.

### ISSUE THREAD

**Issue by shuozhu1** [run-llama/llama_index#11429]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When I set similarity_top_k=3, after querying it only returned two with the highest similarity for me, not three chunks.

Here's part of my code：

#基于原节点构建子节点
all_nodes = []
for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_i_nodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
            ]
        all_nodes.extend(sub_i_nodes)

    #添加父节点文档
    original_node = IndexNode.from_text_node(base_node,base_node.node_id)
    all_nodes.append(original_node)

print(len(all_nodes))
#创建一个节点id和节点对应的字典
all_nodes_dict = {n.node_id: n for n in all_nodes} #字典推导式

#进行递归检索
from llama_index.core.retrievers import RecursiveRetriever
from llama_index.core import get_response_synthesizer

vector_index_chunk = VectorStoreIndex(
    all_nodes, service_context=service_context
)

vector_retriever_chunk = vector_index_chunk.as_retriever(similarity_top_k=3)

#定义检索器
retriever_chunk = RecursiveRetriever(
    "vector",
    retriever_dict={"vector": vector_retriever_chunk},
    node_dict=all_nodes_dict,
    verbose=True,
)
#定义提示模板
response_synthesizer = get_response_synthesizer(response_mode="tree_summarize")
#递归检索
nodes = retriever_chunk.retrieve(
   "我国第一条轨道交通线路在哪里运营？"
)
for node in nodes:
    display_source_node(node, source_length=1000)

#提问并传入llm
from llama_index.core.query_engine import RetrieverQueryEngine

#定义查询引擎
query_engine_chunk = RetrieverQueryEngine.from_args(
    retriever_chunk, service_context=service_context,response_synthesizer=response_synthesizer
)

response = query_engine_chunk.query(
    "我国第一条轨道交通线路在哪里运营？"
)
pp.pprint(str(response))

Here's my output：（only two！！！）

Retrieving with query id None: 我国第一条轨道交通线路在哪里运营？
Retrieved node with id, entering: fcb8d82d-e9c4-484f-8253-393aa4c031fb
Retrieving with query id fcb8d82d-e9c4-484f-8253-393aa4c031fb: 我国第一条轨道交通线路在哪里运营？
Retrieved node with id, entering: e9ac2319-d9e4-4e40-b289-2422542bad64
Retrieving with query id e9ac2319-d9e4-4e40-b289-2422542bad64: 我国第一条轨道交通线路在哪里运营？
Node ID: fcb8d82d-e9c4-484f-8253-393aa4c031fb
Similarity: 0.5775430487905047
Text: 2　国内外研究现状及发展动态分析 2.1　国内发展现状和动态我国对应急管理工作开始系统的研究始于2003年的SARS疫情，2003年以前，国内的应急管理体系上尚不是很健全，各地区只有政府各级的应急管理办公室，经历了这次的公共卫生事件后 ，国家各部门汲取深刻教训，逐步建立并完善了我国的应急管理体系[1]。同时，我国城市轨道交通发展起步较晚，1971年我国第一条地铁在北京投入运营，2000年我国仅北京、天津、上海、广州四个城市拥有城市轨 道交通线。进入21世纪以来，随着我国城市化进程的加快和经济的高速发展，城市轨道交通也进入飞速发展时期，目前已经内地共有51个城市开通运营城市轨道交通，共拥有运营里程8708公里。伴随着城市轨道交通的发 展，城市轨道交通应急管理方面的研究也迅速兴起。国家政策方面，随着城市轨道交通快速发展，运营规模不断扩大，发生的突发事件的频率和突发事件的影响范围越来越大。国家层面开始高度重视城市轨道交通应急管理工作， 先后出台一系列政策规范推动应急管理的发展。2005年，国务院办公厅印发了《国家处置城市地铁事故灾难应急预案》，2007年北京市印发了《北京市轨A Review of Research on Urban Rail Transit Emergency Management Zhang Hai`Wang Chenyan Abstract： The overall development of urban rail transit in my country is rapid, but there is still a lot of room for improvement. The ability to resist disasters and risks in large emergencies such as terrorist attacks, ﬁ res, and epidemics is not strong, and the ability to respond to transportatio n risks needs to be improved. Therefore, this paper analyzes the current research status and dynamic s of urban ra...

Node ID: e9ac2319-d9e4-4e40-b289-2422542bad64
Similarity: 0.5606571700678038
Text: 国外对应急管理方面的研究比较早，并对城市轨道交通方面的研究也较多。城市轨 道交通突发事件的相关研究主要集中在恐怖袭击、脱轨、地震、火灾等众多层面，应急管理研究主要在应急管理的信息技术建设和发展、人员的能力和技能提升、多方协同配合、社会力量的参与、法制法规的建设等方面。主要有 以下特点，发达国家具有较高的科技水平，建立起了协调统一、快速响应的突发事件应急体系；应急工作中体现出综合性应急，通过提升突发事件的组织者和参与者能力、防控技术和方式，不断完善其预警和管理机制、防灾技术 标准和手段；将应急法制的建设摆在首要位置，法律体系置于基础性地位，通过完善和健全法律体系为应急管理提供保障，此来加强城市轨道交通突发事件应急管理的能力。城市轨道交通应急能力评价方面，国内外有关应急能力 的研究集中在对突发公共事件中的城市突发公共事件、城市灾害等方面相关的应急能力评估研究，美国、日本已建立了比较完善的综合应急能力评价体系，国内也有相关研究，但有关城市轨道交通应急能力评估方面研究成果相对 较少。2.3　国外经验借鉴国外城市轨道交通发展的较早，在建设方面和运营过程中积累了丰富经验和教训，尤其是应急管理方面在管理体系、信息化建设、 法律法规、 应急设施设备等方面。新加坡地铁开通于1987年 ，是世界上最安全的地铁之一，目前开设六条地铁线路的130多个地铁车站，共计200公里，每天有超过300万的乘客量。在硬件方面，地铁安装有火灾自动报警系统、自动灭火系统、自动排烟系统、应急照明系统和应急 广播系统，在地铁的安全设计方面，每节车厢都设计藏有一道移动桥，当意外发生在中途时，控制中心会迅速调来一辆车停在故障车旁边，乘客可以从靠近门口的座椅下拉出移动桥，经过移动桥安全地疏散到救援车上。新加坡地 铁每辆列车的轮轴上都装有“安全盘”。一旦轮轴上的两个胶轮发生破裂，车辆可以依靠安全盘行驶到下一个车站。每个车站和每辆车上都装有2个紧急按钮和2部通话机。

Retrieving with query id None: 我国第一条轨道交通线路在哪里运营？
Keyword arguments {'add_special_tokens': False} not recognized.
Retrieved node with id, entering: fcb8d82d-e9c4-484f-8253-393aa4c031fb
Retrieving with query id fcb8d82d-e9c4-484f-8253-393aa4c031fb: 我国第一条轨道交通线路在哪里运营？
Retrieved node with id, entering: e9ac2319-d9e4-4e40-b289-2422542bad64
Retrieving with query id e9ac2319-d9e4-4e40-b289-2422542bad64: 我国第一条轨道交通线路在哪里运营？
'我国第一条地铁在北京投入运营。\n'

**Comment by logan-markewich** [comment]
If you maybe inserted the same piece of text twice, there is a step after retrieval that is de-duplicating results. Or, with a recursive retriever here, it's possible to retrieve both a node and the index node pointing to that node, causing the de-duplicating step to remove one node
