### ISSUE TITLE
[Question]: exception when calling RetrieverQueryEngine with a FusionRetriver

### ISSUE THREAD

**Issue by Apicio** [run-llama/llama_index#11430]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

Hi there, I've a problem on a Jupyter Notebook  that is going to drive me crazy.  When calling the method query() on a query_engine instantiated with a FusionRetriver, I occasionally (but very frequent) get this exception

--------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[6], [line 10](vscode-notebook-cell:?execution_count=6&line=10)
      [1](vscode-notebook-cell:?execution_count=6&line=1) while True:

      [8](vscode-notebook-cell:?execution_count=6&line=8)     #response = query_engine.query(question)
""""""---> [10](vscode-notebook-cell:?execution_count=6&line=10)     response = query_engine_fusion.query("What are the baseline reqs for Security")"""""

(/llama_index/core/base/base_query_engine.py:40), in BaseQueryEngine.query(self, str_or_query_bundle)
     [38](/llama_index/core/base/base_query_engine.py:38) if isinstance(str_or_query_bundle, str):
     [39](/llama_index/core/base/base_query_engine.py:39)     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> [40](/llama_index/core/base/base_query_engine.py:40) return self._query(str_or_query_bundle)

File [llama_index\core\query_engine\retriever_query_engine.py:186](/llama_index/core/query_engine/retriever_query_engine.py:186), in RetrieverQueryEngine._query(self, query_bundle)
    [182]( llama_index/core/query_engine/retriever_query_engine.py:182) """Answer a query."""
    [183]( llama_index/core/query_engine/retriever_query_engine.py:183) with self.callback_manager.event(
    [184]( llama_index/core/query_engine/retriever_query_engine.py:184)     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    [185]( llama_index/core/query_engine/retriever_query_engine.py:185) ) as query_event:
--> [186]( llama_index/core/query_engine/retriever_query_engine.py:186)     nodes = self.retrieve(query_bundle)
    [187]( llama_index/core/query_engine/retriever_query_engine.py:187)     response = self._response_synthesizer.synthesize(
...
---> [47]( llama_index/core/base/embeddings/base.py:47)     product = np.dot(embedding1, embedding2)
     [48]( llama_index/core/base/embeddings/base.py:48)     norm = np.linalg.norm(embedding1) * np.linalg.norm(embedding2)
     [49]( llama_index/core/base/embeddings/base.py:49)     return product / norm

TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?378afad3-40aa-44e3-a78e-fc2570d2453a) or open in a [text editor](command:workbench.action.openLargeOutput?378afad3-40aa-44e3-a78e-fc2570d2453a). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

It looks like that it cannot calculate the cosine similarity because it cannot get the embeddings of something (I don't know if the problem is my vector store o what else...).

Here's my code:

`
vector_store_retriever = get_retriever("vector",index, SIMILARITY_TOP_K)

bm25_retriever = get_retriever("bm25",index, SIMILARITY_TOP_K)

fusion_retriever = QueryFusionRetriever(
    [vector_store_retriever, bm25_retriever],
    similarity_top_k=SIMILARITY_TOP_K,
    num_queries=3,  
    mode="reciprocal_rerank",
    use_async=True
)    

query_engine_fusion = RetrieverQueryEngine.from_args(fusion_retriever)
response = query_engine_fusion.query("What are the baseline reqs for Security?")
display_response(response)`

**Comment by logan-markewich** [comment]
Just to confirm, what is `get_retriever()` doing?

**Comment by Apicio** [comment]
HI @logan-markewich , HERE'S the code:

def get_retriever(retriever_name, index, similarity=0):
    if retriever_name.lower() == "bm25":
        bm25_retriever = BM25Retriever.from_defaults(docstore = index.docstore, similarity_top_k = similarity)
        return bm25_retriever
    elif retriever_name.lower() == "vector":
        return index.as_retriever(similarity_top_k = similarity)

**Comment by Apicio** [comment]
Do you think that, maybe, if I return a vectorretriever by calling the index this could a  problem?

**Comment by juleskuehn** [comment]
Based on where the error is happening (in an embedding similarity calculation) I don't think this has anything to do with `QueryFusionRetriever`.

Can you make a more minimal example, using only the vector retriever, and without your `get_retriever` abstraction, to pinpoint the issue?

**Comment by asti009asti** [comment]
Is BM25Retriever available in llama 0.10.15? There's a bm25_retriever in the legacy package but no BM25Retriever under llama_index.core.retrievers. Not sure if the legacy one is compatible with the new API.

**Comment by logan-markewich** [comment]
@asti009asti integrations are separated into packages.  Check out https://llamahub.ai

But in this case
`pip install llama-index llama-index-retrievers-bm25`

`from llama_index.retrievers.bm25 import BM25Retriever`
