### ISSUE TITLE
[Bug]: 0.10.13.post1 Import errors

### ISSUE THREAD

**Issue by wdeaderick** [run-llama/llama_index#11437]
### Bug Description

After updating to `0.10.13.post1`, I'm unable to run my application due to import errors. In particular, running `from llama_index.core.vector_stores.types import MetadataFilter` ultimately fails due to:
```
    from llama_index.core.settings import Settings
  File "/Users/wdeaderick/.pyenv/versions/play/lib/python3.10/site-packages/llama_index/core/settings.py", line 12, in <module>
    from llama_index.core.llms import LLM
ImportError: cannot import name 'LLM' from 'llama_index.core.llms' (unknown location)
```

### Version

0.10.13.post1

### Steps to Reproduce

Run `from llama_index.core.vector_stores.types import MetadataFilter`

**Comment by logan-markewich** [comment]
@wdeaderick Can you try with a fresh venv?

In a new terminal
```
pip uninstall llama-index  # remove any global install
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by dew-maris-hugeman** [comment]
Could u try this for interim solution.

from llama_index.legacy.vector_stores import MetadataFilter

Or follow below link at the "Pre-Requisites" section

https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77

**Comment by wdeaderick** [comment]
Thanks all, think this was a problem on my end because I first upgraded to `0.10.13` before upgrading to `0.10.13.post1`. I had to manually uninstall both `llama-index` and `llama-index-core` before upgrading to `0.10.13.post1` in order to get it to work, but all good now.
