### ISSUE TITLE
[Bug]: ValidationError: 1 validation error for DataSource

### ISSUE THREAD

**Issue by Mariam013** [run-llama/llama_index#11434]
### Bug Description

from llama_index.core import SQLDatabase
from llama_index.llms.openai import OpenAI

Error:
ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

### Version

 0.10.10

### Steps to Reproduce

by trying to run; 
from llama_index.core import SQLDatabase
from llama_index.llms.openai import OpenAI

**Comment by Mariam013** [comment]
@dosu-bot, any update?

**Comment by Mariam013** [comment]
@dosu-bot. I have not created these functions. I am using them as they are in the installed model

**Comment by Mariam013** [comment]
@dosu-bot

from llama_index.core import SQLDatabase
from llama_index.llms.openai import OpenAI . 
 
 This is the model imported from llama index and it gives this error:
 
 
 --------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 from llama_index import SQLDatabase
      2 from llama_index import OpenAI

File ~\anaconda3.2\lib\site-packages\llama_index\__init__.py:13, in <module>
     10 from typing import Callable, Optional
     12 # import global eval handler
---> 13 from llama_index.callbacks.global_handlers import set_global_handler
     15 # response
     16 from llama_index.core.response.schema import Response

File ~\anaconda3.2\lib\site-packages\llama_index\callbacks\__init__.py:7, in <module>
      5 from .open_inference_callback import OpenInferenceCallbackHandler
      6 from .schema import CBEvent, CBEventType, EventPayload
----> 7 from .token_counting import TokenCountingHandler
      8 from .utils import trace_method
      9 from .wandb_callback import WandbCallbackHandler

File ~\anaconda3.2\lib\site-packages\llama_index\callbacks\token_counting.py:6, in <module>
      4 from llama_index.callbacks.base_handler import BaseCallbackHandler
      5 from llama_index.callbacks.schema import CBEventType, EventPayload
----> 6 from llama_index.utilities.token_counting import TokenCounter
      7 from llama_index.utils import get_tokenizer
     10 @dataclass
     11 class TokenCountingEvent:

File ~\anaconda3.2\lib\site-packages\llama_index\utilities\token_counting.py:6, in <module>
      1 # Modified from:
      2 # https://github.com/nyno-ai/openai-token-counter
      4 from typing import Any, Callable, Dict, List, Optional
----> 6 from llama_index.llms import ChatMessage, MessageRole
      7 from llama_index.utils import get_tokenizer
     10 class TokenCounter:

File ~\anaconda3.2\lib\site-packages\llama_index\llms\__init__.py:1, in <module>
----> 1 from llama_index.core.llms.types import (
      2     ChatMessage,
      3     ChatResponse,
      4     ChatResponseAsyncGen,
      5     ChatResponseGen,
      6     CompletionResponse,
      7     CompletionResponseAsyncGen,
      8     CompletionResponseGen,
      9     LLMMetadata,
     10     MessageRole,
     11 )
     12 from llama_index.llms.ai21 import AI21
     13 from llama_index.llms.anthropic import Anthropic

File ~\anaconda3.2\lib\site-packages\llama_index\core\__init__.py:19, in <module>
     15 from llama_index.core.embeddings.mock_embed_model import MockEmbedding
     17 # indices
     18 # loading
---> 19 from llama_index.core.indices import (
     20     ComposableGraph,
     21     DocumentSummaryIndex,
     22     GPTDocumentSummaryIndex,
     23     GPTKeywordTableIndex,
     24     GPTListIndex,
     25     GPTRAKEKeywordTableIndex,
     26     GPTSimpleKeywordTableIndex,
     27     GPTTreeIndex,
     28     GPTVectorStoreIndex,
     29     KeywordTableIndex,
     30     KnowledgeGraphIndex,
     31     ListIndex,
     32     RAKEKeywordTableIndex,
     33     SimpleKeywordTableIndex,
     34     SummaryIndex,
     35     TreeIndex,
     36     VectorStoreIndex,
     37     load_graph_from_storage,
     38     load_index_from_storage,
     39     load_indices_from_storage,
     40 )
     42 # structured
     43 from llama_index.core.indices.common.struct_store.base import (
     44     SQLDocumentContextBuilder,
     45 )

File ~\anaconda3.2\lib\site-packages\llama_index\core\indices\__init__.py:4, in <module>
      1 """LlamaIndex data structures."""
      3 # indices
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      5 from llama_index.core.indices.document_summary import (
      6     DocumentSummaryIndex,
      7     GPTDocumentSummaryIndex,
      8 )
      9 from llama_index.core.indices.document_summary.base import DocumentSummaryIndex

File ~\anaconda3.2\lib\site-packages\llama_index\core\indices\composability\__init__.py:4, in <module>
      1 """This module contains all classes used for composing graphs over indices."""
----> 4 from llama_index.core.indices.composability.graph import ComposableGraph
      6 __all__ = ["ComposableGraph"]

File ~\anaconda3.2\lib\site-packages\llama_index\core\indices\composability\graph.py:7, in <module>
      5 from llama_index.core.base.base_query_engine import BaseQueryEngine
      6 from llama_index.core.data_structs.data_structs import IndexStruct
----> 7 from llama_index.core.indices.base import BaseIndex
      8 from llama_index.core.schema import (
      9     IndexNode,
     10     NodeRelationship,
     11     ObjectType,
     12     RelatedNodeInfo,
     13 )
     14 from llama_index.core.service_context import ServiceContext

File ~\anaconda3.2\lib\site-packages\llama_index\core\indices\base.py:12, in <module>
     10 from llama_index.core.chat_engine.types import BaseChatEngine, ChatMode
     11 from llama_index.core.data_structs.data_structs import IndexStruct
---> 12 from llama_index.core.ingestion import run_transformations
     13 from llama_index.core.llms.utils import LLMType, resolve_llm
     14 from llama_index.core.schema import BaseNode, Document, IndexNode, TransformComponent

File ~\anaconda3.2\lib\site-packages\llama_index\core\ingestion\__init__.py:2, in <module>
      1 from llama_index.core.ingestion.cache import IngestionCache
----> 2 from llama_index.core.ingestion.pipeline import (
      3     DocstoreStrategy,
      4     IngestionPipeline,
      5     arun_transformations,
      6     run_transformations,
      7 )
      9 __all__ = [
     10     "DocstoreStrategy",
     11     "IngestionCache",
   (...)
     14     "arun_transformations",
     15 ]

File ~\anaconda3.2\lib\site-packages\llama_index\core\ingestion\pipeline.py:31, in <module>
     24 from llama_index.core.constants import (
     25     DEFAULT_APP_URL,
     26     DEFAULT_BASE_URL,
     27     DEFAULT_PIPELINE_NAME,
     28     DEFAULT_PROJECT_NAME,
     29 )
     30 from llama_index.core.bridge.pydantic import BaseModel, Field
---> 31 from llama_index.core.ingestion.api_utils import get_client
     32 from llama_index.core.ingestion.cache import DEFAULT_CACHE_NAME, IngestionCache
     33 from llama_index.core.ingestion.data_sources import (
     34     ConfigurableDataSources,
     35 )

File ~\anaconda3.2\lib\site-packages\llama_index\core\ingestion\api_utils.py:20, in <module>
     13 from llama_index_client.client import AsyncPlatformApi, PlatformApi
     15 from llama_index.core.constants import (
     16     DEFAULT_APP_URL,
     17     DEFAULT_BASE_URL,
     18     DEFAULT_PROJECT_NAME,
     19 )
---> 20 from llama_index.core.ingestion.data_sources import (
     21     ConfiguredDataSource,
     22 )
     23 from llama_index.core.ingestion.transformations import (
     24     ConfiguredTransformation,
     25 )
     26 from llama_index.core.node_parser import SentenceSplitter

File ~\anaconda3.2\lib\site-packages\llama_index\core\ingestion\data_sources.py:340, in <module>
    327     enum_members.append(
    328         (
    329             "DOCUMENT",
   (...)
    334         )
    335     )
    337     return ConfigurableComponent("ConfigurableDataSources", enum_members)
--> 340 ConfigurableDataSources = build_conifurable_data_source_enum()
    342 T = TypeVar("T", bound=BaseComponent)
    345 class ConfiguredDataSource(GenericModel, Generic[T]):

File ~\anaconda3.2\lib\site-packages\llama_index\core\ingestion\data_sources.py:117, in build_conifurable_data_source_enum()
    109 try:
    110     from llama_index.readers.elasticsearch import (
    111         ElasticsearchReader,
    112     )  # pants: no-infer-dep
    114     enum_members.append(
    115         (
    116             "ELASTICSEARCH",
--> 117             DataSource(
    118                 name="Elasticsearch",
    119                 component_type=ElasticsearchReader,
    120             ),
    121         )
    122     )
    123 except ImportError:
    124     pass

File ~\anaconda3.2\lib\site-packages\pydantic\main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for DataSource
component_type
  subclass of BaseComponent expected (type=type_error.subclass; expected_class=BaseComponent)

**Comment by logan-markewich** [comment]
@Mariam013 this works in a fresh google colab instance.

I would suggest creating a new venv

In a new terminal
```
pip uninstall llama-index  # remove any global install
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by dew-maris-hugeman** [comment]
> SQLDatabase

Could u try this for interim solution.

`
from llama_index.legacy import SQLDatabase
`

**Comment by Mariam013** [comment]
Thank you @logan-markewich . I created a new environment and it works now
