### ISSUE TITLE
[Bug]: Gemini is not supported in agentic components

### ISSUE THREAD

**Issue by bottlehounds-dev** [run-llama/llama_index#11439]
### Bug Description

Hey all!

I'm sure that you're aware of this, but using a `gemini` LLM in a query engine, chat engine, or agent isn't possible out of the box.

### Issues
There are two main issues (that I am aware of):
1. `gemini` does not support messages with the `SYSTEM` role, but these are always used by default by `lammaindex` in:
    1. The [TEXT_QA_SYSTEM_PROMPT](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/prompts/chat_prompts.py#L7-L19) for response synthesizers
    2. When using a `ReActAgent`, the default chat formatter prepends the history with the agent instructions as a `SYSTEM` message in [ReActChatFormatter.format](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/agent/react/formatter.py#L93-L97)
2. An error is thrown in [vertex_utils._parse_chat_history](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py#L195-L196) when the chat history is not an even number of messages, this is guaranteed to happen when:
    1. Using the default QA prompts for response synthesizers, as they are composed of two messages
    2. The aforementioned [ReActChatFormatter.format](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/agent/react/formatter.py#L93-L97) method will prepend the history with another message containing agent instructions

### Workarounds
1. For the response synthesizer issues, we can simply override `text_qa_template` to only contain a single `USER`, taking care of both the `SYSTEM` message and the odd number of messages in the chat history.
2. For the agent, we can **only** solve the `SYSTEM` message issue (I did this by subclassing `ReActChatFormatter` and updating the message role from `SYSTEM` to `USER`

### Blocker
Finally we have come to the issue that I do not have a workaround for, outside of reimplementing the `Vertex` LLM and/or how it is used with agents.

**I do not know how to avoid the uneven number of chat history messages when using `gemini` with a `ReAct` agent.** The agent will always need to give its instructions/context. Should I simply attempt to combine this with the user message?

### Version

latest

### Response Synthesizer
1. Create a query engine with a response synthesizer that uses the `gemini` LLM and run a query on it

### Agent
1. Create a ReAct agent with the `gemini` LLM and run a chat on it

**Comment by logan-markewich** [comment]
probably
- system messages get converted into user messages
- uneven messages get merged to create an even number of messages

**Comment by gich2009** [comment]
Hi @bottlehounds-dev? I've been using query engines, chat engines and react agents with gemini models, both pro and ultra and they have been working fine. There was a time they weren't working because of problems with the system message: user message mapping but I raised a similar issue and it was fixed.

What modules are not working on your end?

**Comment by gich2009** [comment]
Hi @bottlehounds-dev, no worries. 

That explains it. I usually use the Gemini abstraction directly. I've never tried running it behind the vertex abstraction. Seems to be a Vertex-Gemini issue. I'll experiment later. It was probably an oversight when the gemini abstraction was fixed.

The gemini one works pretty well. Try it out and tell me if you encounter challenges because I'd be curious to see what they are.

**Comment by shuozhu1** [comment]
> ### Bug Description
> Hey all!
> 
> I'm sure that you're aware of this, but using a `gemini` LLM in a query engine, chat engine, or agent isn't possible out of the box.
> 
> ### Issues
> There are two main issues (that I am aware of):
> 
> 1. `gemini` does not support messages with the `SYSTEM` role, but these are always used by default by `lammaindex` in:
>    
>    1. The [TEXT_QA_SYSTEM_PROMPT](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/prompts/chat_prompts.py#L7-L19) for response synthesizers
>    2. When using a `ReActAgent`, the default chat formatter prepends the history with the agent instructions as a `SYSTEM` message in [ReActChatFormatter.format](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/agent/react/formatter.py#L93-L97)
> 2. An error is thrown in [vertex_utils._parse_chat_history](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/utils.py#L195-L196) when the chat history is not an even number of messages, this is guaranteed to happen when:
>    
>    1. Using the default QA prompts for response synthesizers, as they are composed of two messages
>    2. The aforementioned [ReActChatFormatter.format](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/agent/react/formatter.py#L93-L97) method will prepend the history with another message containing agent instructions
> 
> ### Workarounds
> 1. For the response synthesizer issues, we can simply override `text_qa_template` to only contain a single `USER`, taking care of both the `SYSTEM` message and the odd number of messages in the chat history.
> 2. For the agent, we can **only** solve the `SYSTEM` message issue (I did this by subclassing `ReActChatFormatter` and updating the message role from `SYSTEM` to `USER`
> 
> ### Blocker
> Finally we have come to the issue that I do not have a workaround for, outside of reimplementing the `Vertex` LLM and/or how it is used with agents.
> 
> **I do not know how to avoid the uneven number of chat history messages when using `gemini` with a `ReAct` agent.** The agent will always need to give its instructions/context. Should I simply attempt to combine this with the user message?
> 
> ### Version
> latest
> 
> ### Steps to Reproduce
> ### Response Synthesizer
> 1. Create a query engine with a response synthesizer that uses the `gemini` LLM and run a query on it
> 
> ### Agent
> 1. Create a ReAct agent with the `gemini` LLM and run a chat on it
> 
> ### Relevant Logs/Tracbacks
> _No response_

Hello，I seem to have the same problem as you, but I don't have a suitable solution yet. Could I take a look at your code for this section? Much appreciated！！！！

**Comment by logan-markewich** [comment]
@shuozhu1 I think this is fixed tbh

`pip install llama-index-llms-vertex` should have it working

**Comment by shuozhu1** [comment]
> @shuozhu1 I think this is fixed tbh
> 
> `pip install -U llama-index-llms-vertex` should have it working

i will try. thanks for your help!!!

**Comment by d-mariano** [comment]
@shuozhu1 @logan-markewich sorry friends, I meant to close this one out! <3
