### ISSUE TITLE
[Bug]: SimpleDirectoryReader() doesn't parse superscripts in pdfs causing errors in numbers that end with superscript footnote references

### ISSUE THREAD

**Issue by tgbmo** [run-llama/llama_index#11449]
### Bug Description

 SimpleDirectoryReader() yields incorrect numbers that end with a reference to a footnote (like **$320**<sup>1</sup> in the pdf turning into **$3201** in the text). 

### Version

0.9.30

### Steps to Reproduce

from llama_index import SimpleDirectoryReader as SDR

# pdf file should contain text with superscripts
documents = SDR(input_dir="path_to_dir_containing_pdfs").load_data()
print(documents)

**Comment by tgbmo** [comment]
@dosu-bot is it possible to pass a custom text parser function to SimpleDirectoryReader() that preprocesses the text? I have a superscript detection and retention function that would address this issue.

**Comment by tguptaMT** [comment]
@nerdai - This is the question I asked in the vector meeting today.

**Comment by nerdai** [comment]
> @nerdai - This is the question I asked in the vector meeting today.

Thanks @tguptaMT for flagging me on this. Will take a look this afternoon into it. Get back to you soon.

**Comment by nerdai** [comment]
> @dosu-bot is it possible to pass a custom text parser function to SimpleDirectoryReader() that preprocesses the text? I have a superscript detection and retention function that would address this issue.

Looks like the parser we're using, PdfReader, doesn't do the job here out of the box. My next recommendation would be to try implementing something yourself to get this done. As a stop gap, you can load in the raw data as you need it, apply your preprocess step and then load them into a `Document` manually -- I shared some pseudocode below.

```python
from llama_index.core.schema import Document

pdf_text = load_pdf()
preprocessed_text = preprocessor(pdf_text)
document = Document(text=preprocessed_text))

# you can also save the preprocessed text so then you can read this using SimpleDirectoryReader
```

**Comment by nerdai** [comment]
Going to close this issue for now @tguptaMT, but please feel free to re-open should you need more assistance.
