### ISSUE TITLE
[Bug]: Not able to install LLaMa Index on SageMaker Notebook in AWS

### ISSUE THREAD

**Issue by udaysai50** [run-llama/llama_index#11448]
### Bug Description

I am trying to install llama-index and facing the following error

```
ERROR: Cannot install llama-index-cli because these package versions have conflicting dependencies.

The conflict is caused by:
    llama-index-vector-stores-chroma 0.1.4 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.3 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.2 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.1 depends on onnxruntime<2.0.0 and >=1.17.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
```

Up on trying to reinstall onnxruntime using `!pip3 install onnxruntime>=1.17.0` I am getting following error

```
ERROR: Could not find a version that satisfies the requirement onnxruntime (from versions: none)
ERROR: No matching distribution found for onnxruntime
```

### Version

0.10.13

### Steps to Reproduce

!pip3 install llama-index

**Comment by logan-markewich** [comment]
What version of python do you have?

**Comment by udaysai50** [comment]
> What version of python do you have?

I am using conda_python3 kernal for my sagemaker notebook

**Comment by logan-markewich** [comment]
That's a tad non-deacript ha 

I'm guessing something about your python version (3.8, 3.9, 3.10?) is limiting the versions of onnx you can install?

I'll try to repro and soon if the versions can be loosened.

But also, llama-index is now separated into many packages. You can for example only install what you need

`pip install llama-index-core llama-index-llms-ollama llama-index-embeddings-huggingface`

**Comment by udaysai50** [comment]
> That's a tad non-deacript ha
> 
> I'm guessing something about your python version (3.8, 3.9, 3.10?) is limiting the versions of onnx you can install?
> 
> I'll try to repro and soon if the versions can be loosened.
> 
> But also, llama-index is now separated into many packages. You can for example only install what you need
> 
> For example, installing for ollama LLM and huggingface embeddings `pip install llama-index-core llama-index-llms-ollama llama-index-embeddings-huggingface`

I am using python version of 3.8

**Comment by logan-markewich** [comment]
Ah that explains it. Pytnon3.8 is quite old these days, and limits a lot of the things you can install

**Comment by udaysai50** [comment]
> Ah that explains it. Pytnon3.8 is quite old these days, and limits a lot of the things you can install

I just tried it on Python 3.10 and 3.12 and I am getting same error.

**Comment by wdhorton** [comment]
I've gotten this on Python 3.10 and 3.12, on an M1 mac (if that is relevant)

**Comment by aqzwy** [comment]
cat /etc/os-release  to see system version； and install the right  version of glibc 2.27 ,u can see it in https://pypi.org/project/onnxruntime/1.17.0/#files

**Comment by ramene** [comment]
Thanks @logan-markewich 

Working in `conda` with both `python=3.10` and `python=3.11`,  RAG ON.
```
conda create -n llama-index python=3.10 -y
conda activate llama-index
```

```
pip install llama-index-core mistralai llama-index-embeddings-mistralai
```

```
Installing collected packages: pytz, dirtyjson, wrapt, urllib3, tzdata, typing-extensions, tqdm, tenacity, sniffio, six, regex, PyYAML, pypdf, pillow, packaging, orjson, numpy, networkx, nest-asyncio, mypy-extensions, multidict, joblib, idna, h11, greenlet, fsspec, frozenlist, exceptiongroup, distro, click, charset-normalizer, certifi, attrs, async-timeout, annotated-types, yarl, typing-inspect, SQLAlchemy, requests, python-dateutil, pydantic-core, nltk, marshmallow, httpcore, deprecated, anyio, aiosignal, tiktoken, pydantic, pandas, httpx, dataclasses-json, aiohttp, openai, mistralai, llamaindex-py-client, llama-index-core, llama-index-embeddings-mistralai
Successfully installed PyYAML-6.0.1 SQLAlchemy-2.0.28 aiohttp-3.9.3 aiosignal-1.3.1 annotated-types-0.6.0 anyio-4.3.0 async-timeout-4.0.3 attrs-23.2.0 certifi-2024.2.2 charset-normalizer-3.3.2 click-8.1.7 dataclasses-json-0.6.4 deprecated-1.2.14 dirtyjson-1.0.8 distro-1.9.0 exceptiongroup-1.2.0 frozenlist-1.4.1 fsspec-2024.2.0 greenlet-3.0.3 h11-0.14.0 httpcore-1.0.4 httpx-0.25.2 idna-3.6 joblib-1.3.2 llama-index-core-0.10.17 llama-index-embeddings-mistralai-0.1.3 llamaindex-py-client-0.1.13 marshmallow-3.21.1 mistralai-0.0.11 multidict-6.0.5 mypy-extensions-1.0.0 nest-asyncio-1.6.0 networkx-3.2.1 nltk-3.8.1 numpy-1.26.4 openai-1.13.3 orjson-3.9.15 packaging-23.2 pandas-2.2.1 pillow-10.2.0 pydantic-2.6.3 pydantic-core-2.16.3 pypdf-4.1.0 python-dateutil-2.9.0.post0 pytz-2024.1 regex-2023.12.25 requests-2.31.0 six-1.16.0 sniffio-1.3.1 tenacity-8.2.3 tiktoken-0.6.0 tqdm-4.66.2 typing-extensions-4.10.0 typing-inspect-0.9.0 tzdata-2024.1 urllib3-2.2.1 wrapt-1.16.0 yarl-1.9.4
```
