### ISSUE TITLE
[Question]: ValueError: llm must start with str 'local' or of type LLM or BaseLanguageModel

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#11445]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

llm = Gemini(api_key=api_key, models ='gemini-pro')
embedModel = GeminiEmbedding(model_name="models/embedding-001")
Settings.llm = llm
Settings.embed_model = embedModel
Settings.chunk_size = 2048
Settings.chunk_overlap = 512
chromaClient = chromadb.PersistentClient()
chromaCollection = chromaClient.get_or_create_collection("rythfb")
vectorStore = ChromaVectorStore(chroma_collection = chromaCollection)

storageContext = StorageContext.from_defaults(vector_store = vectorStore)

index = VectorStoreIndex.from_documents(
    data,
    use_async = True,
    storage_context = storageContext
)

response = index.as_query_engine("Your Query")
ValueError: llm must start with str 'local' or of type LLM or BaseLanguageModel
How to get over this error

**Comment by logan-markewich** [comment]
Where did you import Gemini from?

This feels like either it was from langchain, or you are mixing in legacy imports with non-legacy imports

**Comment by Prem-Nitin** [comment]
> Where did you import Gemini from?
> 
> This feels like either it was from langchain, or you are mixing in legacy imports with non-legacy imports

These are my imports
from llama_index.core import StorageContext, SimpleDirectoryReader, Settings, VectorStoreIndex
from llama_index.embeddings.gemini import GeminiEmbedding
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.llms.gemini import Gemini
from llama_index.multi_modal_llms.gemini import GeminiMultiModal
from llama_index.vector_stores.chroma import ChromaVectorStore
