### ISSUE TITLE
[Bug]: module 'llama_index' has no attribute '__version__'

### ISSUE THREAD

**Issue by Kirushikesh** [run-llama/llama_index#11459]
### Bug Description

I recently upgraded my llama-index package. Now when i try to check the version of the library i am getting the error. How ever i can able to use pip freeze to check the llama_index version indirectly. I don't guess this is the expected behaviour.

### Version

0.10.13.post1

### Steps to Reproduce

import llama_index

llama_index.__version__

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [6], in <cell line: 3>()
      1 import llama_index
----> 3 llama_index.__version__

AttributeError: module 'llama_index' has no attribute '__version__'
```

**Comment by logan-markewich** [comment]
`llama_index.core.__version__`
