### ISSUE TITLE
Azure OpenAI Questions

### ISSUE THREAD

**Issue by gmdl007** [run-llama/llama_index#11451]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i am keep getting this using Azure OpenAI, it is a internal one of cause:

File ~/miniforge3/envs/new2/lib/python3.11/site-packages/openai/_base_client.py:980, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    977         err.response.read()
    979     log.debug("Re-raising status error")
--> 980     raise self._make_status_error_from_response(err.response) from None
    982 return self._process_response(
    983     cast_to=cast_to,
    984     options=options,
   (...)
    987     stream_cls=stream_cls,
    988 )

UnprocessableEntityError: Error code: 422 - {'detail': [{'loc': ['body', 'user'], 'msg': 'field required', 'type': 'value_error.missing'}]}

What can this be?

Many Thanks

**Comment by gmdl007** [comment]
my llm code is simple:

from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding

# For Azure OpenAI
api_key = xyz.json()["access_token"]
azure_endpoint = "https://chat-ai.xyz.com/"
api_version = "2023-08-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="gpt-4",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

**Comment by gmdl007** [comment]
if i use :

index = VectorStoreIndex.from_documents(documents)

it works just fine...

but not for KG:

# NOTE: can take a while!
index = KnowledgeGraphIndex.from_documents(
    documents,
    max_triplets_per_chunk=10,
    storage_context=storage_context,
    include_embeddings=True,
    show_progress=True
)

**Comment by logan-markewich** [comment]
Seems like somehow, it is calling `llm.chat()` with an empty list of messages?

**Comment by logan-markewich** [comment]
If you had the full traceback, it would be helpful
