### ISSUE TITLE
[Question]: List of OpenAI models for older llama_index versions

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#11452]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi , 

Looks like llama_index manages it's own list of available OpenAI models .
It can change . How can I update the list without updating llama_index package's version ?

Here the code I am trying to run :

```
from llama_index.llms.openai import OpenAI
llm = OpenAI(model = "gpt-4-turbo-preview", temperature = 0.0, max_tokens = 256)
response = llm.complete(prompt)
```
The error : 

`ValueError: Unknown model 'gpt-4-turbo-preview'. Please provide a valid OpenAI model name in: gpt-4 ....`

Thanks,
Nissim

**Comment by logan-markewich** [comment]
you cant really update the list without updating the llama-index version. You'd have to subclass the openai class itself I think
