### ISSUE TITLE
[Question]: index.as_retrieve returns None, causing an error

### ISSUE THREAD

**Issue by Plusholic** [run-llama/llama_index#11455]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I have a question about retriever.
I define the index through a ChromaVectorStore.

```
    index = VectorStoreIndex.from_vector_store(
        vector_store,
        storage_context=storage_context,
        # service_context=service_context,
    )
```

However, when searching in index.as_retriever(), the following error occurs

ValidationError: 1 validation error for TextNode
text
  none is not an allowed value (type=type_error.none.not_allowed)

In the query part of the source code of the ChromaVectorStore below, when I checked the part where I get the error
a08a1d02-7fcf-4bf0-b533-6d531fe34190 None None 0.33591151237487793
and it looks like this

```
        for node_id, text, metadata, distance in zip(
            results["ids"][0],
            results["documents"][0],
            results["metadatas"][0],
            results["distances"][0],
        ):
```

If the id is found in the docstore, the content of the TextNode exists.
```
docstore = SimpleDocumentStore.from_persist_dir("Mypath")
documents = docstore.docs
documents['a08a1d02-7fcf-4bf0-b533-6d531fe34190']
```

I have no idea where the problem is, I'm using llamaindex version 0.9.12.
Thank you

**Comment by logan-markewich** [comment]
Did you create the vector store with llama-index? If not, then support is a little shakey

**Comment by Plusholic** [comment]
> Did you create the vector store with llama-index? If not, then support is a little shakey

I created a vector store as follows, I used llamaindex and chroma db.

```
    import chromadb
    from llama_index.vector_stores import ChromaVectorStore
    # make chroma vectorstore
    # chroma_clint = chromadb.EphemeralClient()
    db = chromadb.PersistentClient(path=f'./Papers/chroma/{collection_name}_{embed_size}')
    chroma_collection =db.get_or_create_collection(f"{collection_name}_{embed_size}")

    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    storage_context = StorageContext.from_defaults(persist_dir=f'./Papers/chroma/{collection_name}_{embed_size}')

    index = VectorStoreIndex.from_vector_store(
        vector_store,
        storage_context=storage_context,
    )
    
    return index, storage_context
```

**Comment by logan-markewich** [comment]
But did llama-index populate the vector store? LlamaIndex expects a few key fields to be present (for instance, it seems like the text missing)

This makes me think llama-index did not create + populate this vector store

**Comment by Plusholic** [comment]
> But did llama-index populate the vector store? LlamaIndex expects a few key fields to be present (for instance, it seems like the text missing)
> 
> This makes me think llama-index did not create + populate this vector store

I don't know if I understood what you said perfectly.
I think you're asking if the vector store is made of node objects in llamaindex.

Here is part of the code that created the vector store and docstore.
I fetched the Documents via llamaindex's SimpleDirectoryReader, and used HierarchicalNodeParser to parse the nodes from the Documents.

```
node_parser_h = HierarchicalNodeParser.from_defaults(
    chunk_sizes=[
        512,
        256,
        128
    ]
)
node_h = node_parser_h.get_nodes_from_documents(final_doc_list)
leaf_nodes = get_leaf_nodes(node_h)
```

```
    db = chromadb.PersistentClient(path=f'./Papers/chroma/{collection_name}_{embed_size}')
    chroma_collection =db.get_or_create_collection(f"{collection_name}_{embed_size}")
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

    docstore = SimpleDocumentStore()
    docstore.add_documents(nodes)

    storage_context = StorageContext.from_defaults(docstore=docstore,
                                                vector_store=vector_store
                                                )
 index = VectorStoreIndex(nodes=leaf_nodes, storage_context=storage_context)
```

모든 과정을 llamaindex를 통해서 진행했습니다.
