### ISSUE TITLE
[Question]: Composability Of Nodes Using MultiModalVectorStoreIndex Class

### ISSUE THREAD

**Issue by Deepansharora27** [run-llama/llama_index#11460]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I was taking a look at one of this Existing Issues on the LlamaIndex Repository 
https://github.com/run-llama/llama_index/issues/8923

Here Dosubot Suggests that we can have a List Of Nodes and then pass this List to the MultiModalVectorStoreIndex Class and thus this will give us the Combined Index with Both Of these Nodes. 

I am Trying Out this Approach with the Following Code Snippet 

    `node1 = Settings.node_parser.get_nodes_from_documents(documents=document1)
    node2 = Settings.node_parser.get_nodes_from_documents(documents=document2)

    nodes_list = [node1,node2]
    index = MultiModalVectorStoreIndex(nodes=nodes_list)
    index._add_nodes_to_index(index.index_struct,nodes_list)
    index.as_query_engine("What is the Difference Between Both Of the Provided Documents ?")`
    
    With this Code Snippet I am getting the Following Error: 
    ValueError: nodes must be a list of Node objects.
    
    
Anything that I am missing Over Here ? Also Please Correct me but Here Nodes means the Nodes that returned to us by the Node_parser ? 
  
Also Please Suggest a Approach where I could compose Indexes Using VectorStoreIndex Itself in case I do not want to Reply on GPTListIndex for Composability as Mentioned in the Documentation ?

**Comment by Deepansharora27** [comment]
@dosu-bot According to your Response, If Node Object is Equivalent to the BaseNode Class then why can't we directly use 
what I have mentioned earlier in the Code Snippet ?

**Comment by logan-markewich** [comment]
I would take dosu with a grain of salt here

`get_nodes_from_documents` returns a list of nodes. But you combined two outputs `node1` and `node2` such that you had a list of list of nodes

Probably you are meaning to do something like this?
```
nodes1 = Settings.node_parser.get_nodes_from_documents(documents=document1)
nodes2 = Settings.node_parser.get_nodes_from_documents(documents=document2)

index = MultiModalVectorStoreIndex(nodes=nodes1+nodes2)
```

**Comment by Deepansharora27** [comment]
@logan-markewich Exactly I did not follow it's approach and did exactly similar thing to what you are doing in the Code Snippet Provided. I am Facing Issue in the Following Part: 

<img width="1063" alt="Screenshot 2024-02-28 at 12 11 52 PM" src="https://github.com/run-llama/llama_index/assets/43300955/ce61d079-413d-4152-9c67-559cf194ccb3">

With this, I get the Following Error 
`assert isinstance(llm, MultiModalLLM)
AssertionError`

**Comment by Deepansharora27** [comment]
@logan-markewich Exactly I did not follow it's approach and did exactly similar thing to what you are doing in the Code Snippet Provided. I am Facing Issue in the Following Part:

<img width="1074" alt="Screenshot 2024-02-28 at 9 13 37 PM" src="https://github.com/run-llama/llama_index/assets/43300955/de432b32-36d0-4d81-842e-12386538abe0">


With this, I get the Following Error 
` assert isinstance(llm, MultiModalLLM)
AssertionError`

**Comment by logan-markewich** [comment]
Are you mixing legacy imports with non-legacy imports?

Really the only way to combine indexes is to retrieve from them all and combine results. This is what the QueryFusionRetriever does

**Comment by Deepansharora27** [comment]
@logan-markewich Sorry what do you mean exactly by mixing legacy imports with non-legacy imports ?

**Comment by Deepansharora27** [comment]
I realised I was Making a Mistake while Querying so have fixed that as well 
<img width="1014" alt="Screenshot 2024-02-29 at 12 55 17 PM" src="https://github.com/run-llama/llama_index/assets/43300955/6c944ed9-811e-4c3a-80e8-6b56ec3c47b9">

**Comment by Deepansharora27** [comment]
@logan-markewich 
Correct me If I am Wrong But I am Using Llama-2-7b-Chat Model and LLamaCPP in order to load the Model and it's parameters. Can this be the case where it is giving an assertion Error that the llm object is being not supported as an Instance of the MultiModal Class ?

**Comment by logan-markewich** [comment]
That is definitely the case -- llama2 and the llamacpp class is not a multimodal llm
