### ISSUE TITLE
[Question]: TypeError: Object of type VectorIndexRetriever is not JSON serializable in Structured Hierarchical Retrieval

### ISSUE THREAD

**Issue by malee1382** [run-llama/llama_index#11478]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been playing around llama-index and try to learn rag implementations using it. The structured hierarchical retrieval is exactly what I need and I followed the code in https://docs.llamaindex.ai/en/stable/examples/query_engine/multi_doc_auto_retrieval/multi_doc_auto_retrieval.html.

In the Load Summarized Metadata section, when I ran 

```
# Since "index_nodes" are concise summaries, we can directly feed them as objects into VectorStoreIndex
index = VectorStoreIndex(
    objects=index_nodes, storage_context=storage_context_auto
```
) I get the following error:

```
TypeError: Object of type VectorIndexRetriever is not JSON serializable

During handling of the above exception, another exception occurred:

...

ValueError: IndexNode obj is not serializable: <llama_index.core.indices.vector_store.retrievers.retriever.VectorIndexRetriever object at 0x000001C0A45C7B50>
```

From my searches I could not find anything helpful answer. How can I tackle this issue?

**Comment by logan-markewich** [comment]
@malee1382 retrievers are not serializable. Instead, there is a slightly different interface to follow

`VectorStoreIndex(nodes=nodes, objects=objects)`

https://docs.llamaindex.ai/en/stable/examples/retrievers/composable_retrievers.html#composable-objects

**Comment by shawnmittal** [comment]
I don't believe this issue should be closed. I'm running into the same error following the tutorial. The problem is that the way the tutorial is laid out, you're passing a retriever object as part of the IndexNode object.

This means you cannot directly construct the VectorStoreIndex from the list of IndexNodes, even though the tutorial explicitly tells you to do as such.

**Comment by shawnmittal** [comment]
I will add that I do not have a firm grasp on how VectorStoreIndex creates the index using the TextNode objects, so if this doesn't actually blow up the index size and the above code is a sufficient fix, then feel free to use the fix.

**Comment by logan-markewich** [comment]
@shawnmittal it should be working fine in the latest version of `llama-index-core`

`pip install -U llama-index-core`

If not, please provide the code that is not working.

**Comment by shawnmittal** [comment]
If you see below, the IndexNode object is passed a retriever object as the "obj". 

```
async def aprocess_doc(doc, include_summary: bool = True):
    """Process doc."""
    metadata = doc.metadata

    date_tokens = metadata["created_at"].split("T")[0].split("-")
    year = int(date_tokens[0])
    month = int(date_tokens[1])
    day = int(date_tokens[2])

    assignee = (
        "" if "assignee" not in doc.metadata else doc.metadata["assignee"]
    )
    size = ""
    if len(doc.metadata["labels"]) > 0:
        size_arr = [l for l in doc.metadata["labels"] if "size:" in l]
        size = size_arr[0].split(":")[1] if len(size_arr) > 0 else ""
    new_metadata = {
        "state": metadata["state"],
        "year": year,
        "month": month,
        "day": day,
        "assignee": assignee,
        "size": size,
    }

    # now extract out summary
    summary_index = SummaryIndex.from_documents([doc])
    query_str = "Give a one-sentence concise summary of this issue."
    query_engine = summary_index.as_query_engine(
        llm=OpenAI(model="gpt-3.5-turbo")
    )
    summary_txt = await query_engine.aquery(query_str)
    summary_txt = str(summary_txt)

    index_id = doc.metadata["index_id"]
    # filter for the specific doc id
    filters = MetadataFilters(
        filters=[
            MetadataFilter(
                key="index_id", operator=FilterOperator.EQ, value=int(index_id)
            ),
        ]
    )

    # create an index node using the summary text
    index_node = IndexNode(
        text=summary_txt,
        metadata=new_metadata,
        obj=doc_index.as_retriever(filters=filters),
        index_id=doc.id_,
    )

    return index_node


async def aprocess_docs(docs):
    """Process metadata on docs."""

    index_nodes = []
    tasks = []
    for doc in docs:
        task = aprocess_doc(doc)
        tasks.append(task)

    index_nodes = await run_jobs(tasks, show_progress=True, workers=3)

    return index_nodes

index_nodes = await aprocess_docs(docs)

class_name = "LlamaIndex_auto"

vector_store_auto = WeaviateVectorStore(
    weaviate_client=client, index_name=class_name
)
storage_context_auto = StorageContext.from_defaults(
    vector_store=vector_store_auto
)

# Since "index_nodes" are concise summaries, we can directly feed them as objects into VectorStoreIndex
index = VectorStoreIndex(
    objects=index_nodes, storage_context=storage_context_auto
)
```

**Comment by shawnmittal** [comment]
@logan-markewich good callout. Rookie mistake on my end. I was running an outdated version of llama-index-core. Thanks!

**Comment by gartija** [comment]
I'm afraid I'm having the same issue even after upgrading to the latest version of llama-index-core (0.10.16.post1). I'm doing a similar implementation of the Structured Hierarchical Retrieval mentioned here and I get the following error when trying to persist the index: 
`ValueError: IndexNode obj is not serializable: <llama_index.core.indices.vector_store.retrievers.retriever.VectorIndexRetriever object at 0x2af09ecd0>`.
@shawnmittal did the update work for you?

**Comment by gartija** [comment]
hi @logan-markewich it's working now, thanks!
