### ISSUE TITLE
[Question]: duplicated data in index store

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#11471]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When using ElasticsearchStore as the storage for the vector index in my app, I encountered a situation where multiple identical index data of documents is created during multiple app rebooting.
Is that no incremental updating？Like upsert？

**Comment by logan-markewich** [comment]
By default, there is no upsert.

To upsert, you need some layer on top to track which documents have been inserted, and which nodes belong to which parent document.

This is usually tracked by the docstore. This also means its one more piece of storage to take care of.

I would use an ingestion pipeline for this

```python
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.storage.docstore.redis import RedisDocumentStore
from llama_index.storage.docstore.mongodb import MongoDocumentStore
from llama_index.core.node_parser import SentenceSplitter

docstore = SimpleDocumentStore()

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5"),
    ],
    docstore=docstore,
    vector_store=vector_store
)

pipeline.run(documents=documents)

index = VectorStoreIndex.from_vector_store(vector_store)

# save docstore to disk if using SimpleDocstore
docstore.persist("docstore.json")

# load
docstore = SimpleDocumentStore.from_persist_path("docstore.json")
```
