### ISSUE TITLE
[Bug]: Pinecone Upsert infinite loop

### ISSUE THREAD

**Issue by benlabbeus** [run-llama/llama_index#11479]
### Bug Description

When persisting to Pinecone, all of the vectors will be upserted, then the process starts over infinitely. 
The execution never passes this line:
`index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)`

### Version

0.10.13.post1

### Steps to Reproduce

This seems to occur with the following code. When using a SimpleDirectoryReader the issue doesn't occur.

`import os 
from llama_index.core import VectorStoreIndex, StorageContext, SimpleDirectoryReader, load_index_from_storage
from llama_index.readers.database import DatabaseReader
from llama_index.vector_stores.pinecone import PineconeVectorStore
from pinecone import Pinecone, ServerlessSpec
from dotenv import load_dotenv

def execute():
    load_dotenv()
    
    # Index
    PERSIST_DIR = './storage'
    index_name = 'llama-index-learning6'
    pc = Pinecone(api_key=os.getenv('PINECONE_API_KEY'))
    if not os.path.exists(PERSIST_DIR):
        # Load initial data
        print("Connecting to the database...")
        reader = DatabaseReader(
            scheme='postgresql',
            host='localhost',
            port='6005',
            user='pgadmin',
            password='pgpass!',
            dbname='ACME'
        )
        query = "SELECT * FROM \"Account\" AS A INNER JOIN \"MonthlyStats\" AS MS ON A.\"AccountId\" = MS.\"AccountId\""
        print("Load data...")
        documents = reader.load_data(query)
        print("Persisting...")
        pc_index = pc.create_index(
            name=index_name,
            dimension=1536,
            metric='cosine',
            spec=ServerlessSpec(cloud='aws', region='us-west-2')
        ) 
        print("Storing vector store...")
        pc_vector_store = PineconeVectorStore(pinecone_index=pc_index, index_name=index_name)
        print("Storing storage context...")
        storage_context = StorageContext.from_defaults(vector_store=pc_vector_store)
        print("Storing index...")
        os.mkdir(PERSIST_DIR)
        index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)
    else:
        print("Connecting to Pinecone...")
        pc_index = pc.Index(index_name=index_name,host='https://llama-index-learning6-y5whppu.svc.apw5-4e34-81fa.pinecone.io')
        print("Loading vector store...")
        pc_vector_store = PineconeVectorStore(pinecone_index=pc_index, index_name=index_name)
        print("Loading storage context...")
        storage_context = StorageContext.from_defaults(vector_store=pc_vector_store)
        print("Loading index...")
        index = VectorStoreIndex.from_vector_store(storage_context=storage_context, vector_store=pc_vector_store)
        
    # Query
    print("Querying...")
    query_engine = index.as_query_engine()
    prompt = "What was  Eco Aviation Inc.'s revenue in December 2015?"
    response = query_engine.query(prompt)
    print(response)

if __name__ == '__main__':
    execute()`

I'm using a very simple data structure:
`create table "Account"
(
    "AccountId" uuid not null
        constraint "PK_Account"
            primary key,
    "Name"      text not null
);

create table "MonthlyStats"
(
    "MonthlyStatsId" uuid    not null
        constraint "PK_MonthlyStats"
            primary key,
    "AccountId"      uuid    not null
        constraint "FK_MonthlyStats_Account_AccountId"
            references "Account"
            on delete cascade,
    "Year"           integer not null,
    "Month"          integer not null,
    "Revenue"        real    not null,
    "Expenses"       real    not null,
    "Profit"         real    not null
);
`

**Comment by logan-markewich** [comment]
I don't really see how this can loop. Looking at the source code, there's a single upsert call and then it returns.

Are you sure it's not just a ton of data? By default, the index batches data inserts into batches of 2048 (to avoid memory and API issues)

If you call `print(len(documents))` or even calculate the number of nodes, I suspect it will be a lot

```
from llama_index.core import Settings

nodes = Settings.node_parser(documents)
print(len(documents))
print(len(nodes))
```

**Comment by benlabbeus** [comment]
Ahh you're right, that's exactly what's happening. 11,808 documents\nodes. Thank you for the help 🙏
