### ISSUE TITLE
[Feature Request]: incremental updating in es store

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#11472]
### Feature Description

To make ElasticsearchStore update incrementally,  it can modify the `async_add` method to use the es upsert functionality. This may be achieved by changing the operation type from "index" to "update" and providing an upsert document. The upsert document is used if the document does not exist.

### Reason

When using ElasticsearchStore as the storage for the vector index in my app, I encountered a situation where multiple identical index data of documents is created during multiple app rebooting.
Is that no incremental updating？Like upsert？

### Value of Feature

Now, due to duplicated data, I have to defined a wrapper class of ElasticsearchStore to delete existed index when instantiated. That's a little bitter when large existing index data.

**Comment by logan-markewich** [comment]
I'm assuming upsert will only work if the IDs of the nodes are the same? The IDs are randomly generated unless you explicitly set them (unless elasticsearch can upsert based on another field)

I provided an alternative method in another issue you opened

**Comment by Hspix** [comment]
A `id ` arg may be added as ElasticsearchStore param, which determines which key of metadata can be used as "pk". The value of key is provided by user.

**Comment by Hspix** [comment]
> I'm assuming upsert will only work if the IDs of the nodes are the same? The IDs are randomly generated unless you explicitly set them (unless elasticsearch can upsert based on another field)
> 
> I provided an alternative method in another issue you opened

A id  arg may be added as ElasticsearchStore param, which determines which key of metadata can be used as "pk". The value of key is provided by user.
