### ISSUE TITLE
[Question]: How can I set output_parser locally?

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#11497]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I use `guardrails` as output_parser like this:

```
from pydantic import BaseModel
import guardrails as gd
from llama_index.output_parsers.guardrails import GuardrailsOutputParser

class APydanticBaseModel(BaseModel):
        pass

guardrail_prompt_template="..."

guard = gd.Guard.from_pydantic(output_class=APydanticBaseModel, prompt=guardrail_prompt_template)
output_parser = GuardrailsOutputParser(guard)
```

Demonstrating by `LLM` args, output_parser serve for it. When using RetrieverQueryEngine, how can I set the parser locally to engine for extraction object predefined by APydanticBaseModel?

**Comment by Hspix** [comment]
There is no need of GuardrailsOutputParser from your advice?

**Comment by Hspix** [comment]
There is no need of GuardrailsOutputParser from your advice?

**Comment by Hspix** [comment]
> _🤖_
> 
> Sure, I can guide you on how to set the parser locally to the `RetrieverQueryEngine` for an extraction object predefined by `APydanticBaseModel` in the LlamaIndex framework.
> 
> You should utilize the `from_args` class method of the `RetrieverQueryEngine` class. This method allows for the customization of the `response_synthesizer`, which is responsible for parsing and synthesizing the response based on the retrieved data and the query.
> 
> Assuming `APydanticBaseModel` is a subclass of `BaseModel` from `llama_index.core.bridge.pydantic`, and you want to use it as the output class for the response synthesizer, you would specify the `output_cls` parameter in the `from_args` method call. Here's how you can do it:
> 
> ```python
> from llama_index.core.query_engine.retriever_query_engine import RetrieverQueryEngine
> from your_application.models import APydanticBaseModel  # Assuming this is your defined Pydantic model
> from llama_index.core.base.base_retriever import BaseRetriever  # Assuming you have a retriever implementation
> 
> # Initialize your retriever here (this is just a placeholder, replace with your actual retriever)
> retriever = BaseRetriever()
> 
> # Create the RetrieverQueryEngine instance with APydanticBaseModel as the output class
> retriever_query_engine = RetrieverQueryEngine.from_args(
>     retriever=retriever,
>     output_cls=APydanticBaseModel,  # This sets the parser locally to use APydanticBaseModel for parsing the response
> )
> 
> # Now, retriever_query_engine is configured to use APydanticBaseModel for the response synthesis
> ```
> 
> This approach allows you to define how the data should be parsed and structured into a response object, leveraging the capabilities of Pydantic models for data validation and serialization. You can find more details in the [source code](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py) of the `RetrieverQueryEngine` class.
> 
> The `output_cls` parameter in the `from_args` method of the `RetrieverQueryEngine` class is used to specify the class type for the output of the response synthesizer. This parameter allows for the customization of the output format by defining a Pydantic model (`BaseModel`) that the response synthesizer should use to structure its output. This is particularly useful for ensuring that the synthesized response adheres to a specific schema or format, facilitating easier integration and consistency across different parts of a system that utilizes the LlamaIndex framework.
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [llama-index-core/llama_index/core/query_engine/retriever_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

There is no need of GuardrailsOutputParser from your advice?

**Comment by logan-markewich** [comment]
You can pass in the LLM as a kwarg

However, the code seems a little janky, its expecting the LLM object to have a `__call__()` function 

```
Class JankyLLM:
  def __init__(self, llm):
    self.llm = llm
  
  def __call__(self, prompt):
    return str(self.llm.complete(prompt))
    
output_parser = GuardrailsOutputParser(guard, llm=JankyLLM(llm))
```

**Comment by Hspix** [comment]
> > _🤖_
> > Sure, I can guide you on how to set the parser locally to the `RetrieverQueryEngine` for an extraction object predefined by `APydanticBaseModel` in the LlamaIndex framework.
> > You should utilize the `from_args` class method of the `RetrieverQueryEngine` class. This method allows for the customization of the `response_synthesizer`, which is responsible for parsing and synthesizing the response based on the retrieved data and the query.
> > Assuming `APydanticBaseModel` is a subclass of `BaseModel` from `llama_index.core.bridge.pydantic`, and you want to use it as the output class for the response synthesizer, you would specify the `output_cls` parameter in the `from_args` method call. Here's how you can do it:
> > ```python
> > from llama_index.core.query_engine.retriever_query_engine import RetrieverQueryEngine
> > from your_application.models import APydanticBaseModel  # Assuming this is your defined Pydantic model
> > from llama_index.core.base.base_retriever import BaseRetriever  # Assuming you have a retriever implementation
> > 
> > # Initialize your retriever here (this is just a placeholder, replace with your actual retriever)
> > retriever = BaseRetriever()
> > 
> > # Create the RetrieverQueryEngine instance with APydanticBaseModel as the output class
> > retriever_query_engine = RetrieverQueryEngine.from_args(
> >     retriever=retriever,
> >     output_cls=APydanticBaseModel,  # This sets the parser locally to use APydanticBaseModel for parsing the response
> > )
> > 
> > # Now, retriever_query_engine is configured to use APydanticBaseModel for the response synthesis
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This approach allows you to define how the data should be parsed and structured into a response object, leveraging the capabilities of Pydantic models for data validation and serialization. You can find more details in the [source code](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py) of the `RetrieverQueryEngine` class.
> > The `output_cls` parameter in the `from_args` method of the `RetrieverQueryEngine` class is used to specify the class type for the output of the response synthesizer. This parameter allows for the customization of the output format by defining a Pydantic model (`BaseModel`) that the response synthesizer should use to structure its output. This is particularly useful for ensuring that the synthesized response adheres to a specific schema or format, facilitating easier integration and consistency across different parts of a system that utilizes the LlamaIndex framework.
> > I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> > -[Dosu](https://dosu.dev)
> > ## Sources
> > 
> > * [llama-index-core/llama_index/core/query_engine/retriever_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py)
> > 
> > #### About Dosu
> > This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> > Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> > If you want to continue the conversation, start your reply with @dosu-bot.
> 
> There is no need of GuardrailsOutputParser from your advice?

The output_cls parameter is effective for all types response synthesizer in the retriever？

**Comment by Hspix** [comment]
> _🤖_
> 
> Sure, I can guide you on how to set the parser locally to the `RetrieverQueryEngine` for an extraction object predefined by `APydanticBaseModel` in the LlamaIndex framework.
> 
> You should utilize the `from_args` class method of the `RetrieverQueryEngine` class. This method allows for the customization of the `response_synthesizer`, which is responsible for parsing and synthesizing the response based on the retrieved data and the query.
> 
> Assuming `APydanticBaseModel` is a subclass of `BaseModel` from `llama_index.core.bridge.pydantic`, and you want to use it as the output class for the response synthesizer, you would specify the `output_cls` parameter in the `from_args` method call. Here's how you can do it:
> 
> ```python
> from llama_index.core.query_engine.retriever_query_engine import RetrieverQueryEngine
> from your_application.models import APydanticBaseModel  # Assuming this is your defined Pydantic model
> from llama_index.core.base.base_retriever import BaseRetriever  # Assuming you have a retriever implementation
> 
> # Initialize your retriever here (this is just a placeholder, replace with your actual retriever)
> retriever = BaseRetriever()
> 
> # Create the RetrieverQueryEngine instance with APydanticBaseModel as the output class
> retriever_query_engine = RetrieverQueryEngine.from_args(
>     retriever=retriever,
>     output_cls=APydanticBaseModel,  # This sets the parser locally to use APydanticBaseModel for parsing the response
> )
> 
> # Now, retriever_query_engine is configured to use APydanticBaseModel for the response synthesis
> ```
> 
> This approach allows you to define how the data should be parsed and structured into a response object, leveraging the capabilities of Pydantic models for data validation and serialization. You can find more details in the [source code](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py) of the `RetrieverQueryEngine` class.
> 
> The `output_cls` parameter in the `from_args` method of the `RetrieverQueryEngine` class is used to specify the class type for the output of the response synthesizer. This parameter allows for the customization of the output format by defining a Pydantic model (`BaseModel`) that the response synthesizer should use to structure its output. This is particularly useful for ensuring that the synthesized response adheres to a specific schema or format, facilitating easier integration and consistency across different parts of a system that utilizes the LlamaIndex framework.
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> -[Dosu](https://dosu.dev)
> 
> ## Sources
> * [llama-index-core/llama_index/core/query_engine/retriever_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

The output_cls parameter is effective for all types response synthesizer in the retriever？

**Comment by Hspix** [comment]
> Yes, the `output_cls` parameter in the `from_args` method of the `RetrieverQueryEngine` class applies to all types of response synthesizers in the retriever when using the LlamaIndex framework. This is because the `output_cls` parameter is passed to the `get_response_synthesizer` function, which is responsible for initializing the response synthesizer with the provided parameters, including `output_cls`.
> 
> Here is the relevant code snippet from the `from_args` method:
> 
> ```python
> response_synthesizer = response_synthesizer or get_response_synthesizer(
>             llm=llm,
>             service_context=service_context,
>             text_qa_template=text_qa_template,
>             refine_template=refine_template,
>             summary_template=summary_template,
>             simple_template=simple_template,
>             response_mode=response_mode,
>             output_cls=output_cls,
>             use_async=use_async,
>             streaming=streaming,
>         )
> ```
> 
> In this snippet, the `output_cls` parameter is used to define the class of the output response, allowing for customization of the response format across different types of response synthesizers.
> 
> The `output_cls` parameter in the `from_args` method of the `RetrieverQueryEngine` class in the LlamaIndex framework is used to specify the class type for the output of the response synthesizer. This parameter allows for the customization of the output format by defining a Pydantic model (`BaseModel`) that the response synthesizer should use to structure its output. This is particularly useful for ensuring that the synthesized response adheres to a specific schema or format, facilitating easier integration and consistency across different parts of a system that utilizes the LlamaIndex framework.
> 
> You can find more details in the [llama-index-core/llama_index/core/query_engine/retriever_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py) file in the LlamaIndex repository.
> 
> ## Sources
> * [llama-index-core/llama_index/core/query_engine/retriever_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py)
> 
> #### About Dosu

However，it seems that only TreeSummarize synthesizer can accept `output_cls`. If pass it to the `from_args` method of the `RetrieverQueryEngine` class, it just get TreeSummarize synthesizer?
