### ISSUE TITLE
[Question]: OOM when I build VectorStoreIndex using 60kb file

### ISSUE THREAD

**Issue by lchustc** [run-llama/llama_index#11500]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

v0.10.14
memory=16GB

OOM when I build VectorStoreIndex using 60kb file. My code is as follows:

```
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, StorageContext
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings
from llama_index.core.node_parser import SentenceSplitter
# define embed model
embed_model = HuggingFaceEmbedding(model_name="./bge-large-zh")

Settings.embed_model = embed_model
documents = SimpleDirectoryReader("./data").load_data()
issue_index = VectorStoreIndex.from_documents(documents)
retriever = issue_index.as_retriever()
```
<img width="458" alt="image" src="https://github.com/run-llama/llama_index/assets/27990344/f1385123-efec-4973-8da2-bec53ada272b">

Model only takes up 2GB. If i  build VectorStoreIndex using 6kb file, OOM will not occur.

<img width="619" alt="image" src="https://github.com/run-llama/llama_index/assets/27990344/e8bc5922-afae-40b4-a434-17c67c8c6941">

**Comment by lchustc** [comment]
<img width="653" alt="image" src="https://github.com/run-llama/llama_index/assets/27990344/2d4f452c-60e5-4095-b85a-e20fb6250c11">
130kb file take up 18GB memory. Why need so  much memory？

**Comment by logan-markewich** [comment]
It really depends how many nodes you are creating. The default batch size is 10, try lowering that

`embed_model = HuggingFaceEmbedding(model_name="./bge-large-zh", embed_batch_size=1)`
