### ISSUE TITLE
[Documentation]: Notebook for document insertion to index is missing

### ISSUE THREAD

**Issue by terilias** [run-llama/llama_index#11502]
### Documentation Issue Description

Hello!
I was reading the '[Document Management](https://docs.llamaindex.ai/en/stable/module_guides/indexing/document_management.html#insertion)' page on the Documentation and I noticed that the example notebook for insertion is [missing](https://github.com/run-llama/llama_index/blob/main/examples/paul_graham_essay/InsertDemo.ipynb). 
Thanks!

### Documentation Link

https://docs.llamaindex.ai/en/stable/module_guides/indexing/document_management.html#insertion

**Comment by logan-markewich** [comment]
Oh hmm, I'm not sure there even needs to be a notebook for that lol

`index.insert(document)`

`index.insert_nodes(nodes)`

Probably can update to remove that link and just show insertion

**Comment by terilias** [comment]
Yes, I understand. The only information I wanted to find is how to create an empty vector store index and use it later to add documents inside it. But using the documentation's bot I found that this can be done by inserting an empty list of nodes or documents:
```
# Create and save an empty chroma index to disk.
db = chromadb.PersistentClient(path="./new_chroma_test")
chroma_collection = db.get_or_create_collection("test")
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
   documents = [], storage_context=storage_context, embed_model=embed_model, show_progress=True
)
# Now add a document to this index.
index.insert(document=documents[0])
```

Can you please confirm that this code is correct?

**Comment by logan-markewich** [comment]
Yea that works

**Comment by terilias** [comment]
Thanks a lot for your help once again!
