### ISSUE TITLE
[Question]: Keywords extraction in Knowledge graph

### ISSUE THREAD

**Issue by AnujLahoty** [run-llama/llama_index#11505]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

@logan-markewich , thanks a lot for your very quick responses.
I had one doubt:

So while creating the knowledge graph using llamindex, I get that the entities are exarcted using LLMs, correct me if I am wrong and now from each text chunks the keywords are extracted and are stored in the lookup table which I assume is stored in the index_struct.table. Here are my couple of questions:

So during the query time, how are the keywords extracted?

If those keywords are extracted, are they matched against the table stored in index_struct? whichever keywords gets matched it brings forth the respective documents?

I am a bit fuzzy on how the entities are getting extracted from query and how they are matched against and how the text nodes are getting collected?

**Comment by AnujLahoty** [comment]
How can I extract the keywords from the query and inspect them?

**Comment by AnujLahoty** [comment]
@logan-markewich ,
I am a bit eager to know on this and have dire deliverable comming in, may you please help me out here mate?
Thanks in advance.

**Comment by logan-markewich** [comment]
@AnujLahoty the LLM is used to extract keywords. And then these keywords are matched against triplets in your KG. If a match is found and `include_text=True` (it is by default), the text chunk where that triplet was found is used to send to the LLM for context

**Comment by logan-markewich** [comment]
Definitely check out the source code to learn more tbh
https://github.com/run-llama/llama_index/blob/b3112de72f6253510ee9a94a9b18fd0e602ea4c0/llama-index-core/llama_index/core/indices/knowledge_graph/retrievers.py#L188

You can set `index.as_query_engine(..., verbose=True)` to see the keywords extracted from queries

**Comment by AnujLahoty** [comment]
@logan-markewich 
Any thoughts here?
