### ISSUE TITLE
[Documentation]: Llama_Index Vectara AutoRetriever not working based on documentation

### ISSUE THREAD

**Issue by omnific9** [run-llama/llama_index#11515]
### Documentation Issue Description

By following the current documentation on llama_index autoretriever for Vectara: https://docs.llamaindex.ai/en/stable/examples/retrievers/vectara_auto_retriever.html

I started with an existing index, when I reach retriever.retrieve(query), I get the following error:
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for VectorStoreQuerySpec
query
  field required (type=value_error.missing)
filters
  field required (type=value_error.missing)

Looks like several steps are missing in the document. Please find my code snippet below:

```
index = VectaraIndex(vectara_customer_id=VECTARA_CUSTOMER_ID,
                     vectara_corpus_id=VECTARA_CORPUS_ID,
                     vectara_api_key=VECTARA_API_KEY)

vector_store_info = VectorStoreInfo(
    content_info="information about a movie",
    metadata_info=[
        MetadataInfo(
            name="price",
            description="Price of the movie ticket",
            type="integer",
        ),
    ],
)

retriever = VectaraAutoRetriever(
    index,
    vector_store_info=vector_store_info,
)

retriever.retrieve("Show me movies")
```

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/retrievers/vectara_auto_retriever.html

**Comment by logan-markewich** [comment]
Steps are not missing -- seems like the LLM just decided not to write a query or filters

**Comment by omnific9** [comment]
@logan-markewich I've run this a dozen more times and it's not working.

From what you said, my understanding is the underlying LLM to generate the metadata filter is not generating anything. Do I need to specify which LLM to use? Seems strange that it would use an LLM to do this without connecting to anywhere and without me specifying API keys, or is it connecting to OpenAI and reading my default environment API key?

**Comment by logan-markewich** [comment]
It's defaulting to gpt-3.5 yes (which is the default llm/behavior for the entire library)

**Comment by omnific9** [comment]
@logan-markewich anything else I can try?

**Comment by HasnainKhanNiazi** [comment]
I am also facing the same problem. I have tried with GPT3.5, GPT4, GPT4o with temperature from 0-1 but nothing is working.

**Comment by HasnainKhanNiazi** [comment]
I have did multiple tests and it seems like I found an answer what could be the problem.

This is how I am making `VectorIndexAutoRetriever`:

```
vector_store_info = VectorStoreInfo(
    content_info="Brief summary of a Product",
    metadata_info=[
        MetadataInfo(
            name="price",
            description="price of the product",
            type="float",
        )
    ],
)

for index, row in data.iterrows():
        attr = json.loads(row["attributes"])
        text = row["title"]
        embeddingg = json.loads(row["Title Embedding"])
        if "price" in attr:
            node = TextNode(text=text, metadata={"price": attr["price"]}, embedding=embeddingg)
        else:
            node = TextNode(text=text, metadata={"price": 0}, embedding=embeddingg)
        new_nodes.append(node)
        

vector_index = VectorStoreIndex(nodes=new_nodes)
retriever = VectorIndexAutoRetriever(
            vector_index, vector_store_info=vector_store_info
        )
```

In the metadata above `price` is a variable value which can go from 1 to 1000 or even more so if I change from `attr["price"]` to lets say `5` for each node then it works fine but if for every node price is different then it gives the above error;

Now, I don't know how to fix this as I will have to read all the underlying code of Llamaindex `VectorIndexAutoRetriever`.

**Comment by botschmiede** [comment]
I was facing the same issue and its like @logan-markewich already said.
The solution was to give a more descriptive VectorStoreInfo
