### ISSUE TITLE
E5-Large Llama Index embeddings don't match Langchain

### ISSUE THREAD

**Issue by airwindk** [run-llama/llama_index#11521]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can you help me understand why this doesn't tie out? I see that the embeddings are normalized by default in LlamaIndex's implementation and have passed the argument when creating the Langchain object. 

```
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

embedding_func_li = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large"#, max_length=512
)

embedding_func_lc = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large", encode_kwargs={"normalize_embeddings": True})


text_to_embed = "The Nasdaq notched its first record close since 2021. The tech-heavy index rose 0.9% to 16091.92, as enthusiasm about artificial intelligence has helped lift technology shares."

print(embedding_func_li.get_text_embedding(text_to_embed))
print(embedding_func_lc.embed_query(text_to_embed))
```

**Comment by logan-markewich** [comment]
I thiiiiiiink E5 requires some special pooling that got added recently

`HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large", pooling="last")`

(side note, E5 is waaay to big to be worth any improvements in accuracy, my unsolicited hot take)

**Comment by airwindk** [comment]
Mean pooling seemed to do the trick. Thank you! These seem to tie out. 

And not at all on your take. I needed a model that performed decently on medium / longer contexts, which the smaller sentence models seem to struggle with. If you have any other suggestions on open source embedding models let me know.

`from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from langchain.embeddings.huggingface import HuggingFaceEmbeddings

embedding_func_li = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large", pooling="mean")
embedding_func_lc = HuggingFaceEmbeddings(model_name="intfloat/multilingual-e5-large", encode_kwargs={"normalize_embeddings": True})
`

**Comment by logan-markewich** [comment]
I know nomic has some recent embedding models that work with long context.

Anyways, glad it works!
