### ISSUE TITLE
[Question]: Gemma Issue with "query_engine = SQLAutoVectorQueryEngine(sql_tool, vector_tool )" 

### ISSUE THREAD

**Issue by afshinebtia** [run-llama/llama_index#11523]
[TextSQLQuery.txt](https://github.com/run-llama/llama_index/files/14454684/TextSQLQuery.txt)
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone,

I need assistance with my implementation issue and would appreciate it if someone could help me.

I have tried to implement the tutorial of retrieving data from SQL and Wikipedia ([](https://github.com/sudarshan-koirala/youtube-stuffs/blob/main/llamaindex/Combining_Text_to_SQL_with_Semantic_Search_for_Retrieval_Augmented_Generation.ipynb)). The code works without any issues with GPT models.

When using LLM = Gemma and Embedding model = local:BAAI/bge-small-en-v1.5 in my Jupyter notebook, the model can generate appropriate responses for different questions by looking at individual SQL/Wikipedia data, regardless of whether I use the **SQL query engine** or the **vector index query engine** separately.

However, when I use `query_engine = SQLAutoVectorQueryEngine(sql_tool, vector_tool )` to retrieve data from both data sources for the query of `response = query_engine.query("Tell me about the arts and culture of the city with the highest population") `,
I get the following error:

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
File [c:\Users\.conda\envs\llamaindex_py3.10\lib\site-packages\llama_index\core\output_parsers\selection.py:75](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/site-packages/llama_index/core/output_parsers/selection.py:75), in SelectionOutputParser.parse(self, output)
     [74](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/site-packages/llama_index/core/output_parsers/selection.py:74) try:
---> [75](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/site-packages/llama_index/core/output_parsers/selection.py:75)     json_obj = json.loads(json_string)
     [76](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/site-packages/llama_index/core/output_parsers/selection.py:76) except json.JSONDecodeError as e_json:

File [c:\Users\.conda\envs\llamaindex_py3.10\lib\json\__init__.py:346](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:346), in loads(s, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    [343](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:343) if (cls is None and object_hook is None and
    [344](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:344)         parse_int is None and parse_float is None and
    [345](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:345)         parse_constant is None and object_pairs_hook is None and not kw):
--> [346](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:346)     return _default_decoder.decode(s)
    [347](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/__init__.py:347) if cls is None:

File [c:\Users\.conda\envs\llamaindex_py3.10\lib\json\decoder.py:340](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/decoder.py:340), in JSONDecoder.decode(self, s, _w)
    [339](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/decoder.py:339) if end != len(s):
--> [340](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/decoder.py:340)     raise JSONDecodeError("Extra data", s, end)
    [341](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/json/decoder.py:341) return obj

JSONDecodeError: Extra data: line 7 column 1 (char 210)

During handling of the above exception, another exception occurred:

ScannerError                              Traceback (most recent call last)
File [c:\Users\.conda\envs\llamaindex_py3.10\lib\site-packages\llama_index\core\output_parsers\selection.py:84](file:///C:/Users/.conda/envs/llamaindex_py3.10/lib/site-packages/llama_index/core/output_parsers/selection.py:84), in SelectionOutputParser.parse(self, output)
...
    {
        "choice": 2,
        "reason": "The question is about the arts and culture of a city, so the most relevant choice is (2) Useful for answering semantic questions about different cities."
    }
]

**Comment by logan-markewich** [comment]
This is because this specific feature requires the LLM to output a structured JSON, and it seems like gemma did not do this (this is common for open-source LLMs)

**Comment by afshinebtia** [comment]
> This is because this specific feature requires the LLM to output a structured JSON, and it seems like gemma did not do this (this is common for open-source LLMs)

Thanks @logan-markewich for your response.
So is there any solution to modify this?

**Comment by logan-markewich** [comment]
Prompt engineering? Fine tuning?

**Comment by afshinebtia** [comment]
> Prompt engineering? Fine tuning?

Of course they could be some alternatives, however, I need to use RAG in the context of my work.

Btw, do you have any idea why local models such as Gemma are sooo slow in generating responses from indexes?
The gpt3.5 generates in a few seconds, however, for Gemma and Llama it takes like 1 hour!

**Comment by Arsive02** [comment]
Hi @afshinebtia , you can check out https://github.com/guidance-ai/guidance

**Comment by afshinebtia** [comment]
> Hi @afshinebtia , you can check out https://github.com/guidance-ai/guidance

Hi @Arsive02,
Thanks for your reply. I will look at it.
This repo seems fantastic!
