### ISSUE TITLE
[Question]: How to use a remote deployed Llama model?

### ISSUE THREAD

**Issue by chansonzhang** [run-llama/llama_index#11533]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

It is only mentioned in the doc how to[ use a local LLM](https://docs.llamaindex.ai/en/stable/understanding/using_llms/using_llms.html#using-a-local-llm) or Openai. 
However, I has a Llama 13B deployed in a remote server, how can I access it from llamaIndex. 
I tried `llm=OpenAI(api_key=<my api_key>, api_base=<remote server url>)`, but it will report "The model `gpt-3.5-turbo` does not exist"

**Comment by chansonzhang** [comment]
@dosubot I'm trying to bind the llm to a ServiceContext
```
ServiceContext.from_defaults(
    chunk_size=1024,
    llm=llm,
    embed_model=embeddings
)
```
but it report `ValueError: "AzureOpenAIMultiModal" object has no field "callback_manager"`

**Comment by anoopshrma** [comment]
Use openailike, pass the url of your hosted llm and add any random value into key and model. That should be enough for you to get going!
https://docs.llamaindex.ai/en/stable/examples/llm/localai.html#llamaindex-interaction

**Comment by logan-markewich** [comment]
@chansonzhang yea, if it is using openai-like API, use the OpenAILike LLM class

Otherwise, if its just your own custom API, you need to implement your own LLM class
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html#example-using-a-custom-llm-model-advanced

**Comment by logan-markewich** [comment]
Depending on what you deployed your LLM with, it may also be covered by an existing class
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/modules.html

**Comment by chansonzhang** [comment]
> Use openailike, pass the url of your hosted llm and add any random value into key and model. That should be enough for you to get going! https://docs.llamaindex.ai/en/stable/examples/llm/localai.html#llamaindex-interaction

@anoopshrma Thanks, this works for me.
```
llm = OpenAILike(
    model='meta-llama/Llama-2-13b-chat-hf',
    api_key=<my api_key>, 
    api_base=<remote server url>
)
```

**Comment by chansonzhang** [comment]
> Depending on what you deployed your LLM with, it may also be covered by an existing class https://docs.llamaindex.ai/en/stable/module_guides/models/llms/modules.html

@logan-markewich  I also tried this, but when I execute `pip install llama-index-llms-llama-api`, it reports: 
```
ERROR: Could not find a version that satisfies the requirement llamaapi<0.2.0,>=0.1.36 (from llama-index-llms-llama-api) (from versions: none)
ERROR: No matching distribution found for llamaapi<0.2.0,>=0.1.36
```
