### ISSUE TITLE
[Question]: Keep ServiceContext with Settings

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#11543]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can we _not_ replace `ServiceContext` with `Settings`? While I appreciate, and love the idea of a global settings object for this task, it's not in my opinion conducive with all the usage scenarios for Llama-Index, like in systems where the objects you're passing are managed memory, where you don't want a global system apart from that but want volatile objects. 

I'd prefer if we kept `ServiceContext` and allow it's continued use, and maybe allow a way for ServiceContext to feed Settings in the event you wanted to persist to global memory outside your own management of memory and objects.

**Comment by logan-markewich** [comment]
@WAS-PlaiLabs Thanks for the feedback,

Settings are global, but you can still override settings by passing in the objects that classes use

for example
```
index = VectorStoreIndex(..., embed_model=embed_model, transformations=[SentenceSplitter(chunk_size=512)])

index.as_chat_engine(..., llm=llm)

index.as_query_engine(..., llm=llm)
```

And so on.

I gave a larger justification the other day over here, if you are curious
https://github.com/run-llama/llama_index/issues/11467#issuecomment-1969206261

**Comment by WAS-PlaiLabs** [comment]
> @WAS-PlaiLabs Thanks for the feedback,
> 
> Settings are global, but you can still override settings by passing in the objects that classes use
> 
> for example
> 
> ```
> index = VectorStoreIndex(..., embed_model=embed_model, transformations=[SentenceSplitter(chunk_size=512)])
> 
> index.as_chat_engine(..., llm=llm)
> 
> index.as_query_engine(..., llm=llm)
> ```
> 
> And so on.
> 
> I gave a larger justification the other day over here, if you are curious [#11467 (comment)](https://github.com/run-llama/llama_index/issues/11467#issuecomment-1969206261)

Thanks for the reply! And I totally understand where you're coming from. But maybe you're not thinking about all the use-cases for llama-index? For example I have high-hopes for node-network usage. But a global storage, utiliizng a `llm` param means I have to swap models in-line and cannot cache them for quick runs, where the models are loaded independently as objects, and cacheable -- thus the next run, multiple models can run immediately. Yes this means more memory, but also mean efficient runs. If I switch to settings, I have to swap models and load models during every run of the network, significantly slowing it down.

**Comment by logan-markewich** [comment]
For example, if you give me a piece of sample code, I can show what it looks like without service context. I really do think it will be ok 👍🏻
