### ISSUE TITLE
[Question]: from llama_index.finetuning import EmbeddingAdapterFinetuneEngine ImportError: cannot import name 'EmbeddingAdapterFinetuneEngine' from 'llama_index.finetuning' (unknown location)

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#11555]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am facing this issue: from llama_index.finetuning import EmbeddingAdapterFinetuneEngine
ImportError: cannot import name 'EmbeddingAdapterFinetuneEngine' from 'llama_index.finetuning' (unknown location)

with this code:
import json
from llama_index.finetuning import EmbeddingAdapterFinetuneEngine
from llama_index.core.embeddings import resolve_embed_model
import torch

class CustomDataset:
    def __init__(self, data):
        self.queries = data.get('queries', {})
        self.relevant_docs = data.get('relevant_docs', {})
        # Add this line to include the corpus attribute
        self.corpus = data.get('corpus', {})

    # Ensure to add any other methods or attributes expected by the finetuning engine if necessary

# Function to load a JSON file into a Python dictionary
def load_json(file_path):
    with open(file_path, 'r', encoding='utf-8') as file:
        return json.load(file)

# Load your datasets from the JSON files
train_dataset = load_json('train_dataset7.json')
val_dataset = load_json('val_dataset7.json')

train_dataset = CustomDataset(train_dataset)
base_embed_model = resolve_embed_model("BAAI/bge-m3")

val_dataset = CustomDataset(val_dataset)
finetune_engine = EmbeddingAdapterFinetuneEngine(
    train_dataset,
    base_embed_model,
    model_output_path="model_output_test",
    # bias=True,
    epochs=5,
    verbose=True,
    # optimizer_class=torch.optim.SGD,
    # optimizer_params={"lr": 0.01}
)
I also tried with this code but also wasn't succesful. I think it could be some issue with the installation of llama_index but I reinstalled it and have the same issue. Thank you for taking the time to read this.

**Comment by logan-markewich** [comment]
Try with a fresh venv

In a new terminal
```
pip uninstall llama-index  # remove any global install
python -m venv venv 
source venv/bin/activate
pip install llama-index llama-index-finetuning
```
