### ISSUE TITLE
[Documentation]: How to import FaissVectorStore 

### ISSUE THREAD

**Issue by aabor** [run-llama/llama_index#11550]
### Documentation Issue Description

Unable to import FaissVectorStore
The documentation example is incorrect:
from llama_index.vector_stores.faiss import FaissVectorStore

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/vector_stores/FaissIndexDemo.html

**Comment by logan-markewich** [comment]
The documentation is correct.

Did you miss the pip install at the top maybe?

`pip install llama-index-vector-stores-faiss`

**Comment by qbm5** [comment]
Like @logan-markewich  said, you have to import the faiss lib to use faiss vector stores

`pip install llama-index-vector-stores-faiss`

Then for a quick example

```
import faiss
from llama_index.vector_stores.faiss import FaissVectorStore
from llama_index.core import VectorStoreIndex,  SimpleDirectoryReader
from llama_index.core import StorageContext, load_index_from_storage

...

faiss_index = faiss.IndexFlatL2(self.d) # d = dimensions
vector_store = FaissVectorStore(faiss_index=faiss_index)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex(splitDocs, storage_context=storage_context ,show_progress = True)
# or VectorStoreIndex.from_documents
index.storage_context.persist(persist_dir=self.persist_dir) # store the index to disk
```
