### ISSUE TITLE
[Question]: No module named 'llama_index.readers.microsoft_sharepoint'

### ISSUE THREAD

**Issue by BBjie** [run-llama/llama_index#11552]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When I was trying to access sharepoint files as the code below, it popped an error that " Unable to import SharePointReader"  The above exception was the direct cause of the following exception:   "Unable to import SharePointReader"

**from llama_index.core import download_loader
SharePointLoader = download_loader("SharePointReader")
loader = SharePointLoader(
            client_id = client_id,
            client_secret = client_secret,
            tenant_id = tenant_id
)
documents = loader.load_data(
            sharepoint_site_name = SP_SITE,
            sharepoint_folder_path = SP_FOLDER,
            recursive = True,
)**

I checked my env, which I have 

 **llama-index                              0.10.12, 
llama-index-core                         0.10.14.post1, 
llama-index-readers-web                  0.1.6 
llama-index-readers-microsoft-sharepoint 0.1.3,** 

which is weird since I got all the requirements set up. Could anyone help me with it?

**Comment by logan-markewich** [comment]
Since you have it installed, no need to use download loader (which is technically deperacated anyways)

`from llama_index.readers.microsoft_sharepoint import SharePointReader`

**Comment by BBjie** [comment]
> Since you have it installed, no need to use download loader (which is technically deperacated anyways)
> 
> `from llama_index.readers.microsoft_sharepoint import SharePointReader`

Thank you so much for your immediate reply! After I uninstalled all those related packages and reinstalled them again, it worked. No clue what causes this, but the download loader still works.  Thanks again!
