### ISSUE TITLE
[Bug]: LLM evaluated with Llamaindex don't provide scores for certain metrics.

### ISSUE THREAD

**Issue by bastienpo** [run-llama/llama_index#11567]
### Bug Description

Llamaindex crashes when evaluating some large language models for specific metrics (e.g., answer correctness). This happens because these models don't provide scores in their outputs. 

Currently, our temporary solution using a try-except prevents crashes, but a more robust approach is may be required.

Implementing proper error to handle missing scores seems like a good approach or providing any kind of feedback to the developers about the missing score could be valuable. I'm open if you have any other solutions that you think could work in this case.

### Version

v0.10.1

### Steps to Reproduce

Here's the corrected version of the message:

This issue is difficult to reproduce because it's not always deterministic due to its reliance on a large language model (LLM).

**Hyperparameter causing the problem:**
- Using OpenAI embeddings with the "text-embedding-3-large" model.
- OpenAI GPT-3 Turbo model (with default hyperparameters).
- Metric: correctness.

**Data used to reproduce the bug:** 
Unfortunately, I cannot share the data due to confidentiality.

The error appears to be caused by the line `score_str = ''` (empty string).

https://github.com/run-llama/llama_index/blob/d97cec8ade50f3197f09cc380676c6e4f5288439/llama-index-core/llama_index/core/evaluation/eval_utils.py#L183

**Comment by cmishra** [comment]
I threw in some retry logic around my `.evaluate` call cause i'm not quite familiar enough with llama index's abstractions to do much better atm. 

Any examples that could point to how to combine this with a pydantic parser and the self-correcting query engines to do this inside of llama index's abstractions? after all what is the correctness evaluator if not another query over two contexts (the anstwer and reference)
