### ISSUE TITLE
[Bug]: Chroma HNSWLib Dependency Issue

### ISSUE THREAD

**Issue by ytang07** [run-llama/llama_index#11578]
### Bug Description

ERROR: Cannot install llama-index-cli because these package versions have conflicting dependencies.

The conflict is caused by:
    llama-index-vector-stores-chroma 0.1.5 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.4 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.3 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.2 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.1 depends on onnxruntime<2.0.0 and >=1.17.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

Note: OSX Version 13.5.6

### Version

0.10.15

### Steps to Reproduce

pip install llama-index

### Relevant Logs/Tracbacks

```shell
ERROR: Cannot install llama-index-cli because these package versions have conflicting dependencies.

The conflict is caused by:
    llama-index-vector-stores-chroma 0.1.5 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.4 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.3 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.2 depends on onnxruntime<2.0.0 and >=1.17.0
    llama-index-vector-stores-chroma 0.1.1 depends on onnxruntime<2.0.0 and >=1.17.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by fuzziebrain** [comment]
I had the same issue. Within my Conda environment, I installed `onnxruntime` v1.17.1 through Conda Forge before installing `llama-index-vector-stores-chroma` with `pip`. Seems to work. HTH.

**Comment by ytang07** [comment]
cool, seems the chroma team suggested something similar, i posted this for an attendee at a hackathon I was hosting, closing for now as the problem is no longer within my scope

**Comment by nmhjklnm** [comment]
![image](https://github.com/run-llama/llama_index/assets/108562510/e4ae459c-e399-4d35-b1b9-275d31c06351)
if you have this bug too.may be solved by:
`conda install -c conda-forge onnxruntime`
