### ISSUE TITLE
[Documentation]: openai_agent example is incompatible with latest openai library

### ISSUE THREAD

**Issue by adieyal** [run-llama/llama_index#11579]
### Documentation Issue Description

The openai_agent example and accompanying notebook are not compatible with the latest openai library
https://github.com/run-llama/llama_index/blob/main/docs/examples/agent/openai_agent.ipynb
https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent.html

```
def _call_function(self, tool_call: dict) -> ChatMessage:
        id_ = tool_call["id"]
        function_call = tool_call["function"]
        tool = self._tools[function_call["name"]]
        output = tool(**json.loads(function_call["arguments"]))
        return ChatMessage(
            name=function_call["name"],
            content=str(output),
            role="tool",
            additional_kwargs={
                "tool_call_id": id_,
                "name": function_call["name"],
            },
        )
```

should be replaced with

```
def _call_function(self, tool_call) -> ChatMessage:
        id_ = tool_call.id
        function_call = tool_call.function
        tool = self._tools[function_call.name]
        output = tool(**json.loads(function_call.arguments))
        return ChatMessage(
            name=function_call.name,
            content=str(output),
            role="tool",
            additional_kwargs={
                "tool_call_id": id_,
                "name": function_call.name,
            },
        )
```

strictly speaking `tool_call` is of type `openai.types.chat.chat_completion_message_tool_call.ChatCompletionMessageToolCall` and no longer `dict` - I am not sure whether there is an intention to abstract away the OpenAI types

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent.html

**Comment by logan-markewich** [comment]
To be clear, this is just the portion of the example showing creating your own agent, not our actual agent code in the framework

**Comment by adieyal** [comment]
yep - but it's worth updating the documentation in case someone following along encounters the error and doesn't know how to proceed.
