### ISSUE TITLE
[Question]: How to combine multiple indexes into a single index that can be queried.

### ISSUE THREAD

**Issue by qbm5** [run-llama/llama_index#11580]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Could use some help finding direction on this one.  I have a scenario where a use may want to query multiple indexes at the same time.

I went the route of merging them like this

```
for data in self.data:
      loc = data.path.split('/')[1]
      sent = f"embeddings/{loc}_sentence"
      store = FaissVectorStore.from_persist_dir(sent)
      scs = StorageContext.from_defaults(
          vector_store=store, persist_dir=sent
      )
      index = load_index_from_storage(storage_context=scs)
      if mainIndex is None:
          mainIndex = index
      else:
          docs = []
          ds = index.docstore.docs
          for node in ds:
              doc = ds[node]
              docs.append(doc)
          mainIndex.insert_nodes(docs, show_progress=True)
```

That works, but it is a slow process.  I was hoping for a way to quickly combine BaseIndex's on the fly so a user could query 1 or more indexes for their answer. Or maybe some way of merging the query_engine's.

I have seen stuff like this
https://github.com/run-llama/llama_index/issues/1063
but it doesnt seem to work the way I expect.

**Comment by logan-markewich** [comment]
Actually merging the indexes is not really possible. But you can query all them and return an aggregated/ranked result using query fusion retriever 
https://docs.llamaindex.ai/en/stable/examples/retrievers/reciprocal_rerank_fusion.html#reciprocal-rerank-fusion-retriever

**Comment by qbm5** [comment]
@logan-markewich 
Thank you, that was helpful
