### ISSUE TITLE
[Question]: The chromadb migration of November 7, 2023 affects the __call__ method of the EmbeddingFunction function

### ISSUE THREAD

**Issue by renatocava** [run-llama/llama_index#11590]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
import chromadb
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
client = chromadb.PersistentClient(path="/home/PycharmProjects/mvp_2/chromadb_vectors")
text_collection = client.get_or_create_collection(name="text_collection", embedding_function=embed_model)
```

ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'nodes', 'kwargs'])
Please see https://docs.trychroma.com/embeddings for details of the EmbeddingFunction interface.
Please note the recent change to the EmbeddingFunction interface: https://docs.trychroma.com/migration#migration-to-0416---november-7-2023

**Comment by logan-markewich** [comment]
This isn't really a llama-index issue? Normally with any vector db, llama index will embed data before inserting. No need to provide this embedding function.

I'm not sure what chroma expects for this field, but it's not even needed when using llama-index
