### ISSUE TITLE
[Question]: Is the RAPTOR package compatible with OpenSearch?

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#11592]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm following https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb to kick-off some RAPTOR experiments for my use case. I notice that the example notebook uses ChromaVectorStore as an index. I wonder whether the pack is consistent

**Comment by logan-markewich** [comment]
It should work with any vector db (I hope) from llama-index

**Comment by mw19930312** [comment]
@logan-markewich Thanks! I'll give it a try.
