### ISSUE TITLE
[Question]: chat-engi had no respond

### ISSUE THREAD

**Issue by shuozhu1** [run-llama/llama_index#11595]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

memory = ChatMemoryBuffer.from_defaults(token_limit=10000)

chat_engine = base_index.as_chat_engine(
    service_context=service_context,
    memory=memory,
    chat_mode="best",
    verbose=True,
    system_prompt=new_response,
）
chat_engine.reset()

response = chat_engine.stream_chat("描述南京地铁在小行—安德门上行区间的故障")
for token in response.response_gen:
    print(token, end="")

here is the output：

Keyword arguments {'add_special_tokens': False} not recognized.
 Thought: I need to use a tool to help me answer the question.

Action: query_engine_tool

Action Input: {"input": "描述南京地铁在小行—安德门上行区间的故障"}

</s>

**Comment by shuozhu1** [comment]
no respond

**Comment by shuozhu1** [comment]
I noticed that the default query_engine is created in chat, but there are no parameters to pass in the query_engine I have instantiated, is there any way to pass in my own query_engine?

here is my query_engine:
query_engine_base = base_index.as_query_engine(response_mode="tree_summarize",node_postprocessors=[reranker],similarity_top_k=10)

**Comment by logan-markewich** [comment]
You can create the chat engine from scratch using an agent
https://docs.llamaindex.ai/en/stable/module_guides/deploying/agents/modules.html
