### ISSUE TITLE
[Question]: How to load the existing Nebula Graph data into KnowledgeGraphIndex?

### ISSUE THREAD

**Issue by ToeleoT** [run-llama/llama_index#11601]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
I have a question about how to load the existing Nebula Graph data into KnowledgeGraphIndex?
Because i have create the Nebula Graph and insert the data into it, and now i just want to load it to the Index to make some query, what can i do?

**Comment by ToeloeT** [comment]
So after i get the data from the Nebula Graph, and how to use those data into KnowledgeGraphIndex, can you provide some specific process?

**Comment by mavericb** [comment]
@dosu-bot I also want to know: "So after i get the data from the Nebula Graph, and how to use those data into KnowledgeGraphIndex, can you provide some specific process?"

**Comment by ToeloeT** [comment]
> Hello again, @ToeloeT! Great to see you back with more questions.
> 
> To load your existing Nebula Graph data into the KnowledgeGraphIndex, you can use the `NebulaGraphStore` class provided in the `nebulagraph.py` file. Here are the steps you can follow:
> 
> 1. **Initialize the NebulaGraphStore**: Create an instance of the `NebulaGraphStore` class by providing the necessary parameters such as `session_pool`, `space_name`, `edge_types`, `rel_prop_names`, `tags`, and `tag_prop_names`. If you don't have a session pool already created, ensure that the environment variables `NEBULA_USER`, `NEBULA_PASSWORD`, and `NEBULA_ADDRESS` are set, as the `init_session_pool` method uses these to create a session pool.
> 2. **Execute Queries**: Use the `execute` method of the `NebulaGraphStore` instance to run queries against your Nebula Graph data. This method takes a query string and an optional parameter map. It handles retries and session pool reinitialization in case of connection issues.
> 3. **Get Data**: To retrieve data, you can use methods like `get` or `get_flat_rel_map`. The `get` method retrieves triplets for a given subject, while `get_flat_rel_map` retrieves a flat relationship map for given subjects, allowing for multi-hop queries.
> 
> Here's an example of how you might set up and use the `NebulaGraphStore`:
> 
> ```python
> from llama_index.legacy.graph_stores.nebulagraph import NebulaGraphStore
> 
> # Initialize NebulaGraphStore with your specific configuration
> nebula_store = NebulaGraphStore(
>     space_name='your_space_name',
>     edge_types=['your_edge_type'],
>     rel_prop_names=['your_rel_prop_names'],
>     tags=['your_tags'],
>     tag_prop_names=['your_tag_prop_names'],
>     include_vid=True
> )
> 
> # Assuming you have a subject ID to start with
> subject_id = 'your_subject_id'
> 
> # Get triplets for the subject
> triplets = nebula_store.get(subject_id)
> 
> # If you need a more complex relationship map
> subjs = ['list', 'of', 'subject', 'ids']
> rel_map = nebula_store.get_flat_rel_map(subjs=subjs, depth=2, limit=30)
> 
> # Use the retrieved data as needed
> ```
> 
> Please replace placeholders like `'your_space_name'`, `'your_edge_type'`, etc., with actual values from your Nebula Graph setup. This example assumes that the `NebulaGraphStore` class and its methods meet your requirements for interacting with the KnowledgeGraphIndex.
> 
> You can find more details about the `NebulaGraphStore` class and its methods in the [nebulagraph.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/graph_stores/nebulagraph.py) file.
> 
> The `get` method in the `NebulaGraphStore` class retrieves triplets based on a given subject. It calls the `get_flat_rel_map` method with the subject, a depth of 1, and a default limit of 30 to fetch a flat relationship map. This map is then processed to return a list of triplets related to the subject. The triplets represent relationships in the graph, detailing how entities (nodes) are connected through edges (relationships). The method is designed to return knowledge about direct relationships involving the specified subject, which can be useful for tasks that require understanding the connections between entities in a graph.
> 
> The `get_flat_rel_map` method, which the `get` method relies on, constructs a query to fetch relationships from the NebulaGraph database. This query is designed to retrieve multi-hop relation paths, allowing for the extraction of complex relationship chains that involve the subject. The method formats the results into a dictionary where each key is a subject and the value is a list of strings representing the flattened relationships involving that subject. These strings detail the entities involved in the relationships, the type of relationship, and any properties associated with those relationships.
> 
> The data retrieved by the `get` method is thus a list of lists of strings, where each inner list represents a triplet detailing a direct relationship involving the specified subject. This includes information about the entities connected by the relationship and the nature of their connection, which can be used to understand the graph's structure and the roles of different entities within it.
> 
> You can find more details about these methods in the [base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/base.py) file.
> 
> I hope this helps! If you have any more questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [llama-index-legacy/llama_index/legacy/graph_stores/nebulagraph.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/graph_stores/nebulagraph.py)
> * [llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

**Comment by ToeloeT** [comment]
@dosu-bot Sorry for forget @ you, and the question i want to continue is that after i get the data from the Nebula Graph, and how to use those data into KnowledgeGraphIndex to make the query, can you provide some specific process?
