### ISSUE TITLE
[Question]: Is there a way to have the system automatically choose whether to use the LLM or the RAG?

### ISSUE THREAD

**Issue by seanxuu** [run-llama/llama_index#11609]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Now there is a scenario where a man enters a question and wants to get an answer, can this answer be automatically distributed to the RAG system to do an intent recognition function(All information is retrieved from local storage). 

When the man enters another question, this answer is distributed to the LLM, which gives the answer.

**Comment by logan-markewich** [comment]
@seanxuu this is pretty much what an agent does
https://docs.llamaindex.ai/en/stable/module_guides/deploying/agents/root.html
