### ISSUE TITLE
[Bug]: doc_ids parameter of VectorIndexRetriever being absolutely ignored

### ISSUE THREAD

**Issue by Julynx** [run-llama/llama_index#11602]
## TL;DR

The ids of the documents returned by retriever.retrieve() do not belong to 'doc_ids'.
In the docs for VectorIndexRetriever it clearly says:

```
doc_ids (Optional[List[str]]) – list of documents to constrain search.
```

Yet the search is not being constrained to the documents with ids that belong to 'doc_ids', but the entire index is being searched instead

### Version

0.9.45.post1 (I was able to replicate on 0.10.15 as well)

## To reproduce

Consider the following code:

```python

    considered_ids = [doc_id for doc_id, _ in considered_docs]

    retriever = VectorIndexRetriever(
        index,
        similarity_top_k=k,
        doc_ids=considered_ids
    )
    
    documents = retriever.retrieve(query)

    retrieved_ids = [node_with_score.node_id for node_with_score in documents]

    not_matching = [doc_id for doc_id in retrieved_ids
                    if doc_id not in considered_ids]

    print("DEBUG: NOT MATCHING IDS")
    print(not_matching)
```

## Output

```
DEBUG: NOT MATCHING IDS
['81c343b6-0962-499c-b338-b87d301fea89', '1cbd5aa5-b480-4ae0-a440-18af32fefe94', '807760b7-9c44-4d8f-bbde-1c9e1691b72f']
```

## Expected (All ids from result belong to doc_ids)

```
DEBUG: NOT MATCHING IDS
[]
```

**Comment by Julynx** [comment]
To answer the bot. The VectorIndexRetriever documentation clearly includes a 'doc_ids' parameter documented as follows:

```
doc_ids (Optional[List[str]]) – list of documents to constrain search.
```

**Comment by logan-markewich** [comment]
what vector db are you using? Tbh it probably depends on that.

**Comment by Julynx** [comment]
> what vector db are you using? Tbh it probably depends on that.

I'm using GPTVectorStoreIndex

**Comment by Julynx** [comment]
In case this type of "filtering" is only supported by some indexes, I'd strongly suggest indicating this in the documentation. 

Though maybe it's already there and I missed it.

Id also appreciate it if you were able to point me to a way to do any kind of "filtering" with retrievers using this particular index (GPTVectorStoreIndex), as MetadataFilters are also not working at all for me :(

**Comment by logan-markewich** [comment]
`VectorStoreIndex` (the actual name) is a wrapper around any vector db.

Pick a vector db that supports filtering.
https://docs.llamaindex.ai/en/stable/module_guides/storing/vector_stores.html#vector-store-options-feature-support

Here's a few examples.
https://docs.llamaindex.ai/en/stable/examples/vector_stores/WeaviateIndexDemo.html#metadata-filtering

https://docs.llamaindex.ai/en/stable/examples/vector_stores/pinecone_metadata_filter.html

https://docs.llamaindex.ai/en/stable/examples/vector_stores/chroma_metadata_filter.html#multiple-exact-match-metadata-filters
