### ISSUE TITLE
[Question]: Table relationship problem

### ISSUE THREAD

**Issue by acamenhas** [run-llama/llama_index#11605]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I have 2 simple tables:

bookings = Table(
    "bookings",
    metadata_obj,
    Column("number", Integer, primary_key=True),
    Column("date", Date, nullable=False),
    Column("state_id", Integer, ForeignKey("states.state_id"), nullable=False),
)

states = Table(
    "states",
    metadata_obj,
    Column("state_id", Integer, primary_key=True),
    Column("state", String(16), nullable=False),
)

In the states table I only have 2 states: 
1 - finished
2- canceled

When I ask the question "Total of canceled bookings?" it returns the query "SELECT COUNT(*) FROM bookings WHERE state_id = 3", where did it find state_id = 3??

**Comment by logan-markewich** [comment]
@acamenhas it probably hallucinated it, this can happen, especially for open source LLMs
