### ISSUE TITLE
[Feature Request]: Trying to fetch paragraph number from which the answer is generating, but unable to get the desired result.

### ISSUE THREAD

**Issue by dhruvaditya** [run-llama/llama_index#11610]
### Feature Description

Working on Intelligent Document Finder, where i was fetching multiple types of data directly from google drive by Google Drive API by using loader=GoogleDriveReader()
Trying to fetch meta data related to the answer generated by the LLM, 
Successfully fetched filename, page number , author name, but unable to get the paragraph number, like from where the answer is generating. A kind of number of similar paragraph where the answer can be found in the specific page for multiple types of files like PPT, PDF, Word, etc.

### Reason

Meta data extraction method is capable of extracting multiple details of a file but calculating the paragraph number is something that i found missing in the documentation;

### Value of Feature

It will help user to perfectly figure out from where the answer is generating in order to get better understanding of the files.

**Comment by logan-markewich** [comment]
This isn't really possible entirely -- youd need to label/extract paragraphs in the document loading phase, which isn't always an easy task. Furthermore, you'd need to make a node for paragraph, which also removes a lot of surrounding context.

Probably your best bet is using some fuzzy matching
For example: https://llamahub.ai/l/llama-packs/llama-index-packs-fuzzy-citation?from=

The readme is ever so slightly out of date

Should be
```
from llama_index.core import Document, VectorStoreIndex
from llama_index.core.llama_pack import download_llama_pack
```
