### ISSUE TITLE
[Bug]: While embedding chunks with metadata, the text content along with metadata is embedded

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#11619]
### Bug Description

After preparing data with documents = [Document(text=t['text'],metadata=t['metadata']) for t in data_list],
the understanding is only text should be sent as payload for embedding generation for indexing.
But observed that along with text all the metadata too is being sent for embedding creation.
This is happening because in the llama_index/indices/utils.py we have a embed_node() function texts_to_embed.append(node.get_content(metadata_mode=MetadataMode.EMBED)) is set to **EMBED** instead of **NONE**.
This is getting all text content+metadata which should not be the case ideally. Function for reference below:

def embed_nodes(
    nodes: Sequence[BaseNode], embed_model: BaseEmbedding, show_progress: bool = False
) -> Dict[str, List[float]]:
    """Get embeddings of the given nodes, run embedding model if necessary.

    Args:
        nodes (Sequence[BaseNode]): The nodes to embed.
        embed_model (BaseEmbedding): The embedding model to use.
        show_progress (bool): Whether to show progress bar.

    Returns:
        Dict[str, List[float]]: A map from node id to embedding.
    """
    id_to_embed_map: Dict[str, List[float]] = {}

    texts_to_embed = []
    ids_to_embed = []
    for node in nodes:
        if node.embedding is None:
            ids_to_embed.append(node.node_id)
            **texts_to_embed.append(node.get_content(metadata_mode=MetadataMode.EMBED))**
        else:
            id_to_embed_map[node.node_id] = node.embedding

    new_embeddings = embed_model.get_text_embedding_batch(
        texts_to_embed, show_progress=show_progress
    )

    for new_id, text_embedding in zip(ids_to_embed, new_embeddings):
        id_to_embed_map[new_id] = text_embedding

    return id_to_embed_map

Can we fix this or have an parameter for get_content() to be set by user?

### Version

0.9.47

### Steps to Reproduce

set this to EMBED and then NONE to see the difference sent as payload for embedding.
texts_to_embed.append(node.get_content(metadata_mode=MetadataMode.EMBED))

### Relevant Logs/Tracbacks

```shell
NA
```

**Comment by logan-markewich** [comment]
@amitguptadumka this is not a bug. You can control what gets embedded on input documents

```python
document.excluded_embed_metadata_keys = ["key1", ...]
document.excluded_llm_metadata_keys = ["key1", ...]
```

https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents.html#advanced-metadata-customization
