### ISSUE TITLE
[Bug]: ChatAgent: Initial token count exceeds token limit error

### ISSUE THREAD

**Issue by Gianlucq** [run-llama/llama_index#11637]
### Bug Description

An error consistently arises in the chat/stream method whit this error:

    File"/usr/local/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 197, in stream_chat
    all_messages = prefix_messages + self._memory.get(
                                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 88, in get
    raise ValueError("Initial token count exceeds token limit")
ValueError: Initial token count exceeds token limit

### Version

0.10.15

### Steps to Reproduce

We create, following your page documentation, a chat engine with chat_mode='context' a system_prompt and token_limit for ChatMemoryBuffer sets to 3000. As model we use gpt4-32k with Azure OpenAI (AzureChatOpenAI class of langchain)

### Relevant Logs/Tracbacks

```shell
File"/usr/local/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 197, in stream_chat
    all_messages = prefix_messages + self._memory.get(
                                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 88, in get
    raise ValueError("Initial token count exceeds token limit")
ValueError: Initial token count exceeds token limit
```

**Comment by logan-markewich** [comment]
This means your chat engine retrieved more context than is available to fit in the buffer.

You probably want to set the token limit closer to 32k if you are using a 32k model.

Either that, or you need to decrease the top-k or chunk size

**Comment by Gianlucq** [comment]
Hi Logan, is what I did at the end.
