### ISSUE TITLE
[Question]:  The error with Joint QA Summary Query Engine

### ISSUE THREAD

**Issue by Gzj369** [run-llama/llama_index#11647]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I use the Joint QA Summary Query [Engine]((https://docs.llamaindex.ai/en/stable/examples/query_engine/JointQASummary.html),  with the LLM( Qwen-72B-Chat , not gpt-4),    **llama-index version 0.10.15**

My code as bellow:
```Python
from llama_index.core.composability import QASummaryQueryEngineBuilder
from llama_index.core import SimpleDirectoryReader
from llama_index.llms.openai import OpenAI
from langchain_community.embeddings import (
    HuggingFaceBgeEmbeddings,
    HuggingFaceEmbeddings,
)

class MyEmbeddings(HuggingFaceEmbeddings):
    def __init__(self, **kwargs: Any):
        super().__init__(**kwargs)
    xxx ... 

_hf = MyEmbeddings(
        model_name=M3E_BASE_PATH, 
        model_kwargs={'device': 'cuda'},
        encode_kwargs={'normalize_embeddings': True} 
    )
client = OpenAI(
        # This is the default and can be omitted
        base_url=os.environ.get("OPENAI_API_BASE"),
        api_key=os.environ.get("OPENAI_API_KEY"),
        temperature=0,
        embeddings=_hf
    )

query_engine_builder = QASummaryQueryEngineBuilder(
    llm=client,
)

print("-------------21")
start_time01 = time.time()
reader = SimpleDirectoryReader(source_doc_path)
documents = reader.load_data()


query_engine = query_engine_builder.build_from_documents(documents)
end_time01 = time.time()
execution_time01 = (end_time01 - start_time01) / 60.0
print("execution_time01: ", execution_time01, "min")
print("-------------22")
```

the error is as bellow:
![image](https://github.com/run-llama/llama_index/assets/13391430/36513f7f-b7c0-44c2-948e-19e34417c473)

Please help me

**Comment by logan-markewich** [comment]
I think you have not set things up correctly

You will need the langchain wrapper if you want to use langchain embeddings
```
pip install llama-index-embeddings-langchain
```

```
from llama_index.core import Settings
from llama_index.embeddings.langchain import LangchainEmbedding

Settings.embed_model = LangchainEmbedding(_hf)
Settings.llm = OpenAI( 
        base_url=os.environ.get("OPENAI_API_BASE"),
        api_key=os.environ.get("OPENAI_API_KEY"),
        temperature=0,
)
```

And that's it, this will set these two as the global default

**Comment by Gzj369** [comment]
> I think you have not set things up correctly
> 
> You will need the langchain wrapper if you want to use langchain embeddings
> 
> ```
> pip install llama-index-embeddings-langchain
> ```
> 
> ```
> from llama_index.core import Settings
> from llama_index.embeddings.langchain import LangchainEmbedding
> 
> Settings.embed_model = LangchainEmbedding(_hf)
> Settings.llm = OpenAI( 
>         base_url=os.environ.get("OPENAI_API_BASE"),
>         api_key=os.environ.get("OPENAI_API_KEY"),
>         temperature=0,
> )
> ```
> 
> And that's it, this will set these two as the global default

Ok, Thank you very much !
