### ISSUE TITLE
[Bug]: OpenAIAgent chat_history inaccurate in STREAM mode

### ISSUE THREAD

**Issue by jeremielenoir** [run-llama/llama_index#11646]
### Bug Description

Hello there, I'm attempting to use the OpenAIAgent in STREAM mode. However, when I invoke the stream_chat function and the response completes, the chat_history isn't populated correctly. Messages designated with the assistant role are not being included in the ChatHistory. This omission results in an inaccurate list of ChatMessages, containing only user role messages without any from the assistant role.
Furthermore, it appears that using the tools in STREAM MODE also leads to a corrupted chat history, lacking assistant role messages except for tool_call.

### Version

0.10.15

### Steps to Reproduce

To reproduce the issue, execute agent.stream_chat at least twice and observe the chat_history:

```python

while True:
    text_input = input("User: ")
    if text_input == "exit":
        break

    response = openai_agent.stream_chat(text_input)
    response_gen = response.response_gen
    #print chat_history to look the innacurate chat_history
    print(openai_agent.chat_history)
    for token in response_gen:
        print(token, end="")
```
This should help in diagnosing the problem with missing assistant messages in the chat history."

### Relevant Logs/Tracbacks
For example below the chat_history after 2 calls of stream_chat, there is no assistant message !!! :
[ChatMessage(role=<MessageRole.USER: 'user'>, content='Hello', additional_kwargs={}), ChatMessage(role=<MessageRole.USER: 'user'>, content='Est-tu spécialiste en droit ?', additional_kwargs={})]
_No response_

**Comment by jeremielenoir** [comment]
@logan-markewich i have investigating, a solution may be add a "_new_item_thread_event" like as async astream_chat function. And waiting event for add chat assistant message to memory.

**Comment by logan-markewich** [comment]
@jeremielenoir I think I nearly have a fix actually. The main cause is that agents have two memories, and they need to get merged properly when streaming a response

**Comment by jeremielenoir** [comment]
Thanks @logan-markewich i did a fix locally yesterday similar to your PR fix ;-) I'm investigating trough another bug this morning, sometimes a completion from agent with tool call not continue after first LLM response. I'll write a new detailled issue
