### ISSUE TITLE
[Question]: ModuleNotFoundError: No module named 'llama_index.core'

### ISSUE THREAD

**Issue by Vishu611** [run-llama/llama_index#11650]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been using llama index for quite a while, when i tried to load my environment today i get the error. I have the lastest verion v0.10.15

ModuleNotFoundError: No module named 'llama_index.core'

I tried to downgrade the version , still get the same error.

**Comment by logan-markewich** [comment]
@Vishu611 Seems your env is a tad corrupted, v0.10.x had some major changes, any remnants of a previous install in your env will cause issues.

Start with a fresh venv. In a new terminal
```
pip uninstall llama-index  # remove any global
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by Vishu611** [comment]
@logan-markewich , Thanks this worked now! Not sure why it failed when i did the exact same thing the last time.
I was also wondering can we use the llama index cli  like below on the .ipynb files? :

llamaindex-cli upgrade-file <file_path>

**Comment by kkiwas** [comment]
I am getting this 'ModuleNotFoundError' when using the code ´from llama_index.output_parsers.guardrails import GuardrailsOutputParser´

ModuleNotFoundError: No module named 'llama_index.output_parsers'
