### ISSUE TITLE
IndexError in _extract_rel_text_keywords method of KGTableRetriever class

### ISSUE THREAD

**Issue by smanna123** [run-llama/llama_index#11651]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am building RAG q&a bot using knowledge-graph (nebula graph) , while asking some valid question I am getiing answer but when i am some other question, i am getting below error
 keywords = self._extract_rel_text_keywords(
  File "/Users/sayantanmanna/Desktop/knowledge_graph_retriever/venv/lib/python3.10/site-packages/llama_index/core/indices/knowledge_graph/retrievers.py", line 177, in _extract_rel_text_keywords
    keyword = rel_text.split(",")[2]
IndexError: list index out of range
 
 Also I am providing whole script----
 import os
from dotenv import load_dotenv
from llama_index.core import PromptTemplate, load_index_from_storage, KnowledgeGraphIndex, QueryBundle, \
    get_response_synthesizer
from llama_index.core import (
    StorageContext,
    SimpleDirectoryReader
)
from llama_index.llms.openai import OpenAI
from llama_index.core.query_engine import RetrieverQueryEngine
import chainlit as cl
from llama_index.graph_stores.nebula import NebulaGraphStore

load_dotenv()
openai_api_key = os.getenv("OPENAI_API_KEY")
os.environ["NEBULA_USER"] = "root"
os.environ["NEBULA_PASSWORD"] = "nebula"  # default is "nebula"
os.environ[
    "NEBULA_ADDRESS"
] = "127.0.0.1:9669"  # assumed we have NebulaGraph installed locally

space_name = "llamaindex"
edge_types, rel_prop_names = ["relationship"], [
    "relationship"
]  # default, could be omit if create from an empty kg
tags = ["entity"]

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)

PERSIST_DIR = "./storage"

documents = SimpleDirectoryReader("data").load_data()
llm = OpenAI(model="gpt-3.5-turbo")

new_text_qa_tmpl_str = (
    "You are a marine q&a bot, please start answer with Hi or hello"
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information and not prior knowledge, don't answer anything outside the context or marine "
    "industry\n"
    "answer should be contain the point number and also mention reference number and reference pdf names in the "
    "answer\n"
    "Answer should be proper explanation type, include values if possible and constructive answer not generalize.\n"
    "Also include the important keywords and point no from the context in the answer\n"
    "Context information should be included in answer"
    "Query: {query_str}\n"
    "Answer: "
)

new_text_qa_tmpl = PromptTemplate(new_text_qa_tmpl_str)

if not os.path.exists(PERSIST_DIR):

    storage_context_kg = StorageContext.from_defaults(graph_store=graph_store)
    kg_index = KnowledgeGraphIndex.from_documents(
        documents,
        storage_context=storage_context_kg,
        max_triplets_per_chunk=5,
        space_name=space_name,
        edge_types=edge_types,
        rel_prop_names=rel_prop_names,
        tags=tags,
        include_embeddings=True,
    )
    kg_index.storage_context.persist(persist_dir='./storage')
else:

    storage_context_kg = StorageContext.from_defaults(persist_dir='./storage', graph_store=graph_store)
    kg_index = load_index_from_storage(
        storage_context=storage_context_kg,
        max_triplets_per_chunk=5,
        space_name=space_name,
        edge_types=edge_types,
        rel_prop_names=rel_prop_names,
        tags=tags,
        include_embeddings=True,
    )

response_synthesizer = get_response_synthesizer(
    streaming=True
)

graph_rag_retriever = kg_index.as_retriever(similarity_top_k=5)

@cl.on_chat_start
def on_chat_start():
    query_engine = RetrieverQueryEngine.from_args(
        retriever=graph_rag_retriever,
        include_text=True,
        # response_mode="tree_summarize",
        embedding_mode="hybrid",
        explore_global_knowledge=True,
        streaming=True
    )
    query_engine.update_prompts(
        {'response_synthesizer:text_qa_template': new_text_qa_tmpl}
    )

    cl.user_session.set("query_engine", query_engine)

@cl.on_message
async def main(message: cl.Message):
    print("message received")
    query_engine = cl.user_session.get("query_engine")  # type: RetrieverQueryEngine
    response = await cl.make_async(query_engine.query)(message.content)

    response_message = cl.Message(content="")
    ans = ""
    for token in response.response_gen:
        ans += token
        await response_message.stream_token(token=token)

    if response.response_txt:
        response_message.content = response.response_txt

    await response_message.send()

Could you please help in this issue.

**Comment by smanna123** [comment]
so this file retrivers.py belongs to llama_index knowledge_graph, so I is this is a bug?
below is the path
venv/lib/python3.10/site-packages/llama_index/core/indices/knowledge_graph/retrievers.py",

**Comment by younfor** [comment]
pull the master again,  i I added index defense。
But there is still a lot to optimize here, different storages have different formats

**Comment by maqy1995** [comment]
this issue has the same problem:https://github.com/run-llama/llama_index/issues/11693 
and this pr may fix it: https://github.com/run-llama/llama_index/pull/11695
