### ISSUE TITLE
[Bug]: Issue with EmptyIndex and streaming.

### ISSUE THREAD

**Issue by felipearosr** [run-llama/llama_index#11680]
### Bug Description

Im trying to create a simple Intent Detection agent, the basic expected functionality is to select between to queryengines with RouterQueryEngine, one q_engine with an emptyindex, the idea of this one is to have the llm answer directly questions that are not related to the data, and another one with a vector_index. This is just to decrease cost and improve latency for basic responses that dont require going into the vectordb.

The router is working correctly, when the vector_query_engine is selected is working correctly too. Only problem arises when it selects the empty_query_engine.

It gives me the following error:
`'AttributeError: 'Response' object has no attribute 'response_gen'`

Streaming is set to true:
```python
empty_index = EmptyIndex()

simple_query_engine = empty_index.as_query_engine(
  streaming=True,
)
```

This query_engines was also tested with the pinecone index and it worked correctly. So i believe is a problem with EmptyIndex().

If you print the response it gives me `Empty Response`

### Version

0.10.16

### Steps to Reproduce

1.Create an EmptyIndex()
2.Create a query_engine with this empty index.
3.Stream the response.

**Comment by logan-markewich** [comment]
@felipearosr the empty index is a tad deprecated I guess?

It returns zero nodes (since its empty) and then if zero nodes are returned, `Empty Response` Is returned by the synthesizer
https://github.com/run-llama/llama_index/blob/22dd78247e6bd8aa4e4d239bb58864d7492d8f24/llama-index-core/llama_index/core/response_synthesizers/base.py#L179

Even if this check wasn't there, the prompts for the synthesizer don't make sense without context from nodes.

probably I would just make a custom query engine to wrap an LLM call, to have more control over whats going on

```python
from llama_index.core.query_engine import CustomQueryEngine
from llama_index.llms.openai import OpenAI


prompt = "Given the user query, respond as best as possible.\nQuery: {query}"

class MyQueryEngine(CustomQueryEngine):
    """My Query Engine."""

    llm: OpenAI
    prompt: str

    def custom_query(self, query_str: str):
        llm_prompt = self.prompt.format(query=query_str)
        llm_response = llm.complete(llm_prompt)
        return str(llm_response)
        

query_engine = MyQueryEngine(llm=OpenAI(), prompt=prompt)
response = query_engine.query("Hello!")
print(str(response))
```

https://docs.llamaindex.ai/en/stable/examples/query_engine/custom_query_engine.html#defining-a-custom-query-engine

**Comment by felipearosr** [comment]
Hi, thank you for your reply, how can i stream the response of this, also im getting the following error with the following implementation of the code: 

```python
class LlmQueryEngine(CustomQueryEngine):
    """Custom query engine for direct calls to the LLM model."""
    llm: OpenAI
    prompt: str

    def custom_query(self, query_str: str):
        llm_prompt = self.prompt.format(query=query_str)
        llm_response = self.llm.complete(llm_prompt, formatted=True)
        return llm_response
```

I get the following error on the RouterQueryEngine, any help would be greatly appreciated.

**Comment by logan-markewich** [comment]
@felipearosr For non-streaming, you should cast the response as a string. Otherwise, you can use the below to stream

```python
from llama_index.core.base.response.schema import StreamingResponse

class LlmQueryEngine(CustomQueryEngine):
    """Custom query engine for direct calls to the LLM model."""
    llm: OpenAI
    prompt: str

    def custom_query(self, query_str: str):
        llm_prompt = self.prompt.format(query=query_str)
        llm_response = self.llm.stream_complete(llm_prompt, formatted=True)
        
        def response_gen(llm_response):
            for r in llm_response:
                yield str(r)
        return StreamingResponse(response_gen=response_gen(llm_response))
```
