### ISSUE TITLE
[Question]: ImportError: cannot import name 'PDFReader' from 'llama_index.core.readers.file

### ISSUE THREAD

**Issue by MaxiRadomski** [run-llama/llama_index#11681]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a code where i Import from llama_index.core.readers.file import PDFReader

But i get all the time this error
Traceback (most recent call last):
  File "c:\Users\kachi\OneDrive\RAGTESTVS\PythonAgentAI\pdf.py", line 3, in <module>
    from llama_index.core.readers.file.base import PDFReader
ImportError: cannot import name 'PDFReader' from 'llama_index.core.readers.file' (C:\Users\kachi\AppData\Roaming\Python\Python312\site-packages\llama_index\core\readers\file\base.py)  

How can i fix this error?

**Comment by logan-markewich** [comment]
That is not the correct import 

Ensure you have the package
`pip install llama-index-readers-file`

`from llama_index.readers.file import PDFReader`

**Comment by MaxiRadomski** [comment]
> That is not the correct import
> 
> Ensure you have the package `pip install llama-index-readers-file`
> 
> `from llama_index.readers.file import PDFReader`


i have tried this already it is still an import Error

**Comment by logan-markewich** [comment]
@MaxiRadomski then create a fresh venv

In a new terminal 

```
pip uninstall llama-index  # remove any global install
python -m venv venv
source venv/bin/activate
pip install llama-index

# test
python -c "from llama_index.readers.file import PDFReader`
```
