### ISSUE TITLE
[Bug]: cannot download RaptorPack via llamaindex-cli and download_llama_pack

### ISSUE THREAD

**Issue by kun432** [run-llama/llama_index#11689]
### Bug Description

Trying RAPTOR notebook on Google Colab. I need to customize RaptorPack source and translate the summary prompt into  Japanese. so, I want to download the pack, not installing via pip.

Tried via `llamaindex-cli` first.

```
!llamaindex-cli download-llamapack RaptorPack --download-dir ./raptor_pack
```

Also, tried via `download_llama_pack`.

```
from llama_index.core.llama_pack import download_llama_pack

RaptorPack = download_llama_pack("RaptorPack", "./raptor_pack", refresh_cache=False)
```

both failed. Please see logs below.

### Version

llama-index-core-0.10.16.post1, llama-index-cli-0.1.7

### Steps to Reproduce

```
!pip install llama-index
```

then

```
!llamaindex-cli download-llamapack RaptorPack --download-dir ./raptor_pack
```

or 

```
from llama_index.core.llama_pack import download_llama_pack

RaptorPack = download_llama_pack("RaptorPack", "./raptor_pack", refresh_cache=False)
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/usr/local/bin/llamaindex-cli", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 269, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 180, in <lambda>
    func=lambda args: handle_download_llama_pack(**vars(args))
  File "/usr/local/lib/python3.10/dist-packages/llama_index/cli/command_line.py", line 39, in handle_download_llama_pack
    download_llama_pack(
  File "/usr/local/lib/python3.10/dist-packages/llama_index/core/llama_pack/download.py", line 47, in download_llama_pack
    raise ValueError(f"Failed to find python package for class {llama_pack_class}")
ValueError: Failed to find python package for class RaptorPack
```

**Comment by kun432** [comment]
> The RaptorPack class does not exist in the Llama Hub. Please ensure that the class name is spelled correctly and that it exists in the Llama Hub.

RaptorPack is here:
https://llamahub.ai/l/llama-packs/llama-index-packs-raptor
https://github.com/run-llama/llama_index/tree/main/llama-index-packs/llama-index-packs-raptor

> The download_llama_pack function checks if the downloaded class is a subclass of BaseLlamaPack. If RaptorPack is not a subclass of BaseLlamaPack, the function will raise a ValueError.

RaptorPack is a subclass of BaseLlamaPack:
https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/llama_index/packs/raptor/base.py#L328

>However, this fix was applied on February 22, 2024, and you're using llama-index-core-0.10.16.post1, which might not include this fix. Could you please confirm the date when you installed the llama-index-core package? If it was before February 22, 2024, I recommend updating the package and trying again.

v0.10.16 has been released 18 hours ago and I tested just before now. That fix should be included.
https://github.com/run-llama/llama_index/releases/tag/v0.10.16

**Comment by nerdai** [comment]
Hi @kun432,

Sorry about the trouble with this. Unfortunately there is a reliance on `mappings.json` that acts as a registry for which `download_llama_pack` and cli installs depend on. This `mappings.json` has not been updated yet to include the new RAPTOR pack.

Will update and submit a fix very soon.
