### ISSUE TITLE
Embeddings using Huggingface InferenceClient

### ISSUE THREAD

**Issue by ss2342** [run-llama/llama_index#11683]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there any support for using the `InferenceClient` for a hosted embedding model. I did look into the `HuggingfaceInferenceAPIEmbeddings` but seems like I have to specify a `model_name` there. 

This is how I generate embeddings currently with my `InferenceClient`

```python
from huggingface_hub import InferenceClient

client = InferenceClient("<hosted_embedding_url>")

embeddings = client.feature_extraction("Testing")
```

**Comment by logan-markewich** [comment]
@ss2342 looking at the source code for the class, and for the `InferenceClient`, I think "model" in this case can also be the URL (The `InferenceClient` doesn't list a URL option in its args, but the model is the first kwarg, so in your example you are passing in the URL as the model)

Can you give that a shot?
