### ISSUE TITLE
Display source node

### ISSUE THREAD

**Issue by polux0** [run-llama/llama_index#11690]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

From documentation: 

https://docs.llamaindex.ai/en/stable/examples/retrievers/recursive_retriever_nodes.html

### Baseline Retriever
  Define a baseline retriever that simply fetches the top-k raw text nodes by embedding similarity.
  
```
  base_index = VectorStoreIndex(base_nodes, embed_model=embed_model)
  base_retriever = base_index.as_retriever(similarity_top_k=2)
  retrievals = base_retriever.retrieve(
      "Can you tell me about the key concepts for safety finetuning"
  )
  for n in retrievals:
      display_source_node(n, source_length=1500)
```
      
   display_source_node currently outputs: 
    
```
    <IPython.core.display.Markdown object>
    <IPython.core.display.Markdown object>
```

The proposal is to change: 

`display(Markdown(text_md))` from `lama_index/core/response/notebook_utils.py`, line 69 to  `display(Markdown(text_md).data)` 

To get results as expected from the documentation. 

Apologies if this issue is not properly formatted.

**Comment by logan-markewich** [comment]
@polux0 this displays fine in google colab and in my vscode notebook?

(This function is only meant to be used in a notebook btw)

Proof it works fine in a notebook:
https://colab.research.google.com/drive/1jZO88bNPO-ezyOFYQE7V-6plzMUgtMhj?usp=sharing

**Comment by polux0** [comment]
@logan-markewich I was not aware that it was imagined to run in google colab / vscode notebook, apologies. I was running it locally and then changing

```display(Markdown(text_md))```  to ``` display(Markdown(text_md).data)```` returned correct result like: 

**Node ID:** node-7<br>**Similarity:** 0.8682621684107112<br>**Text:** Any core societal information system can be viewed at a high-level as a set of four primary conceptual sub-systems, 
the social, the decision, the material, and the lifestyle.

Maybe `display_source_node` could be rewritten so it becomes environment aware?

**Comment by logan-markewich** [comment]
Maybe? The import is also under `notebook_utils` tho too
