### ISSUE TITLE
LlamaCPP 

### ISSUE THREAD

**Issue by elliotthwang** [run-llama/llama_index#11692]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

# create vector store index
index = VectorStoreIndex.from_documents(documents, embed_model=embed_model)
Token indices sequence length is longer than the specified maximum sequence length for this model (14853 > 2048). Running this sequence through the model will result in indexing errors

**Comment by elliotthwang** [comment]
Adopting legacy service_context, no text spliter is needed.

index = VectorStoreIndex.from_vector_store(
    vector_store,
    service_context=service_context,
)

**Comment by logan-markewich** [comment]
@elliotthwang what embedding model are you using? I would just pass in the splitter there. This also isn't an error, just more-so a warning that it is putting a large sequence through a tokenizer (and will likely get truncated)

```
# you can use one of these
from llama_index.core.node_parser import SentenceSplitter, TokenTextSplitter

index = VectorStoreIndex.from_documents(...., transformations=[TokenTextSplitter(chunk_size=512, chunk_overlap=20)])
```

**Comment by elliotthwang** [comment]
@logan-markewich 
Following your instructions, still got indexing error messages!

from llama_index.core.node_parser import SentenceSplitter, TokenTextSplitter

index = VectorStoreIndex.from_documents(documents, embed_model=embed_model, transformations=[TokenTextSplitter(chunk_size=512, chunk_overlap=20)])
Token indices sequence length is longer than the specified maximum sequence length for this model (14853 > 2048). Running this sequence through the model will result in indexing errors

**Comment by logan-markewich** [comment]
Yea that's not an error though, just that it's counting a large sequence. That happens at times, it's safe to ignore

**Comment by elliotthwang** [comment]
@logan-markewich 
Ignored "Running this sequence through the model will result in indexing errors"

# set up query engine
query_engine = index.as_query_engine(llm=llm,streaming=True)

response = query_engine.query("金蘭醬油")
print(response)

Llama.generate: prefix-match hit

llama_print_timings:        load time =   48839.33 ms
llama_print_timings:      sample time =      48.44 ms /    57 runs   (    0.85 ms per token,  1176.81 tokens per second)
llama_print_timings: prompt eval time =  282544.74 ms /   540 tokens (  523.23 ms per token,     1.91 tokens per second)
llama_print_timings:        eval time =   53513.89 ms /    56 runs   (  955.61 ms per token,     1.05 tokens per second)
llama_print_timings:       total time =  336429.54 ms /   596 tokens
 金蘭醬油是一種由金蘭獨家釀造的醬油，其醬香濃郁，味道鮮甜。[/INST]

 load time =   48839.33 ms

**Comment by elliotthwang** [comment]
@logan-markewich 
adopted legacy service_context
query_str ="金蘭醬油"

Llama.generate: prefix-match hit
 好優米的小麥與澳洲海鹽一同恆溫發酵，豆麥香氣十足，擁有特有濃郁的厚勁，蒸煮炒
llama_print_timings:        load time =     440.50 ms
llama_print_timings:      sample time =      83.53 ms /   100 runs   (    0.84 ms per token,  1197.19 tokens per second)
llama_print_timings: prompt eval time =     148.09 ms /    37 tokens (    4.00 ms per token,   249.85 tokens per second)
llama_print_timings:        eval time =    1629.66 ms /    99 runs   (   16.46 ms per token,    60.75 tokens per second)
llama_print_timings:       total time =    2330.94 ms /   136 tokens
