### ISSUE TITLE
[Feature Request]: Return agents thoughts and observations as part of chat response

### ISSUE THREAD

**Issue by augchan42** [run-llama/llama_index#11705]
### Feature Description

Currently ReActAgent outputs thoughts and observations to the server console output only.  Only the final response is returned in the chat response.

### Reason

For some use-cases it's helpful to see the thoughts and observations, especially for checking model coherence

### Value of Feature

It's valuable as it can improve user experience when interacting with agents

**Comment by zhi-x21** [comment]
Any update on this?
