### ISSUE TITLE
[Bug]: OpenAIAgent function not called in stream mode after a tools_call type response

### ISSUE THREAD

**Issue by jeremielenoir** [run-llama/llama_index#11708]
### Bug Description

On multiple occasions, when the agent executes a chat completion that may include responses with tool calls, the process fails to invoke functions if the response returns a JSON indicating that functions should be called.
After investigating, I've discovered that sometimes, depending on the model used, OpenAI returns an initial blank delta. The issue arises when this blank delta triggers the "_is_function_not_none_thread_event", allowing the code to continue executing and provide a response through the generator without waiting for the thread to complete execution before executing the function.
A way to fix (maybe is a hack) is to add this condition in StreamingAgentChatResponse -> write_response_to_history method the following line 

```python
for chat in self.chat_stream:
self._is_function = is_function(chat.message)
 #condition to add
      if chat.delta != "": 
              self.put_in_queue(chat.delta)
      final_text += chat.delta or ""
```

### Version

0.10.16

### Steps to Reproduce

```python
agent: OpenAIAgent = OpenAIAgent.from_tools(
    tools=tools, llm=llm, verbose=False, system_prompt=FRENCH_LEGAL_ADVICE_ASSISTANT_WITH_FUNCTION_CALLS
)
while True:
    text_input = input("User: ")
    if text_input == "exit":
        break
    
    response: StreamingAgentChatResponse = agent.stream_chat(text_input)
    response_gen = response.response_gen
 
    #message_assistant_content
    for token in response_gen:
        print(token, end="")
```

@logan-markewich If my fix seems appropriate, I'll proceed with creating a pull request to address the issue ;-)"

**Comment by logan-markewich** [comment]
@jeremielenoir ah yea that's a good catch. I'm fine with this proposed fix (would just need it for both sync and async versions)

**Comment by jeremielenoir** [comment]
Bien sûr, i'll make the pull request.

**Comment by jeremielenoir** [comment]
#11713
