### ISSUE TITLE
[Bug]: SimpleDirectoryReader with Remote s3 file system: "ValueError: {s3 bucket name/directory/file_name} is not in the subpath of {as if local fs} OR one path is relative and the other is absolute.

### ISSUE THREAD

**Issue by chrismaresca-scalinglabs** [run-llama/llama_index#11715]
### Bug Description

When attempting to use an s3 remote fs with "SimpleDirectoryReader"...error unless I manually set 'skip_because_hidden' to False. Get following error: "ValueError: {s3 bucket name/directory/file_name} is not in the subpath of {as if local fs} OR one path is relative and the other is absolute."

Where:
-  {s3 bucket name/directory/file_name} is the path to the file in my s3 bucket, starting at bucket_name
-  {as if local fs} is as if I wanted to append {s3 bucket name/directory/file_name} to my current working directory

Fixed by manually setting "skip_because_hidden" to False. Not sure what I did wrong. I also am using "input_dir" instead of "input_files"...because I passed in the directory of the files in my s3 bucket. For some reason there's a mix match...one part assuming I am using a local file system (or at least logging this way), and the other knowing I am using remote. 

### Version

0.10.16

### Steps to Reproduce

Step one: Create simple function to get s3 fs info and return your bucket_name and 'AbstractFileSystem':

def get_s3_info() -> Tuple[str, AbstractFileSystem]:
    """ returns the bucket name and file system needed for LlamaIndex """
    fs = s3fs.S3FileSystem(anon=False)
    bucket_name = bucket_name
    return bucket_name, fs

Step Two: Attempt to Load Documents 

def load_documents(directory_path: str, bucket_name: str = bucket_name, fs: AbstractFileSystem = s3_fs, filename_as_id: bool = True, num_files_limit=None, num_workers=1):

    # construct the input_directory
    input_dir = f"{bucket_name}/{directory_path}"

    # return the directory reader
    reader = SimpleDirectoryReader(input_dir=input_dir, filename_as_id=filename_as_id, num_files_limit=None, fs=fs)

    return reader.load_data(show_progress=True, num_workers=num_workers)

My bucket currently has 3 files: 1 pdf, 1 ppt, and 1 HTML (testing diff MIME types...do not think this would cause the error).

**Comment by sourabhdesai** [comment]
@chrismaresca-scalinglabs thanks for bringing this up - included a fix in my PR [here](https://github.com/run-llama/llama_index/pull/11665)

**Comment by sourabhdesai** [comment]
Merged the above PR to fix this issue. Will close for now, feel free to re-open if the issue persists.
