### ISSUE TITLE
[Question]: What is the difference between PDFReader and PyMuPDFReader

### ISSUE THREAD

**Issue by chansonzhang** [run-llama/llama_index#11729]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the difference between [PDFReader](https://github.com/run-llama/llama_index/blob/a3491cfdac7a8969ad1755f56c7980baedbbc70a/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py#L21)and [PyMuPDFReader](https://github.com/run-llama/llama_index/blob/a3491cfdac7a8969ad1755f56c7980baedbbc70a/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/pymu_pdf/base.py#L10)
- How do they differ in processing?
- Is there any performance comparison?

**Comment by logan-markewich** [comment]
Pdfreader uses pypdf

The other uses pymupdf

That's it :) I don't have a comparison, you can try them out yourself and compare.

LlamaParse also released recently, if you want to check that out 
https://github.com/run-llama/llama_parse
