### ISSUE TITLE
[Question]: use a custom elasticsearch query with llama-index Elasticsearch Vector Store

### ISSUE THREAD

**Issue by cctong-castiel** [run-llama/llama_index#11732]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I tried to use a custom elasticsearch query from ElasticSearch official website and integrate with the llama-index ElasticsearchStore class. It seems I can only use the default one provided by the llama-index. May I know if there is a way to use the below search query and retrieve the nodes in the elasticsearch vector store?

'''
{
            "query": {
                "bool": {
                    "should": [
                        {
                            "text_expansion": {
                                "plot_embedding": {
                                    "model_id": ".elser_model_2",
                                    "model_text": query_str,
                                    "boost": 1
                                }
                            }
                        },
                        {
                            "query_string": {
                                "query": query_str,
                                "boost": 4
                            }
                        }
                    ]
                }
            },
            "min_score": 20
        }
'''

**Comment by joemcelroy** [comment]
you can override the query via `custom_query`
https://docs.llamaindex.ai/en/stable/examples/vector_stores/ElasticsearchIndexDemo.html#custom-filters-and-overriding-query
