### ISSUE TITLE
[Bug]: Bedrock Integration with Claude3 fails

### ISSUE THREAD

**Issue by ayseozgun** [run-llama/llama_index#11739]
### Bug Description

I am trying to run Claude 3 sonnet model with llama index Bedrock. But the code is not running. Is Claude 3 not available yet on llama index? The code i am trying to run is  below:

`from llama_index.llms.bedrock import Bedrock

llm = Bedrock(model="anthropic.claude-3-sonnet-20240229-v1:0", client=bedrock_runtime)`

My env:
llama-index                              0.10.17
llama-index-agent-openai                 0.1.5
llama-index-cli                          0.1.8
llama-index-core                         0.10.17
llama-index-embeddings-openai            0.1.6
llama-index-indices-managed-llama-cloud  0.1.3
llama-index-legacy                       0.9.48
llama-index-llms-anthropic               0.1.5
llama-index-llms-bedrock                 0.1.3
llama-index-llms-openai                  0.1.7
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.4
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.8
llama-index-readers-llama-parse          0.1.3
llama-index-vector-stores-chroma         0.1.5
llama-index-vector-stores-postgres       0.1.2
llama-parse                              0.3.7
llamaindex-py-client                     0.1.13

Can you please help?
Thanks

### Version

0.10.17

### Steps to Reproduce

`from llama_index.llms.bedrock import Bedrock

llm = Bedrock(model="anthropic.claude-3-sonnet-20240229-v1:0", client=bedrock_runtime)`

**Comment by brycecf** [comment]
Same thing here.  I have a [PR ](https://github.com/run-llama/llama_index/pull/11663) open that will (hopefully) be merged soon to fix this.

**Comment by danielftapiar** [comment]
tried with the latest version `llama-index==0.10.20` but still doesn't work

**Comment by ayseozgun** [comment]
yes, same here.

**Comment by ayseozgun** [comment]
`ValueError: `context_size` argument not provided andmodel provided refers to a non-foundation model. Please specify the context_size
`

**Comment by Aniket-ByteIQ** [comment]
Did you find any fix for that? @ayseozgun

**Comment by ayseozgun** [comment]
no, could not solve @Aniket-ByteIQ

**Comment by Aniket-ByteIQ** [comment]
Hey @ayseozgun , It seems like you're using an older version of llama-index-llms-bedrock (0.1.3) and llama-index-llms-anthropic (0.1.5).
Try upgrading them to the newer version:
`pip install --upgrade llama-index-llms-bedrock==0.1.5`
`pip install --upgrade llama-index-llms-anthropic==0.1.7`
This version supports the use of Claude 3 models.
Hope it helps

**Comment by ayseozgun** [comment]
Should i specify context_size parameter? @Aniket-ByteIQ

**Comment by Aniket-ByteIQ** [comment]
> Should i specify context_size parameter? @Aniket-ByteIQ

Not necessary, it was just an example.
Let me know if it worked.

**Comment by Aniket-ByteIQ** [comment]
@ayseozgun This should work to work with Claude 3. Are you still facing issues to load the LLM? Can you show me the error which you're facing?

**Comment by brycecf** [comment]
This should be resolved now. I use Claude Sonnet regularly with LlamaIndex Bedrock.

@ayseozgun can you confirm please so this can be closed?

**Comment by jayanthma** [comment]
Hi @brycecf @ayseozgun @danielftapiar @Aniket-ByteIQ ,

I am getting the below error. Did any of you get the same error?
  File "C:\Users\Jay\coding_projects\RAG_AWS_Neptune\venv\Lib\site-packages\llama_index\llms\bedrock\utils.py", line 157, in get_request_body
    if len(prompt) > 0 and prompt[0]["role"] == "system":
                           ~~~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'


My code:
from llama_index.llms.bedrock import Bedrock
from llama_index.core.base.llms.types import ChatMessage

llm = Bedrock(model="anthropic.claude-3-sonnet-20240229-v1:0", region_name="ap-south-1")
messages = [
    ChatMessage(role="system", content="You are a pirate with a colorful personality"),
    ChatMessage(role="user", content="Tell me a story"),
]
response = llm.chat(messages=messages)

**Comment by Aniket-ByteIQ** [comment]
Hi @jayanthma , Sorry I didn't encounter this issue. Tried running the same code, no issues encountered.
Which version of llama-index are you using?
Mine: llama-index == 0.10.18

**Comment by nefarian-gaming** [comment]
I have same error with @jayanthma. Using 0.2.0 Bedrock.

**Comment by rkrishna116** [comment]
@jayanthma I'm encountering the same error

**Comment by nefarian-gaming** [comment]
I switched to BedrockConverse and I don't have this issue now.

**Comment by rkrishna116** [comment]
Yes, switching to BedrockConverse works, and as a failsafe I also downgraded llama-index to 0.10.30
