### ISSUE TITLE
[Question]: Multi modal rag implementation for pdf text and images

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#11743]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have multiple pdf documents with me that contains both images and text. These documents contain lots of steps/procedures and it may have images for certain steps. The application I want to build should fetch not only the relevant text and also the relevant image. Is it possible to implement this using llamaindex, if so can anyone say a procedure for this

**Comment by Prem-Nitin** [comment]
@dosu-bot that's great and i would be able to extract the text from image but that's not what i expect. I don't want to extract text from images rather i want to extract relevant text and from the document and if there is any relevant image for the retrieved context then the application should also include the image in the response. In my case i have multiple steps in the document and each step have some text followed by some images. I want my application to work in a way such that when a certain step is retrieved  and image under it should also be retrieved

**Comment by CungNguyenHuy** [comment]
> @dosu-bot that's great and i would be able to extract the text from image but that's not what i expect. I don't want to extract text from images rather i want to extract relevant text and from the document and if there is any relevant image for the retrieved context then the application should also include the image in the response. In my case i have multiple steps in the document and each step have some text followed by some images. I want my application to work in a way such that when a certain step is retrieved and image under it should also be retrieved

Do you have a solution for this part yet?
