### ISSUE TITLE
[Bug]:  raise JsonPathLexerError('Unexpected EOF in string literal or identifier')

### ISSUE THREAD

**Issue by Tasarinan** [run-llama/llama_index#11747]
### Bug Description

Use example json and json schema, why we get the following error? 
 raise JsonPathLexerError('Unexpected EOF in string literal or identifier')

### Version

0.10.15

### Steps to Reproduce

1. copy json data and json schema 
2. create jsonengine query
3. run query

**Comment by logan-markewich** [comment]
What LLM are you using? Probably it did not predict a correct or complete JSON query with proper syntax
