### ISSUE TITLE
[Feature Request]: Update llama-index-vector-stores-weaviate to weaviate-client version 4.x

### ISSUE THREAD

**Issue by tos-wdp** [run-llama/llama_index#11745]
### Feature Description

Update llama-index-vector-stores-weaviate from weaviate-client version 3. 26.2 to 4.x

### Reason

Methods are deprecated in weaviate-client > 4.0.
New features are introduced.
A collection upserted with weaviate-client 3.x can not be querried with weaviate-client  4.x

### Value of Feature

Adapting to current Weaviate Cloud Service standard gRPC. Avoid deprecation. Use new features of Weaviate.

**Comment by nerdai** [comment]
@tos-wdp agreed this would be a worthwhile update. Would welcome a PR for this update, if you'd be interested in taking it on.

**Comment by marcelosz** [comment]
Any news on this, please?

**Comment by typefox09** [comment]
Can we add the multi tenant logic Weaviate offers also?

**Comment by typefox09** [comment]
Can we also add the auto_limit (auto_cut) and rerank feature, eg:

    openAiReranked = weaviate.query.hybrid(
        query=query,
        alpha=0.9,
        fusion_type=HybridFusion.RELATIVE_SCORE,
        filters=query_filter,
        auto_limit=2,
        rerank=wvc.query.Rerank(
            prop="content",
            query=query
        )
    )

**Comment by hsm207** [comment]
i want it 😀

**Comment by hsm207** [comment]
> Can we add the multi tenant logic Weaviate offers also?

I opened #13307 to discuss the design

Let's open a separate issue for each feature we'd like see added so it is easier to track progress.
