### ISSUE TITLE
How to use Free-dolly with llama_index?

### ISSUE THREAD

**Issue by nazkhan-8451** [run-llama/llama_index#1174]
The free-dolly (dolly-v2) from databricks https://huggingface.co/databricks/dolly-v2-12b, how do I use it for query and embedding? Will it be possible to create a notebook to show it?

**Comment by logan-markewich** [comment]
dolly is only a language model, so you can't use it for embeddings (or at least, the embeddings would not be good)

See this page for using custom LLMs: https://gpt-index.readthedocs.io/en/latest/how_to/customization/custom_llms.html#example-using-a-custom-llm-model

Seet this page for custom embedding models: https://gpt-index.readthedocs.io/en/latest/how_to/customization/embeddings.html#custom-embeddings

**Comment by logan-markewich** [comment]
I have this working today actually. Something like this

```python
# define prompt helper
# set maximum input size
max_input_size = 2048
# set number of output tokens
num_output = 256
# set maximum chunk overlap
max_chunk_overlap = 20


model_pipeline = pipeline(model="databricks/dolly-v2-12b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")

class CustomLLM(LLM):
    model_name = "databricks/dolly-v2-12b"
    
    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        res = model_pipeline (prompt)
        return res

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": self.model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"


llm_predictor = LLMPredictor(llm=CustomLLM())
embed_model = LangchainEmbedding(HuggingFaceEmbeddings())

node_parser = SimpleNodeParser(text_splitter=TokenTextSplitter(chunk_size=512, chunk_overlap=max_chunk_overlap))
prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model, prompt_helper=prompt_helper, node_parser=node_parser, chunk_size_limit=512)

...

index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
```

You'll notice I moved the pipeline OUTSIDE of the CustomLLM class. Seems like pydantic (from langchain) was causing a huge spike in memory usage by copying the model in memory or something.

**Comment by nazkhan-8451** [comment]
I am getting this INFO: `The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:0 for open-end generation.
Input length of input_ids is 629, but ``max_length`` is set to 20. This can lead to unexpected behavior. You should consider increasing ``config.max_length`` or ``max_length``.` Then get this error: `ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)`

**Comment by logan-markewich** [comment]
@nazkhan-8451 hmmm, here's my package versions

transformers==4.28.0
torch==1.13.1
llama_index==0.5.8 (but newer versions should be fine?)

**Comment by markusantonuis** [comment]
> I have this working today actually. Something like this
> 
> ```python
> import torch
> 
> from transformers import pipeline
> from langchain.llms.base import LLM
> from langchain.embeddings.huggingface import HuggingFaceEmbeddings
> from llama_index import GPTSimpleVectorIndex, GPTListIndex, GPTKeywordTableIndex, Document, MockEmbedding, LLMPredictor, ServiceContext, LangchainEmbedding, PromptHelper
> from llama_index.langchain_helpers.text_splitter import TokenTextSplitter
> from llama_index.node_parser.simple import SimpleNodeParser
> from typing import Optional, List, Mapping, Any
> 
> # define prompt helper
> # set maximum input size
> max_input_size = 2048
> # set number of output tokens
> num_output = 256
> # set maximum chunk overlap
> max_chunk_overlap = 20
> 
> 
> model_pipeline = pipeline(model="databricks/dolly-v2-12b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")
> 
> class CustomLLM(LLM):
>     model_name = "databricks/dolly-v2-12b"
>     
>     def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
>         res = model_pipeline (prompt)
>         return res
> 
>     @property
>     def _identifying_params(self) -> Mapping[str, Any]:
>         return {"name_of_model": self.model_name}
> 
>     @property
>     def _llm_type(self) -> str:
>         return "custom"
> 
> 
> llm_predictor = LLMPredictor(llm=CustomLLM())
> embed_model = LangchainEmbedding(HuggingFaceEmbeddings())
> 
> node_parser = SimpleNodeParser(text_splitter=TokenTextSplitter(chunk_size=512, chunk_overlap=max_chunk_overlap))
> prompt_helper = PromptHelper(max_input_size, num_output, max_chunk_overlap)
> service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor, embed_model=embed_model, prompt_helper=prompt_helper, node_parser=node_parser, chunk_size_limit=512)
> 
> ...
> 
> index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
> ```
> 
> You'll notice I moved the pipeline OUTSIDE of the CustomLLM class. Seems like pydantic (from langchain) was causing a huge spike in memory usage by copying the model in memory or something. Would love to figure out a way to disable that, but for now, this works

I really like llama-index and was wondering how long it would take before being implemented with one of the open source models. Didn't think someone would get there in a matter of weeks! Impressive!
Does this make any api calls or other calls to servers? I have some sensitive data that I would like to index and query with an LLM

**Comment by markusantonuis** [comment]
@logan-markewich  Great to hear. Makes me feel more comfortable using my sensitive info in the index. 
Yes, not expecting any linguistically good responses with the open source models yet, just something that can accept a query and point me in the right direction. The human-like responses will surely follow very soon
Will give it a go and report back my experience here

**Comment by markusantonuis** [comment]
@logan-markewich  were you able to query your index without an openai api key? When I try to load my index using GPTSimpleVectorIndex.load_from_disk() it requests that I enter an api key

**Comment by logan-markewich** [comment]
@markusantonuis make sure you pass the service context back in when doing load from disk

**Comment by markusantonuis** [comment]
@logan-markewich I am a dope. That was indeed the problem. I added service_context into the line like so:
index = GPTSimpleVectorIndex.load_from_disk('Index_file.json', service_context=service_context).

Unfortunately it looks like my hardware isn't up to the task even with the 3B model. It has been hanging on this for some time now: 

INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
INFO:sentence_transformers.SentenceTransformer:Use pytorch device: cpu
Batches: 100%|██████████| 1/1 [00:01<00:00,  1.06s/it]

Might see if I can get my gpu working on it.

**Comment by sudokhan112** [comment]
@markusantonuis have you tried load 8 bit?

**Comment by markusantonuis** [comment]
@sudokhan112  Do you mean using a quantized model? I have not tried this. I gather this is something I would have to run myself?

**Comment by sankethgadadinni** [comment]
@markusantonuis 
what is the embed model that you are using here?
It asks for OpenAI keys when I'm running it

**Comment by CarlosD1111** [comment]
Hello guys!

I am trying to run that code on Azure databricks and using python 3.10.6 and I get this error: 

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aadf829e-883f-4635-aa65-abfee8a728ff/lib/python3.10/site-packages/langchain/llms/base.py:137, in BaseLLM.generate(self, prompts, stop)
    133 self.callback_manager.on_llm_start(
    134     {"name": self.__class__.__name__}, prompts, verbose=self.verbose
    135 )
    136 try:
--> 137     output = self._generate(prompts, stop=stop)
    138 except (KeyboardInterrupt, Exception) as e:
    139     self.callback_manager.on_llm_error(e, verbose=self.verbose)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aadf829e-883f-4635-aa65-abfee8a728ff/lib/python3.10/site-packages/langchain/llms/base.py:325, in LLM._generate(self, prompts, stop)
    323 for prompt in prompts:
    324     text = self._call(prompt, stop=stop)
--> 325     generations.append([Generation(text=text)])
    326 return LLMResult(generations=generations)

File /local_disk0/.ephemeral_nfs/envs/pythonEnv-aadf829e-883f-4635-aa65-abfee8a728ff/lib/python3.10/site-packages/pydantic/main.py:341, in pydantic.main.BaseModel.__init__()

**ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)**

### I have a list of the packages installed if that helps:

Package                  Version
------------------------ -------------
accelerate               0.18.0
aiohttp                  3.8.4
aiosignal                1.3.1
appdirs                  1.4.4
argon2-cffi              21.3.0
argon2-cffi-bindings     21.2.0
asttokens                2.2.1
async-timeout            4.0.2
attrs                    21.4.0
backcall                 0.2.0
beautifulsoup4           4.11.1
black                    22.6.0
bleach                   4.1.0
blinker                  1.4
boto3                    1.24.28
botocore                 1.27.28
cachetools               5.3.0
certifi                  2022.9.14
cffi                     1.15.1
chardet                  4.0.0
charset-normalizer       2.0.4
click                    8.0.4
cmake                    3.26.3
cryptography             37.0.1
cycler                   0.11.0
Cython                   0.29.32
dataclasses-json         0.5.7
dbus-python              1.2.18
debugpy                  1.5.1
decorator                5.1.1
defusedxml               0.7.1
distlib                  0.3.6
distro                   1.7.0
distro-info              1.1build1
docstring-to-markdown    0.12
docx2txt                 0.8
entrypoints              0.4
executing                1.2.0
facets-overview          1.0.2
fastjsonschema           2.16.3
filelock                 3.10.7
fonttools                4.25.0
frozenlist               1.3.3
fsspec                   2023.4.0
googleapis-common-protos 1.56.4
gptcache                 0.1.21
greenlet                 2.0.2
grpcio                   1.48.1
grpcio-status            1.48.1
httplib2                 0.20.2
huggingface-hub          0.14.1
idna                     3.3
importlib-metadata       4.6.4
ipykernel                6.17.1
ipython                  8.10.0
ipython-genutils         0.2.0
ipywidgets               7.7.2
jedi                     0.18.1
jeepney                  0.7.1
Jinja2                   2.11.3
jmespath                 0.10.0
joblib                   1.2.0
jsonschema               4.16.0
jupyter-client           7.3.4
jupyter_core             4.11.2
jupyterlab-pygments      0.1.2
jupyterlab-widgets       1.0.0
keyring                  23.5.0
kiwisolver               1.4.2
langchain                0.0.142
launchpadlib             1.10.16
lazr.restfulclient       0.14.4
lazr.uri                 1.0.6
lit                      16.0.2
llama-index              0.5.27
MarkupSafe               2.0.1
marshmallow              3.19.0
marshmallow-enum         1.5.1
matplotlib               3.5.2
matplotlib-inline        0.1.6
mccabe                   0.7.0
mistune                  0.8.4
more-itertools           8.10.0
mpmath                   1.3.0
multidict                6.0.4
mypy-extensions          0.4.3
nbclient                 0.5.13
nbconvert                6.4.4
nbformat                 5.5.0
nest-asyncio             1.5.5
networkx                 3.1
nltk                     3.8.1
nodeenv                  1.7.0
notebook                 6.4.12
numexpr                  2.8.4
numpy                    1.21.5
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-cupti-cu11   11.7.101
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
nvidia-cufft-cu11        10.9.0.58
nvidia-curand-cu11       10.2.10.91
nvidia-cusolver-cu11     11.4.0.1
nvidia-cusparse-cu11     11.7.4.91
nvidia-nccl-cu11         2.14.3
nvidia-nvtx-cu11         11.7.91
oauthlib                 3.2.0
openai                   0.27.5
openapi-schema-pydantic  1.2.4
packaging                21.3
pandas                   1.4.4
pandocfilters            1.5.0
parso                    0.8.3
pathspec                 0.9.0
patsy                    0.5.2
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.2.0
pip                      23.1.2
platformdirs             2.5.2
plotly                   5.9.0
pluggy                   1.0.0
prometheus-client        0.14.1
prompt-toolkit           3.0.36
protobuf                 3.19.4
psutil                   5.9.0
psycopg2                 2.9.3
ptyprocess               0.7.0
pure-eval                0.2.2
pyarrow                  7.0.0
pycparser                2.21
pydantic                 1.10.7
pyflakes                 3.0.1
Pygments                 2.11.2
PyGObject                3.42.1
PyJWT                    2.3.0
pyodbc                   4.0.32
pyparsing                3.0.9
pyright                  1.1.294
pyrsistent               0.18.0
python-apt               2.4.0+ubuntu1
python-dateutil          2.8.2
python-lsp-jsonrpc       1.0.0
python-lsp-server        1.7.1
pytoolconfig             1.2.2
pytz                     2022.1
PyYAML                   6.0
pyzmq                    23.2.0
regex                    2023.3.23
requests                 2.28.1
rope                     1.7.0
s3transfer               0.6.0
scikit-learn             1.1.1
scipy                    1.9.1
seaborn                  0.11.2
SecretStorage            3.3.1
Send2Trash               1.8.0
sentence-transformers    2.2.2
sentencepiece            0.1.98
setuptools               63.4.1
six                      1.16.0
soupsieve                2.3.1
SQLAlchemy               1.4.48
ssh-import-id            5.11
stack-data               0.6.2
statsmodels              0.13.2
sympy                    1.11.1
tenacity                 8.2.2
terminado                0.13.1
testpath                 0.6.0
threadpoolctl            2.2.0
tiktoken                 0.3.3
tokenize-rt              4.2.1
tokenizers               0.13.3
tomli                    2.0.1
torch                    2.0.0
torchvision              0.15.1
tornado                  6.1
tqdm                     4.65.0
traitlets                5.1.1
transformers             4.28.1
triton                   2.0.0
typing_extensions        4.5.0
typing-inspect           0.8.0
ujson                    5.4.0
unattended-upgrades      0.1
urllib3                  1.26.11
virtualenv               20.16.3
wadllib                  1.3.6
wcwidth                  0.2.5
webencodings             0.5.1
whatthepatch             1.0.2
wheel                    0.37.1
widgetsnbextension       3.6.1
yapf                     0.31.0
yarl                     1.9.2
zipp                     1.0.0  

hope you guys are well and thanks a lot for your help!

**Comment by bradley-pearson6597** [comment]
@CarlosD1111 

The cause of this is that the output of `res = pipeline(prompt)`  is a list. To get it working you need to change the CustomLLM class to this :

```python 
class CustomLLM(LLM):
    def _call(self, prompt, stop=None):
        res = pipeline(prompt)
        prompt_length = len(prompt)
        res = res[0]['generated_text']
        return res   

    def _identifying_params(self):
        return {"name_of_model": "dolly-v2-3b"}
    def _llm_type(self):
        return "custom"
```

**Comment by DhavalWI** [comment]
> @markusantonuis have you tried load 8 bit?

How do we load it in 8 bit? just writing load_in_4bit=True. is not working.

im loading the model like below---

model_name = "databricks/dolly-v2-12b"
pipeline = pipeline("text-generation",model="databricks/dolly-v2-12b", torch_dtype=torch.bfloat16, trust_remote_code=True, device_map="auto")

class CustomLLM(LLM):
    
    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output)[0]["generated_text"]

        # only return newly generated tokens
        return response

    @property 
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": model_name}

    @property
    def _llm_type(self) -> str:
        return "custom"


llm_predictor = LLMPredictor(llm=CustomLLM())
