### ISSUE TITLE
[Bug]: Invalid import path for DeepEvalCallbackHandler

### ISSUE THREAD

**Issue by nikkhn** [run-llama/llama_index#11753]
### Bug Description

When turning on the `deepeval` integration with `set_global_handler("deepeval")`, i receive the error:
```
ImportError: DeepEvalCallbackHandler is not installed. Please install it using `pip install llama-index-callbacks-deepeval
```
despite the package being istalled.

### Version

0.10.17

### Steps to Reproduce

* add `set_global_handler("deepeval")` to one of your project files

**Comment by nikkhn** [comment]
i was having a hard time getting my env set up to run/write tests, however i believe [this](https://github.com/run-llama/llama_index/pull/11754) would solve the issue (its untested)

**Comment by logan-markewich** [comment]
Fixed + merged+ published a new version
