### ISSUE TITLE
[Bug]: Can not create DashScopeEmbedding object

### ISSUE THREAD

**Issue by neoscript99** [run-llama/llama_index#11764]
### Bug Description

Can not create `from llama_index.embeddings.dashscope import DashScopeEmbedding` object

llama_index==0.10.13
llama-index-embeddings-dashscope==0.1.1

The reason is that,   `DashScopeEmbedding` use `from pydantic import PrivateAttr`, not `from llama_index.core.bridge.pydantic import PrivateAttr`

### Version

0.10.13

### Steps to Reproduce

from llama_index.embeddings.dashscope import DashScopeEmbedding
embed_model = DashScopeEmbedding()
Settings.embed_model = embed_model

### Relevant Logs/Tracbacks

```shell
Exception has occurred: ValueError
"DashScopeEmbedding" object has no field "_api_key"
  File "test.py", line 5, in <module>
    embed_model = DashScopeEmbedding()
ValueError: "DashScopeEmbedding" object has no field "_api_key"
```

**Comment by logan-markewich** [comment]
rip, sneaky pydantic import bug. Plz make a PR if you have time

**Comment by logan-markewich** [comment]
This is fixed in the latest version of the package (thanks for the PR!)
