### ISSUE TITLE
[Question]: query_engine.query("query") returns empty response...

### ISSUE THREAD

**Issue by Sridevi17j** [run-llama/llama_index#11771]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Please find my entire code here

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader("data1").load_data()

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
Settings.llm = None
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("what is this document about")
print(response)

Below is the output:

Query: what is this document about
Answer:

If i set Settings.llm = Some Huggingface LLM, then it returns "Empty Response" or "My Response"
so none of them worked.. Could someone pls advise, what am i doing wrong here, I have uploaded a pdf file to query it, i also tried with simple text files too..
But nothing worked..

**Comment by Sridevi17j** [comment]
Hi @dosu-bot I added below code 
service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)

and i get below error
(ServiceContext is deprecated, please use `llama_index.settings.Settings` instead.) -- Deprecated since version 0.10.0.
  service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)
  
so i am using like below

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
Settings.llm = None

also for StorageContext, i could not understand how to use this, and what are all the parameters to be passed in.
if you could explain the paramters inside to be passed in, it would be great.. pls provide your inputs...

**Comment by Sridevi17j** [comment]
@dosu-bot , I saved the index like below
index.storage_context.persist(persist_dir="test")

and i reloaded the index like below
docstore= "test/docstore.json"
index_store= "test/index_store.json"
vector_stores="test/default_vector_store.json"
graph_store= "test/graph_store.json"

service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)
storage_context = StorageContext(docstore=docstore,index_store=index_store,vector_stores=vector_stores,graph_store=graph_store)

new_index = load_index_from_storage(storage_context, service_context=service_context)

i get below error
AttributeError                            Traceback (most recent call last)
Cell In[27], line 12
      9 service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)
     10 storage_context = StorageContext(docstore=docstore,index_store=index_store,vector_stores=vector_stores,graph_store=graph_store)
---> 12 new_index = load_index_from_storage(storage_context, service_context=service_context)

File ~\PycharmProjects\Test1\.venv\Lib\site-packages\llama_index\core\indices\loading.py:33, in load_index_from_storage(storage_context, index_id, **kwargs)
     30 else:
     31     index_ids = [index_id]
---> 33 indices = load_indices_from_storage(storage_context, index_ids=index_ids, **kwargs)
     35 if len(indices) == 0:
     36     raise ValueError(
     37         "No index in storage context, check if you specified the right persist_dir."
     38     )

File ~\PycharmProjects\Test1\.venv\Lib\site-packages\llama_index\core\indices\loading.py:64, in load_indices_from_storage(storage_context, index_ids, **kwargs)
     62 if index_ids is None:
     63     logger.info("Loading all indices.")
---> 64     index_structs = storage_context.index_store.index_structs()
     65 else:
     66     logger.info(f"Loading indices with ids: {index_ids}")

AttributeError: 'str' object has no attribute 'index_structs'

pls provide your inputs..

**Comment by Sridevi17j** [comment]
@dosu-bot in the given links, i saw one line, and i used here for StorageContext for giving the persisten directory path, it did not throw error, but still it gives empty response, check it out

service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)

storage_context = StorageContext.from_defaults(persist_dir="test")

new_index = load_index_from_storage(storage_context, service_context=service_context)
query_engine = new_index.as_query_engine()
response = query_engine.query("what is this document about")
print(response)

--------------

Query: what is this document about
Answer:

**Comment by Sridevi17j** [comment]
@dosu-bot, have followed all your advise, after using custom LLM, instead of empty response, i am getting "My Response" as a response- which is a dummy response that is set in our LLM,   see my code below
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader(input_files = ["data1/test.txt"]).load_data()

index = VectorStoreIndex.from_documents(documents)
index.storage_context.persist(persist_dir="test")


from typing import Optional, List, Mapping, Any
from llama_index.core.llms import (
    CustomLLM,
    CompletionResponse,
    CompletionResponseGen,
    LLMMetadata,
)
from llama_index.core.llms.callbacks import llm_completion_callback


class OurLLM(CustomLLM):
    context_window: int = 3900
    num_output: int = 256
    #model_name: str = "facebook/opt-iml-1.3b"
    model_name: str = "C:/Users/sride/git/lama_test/llama/llama-2-70b-chat"
    dummy_response: str = "My response"

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=self.context_window,
            num_output=self.num_output,
            model_name=self.model_name,
        )

    @llm_completion_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        return CompletionResponse(text=self.dummy_response)

    @llm_completion_callback()
    def stream_complete(
        self, prompt: str, **kwargs: Any
    ) -> CompletionResponseGen:
        response = ""
        for token in self.dummy_response:
            response += token
            yield CompletionResponse(text=response, delta=token)
			
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
Settings.chunk_size = 2048
Settings.context_window = 3900
embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)
Settings.llm = OurLLM()
from llama_index.core.indices.loading import load_index_from_storage
from llama_index.core.storage.storage_context import StorageContext
from llama_index.core import ServiceContext
from llama_index.core.storage.index_store.simple_index_store import SimpleIndexStore

service_context = ServiceContext.from_defaults(chunk_size=2048,llm=OurLLM(), embed_model=embed_model)

storage_context = StorageContext.from_defaults(persist_dir="test")

new_index = load_index_from_storage(storage_context, service_context=service_context)
query_engine = new_index.as_query_engine()
response = query_engine.query("what is the name")
print(response)

My response




I tried setting the settings through Settings also, through ServiceContext... none of them working, tried setting the LLM to None also to CustomLLM, also changed chunk_size, context window... tried all possible way.. still no luck.. meanwhile, please also see my index_store.json below ( Note:- embedding dict is empty)
{"index_store/data": {"ec2be150-8870-4f10-ae22-9690fbcdf08b": {"__type__": "vector_store", "__data__": "{\"index_id\": \"ec2be150-8870-4f10-ae22-9690fbcdf08b\", \"summary\": null, \"nodes_dict\": {\"22663d7f-cb1b-48e9-b7bc-3a90d5f56c15\": \"22663d7f-cb1b-48e9-b7bc-3a90d5f56c15\"}, \"doc_id_dict\": {}, \"embeddings_dict\": {}}"}}}

What am i doing wrong here?

**Comment by mlkorra** [comment]
@Sridevi17j  have you tried using the chatgpt-3.5 api as LLM?

**Comment by Sridevi17j** [comment]
@mlkorra  I m trying to use Ollama , open source LLM

**Comment by Sridevi17j** [comment]
I sorted this issue, by printing response in a stream.

Below code gives response. 

`index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine(streaming=True)
response_stream = query_engine.query("What is this document about?")
response_stream.print_response_stream()`

**Comment by vonrafael** [comment]
> I sorted this issue, by printing response in a stream.
> 
> Below code gives response.
> 
> ```
> index = VectorStoreIndex.from_documents(documents)         
> query_engine = index.as_query_engine(streaming=True)         
> response_stream = query_engine.query("What is this document about?")         
> response_stream.print_response_stream()
> ```

I'm sorry but this didn't helped!!

**Comment by lmaddox** [comment]
`Settings.llm = None` looks strange to me. You said that trying with a dummy LLM does return a response, though? Have you tried setting the llm to not-None?

```
Settings.llm = Ollama(model_name=..., model_url=..., request_timeout=..., use_json=False,)
```

I'm pretty sure the embeddings need to be compatible with your LLM of choice.

```
Settings.embed_model = OllamaEmbedding(...)
```

If you're not setting them globally, then you're gonna wanna pass them as args to quite nearly every constructor or factory.

```
VectorStoreIndex(..., embed_model=...,) # n.b., I'm not seeing an embed_model or llm option for the from_documents factory
```

`as_query_engine` *does* accept an llm parameter.

Adding streaming or async will just complicate things until you get that much working. So far as I can tell, you're using simple storage backends. That's good. Adding, e.g., postgres or redis will require some attention to the embedding dimensions.

**Comment by dheerajsn** [comment]
there appears to be no resolution on this thread

**Comment by Tim-Chen11** [comment]
I have same issue when doing the knowledge graph query. Here's how I solve, hope may help:




Empty response
  The issue was a bug in LlamaIndex's MemgraphPropertyGraphStore:

  1. When verify_vector_support() runs during initialization, it tries to create a vector index
  2. If the index already exists, it catches the error but incorrectly sets _supports_vector_index = 
  False
  3. This causes vector_query() to return empty results instead of performing the actual vector search
  4. The query engine gets no results and returns "Empty Response"

  The fix: After creating the graph_store, manually set:
  graph_store._supports_vector_index = True

  This forces the library to use vector search, which then works perfectly! The knowledge graph
  extraction was working all along - it was just the retrieval that was broken due to this bug.
