### ISSUE TITLE
[Question]: Does using a ContextChatEngine with `stream_chat` always ignore the system prompt?

### ISSUE THREAD

**Issue by ckrapu** [run-llama/llama_index#11777]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When using [chat](https://github.com/run-llama/llama_index/blob/55229321245a81a9574cdfa571c61fb6c30aee9d/llama-index-core/llama_index/core/chat_engine/context.py#L155C9-L155C13) with a `ContextChatEngine`, [it looks like the system prompt ](https://github.com/run-llama/llama_index/blob/55229321245a81a9574cdfa571c61fb6c30aee9d/llama-index-core/llama_index/core/chat_engine/context.py#L134)is always discarded and only the prefix messages are taken. Is this as intended?

What is the ideal way to supply instructions to this type of chat engine?

**Comment by logan-markewich** [comment]
@ckrapu its not discarded.

The context chat engine uses the system prompt to supply retrieved context (you'll notice there is a context template at the top of the file)

The system prompt provided by the user is added to the prefix messages: https://github.com/run-llama/llama_index/blob/55229321245a81a9574cdfa571c61fb6c30aee9d/llama-index-core/llama_index/core/chat_engine/context.py#L89

and then it is later added to the end of the context template

This provides an easy way to give a system prompt without modifying the entire context template.

For example, this works:

```python
>>> from llama_index.core import Document, VectorStoreIndex
>>> index = VectorStoreIndex.from_documents([Document.example()])
>>> chat_engine = index.as_chat_engine(chat_mode="context", system_prompt="Talk like a pirate in every response.")
>>> resp = chat_engine.chat("What do you know about LLMs?")
>>> print(resp)
Arrr matey! LLMs be a mighty fine piece o' technology fer knowledge generation and reasonin'. They be pre-trained on vast amounts o' publicly available data, makin' 'em smart as a savvy pirate on the high seas! If ye be lookin' to augment LLMs with yer own private data, ye be needin' a toolkit like LlamaIndex to help ye on yer quest. Ye can trust me on that, savvy? Arrr!
>>> 
```
