### ISSUE TITLE
[Question]: How to effectively summarize large documents using SummaryIndex or similar?

### ISSUE THREAD

**Issue by sayanmndl21** [run-llama/llama_index#11779]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am following this tutorial to create a small RAG engine with a local llama model (Mixtral 8x7B): [Multi Document Agents v1](https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents-v1.html). But this always leads to `ValueError: Requested tokens (xxx) exceed context window of yyy` at 
```
await summary_query_engine.aquery(
                "Extract a concise 1-2 line summary of this document"
            )
```
I have so far tried reducing chunk size, increase max_tokens to the limit, adding CompactAndRefine() as synthesizer but none of them works. Is an argument which I might be missing?

**Comment by taimans-git** [comment]
I have a similar problem. @sayanmndl21 have you found a solution? Thanks in advance :)

**Comment by sayanmndl21** [comment]
Hey @taimans-git, unfortunately no. I have since then changed directions in favor of simpler methods like Retriever Query Engine which is performing better than expected.

I'd suggest custom retrievers (https://docs.llamaindex.ai/en/stable/examples/query_engine/CustomRetrievers/) and chromadb vector store if you are working with a large document base.

**Comment by taimans-git** [comment]
Hi @sayanmndl21, thanks for your suggestions. I tried different things and with other API models it seems to work. For example, for me it works with models from VertexAI or OpenAI. For MistralAI, I had to additionally set the context window to make it work, e.g.
```
Settings.context_window = 4096
```
