### ISSUE TITLE
[Feature Request]: Add support for non-OpenAI embeddings in RagEvaluatorPack

### ISSUE THREAD

**Issue by vecorro** [run-llama/llama_index#11785]
### Feature Description

Hi,

I'm trying to use `RagEvaluatorPack` to evaluate a pipeline that does NOT use any OpenAI models. Despite being able to set the `judge_llm` when instantiating `RagEvaluatorPack`:

```
rag_evaluator = RagEvaluatorPack(
    judge_llm=Settings.llm,
    query_engine=query_engine,  # built with the same source Documents as the rag_dataset
    rag_dataset=small_rag_eval_dataset,
    show_progress=True,

```

The process fails when trying to run the following block from `https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-rag-evaluator/llama_index/packs/rag_evaluator/base.py` (lines 106-108):

```
   judges["semantic_similarity"] = SemanticSimilarityEvaluator(
            embed_model=OpenAIEmbedding()
        )
```

This forces people to use OpenAI instead of being able to use another embedding model (BAAI's for instance). As I don't have an OpenAI account (we are trying to stick to open source), the process fails with:

```
APIConnectionError: Connection error.
```

Thanks!

### Reason

The current implementation of `RagEvaluatorPack` forces people to use OpenAI instead of being able to use another embedding model (BAAI's for instance). As I don't have an OpenAI account (we are trying to stick to open source), the process fails with:

```
APIConnectionError: Connection error.
```

### Value of Feature

People would be able to use `RagEvaluatorPack` without being OpenAI's hostage :). This is important for many regulated organizations unable to use OpenAI or other cloud-based LM services.

**Comment by logan-markewich** [comment]
Yea it would be pretty easy to update the interface 

But, you do know it's very easy to download the llamapack and edit the code? (They are kind of meant to be used that way)

**Comment by vecorro** [comment]
Thanks @logan-markewich. For sure, however, I thought it'd be natural to assume that any llama-index-related packages would look at the default settings before hard-wiring models, for instance, if I do

```
# LLamaIndex embedding model
Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-base-en-v1.5",
)
```

And llamapacks look for those general settings, then they would behave consistently with the rest of the llama-index code. I think (although I might be wrong).

Thanks again!

**Comment by logan-markewich** [comment]
LlamaPacks are general examples of using llama-index, contributed by the community. The expectations for customizing or using models is a little relaxed compared to the things maintained in the core package
