### ISSUE TITLE
[Question]: Generate text from response

### ISSUE THREAD

**Issue by shahikkhan** [run-llama/llama_index#11796]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

      query_engine= index.as_query_engine()
      response= query_engine.query("Rewrite the text more elegantly in the shakespear style?") 
      print(response)
      index1= VectorStoreIndex.from_documents([response], service_context=service_context)
How can I generate text from an LLM llama index generated response?
TypeError: 'Response' object is not subscriptable

**Comment by logan-markewich** [comment]
str(response) will get the string

If you wanted to index that response, that string needs to go into a document object 

```
from llama_index.core import Document, VectorStoreIndex 

index = VectorStoreIndex.from_documents([Document(text=str(response))])
```

**Comment by shahikkhan** [comment]
index1 = VectorStoreIndex.from_documents(documents, [Document(text=str(response))],service_context=service_context)
how can I pass multiple documents in vectorstoreindex? 
AttributeError: 'list' object has no attribute 'docstore'

**Comment by shahikkhan** [comment]
documents = [str(response)]
This works, 
# Assuming VectorStoreIndex.from_documents takes a list of Document objects
# Replace this with the actual method or class from your library
document_objects = [Document(text=doc) for doc in documents]

index1 = VectorStoreIndex.from_documents(document_objects, service_context=service_context)
