### ISSUE TITLE
[Question]: Predict the prompt 

### ISSUE THREAD

**Issue by shahikkhan** [run-llama/llama_index#11797]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

<img width="792" alt="inbox-3197853-96c0928afba46d4e0e31f15a071502a2-Screenshot 2024-02-29 at 12 16 41" src="https://github.com/run-llama/llama_index/assets/140295809/d5df78d4-0684-444f-b581-39874a0132d3">

     from llama_index.core import Document
     index1 = VectorStoreIndex.from_documents(documents, [Document(text=str(response))],service_context=service_context)

      query_engine1= index.as_query_engine()
      response1= query_engine1.query("Predict the prompt?") 
      print(response1)

Passing multiple text inputs as documents 
AttributeError: 'list' object has no attribute 'docstore'

**Comment by logan-markewich** [comment]
You can't pass in multiple lists of documents like that. It needs to be a single list, followed by normal kwargs

**Comment by logan-markewich** [comment]
You can concatenate lists in python 

documents = documents + [...]

**Comment by shahikkhan** [comment]
documents1= documents + Document(text=str(response))
TypeError: can only concatenate list (not "Document") to list
