### ISSUE TITLE
[Question]: Connection error 

### ISSUE THREAD

**Issue by shahikkhan** [run-llama/llama_index#11802]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

      llm = AzureOpenAI(
    model="gpt-35-turbo-16k",
    temperature=0,
    deployment_name="my-custom-llm",
    api_key=openai.api_key,
    )

     service_context= ServiceContext.from_defaults(llm=llm) 

     documents= SimpleDirectoryReader('/content/gdrive/MyDrive/original_data').load_data()
     index= VectorStoreIndex.from_documents(documents, service_context=service_context)
     query_engine= index.as_query_engine()
     response= query_engine.query("Rewrite the text more elegantly in the shakespear style?") 
    print(response)

APIConnectionError: Connection error?

**Comment by Bharathi-A7** [comment]
I'm facing the same issue. Did you figure out a solution?
