### ISSUE TITLE
[Bug]: 'llama_index.embeddings.huggingface missing? 

### ISSUE THREAD

**Issue by hemanth** [run-llama/llama_index#11804]
### Bug Description

`ModuleNotFoundError: No module named 'llama_index.embeddings.huggingface'`

<img width="802" alt="image" src="https://github.com/run-llama/llama_index/assets/18315/80846117-f011-4032-b3b6-84d3e03295c5">

^ I see this only on colab

### Version

v0.10.18

### Steps to Reproduce

```py
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
```

**Comment by logan-markewich** [comment]
@hemanth did you run `pip install llama-index-embeddings-huggingface` ?

**Comment by hemanth** [comment]
@logan-markewich yup! Still the same.

**Comment by hemanth** [comment]
`llama_index-embeddings-huggingface` matters?  `_` vs `-` in the name.

**Comment by hemanth** [comment]
@logan-markewich 

Well, I created a fresh `venv` I am no more seeing the module error, but, using `llama-index-llms-ollama` 

I am getting a `404` on `httpx.HTTPStatusError: Client error '404 Not Found' for url 'http://localhost:11434/api/chat'` 

`lsof -i :11434` shows `ollama` running, `curl` calls works fine too.

**Comment by logan-markewich** [comment]
You are running the latest version of ollama?

Sometimes I have to edit the base url to be 127.0.0.1 instead of localhost when using WSL on windows 🤷🏻

**Comment by hemanth** [comment]
Same behavior on osx and Debian...

**Comment by hemanth** [comment]
Okies, another attempt on osx with ollama version `0.1.26` and pointing to `127.0.0.1` works. Yet to try the same on `Debian` 🤷

**Comment by logan-markewich** [comment]
I'm going to consider this resolved. Seems like just more putzing around with settings is needed

**Comment by RANA-ATI** [comment]
> @hemanth did you run `pip install llama-index-embeddings-huggingface` ?

Worked for me Thanks

**Comment by salueii** [comment]
after 
pip install llama-index-embeddings-huggingface
error exist!!! and not solved for me.
```
[WinError 126] The specified module could not be found. Error loading "c:\Users\ExpMax\.conda\envs\LlamaIndex_1\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
```

**Comment by korkmazemin1** [comment]
> @hemanth did you run `pip install llama-index-embeddings-huggingface` ?

this worked for me thanks

**Comment by flesym** [comment]
> @hemanth did you run `pip install llama-index-embeddings-huggingface` ?
it worked for me, Thanks!
