### ISSUE TITLE
[Question]: for a Hierarchical (Parent-child chunk referencing) recursive retriever, chroma DB seems to be reducing accuracy

### ISSUE THREAD

**Issue by Kushagra0409** [run-llama/llama_index#11814]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was following the below tutorial for recursive retriever - child chunk referencing parent chunk. In it, we create vectorstoreindex, and proceed with recursively referencing nodes of different chunk sizes. How do I proceed with creating a vector db for said such use case, because calling storage_context with a chromadb gives many hallucinating responses, or does not get the context at all (compared to running without storage_context, which performs better). 

Reference: https://docs.llamaindex.ai/en/stable/examples/retrievers/recursive_retriever_nodes.html#chunk-references-smaller-child-chunks-referring-to-bigger-parent-chunk

https://docs.llamaindex.ai/en/stable/examples/vector_stores/ChromaIndexDemo.html (Basic Example (including saving to disk))

**Comment by logan-markewich** [comment]
@Kushagra0409 This guide is maybe somewhat outdated. 

In v0.10.x, with a slight change, you can just throw everything into your vector db an be on your way without using a recursive retriever

```python
sub_chunk_sizes = [128, 256, 512]
sub_node_parsers = [
    SentenceSplitter(chunk_size=c, chunk_overlap=20) for c in sub_chunk_sizes
]

all_nodes = []
for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode(text=sn.text, index_id=base_node.node_id, obj=sn) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)

    # also add original node
    all_nodes.append(base_node)
    
vector_store = ChromaVectorStore(...)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex(nodes=all_nodes, storage_context=storage_context)

# retriever
retriever = index.as_retriever(..., verbose=True)

# query engine
query_engine = index.as_query_engine(..., verbose=True)
```
