### ISSUE TITLE
[Feature Request]: Dense X retrieval does not have storage_context attribute

### ISSUE THREAD

**Issue by Kushagra0409** [run-llama/llama_index#11812]
### Feature Description

Hello, I created a Dense X retriever and query engine, but I also need to store the vectors in a vector db (chromadb, elasticsearch etc), but unlike a simple VectorStoreIndex which has a storage_context attribute, the dense x implementation has no such attribute. Are there any future changes expected for this, and are there any workarounds as to how do I use a vector db with dense x retriever pack, please do tell.

### Value of Feature

Dense x has a great rag performance but because of lack of a storage context, it becomes difficult to store the embedding vectors in local storage. A storage feature addition will be extremely helpful.

**Comment by Kushagra0409** [comment]
@dosu-bot How would I proceed with integrating a LanternVectoreStore with the existing dense x pack retriever code? I am new to storing and loading vector dbs with LanternVectoreStore , so a code snippet of all necessary changes will be greatly helpful

**Comment by logan-markewich** [comment]
@Kushagra0409 I recommend just downloading the llama-pack and modifying it yourself (this is actually the intention behind llama-packs! 💪🏻 )

`llamaindex-cli download-llamapack DenseXRetrievalPack --download-dir ./dense_pack`
