### ISSUE TITLE
[Question]: SQL router query engine : How to make it conversational ?

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [run-llama/llama_index#11813]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using SQL router query engine but i can query only one query at a time . How can i make use of chat engine and make it conversational . 

reference: https://docs.llamaindex.ai/en/stable/examples/query_engine/SQLRouterQueryEngine.html

**Comment by pulkitmehtaworkmetacube** [comment]
@dosu-bot Actually , i am not only using sql query engine but there is 1 router in between which may route either to sql query engine or vector indexed query engine . How to deal with this case ?

**Comment by logan-markewich** [comment]
@pulkitmehtaworkmetacube Put it in an agent tool
https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent_with_query_engine.html


Or wrap it in a custom retriever and use it on a context (or condense plus context) chat engine
https://docs.llamaindex.ai/en/stable/examples/query_engine/CustomRetrievers.html#define-custom-retriever

```
from llama_index.core.chat_engine import ContextChatEngine

chat_engine = ContextChatEngine.from_defaults(retriever, llm=llm, ...)
```
