### ISSUE TITLE
[Bug]: CodeHierarchyNodeParser Fails with Multi-byte Characters, Leading to Incorrect Parsing

### ISSUE THREAD

**Issue by talshef** [run-llama/llama_index#11818]
### Bug Description

The CodeHierarchyNodeParser currently relies on byte indexing to substring text within the code. This approach leads to issues when handling characters that occupy more than one byte, such as emojis or certain Unicode characters.

- Good Scenario: The parser fails explicitly, alerting the user to the issue.

- Bad Scenario: The parser completes without errors, but the parsed output is incorrect. This happens silently, with no indication of the problem to the user.

### Version

0.10.18

### Steps to Reproduce

example file:
```
import pandas

# comment with emoji 🤣

def fun1():
    s = " emoji 🤣🤣🤣🤣🤣🤣🤣🤣🤣"
    print('fun1')


def fun2():
    x= 1 + 2
    y = 3 + 4
    z = x + y
    return z
```
    
parser failing
```
from llama_index.packs.code_hierarchy import CodeHierarchyAgentPack
from pathlib import Path


documents = SimpleDirectoryReader(
    input_files=["example_file.py"], 
    recursive=True,
    file_metadata=lambda x: {"filepath": x},
    required_exts=[".py"]
).load_data()

split_nodes = CodeHierarchyNodeParser(
    language="python",
    # You can further parameterize the CodeSplitter to split the code
    # into "chunks" that match your context window size using
    # chunck_lines and max_chars parameters, here we just use the defaults
    code_splitter=CodeSplitter(language="python", max_chars=10000, chunk_lines=10),
).get_nodes_from_documents(documents)
```

**Comment by logan-markewich** [comment]
Feel free to submit a PR 💪🏻  LlamaPacks are generally community contributed examples of things you can build with llama-index. Slightly different than what things maintained in `core` are

**Comment by josem7** [comment]
Having the same problem here :/

**Comment by josem7** [comment]
Digging deeper into it we found that tree_sitter_languages uses the byte representation of the text but when chunking you are using the text representation loaded with encoding UTF-8

As you can see in the code snippet below:


llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/code_hierarchy.py 
CodeHierarchyNodeParser._parse_nodes
```
        for node in nodes_with_progress:
            text = node.text
            tree = parser.parse(bytes(text, "utf-8"))

            if (
                not tree.root_node.children
                or tree.root_node.children[0].type != "ERROR"
            ):
                # Chunk the code
                _chunks = self._chunk_node(tree.root_node, node.text)
```

Later in 

CodeHierarchyNodeParser._chunk_node

`current_chunk = text[start_byte : parent.end_byte]`

This leads to chucking error because UTF-8 characters may use 2 bytes while reading the document with utf-8 encoding every character is a single element in the list.

Proposed solution 

```
        for node in nodes_with_progress:
            text = node.text
            tree = parser.parse(bytes(text, "utf-8"))

            if (
                not tree.root_node.children
                or tree.root_node.children[0].type != "ERROR"
            ):
                # Chunk the code
                _chunks = self._chunk_node(tree.root_node, bytes(text, "utf-8"))
```
