### ISSUE TITLE
How to merge different index in llamaindex?

### ISSUE THREAD

**Issue by Aniketparab1999** [run-llama/llama_index#11817]
index1 = GPTVectorStoreIndex(nodes = doc1, service_context=service_context, storage_context=storage_context,show_progress=True)
index2 = GPTVectorStoreIndex(nodes = doc2, service_context=service_context, storage_context=storage_context,show_progress=True)

I have this type of different indices for different document (For Llamaindex framework)
How can I combine these indices
I tried GPTListIndex which is not working

_Originally posted by @Aniketparab1999 in https://github.com/run-llama/llama_index/issues/8883#issuecomment-1988131700_

**Comment by logan-markewich** [comment]
@Aniketparab1999 You can't physically merge them. But you can query them all at the same time

```python
from llama_index.core.retrievers import QueryFusionRetriever

retriever = QueryFusionRetriever(
    [index1.as_retriever(), index2.as_retriever()],
    similarity_top_k=3,
    num_queries=1,  # set this to 1 to disable query generation
    use_async=True,
    verbose=True,
)
```
https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#use-in-a-query-engine

https://docs.llamaindex.ai/en/stable/examples/retrievers/relative_score_dist_fusion.html#relative-score-fusion-and-distribution-based-score-fusion

**Comment by Aniketparab1999** [comment]
But I want to combine both indices into single index, 
like
indices = index1 + index2

**Comment by logan-markewich** [comment]
@Aniketparab1999 you can't. You should make a single index to start with in that case.

The above I linked is essentially the same thing though

**Comment by Aniketparab1999** [comment]
Stop response generation in langchain framework

Python code:
qa_chain = RetrievalQA.from_chain_type(llm=turbo_llm,
                                  chain_type="stuff",
                                  retriever=compression_retriever,
                                  return_source_documents=True
                                    )
response = qa_chain("What is Langchain?")

This is the python code I am using to query over a PDF by following RAG approach.
My requirement is, if it takes more than 1 minute to generate the response then it should stop response generation from the backend.
How I can do that? Is there any python code architecture available for this?
