### ISSUE TITLE
indexing + Response Synthesizer

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#11829]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wish to create indexes for each user and also add response synthesizer to my query engine.

query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[
        SimilarityPostprocessor(similarity_cutoff=0.7)
    ]
)

------------------------------------------------------------------------

list_tool = QueryEngineTool.from_defaults(
    query_engine=list_query_engine,
    description='Useful for summarization questions related to Paul Graham eassy on What I Worked On.',
)

vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description='Useful for retrieving specific context from Paul Graham essay on What I Worked On.',
)

define query engine
query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(),
    query_engine_tools=[
        list_tool,
        vector_tool,
    ]
)
-------------------------------------------------------------------------------------------------

I wish to combine both of them. How can I do that?

**Comment by logan-markewich** [comment]
@Aekansh-Ak create your query engines, and then add them to the router?

```python
query_engine1 = RetrieverQueryEngine(
  retriever=retriever1,
  response_synthesizer=response_synthesizer,
  node_postprocessors=[
    SimilarityPostprocessor(similarity_cutoff=0.7)
    ]
)
...

# create tools for each query engine
tool1 = QueryEngineTool.from_defaults(
  query_engine=query_engine1 ,
  description='<description>',
  name='<name>',
)

# create router
query_engine = RouterQueryEngine(
  selector=LLMSingleSelector.from_defaults(),
  query_engine_tools=[
    tool1,
    ....
  ]
)
```
