### ISSUE TITLE
ModuleNotFoundError: No module named 'llama_index.prompts'

### ISSUE THREAD

**Issue by merterbak** [run-llama/llama_index#11823]
### Bug Description

I use colab for llama index and have a issue about ModuleNotFoundError

### Version

0.10.18

### Steps to Reproduce

here's the error:

!pip install llama-index-llms-huggingface
from llama_index.prompts.prompts import SimpleInputPrompt

ModuleNotFoundError                       Traceback (most recent call last)
 in <cell line: 3>()
      1 # Import the prompt wrapper...but for llama index
      2 get_ipython().system('pip install llama-index-llms-huggingface')
----> 3 from llama_index.prompts.prompts import SimpleInputPrompt
      4 # Create a system prompt
      5 system_prompt = """<s>[INST] <<SYS>>

ModuleNotFoundError: No module named 'llama_index.prompts'

NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

**Comment by logan-markewich** [comment]
@merterbak `llama_index.core.prompts.prompts import SimpleInputPrompt`
