### ISSUE TITLE
[Feature Request]:  Support for structured text generation via outlines lib.

### ISSUE THREAD

**Issue by Tanmaypatil123** [run-llama/llama_index#11824]
### Feature Description

Outlines provides ways to control the generation of language models to make their output more predictable.

following is the example of how outlines can be used for structured text generation task :

```python
import outlines

model = outlines.models.transformers("WizardLM/WizardMath-7B-V1.1")

prompt = "<s>result of 9 + 9 = 18</s><s>result of 1 + 2 = "
answer = outlines.generate.format(model, int)(prompt)
print(answer)
# 3

prompt = "sqrt(2)="
generator = outlines.generate.format(model, float)
answer = generator(prompt, max_tokens=10)
print(answer)
# 1.41421356
```

Github repo link : [outlines](https://github.com/outlines-dev/outlines)

### Reason

current implementation of llamaindex model wrappers for OpenAI gpt's and HuggingFace's open source models doesn't support structured output generation 

### Value of Feature

it will be helpful for generating more robust, formatted and structured output by RAG .

**Comment by sriram-1** [comment]
Please assign this task to me. Would like to work on this. Had used outlines library as part of my work earlier.

**Comment by logan-markewich** [comment]
@Tanmaypatil123 if you are up for it, outlines would fit well with the `program` integrations (i.e. pydantic program, guidelines program, llm format enforcer program all exist)

I think the hard part will be integrating our LLM classes into a format the outlines works with (otherwise, the model will get loaded into memory more than once)

**Comment by Tanmaypatil123** [comment]
hey @logan-markewich  can we add wrapper around huggingface LLM models which will work the same as outlines or can we add other community module which will support outlines with huggingface models?

**Comment by logan-markewich** [comment]
@Tanmaypatil123 Yea we definitely could add an `OutlineLLM` class or similar, not a bad idea, assuming their LLM class can still do normal completions. 

Each `LLM` class has a `llm.structured_predict()` or `llm.astructured_predict()` method, we could override these methods in a new class to use the outlines method for structured output

**Comment by sriram-1** [comment]
@logan-markewich , could I start working on this feature request.

**Comment by logan-markewich** [comment]
Go for it @sriram-1
