### ISSUE TITLE
[Question]: How do you access and customize the prompts for an instance of CondensePlusContextChatEngine?

### ISSUE THREAD

**Issue by Turkzilla** [run-llama/llama_index#11837]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How do I access, customize or update prompts for an implementation of "CondensePlusContextChatEngine"? Any samples? I tried everything on samples docs but it has no 'update_prompts' attribute .

**Comment by Turkzilla** [comment]
@dosu-bot: Is it possible to customize the prompts without having to intercept the nice abstractio llamaindex provides as_chat_engine?
```
from app.engine.index import get_index

def get_chat_engine():
    return get_index().as_chat_engine(
        similarity_top_k=3, chat_mode="condense_plus_context"
    )
```
    
How could I cuustomize prompts while keeping this flow functional?

**Comment by Turkzilla** [comment]
@dosu-bot: How would I implement chat history in this context? And if I wanted to manually pass history, what would be the format?

**Comment by logan-markewich** [comment]
You can also pass the chat history on every chat() call

`chat_engine.chat("hello", chat_history=[<list of ChatMessage>])`

**Comment by Turkzilla** [comment]
@dosu-bot: I get this error with every try:
```
llama_index/core/memory/chat_memory_buffer.py", line 160, in <genexpr>
    msg_str = " ".join(str(m.content) for m in chat_history[-message_count:])
                           ^^^^^^^^^
AttributeError: 'dict' object has no attribute 'content'```

**Comment by Turkzilla** [comment]
@dosu-bot: Is there a way to integrate the HuggingFaceEmbedding with metadata extractors? Objective is to generate local embeddings with metadata

```
async def create_extractors():
    embed_model = HuggingFaceEmbedding()
    llm = OpenAI("gpt-3.5-turbo")
    """Create async extractors for text processing."""
    text_splitter = TokenTextSplitter(
        separator=" ", chunk_size=512, chunk_overlap=128)
    title_extractor = TitleExtractor(nodes=5)
    summary_extractor = SummaryExtractor(llm=embed_model)
    return text_splitter, title_extractor, summary_extractor```

**Comment by Turkzilla** [comment]
@dosu-bot: Can you provide exmpales for using HuggingFace, say `HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")` and the `SimpleDirectoryReader` to generate local embeddings and to use extractors without sending them to OpenAI. Such as `TitleExtractor(nodes=5)`, `summary_extractor = SummaryExtractor()`? Basically, use HuggingFace to extract metadata as well as generating embeddings to store into local vector store.

**Comment by Turkzilla** [comment]
@dosu-bot: So what are the the correct arguments to use HuggingFaceEmbedding for SummaryExtractor? Passing llm is complaining about "model_name" not being valid argument, using your pattern, defaults to OpenAI.

**Comment by Turkzilla** [comment]
@dosu-bot: Can same llm be used for embedding and metadata extraction? Passing it for embedding via HuggingFaceEmbedding and passing it for extractions as llm instance? like a BGE llm?

**Comment by Turkzilla** [comment]
@dosu-bot: What llms other than OpenAI, especially one that can be used locally does llamaindex support for metadata extraction? Take the example here: [Metadata Extractors](https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_metadata_extractor/)

**Comment by Turkzilla** [comment]
@dosu-bot: Is there a way to avoid POSTing to OpenAI for chat completions and keep that local?
