### ISSUE TITLE
[Question]: How can I get the sources when I query my Retriever Query Engine

### ISSUE THREAD

**Issue by sohilbhatia** [run-llama/llama_index#11834]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

## Was wondering if there is a way to figure out what vectors/sources Raptor is pulling from when I query my query engine or if there is a way to do it.

Currently I have 

```
raptor_pack = RaptorPack(
          [],
          embed_model=OpenAIEmbedding(
              model="text-embedding-3-small"
          ),  # used for embedding clusters
          llm=OpenAI(model="gpt-3.5-turbo", temperature=0.1),  # used for generating summaries
          vector_store=vector_store,  # used for storage
          similarity_top_k=2,  # top k for each layer, or overall top-k for collapsed
          mode="collapsed",  # sets default mode
          transformations=[
              SentenceSplitter(chunk_size=400, chunk_overlap=50)
          ],  # transformations applied for ingestion
      )
  
  query_engine = RetrieverQueryEngine.from_args(
          raptor_pack.retriever, llm=OpenAI(model="gpt-3.5-turbo", temperature=0.7)
      )
  
      response = query_engine.query(query) 
```

I'm wondering if there is a way to access what those top 2 (k) vectors are when RAPTOR answers my question as I want to provide the answer and also link sources. I've done this before with retrieval and nodes but I was wondering if there is a way to do this when querying the engine. I am using a ChromaDB vector store.

**Comment by sohilbhatia** [comment]
@dosu-bot how would I look into the metadata of each NodeWithScore object?

**Comment by logan-markewich** [comment]
print(response.source_nodes)

print(response.source_nodes[0].metadata)

print(response.source_nodes[0].text)
