### ISSUE TITLE
[Question]: How to customize the use of third-party proxy OPENAI-BASE-URL and OPENAI-API_KEY with openai in the llamaindex framework

### ISSUE THREAD

**Issue by xjspace** [run-llama/llama_index#11838]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to customize the use of third-party proxy OPENAI-BASE-URL and OPENAI-BASE-URL with openai in the llamaindex framework
.env 
OPENAI-BASE-URL=
OPENAI-BASE-URL=

**Comment by logan-markewich** [comment]
You can set in the class

`OpenAI(..., api_base="..", api_key="...")`
`OpenAIEmbedding(..., api_base="..", api_key="...")`
