### ISSUE TITLE
[Documentation]: Update GithubRepositoryReader documentation

### ISSUE THREAD

**Issue by kaushalpowar** [run-llama/llama_index#11845]
### Documentation Issue Description

I was referring [this](https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo.html) for Github repo reader.

I got this error: 
![Screenshot 2024-03-12 at 2 05 11 PM](https://github.com/run-llama/llama_index/assets/90775147/8d471cd9-5531-4b72-8c4b-7ce4a3b308f0)

Then I did some changes, 
![Screenshot 2024-03-12 at 2 07 21 PM](https://github.com/run-llama/llama_index/assets/90775147/e37afd1a-90be-4673-a589-d7d059b648b3)

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/data_connectors/GithubRepositoryReaderDemo.html

**Comment by kaushalpowar** [comment]
![Screenshot 2024-03-12 at 2 51 43 PM](https://github.com/run-llama/llama_index/assets/90775147/75775101-7b0a-46a3-82c1-6b5e4d77ace0)
Getting new error

**Comment by zmusaddique** [comment]
![image](https://github.com/run-llama/llama_index/assets/84737749/24eb4dcf-eadc-432a-9104-2b40aceb37aa)

@kaushalpowar This seems to work now
