### ISSUE TITLE
[Question]: Excuse me, does the llamaindex support custom http calls Embedding and LLM?

### ISSUE THREAD

**Issue by WhyMEliu** [run-llama/llama_index#11842]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have an LLM service that exposes only http post requests. The same goes for Embedding.
How do I use llamaindex to call them?

**Comment by logan-markewich** [comment]
@WhyMEliu implement a custom llm and custom embedding model that wraps your API requests
https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings.html
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html#using-custom-llm-advanced

**Comment by WhyMEliu** [comment]
Thank you very much for your help.

**Comment by xjw1001001** [comment]
> @WhyMEliu implement a custom llm and custom embedding model that wraps your API requests https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings.html https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html#using-custom-llm-advanced

Hi Logan, Sorry to open this issue again.

If I build custom LLM from this way, and I use this LLM with response_synthesizer: tree summarize,
How can I make this LLM can be called by tree summarize async?

**Comment by logan-markewich** [comment]
@xjw1001001 you'd have to define the async method in the custom LLM (check out the base class for what I mean)

`async def acomplete()`

`async def achat()`

Etc.

For these methods to be truly async (and not fake async) there should be some await used in these methods

**Comment by xjw1001001** [comment]
@logan-markewich  Hi Logan, thank you for your advice. Here is my implementation for reference

class Claude3_Sonnet(CustomLLM):
    context_window: int = 180000
    num_output: int = 4000
    model_name: str = "custom"
    dummy_response: str = "My response"
    system_message: str = "You are a helpful assistant"
    api_key: str

    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=self.context_window,
            num_output=self.num_output,
            model_name=self.model_name,
        )

    @llm_completion_callback()
    def complete(self, prompt: str, system_message: str ="None", **kwargs: Any) -> CompletionResponse:
        api_url = "https://?????/gpt/v2/claude-3-sonnet-20240229-v1"
        if not self.api_key:
            raise ValueError("API key is not set.")
        if system_message== "None":
            system_message = self.system_message
        headers = {"X-APIKey": self.api_key}
        payload = {
            "max_tokens": self.num_output,
            "messages": [{"role": "user", "content": prompt}],
            "system": system_message,
            "anthropic_version": "bedrock-2023-05-31"
        }

        response = requests.post(api_url, headers=headers, json=payload)
        if response.status_code == 200:
            response_text = response.json().get("content", [{}])[0].get("text", "")
            return CompletionResponse(text=response_text)
        else:
            return CompletionResponse(text=f"Error: {response.status_code} - {response.reason}")

    @llm_completion_callback()
    def stream_complete(self, prompt: str, **kwargs: Any) -> CompletionResponseGen:
        raise NotImplementedError("This method has not been implemented yet.")

    @llm_completion_callback()
    async def acomplete(self, prompt: str, system_message: str = "None", **kwargs: Any) -> CompletionResponse:
        api_url = "https://???????/gpt/v2/claude-3-sonnet-20240229-v1"
        if not self.api_key:
            raise ValueError("API key is not set.")
        if system_message == "None":
            system_message = self.system_message
        headers = {"X-APIKey": self.api_key}
        payload = {
            "max_tokens": self.num_output,
            "messages": [{"role": "user", "content": prompt}],
            "system": system_message,
            "anthropic_version": "bedrock-2023-05-31"
        }

        async with httpx.AsyncClient() as client:
            response = await client.post(api_url, headers=headers, json=payload)
            if response.status_code == 200:
                response_text = response.json().get("content", [{}])[0].get("text", "")
                return CompletionResponse(text=response_text)
            else:
                # Use httpx.codes to get a textual reason for the status code
                reason_phrase = httpx.codes.get_reason_phrase(response.status_code)
                return CompletionResponse(text=f"Error: {response.status_code} - {reason_phrase}")

**Comment by xjw1001001** [comment]
@logan-markewich 

Update: Need to add retry and max time for the code:

`
    @llm_completion_callback()
    async def acomplete(self, prompt: str, system_message: str = "None", **kwargs: Any) -> CompletionResponse:
        api_url = "https://???????/gpt/v2/claude-3-sonnet-20240229-v1"
        if not self.api_key:
            raise ValueError("API key is not set.")
        if system_message == "None":
            system_message = self.system_message
        headers = {"X-APIKey": self.api_key}
        payload = {
            "max_tokens": self.num_output,
            "messages": [{"role": "user", "content": prompt}],
            "system": system_message,
            "anthropic_version": "bedrock-2023-05-31"
        }

        # Define an inner async function for making the HTTP request with retries and timeout
        @backoff.on_exception(backoff.expo,
                            httpx.ReadTimeout,
                            max_tries=3)
        async def make_request_with_retries():
            # Set a custom timeout (e.g., connect=5.0 seconds, read=10.0 seconds)
            timeout = httpx.Timeout(120)
            async with httpx.AsyncClient(timeout=timeout) as client:
                response = await client.post(api_url, headers=headers, json=payload)
                return response

        # Call the inner function
        response = await make_request_with_retries()
        if response.status_code == 200:
            response_text = response.json().get("content", [{}])[0].get("text", "")
            return CompletionResponse(text=response_text)
        else:
            # Use httpx.codes to get a textual reason for the status code
            reason_phrase = httpx.codes.get_reason_phrase(response.status_code)
            return CompletionResponse(text=f"Error: {response.status_code} - {reason_phrase}")

`

**Comment by AkshitGulyan** [comment]
Hi @WhyMEliu 
How are you running the agent finally
I am using agent.run() but it is calling the stream function of my customLLM class which is not functioning properly for the tool calling. Is there any way I can call the agent so that it will call another method like chat().
Can you please help me around this? I have some more questions too regarding the CustomLLM class
