### ISSUE TITLE
[Feature Request]: LlamaParse + SimpleDirectoryReader output 1 document，if can output markdown by pages

### ISSUE THREAD

**Issue by SmileLollipop** [run-llama/llama_index#11850]
### Feature Description

LlamaParse + SimpleDirectoryReader output 1 document，if can output markdown by pages

### Reason

 parser = LlamaParse(
    result_type="markdown",  # "markdown" and "text" are available
    verbose=True,
    )
    file_extractor = {".pdf": parser}
    docs = SimpleDirectoryReader(
        input_files=[pdf_file_path], file_extractor=file_extractor,recursive=True
    ).load_data(show_progress=True)
    print(len(docs))

**Comment by anoopshrma** [comment]
LlamaParse has Json mode that you can try with. I havent tried this but try passing markdown as result_type and fetch json result. See if it fulfills your requirements.

https://github.com/run-llama/llama_parse/blob/main/examples/demo_json.ipynb

lmk, Thanks!
