### ISSUE TITLE
[Question]: Improving Performance for Adding 75k Relationships and Ensuring System Functionality

### ISSUE THREAD

**Issue by mavericb** [run-llama/llama_index#11869]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm currently working on a feature where I need to add approximately 75,000 relationships using the `index.upsert_triplet_and_node()` function in our system. While implementing this, I've noticed that the process is quite slow, and I'm concerned about the system's ability to handle such a large number of relationships efficiently.

The code snippet I'm using is as follows:

```python
index.upsert_triplet_and_node((name, 'BELONGS_TO', category_name), user_node, include_embeddings=True)
```

I'd like to optimize this process to make it faster without compromising the system's functionality. Additionally, I'm curious about potential limitations or thresholds where the system may stop working as expected due to the high volume of relationships being added.

To be explicit, I am not using `from_documents`. I am building a graph and need to add the tuples with `upsert_triplet_and_node`.

Any insights, tips, or best practices on how to make this process more efficient and ensure the system can handle adding 75k relationships would be greatly appreciated. Thank you!

**Comment by mavericb** [comment]
Will something like this work?
```
from concurrent.futures import ThreadPoolExecutor
from typing import List, Tuple
from llama_index.core.schema import BaseNode

class KnowledgeGraphIndex(BaseIndex[KG]):
    # ... existing code ...

    def parallel_upsert_triplets_and_nodes(
        self,
        triplets_and_nodes: List[Tuple[Tuple[str, str, str], BaseNode]],
        include_embeddings: bool = False,
        max_workers: int = 10
    ) -> None:
        """
        Perform upserts in parallel for a list of triplets and nodes.

        Args:
            triplets_and_nodes (List[Tuple[Tuple[str, str, str], BaseNode]]):
                A list of tuples containing triplets and corresponding nodes.
            include_embeddings (bool): Option to add embeddings for triplets.
                Defaults to False.
            max_workers (int): The maximum number of threads to use.
                Defaults to 10.
        """
        def upsert(triplet_and_node):
            triplet, node = triplet_and_node
            self.upsert_triplet_and_node(triplet, node, include_embeddings)

        with ThreadPoolExecutor(max_workers=max_workers) as executor:
            executor.map(upsert, triplets_and_nodes)
      ```

**Comment by mavericb** [comment]
can a human please answer or at least telling me that i will not get an answer?

**Comment by mavericb** [comment]
I just learned you're just a team of nine in seed stage!! I thought you were tens of Facebook engineers because of the name LLama. Sorry for expecting you to answer me. I also became aware of this just today, which may solve all of our problems https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html Thank you so much for all your work; the system feels so elegantly coded with engineering structure being laid out on all of these problems

**Comment by logan-markewich** [comment]
Yea in general, our knowledge graph stuff is a little unoptimized in a few places.

Working on a larger refactor with better UX

**Comment by mavericb** [comment]
Awesome, cannot wait to try it!!
