### ISSUE TITLE
[Question]: ChatMemoryBuffer got deprecated in 1.10.X?

### ISSUE THREAD

**Issue by konakoudi** [run-llama/llama_index#11863]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the equivalent of llama_index.memory import ChatMemoryBuffer in version 1.10.X?

**Comment by logan-markewich** [comment]
@konakoudi `from llama_index.core.memory import ChatMemoryBuffer`

Do see the migration guide docs for v0.10.x. All our documentation and notebooks are also updated.
https://pretty-sodium-5e0.notion.site/v0-10-0-Migration-Guide-6ede431dcb8841b09ea171e7f133bd77
