### ISSUE TITLE
[Question]: How to customize summary prompt for a tree index

### ISSUE THREAD

**Issue by DataNoob0723** [run-llama/llama_index#11876]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I want to know how to customize summary prompt for a tree index please? Thx a lot!

**Comment by logan-markewich** [comment]
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts
