### ISSUE TITLE
[Bug]: from llama_index.llms.ollama import Ollama ModuleNotFoundError: No module named 'llama_index.llms.ollama'

### ISSUE THREAD

**Issue by iaoxuesheng** [run-llama/llama_index#11886]
### Bug Description

Traceback (most recent call last):
  File "/cpfs01/zhuhai/home/qianlab03/rjs/llm/python/main.py", line 34, in <module>
    from llama_index.llms.ollama import Ollama
ModuleNotFoundError: No module named 'llama_index.llms.ollama'

### Version

0.10.19

### Steps to Reproduce

no

**Comment by logan-markewich** [comment]
@iaoxuesheng `pip install llama-index-llms-ollama`

Check out https://llamahub.ai for all packages/integrations.
