### ISSUE TITLE
Modules not found after migration to v0.10

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#11891]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wanted to wait a little bit before migrating to v0.10 in order to minimize the risk of bugs but still got confronted to a problem :(

I tried to follow the documentation for a full migration here https://docs.llamaindex.ai/en/latest/getting_started/v0_10_0_migration.html. 

Specifically, I created a fresh miniconda environment with python 3.10.0, then 

`pip install llama-index
`
which installed v0.10.19

then I used the cli tool to migrate:

`llamaindex-cli upgrade-file app.py
`
which gave back the messages

```
Module not found: messages_to_prompt
Switching to core
Module not found: completion_to_prompt
Switching to core
Module not found: RagDatasetGenerator
Switching to core
Module not found:
Switching to core
New installs:
pip install llama-index-llms-replicate
pip install llama-index-vector-stores-chroma
pip install llama-index-llms-llama-cpp
pip install llama-index-llms-openai
pip install llama-index-embeddings-huggingface
```

then tried to run my app:

streamlit run app.py

but got the error

 ```
from llama_index.core.llms.llama_utils import messages_to_prompt, completion_to_prompt
ModuleNotFoundError: No module named 'llama_index.core.llms.llama_utils'
```

Did the migration tool update the module name in a wrong way? And what does it mean by "New installs: pip commands"? Should I run these commands? I thought running `pip install llama-index` in a fresh environment would install everything I need.

**Comment by logan-markewich** [comment]
@stephanedebove maybe its not clear, but its printing packages that you need to install, as well as updating imports for you

```
pip install llama-index-llms-replicate
pip install llama-index-vector-stores-chroma
pip install llama-index-llms-llama-cpp
pip install llama-index-llms-openai
pip install llama-index-embeddings-huggingface
```

`pip install llama-index` just installs a starter bundle of integrations. Every integration is its own package.

**Comment by logan-markewich** [comment]
Happy to help with any migration pains. This specific import maybe didn't get migrated completely (just an edge case) -- should be 
`from llama_index.llms.llama_cpp.llama_utils import messages_to_prompt, completion_to_prompt`


For example, I linked a quick notebook here showing some relevant installs and imports.

https://colab.research.google.com/drive/1NVNZR8ULFdIuTEOUTnOKCgxgdpMaV-Jv?usp=sharing


https://llamahub.ai also lists all integrations/imports/installs

**Comment by stephanedebove** [comment]
ok so yes it looks like this import was not migrated completely. With the line you give it works.

I also installed the other packages. I guess a message a bit more explicit than "New installs:" would be nice.

To complete my migration, can you tell me what happens now if I do:

```
llm = LlamaCPP(
            model_path=modele
)
Settings.llm = llm
```
and then use a query_engine to query my docs.

With the new "lazy" loading, is the model loaded on the LlamaCpp() call, the Settings.llm call, or the query_engine.query() call?

**Comment by logan-markewich** [comment]
It's loaded on the LlamaCPP() call. The lazy loading is for original defaults.

If you don't pass in the llm to as_query_engine() call, then it will pull from what you put on settings
