### ISSUE TITLE
[Bug]: Unable to set node_id attribute of TextNode object

### ISSUE THREAD

**Issue by avi9839** [run-llama/llama_index#11909]
### Bug Description

I am trying to create a custom TextNode object and want to reset the node_id of object lator but it throws the following value error:

ValueError: "TextNode" object has no field "node_id" .

### Version

v0.10.19

### Steps to Reproduce

`from llama_index.core.schema import TextNode

node = TextNode(
                text='Custom data',
                id_ = 'abc'
            )

print(f"Node id: {node.node_id}")
###### Node id: 'abc'

node.node_id = '123'`

### Relevant Logs/Tracbacks

```shell
File ~/anaconda3/envs/app_env/lib/python3.9/site-packages/pydantic/main.py:357, in pydantic.main.BaseModel.__setattr__()

ValueError: "TextNode" object has no field "node_id"
```

**Comment by logan-markewich** [comment]
It's really only there for backwards compatibility 

`node.id_ ="124"`

**Comment by avi9839** [comment]
> It's really only there for backwards compatibility
> 
> `node.id_ ="124"`

@logan-markewich  Thank you for quick response, i verified and it works for me.
But i suggest to update the documentation - https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_nodes.html#customizing-the-id
