### ISSUE TITLE
[Bug]: black-docs-py issue for notebooks

### ISSUE THREAD

**Issue by DoganK01** [run-llama/llama_index#11904]
### Bug Description

I fixed a problem in a notebook but failed while checking linting 

black-docs-py............................................................Failed

I had the same issue with other pull request too (created a new notebook example)

### Version

v0.10.10

### Steps to Reproduce

#11880 you can check the pull request here

**Comment by logan-markewich** [comment]
you just have to add the file again after changes are made

`make lint`
...
```
black-docs-py............................................................Failed
- hook id: black-jupyter
- files were modified by this hook

reformatted docs/examples/pipeline/query_pipeline_sql.ipynb

All done! ✨ 🍰 ✨
1 file reformatted, 427 files left unchanged.
```

`git add docs/examples/pipeline/query_pipeline_sql.ipynb`

**Comment by DoganK01** [comment]
I did lol. Before creating a thread.
