### ISSUE TITLE
[Bug]: ValueError:  ****** Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY. Original error: No API key found for OpenAI. Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization. API keys can be found or created at https://platform.openai.com/account/api-keys  Consider using embed_model='local'. Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules ******

### ISSUE THREAD

**Issue by merterbak** [run-llama/llama_index#11900]
### Bug Description

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/core/embeddings/utils.py](https://r2onflmoun-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240311-060139_RC00_614606380#) in resolve_embed_model(embed_model, callback_manager)
     58             embed_model = OpenAIEmbedding()
---> 59             validate_openai_api_key(embed_model.api_key)
     60         except ImportError:

6 frames
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/core/embeddings/utils.py](https://r2onflmoun-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20240311-060139_RC00_614606380#) in resolve_embed_model(embed_model, callback_manager)
     64             )
     65         except ValueError as e:
---> 66             raise ValueError(
     67                 "\n******\n"
     68                 "Could not load OpenAI embedding model. "

ValueError: 
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options:

### Version

0.10.18

### Steps to Reproduce

from llama_index.core import VectorStoreIndex, download_loader
from pathlib import Path

**Comment by sandu345** [comment]
I'm using fine tuned Huggingface LLM instead of Openai. What is the solution above error in this situation?

**Comment by aprv-tradelyncs** [comment]
@sandu345 Did you find any solution for this issue?
