### ISSUE TITLE
[Question]: Are treeSummarizer calling multiple LLM sessions simultaneuously? If I retrieved 2000 chunks, how is the speed performance of treeSummarizer and compact_and_refine? 

### ISSUE THREAD

**Issue by xjw1001001** [run-llama/llama_index#11903]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I retrieved 2000 chunks, how is the speed performance of treeSummarizer and compact_and_refine? 
Are treeSummarizer calling multiple LLM sessions simultaneuously?

**Comment by logan-markewich** [comment]
`TreeSummarize` will repack nodes so that each LLM call contains as much context as possible, and each layer in the summary tree will be run async/concurrently
