### ISSUE TITLE
[Question]: Using react agent with sql query tool and vector query index but it is not giving proper response for vector query index

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [run-llama/llama_index#11906]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 I am Using react agent with tools as 1. sql query , 2. vector query  but it is not giving proper response for vector query index meaning it is not using source documents for response . It seems react prompt doesn't have custom prompt . How to modify React prompt ?

**Comment by logan-markewich** [comment]
Should be able to use this pattern in latest versions to customize the react prompt
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern.html#getting-and-setting-custom-prompts
