### ISSUE TITLE
[Question]:  Implications of making extract_table_summaries in MarkdownElementNodeParser optional

### ISSUE THREAD

**Issue by mlkorra** [run-llama/llama_index#11915]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently, I see that whenever `MarkdownElementNodeParser` is used, it inherently requires an LLM to extract table summaries, can we make it optional, when the requirement is only to extract the tables without any summary generation? What would be the implications of that on the performance of the Retrieval Engine?

```
def get_nodes_from_node(self, node: TextNode) -> List[BaseNode]:
        """Get nodes from node."""
        elements = self.extract_elements(
            node.get_content(),
            table_filters=[self.filter_table],
            node_id=node.id_,
        )
        table_elements = self.get_table_elements(elements)
        # extract summaries over table elements
        self.extract_table_summaries(table_elements)
        # convert into nodes
        # will return a list of Nodes and Index Nodes
        return self.get_nodes_from_elements(elements, node.metadata)
```

**Comment by logan-markewich** [comment]
The summaries are used directly for retrieval. Without, there is no "retrieve a table by its summary and then replace with its actual table" process

**Comment by mlkorra** [comment]
@logan-markewich Yes, that makes sense. Meanwhile i was looking to extract the tables from the pdf on sample pdf with tables (attached image)  (modifying the `get_nodes_from_node` function to print the table elements) , but it doesn't return any tables and only prints an empty list. What might be the issue here?

![image](https://github.com/run-llama/llama_index/assets/18375776/3ff405dc-9537-4bf0-8f62-03328949a1c1)

**Comment by logan-markewich** [comment]
What did you use to parse the document? I would expect something like llamaparse to work fine here

**Comment by mlkorra** [comment]
sorry for the late reply, I was using llamaparse for extracting the table

**Comment by logan-markewich** [comment]
Hmm, it looks like a scanned image, so it relies on OCR, and table extraction may fail

Can you share the actual pdf? Or is it actually just that image?

**Comment by mlkorra** [comment]
This is the actual pdf @logan-markewich 
[table.pdf](https://github.com/run-llama/llama_index/files/14730829/table.pdf)
