### ISSUE TITLE
query_engine.query Function Not Producing Any Response

### ISSUE THREAD

**Issue by Deepa2024** [run-llama/llama_index#11925]
### Bug Description

I have encountered an issue with the query_engine.query function in my code, which is part of a defined functio. The purpose of this function is to process a JSON file containing research paper information and utilize a query engine to find possible research paper titles cited within a sentence from the paper.

Expected Behavior:
When the query_engine.query function is called with a specific prompt, it is expected to return a response with the title of the research paper that is being cited or 'pass' if the title cannot be determined.

Current Behavior:
Currently, the query_engine.query function does not return any response when it is invoked. This is unexpected and indicates a problem either with the function call, the query engine setup, or the data provided to the function.

My code is running for long time and it is running continuously.  But not creating any response. 

I need assistance in understanding why the query_engine.query function is not producing any response. Any help to identify the root cause or to provide a fix would be greatly appreciated.

### Version

0.10.19

### Steps to Reproduce

def prompting(file_name,d):

    list1 = []

    list5 = []

    t = train()

    index = t[0]

    rerank = t[1]

    query_engine = index.as_query_engine(similarity_top_k=10, node_postprocessors=[rerank]) # Note we are first selecting 10 chunks.

    with open(file_name, 'r') as f:

        data = json.load(f)

        for domain, papers in data.items():

            for paper_url, info in papers.items():

                paper_title = info["Paper Title"]

                sentences = info["Sentences"]

                for sentence_info in sentences:

                    user_content = sentence_info["Sentence"]

                    paper = sentence_info["Citation"]["Citation Paper Title"]

                    author = sentence_info["Citation"]["Citation Paper Authors"]

                    abstract = sentence_info["Citation"]["Citation Paper Abstract"]

                    list5.append(paper.split(":", 1)[1].strip())

                    r = query_engine.query(f"I have taken a sentence from the research paper titled \"{paper_title}\", give me the title of the possible research paper that this sentence is citing to. If you are not able to come up with the paper title write 'pass'. Don't write anything else. Sentence: \"{user_content}\"").response

                    list1.append(r)

                    print(list1,"\n", list5)

        metrics(d,list1,list5)

        list1.clear()

        list5.clear()

    return

### Relevant Logs/Tracbacks

```shell
No logs are generated. It is running with output file empty.
```

**Comment by logan-markewich** [comment]
What llm are you using? Any way for us to reproduce the issue would be ideal, otherwise I can't help much

**Comment by Deepa2024** [comment]
I am using Llama 2

**Comment by Deepa2024** [comment]
**Just an update query_engine.query() is not prompting me any error but is stuck indefinitely in that line**

`r = query_engine.query(f"I have taken a sentence from the research paper titled \"{paper_title}\", give me the title of the possible research paper that this sentence is citing to. If you are not able to come up with the paper title write 'pass'. Don't write anything else. Sentence: \"{user_content}\"").response`

**Comment by logan-markewich** [comment]
Yea like I said, with no way to reproduce, I can't really help. Llama cpp works fine for me (note that it will be very very slow though, especially if it's running on cpu)

**Comment by Deepa2024** [comment]
Ok after couple of hours. I think I figured out what was the issue : SimpleDirectoryReader in train function is not working as it should. The solution what I did was created separate folder for each single json file for train function and now doing fine tuning for single json instead of all. It worked for me but it did not understand the issue really.
