### ISSUE TITLE
[Question]: Can KnowledgeGraphIndex.from_documents handle a large amount of documents, say around 3000?

### ISSUE THREAD

**Issue by DataNoob0723** [run-llama/llama_index#11929]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can KnowledgeGraphIndex.from_documents handle a large amount of documents, say around 3000? Thx a lot!

**Comment by logan-markewich** [comment]
Yes, but it will be slow and expensive.
