### ISSUE TITLE
[Question]: What does 'embedding_mode' parameter mean in .as_query_engine method

### ISSUE THREAD

**Issue by DataNoob0723** [run-llama/llama_index#11928]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What does 'embedding_mode' parameter mean in .as_query_engine method? Thx a lot!

**Comment by logan-markewich** [comment]
The bot is correct

**Comment by logan-markewich** [comment]
I think you meant retriever mode? For what index? 

The bot is mostly correct, it's talking about retriever mode for a knowledge graph index

**Comment by DataNoob0723** [comment]
> I think you meant retriever mode? For what index?
> 
> The bot is mostly correct, it's talking about retriever mode for a knowledge graph index

Yes, and the bot's answer made sense! Thx!
