### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by benisalla** [run-llama/llama_index#11934]
### Feature Description

i could not use PrevNextPostProcessor with index what is build from vectorstore, so the problem is when i fill docstore attribute of PrevNextPostProcessor with index.docstore.

### Reason

    index = VectorStoreIndex.from_vector_store(
        vector_store=vector_store,
        storage_context=storage_context,
        use_async=True,
    )
    node_postprocessor = PrevNextNodePostprocessor(
        docstore=index.docstore, # i guess the issue is here
        num_nodes=2,
        mode="both",
    )

### Value of Feature

node_id not found when the PrevNextNodePostProcessor starts to work

**Comment by logan-markewich** [comment]
When using a remote vector db, the docstore is not automatically populated.

I would suggest just populating it and persisting it yourself

```
from llama_index.core.storage.docstore import SimpleDocumentStore

docstore = SimpleDocumentStore()

nodes = SentenceSplitter(chunk_size=1024, chunk_overlap=20)(documents)

docstore.add_documents(nodes)

index = VectorStoreIndex(nodes=nodes, ...)

docstore.persist("./docstore.json")

docstore = SimpleDocumentStore.from_persist_path("./docstore.json")
```

**Comment by benisalla** [comment]
but i have preprocessed about 20,000 files of 1M text and stored it in vectore database, it is not possible for me to re-do it everytime. 

please i want an alternative way to use this PrevNextNodePostProcessor like: 

1) how can i load nodes from index = VectoreStoreIndex.from_vectore_store()

2) how can i customize PrevNextNodePostProcessor to load nodes that are with ids that are mentioned in the retrieved nodes

any suggestion ? 

thank you so much in advance @logan-markewich

**Comment by benisalla** [comment]
or how to fill storageContext from vector_store or from any remote vector database ? i think this is another way i can solve it, but i found the documentation a little bit difficult , any help if this is a logical solution ?

**Comment by logan-markewich** [comment]
You don't have to redo it every time, it only has to be done once. 

You can't fill a docstore from an existing remote vector db (at least not without a lot of hacky methods/code)

**Comment by AutoScrape123TX** [comment]
@benisalla what is your final workaround about this I got the same issue and I was thinking I was going to use the relationships stored in vector db...
