### ISSUE TITLE
[Documentation]: Broken links in QnA page

### ISSUE THREAD

**Issue by rahulporuri** [run-llama/llama_index#11936]
### Documentation Issue Description

Links to "Example of search over documents" in [Where to Search](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a/root.html#where-to-search) and "Combining multiple sources" in [How to Search](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a/root.html#how-to-search) are broken.

### Documentation Link

https://docs.llamaindex.ai/en/stable/use_cases/q_and_a/root.html

**Comment by rahulporuri** [comment]
Both of these links worked on the previous minor version (0.9). See https://docs.llamaindex.ai/en/v0.9.48/use_cases/q_and_a/root.html but they both linked to the same heading, which now doesn't exist, https://docs.llamaindex.ai/en/v0.9.48/understanding/putting_it_all_together/q_and_a.html#combine-multiple-sources

**Comment by anoopshrma** [comment]
Thanks for bringing this into our attention @rahulporuri ! 

It'll be updated/fixed soon!!

**Comment by sharsha315** [comment]
Hi, is this issue still open. Can I have the opportunity to work on this issue.
