### ISSUE TITLE
[Question]: cannot import name 'LinearAdapterEmbeddingModel' from 'llama_index.core.embeddings'

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#11932]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

from llama_index.core.embeddings import LinearAdapterEmbeddingModel
embed_model2 = LinearAdapterEmbeddingModel(base_embed_model, "/content/drive/MyDrive/model_output_test")
error:
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

[<ipython-input-41-c8782586bc96>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from llama_index.core.embeddings import LinearAdapterEmbeddingModel
      2 embed_model2 = LinearAdapterEmbeddingModel(base_embed_model, "/content/drive/MyDrive/model_output_test")

ImportError: cannot import name 'LinearAdapterEmbeddingModel' from 'llama_index.core.embeddings' (/usr/local/lib/python3.10/dist-packages/llama_index/core/embeddings/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
------------------------------

Does someone know how to fix this?

**Comment by logan-markewich** [comment]
Nomic has their own HF embedding class (it requires a special pooling method as well)

`pip install llama-index-embeddings-nomic`

`from llama_index.embeddings.nomic import NomicHFEmbedding`

**Comment by logan-markewich** [comment]
`pip install llama-index-embeddings-adaptor`

`from llama_index.embeddings.adaptor import AdapterEmbeddingModel`

Not sure where you saw `LinearAdapterEmbeddingModel` -- it doesn't exist when I ctrl-f the entire repo
