### ISSUE TITLE
[Question]: Image Document and how to use it

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#11933]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

As per my understanding, I think ImageDocument is used to read both text and image from a document. If yes, then how to use it. If not, what is its purpose and its use case

**Comment by Prem-Nitin** [comment]
@dosu-bot then how do i extract images from word document with metadata and caption

**Comment by logan-markewich** [comment]
Yea, certain readers will produce ImageDocuments. The bot is correct.
