### ISSUE TITLE
[Feature Request]: Expose transformers.AutoModel.from_pretrained(safe_serialization=True) argument to HuggingFaceEmbedding

### ISSUE THREAD

**Issue by hkristof03** [run-llama/llama_index#11935]
### Feature Description

Currently the [Nomic AI](https://huggingface.co/nomic-ai/nomic-embed-text-v1.5) embeddings cannot be used with `HuggingFaceEmbedding`. The reason is that the `transformers.AutoModel.from_pretrained(safe_serialization=True)` parameter is not exposed to `HuggingFaceEmbedding`, therefore, the instantiation will fail.

This parameter should be added [here](https://github.com/run-llama/llama_index/blob/ff51e2cbf9815a44ebade9a1382216435d7f4bc8/llama-index-integrations/embeddings/llama-index-embeddings-huggingface/llama_index/embeddings/huggingface/base.py#L82).

### Value of Feature

[Nomic AI](https://huggingface.co/nomic-ai) embedding models could be used.

**Comment by logan-markewich** [comment]
@hkristof03  Nomic has their own HF embedding class (it requires a special pooling method as well)

`pip install llama-index-embeddings-nomic`

`from llama_index.embeddings.nomic import NomicHFEmbedding`

**Comment by hkristof03** [comment]
Thanks for the suggestions @logan-markewich . Unfortunately, this 3rd party extension seems like a mess.
When I install it with your instruction and trying to run the import, it fails.

I had to import from the base like `from llama_index.embeddings.nomic.base import NomicHFEmbedding`

But even after that, this fails

`NomicHFEmbedding(model_name="nomic-ai/nomic-embed-text-v1.5", trust_remote_code=True)`

Could you share a working example?

**Comment by logan-markewich** [comment]
I've never actually tried to use it lol I just know nomic contributed it themselves
