### ISSUE TITLE
[Question]: How to integrate models in tranformers in llama index

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_index#11948]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I integrate other models for text to sql conversion. For example -How can I integrate "defog/sqlcoder-7b-2" in NLSQLTableQueryEngine method.

**Comment by logan-markewich** [comment]
We have a few examples. The main thing is ensuring proper prompt formatting

Here's an example with zephyr
https://colab.research.google.com/drive/1C55IGyJNDe14DsHkAIIpIjn76NvK5pc1?usp=sharing#scrollTo=lMNaHDzPM68f
