### ISSUE TITLE
[Bug]:azure_openai Does not support gpt-35-turbo-0125

### ISSUE THREAD

**Issue by matteosdocsity** [run-llama/llama_index#11947]
### Bug Description

within these versions:
```
llama-index==0.10.18
llama-index-llms-openai==0.1.9
llama-index-llms-azure-openai==0.1.5
llama-index-embeddings-openai==0.1.6
llama-index-embeddings-azure-openai==0.1.6
```
and also previous ones seems that `gpt-35-turbo-0125` model coming from Azure OpenAI is not supported.

This seems to be due to `AZURE_TURBO_MODELS` inside `llama_index.llms.openai.utils` that does not contain any reference to `gpt-35-turbo-0125`
```
AZURE_TURBO_MODELS: Dict[str, int] = {
    "gpt-35-turbo-16k": 16384,
    "gpt-35-turbo": 4096,
    # 1106 model (JSON mode)
    "gpt-35-turbo-1106": 16384,
    # 0613 models (function calling):
    "gpt-35-turbo-0613": 4096,
    "gpt-35-turbo-16k-0613": 16384,
}
```

### Version

0.10.18

### Steps to Reproduce

Try to initiate and use the `AzureOpenAI` (`from llama_index.llms.azure_openai import AzureOpenAI`) using the `gpt-35-turbo-0125` model, this error is throwned:

_Unknown model 'gpt-35-turbo-0125'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613_

### Relevant Logs/Tracbacks
The error log is coming from the `ValueError` inside the function `openai_modelname_to_contextsize` inside llama_index.llms.openai.utils
```shell

Unknown model 'gpt-35-turbo-0125'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613
```

**Comment by matteosdocsity** [comment]
@logan-markewich as I reported it's confirmed from the response too the `AZURE_TURBO_MODELS` dictionary in `llama_index.llms.openai.utils` is missing the `gpt-35-turbo-0125` model. Is this an integration in plan to be added or not? The model has been available in some Azure regions since [February](https://learn.microsoft.com/en-us/azure/ai-services/openai/concepts/models#public-cloud-regions-1).

**Comment by logan-markewich** [comment]
@matteosdocsity it just needs to be added to that dict, not a crazy change. I'll get to it at some point. You were the first to notice it wasn't there

**Comment by matteosdocsity** [comment]
@logan-markewich I'just created the [pull request](https://github.com/run-llama/llama_index/pull/11956)

**Comment by logan-markewich** [comment]
merged + published
