### ISSUE TITLE
[Question]: How to change the text to sql model in NLSQLTableQueryEngine

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_index#11944]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can you confirm if I provide GPT4 in Settings.llm, does NLSQLTableQueryEngine method uses the same for text to sql conversion? If not, how can I configure it.

**Comment by sreenivasanm6** [comment]
Do we have any SQL agents in llama index something similar to the one we have in langchain?

**Comment by logan-markewich** [comment]
@sreenivasanm6 it does use the settings llm. you can also pass it in directly to the query engine `llm=llm`

There is no sql agent, but you can give a sql query engine as a tool to an agent.
