### ISSUE TITLE
[Bug]: Unable to find ChromaVectorStore

### ISSUE THREAD

**Issue by avi9839** [run-llama/llama_index#11945]
### Bug Description

Unable to import ChromaVectorStore

### Version

v0.10.19

### Steps to Reproduce

from llama_index.vector_stores.chroma import ChromaVectorStore

**Comment by logan-markewich** [comment]
Did you run `pip install llama-index-vector-stores-chroma` ?

**Comment by avi9839** [comment]
@logan-markewich Thank you for response, it works now with above suggestions.
