### ISSUE TITLE
[Question]: in RAG with vector DB, how to Weightage / Prioritize when multiple vector DBs are available?

### ISSUE THREAD

**Issue by Kushagra0409** [run-llama/llama_index#11943]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Suppose I have created seperate entries into different vector Databases in my local elasticsearch instance, and now my query matches keywords from multiple databases, hence I must choose the response which most likely answers the query. 
So my question is, suppose this happens, is there any way we can manage retrievals, so that only the db which most likely answers the question correctly is chosen, instead of taking answers from multiple dbs and giving a hallucinating answer..

**Comment by logan-markewich** [comment]
You could describe each DB and use a router
https://docs.llamaindex.ai/en/stable/module_guides/querying/router/root.html#using-as-a-retriever

Or you can weight it with query fusion
https://docs.llamaindex.ai/en/stable/examples/retrievers/relative_score_dist_fusion.html
