### ISSUE TITLE
[Question]: VectorStoreIndex from pre-defined embeddings uses API calls?

### ISSUE THREAD

**Issue by MaartenCVonk** [run-llama/llama_index#11950]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am confused why initializing VectorStoreIndex from pre-defined embeddings costs API calls? That is: I have created my text embeddings manually and I feed the embeddings as nodes to the VectorStoreIndex. Why am I being charged here?: 
```
nodes = [TextNode(text=self.texts[i], id_=str(i), embeddings = self.embeddings[i]) for i in indices]
index = VectorStoreIndex(nodes)
```

**Comment by logan-markewich** [comment]
I think I pointed this out in another issue, but you have a typo, should be `embedding` without the `s`

```
nodes = [TextNode(text=self.texts[i], id_=str(i), embedding= self.embeddings[i]) for i in indices]
index = VectorStoreIndex(nodes)
```
