### ISSUE TITLE
[Bug]: Ingestion cache bigger than 16mb for mongo db

### ISSUE THREAD

**Issue by haarisedhi102** [run-llama/llama_index#11958]
### Bug Description

pymongo.errors.OperationFailure: BSONObj size: 35822606 (0x2229C0E) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { _id: "2e69dfa2cc4913fd27bf8a943d871d735c4916322ce6c3e54d718d2d0eacf017" }, full error: {'ok': 0.0, 'errmsg': 'BSONObj size: 35822606 (0x2229C0E) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { _id: "2e69dfa2cc4913fd27bf8a943d871d735c4916322ce6c3e54d718d2d0eacf017" }', 'code': 10334, 'codeName': 'BSONObjectTooLarge'}

### Version

0.1.19

### Steps to Reproduce

run an ingestion pipeline with mongo as Ingestion Cache

### Relevant Logs/Tracbacks

```shell
pymongo.errors.OperationFailure: BSONObj size: 35822606 (0x2229C0E) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { _id: "2e69dfa2cc4913fd27bf8a943d871d735c4916322ce6c3e54d718d2d0eacf017" }, full error: {'ok': 0.0, 'errmsg': 'BSONObj size: 35822606 (0x2229C0E) is invalid. Size must be between 0 and 16793600(16MB) First element: q: { _id: "2e69dfa2cc4913fd27bf8a943d871d735c4916322ce6c3e54d718d2d0eacf017" }', 'code': 10334, 'codeName': 'BSONObjectTooLarge'}
```

**Comment by haarisedhi102** [comment]
@dosu-bot are there any tweaks that can be done in the Mongodb kv store code to reduce the amount data that gets pushed to mongo at once, it seems like all docs are being added by self._db[collection].bulk_write(new_docs) which is why a  BSON document greater than 16MB is being created

**Comment by lz-chen** [comment]
I am facing the same problem, @haarisedhi102 did you find a good solution for this?

**Comment by haarisedhi102** [comment]
No, we just didnt use ingestion cache, mongo works well as a docstore which gets us most of the way there.
