### ISSUE TITLE
[Feature Request]: Add multimodal llms support to Bedrock

### ISSUE THREAD

**Issue by jc1518** [run-llama/llama_index#11952]
### Feature Description

Claude 3 multimodal LLMs (sonnet, haiku) are available in Bedrock now, we need something like `llama-index-multi-modal-llms-bedrock`to support use case like multimodal RAG with Bedrock.

### Reason

`multi_modal_llms` currently does not cover bedrock.

### Value of Feature

This enables user to build multimodal RAG with models in Bedrock.

**Comment by joao-d-oliveira** [comment]
Commenting to also endorse this request.
It should be easy to make both models ("anthropic.claude-3-haiku-20240307-v1:0", "anthropic.claude-3-sonnet-20240229-v1:0") available at Llama Index.
Let me know if I can contribute somehow.
