### ISSUE TITLE
[Bug]: ValueError                                Traceback (most recent call last) <ipython-input-58-3cefaa2d5692> in <cell line: 6>()       4 from llama_index.legacy import VectorStoreIndex, download_loader       5 from pathlib import Path ----> 6 index = VectorStoreIndex.from_documents(documents,show_progress=True)  5 frames /usr/local/lib/python3.10/dist-packages/llama_index/legacy/node_parser/node_utils.py in build_nodes_from_splits(text_splits, document, ref_doc, id_func)      84             nodes.append(node)      85         else: ---> 86             raise ValueError(f"Unknown document type: {type(document)}")      87       88     return nodes  ValueError: Unknown document type: <class 'llama_index.core.schema.Document'>

### ISSUE THREAD

**Issue by merterbak** [run-llama/llama_index#11953]
### Bug Description

ValidationError: 2 validation errors for HuggingFaceLLM
query_wrapper_prompt -> kwargs -> template_vars
  str type expected (type=type_error.str)
query_wrapper_prompt -> kwargs -> kwargs
  str type expected (type=type_error.str)

### Version

0.10.18

### Steps to Reproduce

from llama_index.legacy.llms import HuggingFaceLLM
llm = HuggingFaceLLM(context_window=4096,
                    max_new_tokens=256,
                    system_prompt=system_prompt,
                    query_wrapper_prompt=query_wrapper_prompt,
                    model=model,
                    tokenizer=tokenizer)

**Comment by logan-markewich** [comment]
I would just use the actual package instead of legacy? You need to use ALL legacy imports, or none at all

`pip install llama-index-llms-huggingface`

`from llama_index.llms.huggingface import HuggingFaceLLM`
