### ISSUE TITLE
How do I incorporate streaming into SimpleMultiModalQueryEngine

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_index#11964]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm building my query engine from low level components: 

Depending on the number of documents my user uploads, I'll construct an index for each uploaded document and fuse them using a QueryFusionRetriever. If one of these indices is a MultiModalVectorStoreIndex (because the user uploads an image), I'll send the retriever to a SimpleMultiModalQueryEngine. 

Despite defining a response_synthesizer with streaming set to True, I cannot get my query engine to stream its replies. The object returned is a "Response" object instead of a "StreamingResponse" object.

How do I allow SimpleMultiModalQueryEngine to stream responses?

**Comment by ravi03071991** [comment]
@tituslhy [SimpleMultiModalQueryEngine](https://github.com/run-llama/llama_index/blob/ca9634e660b91799a86ee9f9f0a697eb236bcefd/llama-index-core/llama_index/core/query_engine/multi_modal.py#L30) currently does not support `streaming` and so you are unable to stream the response.

**Comment by tituslhy** [comment]
I see! Thanks! So the only way to stream response for multimodal query engines is to use the high level API right? index.as_query_engine(streaming=True) where index is a MultiModalVectorStoreIndex type?
