### ISSUE TITLE
[Bug]: How do I load existing Index from Pinecone

### ISSUE THREAD

**Issue by darrenwongtss** [run-llama/llama_index#11960]
### Bug Description

![image](https://github.com/run-llama/llama_index/assets/161011126/f286007a-c7ff-4e9b-84af-380d5122b03f)

### Version

0.10.19

### Steps to Reproduce

Nil

**Comment by darrenwongtss** [comment]
Its not working
![image](https://github.com/run-llama/llama_index/assets/161011126/26fa9ce8-bfd5-4285-8e94-da7c41cbc157)

**Comment by logan-markewich** [comment]
index = VectorStoreIndex.from_vector_store(vector_store)
