### ISSUE TITLE
[Question]: What does the context_str in Tree summarizer store?

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#11963]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

## What does the context_str in the Tree Summarizer store? Could someone please clarify this?

I am using QueryPipeline for RAG implementation, but the summarizer does not seem to work fine. The summarizer requires 2 input keys(query_str and nodes). Then I checked the prompt of the summarizer, it contains query_str and context_str. I printed both of them and came to a conclusion that query_str is the input key only, but the context_str contains the metadata of the node instead of storing its text.

## Also suggest me some alternatives of the summarizer

Also, please suggest if there is an alternative for the summarizer, i need to pass the top node as well as the query_engine output, and want the final output to be the combined information from both of them.

**Comment by logan-markewich** [comment]
Tree summarize will summarize nodes/chunks

The context_str is the text from those nodes/chunks

You can use it like so

```
from llama_index.core.response_synthesizer import TreeSummarize

summarizer = TreeSummarize(llm=llm, use_async=True)

response = summarizer.get_response("Summarize facts about <topic>", ["chunk1", ...])
```
