### ISSUE TITLE
gemma:2b chat model not work

### ISSUE THREAD

**Issue by tdr1991** [run-llama/llama_index#11971]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

hi everyone:
i have use ollama load gemma:2b,if set is_chat_model=True, not work
![no-work](https://github.com/run-llama/llama_index/assets/28622364/e3a34247-971d-46df-9f4a-0fca236f41a0)
if set set is_chat_model=False, it will work
![work](https://github.com/run-llama/llama_index/assets/28622364/60a945d5-3879-4d9d-a775-e9b60609f554)

and i test this pipeline by langchain, it work normally
![chain-w](https://github.com/run-llama/llama_index/assets/28622364/b5542352-f1d0-4042-9a4b-6ee78f31bb5e)

so for gemma:2b, it should request "api/generate" to build rag pipeline ?

**Comment by logan-markewich** [comment]
I guess so? This is more of an Ollama issue and how they handle requests for Gemma. I guess they don't handle chat requests
