### ISSUE TITLE
[Question]: VectorStore deletion - nodes and/or documents

### ISSUE THREAD

**Issue by wdeaderick** [run-llama/llama_index#11978]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Wanted to confirm my understanding of a `VectorStore`'s [delete](https://github.com/run-llama/llama_index/blob/cd6700a274e3c77e41215d39e4b5f8799276a3ef/llama-index-core/llama_index/core/vector_stores/types.py#L279) functionality. I'm particularly interested in the [OpensearchVectorStore](https://github.com/run-llama/llama_index/blob/434de440b6302aa0bee108d0caf71b6522e01eb7/llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py#L439), so I'll use that as an example.

This class' `delete` function accepts `ref_doc_id` as argument; as I understand it, this is meant to be a `Document` ID. Indeed, when building a `VectorStoreIndex` over an `OpensearchVectorStore` and calling e.g. `index.update_ref_doc(Document)`, I see that the `Document`'s ID gets passed as argument.

However, [this](https://github.com/run-llama/llama_index/blob/cd6700a274e3c77e41215d39e4b5f8799276a3ef/llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/tests/test_opensearch_client.py#L157) `OpensearchVectorStore` unit test calls `delete` using a `Node` ID. After merging [this change](https://github.com/run-llama/llama_index/pull/11959/files), `delete` works when given a `Document` ID (previously it was erroring out), but no longer seems to work when given a `Node` ID.

Can this function be called with either a `Node` ID or a `Document` ID? Or is the unit test incorrect? Feel like I'm missing something here. @logan-markewich

**Comment by wdeaderick** [comment]
@logan-markewich if you confirm that this unit test is incorrect, I'll make an MR to fix it so that it tests deletion of `Document`s rather than `Node`s.

**Comment by logan-markewich** [comment]
@wdeaderick indeed, it should only be deleting based on a document ID, rather than a node id. Probably that test should be updated

**Comment by wdeaderick** [comment]
MR updating it https://github.com/run-llama/llama_index/pull/11981
