### ISSUE TITLE
[Bug]: Can't create correct metric type by MilvusVectorStore

### ISSUE THREAD

**Issue by shashade2012** [run-llama/llama_index#11975]
### Bug Description

I just want to create collection by MilvusVectorStore by the following code.

`index_params = {"index_type":"FLAT"}
METRIC_TYPE = 'L2'
vector_store = MilvusVectorStore(collection_name=COLLECTION_NAME,
                                 uri=MILVUS_URL,
                                 dim=DIM,
                                 similarity_metric=METRIC_TYPE,
                                 db_name=DBNAME,
                                 overwrite=True,
                                 index_config=index_params
                                )
storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex(nodes,storage_context=storage_context)`

I just check the metric type in Milvus, it is always 'IP'. Please check this.

### Version

llama-index                              0.10.18

### Steps to Reproduce

just use the following python
vector_store = MilvusVectorStore(collection_name=COLLECTION_NAME,
                                 uri=MILVUS_URL,
                                 dim=DIM,
                                 similarity_metric=METRIC_TYPE,
                                 db_name=DBNAME,
                                 overwrite=True,
                                 index_config=index_params
                                )
to reproduce

**Comment by shashade2012** [comment]
Hi 
thanks for quick reply.
But I already check my input metric is 'L2'.
see picture.
![image](https://github.com/run-llama/llama_index/assets/22316457/bcf41e43-e956-4efa-a010-34c64a38bf24)

**Comment by shashade2012** [comment]
I check the latest code , see the following:
similarity_metrics_map = {"ip": "IP", "l2": "L2", "euclidean": "L2"}
similarity_metric = similarity_metrics_map.get(similarity_metric.lower(), "L2")

There is missing "self.similarity_metric"
It could be root cause.

**Comment by logan-markewich** [comment]
This has since been fixed
