### ISSUE TITLE
[Question]: How to improve the retrieval speed of RAG

### ISSUE THREAD

**Issue by HelloEveryonehh** [run-llama/llama_index#11972]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,I am reaching out to seek your assistance. I've been conducting speed tests for vector retrieval using MilvusVectorStore, utilizing the official document paul_graham_essay.txt as a sample. However, I'm encountering an issue where the retrieval speed is displayed as 2 seconds in VSCode, which is perplexing. I was under the impression that vector retrieval speeds would be measured in milliseconds. Attached below is my code, along with the parameters set for MilvusVectorStore.
```python
import logging
import sys

# Uncomment to see debug logs
# logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
# logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Document
from llama_index.vector_stores.milvus import MilvusVectorStore
from IPython.display import Markdown, display
import textwrap
import openai
documents = SimpleDirectoryReader("./data/paul_graham/").load_data()
print("Document ID:",documents[0].doc_id)
from llama_index.core import StorageContext

index ={
    "params": {"M": 16, "efConstruction": 100}  #
}

search_params ={
    "params":{"ef":64}     
}
vector_store = MilvusVectorStore(
    dim=1536,
    overwrite=True,
    uri="http://localhost:19530",
    similarity_metric="L2",
    index_config = index,
    search_config=search_params
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context
)
retriever = index.as_retriever()
nodes = retriever.retrieve("Who is Paul Graham?")
```
![image](https://github.com/run-llama/llama_index/assets/110333012/0fe7c96a-58cb-4143-ad24-8465b9b4eca3)

In addition to addressing this speed concern, I have a broader query. I am preparing to undertake vector retrieval for approximately 4 million data points, with high requirements for both the speed of retrieval and the recall rate. In light of this, could you possibly provide guidance or suggestions on the optimal vector database or indexing method to employ? Furthermore, if you could share the specific values of the indexing parameters you recommend, it would greatly assist me in fine-tuning my setup to meet my needs.
Your insights and recommendations on this matter would be greatly appreciated.
Thank you for your time and consideration.

**Comment by logan-markewich** [comment]
It could be your search params, it could be openai being slow right now, could be your hardware (since you are running a DB locally)

If I run the same with the default in-memory db, its pretty fast

That's also not really the way I would benchmark runtime. At the very least, measure the start and end times.

This takes `0.15666794776916504 secs`

```python
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader("./docs/examples/data/paul_graham").load_data()

index = VectorStoreIndex.from_documents(documents)

retriever = index.as_retriever()

import time
start = time.time()
nodes = retriever.retrieve("test")
end = time.time()
print(end-start)
```


If I switch to something like qdrant (I've never used milvus, I don't feel like setting it up lol)

```python
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, StorageContext
from llama_index.vector_stores.qdrant import QdrantVectorStore
import qdrant_client

client = qdrant_client.QdrantClient("http://localhost:6333")
vector_store = QdrantVectorStore("test_collection", client=client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

documents = SimpleDirectoryReader("./docs/examples/data/paul_graham").load_data()

index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)

retriever = index.as_retriever()

import time
start = time.time()
nodes = retriever.retrieve("test")
end = time.time()
```

It takes `0.20842194557189941 secs` -- a little slower, but qdrant will scale much better than the default vector db, and this is a small example.
