### ISSUE TITLE
[Question]: Utility of custom_embedding_strs parameter in QueryBundle

### ISSUE THREAD

**Issue by SKashyap1999** [run-llama/llama_index#11976]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What does the custom_embedding_strs paratemeter in the QueryBundle class do exactly? Is the user supposed to give the sub-query strings related to the main-query, as an input to this parameter?

**Comment by logan-markewich** [comment]
It lets the user specify different strings used for retrieval. Maybe you want to use a different string for retrieval vs. synthesizing a response with an LLM
