### ISSUE TITLE
[Feature Request]: Support VoyageAI reranker model

### ISSUE THREAD

**Issue by aabor** [run-llama/llama_index#11980]
### Feature Description

Please, add support to VoyageAI Reranker model "rerank-lite-1".

This is the model description from service provider:
https://docs.voyageai.com/docs/reranker 

### Reason

Need to support different types of Reranker models. Currently, only Cohere reranker is working which is quite expensive.

### Value of Feature

Increase competition between Reranker model providers, reduce the cost.

**Comment by logan-markewich** [comment]
btw, there are many rerankers implemented besides cohere? Colbert, flag embedding, sentence transformer
