### ISSUE TITLE
[Documentation]: Qdrant client comment is outdated

### ISSUE THREAD

**Issue by verdverm** [run-llama/llama_index#11987]
### Documentation Issue Description

```
client = qdrant_client.QdrantClient(
    # you can use :memory: mode for fast and light-weight experiments,
    # it does not require to have Qdrant deployed anywhere
    # but requires qdrant-client >= 1.1.1
    location=":memory:"
    # otherwise set Qdrant instance address with:
    # uri="http://<host>:<port>"                                    <=====  THIS LINE
    # set API KEY for Qdrant Cloud
    # api_key="<qdrant-api-key>",
)
```

The way this is used has changed: https://qdrant.tech/documentation/quick-start/

```
client = qdrant_client.QdrantClient("localhost", port=6333)
```

The comment (with options) seems wrong in a few places

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/vector_stores/QdrantIndexDemo.html

**Comment by sharsha315** [comment]
Hi, if this issue is still open.  I would like to work on it.

**Comment by verdverm** [comment]
Seems so: https://github.com/run-llama/llama_index/blob/main/docs/examples/vector_stores/QdrantIndexDemo.ipynb
