### ISSUE TITLE
[Bug]:  Context/CondensePlusContext Chat Engines do not include context in prompts to OpenAILike / OpenAI api

### ISSUE THREAD

**Issue by sitbk** [run-llama/llama_index#11991]
### Bug Description

I'm attempting to create either a Context or a CondensePlusContext chat engine. I've ran two separate scenarios with the attached code, with two separate results. Running this engine with an active HuggingFaceLLM successfully embeds context in an LLM call and returns an accurate response. Running it against an OpenAILike / OpenAI API accessible via local API such as text-generation-webui does not include context or return accurate results. 

1.  Submitting queries with the attached code to a HuggingFaceLLM model successfully incorporates the index / context in generating an accurate response.
2. Submitting queries with the attached code to an OpenAILike / OpenAI (with base_url set to a local LLM accessible via Text-Generation-WebUI / TabbyAPI API's) does not incorporate the context in the prompt sent **to** the LLM's API. I do see context added to the stdout of the chat_engine.chat call, but it isn't actually added to the prompt received by the API.

Could this be a template issue somewhere? 

Query Engines work fine with the OpenAILike API.

### Version

0.10.18

### Steps to Reproduce

I've attached the relevant snippets of code. The overall project uses Settings.llm to set the LLM / Embed models in the **self.engine_defaults variable.

```
def messages_to_prompt(messages):
    prompt_str = "\n".join([str(x) for x in messages])
    return f"<s>[INST] {prompt_str} [/INST] </s>\n"
  
def completion_to_prompt(completion):
    return f"<s>[INST] {completion} [/INST] </s>\n"

api_llm = OpenAILike(  
            api_base=api_url,  
            timeout=600,  # secs  
            api_key=api_key,  
            is_chat_model=True,
            context_window=4096,
            messages_to_prompt= messages_to_prompt,
            completion_to_prompt= completion_to_prompt,
            additional_kwargs= {
                "top_p": 0.5,
                #"top_k": 40,
            },
)

hf_llm = HuggingFaceLLM(
            context_window=4096,
            max_new_tokens=512,
            query_wrapper_prompt=query_wrapper_prompt,
            tokenizer_name="/home/directory/Tools/models/TheBloke_Mistral-7B-Instruct-v0.2-GPTQ",
            model_name="/home/directory/Tools/models/TheBloke_Mistral-7B-Instruct-v0.2-GPTQ",
            device_map="auto",
            tokenizer_kwargs={"max_length": 2048},
            messages_to_prompt= messages_to_prompt,
            completion_to_prompt= completion_to_prompt,
            generate_kwargs={"temperature": 0.3, "do_sample": False},
)

query_engine = self.ds.active_index.as_query_engine(similarity_top_k=4, **self.engine_defaults, streaming=True)
chat_engine = self.ds.active_index.as_chat_engine(
      query_engine = query_engine,
      chat_mode="condense_plus_context", 
      similarity_top_k=4, 
      streaming=True,
      chat_history=custom_chat_history,
      **self.engine_defaults
)
```

**Comment by logan-markewich** [comment]
testing with both is_chat_model=True and is_chat_model=False, we can very clearly see the retrieved context being included when sending to the llm

the "simple" handler I used in the notebook just prints every llm input and output

https://colab.research.google.com/drive/1AuATkiCYq87aEQwuikhh1gXyA--Z6SL8?usp=sharing

**Comment by sitbk** [comment]
> testing with both is_chat_model=True and is_c

So, at least on my end, disabling is_chat_model in OpenAILike results in sending the context to my LLM. However, the response is truncated down to about a sentence. The same occurs with a query engine when is_chat_model is disabled. In both cases it sends the API a "max_new_tokens" of 16.  

When is_chat_model is enabled query engines function as intended, with context sent to the LLM and an accurate, full response is returned. But the LLM does not **receive** the context when using Chat Engine with is_chat_model enabled. The context is however shown in sources (chat_engine.chat().sources).

**Comment by logan-markewich** [comment]
I... don't know what that second part means.

How can I replicate this?

**Comment by logan-markewich** [comment]
I can put a break point right before the api request is made, and see that everything is sent properly

**Comment by logan-markewich** [comment]
Max new tokens of 16 will indeed stop at after a small sentence. That makes sense (16 tokens to generate isn't a lot)

I can also set a break point before the api request is sent, and observe that the full data is being sent in the request.

This seems like an issue with the server you are using not handling system prompts (which is where all the context is)

**Comment by sitbk** [comment]
> Max new tokens of 16 will indeed stop at after a small sentence. That makes sense (16 tokens to generate isn't a lot)
> 
> I can also set a break point before the api request is sent, and observe that the full data is being sent in the request.
> 
> This seems like an issue with the server you are using not handling system prompts (which is where all the context is)

Why would it send a max_new_tokens of 16 when is_chat_model is disabled, but 2000+ when it is enabled?

**Comment by sitbk** [comment]
It seems the OpenAI Completions API at some point (and may still) default to 16 max_tokens for the completions endpoint. I can manually set a max_tokens parameter in OpenAILike to force longer responses, but it does not seem to automatically calculate this parameter as it did with is_chat_model=True. Is that expected behavior?

**Comment by logan-markewich** [comment]
It depends on your server. By default, it's not set. For oepenai, this means generate as much as you can. For other servers, it may fallback to some server default

**Comment by s1at3test** [comment]
I’m **thinking** it’s LlamaIndex sending it as an argument to the API. If I set it manually in OpenAILike parameters and `is_chat_model=False` it respects this setting and the max_new_tokens returned matches the OpenAILike parameter. If I remove the parameter, it defaults to 16. 

I tried manually setting max_new_tokens and enabled auto generation of max_new_tokens on the API server itself, but the server reports receiving an argument of max_new_tokens 16 or whatever parameter I set in OpenAILike.

Setting `is_chat_model=True` results in LlamaIndex sending a variable max_new_tokens to the server, but I lose context in Chat Engines (but not Query Engines).

**Comment by sitbk** [comment]
> It depends on your server. By default, it's not set. For oepenai, this means generate as much as you can. For other servers, it may fallback to some server default

Yeah it's either the model or template applied to said models, so not in the realm of responsibility for run-llama. I set a packet capture on my API to see what is actually coming through. With `is_chat_model=True` messages are submitted to the /chat/completions endpoint, but with different templates depending upon query / chat engine. I'm guessing this is intended behavior. 

Chat tosses the context in the system prompt and Query tosses it in a user prompt. Model / template combo I was using for whatever reason didn't care about context in the system prompt, this second model acknowledges it.
