### ISSUE TITLE
[Question]: Vector dimension 1536 does not match the dimension of the index 3072

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#12009]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I got this code: from llama_index.core import VectorStoreIndex
from llama_index.core import StorageContext
index = VectorStoreIndex.from_vector_store(vector_store)
query_engine = index.as_query_engine()
query_str = "question"
response = query_engine.query(query_str)

and im getting this error: PineconeApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'content-type': 'application/json', 'Content-Length': '104', 'x-pinecone-request-latency-ms': '99', 'x-pinecone-request-id': '3307327073880960409', 'date': 'Sun, 17 Mar 2024 08:57:50 GMT', 'x-envoy-upstream-service-time': '14', 'server': 'envoy', 'Via': '1.1 google', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000'})
HTTP response body: {"code":3,"message":"Vector dimension 1536 does not match the dimension of the index 3072","details":[]}

The thing is I created an index in piencone with 3072 dimensions because to ingest the data nodes I use text embedding 3 large of openai. Like this:
from llama_index.embeddings.openai import OpenAIEmbedding

embed_model = OpenAIEmbedding(model="text-embedding-3-large")
for node in nodes:
    node_embedding = embed_model.get_text_embedding(
        node.get_content(metadata_mode="all")
    )
    node.embedding = node_embedding
 vector_store.add(nodes)
 
 Why is this happening?

**Comment by anoopshrma** [comment]
Yeah openAI creates embedding with 1536 as dimension. You'll have to regenerate the embeddings if you want to use a different embed model.

**Comment by logan-markewich** [comment]
Yea what @anoopshrma said -- you can't mix embeddings of different sizes/model into the same index

**Comment by logan-markewich** [comment]
In this case, it seems like you might not be querying with the proper embedding model

You probably want to do

`VectorStoreIndex.from_vector_store(vector_store, embed_model=embed_model)`

Or set a global

```
from llama_index.core import Settings
Settings embed_model = embed_model 
```
