### ISSUE TITLE
[Feature Request]: No cutomization for embedding model in RAG Evaluator pack

### ISSUE THREAD

**Issue by AarnoStormborn** [run-llama/llama_index#12011]
### Feature Description

The RAG Evaluator Pack is extremely helpful, but it does not provide an option to use an embedding model of our choice, instead it is forcefully using OpenAIEmbeddings. A wide variety of embedding models come from non-OpenAI sources, so allowing more models to be used can lead to better testing and evaluation.

**Comment by anoopshrma** [comment]
Hey!

The llamapacks are designed in an order that you can download the pack and make your changes and run it!

If you look at this line: https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-rag-evaluator/llama_index/packs/rag_evaluator/base.py#L107

This is where openai embedding model is called. You can replace this with your embed model and run it.
