### ISSUE TITLE
[Documentation]: How to use local llama model? The origional document using Ollama seems out of date

### ISSUE THREAD

**Issue by fuzihaofzh** [run-llama/llama_index#12026]
### Documentation Issue Description

I want to use local llama model. (No chatgpt, No Replicate please)
Current sample I can found is https://docs.llamaindex.ai/en/stable/getting_started/customization.html
```
# Global settings
from llama_index.core import Settings
from llama_index.llms.ollama import Ollama

Settings.llm = Ollama(model="mistral", request_timeout=60.0)

# Local settings
index.as_query_engine(llm=Ollama(model="mistral", request_timeout=60.0))
```
However, seems Ollama already moved to legacy. 
How can I use local llama model? If I use Ollama in the legacy, it will report Error:
ValueError: Cannot use llm_chat_callback on an instance without a callback_manager attribute.

Would it be possible to give a new sample for the latest version. I think this is a widely used feature.
Thanks so much for your kind help

### Documentation Link

https://docs.llamaindex.ai/en/stable/getting_started/customization.html

**Comment by logan-markewich** [comment]
The documentation is correct.

Just install the integrations you want and import them

For example
```
pip install llama-index-llms-ollama llama-index-embeddings-huggingface
```

```
from llama_index.llms.ollama import Ollama
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

Settings.llm = Ollama(...)
Settings.embed_model = HuggingFaceEmbedding(...l
```

You can see all integrations on https://llamahub.ai
