### ISSUE TITLE
[Question]: Use GPT-4 for RAG

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#12024]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

query_engine = index.as_query_engine(
      similarity_top_k=5,
      embed_model=embed_model,   # <-- this line
      
)

How can I specify that I want to use GPT-4 model for the retrieval?

**Comment by logan-markewich** [comment]
GPT-4 is not a retrieval model. It can't (and shouldn't) be used for embeddings

Use the latest openai models instead if you want to use openai (or the default, which is ada-002)

```python
from llama_index.embeddings.openai import OpenAIEmbedding

embed_model = OpenAIEmbedding(model='text-embedding-3-small')
```
