### ISSUE TITLE
[Question]: Multi modal rag 

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#12039]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a use case where i got 100's of documents. I have implemented a rag for answering question related to text but the problem is my requirement extends to images also. The documents contains steps for some process. These steps have some text and followed by some image. The application i am trying to implement should behave in a way that, if asked any question about the process it should not only give me the steps but also the images corresponding to it. (have to maintain the order of the images)

For ex:

Step 1: ___ some text ___
respective image for step 1

Step 2: ___ some text ___
respective image for step 2

and so on.

How do you even do this, is it possible?

**Comment by LJ-Hao** [comment]
Check [here](https://www.hackster.io/lijiahaoxyz/multimodal-rag-on-jetson-cd83f9), maybe it will help you, I am trying to use clip to embedding images and text in the next version.
