### ISSUE TITLE
[Bug]: Streaming not working

### ISSUE THREAD

**Issue by hypernovas** [run-llama/llama_index#12031]
### Bug Description

I tried different ways of doing streaming with `index.as_query_engine` or with synthesizer, e.g., 
```
response_synthesizer = get_response_synthesizer(
    streaming=True,
    text_qa_template=self.params.text_qa_prompt,
    refine_template=self.params.refine_prompt,
    service_context=service_context,
)
self.query_engine = RetrieverQueryEngine(
    retriever=self.retriever,
    response_synthesizer=response_synthesizer,
    node_postprocessors=[
        SimilarityPostprocessor(
            similarity_cutoff=self.params.similarity_cutoff)
    ],
```

It turns out StreamingResponse class will return the whole response instead of streaming. 

### Version

0.10.20

### Steps to Reproduce

I just used a simple code to demonstrate
```
import os

import openai

from llama_index.core import get_response_synthesizer, SimpleDirectoryReader, VectorStoreIndex
from llama_index.core.query_engine import RetrieverQueryEngine

## config OpenAI 
_OPENAI_KEY_FILE = "~/.openai-secret"
with open(os.path.expanduser(_OPENAI_KEY_FILE), 'r') as file:
    api_key = file.read().strip()

openai.api_key = api_key

documents = SimpleDirectoryReader("./knowledge_data").load_data()
index = VectorStoreIndex.from_documents(documents)

query_engine = index.as_query_engine(streaming=True, similarity_top_k=5)
streaming_response = query_engine.query(
    "How to use xxxx?",
)

# The whole response is returned
print(streaming_response)

# nothing output at this step
for text in streaming_response.response_gen:
    print(text)

```

**Comment by logan-markewich** [comment]
By printing the response object before iterating over it, you are consuming the stream

**Comment by hypernovas** [comment]
> By printing the response object before iterating over it, you are consuming the stream

That was to demonstrate the bug. I didn't have print originally. 

Using a clean venv, installed llama-index only with `python3.11 -m pip install llama-index`

The code prints nothing. Curious, if you could reproduce, it should be quick.

**Comment by logan-markewich** [comment]
Works fine for me. Maybe your node-post processor filtered out all the nodes?

```python
import os

os.environ["OPENAI_API_KEY"] = "sk-..."

from llama_index.core import Document, VectorStoreIndex, get_response_synthesizer
from llama_index.core.query_engine import RetrieverQueryEngine

index = VectorStoreIndex.from_documents([Document.example()])

query_engine = RetrieverQueryEngine.from_args(
    index.as_retriever(),
    response_synthesizer=get_response_synthesizer(response_mode="compact", streaming=True),
)

resp = query_engine.query("Tell me about LLMs")
for r in resp.response_gen:
  print(str(r), end="", flush=True)
```

**Comment by hypernovas** [comment]
> Works fine for me. Maybe your node-post processor filtered out all the nodes?
> 
> ```python
> import os
> 
> os.environ["OPENAI_API_KEY"] = "sk-..."
> 
> from llama_index.core import Document, VectorStoreIndex, get_response_synthesizer
> from llama_index.core.query_engine import RetrieverQueryEngine
> 
> index = VectorStoreIndex.from_documents([Document.example()])
> 
> query_engine = RetrieverQueryEngine.from_args(
>     index.as_retriever(),
>     response_synthesizer=get_response_synthesizer(response_mode="compact", streaming=True),
> )
> 
> resp = query_engine.query("Tell me about LLMs")
> for r in resp.response_gen:
>   print(str(r), end="", flush=True)
> ```

Thanks a lot! I found a bit clue. I was using python3.11. Then, I switched to python 3.10 and it would work fine. Do you mind let me know which python version are you using?

**Comment by logan-markewich** [comment]
I was also using 3.10, but I really don't see how that would cause this to not work 🤔

**Comment by hypernovas** [comment]
> I was also using 3.10, but I really don't see how that would cause this to not work 🤔

It must something related to the other libs being installed. I am very puzzled. Got to log the internals to see why. I will close this as it is not a common bug.

**Comment by hypernovas** [comment]
not reproducible
