### ISSUE TITLE
[Question]: BM25Retriever does not support embeddings, skipping

### ISSUE THREAD

**Issue by mirix** [run-llama/llama_index#12049]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I am having troubles adapting my old scripts to the new llamaindex.

I have created a hybrid retriever as per:

https://docs.llamaindex.ai/en/latest/examples/retrievers/bm25_retriever.html

This approach used to work fine with the previous versions of llamaindex.

Now, for most questions, the retriever does not find any sources. 

It shows the following warning:

BM25Retriever does not support embeddings, skipping...

**Comment by logan-markewich** [comment]
What's the actual issue you are having? How does it not find sources? It will retrieve from one of the options, unless the LLM errors out.

Maybe one of your options is empty?

**Comment by mirix** [comment]
Thanks @logan-markewich 

I have found the issue. My bad. Apologies.

I was filtering the responses with the FaithfulnessEvaluator and it seems that the sensitivity has changed in the new version.
