### ISSUE TITLE
[Bug]: Streaming not working (root cause found), reopen issue 12031

### ISSUE THREAD

**Issue by hypernovas** [run-llama/llama_index#12055]
### Bug Description

Reopening this for [issue 12031](https://github.com/run-llama/llama_index/issues/12031)

The streaming generator from StreamingResponse class will be pre-consumed by `dispatcher.event(SynthesizeEndEvent(query=query, response=str(response)))` in Synthesizer. Hence, nothing output in the generator.

Version has issue `llama-index-core==0.10.20.post2`

Revert to `0.10.19 `and things will resume.

### Version

llama-index-core==0.10.20.post2

### Steps to Reproduce

1. install the latest core lib: `pip install llama-index-core==0.10.20.post2`
2. Run any streaming code, e.g.,:
```python
import os
import logging

from llama_index.core import Document, VectorStoreIndex, get_response_synthesizer
from llama_index.core.query_engine import RetrieverQueryEngine


logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
_logger = logging.getLogger(__name__)

## config OpenAI 
_OPENAI_KEY_FILE = "~/.openai-secret"
with open(os.path.expanduser(_OPENAI_KEY_FILE), 'r') as file:
    api_key = file.read().strip()

os.environ["OPENAI_API_KEY"] = api_key

index = VectorStoreIndex.from_documents([Document.example()])

query_engine = RetrieverQueryEngine.from_args(
    index.as_retriever(),
    response_synthesizer=get_response_synthesizer(response_mode="compact", streaming=True),
)

resp = query_engine.query("Tell me about LLMs")
for text in resp.response_gen:
    print(text, end="", flush=True)
```

3. If you uninstall it and install `llama-index-core==0.10.19`, things will resume
4. If you comment out `llama_index/core/response_thesizers/base.py` line 243, it would also be a workaround.

**Comment by benbenz** [comment]
I have the same issue. Rolling back did the trick.
```
llama-index==0.10.19
llama-index-core==0.10.19
```

**Comment by nerdai** [comment]
Yeah, sorry this BUG was introduced in attempt to address another one. Working on the fix now that won't have the generators be consumed from the construction of the `SynthesizeEndEvent`.

**Comment by benbenz** [comment]
Great. Thanks!
