### ISSUE TITLE
[Bug]: test_openai_agent.py was deleted

### ISSUE THREAD

**Issue by JoelGotsch** [run-llama/llama_index#12056]
### Bug Description

I think the file llama_index/llama-index-integrations/agent/llama-index-agent-openai/tests/test_openai_agent.py was deleted by accident in the commit "New instrumentation module" (#11831)

### Version

0.10.20

### Steps to Reproduce

See the commit history:

https://github.com/run-llama/llama_index/pull/11831/files#diff-b263e27784ee19509f42326d2b0e5ee6a74789b4881925363c731877b0e8c374

**Comment by logan-markewich** [comment]
Merged
