### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED on server_hostname='api.cloud.llamaindex.ai'

### ISSUE THREAD

**Issue by jmiddleton** [run-llama/llama_index#12058]
### Bug Description

I'm using LlamaParser but since today i'm getting the following error:

DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x13b3f6690> server_hostname='api.cloud.llamaindex.ai' timeout=2000
DEBUG:httpcore.connection:start_tls.failed exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')

The certificate name is: Kubernetes Ingress Controller Fake Certificate

Please review and thanks.

### Version

latest

### Steps to Reproduce

open a browser and access https://api.cloud.llamaindex.ai

### Relevant Logs/Tracbacks

```shell
INFO:root:Creating new index
DEBUG:llama_index.core.readers.file.base:> [SimpleDirectoryReader] Total files added: 3
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:httpx:load_ssl_context verify=True cert=None trust_env=True http2=False
DEBUG:httpx:load_verify_locations cafile='/Users/jmiddleton/Library/Caches/pypoetry/virtualenvs/app-iwm1hSXD-py3.11/lib/python3.11/site-packages/certifi/cacert.pem'
DEBUG:httpcore.connection:connect_tcp.started host='api.cloud.llamaindex.ai' port=443 local_address=None timeout=2000 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.anyio.AnyIOStream object at 0x13ad51490>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x13b3f6690> server_hostname='api.cloud.llamaindex.ai' timeout=2000
DEBUG:httpcore.connection:start_tls.failed exception=SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)')
```

**Comment by logan-markewich** [comment]
I have no issues accessing llamacloud

I think this is due to the env where you are running code?

**Comment by jmiddleton** [comment]
looks better now. Thanks
