### ISSUE TITLE
[Bug]: Cohere Reranker not found

### ISSUE THREAD

**Issue by jbbae** [run-llama/llama_index#12069]
### Bug Description

Hi - I am simply trying to follow the instructions in https://docs.llamaindex.ai/en/latest/examples/node_postprocessor/CohereRerank.html to use a Cohere reranker:

```
from llama_index.postprocessor.cohere_rerank import CohereRerank


api_key = os.environ["COHERE_API_KEY"]
cohere_rerank = CohereRerank(api_key=api_key, top_n=2)
```

But I am getting an error (see below). What's wrong...? I am using the latest version of LlamaIndex, so can't imagine it'd be a version issue... 

### Version

0.10.20

### Steps to Reproduce

1. Install latest LlamaIndex
2. Run "from llama_index.postprocessor.cohere_rerank import CohereRerank"

### Relevant Logs/Tracbacks

```shell
ModuleNotFoundError: No module named 'llama_index.postprocessor'
```

**Comment by logan-markewich** [comment]
The top of the example has an install

`pip install llama-index-postprocessor-cohere-rerank`

Every integration is a package. See https://llamahub.ai has all the integrations
