### ISSUE TITLE
[Feature Request]: Filter / Customize nodes generated by CodeSplitter

### ISSUE THREAD

**Issue by sansmoraxz** [run-llama/llama_index#12066]
### Feature Description

I propose adding a new feature to codesplitter to split based on capture groups:

For instance consider below example where I am only interested in just the function and class definations at the root level of the python source code:-

```python
def foo():
    """Helllo, world!"""
    def bar(**x):
        print("Hello, world!")
        print(x)
    if bar:
        baz(x=3, y=6)

class MyC:
  def hello():
    print(22)

if __name__ == "__main__":
    foo()
    f=3
```

I can use the following tree sitter query to named capture the function definations and class definations of the root:-
```
((module
  (function_definition) @root.function
  (class_definition) @root.class
))
```

You may test tree sitter queries here: https://tree-sitter.github.io/tree-sitter/playground

### Reason

Current implementation is to split recursively based on size, without any metadata being generated which feel limiting for some scenarios.

### Value of Feature

In the sample abve I captured function and class definations at root level ignoring the exectution statements, comments etc. from the root level.

It could also help us to tackle scenarios such as capturing the top level imports as metadata (hello java?) which is normally lost after chunking.

**Comment by logan-markewich** [comment]
I highly encourage a PR to improve code splitting :)
