### ISSUE TITLE
[Question]: Bedrock integration with Claude3 fails {   "detail": "Internal Server Error from An error occurred (ValidationException) when calling the InvokeModel operation: \"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead." }

### ISSUE THREAD

**Issue by Aniket-ByteIQ** [run-llama/llama_index#12081]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Example code:
```
  from llama_index.legacy import ServiceContext
from llama_index.legacy.embeddings import BedrockEmbedding
from llama_index.legacy.llms import Bedrock
  def build_model(self):
        try:
            self.llm = Bedrock(
                model=self.model,
                context_size=self.context_size,
                aws_access_key_id=self.access_key_id,
                aws_secret_access_key=self.secret_access_key,
                region_name=self.region_name,
            )

            self.embed_model = BedrockEmbedding(
                model=self.model,
                aws_access_key_id=self.access_key_id,
                aws_secret_access_key=self.secret_access_key,
                region_name=self.region_name,
            )

            self.service_context = ServiceContext.from_defaults(
                llm=self.llm,
                embed_model=self.embed_model
            )
```
 to build the model and passing it as service context in NLSQLTableQueryEngine :
 `query_engine = NLSQLTableQueryEngine(
            service_context=self.service_context,
            text_to_sql_prompt=TEXT_TO_SQL_PROMPT,
            sql_database=sql_db,
            tables=sql_db.get_usable_table_names(),
            synthesize_response=True
        )`
 While using the claude 2 model, its working perfectly fine but using the claude 3 sonnet model raises this issue: "{
  "detail": "Internal Server Error from An error occurred (ValidationException) when calling the InvokeModel operation: \"claude-3-sonnet-20240229\" is not supported on this API. Please use the Messages API instead."
}".
How can i fix this issue and use claude 3 in my code?

**Comment by logan-markewich** [comment]
@Aniket-ByteIQ its not supported in legacy. You'll have to switch to non-legacy imports

```
pip install llama-index-embeddings-bedrock llama-index-llms-bedrock
```

Updated imports (you'll need to avoid using legacy now)
```
from llama_index.core import ServiceContext
from llama_index.embedings.bedrock import BedrockEmbedding
from llama_index.llms.bedrock import Bedrock
```

**Comment by Aniket-ByteIQ** [comment]
@logan-markewich Thanks a lot! It worked! I completely forgot that i was using legacy.
