### ISSUE TITLE
[Question]:  why cant i import the FnRetrieverOpenAIAgent

### ISSUE THREAD

**Issue by Vishu611** [run-llama/llama_index#12088]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is FnRetrieverOpenAIAgent still in use or has it been pushed to legacy?

**Comment by logan-markewich** [comment]
That's still the correct way. It just wasn't migrated (yet) to the new Agent runner/worker architecture, hence the legacy import.

It still works though

**Comment by Vishu611** [comment]
When I try to import it throws me error, 

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[127], line 1
----> 1 from llama_index.agent.openai_legacy import FnRetrieverOpenAIAgent

ModuleNotFoundError: No module named 'llama_index.agent.openai_legacy'

**Comment by logan-markewich** [comment]
`pip install llama-index-agent-openai-legacy`

The install is also in the notebook 👀

**Comment by Vishu611** [comment]
That works. 
Thanks
