### ISSUE TITLE
[Feature Request]: Multiple vector stores shared accross the same document store namespace, while using refresh_ref_docs

### ISSUE THREAD

**Issue by benbenz** [run-llama/llama_index#12086]
La### Feature Description

Is it always required to have a document store per vector store ? 
I have separated the namespace generation between the doc stores and the vector stores, depending on different attributes:
- index type + language + loading parameters (loaders) >> doc store namespace
- index type + language + loading parameters (loaders) + chunking parameters (parsers/transformations) >> vector store namespace

This allows to minimize the number of entries in the docstore table/database - mostly for performances considerations.
The issue is that, when using the refresh_ref_docs method (combined with a transformed file_path as ID), the node is not added to the vector store if the document is already in the doc store and its hash is identical ... which is a great feature. But it means we can't mutualize the document store entries with different vector store entries: if - by any chance - one of the node/document has the same hash, it will just disappear from the vector store and the index will be incomplete ...

The fix is to have non-mutualized document stores but it would a nice feature to handle these cases?

**Comment by benbenz** [comment]
> To minimize the number of entries in the `docstore` and enhance performance, consider implementing a preprocessing step that filters out documents that do not need to be refreshed. This can be achieved by comparing the hashes of the documents locally before invoking `refresh_ref_docs`. Only documents with changed hashes should be passed to `refresh_ref_docs` for updating.

I dont think this works. We are filtering out even more documents and refresh_ref_docs is just doing the right business logic for this already ... The issue is: if a node/document happens to have the same hash+doc_id, it wont be added to the vector store; and this can happen even if the chunking parameters are different.

The solution would be to check in `refresh_ref_docs` if the node is present or not and add it if it isn't, when the doc_id is in the doc store and the hash is equal.

**Comment by IgnacioPascale** [comment]
@benbenz I support adding this. 

Currently dealing with a case in which I want to have various vector stores but use only one `docstore` (this doesn't seem like a crazy use case, especially if you're dealing with different embedding models / embedding dimensions / chunk sizes / any config). This behaviour pushes me to set a 1:1 docstore:vector_store relationship.

I did thorough research over Documentation / Codebase and was not able to find a way around this with existing functionalities. Please do correct me if I'm wrong though.
