### ISSUE TITLE
[Question]: how to  mesasure the llamaindex throughput?

### ISSUE THREAD

**Issue by lambda7xx** [run-llama/llama_index#12099]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

hi, If I want to mesasure the llamaindex throughput? how to measure its throughput? I deploy the llamaindex as a  onlinesystem and it can receive requests. Then I generate some request per seconds  and send the the request to the llaamindex system? Is it ok?

**Comment by hypernovas** [comment]
Try Locust https://docs.locust.io/en/stable/
