### ISSUE TITLE
[Feature Request]: Include token counts on AWS Bedrock integration

### ISSUE THREAD

**Issue by anticorrelator** [run-llama/llama_index#12096]
### Feature Description

Some model integrations include token count info on the `CompletionResponse` object emitted along with `LLMCompletionEvent`s, such as the [Anthropic integration](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-anthropic/llama_index/multi_modal_llms/anthropic/base.py#L204-L208).

The AWS Bedrock integration [does not include](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-bedrock/llama_index/llms/bedrock/base.py#L232-L234) any `additional_kwargs`. Many LLMs supported by AWS Bedrock include token count info in the `x-amzn-bedrock-input-token-count` and `x-amzn-bedrock-output-token-count` headers. If possible, it'd be useful to include token count information wherever possible in `CompeltionResponse` objects.

### Reason

I help maintain LlamaIndex instrumentation in ArizeAI's [`OpenInference`](https://github.com/Arize-ai/openinference) library. Many users of `LlamaIndex` instrumentation rely on tracing to understand the token usage of their applications, especially complex ones managed with `LlamaIndex`. Our users are needing to combine `LlamaIndex` autoinstrumentation along with a second instrumentation package in order to see token counts, leading to duplicated spans and additional complexity.

### Value of Feature

We can improve the experience of using LlamaIndex tracing, as many users rely on instrumentation to help them both understand application behavior and evaluate costs.

**Comment by jlonge4** [comment]
I think returning raw response here -> https://github.com/run-llama/llama_index/blob/e2396a7c6951973527339df62ce0f4a8ad17723b/llama-index-core/llama_index/core/base/llms/types.py#L90 would allow us to get -> 'usage': {'input_tokens': 32, 'output_tokens': 383} from the Bedrock response correct?

**Comment by omenking** [comment]
Right now It doesn't work still.

**Comment by ryann-sportsbet** [comment]
reopen the issue as I'm experiencing the same thing
