### ISSUE TITLE
[Feature Request]: Tools agent with structured output

### ISSUE THREAD

**Issue by jhostyk** [run-llama/llama_index#12090]
### Feature Description

We can build [an OpenAI agent](https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent.html#our-slightly-better-openaiagent-implementation).
We can require [structured output](https://docs.llamaindex.ai/en/stable/examples/output_parsing/openai_pydantic_program.html#extraction-into-album).
We just can't do them both together.

### Reason

I've tried variations on the snippet below, using output_cls, but agent.chat always just returns a string, not json.

```
%pip install llama-index-agent-openai
%pip install llama-index-llms-openai
!pip install llama-index
import os
os.environ["OPENAI_API_KEY"] = "YOUR_KEY"
from llama_index.core.tools import FunctionTool
from pydantic import BaseModel
class Answer(BaseModel):
    answer: int

def multiply(a: int, b: int) -> int:
    """Multiple two integers and returns the result integer"""
    return a * b


multiply_tool = FunctionTool.from_defaults(fn=multiply)

def add(a: int, b: int) -> int:
    """Add two integers and returns the result integer"""
    return a + b


add_tool = FunctionTool.from_defaults(fn=add)

from llama_index.agent.openai import OpenAIAgent
from llama_index.llms.openai import OpenAI
llm = OpenAI(model="gpt-3.5-turbo-0613")
agent = OpenAIAgent.from_tools(
    [multiply_tool, add_tool], llm=llm, verbose=True, output_cls=Answer
)
response = agent.chat("What is (121 * 3) + 42?")
print(str(response))
```

### Value of Feature

All interactions with the llm should be able to have structured output.
It's tough that, for example, [index.as_query_engine()](https://docs.llamaindex.ai/en/stable/examples/query_engine/pydantic_query_engine.html#create-the-index-query-engine-openai) can take output_cls as an arg - but a standard agent can't.

**Comment by logan-markewich** [comment]
It would indeed have to be a new agent class. I welcome you to contribute something for this :)
