### ISSUE TITLE
[Documentation]: 这样写貌似有点疑惑，确认一下是正确的吗？

### ISSUE THREAD

**Issue by 827648313** [run-llama/llama_index#12109]
### Documentation Issue Description

![微信图片_20240319145912](https://github.com/run-llama/llama_index/assets/66358885/500cec49-5024-4922-987c-3ed3e8456bfd)

### Documentation Link

1123

**Comment by hatianzhang** [comment]
@827648313 thanks for reporting. since `CompletionResponseGen` is derived from `CompletionResponse`  https://github.com/run-llama/llama_index/blob/2ba13544cd2583418cbeade5bea45ff1da7bb7b8/llama-index-core/llama_index/core/base/llms/types.py#L93
so we should be fine
