### ISSUE TITLE
[Bug]: Error: 'GCSFile' object has no attribute 'name' when processing PDF files

### ISSUE THREAD

**Issue by bhavan-kaya** [run-llama/llama_index#12108]
### Bug Description

When using `SimpleDirectoryReader` from `llama-index` with `GCSFileSystem` from `gcsfs` to read files from a GCP bucket, I encounter a `'GCSFile' object has no attribute 'name'` error, but this issue only occurs for PDF files and not for DOCX files. The issue seems to arise in the `default_file_metadata_func` function, which attempts to access the `name` attribute from the file stat result provided by `gcsfs`.

```python
import google.auth
from llama_index.core import SimpleDirectoryReader
from gcsfs import GCSFileSystem
from fs_gcsfs import GCSFS

def __load_gcp_bucket(bucket_path: str):
    credentials, project_id = google.auth.default(
        scopes=["https://www.googleapis.com/auth/devstorage.read_only"]
    )

    gcp_fs = GCSFileSystem(project=project_id, token=credentials)

    reader = SimpleDirectoryReader(
        input_dir=bucket_path,
        fs=gcp_fs,
    )

    documents = reader.load_data()
    return documents

documents = __load_gcp_bucket("<bucket-path>/")
print(documents)
```

### Version

0.10.20

### Steps to Reproduce

1. Configure a `SimpleDirectoryReader` instance to read files from a specified GCP bucket path.
2. Ensure the bucket contains both `.pdf` and `.docx` files.
3. Execute the reader's `load_data` method.
4. Observe that the process successfully reads `.docx` files but fails for `.pdf` files with the mentioned error.

### Relevant Logs/Tracbacks

```shell
Failed to load file <GCS bucket path>/file.pdf with error: 'GCSFile' object has no attribute 'name'. Skipping...
```

**Comment by logan-markewich** [comment]
This should be fixed
