### ISSUE TITLE
Implement Rate Limit Handling in TogetherEmbedding() Class.

### ISSUE THREAD

**Issue by vaishakhRaveendran** [run-llama/llama_index#12104]
### Feature Description

The Together AI platform provides a valuable service by offering generous credits to users for utilizing their embeddings and language models. However, for free users, there is a limit of 1 query per second. When using the TogetherEmbedding() class for processing larger documents, users often encounter the 429 - Rate Limit Error, indicating that they have exceeded the query rate limit.
Currently, the TogetherEmbedding() class does not handle this rate limit error gracefully. It would be beneficial to enhance this class to automatically handle the 429 error by retrying after the reset time specified in the response headers.

### Reason

Implementing rate limit handling in LlamaIndex's TogetherEmbedding class requires modifications to the _generate_embedding and _agenerate_embedding functions. Currently, the absence of error handling leads to potential connection errors and inefficient retries. Integrating rate limit error handling within the baseEmbedding class would be better.

### Value of Feature

Implementing rate limit handling not only allows users to experiment freely with their free credits without worrying about query per second errors but also significantly enhances the overall user experience.

**Comment by vaishakhRaveendran** [comment]
@dosu-bot should i work on the fix. Can you assign me for this issue

**Comment by nerdai** [comment]
> @dosu-bot should i work on the fix. Can you assign me for this issue

HI @vaishakhRaveendran, we'd certainly welcome a PR for this! By all means :)

**Comment by vaishakhRaveendran** [comment]
@logan-markewich can help me fix.

**Comment by vaishakhRaveendran** [comment]
@dosu-bot  can you help me with the fix

**Comment by vaishakhRaveendran** [comment]
@dosu-bot what could be the reason for the code to fail during linting😔

**Comment by vaishakhRaveendran** [comment]
@dosubot where can i get the environment setup guide
