### ISSUE TITLE
[Question]: RAG Inference Latency 

### ISSUE THREAD

**Issue by Prathit-tech** [run-llama/llama_index#12110]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I have a RAG system that uses the Zephyr 3b model and uses llama-index for the VectorStoreEmbedding and inference. My problem is with the latency as it seems to take 300s to generate an output. Is there any way that i can get this latency to GPT levels or atleast 60s?

**Comment by logan-markewich** [comment]
Either get a better GPU (lol) or try using something like TGI or vLLM
