### ISSUE TITLE
[Bug]: Embedding Model Not Recognized in UnstructuredElementNodeParser Despite Being Set in Settings

### ISSUE THREAD

**Issue by Leonschmitt** [run-llama/llama_index#12117]
### Bug Description

When attempting to use the UnstructuredElementNodeParser  the embedding model specified through HuggingFaceEmbedding in the settings is not recognized. Despite setting the embedding model explicitly with Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-m3"), the process defaults to using MockEmbedding and prints a message indicating that embeddings have been explicitly disabled.

### Version

llama-index version: 0.10.20 llama-index-core version: 0.10.20.post2

### Steps to Reproduce

Set the embedding model using the HuggingFaceEmbedding from llama_index.embeddings.huggingface:

```python
from llama_index.core import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-m3")
```
Initialize the UnstructuredElementNodeParser and attempt to parse documents:

```python
from llama_index.core.node_parser import UnstructuredElementNodeParser

unstructured_node_parser = UnstructuredElementNodeParser()
nodes = unstructured_node_parser.get_nodes_from_documents(documents=docs)
```

### Relevant Logs/Tracbacks

```shell
service_context = ServiceContext.from_defaults(llm=llm, embed_model=None)
Embeddings have been explicitly disabled. Using MockEmbedding.
0it [00:00, ?it/s]0it [00:00, ?it/s]
```

**Comment by logan-markewich** [comment]
This is a benign message, I know it looks scary, but its just using a summary index under the hood and disables embeddings for that step (since embeddings aren't used)

Will update to remove this though, it shouldn't be using the service context
