### ISSUE TITLE
[Bug]:  AttributeError: 'tuple' object has no attribute 'get_doc_id' 

### ISSUE THREAD

**Issue by saireddythfc** [run-llama/llama_index#12136]
### Bug Description

Was trying out the Milvus integration creating the AI agent as follows:

if not INDEX_LOADED:
    #load data
    path = os.getcwd()
    vair_docs = SimpleDirectoryReader(
        input_files=["./data/2023-2024_IFAB_Laws_of_the_Game.pdf"]
    ).load_data()

    #build index
    vector_store_vair = MilvusVectorStore(dim=1536, collection_name="vair", overwrite=False)
    storage_context = StorageContext.from_defaults(vector_store=vector_store_vair)
    vair_index = VectorStoreIndex.from_documents(vector_store_vair ,storage_context=storage_context)

    #persist index
    vair_index.storage_context.persist(persist_dir="./storage/vair")

### Version

0.10.15

### Steps to Reproduce

Follow the tutorial by Zilliz with their distributed Milvus vector DB on creating a RAG-based AI agent for lyft/uber financial information chatbot.

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/Users/hurrikane/Desktop/VA(I)R/vair.py", line 40, in <module>
    vair_index = VectorStoreIndex.from_documents(vector_store_vair ,storage_context=storage_context)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 133, in from_documents
    docstore.set_document_hash(doc.get_doc_id(), doc.hash)
                               ^^^^^^^^^^^^^^
AttributeError: 'tuple' object has no attribute 'get_doc_id'
```

**Comment by logan-markewich** [comment]
You didnt pass in any documents? I think you mean to do


```python
vair_index = VectorStoreIndex.from_documents(vair_docs , storage_context=storage_context)

```

**Comment by saireddythfc** [comment]
I thought we had to pass the nodes as while using the normal VectorStoreIndex function as is.
Thanks!
