### ISSUE TITLE
[Question]:  Structred data extraction using pydantic and open source model (llama based)

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#12142]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am experimenting on data extracttion from medical documents using pydantic and open source model.
I did not find much in the llama index documentation.
here is my very basic approach - the code is not able to generate a response?
please suggest if extracting structred data from documents using pydantic and open source llama based models possible?

`from llama_index.core import SimpleDirectoryReader
from llama_index.core import VectorStoreIndex

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.llama_cpp import LlamaCPP

from typing import List
from pydantic import BaseModel
 #!mkdir -p 'data/paul_graham/'
#!wget 'https://raw.githubusercontent.com/run-llama/llama_index/main/docs/examples/data/paul_graham/paul_graham_essay.txt' -O 'data/paul_graham/paul_graham_essay.txt'
documents = SimpleDirectoryReader("./data/paul_graham").load_data()
class Biography(BaseModel):
    """Data model for a biography."""

    name: str
    best_known_for: List[str]
    extra_info: str
    

#model_url = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGML/resolve/main/llama-2-13b-chat.ggmlv3.q4_0.bin"
#model_url = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf"

llm = LlamaCPP(
    #You can pass in the URL to a GGML model to download it automatically
    model_path=r'/Users/Ramuchilakamarri/Library/CloudStorage/OneDrive-ProvidenceSt.JosephHealth/Work/RAG/llama_index/models/zephyr-7b-alpha.Q5_K_S.gguf',

    temperature=0.1,
    max_new_tokens=256,
    #llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    #kwargs to pass to __call__()
    generate_kwargs={},
    #kwargs to pass to __init__()
    #set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 1},
    verbose=True,
)

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en")

index = VectorStoreIndex.from_documents(
    documents,embed_model=embed_model
)

query_engine = index.as_query_engine(
    output_cls=Biography, response_mode="compact", llm=llm
)

response = query_engine.query("Who is Paul Graham?")`

**Comment by ram510** [comment]
Code worked with Mistral. will test more and post if there are any blockers

**Comment by anoopshrma** [comment]
Structured output with open source llm is not that great at the moment. Some llm give output after prompt modification.
