### ISSUE TITLE
In rag how to make sure it doesnt answer out of context

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12145]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a RAG for specific debugging problems, but if asked question about random things, it still answers, how to restrict this? Im using zephyr 7b

**Comment by logan-markewich** [comment]
It's basically just prompt engineering. Or introducing a second llm call to tryvand get the llm to filter itself

**Comment by mirix** [comment]
You can use the an evaluator such as the FaithfulnessEvaluator (unfortunately, this is a binary evaluator). 

For my current project, however, I am just measure how relevant is the the most relevant node (as assesed by the reranker):

```
	if response.source_nodes[0].score < 0.25:
		response_text = 'I cannot find an answer to that question in en.swissquote.lu. Please, rephrase the question.'
		source = 'No sources'
	else:
		response_text = str(response)
```

**Comment by JINO-ROHIT** [comment]
i tried add a post context prompt and it worked fairly well, thanks

**Comment by Aekansh-Ak** [comment]
Hi @JINO-ROHIT,

Can you help me with how you added post context prompt?

**Comment by JINO-ROHIT** [comment]
@Aekansh-Ak hey sure, what i did was -
post_prompt = """ if the information isnt available in the given context to formulate the answer, just reply with NO ANSWER""""
response = query_engine.query(SYS_PROMPT + user_query + post_prompt)

this is what worked for me
