### ISSUE TITLE
[Question]: Response Synthesizer only works with OpenAi?

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12153]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I just imported response Synthesizer and tried to use it, I get this error.

my_synthesizer = get_response_synthesizer(response_mode="compact")

******
Could not load OpenAI model. Using default LlamaCPP=llama2-13b-chat. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

******
Downloading url https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf to path /tmp/llama_index/models/llama-2-13b-chat.Q4_0.gguf
Error downloading model: [Errno 13] Permission denied: '/tmp/llama_index/models/llama-2-13b-chat.Q4_0.gguf'
Download incomplete. Removing partially downloaded file.
Traceback (most recent call last):
  File "/home/seceon/opensearch_lm_index/model.py", line 111, in <module>
    response_synthesizer = get_response_synthesizer(

**Comment by logan-markewich** [comment]
You need to either pass in the `llm` as a kwarg 

`get_response_synthesizer(..., llm=llm)`

or change the global defaults

```
from llama_index.core import Settings
Settings.llm = llm
```

**Comment by Aekansh-Ak** [comment]
My llm is defined like this-:

pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens = 4000,
        streamer= streamer,
        torch_dtype=torch.float16,
        device_map="auto",
        top_p=0.9,
        temperature = 0.3,
        eos_token_id=tokenizer.eos_token_id
    )

llm = HuggingFacePipeline(pipeline=pipe)



response_synthesizer = get_response_synthesizer(llm=llm)
TypeError: get_response_synthesizer() got an unexpected keyword argument 'llm'

**Comment by logan-markewich** [comment]
This is a langchain LLM class no? Need to wrap it with a langchain wrapper

Also, I think you have an older version of llama-index

**Comment by Aekansh-Ak** [comment]
Upgraded the llama-index version, I am getting this error-:

TypeError: unsupported operand type(s) for -: 'tuple' and 'int'


Code-:
#######################################################333
client = OpensearchVectorClient(
    endpoint, idx, dim=1024, embedding_field=embedding_field, text_field=text_field, use_ssl = False, verify_certs = False
)

vector_store = OpensearchVectorStore(client)

model_id = "lmsys/vicuna-13b-v1.5"
model = AutoModelForCausalLM.from_pretrained(model_id,
#                                            load_in_8bit=True, # set these options if your GPU supports them!
                                            device_map='auto',
                                            torch_dtype=torch.float16,
 #                                           low_cpu_mem_usage=True
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

embeddings = HuggingFaceInstructEmbeddings(model_name="intfloat/multilingual-e5-large",
                                                model_kwargs={"device": "cpu"})

text_split = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=200)
Settings.text_splitter = LangchainNodeParser(text_split)

pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens = 4000,
        streamer= streamer,
        torch_dtype=torch.float16,
        device_map="auto",
        top_p=0.9,
        temperature = 0.3,
        eos_token_id=tokenizer.eos_token_id
    )

llm = HuggingFacePipeline(pipeline=pipe)
llm = LangChainLLM(llm)

Settings.llm = llm
Settings.embed_model = embeddings
Settings.context_window=4096,
Settings.num_output=256,
Settings.chunk_overlap_ratio=0.1,
Settings.chunk_size_limit=None

vsi = VectorStoreIndex.from_vector_store(
    vector_store = vector_store,
)

query_engine = vsi.as_query_engine()
res = query_engine.query("query")

**Comment by Aekansh-Ak** [comment]
Okay, I solved the error, this needs to be changed in prompt_helper.py-:

context_size_tokens = self.context_window[0] - num_prompt_tokens - self.num_output[0]


Will test the response synthesizer now
