### ISSUE TITLE
[Question]: operator arg in MetadataFilter

### ISSUE THREAD

**Issue by kentaro-sagara** [run-llama/llama_index#12159]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I would like to use MetadataFilter to filter cases where value contains the specified word.
I looked at [this page](https://docs.llamaindex.ai/en/stable/examples/vector_stores/postgres.html#apply-nested-filters) and wrote the following code.
```
filters = MetadataFilters(
            filters=[
                MetadataFilter(key="subject", value=subject, operator="in"),
            ],
        )
```

When I run this code, I get an error message like below:
```
ValueError: Vector Store only supports exact match filters. Please use ExactMatchFilter or FilterOperator.EQ instead.
```

Please tell me the solution, thank you.

**Comment by logan-markewich** [comment]
As the error states, the vector store you are using only supports eq filters.

Try using chroma, qdrant, or Postgres (off the top of my head)
