### ISSUE TITLE
How to do Prompt Engineering without OpenAI 

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12150]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to do prompt engineering where I would like to tell me model to act like a chatbot and give answers briefly.

How do I do that in llama-index? The documentation just talk about openAI.

**Comment by logan-markewich** [comment]
It's the same for other LLMs as openai, they all have the same interface and methods. The only difference is the constructor

**Comment by Aekansh-Ak** [comment]
Hi Logan,

Please help me, I don't understand your documentation.

Can you give an example?

**Comment by logan-markewich** [comment]
Take the example you see with openai, and swap in any other LLM?

We have a lot of guides on setting up LLMs (and also embed models)

For example, i might start an ollama server, pull a model, and do

```
pip install llama-index-llms-ollama
```

```
from llama_index.llms.ollama import Ollama

llm = Ollama(model="...", request_timeout=3000)
print(llm.complete("Hello!"))

index = VectorStoreIndex.from_documents(documents, embed_model=embed_model)
query_engine = index.as_query_engine(llm=llm)
```

Or you can change the global defaults
```
from llama_index.core import Settings 

Settings.llm = llm
Settings.embed_model = embed_model
```

**Comment by Aekansh-Ak** [comment]
This is my code modified as per your documentation, https://docs.llamaindex.ai/en/v0.9.48/examples/prompts/prompts_rag.html -:

vsi = VectorStoreIndex.from_vector_store(
    vector_store = vector_store,
    service_context=service_context
)

qa_prompt_tmpl_str = """\
You are a chatbot. You have to be professional and not give unhelpful answers. Your answers should  not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.
If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct.

Act like a chatbot and answer this query

Query: {query}
Answer: \
"""

qa_prompt_tmpl = PromptTemplate(
    qa_prompt_tmpl_str,
)

query_engine = vsi.as_query_engine()

query_engine.update_prompts(
    {"response_synthesizer:text_qa_template": qa_prompt_tmpl}
)

res = query_engine.query("query")

Error-: AttributeError: 'RetrieverQueryEngine' object has no attribute 'update_prompts'

**Comment by logan-markewich** [comment]
What version of llama-index do you have? This works for me

**Comment by Aekansh-Ak** [comment]
llama-index==0.8.46

Okay, I will update it and let you know.

**Comment by Aekansh-Ak** [comment]
I have added the prompt template like this:

####################################################################################
qa_prompt_tmpl_str = """
You are a chatbot. You have to be professional and not give unhelpful answers. Your answers should not include any harmful, unethical, racist, sexist, toxic, dangerous, or illegal content.
If a question does not make any sense, or is not factually coherent, explain why instead of answering something not correct.

Act like a chatbot and answer this query

Query: {query_str}
Answer:
"""

vsi = VectorStoreIndex.from_vector_store(
    vector_store = vector_store,
)

chat_text_qa_msgs = [
    (
        "system",
        "Always answer the question, even if the context isn't helpful.",
    ),
    ("user", qa_prompt_tmpl_str),
]
text_qa_template = ChatPromptTemplate.from_messages(chat_text_qa_msgs)

query_str = "Was there a privilege change event generated for Ashish?"

query_engine = vsi.as_query_engine(text_qa_template=text_qa_template,llm=llm)

res = query_engine.query(query_str)
#######################################################

I get the output that please provide me context to answer this query.
How do I give it context? I have already created a vector database. 
https://docs.llamaindex.ai/en/stable/examples/customization/prompts/chat_prompts/
