### ISSUE TITLE
How can I set device from FlagEmbeddingReranker class?

### ISSUE THREAD

**Issue by Songjiadong** [run-llama/llama_index#12166]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to set parameter device, but currently the system is set automatically. How can I set `device=cpu`? 
my code
```py
 reranker = FlagEmbeddingReranker(
            top_n=k,
            model=RERANK_MODEL_NAME,
            use_fp16=True
        )
```
FlagEmbeddingReranker class
```py
       self._model = FlagReranker(
            model,
            use_fp16=use_fp16,
        )
```
```py

FlagReranker class
```py
        if torch.cuda.is_available():
            self.device = torch.device("cuda")
        elif torch.backends.mps.is_available():
            self.device = torch.device("mps")
        elif is_torch_npu_available():
            self.device = torch.device("npu")
        else:
            self.device = torch.device("cpu")
            use_fp16 = False
        if use_fp16:
            self.model.half()
```

**Comment by Songjiadong** [comment]
```py
device = torch.device('cpu')
reranker = FlagEmbeddingReranker(
    top_n=k,
    model=RERANK_MODEL_NAME,
    use_fp16=True
)
reranker._model.to(device)
```
reranker can't invoke private propertiy`_model`.

**Comment by tslmy** [comment]
> ```python
> device = torch.device('cpu')
> reranker = FlagEmbeddingReranker(
>     top_n=k,
>     model=RERANK_MODEL_NAME,
>     use_fp16=True
> )
> reranker._model.to(device)
> ```
> 
> reranker can't invoke private propertiy`_model`.

"can't" as in "shouldn't" or "not being able to"?

I don't think `_whatever` are private functions. Are they? Did the code not work?

I always thought it has to take **two** underscores to mark a function private. My memory might have lied, though.

**Comment by Songjiadong** [comment]
@tslmy  you are right,but FlagEmbeddingReranker has  been initialized. I want to initialize the model when it is set by device,rather than to set device after model initialization which is complete
