### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'context_window'

### ISSUE THREAD

**Issue by helloadish007** [run-llama/llama_index#12164]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a custom llm running in cloud and i need to use raptor package , but i'm facing the above issue.

class CustomLLM1(LLM):
    model_id: str
    endpoint: str
    decoding_method: str
    temperature: float
    top_p: float
    top_k: int
    repetition_penalty: float
    validation_sequences: dict
    stopping_sequences: List[str]
    min_new_tokens: int
    max_new_tokens: int
    
    @property
    def _llm_type(self) -> str:
        return "custom"

    def _call(
        self,
        prompt: str,
        # stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        # if stop is not None:
        #     raise ValueError("stop kwargs are not permitted.")
        url = "http://123.46.10.123:123/func/genAI"
        data = {
            "prompt": prompt,
            "model_id": self.model_id,
            "decoding_method": self.decoding_method,
            "temperature": self.temperature,
            "top_p": self.top_p,
            "top_k": self.top_k,
            "repetition_penalty": self.repetition_penalty,
            "validation_sequences": self.validation_sequences,
            "stopping_sequences": self.stopping_sequences,
            "min_new_tokens": self.min_new_tokens,
            "max_new_tokens": self.max_new_tokens,
            "context_window" : 8192, # changed
            "endpoint": self.endpoint,
        }
        response = requests.post(url, data=json.dumps(data))
        response_text = response.text
        return response_text

llm = CustomLLM1(
    model_id="mistralai/mixtral-8x7b-instruct-v0-1",
    endpoint="",
    decoding_method="greedy", # can be one of greedy and sample
    temperature=0.7,
    top_p=0.9,
    top_k=50,
    repetition_penalty=1.0,
    validation_sequences={},
    stopping_sequences=["######"],
    min_new_tokens=1,
    max_new_tokens=200,
    context_window =8192,
)

**Comment by helloadish007** [comment]
Please help me in resolving : 
AttributeError: 'NoneType' object has no attribute 'context_window

**Comment by logan-markewich** [comment]
This is a custom langchain llm no?

You need the compatibility wrapper for langchain stuff 
https://docs.llamaindex.ai/en/stable/examples/llm/langchain/

**Comment by helloadish007** [comment]
Yes, you are right.

from llama_index.core.llms import LLMMetadata
from llama_index.core import Settings
from llama_index.llms.langchain import LangChainLLM


class CustomLLM1(LLM):
    model_id: str
    endpoint: str
    decoding_method: str
    temperature: float
    top_p: float
    top_k: int
    repetition_penalty: float
    validation_sequences: dict
    stopping_sequences: List[str]
    min_new_tokens: int
    max_new_tokens: int
    
    context_window: int = 8192
    num_output: int = 256
    model_name: str = "custom"


    @property
    def _llm_type(self) -> str:
        return "custom"
    
    @property
    def metadata(self) -> LLMMetadata:
        """Get LLM metadata."""
        return LLMMetadata(
            context_window=self.context_window,
            num_output=self.num_output,
            model_name=self.model_name,
        )

    def _call(
        self,
        prompt: str,
        # stop: Optional[List[str]] = None,
        run_manager: Optional[CallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> str:
        # if stop is not None:
        #     raise ValueError("stop kwargs are not permitted.")
        url = "http://123.46.10.123:123/func/genAI"
        data = {
            "prompt": prompt,
            "model_id": self.model_id,
            "decoding_method": self.decoding_method,
            "temperature": self.temperature,
            "top_p": self.top_p,
            "top_k": self.top_k,
            "repetition_penalty": self.repetition_penalty,
            "validation_sequences": self.validation_sequences,
            "stopping_sequences": self.stopping_sequences,
            "min_new_tokens": self.min_new_tokens,
            "max_new_tokens": self.max_new_tokens,
            "context_window" : 8192, # changed
            "endpoint": self.endpoint,
        }
        response = requests.post(url, data=json.dumps(data))
        response_text = response.text
        return response_text


llm = LangChainLLM(CustomLLM1(
    model_id="mistralai/mixtral-8x7b-instruct-v0-1",
    endpoint="",
    decoding_method="greedy", # can be one of greedy and sample
    temperature=0.7,
    top_p=0.9,
    top_k=50,
    repetition_penalty=1.0,
    validation_sequences={},
    stopping_sequences=["######"],
    min_new_tokens=1,
    max_new_tokens=200,
    context_window =8192,
))

I'm trying to invoke : 

from llama_index.packs.raptor import RaptorPack

raptor_pack = RaptorPack(
    documents,
    embed_model=embedding_function,  # used for embedding clusters
    llm=llm,  # used for generating summaries
    vector_store=vector_store,  # used for storage
    similarity_top_k=2,  # top k for each layer, or overall top-k for collapsed
    mode="collapsed",  # sets default mode
    transformations=[
        SentenceSplitter(chunk_size=400, chunk_overlap=50)
    ],  # transformations applied for ingestion
)

This is creating the context_window error - i guess this should be passed somehow , but i'm not able to . please help me out here , so that i can invoke the raptor package

**Comment by logan-markewich** [comment]
Try making the context window smaller

**Comment by helloadish007** [comment]
It's not working - i gave a context window of 1000. 

I'm seeing an article : https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom.html

Here what i can understand is that somehow i need to pass context_window in my customLLM class and update it. 

if anyone faced this issue - please help me out

**Comment by helloadish007** [comment]
@logan-markewich @tobi @wpiekutowski @bborn  

Hi , Can anyone help me out to resolve the above issue ?

**Comment by logan-markewich** [comment]
It's getting the metadata here

Not sure what to tell you beyond lowering it
https://github.com/run-llama/llama_index/blob/f9d80c0f7d4d075a57c0f1967fcedfe1d871b99e/llama-index-integrations/llms/llama-index-llms-langchain/llama_index/llms/langchain/base.py#L81
