### ISSUE TITLE
[Bug]: Kernel Crashing or CUDA OutOfMemory Error when running embedding model locally for large text files

### ISSUE THREAD

**Issue by rigvedrs** [run-llama/llama_index#12165]
### Bug Description

The system is overloading when I pass 4 page pdf documents or larger for converting to vectors. It is working when I pass small amount of texts like just 3 sentences. I have a 2 GB graphic card that can easily run the "BAAI/bge-small-en" embedding model, so this error is not supposed to occur. Running the model on cpu also ends up crashing the entire kernel.

### Version

0.10.18

### Steps to Reproduce

```
# load documents with deterministic IDs
documents = SimpleDirectoryReader(
    "../assets/files", filename_as_id=True
).load_data()

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en", cache_folder="./store/models", device='cpu')

index = VectorStoreIndex.from_documents(documents, embed_model=embed_model)

```

**Comment by rigvedrs** [comment]
Does llama index pass multiple nodes at once as inputs (asynchronously)? If so, is there a way to make make it run synchronously? It is working on a small chunk size of 300, but that wont be practical for my use case.

**Comment by rigvedrs** [comment]
@dosu-bot Does llama index pass multiple nodes at once as inputs (asynchronously)? If so, is there a way to make make it run synchronously? It is working on a small chunk size of 300, but that wont be practical for my use case.

**Comment by logan-markewich** [comment]
Local models cannot run async (they are compute bound), only api based models can be async

You could try lowering the batch size to reduce memory usage, default is 10

`HuggingFaceEmbedding(..., embed_batch_size=1)`

**Comment by rigvedrs** [comment]
This worked, thanks!
