### ISSUE TITLE
[Bug]: cannot get document node

### ISSUE THREAD

**Issue by yingfhu** [run-llama/llama_index#12171]
### Bug Description

The `get_document` function cannot get any document nodes
The following code uses the` node_collections` which does not include any document node.
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/storage/docstore/keyval_docstore.py#L276

### Version

master

### Steps to Reproduce

```
mini_index = VectorStoreIndex.from_documents([Document(text='hello world')])
mini_index.storage_context.docstore._kvstore.get_all(collection=mini_index.storage_context.docstore._ref_doc_collection)
mini_index.storage_context.docstore.get_document('*****replace with above doc id******')
```

**Comment by logan-markewich** [comment]
I know it's confusing, but the docstore only stores nodes (as well as matadata about each parent document)

**Comment by yingfhu** [comment]
Thanks for your reply. BTW, is there any interface that i can get the full document of a single node

**Comment by logan-markewich** [comment]
Once its broken into nodes, not really (mostly to avoid storing duplicates of the same text)

You can store in the metadata the name of the file though, to map back to it
