### ISSUE TITLE
[Question]: 新索引的使用

### ISSUE THREAD

**Issue by 827648313** [run-llama/llama_index#12172]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

有没有关键词索引 摘要索引的简单示例

**Comment by tslmy** [comment]
“关键词”的话，试试我写的这个？

https://github.com/tslmy/agent/blob/main/sub_question_generating_prompt_in_keywords.py

**Comment by 827648313** [comment]
> “关键词”的话，试试我写的这个？
> 
> https://github.com/tslmy/agent/blob/main/sub_question_generating_prompt_in_keywords.p
您这个我怎么感觉是构建prompt 呀，没有构建索引，以及查询的流程呢?

**Comment by 827648313** [comment]
> 嘿，@827648313！很高兴再次见到你，希望一切都好。
> 
> 是的，LlamaIndex支持关键词索引。提供的代码定义了一个`BaseKeywordTableIndex`类，该类从文本中提取关键词，并将每个关键词映射到相应的节点。这个过程模仿了一个"哈希表"机制，在索引构建过程中，通过从每个节点提取关键词并创建内部映射来构建关键词表。在查询时，从查询文本中提取关键词，然后使用这些关键词在关键词表中进行索引，以检索回答查询的节点。这个功能在`BaseKeywordTableIndex`类中的`_extract_keywords`，`_add_nodes_to_index`，和`_build_index_from_nodes`方法中很明显，以及在`KeywordTableIndex`类中重写的`_extract_keywords`方法，该方法特别使用了GPT模型来提取关键词。
> 
> 源代码：
> 
> * [llama-index-core/llama_index/core/indices/keyword_table/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/keyword_table/base.py)
> 
> 对于摘要索引，LlamaIndex目前可能还不支持。如果您需要这个功能，我建议您在LlamaIndex的GitHub仓库中提交一个新的issue，请求添加这个功能。
> 
> ## Sources
> * [llama-index-core/llama_index/core/indices/keyword_table/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/keyword_table/base.py)
> 
> #### About Dosu
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

 我看llamaIndex的官方文档是有这个索引的 ，难道是只有简单的描述？ 没有实际功能，除此之外，我看还有一个文档摘要，这个有实际的功能么？https://docs.llamaindex.ai/en/stable/api_reference/indices/summary/

**Comment by tslmy** [comment]
@dosu-bot 请对 @827648313 讲中文。

**Comment by tslmy** [comment]
@827648313 现在我明白您的意思了。不好意思，我其实不太清楚这些术语在汉语里怎么说。

您试过在GitHub里搜索“llama_index SummaryIndex”了吗？

<img width="653" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/b42106bf-d146-4f52-9aa7-199504b22698">

我这样搜索后，第一页就有这样的条目：

<img width="485" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/d1aa3a34-d644-4db2-951b-c5ab773fa385">

点开之后，我再在网页里搜索“SummaryIndex”字样，立刻就找到了它是怎么被使用的：

https://github.com/pchunduri6/rag-demystified/blob/e7b38d89ed5671675a9299a697e413483b75cfd6/llama_index_baseline.py#L149-L151

GitHub的搜索功能近年来有极高的增强，非常建议一试。

**Comment by 827648313** [comment]
> llama_index SummaryIndex
好的 感谢感谢

**Comment by tslmy** [comment]
@827648313 没啥追加问题的话可以先把这个issue关了，反正他们大部分人也读不懂中文 放这儿他们很多人都不知道该拿这个issue怎么办（我自己只是个志愿者）
