### ISSUE TITLE
[Feature Request]: is there a plan to integrate Grok-1 please?

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#12176]
### Feature Description

dear llama_index, is there a plan to integrate Grok-1 please?

**Comment by tslmy** [comment]
Dear @justinzyw (I'm not LlamaIndex though),

You can try Ollama. It can serve Grok 1:

<img width="849" alt="Screenshot 2024-03-25 at 00 05 08" src="https://github.com/run-llama/llama_index/assets/594058/6a067282-d396-4799-b761-3576fe0d33a4">

([source](https://ollama.com/joefamous/grok-1))

And LlamaIndex has integration with Ollama, so this route is technically possible.

Please let us know how it goes.

**Comment by justinzyw** [comment]
many thx for your suggestions.

**Comment by someshfengde** [comment]
grok has it's API also just laucned for public beta grok-2 is significant improvement would make sense for adding Grok as a provider current provider on Openai is not working when I tried. it checks for openai model names and errors out.

**Comment by MattBoraske** [comment]
> grok has it's API also just laucned for public beta grok-2 is significant improvement would make sense for adding Grok as a provider current provider on Openai is not working when I tried. it checks for openai model names and errors out.

Also encountered this and would like to use the xAI API for grok-2.

https://x.ai/blog/api
