### ISSUE TITLE
Remove stray service context usage for CondensePlusContextChatEngine

### ISSUE THREAD

**Issue by Shadyelgewily** [run-llama/llama_index#12177]
### Feature Description

As described and fixed in #12133, we should avoid using the Service Context and use global Settings object instead. This has not been done yet for the CondensePlusContextChatEngine.

### Reason

It may not have been obvious that the service context is still in use here, or it was not a priority yet.

### Value of Feature

It follows the suggested approach of lazily loading the llm, embedding models, etc.

**Comment by logan-markewich** [comment]
Can you clarify what you mean? I did a quick skim, the service context is not being used, it's merely a kwarg for backwards compatibility 

https://github.com/run-llama/llama_index/blob/f5263896121721de1051ce58338a1e0ea6950ca7/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L112

**Comment by Shadyelgewily** [comment]
My bad, I was looking at the legacy/chat_engine/condense_plus_context. IT has indeed already been updated. Will close this issue.
