### ISSUE TITLE
[Question]: SimpleDirectoryReader Problem Does not generate vector data

### ISSUE THREAD

**Issue by rgaesspi** [run-llama/llama_index#12181]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I have tried the sample code for using the SimpleDirectoryReader, however, i notice it doesn't work and throws ValueError message, i have tried on both Mac and Windows, and same issue has occured. I notice this with 0.10.20 version. Earlier version doesn't throw this kind of exception because i can see before that before the upgrade i did, i still see the vector data being generated.

Here's the sample code:
```
import os
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader("data").load_data()
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)
```

i tried debugging it by checking if i have correct permission and it seems that's not the issue because i can list the files in the data folder with the command below:
```
print("Current Working Directory:", os.getcwd())

# Attempt to list files in the "data" directory
try:
    print("Files in 'data' directory:", os.listdir("data"))
except FileNotFoundError:
    print("The 'data' directory was not found.")
except PermissionError:
    print("Permission denied when accessing the 'data' directory.")
```

The error message was:
```
Traceback (most recent call last):
  File "/Users/user/.pythonvenv/llamaindex-test/starter.py", line 7, in <module>
    documents = SimpleDirectoryReader("data").load_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pythonvenv/llamaindex-test/lib/python3.12/site-packages/llama_index/core/readers/file/base.py", line 215, in __init__
    self.input_files = self._add_files(self.input_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pythonvenv/llamaindex-test/lib/python3.12/site-packages/llama_index/core/readers/file/base.py", line 297, in _add_files
    raise ValueError(f"No files found in {input_dir}.")
ValueError: No files found in data.
```
Can anyone help me figure out what could be the problem?

**Comment by logan-markewich** [comment]
@rgaesspi do you have a folder named `"data"` ? Is that the correct path to the folder?

**Comment by logan-markewich** [comment]
This error is only raised if no files are found at that path

**Comment by rgaesspi** [comment]
![Screenshot 2024-03-22 at 11 53 59 PM](https://github.com/run-llama/llama_index/assets/26157131/623e3d1a-68ed-475b-b1f3-705555f56fa9)
i can confirm that i do have it. and permission are correct. which really confuses me what's going on.

**Comment by logan-markewich** [comment]
```
import os
print(os.listdir("./data"))

from llama_index.core import SimpleDirectoryReader
documents = SimpleDirectoryReader("./data").load_data()
print(len(documents))
```

Does that code work?

**Comment by rgaesspi** [comment]
> ```
> import os
> print(os.listdir("./data"))
> 
> from llama_index.core import SimpleDirectoryReader
> documents = SimpleDirectoryReader("./data").load_data()
> print(len(documents))
> ```
> 
> Does that code work?

No it didn't work. but it can print the data listed. 
```
['.DS_Store', 'paul_graham_essay.txt', 'old_vector', 'raw']
Traceback (most recent call last):
  File "/Users/randolfarevalo/.pythonvenv/esspiai-api/test.py", line 5, in <module>
    documents = SimpleDirectoryReader("./data").load_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pythonvenv/esspiai-api/lib/python3.12/site-packages/llama_index/core/readers/file/base.py", line 215, in __init__
    self.input_files = self._add_files(self.input_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/.pythonvenv/esspiai-api/lib/python3.12/site-packages/llama_index/core/readers/file/base.py", line 297, in _add_files
    raise ValueError(f"No files found in {input_dir}.")
ValueError: No files found in data.
```
this is tricky. hmm.

**Comment by tslmy** [comment]
@rgaesspi , how comfortable are you with IDEs? Can I ask you to go create a breakpoint at this line:

<img width="351" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/79ed1540-9a56-433a-810f-075a2ddb4b45">

set up a Run Configuration for your script, and then click this button:

<img width="97" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/b03685a8-6cc0-48dc-96c0-3f4af93a954b">

This invokes a debugger. It will pause the program at the line with that little red dot. You can then step through the code and see all the variables available at each line. You can at which point the reader decided to ignore the `.txt` file you provided.

Let us know how it goes.

**Comment by rgaesspi** [comment]
hey @tslmy thank you for the clue, i debug the code related to that and it seems to be skipping my files because of this code block
<img width="486" alt="Screenshot 2024-03-25 at 10 40 53 PM" src="https://github.com/run-llama/llama_index/assets/26157131/4be322ab-e10b-48c3-afc9-010bcc321bb2">

skip_because_hidden becomes TRUE. i set my parameters to this

`documents = SimpleDirectoryReader("data", exclude_hidden=False).load_data()`

and the error disappears. aggghhh. i least i figured out what's wrong.
