### ISSUE TITLE
[Question]: Index query vector has 1024 dimensions, but indexed vectors have 1536.

### ISSUE THREAD

**Issue by delicate00** [run-llama/llama_index#12195]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

我使用自己的向量模型“bge-large-zh”
vector_store = Neo4jVectorStore(username, password, url, 1024)
llm = Tongyi()
llm_predictor = LLMPredictor(llm=Tongyi())
from llama_index.legacy.embeddings.utils import resolve_embed_model
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    chunk_size=512,
    embed_model="local:bge-large-zh") 
storage_context = StorageContext.from_defaults(
        persist_dir='./storage_neo4j_Vector/nit',
        vector_store=vector_store,
        )
vector_index = load_index_from_storage(
        service_context=service_context,
        storage_context=storage_context
)
vector_query_engine = vector_index.as_query_engine()
response = vector_query_engine.query(question)

 报错问题为：
 Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 552, in _run_script
    exec(code, module.__dict__)
  File "D:\WYN\llamaindex\llamaindex_neo4j\llamaindex_neo4j\pages\1_基于原生向量对话.py", line 36, in <module>
    ai_message = query_Vector(prompt)                   # 使用chat对象对用户输入的消息进行处理，并将返回的助手消息赋值给ai_message变量
  File "D:\WYN\llamaindex\llamaindex_neo4j\llamaindex_neo4j\llamaindex_neo4j.py", line 167, in query_Vector
    response = vector_query_engine.query(question)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\core\base_query_engine.py", line 40, in query
    return self._query(str_or_query_bundle)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\query_engine\retriever_query_engine.py", line 171, in _query
    nodes = self.retrieve(query_bundle)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\query_engine\retriever_query_engine.py", line 127, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\core\base_retriever.py", line 229, in retrieve
    nodes = self._retrieve(query_bundle)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\indices\vector_store\retrievers\retriever.py", line 91, in _retrieve     
    return self._get_nodes_with_embeddings(query_bundle)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\indices\vector_store\retrievers\retriever.py", line 165, in _get_nodes_wi
th_embeddings
    query_result = self._vector_store.query(query, **self._kwargs)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\vector_stores\neo4jvector.py", line 380, in query
    results = self.database_query(read_query, params=parameters)
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\vector_stores\neo4jvector.py", line 334, in database_query
    return [r.data() for r in data]
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\llama_index\legacy\vector_stores\neo4jvector.py", line 334, in <listcomp>
    response.on_failure(summary_metadata or {})
  File "C:\ProgramData\Anaconda3\envs\deepke\lib\site-packages\neo4j\_sync\io\_common.py", line 245, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.queryNodes`: Caus
ed by: java.lang.IllegalArgumentException: Index query vector has 1024 dimensions, but indexed vectors have 1536.}
我如何将索引向量调整为1024，令它跟索引查询向量保持一致，我应该在哪里进行修改呢？

**Comment by delicate00** [comment]
@dosu-bot 当我修改了Elasticsearch的"dims": 1024，仍然会报这个错，我给如何解决？

**Comment by tslmy** [comment]
@delicate00 我有个猜想啊，您的数据库里是不是已经有数据了，然后这些数据当初输入进去的时候，是用的一个 1536 维度的模型？如果是的话，那么：

1. 如果想知道为什么，咱们需要找出来到底是哪个模型当初创建了存储进去的那些向量；
2. 如果想绕过这个问题，直接把数据库清空然后重新用bge-large-zh建立一遍即可。

**Comment by delicate00** [comment]
@tslmy 感谢您的回复，我尝试过清空本地持久化的数据以及neo4j中的数据，当我重新建立的时候还是在报这个错，所以综合您在上个问题的回复，我在考虑是不是我的用法有问题，又或者是哪里忘记修改导致的

**Comment by delicate00** [comment]
@tslmy @dosubot 下面是我的测试代码：
import os

from langchain_community.llms.tongyi import Tongyi
from llama_index.legacy import ServiceContext, SimpleDirectoryReader, VectorStoreIndex, StorageContext, LLMPredictor, \
    load_index_from_storage
from llama_index.legacy.embeddings import HuggingFaceEmbedding
from llama_index.legacy.vector_stores import Neo4jVectorStore
host = "127.0.0.1"
port = 7687
username = "neo4j"
password = "neo4j123"
url = f"bolt://{host}:{port}"

embed_dim = 1536
vector_store = Neo4jVectorStore(username, password, url, embed_dim)

os.environ["DASHSCOPE_API_KEY"] = ""
embed_model = HuggingFaceEmbedding(model_name="E:/ning/pycharm/llamaindex/llamaindex_neo4j/bge-large-zh-v1.5")

from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import Settings

Settings.embed_model = HuggingFaceEmbedding(
    model_name="/bge-large-zh-v1.5"
)

llm_predictor = LLMPredictor(llm=Tongyi())

service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    chunk_size=512,
    embed_model="local:E:/ning/pycharm/llamaindex/llamaindex_neo4j/bge-large-zh-v1.5"
    )

# 将一些文字转换为向量形式
documents = SimpleDirectoryReader(input_files=["E:/ning/pycharm/llamaindex/llamaindex_neo4j/doc/log.txt"]).load_data()
index = VectorStoreIndex.from_documents(documents,
                                        service_context=service_context,
                                        storage_context=StorageContext.from_defaults(vector_store=vector_store),
                                        # llm_predictor=LLMPredictor(llm=Tongyi())
                                        )
index.storage_context.persist(persist_dir='./test')


query_engine = index.as_query_engine()
response = query_engine.query("你好")
print("response", response)

报错为
neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureCallFailed} {message: Failed to invoke procedure `db.index.vector.queryNodes`: Caused by: java.lang.IllegalArgumentException: Index query vector has 1024 dimensions, but indexed vectors have 1536.}
Exception ignored in: <function Driver.__del__ at 0x000001C2EED89BD0>

**Comment by tslmy** [comment]
@delicate00 这应该是个bug，不然的话就是他们的文档里忘写了什么注意事项。我去替你用英语开个issue吧

**Comment by tslmy** [comment]
@delicate00 ， 等他们研究研究吧。在等待期间，你这边一定必须要用 Neo4jVectorStore 吗？可以用别的先代替一下吗？

```python
from llama_index.core import (
    Settings,
    SimpleDirectoryReader,
    StorageContext,
    VectorStoreIndex,
)
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.ollama import Ollama
from llama_index_client import ChromaVectorStore

# 我习惯用 Ollama 来 serve 我的 LLMs。
Settings.llm = Ollama(
    # “Qwen” 是“通义千问”的英文名。
    model="qwen",
    request_timeout=60,  # secs
    additional_kwargs={
        "stop": ["Observation:", "<|im_start|>", "<|im_end|>"],
    },
)
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-large-zh-v1.5")
# https://www.trychroma.com/
import chromadb

db = chromadb.PersistentClient(path="chroma_db")

if __name__ == "__main__":
    chroma_collection = db.create_collection("my_collection")
    vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
    documents = SimpleDirectoryReader(input_files=["文件.txt"]).load_data()
    print(f"A total of {len(documents)} documents loaded.")
    index = VectorStoreIndex.from_documents(
        documents=documents,
        storage_context=StorageContext.from_defaults(vector_store=vector_store),
    )
    query_engine = index.as_query_engine()
    response = query_engine.query("财报")
```

**Comment by delicate00** [comment]
感谢您，我尝试着替换一下数据库，然后重新上传我的数据，祝您工作顺利！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午1:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [run-llama/llama_index] [Question]: Index query vector has 1024 dimensions, but indexed vectors have 1536. (Issue #12195)





 
@delicate00 ， 等他们研究研究吧。在等待期间，你这边一定必须要用 Neo4jVectorStore 吗？可以用别的先代替一下吗？
 from llama_index.core import (     Settings,     SimpleDirectoryReader,     StorageContext,     VectorStoreIndex, ) from llama_index.embeddings.huggingface import HuggingFaceEmbedding from llama_index.llms.ollama import Ollama from llama_index_client import ChromaVectorStore # 我习惯用 Ollama 来 serve 我的 LLMs。 Settings.llm = Ollama(     # “Qwen” 是“通义千问”的英文名。     model="qwen",     request_timeout=60,  # secs     additional_kwargs={         "stop": ["Observation:", "<|im_start|&gt;", "<|im_end|&gt;"],     }, ) Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-large-zh-v1.5") # https://www.trychroma.com/ import chromadb db = chromadb.PersistentClient(path="chroma_db") if __name__ == "__main__":     chroma_collection = db.create_collection("my_collection")     vector_store = ChromaVectorStore(chroma_collection=chroma_collection)     documents = SimpleDirectoryReader(input_files=["文件.txt"]).load_data()     print(f"A total of {len(documents)} documents loaded.")     index = VectorStoreIndex.from_documents(         documents=documents,         storage_context=StorageContext.from_defaults(vector_store=vector_store),     )     query_engine = index.as_query_engine()     response = query_engine.query("财报")

**Comment by tslmy** [comment]
@delicate00 , 没事的！

另外，我觉得暂时可以把 https://github.com/run-llama/llama_index/issues/12195, https://github.com/run-llama/llama_index/issues/12221, and https://github.com/run-llama/llama_index/issues/12193 关掉，对他们也算是减少点干扰（他们大部分人好像都不懂汉语）

需要帮助的话我可以帮你用英文写一写，可以给我发一个联系方式到 issue12195@myli.page

**Comment by delicate00** [comment]
好的，我稍后就关闭



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月26日(星期二) 中午1:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [run-llama/llama_index] [Question]: Index query vector has 1024 dimensions, but indexed vectors have 1536. (Issue #12195)





 
@delicate00 , 没事的！
 
另外，我觉得暂时可以把 #12195, #12221, and #12193 关掉，对他们也算是减少点干扰（他们大部分人好像都不懂汉语）
 
需要帮助的话我可以帮你用英文写一写，可以给我发一个联系方式到 ***@***.***
