### ISSUE TITLE
[Bug]: NotImplementedError when accessing ref_doc_info after loading index from storage

### ISSUE THREAD

**Issue by Leonschmitt** [run-llama/llama_index#12201]
### Bug Description

After loading an index from storage with` load_index_from_storage` accessing the` ref_doc_info` attribute using Qdrant or Weaviate as vector store backends resulted in a `NotImplementedError`.  This error specifically indicates that Vector store integrations that store text in the vector store are not supported by ref_doc_info yet." This behavior was unexpected and indicates a limitation or an unimplemented feature within the llama-index library's handling of vector store integrations.

Interestingly, this issue doesn’t arise with `SummaryIndex`, indicating the problem is specific to VectorStoreIndex and its compatibility with the vector store backends.

### Version

llama-index version: 0.10.20 llama-index-core version: 0.10.20.post2

### Steps to Reproduce

1. Initialize the Vector Store and create a new `VectorStoreIndex`:
    ```python
    client = QdrantClient(path="/storage/qdrantstore")
    vector_store = QdrantVectorStore("llama2_paper", client=client, enable_hybrid=True, batch_size=20)
    new_index4 = VectorStoreIndex.from_documents(documents=[], storage_context=storage_context, store_nodes_override=True, show_progress=True)
    ```

2. Set up an `IngestionPipeline` and insert nodes into the index:
    ```python
    pipeline = IngestionPipeline(transformations=transformations, documents=docs)
    nodes = await pipeline.arun()
    new_index4.insert_nodes(nodes=nodes)
    ```

3. Set the index ID and persist the context:
    ```python
    new_index4.set_index_id("VSI-8af6bb89-0362-440d-a1a4-f88530dd0016")
    new_index4.storage_context.persist(persist_dir="/storage/newteststore")
    storage_context.docstore.add_documents(docs)
    ```

4. After these steps, when trying to access `ref_doc_info` from the loaded index, the following `NotImplementedError` is thrown:
 ```python
index = load_index_from_storage(storage_context=storage_context, index_id="VSI-8af6bb89-0362-440d-a1a4-f88530dd0016")
refinfo = index.ref_doc_info
```

```plaintext
    NotImplementedError: Vector store integrations that store text in the vector store are not supported by ref_doc_info yet.
   ```

- Interestingly, loading a `SummaryIndex` instead of a `VectorStoreIndex` does not result in the same error, indicating the functionality works as expected in that context. Furthermore, it's worth noting that accessing `refinfo = new_index4.ref_doc_info` directly (after the index's creation) works flawlessly.  
- This issue persists across both Qdrant and Weaviate vector store integrations.

**Comment by Leonschmitt** [comment]
@dosu-bot  This property is only applicable when the vector store does not store text or when the store_nodes_override flag is set to True.  But I have set the value of `store_nodes_override`  flag to true and still encounter this error after `load_index_from_storage`

**Comment by logan-markewich** [comment]
@Leonschmitt ref_doc_info doesn't really work with qdrant (or most vector db integrations) since the docstore is disabled by default. The nodes are all being stored in qdrant

you can override with with `VectorStoreIndex(..., store_nodes_override=True)` -- but you'll need to be sure to save the docstore/index_store to disk (or use a remote integration)

(and if you don't go that route, you don't really need load_index_from_storage, you could just use `VectorStoreIndex.from_vector_store(vector_store)`)
