### ISSUE TITLE
[Question]: My OpenAI resources have been depleted. How should I renew them?

### ISSUE THREAD

**Issue by newgooooal** [run-llama/llama_index#12212]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My OpenAI resources have been depleted. How should I renew them? I am using a Windows system, and I have tried changing the environment variables, but it has not worked.

**Comment by newgooooal** [comment]
> Hello @newgooooal! 👋 I'm [Dosu](https://dosu.dev), a bot here to help you solve bugs, answer your questions, and guide you on your journey to becoming a contributor. While we wait for a human maintainer, know that I'm here to assist you with any issues or questions you might have. I see you're having some trouble with your OpenAI resources - let me take a closer look and I'll provide you with a detailed answer shortly!

My OpenAI resources have been exhausted, and I would like to switch to a new OpenAI API. What should I do?

**Comment by tslmy** [comment]
@newgooooal , 你的问题读起来是因为你的OpenAI账号里余额不足。你可以去他们网站上充钱。这不是一个针对LlamaIndex的问题，所以在这里提问估计不会得到答案。

如果我误解了你的意思，请把你见到的错误提示复制、粘贴到这里，我们好能一起看。

(I wrote Chinese here because I saw you've been translating the webpage when you read replies from Dosu. If my assumption was wrong, you have my apologies.)
