### ISSUE TITLE
[Question]: where is the code in llama_index that generates one token?

### ISSUE THREAD

**Issue by lambda7xx** [run-llama/llama_index#12210]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to profile the model forward pass by using `torch.cuda.nvt`. Before call the forward to generate one token,  I add `nvtx.range_push`, after generate one token, I add `nvtx.range_pop()`

the code maybe like this.

```
import torch.cuda.nvtx as nvtx

llm = HuggingFaceLLM(
    model_name="mistralai/Mistral-7B-Instruct-v0.1",
    tokenizer_name="mistralai/Mistral-7B-Instruct-v0.1",
    query_wrapper_prompt=PromptTemplate("<s>[INST] {query_str} [/INST] </s>\n"),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"torch_dtype": torch.bfloat16},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.2, "top_k": 5, "top_p": 0.95},
    device_map="auto",
)


Settings.llm = llm

nvtx.range_push("forward)
code that generate one token.
nvtx.range_pop()

```

but where is the code in llama_index that generates one token?

**Comment by logan-markewich** [comment]
Assuming you mean during streaming?

The code is here for huggingface llm
https://github.com/run-llama/llama_index/blob/be63bae53227f1360472477eb2afa993791c09ce/llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py#L351

**Comment by lambda7xx** [comment]
that's awesome. thank you so much.
