### ISSUE TITLE
[Question]: /llama_index/legacy/service_context.py

### ISSUE THREAD

**Issue by delicate00** [run-llama/llama_index#12221]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

  在“/llama_index/legacy/service_context.py)”中提到了：
    # NOTE: the embed_model isn't used in all indices
    # NOTE: embed model should be a transformation, but the way the service
    # context works, we can't put in there yet.
    embed_model = resolve_embed_model(embed_model)
    embed_model.callback_manager = callback_manager
这代表我无法完全替换embedding模型吗，就算是我加载了本地的embed_model，也不能完全统一维度为我本地模型的维度吗？

**Comment by delicate00** [comment]
请问接下来会完善一下这个功能吗

**Comment by delicate00** [comment]
@dosubot  请问接下来会完善这个功能吗？

**Comment by tslmy** [comment]
@delicate00 我觉得很难了。官方已经把 ServiceContext 给 deprecate 掉了。

我不知道您在软件开发行业的背景深浅，所以我再多一句嘴，解释一下“deprecate”这个词的意思。它的意思里，包含（但不限于）这一条：之前他们写的“以后要fix 某某事“（这就包括您提到的“can't do that **yet**”里“yet”暗示的这个意思），都不会再考虑了。

我建议趁沉没成本还没有变得更加厚重，赶紧先转移到新版的写法。

**Comment by delicate00** [comment]
> @delicate00 我觉得很难了。官方已经把 ServiceContext 给 deprecate 掉了。
> 
> 我不知道您在软件开发行业的背景深浅，所以我再多一句嘴，解释一下“deprecate”这个词的意思。它的意思里，包含（但不限于）这一条：之前他们写的“以后要fix 某某事“（这就包括您提到的“can't do that **yet**”里“yet”暗示的这个意思），都不会再考虑了。
> 
> 我建议趁沉没成本还没有变得更加厚重，赶紧先转移到新版的写法。

好的，感谢您的答复和建议。如果是这样的话，相当于llamaindex把向量部分写死了，维度只能用1563的embedding模型，及时要使用本地加载，也只能是openai的text-embedding-ada-002，可以这样理解吗

**Comment by tslmy** [comment]
@delicate00 说实话，我从来没有读出过“向量维度被写死了”的意思。您是在哪里看到“1563”这个数字的呢？

在新版里（也就是把 ServiceContext 给替换成了 Settings object 的版本里），想用本地的，可以这样写：

https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings/#local-embedding-models

我去搜了一下这个示例里提到的“BAAI/bge-small-en-v1.5“这个模型，找到了[这个网页](https://huggingface.co/BAAI/bge-small-en-v1.5#evaluation)，发现这个模型是384维的：

<img width="470" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/d3ef00cb-e830-409f-9da6-5d552b42ff3c">

所以我觉得至少在新版里（重申：使用了 Settings object 的版本里），这个维度数量不是写死的。

如果你观测到了“维度被写死成 1563 了”这个现象，请把最直接的能复现这个问题的代码发来一下，并附上运行结果，我们可以一起看一下。
