### ISSUE TITLE
[Question]:can  RetryAgentWorker  only be implemented with OPENAI

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#12229]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`
query_engine_tools = vector_tools`
`agent_worker = RetryAgentWorker.from_tools(
    query_engine_tools,
    llm=llm,
    verbose=True,
    callback_manager=callback_manager,
)
`

ValueError: OpenAIPydanticProgram only supports OpenAI LLMs. Got: <class 'llama_index.llms.gemini.base.Gemini'>
How to correct the error?

**Comment by lzu-tangym** [comment]
same questions, I want to use other LLM instead of gpts, can I use the RetryAgentWorker with any settings ? or is there any class like RetryAgentWorker supports other LLM ?

**Comment by pipoupiwam** [comment]
Same question, i would like to use ollama local models.
