### ISSUE TITLE
[Question]: Using Agents with tools

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#12235]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I often find the agents using tools when it is not needed and it cant answer simple questions like "hi" and "what can you  do?" . It picks up a tool and gives response "sorry, cant answer your query". What can I do for this?.

**Comment by Prem-Nitin** [comment]
@dosu-bot how to do this in a application, I dont understand where to include the above code

**Comment by logan-markewich** [comment]
Add a system prompt to the agent with better instructions maybe? Or use a smarter LLM 😉
