### ISSUE TITLE
[Question]: Canceling Stream

### ISSUE THREAD

**Issue by sitbk** [run-llama/llama_index#12242]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Are there any built-in or otherwise recommended methods for canceling stream generation? I’ve tinkered a bit with multiprocessing and termination but it seems a bit overkill.

**Comment by logan-markewich** [comment]
There's nothing built in to cancel a stream 👀

**Comment by sitbk** [comment]
> There's nothing built in to cancel a stream 👀

That’s what I figured, tore through the documents before writing the question but hoped I missed something. Had a few occasions where the LLM just kept going and going.

Had a partial solution using multiprocessing where I’d spinoff the chat engine and terminate it as needed. Works well enough for “simple” chat mode engines but run into CUDA issues with other engines. Setting multiprocessing.set_start_method to spawn as the error recommends leads to pickling errors, so need to tweak some more.

Will figure something out.
