### ISSUE TITLE
[Question]: How to specify SystemMessage without LLMPredictor

### ISSUE THREAD

**Issue by apocas** [run-llama/llama_index#12241]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Before the LLMPredictor deprecation I would do this in order to specify a system message:
```qa_prompt = PromptTemplate(qa_prompt_tmpl)
llm_predictor = LLMPredictor(llm=model.llm, system_prompt=sysTemplate)
response_synthesizer = get_response_synthesizer(llm=llm_predictor, text_qa_template=qa_prompt, streaming=questionModel.stream)

query_engine = RetrieverQueryEngine(
    retriever=retriever,
    response_synthesizer=response_synthesizer
)
```
How can I specify a system message for the QueryEngine to use?

**Comment by logan-markewich** [comment]
Either include the system prompt in your prompt template, or include it in the LLM class itself

`<LLM_CLASS>(..., system_prompt="...")`
