### ISSUE TITLE
[Question]: can I use IngestionPipeline with TextNode objects?  

### ISSUE THREAD

**Issue by haolxx** [run-llama/llama_index#12250]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can I use IngestionPipeline with TextNode objects instead of documents? Thanks!

import asyncio

loop = asyncio.get_event_loop()
%timeit loop.run_until_complete(pipeline.arun(documents=documents, num_workers=4))

**Comment by logan-markewich** [comment]
`pipeline.run(nodes=nodes, ...)`
