### ISSUE TITLE
[Question]: Token Text Splitter not working

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12252]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

text_splitter = TokenTextSplitter(
  chunk_size=100,
  chunk_overlap=30,
  separator = ' ',
  tokenizer=tokenizer
)

index = VectorStoreIndex.from_documents(
    documents=documents, tranformations=text_splitter, storage_context=storage_context
)

When I check my vector database, the chunk size is more than 500 easy.
This is a problem I am experiencing after I upgraded to the latest llama-index version.

**Comment by logan-markewich** [comment]
Should be `tranformations=[text_splitter],`

tbh I'm surprised this doesn't raise an error (also fyi, chunk size of 100 is tiny, but I hopefully you know what's going on lol)

**Comment by Aekansh-Ak** [comment]
I tried that, it doesn't make a difference.

I did 100 to see if there is chunking going on or not.
