### ISSUE TITLE
[Question]: Don't include metadata for vectorstore

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#12260]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when i put this: #THIS

from llama_index.vector_stores.pinecone import PineconeVectorStore

vector_store = PineconeVectorStore(pinecone_index=pinecone_index, metadata_config=None )

but after this: # Create a new list with only the nodes that have a non-None embedding attribute

nodes_with_embeddings = [node for node in nodes if hasattr(node, 'embedding') and node.embedding is not None]

# Add only the nodes with embeddings to the vector store

vector_store.add(nodes_with_embeddings)

it get me this error: Upserted vectors: 0%| | 0/14837 [00:00<?, ?it/s]

--------------------------------------------------------------------------- PineconeApiException Traceback (most recent call last) Cell In[78], line 7 4 nodes_with_embeddings = [node for node in nodes if hasattr(node, 'embedding') and node.embedding is not None] 6 # Add only the nodes with embeddings to the vector store ----> 7 vector_store.add(nodes_with_embeddings) File ~/.local/lib/python3.10/site-packages/llama_index/vector_stores/pinecone/base.py:353, in PineconeVectorStore.add(self, nodes, add_kwargs) 351 ids.append(node_id) 352 entries.append(entry) --> 353 self._pinecone_index.upsert( 354 entries, 355 namespace=self.namespace, 356 batch_size=self.batch_size, 357 self.insert_kwargs, 358 ) 359 return ids File ~/.local/lib/python3.10/site-packages/pinecone/utils/error_handling.py:10, in validate_and_convert_errors.<locals>.inner_func(*args, **kwargs) 7 @wraps(func) 8 def inner_func(*args, **kwargs): 9 try: ---> 10 return func(*args, **kwargs) 11 except MaxRetryError as e: 12 if isinstance(e.reason, ProtocolError):

...

I don't want to include the metadata when uploading the nodes. How do I do that?

**Comment by logan-markewich** [comment]
Remove the metadata from your nodes? `node.metadata = {}` ?

Its not clear what the error is though, the traceback is all on one line and hard to read, seems like just a retry/connection issue though?

**Comment by GEN200J** [comment]
> Remove the metadata from your nodes? `node.metadata = {}` ?
> 
> Its not clear what the error is though, the traceback is all on one line and hard to read, seems like just a retry/connection issue though?

It isn't a connection issue, it's the fact that metadata is larger than the limit. I want to reduce the metdata size, how can I do it

**Comment by anoopshrma** [comment]
Before inserting, you could iterate over the and reduce the size of those which have large number of metadata.
