### ISSUE TITLE
[Question]: ImportError of ollama usage

### ISSUE THREAD

**Issue by linsong8208** [run-llama/llama_index#12269]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Saw some issues about ollama or gemma, but seems didnt cover my question.
I have successfully installed ollama, pulled gemma:2b, “ollama run gemma:2b”, ask and answer, everything all good.
I have successfully ‘pip install llama-index-llms-ollama’, and showed all requirements already satisfied.
But when
from llama_index.llms.ollama import Ollama
llm = Ollama(model="gemma:2b")
there was ImportError: cannot import name ‘global_handler’ from ‘llama_index.core’.

**Comment by lancercat** [comment]
Or simply drop all folders starts with llama here (fixed for me):

/home/[usr name]/.local/lib/python3.11/site-packages

**Comment by linsong8208** [comment]
Thanks Anoop, a new env worked well.
And also thanks lancercat although did not try your suggestion.
