### ISSUE TITLE
[Question]: How to know that  how many chunks a document is totally divided into

### ISSUE THREAD

**Issue by Xu-pixel** [run-llama/llama_index#12271]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

in starter example, I only can see it is in embedding process but can not see how many chunks a document is totally divided into.
Is there any method to get how much time it will take to finish all embeddings?
![image](https://github.com/run-llama/llama_index/assets/58813571/2a52566f-3431-4f48-b0b9-4c4bbac59668)

**Comment by anoopshrma** [comment]
You can set the chunk size as what Dosubot suggested.

**Comment by logan-markewich** [comment]
It inserts in batches of 2048 to limit memory usage. You could change that

You can also get the total number of nodes if you split before indexing

```
from llama_index.core.node_parser import SentenceSplitter, TokenTextSplitter

splitter = SentenceSplitter(chunk_size=1024, chunk_overlap=20)  # or could use token text splitter
nodes = splitter(documents)

print(len(nodes))

index = VectorStoreIndex(nodes=nodes, ..., insert_batch_size=2048)
```

**Comment by Xu-pixel** [comment]
> It inserts in batches of 2048 to limit memory usage. You could change that
> 
> You can also get the total number of nodes if you split before indexing
> 
> ```
> from llama_index.core.node_parser import SentenceSplitter, TokenTextSplitter
> 
> splitter = SentenceSplitter(chunk_size=1024, chunk_overlap=20)  # or could use token text splitter
> nodes = splitter(documents)
> 
> print(len(nodes))
> 
> index = VectorStoreIndex(nodes=nodes, ..., insert_batch_size=2048)
> ```

Thank you , it works, This is exactly what I want！
