### ISSUE TITLE
[Documentation]: quick add to the Loading Data (Ingestion) in Learn section

### ISSUE THREAD

**Issue by C00kie-** [run-llama/llama_index#12285]
### Documentation Issue Description

Hello; there is just the import line missing for this example: 

```text_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=10)

# global
from llama_index.core import Settings

Settings.text_splitter = text_splitter

# per-index
index = VectorStoreIndex.from_documents(
    documents, transformations=[text_splitter]
)

````
Which is (if I am not wrong ;-) ) this one: 

````
from llama_index.core.node_parser import SentenceSplitter

````

Thanks!

### Documentation Link

https://docs.llamaindex.ai/en/stable/understanding/loading/loading/

**Comment by sharsha315** [comment]
Hi, is this issue still open. Can I have the opportunity to work on this issue.
