### ISSUE TITLE
[Bug]: double docs folder for examples broke every single link in llamaindex documentation website 

### ISSUE THREAD

**Issue by LDD19** [run-llama/llama_index#12283]
### Bug Description

Directory is actually 
https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/llm/anthropic.ipynb instead of https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/anthropic.ipynb
![image](https://github.com/run-llama/llama_index/assets/25827839/5a6e4975-1ce3-4609-84af-6a6b0b451272)

### Version

latest

### Steps to Reproduce

open any colab link in https://docs.llamaindex.ai
example: https://docs.llamaindex.ai/en/stable/examples/llm/anthropic/

**Comment by logan-markewich** [comment]
I just merged a PR to fix this -- will be in the next release, should be on `latest` already
https://github.com/run-llama/llama_index/pull/12219/files

Funny enough, it doesn't seem like every link was caught, will fix on the next release
