### ISSUE TITLE
[Bug]: Query Understanding Agent LlamaPack example does not include pack installation example

### ISSUE THREAD

**Issue by justinwiley** [run-llama/llama_index#12298]
### Bug Description

The example [here](https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-query-understanding-agent/examples/query_understanding_agent.ipynb)

```
from llama_index.packs.query_understanding_agent.step import (
    QueryUnderstandingAgentWorker,
    HumanInputRequiredException,
)
```

...when run, produdes the error:

```
ModuleNotFoundError: No module named 'llama_index.packs'
```

### Version

0.10.23

### Steps to Reproduce

Run the associated notebook.  I was doing this outside of colab on a locale environment after installing the llama_index package.

**Comment by chilicrabcakes** [comment]
Can you try running `!pip install llama-index-packs-query-understanding-agent`? This seems to fix the issue for me
