### ISSUE TITLE
[Feature Request]: Streaming openai assistant api

### ISSUE THREAD

**Issue by illusion77** [run-llama/llama_index#12294]
### Feature Description

Streaming assistant api is now available.
https://community.openai.com/t/streaming-is-now-available-in-the-assistants-api/682011
https://platform.openai.com/docs/assistants/overview?context=with-streaming

**Comment by VJlaxmi** [comment]
Hello @illusion77,

Thank you for highlighting the availability of the streaming feature in the OpenAI Assistants API. This is a valuable addition and could enhance real-time interactions significantly.

To proceed, we should define clear use cases and requirements for integrating streaming. A technical proposal will then be drafted to outline how this feature can be incorporated into our current API structure.

I suggest we start with a basic implementation to test the core functionality and ensure compatibility. Concurrently, we can work on comprehensive documentation and testing strategies.

Looking forward to your input and collaboration to bring this feature to life!

**Comment by sveinjhu** [comment]
Any updates on this?
