### ISSUE TITLE
[Bug]: Unsatisfactory Results with Llama Index and MongoDB Vector Indexing

### ISSUE THREAD

**Issue by loyal812** [run-llama/llama_index#12292]
### Bug Description

I attempted to implement the Llama index alongside MongoDB vector indexing in my project, aiming to retrieve relevant data efficiently. However, after following the guide provided at https://www.mongodb.com/developer/products/atlas/rag-with-polm-stack-llamaindex-openai-mongodb/ and adapting it to my CSV data, the results have been disappointing. I am unable to retrieve the expected relevant data using this configuration.

### Version

0.10.22

### Steps to Reproduce

1. Followed the guide mentioned above to integrate Llama index with MongoDB vector indexing.
2. Imported and utilized my CSV data for indexing.
3. Executed queries to retrieve relevant data based on the implemented indexing.

### Additional Details:
- I have ensured that the configuration is correct and aligned with the provided guide.
- The CSV data used for indexing is structured appropriately.
- I have cross-checked the queries for accuracy.

**Comment by logan-markewich** [comment]
CSV data is pretty tricky. Vector retrieval/top-k is probably not what you want, unless each row represents a document

Probably you would be more interested in text-2-sql or pandas query engine

**Comment by loyal812** [comment]
> CSV data is pretty tricky. Vector retrieval/top-k is probably not what you want, unless each row represents a document
> 
> Probably you would be more interested in text-2-sql or pandas query engine

@logan-markewich Thank you for suggestion.

I've tried using pandas before, but unfortunately, the results were not satisfactory. However, I'm excited to try out text-2-SQL as a new solution. I'll give it a go and then I'll get back to you with an update. Let's see how it goes!
