### ISSUE TITLE
[Question]: Why is the abstraction `BaseAgentChatFormatter` there?

### ISSUE THREAD

**Issue by tslmy** [run-llama/llama_index#12308]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`ReActChatFormatter` is the only class that extends `BaseAgentChatFormatter`. It's actually also the only mention of `BaseAgentChatFormatter` besides `class BaseAgentChatFormatter`.

Judging from the names, I suspect @jerryjliu intended `BaseAgentChatFormatter` to be shared with `OpenAIAgent` back in 7/2023, but this seems to be no longer on the plan, is it?

https://github.com/run-llama/llama_index/blob/ff73754c5b68e9f4e49b1d55bc70e10d18462bce/llama-index-core/llama_index/core/agent/react/formatter.py#L35-L53

**Comment by logan-markewich** [comment]
I think the idea was maybe that other reasoning loops for agents would need a similar formatter 🤷🏻
