### ISSUE TITLE
RAG using GGUF building a real time chat application

### ISSUE THREAD

**Issue by elliotthwang** [run-llama/llama_index#12320]
### Feature Description

RAG using GGUF building a real time chat application

### Reason

Adopting the new settings configuring on GGUF, it taking  32 minutes to come up with the response unacceptable for a real time chat application.
DataDrivenInvestor's  Amaresh Patnaik publihed the article "RAG using GGUF" to show:
<img width="505" alt="RAG using GGUF" src="https://github.com/run-llama/llama_index/assets/22218711/1e9b04c4-70d8-4c61-bf2d-8651a4e90884">
Strongly suggest reserving the serviecontext as legacy to enjoy the real time chat. 
The following figures are excellent servicecontext performances：
llama_print_timings: load time = 440.50 ms
llama_print_timings: sample time = 83.53 ms / 100 runs ( 0.84 ms per token, 1197.19 tokens per second)
llama_print_timings: prompt eval time = 148.09 ms / 37 tokens ( 4.00 ms per token, 249.85 tokens per second)
llama_print_timings: eval time = 1629.66 ms / 99 runs ( 16.46 ms per token, 60.75 tokens per second)
llama_print_timings: total time = 2330.94 ms / 136 tokens

### Value of Feature

Let LLM into AGI to support mobile QA(quality assurance) of daily operation in any organization.

**Comment by elliotthwang** [comment]
DataDrivenInvestor's Amaresh Patnaik publihed the article "RAG using GGUF":
https://medium.datadriveninvestor.com/rag-using-gguf-a6a1bae49592

**Comment by logan-markewich** [comment]
Sorry, but there is no clear action item from this github issue.

GGUFcan be slow, depending on the hardware and model used, as well as how much data you are sending to the llm

**Comment by elliotthwang** [comment]
@logan-markewich 
Servicecontext has already reached the  online chat on GGUF, just reserve it into your legacy.
