### ISSUE TITLE
[Question]: Confusion after version update.

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12332]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Just need your validation if this is the correct way to use llama-index.
The documentation doesn't seem helpful.

#######################################################################
endpoint = f"https://admin:admin@localhost:9200"
idx = "sample-index"
text_field = "content"
embedding_field = "embedding"
client = OpensearchVectorClient(
    endpoint, idx, dim=384, embedding_field=embedding_field, text_field=text_field, use_ssl = False, verify_certs = False
)

vector_store = OpensearchVectorStore(client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

documents = SimpleDirectoryReader("/home/seceon/opensearch_lm_index/textdocs").load_data()

model_id = "lmsys/vicuna-13b-v1.5"
model = AutoModelForCausalLM.from_pretrained(model_id,
                                            device_map='auto',
                                            torch_dtype=torch.float16,
)

tokenizer = AutoTokenizer.from_pretrained(model_id)
streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

embeddings = HuggingFaceEmbedding()

text_split = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=300)
text_splitter = LangchainNodeParser(text_split)
Settings.text_splitter = text_splitter

pipe = pipeline(
        "text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens = 4000,
        streamer= streamer,
        torch_dtype=torch.float16,
        device_map="auto",
        top_p=0.93,
        temperature = 0.3,
        eos_token_id=tokenizer.eos_token_id
    )

llm = HuggingFacePipeline(pipeline=pipe)
llm = LangChainLLM(llm)

Settings.llm = llm
Settings.embed_model = embeddings
Settings.context_window=4096,
Settings.num_output=256,
Settings.chunk_overlap_ratio=0.3,
Settings.chunk_size_limit=None

# using a simple VectorStoreIndex
index = VectorStoreIndex.from_documents(
    documents=documents,  storage_context=storage_context,
)

Question:
Should I explicitly do transformation = [text_splitter ] or is it okay because I did Settings.text_splitter = text_splitter.
Any other suggestion is welcome.

**Comment by logan-markewich** [comment]
`Settings.text_splitter = text_splitter` is fine, this sets the global default

`transformations=[text_splitter]` would be for local overrides to the global default
