### ISSUE TITLE
[Bug]: Newest versions of llama-index-agent-openai don't install

### ISSUE THREAD

**Issue by JoelGotsch** [run-llama/llama_index#12330]
### Bug Description

llama_index pyproject.toml has dependency llama-index-agent-openai = "^0.1.4", but newest version is 0.2.1, which is therefore incompatible.
A simple version bump should do it, will create a quick PR for it. But if the PR is not accepted because its not material, I'd understand.

### Version

0.10.24

### Steps to Reproduce

Try to update your project to newest llama-index-agent-openai version.
This will install a 0.1.x version, not 0.2.1

**Comment by logan-markewich** [comment]
Oh whoops, good catch. I can bump the version there

**Comment by JoelGotsch** [comment]
It's in two places though, as I just discovered. program-openai also has the dependency pinned and needs therefore a bump.
PR is 5min away, just testing that there are no conflicts ;)
