### ISSUE TITLE
[Bug]: LangchainEmbedding Deleted??!

### ISSUE THREAD

**Issue by CHesketh76** [run-llama/llama_index#12331]
### Bug Description

LangchainEmbedding has been completely removed and current documentation has not updated to reflect any changes.

### Version

V0.10.24, I think, PLEASE ADD ```llama_index.__version___``` like what ever other package does

### Steps to Reproduce

1.) Open Colab notebook
2.) Run ```!pip install llama_index```
3.) Run any of these lines ```from llama_index import LangchainEmbedding``` or ```from llama_index.embeddings import LangchainEmbedding``` or ```from llama_index.embeddings.langchain import LangchainEmbedding```

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------

ImportError                               Traceback (most recent call last)

<ipython-input-1-683b3f1b99b4> in <cell line: 13>()
     11 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
     12 
---> 13 from llama_index.embeddings import LangchainEmbedding
     14 from langchain.embeddings.huggingface import HuggingFaceEmbeddings
     15 

ImportError: cannot import name 'LangchainEmbedding' from 'llama_index.embeddings' (unknown location)


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by logan-markewich** [comment]
@CHesketh76 v0.10.x split every package into an integration, using namespaces imports -- `llama-index-core`, `llama-index-embeddings-langchain`, etc, are all packages.

There is no actual root package, `llama-index` is an empty package that wraps several starter dependencies

`llama_index.core.__version__` is probably what you want.

As for the actual package in question

`pip install llama-index-embeddings-langchain`

`from llama_index.embeddings.langchain import LangchainEmbedding`

All our documentation reflects these new installs and imports.

You can also see https://llamahub.ai for all integrations, or check out the api reference https://docs.llamaindex.ai/en/stable/api_reference/

**Comment by logan-markewich** [comment]
This docs page is also updated
https://docs.llamaindex.ai/en/stable/examples/embeddings/Langchain/?h=langcha
