### ISSUE TITLE
[Bug]: Error Encountered with asyncio.run() while Generating Train Data using Llama Index

### ISSUE THREAD

**Issue by loyal812** [run-llama/llama_index#12336]
### Bug Description

When trying to generate train data using Llama Index following the documentation for fine-tuning OpenAI models, I encountered the following error: "`asyncio.run() cannot be called from a running event loop`". I followed the instructions provided in the official documentation, but I am facing this issue now.

### Version

0.10.20

### Steps to Reproduce

1. Followed the guide at: [Link to the documentation](https://docs.llamaindex.ai/en/v0.10.22/examples/finetuning/openai_fine_tuning/)
2. Attempted to generate train data as per the instructions
3. Encountered the error: "`asyncio.run() cannot be called from a running event loop`"

### Relevant Logs/Tracbacks

```shell
Error in attempt: asyncio.run() cannot be called from a running event loop
```

**Comment by logan-markewich** [comment]
Add this to your code

```
import nest_asyncio
nest_asyncio.apply()
```

**Comment by loyal812** [comment]
> Add this to your code
> 
> ```
> import nest_asyncio
> nest_asyncio.apply()
> ```

@logan-markewich Thank you
It working well.
