### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.core.vector_stores.google'

### ISSUE THREAD

**Issue by napokhte** [run-llama/llama_index#12358]
### Bug Description

I attempted to execute the notebook from https://docs.llamaindex.ai/en/stable/examples/managed/GoogleDemo
In the setup cell, the code includes `import llama_index.core.vector_stores.google.generativeai.genai_extension as genaix`. 
However, executing this line resulted in a "module not found" error.

### Version

latest

### Steps to Reproduce

Follow the notebook instructions sequentially until you reach the setup cell.
https://docs.llamaindex.ai/en/stable/examples/managed/GoogleDemo/#setup

**Comment by napokhte** [comment]
llama-index                              0.10.24
llama-index-agent-openai                 0.1.7
llama-index-cli                          0.1.11
llama-index-core                         0.10.24.post1
llama-index-embeddings-openai            0.1.7
llama-index-indices-managed-google       0.1.3
llama-index-indices-managed-llama-cloud  0.1.5
llama-index-legacy                       0.9.48
llama-index-llms-gemini                  0.1.6
llama-index-llms-openai                  0.1.13
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.5
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.12
llama-index-readers-llama-parse          0.1.4
llama-index-response-synthesizers-google 0.1.3
llama-index-vector-stores-google         0.1.5
llama-parse                              0.4.0
llamaindex-py-client                     0.1.13

**Comment by napokhte** [comment]
replace: `import llama_index.core.vector_stores.google.generativeai.genai_extension as genaix`
with:
`import llama_index.vector_stores.google.genai_extension as genaix`
to fix the issue.

**Comment by napokhte** [comment]
Upon proceeding to the "Basic Usage" cell and executing it, I encountered the following output:

```
Newly created corpus ID is llama-index-colab-171406-1.
Document c639326f-56e2-47b8-9bef-945fc92e0807 in corpus llama-index-colab-171406-1 not found: 404 Document does not exist.
```

However, the "Download Data" cell successfully retrieved the data as shown below:

```
--2024-03-28 01:26:23--  https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 75042 (73K) [text/plain]
Saving to: ‘data/paul_graham/paul_graham_essay.txt’

data/paul_graham/paul_graham_essay.txt 100%[===================>]  73.28K  --.-KB/s    in 0.02s   

2024-03-28 01:26:23 (2.93 MB/s) - ‘data/paul_graham/paul_graham_essay.txt’ saved [75042/75042]
```

This indicates that while the data download was successful, there seems to be an issue with document retrieval or indexing in the subsequent cell.

**Comment by ychenwynn** [comment]
Was this ever resolved? I'm running into the same issue
