### ISSUE TITLE
[Question]: Is `seed` supported with Azure OpenAI?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#12355]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is the `seed` OpenAI parameter supported in the existing `AzureOpenAI` implementation in LlamaIndex?  Running through the debugger it appears not.

**Comment by logan-markewich** [comment]
It's probably supported through the `additinal_kwargs`  option I would think?

**Comment by brycecf** [comment]
It definitely doesn't follow the same path as something like `temperature`.  Without code changes, it may need to be an argument to [QueryPipeline.run](https://github.com/run-llama/llama_index/blob/79deba359cfdbc3e89b3dfa92a8805285ea3d14b/llama-index-core/llama_index/core/query_pipeline/query.py#L320)

**Comment by brycecf** [comment]
Confirmed `additional_kwargs` is the answer. Also, provides a way to use systems prompts in a query pipeline.  Thanks @logan-markewich
