### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.storage'

### ISSUE THREAD

**Issue by rudrakhsha-c** [run-llama/llama_index#12364]
### Bug Description

I am unable to use the chat store object provided by the llama index storage class. 
```
from llama_index.storage.chat_store.redis import RedisChatStore

ModuleNotFoundError: No module named 'llama_index.storage'
```
Getting the above error
How do I solve this issue?
Is there any other dependency we have to install to access chatstores?

### Version

0.10.25

### Steps to Reproduce

!pip install llama-index
from llama_index.storage.chat_store.redis import RedisChatStore

Run the above code and you will get the error.

**Comment by rudrakhsha-c** [comment]
@dosubot even after modifying my requirements according to your given changes, the error still persists.
```
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-21-454faf11dd3e>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from llama_index.core.storage.chat_store.redis_chat_store import RedisChatStore

ModuleNotFoundError: No module named 'llama_index.core.storage.chat_store.redis_chat_store'
```
Using the version mentioned in your comment. Can you please help?

**Comment by logan-markewich** [comment]
@rudrakhsha-c its a package, the same as every integration

`pip install llama-index-storage-chat-store-redis`

I welcome a PR to update that docs page, otherwise I'll get to it at some point
