### ISSUE TITLE
[Question]: why response is always document related.. eventhough query is simple "Hi"

### ISSUE THREAD

**Issue by Sridevi17j** [run-llama/llama_index#12360]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

"Why does the LLM consistently respond with document-related information instead of acknowledging a simple greeting like 'Hi'?"

**Comment by Sridevi17j** [comment]
Can you give some sample code, in lama_index, if I type "hi" or "hello" non query input, it should reply with "Hello! How can I assist you today"? like this...

**Comment by Sridevi17j** [comment]
@dosu-bot Can you give some sample code, in lama_index, if I type "hi" or "hello" non query input, it should reply with "Hello! How can I assist you today"? like this...

**Comment by logan-markewich** [comment]
@Sridevi17j Are you using a chat engine? Or a query engine? The query engine by default uses very specific prompt templates that basically tell it to only use retrieved context to answer. These are meant for one-off queries, not conversations

chat engines are more open-ended
