### ISSUE TITLE
[Question]: Using Llama-index text to sql query engine, with vector store index. Are embedding loaded in memory or in disk?

### ISSUE THREAD

**Issue by Vybhav448** [run-llama/llama_index#12367]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Question]: Using Llama-index text to sql query engine, with vector store index. Having created the table and row embeddings, can you explain where we are hosting or loading the embedding for retrieving the relevant nodes, is it in-memory or in disk.

**Comment by logan-markewich** [comment]
It depends where your embeddings are and what vector db you are using, but the default is in-memory

Other vector dbs are more efficient/scalable (qdrant, chroma), or are hosted in the cloud (pinecone, weaviate)
