### ISSUE TITLE
[Question]: Usage of dataframe operations

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_index#12368]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi Team,

I could see that I able to run application using single dataframe as per below link:
https://docs.llamaindex.ai/en/stable/examples/query_engine/pandas_query_engine/

But, If I wanted to perform complex operations like with multiple dataframes and finding matches, sorting etc, is it supported? If so, how it can be?

**Comment by logan-markewich** [comment]
It's not supported, or rather, not built in. You could build/design your own query pipeline to do this though

https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline_pandas/
https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline/?h=query+pipeline
