### ISSUE TITLE
[Question]: Hybrid search?

### ISSUE THREAD

**Issue by chengyjonathan** [run-llama/llama_index#12381]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there!

I'm wondering where would be the best place to get started if I wanted to implement a lexical, semantic, graph search hybrid.

I see the examples for doing lexical + semantic retrieval. 

And I was wondering if there are any guides for doing semantic + kg retrieval.

**Comment by logan-markewich** [comment]
I think any custom retriever could do this. Or using the query fusion retriever and passing in all the retrievers you want to mix

https://docs.llamaindex.ai/en/stable/examples/retrievers/relative_score_dist_fusion/?h=query+fusion

**Comment by logan-markewich** [comment]
@chengyjonathan 3 retrievers, that then get composed into one. How you get those retrievers is up to you 👍🏻

**Comment by anhthyngo** [comment]
> I think any custom retriever could do this. Or using the query fusion retriever and passing in all the retrievers you want to mix
> 
> https://docs.llamaindex.ai/en/stable/examples/retrievers/relative_score_dist_fusion/?h=query+fusion

@logan-markewich 

If I had a KnowledgeGraphRAGRetriever and a VectorIndexAutoRetriever and wanted to fuse them - would the SQLAutoVectoryQueryEngine framework but for Knowledge Graphs be the correct approach over this Fusion retriever?

 https://docs.llamaindex.ai/en/stable/examples/query_engine/SQLAutoVectorQueryEngine/
