### ISSUE TITLE
[Question]: Streaming using TextStreamer

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12384]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

from transformers import AutoTokenizer, AutoModelForCausalLM, TextStreamer
from llama_index.llms.huggingface import HuggingFaceLLM

streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

llm = HuggingFaceLLM(
    model_name=model_id,
    tokenizer_name=model_id,
    query_wrapper_prompt=PromptTemplate(PROMPT),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"torch_dtype": torch.float16},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.2,  "top_p": 0.95},
    device_map="auto",
    streamer=streamer
)

This doesn't work, how can I use TextStreamer in llamaindex

**Comment by logan-markewich** [comment]
@Aekansh-Ak its already using that under the hood for streaming. There's no option to pass it in

```
resp = llm.stream_complete("Hello")
for r in resp:
  print(str(r), end="", flush=True)
```

**Comment by Aekansh-Ak** [comment]
The output comes out like this:

In 
In the 
In the given 
In the given 
In the given scenario, 
In the given scenario, my 
In the given scenario, my role 
In the given scenario, my role as 
In the given scenario, my role as a 
In the given scenario, my role as a 
In the given scenario, my role as a 
In the given scenario, my role as a 
In the given scenario, my role as a 
In the given scenario, my role as a chatbot 
In the given scenario, my role as a chatbot 
In the given scenario, my role as a chatbot 
In the given scenario, my role as a chatbot doesn't 
In the given scenario, my role as a chatbot doesn't involve 
In the given scenario, my role as a chatbot doesn't involve discussing 
In the given scenario, my role as a chatbot doesn't involve discussing any 
In the given scenario, my role as a chatbot doesn't involve discussing any particular 
In the given scenario, my role as a chatbot doesn't involve discussing any particular individual

**Comment by Aekansh-Ak** [comment]
Got this from your documentation-:

query_engine = index.as_query_engine(streaming=True, similarity_top_k=1)
response_stream = query_engine.query(
    "What did the author do growing up?",
)

response_stream.print_response_stream()

Gives error-:    

res.print_response_stream()
AttributeError: 'Response' object has no attribute 'print_response_stream'

**Comment by logan-markewich** [comment]
@Aekansh-Ak works fine for me
https://colab.research.google.com/drive/13w6OkOxf98Yow9uTqZ8lUV9hEUhKrQVR?usp=sharing

**Comment by logan-markewich** [comment]
Should have been print(r.delta, end="", flush=True) btw

**Comment by Aekansh-Ak** [comment]
Thanks but I did using this, it worked.

resp = query_engine.query(query_str)
for r in resp.response_gen:
   print(str(r), end="", flush=True)
