### ISSUE TITLE
[Question]: Query questions encountered in the search.

### ISSUE THREAD

**Issue by rap8** [run-llama/llama_index#12398]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I just learned lamaindex. I'm curious how metadata is involved in the retrieval part of the query retrieval phase, but I can't seem to find a description of this part in the documentation. Can you simply point out the area of code? Or a document. This is very helpful to me, thank you.^^.

**Comment by rap8** [comment]
> Hey there, @rap8! Nice to see you diving into LlamaIndex again. Hope you're doing awesome! 😄👋嘿，！很高兴看到您再次潜入 LlamaIndex。希望你做得很好！😄👋
> 
> Sure, I can help with that. The usage of metadata in the retrieval part of the query retrieval phase in LlamaIndex is not explicitly described in the documentation. However, there is a similar issue that was raised and closed in the LlamaIndex repository that might be helpful to you.当然，我可以帮忙。文档中没有明确描述 LlamaIndex 中查询检索阶段的检索部分元数据的使用。但是，在 LlamaIndex 存储库中提出并关闭了一个类似的问题，可能对您有所帮助。
> 
> The issue is titled [[Question]: How does llama-index using metadata for query?](https://github.com/run-llama/llama_index/issues/8172). The solution provided in this issue suggests customizing the usage of metadata in LlamaIndex to improve the recall of a Retriever. This is done by extending the keywords list with the 'summary' in metadata. You can achieve this by modifying the `_retrieve` method in the `DocumentSummaryIndexLLMRetriever` class.该问题的标题是 [问题]：如何使用元数据进行查询的 llama-index？。本期提供的解决方案建议自定义 LlamaIndex 中元数据的使用，以改善对 Retriever 的召回。这是通过在元数据中使用“摘要”扩展关键字列表来完成的。可以通过修改 `DocumentSummaryIndexLLMRetriever` 类中 `_retrieve` 的方法来实现此目的。
> 
> Here is the code snippet provided in the issue:以下是问题中提供的代码片段：
> 
> ```python
> def _retrieve(
>     self,
>     query_bundle: QueryBundle,
> ) -> List[NodeWithScore]:
>     """Retrieve nodes."""
>     summary_ids = self._index.index_struct.summary_ids
>     all_summary_ids: List[str] = []
>     all_relevances: List[float] = []
>     for idx in range(0, len(summary_ids), self._choice_batch_size):
>         summary_ids_batch = summary_ids[idx : idx + self._choice_batch_size]
>         summary_nodes = self._index.docstore.get_nodes(summary_ids_batch)
>         
>         # Extend the keywords list with the 'summary' in metadata
>         for node in summary_nodes:
>             if 'metadata' in node and 'summary' in node['metadata']:
>                 node['keywords'].extend(node['metadata']['summary'])
>         
>         query_str = query_bundle.query_str
>         fmt_batch_str = self._format_node_batch_fn(summary_nodes)
>         # call each batch independently
>         raw_response = self._service_context.llm_predictor.predict(
>             self._choice_select_prompt,
>             context_str=fmt_batch_str,
>             query_str=query_str,
>         )
>         raw_choices, relevances = self._parse_choice_select_answer_fn(
>             raw_response, len(summary_nodes)
>         )
>         choice_idxs = [choice - 1 for choice in raw_choices]
> 
>         choice_summary_ids = [summary_ids_batch[ci] for ci in choice_idxs]
> 
>         all_summary_ids.extend(choice_summary_ids)
>         all_relevances.extend(relevances)
> 
>     zipped_list = list(zip(all_summary_ids, all_relevances))
>     sorted_list = sorted(zipped_list, key=lambda x: x[1], reverse=True)
>     top_k_list = sorted_list[: self._choice_top_k]
> 
>     results = []
>     for summary_id, relevance in top_k_list:
>         node_ids = self._index.index_struct.summary_id_to_node_ids[summary_id]
>         nodes = self._index.docstore.get_nodes(node_ids)
>         results.extend([NodeWithScore(node=n, score=relevance) for n in nodes])
> 
>     return results
> ```
> 
> This modification assumes that each node has a 'keywords' list and a 'metadata' dictionary with a 'summary' list. The 'summary' list from the metadata is added to the 'keywords' list for each node.此修改假定每个节点都有一个“关键字”列表和一个带有“摘要”列表的“元数据”字典。元数据中的“摘要”列表将添加到每个节点的“关键字”列表中。
> 
> The original `_retrieve` method can be found in the `DocumentSummaryIndexLLMRetriever` class in the [llama_index/indices/document_summary/retrievers.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/document_summary/retrievers.py) file.原始 `_retrieve` 方法可以在 `DocumentSummaryIndexLLMRetriever` 类的 llama_index/indices/document_summary/retrievers.py 文件中找到。
> 
> I hope this helps! If you have any other questions, feel free to ask.我希望这会有所帮助！如果您有任何其他问题，请随时提问。
> 
> ## Sources 来源
> * [[Question]: How does llama-index using metadata for query?[问题]：llama-index 如何使用元数据进行查询？](https://github.com/run-llama/llama_index/issues/8172)
> * [llama-index-core/llama_index/core/extractors/metadata_extractors.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/extractors/metadata_extractors.py)
> 
> #### About Dosu 关于Dosu
Sorry, maybe my problem description is not appropriate. What I want to know is how the metadata is involved in generating the corresponding response when generating the response. I don't quite understand this part. If you can provide this part of the code or documentation, it will be of great help to me, thank you!

**Comment by rap8** [comment]
I think I found the answer to my question, it helped me a lot, thank you~ ^^

**Comment by logan-markewich** [comment]
@rap8 Yea, metadata is included by default when generating embeddings and sending text to the LLM

You can control what metadata is used by customizing the nodes/documents. You can read more here
https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/?h=customizing#advanced-metadata-customization
