### ISSUE TITLE
[Question]: Token limit openai 

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#12404]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone, I am building a RAG system and currently in the process of converting data to embeddings and ingesting to vectordb. However, I am running on an issue with the embedding large model when using the api. After 145 min of converting the data to embeddings, I got an error saying that the index exceeded the token limit. The problem is that I coded a mini tool to identify if there were any indexes/nodes that I have that exceeded the 8191 limit. After running it it said that no index had over 8190 tokens. I know it works well because before, I had a lot of issues with exceeding the token limit and the tool worked great and identified each index. The problem is now I don’t know what is happening, I obviously counted metadata to do this, but the tool sais there is not index but openai api stopped after a while because of one index. Please answer if you have issues with token limits or if you know smth about this. What I was thinking now is that maybe the request to the api adds more tokens but I am not sure since I did this many times and never happened.

This is the code I run:
for node in nodes:
    node_embedding = embed_model.get_text_embedding(
        node.get_content(metadata_mode="all")
    )
    node.embedding = node_embedding

**Comment by logan-markewich** [comment]
@GEN200J did you chunk your data when creating nodes? Its highly recommended to use some kind of text splitter to control chunk sizes

I might do
```
from llama_index.core.node_parser import TokenTextSplitter, SentenceSplitter

nodes = TokenTextSplitter(chunk_size=1024, chunk_overlap=20)(nodes)
```

**Comment by GEN200J** [comment]
> @GEN200J did you chunk your data when creating nodes? Its highly recommended to use some kind of text splitter to control chunk sizes
> 
> I might do
> 
> ```
> from llama_index.core.node_parser import TokenTextSplitter, SentenceSplitter
> 
> nodes = TokenTextSplitter(chunk_size=1024, chunk_overlap=20)(nodes)
> ```

I didnt use one of the llama index text splitters, I used my own. But I don't know why its giving me that error since I verified using the code I already posted.

**Comment by logan-markewich** [comment]
@GEN200J it's giving that error because your text is exceeding the context size. Maybe double check your splitting?

Remember, node metadata is also included in embeddings unless specifically excluded 
https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/#advanced-metadata-customization

**Comment by GEN200J** [comment]
Logan, I checked all the chunks and were fine. I re run the process of embedding all nodes again and got the error in about 10 out of 24k nodes. In the code I included to tell me which indexes exceeded the limit, I checked, and the nodes I got errors were about 8050 each. I now that the metadata also counts for token limit, however, the metadata each node had was between 50-100 tokens. I really don't know what happened there because I got nodes that are 8120 tokens with a metadata of 60 tokens and I get no errors.

**Comment by logan-markewich** [comment]
@GEN200J how are you counting tokens?

**Comment by GEN200J** [comment]
> @GEN200J how are you counting tokens?

Using tiktoken with cl100k_base tokenizer

**Comment by logan-markewich** [comment]
But like, give me a code example 😅
