### ISSUE TITLE
[Bug]: Static typed returns in the method "class_name"

### ISSUE THREAD

**Issue by saurabhmahra91** [run-llama/llama_index#12409]
### Bug Description

There is a typing error [here](https://github.com/run-llama/llama_index/blob/0cfb2c912041828a6c08cc85eb538cfc45f096ef/llama-index-integrations/vector_stores/llama-index-vector-stores-pinecone/llama_index/vector_stores/pinecone/base.py#L344)

Instead of `return "PinconeVectorStore"` it should have been `return "PineconeVectorStore"` (mind the misspelled `e`)

It should not have occurred in the first place. The class name attribute should be dynamically calculated rather than hardcoding it. This could've been done with builtin methods in python such as 

dog = Animal()
dog.\_\_class\_\_.\_\_name\_\_  \#returns the string "Animal"

### Version

0.10.25

### Steps to Reproduce

```python
from llama_index.vector_stores.pinecone import PineconeVectorStore
print(PineconeVectorStore.class_name())
```

**Comment by logan-markewich** [comment]
@saurabhmahra91 making it dynamic is not ideal. This should be a static name. This is intended to help with serializing and deserializing into proper classes. If the key can change any time, then it makes that task a lot harder

**Comment by saurabhmahra91** [comment]
@logan-markewich Not dynamic like that.
Basically we should never have to type again the name of the class, and the class_name method should always return the class name based on its definition.

By dynamically calculated, I meant that the class_name method should return the class's actual name instead of a user-defined string that could differ from the actual class name.

I have also highlighted a typing error in the codebase. Please have a look at it to understand what I am trying to say.
