### ISSUE TITLE
[Question]: Storing query responses as cache for faster retrieval

### ISSUE THREAD

**Issue by AniketNG** [run-llama/llama_index#12411]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm currently using llama-index to query with database and I want to store the query responses as cache or in some format such that further when similar questions are asked it'll retrieve the responses quickly and without having to process using llm. 
Is there anything like this that already exists, i was unable to find something specifically for querying with databases.

**Comment by AniketNG** [comment]
> Hey @AniketNG! Great to see you diving deeper into LlamaIndex. How's the coding journey going? 😎
> 
> To store query responses as cache for faster retrieval in future similar queries using LlamaIndex, you can use the `IngestionCache` class. This class is designed to cache the results of data transformations during the ingestion process, which can help avoid redundant computations by storing the results of transformations and retrieving them when the same transformation is requested again.
> 
> Here's a basic example of how you can use `IngestionCache`:
> 
> ```python
> from llama_index.ingestion.cache import IngestionCache, get_transformation_hash
> from llama_index.ingestion.transform import TransformComponent
> from llama_index.node import BaseNode, TextNode
> from typing import List, Any
> 
> # Instantiate the IngestionCache
> cache = IngestionCache()
> 
> # Define your transformation
> class DummyTransform(TransformComponent):
>     def __call__(self, nodes: List[BaseNode], **kwargs: Any) -> List[BaseNode]:
>         for node in nodes:
>             node.set_content(node.get_content() + "\nTESTTEST")
>         return nodes
> 
> # Generate a transformation hash
> transformation = DummyTransform()
> node = TextNode(text="dummy")
> hash = get_transformation_hash([node], transformation)
> 
> # Apply the transformation and cache the result
> new_nodes = transformation([node])
> cache.put(hash, new_nodes)
> 
> # Retrieve cached data
> cache_hit = cache.get(hash)
> if cache_hit is not None:
>     # Use the cached data
>     pass
> 
> # Clear the cache (optional)
> cache.clear()
> ```
> 
> In this example, `DummyTransform` is a simple transformation that appends "\nTESTTEST" to the content of each node. The `get_transformation_hash` function is used to generate a unique hash for your query or transformation. This hash serves as a key for caching. The `put` method of the `IngestionCache` instance is used to store the result using the previously generated hash. To retrieve cached data for a similar query in the future, generate the hash again using the same input and transformation, and use the `get` method of the `IngestionCache` instance with this hash. If the data is in the cache, it will be returned; otherwise, `None` is returned.
> 
> You can find more details about the `IngestionCache` class and its usage in the [test_cache.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/tests/ingestion/test_cache.py) file in the LlamaIndex repository.
> 
> Regarding the maximum size of the cache in the `IngestionCache` class and how it can be configured, I wasn't able to find this information in the repository. It's possible that this information is available elsewhere, or I may have missed it. If you need more specific information about this, please provide more details about your use case.
> 
> I hope this helps! If you have any more questions, feel free to ask.
> 
> For more information, you can refer to these similar issues in the LlamaIndex repository:
> 
>     * [[Question]: Use LLM caching with llama index.](https://github.com/run-llama/llama_index/issues/10645)
> 
>     * [[Question]: LLM Caching](https://github.com/run-llama/llama_index/issues/12082)
> 
> 
> [Source Code](https://github.com/run-llama/llama_index/blob/main/llama-index-core/tests/ingestion/test_cache.py)
> ## Sources
> 
>     * [[Question]: Use LLM caching with llama index.](https://github.com/run-llama/llama_index/issues/10645)
> 
>     * [[Question]: LLM Caching](https://github.com/run-llama/llama_index/issues/12082)
> 
>     * [llama-index-core/tests/ingestion/test_cache.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/tests/ingestion/test_cache.py)
> 
> 
> #### About Dosu

@dosubot How to use it with NLSQLTableQueryEngine while querying?

**Comment by AniketNG** [comment]
> e caching to improve query performance by avoiding redundant computations and database queries.

If I re-run a query after it's been executed but the data has changed since the last time I ran it, will I get the old data or will it fetch the new data from the database? As I always want the current state of data.

**Comment by AniketNG** [comment]
> To integrate caching with `NLSQLTableQueryEngine` using `IngestionCache`, follow these steps:
> 
>     1. **Extend `NLSQLTableQueryEngine` with Caching**:
>        
>        * Add an `IngestionCache` instance within your `NLSQLTableQueryEngine`. This can be a simple cache or any custom implementation that fits your needs.
>        * Before executing a query, check if the result is already in the cache using the `get` method.
>        * If a result is found, return it directly. Otherwise, proceed with the query, and cache the result using the `put` method.
> 
>     2. **Cache Key Generation**:
>        
>        * Implement a method to generate a unique cache key for each query. This could be as simple as hashing the query string.
> 
>     3. **Cache Configuration and Management**:
>        
>        * Configure the maximum size and persistence of the cache based on your chosen backend. For a simple in-memory cache, you might extend it to manage size limits or implement persistence to disk.
> 
> 
> Here's a simplified example:
> 
> ```python
> from your_project.query_engine import NLSQLTableQueryEngine
> from llama_index.core.ingestion.cache import IngestionCache, SimpleCache
> 
> class EnhancedNLSQLTableQueryEngine(NLSQLTableQueryEngine):
>     def __init__(self, *args, **kwargs):
>         super().__init__(*args, **kwargs)
>         self.cache = IngestionCache(cache=SimpleCache())
> 
>     def query(self, query_string):
>         cache_key = self.generate_cache_key(query_string)
>         cached_result = self.cache.get(cache_key)
>         if cached_result:
>             return cached_result
> 
>         result = super().query(query_string)
>         self.cache.put(cache_key, result)
>         return result
> 
>     def generate_cache_key(self, query_string):
>         return hash(query_string)
> ```
> 
> This approach allows you to leverage caching to improve query performance by avoiding redundant computations and database queries. Remember to manage the cache lifecycle, including clearing and persisting the cache as needed, to ensure it remains effective and efficient.
> ## Sources
> 
>     * [llama-index-legacy/llama_index/legacy/indices/struct_store/sql_query.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/indices/struct_store/sql_query.py)
> 
>     * [llama-index-legacy/llama_index/legacy/ingestion/cache.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/ingestion/cache.py)
> 
>     * [llama-index-core/llama_index/core/ingestion/cache.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/ingestion/cache.py)
> 
> 
> #### About Dosu

@dosubot If I re-run a query after it's been executed but the data has changed since the last time I ran it, will I get the old data or will it fetch the new data from the database? As I always want the current state of data.

**Comment by bdegoy** [comment]
@dosu I understand that using a hash means that we consider exact same query and not similar query ?
