### ISSUE TITLE
[Bug]:  AttributeError: 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by chxlqqx** [run-llama/llama_index#12431]
### Bug Description

./llama_index/legacy/readers/file/docs_reader.py 
metadata = {"file_name": file.name}   
AttributeError: 'str' object has no attribute 'name'

### Version

lastest

### Steps to Reproduce

The file is a string file path, not a file object. When the file is passed to the DocxReader and file.name is called, it throws an error.

**Comment by logan-markewich** [comment]
Did you pass in a path object to the reader?

```
from pathlib import Path

docx_reader.load_data(Path(filepath))
```
