### ISSUE TITLE
[Question]: Response is cut off when using query engine

### ISSUE THREAD

**Issue by GEN200J** [run-llama/llama_index#12441]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using this code to get an answer from the RAG system: response = query_engine.query(query_str)
However, when I use this to print my answer (which is long, about 800 tokens): 

print(str(response))

The response cuts on the middle of a sentence, anyone knows how to solve this? I thought it was a jupyter notebook problem with the size of the response but I tried saving the response to afile using this:

with open("output.txt", "w") as file:
    file.write(str(response))

but got the same problem.

**Comment by logan-markewich** [comment]
@GEN200J increase `max_tokens` on your LLM (not sure what you LLM setup looks like)

**Comment by GEN200J** [comment]
> @GEN200J increase `max_tokens` on your LLM (not sure what you LLM setup looks like)

Thanks I was able to do it.
