### ISSUE TITLE
[Bug]: '_Settings' object has no attribute 'get_nodes_from_documents' error in examples

### ISSUE THREAD

**Issue by hapasa** [run-llama/llama_index#12445]
### Bug Description

https://docs.llamaindex.ai/en/stable/examples/query_engine/CustomRetrievers

code has section:

from llama_index.core import Settings

nodes = Settings.get_nodes_from_documents(documents)

which is failing because the _Settings object has no attribute get_nodes_from_documents.

### Version

0.10.15

### Steps to Reproduce

Try the example

### Relevant Logs/Tracbacks

```shell
documents = get_documents()
nodes = Settings.get_nodes_from_documents(documents)
```

**Comment by hapasa** [comment]
Traceback (most recent call last):
...
   nodes = Settings.get_nodes_from_documents(documents)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: '_Settings' object has no attribute 'get_nodes_from_documents'

**Comment by hapasa** [comment]
get_documents is just a wrapper:

def get_documents():
    return SimpleDirectoryReader(DATA_DIR).load_data()

**Comment by logan-markewich** [comment]
@hapasa this is a typo in the docs

Should be
`nodes = Settings.node_parser.get_nodes_from_documents(documents)`
