### ISSUE TITLE
[Bug] Raptor retriever with azure open ai in llama pack throws error

### ISSUE THREAD

**Issue by sarathsurpur** [run-llama/llama_index#12459]
### Bug Description

I was following raptor notebook, but when I am using raptor retriever with azure open ai I am getting below error 
AttributeError: 'AzureOpenAI' object has no attribute 'metadata'

llama index Version: 0.10.20

Name: llama-index-packs-raptor
Version: 0.1.3

### Version

0.10.20

### Steps to Reproduce

llama index Version: 0.10.20

Name: llama-index-packs-raptor
Version: 0.1.3

install these versions and try the example notebook https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb

**Comment by logan-markewich** [comment]
@sarathsurpur Sounds like you might be using a langchain LLM class? If so, you need to wrap it with `LangChainLLM(my_llm)` -- or, just use the azure class in llama-index

**Comment by sarathsurpur** [comment]
Instead of using native openai package, class defined within llama index helped to resolve the issue, thanks @logan-markewich
