### ISSUE TITLE
[Question]: If we se node parser to split the document into chunks, then do we need service context in the vectorindex?

### ISSUE THREAD

**Issue by GildeshAbhay** [run-llama/llama_index#12464]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

There are two methods of VectorIndexing, first on nodes and second on documents.

index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)
index = VectorStoreIndex.from_documents([document], service_context=sentence_context)

where nodes are defined below
nodes = node_parser.get_nodes_from_documents([document])
and document like this
content = document["content"]
doc = Document(text=content) #type(retrieved_nodes[0]) type(retriever.retrieve(rag_prompt)) type(nodes[0])

and service context like this
service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model,node_parser=node_parser)

Now, the question is, that since Servicecontext already has a node parser,it would be wrong to pass nodes to a vector index that is using a service context?

**Comment by logan-markewich** [comment]
I think it's fine either way. from_documents will use the node parser, the other will not.

However, both will use the node parser for index.insert
