### ISSUE TITLE
[Question]: OpenAILike when querying with ReActAgent gives ValueError: Could not parse output:  Thought: The current language of the user is: en. I need

### ISSUE THREAD

**Issue by jerinjoseph1** [run-llama/llama_index#12460]
### Bug Description

I assigned an open ai compatible server using OpenAILike using:
`from llama_index.llms.openai_like import OpenAILike
llm = OpenAILike(model="TheBloke/Mistral-7B-Instruct-v0.1-AWQ", api_base="https://myserver.net/v1", api_key="fake")`

This successfully gives outputs when questions are asked using chat method. For e.g:
`response = llm.complete("Who is the ceo of google")
print(str(response))`
 Successfully gives the result: ? Sundar Pichai is the CEO of Google.
 
 But when an agent is created as mentioned in the llamaindex docs (https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents-v1/?h=fnretrieveropenaiagent) and we query something error is popped up 
`ValueError: Could not parse output: 
Thought: The current language of the user is: en. I need`

The sample query i gave for my custom docs is:
`top_agent = ReActAgent.from_tools(
    tool_retriever = obj_index.as_retriever(similarity_top_k=3),
    system_prompt=""" \
You are an agent designed to answer informations about Reflexa.
Please always use the tools provided to answer a question. Do not rely on prior knowledge.\

""",
    llm=llm,
    verbose=True,
)
response = top_agent.query("Who created the company document for Reflexa?")
`
<img width="1150" alt="Screenshot 2024-04-01 at 4 07 05 PM" src="https://github.com/run-llama/llama_index/assets/42619953/99c2ef0a-6822-4f92-afb3-45914653b032">

### Version

v0.10.20

### Steps to Reproduce

I followed this tutorial https://github.com/sugarforever/Advanced-RAG/blob/main/03_llama_index_multi_doc_agent.ipynb but replaced llm with openAILike module from llama-index

**Comment by logan-markewich** [comment]
@jerinjoseph1 you have the LLM configured to only output a small number of tokens (it looks like it got cut off tbh)?

Either that, or the LLM just didn't follow instructions for the output format, and the react loop couldn't be parsed

**Comment by jerinjoseph1** [comment]
Yes, you'r right. It was a mistake from my part, I missed the number of tokens part. Passing `context_window` argument to OpenAILike resolved the issue.
