### ISSUE TITLE
[Question]: ssl certificate verification for Elasticsearch vector store

### ISSUE THREAD

**Issue by haolxx** [run-llama/llama_index#12468]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi LlamaIndex team,

When I use Elasticsearch for semantic search, when creating the client, can I pass in a SSL certificate for verification? My ES url must be https instead of http for security concern.

Thanks!
Hao

**Comment by maxjakob** [comment]
@haolxx You can make your own `AsyncElasticsearch` object with TLS certificate and give this as an `es_client` argument to `ElasticsearchStore`.

**Comment by allanwakes** [comment]
> @haolxx You can make your own `AsyncElasticsearch` object with TLS certificate and give this as an `es_client` argument to `ElasticsearchStore`.

Thanks for your reply.
I tried AsyncElasticsearch, but it didn't work, the error is below:
```
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x713d2c17bf50>
Unclosed connector
connections: ['deque([(<aiohttp.client_proto.ResponseHandler object at 0x713d48703930>, 780618.084782238)])']
connector: <aiohttp.connector.TCPConnector object at 0x713d2c2785d0>
```


My env:
ES: 8.15.3
```
python = ">=3.11,<3.12"
llama-index-core = "^0.12.0"
llama-index-embeddings-huggingface = "^0.4.0"
llama-index-llms-ollama = "^0.4.0"
llama-index-readers-file = "^0.4.0"
llama-index-vector-stores-elasticsearch = "^0.4.0"
elasticsearch = {extras = ["async"], version = "^8.16.0"}
```

Thank you.
