### ISSUE TITLE
Similarity score in nodes: how is it calculated

### ISSUE THREAD

**Issue by xyzgorba** [run-llama/llama_index#12461]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, 
I can't understand why similarity score for top nodes returned after 

`query_engine.query(qry_string) 
`

is different comparing to direct calculation for some specific node using i.e.: 

```
embedding = Settings.embed_model.get_text_embedding(node.text) 
query_embedding = Settings.embed_model.get_query_embedding(qry_string) 
Settings.embed_model.similarity(embedding, query_embedding)
```

What is the possible reason? Could it be impact from node's metadata? 
Cannot find answer in documentation

**Comment by logan-markewich** [comment]
@xyzgorba what vector db are you using? The default? Something else? Many vector dbs will use approximate methods to speed up similarity search, rather than computing raw cosine similarity

**Comment by logan-markewich** [comment]
@xyzgorba Also, embeddings are calculated with a different text attribute

`embedding = Settings.embed_model.get_text_embedding(node.get_content(metadata_mode="embed"))`

**Comment by xyzgorba** [comment]
@logan-markewich - thank you for answer. Yes, it was a default vector db. Thank you for pointing to a fact that embeddings are calculated with a different text attribute. In my case the problem is not that scores are different, but that much less relevant nodes were retrieved as a result, comparing to cosine similarity

**Comment by JMTCoder** [comment]
heyo,
I was facing a similar issue. I am performing a rag operation using the default vector store stored locally and i am getting less relevant nodes retrieved as a result. For instance, In some cases when the query is out of context, the rag operation always retrieves chunks from the vector store (although the query is not semantically similar)

**llama version: 0.9.40**

Hence i had the following questions in mind:
 - what is the distance metric used to measure the similarity between the chunks and the query with the default vector store? 
 - can we change it ?
 - why does it also provide "high" similarity scores (around 0.7) for non relevant queries, even when trying nonsensical queries like "aaaaaa a a a"? --> cause this complicates the use of the threshold_cutoff attribute with the optimizer.

cheers & thanks in advance
