### ISSUE TITLE
[Bug]: Raptor Retriever with Qdrant vector store throws error

### ISSUE THREAD

**Issue by sarathsurpur** [run-llama/llama_index#12474]
### Bug Description

I am using RAPTOR Retriever package with qdrant vector db, I successfully ingested the document in to vector db but when retrieving it using retriever from qdrant vector db throws error

nodes = raptor_pack.run("What baselines is raptor compared against?", mode="collapsed")

AttributeError: 'NoneType' object has no attribute 'search'

### Version

0.10.20

### Steps to Reproduce

follow the steps defined in the notebook and use the vector store as 

vector_store = QdrantVectorStore(client=qc_client, collection_name=COLLECTION)

Reference notebook -> https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-raptor/examples/raptor.ipynb

**Comment by logan-markewich** [comment]
Pass I'm the async client as well as the sync client (keep in index these don't share data when in :memory: mode)

`QdrantVectorStore(..., client=QdrantClient(..), aclient=AsyncQdrantClient(...))`

**Comment by sarathsurpur** [comment]
thanks @logan-markewich passing async qdrant client helped to resolve the error
