### ISSUE TITLE
[Bug]: ValueError: Tool with name python not found

### ISSUE THREAD

**Issue by andrewd6789** [run-llama/llama_index#12479]
### Bug Description

Trying to rebuild the Multi-Documents Agent Example: https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents/

Using the code as-is (and only changing the doc names to match my data), running the agent at the end will end up in this error "**ValueError**: Tool with name python not found":

![image](https://github.com/run-llama/llama_index/assets/165754217/2112a488-336d-402e-9794-6048432a793b)

Thanks in advance!

### Version

0.10.25

### Steps to Reproduce

Follow the code step-by-step and execute it at the end:
https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents/

**Comment by logan-markewich** [comment]
Seems like the LLM hallucinated a tool name. Not sure what your prompt was, the LLM, or tools/descriptions, but the notebook runs fine as is for me
