### ISSUE TITLE
[Question]: Is there a difference between "RetrieverQueryEngine.from_args" and "RetrieverQueryEngine" when used for creating query engines in llamaindex?

### ISSUE THREAD

**Issue by GildeshAbhay** [run-llama/llama_index#12477]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

auto_merging_engine = RetrieverQueryEngine.from_args(automerging_retriever, node_postprocessors=node_postprocessors)
        query_engine = RetrieverQueryEngine(retriever=retriever,response_synthesizer=response_synthesizer,node_postprocessors = node_postprocessors)

I have these two codes, what is the practical difference between the two in terms of output and functionality?

**Comment by GildeshAbhay** [comment]
but is there a difference in the output of the query engine? or is it purely ornamental, in the sense of "ease of use"?

**Comment by logan-markewich** [comment]
There is no difference, `from_args` just defines more defaults (or at least, it used to) than compared to the base constructor
