### ISSUE TITLE
[Bug]: Error loading Composable Graph from persist directory

### ISSUE THREAD

**Issue by andrewd6789** [run-llama/llama_index#12478]
### Bug Description

Hi LlamaIndex Team,

Getting this weird 'KeyError: default' error when I'm trying to load Composable Graph from the persist dir.  The root_id is correctly set. I'm working within Databricks environment, if that'll help.

![image](https://github.com/run-llama/llama_index/assets/165754217/800c5146-883c-43ce-a63e-6a2dd411f74d)

Thanks in advance!

### Version

0.10.25

### Steps to Reproduce

1. Create a composable graph
2. Save the graph in persist directory
3. Load the graph, and you'll get the error

**Comment by dungnq271** [comment]
I encountered a similar error here.
