### ISSUE TITLE
[Bug]: error when try to use YoutubeTranscriptReader

### ISSUE THREAD

**Issue by Sandy4321** [run-llama/llama_index#12472]
### Bug Description

error when try to use YoutubeTranscriptReader
when use as recommended in base.py
from llama_index.readers.youtube_transcript import YoutubeTranscriptReader

i use
llama-hub                                0.0.79.post1
llama-index                              0.10.26
llama-index-agent-openai                 0.2.1
llama-index-cli                          0.1.11
llama-index-core                         0.10.26
llama-index-embeddings-openai            0.1.7
llama-index-graph-stores-neo4j           0.1.4
llama-index-indices-managed-llama-cloud  0.1.5
llama-index-legacy                       0.9.48
llama-index-llms-openai                  0.1.14
llama-index-multi-modal-llms-openai      0.1.4
llama-index-program-openai               0.1.5
llama-index-question-gen-openai          0.1.3
llama-index-readers-file                 0.1.13
llama-index-readers-llama-parse          0.1.4
llama-index-vector-stores-chroma         0.1.6

### Version

llama-hub                                0.0.79.post1 llama-index                              0.10.26 llama-index-agent-openai                 0.2.1 llama-index-cli                          0.1.11 llama-index-core                         0.10.26 llama-index-embeddings-openai            0.1.7 llama-index-graph-stores-neo4j           0.1.4 llama-index-indices-managed-llama-cloud  0.1.5 llama-index-legacy                       0.9.48 llama-index-llms-openai                  0.1.14 llama-index-multi-modal-llms-openai      0.1.4 llama-index-program-openai               0.1.5 llama-index-question-gen-openai          0.1.3 llama-index-readers-file                 0.1.13 llama-index-readers-llama-parse          0.1.4 llama-index-vector-stores-chroma         0.1.6

### Steps to Reproduce

new style recommended 
from llama_index.readers.youtube_transcript import YoutubeTranscriptReader
Traceback (most recent call last):
  Debug Console, prompt 24, line 18
builtins.ModuleNotFoundError: No module named 'llama_index.readers.youtube_transcript'

During handling of the above exception, another exception was raised:

Traceback (most recent call last):
  Debug Console, prompt 24, line 1
    #S_lamaindex_neo4j_apr1
builtins.ModuleNotFoundError: No module named 'llama_index.readers.youtube_transcript'

legacy seems to be no error
from llama_index.legacy.readers.youtube_transcript import YoutubeTranscriptReader
[nltk_data] Downloading package stopwords to C:\my_py_environments\py3
[nltk_data]     10_env_llamaindex_apr2024\lib\site-
[nltk_data]     packages\llama_index\legacy\_static/nltk_cache...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package punkt to C:\my_py_environments\py310_e
[nltk_data]     nv_llamaindex_apr2024\lib\site-
[nltk_data]     packages\llama_index\legacy\_static/nltk_cache...
[nltk_data]   Unzipping tokenizers\punkt.zip.

old style
from llama_hub.youtube_transcript import YoutubeTranscriptReader
Traceback (most recent call last):
  Debug Console, prompt 25, line 18
builtins.ModuleNotFoundError: No module named 'llama_index.readers.youtube_transcript'

During handling of the above exception, another exception was raised:

Traceback (most recent call last):
  Debug Console, prompt 25, line 1
    #S_lamaindex_neo4j_apr1
  File "c:\my_py_environments\py310_env_llamaindex_apr2024\lib\site-packages\llama_hub\youtube_transcript\__init__.py", line 1, in <module>
    from llama_hub.youtube_transcript.base import (
  File "c:\my_py_environments\py310_env_llamaindex_apr2024\lib\site-packages\llama_hub\youtube_transcript\base.py", line 5, in <module>
    from llama_index.readers.base import BaseReader
builtins.ModuleNotFoundError: No module named 'llama_index.readers.base'

**Comment by logan-markewich** [comment]
llama-hub (the package) is not supported with v0.10.x

Looks like you don't have the transcript reader installed

`pip install llama-index-readers-youtube-transcript`
