### ISSUE TITLE
[Bug]: ValueError: Tool with name functions not found

### ISSUE THREAD

**Issue by andrewd6789** [run-llama/llama_index#12483]
### Bug Description

Was trying to use the ToolRetrieverRouterQueryEngine function to retrieve Object Index when this error popped out:

![image](https://github.com/run-llama/llama_index/assets/165754217/4dbe3329-277f-438e-b383-b7375c77932d)

Thanks in advance.

### Version

0.10.25

### Steps to Reproduce

Trying to replicate this workflow:
https://docs.llamaindex.ai/en/stable/examples/query_engine/RetrieverRouterQueryEngine/

Code is kept intact as-is; the only changes are the doc naming to match my data source.

**Comment by logan-markewich** [comment]
Seems like the LLM hallucinated a tool name? It works fine for me in google colab though

<img width="761" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/f231823d-0b24-4760-a25f-47b071a40c2a">

I suggest double checking your tool names and descriptions to see if they make sense. Something about that + the query you made seems to have made the LLM hallucinate a tool name

**Comment by andrewd6789** [comment]
Hi, after pip llama-index to 10.26, somehow this error disappeared. 

On another note, is it possible for an LLM to hallucinate a tool name and break the execution flow?  That sounds like borderline Skynet territory :)

Apology in advance for the noob-ish question, but I'm quite new in this LLM space and still learning new things daily.

**Comment by logan-markewich** [comment]
It definitely is possible for the llm to hallucinate a tool name. It's good practice to give tools simple,  meaningful and distinct names to help avoid this

**Comment by andrewd6789** [comment]
I see.  In the example code, I can see there are two places where the agent prompts are defined by default:

![image](https://github.com/run-llama/llama_index/assets/165754217/f61e8db7-c50f-4368-8f7f-d37cb73588f8)

and 

![image](https://github.com/run-llama/llama_index/assets/165754217/b2e298c0-4ec8-4ac6-a5fb-b93b09a8cca3)

Trying to understand the behavior, so could you please elaborate which one of those prompts is potentially causing the hallucination?

**Comment by logan-markewich** [comment]
Both of those are setting the same -- a system prompt.

Optimizing that, plus with proper tool names / descriptions, is the way to go 

The agent has to decide whether to use a tool or not to respond to the user
