### ISSUE TITLE
Reason of using _to_llama_similarities() normalization technique and not using raw similarity scores for Retrieval through Elastic Search Vector Store

### ISSUE THREAD

**Issue by Subham0793** [run-llama/llama_index#12486]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Because of _to_llama_similarities function, the scores are normalized and maximum score is always at 1.0

What is the reason of this normalization technique, and why has this being called by default? 

The problem may arise when some query which is not related to a particular document, is used for retrieving the chunks, and still the results will contain scores starting from 1.0 , even when there is no relation of the chunk with respect to the query.

Code snippet: 

`return VectorStoreQueryResult(
            nodes=top_k_nodes,
            ids=top_k_ids,
            similarities=_to_llama_similarities(top_k_scores),
  )`

Line no. 623 in 

> https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py

**Comment by Subham0793** [comment]
but what if in case scores before normalization are very low (0.3-0.4), this function still changes the range to keep the max score at 1.0 which should not be right. Retrieved docs with low scores can be of very low quality, and after normalization we are giving it a high score.

**Comment by logan-markewich** [comment]
I think this was added at one point because elastic returned scores that are not ranged 0 to 1

Feel free to make a PR to change this

**Comment by Subham0793** [comment]
but isn't this a bug? Why was this specifically made to keep the max value at 1.0.

say we are getting top 5 docs from a query. And the doc at k=1 need not be of score 1.0, it can be of score 0.85

The problem with this is we are giving high scores for those documents which are not that similar to the query
