### ISSUE TITLE
[Question]: Similarity score for pinecone vector store.

### ISSUE THREAD

**Issue by rudrakhsha-c** [run-llama/llama_index#12487]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone. I am building an IT chatbot using llama index and pinecone as the vector database along with OpenAI 3.5-turbo as the llm and text-ada-002 as the embedding model. For pinecone similarity search, I am using cosine similarity function. 
I want to record the similarity score which is given during retrieval of nodes when using a context chat engine in the response
```
response = chat_engine.chat("Steps to reset ad password?")
response.source_nodes 
``` 
will give the nodes along with the similarity score for each node.
When verifying these scores, when the query has some relevant information in the documents then the nodes retrieved will have a score of 0.8, 0.81 and such. 
But when having some normal chat with the bot and asking it some general knowledge based questions like ```Give me the revipe to make pasta``` it still retrieves some nodes along with scores like 0.71, 0.72 even though there is nothing similar among the question asked and the nodes retrieved from documents indexed.

I want the score to work properly as my application has to make some logical decisions based on the threshold of this score. Is there something that I am doing wrong with pinecone. Can someone help me with this issue?
Thanks.

**Comment by logan-markewich** [comment]
@rudrakhsha-c this is correct, and in general, matches my experience with openai embeddings. 0.7-ish is a neutral score in my experience for ada-002. Anything above 0.78 is probably relevant
