### ISSUE TITLE
[Bug]: Failed to find python package for class QueryUnderstandingAgent

### ISSUE THREAD

**Issue by dungnq271** [run-llama/llama_index#12482]
### Bug Description

I run this [notebook](https://github.com/run-llama/llama_index/blob/main/llama-index-packs/llama-index-packs-query-understanding-agent/examples/query_understanding_agent.ipynb) in Google Colab but there was an error when downloading the QueryUnderstandingAgentPack

When I ran this cell `from llama_index.packs.query_understanding_agent.step import (
    QueryUnderstandingAgentWorker,
    HumanInputRequiredException,
)` the error is `ModuleNotFoundError: No module named 'llama_index.packs'`

So I had to download the pack like in this [link](https://llamahub.ai/l/llama-packs/llama-index-packs-query-understanding-agent?from=llama-packs) and the final result was an error: `ValueError: Failed to find python package for class QueryUnderstandingAgent`
Thanks a lot for helping me!

### Version

0.10.26

### Steps to Reproduce

I ran this code to download the pack:
```
from llama_index.core.llama_pack import download_llama_pack

# download and install dependencies
QueryUnderstandingAgentPack = download_llama_pack(
    "QueryUnderstandingAgent", "./query_understanding_agent"
)
```

**Comment by logan-markewich** [comment]
@dungnq271 `pip install llama_index-packs-query-understanding-agent`

**Comment by dungnq271** [comment]
Thank you a lot. It works!
