### ISSUE TITLE
[Bug]: Setting global tokenizer doesn't work when `num_workers` > 1

### ISSUE THREAD

**Issue by ckrapu-nv** [run-llama/llama_index#12498]
### Bug Description

Using `set_global_tokenizer` and/or passing a suitable function for `tokenizer` as a kwarg to `SentenceSplitter` correctly sets the tokenizer when `num_workers=1`, but fails for >1. 

### Version

`llama-index-core==0.10.19`

### Steps to Reproduce

1. Create some documents
2. Use `SentenceSplitter` with a tokenizer besides the default one based on cl100k
3. insert a logging or print statement in the SentenceSplitter implementation after this line `self._tokenizer = tokenizer or get_tokenizer()`
4. Observe that the non-default tokenizer is not used.

**Comment by logan-markewich** [comment]
@ckrapu-nv your description doesn't really mention how to reproduce this. You mention num_workers, but your steps make no mention of this.

Providing some code sample would be ideal

**Comment by logan-markewich** [comment]
hmmm, in any case, I think this is related to how the tokenizer isn't pickleable, so when multiprocessing happens, the tokenizer is erased.

**Comment by logan-markewich** [comment]
I don't see this being fixed easily, but open to ideas or PRs

**Comment by ckrapu-nv** [comment]
It's a little hard to easily show this result without directly editing the local version, but this is sufficiently to cause the issue, even if it doesn't readily make it apparent.

```
from llama_index.core import Document
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.ingestion import IngestionPipeline
from transformers import AutoTokenizer

tokenizer=AutoTokenizer.from_pretrained('intfloat/e5-large-v2')
documents = [Document(t='')]
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(tokenizer=tokenizer.encode
        ),
    ]
)
nodes = pipeline.run(documents=documents, num_workers=8)
```
