### ISSUE TITLE
[Question]: delete VLLM models

### ISSUE THREAD

**Issue by osafaimal** [run-llama/llama_index#12492]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I didn't find how i can delete the model. 
with the default Vllm:
```python
import gc
import torch
from vllm import LLM

# Load the model via vLLM
llm = LLM(model=model, download_dir="./models",max_model_len=27952)
!nvidia-smi

# Delete the llm object and free the memory
del llm.llm_engine.driver_worker
del llm
gc.collect()
torch.cuda.empty_cache()
!nvidia-smi
```
it works
but when i try:
```python
from vllm.model_executor.parallel_utils.parallel_state import destroy_model_parallel
import gc
import torch

# Delete the llm object and free the memory
del llm.llm_engine.driver_worker
del llm
gc.collect()
torch.cuda.empty_cache()
!nvidia-smi
```
with the one of llamaindex, there is no llm_engine member and if i remove this line the memory is still used by python. So how should we unload the model from the memory with llamaindex?

**Comment by osafaimal** [comment]
no it doesn't work

**Comment by logan-markewich** [comment]
The code does this in the constructor

```
self._client = VLLModel(
    model=model,
    tensor_parallel_size=tensor_parallel_size,
    trust_remote_code=trust_remote_code,
    dtype=dtype,
    download_dir=download_dir,
    **vllm_kwargs
)
```

So, probably some operation on the client is needed. Kind of surprised just 

```
del llamaindex_llm
gc.collect()
torch.cuda.empty_cache()
```

Doesn't work. GPU memory is hard to manage in my experience
