### ISSUE TITLE
[Bug]: How to fix this error No module named 'llama_index.llms.llama_cpp'

### ISSUE THREAD

**Issue by deecancode** [run-llama/llama_index#12502]
### Bug Description

Hi all,

I am trying to use mixtral-8x7b with my own data with no luck.

### Version

0.10.25

### Steps to Reproduce

```
import torch
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.llms.llama_cpp.llama_utils import messages_to_prompt, completion_to_prompt
llm = LlamaCPP(
    model_url=None, # We'll load locally.
    model_path='./Models/mixtral-8x7b-instruct-v0.1.Q4_K_M.gguf', # 4-bit model
    temperature=0.1,
    max_new_tokens=1024, # Increasing to support longer responses
    context_window=8192, # Mistral7B has an 8K context-window
    generate_kwargs={},
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 40}, # 40 was a good amount of layers for the RTX 3090, you may need to decrease yours if you have less VRAM than 24GB
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True
)
```

### Relevant Logs/Tracbacks

```shell
Which gives error No module named 'llama_index.llms.llama_cpp'.

I have installed llama_index, used my MAC Mini and also Google Colab's GPUs

Any suggestions?
```

**Comment by logan-markewich** [comment]
`pip install llama-index-llms-llama-cpp` -- every integration is a package

Tbh though, I would use Ollama, the setup is 1000x easier (similar install, `pip install llama-index-llms-ollama`)

**Comment by sykuann** [comment]
i have the same issue and tried CMAKE_ARGS="-DLLAMA_METAL=on" FORCE_CMAKE=1 pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir but still it doesn't work.

**Comment by logan-markewich** [comment]
@sykuann that only installs llama cpp itself, you still need to install the integration (which I've linked above)

**Comment by compilebunny** [comment]
> `pip install llama-index-llms-llama-cpp` -- every integration is a package
> 
> Tbh though, I would use Ollama, the setup is 1000x easier (similar install, `pip install llama-index-llms-ollama`)

I suspect that both @deecancode and I are trying replicate the RAG implementation described [here](https://netraneupane.medium.com/retrieval-augmented-generation-rag-using-llamaindex-and-mistral-7b-228f93ba670f). 

I still get the same error after installing the llamaCPP integration. 

"pip show llama-index-llms-llama-cpp" produces

```
Name: llama-index-llms-llama-cpp
Version: 0.1.4
Summary: llama-index llms llama cpp integration
Home-page: 
Author: Your Name
Author-email: you@example.com
License: MIT
Location: /(censored)/site-packages
Editable project location: /(censored)/llama_index/llama-index-integrations/llms/llama-index-llms-llama-cpp
Requires: llama-cpp-python, llama-index-core
Required-by: 

```

but I still get the following when I try to execute code similar to that of the original poster.

```
Traceback (most recent call last):
  File "(directory strucure censored)/ragtest.py", line 3, in <module>
    from llama_index.llms import LlamaCPP
ImportError: cannot import name 'LlamaCPP' from 'llama_index.llms' (unknown location)

```
