### ISSUE TITLE
[Question]: Does docstore support filter?

### ISSUE THREAD

**Issue by mistoFENG** [run-llama/llama_index#12516]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Does docstore support filter, like vector database? like:
```
jerry_query_engine = index.as_query_engine(
    filters=MetadataFilters(
        filters=[
            ExactMatchFilter(
                key="user",
                value="Jerry",
            )
        ]
    ),
    similarity_top_k=3,
)
```

**Comment by mistoFENG** [comment]
> Hey @mistoFENG, great to see you diving into another interesting feature! 😎
> 
> Yes, the LlamaIndex's docstore feature does support filtering similar to a vector database. The SimpleVectorStore index in LlamaIndex allows for filtering on both metadata and doc_id while querying. This feature enables the creation of a combined index that can answer from all files or a single file as per the user's requirement.
> 
> Here is an example of how you can use this feature:
> 
> ```python
> from llama_index import Document
> from llama_index.vector_stores.types import ExactMatchFilter, MetadataFilters
> 
> # Insert a document with specific metadata
> doc = Document(text="target", metadata={"tag": "target"})
> index.insert(doc)
> 
> # Create a filter that matches the inserted metadata
> filters = MetadataFilters(
>     filters=[ExactMatchFilter(key="tag", value="target")]
> )
> 
> # Use the filter in the retriever to retrieve only the documents that match the filter
> retriever = index.as_retriever(
>     similarity_top_k=20,
>     filters=filters,
> )
> 
> source_nodes = retriever.retrieve("What did the author do growing up?")
> ```
> 
> This code will retrieve only the documents that have a metadata tag "tag" with the value "target".
> 
> Please note that the default vector store built into llama-index doesn't support metadata filters. You would have to use something with llama index that supports it to make your life easier (qdrant, chroma, pinecone, weaviate).
> 
> For multiple values for a metadata key on the filter, it seems like there is a limitation on the vector store. You might need to find a workaround or use a different vector store that supports this feature.
> 
> You can find more information about this in the following issues and pull requests:
> 
> * [[Question]: Metafilter ](https://github.com/run-llama/llama_index/issues/6846)
> * [[Feature Request]: Filter on metadata for SimpleVectorstoreindex](https://github.com/run-llama/llama_index/issues/6948)
> * [I have converted the document type into a json vector file, if I want to query some questions in multiple json vector files, what should I do?](https://github.com/run-llama/llama_index/issues/1167)
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Sources:
> 
> * [[Question]: Metafilter ](https://github.com/run-llama/llama_index/issues/6846)
> * [[Feature Request]: Filter on metadata for SimpleVectorstoreindex](https://github.com/run-llama/llama_index/issues/6948)
> * [I have converted the document type into a json vector file, if I want to query some questions in multiple json vector files, what should I do?](https://github.com/run-llama/llama_index/issues/1167)
> * [docs/examples/vector_stores/SimpleIndexDemo.ipynb](https://github.com/run-llama/llama_index/blob/main/docs/examples/vector_stores/SimpleIndexDemo.ipynb)
> * [llama_index/vector_stores/postgres.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/postgres.py)
> * [llama_index/node_parser/extractors/metadata_extractors.py](https://github.com/run-llama/llama_index/blob/main/llama_index/node_parser/extractors/metadata_extractors.py)
> 
> ## Sources
> * [[Question]: Filtering on metadata in SimpleVectorStore index](https://github.com/run-llama/llama_index/discussions/8361)
> * [[Question]: Filtering on metadata in SimpleVectorStore index](https://github.com/run-llama/llama_index/issues/6908)
> * [llama-index-legacy/tests/vector_stores/test_jaguar.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/tests/vector_stores/test_jaguar.py)
> * [llama-index-legacy/llama_index/legacy/vector_stores/simple.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/vector_stores/simple.py)
> 
> #### About Dosu

Taking `SimpleDocumentStore` as an example, how to implement `docstore` with filter？

**Comment by logan-markewich** [comment]
@mistoFENG dosu is hallucinating. There is no filter for dicstore, since it's just a key-val lookup interface.

You can use docstore.docs to get all docs and filter from there, but that's the only way I can think of.
