### ISSUE TITLE
[Feature Request]: elasticsearch retriever wanted

### ISSUE THREAD

**Issue by dl942702882** [run-llama/llama_index#12510]
### Feature Description

i wanna use elasticsearch retriever to do keyword retrieve, what do i need?
any existing Retriever suggested?

### Reason

any existing Retriever suggested?

**Comment by dl942702882** [comment]
use elasticseearch not for vector search, but use its inverting index for keyword retrieve

**Comment by adrian539859** [comment]
How about setting alpha=0.0?

```python
query_engine = index.as_query_engine(
    vector_store_query_mode="hybrid", similarity_top_k=2, alpha=0.0
)
```

**Comment by maxjakob** [comment]
@dl942702882 From version 0.2.0 of `llama-index-vector-stores-elasticsearch` you can do keyword retrieval, see https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/ElasticsearchIndexDemo.ipynb

**Comment by yzgrfsy** [comment]
> @dl942702882 From version 0.2.0 of `llama-index-vector-stores-elasticsearch` you can do keyword retrieval, see https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/ElasticsearchIndexDemo.ipynb从 0.2.0 版开始， `llama-index-vector-stores-elasticsearch` 您可以进行关键字检索，请参阅 https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/ElasticsearchIndexDemo.ipynb

您好，请问这个必须配合 ES数据库的高级版才可以使用是吗，我更新了llama-index-vector-stores-elasticsearch 版本 ，但是在混合检索的时候 一直出错“elasticsearch.AuthorizationException: AuthorizationException(403, 'security_exception', 'current license is non-compliant for [Reciprocal Rank Fusion (RRF)]')”

**Comment by yzgrfsy** [comment]
@maxjakob 您好，请问这个必须要求ES的高级版才可以使用是吗，我更新了llama-index-vector-stores-elasticsearch，在混合搜索的时候 ，一直出错“elasticsearch.AuthorizationException: AuthorizationException(403, 'security_exception', 'current license is non-compliant for [Reciprocal Rank Fusion (RRF)]')”

**Comment by adrian539859** [comment]
> @maxjakob 您好，请问这个必须要求ES的高级版才可以使用是吗，我更新了llama-index-vector-stores-elasticsearch，在混合搜索的时候 ，一直出错“elasticsearch.AuthorizationException: AuthorizationException(403, 'security_exception', 'current license is non-compliant for [Reciprocal Rank Fusion (RRF)]')”

You can also use a 30-day trial version of ES with `xpack.license.self_generated.type=trial`. 
See https://docs.llamaindex.ai/en/stable/examples/vector_stores/ElasticsearchIndexDemo/

**Comment by maxjakob** [comment]
@yzgrfsy Keyword-only retrieval (BM25) is a regular feature of Elasticsearch. Hybrid search (dense vector + BM25 retrieval, combining the results using RRF) is a licensed feature that you can trial with the parameter that @adrian539859 shared or with a [trial in Elastic Cloud](https://www.elastic.co/cloud/cloud-trial-overview).

**Comment by yzgrfsy** [comment]
@dl942702882  thank you for your answer。

**Comment by yzgrfsy** [comment]
@maxjakob  thank you for your answer。我实现创建了index到ES中，现在按照LLamaindex的官网指导 
(https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever/)，创建自定义的检索器(结合矢量检索器和 BM25 检索器),实现  Hybrid Retriever ：

 class HybridRetriever(BaseRetriever):
    def __init__(self, vector_retriever, bm25_retriever):
        self.vector_retriever = vector_retriever
        self.bm25_retriever = bm25_retriever
        super().__init__()

    def _retrieve(self, query, **kwargs):
        bm25_nodes = self.bm25_retriever.retrieve(query, **kwargs)
        vector_nodes = self.vector_retriever.retrieve(query, **kwargs)

        # combine the two lists of nodes
        all_nodes = []
        node_ids = set()
        for n in bm25_nodes + vector_nodes:
            if n.node.node_id not in node_ids:
                all_nodes.append(n)
                node_ids.add(n.node.node_id)
        return all_nodes

但是我遇到一个问题，我需要实例化两个检索器。其中：vector_retriever 是这样实例化：
vector_store = ElasticsearchStore(
        index_name=es_index_name, es_url=CONS_ELASTIC_SEARCH_URL
    )
   
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = VectorStoreIndex.from_vector_store(embed_model=Settings.embed_model, vector_store=vector_store,
                                               storage_context=storage_context)
vector_retriever = index.as_retriever(similarity_top_k=10) 。但是：实例化bm25_retriever
bm25_retriever = BM25Retriever.from_defaults(index=index, similarity_top_k=10)或者
bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=10)均出错，请问您知道如何从已保存index的ES中得到nodes 吗

**Comment by maxjakob** [comment]
@yzgrfsy There is a simpler way to do hybrid retrieval, see the [documentation](https://docs.llamaindex.ai/en/stable/examples/vector_stores/ElasticsearchIndexDemo/#hybrid-retrieval):
```python
from llama_index.vector_stores.elasticsearch import AsyncDenseVectorStrategy

hybrid_store = ElasticsearchStore(
    es_url="http://localhost:9200",
    index_name="xyz",
    retrieval_strategy=AsyncDenseVectorStrategy(hybrid=True),
)

storage_context = StorageContext.from_defaults(vector_store=hybrid_store)
index = VectorStoreIndex(nodes, storage_context=storage_context)
retriever = index.as_retriever()
print(retriever.retrieve(query))
```

This will use dense vector retrieval and BM25 and combine the results using [RRF](https://www.elastic.co/guide/en/elasticsearch/reference/current/rrf.html).
