### ISSUE TITLE
[Question]: Simple directory reader load_data takes long

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12513]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Im using 3 documents total of 10k pages, but the load_data() takes too long for all 3 of them, I tried to also increase num_workers but still its extremely slow. I ran for 50 mins and still it didnt finish, how to resolve this?

**Comment by logan-markewich** [comment]
There's no other way to speed this up -- you can only parallelize per file. If each file is huge, thats just how it is (its loaded into memory and then the content is parsed)

**Comment by JINO-ROHIT** [comment]
@logan-markewich alright , i was able to write a workaround using unstructured + converting to llamaindex Document type -- now takes me around ~ 10 mins

**Comment by logan-markewich** [comment]
You could also use the unstructured loader from llamaindex, and plugged that into simple directory reader for the filetype you wanted

`pip install llama-index-readers-file unstructured`

```
from llama_index.readers.file import UnstructuredReader

file_extractor = {".pdf": UnstructuredReader()}

documents = SimpleDirectoryReader(..., file_extractor=file_extractor).load_data()
```

But glad it works in any case

**Comment by wilfrediscoming** [comment]
> llama-index-readers-file unstructured

is this faster against pdf file?
