### ISSUE TITLE
[Feature Request]: Integrate graph databases as LlamaIndex Graph Stores

### ISSUE THREAD

**Issue by ztor2** [run-llama/llama_index#12517]
### Feature Description

Our company developed and is a main contributor to 'Apache AGE', an open source graph database based on PostgreSQL.
We would like to make our graph database available as a Graph Store in LlamaIndex's RAG framework. 
Apache AGE is available as an extension to PostgreSQL and can be integrated into the Graph RAG framework as a Graph Store, storing and retrieving graph data based on OpenCypher. 

We've already read the provided 'Contribution Guideline', but we didn't find any clear integration guidelines for the Graph Store.
If you can provide more detailed guidelines for the integration, we'd be happy to provide more detailed information and test results in line with those guidelines.

- [https://github.com/apache/age](https://github.com/apache/age)

### Reason

LlamaIndex has a few different kinds of Graph Stores, but most appear to be native (or single-model) graph database products. Also, some Graph Stores are commercial products, which makes them inaccessible to the average user.  

### Value of Feature

Apache AGE is an extension to PostgreSQL, which means that it can be integrated with many other PostgreSQL extensions while still using a traditional RDB. It's also an open source graph database, making it easy to use for the average user.
As the structure of LLM applications grows more complex, modules that are highly interoperable and extensible are becoming more favorable to use. Apache AGE is a product that fits this trend because it is based on PostgreSQL, has excellent integration and scalability, and has a large community.
Apache AGE is also a validated project that has been named a Top-Level Project (TLP) by the Apache Software Foundation.

- [https://news.apache.org/foundation/entry/the-apache-software-foundation-announces83](https://news.apache.org/foundation/entry/the-apache-software-foundation-announces83)

**Comment by ztor2** [comment]
Thank you for your response. However, we have a few more questions about the process. 

1. After we finally implement the class for the graph store, should we commit it to the LlamaIndex repository as a branch? Or do we need to deliver the files via email or something? 
2. How will the validation process of the appropriateness of the submitted graph store be done? 
3. Are there any additional requirements for integration?

Thank you in advance for your future response. 

_p.s. If there is a separate contact for detailed inquiries, I will reach out to you there._

**Comment by liorkesos** [comment]
Any reason or discussion why this is not-planned ?
I saw the bot closed it but I don't understand if this is human led guidance .
I'd like to move from lanchain to llamaindex but using apacge-age and pg_vecor is important for my team
