### ISSUE TITLE
[Bug]: Error when loading PDFs

### ISSUE THREAD

**Issue by enkiid** [run-llama/llama_index#12522]
### Bug Description

In the [latest commit for the PDFReader class](https://github.com/run-llama/llama_index/commit/b730fb67b66870eec7a9bd430750735e4125ec31) there is a switch from ```fp.name``` -> ```file.name```. However ```file``` is a string containing the path, i.e., not a object with ```name``` as an attribute, this results in an error when trying to load pdfs. 

Maybe revert the change?

### Version

0.10.26

### Steps to Reproduce

```python
from llama_index.core.readers.file.base import _try_loading_included_file_formats

FILE_READER_CLS = _try_loading_included_file_formats()

reader_cls = FILE_READER_CLS.get(".pdf")
reader_cls = reader_cls()
docs = reader_cls.load_data(file="path-to-pdf-file")
```

**Comment by logan-markewich** [comment]
@enkiid if you wanted to get specific, the input is typed as a Path object 
https://github.com/run-llama/llama_index/blob/2710433c746acdefba1d3604486ab3766b2f42c0/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/docs/base.py#L32

But sure, it could probably be casted as path under the hood to make it easier for people

**Comment by enkiid** [comment]
Yeah, my bad, I'm tired... Have a good one!
