### ISSUE TITLE
[Bug]: keyerror in msg["additional_kwargs"] when using langfuse and a chat engine

### ISSUE THREAD

**Issue by taimans-git** [run-llama/llama_index#12524]
### Bug Description

When I updated to the current version of llama index, a key error occurs, when I use langfuse as callback manager in a chat engine:

..\llama_index\core\base\llms\types.py", line 66, in dict
    for key, value in msg["additional_kwargs"].items():
KeyError: 'additional_kwargs'

In previous versions, I have not had this issue (e.g. in v0.10.24.). It seems like it is a new method implemented in this version, which assumes that the keyword is always provided.

### Version

v0.10.26

### Steps to Reproduce

1. Set langfuse as callback handler:
```
langfuse_callback_handler = LlamaIndexCallbackHandler(
    public_key="pk-lf...",
    secret_key="sk-lf...",
    host="http://localhost:3000"
)
langfuse_manager = CallbackManager([langfuse_callback_handler])
Settings.callback_manager = langfuse_manager
```
2. Create a chat engine for example from a tree index. Set langfuse as callback manager for the chat engine.

3. The error is raised, when a message is provided via .chat().

### Relevant Logs/Tracbacks

```shell
KeyError: 'additional_kwargs'
ERROR:langfuse:'additional_kwargs'
Traceback (most recent call last):
  File "...\site-packages\langfuse\client.py", line 1336, in generation
    "body": new_body.dict(exclude_none=True),
  File "...\site-packages\langfuse\api\resources\ingestion\types\create_generation_body.py", line 45, in dict
    return super().dict(**kwargs_with_defaults)
  File "...\site-packages\langfuse\api\resources\ingestion\types\create_span_body.py", line 34, in dict
    return super().dict(**kwargs_with_defaults)
  File "...\site-packages\langfuse\api\resources\ingestion\types\create_event_body.py", line 27, in dict
    return super().dict(**kwargs_with_defaults)
  File "...\site-packages\langfuse\api\resources\ingestion\types\optional_observation_body.py", line 47, in dict
    return super().dict(**kwargs_with_defaults)
  File "...\site-packages\pydantic\v1\main.py", line 449, in dict
    return dict(
  File "...\site-packages\pydantic\v1\main.py", line 866, in _iter
    v = self._get_value(
  File "...\site-packages\pydantic\v1\main.py", line 793, in _get_value
    return v.__class__(*seq_args) if is_namedtuple(v.__class__) else v.__class__(seq_args)
  File "...\site-packages\pydantic\v1\main.py", line 778, in <genexpr>
    cls._get_value(
  File "...\site-packages\pydantic\v1\main.py", line 742, in _get_value
    v_dict = v.dict(
  File "...\site-packages\llama_index\core\base\llms\types.py", line 66, in dict
    for key, value in msg["additional_kwargs"].items():
KeyError: 'additional_kwargs'
```

**Comment by logan-markewich** [comment]
Can you give more code? Are you using a certain LLM?

Tbh this feels a tad impossible -- a chat message object always has an additional kwargs property, and calling to_dict() will always have that key

**Comment by taimans-git** [comment]
Sure, thanks for the quick response. I use the chat-bison model from Vertex Ai. 

I have created a small set up:
1. Read in data
```
from llama_index.core import SimpleDirectoryReader
from bs4 import BeautifulSoup

data = ""
docs = SimpleDirectoryReader(data).load_data()
# get soup
for doc in docs:
    soup = BeautifulSoup(docs[0].text, 'html.parser')

    # add text
    doc.text = soup.get_text(strip=True)
```
2. Set up callback handler
```
langfuse_callback_handler = LlamaIndexCallbackHandler(
    public_key="pk-lf-...",
    secret_key="sk-lf-...",
    host="http://localhost:3000"
)
langfuse_manager = CallbackManager([langfuse_callback_handler])
Settings.callback_manager = langfuse_manager
```
3. Create nodes
'''
from llama_index.core.ingestion import IngestionPipeline
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
    ]
)
nodes = pipeline.run(
    documents=docs,
    in_place=True,
)
'''
4. Create vectorstore with chat engine
'''
from llama_index.core import VectorStoreIndex

vs_index = VectorStoreIndex(nodes)
chat_engine = vs_index.as_chat_engine(
    llm=llm_chat,
    verbose=True
)
'''
5. And chat with the model:
'''
response = chat_engine.chat("Hi")
'''

Then the error from above occurs. The model still creates a responds, but an update call from langfuse seems to be the problem.

**Comment by taimans-git** [comment]
yes, seems possible..

> Ah, seems like langfuse maybe overrode the chat message class? Spooky. I can make a fix to make the `dict()` method safer at least 🤷🏻
