### ISSUE TITLE
[Bug]: Unprocessable Entity Error

### ISSUE THREAD

**Issue by philotimo3** [run-llama/llama_index#12554]
### Bug Description

I have been working on a multi-document agent that has been providing pretty great responses to queries about the pdf documents I am processing. However, there has been a very recent  change that is causing me to receive the following error: "Retrying llama_index.llms.openai.base.OpenAI._chat in actual_number seconds as it raised UnprocessableEntityError: Error code: 422 - {'error': 'Template error: syntax error: Conversation roles must alternate user/assistant/user/assistant/... (in <string?:1)', 'error_type': 'template_error'}". Where can I find the documentation for this template change? My current code is very similar to what is found here: https://docs.llamaindex.ai/en/v0.10.17/examples/agent/multi_document_agents.html

### Version

0.10.19

### Steps to Reproduce

Create a multi-document agent following this format: https://docs.llamaindex.ai/en/v0.10.17/examples/agent/multi_document_agents.html

**Comment by logan-markewich** [comment]
@philotimo3 do you have the full traceback? There was no change I was aware of. But I do know some APIs do not like system prompts, or they enforce this alternating pattern

What LLM are you using?

**Comment by philotimo3** [comment]
@logan-markewich you are right this was due to a change in the api I was using for the LLM
