### ISSUE TITLE
[Question]: Can SQLTableRetrieverQueryEngine or NLSQLTableQueryEngine filter specific value ?

### ISSUE THREAD

**Issue by Ninlawat-Puhu** [run-llama/llama_index#12569]
### Question Validation

- [ ] I have searched both the documentation and discord for an answer.

### Question

I use LLM= gpt-3.5-turbo and llama_index to connect database SQL server but I don't see the document to filter value while query in database or pass some values to filter data.

I see llama_index will convert prompt from users to statement SQL but cannot put or pass values before that and the get result from database.

Can you suggest how I can filter data with using NLSQLTableQueryEngine or SQLTableRetrieverQueryEngine ?

Ref: https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo/

**Comment by Ninlawat-Puhu** [comment]
Can you show example that easily I can modify code or modified code in https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo/ 
?

**Comment by logan-markewich** [comment]
You probably want to create a more custom text-2-sql query pipeline
https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline_sql/?h=querypipeline
