### ISSUE TITLE
[Bug]: Explicitly setting llm property to None is overridden in core settings

### ISSUE THREAD

**Issue by davidtheITguy** [run-llama/llama_index#12560]
### Bug Description

I am trying to write my own document ingestion pipeline using the llamaindex core and IngestionPipeline framework. My use case calls for using a local llm only which I am doing via Ollama and the OllamaEmbedding class. It works. However, other transformer classes seem to be always attempting to use OpenAI as a default regardless of what is set in the base class "llm" property.

``` def my_pipeline(self):
        try:          
            transformations = [
                SentenceSplitter(chunk_size=512, chunk_overlap=20),                
                TitleExtractor(llm=None),
                OllamaEmbedding(llm="llama2")
            ]
            pipeline = IngestionPipeline(transformations=transformations)
            return pipeline 
        except Exception as e:
            self.logger.error("Error in my pipeline: %s", str(e))
            raise
```
So in the above definition, setting llm=None has no effect and ultimately gets reset to `default` regardless of setting llm.

I've traced this via through `metadata_extractors.py` and the super class properties of `TitleExtractor` and discovered this code in `settings.py`:
```    # ---- LLM ----

    @property
    def llm(self) -> LLM:
        """Get the LLM."""
        if self._llm is None:
            self._llm = resolve_llm("default")

        if self._callback_manager is not None:
            self._llm.callback_manager = self._callback_manager

        return self._llm
```
So it appears that no matter when None is set, the value always goes back to `default`, which is the Open AI LLM hard coded and which will throw an error since no `OPENAI_API_KEY` has been set.

This doesn't appear to me to be expected nor intended behavior.

### Version

0.10.26

### Steps to Reproduce

Using the above sample ingestion pipeline definition provided, set ` TitleExtractor(llm=None),` in the pipeline, do not set an `OPENAI_API_KEY` either inline or in the environment and call the pipeline,

### Relevant Logs/Tracbacks

```shell
Here is my error trace:

20240403 16:30:26 - Error in pipeline: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
20240403 16:30:26 - Error ingesting document: 
******
```

**Comment by logan-markewich** [comment]
Change the defaults in the global settings, or specifically pass in the LLM and embed model to your modules (anything that uses an LLM or embed model  accepts it in the interface)

**Comment by logan-markewich** [comment]
The title extractor needs an LLM, you can't set it to none

**Comment by logan-markewich** [comment]
For example, you can do

```
from llama_index.llms.Ollama import Ollama

llm = Ollama(model="llama2", request_timeout=3000.0)

# set the default LLM in settings
from llama_index.core import Settings
Settings.llm = llm

# or pass in the LLM to the extractor
TitleExtractor(llm=llm)

```

**Comment by davidtheITguy** [comment]
> The title extractor needs an LLM, you can't set it to none

@logan-markewich thank you for the quick reply. Of course it does lol.... Was unclear to me in the docs, but seeing your comments now makes it obvious. Thanks again

**Comment by logan-markewich** [comment]
Happy to help!
