### ISSUE TITLE
[Question]: What is the difference between vector store and storage context in terms of storing embeddings that are generated while creating a vector index?

### ISSUE THREAD

**Issue by GildeshAbhay** [run-llama/llama_index#12571]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So I have this code here
```
    node_parser = HierarchicalNodeParser.from_defaults(chunk_sizes=chunk_size)
    nodes = node_parser.get_nodes_from_documents([doc])
    service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model,node_parser=node_parser)
    storage_context = StorageContext.from_defaults()
    storage_context.docstore.add_documents(nodes)
    index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)
    index.storage_context.persist(persist_dir=pathname)
    reranker = SentenceTransformerRerank(top_n = rr_metadata)
    retriever = index.as_retriever(similarity_top_k=retrieval_metadata_similarity)
    retriever = AutoMergingRetriever(retriever,index.storage_context,verbose=True)
    response_mode = 'tree_summarize'
    response_synthesizer = get_response_synthesizer(response_mode=response_mode)
    node_postprocessors = [postproc, reranker]
    node_postprocessors = [processor for processor in node_postprocessors if processor is not None]
    query_engine = RetrieverQueryEngine(retriever, node_postprocessors=node_postprocessors)
    summary_whole = query_engine.query(rag_prompt_original)
```
As can be seen, I am using the storage context to store the embeddings in pathname (which is in my local).
Now, what to do if I want to replace this local path with mongodb?
I found the below code via a tutorial, can you confirm if this is correct?

```
vector_store = MongoDBAtlasVectorSearch(client, db_name=db, collection_name=collection, index_name="vector_index")
vector_store.add(nodes)
index = VectorStoreIndex.from_vector_store(vector_store)
```

Also, I can't find any replacement of the "persist" in the topmost code in the above code. Somehow, I feel the mongodb code is just reading the indexes that are already saved in the mongodb.

Can someone tell me how to save my embeddings to mongodb while creating them for the first time, and then reading it from mongodb the next time?

**Comment by GildeshAbhay** [comment]
thanks

also, in my previous code

```
storage_context.docstore.add_documents(nodes)
index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)
```

why exactly is the storage context used here if nodes are already used?

is this argument, storage context in the 2nd line above, basically saving the nodes to storage? Which is again confusing as we have the below line for it
`
 index.storage_context.persist(persist_dir=pathname)`

my point for asking this followup question is this, that in the mongodb code you just gave, the index is created first and the `mongodb vector_store.add_nodes` occurs second. while in my code, the storage context is defined first and used while creating the indexes.

Lastly, If i keep the storage context code as well as the mongodb code both, would it be a problem  ? I would not keep the storage.persist line so I don't think i would be using any unnncessary storage.  Isn't it?

**Comment by GildeshAbhay** [comment]
quick follow up question, 

`index_name="vector_index",  # Ensure this matches the name of your vector search index`

So, my index code is this
`index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)
`
that's why the index name here would be "index"?

Thus the mongo code would be this
```
vector_store = MongoDBAtlasVectorSearch(
    client,
    db_name="your_database",
    collection_name="your_collection",
    index_name="index",  # Ensure this matches the name of your vector search index
)
```
Right?

**Comment by logan-markewich** [comment]
@GildeshAbhay Just to clarify, if you are using mongdb atlas (or any vectored integration), all the data is stored in the DB, you don't need a docstore or anything else unless you want key-val access to the nodes.

This also means there's no persist or loading, this all happens automatically.

For example, here's a full walkthrough

```
# Creating the index
vector_store = MongoDBAtlasVectorSearch(
    client,
    db_name="your_database",
    collection_name="your_collection",
    index_name="index",  # Ensure this matches the name of your vector search index
)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

# this will chunk and embed your nodes, and put them in MongoDB
index = VectorStoreIndex.from_documents(documents, storage_context=storage_context, ...)

# you can also pre-chunk the nodes, and pass those in. This will not apply chunking, it will just embed
index = VectorStoreIndex(nodes=nodes, storage_context=storage_context, ...)

# then to "load" and existing index, just use from_vector_store
index = VectorStoreIndex.from_vector_store(vector_store)
```

**Comment by GildeshAbhay** [comment]
which field exactly are the embeddings stored in the collection ?

**Comment by GildeshAbhay** [comment]
If I want to "see" the embeddings in the mongodb collection, would I have to perform the below step? 

```
for node in nodes:
    node_embedding = embed_model.get_text_embedding(
        node.get_content(metadata_mode="all")
    )
    node.embedding = node_embedding
```
