### ISSUE TITLE
Does llama index can read a BLOB type from sqllite database column?

### ISSUE THREAD

**Issue by Avinash-Raj** [run-llama/llama_index#12578]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

One of the table in SQLite database act as a document storage where all types of documents such as ".pdf", ".docx", etc stored as a BLOB type.  

Can we use `PDFReader` or `SimpleDirectoryReader` to read and create list of Documents from those files? If so, pls help me to achieve this.

**Comment by logan-markewich** [comment]
I don't think so. You need to get the blobs from your SQL db and either write them to a temp file and load them, or parse them in memory manually.
