### ISSUE TITLE
[Question]: DuckDB failed to release v0.1.3 - stuck with bug

### ISSUE THREAD

**Issue by iwilltry42** [run-llama/llama_index#12580]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

https://github.com/run-llama/llama_index/actions/runs/8547911319/job/23420834460

The "push to pypi" job failed due to lack of permissions, so we're stuck with 0.1.2 which errors out when reading an existing DuckDB from disk.

cc @logan-markewich (https://github.com/run-llama/llama_index/commit/b5a16cbfe323d0049a3d876225a7ba19f8f4d3cf)

**Comment by logan-markewich** [comment]
@iwilltry42 I know -- the author published it under their own account, I have no control over the package 😮‍💨 Trying to clear it up with them

In the meantime, please install v0.1.1. -- `pip install llama-index-vector-stores-duckdb==0.1.1`
