### ISSUE TITLE
[Bug]: Persist to Simple File store isn't working properly?

### ISSUE THREAD

**Issue by Data-drone** [run-llama/llama_index#12582]
### Bug Description

I am trying to persist a simple storage context and I cannot reload it successfully

It looks like persist function is creating vector_store with name `default__vector_store.json` and `index_store.jsom` not `vector_store.json` which the reload function is looking for?

### Version

'0.10.26

### Steps to Reproduce

create a vector store index
create a storage context with SimpleDocumentStore SimpleIndexStore SimpleVectorstore
persist
reload with from_persist_dir methods

### Relevant Logs/Tracbacks

```shell
ValueError: No existing llama_index.core.vector_stores.simple found at /Volumes/brian_tab_test/rag_bot/dataset/llama_index/beginner_index/vector_store.json, skipping load.
File <command-4049278270854854>, line 12
      5 from llama_index.core.storage.index_store import SimpleIndexStore
      6 from llama_index.core.vector_stores import SimpleVectorStore
      8 storage_context = StorageContext.from_defaults(
      9     docstore=SimpleDocumentStore.from_persist_dir(persist_dir=f'/Volumes/{catalog}/{schema}/{volumes}/llama_index/beginner_index'),
     10     index_store=SimpleIndexStore.from_persist_dir(
     11       persist_dir=f'/Volumes/{catalog}/{schema}/{volumes}/llama_index/beginner_index'),
---> 12     vector_store=SimpleVectorStore.from_persist_dir(
     13       persist_dir=f'/Volumes/{catalog}/{schema}/{volumes}/llama_index/beginner_index'),
     14 )
File /local_disk0/.ephemeral_nfs/envs/pythonEnv-0f6f9afd-d25d-4217-af43-1bcc2e7dadb5/lib/python3.10/site-packages/llama_index/core/vector_stores/simple.py:305, in SimpleVectorStore.from_persist_path(cls, persist_path, fs)
    303 fs = fs or fsspec.filesystem("file")
    304 if not fs.exists(persist_path):
--> 305     raise ValueError(
    306         f"No existing {__name__} found at {persist_path}, skipping load."
    307     )
    309 logger.debug(f"Loading {__name__} from {persist_path}.")
    310 with fs.open(persist_path, "rb") as f:
```

**Comment by logan-markewich** [comment]
Works fine for me

https://colab.research.google.com/drive/1cjC-kmEqPmQEoQr8_Xd5ebS58men0-s5?usp=sharing

**Comment by logan-markewich** [comment]
Am I missing something?

**Comment by Data-drone** [comment]
I am trying to reload the documents as a list so that I can use other index structures. what is the best approach for this?

**Comment by logan-markewich** [comment]
list(storage_context.docstore.docs.values())  will get you all the nodes

**Comment by Data-drone** [comment]
hi @logan-markewich there is no `values` attribute? in `SimpleDocumentStore`? I am using `llama_index==0.10.25`

**Comment by Data-drone** [comment]
it was: `VectorStoreIndex.docstore.docs.values()` that got me what I want not VectorStoreIndex.storage_context.docstore.docs.values()
