### ISSUE TITLE
[Bug]: SimpleDirectoryReader cant recursively find docs

### ISSUE THREAD

**Issue by alalalbert** [run-llama/llama_index#12585]
### Bug Description

Recursive use of SimpleDirectoryReader doesn't find files:

`  File "/Users/User/load.py", line 24, in <module>
    loader = SimpleDirectoryReader(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cahier/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 223, in __init__
    self.input_files = self._add_files(self.input_dir)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/User/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 305, in _add_files
    raise ValueError(f"No files found in {input_dir}.")`

### Version

0.10.26

### Steps to Reproduce

Use code here: https://huggingface.co/learn/cookbook/rag_llamaindex_librarian

from llama_index.core import SimpleDirectoryReader

loader = SimpleDirectoryReader(
    input_dir="./.test/",
    recursive=True,
    required_exts=[".epub"],
)

documents = loader.load_data()

**Comment by logan-markewich** [comment]
Personally, I think this is a typo in the guide. It's saving data to a hidden dir `.test` -- I think it should be `./test`

And if it is supposed to be `.test`, `SimpleDirectoryReader` has an option for including hidden files, which is by default true

`SimpleDirectoryReader(..., exclude_hidden=False)`

I'll get the guide updated on huggingface

**Comment by RichardScottOZ** [comment]
yes, I have come to this conclusion too I think - why have a test directory called .test?
