### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by valentindjangone** [run-llama/llama_index#12584]
### Bug Description

ImportError: cannot import name 'LLM' from 'llama_index.core.llms'

### Version

0.9.48

### Steps to Reproduce

I tried to import the following modules numerous times locally, with pip and conda, in the cloud with serve, colab and others and I failed in weird ways every time.

````
from llama_index.vector_stores.pinecone import PineconeVectorStore
from llama_index.core.settings import Settings
from llama_parser import LlamaParser
from llama_index.llms.openai import OpenAI
from llama_index.postprocessor.cohere_rerank import CohereRerank
from llama_index.core.node_parser import MarkdownElementNodeParser
from llama_index.embeddings.cohere import CohereEmbedding
````

--------------------------------------------------------------------------------------------------------
Here are the steps I take :

## Env loading :
```
python -m venv venv
source venv/bin/activate

```

## Importing
Now I'm running the import cell and iterate the imports with pip manually to find what's wrong because the simple following way doesn't do the job.

```
pip install -r requirements.txt 
```
```
#requirements.txt
llama-index
llama-index-core
llama-index-postprocessor-cohere-rerank
llama-index-vector-stores-pinecone
llama-index-embeddings-cohere
```

So I do 
```

pip install llama-index-vector-stores-pinecone

```
And when running the import cell again I immediately get the error :

- ImportError: cannot import name 'LLM' from 'llama_index.core.llms' (/Users/valentin/Desktop/betterstudy-ai/venv/lib/python3.11/site-packages/llama_index/core/llms/__init__.py)

Any help is welcome.

**Comment by logan-markewich** [comment]
You sure you are on version 0.9.48? It seems like you are just on latest?

In any case, the import works fine for me, and on google colab.

I suggest making a fresh venv

In a new terminal
```
# remove any global install related to llama-index
pip freeze | grep llama-index | xargs pip uninstall -y 

# start with a fresh venv
python -m venv llama_venv
source llama_venv/bin/activate
pip install llama-index llama-index-postprocessor-cohere-rerank llama-index-vector-stores-pinecone llama-index-embeddings-cohere
```

**Comment by valentindjangone** [comment]
I closed this too early, I've made a mistake in the name of a module : 
```
from  llama_parser import LlamaParser
```
Should be
```
from llama_parse import LlamaParser
```

(without the r at llama_parse)

Now, I have the same issue for another package.

The following gives me the same import error
```

# remove any global install related to llama-index
pip freeze | grep llama-index | xargs pip uninstall -y

# start with a fresh venv
python -m venv llama_venv
source llama_venv/bin/activate
pip install python-dotenv llama-index llama-index-core llama-index-postprocessor-cohere-rerank llama-index-vector-stores-pinecone llama-index-embeddings-cohere llama-parser
```

Does it work for you ?

**Comment by logan-markewich** [comment]
llama-parse is included in the `llama-index` installation as a dependency. But you can also do `pip install llama-parse` 

It works fine for me though, not sure what the issue is

**Comment by valentindjangone** [comment]
There we go, pip install llama-parse seemed to have conflicts with llama_parse obtained from llama-index.

I just installed llama-index and imported llama_parse from there and it worked. Thank you.
