### ISSUE TITLE
[Question]: How to decide the number of dimensions to query a vector index with ?

### ISSUE THREAD

**Issue by GildeshAbhay** [run-llama/llama_index#12598]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So I have the below code

`        pathname = os.path.join(os.getcwd(),embed_folder_name)
        pathname = os.path.join(pathname, document['DOI_CROSSREF'])
        content = document["content"]
        doc = Document(text=content)
        node_parser = HierarchicalNodeParser.from_defaults(chunk_sizes=chunk_size)
        nodes = node_parser.get_nodes_from_documents([doc])
        len(nodes)
        db = 'staging'
        collection = 'abhay_test'
        
        vector_store = MongoDBAtlasVectorSearch(client, db_name=db, collection_name=collection, index_name="nanopore_index", embeddings = OpenAIEmbeddings())
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        index = VectorStoreIndex(nodes=nodes, storage_context=storage_context,)        
        index1 = VectorStoreIndex.from_vector_store(vector_store)
        
        postproc = None
        reranker = SentenceTransformerRerank(top_n = rr_metadata)
        retriever = index.as_retriever(similarity_top_k=retrieval_metadata_similarity)
        retriever = AutoMergingRetriever(retriever,index.storage_context,verbose=True)
        response_synthesizer = get_response_synthesizer(response_mode=response_mode)
        node_postprocessors = [postproc, reranker]
        node_postprocessors = [processor for processor in node_postprocessors if processor is not None]
        query_engine = RetrieverQueryEngine(retriever, node_postprocessors=node_postprocessors)
        summary_whole = query_engine.query(rag_prompt_original)`
        
        
and in the last line, I get the following error

`
  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\network.py:192 in command
    helpers._check_command_response(

  File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\pymongo\helpers.py:230 in _check_command_response
    raise OperationFailure(errmsg, code, response, max_wire_version)

OperationFailure: PlanExecutor error during aggregation :: caused by :: vector field is indexed with 256 dimensions but queried with 1536, full error: {'ok': 0.0, 'errmsg': 'PlanExecutor error during aggregation :: caused by :: vector field is indexed with 256 dimensions but queried with 1536', 'code': 8, 'codeName': 'UnknownError', '$clusterTime': {'clusterTime': Timestamp(1712306589, 4), 'signature': {'hash': b'm\xcc\xdd\x0cx\xa3\x11\x06\x13\xfbJ\xa7\xa2\x8d\xa7\x80w\xee\x14\xe8', 'keyId': 7314031504940597260}}, 'operationTime': Timestamp(1712306589, 4)}`

I already know that my vector index in mongodb is of 256 dimensions. but not sure where did the 1536 number come from?

**Comment by logan-markewich** [comment]
This is a repeat, I answered in another issue.
