### ISSUE TITLE
[Bug]: Cohere Embedding through AWS Bedrock failing to create index

### ISSUE THREAD

**Issue by pikarpov** [run-llama/llama_index#12592]
### Bug Description

The wiki example of [CohereAI Embeddings](https://docs.llamaindex.ai/en/stable/examples/embeddings/cohereai/#now-with-latest-embed-english-v30-embeddings) doesn't seem to work when `cohere.embed-english-v3` is loaded through `BedrockEmbedding` with default parameters using longer documents. I was able to get it to work if I set the `Settings.chunk_size=80` and `Settings.chunk_overlap=10`, but it is very low chunk size for most productive tasks. Anything higher than that, and I get an error of exceeding `maxLength=2048`. 

The same procedure doesn't encounter any issues with the default `chunk_size=1024`, when using `amazon.titan-embed-text-v1`. It might be due to titan having a token limit (8k), while cohere's limit is defined in **characters** (2k). However, I would still expect cohere to support larger chunk sizes than 80.

### Version

0.10.24

### Steps to Reproduce

Follow [CohereAI Embeddings](https://docs.llamaindex.ai/en/stable/examples/embeddings/cohereai/#now-with-latest-embed-english-v30-embeddings) example for `embed-english-v3.0`, using the same sample data. The only difference is that the embedding model is loaded through Bedrock instead of directly from cohere.

```shell
!mkdir -p 'data/paul_graham/'
!wget 'https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt' -O 'data/paul_graham/paul_graham_essay.txt'
```

```python
from llama_index.embeddings.bedrock import BedrockEmbedding
import os

embed_model_name = "cohere.embed-english-v3"
embed_model = BedrockEmbedding(
    model=embed_model_name,
    aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
    aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
    aws_session_token=os.getenv("AWS_SESSION_TOKEN"),
    region_name=region_name,
    profile_name=profile_name,
)

documents = SimpleDirectoryReader("./data/paul_graham/").load_data()

index = VectorStoreIndex.from_documents(
    documents=documents,
    embed_model=embed_model
)
```

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ValidationException                       Traceback (most recent call last)
Cell In[4], line 23
     12 embed_model = BedrockEmbedding(
     13     model=embed_model_name,
     14     aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
   (...)
     18     profile_name=profile_name,
     19 )
     21 documents = SimpleDirectoryReader("./data/paul_graham/").load_data()
---> 23 index = VectorStoreIndex.from_documents(
     24     documents=documents,
     25     embed_model=embed_model,
     26 )
...
---------------------------------------------------------------------------

ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #/texts/0: expected maxLength: 2048, actual: 4288#/texts/1: expected maxLength: 2048, actual: 4357#/texts/2: expected maxLength: 2048, actual: 4391#/texts/3: expected maxLength: 2048, actual: 4369#/texts/4: expected maxLength: 2048, actual: 4459#/texts/5: expected maxLength: 2048, actual: 4311#/texts/6: expected maxLength: 2048, actual: 4294#/texts/7: expected maxLength: 2048, actual: 4307#/texts/8: expected maxLength: 2048, actual: 4387#/texts/9: expected maxLength: 2048, actual: 4295, please reformat your input and try again.
```

**Comment by pikarpov** [comment]
This doesn't explain why `chunk_size=128` or 256, 512, 1024 do not work. They are all under the `maxLength=2048` limit, yet fail.

**Comment by billytrend-cohere** [comment]
hey @pikarpov what version of the cohere sdk are you using? thanks!

**Comment by pikarpov** [comment]
@billytrend-cohere , I am using:

```shell
llama-index-llms-cohere==0.1.6
llama-index-embeddings-cohere==0.1.5
```

**Comment by kerlion** [comment]
I guess, maxLength=2048 for characters  while chunk_size is for tokens.

**Comment by RiEnClVi** [comment]
This fix seems to work only limited if you use it in combination with Pinecone + Cohere Embeddings of bedrock. Despite having max chunk size of 300 tokens + the newest version of llama index 0.10.34.

I still get:

> ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Input is too long for requested model.
