### ISSUE TITLE
[Question]: How to make a agent process to two index to answer? 

### ISSUE THREAD

**Issue by Ninlawat-Puhu** [run-llama/llama_index#12601]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have two indexs like this code

`from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.core.query_engine import SubQuestionQueryEngine
from llama_index.core.query_engine import RouterQueryEngine
from llama_index.core.selectors import PydanticMultiSelector

index_detail = VectorStoreIndex.from_documents(list_of_documents_leave_detail)
index = VectorStoreIndex.from_documents(list_of_documents_leave)

query_engine_leave_detail = index_detail.as_query_engine(similarity_top_k=100,filters = filters,streaming=True,)
query_engine_leave = index.as_query_engine(similarity_top_k=2,filters = filters,streaming=True,)

tool1 = QueryEngineTool.from_defaults(
query_engine=query_engine_leave_detail,
description="เป็นข้อมูลเกี่ยวกับข้อมูลส่วนตัวของพนักงานและรายละเอียดของการลาในแต่ละครั้ง ประกอบไปด้วย รหัสพนักงาน,ชื่อของพนักงาน,ชื่อเล่นของพนักงาน,เบอร์โทรศัพท์มือถือ,ตำแหน่ง,สังกัด,อีเมล,type of leave ในแต่ละครั้ง,จำนวนวันที่ลาในแต่ละครั้ง,วันแรกที่ลาในแต่ละครั้ง,วันสุดท้ายที่ลาในแต่ละครั้ง,reason of leave ในแต่ละครั้ง,support reason of leave ในแต่ละครั้ง",
)
tool2 = QueryEngineTool.from_defaults(
query_engine=query_engine_leave,
description="เป็นข้อมูลเกี่ยวกับสรุปจำนวนการลาทั้งหมด ประกอบไปด้วย รหัสพนักงาน, ประเภทของวันลาพร้อมกับจำนวนวันลาที่สะลมมาจากปีที่แล้ว, จำนวนวันลาที่ใช้ไปทั้งหมด, สิทธิการลาทั้งหมด,  และจำนวนวันลาที่เหลืออยู่ทั้งหมด ของแต่ละประเภท"
)
query_engine = RouterQueryEngine(
    selector=PydanticMultiSelector.from_defaults(),
    query_engine_tools=[tool1, tool2],
)`

When the program process, it process only one index. I means, when I ask question that related between two index (too1 and tool2). My question is that how to make a agent processing two indexs ? from this code what I should add programs or can you provide example of code ?

**Comment by logan-markewich** [comment]
@Ninlawat-Puhu you should provide meaningful names and descriptions to your tools, so that the agent can better understand which tools it should be using to answer a query.

All the agent sees is the user message + chat history/system prompt, the tool names, and tool descriptions, and has to decide from there
