### ISSUE TITLE
[Question]: how to control the chunking of documents according to chapter number etc?

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#12605]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

by analysing the docstore, I realized a problem that it might happen that the end of a previous chapter and the start of the next chapter were chunked into one node. This results in the fact that llm misunderstood the content of the node, tried to mix the two parts together and generated incorrect responses.

Is there a way to resolve this problem please?

**Comment by justinzyw** [comment]
wonder whether there is a way to chunk according to chapter numbers? say .... chunk at end of chapter 1, chapter 2, etc...

**Comment by justinzyw** [comment]
thanks for the suggestion. unfortunately Semantic splitter says that it only works with English language, which does not fulfill my needs to adapt multiple lanaguages. I also noticed that there is a MarkdownNodeParser and a HTMLNodeParser. what if I change my documents into html or md format? can it give me control the chunking by explicitly setting heading levels?

**Comment by logan-markewich** [comment]
@justinzyw you'd have to have a way of identifying where chapter 1, chapter 2, etc. starts and ends, which is non-trivial

**Comment by justinzyw** [comment]
> @justinzyw you'd have to have a way of identifying where chapter 1, chapter 2, etc. starts and ends, which is non-trivial

true. I found that I could use md format to ensure the breaks in between chapters. trival but works. Thanks for your suggestion.
