### ISSUE TITLE
[Feature Request]: KnowledgeGraph metadata extractors

### ISSUE THREAD

**Issue by stdweird** [run-llama/llama_index#12600]
### Feature Description

Implement KnowledgeGraph metadata extractors that can run in a pipeline and add the extracted data as node metadata.
Also add code in KnowledgeGraph classed to extract the metadata from the node.

2 extractors are needed:
- KGTripetExtractor (based on the code from the KnowledgeGraphIndex), optionally adding the triplet embedding (the triplet embedding metadata must be added to the node excluded_llm_metadata_keys / excluded_embed_metadata_keys)
- KGKeywordExtractor (based on the code from KGTableRetriever)

Ideally they current code from KnowledgeGraphIndex and KGTableRetriever is factored out (in eg llama_index.core.indices.knowledge_graph.utils), so both the metadata extractor and the current code use the same code/templates/processing...

### Reason

I think the pipeline flow is the only way to do data ingestion, the current KnowledgeGraph code is complicating this clean flow.

### Value of Feature

Integrating the KnowledgeGraph in the pipeline flow is imho less useful. 
Having the metadata in the node might also benefit vector_store RAG, and having easy access via the docstore to the extracted triplets and keywords also benefits debugging RAG flow (as you can clearly see the data from each node in eg the observer of choice).

**Comment by stdweird** [comment]
i am willing to give this a try, but need to know if this is acceptable etc etc

**Comment by logan-markewich** [comment]
@stdweird the current knowledge graph index is kind of in tech-debt mode. It doesn't scale well, is complicated to use, and generally not great.

There is a refactor in progress to introduce a new graph index, which will probably help. But due to that, I wouldn't expect any changes to the existing knowledge graph index

Also, ingestion pipeline isn't the only way to do ingestion? You can insert nodes or documents directly into an index. You can even run an ingestion pipeline and insert the output nodes into your index

**Comment by stdweird** [comment]
@logan-markewich good to hear about the refactor. i will wait for that and continue my other testing with current design.

wrt the pipeline, i was not suggesting to drop current interfaces and only support pipeline. far from it. my usage now is already to pass nodes to the KGindex.

but these nodes come from an ingestion pipeline (the coupling with a docstore to avoid unnecessary work etc is what i consider essential part of the ingest in our case). 

and tbh i would prefer to have the triplets and keywords in the docstore. it makes it easier to debug problems with the RAG flow. if eg a query doesn't return expected answer, documentation maintainers can eg inspect the node with parts of the correct reply, and then see possible issues like missing relation triplets. (documentation maintainers know how eg the pdf looks like, but have no clue how the plain text version looks like, or the where chunking happpens, let alone what relations a LLM would extract from them).

**Comment by robmoss2k** [comment]
`There is a refactor in progress to introduce a new graph index`

Which branch does this live on? We're very interested in something that indexes faster, preferably queuing up calls using AsyncOpenAI, or making calls using multiple threads. It can take hours for a large document, and AWS Lambda functions only give you up to 15 minutes. We've tried overriding some of the internals with the various available arguments but got nowhere as parts of the graph are missing when we do that.

**Comment by logan-markewich** [comment]
Imp I would expect extracting triplets to remain a bottleneck always though, unless LLMs get dramatically faster and rate limits over apis become a non-issue 

The APIs themselves are really not there yet for production use in high-volume tasks like this (this is just my opinion lol, it's slow, and expensive, but makes for a cool demo)
