### ISSUE TITLE
[Bug]: installing `llama-index-llms-huggingface` breaks the environment

### ISSUE THREAD

**Issue by ShivanshuPurohit** [run-llama/llama_index#12608]
### Bug Description

`pip install llama-index-llms-huggingface` installs various nvidia libraries that break my environment to the point where `nvidia-smi` says `Failed to initialize NVML: Unknown Error`. 

Any way to disable installs for the nvidia libraries?

### Version

0.10.26

### Steps to Reproduce

`pip install llama-index-llms-huggingface` or `pip install llama-index-embeddings-huggingface` both show this.

**Comment by logan-markewich** [comment]
@ShivanshuPurohit dosu is correct here -- install the dependencies before installing the library if you don't want it to mess with things.

As you can see, nothing explicitly cuda related is in the dependencies. Install torch, transformers ahead of time and in way that works for your env, and you will be good to go
