### ISSUE TITLE
[Question]: ValueError: doc_id ae078fc5-a18a-4d9c-a36b-56aa2793f381 not found.

### ISSUE THREAD

**Issue by GildeshAbhay** [run-llama/llama_index#12603]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So i am running a basic RAG application and storing embeddings in mongodb, but when I run the query engine, I get the error doc_id not found.

Here is my basic code
`      content = document["content"]
        doc = Document(text=content)
        node_parser = HierarchicalNodeParser.from_defaults(chunk_sizes=chunk_size)
        nodes = node_parser.get_nodes_from_documents([doc])
        
        for node in nodes:
            node_embedding = embed_model.get_text_embedding(
                node.get_content(metadata_mode="all")
            )
            node.embedding = node_embedding
        len(nodes)
        db = 'staging'
        collection = 'abhay_test'
        
        vector_store = MongoDBAtlasVectorSearch(client, db_name=db, collection_name=collection, index_name="nanopore_index", embeddings = OpenAIEmbeddings())
        vector_store.add(nodes)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        index = VectorStoreIndex(nodes=nodes, storage_context=storage_context,)        
        index1 = VectorStoreIndex.from_vector_store(vector_store)
        
        postproc = None
        reranker = SentenceTransformerRerank(top_n = rr_metadata)
        retriever = index.as_retriever(similarity_top_k=retrieval_metadata_similarity)
        retriever = AutoMergingRetriever(retriever,index.storage_context,verbose=True)
        response_synthesizer = get_response_synthesizer(response_mode=response_mode)
        node_postprocessors = [postproc, reranker]
        node_postprocessors = [processor for processor in node_postprocessors if processor is not None]
        query_engine = RetrieverQueryEngine(retriever, node_postprocessors=node_postprocessors)
        query_engine = RetrieverQueryEngine(retriever)
        summary_whole = query_engine.query(rag_prompt_original)
        summary_text = str(summary_whole)  # Convert the summary object to a string
   
`
I guess the problem is that one of the nodes is not found ? Would changing the embedding dimensions help?

**Comment by GildeshAbhay** [comment]
I checked, its not a document id at all. It's most likely a node id

**Comment by GildeshAbhay** [comment]
@logan-markewich  can you help please

**Comment by logan-markewich** [comment]
@GildeshAbhay when using a vector db integration, only the vector store is used. However, you need access to more than just the nodes in the vector store for this to work.

You should either manually populate (and persist) the docstore on the storage context, or set `store_nodes_override=True` when creating your index.

Furthermore, for auto-merging retriever to even work, I think you are missing a step? Normalizing you'd add all nodes to your docstore, and only index the leaf nodes.
https://docs.llamaindex.ai/en/latest/examples/retrievers/auto_merging_retriever/?h=auto+mer

**Comment by GildeshAbhay** [comment]
thanks a lot for responding!!

Here, I edited the code a bit.

`       doc = Document(text=content)
        node_parser = HierarchicalNodeParser.from_defaults(chunk_sizes=chunk_size)
        nodes = node_parser.get_nodes_from_documents([doc])


        leaf_nodes = get_leaf_nodes(nodes)
        root_nodes = get_root_nodes(nodes)

        for node in nodes:
            node_embedding = embed_model.get_text_embedding(
                node.get_content(metadata_mode="all")
            )
            node.embedding = node_embedding
        len(nodes)
        db = 'staging'
        collection = 'abhay_test'
        
        vector_store = MongoDBAtlasVectorSearch(client, db_name=db, collection_name=collection, index_name="nanopore_index_1", embeddings = OpenAIEmbeddings())
        vector_store.add(nodes)
        storage_context = StorageContext.from_defaults(vector_store=vector_store)
        index = VectorStoreIndex(nodes=nodes, storage_context=storage_context,store_nodes_override=True)        
        index = VectorStoreIndex(nodes = leaf_nodes, storage_context = storage_context, nodes_override= True)
        #index = VectorStoreIndex.from_vector_store(vector_store)
        
        postproc = None
        reranker = SentenceTransformerRerank(top_n = rr_metadata)
        retriever = index.as_retriever(similarity_top_k=retrieval_metadata_similarity)
        retriever = AutoMergingRetriever(retriever,index.storage_context,verbose=True)
        response_synthesizer = get_response_synthesizer(response_mode=response_mode)
        node_postprocessors = [postproc, reranker]
        node_postprocessors = [processor for processor in node_postprocessors if processor is not None]
        query_engine = RetrieverQueryEngine(retriever, node_postprocessors=node_postprocessors)
        query_engine = RetrieverQueryEngine(retriever)
        summary_whole = query_engine.query(rag_prompt_original)`
        
It's working now.
Tell me however, a few things.
1. If I put leaf nodes instead of nodes in index, the fina, output is only marginally different (95% same)
2. The docstore part that you mentioned is already taken care by the below code
`vector_store.add(nodes)`
Can you confirm?
3. For actually storing the embeddings in mongodb, is this step necessary?
` for node in nodes:
            node_embedding = embed_model.get_text_embedding(
                node.get_content(metadata_mode="all")
            )
            node.embedding = node_embedding`
Without this, step, its not possible to store embeddings in mongo db ? And then read it from mongodb?        
4. LAstly, currently each node is stored separately like this
![image](https://github.com/run-llama/llama_index/assets/147131617/de5e763d-26ca-4d35-893a-bea561926d38)
but i want all the nodes embeddings to be stored in the same row of data which harbors the information about the rest of the node.
![image](https://github.com/run-llama/llama_index/assets/147131617/f45d03c2-3507-4faf-ba36-26a4ac490e37)
under a key value pair.
How to achieve this?

**Comment by GildeshAbhay** [comment]
one more thing, if I want to use those embeddings (mentioned above), what should i run?

**Comment by logan-markewich** [comment]
Yea, it might not make a huge difference, especially if the top k is low

The vector store and docstore are different. If enough nodes are retrieved from the vector store that have the same parent, the are replaced with their parent node (which is only in the docstore)

You can pre-calculate and attach the nodes like you are, but if you didn't, the same would be done under the hood if they were missing.

You can't change how it's stored in mongodb.

I don't know what you mean by using those embeddings?

**Comment by GildeshAbhay** [comment]
THanks again for taking the time to reply ! Appreciate it!

> Yea, it might not make a huge difference, especially if the top k is low
Cool. So that's sorted. 
> The vector store and docstore are different. If enough nodes are retrieved from the vector store that have the same parent, the are replaced with their parent node (which is only in the docstore)
Can you please give me the codes for both and explicitly show the difference? Basically, I want to know how to add node/doc information to both and then retrieve both so that I don't waste keys on embeddings. 
> You can pre-calculate and attach the nodes like you are, but if you didn't, the same would be done under the hood if they were missing.
If I didn't write the node.embeddings lines, the index code gives an error. Says, "embed" not defined.
> You can't change how it's stored in mongodb.
Okay. So If my overall goal is to store the embeddings in mongodb just so that I can retrieve it from there (whenever I want to use it,  so that re-indexing doesn't have to happen), is it better to then store the embeddings locally as json files and then "upsert" it to mongodb? 
> I don't know what you mean by using those embeddings?
Using means, using them so that I don't have re-calculate the embeddings and waste tokens.

**Comment by GildeshAbhay** [comment]
@logan-markewich  can you please help here

**Comment by YanSte** [comment]
Did you solve your issue i have the same ..

**Comment by YanSte** [comment]
I have resolved the issue as follows:

**Using MongoDB:**
- Created a `MongoDBAtlasVectorSearch` as the vector store.
- Created a `MongoDocumentStore` as the document store.

**Note:** When using MongoDB with the Search Index Atlas, you need to manually create the index vector with doc vector. With a Cluster M10, you can simply code this process.

After that:

```
index = VectorStoreIndex.from_vector_store(vector_store=vector_store)

base_retriever = index.as_retriever(similarity_top_k=...)

storage_context = StorageContext.from_defaults(index_store=index, docstore=docstore)

retriever = AutoMergingRetriever(
    vector_retriever=base_retriever,
    storage_context=storage_context
)

query_engine = RetrieverQueryEngine.from_args(
    retriever=retriever,
    node_postprocessors=[rerank_model],
    llm=...
)
```
