### ISSUE TITLE
[Question]: cannot properly install 0.10 in windows

### ISSUE THREAD

**Issue by junxu-ai** [run-llama/llama_index#12617]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

after installing the llama-index =0.10.27, the main components are not included to use, e.g., core, llms, etc, although the package can be found in the lib. 

(llamaindex) C:\Users\python
Python 3.11.8 | packaged by Anaconda, Inc. | (main, Feb 26 2024, 21:34:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_index
>>> dir(llama_index)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>>

-------------below is the installation logs -----------
(llamaindex) C:\Users\>pip install llama-index
Collecting llama-index
  Using cached llama_index-0.10.27-py3-none-any.whl.metadata (11 kB)
Collecting llama-index-agent-openai<0.3.0,>=0.1.4 (from llama-index)
  Using cached llama_index_agent_openai-0.2.2-py3-none-any.whl.metadata (677 bytes)
Collecting llama-index-cli<0.2.0,>=0.1.2 (from llama-index)
  Using cached llama_index_cli-0.1.11-py3-none-any.whl.metadata (1.5 kB)
Collecting llama-index-core<0.11.0,>=0.10.27 (from llama-index)
  Using cached llama_index_core-0.10.27-py3-none-any.whl.metadata (3.6 kB)
Collecting llama-index-embeddings-openai<0.2.0,>=0.1.5 (from llama-index)
  Using cached llama_index_embeddings_openai-0.1.7-py3-none-any.whl.metadata (603 bytes)
Collecting llama-index-indices-managed-llama-cloud<0.2.0,>=0.1.2 (from llama-index)
  Using cached llama_index_indices_managed_llama_cloud-0.1.5-py3-none-any.whl.metadata (3.8 kB)
Collecting llama-index-legacy<0.10.0,>=0.9.48 (from llama-index)
  Using cached llama_index_legacy-0.9.48-py3-none-any.whl.metadata (8.5 kB)
Collecting llama-index-llms-openai<0.2.0,>=0.1.13 (from llama-index)
  Using cached llama_index_llms_openai-0.1.14-py3-none-any.whl.metadata (559 bytes)
Collecting llama-index-multi-modal-llms-openai<0.2.0,>=0.1.3 (from llama-index)
  Using cached llama_index_multi_modal_llms_openai-0.1.4-py3-none-any.whl.metadata (728 bytes)
Collecting llama-index-program-openai<0.2.0,>=0.1.3 (from llama-index)
  Using cached llama_index_program_openai-0.1.5-py3-none-any.whl.metadata (715 bytes)
Collecting llama-index-question-gen-openai<0.2.0,>=0.1.2 (from llama-index)
  Using cached llama_index_question_gen_openai-0.1.3-py3-none-any.whl.metadata (785 bytes)
Collecting llama-index-readers-file<0.2.0,>=0.1.4 (from llama-index)
  Using cached llama_index_readers_file-0.1.13-py3-none-any.whl.metadata (934 bytes)
Collecting llama-index-readers-llama-parse<0.2.0,>=0.1.2 (from llama-index)
  Using cached llama_index_readers_llama_parse-0.1.4-py3-none-any.whl.metadata (3.5 kB)
Collecting openai>=1.14.0 (from llama-index-agent-openai<0.3.0,>=0.1.4->llama-index)
  Using cached openai-1.16.2-py3-none-any.whl.metadata (21 kB)
Collecting PyYAML>=6.0.1 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting SQLAlchemy>=1.4.49 (from SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading SQLAlchemy-2.0.29-cp311-cp311-win_amd64.whl.metadata (9.8 kB)
Collecting aiohttp<4.0.0,>=3.8.6 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading aiohttp-3.9.3-cp311-cp311-win_amd64.whl.metadata (7.6 kB)
Collecting dataclasses-json (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached dataclasses_json-0.6.4-py3-none-any.whl.metadata (25 kB)
Collecting deprecated>=1.2.9.3 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached Deprecated-1.2.14-py2.py3-none-any.whl.metadata (5.4 kB)
Collecting dirtyjson<2.0.0,>=1.0.8 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached dirtyjson-1.0.8-py3-none-any.whl.metadata (11 kB)
Collecting fsspec>=2023.5.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached fsspec-2024.3.1-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached httpx-0.27.0-py3-none-any.whl.metadata (7.2 kB)
Collecting llamaindex-py-client<0.2.0,>=0.1.16 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached llamaindex_py_client-0.1.16-py3-none-any.whl.metadata (711 bytes)
Collecting nest-asyncio<2.0.0,>=1.5.8 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached nest_asyncio-1.6.0-py3-none-any.whl.metadata (2.8 kB)
Collecting networkx>=3.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached networkx-3.2.1-py3-none-any.whl.metadata (5.2 kB)
Collecting nltk<4.0.0,>=3.8.1 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached nltk-3.8.1-py3-none-any.whl.metadata (2.8 kB)
Collecting numpy (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.6 MB/s eta 0:00:00
Collecting pandas (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading pandas-2.2.1-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting pillow>=9.0.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading pillow-10.3.0-cp311-cp311-win_amd64.whl.metadata (9.4 kB)
Collecting requests>=2.31.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting tenacity<9.0.0,>=8.2.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached tenacity-8.2.3-py3-none-any.whl.metadata (1.0 kB)
Collecting tiktoken>=0.3.3 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading tiktoken-0.6.0-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting tqdm<5.0.0,>=4.66.1 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached tqdm-4.66.2-py3-none-any.whl.metadata (57 kB)
Collecting typing-extensions>=4.5.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached typing_extensions-4.11.0-py3-none-any.whl.metadata (3.0 kB)
Collecting typing-inspect>=0.8.0 (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached typing_inspect-0.9.0-py3-none-any.whl.metadata (1.5 kB)
Collecting wrapt (from llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading wrapt-1.16.0-cp311-cp311-win_amd64.whl.metadata (6.8 kB)
Collecting beautifulsoup4<5.0.0,>=4.12.3 (from llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Using cached beautifulsoup4-4.12.3-py3-none-any.whl.metadata (3.8 kB)
Collecting pymupdf<2.0.0,>=1.23.21 (from llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Downloading PyMuPDF-1.24.1-cp311-none-win_amd64.whl.metadata (3.4 kB)
Collecting pypdf<5.0.0,>=4.0.1 (from llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Using cached pypdf-4.1.0-py3-none-any.whl.metadata (7.4 kB)
Collecting striprtf<0.0.27,>=0.0.26 (from llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Using cached striprtf-0.0.26-py3-none-any.whl.metadata (2.1 kB)
Collecting llama-parse<0.5.0,>=0.4.0 (from llama-index-readers-llama-parse<0.2.0,>=0.1.2->llama-index)
  Using cached llama_parse-0.4.0-py3-none-any.whl.metadata (3.4 kB)
Collecting aiosignal>=1.1.2 (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached attrs-23.2.0-py3-none-any.whl.metadata (9.5 kB)
Collecting frozenlist>=1.1.1 (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading frozenlist-1.4.1-cp311-cp311-win_amd64.whl.metadata (12 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading multidict-6.0.5-cp311-cp311-win_amd64.whl.metadata (4.3 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp<4.0.0,>=3.8.6->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading yarl-1.9.4-cp311-cp311-win_amd64.whl.metadata (32 kB)
Collecting soupsieve>1.2 (from beautifulsoup4<5.0.0,>=4.12.3->llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Using cached soupsieve-2.5-py3-none-any.whl.metadata (4.7 kB)
Collecting pydantic>=1.10 (from llamaindex-py-client<0.2.0,>=0.1.16->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached pydantic-2.6.4-py3-none-any.whl.metadata (85 kB)
Collecting anyio (from httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached anyio-4.3.0-py3-none-any.whl.metadata (4.6 kB)
Collecting certifi (from httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Collecting httpcore==1.* (from httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached httpcore-1.0.5-py3-none-any.whl.metadata (20 kB)
Collecting idna (from httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting sniffio (from httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached h11-0.14.0-py3-none-any.whl.metadata (8.2 kB)
Collecting click (from nltk<4.0.0,>=3.8.1->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting joblib (from nltk<4.0.0,>=3.8.1->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached joblib-1.3.2-py3-none-any.whl.metadata (5.4 kB)
Collecting regex>=2021.8.3 (from nltk<4.0.0,>=3.8.1->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading regex-2023.12.25-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB ? eta 0:00:00
Collecting distro<2,>=1.7.0 (from openai>=1.14.0->llama-index-agent-openai<0.3.0,>=0.1.4->llama-index)
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting PyMuPDFb==1.24.1 (from pymupdf<2.0.0,>=1.23.21->llama-index-readers-file<0.2.0,>=0.1.4->llama-index)
  Using cached PyMuPDFb-1.24.1-py3-none-win_amd64.whl.metadata (1.4 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.31.0->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl.metadata (34 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.31.0->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting greenlet!=0.4.17 (from SQLAlchemy>=1.4.49->SQLAlchemy[asyncio]>=1.4.49->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading greenlet-3.0.3-cp311-cp311-win_amd64.whl.metadata (3.9 kB)
Collecting colorama (from tqdm<5.0.0,>=4.66.1->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting mypy-extensions>=0.3.0 (from typing-inspect>=0.8.0->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached mypy_extensions-1.0.0-py3-none-any.whl.metadata (1.1 kB)
Collecting marshmallow<4.0.0,>=3.18.0 (from dataclasses-json->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached marshmallow-3.21.1-py3-none-any.whl.metadata (7.2 kB)
Collecting python-dateutil>=2.8.2 (from pandas->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting pytz>=2020.1 (from pandas->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Collecting packaging>=17.0 (from marshmallow<4.0.0,>=3.18.0->dataclasses-json->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached packaging-24.0-py3-none-any.whl.metadata (3.2 kB)
Collecting annotated-types>=0.4.0 (from pydantic>=1.10->llamaindex-py-client<0.2.0,>=0.1.16->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.16.3 (from pydantic>=1.10->llamaindex-py-client<0.2.0,>=0.1.16->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Downloading pydantic_core-2.16.3-cp311-none-win_amd64.whl.metadata (6.6 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->llama-index-core<0.11.0,>=0.10.27->llama-index)
  Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
Using cached llama_index-0.10.27-py3-none-any.whl (6.9 kB)
Using cached llama_index_agent_openai-0.2.2-py3-none-any.whl (12 kB)
Using cached llama_index_cli-0.1.11-py3-none-any.whl (26 kB)
Using cached llama_index_core-0.10.27-py3-none-any.whl (15.4 MB)
Using cached llama_index_embeddings_openai-0.1.7-py3-none-any.whl (6.0 kB)
Using cached llama_index_indices_managed_llama_cloud-0.1.5-py3-none-any.whl (6.7 kB)
Using cached llama_index_legacy-0.9.48-py3-none-any.whl (2.0 MB)
Using cached llama_index_llms_openai-0.1.14-py3-none-any.whl (10 kB)
Using cached llama_index_multi_modal_llms_openai-0.1.4-py3-none-any.whl (5.8 kB)
Using cached llama_index_program_openai-0.1.5-py3-none-any.whl (4.1 kB)
Using cached llama_index_question_gen_openai-0.1.3-py3-none-any.whl (2.9 kB)
Using cached llama_index_readers_file-0.1.13-py3-none-any.whl (36 kB)
Using cached llama_index_readers_llama_parse-0.1.4-py3-none-any.whl (2.5 kB)
Downloading aiohttp-3.9.3-cp311-cp311-win_amd64.whl (365 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 365.3/365.3 kB 22.2 MB/s eta 0:00:00
Using cached beautifulsoup4-4.12.3-py3-none-any.whl (147 kB)
Using cached Deprecated-1.2.14-py2.py3-none-any.whl (9.6 kB)
Using cached dirtyjson-1.0.8-py3-none-any.whl (25 kB)
Using cached fsspec-2024.3.1-py3-none-any.whl (171 kB)
Using cached llama_parse-0.4.0-py3-none-any.whl (7.0 kB)
Using cached llamaindex_py_client-0.1.16-py3-none-any.whl (135 kB)
Using cached httpx-0.27.0-py3-none-any.whl (75 kB)
Using cached httpcore-1.0.5-py3-none-any.whl (77 kB)
Using cached nest_asyncio-1.6.0-py3-none-any.whl (5.2 kB)
Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Using cached nltk-3.8.1-py3-none-any.whl (1.5 MB)
Using cached openai-1.16.2-py3-none-any.whl (267 kB)
Downloading pillow-10.3.0-cp311-cp311-win_amd64.whl (2.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 53.6 MB/s eta 0:00:00
Downloading PyMuPDF-1.24.1-cp311-none-win_amd64.whl (3.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 12.8 MB/s eta 0:00:00
Using cached PyMuPDFb-1.24.1-py3-none-win_amd64.whl (24.9 MB)
Using cached pypdf-4.1.0-py3-none-any.whl (286 kB)
Downloading PyYAML-6.0.1-cp311-cp311-win_amd64.whl (144 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 144.7/144.7 kB 8.4 MB/s eta 0:00:00
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Downloading SQLAlchemy-2.0.29-cp311-cp311-win_amd64.whl (2.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 66.6 MB/s eta 0:00:00
Using cached striprtf-0.0.26-py3-none-any.whl (6.9 kB)
Using cached tenacity-8.2.3-py3-none-any.whl (24 kB)
Downloading tiktoken-0.6.0-cp311-cp311-win_amd64.whl (798 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 798.7/798.7 kB 24.6 MB/s eta 0:00:00
Using cached tqdm-4.66.2-py3-none-any.whl (78 kB)
Using cached typing_extensions-4.11.0-py3-none-any.whl (34 kB)
Using cached typing_inspect-0.9.0-py3-none-any.whl (8.8 kB)
Downloading wrapt-1.16.0-cp311-cp311-win_amd64.whl (37 kB)
Using cached dataclasses_json-0.6.4-py3-none-any.whl (28 kB)
Downloading numpy-1.26.4-cp311-cp311-win_amd64.whl (15.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 72.5 MB/s eta 0:00:00
Downloading pandas-2.2.1-cp311-cp311-win_amd64.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 81.8 MB/s eta 0:00:00
Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Using cached anyio-4.3.0-py3-none-any.whl (85 kB)
Using cached attrs-23.2.0-py3-none-any.whl (60 kB)
Using cached certifi-2024.2.2-py3-none-any.whl (163 kB)
Downloading charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.9/99.9 kB 5.6 MB/s eta 0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Downloading frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.5/50.5 kB ? eta 0:00:00
Downloading greenlet-3.0.3-cp311-cp311-win_amd64.whl (292 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 292.8/292.8 kB 18.8 MB/s eta 0:00:00
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached marshmallow-3.21.1-py3-none-any.whl (49 kB)
Downloading multidict-6.0.5-cp311-cp311-win_amd64.whl (28 kB)
Using cached mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Using cached pydantic-2.6.4-py3-none-any.whl (394 kB)
Downloading pydantic_core-2.16.3-cp311-none-win_amd64.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 60.3 MB/s eta 0:00:00
Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Using cached pytz-2024.1-py2.py3-none-any.whl (505 kB)
Downloading regex-2023.12.25-cp311-cp311-win_amd64.whl (269 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.5/269.5 kB ? eta 0:00:00
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached soupsieve-2.5-py3-none-any.whl (36 kB)
Using cached tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Using cached urllib3-2.2.1-py3-none-any.whl (121 kB)
Downloading yarl-1.9.4-cp311-cp311-win_amd64.whl (76 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.7/76.7 kB ? eta 0:00:00
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Using cached packaging-24.0-py3-none-any.whl (53 kB)
Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: striprtf, pytz, dirtyjson, wrapt, urllib3, tzdata, typing-extensions, tenacity, soupsieve, sniffio, six, regex, PyYAML, pypdf, PyMuPDFb, pillow, packaging, numpy, networkx, nest-asyncio, mypy-extensions, multidict, joblib, idna, h11, greenlet, fsspec, frozenlist, distro, colorama, charset-normalizer, certifi, attrs, annotated-types, yarl, typing-inspect, tqdm, SQLAlchemy, requests, python-dateutil, pymupdf, pydantic-core, marshmallow, httpcore, deprecated, click, beautifulsoup4, anyio, aiosignal, tiktoken, pydantic, pandas, nltk, httpx, dataclasses-json, aiohttp, openai, llamaindex-py-client, llama-index-legacy, llama-index-core, llama-parse, llama-index-readers-file, llama-index-llms-openai, llama-index-indices-managed-llama-cloud, llama-index-embeddings-openai, llama-index-readers-llama-parse, llama-index-multi-modal-llms-openai, llama-index-cli, llama-index-agent-openai, llama-index-program-openai, llama-index-question-gen-openai, llama-index
Successfully installed PyMuPDFb PyYAML SQLAlchemy aiohttp aiosignal annotated-types anyio attrs beautifulsoup4 certifi charset-normalizer click colorama dataclasses-json deprecated dirtyjson distro frozenlist fsspec greenlet h11 httpcore httpx idna joblib llama-index llama-index-agent-openai llama-index-cli llama-index-core llama-index-embeddings-openai llama-index-indices-managed-llama-cloud llama-index-legacy llama-index-llms-openai llama-index-multi-modal-llms-openai llama-index-program-openai llama-index-question-gen-openai llama-index-readers-file llama-index-readers-llama-parse llama-parse llamaindex-py-client marshmallow multidict mypy-extensions nest-asyncio networkx nltk numpy openai packaging pandas pillow pydantic pydantic-core pymupdf pypdf python-dateutil pytz regex requests six sniffio soupsieve striprtf tenacity tiktoken tqdm typing-extensions typing-inspect tzdata urllib3 wrapt yarl

**Comment by junxu-ai** [comment]
btw, the installation for 0.9.48 is ok to use. however, due to signfiicant API changes, i decided to use the latest 0.10.x.

**Comment by junxu-ai** [comment]
> @junxu-ai use a fresh venv (and tbh, don't use conda, but that's just my opinion)
> 
> In a fresh terminal (assuming powershell)
> 
> ```
> # remove any global install
> pip freeze | grep llama-index | xargs pip uninstall -y
> 
> python -m venv venv
> 
> # this is specific to your terminal. For windows powershell, it should be 
> ./venv/Scripts/Activate.ps1
> pip install llama-index
> ```

Yes, i created a new conda env, and install it from fresh, although some libraries were cached.

**Comment by junxu-ai** [comment]
> Hello @junxu-ai,
> 
> Based on the installation logs you've provided and the issue you're encountering, it seems like the installation process completed successfully, but you're unable to access the main components of the `llama-index` package.
> 
> Following the advice from @logan-markewich, using a fresh virtual environment (venv) could potentially solve the issue you're facing. It's important to ensure that there are no global installations of `llama-index` that might be conflicting with your project-specific installation. Here's a step-by-step guide tailored for Windows PowerShell, as suggested:
> 
> 1. **Remove any global installations of `llama-index`**:
>    First, ensure that there are no globally installed versions of `llama-index` that could be causing conflicts. You can do this by running the following command in your terminal:
>    ```powershell
>    pip freeze | grep llama-index | xargs pip uninstall -y
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This command lists all installed packages, filters for `llama-index`, and then uninstalls it.
> 2. **Create a new virtual environment**:
>    Next, create a new virtual environment to ensure a clean, isolated workspace for your project. You can do this by running:
>    ```powershell
>    python -m venv venv
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This command creates a new virtual environment named `venv` in your current directory.
> 3. **Activate the virtual environment**:
>    Before installing any packages, you need to activate the virtual environment. For Windows PowerShell, use the following command:
>    ```powershell
>    ./venv/Scripts/Activate.ps1
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    You should now see `(venv)` at the beginning of your terminal prompt, indicating that the virtual environment is active.
> 4. **Install `llama-index` within the virtual environment**:
>    Finally, with the virtual environment activated, install `llama-index` by running:
>    ```powershell
>    pip install llama-index
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    This will install `llama-index` and its dependencies in the isolated environment, avoiding any conflicts with globally installed packages.
> 
> By following these steps, you should be able to successfully install and use `llama-index` on your Windows system. If you encounter any issues during this process, please feel free to reach out for further assistance.
> 
> Best, [Dosu](https://dosu.dev)
> 
> #### About Dosu

after using "python -m venv" to create a new venv, i installed it with "pip install --no-cache-dir llama-index". but the problem is still same. 

(llamaindex2) (base) C:\Users>python
Python 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama_index as li
>>> dir(li)
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
>>>

**Comment by junxu-ai** [comment]
does the setup.py include all the components?

**Comment by logan-markewich** [comment]
I don't really see what the problem is actually, or what you are looking for? You can't import anything? Or?

The `llama-index` package isnt a real package, but just a wrapper around several starter packages like `llama-index-core`, `llama-index-llms-openai`, etc.

These are all namepsaced python packages, which is why you have imports like `from llama_index.core import VectorStoreIndex` and `from llama_index.llms.openai import OpenAI`

There is no setup.py. it's all just `project.toml` based.

You can see llama-index-core here
https://github.com/run-llama/llama_index/tree/main/llama-index-core

And llama-index-llms-openai here
https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/llms/llama-index-llms-openai

**Comment by logan-markewich** [comment]
Going to close this for now. Clarifying once again `llama-index` isn't really a package on its own, but a wrapper on several sub-packages `llama_index.core` and` llama_index.llms.openai` for example
