### ISSUE TITLE
Streaming with output_cls pydantic in query engine

### ISSUE THREAD

**Issue by teis-e** [run-llama/llama_index#12619]
### Bug Description

Using output_cls + streaming doesn’t work on an query engine, is this a bug or isn’t it suppose to. It just gives a normal output like output_cls isn’t provided, no warning or anything.

### Version

0.10.27

### Steps to Reproduce

Create a queryengine with output_cls=basemod, streaming=True

**Comment by logan-markewich** [comment]
@teis-e it works fine for me, but pydantic can be wonky either v1 and v2.

Use `from pydantic.v1 import BaseModel` imports, or `from llama_index.core.bridge.pydantic import BaseModel` which does that for you
