### ISSUE TITLE
[Bug]: Truncate method for too many nodes drops info dramatically 

### ISSUE THREAD

**Issue by qiisziilbash** [run-llama/llama_index#12613]
### Bug Description

When using a query engine with a `response_synthesizer` of `simple_summarize` response mode with too many nodes, [truncate method ](https://github.com/run-llama/llama_index/blob/2254bb5df37daffd10b25a75f8fae378ef12533b/llama-index-core/llama_index/core/indices/prompt_helper.py#L261) truncates each node to very few tokens that theoretically no info is preserved (and if number of nodes are sufficiently big enough it crashes due to negative chunk size).

A better behavior would be reducing number of nodes that chunks can fit into the context window or combination of this and existing behavior. ****

### Version

latest

### Steps to Reproduce

make a query engine using an index that has sufficiently big enough chunks and ask a question
```python
similarity_top_k = a very big number
index.as_query_engine(
        similarity_top_k=similarity_top_k,
        response_synthesizer=get_response_synthesizer(
            response_mode="simple_summarize",
        ),
    )
```

**Comment by logan-markewich** [comment]
@qiisziilbash this module is called simple summarize because its very simple :)

If you need to summarize across variable number of nodes, I recommend using tree summarize

**Comment by qiisziilbash** [comment]
totally understand; would not truncating the chunks list be simpler tho :D ?

**Comment by logan-markewich** [comment]
@qiisziilbash probably these two steps should just be swapped in the code

```
truncated_chunks = self._service_context.prompt_helper.truncate(
            prompt=text_qa_template,
            text_chunks=text_chunks,
        )
node_text = "\n".join(truncated_chunks)
```

Merge first, then truncate

**Comment by qiisziilbash** [comment]
agreed

**Comment by scriptator** [comment]
I agree that it makes more sense to merge first and then truncate, but the merged solution introduced another problem: `truncated_chunks` now contains a list with a single string in it instead of just the string, so when you pass that on to the LLM class the `context_str` gets formatted like this `['{truncated_str}']`.
