### ISSUE TITLE
[Bug]: llama-index-llms-anthropic and llama-index-multi-modal-llms-anthropic dependency conflict

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#12631]
### Bug Description

llama-index-llms-anthropic and llama-index-multi-modal-llms-anthropic have depend on different anthropic packages and this raises a pip Error.

### Version

llama-index-core (0.10.27); llama-index-llms-anthropic(0.1.9); llama-index-multi-modal-llms-anthropic (0.1.3)

### Steps to Reproduce

Try upgrading the llama-index-llms-anthropic package to the latest version and upgrading llama-index-multi-modal-llms-anthropic package to the latest version as well.

### Relevant Logs/Tracbacks

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llama-index-llms-anthropic 0.1.9 requires anthropic<0.24.0,>=0.23.1, but you have anthropic 0.20.0 which is incompatible.


ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llama-index-multi-modal-llms-anthropic 0.1.3 requires anthropic==0.20.0, but you have anthropic 0.23.1 which is incompatible.
```

**Comment by logan-markewich** [comment]
I can update this dependency, but seems like the multi-modal anthropic class doesn't have any `chat()` methods implemented, leaving that for a future PR
