### ISSUE TITLE
[Question]: exclude auto-generated code from pre-commit

### ISSUE THREAD

**Issue by ossaleon** [run-llama/llama_index#12648]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am contributing the WordLift Vector Store. The Vector Store uses a client generated using an openapi.yaml file and the OpenAPI Client Generator Tool.
The code generated from the Client Generator Tool doesn’t pass however the formatting/linting. I was looking at different solutions:
1. Solution A: exclude the generated client folder from pre-commit, but without changing pre-commit-config.yaml.
2. Solution B: exclude the generated client folder adding to our pyproject.yaml an exclude option for each hook. 

I wasn’t able to apply solution A so I will proceed with solution B, but I was wondering if it would be acceptable and whether there’s a better way of doing it?

**Comment by logan-markewich** [comment]
@ossaleon I would just exclude it in the .pre-commit-config.yaml, nothing wrong with modifying that 👍🏻
