### ISSUE TITLE
[Bug]: can elasticsearchstore accept https url and a pem ssl certificate?

### ISSUE THREAD

**Issue by haolx** [run-llama/llama_index#12656]
### Bug Description

from elasticsearch import Elasticsearch
from llama_index.vector_stores.elasticsearch import ElasticsearchStore

url = "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
username = xxxxxxxxxxxxxxxxxx
password = xxxxxxxxxxxxxxxxxx

# Create a custom Elasticsearch client
es_client = Elasticsearch(
    [url],
    http_auth=(username, password),
    verify_certs=True,
    ca_certs='./cert.pem',
    # any other configuration options
)

# Pass the custom client to ElasticsearchStore
es = ElasticsearchStore(
    index_name='xxxxxxxxxxxxxxx',
    es_client=es_client,
)

ImportError: cannot import name 'DEFAULT_PERSIST_FNAME' from partially initialized module 'llama_index.core.vector_stores.simple' (most likely due to a circular import) (/home/jovyan/.local/lib/python3.10/site-packages/llama_index/core/vector_stores/simple.py)

### Version

tried both 0.9.13 and 0.10.27 

### Steps to Reproduce

can elasticsearchstore accept https url and a pem ssl certificate? Thanks!

from elasticsearch import Elasticsearch
from llama_index.vector_stores.elasticsearch import ElasticsearchStore

url = "https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
username = xxxxxxxxxxxxxxxxxx
password = xxxxxxxxxxxxxxxxxx

# Create a custom Elasticsearch client
es_client = Elasticsearch(
    [url],
    http_auth=(username, password),
    verify_certs=True,
    ca_certs='./cert.pem',
    # any other configuration options
)

# Pass the custom client to ElasticsearchStore
es = ElasticsearchStore(
    index_name='xxxxxxxxxxxxxxx',
    es_client=es_client,
)

**Comment by haolxx** [comment]
it worked. please close
