### ISSUE TITLE
[Question]: How to force "Answer" to be the same as "Observation"?(prompt does not work) 

### ISSUE THREAD

**Issue by lchustc** [run-llama/llama_index#12671]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

<img width="814" alt="image" src="https://github.com/run-llama/llama_index/assets/27990344/35e54290-21bd-4cf8-a61e-410d7fe8108b">

I want the "Answer" to be the same as the （last）"Observation".

**Comment by lchustc** [comment]
Doesn't work, I hope the Answer is the same as the tool obeservation. These include functions and QA tools

**Comment by logan-markewich** [comment]
Hate to say it, but this is fundamental to how agents work, prompting is really the only way....

However, I just merged a fix into main that will be in the next release

```
tool = FunctionTool.from_defaults(...., return_direct=True)
```

You can declare tools as return_direct -- but be aware, this has limitations!
- If a tool with `return_direct` is used, it will end the loop (no more tool calls)
- If more than one tool is invoked (this really only applies to function calling/openai agents), then return_direct is ignored
