### ISSUE TITLE
[Question]: LF self-hosted VectorStore that supports BM25

### ISSUE THREAD

**Issue by juleskuehn** [run-llama/llama_index#12679]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

(I cannot use Discord at work)

After trying quite a few options, I have yet to find a LlamaIndex VectorStore that is self-hosted (Docker OK), supports BM25 search and filtering.

Am I missing something here?

### Postgres
Has text search, but no BM25.

### ParadeDB
Adds BM25 to Postgres, but the PGVectorStore class needs to be overhauled to support the BM25 functionality.

### Weaviate
This *should* work but the implementation is broken right now; this `v3 -> v4` situation is not helping matters, but I simply couldn't get it to work at all, following the LlamaIndex examples and Weaviate docs. I had high hopes this one would work!

### Qdrant
Has SPLADE, but it is very slow compared to BM25 (when running self-hosted with CPU) and also, VectorStore filters don't work properly. Qdrant devs don't seem enthused about providing BM25 support, from what I read on Hacker News.

### Milvus
Supports BM25, but the VectorStore class doesn't. Only equality filters implemented in VectorStore.

---

**Can anyone recommend a LlamaIndex VectorStore that can do BM25 and vector search with at least SOME\* filtering?**

*_Filtering from a subset of documents would be a good start, and I think most support this albeit with different interfaces... but I do also need `>=`, `<=` eventually._

**Comment by logan-markewich** [comment]
@juleskuehn isn't this weaviate?

**Comment by logan-markewich** [comment]
Oh you mentioned it

**Comment by logan-markewich** [comment]
I would use weaviate v3 until that integration gets migrated? Tbh this is the one I would recommend

**Comment by logan-markewich** [comment]
Either that, or feel free to make a PR to make this work in other vector dbs like milvus. Optionally you can run the Bm25 algorithm yourself and store sparse vectors in qdrant or pinecone. 

Downside with BM25 is that when anything is inserted, all sparse embedding have to be recalculated for the entire index (so BM25 is not great in general if you are expecting to insert new data frequently, or have large indexes)

**Comment by juleskuehn** [comment]
> I would use weaviate v3 until that integration gets migrated? Tbh this is the one I would recommend

Thanks for the reply Logan. I thought this was the case, but I just kept hitting error after error trying to follow the documentation. Problems I couldn't solve by looking at Weaviate docs either. Like, how do you tell it what specific OpenAI embedding to use (i.e. large)? Unclear, but it's failing without it.

Ultimately these are more complaints about Weaviate than LlamaIndex, I just hoped that one of the other (many) VectorStore implementations would check all these boxes without requiring a deep dive...

**Comment by logan-markewich** [comment]
@juleskuehn you can use any embedding model 😅 But you have to make sure that you use the same embedding model for indexing and querying

The example notebook runs fine for me 

https://docs.llamaindex.ai/en/stable/examples/vector_stores/WeaviateIndexDemo-Hybrid/?h=weaviate

Curious what error you are hitting, and what your code looks like

**Comment by juleskuehn** [comment]
> @juleskuehn you can use any embedding model 😅 But you have to make sure that you use the same embedding model for indexing and querying
> 
> The example notebook runs fine for me
> 
> https://docs.llamaindex.ai/en/stable/examples/vector_stores/WeaviateIndexDemo-Hybrid/?h=weaviate
> 
> Curious what error you are hitting, and what your code looks like

I'm taking a look at modifying `create_default_schema` with some additional `moduleConfig` to see if that does the trick, ala https://medium.com/@yus_erdo/weaviate-setup-on-azure-openai-1e113ccc6bed

```python
# vector_stores/weaviate/utils.py

def create_default_schema(client: Any, class_name: str) -> None:
    """Create default schema."""
    validate_client(client)
    class_schema = {
        "class": class_name,
        "description": f"Class for {class_name}",
        "properties": NODE_SCHEMA,
    }
    client.schema.create_class(class_schema)
```

**Comment by logan-markewich** [comment]
oh boy, the schema is one of the more (annoying?) parts of weaviate lol. LlamaIndex kind of hardcodes it (unless you take that hardcoded default, and modify, which I think you are doing?)

I'll have to try and take a look at doing that

**Comment by juleskuehn** [comment]
I ended up solving the Weaviate problem! It just required specifying the embedding model explicitly:

```python
def get_vector_index(library):
    vector_store = WeaviateVectorStore(
        weaviate_client=client, index_name=library.capitalize()
    )
    index = VectorStoreIndex.from_vector_store(
        vector_store, embed_model=embed_model
    )
    return index
```

After this, I had no problems using the same interfaces such as `insert_nodes` and querying. No need to mess with the schema.

This was a bit different from what I had for Postgres, which didn't require specifying the embedding:
```python
def get_vector_index(library):
    # Perform setup is non-destructive (only creates tables if they don't exist)
    vector_store = PGVectorStore.from_params(
        database=DB_NAME,
        host=url.host,
        password=url.password,
        port=url.port,
        user=url.username,
        table_name=library,
        embed_dim=1024,
        perform_setup=True,
        hybrid_search=True,
        text_search_config="english",
        debug=False,
        use_jsonb=True,
    )

    storage_context = StorageContext.from_defaults(
        vector_store=vector_store,
    )

    return VectorStoreIndex.from_vector_store(
        vector_store=vector_store, storage_context=storage_context
    )
```

Anyway, its working now - will likely require some tweaks to the filters code, but I'm pleased. Thanks for confirming that the basic use case in the notebook indeed works - that gave me the encouragement to keep fiddling with it. :)
