### ISSUE TITLE
[Question]: How to save a text node and then load it up again?

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12689]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have text nodes in the format - 
TextNode(id_='node_0', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='97a68807-c87d-4332-b23e-833aa75d204c', node_type=<ObjectType.DOCUMENT: '4'>, metadata={}, hash='f54321c2afdcd2bd45d2b9c8324fcc6d4d6d75c78b07be6c35679b66efd0aa38'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='6d3af5ce-1039-4542-bc34-3d9f697ac160', node_type=<ObjectType.TEXT: '1'>, metadata={}, hash='47b028b14677a7f280b425bae9a305f91526c8652123e2d26ea38c48c70be0bf')}, text="blah blah blah.\n\n", start_char_idx=0, end_char_idx=5867, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n')
How can i save this and then use this in another file?

Please help, thanks

**Comment by logan-markewich** [comment]
@JINO-ROHIT 

```
json_str = node.json()

node = TextNode.parse_raw(json_str)
```

**Comment by JINO-ROHIT** [comment]
@logan-markewich thanks, and for a list of text nodes? can i save it as some file name and then read it into another py script

**Comment by logan-markewich** [comment]
Just make a list of json node strings, and read/write to a file 👍🏻 

```
for json_str in json_strs
  f.write(json_str + "\n")
```

**Comment by JINO-ROHIT** [comment]
thanks so much!
