### ISSUE TITLE
[Bug]: Error: NotFoundError - Resource not found while implementing llama index with Azure OpenAI for fine-tuning

### ISSUE THREAD

**Issue by loyal812** [run-llama/llama_index#12685]
### Bug Description

During the implementation of the llama index with Azure OpenAI for fine-tuning, the following error occurred:

```
Retrying llama_index.llms.openai.base.OpenAI._chat in 0.6394267984578837 seconds as it raised NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}.
```

### Version

0.10.22

### Steps to Reproduce

**Code snippet:**
```python
# Perform query to retrieve the contexts and answers for the generated questions

self.llm = OpenAI(
    api_base=self.azure_openai_endpoint,
    api_key=self.azure_openai_api_key,
    api_version=self.azure_openai_api_version,
    model=self.model,
    temperature=self.temperature
)

query_engine = index.as_query_engine(similarity_top_k=2, llm=self.llm)
```

**Additional Information:**
The error seems to be related to a `NotFound` error with code 404 indicating that the requested resource was not found. 

**Problem Statement:**
The issue occurs while trying to execute the query using Azure OpenAI. The error message suggests that the resource being requested is not found.

**Solution Required:**
Please provide guidance on how to resolve this issue as I am unsure how to proceed.

**Comment by loyal812** [comment]
@dosu-bot

I've already successfully generated training and evaluation data using Azure openai, but I'm getting an error when I try to use the query engine. Could you please review this again?

**Comment by logan-markewich** [comment]
@loyal812 please double check that you've specified the correct model name that you've deployed.

Here's an example that works for me

```
from llama_index.llms.azure_openai import AzureOpenAI

aoai_api_key = "YOUR_AZURE_OPENAI_API_KEY"
aoai_endpoint = "YOUR_AZURE_OPENAI_ENDPOINT"
aoai_api_version = "2023-07-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="YOUR_AZURE_OPENAI_COMPLETION_DEPLOYMENT_NAME",
    api_key=aoai_api_key,
    azure_endpoint=aoai_endpoint,
    api_version=aoai_api_version,
)
```
