### ISSUE TITLE
[Question]:  PandasQueryEngine with open source LLM's 

### ISSUE THREAD

**Issue by amygbAI** [run-llama/llama_index#12692]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

pfb the code 
`
import torch
from transformers import BitsAndBytesConfig
from llama_index.core.prompts import PromptTemplate
from llama_index.llms.huggingface import HuggingFaceLLM

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

llama2llm = HuggingFaceLLM(
    model_name="meta-llama/Llama-2-7b-chat-hf",
    tokenizer_name="meta-llama/Llama-2-7b-chat-hf",
    context_window=3900,
    model_kwargs={"quantization_config": quantization_config},
    #tokenizer_kwargs={"token": hf_token},
    device_map="auto",
)

import pandas as pd
from llama_index.core.query_engine import PandasQueryEngine

df = pd.DataFrame( {
    'Item': ['water bottle', 'snack box', 'diapers'],
    'Quantity': [2, 3, 4],
    'Price': [30, 40, 50],
    'Total Amount': [60, 120, 200]
} )
query_engine = PandasQueryEngine(df=df, llm=llama2llm, verbose=True)

response = query_engine.query(
    "please give me the name of the item which has the least quantity and price ?",
)
prompts = query_engine.get_prompts()
print(prompts["pandas_prompt"].template)
print(f"{response}")

`
# Notes
i have tried Mistral-7B and llama2-7b ..all of them have serious issues with what i consider a critical component for enterprises. What most folks probably dont realize is that a TON of documents ( which have a lot of **tabular information** ) and **spreadsheets** present in shared folders of companies can ONLY be **"LLM"ized** by converting into a dataframe ( and bigger sets will need to go into the DB ) .. the sad truth is that this particular engine ONLY works with GPT and not the major open source LLM's. 

I do understand that llama index has no responsibility whatsoever on this front but has someone benchmarked the major engines with something like llama2 ? not all of us would want to pump our data into paid LLMs and more importantly , in some cases, our smaller finetuned models are BETTER than GPT4 on narrow tasks. If there are any pointers , i would be really grateful. Here are some of the answers the above code gave me

PS - please forgive the formatting for the below 

QUERY -  give me the name of the item has the max qty?

> Pandas Instructions:
df['Total Amount'].max()['Description']
Explanation:

* `df['Total Amount'].max()` returns the maximum value in the 'Total Amount' column of the dataframe.
* `['Description']` returns the corresponding column name of the maximum value.

Note: The `['Description']` part is optional, if you want to get the name of the column that corresponds to the maximum value, you can simply use `['Description']`.

*** wrong df query 

QUERY -  "which item has the lowest price?"

> Pandas Instructions:
`print(df['Price'].min())`
30
> Pandas Output: None

*** answers only a part of the query 

QUERY - "please give me the name of the item which has the least quantity and price ?"

> Pandas Instructions:
least_item = df['Quantity'].min()[df['Price'].min()]
print(least_item)

*** wrong df query

**Comment by amygbAI** [comment]
the above was a terrible summary by the bot .. i know for a fact that the problem is NOT with the query engine ..its the LLM's which keep throwing random stuff the engine's way ( coz the engine is simply creating custom templates for different tasks and handing it over to the LLM )

**Comment by logan-markewich** [comment]
@amygbAI open-source LLMs are, in general, terrible with structured outputs. Add complex reasoning on top of that, and its not going to be a fun time. 

You mentioned Llama2, which is my experience is one of the worst offenders.

Newer models are maybe getting better (command-r, codellama, etc.), but not really reliable for this task without finetuning

**Comment by logan-markewich** [comment]
Anthropic, gemini, openai, mistral-large, etc. all work pretty well though. Of course, those are hosted models

**Comment by amygbAI** [comment]
Thank you for your response 😊..agreed ..just that getting any URL
whitelisted ( for access to hosted models ) via any reasonably sized
company's infosec team is a bureaucratic nightmare ..I'm hoping llama3
release might help ..if I do manage to fine-tune this for llama2 though, I
shall add details to this thread

**Comment by uzairlatif90** [comment]
Hello @amygbAI ! I am currently dealing with the same problem. I also found this [langchain function](https://python.langchain.com/v0.1/docs/integrations/toolkits/pandas/) but it has the same problem that it only works with GPT LLMs. I am thinking of using of the [Llama 3 LLM](https://huggingface.co/NousResearch/Meta-Llama-3-8B-Instruct-GGUF) locally. Were you able to find a solution to your problems?

**Comment by amygbAI** [comment]
Hi @uzairlatif90 i did exactly what you are/were thinking of doing. Just deployed Llama3 ( instruct-8B ) ..now im working on quantizing it via llama cpp ..but llama3 is still a ways behind gpt4 so i am building a scaffolding framework around double checking its output. Basically have a set of pre defined query responses and see how the output compares. In my case it was ~80-85% accurate.

**Comment by uzairlatif90** [comment]
Thank you so much for your reply @amygbAI ! Would you be able to share a snippet from your code on how exactly you deployed the Llama3 (instruct-8B) to analyse the dataframe with llamacpp. I have been struggling with that and I would be really grateful for your help.

**Comment by amygbAI** [comment]
@uzairlatif90 the llama cpp thing is a WIP :) ..like i mentioned in my comment, i am still working on it .. once im able to get it up and running i will most certainly share it here

**Comment by amygbAI** [comment]
@uzairlatif90 it was really simple in the end .. install ollama https://github.com/ollama/ollama/tree/main and ```ollama pull llama3:instruct``` and start their server using ```ollama serve``` ..ideally it starts by default ..then you can create your own API using a simple python requests like so
```
url = "http://localhost:11434/api/generate"
data = {
        "model": "llama3:instruct",
    "prompt": '''In the following code below extract the global variables and method definitions. Restrict answer to 2 lists. One with list of variables and the other with list of method definitions.\n govt_id_sync_dict = dict({"drivinglicence" : "DL",
                          "voterid" : "Voter ID",
                          "passport" : "Passport",
                          "aadhaar" : "Aadhaar",
                          "pan" : "PAN"})

def get_num_pages(pdf_path):
    # Get num of pages '''
}

```
the only thing is the response comes out in the form of individual tokens so you will need to process it but otherwise, quality wise there's a small degradation ( since this is a 4.7 GB quantized version of the 8B instruct model ) BUT still much much better than llama2 and almost as good as gpt3.5 
once u have this wrapper, instead of calling the pandasqueryengine you can call this straightaway
