### ISSUE TITLE
[Question]: I keep having issues when a react agent tries to use a tool

### ISSUE THREAD

**Issue by brainiakk** [run-llama/llama_index#12699]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The question I asked it is "What's today's date"

I already created a simple function tool to answer this correctly to eliminate hallucination:
```
    def current_date(self) -> str:
        """
        Get current date
        
        args:
            None
        """
        return datetime.today().strftime('%B %d, %Y')
```
This is the output when I call `agent.chat(...)`:
```
  Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
  Thought: The current language of the user is: English. I need to use a tool to help me answer the question.
  Action: current_date
  Action Input: {'type': 'object', 'properties': AttributedDict()}
  Observation: Error: current_date() got an unexpected keyword argument 'type'
  Thought: The current language of the user is: English. I need to use a tool to help me answer the question.
  Action: current_date
  Action Input: {'type': 'object'}
  Observation: Error: current_date() got an unexpected keyword argument 'type'
  Thought: The current language of the user is: English. I need to use a tool to help me answer the question.
  Action: current_date
  Action Input: {}
  Observation: April 10, 2024
  Thought: Now that we know the current date, let's find out what day of the week it is.
  Action: current_date
  Action Input: {'type': 'object'}
  Observation: Error: current_date() got an unexpected keyword argument 'type'
  Thought: The current language of the user is: English. I need to use a tool to help me answer the question.
  Action: current_date
  Action Input: {}
  Observation: April 10, 2024
  Thought: Now that we know the current date, let's find out what day of the week it is.
  Action: query_tool
  Action Input: {'input': "What day is 'April 10, 2024'?"}
```

As you can see, sometimes it gets it, and sometimes it get's this:
```
  Action Input: {'type': 'object'}
  Observation: Error: current_date() got an unexpected keyword argument 'type'
```
it's always unstable, and sometimes it just hallucinates till it chooses the wrong tool and other times it get's to max iterations after running for a while.

Is there something I'm missing, or is this just a bug, also how can I fix it.

**Comment by logan-markewich** [comment]
@brainiakk ReAct agents require an LLM to follow pretty careful instructions. Most LLMs (especially open source) are pretty bad at this. Its nothing wrong with any code, just the fact that the LLM you are using isn't capable enough to perform this type of action reliably

**Comment by brainiakk** [comment]
> ```python
> , **kwargs
> ```

I'm using dolphin-mistral, what would you recommend?

**Comment by brainiakk** [comment]
Also, even if I set max_iterations and it returns the right output, it just throws an error, do I need to change anything?
` agent = ReActAgent.from_tools(tools, llm=Settings.llm, verbose=True, context=self._prompt, max_iterations=2)`

**Comment by AdaptavistChak** [comment]
@logan-markewich I'm having some similar error messages as @brainiakk where it sometimes outputs:

`Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.`

Is this also down to the LLM choice? I've set a system prompt and am using Llama2 and it seems like the big versions of Llama2 are better at following instructions. But it feels weird to me since that error should throw an exception rather than be rolled into the LLM thought/observation process. When I see this message it just continues like nothing happened, sometimes have the same error multiple times in a row:

`Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.`

**Comment by brainiakk** [comment]
I also got the same 
`Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.`

**Comment by AdaptavistChak** [comment]
So what fixed it for me was installing pytorch after everything else.

I'm using Pipfiles which resolves all the dependencies and I install all the packages using that first. But to not have the above error, I need to activate the virtual environment and do a manual pip install.

My steps are:
pipenv install
pipenv shell
pip install torch==2.2.1

I haven't tested if it works for 2.2.2 of pytorch and I'm unsure why this works and how it affects things but hopefully there's a clue somewhere. Maybe it's one of the dependency changes when I throw torch into my Pipfile.

**Comment by AdaptavistChak** [comment]
Another thing I found is that having a reader package installed will cause the same problem. I'm using llama-index-readers-confluence and regardless of the version of that or pytorch I have, it results in the same issue with the error being part of the observation

**Comment by kiruz-0** [comment]
> Same issue. Most of the time it hallucinates and starts calling other tools even though the first tool has returned the answer which is required. Any help regarding modification of the reAct system prompt as i'm using custom functions in llama3 7b via ollama.

I'm struggling with this too and have same experience. Sometimes it answers but still tries to run another tool, which end up in a loop (Nano Mistral). Or is trying to use wrong params etc. I'm not really sure how it all corelates with model. Is it template issue, system params, parsing?
I can only tell that gemma2:9b is not bad for this. Sometimes it goes off rails. But if you can run 27b model, then go with it. It uses proper tools, answers based on it and uses proper params almost 0-shot (9b needs few tries).

**Comment by CashVo** [comment]
I am running into this error too. I am using Llama 3.2-1b-instruct from HuggingFace (free tier) ...  Things were going great but now it's stuck here on every prompt. Did I just hit a limit with this model on HF?

**Comment by anushalihala** [comment]
I've noticed this happens when an ObservationReasoningStep follows another ObservatioReasoningStep instead of an ActionReasoningStep. Could this be a bug?

**Comment by aybakana** [comment]
I changed the model that I use and it fixed the problem for me.

**Comment by ELhadratiOth** [comment]
@JoseGHdz  did u found  any  solution for  that  ? i am struggling with it  too

**Comment by JoseGHdz** [comment]
> [@JoseGHdz](https://github.com/JoseGHdz) did u found any solution for that ? i am struggling with it too

What I did was truncate the output to only the important content I want. If you have too much content in the action stage, once it reaches the observation stage it's going to struggle and begin hallucinating which then gives out this error.

**Comment by ELhadratiOth** [comment]
@JoseGHdz  i changed the OutputReActParser to :
        ``` python 
            if "Thought:" not in output:
            # NOTE: handle the case where the agent directly outputs the answer
            # instead of following the thought-answer format
            # return ResponseReasoningStep(
            #     thought="(Implicit) I can answer without any more tools!",
            #     response=output,
            #     is_streaming=is_streaming,
            # )
            return parse_action_reasoning_step(output)
    ```

but  i got this new error : Observation: Error: Could not parse output. Please follow the thought-action-input format. Try again.
and after some  iterations it respond to  the  user Query.
do u have  any  idea to resolve this

**Comment by Jyothikumar-b** [comment]
I used llama3.1, this gives better output.

**Comment by Carlosgoncalves00** [comment]
Just like @logan-markewich said, ReAct framework needs a language model that follows careful instructions!

However, there are a few things you could try, such as creating, updating, or removing (which reverts to the default) the LM chat template. Based on my experience, this affects the outcome and the generation time.

**Comment by nagarciah** [comment]
This might help: https://github.com/run-llama/llama_index/pull/18818
