### ISSUE TITLE
Embedding getting saved as "number" datatype in Elastic Search Store, instead of "dense_vector". What can be the reason behind it?

### ISSUE THREAD

**Issue by Subham0793** [run-llama/llama_index#12698]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Following is the code snippet i am using for indexing data into Elastic Store

`
from llama_index.vector_stores.elasticsearch import ElasticsearchStore
from llama_index.core import (
    VectorStoreIndex,
    ServiceContext,
    StorageContext,
    Settings
)

self.node_parser = SentenceWindowNodeParser.from_defaults(
            window_size=3,
            window_metadata_key="window",
            original_text_metadata_key="original_text",
 )

self.service_context = ServiceContext.from_defaults(
    llm=None,
    embed_model=self.embedding, # azure open ai embedding of 512 dimensions
)        
self.document_store = ElasticsearchStore(
    es_url=self.elasticsearch_url,
    index_name=index_id,
)
self.storage_context = StorageContext.from_defaults(
    vector_store=self.document_store,
)

self.index = VectorStoreIndex.from_vector_store(
    vector_store=self.document_store,
    storage_context=self.storage_context,
    service_context=self.service_context,
)

sentence_nodes = self.node_parser.get_nodes_from_documents(docs) # docs is of List[Document] type

self.index = VectorStoreIndex(
    sentence_nodes,
    service_context=self.service_context,
    storage_context=self.storage_context
)

`

When i am indexing the data, its taking embedding field as **number** data type. Because of this I am unable to perform the retrieve operation as it is expecting a **dense vector** field.

What can be the reason that after indexing, the embedding field is getting saved as **number** datatype ?

**Comment by logan-markewich** [comment]
No idea. Feel free to make a PR if the code can be improved
https://github.com/run-llama/llama_index/blob/32e3c1f6f3acd28ec48b868568d3337b783e56d7/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py#L355
