### ISSUE TITLE
[Question]: JSON _metadata._node_content duplicates twice the metadata?

### ISSUE THREAD

**Issue by benbenz** [run-llama/llama_index#12696]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I've noticed that the nodes entries inserted in the vector store database are copying the metadata in _node_content. Am I doing something wrong ?
The `_metadata._node_content` of the entries seems to have the metadata repeated twice in there... 
This seems this could potentially cause some unneeded loss of disk space and performance.

**Comment by benbenz** [comment]
This seems to be a duplicate from [this](https://github.com/run-llama/llama_index/issues/10967).
It would be great if this could be solved.

**Comment by logan-markewich** [comment]
@benbenz nothing wrong, `_node_content` is just the entire node serialized. Maybe the process could be improved, but thats just how it works right now

**Comment by logan-markewich** [comment]
Some metadata is moved to the top level in some vector db integrations so that it is filterable/searchable. Other vector dbs can filter/search directly on the node content field

**Comment by benbenz** [comment]
Great. Thank you for your answer :)

**Comment by meninder** [comment]
Yes, thank you Logan.  I have the same issue.  Doing it this way creates multiples in the size of each node (carrying a lot of metadata) which becomes prohibitive when using this at scale.  Ive used redis, lance, chrome and other dbs, haven't found the use case where this is useful.  Is there a simple way to "turn it off"?

**Comment by logan-markewich** [comment]
@meninder can't really turn it off -- its using the serialized node to reconstruct the node at retrieval time. Without it, you get no node

**Comment by meninder** [comment]
interesting.  thank you
