### ISSUE TITLE
[Question]: Multiple Index for one doc OR query with multiple indices 

### ISSUE THREAD

**Issue by Daniel-Xiong** [run-llama/llama_index#12694]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I am trying to build multiple index for one node to improve the retrieval performance.
For example, one vector for title, one for node content, one for meta-data.
This will create three vectors for one node, is it any way I can achieve that?

The other way I can think of is to Create a Query with multiple indices, but still don't know how to achieve that.

Thank you!

**Comment by logan-markewich** [comment]
You'd have to create thee nodes in this case (one for each embedding). Which would be 3 indexes yes.

You could combine them using a query fusion retriever for example
https://docs.llamaindex.ai/en/stable/examples/retrievers/relative_score_dist_fusion/?h=queryfusion
