### ISSUE TITLE
[Feature Request]: support for gpt-4-turbo in multi_modal_llms

### ISSUE THREAD

**Issue by mphipps2** [run-llama/llama_index#12708]
### Feature Description

OpenAI took GPT-4V out of preview mode and it's available now through 'gpt-4-turbo'. This needs updated in multi_modal_llms/openai/utils.py.

This new release finally allows function calling and json mode with gpt-4v, so would be great to add these too.

[https://platform.openai.com/docs/models/continuous-model-upgrades](https://platform.openai.com/docs/models/continuous-model-upgrades)

### Reason

OpenAI update

**Comment by logan-markewich** [comment]
@mphipps2 it's already there-- `pip install -U llama-index-multi-modal-llms-openai`

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/blob/3553f56f7698ddd65a1e693f4ceb0ba70fd67a25/llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms-openai/llama_index/multi_modal_llms/openai/utils.py#L15
