### ISSUE TITLE
[Question]: How to create a retriever from pgvector store 

### ISSUE THREAD

**Issue by MNLubov** [run-llama/llama_index#12707]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am manually insert data into Postgres using pgvector. For that I used Ingestion pipeline and direct writing to SQL using SQL query. 
Now, as I have vector store, I want to connect to it and retirever most relevant chuncks of documents. 
However when I do the following, I always get an empty response:
```
       vector_store = PGVectorStore.from_params(
          database="fragments",
          host="localhost",
          password="admin",
          port=5432,
          user="postgres",
          table_name="vector_store",
          embed_dim=1536,  
      )
      embedding_model = OpenAIEmbedding(api_key = openai_api_key)
      index = VectorStoreIndex.from_vector_store(vector_store=vector_store, embed_model=embedding_model)
      retriever = VectorIndexRetriever(index=index, similarity_top_k=10,)
      response = retriever.retrive("What is a sun?")
      print(response)
```

        How to fix it?

**Comment by logan-markewich** [comment]
@MNLubov hard to say -- did you insert the data using llama-index? You are sure the DB details are correct?

What If you try ingesting one more node? 

```
from llama_index.core.schema import TextNode

node = TextNode(text="test node")

index.insert_nodes([node])
```

**Comment by MNLubov** [comment]
> @MNLubov hard to say -- did you insert the data using llama-index? You are sure the DB details are correct?
> 
> What If you try ingesting one more node?
> 
> ```
> from llama_index.core.schema import TextNode
> 
> node = TextNode(text="test node")
> 
> index.insert_nodes([node])
> ```

I found out that I didn't create `node_id` column in my table. So, without node_id column, it's impossible to retriever embeddings?

**Comment by MNLubov** [comment]
> Yes, the absence of a `node_id` column in your table would indeed prevent you from retrieving embeddings. In the LlamaIndex system, the `node_id` serves as a crucial identifier for each node, mapping them to their respective embeddings. This is evident from the LlamaIndex codebase, particularly in methods related to retrieval and insertion of nodes, where `node_id` is explicitly required for operations to function correctly.
> 
> The `node_id` column is expected to be a string and must be unique for each node. This uniqueness is typically ensured by using UUIDs (Universally Unique Identifiers), which can be generated in Python using `uuid.uuid4()`. This approach guarantees that each `node_id` is unique across the database, facilitating the accurate retrieval of embeddings based on these identifiers.
> 
> To resolve your issue, you should add a `node_id` column to your `vector_store` table, ensuring it is of type string (or an equivalent type that can store UUIDs) and that each entry is unique. After adjusting your database schema to include this column and populating it with unique identifiers for each node, your retrieval operations should start working as expected.
> 
> If you've already ensured that your `vector_store` table is correctly formatted and that the embeddings are properly stored with matching `embed_dim` parameters, but are still facing issues, it might be helpful to double-check the data and the configuration of your retrieval setup. Make sure that the embeddings stored in the database match the expected format and dimensionality required by your retrieval logic.
> 
> ## Sources
> * [llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/tests/test_postgres.py)
> * [llama-index-core/llama_index/core/indices/vector_store/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/vector_store/base.py)
> * [llama-index-core/llama_index/core/schema.py](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/schema.py)
> 
> #### About Dosu

I've added node_id but it still doesn't retrieve the data. It seems it is a problem in retireval part.

**Comment by logan-markewich** [comment]
@MNLubov its really recommended to create the table/vector store with llama-index.

Feel free to check out the query code though https://github.com/run-llama/llama_index/blob/3553f56f7698ddd65a1e693f4ceb0ba70fd67a25/llama-index-integrations/vector_stores/llama-index-vector-stores-postgres/llama_index/vector_stores/postgres/base.py#L729

If it doesn't follow some exact schema, its probably not going to work
