### ISSUE TITLE
[Question]: Can I use llama-index , but use my custom nodes

### ISSUE THREAD

**Issue by wangpengfei2048** [run-llama/llama_index#12733]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

     I already have docs for chunk-text, like BaseNode in llama-index,  can I use the index related the docs I custom? without the

**Comment by wangpengfei2048** [comment]
But my docs already have independent structure，can I use it reference by llama-index?
Can I use class IndexNode in llama-index,  from the descrition, I think it can meet my needs.
the description with the class: :"Node with reference to any object.

    This can include other indices, query engines, retrievers.

    This can also include other nodes"

**Comment by busaud** [comment]
Can you provide some examples? I am not sure if I am understanding you correctly. Do you inherit BaseNode?
