### ISSUE TITLE
[Question]: Can I use load_indices_from_storage() to load multiple Indices from an external Vector store such as Weaviate

### ISSUE THREAD

**Issue by dfinnert** [run-llama/llama_index#12745]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can I use load_indices_from_storage() to load multiple Indices from an external Vector store such as Weaviate?.
It only seems to work when using the default in-memory vector store.

I tried with:

```
vector_store = WeaviateVectorStore(
    weaviate_client=client
)
storage_context = StorageContext.from_defaults(
    vector_store=vector_store
    )

loaded_indices = load_indices_from_storage(
     storage_context, index_ids=["Index1", "Index2"]
 )  # loads specific indices
```

and get error:
    `ValueError: Failed to load index with ID Index1`

**Comment by logan-markewich** [comment]
@dfinnert nope -- just create the `vector_store` object that points to each of your weaviate indexes, then do

`index = VectorStoreIndex.from_vector_store(vector_store)`
