### ISSUE TITLE
[Bug]: import error in version 0.10.28

### ISSUE THREAD

**Issue by sczlmy** [run-llama/llama_index#12743]
### Bug Description

No module named 'llama_index.postprocessor’
No module named 'llama_index.schema'

### Version

0.10.28

### Steps to Reproduce

from llama_index.indices.postprocessor.flag_embedding_reranker import FlagEmbeddingReranker
from llama_index.schema import NodeWithScore, QueryBundle, TextNode

**Comment by adrian539859** [comment]
Can you try this?
```python
from llama_index.core.schema import NodeWithScore, QueryBundle, TextNode
from llama_index.postprocessor.flag_embedding_reranker import FlagEmbeddingReranker
```

**Comment by sczlmy** [comment]
> Can you try this?
> 
> ```python
> from llama_index.core.schema import NodeWithScore, QueryBundle, TextNode
> from llama_index.postprocessor.flag_embedding_reranker import FlagEmbeddingReranker
> ```

”from llama_index.core.schema import NodeWithScore, QueryBundle, TextNode“，it works。
”from llama_index.postprocessor.flag_embedding_reranker import FlagEmbeddingReranker“， error，No module named 'llama_index.postprocessor'

**Comment by adrian539859** [comment]
Have you installed the required library?
```
pip install llama-index-postprocessor-flag-embedding-reranker
```

**Comment by sczlmy** [comment]
> Have you installed the required library?
> 
> ```
> pip install llama-index-postprocessor-flag-embedding-reranker
> ```

Thanks for "pip install llama-index-postprocessor-flag-embedding-reranker"，I only install with ”pip install llama-index FlagEmbedding“.  The problem has been solved.
I am trying to run the code from https://colemurray.medium.com/enhancing-rag-with-baai-bge-reranker-a-comprehensive-guide-fe994ba9f82a

Howerer，I have a new problem:    

ranked_nodes = reranker._postprocess_nodes(nodes, query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omnisky/.conda/envs/FlagEmbedding/lib/python3.11/site-packages/llama_index/postprocessor/flag_embedding_reranker/base.py", line 73, in _postprocess_nodes
    assert len(scores) == len(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by logan-markewich** [comment]
How many nodes are you passing in? I wonder if it's batching? This is the code
<img width="533" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/90307d42-65f3-4b88-8680-0172b8aa704e">

**Comment by sczlmy** [comment]
> How many nodes are you passing in? I wonder if it's batching? This is the code <img alt="image" width="533" src="https://private-user-images.githubusercontent.com/22285038/321681862-90307d42-65f3-4b88-8680-0172b8aa704e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDgzNTAsIm5iZiI6MTcxMjg0ODA1MCwicGF0aCI6Ii8yMjI4NTAzOC8zMjE2ODE4NjItOTAzMDdkNDItNjVmMy00Yjg4LTg2ODAtMDE3MmI4YWE3MDRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1MDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YmMxMWVjNGIyMzA0ZTdhMDdkNGVhNjBiYzU0ZGEwYWNlMjlhOTUzN2Q4NDJmYWFmYWU5MzBiNDgyMjlmYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YOAUHby_bJY-BRr6phyjAs0SAaoKbRHILAtFmlPvDOk">

My codes refer to (https://colemurray.medium.com/enhancing-rag-with-baai-bge-reranker-a-comprehensive-guide-fe994ba9f82a). It seems 4 nodes.


    from llama_index.core.schema import NodeWithScore, QueryBundle, TextNode
    from llama_index.postprocessor.flag_embedding_reranker import FlagEmbeddingReranker
    reranker = FlagEmbeddingReranker(
        top_n=3,
        model="BAAI/bge-reranker-large",
        use_fp16=False
    )

    documents = [
        "Retrieval-Augmented Generation (RAG) combines retrieval and generation for NLP tasks.",
        "Generative Pre-trained Transformer (GPT) is a language generation model.",
        "RAG uses a retriever to fetch relevant documents and a generator to produce answers.",
        "BERT is a model designed for understanding the context of a word in a sentence."
    ]

    nodes = [NodeWithScore(node=TextNode(text=doc)) for doc in documents]
    print(len(nodes))
    query = "What is RAG in NLP?"
    query_bundle = QueryBundle(query_str=query)
    ranked_nodes = reranker._postprocess_nodes(nodes, query_bundle)

    for node in ranked_nodes:
        print(node.node.get_content(), "-> Score:", node.score)

**Comment by logan-markewich** [comment]
Hmm, that code ran fine for me 😅 

```
(venv) python ./test_flag.py                                                                               
4
Retrieval-Augmented Generation (RAG) combines retrieval and generation for NLP tasks. -> Score: 4.518403053283691
RAG uses a retriever to fetch relevant documents and a generator to produce answers. -> Score: -3.920592784881592
Generative Pre-trained Transformer (GPT) is a language generation model. -> Score: -5.563228130340576
(venv) 
```

Maybe try a fresh venv? 

In a new terminal
```
python -m venv venv
source venv/bin/activate
pip install llama-index llama-index-postprocessor-flag-embedding-reranker 
pip install git+https://github.com/FlagOpen/FlagEmbedding.git
```

**Comment by sczlmy** [comment]
> Hmm, that code ran fine for me 😅
> 
> ```
> (venv) python ./test_flag.py                                                                               
> 4
> Retrieval-Augmented Generation (RAG) combines retrieval and generation for NLP tasks. -> Score: 4.518403053283691
> RAG uses a retriever to fetch relevant documents and a generator to produce answers. -> Score: -3.920592784881592
> Generative Pre-trained Transformer (GPT) is a language generation model. -> Score: -5.563228130340576
> (venv) 
> ```
> 
> Maybe try a fresh venv?
> 
> In a new terminal
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install llama-index llama-index-postprocessor-flag-embedding-reranker 
> pip install git+https://github.com/FlagOpen/FlagEmbedding.git
> ```

It failed for me again：


Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at /data/models_path/bge-reranker-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

  File "/data/liumuyuan/RAG/rerank/test_rerank.py", line 42, in test_2
    ranked_nodes = reranker._postprocess_nodes(nodes, query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omnisky/venv/lib/python3.11/site-packages/llama_index/postprocessor/flag_embedding_reranker/base.py", line 73, in _postprocess_nodes
    assert len(scores) == len(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by sczlmy** [comment]
> Hmm, that code ran fine for me 😅
> 
> ```
> (venv) python ./test_flag.py                                                                               
> 4
> Retrieval-Augmented Generation (RAG) combines retrieval and generation for NLP tasks. -> Score: 4.518403053283691
> RAG uses a retriever to fetch relevant documents and a generator to produce answers. -> Score: -3.920592784881592
> Generative Pre-trained Transformer (GPT) is a language generation model. -> Score: -5.563228130340576
> (venv) 
> ```
> 
> Maybe try a fresh venv?
> 
> In a new terminal
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install llama-index llama-index-postprocessor-flag-embedding-reranker 
> pip install git+https://github.com/FlagOpen/FlagEmbedding.git
> ```

It failed again：
`Some weights of XLMRobertaForSequenceClassification were not initialized from the model checkpoint at /data/models_path/bge-reranker-large and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']

You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
    ranked_nodes = reranker._postprocess_nodes(nodes, query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omnisky/venv/lib/python3.11/site-packages/llama_index/postprocessor/flag_embedding_reranker/base.py", line 73, in _postprocess_nodes
    assert len(scores) == len(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

`
