### ISSUE TITLE
[Bug]: GoogleDemo.ipynb notebook seems to be requiring OpenAI API key

### ISSUE THREAD

**Issue by mariohinojosa** [run-llama/llama_index#12753]
### Bug Description

Hi,

I'm following the demo: https://github.com/run-llama/llama_index/blob/2f2d5a4735dd82f8acd2f630c745758e92202be2/docs/docs/examples/managed/GoogleDemo.ipynb

I have configured service account auth, enabled the Google API, downloaded the paul graham doc, but when I get to the basic querying section I get the following error:

ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******

I was under the impression that the LLM in this case would be Google's Gemini and the necessary credentials were already set by passing the Service Account details to `set_google_config(auth_credentials=credentials)` 

### Version

llama_index-0.10.28

### Steps to Reproduce

Follow the instructions on the notebook

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/llama_index/core/llms/utils.py in resolve_llm(llm, callback_manager)
     40             llm = OpenAI()
---> 41             validate_openai_api_key(llm.api_key)
     42         except ImportError:

6 frames
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/llama_index/core/llms/utils.py in resolve_llm(llm, callback_manager)
     46             )
     47         except ValueError as e:
---> 48             raise ValueError(
     49                 "\n******\n"
     50                 "Could not load OpenAI model. "

ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******
```

**Comment by logan-markewich** [comment]
It still needs an LLM to do response synthesis. It doesn't do that for you, and instead defaults to the global settings

You should define an LLM, and either change the global defaults

```
from llama_index.core import Settings
Settings.llm = llm
```

Or pass it in (I'm assuming its this line of code, although you didn't specify)
`query_engine = index.as_query_engine(llm=llm)`

**Comment by logan-markewich** [comment]
Seems like an issue with the response coming from googles API 😞
