### ISSUE TITLE
[Question]: How to add memory to OpenAI Agent

### ISSUE THREAD

**Issue by JulianOestreich90** [run-llama/llama_index#12788]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using an OpenAIAgent as a Top Level Agent, as shown in [Multi Document Agents](https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents/) and i want to enable conversational chat features. How can i add the chat history (User Queries & Answers) to the Top Level Calls? 

I tried to use ChatMemoryBufffer, but it seems that this is not the feature i am looking for, since it only saves the last call:
```
from llama_index.agent.openai import OpenAIAgent
from llama_index.storage.chat_store.redis import RedisChatStore
from llama_index.core.memory import ChatMemoryBuffer

chat_store = RedisChatStore(redis_url="redis://localhost:6379", ttl=30000)

chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=3000,
    chat_store=chat_store,
    chat_store_key="user1",
)

top_agent = OpenAIAgent.from_tools(
    tool_retriever=obj_index.as_retriever(similarity_top_k=10),
    memory=chat_memory,
    system_prompt=""" \
You are an agent designed to answer queries about a set of given documents.
Please always use the tools provided to answer a question. Do not rely on prior knowledge.\

""",
    verbose=True,
)
````

**Comment by logan-markewich** [comment]
@JulianOestreich90 the chat memory buffer is indeed the feature you want, and it's used automatically under the hood. It works by always giving the agent the last X messages that fit under a token limit.

Try changing the token limit if your agent is filling up the buffer quickly (just be aware its possible to cause token overflow errors if too big)

```
chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=6000,
    chat_store=chat_store,
    chat_store_key="user1",
)
```

We have plenty of unit tests, it works fine. You can test it your self too

```
chat_memory.put(ChatMessage(role="user", content="test"))

# get the current buffer
messages = chat_memory.get()

# get all
messages = chat_memory.get_all()
```

**Comment by JulianOestreich90** [comment]
@logan-markewich Yes, thank you, but that was not the problem.  I think the main problem was, that i used the `query()` fn instead of the `chat()` fn. When using chat() it worked, but many other problem arised. One of the biggest problem was that `ChatMemoryBuffer` doesnt work well with the`OpenAIAgent` because it omit chat messages such as 'tool_calls' and the chat_history becomes malformed for the OpenAI API. I had to switch to an ReActAgent to solve this problem.

**Comment by logan-markewich** [comment]
@JulianOestreich90 I specifically fixed it to not remove tool calls 😓 But I see you are using the redis chat store. Maybe you did not have the latest versions of llama-index-core and llama-index-chat-stores-redis ?

**Comment by JulianOestreich90** [comment]
@logan-markewich yes i saw your issue and that the pull request was merged, but it didn't worked with the latest version.

I was using llama-index 0.10.28 and llama-index-vector-stores-redis 0.2.0

**Comment by logan-markewich** [comment]
Hmm, I just tried and got an error about `content is none`. Made a fix and it seemed to work. Will make a PR

**Comment by Namasivaayam-L** [comment]
> [@logan-markewich](https://github.com/logan-markewich) Yes, thank you, but that was not the problem. I think the main problem was, that i used the `query()` fn instead of the `chat()` fn. When using chat() it worked, but many other problem arised. One of the biggest problem was that `ChatMemoryBuffer` doesnt work well with the`OpenAIAgent` because it omit chat messages such as 'tool_calls' and the chat_history becomes malformed for the OpenAI API. I had to switch to an ReActAgent to solve this problem.

Hey man, any solution found for the missing tool_calls message error from openai agent? (I can't switch to a ReactAgent, I'm using llama workflows with AzureOpenAI and Redis chat store.

**Comment by projectmnemos** [comment]
## Summary

I'd like to propose an integration with **mnem** (https://github.com/Uranid/mnem), a Rust-native, content-addressed knowledge graph engine that functions as "git for agent memory" - giving agents a persistent, versioned, auditable memory layer with no external dependencies.

## The gap this fills

llama's current memory implementation is session-scoped, no versioning, requires cloud service, no audit trail. mnem addresses this with:

- **Versioned storage**: every fact write is a content-addressed commit (BLAKE3 + DAG-CBOR)
- **Three-way merge**: concurrent agent writes are reconciled without silent overwrite
- **Full audit trail**: `mnem blame`, `mnem diff`, `mnem log` on the knowledge graph
- **Hybrid retrieval**: HNSW vector + BM25/SPLADE sparse + multi-hop graph traversal, fused via RRF
- **Offline-first**: bundled ONNX embedder, single ~40MB binary, no API keys
- **MCP-native**: ships with a full MCP server - integrates with any MCP-capable host with zero
  framework-specific code

## Benchmark evidence

On published memory benchmarks, mnem scores:
- LoCoMo R@5 = 0.726 (+0.218 over MemPalace, 1986 questions)
- LongMemEval R@5 = 0.966 (500 questions)
- MemBench R@5 = 0.960
- ConvoMem recall = 0.976 (+0.047 over baseline)

## Proposed integration shape

The simplest integration path is through the existing MCP interface - mnem runs as a local MCP server and any MCP-capable agent host can read/write to it without framework-specific bindings. A tighter integration (e.g., a dedicated memory backend class) is also feasible if the team is interested.

## License

Apache-2.0. No cloud dependency, no managed service requirement.

## Quick start

```
cargo install --locked mnem-cli --features bundled-embedder

mnem serve  # starts HTTP + MCP server on [[localhost](http://localhost/)](http://localhost)

mnem integrate  # auto-wires into Claude Code, Cursor, Continue, Zed
```

Happy to discuss design options or submit a draft PR.
