### ISSUE TITLE
[Bug]: TypeError: object HeadApiResponse can't be used in 'await' expression

### ISSUE THREAD

**Issue by AlgerTK** [run-llama/llama_index#12787]
### Bug Description

[RUN CODE]
url = "https://127.0.0.1:9200"
username = "elastic"
password = "xxxx"

es_client = Elasticsearch(
[url],
basic_auth=(username, password),
verify_certs=True,
ca_certs='./server_cert.pem')

vector_store = ElasticsearchStore(
    index_name="example", es_client=es_client
)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

[VERSION]
elasticsearch=8.13.0
llama-index-vector-stores-elasticsearch=0.1.7
llama-index=0.10.28

The Python Elasticsearch Clients elasticsearch[async] and elasticsearch both report the same error.

### Version

0.10.28

### Steps to Reproduce

I'm attempting to generate embeddings by utilizing the VectorStoreIndex.from_documents method.

### Relevant Logs/Tracbacks

```shell
File "/opt/homebrew/Caskroom/miniconda/base/envs/rag/lib/python3.12/site-packages/llama_index/vector_stores/elasticsearch/base.py", line 281, in _create_index_if_not_exists
    if await self.client.indices.exists(index=index_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object HeadApiResponse can't be used in 'await' expression
```

**Comment by logan-markewich** [comment]
@AlgerTK Try updating your elastic client version. There's been a ton of back on worth on this error, and It comes down the elastic client version you are using

**Comment by onazaruk** [comment]
> sion. There's been a ton of back on worth on this error, and It comes down the elastic client version you are using

Getting the same issue when passing pre-created es_client object (works fine when using es_url).
elasticsearch lib version is 8.12.1
llama_index 0.10.20
There is no way to increase request timeout when using internal ES client, that is why would like to pass external client object.

**Comment by scottmoney** [comment]
Any specific guidance on versions? I am seeing this error with these versions
elasticsearch: (8, 13, 0) 
llama_index.core : 0.10.31

**Comment by maxjakob** [comment]
The `ElasticsearchStore` expects an `AsyncElasticsearch` object for `es_client`. It's described in the [docstring](https://github.com/run-llama/llama_index/blob/1bde70b75ee5b4e6a5bc8c1c3f95eaa0dd889ab0/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py#L126). The [type annotation](https://github.com/run-llama/llama_index/blob/1bde70b75ee5b4e6a5bc8c1c3f95eaa0dd889ab0/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py#L207) could also make this clear.
