### ISSUE TITLE
[Feature Request]: SUPPORT OF AZUREOPENAI IN NLSQL TABLE QUERY ENGINE

### ISSUE THREAD

**Issue by swagatamr** [run-llama/llama_index#12794]
### Feature Description

SUPPORT OF AZUREOPENAI IN NLSQL TABLE QUERY ENGINE IS REQUIRED SO THAT I CAN USE MY AZURE CREDENTIALS AND CAN WORK IN AZURE MARKET PLACE

**Comment by logan-markewich** [comment]
@swagatamr Its already supported

Setup azure
https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI/?h=azure

And either set on the global settings

`Settings.llm = azure_llm`

Or pass it in

`NLSQLTableQueryEngine(..., llm=azure_llm)`
