### ISSUE TITLE
[Question]: Ensemble Querying / Advanced Retrieving from VectorStore

### ISSUE THREAD

**Issue by ad092** [run-llama/llama_index#12797]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

i've stored a lot of Nodes in a QdrantVectorStore.

https://docs.llamaindex.ai/en/stable/examples/query_engine/RetrieverRouterQueryEngine/
https://docs.llamaindex.ai/en/stable/examples/query_engine/ensemble_query_engine/

I'm not sure if I'm confusing things. If so, I'm sorry - please explain it to me.

I can't index my data with every start of my application because it is using a large knowledge index (separation of concerns).

**Q1:**
Is it possible to create a keyword index from a VectorStore? The data is already there and also keywords could be used through the keyword extractor.

The documentation suggests using the nodes. I don't understand why I need to load the nodes again if I already stored them in a VectorStoreIndex.

**Q2:**
How do I know what data the retriever is using? does it only use the embedded user query or can I use a pre-filtered search (e.g. keywords) to retrieve the relevant documents?

![grafik](https://github.com/run-llama/llama_index/assets/86461901/48faef1c-c39c-4f1d-9ad2-7617e44dab51)

### indexing.py
```python
config.embed_model = HuggingFaceEmbedding(model_name="mixedbread-ai/mxbai-embed-large-v1")
config.node_parser = SentenceSplitter.from_defaults(chunk_size=1024, chunk_overlap=100)

list_of_documents = [
  Document(
      text="...",
      metadata=[...]
  ),
...
]

nodes = config.node_parser.get_nodes_from_documents(
  list_of_documents,
  show_progress=DEBUG
)

client = QdrantClient()
vector_store = QdrantVectorStore(client=client, collection_name="large_index")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

VectorStoreIndex(
    embed_model=config.embed_model,
    storage_context=storage_context,
    nodes=nodes,
    show_progress=DEBUG
)       
```

### retrieving.py
```python
config.llm = Ollama(model="mistral")
client = QdrantClient()
vector_store = QdrantVectorStore(client=client, collection_name=collection__name)
index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
query_str = "I want to watch a movie about space"
chat_engine = index.as_chat_engine(
    llm=config.llm,
    verbose=DEBUG
)
streaming_response = chat_engine.stream_chat(query_str)
for token in streaming_response.response_gen:
    print(token, end="")
```

**Comment by logan-markewich** [comment]
Q1: You need the nodes, because you need to extract and map keywords to nodes. This does not work with a vector index. Some vector dbs offer hybrid search, which is similar-ish to keyword search.

Q2: It uses all the data in your configured index/namespace/collection. If you apply metadata filters, those filter the data before performing the top-k search

**Comment by ad092** [comment]
Thanks for the explanation. That was helpful.
