### ISSUE TITLE
[Feature Request]: Allow SSL Connections to Postgress DB (PGVectorStore)

### ISSUE THREAD

**Issue by dhanushreddy291** [run-llama/llama_index#12795]
### Feature Description

My Postgress DB doesnt allow connections without a valid SSL certificate. Need to make some changes in underlying sqlalchemy code and pass those params to enable ssl.

Can be a good first issue, if anyone wants to pick it up.

### Reason

My DB doesnt allow non ssl connections, so I wasnt able to connect it.

### Value of Feature

It will allow anyone to connect to a DB securely which allows only SSL connections.

**Comment by logan-markewich** [comment]
plz make a PR if you are interested. I saw the other PR was closed for some reason (the contributor never really responded 🤷🏻)

**Comment by kmcleste** [comment]
@logan-markewich That was me. I need to get additional approval through work before I can really do anything else. Assuming I'm able, I intend to finish that PR. I closed it for the time being, not knowing how long this approval process will take and didn't want people holding their breath.
