### ISSUE TITLE
[Question]: How can I use a local embedding model without using HuggingfaceEmbedding?

### ISSUE THREAD

**Issue by dawancha** [run-llama/llama_index#12798]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

HI all,
I want to use a local embedding model and not download it automatically from huggingface, I need to download it manually because I can't connect to huggingface.
A few days ago,I was  still able to do it using this method:
<code>
model_path = "./models/embedding/BAAI/bge-small-en-v1.5"
model = AutoModel.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(model_path)

Settings.embed_model = HuggingFaceEmbedding(
    model=model,
    tokenizer=tokenizer,
    device="cuda"
)
</code>
But Now, it caught an error: model is deprecated. Please remove it from the arguments.
So what should I do now?

**Comment by logan-markewich** [comment]
Download the model locally, and pass the local model path to highingfaceembedding 

`HuggingFaceEmbedding(model_name="path/to/model_dir")`

**Comment by dawancha** [comment]
> Download the model locally, and pass the local model path to highingfaceembedding
> 
> `HuggingFaceEmbedding(model_name="path/to/model_dir")`

Wow, it worked, thank you!
