### ISSUE TITLE
[Question]: Use of metadata filters in Chat Engines

### ISSUE THREAD

**Issue by FaresKi** [run-llama/llama_index#12809]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using Supabase Vector Stores and inserting PDF data inside of them, with provided metadata in each document
I want the vector store index to create chat engines specialized based on provided metadata filters (key/value metadata)
How can I pass the metadata to the `as_chat_engine` method?

Thanks!

**Comment by FaresKi** [comment]
@dosu-bot I feel like you misunderstood.
here's what my code looks like:
```py
from llama_index.core.vector_stores.types import (
    MetadataFilters,
    ExactMatchFilter,
)
from llama_index.core.indices.vector_store import VectorStoreIndex
from app.engine.vector_store import get_vector_store

metadata_filters = MetadataFilters(
        filters=[
            ExactMatchFilter(key="topic", value="math"),
            ExactMatchFilter(key="user_id", value=1),
        ]
    )
vector_store = get_vector_store()
index = VectorStoreIndex.from_vector_store(vector_store)

chat_engine = index.as_chat_engine() # how to pass metadata_filters here
chat_response = chat_engine.chat('hello world')
```  

I want to pass the metadata filter to the index for chat engines

**Comment by FaresKi** [comment]
@dosu-bot what about the chat history, how can i include it?

**Comment by logan-markewich** [comment]
@FaresKi I think I answered this on discord. Going to copy and paste here for completeness

```
Logan - Yesterday at 2:38 PM
Do you mean metadata filtering?
https://docs.llamaindex.ai/en/stable/examples/vector_stores/Qdrant_metadata_filter/?h=qdrant+filt

Or with native qdrant filter syntax
https://docs.llamaindex.ai/en/stable/examples/vector_stores/Qdrant_using_qdrant_filters/?h=qdrant+filter

Fares — Today at 7:48 AM
the retriever engine works, but this doesn't mention the implementation with a chat engine. is it possible for chat engines to use metadata? 

Logan M — Today at 11:18 AM
It works fine with a chat engine

index.as_chat_engine(filters=filters, ...)
The filters kwarg just gets passed to the retriever for the index
which is actually using it

Fares — Today at 11:23 AM
That's the thing, I don't think the chat_engine is getting the metadata thru.
Here's the query engine:
Image
And here's the chat engine:
Image
You'll see that chat response object doesn't contain a metadata property, and that the responses are vastly different (the query engine acknowledges that the topic passed thru the filter are outside the message's context, the chat engine doesn't even acknowledge that)

Logan M — Today at 11:32 AM
The metadata property on the response object is not really related.

If you check, both have a source_nodes attribute -- this contains the nodes used to generate a response. Both should have metadata that aligns with your filters.

As for the difference in responses, its pretty important to understand the difference between a query engine and chat engine

A query engine takes the query, retrieves, and then sends the retrieved context + query to the LLM, using a prompt template that asks the LLM to use only the context and answer the question

For your chat engine, since you didn't specify a chat mode, it defaults to an agent. This agent has a single tool, which is the query engine from your index. On every user message, the agent looks at the message + chat history + tools, and decides to invoke a tool or not. Here, it invoked the query engine, the query engine ran, and then it rewrites the query engine response in context with the chat history. (Optionally, it could decide to not call a tool, and response direclty)

Agent behaviour is largely controlled by system prompts, and tool names + descriptions 
There are a few other chat modes
https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/usage_pattern/#available-chat-modes

Fares — Today at 11:45 AM
you're absolutely right, i completely forgot about the chat mode!!
```

**Comment by mirallm** [comment]
Hello, I am using this code, but the metadata filter is not working. I tried also to use pre_filters and filters attributes and its wasn't working. can you tell me how? @dosu @logan-markewich 


`   async def setup_chatengine(self, pre_filters={}):
        pre_filters={"filename":"babe.pdf"}
        from llama_index.core.vector_stores.types import MetadataFilters, ExactMatchFilter
        metadata_filters = MetadataFilters(
    filters=[
        ExactMatchFilter(key="source_id", value=5),
   
    ]
)

        
        
        self.chat_engine = self.index_handler.vector_index.as_chat_engine(
            chat_mode="condense_plus_context",
            memory=self.memory,
            llm=self.llm,
            context_prompt=(
                "You are a chatbot, You always answer in the language of the query."
                "You only answer questions based on the context"
                "Here are the relevant documents for the context:\n"
                "{context_str}"
                "\nInstruction: Use the previous chat history, or the context above, to interact and help the user."
                "Do NOT answer questions that are not related to the context or any normal interactions. always say I am sorry in that case."
            ),
            MetadataFilters=metadata_filters, # Pass metadata filters here
            verbose=False,
            streaming=True,
            use_async=True
   
        )
`

**Comment by mirallm** [comment]
metadata_filters = MetadataFilters(
        filters=[
            ExactMatchFilter(key="source_id", value=5),
        ]
    )

How to use if i want for source_id=5 or for file_name="name.pdf", not an AND but more like to get source for this or that @dosu

**Comment by mirallm** [comment]
@dosu
