### ISSUE TITLE
[Question]: error in code - prompt = self.template.format(**mapped_all_kwargs)

### ISSUE THREAD

**Issue by lawplus** [run-llama/llama_index#12816]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**running errors**:
\llama_index\core\prompts\base.py", line 196, in format   
    prompt = self.template.format(**mapped_all_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: '"problem_sort"'

**My codes below**: 
`
def rag_string_query_with_template(query_str, str2, str3, str4):
    # chat_face.title = "AI助手  (基于数据集：" + collection_name + ")"
    logger.info("query_str is " + str(query_str) + ", collection name is " + collection_name)
    logger.info(" ---  ---  ---  ---  ---  --- ")
    qa_prompt = PromptTemplate(
        "Context information is below.\n"
        "---------------------\n"
        "{context_str}\n"
        "---------------------\n"
        #"Given the context information and not prior knowledge, "
        #"answer the query.\n"
        "You can only answer questions about the provided context.  "
        "If you know the answer but it is not based in the provided context, "
        "don't provide the answer, just state the answer is not in the knowledge base and can't provide the answer. "
        
        # 将获取到的数据格式化为json格式，包括字段：问题小类[m] - problem_sort、详细解决方案 - detail_solution、关联数据库表 - db_table
        "Please format your answer as JSON. "
        "The JSON format includes 'problem_sort'（问题小类[m]）, 'detail_solution'（详细解决方案）, and 'db_table'（关联数据库表）. "
        "You need to extract these fields from the Context information. "
        "At this time, your output response cannot contain any non-JSON characters. "
        "If you cannot extract it, please reply that the detail error.\n"
        "For example, your answer should look like this: "
        "`{\"problem_sort\": \"系统漏单\", \"detail_solution\": \"从用户查询中抽取关键信息，利用数据库进行接口字段补全后调用AI python函数interact_with_erp_system，返回响应ok则代表问题已解决!\", \"db_table\": \"涉及到的表有table1、table2\"}`\n"

        "Query: {query_str}\n"
        "Answer: "
    )
    class RAGStringQueryEngine(CustomQueryEngine):
        """RAG String Query Engine."""

        retriever: BaseRetriever
        response_synthesizer: BaseSynthesizer
        llm: OpenAI
        qa_prompt: PromptTemplate

        def custom_query(self, query_str: str):
            nodes = self.retriever.retrieve(query_str)
            context_str = "\n\n".join([n.node.get_content() for n in nodes])
            logger.info(" --- context_str is --- " + str(context_str))
            logger.info(" ---  ---  ---  ---  ---  --- ")
            response = self.llm.complete(
                qa_prompt.format(context_str=context_str, query_str=query_str)
            )
            return str(response)`

**Comment by logan-markewich** [comment]
@lawplus due to how python string formatting works, if your prompt has `{` or `}` characters in it that don't represent string variables, you'll need to escape them by doubling them, `{{` and `}}`

**Comment by lawplus** [comment]
other error :  AttributeError: 'tuple' object has no attribute 'get_doc_id'

**Comment by lawplus** [comment]
> @lawplus due to how python string formatting works, if your prompt has `{` or `}` characters in it that don't represent string variables, you'll need to escape them by doubling them, `{{` and `}}`

thanks . resovled
