### ISSUE TITLE
[Bug]: llama-index-embeddings-google and llama-index-vector-stores-google need package bump.

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#12811]
### Bug Description

llama-index-embeddings-google and llama-index-vector-stores-google depend on google-generativeai<0.4.0 and >=0.3.2

Whereas
llama-index-embeddings-gemini 0.1.6 depends on google-generativeai<0.5.0 and >=0.4.1
  llama-index-llms-gemini 0.1.7 depends on google-generativeai<0.5.0 and >=0.4.1
  llama-index-llms-palm 0.1.5 depends on google-generativeai<0.5.0 and >=0.4.1
  llama-index-multi-modal-llms-gemini 0.1.5 depends on google-generativeai<0.5.0 and >=0.4.1

This causes an issue with the pip resolver

### Version

llama-index-vector-stores-google 0.1.5 and llama-index-embeddings-google 0.1.4

### Steps to Reproduce

Just installl the latest packages for vector-stores-google and embeddings-google

### Relevant Logs/Tracbacks

```shell
ERROR: Cannot install -r requirements-lock.txt (line 102), -r requirements-lock.txt (line 105), -r requirements-lock.txt (line 87), -r requirements-lock.txt (line 95), google-generativeai==0.4.1 and llama-index-vector-stores-google==0.1.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested google-generativeai==0.4.1
    llama-index-embeddings-gemini 0.1.6 depends on google-generativeai<0.5.0 and >=0.4.1
    llama-index-llms-gemini 0.1.7 depends on google-generativeai<0.5.0 and >=0.4.1
    llama-index-llms-palm 0.1.5 depends on google-generativeai<0.5.0 and >=0.4.1
    llama-index-multi-modal-llms-gemini 0.1.5 depends on google-generativeai<0.5.0 and >=0.4.1
    llama-index-vector-stores-google 0.1.5 depends on google-generativeai<0.4.0 and >=0.3.2

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by logan-markewich** [comment]
@gich2009 I'm unable to test googles services. If you cam test that the latest Google packages do not break things for vector-stores-google, and make a PR, that would be extremely appreciated

**Comment by gich2009** [comment]
Alright @logan-markewich. Will take a look when I get the chance.
