### ISSUE TITLE
[Question]: How to use SimpleDirectoryReader to also process .json files for IngestionPipeline?

### ISSUE THREAD

**Issue by Turkzilla** [run-llama/llama_index#12826]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can you give me a full example of how to use `SimpleDirectoryReader` on a folder that has pdf, txt but also JSON files (such as a database export as JSON) to later be fed into the `IngestionPipeline`? When I use JSONReader, I get FULL document (exceeding token limit) instead of `Document` nodes with tracking `_part` references like SimpleDirectoryReader does to other files.

```
def get_documents(folder):
return SimpleDirectoryReader(folder, encoding="utf-8", filename_as_id=True).load_data()
```
Then something like:
```
def ingestDocs(docs):
     text_splitter = SentenceSplitter(
        chunk_size=512, chunk_overlap=64, tokenizer=tokenizer)
     pipeline = IngestionPipeline(
        transformations=[text_splitter])
      
      nodes = pipeline.run(documents=docs)
      # ...
      
```

**Comment by Turkzilla** [comment]
> Hey @Turkzilla! 👋 Long time no see in the issue tracker. Hope you've been all good and coding hasn't turned you into a nocturnal creature... yet. 😄 I'm diving into your question now and will get back to you with a full run-down shortly! 🚀

Edited the question.

**Comment by logan-markewich** [comment]
@Turkzilla 

`pip install llama-index-readers-json`

```
from llama_index.readers.json import JSONReader

file_extractor = {".json": JSONReader()}

documents = SimpleDirectorReader(..., file_extractor= file_extractor).load_data()
```

Or, write your own JSON loader (which tbh I would probably recommend -- you probably want the JSON loaded in a particular way)
https://docs.llamaindex.ai/en/stable/module_guides/loading/simpledirectoryreader/?h=simpledirect#extending-to-other-file-types

**Comment by Turkzilla** [comment]
@logan-markewich : Thank you for the followup and suggestion. I tried that first but my experiment yielded "Token indices sequence length is longer than the specified maximum sequence length for this model (1175456 > 4096). Running this sequence through the model will result in indexing errors" I agree that I should create my own Json loader but I just want to nail down the whole ingestion components before customizing. Do you happen to have a sample cusyom loader that is compatible with the `IngetionPipeline`?

**Comment by logan-markewich** [comment]
The readers and ingestion pipelines are not related

That message you describe is fine -- llama-index is counting tokens during splitting, and this just means there was a very large chunk that was counted. (I think this comes from hughingface tokenizers?)

If you let it run and inspect the output nodes/chunks, I think you'd see it's working fine
