### ISSUE TITLE
[Question]: I only persisted the docstore for my VectorStoreIndex How can I rebuild the index?

### ISSUE THREAD

**Issue by Data-drone** [run-llama/llama_index#12829]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I only persisted the `Docstore` in my storage context. 

Now I can't reload my `VectorStoreIndex` even though I think the Docstore contains all the we need?

I have feeding the reloaded Docstore into a new VectorStoreIndex using the `from_documents` but it doesn't work

**Comment by logan-markewich** [comment]
@Data-drone The docstore probably doesn't contain the embeddings, unless you specifically attached embeddings to your nodes before they were inserted.

So, embeddings aside, you can get the nodes back with 

```
from llama_index.core.storage.docstore import SimpleDocumentStore

docstore = SimpleDocumentStore.from_persist_path("./storage/docstore.json")

nodes_dict = docstore.docs
nodes = list(nodes_dict.values())

index = VectorStoreIndex(nodes=nodes, ...)
```
