### ISSUE TITLE
[Question]: how to started with multi gpu

### ISSUE THREAD

**Issue by OKC13** [run-llama/llama_index#12834]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

my gpu is 24G memory，so， its possiable to spread models to 2 GPUs。

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 172.00 MiB. GPU 0 has a total capacity of 23.50 GiB of which 7.19 MiB is free. Including non-PyTorch memory, this process has 23.48 GiB memory in use. Of the allocated memory 23.26 GiB is allocated by PyTorch, and 1.81 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

**Comment by logan-markewich** [comment]
@OKC13 Its not really possible right now, or at least not with llama-index

You'd have to load the model and tokenizer outside of llama-index, using huggingface and PyTorch. such that its multi-gpu (they have docs on this), and then pass it in

`llm = HuggingFaceLLM(model=model, tokenizer=tokenizer, ...)`
