### ISSUE TITLE
[Bug]: ImportError: cannot import name 'OpenAIFinetuneEngine' from 'llama_index.finetuning' (unknown location)

### ISSUE THREAD

**Issue by xniuuu** [run-llama/llama_index#12838]
### Bug Description

I tried to follow the finetuning tutorial from [https://docs.llamaindex.ai/en/stable/examples/finetuning/openai_fine_tuning/](url) and got to the chapter of creating the finetune engine:

```
from llama_index.finetuning import OpenAIFinetuneEngine

finetune_engine = OpenAIFinetuneEngine(
    "gpt-3.5-turbo",
    "finetuning_events.jsonl",
    # start_job_id="<start-job-id>"  # if you have an existing job, can specify id here
)

# finetune_engine = OpenAIFinetuneEngine.from_finetuning_handler(
#     finetuning_handler,
#     "gpt-3.5-turbo",
#     "tmp.jsonl"
# )
```

When I try to run this code, I receive an import error (see title). I also tried to import it from `llama_index.finetuning.openai`, since the OpenAIFinetuneEngine class was in the "openai" directory, as well as `llama_index.finetuning.openai.base` , but both returned the error:

```
from llama_index.finetuning.openai.base import OpenAIFinetuneEngine
ModuleNotFoundError: No module named 'llama_index.finetuning.openai'
```
So far I had no luck in finding the solution to this, so I was hoping anyone here could help me out.
Cheers :) 

### Version

0.10.29

### Steps to Reproduce

Follow this tutorial:
[https://docs.llamaindex.ai/en/stable/examples/finetuning/openai_fine_tuning/](url)
The error should occur at chapter "Create OpenAIFinetuneEngine"

**Comment by logan-markewich** [comment]
@xniuuu It works fine for me
https://colab.research.google.com/drive/1sXV_deH17N5fPM-oE3PAstPUrMc178zJ?usp=sharing

Maybe try a fresh venv? Seems like an env issue

In a new terminal
```
python -m venv venv
source venv/bin/activate
pip install llama-index-finetuning
```

**Comment by xniuuu** [comment]
> @xniuuu It works fine for me https://colab.research.google.com/drive/1sXV_deH17N5fPM-oE3PAstPUrMc178zJ?usp=sharing
> 
> Maybe try a fresh venv? Seems like an env issue
> 
> In a new terminal
> 
> ```
> python -m venv venv
> source venv/bin/activate
> pip install llama-index-finetuning
> ```

Yes, that helped, thank you very much :)
