### ISSUE TITLE
[Feature Request]: `OpenAILike` to use `messages_to_prompt` and `completion_to_prompt`

### ISSUE THREAD

**Issue by qdm12** [run-llama/llama_index#12833]
### Feature Description

Support specifying custom `messages_to_prompt` and `completion_to_prompt` functions for the `OpenAILike` LLM component. Right now it is possible to specify them but they are never called, most likely because OpenAILike does not inherit from the `CustomLLM` LLM component.

### Reason

I am running an OpenAI-like API (VLLM) running a Mistral model, and I cannot use it with your library because the prompt style is different than OpenAI's one.

### Value of Feature

Extend usage of this library for any LLM model on an LLM server serving over an OpenAI-like API.

**Comment by logan-markewich** [comment]
@qdm12 They are called, please see the source cdoe

For example:

https://github.com/run-llama/llama_index/blob/6af5b1377a652f3e1de2f8523e0cbab2378ebb33/llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py#L112

https://github.com/run-llama/llama_index/blob/6af5b1377a652f3e1de2f8523e0cbab2378ebb33/llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py#L94

**Comment by qdm12** [comment]
My apologies, the `is_chat_model` was set to `True` and therefore these two functions were not called. Thanks for pointing me in the right direction 💯 !
