### ISSUE TITLE
[Bug]: Metadata keys are being removed automatically when using auto_retriever

### ISSUE THREAD

**Issue by the-corner-guy** [run-llama/llama_index#12843]
### Bug Description

I am trying to implement auto_retriever for my use case with pinecone vector DB, Auto-retrieve is fetching the correct vector according to the use case but the metadata elements relating to the vector are getting lost in the process

What is expected:
{'download': '', 'id':'','modified': '2021-02-25T21:00:42Z', 'scope': '{"scope": "users"}', 'source': '', 'text': '', 'type': 'SharepointConnect', 'view_url': ''}

What is received:
{'download': '', 'modified': '2021-02-25T21:00:42Z', 'scope': '{"scope": "users"}', 'source': '', 'type': '', 'view_url': '', 'id': ''}

Notice that the text element from the metadata is missing in the auto retrieve response, I have removed the values for privacy reasons 

### Version

>=0.9.31

### Steps to Reproduce

Step Up a pinecone db with the following metadata schema:

{'download': '', 'id':'','modified': '2021-02-25T21:00:42Z', 'scope': '{"scope": "users"}', 'source': '', 'text': '', 'type': 'SharepointConnect', 'view_url': ''}

And try to implement auto_retriever 

`from pinecone import Pinecone
from llama_index.core import VectorStoreIndex
from llama_index.vector_stores.pinecone import PineconeVectorStore
from llama_index.core.vector_stores.types import MetadataInfo, VectorStoreInfo
from llama_index.core.retrievers import VectorIndexAutoRetriever
import os

os.environ[
    "PINECONE_API_KEY"
] = "key"
os.environ["OPENAI_API_KEY"] = "key"
api_key = os.environ["PINECONE_API_KEY"]
pc = Pinecone(api_key=api_key)
index_name = "index name"
pinecone_index = pc.Index(index_name)
vector_store = PineconeVectorStore(pinecone_index=pinecone_index , namespace = 'development_test_two')
index = VectorStoreIndex.from_vector_store(vector_store=vector_store)

vector_store_info = VectorStoreInfo(
    content_info="Knowledge source accumulated from different documents",
    metadata_info=[
        MetadataInfo(
            name="source",
            type="str",
            description=(
                "source of the information"
                "document from where the data is originated"
            ),
        )    ],
)

retriever = VectorIndexAutoRetriever(
    index, vector_store_info=vector_store_info
)

res = retriever.retrieve(' According to Plan.doc  when will the long term backup will be used')`

**Comment by logan-markewich** [comment]
I'm not able to reproduce 

https://colab.research.google.com/drive/1JDZn0AGylyu8umdmYGtveMEtMqzvDHQ_?usp=sharing

The metadata from retrieved nodes is never modified in the source code. I think it's possible some of your data was inserted with blank fields? Either that, or it's a bug with older versions of llama-index (I noticed you are using v0.9.x? The latest is v0.10.29)

**Comment by the-corner-guy** [comment]
> `remove_text_from_metadata`

This did not resolve the issue

**Comment by the-corner-guy** [comment]
> I'm not able to reproduce
> 
> https://colab.research.google.com/drive/1JDZn0AGylyu8umdmYGtveMEtMqzvDHQ_?usp=sharing
> 
> The metadata from retrieved nodes is never modified in the source code. I think it's possible some of your data was inserted with blank fields? Either that, or it's a bug with older versions of llama-index (I noticed you are using v0.9.x? The latest is v0.10.29)

@logan-markewich 

I would try using the latest version I hope it works but the data is clean
