### ISSUE TITLE
[Feature Request]: add azure_ad_token_provider support for AzureOpenAI and AzureOpenAIEmbedding

### ISSUE THREAD

**Issue by 3x3cut0r** [run-llama/llama_index#12849]
### Feature Description

I need to authenticate via azure_ad_token_provider, but i think that is not implemented and only works for AzureOpenAI via openai
```
from openai import AzureOpenAI
from azure.identity import DefaultAzureCredential, get_bearer_token_provider

token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

client = AzureOpenAI(
    api_version='2024-02-15-preview',
    azure_endpoint='https://my-azure.openai.azure.com',
    azure_ad_token_provider=token_provider,
)
```
This applies to both AzureOpenAI and AzureOpenAIEmbedding from llama_index.

### Reason

azure_ad_token_provider is not implemented into [AzureOpenAI](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-azure-openai/llama_index/llms/azure_openai/base.py) or [AzureOpenAIEmbedding](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/embeddings/llama-index-embeddings-azure-openai/llama_index/embeddings/azure_openai/base.py) from llama_index

### Value of Feature

After that, I can login via azure_ad_token_provider like this:
```
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
from azure.identity import DefaultAzureCredential, get_bearer_token_provider

token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

llm = AzureOpenAI(
    api_version='2024-02-15-preview',
    azure_endpoint='https://my-azure-endpoint.openai.azure.com',
    azure_ad_token_provider=token_provider,
)

embed_model = AzureOpenAIEmbedding(
    api_version='2024-02-15-preview',
    azure_endpoint='https://my-azure-endpoint.openai.azure.com',
    azure_ad_token_provider=token_provider,
)

from llama_index.core import Settings

Settings.llm = llm
Settings.embed_model = embed_model
```

**Comment by 3x3cut0r** [comment]
I found out, there are new versions of `llama_index.llms.azure_openai` and `llama_index.embeddings.azure_openai` that now supports adding `azure_ad_token_provider`, but now i got errors:
```
httpx.LocalProtocolError: Illegal header value b'Bearer '
```
because the `api_key` is not set. if i will set a fake `api_key`, then i am unable to authenticate.
is there a workaround for that?

the only way for me to generate embedding is like this:
```
# powershell -ex AllSigned -c "Invoke-RestMethod 'https://aka.ms/install-azd.ps1' | Invoke-Expression"
# azd auth login

import os
from azure.identity import DefaultAzureCredential, get_bearer_token_provider
from dotenv import load_dotenv, find_dotenv

# from llama_index.llms.azure_openai import AzureOpenAI
from openai import AzureOpenAI

# load .env
_ = load_dotenv(find_dotenv())

# set up azure openai variables
# azure_openai_api_key = os.environ["AZURE_OPENAI_API_KEY"]
azure_openai_api_base = os.environ["AZURE_OPENAI_API_BASE"]
azure_openai_api_version = os.environ["AZURE_OPENAI_API_VERSION"]
azure_openai_model_name = os.environ["AZURE_OPENAI_MODEL"]
azure_openai_embed_model_name = os.environ["AZURE_OPENAI_EMBED_MODEL"]
azure_openai_engine = os.environ["AZURE_OPENAI_ENGINE"]

token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

client = AzureOpenAI(
    api_version=azure_openai_api_version,
    azure_endpoint=azure_openai_api_base,
    azure_ad_token_provider=token_provider,
    engine=azure_openai_engine,
    engine=azure_openai_engine,
)

response = client.embeddings.create(
    input="Your text string goes here", model=azure_openai_embed_model_name
)

print(response.model_dump_json(indent=2))
```

**Comment by pamelafox** [comment]
I was able to get it to work with:

    token_provider = azure.identity.get_bearer_token_provider(
        azure.identity.DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
    )
    llm = AzureOpenAI(
        model=os.getenv("OPENAI_MODEL"),
        deployment_name=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
        azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
        api_version=os.getenv("AZURE_OPENAI_VERSION"),
        use_azure_ad=True,
        azure_ad_token_provider=token_provider,
    )

I think you're missing use_azure_ad=True

**Comment by pamelafox** [comment]
Relatedly, the docs don't describe these parameters:
https://docs.llamaindex.ai/en/stable/api_reference/llms/azure_openai/?h=azureopenai#llama_index.llms.azure_openai.AzureOpenAI

Can they be updated? I can work on PR if desired.

**Comment by 3x3cut0r** [comment]
> I think you're missing use_azure_ad=True

ah, thanks, great hint. i will try it at work next week.
in the meantime i use my own class `MyAzureOpenAIEmbedding` which gets the embedding `from openai import AzureOpenAI` which works great.

**Comment by 3x3cut0r** [comment]
So i can confirm, its working with `use_azure_ad=true` and without providing an `api_key`

**Comment by ingoke** [comment]
It would be great if AzureOpenAIEmbedding would be enhanced with `use_azure_ad=true` and `_get_credential_kwargs` can be modified so that it can be used without an API key like in AzureOpenAI.

**Comment by pamelafox** [comment]
@ingoke Agreed! Since this issue is closed, could you file a new feature request so your request gets more visibility?
