### ISSUE TITLE
[Bug]: data_generator.generate_questions_from_nodes() does not generate questions. Progress bar does not move

### ISSUE THREAD

**Issue by Luchao2012** [run-llama/llama_index#12859]
### Bug Description

data_generator.generate_questions_from_nodes() does not generate questions. Progress bar does not move

### Version

0.10.27

### Steps to Reproduce

llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="test-gpt-35-turbo",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="test-text-embedding-ada-002",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

from llama_index.core import Settings

Settings.llm = llm
Settings.embed_model = embed_model

reader = SimpleDirectoryReader(
    input_dir="../../reports_reservoir_sub",
    recursive=True,
)

docs = reader.load_data(num_workers=4)  # Load the documents from the directory

from llama_index.core.evaluation import DatasetGenerator

data_generator = DatasetGenerator.from_documents(docs, 
                                                 num_questions_per_chunk=1, 
                                                 llm=llm,
                                                 show_progress=True)

eval_questions = data_generator.generate_questions_from_nodes()

The code stops at the end and does not progress.

**Comment by logan-markewich** [comment]
Maybe confirm your llm works 

`print(llm.complete("hello world"))`

If it works, try hitting ctrl-c when it's "stuck" and see where it is in the code from the traceback

**Comment by Luchao2012** [comment]
print(llm.complete("hello world"))
shows: Hello! How can I assist you today?

All the code works until the last line of code where is "stuck":
eval_questions = data_generator.generate_questions_from_nodes()

**Comment by Luchao2012** [comment]
> print(llm.complete("hello world")) shows: Hello! How can I assist you today?
> 
> All the code works until the last line of code where is "stuck": eval_questions = data_generator.generate_questions_from_nodes()

print(llm.complete("hello world"))
shows: Hello! How can I assist you today?

All the code works until the last line of code where is "stuck":
eval_questions = data_generator.generate_questions_from_nodes()

**Comment by Luchao2012** [comment]
I changed it to RagDatasetGenerator
from llama_index.core.llama_dataset.generator import RagDatasetGenerator
dataset_generator = RagDatasetGenerator.from_documents(docs, 
                                                 num_questions_per_chunk=1, 
                                                 llm=llm,
                                                 show_progress=True)
rag_dataset = dataset_generator.generate_dataset_from_nodes()

There is progress now. What is the reason that the DatasetGenerator does not progress with all the other code are the same.

**Comment by logan-markewich** [comment]
@Luchao2012 and if you hit ctrl+c (or kill/interrupt the program), what's the traceback? 

It works fine for me locally, so just trying to figure out where the issue is

If you are running in a notebook (or some other async function), maybe try the async version? `eval_questions = await data_generator.agenerate_questions_from_nodes()`
