### ISSUE TITLE
[Feature Request]: retrievers from up-to-date data

### ISSUE THREAD

**Issue by stdweird** [run-llama/llama_index#12851]
### Feature Description

Some retrievers seem to work on a snapshot of data instead of the data in a store. And this is not really made clear in the docs Eg. the DM25Retriever, you can pass a docstore during init; suggesting, at least imho, that the docstore will be queried. But the actual code converts the docstore in static list of nodes.

As a feature, i would like that we can get this dynamically (either by talking to the docstore directly, or by making a `docstore.nodes` property that updates the nodes somehow).

I ran into similar issue with the KGTableRetriever, where the only way to use an existing KGstore is to pass an index_struct from corresponding index_store (and that index_struct is also static).

Anyway, i "fixed" the issue by subclassing the retrievers and update the atrribute in a custom `_retrieve` method on each retrieve call; but it is slowish.

### Reason

In a production setup i expect to be able to update the backend stores with eg new nodes (eg by rerunning a pipeline) independent of having to reinitiate the clients.

**Comment by logan-markewich** [comment]
@stdweird the thing with BM25 is that, it IS a static index. The way BM25 works is that if any nodes are added, the entire index needs to be recalculated (this is how the BM25 algorithm works)

**Comment by stdweird** [comment]
@logan-markewich  ok, that's embarassing i didn't know that. i'll further test the bm25 retriever, and how much we really benefit from it.
