### ISSUE TITLE
[Question]: How do I import the ToolSpec? 

### ISSUE THREAD

**Issue by DrRaja** [run-llama/llama_index#12850]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I've searched the documentation and it seems like some latest changes are not reflected. For example, I'm trying to import the Brave_Search Tool and according to the documentation and example notebook it should be as straightforward as 

```
from llama_index.tools.brave_search import BraveSearchToolSpec
```

However this returns an error: ModuleNotFoundError: No module named 'llama_index.tools'

From the repo I see that all tool specs have been moved into integrations directory, but how do I use these now?

**Comment by logan-markewich** [comment]
@DrRaja you need to install it

`pip install llama-index-tools-brave-search`

**Comment by DrRaja** [comment]
Thank you!
