### ISSUE TITLE
[Question]: how to keep track of pages nimbers for each chunk

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12869]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a pdf and im using unstructuredio partition_pdf for ingestion, now i also need to keep track of the page numbers for each chunk to display to the users, how to do this? Thanks

**Comment by logan-markewich** [comment]
You can add the page number to metadata assuming you have the page numbers 

```
from llama_index.core import Document

document = Document(text=text, metadata={"page_number": 1})
```

**Comment by JINO-ROHIT** [comment]
thanks!
