### ISSUE TITLE
[Question]: can i use llamaindex for response completion using huggingface models?

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#12867]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

is there a way to use huggingface models for response completion without any indexing or anything?

**Comment by logan-markewich** [comment]
```
llm = HuggingFaceLLM(....)
llm.complete("Hello world")
```

**Comment by JINO-ROHIT** [comment]
thanks!
