### ISSUE TITLE
[Question]: How to insert data into specific database for Milvus?

### ISSUE THREAD

**Issue by momocat-aric** [run-llama/llama_index#12868]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I use llamaindex to connect the Milvus, and I specify the Milvus db-name as "New_DBName". But when insert data, I found all the data is inserted into 'default' database. Following is my connect code:
`vector_store = MilvusVectorStore(dim=384, db_name="New_DBName", overwrite=True)`

Env:
python 3.9
llamaindex 0.9.48

**Comment by momocat-aric** [comment]
> It appears there's a mix-up with the parameter used to specify the database or collection name in your code. In the version of LlamaIndex you're using, the `MilvusVectorStore` class expects a `collection_name` parameter for defining where the data should be stored, not `db_name`. Here's how you can adjust your code to ensure data is inserted into the correct collection:
> 
> ```python
> from llama_index.legacy.vector_stores.milvus import MilvusVectorStore
> 
> vector_store = MilvusVectorStore(
>     dim=384,
>     collection_name="New_DBName",  # Use collection_name instead of db_name
>     overwrite=True
>     # Include other necessary parameters like URI and token if needed
> )
> ```
> 
> By specifying `collection_name="New_DBName"`, your data will be inserted into the "New_DBName" collection. Ensure that any other required parameters, such as the Milvus instance URI and token (if using RBAC), are also correctly set in your `MilvusVectorStore` initialization.
> 
> This adjustment should direct your insert operations to the intended collection. If you encounter further issues or have additional questions, feel free to ask.
> 
> ## Sources
> * [llama-index-legacy/llama_index/legacy/vector_stores/milvus.py](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/vector_stores/milvus.py)
> 
> #### About Dosu

not solve my problem. 
Milvus support user to manage different database (note: not the collection),  you can pass in the db_name to connect different database using pymilvus. So I want to know, how can I access different database using llamaindex, so that I can insert different data into different database.

**Comment by logan-markewich** [comment]
@momocat-aric `db_name` is not a valid kwarg to milvus vector store. It seems like it might get passed in as part of kwargs, but I wouldn't be surprised if this wasn't supported properly

Feel free to checkout the source code
https://github.com/run-llama/llama_index/blob/ce5963486d8b99fa045659dbdb7bd1398d6b7da5/llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py#L173

**Comment by momocat-aric** [comment]
> @momocat-aric `db_name` is not a valid kwarg to milvus vector store. It seems like it might get passed in as part of kwargs, but I wouldn't be surprised if this wasn't supported properly
> 
> Feel free to checkout the source code
> 
> https://github.com/run-llama/llama_index/blob/ce5963486d8b99fa045659dbdb7bd1398d6b7da5/llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py#L173

Thanks for your reply.  
Yes, I debugged the code and found the db_name actually can be passed into MilvusClient class. But it still not work, that is weird. 

And I tried another way:  use "/" to concat the URI and db_name,  it works, like:
```
URI = "<URI>/<DB_NAME>"
vector_store = MilvusVectorStore(dim=N, uri=URI, overwrite=True)
```
