### ISSUE TITLE
[Feature Request]: Read binary data (bytes)

### ISSUE THREAD

**Issue by ihgumilar** [run-llama/llama_index#12878]
### Feature Description

When a user uploads PDF / txt/ csv files to a frontend, it will be turned to binary data (bytes). I am wondering if there is any method to read such binary data (bytes) ? I know that there is a connector that directly read the above listed types of file, but not the binary data (bytes). Is there a way to do that ?

### Reason
I want to work mostly with in-memory database. There will be no physical file that will be stored somewhere in a server.

_No response_

### Value of Feature

This can be useful, for those who don't want to store uploaded files into physical drive and want to work in-memory database, eg. redis. Sometime, an organization's policy for privacy may prevent developer to store any kinds of file in a cloud.

Thanks for your advice in advanced @logan-markewich

**Comment by rjzhb** [comment]
I have an idea. Firstly, from an overall perspective, we need two parameters: 
1 Binary data in memory 
2. File type
Based on these two conditions, we can restore the file

However, there is a challenge here, which is how to determine the type of file from binary data in memory (because during normal front-end and back-end interaction, there is a Content Type field, but this condition does not seem to exist in the llamaIndex scenario). To solve this problem, I think we can use **Python magic**, which is a parsing library that can guess the file format based on its content
The above are my thoughts. What do you think？

**Comment by rjzhb** [comment]
demo looks like this:
```
import magic

mime_to_extension = {
    'application/pdf': '.pdf',
    'image/jpeg': '.jpg',
    'text/plain': '.txt',
    # More mappings can be added here
}

# Create and read a file, then convert its content to binary
file_path_to_create = '../data/1.txt'
with open(file_path_to_create, 'w') as file:
    file.write("This is a test file. Let me test it.\nWith multiple lines of text.")

# Read file content and convert to binary data
with open(file_path_to_create, 'rb') as file:
    binary_data = file.read()

# Get MIME type from binary_data
mime_type = magic.from_buffer(binary_data, mime=True)
# Get file extension from the mapping table, defaulting to '.bin' if not found
file_extension = mime_to_extension.get(mime_type, '.bin')

# Create file name
file_name = f"restored_file{file_extension}"

# Create file under '../data/' directory
file_path = f"../data/{file_name}"

# Now, write the binary data to a file
with open(file_path, "wb") as file:
    file.write(binary_data)

print(f"File restored as {file_name}")
```
After running it, you will find that the binary data has been successfully restored

**Comment by ihgumilar** [comment]
Hi @rjzhb ,

Thanks a lot for your response. Let me try your suggestions. Once again, thanks a lot for this.

Cheers

**Comment by rjzhb** [comment]
@ihgumilar 
If you need, I believe I can incorporate this code snippet as a new interface in LLamaIndex.
@logan-markewich  What do you think of?

**Comment by ihgumilar** [comment]
That would be great @rjzhb to integrate it
