### ISSUE TITLE
[Question]: Jerry Liu: Summary Query Engine?

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#12875]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

![image](https://github.com/run-llama/llama_index/assets/64459173/5482c25b-c691-49e4-ae5d-4ade407125d1)

In this video he talks about a summary query engine and a vector query engine.

As per my understanding-:

1. Vector query engine would return a response as per the user question, depending on the top_k.
2. The summery query engine would summarize from my documents about my query, not the whole document, just stuff related to my query.

I can't find a dedicated summary query engine for that task, should I just use response_mode= tree_summarize? The tree_summarie thing doesn't return answers as per my satisfaction.

**Comment by logan-markewich** [comment]
I think specifically it's a summary index (which is just sending all the nodes to the LLM iteratively). Or you can directly use a response synthesizer for lower-level interactions

```python
index = SummaryIndex.from_documents(documents)
query_engine = index.as_query_engine(response_mode="tree_summarize")
response = query_engine.query("Summarize the provided text.")
```

Or more directly/low-level

```python
from llama_index.core.response_synthesizers import TreeSummarize

synth = TreeSummarize(llm=llm)
summary = synth.get_response("Summarize the provided text.", ["text1", "text2", ...])
```

**Comment by Aekansh-Ak** [comment]
index = SummaryIndex.from_documents(documents)

What is SummaryIndex here?

I am using an opensearch vector database, just to be clear.

**Comment by Aekansh-Ak** [comment]
For example-:

I have a detailed description of zoo animal activities and what they do everyday.

If I want a detailed summary of just the tiger and my query is "Summarise all the activities of a tiger", so it should just respond with tiger's detailed activities.

**Comment by logan-markewich** [comment]
@Aekansh-Ak 

```
from llama_index.core import SummaryIndex

index = SummaryIndex.from_documents(documents)

# or from nodes
index = SummaryIndex(nodes=nodes)
```

If you are using a vector db already, there isn't really a way to connect it besides retrieving all the nodes from the db and shoving it into this object

**Comment by Aekansh-Ak** [comment]
Thank you
