### ISSUE TITLE
[Bug]: QueryFusionRetriever skip BM25Retriever 

### ISSUE THREAD

**Issue by KelinTan** [run-llama/llama_index#12881]
### Bug Description

`
import json
import logging
import sys
from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
)
from llama_index.core.query_engine.router_query_engine import RouterQueryEngine
from llama_index.core.tools.query_engine import QueryEngineTool
from llama_index.retrievers.bm25 import BM25Retriever
from llama_index.core.retrievers import VectorIndexRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.retrievers import QueryFusionRetriever

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

DEFAULT_SUMMARY_TEXT = "Use this index for summarization queries"
DEFAULT_QA_TEXT = (
    "Use this index for queries that require retrieval of specific "
    "context from documents."
)

summary_index = load_index_from_storage(
    StorageContext.from_defaults(
        persist_dir="./storage/d5c5b6bba5a7422d88362e1835776ad3/summary"
    )
)
vector_index = load_index_from_storage(
    StorageContext.from_defaults(
        persist_dir="./storage/d5c5b6bba5a7422d88362e1835776ad3/vector"
    )
)

vector_retriever = VectorIndexRetriever(vector_index, similarity_top_k=2)
bm25_retriever = BM25Retriever.from_defaults(
    docstore=vector_index.docstore, similarity_top_k=2
)
query_fusion_retriever = QueryFusionRetriever(
    # [bm25_retriever, vector_retriever],
    [vector_retriever, bm25_retriever],
    similarity_top_k=2,
    num_queries=1,  # set this to 1 to disable query generation
    mode="reciprocal_rerank",
    use_async=False,
    verbose=True,
    # query_gen_prompt="...",  # we could override the query generation prompt here
)
hybrid_engine = RetrieverQueryEngine.from_args(retriever=query_fusion_retriever)
summary_query_engine = summary_index.as_query_engine(response_mode="tree_summarize")
router_engine = RouterQueryEngine.from_defaults(
    query_engine_tools=[
        QueryEngineTool.from_defaults(hybrid_engine, description=DEFAULT_QA_TEXT),
        QueryEngineTool.from_defaults(
            summary_query_engine, description=DEFAULT_SUMMARY_TEXT
        ),
    ],
    select_multi=False,
)

query = "What is the registration interface"
response = router_engine.query(query)
logging.info(f"Query response: {response}")

`

### Version

0.10.27

### Steps to Reproduce

Just changes the retrievers order:

-     [vector_retriever, bm25_retriever]: waring log: WARNING:llama_index.retrievers.bm25.base:BM25Retriever does not support embeddings, skipping...

-     [bm25_retriever, vector_retriever]: fine

### Relevant Logs/Tracbacks

```shell
waring log: WARNING:llama_index.retrievers.bm25.base:BM25Retriever does not support embeddings, skipping...
```

**Comment by KelinTan** [comment]
[https://github.com/run-llama/llama_index/blob/9e40a9de4058728bf1b99f8613903bd022db210a/llama-index-core/llama_index/core/retrievers/fusion_retriever.py#L249](url)
https://github.com/run-llama/llama_index/blob/9e40a9de4058728bf1b99f8613903bd022db210a/llama-index-core/llama_index/core/indices/vector_store/retrievers/retriever.py#L96

Guess this is the key code

**Comment by logan-markewich** [comment]
It didn't skip, it just ignored any embeddings attached to the query bundle

**Comment by logan-markewich** [comment]
I can almost guarantee it ran retrieval over bm25 and any other retriever you added

**Comment by logan-markewich** [comment]
The warning message could maybe be changed, but not a bug. Feel free to open a pr
