### ISSUE TITLE
[Bug]: Node Parsing error with Qdrant and Llama Index query engine

### ISSUE THREAD

**Issue by Prathit-tech** [run-llama/llama_index#12891]
### Bug Description

I have a query engine built  for a vector store in Qdrant, i have uploaded the embeddings in qdrant and now i just want to query it. I get errors with Node parsing: 
a similar error was raised previously but the documentation solving that has expired and i was looking for a solution to this

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant/base.py](https://localhost:8080/#) in parse_to_query_result(self, response)
    748 
--> 749     def _build_query_filter(self, query: VectorStoreQuery) -> Optional[Any]:
    750         if not query.doc_ids and not query.query_str:

14 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/core/vector_stores/utils.py](https://localhost:8080/#) in metadata_dict_to_node(metadata, text)
     69     if node_json is None:
---> 70         raise ValueError("Node content not found in metadata dict.")
     71 

ValueError: Node content not found in metadata dict.

During handling of the above exception, another exception occurred:

ValidationError                           Traceback (most recent call last)
[<ipython-input-24-84c1668e468c>](https://localhost:8080/#) in <cell line: 2>()
      1 query_engine = index.as_query_engine(verbose=True,node_parser= SimpleNodeParser.from_defaults(chunk_size=512, chunk_overlap=32))
----> 2 res = query_engine.query("hello")

[/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py](https://localhost:8080/#) in wrapper(func, instance, args, kwargs)
    272             )
    273             try:
--> 274                 result = func(*args, **kwargs)
    275             except BaseException as e:
    276                 self.event(SpanDropEvent(span_id=id_, err_str=str(e)))

[/usr/local/lib/python3.10/dist-packages/llama_index/core/base/base_query_engine.py](https://localhost:8080/#) in query(self, str_or_query_bundle)
     51             if isinstance(str_or_query_bundle, str):
     52                 str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 53             query_result = self._query(str_or_query_bundle)
     54         dispatch_event(QueryEndEvent())
     55         return query_result

[/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py](https://localhost:8080/#) in wrapper(func, instance, args, kwargs)
    272             )
    273             try:
--> 274                 result = func(*args, **kwargs)
    275             except BaseException as e:
    276                 self.event(SpanDropEvent(span_id=id_, err_str=str(e)))

[/usr/local/lib/python3.10/dist-packages/llama_index/core/query_engine/retriever_query_engine.py](https://localhost:8080/#) in _query(self, query_bundle)
    187             CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    188         ) as query_event:
--> 189             nodes = self.retrieve(query_bundle)
    190             response = self._response_synthesizer.synthesize(
    191                 query=query_bundle,

[/usr/local/lib/python3.10/dist-packages/llama_index/core/query_engine/retriever_query_engine.py](https://localhost:8080/#) in retrieve(self, query_bundle)
    142 
    143     def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
--> 144         nodes = self._retriever.retrieve(query_bundle)
    145         return self._apply_node_postprocessors(nodes, query_bundle=query_bundle)
    146 

[/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py](https://localhost:8080/#) in wrapper(func, instance, args, kwargs)
    272             )
    273             try:
--> 274                 result = func(*args, **kwargs)
    275             except BaseException as e:
    276                 self.event(SpanDropEvent(span_id=id_, err_str=str(e)))

[/usr/local/lib/python3.10/dist-packages/llama_index/core/base/base_retriever.py](https://localhost:8080/#) in retrieve(self, str_or_query_bundle)
    242                 payload={EventPayload.QUERY_STR: query_bundle.query_str},
    243             ) as retrieve_event:
--> 244                 nodes = self._retrieve(query_bundle)
    245                 nodes = self._handle_recursive_retrieval(query_bundle, nodes)
    246                 retrieve_event.on_end(

[/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py](https://localhost:8080/#) in wrapper(func, instance, args, kwargs)
    272             )
    273             try:
--> 274                 result = func(*args, **kwargs)
    275             except BaseException as e:
    276                 self.event(SpanDropEvent(span_id=id_, err_str=str(e)))

[/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/vector_store/retrievers/retriever.py](https://localhost:8080/#) in _retrieve(self, query_bundle)
     99                     )
    100                 )
--> 101         return self._get_nodes_with_embeddings(query_bundle)
    102 
    103     @dispatcher.span

[/usr/local/lib/python3.10/dist-packages/llama_index/core/indices/vector_store/retrievers/retriever.py](https://localhost:8080/#) in _get_nodes_with_embeddings(self, query_bundle_with_embeddings)
    175     ) -> List[NodeWithScore]:
    176         query = self._build_vector_store_query(query_bundle_with_embeddings)
--> 177         query_result = self._vector_store.query(query, **self._kwargs)
    178         return self._build_node_list_from_query_result(query_result)
    179 

[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant/base.py](https://localhost:8080/#) in query(self, query, **kwargs)
    598                 query_filter=query_filter,
    599             )
--> 600             return self.parse_to_query_result(response)
    601 
    602     async def aquery(

[/usr/local/lib/python3.10/dist-packages/llama_index/vector_stores/qdrant/base.py](https://localhost:8080/#) in parse_to_query_result(self, response)
    755         if query.doc_ids:
    756             must_conditions.append(
--> 757                 FieldCondition(
    758                     key="doc_id",
    759                     match=MatchAny(any=query.doc_ids),

[/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py](https://localhost:8080/#) in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for TextNode
text
  none is not an allowed value (type=type_error.none.not_allowed)

### Version

0.10.29

### Steps to Reproduce

vector_store = QdrantVectorStore(client=client, collection_name="..")#add collection name
storage_context = StorageContext.from_defaults(vector_store = vector_store)
query_engine = index.as_query_engine(verbose=True)
res = query_engine.query("hello") This is the code i use, i havent loaded the documents, because someone else has already uploaded the embeddings to Qdrant

**Comment by logan-markewich** [comment]
@Prathit-tech if you didn't populate the qdrant vector store using llama-index, you need to ensure it has a few key fields

If its missing a text field, then it won't work 

Notice that if the index wasn't created with llama-index, It uses some fallback logic, but it needs that text field or else this error happens
<img width="719" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/1a53f185-2d54-47be-b774-09695c40cabd">
