### ISSUE TITLE
[Documentation]: 

### ISSUE THREAD

**Issue by schkovich** [run-llama/llama_index#12892]
### Documentation Issue Description

The link on the line 
- integrations have separate `pip install`s (See the [full registry](https://pretty-sodium-5e0.notion.site/ce81b247649a44e4b6b35dfb24af28a6?v=53b3c2ced7bb4c9996b81b83c9f01139))
is broken.

> The page you are looking for cannot be found!
Please ask the owner of the page for an updated link. 

### Documentation Link

https://github.com/run-llama/llama_index/blob/main/docs/docs/getting_started/v0_10_0_migration.md

**Comment by logan-markewich** [comment]
Ah yea, our notion did some update that broke some links -- the most up to date registry is actually just https://llamahub.ai

**Comment by schkovich** [comment]
I updated the link. https://github.com/run-llama/llama_index/compare/main...schkovich:llama_index:patch-2
