### ISSUE TITLE
[Question]: I can't continue with the custom RAG CLI

### ISSUE THREAD

**Issue by avalonliberty** [run-llama/llama_index#12906]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I've followed the custom CLI instruction step by step; but I failed to run the cli in my end. Here are the screenshots about the python I used and the python file in the path variable. Is there anything I missed so that I couldn't set up the custom RAG CLI?
<img width="362" alt="Screenshot 2024-04-18 110033" src="https://github.com/run-llama/llama_index/assets/34063554/6114dc71-d304-4803-950b-58a20ad22d7f">
<img width="356" alt="Screenshot 2024-04-18 105955" src="https://github.com/run-llama/llama_index/assets/34063554/8f008805-7aa2-4544-a718-7e7fb7089587">
<img width="436" alt="Screenshot 2024-04-18 110100" src="https://github.com/run-llama/llama_index/assets/34063554/496d011c-8187-418c-996f-048cd7040943">

**Comment by logan-markewich** [comment]
You have to run the script with python I think

`python ./ollama-index_cli.py -h`

**Comment by avalonliberty** [comment]
@logan-markewich Yeah, you are right. I purely followed the instruction there so I forgot to add a python at the beginning

**Comment by avalonliberty** [comment]
The instruction does not include a "python" command at the beginning so that make sure you have it when you run your cli py file
