### ISSUE TITLE
[Feature Request]: The supporting of "Retrieve in embedding mode" in KnowledgeGraphRAGRetriever

### ISSUE THREAD

**Issue by PHD-lanyu** [run-llama/llama_index#12914]
### Feature Description

Graph RAG is a very powerful weapon, but currently, "Retrieve in embedding mode"  is not supported in the latest version, looking forward to adding this feature in the next version, thank you very much!
<img width="861" alt="image" src="https://github.com/run-llama/llama_index/assets/95006080/2d03b835-474e-4237-8e4b-af7b833eadd8">

**Comment by Manel-Hik** [comment]
Hi @PHD-lanyu 
I'm trying to implement graph rag for a simple rag pipeline, Could you share with me a tuto for this?
thanks in advance

**Comment by PHD-lanyu** [comment]
@Manel-Hik This [official document](https://docs.llamaindex.ai/en/v0.10.23/examples/query_engine/knowledge_graph_rag_query_engine/) may be helpful to you!
