### ISSUE TITLE
[Question]: TextEmbeddingsInference installation installs torch and cuda 

### ISSUE THREAD

**Issue by erik-squared** [run-llama/llama_index#12945]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am working with TextEmbeddingsInference, and was surprised that:

`pip install llama-index-embeddings-text-embeddings-inference`

installs torch, cuda, etc. This seems excessive since when using TEI embeddings run in a server?

**Comment by logan-markewich** [comment]
Yea it uses some utils from `llama-index-embeddings-huggingface` -- probably those should be moved to some generic huggingface utils package/file

**Comment by dbkinghorn** [comment]
I saw this too and thought I had made a mistake. I blew away my env and started over. 
When you consider that a one line curl command will access the server and return the embeddings it seems crazy.  
I don't want to create a custom embedding class for this so I'll use it for now, but hope it gets fixed.

Llamaindex is very cool but could use some optimization :-)

**Comment by logan-markewich** [comment]
I welcome a PR @dbkinghorn 😉
