### ISSUE TITLE
[Bug]: llama3 cookbook

### ISSUE THREAD

**Issue by kovtcharov** [run-llama/llama_index#12950]
### Bug Description

When running the snippet below from the [cookbook](https://docs.llamaindex.ai/en/latest/examples/cookbooks/llama3_cookbook/):
```
from llama_index.llms.huggingface import HuggingFaceLLM

llm = HuggingFaceLLM(
    model_name="meta-llama/Meta-Llama-3-8B-Instruct",
    generate_kwargs={
        "do_sample": True,
        "temperature": 0.6,
        "top_p": 0.9,
    },
    tokenizer_name="meta-llama/Meta-Llama-3-8B-Instruct",
    stopping_ids=stopping_ids,
)
```
I get the following error:
```
Make sure to have access to it at https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct.
401 Client Error. (Request ID: Root=1-6621d34c-6fc12d59548f9da96676265d;ba825de0-4dcf-4529-85b6-cc85d6560bd4)

Cannot access gated repo for url https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct/resolve/main/config.json.
Repo model meta-llama/Meta-Llama-3-8B-Instruct is gated. You must be authenticated to access it.
```
It seems I need to set the HF token, but the class does not support it.

### Version

0.10.20

### Steps to Reproduce

run cookbook example here: https://docs.llamaindex.ai/en/latest/examples/cookbooks/llama3_cookbook/, do not pass a hf token.

**Comment by logan-markewich** [comment]
The class does support it

HuggingFaceLLM(... model_kwargs={"token": hf_token})

Once you do it once, it gets cached.

You can also load the model and/or tokenizer outside of llamaindex and just pass it in

HughingfaceLLM(model=model, tokenizer=tokenizer, ...)
