### ISSUE TITLE
[Question]: Error: Statement "{sql query}" is invalid SQL

### ISSUE THREAD

**Issue by Aniket-ByteIQ** [run-llama/llama_index#12979]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

While implementing a simple NLSQLTableQueryEngine on PostgreSQL DB I was facing this issue:
**SQL query:** {'sql_query': 'sql\nSELECT\n  COUNT(*) AS num_movies\nFROM movieRatings;'}
**Response:** Error: Statement 'sql\nSELECT\n  COUNT(*) AS num_movies\nFROM movieRatings;' is invalid SQL.

Apparently it was generating additional "sql\n" term while working with Gemini Pro model, after managing it by modifying the prompt template it sometimes shows correct SQL query and sometimes it doesn't. Even when the SQL query is completely correct, it shows response as:
**Error: Statement 'SELECT COUNT(*) FROM movieRatings' is invalid SQL.**

**Comment by tomasemilio** [comment]
After a lot of digging I think I found the issue:
`llama_index.core.utilities.sql_wrapper`
the function: run_sql.

If you specify schema then how they do replacements is just wrong.
```python
 if self._schema:
        command = command.replace("FROM ", f"FROM {self._schema}.")
        command = command.replace("JOIN ", f"JOIN {self._schema}.")
```   
This is not right.

**Comment by saccpp** [comment]
Any resolution for this issue, I am still facing the same error.

**Comment by damico** [comment]
I also have the same problem ==> NotImplementedError: Statement 'sql\nSELECT, the query is written with sql\n in the beginning and even adding to the default query prompt instructions to avoid it, it stills add this typo. @dosu

**Comment by damico** [comment]
I've just fixed the problem using **parse_response_to_sql** function, adding  **response = response.replace("```sql\n", "")** at the end, before the return.

```
def parse_response_to_sql(response: ChatResponse) -> str:
    """Parse response to SQL."""
    response = response.message.content
    sql_query_start = response.find("SQLQuery:")
    if sql_query_start != -1:
        response = response[sql_query_start:]
        # TODO: move to removeprefix after Python 3.9+
        if response.startswith("SQLQuery:"):
            response = response[len("SQLQuery:") :]
    sql_result_start = response.find("SQLResult:")
    if sql_result_start != -1:
        response = response[:sql_result_start]

    response = response.replace("```sql\n", "")
    return response.strip().strip("```").strip()
```
