### ISSUE TITLE
[Bug]: CodeHierarchyQuery Engine doing redundant operations & not finding heirarchical nodes

### ISSUE THREAD

**Issue by 345ishaan** [run-llama/llama_index#12981]
### Bug Description

The following lines of code are redundant:
https://github.com/run-llama/llama_index/blob/954398e1957027a364d0d332fee61733ad322f8b/llama-index-packs/llama-index-packs-code-hierarchy/llama_index/packs/code_hierarchy/query_engine.py#L116-L121

1) We are doing DFS to find all kvs from the root_map 
2) Then we are again doing DFS to find if there is any exact match.

Instead the kvs should be made from self.node_dict and DFS should be happening on the self.root_map

cc @logan-markewich 

### Version

Latest

### Steps to Reproduce

NA

**Comment by logan-markewich** [comment]
Feel free to make a pr @345ishaan 👍

**Comment by 345ishaan** [comment]
> Feel free to make a pr @345ishaan 👍

I have created a PR here: https://github.com/run-llama/llama_index/pull/12983 but I think the current behavior is correct and we should remove the unncessary DFS logic. 

Maybe the owner of the this llama-pack can shed some light on what was the reason for doing this.
