### ISSUE TITLE
[Feature Request]: Change OpenAI default embedding model from "text-embedding-ada-002" to "text-embedding-3-small"

### ISSUE THREAD

**Issue by dsanr** [run-llama/llama_index#12994]
### Feature Description

text-embedding-3-small model is better and less costly than the text-embedding-ada-002 model. So, it is beneficial to make the former model default.
https://openai.com/blog/new-embedding-models-and-api-updates
https://openai.com/pricing

**Comment by logan-markewich** [comment]
@dsanr this would be a giant breaking change. Probably this should be 

a) saved for a larger version bump
b) properly communicated ahead of time to users

**Comment by dsanr** [comment]
@logan-markewich They both have the same dimensionality of 1536. Are there any other reasons why this would be a giant breaking change?

**Comment by justinzyw** [comment]
I tried to replace adda with 3-small and found that they are not compatible even if the dimensionality is the same. ie, all users created indexes using default ada will find their queries behave quite differently using default 3-small.

**Comment by logan-markewich** [comment]
@justinzyw is correct. It's not the dimension that matters so much, they are trained on completely different data. Vectors created with Ada are in a completely different vector space compared to small-3

**Comment by dsanr** [comment]
@justinzyw Thanks for trying it out.
@logan-markewich Yeah, in this case, we can only take up this in any next major release.
