### ISSUE TITLE
Error while importing OpenAI from llama_index.llms

### ISSUE THREAD

**Issue by nbibin001** [run-llama/llama_index#13001]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am getting the below error while trying to follow the code explained in the Youtube video (https://www.youtube.com/watch?v=WL7V9JUy2sE) . Could you please help and let me know what am I missing
![image](https://github.com/run-llama/llama_index/assets/15659590/edec4dec-a638-405e-b321-809321b9bf6c)

**Comment by logan-markewich** [comment]
@nbibin001 it's `from llama_index.llms.openai import OpenAI`

Since every integration (including llms) is a separate namepsaced package, you need a more complete import
