### ISSUE TITLE
[Question]: OpenAIEmbedding Auth

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#13004]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`OpenAIEMbedding` is complaining about no api_key? Why isn't it using api_key param, like other classes? I'm feeding it the same OpenAI key that works fine for actual models. The models work fine. 

```
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******
```

The documentation doesn't even show use of the API key like models, yet is clearly very much needed.

**Comment by logan-markewich** [comment]
It does use api_key param

But you probably are missing some place to pass it in and it's defaulting to one without the key? Code sample to replicate?

**Comment by logan-markewich** [comment]
For example, this will work fine

```
embed_model = OpenAIEmbedding(api_key="sk-...")

embedding = embed_model.get_text_embedding("hello world")
```

I would just set it as a global

```
from llama_index.core import Settings

Settings.embed_model = embed_model 
```

Or ensure it's passed it

`VectorStoreIndex(..., embed_model=embed_model)`

**Comment by WAS-PlaiLabs** [comment]
> For example, this will work fine
> 
> ```
> embed_model = OpenAIEmbedding(api_key="sk-...")
> 
> embedding = embed_model.get_text_embedding("hello world")
> ```
> 
> I would just set it as a global
> 
> ```
> from llama_index.core import Settings
> 
> Settings.embed_model = embed_model 
> ```
> 
> Or ensure it's passed it
> 
> `VectorStoreIndex(..., embed_model=embed_model)`

Oh jeez. I feel silly. I still had the actual embedding I was loading commented out on the vector index node. >.<

**Comment by WAS-PlaiLabs** [comment]
Does TreeIndex really not use an `embed_model` param? It appears missing and seems the only way to get it to the `TreeIndex` is `service_context` that is deprecated?

**Comment by logan-markewich** [comment]
Tree index does not use an embed model during construction 

The tree index has several retrievers though, some of which use an embedding model. Soy you can pass it in during retriever/query engine construction

`index.as_query_engine(..., embed_model=embed_model)`

**Comment by logan-markewich** [comment]
as_query_engine() works by calling as_retriever() and then constructing a retriever query engine.

https://github.com/run-llama/llama_index/blob/f116d75557d6867ed2cc61811a1c2f0b0c4d4ddb/llama-index-core/llama_index/core/indices/tree/base.py#L104

**Comment by WAS-PlaiLabs** [comment]
Oh ok, that makes sense. Thanks a lot. Got these working again off new structure.

**Comment by WAS-PlaiLabs** [comment]
Does TreeIndex really not use an `embed_model` param? It appears missing and seems the only way to get it to the `TreeIndex` is `service_context` that is deprecated?
