### ISSUE TITLE
[Question]: How to add nodes from IngestionPipeline to VectorStore asyncronously?

### ISSUE THREAD

**Issue by Turkzilla** [run-llama/llama_index#13010]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I keep getting either `One of nodes, objects, or index_struct must be provided.` error or `An asyncio.Future, a coroutine or an awaitable is required` What is the right way to `upsert` a node coming out of IngestionPipeline?

Snippet:
```
aclient = AsyncQdrantClient(
      url="http://localhost", port=6333, grpc_port=6334, prefer_grpc=True)
      
  vector_store = QdrantVectorStore(
      aclient=aclient, collection_name=collection_name, batch_size=20)
  storage_context = StorageContext.from_defaults(
      vector_store=vector_store)
  # Transformations here
  pipeline = IngestionPipeline(transformations=[
                               text_splitter, title_extractor, summary_extractor, qa_extractor, entity_extractor])
  nodes = await pipeline.arun(documents=documents, storage_context=storage_context, show_progress=True)
  vector_index = VectorStoreIndex(
      storage_context=storage_context, use_async=True)
  for node in nodes:
      content = node.get_content(metadata_mode=MetadataMode.EMBED)
      # embedding and metadata added here
      node.metadata.update(metadata)
      node.embedding = embedding

      await vector_index.add_node(node)
```

**Comment by logan-markewich** [comment]
await vector_store.async_add(node)

**Comment by Turkzilla** [comment]
@logan-markewich : Thank you for answering. Are you suggesting I bypass `storage_context` and directly add via instance of `vector_store`?

**Comment by Turkzilla** [comment]
@dosu-bot: Any suggestions?

**Comment by logan-markewich** [comment]
@Turkzilla you certainly can, I was just going off of your code snippet

**Comment by Turkzilla** [comment]
@logan-markewich : I tested with and without. Your suggestion did not work.

**Comment by Turkzilla** [comment]
My pipeline needs to run in an async function. I already tried running without `await` and got `An asyncio.Future, a coroutine or an awaitable is required`. I tried various methods from VectoreStoreIndex base but none worked. Is there an async alternative to `build_index_from_nodes`?

**Comment by Turkzilla** [comment]
@dosu-bot: Doing that just hit a dead-end: `'NoneType' object has no attribute 'get_collection'`

**Comment by logan-markewich** [comment]
@Turkzilla how did my suggestion not work? Any errors you received would have been helpful.

I wouldn't listen to the bot here... 😅

Skimming the previous attempts, Make sure you pass both a client and aclient for qdrant

`QdrantVectorStore(..., client=QdrantClient(..), aclient=AsyncQdrantClient(...))`

**Comment by Turkzilla** [comment]
@logan-markewich : The error I was getting was: `'VectorStoreIndex' object has no attribute 'async_add'`. But your suggestion to pass a client and aclient, definitely took care of previous errors. I am now getting `Wrong input: Not existing vector name error: text-sparse-new` from qdrant. What am I missing or does this mean there is a mis-alignment with llamaindex and qdrant vector store? (and does it seem to be attempting a sparse vector? )
