### ISSUE TITLE
[Feature Request]: Add streaming for OpenAIAssistantAgent

### ISSUE THREAD

**Issue by tioans** [run-llama/llama_index#13015]
### Feature Description

The OpenAI Assistant API now supports [streaming](https://platform.openai.com/docs/assistants/overview?context=with-streaming), it would be great to also support this feature via the `OpenAIAssistantAgent` wrapper. 

### Reason

Currently, the LlamaIndex agent only supports standard message passing via chats. There seems to be some functionality for `async` conversations, but it is not implemented.

### Value of Feature

Having this feature available to use with agents will significantly improve the user experience, especially for complex iterations that require more processing.

**Comment by justinzyw** [comment]
+1 this would be very useful

**Comment by naingthet** [comment]
I'd love to take a look at this if there's interest? @logan-markewich

**Comment by logan-markewich** [comment]
Definitely @naingthet go for it! It's been on my today list to update the openai assistant, since it's basically broken right now 😅

**Comment by naingthet** [comment]
Awesome! This would be my first contribution, so it may take me a bit to get oriented with the process. If anyone else is able to get to it before me, please feel free!

**Comment by mpereira** [comment]
FTR I'm giving this a go. Will maybe open a PR within the next day or so.

**Comment by mpereira** [comment]
I have a working implementation here: https://github.com/mpereira/llama_index/pull/2/files

Still not ready to upstream I think. Would still need to figure out how to make `OpenAIAssistantAgent.stream_chat` return a `StreamingAgentChatResponse` instead of an `Iterator[AssistantStreamEvent]`.
