### ISSUE TITLE
Raw response content: b'{"status":{"error":"Wrong input: Not existing vector name error: "},"time":0.030060406}'

### ISSUE THREAD

**Issue by Zeeshan0123** [run-llama/llama_index#13020]
### Bug Description

i am getting this error i dont khow how to solve this

### Version

new version

### Steps to Reproduce

from qdrant_client import QdrantClient
from llama_index.vector_stores.qdrant import QdrantVectorStore
from llama_index.storage.storage_context import StorageContext
from llama_index import VectorStoreIndex

# Initialize the Qdrant client
client = QdrantClient(url="http://localhost:6333/dashboard", prefer_grpc=False, timeout=100)

# Specify the collection name
collection_name = "med_embeddings"

# Check if the collection exists
if not client.collection_exists(collection_name):
    # If the collection doesn't exist, create it
    client.create_collection(
        collection_name=collection_name,
        vectors_config={
            "base_nodes": models.VectorParams(size=786, distance=models.Distance.DOT),
            "objects": models.VectorParams(size=786, distance=models.Distance.COSINE),
        }
    )

# Initialize the Qdrant vector store
vector_store = QdrantVectorStore(client=client, collection_name=collection_name, embed_model=embed_model)

# Get the nodes from the documents
node_parser = MarkdownElementNodeParser(llm=None, num_workers=8)
nodes = node_parser.get_nodes_from_documents(documents, progress=True)

# Get the storage context
st = StorageContext.from_defaults(vector_store=vector_store)

# Get the base nodes and objects
base_nodes, objects = node_parser.get_nodes_and_objects(nodes)

# Create the index
recursive_index = VectorStoreIndex(nodes=base_nodes+objects, storage_context=st)

**Comment by logan-markewich** [comment]
@Zeeshan0123 I believe I fixed this, just update the package

`pip install -U llama-index-vector-stores-qdrant`
