### ISSUE TITLE
[Bug]: return_direct not working with openai agent

### ISSUE THREAD

**Issue by jhavlicek91** [run-llama/llama_index#13025]
### Bug Description

After setting `return_direct` to True for tools being used with the openai agent, the tools get called, but the agent still runs steps beyond the tools response.

The `return_direct` functionality was released with version 0.10.28 of `llama_index_core`, but an updated version of `llama-index-agent-openai` hasn't been released since [#12587](https://github.com/run-llama/llama_index/pull/12587) was merged in.

### Version

0.10.30

### Steps to Reproduce

Run the openai agent passing in tools with `return_direct` set to true

**Comment by logan-markewich** [comment]
v0.2.3 will be published after this merges, thanks for the heads up
https://github.com/run-llama/llama_index/pull/13026

**Comment by jhavlicek91** [comment]
Great, thanks for the quick response
