### ISSUE TITLE
[Question]: What do PromptTypes actually do?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#13030]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I know `llama_index.core.prompts.PromptType` is an enum, but what is it actually meant to be used for?  Why not just let the prompt content/message itself determine the LLM behavior?  

Presumably, there is some check somewhere in the code for it, but if I am effectively just writing custom query engines through the query pipeline interface and, in so doing, using `InputComponent` or `PromptTemplate`, does it remain applicable?

The [PromptTemplate usage guide](https://docs.llamaindex.ai/en/stable/module_guides/models/prompts/usage_pattern/) does not touch upon it.

**Comment by logan-markewich** [comment]
They are used under the hood for unit testing and mapping prompts to some expected output

They aren't mentioned in the docs because they aren't really meant to be used by users 😉
