### ISSUE TITLE
[Bug]: HuggingfaceEmbeddings cant find config.json

### ISSUE THREAD

**Issue by UniZeugNick** [run-llama/llama_index#13035]
### Bug Description

the code from the documentation doesn't seem to work.
https://docs.llamaindex.ai/en/stable/examples/embeddings/Langchain/

"""
from langchain.embeddings import HuggingFaceEmbeddings
from llama_index.embeddings.langchain import LangchainEmbedding

lc_embed_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)
embed_model = LangchainEmbedding(lc_embed_model)
"""

it also doesn't work with the llama-index-embeddings-huggingface module, not just the one from Langchain. 

This is probablly an issue with huggingface itself because it loads the model but maybe someone here has an anwser.

### Version

v.0.10

### Steps to Reproduce

from langchain.embeddings import HuggingFaceEmbeddings
from llama_index.embeddings.langchain import LangchainEmbedding

lc_embed_model = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-mpnet-base-v2"
)
embed_model = LangchainEmbedding(lc_embed_model)

### Relevant Logs/Tracbacks

```shell
modules.json: 100%
 349/349 [00:00<00:00, 25.2kB/s]
config_sentence_transformers.json: 100%
 252/252 [00:00<00:00, 16.3kB/s]
WARNING:sentence_transformers.SentenceTransformer:You try to use a model that was created with version 2.7.0.dev0, however, your version is 2.7.0. This might cause unexpected behavior or errors. In that case, try to update to the latest version.



README.md: 100%
 83.9k/83.9k [00:00<00:00, 3.84MB/s]
sentence_bert_config.json: 100%
 107/107 [00:00<00:00, 7.39kB/s]
config.json: 100%
 738/738 [00:00<00:00, 46.2kB/s]
model.safetensors: 100%
 436M/436M [00:04<00:00, 82.4MB/s]
tokenizer_config.json: 100%
 1.38k/1.38k [00:00<00:00, 85.2kB/s]
vocab.txt: 100%
 232k/232k [00:00<00:00, 13.1MB/s]
tokenizer.json: 100%
 712k/712k [00:00<00:00, 3.16MB/s]
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-31-aaec20aedf5c> in <cell line: 5>()
      3 from llama_index.embeddings.langchain import LangchainEmbedding
      4 
----> 5 lc_embed_model = HuggingFaceEmbeddings(
      6     model_name="Snowflake/snowflake-arctic-embed-m"
      7 )

3 frames
/usr/local/lib/python3.10/dist-packages/sentence_transformers/models/Pooling.py in load(input_path)
    225     @staticmethod
    226     def load(input_path):
--> 227         with open(os.path.join(input_path, "config.json")) as fIn:
    228             config = json.load(fIn)
    229 

FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/huggingface/hub/models--Snowflake--snowflake-arctic-embed-m/snapshots/2169d312a6791367e67bb4087dba155819948a6e/1_Pooling/config.json'
special_tokens_map.json: 100%
 695/695 [00:00<00:00, 41.2kB/s]
```

**Comment by logan-markewich** [comment]
@UniZeugNick Your example and traceback do not match. Either way, both models work for me.

Maybe try updating? `pip install -U llama-index-embeddings-huggingface`

https://colab.research.google.com/drive/1NKAPndSL8jkh1jnTwYicFCxgo-cimjS_?usp=sharing

**Comment by UniZeugNick** [comment]
Oh, I see, I tried some different models and they all hat the same mistake. But it looks like that there was an issue with HF.
