### ISSUE TITLE
[Question]: OpenAIAgent.from_tools not working with streamlit, works fine outside it. 

### ISSUE THREAD

**Issue by ahmedrabbani** [run-llama/llama_index#13040]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have created a text to sql agent using OpenAIAgent.from_tools method, where my only tool is an sql tool defined by SQLTableRetrieverQueryEngine. The agent works fine while using .query method in a notebook but does not work properly in a streamlit app.

As per the debugging, the agent sends the same input to the underlying sql_tool both when executed using a notebook or via the streamlit app. But it does not get the same output from the sql_tool. 

Just wondering if anyone else faced this issue. Any kind of guidance is appreciated. Thank you.

**Comment by logan-markewich** [comment]
Can you give more details? Is it writing the same sql query? Is it returning a response? 


It could just be variation when you have different sql data or different embeddings. Or different llm responses depending on temperature.

Other than that, I wouldn't expect any difference

**Comment by ahmedrabbani** [comment]
**Notebook**
Description: Using chat/query/chat_repl methods

User prompt to sql_agent: What is the price of the Mechanical Keyboard?
Input to sql_tool: SELECT price FROM products WHERE name = 'Mechanical Keyboard
Output from sql_tool: The price of the Mechanical Keyboard is $45.2.
Out from sql_agent: The price of the Mechanical Keyboard is $45.2.

**Streamlit**
Description: Chat agent is defined as st.session_state["chat_agent"] = get_chat_agent(), where get_chat_agent returns the sql_agent provided with sql_tool

User prompt to sql_agent: What is the price of the Mechanical Keyboard?
Input to sql_tool: SELECT price FROM products WHERE name = 'Mechanical Keyboard
Output from sql_tool: I'm sorry, but there was an error in the SQL statement. Please check the syntax and try again.
Out from sql_agent: I'm sorry, but there was an error in the SQL statement. Please check the syntax and try again.

**Comment by logan-markewich** [comment]
Seems like maybe a difference in installed dependencies? Thats my best guess

**Comment by ahmedrabbani** [comment]
So both notebook and streamlit files are being run in the same python environment.
