### ISSUE TITLE
[Bug]: Unable to view token counts from Bedrock LLM instance and phoenix Observability

### ISSUE THREAD

**Issue by chaitanya-nit** [run-llama/llama_index#13046]
### Bug Description

I am unable to see token counts for LLM models instantiated using Bedrock class. I am using phoenix as Observability tool.

### Version

0.10.20

### Steps to Reproduce

You can use the starter 5 lines code to reproduce this.
import phoenix as px
from llama_index.core import set_global_handler
from llama_index.llms.bedrock import Bedrock
from llama_index.core import Settings

session = px.launch_app()
set_global_handler("arize_phoenix")
profile_name = "Your aws profile name"
llm= Bedrock(
    model="amazon.titan-text-express-v1", profile_name=profile_name
)
Settings.llm = llm
llm.complete("What is the capital of france?")

**Comment by chaitanya-nit** [comment]
@dosu I am aware that the token counting handler is sufficient for estimating the token counts. But this issue is related to arize_phoenix observability integration is not working with Bedrock models of llama-index. Hope you got the context now.

**Comment by bhavesh-kf** [comment]
I am getting following error:
ImportError: cannot import name 'CallbackManager' from 'llama_index.core' 

(llama-index : Version: 0.11.1)
