### ISSUE TITLE
[Question]: Can the FAISS index speed up the retrieval of a specified retriever (Like BM25)? Why using as_query_engine is much more faster than using a specified retriever?

### ISSUE THREAD

**Issue by TianyuFan0504** [run-llama/llama_index#13054]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have two indices, one (index1) is stored in FAISS index, and the other (index2) is stored in naive Vector Store Index:

```
documents = SimpleDirectoryReader("../datasets").load_data()
vector_store = FaissVectorStore(faiss_index=faiss_index)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index1 = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context
)

nodes = Settings.node_parser.get_nodes_from_documents(documents,show_progress = True)
index2 = VectorStoreIndex(nodes,include_embeddings=True)
```

However, when I use BM25 retriever on them, the time they consumed is comparable:

```
retriever = BM25Retriever.from_defaults(
    index=index1,
    similarity_top_k=10,
    verbose= True,
)
query = "What is the name of the archetype of the god worshipped in the city of Amathus on Cyprus?"
nodes_retrieved1 = retriever.retrieve(query)#Consume 10m27s



retriever = BM25Retriever.from_defaults(
    index=index2,
    similarity_top_k=10,
    verbose= True,
)
query = "What is the name of the archetype of the god worshipped in the city of Amathus on Cyprus?"
nodes_retrieved2 = retriever.retrieve(query)#Consume 10m20s
```

But if I use index.as_query_engine(), the speed is much more faster:
```
query_engine = index1.as_query_engine()
response1 = query_engine.query(query)#Consume 3.7s
```

In my understanding, `as_query_engine` is actually the wrapped default retriever. Why is there such a big difference in speed between the two of them?

Can I use the specified retriever+faiss index to achieve the same speed as using `as_query_engine`?

**Comment by logan-markewich** [comment]
🤷🏻 These aren't exactly comparable

BM25 is not using your vector store. It's just loading all your nodes into memory, calculating the sparse embeddings with BM25s algorithm, and then running some pairwise comparison on query against all your nodes (this is using the `rank_bm25` library under the hood).

Whereas `as_query_engine()` will be doing both a retrieval and at least 1 LLM call. (if you just want the retrieval time, you should use `index.as_retriever().retrieve("..")`. And FAISS is highly optimized for retrieval, and will easily be faster than BM25 for large datasets

**Comment by TianyuFan0504** [comment]
> 🤷🏻 These aren't exactly comparable
> 
> BM25 is not using your vector store. It's just loading all your nodes into memory, calculating the sparse embeddings with BM25s algorithm, and then running some pairwise comparison on query against all your nodes (this is using the `rank_bm25` library under the hood).
> 
> Whereas `as_query_engine()` will be doing both a retrieval and at least 1 LLM call. (if you just want the retrieval time, you should use `index.as_retriever().retrieve("..")`. And FAISS is highly optimized for retrieval, and will easily be faster than BM25 for large datasets

Thanks @logan-markewich. I'm new to llamaindex and IR, so huge thanks for your answer : )
