### ISSUE TITLE
[Bug]: tuple index out of range when calling LLM with prompt keyword arg

### ISSUE THREAD

**Issue by erictse** [run-llama/llama_index#13056]
### Bug Description

This succeeds:
```python
output = llm.complete(prompt)
```
but see how it fails in Steps to Reproduce below. I could be wrong if providing `prompt` as a keyword arg is unsupported, but I didn't see any documentation or comments about that.

### Version

0.10.30

### Steps to Reproduce

```python
output = llm.complete(prompt=prompt)
```

### Relevant Logs/Tracbacks

```shell
File "…/main.py", line 411, in …
    output = llm.complete(prompt=prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "…/.venv/lib/python3.12/site-packages/llama_index/core/llms/callbacks.py", line 305, in wrapped_llm_predict
    prompt = kwargs.get("prompt", default=args[0])
                                          ~~~~^^^
IndexError: tuple index out of range
```

**Comment by logan-markewich** [comment]
Yea it's technically not supported/advised. It might not be mentioned in the docs, but also, I don't think there's any example that uses it as a kwarg either 😅
