### ISSUE TITLE
[Question]: CondenseQuestionChatEngine try to change the question?

### ISSUE THREAD

**Issue by Ninlawat-Puhu** [run-llama/llama_index#13051]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I used CondenseQuestionChatEngine to call chat_engine  in order to keep history conversaion

`tool2 = QueryEngineTool.from_defaults(
query_engine=query_engine_leave,
description=f"Useful for answering personal questions e.g How many leave days are left?, What is the total number of leave days
used?,What is the total amount of leave rights this year?, Organizationnameth, Position,Email"",nick name, mobile phone"
)    `

`query_engine = RouterQueryEngine.from_defaults(query_engine_tools=[tool2],verbose = True)
chat_engine = CondenseQuestionChatEngine.from_defaults(
    query_engine=query_engine,
    verbose = True,
) 
`

However, CondenseQuestionChatEngine  try to change my question and the result is quite different between query_engine and chat_engine 

`question = "ฉันเหลือวันลากี่วัน"
response = query_engine.query(question)
print(response)`

Outout:

> Selecting query engine 0: The choice is relevant because it includes answering personal questions about leave days, which directly corresponds to the question about how many leave days are left..
คุณเหลือวันลาพักผ่อนประจำปี 11.5 วัน และวันลาป่วย 30 วันค่ะ

`question = "ฉันเหลือวันลากี่วัน" 
response = chat_engine.chat(question)
print(response)`

Outout:

> Querying with: ฉันเหลือวันลาป่วยกี่วันค่ะ?
Selecting query engine 0: The choice is relevant because it mentions the capability to answer personal questions related to leave days, which directly corresponds to the question about the remaining sick leave days..
คุณเหลือวันลาป่วย 30 วันค่ะ

Hence, what I should do to prevent CondenseQuestionChatEngine change the question and give me the same answer when I call query_engine.

**Comment by logan-markewich** [comment]
The condense question chat engine will look at the current message and chat history, and rewrite the query in the context of previous messages.

You can modify the prompt template for how it does this. Here's the default

```
my_prompt = """\
Given a conversation (between Human and Assistant) and a follow up message from Human, \
rewrite the message to be a standalone question that captures all relevant context \
from the conversation.

<Chat History>
{chat_history}

<Follow Up Message>
{question}

<Standalone question>
"""

chat_engine = CondenseQuestionChatEngine.from_defaults(..., condense_question_prompt=my_prompt)
```

**Comment by Ninlawat-Puhu** [comment]
@logan-markewich  If I don't want to rewrite the question based on the context of previous message what I should do? because I wanna keep historical data and it is used when users ask question related to previous data only.

**Comment by RussellLuo** [comment]
Could be off-topic, after reading through the implementation code:

https://github.com/run-llama/llama_index/blob/631cb60b60af4569ffd67406704cfa199f171cff/llama-index-core/llama_index/core/chat_engine/condense_question.py#L114-L127

I'm considering whether it's better to condense the question only when `chat_history` is not empty, as it cloud reduce unnecessary interactions with the LLM. If this is appropriate, I can submit a PR.

**Comment by logan-markewich** [comment]
Yea that could be a minor optimization yes 👍

**Comment by RussellLuo** [comment]
I noticed that `CondensePlusContextChatEngine` has a special boolean property `skip_condense`, which controls whether to skip condensing:

https://github.com/run-llama/llama_index/blob/f1ff1ebafccd6bfd3aec98ac325447c870072bf0/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L138

As for `CondenseQuestionChatEngine`, this might be exactly what @logan-markewich are asking for.

But personally, as discussed above, I'm not sure why there is a need to skip condensing if we are already using `CondenseQuestionChatEngine` or `CondensePlusContextChatEngine`.

**Comment by Ninlawat-Puhu** [comment]
@RussellLuo I used `CondenseQuestionChatEngine` because I saw only that way can call `query_engine = RouterQueryEngine(..)` in method. Following that `CondenseQuestionChatEngine` change user questions. That why I open the question in this pose.

**Comment by RussellLuo** [comment]
@Ninlawat-Puhu I'm afraid I don't fully understand your use case. To my understanding, a [RouterQueryEngine](https://docs.llamaindex.ai/en/stable/examples/query_engine/RouterQueryEngine/) typically uses a selector (backed by LLM), rather than a [ChatEngine](https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/) (e.g. `CondenseQuestionChatEngine `), to select one out of several candidate query engines to execute a query.

Could you please provide some more background or sample code?
