### ISSUE TITLE
[Question]: Does `file_ids` parameter still exist?

### ISSUE THREAD

**Issue by dxtym** [run-llama/llama_index#13099]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm uploading documents to a `QueryEngineTool` object and passing that as a `tool` parameter to `OpenAIAssistantAgent`. As a result, I'm getting the `TypeError: Assistant.create() got an unexpected keyword argument 'file_ids'` error. When I looked at the reference of the API, I found out that there was no `file_ids` argument being passed. Yet, the same implementation was working correctly on Jupyter Notebook (this one's a part of Telegram bot, by the way). I checked the versions for LlamaIndex of both ways and they were the same: 0.10.30. Is that internal thing or something's wrong with my code?

Thank you for your response.

**Comment by RussellLuo** [comment]
Hi @dxtym, what's the version of your `openapi-python` library. AFAIK, this library has changed the parameter `file_ids` to other names recently, see https://github.com/openai/openai-python/pull/1325.

**Comment by logan-markewich** [comment]
@RussellLuo is correct, the API has changed. Still need to update this class (its somewhere on the TODO list 😓 )

**Comment by dxtym** [comment]
Thank  you @RussellLuo @logan-markewich ! 
Apparently, I was using the older version of the API in my notebook, just downgraded the other one. Now, everything works fine!
