### ISSUE TITLE
[Bug]: Reopening :[Bug]: Error Encountered while loading documents into Qdrant Vectorstore #13090 was closed without resolution

### ISSUE THREAD

**Issue by plaban1981** [run-llama/llama_index#13091]
### Bug Description

client = qdrant_client.QdrantClient(location=":memory:")
#
vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

### Version

llama-index==0.10.31

### Steps to Reproduce

```
## Libraries installed

llama-index
llama-index-llms-huggingface
llama-index-embeddings-fastembed
llama-parse
fastembed
chromadb
python-dotenv
langchain-groq
chainlit
fastembed
unstructured[md]
llama-index-vector-stores-qdrant
einops
accelerate


!mkdir -p 'data/paul_graham/'
!wget 'https://raw.githubusercontent.com/run-llama/llama_index/main/docs/docs/examples/data/paul_graham/paul_graham_essay.txt' -O 'data/paul_graham/paul_graham_essay.txt'

# load documents
documents = SimpleDirectoryReader("./data/paul_graham/").load_data()

client = qdrant_client.QdrantClient(
    # you can use :memory: mode for fast and light-weight experiments,
    # it does not require to have Qdrant deployed anywhere
    # but requires qdrant-client >= 1.1.1
    location=":memory:"
    # otherwise set Qdrant instance address with:
    # url="http://<host>:<port>"
    # otherwise set Qdrant instance with host and port:
    #host="localhost",
    #port=6333
    # set API KEY for Qdrant Cloud
    # api_key="<qdrant-api-key>",
)

vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)
```

**Comment by logan-markewich** [comment]
Its  fixed, but you need the latest version as I said (if its installed already, you have to upgrade)

`pip install -U llama-index-vector-stores-qdrant`

Here it is working on a fresh colab
https://colab.research.google.com/drive/147NQZ1VXvQ9Gs0SUlLpJ2WD9ufZxJqAb?usp=sharing

**Comment by logan-markewich** [comment]
If you are working in a notebook locally, you will have to restart it for any installs to take effect

**Comment by plaban1981** [comment]
Let me do that and I will get back to u. Please do not close the ticket

**Comment by plaban1981** [comment]
@logan-markewich  will do and get back to you

**Comment by plaban1981** [comment]
@logan-markewich  Thank You Very much . Restarting the kernel worked. You may close the ticket now
