### ISSUE TITLE
[Feature Request]: Allow google readers to take token and credential path

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#13092]
### Feature Description

The documentation just says to have token.json and credentials.json available, but doesn't specify from where -- and in our instance doesn't work. Is it possible to have paths to supply `GoogleDocsReader` or it's `load_data` method? 

`Credentials.from_authorized_user_file(token_path, SCOPES)`
`InstalledAppFlow.from_client_secrets_file(creds_path, SCOPES)`

### Reason

Platform specific filesystems and CDNs

### Value of Feature

Allows a more programmatic usage of google reader.

**Comment by WASasquatch** [comment]
Why is this not planned? It's base functionality of the methods you're using.
