### ISSUE TITLE
[Question]: How can I get nodes from VectorStoreIndex ?

### ISSUE THREAD

**Issue by zzk2021** [run-llama/llama_index#13103]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

index  = VectorStoreIndex(nodes)
Now I want to get nodes from index, How can I do it?

**Comment by logan-markewich** [comment]
If you are using the default vector store `list(index.storage_context.docs.values())` Will get a list of nodes 

Otherwise, you need to do a retrieve with a large top k, or use the underlying vector store client

**Comment by anhthyngo** [comment]
> list(index.storage_context.docs.values())

This is always an empty dict_values([]) for me, why?
