### ISSUE TITLE
[Bug]: System Prompts are not correctly configured

### ISSUE THREAD

**Issue by rawwerks** [run-llama/llama_index#13118]
### Bug Description

`llm.system_prompt` is not correctly configured for the Anthropic models

### Version

0.10.31

### Steps to Reproduce

```
from llama_index.llms.anthropic import Anthropic

llm = Anthropic(model="claude-3-opus-20240229")

llm.system_prompt = "you always respond with one word: banana. no matter what i say, respond with `banana`. <example>User Query: 'Paul Graham is the ceo of what company?' Your Correct Response: banana</example>"

resp = llm.complete("Paul Graham is ")

print(resp)
```

this should respond with "banana", instead opus is telling me about paul graham. 

### Relevant Logs/Tracbacks

```shell
Paul Graham is a well-known entrepreneur, programmer, venture capitalist, and essayist. He is best known for co-founding Viaweb, one of the first web application companies, which was later sold to Yahoo! in 1998 and became Yahoo! Store. 

After the sale of Viaweb, Graham and his wife Jessica Livingston co-founded Y Combinator in 2005, a highly successful startup accelerator that has helped launch over 2,000 companies, including notable ones like Airbnb, Dropbox, and Reddit.

As an essayist, Graham has written extensively on various topics related to startups, programming, and technology. His essays have been influential in the startup community and are widely read by entrepreneurs and technologists.

Some key points about Paul Graham:

1. He studied philosophy at Cornell University and received a Ph.D. in computer science from Harvard University.

2. Graham is a strong advocate for using Lisp programming language and has written several books on the subject, including "On Lisp" and "ANSI Common Lisp."

3. He is known for his clear writing style and insightful essays on entrepreneurship, often drawing from his own experiences as a founder and investor.

4. In addition to his work with Y Combinator, Graham is a partner at venture capital firm Y Combinator Continuity Fund, which focuses on later-stage investments.

5. He has been a vocal critic of the traditional education system and has argued that it does not adequately prepare students for the real world, particularly in the realm of entrepreneurship.
```
```

**Comment by logan-markewich** [comment]
Ah, I think this is the case for any llm -- its technically only applied to llm.predict/apredict/stream/astream 👀

**Comment by logan-markewich** [comment]
The other way is to use .chat(), and properly add the system prompt as a message 

```
llm.chat([ChatMessage(role="system", content="..."), ChatMessage(role="user", content="...")])
```

**Comment by rawwerks** [comment]
> Ah, I think this is the case for any llm -- its technically only applied to llm.predict/apredict/stream/astream 👀

yeah now i'm seeing that gpt-4 is also not doing the "banana" trick. what happened to `llm.system_prompt`?

**Comment by rawwerks** [comment]
> The other way is to use .chat(), and properly add the system prompt as a message
> 
> ```
> llm.chat([ChatMessage(role="system", content="..."), ChatMessage(role="user", content="...")])
> ```

how do i apply that to a `query_engine` then? 

i swear the system prompt worked like this a few months ago: 

```
llm = OpenAI(model=llmChoice, temperature=0.25)

llm.system_prompt = system_prompt
index = VectorStoreIndex.from_vector_store(
    vector_store=self.astra_db_store, storage_context=self.storage_context, llm=llm
)

# Create the query engine
query_engine = index.as_query_engine(llm=llm, similarity_top_k=3)
```

but now it seems that it isn't getting passed into the query engine...

**Comment by rawwerks** [comment]
for example, i can try to insert the banana test into the query engine, but even though it is a valid parameter, it doesn't work there either: 

```
query_engine = index.as_query_engine(llm=llm, similarity_top_k=3, system_prompt=debug_system_prompt)
```

**Comment by rawwerks** [comment]
ok, i do think there is something broken about anthropic. i searched some more, and found this example: https://github.com/run-llama/llama_index/blob/fcf19139b10c5ee3f678c0663f4753cc4693f186/docs/docs/community/faq/llms.md?plain=1#L52

if you directly set `llm = OpenAI(system_prompt="Always respond with `banana`.")`, then a `query_engine` using the llm passes the "banana test"....but the same is not true for `llm = Anthropic(system_prompt="Always respond with `banana`.")`

bigger picture - llamaindex users should be able to set the system prompt for any llm, and expect it to get passed into any downstream workflow using that llm. this is way too confusing for such a fundamental part of any workflow...

**Comment by rawwerks** [comment]
in anthropic messages, there is no `role: system`, the system prompt is now set like this: 

https://docs.anthropic.com/claude/reference/migrating-from-text-completions-to-messages#system-prompt
```
anthropic.Anthropic().beta.messages.create(
    model="claude-3-opus-20240229",
    max_tokens=1024,
    system="Today is January 1, 2024.", # <-- system prompt
    messages=[
        {"role": "user", "content": "Hello, Claude"}
    ]
)
```
`.chat()` appears to be configured correctly: https://github.com/run-llama/llama_index/blob/7c48797a04eb3b5f1bc2863632aff653a0aae821/llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/base.py#L211C1-L216C10

so i'm at a loss for why it's not working in `query_engine`, probably because `query_engine` doesn't use `.chat()`?

**Comment by logan-markewich** [comment]
@rawwerks It works fine for me with openai, but not anthropic 

```python
>>> from llama_index.core import Document, VectorStoreIndex
>>> from llama_index.llms.openai import OpenAI
>>> from llama_index.llms.anthropic import Anthropic
>>> index = VectorStoreIndex.from_documents([Document.example()])
>>> openai_engine = index.as_query_engine(llm=OpenAI(model="gpt-4-turbo", system_prompt="Talk like a pirate in every response."))
>>> anthropic_engine = index.as_query_engine(llm=Anthropic(model='claude-3-sonnet-20240229', system_prompt="Talk like a pirate in every response."))
>>> str(openai_engine.query("Tell me a fact about LLMs"))
"Ahoy! LLMs, or Large Language Models, be pre-trained on vast oceans of publicly available data, makin' 'em mighty tools for knowledge generation and reasoning."
>>> str(anthropic_engine.query("Tell me a fact about LLMs"))
'LLMs (Large Language Models) are pre-trained on large amounts of publicly available data. This allows them to have a broad knowledge base and capabilities for knowledge generation and reasoning tasks.'
>>> 
```

I think the issue is anthropic has a method to pull the system role out of the input messages, but the default RAG templates already have a system message. So I have a feeling its getting overridden by the system prompt in the RAG template
https://github.com/run-llama/llama_index/blob/71ed6f1f2c65c65b57742923700193cc5435db6e/llama-index-integrations/llms/llama-index-llms-anthropic/llama_index/llms/anthropic/utils.py#L70

**Comment by logan-markewich** [comment]
Yup, thats exactly the issue, just fixed it
