### ISSUE TITLE
[Question]: What is the best to retrieve Knowledge graphs embeddings

### ISSUE THREAD

**Issue by navneteberi30** [run-llama/llama_index#13129]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

Hi I have general question,
How can we retrieve the knowledge graph embeddings from the graph store instead of using the local storage context?
I am unable to find any documentation related to that or is it something we can expect in future
current process looks something like this once we create the knowledge graphs and then use local storage context.
Could you please share how can we retrieve from the graph store that we build
kg_index = load_index_from_storage(
        storage_context=storage_context,
        max_triplets_per_chunk=10,
        space_name=space_name,
        edge_types=edge_types,
        rel_prop_names=rel_prop_names,
        tags=tags,
        verbose=True,
    )

**Comment by oykunehir** [comment]
I have the same problem, as you mentioned in your code KGTableRetriever takes knowledge_graph_index as parameter. Which means every time we need to re-build the KG index. Is there a way to build the KG indexes and store in a graph database, then query without building the index again?

**Comment by navneteberi30** [comment]
@dosu The code you provided when we will call KGTableRetriever it needs index=knowledge_graph_index so every time we call the kg_table_retriever it will recreate the knowledge_graph_index which we want to avoid.

knowledge_graph_index = KnowledgeGraphIndex(service_context=service_context, graph_store=your_graph_store)
kg_table_retriever = KGTableRetriever(index=knowledge_graph_index, retriever_mode=KGRetrieverMode.EMBEDDING)

**Comment by gich2009** [comment]
Hi @navneteberi30 @oykunehir, have you guys tried using the KnowledgeGraphRAGRetriever()? You can build your index with the KnowledgeGraphIndex() and then pass in the graph_store you used for this process to the KnowledgeGraphRAGRetriever(). Let me know if this works for you.

**Comment by navneteberi30** [comment]
@gich2009 that doesn't work because once i build the  KnowledgeGraphIndex.from_documents() and unable to get any reposnse

```
kg_index = KnowledgeGraphIndex.from_documents(
        documents=github_document_loader(),
        llm=OpenAI(model="gpt-4", temperature=0.1),
        graph_store=graph_store,
        max_triplets_per_chunk=10,
        space_name=SPACE_NAME,
        edge_types=EDGE_TYPES,
        rel_prop_names=REL_PROP_NAMES,
        tags=TAGS,
        include_embeddings=True,
    )
    
 storage_context = StorageContext.from_defaults(graph_store=graph_store)
    graph_rag_retriever = KnowledgeGraphRAGRetriever(
        storage_context=storage_context,
        verbose=True,
    )
```

**Comment by gich2009** [comment]
@navneteberi30, let me give it a try on my side then I'll get back to you on it.

**Comment by logan-markewich** [comment]
You think can just do `KnowledgeGraphIndex(nodes=[], storage_context=storage_context)`
or just skip the index, and throw the graph store into the `KnowledgeGraphRAGRetriever`

**Comment by hungbui-io** [comment]
@logan-markewich Hi, is there any way to get the metadata, text, embedding of original documents that are retrieved when querying with `KnowledgeGraphRAGRetriever`? The original documents are ones that were used to generate KG with `kg_index=KnowledgeGraphIndex.from_documents(documents)`

**Comment by endrol** [comment]
@logan-markewich 
Thank you, 

> You think can just do `KnowledgeGraphIndex(nodes=[], storage_context=storage_context)` or just skip the index, and throw the graph store into the `KnowledgeGraphRAGRetriever`

`KnowledgeGraphIndex(nodes=[], storage_context=storage_context)` is exactlly what I need! Save my day!!
