### ISSUE TITLE
[Question]: on querying responses are totally incorrect

### ISSUE THREAD

**Issue by elvisbegovic** [run-llama/llama_index#13130]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there, sory to make noise here. 

I am impressed how responses are completly incorrect base on a simple "structured" csv file. Am I doing things correctly ? 

# Step 1, persist csv file with load.py : 
```python
documents = SimpleDirectoryReader("./data").load_data()
Settings.embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")
Settings.llm = Ollama(model="llama3", request_timeout=60.0)
index = VectorStoreIndex.from_documents(documents)
index.storage_context.persist(persist_dir="./persist/")
```

# Step 2, chat with data with chat.py : 
```python
Settings.embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")
Settings.llm = Ollama(model="llama3", request_timeout=60.0)
storage_context = StorageContext.from_defaults(persist_dir="./persist/")
index = load_index_from_storage(storage_context)
query_engine = index.as_query_engine()

while True:
    user_input = input("Ask your question ?")
    if user_input.lower() == "quit":
        break
    response = query_engine.query(user_input)
    print(response)
```

So on code / compilation etc everytihng works perfectly (llama-index is awesome) BUT every question I asking on this CSV file, reponses are completly wrong. What Am I doing wrong here ?

**Comment by elvisbegovic** [comment]
@dosu ok but there is NO documentation/exemple on "SimpleDirectoryReader" and cannot find any readers to install. If I shouldn't use SimpleDirectoryReader as you said, give me simple example to persist simple data.csv to ./persist/ folder using PagedCSVReader.

**Comment by elvisbegovic** [comment]
@dosu ok but there is NO documentation/exemple on "PagedCSVReader" and cannot find any readers to install. If I shouldn't use SimpleDirectoryReader as you said, give me simple example to persist simple data.csv to ./persist/ folder using PagedCSVReader.

**Comment by logan-markewich** [comment]
@elvisbegovic structured data is pretty special case. Unless it makes sense to embed and retrieve individual rows (maybe you have QA pairs, etc.), using a vector index is probably not the right approach

Instead you probably want to put it into a sqlite db or similar and do text-to-sql, or a dataframe and do text-to-pandas

https://docs.llamaindex.ai/en/stable/use_cases/q_and_a/#qa-over-structured-data

**Comment by elvisbegovic** [comment]
Thank you @logan-markewich i will try what you say and I understand what txt-to-sql try to achieve... thanks.

let me ask : I want be sure to understand. As "base readers" includes CSV file extension and as far as I know every CSV is "structured". So what explain that  llama-index support officially reading CSV as core feature and you say it is "special case? Is there any different way of what im doing here to create documents[] based on csv. Or in other words: what is usecase reading csv using SimpleDirectoryReader? thank you

**Comment by RussellLuo** [comment]
From my observation, the built-in readers of `SimpleDirectoryReader` are mainly focus on parsing unstructured texts from various unstructured or structured files.

As for a sample CSV as below:

```csv
a, b, c
d, e, f
g, h, i
```

there will only be one document with the text: `"d,  e,  f\ng,  h,  i"` (the first row is ignored since it might be treated as a title line by pandas).

Similarly, for the following JSON:

```json
{
  "a": "b":
  "c": [
    {
      "n": 1
    },
    {
      "n": 2
    }
  ]
}
```

you will also get a single document that contains the text: `"{\n  "a": "b":\n  "c": [\n    {\n      "n": 1\n    },\n    {\n      "n": 2\n    }\n  ]\n}\n"`.

@elvisbegovic Returning to the current issue, I think it matters what the content your CSV file contains and what the Q/A behavior you expect. It may be helpful if you can provide more information.
