### ISSUE TITLE
[Question]: How to store two index in redis?

### ISSUE THREAD

**Issue by Ninlawat-Puhu** [run-llama/llama_index#13166]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have two index that keep different data as below code

`index_policy = VectorStoreIndex(nodes = base_nodes+objects)`
`index_leave = VectorStoreIndex.from_documents(list_of_documents_leave)`
`query_engine_leave = index_leave.as_query_engine(similarity_top_k=2,filters = filters,streaming=True)`
`query_engine_policy = index_policy.as_query_engine(similarity_top_k=6,streaming=True)`

But I want to save those index (index_policy,index_leave) in redis database to persist data and I want to call index from redis database instead of local paths. Moreover, with index_leave, I also used ExactMatchFilter for filter information in some columns.

Can you recommend how to develop the code from my requirement?

**Comment by Ninlawat-Puhu** [comment]
I got an error 

> Deprecated kwarg, index_name, found upon initialization. RedisVectorStore now requires an IndexSchema object

**Comment by Ninlawat-Puhu** [comment]
@logan-markewich  Can you help me for this case? if you want more information don't hesitate ask

**Comment by logan-markewich** [comment]
@Ninlawat-Puhu You can use the redis vector store
https://docs.llamaindex.ai/en/stable/examples/vector_stores/RedisIndexDemo/?h=redisve
