### ISSUE TITLE
[Question]: How can I make sure no duplicate documents are added to the vector store?

### ISSUE THREAD

**Issue by dsanr** [run-llama/llama_index#13162]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently, I am using Ingestion Pipeline
`pipeline = IngestionPipeline(
    transformations = [SentenceSplitter(chunk_size=512, chunk_overlap=128),
                       OpenAIEmbedding(model_name='text-embedding-3-small', callback_manager=CallbackManager([token_counter]))],
    docstore=SimpleDocumentStore(),
    vector_store=vector_store)`
`nodes = pipeline.run(documents=documents, show_progress=True, num_workers=-1)`
vector_store is a Chroma vector DB, document is paul_graham essay.
When I re-run the pipeline with the same documents, no duplicates are added to Docstore. But embeddings are calculated again for the document and the chroma_collection count is increasing.
How can I ensure no duplicate chunks/nodes are added to the vector_store?

**Comment by logan-markewich** [comment]
Are you saving and loading the docstore between runs? Do your documents have consistent IDs? Both of those are pretty important

**Comment by dsanr** [comment]
@logan-markewich Saving and loading the docstore between runs made it work. Thank you.
