### ISSUE TITLE
[Question]: How to use Custom System prompt in CondensePlusContextChatEngine

### ISSUE THREAD

**Issue by shiyuangu** [run-llama/llama_index#13161]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I observe that in `CondensePlusContextChatEngine`, custom `system_prompt` is prepended  to the default prompt instead of replacing  as I would expect. You can see this in the  [source code here](https://github.com/run-llama/llama_index/blob/5e01f9c60c1516df35170fa45f36a848dd82353e/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L221).  This change seems to be intended as in [this PR](https://github.com/run-llama/llama_index/pull/9123/files). Also, the template strings in the custom`system_prompt` are not formatted (Cf: [source code](https://github.com/run-llama/llama_index/blob/5e01f9c60c1516df35170fa45f36a848dd82353e/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L218)  ). Is there a way I can use my own prompt?  Also, `create-llama` python-backend generates `.env`  that implies we can indeed provide a custom system prompt but it doesn't work (Cf: [code](https://github.com/run-llama/private-claude/blob/1203762bf1267ee36f5f55c404354676555c85a3/backend/.env#L28)).

**Comment by logan-markewich** [comment]
@shiyuangu you can customize the system prompt template

Here's the default prompt and how to pass it in
```python
DEFAULT_CONTEXT_PROMPT_TEMPLATE = """
  The following is a friendly conversation between a user and an AI assistant.
  The assistant is talkative and provides lots of specific details from its context.
  If the assistant does not know the answer to a question, it truthfully says it
  does not know.

  Here are the relevant documents for the context:

  {context_str}

  Instruction: Based on the above documents, provide a detailed answer for the user question below.
  Answer "don't know" if not present in the document.
  """
  
chat_engine = CondensePlusContextChatEngine.from_defaults(retriever, context_prompt= DEFAULT_CONTEXT_PROMPT_TEMPLATE)
```

**Comment by shiyuangu** [comment]
> @shiyuangu you can customize the system prompt template
> 
> Here's the default prompt and how to pass it in
> 
> ```python
> DEFAULT_CONTEXT_PROMPT_TEMPLATE = """
>   The following is a friendly conversation between a user and an AI assistant.
>   The assistant is talkative and provides lots of specific details from its context.
>   If the assistant does not know the answer to a question, it truthfully says it
>   does not know.
> 
>   Here are the relevant documents for the context:
> 
>   {context_str}



> 
>   Instruction: Based on the above documents, provide a detailed answer for the user question below.
>   Answer "don't know" if not present in the document.
>   """
>   
> chat_engine = CondensePlusContextChatEngine.from_defaults(
>   retriever, 
>   context_prompt= DEFAULT_CONTEXT_PROMPT_TEMPLATE
> )
> ```
I see. So we need to pass the prompt as `context_prompt` instead of `system_prompt`.  Thank you very much!  
btw:  [create-llama](https://github.com/run-llama/create-llama/blob/c981eb14230a818f79bb79be62869b3018443a71/templates/components/engines/python/chat/__init__.py#L21) needs a fix then.
