### ISSUE TITLE
[Question]: Agents-function calling with followup question

### ISSUE THREAD

**Issue by risos8200** [run-llama/llama_index#13167]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to build a framework where Agents can call specific functions whenever necessary, but how do I add a functionality for it to ask follow up questions when it doesn't have all the parameters needed to call a function.

Example: Calling an email sending function using Agent Framework but the to_send address is missing in the query, in such situation, I want my agent to ask a followup question or call any additional function, instead it just ends up sending to some example email address.

**Comment by logan-markewich** [comment]
@risos8200 You could add a tool that specifically requires input from a user when it runs

```
def ask_user(message: str) -> str:
  """Useful for asking a user for any required information that you are missing."""
  response = input(message).strip()
  return response
  
tool = FunctionTool.from_defaults(ask_user)
```

**Comment by risos8200** [comment]
Thanks, that worked!

**Comment by risos8200** [comment]
How do I do it for web based applications? Like I want to return a response to the agent to ask for further details in my flask app. But it goes into a infinite loop of asking itself the same question and calling the ask_user function.
