### ISSUE TITLE
[Question]: Intended difference between `KnowledgeGraph` & `ComposableGraph`?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#13179]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Noticing that `ComposableGraph` is not used in a `KnowledgeGraphIndex`, what is the intended usage for `ComposableGraph`?

**Comment by logan-markewich** [comment]
@brycecf A composable graph is just a collection of indexes that are arranged/queried in a sort of tree/graph structure. Its an older idea that is mostly deprecated at this point.

A knowledge graph is a collection of knowledge facts (i.e. triplets of subject, relation, object), along with the text chunks those triplets were extracted from.

So, the two are not related at all.
