### ISSUE TITLE
[Question]: Built in http retry

### ISSUE THREAD

**Issue by grahamnedelka** [run-llama/llama_index#13175]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi! For the Slack reader, you may want to consider importing the RateLimitErrorRetryHandler from slack_sdk:

```
from slack_sdk import WebClient
from slack_sdk.http_retry.builtin_handlers import RateLimitErrorRetryHandler

client = WebClient(token="yadayada", retry_handlers=[RateLimitErrorRetryHandler(max_retry_count=5)])
```

This will automatically handle rate-limiting

**Comment by logan-markewich** [comment]
There is some retry too
https://github.com/run-llama/llama_index/blob/93cb09518e5cec121849bbba70584a1d5b98f415/llama-index-integrations/readers/llama-index-readers-slack/llama_index/readers/slack/base.py#L133

Feel free to make a PR to improve though
