### ISSUE TITLE
[Question]: Anyone else encounter Ollama Starter Example working once, then failing thereafter?

### ISSUE THREAD

**Issue by 130jd** [run-llama/llama_index#13188]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I've previously used a RAG system using Ollama x langchain, but decided to try Ollama x llama-index to see if I'd get better results. Started off with the [Ollama Starter Example](https://docs.llamaindex.ai/en/stable/getting_started/starter_example_local/), **got it to work once, and then thereafter it would always timeout** (despite setting a 10+ min timeout).

**More details:** In these failures, I noticed that **it wouldn't even progress to the embedding phase (where the progress bars load)**, and looking in task manager the **`ollama_llama_server.exe` was consuming a ton of resources but nothing was happening until the timeout**. When it timed out, the error message would mention **`map_httpcore_exceptions` (similar to the logs [here](https://github.com/ollama/ollama/issues/2424))**.

1. **Is it a problem with my machine specs?** I have 16GB RAM and the Starter Tutorial says at least 32GB of RAM is required. If so, why did it work the first time? [Also, others have run it on 16GB machines.](https://github.com/ollama/ollama/issues/2424#issuecomment-1935459956)
2. **Is it a problem specific to llama-index?** I tried to use (through Ollama) the 4-bit quantized mistral and phi3 models, all of which have worked fine (by themselves and in the langchain RAG) on my machine. For example, llama-index has an [in-memory vector store](https://docs.llamaindex.ai/en/stable/community/faq/vector_database/); is it possible that it worked the first time, then the in-memory vector store ran out of memory and thus failed on subsequent tries? Or is it a problem specific to the `llama-index-llms-ollama` library; [some say using the Ollama library works](https://github.com/ollama/ollama/issues/2424#issuecomment-1961173682)?
3. **Is it a problem with Ollama itself?** It sounds like some default context window mismatches are causing odd behavior. See [here](https://github.com/run-llama/llama_index/issues/13106) and [here](https://github.com/run-llama/llama_index/pull/13139).

Does any of the above give any clues that help diagnose what's going on? I'm not just looking for a fix, but more trying to understand the principles of why llama-index may not be working for me. And if there's some fundamental problem with Ollama x llama-index (that isn't a problem with Ollama x langchain), such that if I want to use llama-index I need to ditch Ollama for OpenAI?

Thanks in advance.

**Comment by logan-markewich** [comment]
I've never had or really seen this issue 🤔  you could decrease the context window on the llm to try and reduce memory usage if that feels like the issue.

LlamaIndex really tries to use the full context window always, to reduce llm calls
