### ISSUE TITLE
[Question]: TreeSummarize Error: ValueError: could not broadcast input array from shape (371,) into shape (320,)

### ISSUE THREAD

**Issue by utility-aagrawal** [run-llama/llama_index#13198]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Getting this error when I am trying to summarize a document using llama-3 (via llama_cpp).

Here's the minimum code to reproduce the error:

import torch
from llama_index.core import Settings, SimpleDirectoryReader
from llama_index.llms.llama_cpp import LlamaCPP
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.response_synthesizers import TreeSummarize

def llm_summary(text_chunks):
    synth = TreeSummarize()
    summary = synth.get_response("Summarize the provided text in about 200 words or less", text_chunks)
    return summary

# Coverts input to Llama-3 prompt format
def completion_to_prompt_llama3(completion: str) -> str:
    system_prompt_str = ""

    return (f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n"
    f"{system_prompt_str.strip()}<|eot_id|><|start_header_id|>user<|end_header_id|>\n"
    f"{completion.strip()}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n")

filepath = "Mount Everest.docx"
device = torch.device("cuda:0") if torch.cuda.is_available() else torch.device("cpu")
n_gpu_layers = 0 if device == "cpu" else -1
llm = LlamaCPP(
    model_url="https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/resolve/main/Meta-Llama-3-8B-Instruct.Q4_K_M.gguf",
    model_path=None, #llama-2-7b-chat.Q4_K_M.gguf
    temperature=0.1,
    max_new_tokens=256,
    # llama3 has a context window of 8192 tokens, but we set it lower to allow for some wiggle room
    context_window=8000,
    generate_kwargs={},
    model_kwargs={"n_gpu_layers": n_gpu_layers, "offload_kqv": True},
    # transform inputs into Llama3 format
    completion_to_prompt=completion_to_prompt_llama3,
    verbose=True,
)

Settings.llm = llm

reader = SimpleDirectoryReader(input_files = [filepath], filename_as_id = True) #, file_metadata = extract_metadata
documents = reader.load_data()

nodes = SentenceSplitter(chunk_size=512, chunk_overlap=20).get_nodes_from_documents(documents)
text_chunks = [node.text for node in nodes]
summary_llm = llm_summary(text_chunks)
print(f"LLM Summary => {summary_llm}")

Here's the input file:
[Mount Everest.docx](https://github.com/run-llama/llama_index/files/15178676/Mount.Everest.docx)

Can someone tell me what could be wrong? This input doc is 37 pages long. The same code works if I just pass the first 2 pages. Here's the input that works:
[Mount Everest_first_2_pages.docx](https://github.com/run-llama/llama_index/files/15178690/Mount.Everest_first_2_pages.docx)

Thanks!

**Comment by logan-markewich** [comment]
Try setting the global tokenizer so that you get proper token counts, seems like an issue with an input being too large, likely due to counting tokens with a gpt-3.5 tokenizer.

```
from llama_index.core import Settings

Settings.tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B")
```

Either that, or maybe try lowering the context window a tad on the LLM

**Comment by utility-aagrawal** [comment]
Thanks @logan-markewich ! I tried both solutions separately and together but that didn't fix the problem. Do you have any other recommendations?

After I set the global tokenizer,  error:
ValueError: could not broadcast input array from shape (407,) into shape (344,)

After I set the context window lower from 8k to 7k, error:
ValueError: could not broadcast input array from shape (365,) into shape (344,)

Using both changes together, error:
ValueError: could not broadcast input array from shape (407,) into shape (344,)

**Comment by logan-markewich** [comment]
Hmm that error is very not helpful haha. It's hard to say what the issue is. It seems like the model itself might be broken? Do you have the latest installation of the ollama server?

**Comment by utility-aagrawal** [comment]
@logan-markewich , It seems like a llama-cpp error. I have raised an issue there: https://github.com/abetlen/llama-cpp-python/issues/1421
