### ISSUE TITLE
[Question]: Why pass both `nodes` AND `storage_context` into `VectorStoreIndex`?

### ISSUE THREAD

**Issue by 130jd** [run-llama/llama_index#13208]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

From [Customizing Storage](https://docs.llamaindex.ai/en/stable/module_guides/storing/customization/#low-level-api):

```
# create (or load) docstore and add nodes
storage_context.docstore.add_documents(nodes)

# build index
index = VectorStoreIndex(nodes, storage_context=storage_context)
```

Why do we pass `nodes` AND `storage_context` into `VectorStoreIndex`, when `nodes` is also already passed into `storage_context`? Given that `nodes` is already passed into `storage_context`, why aren't we passing only EITHER `nodes` OR `storage_context` into `VectorStoreIndex`? Can someone help me understand what is the purpose of passing both? Thank you

**Comment by logan-markewich** [comment]
The nodes still have to be embedded and inserted into a vector index

**Comment by 130jd** [comment]
Thanks, that makes sense why `VectorStoreIndex` requires nodes to be passed in. But I've also seen some examples where it's just `VectorStoreIndex(nodes)`, and `storage_context` isn't passed in. What would be the difference (reasons to choose one over the other in different use cases) between `VectorStoreIndex(nodes)` and `VectorStoreIndex(nodes, storage_context=storage_context)`?

**Comment by 130jd** [comment]
@dosu

If you have pre-existing `storage_context` that you want to pass in, you can recreate `index = load_index_from_storage(storage_context)` without needing to pass in `nodes`.

If you don't have pre-existing `storage_context` then you would just make a new `index = VectorStoreIndex(nodes)`.

I still don't understand in what circumstances you would need to make a new index with `VectorStoreIndex(nodes)` that also requires `storage_context`.

**Comment by logan-markewich** [comment]
@130jd if you configure a specific vector store (qdrwnr, chroma, etc) or a specific docstore/index store (mongodb, redis), then that is what the storage context is for

It will add the nodes to the docstore and vector store, and register the ID of the index in the index store.

Although by default, when using a remote vector store like qdrant, the docstore/index store is not used, to help simplify storage (nodes are stored in the vector store)

You can override this by setting `store_nodes_override=True`

**Comment by 130jd** [comment]
@logan-markewich thanks for the clarification. I've been using chroma as vector store and observed `nodes = index.docstore.docs.values()` is empty, which I guess is because docstore isn't used like you noted.

Is this also why index.refresh_ref_docs() won't work for me (despite using the `SimpleDirectoryReader` `filename_as_id=True` flag)? I keep running the refresh with the same document, to test if it'll recognize that the document is already in the chromadb, but the chroma_collection.count() keeps growing (which means it can't recognize the doc as a repeat).

@dosu
