### ISSUE TITLE
[Feature Request]: user-friendly exception message when some modules is not found

### ISSUE THREAD

**Issue by HairlessVillager** [run-llama/llama_index#13214]
### Feature Description

When some modules is not found but can be installed via `pip install`, append helpful text to the exception message so that user can **directly** install the corresponding packages, instead of searching issues on GitHub.

For example, this is unfriendly:
```text
ModuleNotFoundError: No module named 'llama_index.llms.ollama'
```
, and this is friendly:
```text
ModuleNotFoundError: No module named 'llama_index.llms.ollama', please run `pip install llama-index-llms-ollama`
```

See #11886.

**Comment by logan-markewich** [comment]
As far as I know, I can't think of a technical way to imement this. Would love to see some ideas.

In general, every integration is a package. The installs and integrations are all listed on https://llamahub.ai

**Comment by logan-markewich** [comment]
There's no way for the code to know what integrations exist, and if the import is a typo or some actual import. Further, python doesn't really provide a way to catch import errors that are happening outside of your package

**Comment by HairlessVillager** [comment]
You are right, it's hard to implement technically. But I just want the new users to know how to fix the unexpected ModuleNotFoundError by https://llamahub.ai/.

Hope there will be a better way to implement this, like a item in FAQ or others.
