### ISSUE TITLE
[Question]: OpenAIAgent changes user query

### ISSUE THREAD

**Issue by mayank-rakesh-mck** [run-llama/llama_index#13216]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My OpenAIAgent with tools sometimes drastically changes the user input during agent.chat() operation. Like if user query is "What is the problem statement in the module?" it calls my query engine tools sometimes with just the args "problem statement".

How can I force the Agent to pass the user query as it is or with marginal changes to the query engine tools?

**Comment by mayank-rakesh-mck** [comment]
@logan-markewich can you help with this?

**Comment by logan-markewich** [comment]
This is how an agent works. You can try writing a system prompt or giving better descriptions in your tools
