### ISSUE TITLE
[Question]: How to handle multipe users, if they send messages to LLM concurrently.

### ISSUE THREAD

**Issue by Varshan2003** [run-llama/llama_index#13227]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello all, I'm facing the issues regarding handling different users, if two or more users sends a message to LLM concurrently,it doesn't work as expected,the questions of each users are getting mixed,users are getting irrelevant answers.

**Comment by logan-markewich** [comment]
What LLM are you using?

**Comment by Varshan2003** [comment]
Azure OpenAI

**Comment by logan-markewich** [comment]
How are you using it? Azure and OpenAI both handle concurrent requests fine for me

**Comment by Varshan2003** [comment]
I've integrated it with slack,where the slack is sending message to Bot, If 3 users send messages to Bot It is giving the single response to all the users..

**Comment by Varshan2003** [comment]
I've followed the RAG system,creating index and chating with Index using asChatEngine method..

**Comment by TitasDas** [comment]
@Varshan2003 are you able to share snippets or a template of your code to show how you are handling user requests now?

**Comment by Varshan2003** [comment]
`app = App(token=os.getenv("SLACK_BOT_TOKEN"))

PERSIS_DIR = "./db_fin"

try:
    llm = AzureOpenAI(
        model="gpt-35-turbo",
        deployment_name="gpt-35-turbo-default",
        api_key=api_key,
        azure_endpoint=azure_endpoint,
        api_version=api_version
    )
    Settings.llm = llm
    print("initialized the llm")
except Exception as e:
    print("Error initializing llm:", e)

try:
    embed_model = AzureOpenAIEmbedding(
        model="text-embedding-ada-002",
        deployment_name="text-embedding-ada-002",
        api_key=api_key,
        azure_endpoint=azure_endpoint,
        api_version=api_version
    )
    Settings.embed_model = embed_model
    print("initialized the embed-model")
except Exception as e:
    print("Error initializing embed_model:", e)



def create_index():
    try:
        if not os.path.exists(PERSIS_DIR):
            documents = SimpleDirectoryReader("data").load_data()
            index = VectorStoreIndex.from_documents(documents)
            parser = SimpleNodeParser()
            nodes = parser.get_nodes_from_documents(documents)
            # Initialize service context
            service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
            storage_context = StorageContext.from_defaults()
            index = VectorStoreIndex(nodes = nodes, service_context=service_context, storage_context=storage_context)
            # Persist the index to directory
            index.storage_context.persist(persist_dir=PERSIS_DIR)
        else:
            # Load the index from directory
            service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
            storage_context = StorageContext.from_defaults(persist_dir=PERSIS_DIR)
            index = load_index_from_storage(service_context=service_context, storage_context=storage_context)
        return index
    except Exception as e:
        print("Error creating index:", e)
        return None
    
import re  
def post_processing_query(data, csv_file):
    answer = data.get('key1', "")
    page_id = data.get('key2', "")[:-4]

    # Load CSV data
    references = {}
    with open(csv_file, newline='') as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            if row['Page ID'] in references:
                references[row['Page ID']].append({'page_title': row['Page Name'], 'url': row['URL']})
            else:
                references[row['Page ID']] = [{'page_title': row['Page Name'], 'url': row['URL']}]

    additional_reference = {'page_title': 'Security Home', 'url': 'https://confluence.ops.expertcity.com//display/Security/Security+Home'}
    if page_id in references:
        references[page_id].append(additional_reference)
    else:
        references[page_id] = [additional_reference]

    # Construct JSON response
    response = {'answer': answer}
    if page_id in references:
        response['reference'] = references[page_id]
    else:
        response['reference'] = []

    return json.dumps(response)




index = create_index() 

memory = ChatMemoryBuffer.from_defaults(token_limit=3900)
chat_engine = index.as_chat_engine(
    chat_mode="context",
    memory=memory,
    system_prompt=cfg.prompt)

# Message handler for Slack
@app.message(".*")
def message_handler(message, say, logger):    
    print(message)
    question = message['text']
    response = chat_engine.chat(str(question)).response
    say(response)


# Start your app
if __name__ == "__main__":
    SocketModeHandler(app, os.environ["SLACK_APP_TOKEN"]).start()`

**Comment by Varshan2003** [comment]
@dosu can you look into above?

**Comment by Varshan2003** [comment]
@dosu is the above solution scalable?
