### ISSUE TITLE
[Question]: How to see the intermediate step in the response synthesis

### ISSUE THREAD

**Issue by hunryandev** [run-llama/llama_index#13222]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

After retrieving the most similar nodes to my query over my index, I want to inspect the intermediate steps in the response synthesis ( What context is used for each LLM call, and what is the associated answer generated, especially for the refined response mode), so that I can better understand how it works and why I don't have a final good result. Is it possible ?

Thanks in advance for your help !

**Comment by logan-markewich** [comment]
You can enable logging for every llm input and output

```
import llama_index.core

llama_index.core.set_global_handler("simple")
```

**Comment by hunryandev** [comment]
> You can enable logging for every llm input and output
> 
> ```
> import llama_index.core
> 
> llama_index.core.set_global_handler("simple")
> ```

Sorry, I'm not that familiar with logging. So after enabling logging info for llm how can I print them to the console ?
