### ISSUE TITLE
[Question]: Stream Responses of ReAct Agent Query Engine without intermediate steps

### ISSUE THREAD

**Issue by JulianOestreich90** [run-llama/llama_index#13226]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to stream responses of a ReAct Query Engine with FastApi and so far i am doing the following:
```python
from fastapi import APIRouter, Depends, Request
from fastapi.responses import StreamingResponse
from llama_index.core.agent.react.base import ReActAgent

chat_router = r = APIRouter()

async def chat_stream(chat_engine, input_text):
    response = chat_engine.stream_chat(input_text)
    for token in response.response_gen:
        yield token

@r.post("")
async def chat(
    request: Request,
    data: _ChatData = Depends(json_to_model(_ChatData)),
    agent: ReActAgent = Depends(get_agent),
):
    lastMessage = data.messages.pop()
   
    return StreamingResponse(
        chat_stream(agent, lastMessage.content), media_type="text/event-stream"
    )
    return resp.response

```
My problem is, that this returns all the intermediate Agent Results in the the response generator. How can i just stream the final answer?

**Comment by logan-markewich** [comment]
@JulianOestreich90 What LLM are you using? I'm not actually able to reproduce this

```python
>>> from llama_index.core import VectorStoreIndex, Document
>>> index = VectorStoreIndex.from_documents([Document.example()])
>>> chat_engine = index.as_chat_engine(chat_mode="react")
>>> response = chat_engine.stream_chat("Tell me a fact about LLMs?")
>>> for token in response.response_gen:
...   print(token, end="", flush=True)
... 
LLMs are pre-trained on large amounts of publicly available data, making them a powerful tool for knowledge generation and reasoning. 
```

**Comment by JulianOestreich90** [comment]
@logan-markewich I am using multi-document agents like in the [example](https://docs.llamaindex.ai/en/latest/examples/agent/multi_document_agents/) in the documentation. I made some changes by using a ReAct Agent with Mistral-7B-Instruct-v0.2 on llama cpp instead of an OpenAIAgent. I pass the top_agent into the `chat_stream()` fkt together with the input text.

**Comment by JulianOestreich90** [comment]
The problem is solved. It just occured for specific queries.

**Comment by jp-kh-kim** [comment]
@JulianOestreich90 Hi, I'm stuck at this problem, can you share how did you solve this problem?
