### ISSUE TITLE
[Question]: How exactly do the title, keyword, summary and question answer metadata extractors work?

### ISSUE THREAD

**Issue by TitasDas** [run-llama/llama_index#13225]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm struggling to understand how the metadata extractor class functions as a feature extractor. Could you provide a simplified explanation using one of the extractors except for the entity extractor as an example?

**Comment by logan-markewich** [comment]
`node text + llm prompt = extracted summary/keywords/qa pair`

**Comment by TitasDas** [comment]
> `node text + llm prompt = extracted summary/keywords/qa pair`

What happens when I don't give the llm prompt - or when I dont use the llm parameter , does it implicitly still use a llm , if yes which one?

**Comment by TitasDas** [comment]
```
  llm: LLMPredictorType = Field(description="The LLM to use for generation.")
    nodes: int = Field(
        default=5,
        description="The number of nodes to extract titles from.",
        gt=0,
    )
    node_template: str = Field(
        default=DEFAULT_TITLE_NODE_TEMPLATE,
        description="The prompt template to extract titles with.",
    )
    combine_template: str = Field(
        default=DEFAULT_TITLE_COMBINE_TEMPLATE,
        description="The prompt template to merge titles with.",
    )
```
Snippet from the title extractor , is this the LLM you are talking about?

**Comment by TitasDas** [comment]
Also where can we find this prompt?

**Comment by TitasDas** [comment]
Ok got an answer to what prompts are used by finding the templates in [metadata_extractors.py](https://github.com/run-llama/llama_index/tree/fcdc55006055e114d4e6b606804d67bb9c2784a9/llama-index-core/llama_index).

Still couldn't find what LLM the base LLM points to but have a feeling it may be a version of llama.

**Comment by TitasDas** [comment]
Happy to close this once there is an answer to what LLM is used for the metadata extractors , I have been able to gather answers to other parts of my original question.

**Comment by logan-markewich** [comment]
@TitasDas any component that uses an llm uses what Settings.llm points to (which by default is gpt-3.5)

You can change this by modifying the settings or passing in your own llm to the extractor constructor.

**Comment by TitasDas** [comment]
Thank you so much for sharing that.
