### ISSUE TITLE
[Question]: is it possible use function + Context Retriever both combine (ContextRetrieverOpenAIAgent)

### ISSUE THREAD

**Issue by avipaghadar-maruti** [run-llama/llama_index#13221]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Our requirement is to use openAI function Calling API along with ContextChatEngine for make more better responses of users queries.

So We use JS for Write Function is there any ways for pass direct Schema in FunctionTool 

I want to execute Function if query is relavent to it otherwise normal Retriever flow of Question/Answer will execuet

**Comment by logan-markewich** [comment]
You've opened this issue twice.
