### ISSUE TITLE
Llama3-8B-Instruct not supported in `llama_index.llms.llama_cpp`

### ISSUE THREAD

**Issue by VaradDeshmukh97** [run-llama/llama_index#13237]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I used to use the Llama2-13B model from TheBloke for my application, with the `LlamaCPP()` class from `llama_index.llms.llama_cpp`. But when I changed the model to Llama3-8B GGUF from TheQuantFactory or anywhere else, the model is not downloaded. It gives me the following error:
```
Downloading url https://huggingface.co/QuantFactory/Meta-Llama-3-8B-Instruct-GGUF/blob/main/Meta-Llama-3-8B-Instruct.Q8_0.gguf to path [C:\Users\dccte\AppData\Local\llama_index\models\Meta-Llama-3-8B-Instruct.Q8_0.gguf](file:///C:/Users/dccte/AppData/Local/llama_index/models/Meta-Llama-3-8B-Instruct.Q8_0.gguf)
Error downloading model: ('Content should be at least 1 MB, but is only', '48119', 'bytes')
Download incomplete. Removing partially downloaded file.
```
I have tried using GGUF models from various HF repos, but in vain. I wonder if LlamaIndex does not yet support Llama3-8B or is there anything else?

**Comment by VaradDeshmukh97** [comment]
@dosu 
Obviously the model is greater than 1 MB in size. I didn't find anybody else facing a similar problem.

**Comment by VaradDeshmukh97** [comment]
@dosu 
This does not solve my problem. The issue persists with all the GGUF versions from multiple repos, I tried using QuantFactory, NousResearch, etc. Maybe this needs a deeper look, does it? @logan-markewich?

**Comment by logan-markewich** [comment]
@VaradDeshmukh97 seems like the URL is incorrect. Try running `wget <url>` to see if it's downloading the proper model weights. 

Otherwise though, I would just use ollama, so much easier

**Comment by logan-markewich** [comment]
(This isn't an issue with llamaindex though)
