### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.readers.web.browserbase'

### ISSUE THREAD

**Issue by VN-huster** [run-llama/llama_index#13241]
### Bug Description

In line 8 of llama_index/readers/web/__init__.py, it must be from llama_index.readers.web.browserbase_web.base import BrowserbaseWebReader. Please fix it as soon as possible

### Version

In main branch

### Steps to Reproduce

import something from llama_index.readers.web

**Comment by anirbanbasu** [comment]
I have the same problem even when I am only importing `BeautifulSoupWebReader` and `TrafilaturaWebReader`.

Line 8: `from llama_index.readers.web.browserbase.base import BrowserbaseWebReader` at `llama_index/readers/web/__init__.py` generates this problem.

Running `pip install browserbase` does not help either even though there should be no reason to install `browserbase` when I am not using it.

The import line in my code `from llama_index.readers.web import BeautifulSoupWebReader, TrafilaturaWebReader` used to work before I upgraded `llama_index` and its readers.

**Comment by logan-markewich** [comment]
Should be fixed, just need to run `pip install -U llama-index-readers-web` (will take one or two minutes to publish)

**Comment by Srushanth** [comment]
Thanks @logan-markewich.

This worked for me.

```bash
pip install -U llama-index-readers-web
```
