### ISSUE TITLE
AttributeError:  object has no attribute 'get_text_embedding_batch'

### ISSUE THREAD

**Issue by NeevrajKB** [run-llama/llama_index#13266]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

s
    new_embeddings = embed_model.get_text_embedding_batch(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'BertTokenizerFast' object has no attribute 'get_text_embedding_batch'
PS C:\Users\Admin> 

This happened because i am using 
`from llama_index.agent.openai import OpenAIAgent

agent = OpenAIAgent.from_tools(TOOLS, verbose=True)

agent.chat_repl()`

But by setting the embeddings model to
embed_model = AutoTokenizer.from_pretrained("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")
Settings.embed_model=embed_model

I am doing this because i want to use open source models for agent like Groq/Huggingface but i cant find a way to do so.

**Comment by logan-markewich** [comment]
@alineberry you set the embedding model to be a tokenizer. Probably you should do this

`pip install llama-index-embeddings-huggingface`

```
from llama_index.embeddings.huggingface import HuggingFaceEmbedding 

embed_model = HuggingFaceEmbedding(model_name="<...>", embed_batch_size=10, device="<cpu or gpu>")

**Comment by alineberry** [comment]
@logan-markewich I think you tagged me on accident

**Comment by logan-markewich** [comment]
Oops I did, whoops!

@NeevrajKB

**Comment by NeevrajKB** [comment]
😁 Man you really made my day 😂😂😂
