### ISSUE TITLE
[Question]: Combine/merge multiple VectorStoreIndex directories into a single index for querying

### ISSUE THREAD

**Issue by duotangx** [run-llama/llama_index#13264]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Many questions about this but havent seen a clean solution (other than creating a single vectorstoreindex by appending/inserting each doc to an index at the outset when initially loading the docs). Doesnt help those who have already created indices and simply want to combine previous indices with newly generated indices into a single index for querying.

Have seen references to load_indices_from_storage, GPTListIndex, MultiModalVectorStoreIndex, SummaryIndex, etc. but none seem to work.

So for clarity, let's say one has a directory, './storage', with a series of subdirectories containing indices:

./storage
├───aaa
│   └───default__vector_store.json
│   └───docstore.json
│   └───graph_store.json
│   └───image_vector.json
│   └───index_store.json
├───bbb
│   └───default__vector_store.json
│   └───docstore.json
│   └───graph_store.json
│   └───image_vector.json
│   └───index_store.json

What is the best practice for combining the 'aaa' and 'bbb' directories into a single index?

**Comment by andytan98** [comment]
Hi any update/solution for this issue? also trying to solve this
