### ISSUE TITLE
[Bug]: Join queries generate by LLM are not handled with schema appropriately

### ISSUE THREAD

**Issue by sravan-onefc** [run-llama/llama_index#13276]
### Bug Description

I tried to link a SQL style database which has few tables under a particular schema. If the LLM generates a query which has "JOIN" statement, the schema is not handled appropriately. Below is the code snippet where "FROM" is handled but "JOIN" isn't.

![Screenshot 2024-05-05 at 9 40 11 PM](https://github.com/run-llama/llama_index/assets/85609953/599fc863-35f0-475a-a1a3-d25e2782f6bf)

### Version

0.10.34

### Steps to Reproduce

Add some data in any database under any schema(no schema situation is working fine) and try to create a Text-to-SQL agent(Step 1 from [this documentation](https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo/#part-1-text-to-sql-query-engine)).

If the query generated by LLM contains any join step, the schema for the query is not handled properly and the query execution fails.

**Comment by logan-markewich** [comment]
Do make a pr if you have a fix in mind

**Comment by sravan-onefc** [comment]
Created a PR, please review: https://github.com/run-llama/llama_index/pull/13277
