### ISSUE TITLE
Trying to Create ReACT Agent using Mistral LLM using HuggingFace Inference API but getting error: NotImplementedError: Messages passed in must be of odd length.

### ISSUE THREAD

**Issue by AnandUgale** [run-llama/llama_index#13288]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Trying to Create ReACT Agent using Mistral LLM using HuggingFace Inference API but getting error

HuggingFaceAPI
import os
from getpass import getpass
from huggingface_hub import login

HuggingFace API
HF_TOKEN = getpass()

login(token=HF_TOKEN)

Loading LLM endpoint
from llama_index.llms.huggingface import HuggingFaceInferenceAPI
llm = HuggingFaceInferenceAPI(model_name="mistralai/Mistral-7B-Instruct-v0.2", token=HF_TOKEN, num_output=512, is_function_calling_model=True, is_chat_model=True)

Simple Calculator
from llama_index.core.agent import ReActAgent
from llama_index.core.llms import ChatMessage
from llama_index.core.tools import BaseTool, FunctionTool

Define Tool
def multiply(a: int, b: int) -> int:
    """Multiply two integers and returns the result integer"""
    return a * b

def add(a: int, b: int) -> int:
    """Add two integers and returns the result integer"""
    return a + b

def subtract(a: int, b: int) -> int:
    """Subtract two integers and returns the result integer"""
    return a - b

multiply_tool = FunctionTool.from_defaults(fn=multiply)
add_tool = FunctionTool.from_defaults(fn=add)
subtract_tool = FunctionTool.from_defaults(fn=subtract)

Mistral
agent = ReActAgent.from_tools([multiply_tool, add_tool, subtract_tool], llm=llm, verbose=True)
response = agent.chat("What is 20+(2*4)? Calculate step by step.")

Error -
NotImplementedError: Messages passed in must be of odd length.

**Comment by AnandUgale** [comment]
> The error you're encountering is due to the sequence of messages passed into the LlamaIndex framework not having an odd length, as it expects a pattern starting with a user message, alternating between user and assistant messages, and ending with a user message. To fix this, ensure your sequence of messages begins with a user message and follows this alternating pattern, maintaining an odd number of messages overall.
> 
> For example, you can prepend an initial system message to your sequence to adjust the number of messages:
> 
> ```python
> initial_message = "Starting calculation..."
> response = agent.chat([initial_message, "What is 20+(2*4)? Calculate step by step."])
> ```
> 
> This adjustment ensures the sequence has an odd number of messages, aligning with the framework's expectations and resolving the `NotImplementedError` you're facing.
> 
> #### Details
> _To continue the conversation, mention @dosu._

Tried your suggestion but encountering another error.

initial_message = "Starting calculation..."
response = agent.chat([initial_message, "What is 20+(2*4)? Calculate step by step."])
print(str(response))

error -
ValidationError: 1 validation error for Task
input
  str type expected (type=type_error.str)

**Comment by AnandUgale** [comment]
> ```python
> HuggingFaceLLM
> ```

I am trying to access it using the **HuggingFace Inference API**, not with **HuggingFace LLM**. Can you tell me how it could be possible using the **HuggingFace Inference API**?

**Comment by AnandUgale** [comment]
> Yea huggingface does not like system messages from some LLMs
> 
> You'll have to write your own messages_to_prompt() function hook to transform message objects into a prompt for your LLM
> 
> Here's a naive way for mistral
> 
> ```python
> def messages_to_prompt(messages):
>   message_str = "\n".join([str(x) for x in messages])
>   return f"[INST] {message_str} [/INST] "
>   
> llm = HuggingFaceLLM(..., messages_to_prompt=messages_to_prompt)
> ```

I am trying to access it using the HuggingFace Inference API, not with HuggingFace LLM. Can you tell me how it could be possible using the HuggingFace Inference API?

**Comment by logan-markewich** [comment]
@AnandUgale agent.chat() takes a single string, not a list

**Comment by atomwalk12** [comment]
This does not solve the issue for me. I tried using the callback using the `HuggingFaceInferenceAPI`, however I am still getting the same error. I noticed that @logan-markewich proposed a solution using `HuggingFaceLLM`, however OP mentioned `HuggingFaceInferenceAPI`.
