### ISSUE TITLE
enabling row-level-security in PGvector-based embeddings

### ISSUE THREAD

**Issue by mgrabmayr** [run-llama/llama_index#13299]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I use to store the nodes & index and things work fine. as we are moving to a multi-tenant setup, I would like to extend the controls with row-level-security. For this, I would need to specify an additional column and its content when adding data. I have not found a solution to "easily" add this. Anyone else? Looking forward to insights

**Comment by logan-markewich** [comment]
I think the idea here would be just to filter based on metadata in each row/node

So put some user-id in the metadata, filter using that at retrieval time
