### ISSUE TITLE
[Question]: Redis Chat Store with ChatSummaryMemoryBuffer guide

### ISSUE THREAD

**Issue by risos8200** [run-llama/llama_index#13308]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is the redis chat store still supported?

I am trying to have a session managed based memory history, some another question recommended using chat store with keys, so I wanted to use Redis Chat Store to do so. Anyone has guide or test examples for using redischatstore with the new ChatSummaryMemoryBuffer?

**Comment by logan-markewich** [comment]
It's definitely still supported 😅 at first glance the not response looks right. I can check further in a bit

**Comment by risos8200** [comment]
Thanks a lot, @logan-markewich , please let me know!

And just to confirm I can pass chat_summary_memory_buffer to the agent.chat directly directly for dynamic updation of user conversation instead of the manual chat_summary_memory_buffer.put

**Comment by risos8200** [comment]
redis.exceptions.DataError: Invalid input of type: 'dict'. Convert to a bytes, string, int or float first.

Getting this error when building with redis client

redis_client= redis.Redis(host="myurl", port=myport,
    username="default", 
    password=os.getenv("mypassword")) 
chat_store=RedisChatStore(redis_client=redis_client)

memory = ChatSummaryMemoryBuffer.from_defaults(
chat_store=chat_store,
chat_store_key=user_key,
token_limit=512,
)

**Comment by logan-markewich** [comment]
This worked for me:

```python
from llama_index.core.memory import ChatSummaryMemoryBuffer
from llama_index.storage.chat_store.redis import RedisChatStore
from llama_index.core import Document, VectorStoreIndex

index = VectorStoreIndex.from_documents([Document.example()])

chat_store = RedisChatStore(redis_url="redis://localhost:6379")
memory = ChatSummaryMemoryBuffer.from_defaults(
    token_limit=5000,
    chat_store=chat_store,
    chat_store_key="user123"
)

chat_engine = index.as_chat_engine(
    chat_mode="condense_plus_context",
    memory=memory
)

response = chat_engine.chat("hello!")
print(memory.get_all())

chat_store = RedisChatStore(redis_url="redis://localhost:6379")
memory = ChatSummaryMemoryBuffer.from_defaults(
    token_limit=5000,
    chat_store=chat_store,
    chat_store_key="user123"
)
print(memory.get_all())
```

Although I noticed a bug in `from_defaults` for the summary buffer where it always erases the previous chat history. Will fix that

**Comment by risos8200** [comment]
I am getting `ModuleNotFoundError: No module named 'llama_index.storage'`, am I missing something here?

**Comment by risos8200** [comment]
Never mind, found it in #12364

**Comment by risos8200** [comment]
@logan-markewich seem like when you call the chat_engine, that's when the redis data gets pushed

`chat_engine = index.as_chat_engine(
    chat_mode="condense_plus_context",
    memory=memory
)
 `

How do we do that when we are using agent.chat? I tried a couple of time even added this chat_mode in agent.chat but redis doesn't seem to get updated.

**Comment by logan-markewich** [comment]
@risos8200 that's not when it gets pushed? It gets pushed on every .chat() call?

**Comment by logan-markewich** [comment]
It seems to work fine for me, other than that bug I mentioned above

**Comment by risos8200** [comment]
Base on my analysis of the code, there is ` self._memory.put(ChatMessage(content=message, role=MessageRole.USER))` in chat_enginer, but no such thing in AgentRunner, do you think it's a bug? or am I missing something?

@logan-markewich

**Comment by samayra2029** [comment]
> @risos8200 that's not when it gets pushed? It gets pushed on every .chat() call?

@risos8200  are you able to get messages showing up at Redis side? Even I am not seeing this updated at Redis side. I am using stream_chat call.

**Comment by usmanmukhtarml** [comment]
Expected type 'BaseChatStore | None', got 'RedisChatStore' instead

getting above mentioned error on the following line 

memory = ChatMemoryBuffer.from_defaults(
                token_limit=5000,
                chat_store=redis_chat_store,
                chat_store_key=user_uuid
            )
