### ISSUE TITLE
[Feature Request]: Add support for multi-tenancy in weaviate

### ISSUE THREAD

**Issue by hsm207** [run-llama/llama_index#13307]
### Feature Description

Add support for [multi-tenancy](https://weaviate.io/developers/weaviate/manage-data/multi-tenancy) (MT) in Weaviate

### Reason

MT in weaviate requires changes to the schema (enable MT) and CRUD ops (pass tenant name). How should we update the llamaindex integration to account for this?

### Value of Feature

Allow efficient support for large scale use cases. See this [blog post](https://weaviate.io/blog/multi-tenancy-vector-search#the-need-for-multi-tenancy) for examples

**Comment by hsm207** [comment]
Idea 1:


>  just update the constructor of the class to help enable multi tenancy

This is not enough, I think.

The impact of MT on weaviate is that CRUD ops need to specify a tenant.

So, assuming we want to require llamaindexusers to specify all their tenants upfront, we can do:

```
vector_store_fixed = WeaviateVectorStore(
    weaviate_client=client,
    index_name="LlamaIndex",
    # we pass our custom batch as a client_kwargs
    client_kwargs={"custom_batch": custom_batch},
    tenants = ["Foo", "Bar", "Baz"]
)
```

The problem is with querying, at the moment querying involves doing this:

```
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
```

which means the query() method needs to take something like a tenant param e.g.:

```
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?", tenant="Foo")
```

The assumption here is that users what to be able to dynamically select the tenants they want to do CRUD ops on from a single instance of WeaviateVectorStore. If that's not the case, then updating the constructor is enough and the usage will look like this:

```
vector_store_fixed _foo= WeaviateVectorStore(
    weaviate_client=client,
    index_name="LlamaIndex",
    # we pass our custom batch as a client_kwargs
    client_kwargs={"custom_batch": custom_batch},
    tenants = "Foo"

vector_store_fixed_bar = WeaviateVectorStore(
    weaviate_client=client,
    index_name="LlamaIndex",
    # we pass our custom batch as a client_kwargs
    client_kwargs={"custom_batch": custom_batch},
    tenants = "Bar"
)


vector_store_fixed_baz = WeaviateVectorStore(
    weaviate_client=client,
    index_name="LlamaIndex",
    # we pass our custom batch as a client_kwargs
    client_kwargs={"custom_batch": custom_batch},
    tenants = "Baz"
)
```

Then users will instantiate as many query engines as there are tenants and write additional code to the right query engine.  This gets more complicated if we want to support dynamic tenants i.e. users can create new tenants at run time in llama index.

**Comment by logan-markewich** [comment]
@hsm207 specifying the tenant in the constructor makes sense. If you think about a FastAPI application for example, the tenant would be in the request, and a user would create a `WeaviateVectorStore` object to serve that request (which is reasonable, especially since creating that object is basically a no-op).

For adding tenants dynamically, we could even have a classmethod (or normal method) for this? `WeaviateVectorStore.add_tenant("new_tenant", client=client, index_name=index_name)` ?

**Comment by logan-markewich** [comment]
I agree, constructors should not be making network calls @hsm207  -- this is a bad habit across vector stores honestly
