### ISSUE TITLE
[Bug]: System prompts not propogating in a query pipeline.

### ISSUE THREAD

**Issue by SinghCoder** [run-llama/llama_index#13311]
### Bug Description

Hey team, it seems like the system prompt doesn't propogates when creating an LLM and passing it to QueryPipeline.
A small reproducible example:
```python
from llama_index.llms.openai import OpenAI
from llama_index.core.callbacks.global_handlers import set_global_handler
set_global_handler("langfuse")

from llama_index.core.query_pipeline import QueryPipeline
from llama_index.core.prompts import PromptTemplate
prompt_str = "Please generate related movies to {movie_name}"
prompt_tmpl = PromptTemplate(prompt_str)
llm = OpenAI(model="gpt-3.5-turbo", system_prompt="You always respond with the message 'I won't answer this question man! I am sorry'")

p = QueryPipeline(chain=[prompt_tmpl, llm], verbose=True)

resp = p.run("Inception")
print(f"resp = {resp}")
```

Here, I set some system prompt but as you can see in the trace, it was not reflected back.
Now, when I try to put it in user prompt, it works, but that isn't something I wanted. Can someone please take a look once?

### Version

0.10.34

### Steps to Reproduce

Code is given in the body.

Not able to attach images below, so attaching here:

![image](https://github.com/run-llama/llama_index/assets/32142363/8cfd0279-3339-4aa0-913c-27c64f0b44a7)
![image](https://github.com/run-llama/llama_index/assets/32142363/3c6c871c-b394-47cf-a686-e2ba19b18d99)

**Comment by logan-markewich** [comment]
The system prompt is only used if you do llm.predict (which is only used in query engines, or if you explicitly used that method)

If you want a system prompt, you should make a prompt template that includes one

```
from llama_index.core.llms import ChatMessage, MessageRole
from llama_index.core import ChatPromptTemplate

# Text QA Prompt
chat_text_qa_msgs = [
    ChatMessage(
        role=MessageRole.SYSTEM,
        content=(
            "Always answer the question, even if the context isn't helpful."
        ),
    ),
    ChatMessage(role=MessageRole.USER, content="Please generate moves related to {movie_name}"),
]
text_qa_template = ChatPromptTemplate(chat_text_qa_msgs)

```

**Comment by SinghCoder** [comment]
but the llm interface exposes system_prompt parameter. And, it makes sense that a llm query component being used in a query pipeline is "specialized" (has a system prompt), don't you think?

**Comment by logan-markewich** [comment]
That param was basically only introduced to make modifying the system prompt on query engines easier, but tbh I lean towards thinking it should be deprecated/removed 😅

It makes more design sense to keep the llm object as "stateless" as possible and a avoiding side effects. And here you are already writing the prompt template anyways.

**Comment by SinghCoder** [comment]
Alright.. thank you so much for taking out time to explain!! Marking this closed then.
