### ISSUE TITLE
[Question]: Why indexing so slow?

### ISSUE THREAD

**Issue by jiaoqianji** [run-llama/llama_index#13313]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to create indexes for a database that is 50 GB in size, and I've spent more than 5 days running the code below without any results. Then I noticed that the GPU utilization remains at 0; what should I do to speed up the indexing process?

![image](https://github.com/run-llama/llama_index/assets/103246345/3d03172d-8568-4076-8eed-e0c7239b6ced)

```Python
import os
from datetime import datetime, timedelta
from typing import Optional, Any

from llama_index.core import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
)
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
from llama_index.core.embeddings import resolve_embed_model
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

data_path = "/databases/"
PERSIST_DIR = "/data_cache/fin_databases"
embedding_model_path = "/Qwen1.5-0.5B/"

documents = SimpleDirectoryReader(data_path).load_data()

embed_model = HuggingFaceEmbedding(
    model_name=embedding_model_path,
    device="cuda:7"
)

index = VectorStoreIndex.from_documents(documents, show_progress=True, transformations=[embed_model])

index.storage_context.persist(persist_dir=PERSIST_DIR)
```

**Comment by logan-markewich** [comment]
50GB of data is a ton of data to load into memory. I wonder if it's getting stuck there? If you hit ctrl+c, the traceback would tell us where it is in the code.

I would also suggest testing the embedding model on its own first to ensure it uses GPU
`embeddings = embed_model.get_text_embedding("Hello World!")` is an easy test

If you have the memory, you can also increase the batch size: `HuggingFaceEmbedding(..., embed_batch_size=10)` (default is 10)

**Comment by logan-markewich** [comment]
Also, by specifying `transformations=[embed_model]`, you are removing any text splitting (not sure if intended or not)

**Comment by logan-markewich** [comment]
If I was to re-write this, it might look like:

```
splitter = SentenceSplitter(chunk_size=1024, chunk_overlap=128)
vector_store = <some remote/hosted/optimized vector store, qdrant, chroma, weaviate, etc.>
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex(nodes=[], storage_context=storage_context, embed_model=embed_model)

# iter and insert in batches
cur_batch = []
for doc in SimpleDirectoryReader(data_path).iter_data():
  cur_batch.append(doc)
  if len(cur_batch) == 100:
    nodes = splitter(cur_batch)
    index.insert_nodes(nodes)
    cur_batch = []

# get the last batch
nodes = splitter(cur_batch)
index.insert_nodes(nodes)
```

**Comment by jiaoqianji** [comment]
Thanks for ur help, really apperciate it. I realized it was stuck and split it into small batches then. thanks a lot.

**Comment by BafS** [comment]
@logan-markewich when I'm trying your code (I changed the node line to `nodes = splitter.get_nodes_from_documents(cur_batch)`) I get `AttributeError: 'list' object has no attribute 'id_'`. What would be the proper way to deal with this? Indexing per batch is pretty important with a lot of data, would be great to see it in the official doc :)
