### ISSUE TITLE
Agent Translating to sql query 100% correct but None.H returned for query result [Bug]: 

### ISSUE THREAD

**Issue by RKBurkhart** [run-llama/llama_index#13324]
### Bug Description

Working on an OpenAI (gpt-3.5-turbo-0613) RAG chat agent and the agent is taking the prompt, accurately translating to the correct SQL query and running it, but I get this response:

**=== Calling Function === Calling function: AG-Database-Query with args: {"input":"SELECT CLIENT FROM CLIENT_DELIVERY"} Got output: Error: None.H**

Yet, if I copy/paste that query into SSMS I get the proper result. The code uses SQLAlchemy to connect to the database, so I hard-coded the same query against the SQLAlchemy connection and I get a valid result. Somewhere in the libraries of the llama_index agent, to the llama_index query_engine it is losing the ability to connect to get a query response. I'm happy to provide additional code, just wondering if anyone has seen this?

The primary code chunks are:

 sql_query_engine = NLSQLTableQueryEngine( sql_database = sql_database, tables=table_name, )

sql_tool = QueryEngineTool.from_defaults(
        query_engine=sql_query_engine,
        name="AG-Database-Query",
        description=DESCRIPTION,
)
agent = OpenAIAgent.from_tools(
        tools=[sql_tool],
        context=context,
        verbose=True

### Version

0.10.34

### Steps to Reproduce

1. Populate prompt variable with NL question
2. Agent resolves question to SQL query
3. SQL query returns None.H when sent to the query_engine

### Relevant Logs/Tracbacks

```shell
I am using SQLAlchemy version 2.0.30 to connect to the MS SQL Server and have validated that connection is working.
```

**Comment by RKBurkhart** [comment]
More verbose code if desired (obfuscated connection details) :

import pyodbc
import os
import logging
import sys
from llama_index.llms.openai import OpenAI
from llama_index.core import StorageContext, SQLDatabase,load_index_from_storage, QueryBundle, Settings, SimpleKeywordTableIndex, VectorStoreIndex, get_response_synthesizer
from llama_index.core.query_engine import RetrieverQueryEngine, SQLAutoVectorQueryEngine
from llama_index.core.indices.struct_store.sql_query import NLSQLTableQueryEngine
from llama_index.core.tools import QueryEngineTool,FunctionTool 
from llama_index.core.agent import ReActAgent
from note_engine import note_engine
from llama_index.agent.openai import OpenAIAgent
#from llama_index.core.readers.database import DatabaseReader
from llama_index.core.chat_engine import SimpleChatEngine
from llama_index.core.chat_engine.context import ContextChatEngine
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.base.llms.types import ChatMessage
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.data_structs import Node
from llama_index.core.schema import TextNode,NodeWithScore 
from prompts import new_prompt,context
from typing import Dict,List
from sqlalchemy import (
    create_engine,
    Table,
    Column,
    String,
    Integer,
    select,
    column,
    MetaData,
    text
)
from llama_index.core.retrievers import (
    BaseRetriever,
    VectorIndexRetriever,
    KeywordTableSimpleRetriever,
    NLSQLRetriever,
)



def askAsst(prompt:str,num_clicks):
     if num_clicks == 0:
        print('Update Prevented.')
        raise PreventUpdate
     else:
        llm = OpenAI(model_name="gpt-3.5-turbo-0613",
             temperature=0,
             streaming=True)

        embedding = OpenAIEmbedding()

        Settings.llm = llm
        Settings.embed_model=embedding
        Settings.chunk_size = 1024


        #setup SQLAlchemy connection
        server = "{db server}"
        database = "{db name}"
        driver = "SQL Server"
        db_conn = f'mssql://{server}/{database}/?driver={driver},trusted_connection=true'
        engine = create_engine('mssql+pyodbc://@' + server + '/' + database + '?trusted_connection=yes&driver=ODBC+Driver+17+for+SQL+Server')
        conn = engine.connect()
        metadata_obj = MetaData()
        metadata_obj.create_all(engine)
       

        sql_database = SQLDatabase(engine,include_tables=["{table_name}"])
        table_name = "{table_name}"

        sql_query_engine = NLSQLTableQueryEngine(
            sql_database = sql_database,
            tables=table_name,
        )

        context = """data source NL context"""

        DESCRIPTION = """table NL description"""

        sql_tool = QueryEngineTool.from_defaults(
            query_engine=sql_query_engine,
            name="HMI-Database-Query",
            description=DESCRIPTION,
        )

        agent = OpenAIAgent.from_tools(
            tools=[sql_tool],
            context=context,
            verbose=True
        )

        while True:
            response = agent.chat(prompt)

            return(str(response))

**Comment by logan-markewich** [comment]
@RKBurkhart the code to run SQL is here. Maybe you can spot the issue or use this class yourself to test SQL

https://github.com/run-llama/llama_index/blob/abfd92a289ce459ce4b7960f9542439e1c796171/llama-index-core/llama_index/core/utilities/sql_wrapper.py#L210

**Comment by RKBurkhart** [comment]
Thanks Logan, I'll give that a try.

**Comment by RKBurkhart** [comment]
Hi Logan,

I'm not able to make this work. I thought I could just import the wrapper class and create a new object based on it, but I must be doing something wrong. Can you provide a little more guidance?

**Comment by logan-markewich** [comment]
I'm pretty sure that's all you need to do. Whats the issue/error?

**Comment by RKBurkhart** [comment]
Cannot import Name SQLDatabase from module li_main (e.g. the wrapper)

**Comment by logan-markewich** [comment]
Hmm, I'm not sure what your wrapper is doing, but this is the import I would run

`from llama_index.core.utilities.sql_wrapper import SQLDatabase`

**Comment by RKBurkhart** [comment]
Logan, I resolved the issue by cleaning up my code and it is working. Not 100% sure what caused it, but something in my code definitely did. Thanks for your help.

**Comment by logan-markewich** [comment]
Cool! Glad it works!
