### ISSUE TITLE
Multiple Metadata filters are not working after version upgradation

### ISSUE THREAD

**Issue by VRSupriya** [run-llama/llama_index#13322]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was using llama_index 0.9.36 earlier. I could filter the azure ai search using multiple metadata filters. The code is given below

from llama_index.core.vector_stores import (
    MetadataFilter,
    MetadataFilters,
    FilterOperator,
    ExactMatchFilter,
    FilterCondition
)

metadata_filters = MetadataFilters(
    filters=[
        ExactMatchFilter(key="l_65c356b6725083ba39975d56", value="True"),
        ExactMatchFilter(key="file_guid",  value="1234"),
    ]
)

query_engine = index.as_query_engine(text_qa_template=qa_template, similarity_top_k = 2, filters=metadata_filters)

Now after upgrading to latest version 0.10.34 and adding additional libraries llama-index-embeddings-azure-openai==0.1.9, llama-index-llms-azure-openai==0.1.7, llama-index-vector-stores-azureaisearch==0.1.5, I am getting following error for the same code.

Invalid expression: Syntax error at position 93 in 'l_65c356b6725083ba39975d56 eq 'True' {metadata_filters.condition.value} file_guid eq '1234''.
Parameter name: $filter
Code: 
Message: Invalid expression: Syntax error at position 93 in 'l_65c356b6725083ba39975d56 eq 'True' {metadata_filters.condition.value} file_guid eq '1234''.
Parameter name: $filter

**Comment by VRSupriya** [comment]
tried below code as well. But getting same error

metadata_filters = MetadataFilters(
    filters=[
        MetadataFilter(key="l_65c356b6725083ba39975d56", value="True",operator=FilterOperator.EQ),
        MetadataFilter(key="file_guid",  value="1234",operator=FilterOperator.EQ),
    ],
condition= FilterCondition.AND
)

**Comment by GillesJ** [comment]
MetadataFilter with Azure AI Search seem to be huge mess, good luck getting anything working beyond exact matching of literals.
