### ISSUE TITLE
[Question]: How can attempting mathematical calculations be prevented?

### ISSUE THREAD

**Issue by Leo-at-PR** [run-llama/llama_index#13334]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

We using LLama Index for a chatbot to answer engineering-related questions. We have a large library of PDFs which we use for Q&A. We are currently using the `ContextChatEngine` class to allow for chat history. One problem we have come across quite extensively is that the LLM attempts to make mathematical calculations (which it often gets wrong) which we would like to minimise. We are using OpenAI's `text-embedding-3-large` for embeds, a chunk size of 256, and the `mixtral-8x7b-32768` model via Groq because, in testing, gpt-3.5-turbo is not good enough and gpt-4 is too slow.

We have attempted to modify the `system_prompt` parameter a few times, as seen below. However, it does not seem to be influenced by it:
```py
engine = ContextChatEngine.from_defaults(
    retriever=retriever, # using VectorIndexRetriever with top k at 5
    node_postprocessors=node_postprocessors, # similarity cutoff at 0.4. Anything over tends to come back with less than 5 sources (sometimes 0, meaning it is all hallucinated)
    system_prompt=(
        "You are a knowledgeable chatbot capable of answering focused and specific questions about engineering. "
        "You always keep your answers short and concise. "
        "You do not attempt to make any mathematical calculations. At most, you can provide a formula if one is known."
    )
)
```
And then using the `chat(self, message: str, chat_history: Optional[List[ChatMessage]] = None)` method:
```
Question:
what is the bending capacity of a scaffold tube?
```
```
Answer:
The bending capacity of a scaffold tube can be calculated using the formula:

M = S * fy
where M is the bending capacity (moment), S is the plastic section modulus, and fy is the characteristic yield stress.

For a type 4 steel scaffold tube with an outer diameter of 48.3 mm and a nominal thickness of 4.0 mm, the bending capacity is:

M = 1.57 cm³ * 7.87 N/mm² = 12.3 kNm

Note: This calculation assumes that the scaffold tube is subjected to pure bending, which may not always be the case in practical applications.
```
The formula given in the answer is not part of the PDF content; however, some of the numerical values are. We would ideally like it to stop at the formula (if it is found, or at the minimum any numerical values that are included in the PDF content) and not attempt to provide any numerical calculations. Almost all questions with formulas and mathematics also result in hallucination (using the `FaithfulnessEvaluator` class), whereas most other focused questions which are more text-retrieval-based are not hallucinated.

Thanks!

**Comment by kavishsathia** [comment]
Hi @Leo-at-PR,

You can probably give examples for the AI model to better understand what you mean.
For instance:

```python
engine = ContextChatEngine.from_defaults(
    retriever=retriever, # using VectorIndexRetriever with top k at 5
    node_postprocessors=node_postprocessors, # similarity cutoff at 0.4. Anything over tends to come back with less than 5 sources (sometimes 0, meaning it is all hallucinated)
    system_prompt=(
        """
          You are a knowledgeable chatbot capable of answering focused and specific questions about engineering.
          You always keep your answers short and concise.
          You should not attempt to make any mathematical calculations. At most, you can provide a formula if one is known.

          For example, given that you know that the constant m has the value of 2 kg and the constant a has the value of 9.81
          m/s^2, and you are aware that F = ma, I need you to generate a response that resembles: 'F = ma = 2 kg * 9.81 m/s^2'. You
          should not calculate the actual value of 2 kg * 9.81 m/s^2.

        """
    )
)
```

You should adjust the example based on your data, and you could even provide more than 1 example if this doesn't work. Hope this helps!

**Comment by Leo-at-PR** [comment]
Thanks for the suggestion @kavishsathia. We actually fixed it by changing the LLM to `llama3-8b-8192` via Groq. We found that:
- LLama 3 70B and GPT-4 were too slow
- Mixtral wasn't listening to the system prompts
- GPT-3.5-turbo's answers weren't great (lacking important detail).

We also added a `context_template` to the `ContextChatEngine` to reiterate the system prompt:
```py
context_template = (
    "Context information is below."
    "\n--------------------\n"
    "{context_str}"
    "\n--------------------\n"
    "Do not attempt to make any mathematical calculations, instead provide a formula but only if it is explicitly stated within the context."
    "Do not attempt to make up formulas from numerical values in the context."
)

engine = ContextChatEngine.from_defaults(
    retriever=retriever,
    node_postprocessors=node_postprocessors,
    system_prompt=(
        "You are a knowledgeable chatbot capable of answering focused and specific questions about engineering. "
        "You always keep your answers short and concise. "
        "Do not attempt to make any mathematical calculations, instead provide a formula if one is known."
        "Do not attempt to make up formulas from numerical values that you know."
    ),
    context_template=context_template,
)
```
And the outcome:
```
Question:
what is the bending capacity of a scaffold tube?
```
```
Answer:
According to the provided context, the bending capacity of a scaffolding tube is not explicitly stated.
However, it is mentioned that the safe axial tensile load for Type 4 scaffold tube is 79.1 kN, and the 
safe slip load capacity of one coupler is 6.1 kN.
```
This time, the values are in the provided documents and are correct.
