### ISSUE TITLE
[Feature Request]: Enable option to apply preprocessor on input query string and use original query string in response synthesizer

### ISSUE THREAD

**Issue by flamelite** [run-llama/llama_index#13332]
### Feature Description

Enable option to apply preprocessor on input query string and use original query string in response synthesizer.
Eg. Say it is needed to remove the stopwords from original query string to improve the query embedding generation and in the during response synthesis using LLM chat completion original query string needs to be passed.

### Reason

It is needed to remove the stopwords from original query string to improve the query embedding generation

**Comment by logan-markewich** [comment]
You can specify separate strings for response synthesizer vs. retrieval 

```python
from llama_index.core import QueryBundle

query_engine.query(QueryBundle(query_str="Hello", custom_embedding_strs=["Other string", ...]))
```
