### ISSUE TITLE
[Question]: Does `gpt-4-32k` still exist and should be in `llama_index` code?

### ISSUE THREAD

**Issue by Danipulok** [run-llama/llama_index#13339]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Here's my small investigation on all models from [gpt4 models](https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4) and [gpt 3.5 models](https://platform.openai.com/docs/models/gpt-3-5-turbo).

1. Judging by following API answer, `gpt-4-32k` does not exist anymore.
> gpt-4-32k ("The requested model \'gpt-4-32k\' does not exist.")

Can anyone confirm \ deny this, and any thoughts on deleting invalid \ partly available models from the models list?

2. Also, it's really strange `gpt-4-32k` and `gpt-4-32k-0613` are invalid but `gpt-4-32k-0314` is valid. 
Any idea why?

3. `openai` python SDK has wrong type hints. For example, `gpt-4-vision-preview` can be used for assistants judging by the hints, and `gpt-4-1106-vision-preview` is unknown at all. 

**Code**
```python
from openai.resources.beta import Assistants
from openai import Client

API_KEY = "..."
client = Client(api_key=API_KEY)
assistant = Assistants(client)

models = [
    "gpt-4-turbo",
    "gpt-4-turbo-2024-04-09",
    "gpt-4-0125-preview",
    "gpt-4-turbo-preview",
    "gpt-4-1106-preview",
    "gpt-4-vision-preview",
    "gpt-4-1106-vision-preview",
    "gpt-4",
    "gpt-4-0314",
    "gpt-4-0613",
    "gpt-4-32k",
    "gpt-4-32k-0314",
    "gpt-4-32k-0613",
    "gpt-3.5-turbo",
    "gpt-3.5-turbo-16k",
    "gpt-3.5-turbo-0301",
    "gpt-3.5-turbo-0613",
    "gpt-3.5-turbo-1106",
    "gpt-3.5-turbo-0125",
    "gpt-3.5-turbo-16k-0613",
]


def check_chat_models() -> None:
    for model in models:
        try:
            result = client.chat.completions.create(
                model=model,
                messages=[
                    {"role": "system", "content": "You are a helpful assistant."},
                    {"role": "user", "content": "2+2=?"},
                ]
            )
        except Exception as e:
            print(f"{model} ❌: {repr(e)}")
        else:
            print(f"{model} ✅: {result}")

def check_assistant_models() -> None:
    for model in models:
        try:
            result = assistant.create(
                name=f"My `{model}` Assistant",
                model=model,
            )
        except Exception as e:
            print(f"{model} ❌: {repr(e)}")
        else:
            print(f"{model} ✅: {result}")


if __name__ == '__main__':
    check_chat_models()
    check_assistant_models()
```

**Raw output:**
https://pastebin.com/raw/1p6aQkLB
### Summary:
**Valid chat models:**
```
gpt-4-turbo
gpt-4-turbo-2024-04-09
gpt-4-0125-preview
gpt-4-turbo-preview
gpt-4-1106-preview
gpt-4-vision-preview
gpt-4-1106-vision-preview
gpt-4
gpt-4-0314
gpt-4-0613
gpt-4-32k-0314
gpt-3.5-turbo
gpt-3.5-turbo-16k
gpt-3.5-turbo-0301
gpt-3.5-turbo-0613
gpt-3.5-turbo-1106
gpt-3.5-turbo-0125
gpt-3.5-turbo-16k-0613
```

**Invalid chat models:**
```
gpt-4-32k (The model `gpt-4-32k` does not exist or you do not have access to it.)
gpt-4-32k-0613 (The model `gpt-4-32k-0613` does not exist or you do not have access to it.)
```

**Valid assistant models:**
```
gpt-4-turbo
gpt-4-turbo-2024-04-09
gpt-4-0125-preview
gpt-4-turbo-preview
gpt-4-1106-preview
gpt-4
gpt-4-0314
gpt-4-0613
gpt-4-32k-0314
gpt-3.5-turbo
gpt-3.5-turbo-16k
gpt-3.5-turbo-0613
gpt-3.5-turbo-1106
gpt-3.5-turbo-0125
gpt-3.5-turbo-16k-0613
```

**Invalid assistant models:**
```
gpt-4-vision-preview ("The requested model \'gpt-4-vision-preview\' cannot be used with the Assistants API.")
gpt-4-1106-vision-preview ("The requested model \'gpt-4-1106-vision-preview\' cannot be used with the Assistants API.")
gpt-4-32k ("The requested model \'gpt-4-32k\' does not exist.")
gpt-4-32k-0613 ("The requested model \'gpt-4-32k-0613\' does not exist."")
gpt-3.5-turbo-0301 ("The requested model \'gpt-3.5-turbo-0301\' cannot be used with the Assistants API.")
```

### Question
Should `gpt-4-32k` be removed from the list or it still exists?

**Comment by logan-markewich** [comment]
Feel free to clean this up 😓 OpenAI changes their models like every week, so some of these are probably out of date. But we mostly just need this to map context size to model name

But on the other hand, users don't really interact with this list directly, they just provide model names 🤷🏻

**Comment by Danipulok** [comment]
It's just if I remember correctly earlier (like 2-3 months ago maybe) when I used model name that was valid but not in `llama_index` list of context, there was some error like 'unknown model'. Was this behavior changed?

**Comment by logan-markewich** [comment]
That still happens. I guess my comment was referring more to models that were older, rather than models that might be missing (I try my best to keep up with at least adding new models, the community is usually vocal when a valid model is missing)

**Comment by Danipulok** [comment]
Okay, got it. Thanks so much for answering my questions!
