### ISSUE TITLE
[Feature Request]: Add support for IN filter in weaviate

### ISSUE THREAD

**Issue by hsm207** [run-llama/llama_index#13344]
### Feature Description

Add support for llamaIndex's `IN` filter, which gets translated to Weaviate's [`ContainsAny` ](https://weaviate.io/developers/weaviate/search/filters#containsany-filter)filter.

### Reason

¯_(ツ)_/¯

### Value of Feature

See this [comment](https://github.com/run-llama/llama_index/pull/13229/files/1f5002aa0972c95e9b5cdc78a12c19158603e50b#r1593006633)

**Comment by andrewisplinghoff** [comment]
`ContainsAny` is available via `FilterOperator.ANY` by now so having `FilterOperator.IN` additionally might not be required.

Implemented in https://github.com/run-llama/llama_index/commit/4eab119528b74eabcfbeff33822b171cae94005f#diff-cb2abb4f6be801ec45439b0b1ec8301968020f30136a00dd69f5403a0e81a6d8R61-R64
