### ISSUE TITLE
[Question]: How to classify the data using llama-index(using LLM)

### ISSUE THREAD

**Issue by Varshan2003** [run-llama/llama_index#13355]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello all, we are facing an issue to classify the jira tickets as FP,Owner reassignments and other, our data is also limited (about 200 comments per category ) we tried different ML models and RAG approache using llama-index, how can we solve this issue?

**Comment by logan-markewich** [comment]
LLM is maybe overkill, but could definitely work. I would just use a pydantic class with a prompt

```
from pydantic.v1 import BaseModel, Field
from typing import Literal

class TicketClassification(BaseModel):
  owner: str = Field(description="The most likely owner of the ticket based on the ticket data.")
  ticket_type: Literal["feature", "bug", "documentation"] = Field(description="The type of the ticket.")


from llama_index.program.openai import OpenAIPydanticProgram

prompt_template_str = """\
Given the ticket data below, classify the ticket and provide an owner.

Ticket Data:
{ticket_data}
"""
program = OpenAIPydanticProgram.from_defaults(
    output_cls=TicketClassification, prompt_template_str=prompt_template_str, verbose=True
)

output = program(ticket_data=ticket_data)
print(output.owner)
print(output.ticket_type)
```

More examples from here
https://docs.llamaindex.ai/en/stable/module_guides/querying/structured_outputs/pydantic_program/


As for ML models, have you looked into models like Gliner or NuNER? 
https://huggingface.co/urchade/gliner_base
https://huggingface.co/models?sort=trending&search=NuNER

**Comment by logan-markewich** [comment]
Going to close this out though, as the above are really two of the best suggestions
