### ISSUE TITLE
[Bug]: Code in Guidance Pydantic Program doc not working

### ISSUE THREAD

**Issue by ubervincent** [run-llama/llama_index#13379]
### Bug Description

Simply following the code in https://docs.llamaindex.ai/en/stable/examples/output_parsing/guidance_pydantic_program/ would yield 

ModuleNotFoundError: No module named 'guidance.llms'

### Version

llama-index = "^0.10.35"

### Steps to Reproduce

Follow the doc in their project.

**Comment by logan-markewich** [comment]
Likely the guidance package has updated.

Very open to contributions to update the notebook
