### ISSUE TITLE
[Question]: Is `llama_index` thead-safe?

### ISSUE THREAD

**Issue by ashishb** [run-llama/llama_index#13375]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is it safe to use `llama_index` for multiple LLM requests in parallel?
Is it thread-safe or does one need locking?

**Comment by logan-markewich** [comment]
In general I think it depends what features you are using. Most LLM clients have some internal locking (like the openai client does). Things that are writing to in-memory objects are likely not thread safe (like the default vector store). Reading is typically fine though.

In general, using async/concurrency will be much safer than trying to manage threads.

**Comment by ashishb** [comment]
> In general, using async/concurrency will be much safer than trying to manage threads.

@logan-markewich thanks. Can you elaborate on `using async/concurrency will be much safer than trying to manage threads.`? Any examples/docs would be helpful.

Context: I am using `llama-index` with a Python web server.

**Comment by logan-markewich** [comment]
I just mean using async calls in something like fastapi (I.e query_engine.aquery(), chat_engine.achat() , etc.). 

Otherwise for threading, it's safer to create objects from scratch for each request, (and use remote models and vector stores)
