### ISSUE TITLE
[Question]: BM25 Retriever takes long time to load with docstore are its parameter

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#13389]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using bm25retriever. 

`
BM25Retriever.from_defaults(docstore=get_document_store() , similarity_top_k = 10)
`

this takes a long time to get initialized. Any way to make it fast.

Another question is, will changing it to MongodbAtlasBM25retriever make it faster

**Comment by logan-markewich** [comment]
There's no way to make it faster that I know of. It's loading all the nodes from the docstore that can be slow.

You can get those nodes another way if you want, and pass them in instead of a docstore
