### ISSUE TITLE
[Question]: AttributeError: 'NoneType' object has no attribute 'search'

### ISSUE THREAD

**Issue by Amiya-Lahiri-AI** [run-llama/llama_index#13391]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using QueryFusionRetriever

`from llama_index.core.retrievers import QueryFusionRetriever

retriever = QueryFusionRetriever(
    [vector_retriever, bm25_retriever],
    similarity_top_k=4,
    num_queries=4,
    mode="reciprocal_rerank",
    verbose=True,
)`

`from llama_index.core.postprocessor import (
    MetadataReplacementPostProcessor,
    SimilarityPostprocessor,
)
from llama_index.core.postprocessor import SentenceTransformerRerank
from llama_index.core.query_engine import RetrieverQueryEngine

query_engine = RetrieverQueryEngine.from_args(retriever,
                        node_postprocessors=[
                            MetadataReplacementPostProcessor(target_metadata_key="window"),
                            SentenceTransformerRerank(
                                model="BAAI/bge-reranker-base"
                            )
                        ],
                )`

after that I am asing a query 
response = query_engine.query("what are requimenets to submit the tender")
however I am facing an error AttributeError: 'NoneType' object has no attribute 'search'
it is coming from the engine_query 
Can anyone please help me out why I am getting this error

**Comment by logan-markewich** [comment]
You are using qdrant I'm guessing? Provide the async client 

`QdrantVectorStore(..., client=QdrantClient(...), aclient=AsyncQdrantClient(...))`

Note that if using `:memory:` mode, these clients do not share data

**Comment by Amiya-Lahiri-AI** [comment]
Hi @logan-markewich 
thanks for your reply. I am indeed using QdrantVectorStore
`
import qdrant_client
from llama_index.vector_stores.qdrant import QdrantVectorStore
client = qdrant_client.QdrantClient(
    url="https://a9e22f35-d4a5-48eb-9ffb-eae1aab5ab2d.us-east4-0.gcp.cloud.qdrant.io:6333",
    api_key="LESIaUhAIdFeB1C9glPB2nYsYu0Gq4ixi_sGbKuEh8OSxhMScDok7w",
)
asynclient = qdrant_client.AsyncQdrantClient(
    url="https://a9e22f35-d4a5-48eb-9ffb-eae1aab5ab2d.us-east4-0.gcp.cloud.qdrant.io:6333",
    api_key="LESIaUhAIdFeB1C9glPB2nYsYu0Gq4ixi_sGbKuEh8OSxhMScDok7w",
)
vector_store = QdrantVectorStore(client=client, collection_name="Tender-Db", aclient=asynclient)
`
however can you please tell me why I was getting the error in the first place.
also after integrating your solution I am getting this warning message 
WARNING:llama_index.vector_stores.qdrant.base:Both client and aclient are provided. If using `:memory:` mode, the data between clients is not synced.
can't I just use QdrantClient without using the AsyncQdrantClient?

**Comment by logan-markewich** [comment]
That warning is fine

Qdrant supports both async and sync operations. Some features use async, and need the async client

**Comment by Amiya-Lahiri-AI** [comment]
ok thank you @logan-markewich
