### ISSUE TITLE
[Question]: why PostgresKVStore table class does not match my postgres vector table schema?

### ISSUE THREAD

**Issue by jodiewuxi** [run-llama/llama_index#13392]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

**Question**
I  am using PostgresDocumentStore and PostgresKVStore  to get Next and Prev node .  But I got the follow error 
> psycopg2.errors.UndefinedColumn) column data_small_db.key does not exist 
> [SQL: SELECT public.data_small_db.id, public.data_small_db.key, public.data_small_db.namespace, public.data_small_db.value 
> FROM public.data_small_db 
> WHERE public.data_small_db.key = %(key_1)s AND public.data_small_db.namespace = %(namespace_1)s]

I have a vector database small_db that created by llama-index  and default schema is 

```
  Column   |       Type        | Collation | Nullable |                  Default
-----------+-------------------+-----------+----------+-------------------------------------------
 id        | bigint            |           | not null | nextval('data_small_db_id_seq'::regclass)
 text      | character varying |           | not null |
 metadata_ | json              |           |          |
 node_id   | character varying |           |          |
 embedding | vector(1536)
```

Column definition in PostgresKVStore 
```
class AbstractData(base):  # type: ignore
        __abstract__ = True  # this line is necessary
        id = Column(Integer, primary_key=True, autoincrement=True)
        key = Column(VARCHAR, nullable=False)
        namespace = Column(VARCHAR, nullable=False)
        value = Column(metadata_dtype)
```

I found the issue is that  column in PostgresKVStore not match my vector database. 
Am I missing something, or is there a bug here?

**Comment by logan-markewich** [comment]
The kvstore and vector store should be created as two different tables, with different table names and different schemas 

It seems like you are querying the vector store thinking it has the same fields as the kv store?
