### ISSUE TITLE
[Bug]: DEFAULT_RESPONSE_SYNTHESIS_PROMPT missing

### ISSUE THREAD

**Issue by Hspix** [run-llama/llama_index#13425]
### Bug Description

After upgrading `0.10.14` to `0.10.36`, `from llama_index.core.query_engine.pandas.pandas_query_engine import DEFAULT_RESPONSE_SYNTHESIS_PROMPT` is error.

### Version

0.10.36

### Steps to Reproduce

`from llama_index.core.query_engine.pandas.pandas_query_engine import DEFAULT_RESPONSE_SYNTHESIS_PROMPT`

**Comment by logan-markewich** [comment]
Pandas query engine got moved to experimental 

`pip install llama-index-experimental`

In this case, it's here
https://github.com/run-llama/llama_index/blob/e1711ce5f95b7a6004d1c48a306699359296646b/llama-index-experimental/llama_index/experimental/query_engine/pandas/pandas_query_engine.py#L53

`from llama_index.experimental
