### ISSUE TITLE
[Question]: Can llama-index milvus vector store use Milvus'es built-in embedding models that they provide instead of using openai for embedding?

### ISSUE THREAD

**Issue by mballav** [run-llama/llama_index#13421]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

We are considering using Milvus on the cloud (zilliz.com) as a managed solution for storing and querying our vectors. Right now, if we use Open AI to get our documents vectorized, it takes a long time if there are more than say 10 documents. 

Also, we are using llama-index (over langchain) for our RAG application. 

All the examples I found, that showcase use of Milvus vector store, use Open AI for embedding. Is there a way to use Milvus'es built-in local models for embedding which will likely speed up the document uploads.

Any pointers or any alternative solution will be greatly appreciated.

**Comment by logan-markewich** [comment]
You can't use milvus's built-in embeddings, but you can
- increase the batch size on openai: `embed_model = OpenAIEmbedding(..., embed_batch_size=2000)`
- run your own model locally
- use the zilliz managed index: https://docs.llamaindex.ai/en/stable/examples/managed/zcpDemo/

**Comment by wxywb** [comment]
> @logan-markewich, Thanks a lot for the prompt reply.
> 
> Looking at the options that you mentioned, option #3 is appealing, though even zilliz managed index requires openai key. I am assuming that zilliz under the hood vectorizes a document using OpenAI's text-ada model. If we go that route, do you think that their pipeline would be any faster than if we ourselves vectorized using OpenAI?
>
@mballav zilliz managed index can use a hosted version of bge models, checkout [this](https://docs.zilliz.com/docs/pipelines-text-data) for all supported models.
