### ISSUE TITLE
[Bug]: Unable to delete pinecone stored vectors with new pinecone serverless index architecture 

### ISSUE THREAD

**Issue by OmriNach** [run-llama/llama_index#13451]
### Bug Description

Pinecone is forcing all free plans to migrate to serverless indexes. According to their release, with serverless you are no longer able to delete vectors by metadata filtering, which is the primary way to delete using llama_index:
`   def delete(self, ref_doc_id: str, **delete_kwargs: Any) -> None:
        """
        Delete nodes using with ref_doc_id.

        Args:
            ref_doc_id (str): The doc_id of the document to delete.

        """
        # delete by filtering on the doc_id metadata
        self._pinecone_index.delete(
            filter={"doc_id": {"$eq": ref_doc_id}},
            namespace=self.namespace,
            **delete_kwargs,
        )`

Currently, the new way to remove ids belonging to the same document is to use 
`# To iterate over all result pages using a generator function
for ids in index.list(prefix='doc1#', namespace='ns1'):
    print(ids)
  index.delete(ids=ids, namespace=namespace)`

This requires knowledge of the vector id that was used when llama_index uses the vector_store.add method. 
`        self._pinecone_index.upsert(
            entries,
            namespace=self.namespace,
            batch_size=self.batch_size,
            **self.insert_kwargs,
        )
        return ids`
However, when you use a vector_store as part of the ingestion pipeline class, the vector ids are not returned in the run method:
```
        if self.vector_store is not None:
            self.vector_store.add([n for n in nodes if n.embedding is not None])

        return nodes
```
How should one be deleting from pinecone now? I think it's pretty useful information to store the pinecone vector ids for both tracking purposes and deleting now that it is essential.

### Version

0.10.30

### Steps to Reproduce

Index a document to pinecone and try to remove it

**Comment by OmriNach** [comment]
@dosu although the add method returns the vector ids, when it is called from the ingestion pipeline run method, this run method does not return the ids. 

and the approach you provided seems rather convoluted for something as simple as deleting vectors, i think a better solution is to modify the pineconevectorstoree class similar to the modification in the __init__ method to identify the pinecone version and serverless or not in order to initiate the pinecone client, to do the same for delete

**Comment by stg609** [comment]
How is it going? I just encountered the same issue using version 0.10.57
