### ISSUE TITLE
[Question]: Similarity_Top_K returns fewer nodes than requested 

### ISSUE THREAD

**Issue by Jez77** [run-llama/llama_index#13457]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I get inconsistent performance when retrieving documents. I am not sure if this is down to something in llamaindex or something perhaps in Pinecone, my vector db store. I have two indexes: A and B. Both contain substantially the same content except that B is chunked differently to A. 

When I run a similarity top K = 17 on index A, I get 17 results, as expected. When I run the same code but set the pinecone index to B, I get some random number of nodes always less than 17. If I ask for 7 nodes I may get back 2 or 4. If I ask for 100 I get back 70 or 75, it varies. I can't fathom why I don't get back the number of nodes I request (17 or 100, or whatever), I do in my other index. Can anyone shed any light on why this might be the case please? 

The only setting I'm changing is the name of the pincone index in this code: 

pinecone_index = pc.Index(name=os.environ['PINECONE_NAME'])

This is all I'm using for retrieval:

retriever = VectorIndexRetriever(
    index=index,
    similarity_top_k=17,
)

I'm looking at the number of returned nodes using 
        len(response)

and looking through the actual nodes via 
        for node_with_score in response:
            node = node_with_score.node
etc.

**Comment by Jez77** [comment]
@dosu 
The only difference is that index A chunks on a 1024 basis whereas index B chunks on a 2048 basis. Otherwise, the indexes are identical. 

There is no filtering. The parameters are identical between the indexes. Both indexes use 3072 dimensions. 

The indexes are both capable of returning the number of documents I request, since index B if asked for 100 docs can return 70, so it must be capable of returning 17 if only asked for 17.

**Comment by logan-markewich** [comment]
@Jez77 there is a step that removes duplicates in the base retriever class -- perhaps you have duplicate data in your pinecone index?

**Comment by wheynelau** [comment]
Could you manually set the similarity thresholds to see if it does anything? I've never used pinecone but wondering if they have some kind of dynamic threshold
