### ISSUE TITLE
[Feature Request]: Allow RagEvaluatorPack to use HuggingFace/Open Source Embeddings

### ISSUE THREAD

**Issue by v-sonawane** [run-llama/llama_index#13460]
### Feature Description

This will allow user's to evaluate their RAG pipeline with the synthetic eval dataset generated using llama_index.core.llama_dataset.generator without an OpenAI API Key

### Reason

Currently, RagEvaluatorPack only supports OpenAI Embeddings. While judge_llm allows the user to use open source LLMs, the method still requires an OpenAI API Key to run owing to the following code. 

Source code from llama-index-packs/llama-index-packs-rag-evaluator/llama_index/packs/rag_evaluator/base.py, line 94 

def _prepare_judges(self):
        """Construct the evaluators."""
        judges = {}
        judges["correctness"] = CorrectnessEvaluator(
            llm=self.judge_llm,
        )
        judges["relevancy"] = RelevancyEvaluator(
            llm=self.judge_llm,
        )
        judges["faithfulness"] = FaithfulnessEvaluator(
            llm=self.judge_llm,
        )
        judges["semantic_similarity"] = SemanticSimilarityEvaluator(
            embed_model=OpenAIEmbedding() #this line requires an OpenAI API key from the user's end
        )
        return judges

![image](https://github.com/run-llama/llama_index/assets/67231253/8571faa5-2a3f-41c8-b973-be78b9a76674)

**Comment by logan-markewich** [comment]
@v-sonawane fyi, the main purpose of llama-packs is to actually give you boiler-plate code you can quickly copy and modify. I highly recommend also just doing that :)
