### ISSUE TITLE
SummaryModule.__init__() got an unexpected keyword argument 'num_workers'[Question]: 

### ISSUE THREAD

**Issue by sohilbhatia** [run-llama/llama_index#13469]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`summary_prompt = "As a professional summarizer, create a concise and comprehensive summary of the provided text, be it an article, post, conversation, or passage with as much detail as possible."`

```
# Adding SummaryModule you can configure the summary prompt and number of workers doing summaries.
summary_module = SummaryModule(
    llm=OpenAI(model="gpt-3.5-turbo", temperature=0.1), summary_prompt=summary_prompt, num_workers=16)
```
    
  Why is it saying SummaryModule.__init__() got an unexpected keyword argument 'num_workers' even though:
  
```
  class SummaryModule(BaseModel):
    response_synthesizer: BaseSynthesizer = Field(description="LLM")
    summary_prompt: str = Field(
        default=DEFAULT_SUMMARY_PROMPT,
        description="Summary prompt.",
    )
    num_workers: int = Field(
        default=4, description="Number of workers to generate summaries."
    )
    show_progress: bool = Field(default=True, description="Show progress.")
```

**Comment by logan-markewich** [comment]
@sohilbhatia there is a separate init just under that, num_workers is also clearly defined there

<img width="461" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/01051eea-aba6-4a06-85e2-3f68eab7a9a1">

This works fine for me
```python
>>> from llama_index.packs.raptor.base import SummaryModule
>>> from llama_index.llms.openai import OpenAI
>>> module = SummaryModule(llm=OpenAI(), summary_prompt="test", num_workers=16)
>>> 
```

Maybe update: `pip install -U llama-index-packs-raptor`, or double check your pydantic version (mine is 2.6.4)
