### ISSUE TITLE
[Question]: Inconsistencies when providing answer using contextchatengine

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#13475]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently, I am using context chat engine for the rag application and the i am seeing some inconsistencies with it. For the exact same question sometimes it gives the correct answer and other times it does not. What causes these inconsistencies and how can i rectify this.

**Comment by logan-markewich** [comment]
Probably llm temperature? Even then, that doesn't always seem to eliminate variability
