### ISSUE TITLE
[Question]: MongoDB atlas vector search vs ChromaDB

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#13474]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently I have two rag stack where one uses mongodb atlas vector search and another one uses chromadb. Everything related to the chunk sizes, retriever and prompts are the same but the answers i receive are entirely different. When using chroma the answers are exactly what i want and when i use mongodb the answers are not good. What is the reason for this?

**Comment by logan-markewich** [comment]
Different vector search algorithms/settings in each vector db? Possibly not the same data in each db?
