### ISSUE TITLE
[Question]: How to Achieve Parallel processing in SentenceSplitter

### ISSUE THREAD

**Issue by umesh9794** [run-llama/llama_index#13473]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have below simple implementation of SentenceSplitter: 

```
# chunking logic here
splitter = SentenceSplitter(chunk_size=conf.chunk_size, chunk_overlap=conf.chunk_overlap)
for node in splitter.split_text(scrap["scrap_text"]):
   # adiitonal processing like trash removal etc goes here
```

The above code runs on Apache Spark. Still I am not seeing any parallelism happening in the SentenceSplitter level. Is this the expected behaviour or am I doing something wrong? 

If want to parallelize SentenceSplitter, is IngestionPipeline only option or can I do that without using IngestionPipeline?

**Comment by logan-markewich** [comment]
I would use multiprocessing 🤷🏻  

```
def split(x):
  splitter = SentenceSplitter(...)
  return splitter(x)

from multiprocessing import Pool

with Pool(5) as p:
    results = p.map(split, [doc2, doc2, doc3, ...])
```

**Comment by umesh9794** [comment]
@logan-markewich thanks for quick hint, however I think my issue is slightly different. The code block you shared does the parallelism for the number of docs. That I am getting from the Apache Spark workers. 

But my question is how can I split each document and do some transformation in parallel ? Sorry if I was not clear before.

**Comment by logan-markewich** [comment]
So you want to split the document into pieces and then run nodes in parallel/batches? The solution will be the same as above, or use the ingestion pipeline. I don't know how that translate to apache spark workers, never used that before

**Comment by umesh9794** [comment]
> So you want to split the document into pieces and then run nodes in parallel/batches? The solution will be similar as above, or use the ingestion pipeline. I don't know how that translate to apache spark workers, never used that before

@logan-markewich Yes you got it right.

**Comment by umesh9794** [comment]
> To achieve parallel processing for splitting each document into chunks and performing transformations on those chunks within Apache Spark, you can follow a structured approach leveraging Spark's distributed data processing capabilities:
> 
> 1. **Distribute Your Data**: Create a Resilient Distributed Dataset (RDD) or a DataFrame with your documents to distribute them across the Spark cluster.
> 
> ```python
> # Assuming `sc` is your SparkContext and `data` is your list of documents
> rdd = sc.parallelize(data)
> ```
> 
> 2. **Define Transformation Function**: Implement a function that applies the `SentenceSplitter` to split the document and then performs any additional processing required on the chunks.
> 
> ```python
> def process_document(document):
>     splitter = SentenceSplitter(chunk_size=conf.chunk_size, chunk_overlap=conf.chunk_overlap)
>     chunks = splitter.split_text(document)
>     # Perform additional processing on chunks here
>     return processed_chunks
> ```
> 
> 3. **Apply Transformations in Parallel**: Use the `map` function to apply your `process_document` function to each document in the RDD, enabling parallel processing of the document splitting and transformations.
> 
> ```python
> processed_rdd = rdd.map(process_document)
> ```
> 
> 4. **Collect or Store the Results**: After processing, you can collect the results back to the driver program or store them in an external system.
> 
> ```python
> results = processed_rdd.collect()
> ```
> 
> This method utilizes Spark's parallel processing capabilities to distribute the workload across the cluster, ensuring that each document is split and processed in parallel. The actual parallelism level will depend on your Spark cluster's configuration, such as the number of worker nodes and cores per node. Remember, Spark's transformations are lazy and only execute when an action (like `collect`) is called, allowing Spark to optimize the execution plan.
> 
> #### Details
> _To continue the conversation, mention @dosu._

I have something like this already : 

 ```
df = spark.read\
            .format("kafka")\
            .option("kafka.bootstrap.servers", conf.kafka_brokers)\
            .option("kafka.security.protocol", "PLAINTEXT")\
            .option("failOnDataLoss","false")\
            .option("subscribe", conf.kafka_topic_name)\
            .option("startingOffsets", json.dumps(offsets))\
            .option("endingOffsets", json.dumps(end_offsets))\
            .load()
    rdd = df.foreach(apply_cleanup_and_store) 
```

Now the `apply_cleanup_and_store` looks like this : 

```
def apply_cleanup_and_store(row):
   # Some preprocessing 
   ..
   # chunking logic here
   splitter = SentenceSplitter(chunk_size=conf.chunk_size, chunk_overlap=conf.chunk_overlap)
   for node in splitter.split_text(scrap["scrap_text"]):
      # adiitonal processing like trash removal etc goes here
      ..
      # Store into vector DB
```

So `apply_cleanup_and_store` runs on Spark executors. What I want to paralleize is this for loop : 
`for node in splitter.split_text(scrap["scrap_text"]):`
