### ISSUE TITLE
[Question]: How can we store ChatEngineInstance and ChatMemoryBuffer in a centrailized storage.

### ISSUE THREAD

**Issue by Varshan2003** [run-llama/llama_index#13471]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have develouped the RAG system, where multiple users are using it ,when people working parallely , we should scale our app, we are running it on ECS so we'll be running 2 or more instances, that time we have to store it in centralized location, I tried to store in REDIS cache(using pickle) it's not working,causing error in serialization and desirialization.Earlier I was using only simple dectionary, I have to store it in centrailized location now, could you please help me out.Thank you
```

user_chat_contexts = {} 
user_last_interaction = {}
def message_handler(message, say, logger):
    try:
        user_id = message['user']  
        question = message['text']
        real_name = message['user_profile']['real_name']

        if real_name in real_names:
            # Check if the user already has a chat context, if not, create one
            if user_id not in user_chat_contexts:
                memory = ChatMemoryBuffer.from_defaults(token_limit=3900)
                chat_engine = index.as_chat_engine(
                    chat_mode="context",
                    memory=memory,
                    system_prompt=cfg.prompt
                )
                user_chat_contexts[user_id] = {'memory': memory, 'chat_engine': chat_engine}

            # Update the last interaction time for the user
            user_last_interaction[user_id] = time.time()

            chat_context = user_chat_contexts[user_id]
            response = chat_context['chat_engine'].chat(str(question)).response

```
here I should store it in Centrailized storage instead of dictionary.

**Comment by logan-markewich** [comment]
The latest version of the redis chat store should work just fine (not pickling things, just saving the chat history)

https://docs.llamaindex.ai/en/stable/module_guides/storing/chat_stores/?h=chat+store#redischatstore

**Comment by logan-markewich** [comment]
since the chat history is a pydantic object, its fairly easy to serialize if you want to store somewhere else

**Comment by logan-markewich** [comment]
(note that you'd store just the chat history, not the entire memory object)

**Comment by Varshan2003** [comment]
Can I get the basic implementation of code

**Comment by logan-markewich** [comment]
The link above has all you need?

`pip install llama-index-storage-chat-store-redis`

```
from llama_index.storage.chat_store.redis import RedisChatStore
from llama_index.core.memory import ChatMemoryBuffer

chat_store = RedisChatStore(redis_url="redis://localhost:6379", ttl=300)

chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=3000,
    chat_store=chat_store,
    chat_store_key="user1",
)
```

Set the chat store key, throw that memory into your agent/chat engine, and off you go

```
index.as_chat_engine(..., memory=chat_memory)
```

**Comment by JonGerrand** [comment]
Just a note that the current documentation doesn't make the extra pip install all too obvious: 
```
pip install llama-index-storage-chat-store-redis
```

**Comment by logan-markewich** [comment]
Yea fair, that's why I included it above
