### ISSUE TITLE
[Question]: RAG on persistent VectoreStore with local Huggingface LLM

### ISSUE THREAD

**Issue by blackjackcola** [run-llama/llama_index#13478]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 Hello ! I m currently trying to use a opensource LLM for my RAG application using Llamaindex. While it works perfectly fine for the ingestion process , I cant get it working for the retrieval on a persisten Vector index. Llamaindex is ignoring my LLM Setting and trying to default Openai . I m using a local LLM on Gpu . Does anyone know a quickfix for this specific issue ? I m not a professional in machine learning , so I was hoping that somebody already had that issue and solved it . Thank you !

**Comment by logan-markewich** [comment]
@blackjackcola can you share some code? You'll need to make sure you setup both an embed model and an LLM

**Comment by blackjackcola** [comment]
Yes of course. 

Context: As of now I tried to set up the variables globally but also didn t help. What I don t understand is that it works fine for the ingestion but not for the query/chat engine. I 've also tied to set embed model to 'local'  even though I dont really need it since I dont use node-postprocessing atm.  But there is probably a dumb mistake I am making.
Aprecciate any kind of help !

CODE:

import logging
import sys
import torch
from transformers import AutoTokenizer, BitsAndBytesConfig
from llama_index.core.settings import Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.core import StorageContext, load_index_from_storage
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.llms.huggingface import HuggingFaceLLM


# Configure logging
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

# Configuration for model quantization
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Initialize HuggingFace LLM with specific settings
llm = HuggingFaceLLM(
    model_name="meta-llama/Meta-Llama-3-8B",
    tokenizer_name="meta-llama/Meta-Llama-3-8B",
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"quantization_config": quantization_config},
    generate_kwargs={"temperature": 0.1, "top_k": 50, "top_p": 0.95},
    device_map="cuda",
)

# Ensure that the local model is resolved correctly
def resolve_local_model():
    try:
        embed_model = resolve_embed_model(embed_model='local:BAAI/bge-large-en-v1.5')
        return embed_model
    except ValueError as e:
        logging.error(f"Failed to initialize the local embedding model: {e}")
        raise

embed_model = resolve_local_model()

# Load the existing index
storage_context_vector = StorageContext.from_defaults(persist_dir="./Tiny_Data_embed")
index = load_index_from_storage(storage_context=storage_context_vector)

# Set global settings
Settings.llm = llm
Settings.embed_model = embed_model

# Initialize chat memory buffer
memory = ChatMemoryBuffer.from_defaults(token_limit=4090)

# Main function
if __name__ == "__main__":
    logging.info("Loading existing embeddings and preparing for querying...\n")

    primary_chat_engine = index.as_chat_engine(
        chat_mode="context",
        memory=memory,
        llm=llm,
        system_prompt=(
            "You are a chatbot specifically designed to create Exudyn Code for Multibodysystem simulation:"
            "Here are the relevant documents for the context:\n"
            "{context_str}"
            "\nInstruction: Use the previous chat history, or the context above, to interact and help the user."
        ),
        verbose=False
    )

    while True:
        query = input("Enter your query (or type 'quit' to stop): ").strip()
        if query.lower() == "quit":
            print("Exiting the query engine.")
            break

        try:
            response = primary_chat_engine.chat(query)
        except ValueError as e:
            if "Optimizer returned zero sentences" in str(e):
                logging.info(
                    "Optimizer found zero relevant sentences. Initiating fallback chat engine..."
                )
                response = llm.complete(query)
            else:
                raise  # Re-raise the exception if it's not the one we're looking for
        except Exception as e:
            logging.error(f"Unexpected error occurred: {str(e)}")
            response = "An error occurred, please try again later."

        print("Response:", response)

**Comment by logan-markewich** [comment]
@blackjackcola you should set settings as soon as possible in your code.

Since you loaded the index before setting your settings, the index loaded with the openai defaults

**Comment by blackjackcola** [comment]
@logan-markewich  how did I not think of that ?! Thank you for your help !
