### ISSUE TITLE
[Question]: How to persist a finetuned embeddings model?

### ISSUE THREAD

**Issue by dbeltranruiz** [run-llama/llama_index#13481]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 

After following the guide https://docs.llamaindex.ai/en/stable/examples/finetuning/embeddings/finetune_embedding.html, I would like persist the trained model so that I can use it as my embedding model instead of the one of the huggingfaces.  I followed the local models guide https://docs.llamaindex.ai/en/stable/examples/embeddings/huggingface/ but couldnt make it work. Maybe is something obvious so sorry for asking if this is the case. From other side if I have the issue maybe others are also facing it.

Thank you in advance. 

Best regards,

David

**Comment by dbeltranruiz** [comment]
The problem is that I don't have the model persisted, this is what I am trying to achieve, so I can't provide any path to the OptimumEmbedding.

**Comment by dbeltranruiz** [comment]
Great, and how can I accomplish the step number 1: "Save Your Fine-Tuned Model"?

**Comment by wheynelau** [comment]
to add to the bot above, you can check the official sentence transformers documentation [here](https://sbert.net/docs/package_reference/SentenceTransformer.html).

If you have already trained it, use the `.save` method, so you need to use `your_model.model.save("output_path")`

**Comment by dbeltranruiz** [comment]
Thank you very much the combination below worked well as indicated by the bot. I was trying to pass the model name as it is resolved internally by the finetune_engine after calling get_finetuned_model via "local:model_name", but Optimum then raised an error. The issue was to not use the local name but the path where the model was persisted by the SentenceTransformer. 
    
   finetune_engine.finetune()

    OptimumEmbedding.create_and_save_optimum_model(
        model_name_or_path=output_model,
        output_path=output_path
    )

     Settings.embed_model = OptimumEmbedding(folder_name=output_path)
