### ISSUE TITLE
[Bug]: System prompt not working in llm.chat or llm.complete

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#13494]
### Bug Description

I have the following code creating an openAI model

```
from llama_index.core.base.llms.generic_utils import prompt_to_messages
token_counter = TokenCountingHandler(
        tokenizer=tiktoken.encoding_for_model("gpt-4-turbo-2024-04-09").encode)
llm = OpenAI(
        model="gpt-4-turbo-2024-04-09",
        api_key=get_secret_from_secret_manager(
            "test/openai_api_key", "OPENAI_API_KEY"
        ),
        max_new_tokens=300,
        callback_manager=CallbackManager([token_counter]),
        temperature=0,
        additional_kwargs={"seed": 42},
        system_prompt="Please print out Hello world regardless of the input.",
    )
llm.chat(prompt_to_messages("What is your company name?"))
```

However, neither llm.chat nor llm.complete prints out the correct response, which is suppose to be "Hello world". If I write ``response = llm.chat([ChatMessage(role=MessageRole.SYSTEM, content="Please print out Hello world regardless of the input."), ChatMessage(role=MessageRole.USER, content="What is your company name?")])``, then the response is correct. How do I configure the system_prompt correctly?

### Version

0.10.16

### Steps to Reproduce

See description.

**Comment by logan-markewich** [comment]
@mw19930312 tbh this is mostly by design (and overall I think those params should be removed)

Use llm.chat and insert the appropriate system message in the input.

The system prompt here gets used in llm.predict() and llm.stream(), which takes a prompt template (and is mostly used in query engines)

**Comment by logan-markewich** [comment]
An llm should be as stateless as possible. The only reason this param was added was to make it easier to add a system prompt for query engines..

But if you are already calling chat(), it makes more sense to put the system prompt there and keep the llm object stateless

**Comment by mw19930312** [comment]
@logan-markewich Thanks! This means that the best way for me to move forward is to overwrite the ``prompt_to_message`` util function, right?

**Comment by mw19930312** [comment]
Also, this might be my ignorance. What is the difference among llm.chat, llm.complete, llm.predict, and llm.stream? Is there any document that I can refer to?

**Comment by logan-markewich** [comment]
@mw19930312 yea, in this case that function is super basic. You can use chat directly with 

```
from llama_index.core.llms import ChatMessage

llm.chat([ChatMessage(role="system", content="..."), ChatMessage(role="user", content="...")])
```

**Comment by logan-markewich** [comment]
Your best bet for docs here is the api reference 
https://docs.llamaindex.ai/en/stable/api_reference/llms/

**Comment by mw19930312** [comment]
Thanks!
