### ISSUE TITLE
[Question]: GPT-4o not available for LLMs

### ISSUE THREAD

**Issue by JoseGHdz** [run-llama/llama_index#13490]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I tested my rag system with GPT-4o and I got the error that the model is invalid, and a list of valid models. This tells me that it is not available yet, so is there an approximate date in which GPT-4o will become available for testing using LLM's? 

Here is the code that I used to test:
from llama_index.llms.openai import OpenAI
llm_4 = OpenAI(model="gpt-4o", temperature=0.3)

Error:
ValueError: Unknown model 'gpt-4o'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613

**Comment by logan-markewich** [comment]
@JoseGHdz its available, but make sure you update

`pip install -U llama-index-llms-openai`

**Comment by JoseGHdz** [comment]
> @JoseGHdz its available, but make sure you update
> 
> `pip install -U llama-index-llms-openai`

It worked, thanks!
