### ISSUE TITLE
When will gpt-4o be supported?

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#13502]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When will gpt-4o be supported?

**Comment by logan-markewich** [comment]
It already is. Since day 0

`pip install -U llama-index-llms-openai`

`llm = OpenAI(model="gpt-4o")`

**Comment by logan-markewich** [comment]
Install the latest openai package. If you are running in a notebook, you'll have to restart it as well

**Comment by cxycxm** [comment]
thanks
