### ISSUE TITLE
[Bug]: query pipeline didn't support OpenAILike Meta-Llama-3-8B-Instruct model and embedding model with dimension other than 384 

### ISSUE THREAD

**Issue by hushuitian** [run-llama/llama_index#13506]
### Bug Description

(3)Use the code from https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline/ with the following modification:  
...
%pip install llama-index-llms-openai-like
#Settings.llm = OpenAI(model="gpt-3.5-turbo")
from llama_index.llms.openai_like import OpenAILike
llm = OpenAILike(
    api_key="token-abc123",
    api_base="http://localhost:8000/v1", 
    is_chat_model=True, 
    context_window=1024, 
    model="/home/techplus-820/w/Meta-Llama-3-8B-Instruct",    
    is_function_calling_model=True  # provide this field
)
Settings.llm = llm
#%pip install llama-index-llms-openai-like
#Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
#embedding dimension 384(OK)
#embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
#embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-en-v1.5")
#Got ValueError: shapes (1024,) and (384,) not aligned: 1024 (dim 0) != 384 (dim 0)
#embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-large-en-v1.5")
#Got ValueError: shapes (512,) and (384,) not aligned: 512 (dim 0) != 384 (dim 0)
embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-zh-v1.5")
Settings.embed_model = embed_model
...
(4)Test results
(4b)if using embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-zh-v1.5"):
It will report: ValueError: shapes (512,) and (384,) not aligned: 512 (dim 0) != 384 (dim 0)
(4c)if using embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-large-en-v1.5"):
It will report: ValueError: shapes (1024,) and (384,) not aligned: 1024 (dim 0) != 384 (dim 0)

### Version

llama_index-0.10.36

### Steps to Reproduce

Test Environment: ubuntu 22.04 server with 2 T4 GPUs
(1)Download Meta-Llama-3-8B-Instruct,bge-small-en-v1.5,bge-small-zh-v1.5,etc. models to a local directory such as /home/techplus-820/w/
(2)Launch vllm 0.4.2 as OpenAI Compatible Server
python -m vllm.entrypoints.openai.api_server --model /home/techplus-820/w/Meta-Llama-3-8B-Instruct --dtype half -tp 2 --worker-use-ray --api-key token-abc123
(3) Use the code from https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline/ with the following modification:  
...
%pip install llama-index-llms-openai-like
#Settings.llm = OpenAI(model="gpt-3.5-turbo")
from llama_index.llms.openai_like import OpenAILike
llm = OpenAILike(
    api_key="token-abc123",
    api_base="http://localhost:8000/v1", 
    is_chat_model=True, 
    context_window=1024, 
    model="/home/techplus-820/w/Meta-Llama-3-8B-Instruct",    
    is_function_calling_model=True  # provide this field
)
Settings.llm = llm
#%pip install llama-index-llms-openai-like
#Settings.embed_model = OpenAIEmbedding(model="text-embedding-3-small")
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
#embedding dimension 384(OK)
#embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
#embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-en-v1.5")
#Got ValueError: shapes (1024,) and (384,) not aligned: 1024 (dim 0) != 384 (dim 0)
#embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-large-en-v1.5")
#Got ValueError: shapes (512,) and (384,) not aligned: 512 (dim 0) != 384 (dim 0)
embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-zh-v1.5")
Settings.embed_model = embed_model
...
(4)Test results
(4a)if using embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-en-v1.5"):
Everything will be OK and the test will be succeeded
(4b)if using embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-small-zh-v1.5"):
it will report: ValueError: shapes (512,) and (384,) not aligned: 512 (dim 0) != 384 (dim 0)
(4c)if using embed_model = HuggingFaceEmbedding(model_name="/home/techplus-820/w/bge-large-en-v1.5"):
it will report: ValueError: shapes (1024,) and (384,) not aligned: 1024 (dim 0) != 384 (dim 0)
(5)It seems that current query pipeline only supports embedding model with dimension 384 and doesn't support embedding model with dimension other than 384(e.g., doesn't support embedding model with dimension such as 512, 1024,etc.)
(6)Please advise how to fix this issue? Thanks a lot in advance!

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[30], line 1
----> 1 response = p.run(topic="YC")

File ~/.local/lib/python3.10/site-packages/llama_index/core/query_pipeline/query.py:320, in QueryPipeline.run(self, return_values_direct, callback_manager, *args, **kwargs)
    316     query_payload = json.dumps(str(kwargs))
    317 with self.callback_manager.event(
    318     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_payload}
    319 ) as query_event:
--> 320     outputs, _ = self._run(
    321         *args,
    322         return_values_direct=return_values_direct,
    323         show_intermediates=False,
    324         **kwargs,
    325     )
    326     return outputs

File ~/.local/lib/python3.10/site-packages/llama_index/core/query_pipeline/query.py:544, in QueryPipeline._run(self, return_values_direct, show_intermediates, *args, **kwargs)
    535 """Run the pipeline.
    536 
    537 Assume that there is a single root module and a single output module.
   (...)
    540 
    541 """
    542 root_key, kwargs = self._get_root_key_and_kwargs(*args, **kwargs)
--> 544 result_outputs, intermediates = self._run_multi(
    545     {root_key: kwargs}, show_intermediates=show_intermediates
    546 )
    548 return (
    549     self._get_single_result_output(result_outputs, return_values_direct),
    550     intermediates,
    551 )

File ~/.local/lib/python3.10/site-packages/llama_index/core/query_pipeline/query.py:717, in QueryPipeline._run_multi(self, module_input_dict, show_intermediates)
    715 if self.verbose:
    716     print_debug_input(module_key, module_input)
--> 717 output_dict = module.run_component(**module_input)
    719 if show_intermediates and module_key not in intermediate_outputs:
    720     intermediate_outputs[module_key] = ComponentIntermediates(
    721         inputs=module_input, outputs=output_dict
    722     )

File ~/.local/lib/python3.10/site-packages/llama_index/core/base/query_pipeline/query.py:199, in QueryComponent.run_component(self, **kwargs)
    197 kwargs.update(self.partial_dict)
    198 kwargs = self.validate_component_inputs(kwargs)
--> 199 component_outputs = self._run_component(**kwargs)
    200 return self.validate_component_outputs(component_outputs)

File ~/.local/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py:347, in RetrieverComponent._run_component(self, **kwargs)
    345 def _run_component(self, **kwargs: Any) -> Any:
    346     """Run component."""
--> 347     output = self.retriever.retrieve(kwargs["input"])
    348     return {"output": output}

File ~/.local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py:276, in Dispatcher.span.<locals>.wrapper(func, instance, args, kwargs)
    273 try:
    274     #print("args:\n", args)
    275     print("*kwargs:\n", *kwargs)
--> 276     result = func(*args, **kwargs)
    277     #print("result:\n", result)
    278 except BaseException as e:

File ~/.local/lib/python3.10/site-packages/llama_index/core/base/base_retriever.py:244, in BaseRetriever.retrieve(self, str_or_query_bundle)
    239 with self.callback_manager.as_trace("query"):
    240     with self.callback_manager.event(
    241         CBEventType.RETRIEVE,
    242         payload={EventPayload.QUERY_STR: query_bundle.query_str},
    243     ) as retrieve_event:
--> 244         nodes = self._retrieve(query_bundle)
    245         nodes = self._handle_recursive_retrieval(query_bundle, nodes)
    246         retrieve_event.on_end(
    247             payload={EventPayload.NODES: nodes},
    248         )

File ~/.local/lib/python3.10/site-packages/llama_index/core/instrumentation/dispatcher.py:276, in Dispatcher.span.<locals>.wrapper(func, instance, args, kwargs)
    273 try:
    274     #print("args:\n", args)
    275     print("*kwargs:\n", *kwargs)
--> 276     result = func(*args, **kwargs)
    277     #print("result:\n", result)
    278 except BaseException as e:

File ~/.local/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py:102, in VectorIndexRetriever._retrieve(self, query_bundle)
     96         query_bundle.embedding = (
     97             self._embed_model.get_agg_embedding_from_queries(
     98                 query_bundle.embedding_strs
     99             )
    100         )
    101 #print("self._get_nodes_with_embeddings(query_bundle):\n", self._get_nodes_with_embeddings(query_bundle))        
--> 102 return self._get_nodes_with_embeddings(query_bundle)

File ~/.local/lib/python3.10/site-packages/llama_index/core/indices/vector_store/retrievers/retriever.py:181, in VectorIndexRetriever._get_nodes_with_embeddings(self, query_bundle_with_embeddings)
    177 def _get_nodes_with_embeddings(
    178     self, query_bundle_with_embeddings: QueryBundle
    179 ) -> List[NodeWithScore]:
    180     query = self._build_vector_store_query(query_bundle_with_embeddings)
--> 181     query_result = self._vector_store.query(query, **self._kwargs)
    182     print("query_result:\n" , query_result)
    183     return self._build_node_list_from_query_result(query_result)

File ~/.local/lib/python3.10/site-packages/llama_index/core/vector_stores/simple.py:288, in SimpleVectorStore.query(self, query, **kwargs)
    280     top_similarities, top_ids = get_top_k_mmr_embeddings(
    281         query_embedding,
    282         embeddings,
   (...)
    285         mmr_threshold=mmr_threshold,
    286     )
    287 elif query.mode == VectorStoreQueryMode.DEFAULT:
--> 288     top_similarities, top_ids = get_top_k_embeddings(
    289         query_embedding,
    290         embeddings,
    291         similarity_top_k=query.similarity_top_k,
    292         embedding_ids=node_ids,
    293     )
    294 else:
    295     raise ValueError(f"Invalid query mode: {query.mode}")

File ~/.local/lib/python3.10/site-packages/llama_index/core/indices/query/embedding_utils.py:38, in get_top_k_embeddings(query_embedding, embeddings, similarity_fn, similarity_top_k, embedding_ids, similarity_cutoff)
     36 similarity_heap: List[Tuple[float, Any]] = []
     37 for i, emb in enumerate(embeddings_np):
---> 38     similarity = similarity_fn(query_embedding_np, emb)
     39     if similarity_cutoff is None or similarity > similarity_cutoff:
     40         heapq.heappush(similarity_heap, (similarity, embedding_ids[i]))

File ~/.local/lib/python3.10/site-packages/llama_index/core/base/embeddings/base.py:57, in similarity(embedding1, embedding2, mode)
     55     return np.dot(embedding1, embedding2)
     56 else:
---> 57     product = np.dot(embedding1, embedding2)
     58     norm = np.linalg.norm(embedding1) * np.linalg.norm(embedding2)
     59     return product / norm

ValueError: shapes (512,) and (384,) not aligned: 512 (dim 0) != 384 (dim 0)
```

**Comment by logan-markewich** [comment]
@hushuitian you need to make sure you are querying with the same embedding model that created the index.

If you switch embedding models, you need to build a new index

**Comment by hushuitian** [comment]
@Disiok !hanks for fixing advices.But it doesn't work.

**Comment by hushuitian** [comment]
> @hushuitian you need to make sure you are querying with the same embedding model that created the index.
> 
> If you switch embedding models, you need to build a new index

Thanks a lot for your advice! In my test case. It uses SimpleVectorStore. In get_top_k_embeddings() of ~/.local/lib/python3.10/site-packages/llama_index/core/indices/query/embedding_utils.py,  
...
embeddings_np = np.array(embeddings)
...
embeddings_np.shape is set to (22, 384). I don't know where is the number 384 coming from? Some default configurations somewhere?  How can we change this shape to (22,512) that will correctly match query_embedding_np.shape (512,)?

**Comment by logan-markewich** [comment]
@hushuitian there is a mismatch between the embeddings used to create the index, and the embeddings used to query the index. That is where the 384 and 512 are coming from

**Comment by logan-markewich** [comment]
You can change the embedding model and query an existing index, which is what you are doing

If you change the embedding model, you NEED to create the index again using `VectorStoreIndex.from_documents(documents, ...)` or `VectorStoreIndex(nodes, ...)` before you can query again

**Comment by logan-markewich** [comment]
In the notebook you are following, there is this block of code

```python

 import os
from llama_index.core import (
    StorageContext,
    VectorStoreIndex,
    load_index_from_storage,
)

if not os.path.exists("storage"):
    index = VectorStoreIndex.from_documents(docs)
    # save index to disk
    index.set_index_id("vector_index")
    index.storage_context.persist("./storage")
else:
    # rebuild storage context
    storage_context = StorageContext.from_defaults(persist_dir="storage")
    # load index
    index = load_index_from_storage(storage_context, index_id="vector_index")
```

If you change the embedding model, you should delete the existing storage folder so that the index is created again

**Comment by hushuitian** [comment]
@logan-markewich Thank you very much! The quick fixing solution is that I should delete the old ./storage directory after changing the embedding model. It now works perfectly as expected.Thank you very much again for helping me get out of the rabbit hole!
