### ISSUE TITLE
How to close a stream using chat_engine.stream_chat

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#13503]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to close a stream using chat_engine.stream_chat

**Comment by logan-markewich** [comment]
I actually don't think there is a way besides either exhausting the stream, or never continuing the stream

**Comment by cxycxm** [comment]
Can the client connection of this chat_engine be actively disconnected, similar to httpclient.close()

**Comment by logan-markewich** [comment]
Maybe? I think it really depends on the llm being used too. You'd have to do some digging into api docs there

**Comment by RussellLuo** [comment]
Maybe we can add a close method to `StreamingAgentChatResponse` by leveraging [generator.close()](https://docs.python.org/3/reference/expressions.html#generator.close), for example:

```python
class StreamingAgentChatResponse:
    ...

    def close(self) -> None:
        if self.chat_stream is not None:
            # Here we assume that self.chat_stream is a generator
            self.chat_stream.close()
```

Then  we also need to handle [GeneratorExit](https://docs.python.org/3/library/exceptions.html#GeneratorExit) in the relevant llm's `stream_chat()` method. Take [OpenAI](https://github.com/run-llama/llama_index/blob/4c0a6172226214b92275e9e2c5eb0d21856d6863/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L103) for example, we might update its `_stream_chat()` as below:

```python
def _stream_chat(
    self, messages: Sequence[ChatMessage], **kwargs: Any
) -> ChatResponseGen:
    ...

    def gen() -> ChatResponseGen:
        ...

        stream = client.chat.completions.create(
            messages=message_dicts,
            stream=True,
            **self._get_model_kwargs(**kwargs),
        )
        for response in stream:
            try:
                ...

                yield ChatResponse(
                    message=ChatMessage(
                        role=role,
                        content=content,
                        additional_kwargs=additional_kwargs,
                    ),
                    delta=content_delta,
                    raw=response,
                    additional_kwargs=self._get_response_token_counts(response),
                )
            except GeneratorExit:
                # Interrupt the stream by closing the connection.
                # see https://github.com/openai/openai-python/issues/969#issuecomment-1857158754
                stream.response.close()

    return gen()
```

**Comment by logan-markewich** [comment]
This would need to be implemented for every streaming llm 😅

**Comment by logan-markewich** [comment]
But, makes sense

**Comment by RussellLuo** [comment]
> This would need to be implemented for every streaming llm 😅

Yes, both the sync and async versions need to be modified. Perhaps we can leverage some decorators, although they may not be helpful in all cases.

**Comment by cxycxm** [comment]
thanks
