### ISSUE TITLE
[Question]: pip install for "from llama_index.indices.multi_modal.base import MultiModalVectorStoreIndex"

### ISSUE THREAD

**Issue by eranault** [run-llama/llama_index#13515]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey, I am quite new.
Does anyone know what are the "pip install" necessary for this import : "from llama_index.indices.multi_modal.base import MultiModalVectorStoreIndex"

Thanks a lot.

Sincerely,
A.R.

**Comment by logan-markewich** [comment]
@eranault the import is incorrect

`from llama_index.core.indices.multi_modal.base` (its inside `llama-index-core`, which is installed for you when you run `pip install llama-index`)
