### ISSUE TITLE
[Question]: Multithread VectorStoreIndex for PGVectoRsStore

### ISSUE THREAD

**Issue by joshpopelka20** [run-llama/llama_index#13517]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using PGVectoRsStore and creating a VectorStoreIndex. From the docs, I got this code:

```
from llama_index.core import SimpleDirectoryReader, VectorStoreIndex
from llama_index.vector_stores.pgvecto_rs import PGVectoRsStore

from llama_index.core import StorageContext

vector_store = PGVectoRsStore(client=client)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    docs, storage_context=storage_context
)
```

I'm using a Huggingface Embedding model to embed the docs with an embedding dimension of 768. I have over 400K docs that need to be embedded and it's running extremely slow. Is there a way to multi-thread this to speed up the performance?

**Comment by logan-markewich** [comment]
You can't really multi-thread local embeddings. Or you kind of can, but each thread needs to have its own instance of the embeddings in memory (effectively creating X embedding models per X threads)

If you have the memory, you can increase the batch size on embeddings: `HuggingFaceEmbedding(..., embed_batch_size=20)`

If you aren't already running on a GPU, you'll also want that. 

Tbh I would also maybe try using TEI, it's much more optimized. At the end of the day throughput is mostly limited by how much you can scale
https://docs.llamaindex.ai/en/stable/examples/embeddings/text_embedding_inference/?h=text+embedding+inference

**Comment by joshpopelka20** [comment]
I got it to finally increase the batch size in vectorstoreindex:

```
index = VectorStoreIndex.from_documents(
    docs, storage_context=storage_context, insert_batch_size=3000
)
```

If I increase it too high, I get CUDA out of memory.

Thanks for the help and I'll close the issue.
