### ISSUE TITLE
[Bug]: Parameter mismatch in _get_function_tool.<locals>.model_fn()

### ISSUE THREAD

**Issue by akumar-b6i** [run-llama/llama_index#13518]
### Bug Description

Seems like the [below code](https://github.com/run-llama/llama_index/blob/4c0a6172226214b92275e9e2c5eb0d21856d6863/llama-index-core/llama_index/core/program/function_program.py#L35) was added recently for function_program calling.

```
def _get_function_tool(output_cls: Type[Model]) -> FunctionTool:
    """Get function tool."""
    schema = output_cls.schema()
    schema_description = schema.get("description", None)

    # NOTE: this does not specify the schema in the function signature,
    # so instead we'll directly provide it in the fn_schema in the ToolMetadata
    def model_fn(**kwargs: Any) -> BaseModel:
        """Model function."""
        return output_cls(**kwargs)

    return FunctionTool.from_defaults(
        fn=model_fn,
        name=schema["title"],
        description=schema_description,
        fn_schema=output_cls,
    )
```

This method is calling `FunctionTool.from_defaults` from [here](https://github.com/run-llama/llama_index/blob/4c0a6172226214b92275e9e2c5eb0d21856d6863/llama-index-core/llama_index/core/tools/function_tool.py#L24), but the [call](https://github.com/run-llama/llama_index/blob/4c0a6172226214b92275e9e2c5eb0d21856d6863/llama-index-core/llama_index/core/tools/function_tool.py#L88C33-L88C37) and [acall](https://github.com/run-llama/llama_index/blob/4c0a6172226214b92275e9e2c5eb0d21856d6863/llama-index-core/llama_index/core/tools/function_tool.py#L98) method are passing two parameters to the `model_fn()`.

I think due to this when used, I am getting the below error when I call `astructured_predict` method as below

Method call:

```
response : my_output_cls = await my_llm.astructured_predict(  
                    output_cls=my_output_cls,
                    prompt=my_prmpt, 
                    prompt_arg1= prompt_arg1 #some more prompt args
                    
                )
```
Error:
```
 _get_function_tool.<locals>.model_fn() takes 0 positional arguments but 1 was given
 ```

### Version

llama-index-core == 0.10.31

### Steps to Reproduce

Use the below method call:

```
response : my_output_cls = await my_llm.astructured_predict(  
                    output_cls=my_output_cls,
                    prompt=my_prmpt, 
                    prompt_arg1= prompt_arg1 #some more prompt args
                    
                )
```

**Comment by logan-markewich** [comment]
@akumar-b6i hmm, I can't reproduce. Am I missing a step?

```python
from llama_index.llms.openai import OpenAI
from llama_index.core.prompts import PromptTemplate
from pydantic.v1 import BaseModel

class Test(BaseModel):
  """A test name."""
  name: str


async def run():
  await OpenAI().astructured_predict(
    Test,
    PromptTemplate("Predict a random test name about {topic1} or {topic2}."),
    topic1="cats",
    topic2="dogs",
  )


import asyncio
asyncio.run(run())
```

This is using the latest version of llama-index-core

**Comment by akumar-b6i** [comment]
Hey @logan-markewich  - You are using OpenAI maybe that's working just fine because it uses `OpenAIPydanticProgram.from_defaults` but I am using Gemini which is hitting the `FunctionCallingProgram.from_defaults` somehow. [Code here](https://github.com/run-llama/llama_index/blob/932b012b85ae1c85dde0793f8664b148bfdfee85/llama-index-core/llama_index/core/program/utils.py#L34)

Eventually, calling the `FunctionTool`, let me know if that makes sense. Thanks!

**Comment by logan-markewich** [comment]
Good point, I can try anthropic

Function calling isn't implemented in the `Gemini` class yet, so weird that it would even get to the function calling program though

**Comment by logan-markewich** [comment]
@akumar-b6i do you have the full traceback?

**Comment by logan-markewich** [comment]
Ah, I think I see the issue now actually (not sure how gemini got in there though haha)

**Comment by akumar-b6i** [comment]
I am not getting any stack trace pointing to the model_fn(), just the astructured_predict() returns the error string as a result. 
Also, I tried with gpt4-32k (from AzureOpenAI) and got the same error.

**Comment by logan-markewich** [comment]
Ok, I've narrowed this down, and there is this function `def acall_tool()` where if there is a single kwarg, we pass it in as a single arg to avoid cases where the LLM hallucinates the input name

This works for normal functions, but for pydantic class, we NEED the kwarg (you can initialize a pydantic object with positionals)

**Comment by logan-markewich** [comment]
So if your structured class has more than one argument, it will work fine. Going to try and figure out a fix for this

**Comment by akumar-b6i** [comment]
@logan-markewich  - Are you implementing the same idea as above by @dosu, I had the same suggestion but wanted to check with someone! Let me know, if not I can raise a PR!

**Comment by logan-markewich** [comment]
@akumar-b6i dosu's suggestion isn't quite correct. I'll open a PR in a sec, just got something working nicely
