### ISSUE TITLE
Whether chat_engine can call stream_complete()?

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#13527]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Whether chat_engine can call stream_complete()?

**Comment by logan-markewich** [comment]
the method you are looking for is `chat_engine.stream_chat()`

**Comment by cxycxm** [comment]
but i need stream_complete()，my purpose is to complete the conversation

**Comment by logan-markewich** [comment]
That's not how it works with chat engines sadly. Completion only makes sense if you have a single string, not a an alternating chat history.

You can prompt it with a chat history and take the llms response as a completion of the previous message if you want
