### ISSUE TITLE
[Question]: How are citations generated in the response of CitationQueryEngine?

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#13536]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I understand that in a CitationQueryEngine, we retrieve a couple of reference nodes from a vector index. Then, these nodes are passed into a synthesizer to generate a final response.

**Comment by logan-markewich** [comment]
The nodes are labeled as `source 1, source 2, etc.` and then the LLM is prompted to cite which sources it used

**Comment by mw19930312** [comment]
Would you mind referring me where the LLM is prompted? I just wonder how to pass the citation URLs if there are any. Also, if I understand it correctly, the nodes are formatted as the following through a metadata conversion template, right?

[source 1]
context: <text>
metadata: 
    xxx: xxx
    url: url

**Comment by mw19930312** [comment]
@logan-markewich ^^

**Comment by logan-markewich** [comment]
@mw19930312 

prompt: https://github.com/run-llama/llama_index/blob/287c3df887792035c9605ae87234903c2ca68795/llama-index-core/llama_index/core/query_engine/citation_query_engine.py#L32

code entry point: https://github.com/run-llama/llama_index/blob/287c3df887792035c9605ae87234903c2ca68795/llama-index-core/llama_index/core/query_engine/citation_query_engine.py#L266
