### ISSUE TITLE
[Question]: How to delete document from VectorStoreIndex?

### ISSUE THREAD

**Issue by levente-murgas** [run-llama/llama_index#13537]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi!

I'm struggling to find a way to delete documents (along with its nodes) from a VectorStoreIndex. I'm using the **AzureAISearchVectorStore** as a VectorStore, which **stores both the text and embeddings** for the documents. The [example](https://docs.llamaindex.ai/en/stable/examples/vector_stores/AzureAISearchIndexDemo/?h=azure#adding-a-document-to-existing-index) in the documentations, does give a nice example on how to insert nodes, but nothing for deletion (or update). After digging in the source code of the  VectorStore class I found a function that should provide a way to delete nodes:

```
def delete_ref_doc(
        self, ref_doc_id: str, delete_from_docstore: bool = False, **delete_kwargs: Any
    ) -> None:
        """Delete a document and it's nodes by using ref_doc_id."""
        self._vector_store.delete(ref_doc_id, **delete_kwargs)

        # delete from index_struct only if needed
        if not self._vector_store.stores_text or self._store_nodes_override:
            print("Deleting from index_struct and vector store")
            ref_doc_info = self._docstore.get_ref_doc_info(ref_doc_id)
            if ref_doc_info is not None:
                for node_id in ref_doc_info.node_ids:
                    self._index_struct.delete(node_id)
                    self._vector_store.delete(node_id)

        # delete from docstore only if needed
        if (
            not self._vector_store.stores_text or self._store_nodes_override
        ) and delete_from_docstore:
            print("Deleting from docstore")
            self._docstore.delete_ref_doc(ref_doc_id, raise_error=False)

        self._storage_context.index_store.add_index_struct(self._index_struct)
```

However when I tried using this method, I found that it had no effect on the index. Here's my code:
![image](https://github.com/run-llama/llama_index/assets/66883416/e2cc6ebd-227f-4b87-ab1a-918be0630768)

This is also evident in the Search Explorer in the Azure Portal:
![image](https://github.com/run-llama/llama_index/assets/66883416/3fd925f3-9f38-4d92-aefe-6ea3d1c25404)

The code for my initial setup:

```
search_service_api_key = os.getenv("AZURE_SEARCH_API_KEY")
search_service_endpoint = f'https://{os.getenv("AZURE_SEARCH_SERVICE_NAME")}.search.windows.net'
search_service_api_version = "2023-11-01"
credential = AzureKeyCredential(search_service_api_key)
index_name = os.getenv("AZURE_SEARCH_INDEX_NAME")

# Use index client to demonstrate creating an index
index_client = SearchIndexClient(
    endpoint=search_service_endpoint,
    credential=credential,
)

metadata_fields = {
    "author": "author",
    "theme": ("topic", MetadataIndexFieldType.STRING),
    "director": "director",
}

vector_store = AzureAISearchVectorStore(
    search_or_index_client=index_client,
    filterable_metadata_field_keys=metadata_fields,
    index_name=index_name,
    index_management=IndexManagement.CREATE_IF_NOT_EXISTS,
    id_field_key="id",
    chunk_field_key="chunk",
    embedding_field_key="embedding",
    embedding_dimensionality=1024,
    metadata_string_field_key="metadata",
    doc_id_field_key="doc_id",
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

test_doc = Document(text="The sun is shining.")

index = VectorStoreIndex.from_documents(
    [test_doc], storage_context=storage_context
)
```

I believe the results are because neither of the conditionals were True when I called the delete function. As the AzureAISearchVectorStore stores both text and embeddings `self._vector_store.stores_text` is inherently True and for some reason there's no way to initialize the VectorStoreIndex with `self._store_nodes_override=True` with the `from_document` function, so I'm rather clueless on how should someone use this function properly. Another suspicion I have is that the `doc_id` and the `ref_doc_id` are not the same for the same node (i.e. it's generated during the node parsing), but that seems rather counterproductive. 

I appreciate any help I can get!

**Comment by logan-markewich** [comment]
You used `index.insert_nodes()` to insert a document -- I would have done `index.insert(doc[0])` instead, so that the parent doc -> node relation is created and we can delete using the `doc_id`

You can see that the `delete_ref_doc()` function will call `self._vector_store.delete(ref_doc_id, **delete_kwargs)` no matter what

If we follow that, we end up here
https://github.com/run-llama/llama_index/blob/bd51d01cb035c27934b2b851ee0a0280d5d42863/llama-index-integrations/vector_stores/llama-index-vector-stores-azureaisearch/llama_index/vector_stores/azureaisearch/base.py#L555

Lastly, you can definitely pass in `store_nodes_override=True` if you want (`from_documents(documents, store_nodes_override=True)` will pass kwargs to the class constructor), but its not needed here, and also not the issue.

**Comment by deval-aiml** [comment]
docstore = RedisDocumentStore.from_host_and_port(
        host=config.redis_config.host, 
        port=config.redis_config.port, 
        namespace="llamasearch"
    )
    parser = SentenceSplitter()
    print(f"Creating new ingestion pipeline")
    ingestion = IngestionPipeline(
        transformations=[parser],
        docstore=docstore,
        vector_store=qdrant_search.vector_store,
        cache=IngestionCache(
            cache=RedisCache.from_host_and_port(
                host=config.redis_config.host, 
                port=config.redis_config.port
            ),
            collection="redis_cache",
        ),
        docstore_strategy=DocstoreStrategy.UPSERTS,
    )
  .....
documents = SimpleDirectoryReader(input_files=[file_path1, file_path2], filename_as_id=True, required_exts=[".pdf", ".docx", ".csv"]).load_data()
    for doc in documents:
        print(f"Processing Document ID: {doc.id_}")
        docs.append(doc.id_)
    nodes = await ingestion.arun(documents=documents)
    print(f"Ingesting {len(nodes)} nodes for {len(ingestion.docstore.docs)} chunks")
    await self.index._async_add_nodes_to_index(
            self.index.index_struct,
            nodes,
            show_progress = True
        )
    return nodes

@logan-markewich Is this correct way of inserting nodes using ingestion pipeline to vector db and docstore? I am confused which is the standard way of inserting/deleting when using IngestionPipeline in Llamaindex
