### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by pedrohernandezgeladocma** [run-llama/llama_index#13532]
### Bug Description

The class HuggingFaceLLM does not have a HuggingFace token parameter, making it impossible to use this class with an LLM that is in a gated or private repo.

See [HuggingFaceLLM](https://github.com/run-llama/llama_index/blob/1bde70b75ee5b4e6a5bc8c1c3f95eaa0dd889ab0/llama-index-legacy/llama_index/legacy/llms/huggingface.py#L52)

### Version

v0.10.37

### Steps to Reproduce

Evident from code [HuggingFaceLLM](https://github.com/run-llama/llama_index/blob/1bde70b75ee5b4e6a5bc8c1c3f95eaa0dd889ab0/llama-index-legacy/llama_index/legacy/llms/huggingface.py#L52). 

Alternatively try to instatiate with a gated repo in HuggingFace, e.g. llama3

**Comment by logan-markewich** [comment]
@pedrohernandezgeladocma you can pass any parameter using kwargs

Here's an example with llama3
```python
import torch
from transformers import BitsAndBytesConfig

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("meta-llama/Meta-Llama-3-8B-Instruct")

stopping_ids = [
  tokenizer.eos_token_id,
  tokenizer.convert_tokens_to_ids("<|eot_id|>")
]


from llama_index.llms.huggingface import HuggingFaceLLM

llm = HuggingFaceLLM(
    model_name="meta-llama/Meta-Llama-3-8B-Instruct",
    tokenizer=tokenizer,
    context_window=7900,
    model_kwargs={"token": hf_token, "quantization_config": quantization_config},
    stopping_ids=stopping_ids,
    device_map="auto",
    is_chat_model=True,
)
```

**Comment by logan-markewich** [comment]
You can always load the model and tokenizer outside of llama-index and pass it in as well

```
llm = HuggingFaceLLM(model=model, tokenizer=tokenizer, ...)
```

**Comment by pedrohernandezgeladocma** [comment]
@logan-markewich thanks so much this is so helpful!
