### ISSUE TITLE
[Bug]: OpenAI key required even though I am using open sourced model

### ISSUE THREAD

**Issue by kartik122** [run-llama/llama_index#13534]
### Bug Description

While trying to create a multimodal RAG application 
 I have tried using multimodal Ollama models and open source embeddings model but somehow the error comes up to require openai key which i am not using in the application

ValueError: 
******
Could not load OpenAI embedding model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys
 
Consider using embed_model='local'.
Visit our documentation for more embedding options: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules
******

### Version

0.10.36

### Steps to Reproduce

class RagBot: 
    def __init__(self, model):
       self.index = None 
        self.model = model.multimodal_llm 
        self.azure = model.llm_client 
        self.embed_model = HuggingFaceEmbedding(model_name='Alibaba-NLP/gte-large-en-v1.5', trust_remote_code=True) 
        Settings.llm = self.model 
        Settings.embed_model = self.embed_model 

        self.client = QdrantClient(":memory:") 
        self.text_store = QdrantVectorStore(client=self.client, collection_name="text_collection") 
        self.image_store = QdrantVectorStore(client=self.client, collection_name="image_collection") 
        self.storage_context = StorageContext.from_defaults( 
            vector_store=self.text_store, image_store=self.image_store, 
        ) 
    def vector_store_indexing(self, source_files): 
         documents = SimpleDirectoryReader(source_files).load_data() 
         self.index = MultiModalVectorStoreIndex.from_documents( 
             documents, storage_context=self.storage_context, 
           ) 
        query_engine = self.index.as_query_engine( 
            llm=self.model , similarity_top_k=3, image_similarity_top_k=3,text_qa_template=qa_tmpl 
        ) if hasattr(self, 'index') else None

**Comment by logan-markewich** [comment]
I'm not able to reproduce. Please double check your code. 
https://colab.research.google.com/drive/1N5ZXx7uLV85c12ZvgUyleUsok5ecDHGI?usp=sharing

The important thing is that `Settings.embed_model` and `Settings.llm` should be set before any index is created.

Alternatively, you have to pass in specific kwargs for models
`VectorStoreIndex.from_documents(..., embed_model=embed_model)`
`index.as_query_engine(llm=llm)`
