### ISSUE TITLE
[Question]: Is log probability available in llm.achat?

### ISSUE THREAD

**Issue by mw19930312** [run-llama/llama_index#13544]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wonder whether log prob can be retrieved through llm.achat (see https://platform.openai.com/docs/api-reference/chat#chat-create-logprobs) for log prob in OpenAI API. If so, is there an example code?

**Comment by logan-markewich** [comment]
@mw19930312 it already is

```
llm = OpenAI(..., logprobs=True, top_logprobs=20)

response = await llm.achat([ChatMessage(role='user', content='Hello!')])

print(response.logprobs)
```

20 is the highest openai lets you select.
