### ISSUE TITLE
How to retrieve specific files? 

### ISSUE THREAD

**Issue by susht3** [run-llama/llama_index#13550]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have multiple files，can i retrieve specify document nodes or all nodes? like this:
nodes = recursive_retriever.retrieve(query, "xx_name")
which xx_name is my file_name

**Comment by logan-markewich** [comment]
Probably use metadata filtering, assuming the file name/path is in the metadata of nodes you inserted
Here's an example with pinecone
https://docs.llamaindex.ai/en/stable/examples/vector_stores/pinecone_metadata_filter/?h=metadata+filter

**Comment by susht3** [comment]
> Probably use metadata filtering, assuming the file name/path is in the metadata of nodes you inserted Here's an example with pinecone https://docs.llamaindex.ai/en/stable/examples/vector_stores/pinecone_metadata_filter/?h=metadata+filter

thank you，it looks simple and efficient，but it uses PINECONE_API_KEY，how to get this key? is it free?
