### ISSUE TITLE
[Question]: CondensePlusContextChatEngine with CitationQueryEngine?

### ISSUE THREAD

**Issue by levente-murgas** [run-llama/llama_index#13552]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi!

I'm struggling to find a way to combine these two mentioned in the title. I saw that in the documentation of `CondensePlusContextChatEngine` you can init it using any class extending the `BaseRetriever`. However, CitationQueryEngine extends the `BaseChatEngine` class. Is there any workaround for this?

**Comment by logan-markewich** [comment]
There is no workaround -- context chat engines only work with a retriever. CitationQueryEngine is a full query engine

If you want citations in a chat engine, you'd probably have to make it "from scratch". There's one low-level example of a custom chat engine here 
https://docs.llamaindex.ai/en/stable/examples/pipeline/query_pipeline_memory/?h=query+pipeline+chat
