### ISSUE TITLE
[Feature Request]: Add LMStudio support

### ISSUE THREAD

**Issue by shivamklr** [run-llama/llama_index#13556]
### Feature Description

Add a way to connect LMStudio with LlamaIndex.

### Reason

Add direct implementation for LMStudio

### Value of Feature

This features enables loading models on LMStudio and allows LlamaIndex index to send request to the API provided by LMStudio.

**Comment by nielinjie** [comment]
how to use embedding model from LMStudio?

**Comment by shivamklr** [comment]
@nielinjie Haven't implemented the logic for that yet. Perhaps you can create an issue explaining your use case.
