### ISSUE TITLE
[Question]: FunctionCallingAgentWorker with functionary Local LLM

### ISSUE THREAD

**Issue by pseudorandomrants** [run-llama/llama_index#13563]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the best way to get FunctionCallingAgentWorker to work with a local LLM (with native function calling) like functionary?

**Comment by logan-markewich** [comment]
An LLM needs to implement the `FunctionCallingLLM` class -- currently only openai, anthropic, TGI, and mistral implement this

There would need to be an LLM integration with functionary for example that implements this class
