### ISSUE TITLE
[Question]: Google Gemini 1.5 flash model support

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#13573]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

I am trying to use gemini flash with following model definition
    llm = Gemini(
        model="models/gemini-1.5-flash-latest",
        api_key="SOME-KEY",
        is_chat_model=True,
        is_function_calling_model=False,
        temperatue=0.1
    )
    
but on llm.complete() I am getting:
Error 400 Add an image to use models/gemini-pro-vision, or switch your model to a text model.

**Comment by carlisia** [comment]
I am having the same issue, and have tried with different embedding models.

**Comment by edoardolobl** [comment]
Unfortunately, I am encountering the same problem. I've tried everything and couldn't find a workaround.
