### ISSUE TITLE
[Bug]: loading 5.7 GB data to llama-index

### ISSUE THREAD

**Issue by yasir23** [run-llama/llama_index#13588]
### Bug Description

I have loaded 5.7 GB dataset to the loader but its giving this response:
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 63 0 (offset 0)
whole dataset is composed of pdf files...
![● chatbot ipynb - SP client - Cursor 5_20_2024 7_15_19 AM](https://github.com/run-llama/llama_index/assets/46179498/2db83363-879f-478e-b857-bdcd36795e54)

### Version

latest

### Steps to Reproduce

from llama_index.core import SimpleDirectoryReader

reader = SimpleDirectoryReader(input_dir="./dataset")
documents = reader.load_data()

**Comment by logan-markewich** [comment]
I've never seen his before. Pretty impossible to debug without a way to reproduce 😅 

My guess is either running out of memory, or some kind of error reading some of your pdfs (corrupted? password protected?)

You can try loading them one by one instead maybe?

```
index = VectorStoreIndex(nodes=[], ...)

for doc in reader.iter_data():
  index.insert(doc)
```
