### ISSUE TITLE
[Bug]: Unable to use Seaborn when asking the LLM to graph

### ISSUE THREAD

**Issue by toaster9996** [run-llama/llama_index#13592]
### Bug Description

When I ask the LLM to graph using seaborn, I get this error even though Seaborn is in the allowed imports.

RuntimeError: Execution of code containing references to private or dunder methods, disallowed builtins, or any imports, is forbidden!

### Version

0.10.37

### Steps to Reproduce

Ask the LLM to graph using Seaborn, given an error: "RuntimeError: Execution of code containing references to private or dunder methods, disallowed builtins, or any imports, is forbidden!"

**Comment by logan-markewich** [comment]
I'm not sure what you mean by using the llm to graph, but this error is raised in the pandas query engine when the generated pandas code is unsafe to execute

**Comment by toaster9996** [comment]
> I'm not sure what you mean by using the llm to graph, but this error is raised in the pandas query engine when the generated pandas code is unsafe to execute

Why would being able to call a Python library be considered unsafe to execute, if the related library (seaborn) is in the allowed import list?

**Comment by toaster9996** [comment]
@dosu._ How to use safe importing?

**Comment by toaster9996** [comment]
@dosu._ how to use _restricted_import('seaborn') and saved in your enivronment?

**Comment by toaster9996** [comment]
@dosu._ after importing the library using seaborn = _restricted_import('seaborn') code, still provides the same RunTimeError (RuntimeError: Execution of code containing references to private or dunder methods, disallowed builtins, or any imports, is forbidden!)

How to enable the use of imported libraries?

**Comment by toaster9996** [comment]
@dosu._ Setting up the libraries with _restricted_import and using safe_exec, still returns the error: RuntimeError: Execution of code containing references to private or dunder methods, disallowed builtins, or any imports, is forbidden!

**Comment by toaster9996** [comment]
@dosu._ Which prompt should be used in order to ensure the PandasQueryEngine uses the recommended library without calling the library in the query question

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from outputting multiple quotes when running the eval function():

> Pandas Instructions:
```
```
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Assuming df is already created with the given data

sns.set()

plt.figure(figsize=(10, 6))
sns.barplot(x="Department", y="Salary", hue="Department", data=df)

plt.title("Salaries by Department")
plt.xlabel("Department")
plt.ylabel("Salary (USD)")
plt.legend(title="Departments")

plt.show()
```
```

**Comment by toaster9996** [comment]
@dosu._ How to put more importance on using specific libraries in PandasQueryEngine?

**Comment by toaster9996** [comment]
@dosu._ This error occurs when trying to eval multiple lines of Python code: SyntaxError: invalid syntax
How to allow PandasQueryEngine be used to run multiple lines of code?

**Comment by toaster9996** [comment]
@dosu._ PandasQueryEngine still has issues with importing libraries to use.

**Comment by toaster9996** [comment]
@dosu._ 
How to allow PandasQueryEngine be used to run multiple lines of code in the eval() function?

**Comment by toaster9996** [comment]
@dosu._
How to allow PandasQueryEngine in Pandas_prompt to use multiple lines of code?

**Comment by toaster9996** [comment]
@dosu._ How to adjust PandasQueryEngine with custom output parsers

**Comment by toaster9996** [comment]
@dosu._ How to ensurePandasQueryEngine contains the neccessary libaries in the output parse?

**Comment by toaster9996** [comment]
@dosu._ normal Python expressions have issues with changes  with error: SyntaxError: invalid syntax

**Comment by toaster9996** [comment]
@dosu._ How to filter out string expressions in the final Python code expressions?

**Comment by toaster9996** [comment]
@dosu._ How to ensure PandasQueryEngine to differeanciate between plotting and calculations?

**Comment by toaster9996** [comment]
@dosu._ How to fix this issue:
SyntaxError: unterminated string literal (detected at line 3)

**Comment by toaster9996** [comment]
@dosu._ How to stop the PandasQueryEngine from setting the final line of code as a variable and calling the Python expression if no other action is needed to be performed on the dataframe?

**Comment by toaster9996** [comment]
@dosu._ Where in the prompt instructions to stop PandasQueryEngine from trying to connecto to a SQL database or reading a CSV file when the data is already loaded into the environment?

**Comment by toaster9996** [comment]
@dosu._ how to stop PandasQueryEngine from double-quoting the results

**Comment by toaster9996** [comment]
@dosu._ How to stop the PandasQueryEngine from producing outputs like this:

> Pandas Instructions:
```
The expression you are looking for is:

```
df['parch'].sum()
```
```

**Comment by toaster9996** [comment]
@dosu._ How to ensure the PandasQueryEngine includes plot title and axis when creating graphs?

**Comment by toaster9996** [comment]
@dosu._ Still has issues with the previous prompt to include titles

**Comment by toaster9996** [comment]
@dosu._ How to ensure PandasQueryEngine includes plt.title() when using Seaborn to generate plots?

**Comment by toaster9996** [comment]
@dosu._ How to create a parse function for either graphing plots or computations?

**Comment by toaster9996** [comment]
@dosu._ what prompt should be used to add more emphasis to include a title when plotting using PandasQueryEngine

**Comment by toaster9996** [comment]
@dosu._ how to stop PandasQueryEngine from producing extra quotes

**Comment by toaster9996** [comment]
@dosu._ how to stop PandasQueryEngine from producing extra quotes? Should specific key words be used in the prompt to tell PandasQueryEngine to plot (IE: plot, graph, chart)

**Comment by toaster9996** [comment]
@dosu._ Where should specific key words be used in the prompt to tell PandasQueryEngine to plot (IE: plot, graph, chart)

**Comment by toaster9996** [comment]
@dosu._ How to ensure PandasQueryEngine provides a title when plotting, using set_title() function

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from using seaborn code when asking for calculations in the prompts?

**Comment by toaster9996** [comment]
@dosu._ How to let PandasQueryEngine choose between plotting and calculations in prompt?

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from writing synthesized response in the code?

**Comment by toaster9996** [comment]
@dosu._ For PandasQueryEngine, how to stop it from providing responses like 

"> Pandas Instructions:
Sure, I'd be happy to help! Based on the data provided in the Pandas DataFrame `df`"

When synthesize_response = False is already set

**Comment by toaster9996** [comment]
@dosu._ How can PandasQueryEngine explain the graph or calucations results to the user?

**Comment by toaster9996** [comment]
@dosu._ How to ensure that PandasQueryEngine outputs proper Python code (without creaing errors)

**Comment by toaster9996** [comment]
@dosu._ How to adjust the PandasQueryEngine response query?

**Comment by toaster9996** [comment]
@dosu._ Should the PandasQueryEngine response prompt be changed to ignore using extra quotes?

**Comment by toaster9996** [comment]
@dosu._  How to stop PandasQueryEngine from producing these response with synthesize_response = False
"Sure, I'd be happy to help! Based on your query, here's a Python expression that should accomplish what you're looking for:"

**Comment by toaster9996** [comment]
@dosu._ How to fix this issue:
> Pandas Output: There was an error running the output as Python code. Error message: invalid syntax (<string>, line 0)
There was an error running the output as Python code. Error message: invalid syntax (<string>, line 0)
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.12/site-packages/llama_index/experimental/query_engine/pandas/output_parser.py", line 60, in default_output_processor
    output_str = str(safe_eval(module_end_str, global_vars, local_vars))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/llama_index/experimental/exec_utils.py", line 158, in safe_eval
    return eval(__source, _get_restricted_globals(__globals), __locals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 0
    
SyntaxError: invalid syntax

**Comment by toaster9996** [comment]
@dosu._ How to handle removing extra leading/trailing quotes?

**Comment by toaster9996** [comment]
@dosu._ How to handle removing extra leading/trailing ``` quotes?

**Comment by toaster9996** [comment]
@dosu._ why does PandasQueryEngine have issues with writing Python code for questions previously asked?

**Comment by toaster9996** [comment]
@dosu._ How to provide explainations to calculation or graphing results without synthesize_results = True, since it will affect code generation

**Comment by toaster9996** [comment]
@dosu._ How to provide explainations to calculation or graphing results

**Comment by toaster9996** [comment]
@dosu._ How can PandasQueryEngine generate response more similar to data analytics explainations?

**Comment by toaster9996** [comment]
@dosu._ How can PandasQueryEngine provide a data analytic explaination for the calculation or graphing result?

**Comment by toaster9996** [comment]
@dosu._ How can PandasQueryEngine provide more insight into the analysis provided?

**Comment by toaster9996** [comment]
@dosu._ How can PandasQueryEngine provide a detailed data analytic insight into the analysis provided?

**Comment by toaster9996** [comment]
@dosu._ PandasQueryEngine has issues providing an explaination for graphs

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed reports

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed analysis reports

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed analysis reports providing more insight from the data

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed analysis reports providing more insight from the data

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed analysis reports providing more insight from the calculations or graphs

**Comment by toaster9996** [comment]
@dosu._ how can PandasQueryEngine create detailed analysis reports providing more insight from the calculations or graphs with proper syntax and no synthesized responses within the Python code.

**Comment by toaster9996** [comment]
@dosu._ How to let the PandasQueryEngine synthesize response show coding results along with insight explainations

**Comment by toaster9996** [comment]
@dosu._ How to let the PandasQueryEngine synthesize response show coding results along with insight explainations

**Comment by toaster9996** [comment]
@dosu._ How stop PandasQueryEngine from degrading in code quality?

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from write synthesized response using prompts

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from writing "python" at the beginning of the code?

**Comment by toaster9996** [comment]
@dosu._ How to stop PandasQueryEngine from writing "python" at the beginning of the code with intructions?

**Comment by toaster9996** [comment]
@dosu._ Write a function in PandasQueryEngine to ignore string that does not start with `#` or `import` in the first line of code
