### ISSUE TITLE
[Question]: Approaches to searching documents requiring different kind of embeddings (multimodal too)

### ISSUE THREAD

**Issue by coffepowered** [run-llama/llama_index#13594]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
I am reflecting on how to tackle the problem of searching over a knowledge base that could require different modalities for embeddings. To make this more concrete, my users are used to upload:

- business documents/reports (what the system was conceived to ingest)
- documents containing code or SQL (I get bad performance on this!)
- documents containing images
- documents containing tables

I recall llama_index has some approaches to images and tables, but is there a general preferred pattern to do this?
In general, I see some options to handle this:
1. having a super strong multimodal embedding (which is able to interpret images, SQL, multilingual text and whatever). I am not aware of such an embedded 
2. maintaining segregated indexes for each modalities, then route queries depending on the type of question
3. a mix of 1-2.

Do you see more pattern to apply? Which would be the "llama-index" way of approaching the problem, if any?

**Comment by logan-markewich** [comment]
Basically it's 2. Create indexes for each type. The multimodal index is one specific use case of these, for images and text, but the general approach makes sense, since each modality requires a specific embedding model
