### ISSUE TITLE
[Question]: Is there any way to initialize my index data from the Elastic Search database?

### ISSUE THREAD

**Issue by mglslg** [run-llama/llama_index#13593]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I get an index initialized with a docstore through `VectorStoreIndex.from_vector_store`? When I create an index using the `VectorStoreIndex.from_vector_store` method, I find that its docstore is actually empty, which means that my memory is not initialized with vectors and there are no nodes. Is this a bug?

Or, is there any other way to initialize my index data from the Elastic Search database?

**Comment by mglslg** [comment]
@logan-markewich  Thank you for your answer!

I am a little confused about this docstore object. 

It seems like the docstore is something like a cache because when I call refresh_ref_docs, I found code like `self.docstore.set_document_hash(document.get_doc_id(), document.hash)`, and later when deciding whether to update, it compares the hash value in the docstore.

Could you please help me explain its design concept? I did not find any explanation related to it in the official documentation. I initially thought that using the refresh_ref_docs method would automatically read data from Elasticsearch and match the hash value, but later discovered that it only matches the cached hash value in the docstore. In the end, I had to manually check the hash value in Elasticsearch for matching. My code is finally like this:

```python
def get_changed_docs(es_index_name: str, doc_list: List[Document]) -> List[Document]:
    es_client = get_es_client()
    changed_doc_list = []
    for doc in doc_list:
        query = {
            "query": {
                "match": {
                    "metadata.doc_id": f"{doc.get_doc_id()}"
                }
            }
        }
        result = es_client.search(index=es_index_name, body=query)

        if not result['hits']['hits']:
            changed_doc_list.append(doc)
            continue

        hits = result['hits']['hits']

        for hit in hits:
            node_content = hit['_source']['metadata']['_node_content']
            node_obj = json.loads(node_content)
            if node_obj['relationships']['1']['hash'] != doc.hash:
                changed_doc_list.append(doc)

    return changed_doc_list


need_refresh_docs = get_changed_docs(es_index_name, mongo_documents)

index.refresh_ref_docs(need_refresh_docs)
```

Are there any other better implementations in llamaindex framework?

**Comment by schelv** [comment]
@mglslg Were you able to find a better solution?
