### ISSUE TITLE
[Question]: Storing Duplicates in vector Db

### ISSUE THREAD

**Issue by Amiya-Lahiri-AI** [run-llama/llama_index#13595]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have created nodes and the nodes are unique,. However when I am trying to create a vector Store index  it is creating duplicate 
entries in my vector db. I am using Qdrant Db and I have checked in my vector db, There are duplicate entries available.
this is my Qdrant db initialization 

```
import qdrant_client
from llama_index.vector_stores.qdrant import QdrantVectorStore
client = qdrant_client.QdrantClient(
    url="xxxxx",
    api_key="xxxxx",
)
asynclient = qdrant_client.AsyncQdrantClient(
    url="xxxxxx",
    api_key="xxxxxx",
)
# vector_store = QdrantVectorStore(client=client, collection_name="Tender-Db", aclient=asynclient)

```
and after creating nodes I am using the  storagecontext

```
from llama_index.core import VectorStoreIndex
from llama_index.core import StorageContext

storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    nodes,
    storage_context=storage_context,
    embed_model = VoyageEmbeddModel
)
# index = VectorStoreIndex.from_vector_store(vector_store=vector_store, embed_model=VoyageEmbeddModel)
```
can anyone please tell me how to resolve this issue

**Comment by logan-markewich** [comment]
You should use an ingestion pipeline with a docstore and vector store attached

Assuming each input document has a consistent doc id, it can look up the existing hash of that document (if any) in the docstore, and decide to upsert, skip, or insert 

Here's one example (ignore the cache though)
https://docs.llamaindex.ai/en/stable/examples/ingestion/redis_ingestion_pipeline/?h=ingestion+pipeline

**Comment by 130jd** [comment]
Thanks @logan-markewich would this be your recommended implementation if I wanted to do Chroma vector_store and a locally stored docstore?

**Embed and store in Chroma vector_store and local docstore:**
```
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        embed_model,
    ],
    docstore=SimpleDocumentStore(),
    vector_store=ChromaVectorStore(
        chroma_collection=chromadb.PersistentClient(path="./chroma_db").get_or_create_collection("collection_name")
    )
    docstore_strategy=DocstoreStrategy.UPSERTS
]

nodes = pipeline.run(documents=documents)

index = VectorStoreIndex.from_vector_store(
    pipeline.vector_store, embed_model=embed_model
)

pipeline.persist("./pipeline_storage")
```

**Load from Chroma vector_store and local docstore:**
```
documents = SimpleDirectoryReader(
    "./test_redis_data", filename_as_id=True
).load_data()

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5"),
    ]
)

pipeline.load("./pipeline_storage")

nodes = pipeline.run(documents=documents)

index = VectorStoreIndex.from_vector_store(
    pipeline.vector_store, embed_model=embed_model
)
```

**Comment by logan-markewich** [comment]
@130jd not quite -- you should pass in the vector store again when loading. Tbh I would load both the vector and docstore outside of the pipeline and just pass it in. But that's just me
