### ISSUE TITLE
[Question]: refresh_ref_docs does not work in Chroma even when using docstore. Am I doing something wrong?

### ISSUE THREAD

**Issue by pliablepixels** [run-llama/llama_index#13604]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi there, in [this issue](https://github.com/run-llama/llama_index/issues/8832)  @logan-markewich suggested an approach to use `refresh_ref_docs` when using 3rd party dbs (like Chroma). I've been trying that approach, but I don't see the system working as intended. More details below:

Here is how I'm creating:

```
docs = SimpleDirectorReader(input_dir=path, filename_as_id=True, recursive=True).load_data()
db = chromadb.PersistentClient(path=persist_dir)
cc=db.get_or_create_collection(col_name)
vector_store = ChromaVectorStore(chroma_collection=cc)
storage_context = StorageContext.from_defaults(vector_store = vector_store)
index = VecstoreStoreIndex.from_documents(docs, storage_context = storage_context, store_nodes_override=True, show_progress=True)
index.storage_context.persist(persist_dir)
```

All good. I see `docstore.json` being created with the file metadata, filenameas as doc_ids etc. in addition to chroma db sqlite dbs. I validated docstore.json file is acurage (total 5 files with the right meta data)

Now, I go to source docs and remove 2 files. Then I run the 'load' part:

```
db = chromadb.PersistentClient(path=persist_dir)
cc=db.get_or_create_collection(col_name)
vector_store = ChromaVectorStore(chroma_collection=cc)docs = SimpleDirectorReader(input_dir=path, filename_as_id=True, recursive=True).load_data()
storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir=persist_dir)
docstore_index = load_index_from_storage(storage_context)
r = docstore_index.refresh_ref_docs(docs, update_kwargs={"delete_kwargs": {"delete_from_docstore":True}})
print (sum(r))
# Do I need to persist docstore after this?

```
What I see however is no documents were deleted (sum(r)=0). 

Thanks

**Comment by logan-markewich** [comment]
It's only meant to upsert existing docs. If a doc is missing, it won't catch it

**Comment by logan-markewich** [comment]
Since posting that comment, I would lean towards using an ingestion pipeline with a docstore and vector store attached, which does support the "delete things that are missing" use case you are wanting here

**Comment by logan-markewich** [comment]
```python
from llama_index.core.ingestion import (
    DocstoreStrategy,
    IngestionPipeline,
    IngestionCache,
)

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(),
        OpenAIEmbedding(embed_batch_size=100),
    ],
    docstore=docstore,
    vector_store=vector_store,
    docstore_strategy=DocstoreStrategy.UPSERTS_AND_DELETE,
)

pipeline.run(documents=documents)
```

**Comment by pliablepixels** [comment]
whoa. Seems much simpler. Giving this a try. Will report.

**Comment by pliablepixels** [comment]
@logan-markewich perfect. Everything works A-OK!
