### ISSUE TITLE
[Question]: LLamaIndex Chat engine restricting answers to context

### ISSUE THREAD

**Issue by Varshan2003** [run-llama/llama_index#13613]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to have a chat engine by providing a context but I am getting answers outside the context too. I tried the same thing with the query engine and seems to work fine, the problem is only with the chat engine. When I ask a question about Amazon or Google, I am getting the answer from LLM but what I am expecting is a message that the context did not have the information. This behavior is observed in the query engine

storage_context = StorageContext.from_defaults(persist_dir="storage")
index=load_index_from_storage(storage_context,service_context=service_context)
chat_engine = index.as_chat_engine(
            chat_mode="context",
            memory=memory,
          verbose=True,            
        )
Thanks in advance for the help

**Comment by Varshan2003** [comment]
@logan-markewich  could you please help me with this?

**Comment by Varshan2003** [comment]
@shivamklr It's working with query engine, but not with chat Engine

**Comment by shivamklr** [comment]
Two things 
1. (Unrelated, but still )StorageContext is legacy.
2. The example you have provided, uses class ContextChatEngine behind the scenes which uses this prompt. 

    > DEFAULT_CONTEXT_TEMPLATE = (
        "Context information is below."
        "\n--------------------\n"
        "{context_str}"
        "\n--------------------\n"
    )

    Whereas, when you use `as_query_engine` method on a class that inherits BaseIndex class, it uses the RetrieverQueryEngine
which uses this prompt template
    > DEFAULT_TEXT_QA_PROMPT_TMPL = (
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information and not prior knowledge, "
    "answer the query.\n"
    "Query: {query_str}\n"
    "Answer: "
)

This is the **default** behavior as of now. You can create wrapper classes around the already implemented classes to modify the behavior. I hope that explains it.

**Comment by shivamklr** [comment]
On second thought, you don't need a wrapper class, you can pass the the additional arguments in the `as_chat_engine` method, like this.
```python
chat_engine = index.as_chat_engine(
chat_mode="context",
system_prompt=
context_template=
memory=memory,
verbose=True,
)
```
You can look into the docs for more info on prompts.

**Comment by Varshan2003** [comment]
Thank you

**Comment by logan-markewich** [comment]
@Varshan2003 since you are already specifying the context template, you'd really only have to add the instructions there. Just a matter of prompt engineering

**Comment by logan-markewich** [comment]
@shivamklr is right @Varshan2003 , you can modifying the context template, or specify a system prompt, which gets appended to the context template
