### ISSUE TITLE
[Question]: PGVectorStore

### ISSUE THREAD

**Issue by Giselasnjota** [run-llama/llama_index#13624]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to use PGVectorStore but when is creating a table instead of use the table name I pass, why? And the file is created empty.

vector_store = PGVectorStore.from_params(
     database=db_name,
     host=url.host,
     password=url.password,
     port=url.port,
     user=url.username,
     table_name="interrests_embeddings",
     schema_name="public",
     perform_setup= False,
     embed_dim=1536  # openai embedding dimension
)

And what collumns are necessary in my table?

**Comment by cay89** [comment]
I use UUID as the primary key throughout my database. Is it necessary to use a numeric auto-increment ID for this table? Are there any other options for using the UUID type in the ID field?
