### ISSUE TITLE
[Feature Request]: Use LLM based on OpenAI's official client

### ISSUE THREAD

**Issue by o1iv3r** [run-llama/llama_index#13621]
### Feature Description

It would be great if one could use an LLM based on the official OpenAI client. More precisely, I would like to have an OpenAI-like LLM class which inherits from the official OpenAI client:

```
from openai import OpenAI

class LLM_standardized_UI(OpenAI)

llm = LLM_standardized_UI()
# then use llm.invoke(...) etc.
```

### Reason

Many LLM hosting frameworks like TGI and vLLLM are compatible with the Open AI API. Hence their client can be used. For some users, the authentication process is a bit more complicated due to corporate gateways etc. Thus, changing secret and url is not sufficient. For example, I have to make bigger changes to the [authentication header of the client](https://github.com/openai/openai-python/blob/5a89126ad208c58b9e1dbd1fbdb698e4c00f7d8e/src/openai/_client.py#L156)

### Value of Feature

If there was a class that inherits from OpenAI's official client, it would be easy to inherit from any class with minor modifications, say updated headers.  Currently `from 
from llama_index.llms.openai import OpenAI` does not inherit from the official client, hence, major modifcations are required. I'd then simply use llama-index like this

```
from openai import OpenAI

class myOAIimplementation(OpenAI):
   # modify auth_headers

class LLM_standardized_UI(myOAIimplementation)

llm = LLM_standardized_UI()
# then use llm.invoke(...) etc.
```

**Comment by logan-markewich** [comment]
@o1iv3r have you seen the `OpenAILike` LLM class? Does this solve your need?

`pip install llama-index-llms-openai-like`

```
from llama_index.llms.openai_like import OpenAILike

llm = OpenAILike(base_url="..", api_key="fake", model="some_model")
```

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-openai-like/llama_index/llms/openai_like/base.py

**Comment by o1iv3r** [comment]
Thanks, unfortunately not. I have seen this. But we have to change more then simply the base_url and the api_key.
