### ISSUE TITLE
[Question]: convert default VectorStoreIndex into PGVectoRsStore

### ISSUE THREAD

**Issue by veeresh-dammur** [run-llama/llama_index#13627]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
from llama_index.core import StorageContext, load_index_from_storage, VectorStoreIndex

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="<persist_dir>")

# load index
index = load_index_from_storage(storage_context)
```

The above snippet is from the [official documentation](https://docs.llamaindex.ai/en/stable/understanding/storing/storing/). 

Is it possible to convert the "index" into  PGVectoRsStore ?

context : I am running the housekeeping job that performs the indexing. at the end of the indexing process I want to persist to the directory and I want to use artifacts  (stored at the persist dir) to build the PGVectorStore.

**Comment by logan-markewich** [comment]
I feel like dosu hallucinated that?

I'm curious whybyou don't build the index with pgvector to begin with?

In any case, you'd need the nodes and embeddings 

So something like

```
index = load_index_from_storage(...)

nodes = list(index.docstore.docs.values())

for node in nodes:
  node.embedding = index.vector_store.get(node.node_id)

pg_vector_store = PGVectorStore.from_params(...)

pg_vector_store.add(nodes)

new_index = VectorStoreIndex.from_vector_store(vector_store)
```

**Comment by veeresh-dammur** [comment]
This is what I was looking for. Thank you for the quick response  :)

**Comment by Suhaib441** [comment]
How do I specify the index type (HNSW or IVFFlat) during the indexing step? I don't see any parameters specifying the index type. There is only the possibility to choose the index during querying in PgVector Query Options.
