### ISSUE TITLE
how to use metadata of node?

### ISSUE THREAD

**Issue by susht3** [run-llama/llama_index#13637]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i want to set some attributes for node，like this:
```
node.metadata = {"file_name": file_name, "module": module_name}
node.excluded_llm_metadata_keys = ["file_name"]
node.excluded_embed_metadata_keys = ["file_name"]
```
What role does metadata play? does it append "module" to origin text？
i find the document：metadata - a dictionary of annotations that can be appended to the text.

**Comment by logan-markewich** [comment]
It's added to the text during embedddings and/or llm calls

See here
https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/?h=customizing#advanced-metadata-customization
