### ISSUE TITLE
[Bug]: When using llamaIndex to access a Ollama local LLM (llama3:8b)service in mac, there will be error 503

### ISSUE THREAD

**Issue by toondata** [run-llama/llama_index#13640]
### Bug Description

In a Mac environment, when the OS system proxy is set, using llamaIndex to access the local Ollama environment LLM , It will results in an access error.

error msg ----------------------------------------------------------------------------------------------------------
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://127.0.0.1:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

and i try to change the baseurl , it's error too
--------------------------------------------------------
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://localhost:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503

so maybe this has nothing to do with proxy

But I use Rapid api tools build the same http request,it can access the serivce and no error

--------------------------------------------------Rapid Api access is OK
![image](https://github.com/run-llama/llama_index/assets/161798274/6f4b0e03-6496-4cff-81c0-2fcf04b78f5e)

### Version

0.10.37

### Steps to Reproduce

 self.llm = Ollama(model="llama3:8b", request_timeout=120.0, json_mode=True,base_url="http://127.0.0.1:11434")

messages = [
            ChatMessage(
                role="system", content=systemPrompt
            ),
            ChatMessage(role="user", content=userPrompt),
        ]
  resp = self.llm.chat(messages=messages) ---error

------------------------------------------------------------- use the same code but change llm to openai,the code is running  ok
self.llm = OpenAI(model=model,api_key="sk-xxxxxxx")
messages = [
            ChatMessage(
                role="system", content=systemPrompt
            ),
            ChatMessage(role="user", content=userPrompt),
        ]
  resp = self.llm.chat(messages=messages)

### Relevant Logs/Tracbacks

```shell
File "/Users/xxx/Library/Mobile Documents/com~apple~CloudDocs/products/dev/workspaces/flask/llm/ollama.py", line 31, in chat
    resp = self.llm.chat(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/anaconda3/envs/ollama/lib/python3.11/site-packages/llama_index/core/llms/callbacks.py", line 148, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/xxx/anaconda3/envs/ollama/lib/python3.11/site-packages/llama_index/llms/ollama/base.py", line 135, in chat
    response.raise_for_status()
  File "/Users/xxx/anaconda3/envs/ollama/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '503 Service Unavailable' for url 'http://127.0.0.1:11434/api/chat'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503
```

**Comment by RussellLuo** [comment]
> In a Mac environment, when the OS system proxy is set, using llamaIndex to access the local Ollama environment LLM , It will results in an access error.

If the proxy is turned off, would LlamaIndex still throws the same error?

> so maybe this has nothing to do with proxy
>
> But I use Rapid api tools build the same http request,it can access the serivce and no error

I'm not familiar with Rapid API, but I guess perhaps it's aware of the proxy if you have set Proxy Configurations for it.

As a comparison, I suggest you try the cURL command to see what results it yields.

**Comment by toondata** [comment]
Thank you everyone. The ultimate issue indeed stemmed from the setting of a global proxy. It remains unclear why the use of Rapid API did not trigger the proxy while behaving normally. The issues observed with the effects of curl and the Python Flask application calls were similar. Additionally, the attempted solution of bypassing the global proxy via macOS network settings proved ineffective on my machine, and it's unclear whether it's due to my configuration. However, this isn't my most pressing concern at the moment, so I've adjusted my local large model trial to conduct various tests of large model performance through OpenRouter. Thanks again, everyone.

**Comment by Lyy0617** [comment]
> Thank you everyone. The ultimate issue indeed stemmed from the setting of a global proxy. It remains unclear why the use of Rapid API did not trigger the proxy while behaving normally. The issues observed with the effects of curl and the Python Flask application calls were similar. Additionally, the attempted solution of bypassing the global proxy via macOS network settings proved ineffective on my machine, and it's unclear whether it's due to my configuration. However, this isn't my most pressing concern at the moment, so I've adjusted my local large model trial to conduct various tests of large model performance through OpenRouter. Thanks again, everyone.

Hello, I have encountered a similar issue as you. After using the global proxy, I couldn't connect to the local Ollama service. Have you found a solution?
