### ISSUE TITLE
[Bug]: SpaCy version issue

### ISSUE THREAD

**Issue by neeagl** [run-llama/llama_index#13650]
### Bug Description

Our build with 0.10.37 started to fail when 0.10.38 was released today. pip was unable to resolve SpaCy version requirements.
On further digging, I found that spacy version requirement has been changed to * 
https://github.com/run-llama/llama_index/pull/13634/files#diff-27c22ecf2f62e56c8d2bf98a06cb5d30d84a49c6aba59fc5192ed92732f08d50R66

<img width="1104" alt="Screenshot 2024-05-22 at 3 14 25 PM" src="https://github.com/run-llama/llama_index/assets/902759/0c61a207-1e39-4464-a0d0-a709e8ca0897">

Request you to release a fix immediately.

### Version

0.10.37

### Steps to Reproduce

Described above.

**Comment by neeagl** [comment]
@dosu we're using pip not poetry.

**Comment by logan-markewich** [comment]
You must have some other requirements that are causing spacy to search for a version? A `pip install llama-index` in a fresh env works for me

**Comment by logan-markewich** [comment]
Fixed in `llama-index-core=0.10.38.post2`

`pip install -U llama-index-core` will get it
