### ISSUE TITLE
[Question]: How to get nodes from ES ？

### ISSUE THREAD

**Issue by yzgrfsy** [run-llama/llama_index#13656]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

我实现创建了index到ES中，现在按照LLamaindex的官网指导
https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever/
创建自定义的检索器(结合矢量检索器和 BM25 检索器),实现 Hybrid Retriever ：

class HybridRetriever(BaseRetriever):
    def init(self, vector_retriever, bm25_retriever):
    self.vector_retriever = vector_retriever
    self.bm25_retriever = bm25_retriever
    super().init()

    def _retrieve(self, query, **kwargs):
        bm25_nodes = self.bm25_retriever.retrieve(query, **kwargs)
        vector_nodes = self.vector_retriever.retrieve(query, **kwargs)
    
        # combine the two lists of nodes
        all_nodes = []
        node_ids = set()
        for n in bm25_nodes + vector_nodes:
            if n.node.node_id not in node_ids:
                all_nodes.append(n)
                node_ids.add(n.node.node_id)
        return all_nodes

但是我遇到一个问题，我需要实例化两个检索器。其中：vector_retriever 是这样实例化：
vector_store = ElasticsearchStore(
index_name=es_index_name, es_url=CONS_ELASTIC_SEARCH_URL
)

storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_vector_store(embed_model=Settings.embed_model, vector_store=vector_store,
                                           storage_context=storage_context)

vector_retriever = index.as_retriever(similarity_top_k=10) 。这个是ok的。
但是：在实例化bm25_retriever时候：、
bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=10)出错，请问大家，如何从已保存index的ES中得到nodes ，然后实例化bm25_retriever

我在保存index的代码是这样的：存储index是ok的。
def load_nodes(file_dir: str) -> List[BaseNode]:
    documents = read_file(input_dir=file_dir, required_exts=[".csv"], recursive=False)
    parser = SentenceSplitter(chunk_size=CHUNK_SIZE, chunk_overlap=CHUNK_OVERLAP)
    nodes = parser.get_nodes_from_documents(documents)
    logging.info("node的数量：{num}".format(num=len(nodes)))
    return nodes

def save_es_index(nodes: List[BaseNode], index_name: str, es_url: str):
    vector_store = ElasticsearchStore(
        index_name=index_name, es_url=es_url
    )
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    storage_context.docstore.add_documents(nodes)
    index = VectorStoreIndex(nodes, storage_context=storage_context,
                             show_progress=True)
    return index

def load_csv_data_to_es(file_path: str, index_name: str = "hr_nodes"):
    nodes = load_nodes(file_dir=file_path)
    save_es_index(nodes=nodes, index_name=index_name, es_url=CONS_ELASTIC_SEARCH_URL)

感谢感谢。

**Comment by zhaozhiming** [comment]
@yzgrfsy  You should create elasticsearch bm25 retriever like this: 

```py
from llama_index.vector_stores.elasticsearch import AsyncBM25Strategy
from llama_index.core import Settings

text_store = ElasticsearchStore(
    index_name="avengers",
    es_url="http://localhost:9200",
    retrieval_strategy=AsyncBM25Strategy(),
)
Settings.embed_model = embed_model
text_index = VectorStoreIndex.from_vector_store(
    vector_store=text_store,
)
text_retriever = text_index.as_retriever(similarity_top_k=2)
```
