### ISSUE TITLE
[Bug]: Where is the InsertDemo.ipyb in official website? 

### ISSUE THREAD

**Issue by FWiner** [run-llama/llama_index#13680]
### Bug Description

[document management](https://docs.llamaindex.ai/en/stable/module_guides/indexing/document_management/)
where is the An example notebook showcasing our insert capabilities is given [here](https://github.com/jerryjliu/llama_index/blob/main/examples/paul_graham_essay/InsertDemo.ipynb)??? 
That is showing 404 page not found.

### Version

0.10.26

### Steps to Reproduce

where is the An example notebook showcasing our insert capabilities is given [here](https://github.com/jerryjliu/llama_index/blob/main/examples/paul_graham_essay/InsertDemo.ipynb)

**Comment by logan-markewich** [comment]
Its an out of date link, we deleted that folder. That link should just be removed from the docs.

Looking back at what it was, it was a pretty useless demo lol

You can insert documents `index.insert(document)` or insert nodes with `index.insert_nodes(nodes)`
