### ISSUE TITLE
[Question]: index.insert(new_docuemnts) performance

### ISSUE THREAD

**Issue by FWiner** [run-llama/llama_index#13683]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

here's my code:

Load init documents:

```
documents = SimpleDirectoryReader('../../data/knowledge').load_data(show_progress=True)
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-m3", embed_batch_size=20, cache_folder="../../model_cache")
```

Create vector store and get index with init documents:

```
chroma_collection = get_or_create_collection('./chroma_test', 'chroma_test')

print(chroma_collection.peek())


vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context, embed_model=embed_model
)
```

add a new document:

```
new_documents = SimpleDirectoryReader(input_files=['../../data/csv/agent_list.pdf']).load_data(show_progress=True)
for doc_chunk in new_documents:
    index.insert(doc_chunk)
```
index.insert a new document with 2min36s (with 68 pages)

Now  i have some questions.
1. Whether index is saved in-memory?
2. Whether chroma_collection is updated when index.insert a new document ?
3. Will the embeddings model specified when creating the index be automatically used when executing index.insert? Is this why it's slow?

**Comment by logan-markewich** [comment]
1. Whether or not it's saved in memory depends on the vector db you are using. I can't say for sure how chroma manages memory 
2. Yes
3. Yes, it uses the embed model attached to the index. `bge-m3` is a pretty large model as far as embedding models go (2.2GB). The speed largely depends on your hardware, running on cpu vs. gpu, and the size of chunks being embedded

**Comment by FWiner** [comment]
Thank you very much for your patient answer! @logan-markewich

Now I  want to delete a previously added document, how do I do it?
chroma can delete documents use ids. index can delete document use  `index.delete_ref_doc("doc_id_0", delete_from_docstore=True)
`
Is that mean i need to save the doc_id or set a special id after load data for deletion and update ?

**Comment by logan-markewich** [comment]
The ID here is just the doc id of the original input document

**Comment by FWiner** [comment]
```
documents = SimpleDirectoryReader("."+ KNOWLEDGE_BASE_PATH).load_data(show_progress=True)
print(len(documents))  //39
```

```
chroma_collection = get_or_create_collection('./chroma_test', 'chroma_test')


vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

storage_context = StorageContext.from_defaults(vector_store=vector_store)

index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context, embed_model=embed_model
)

print(chroma_collection.count())  //57
```

![image](https://github.com/run-llama/llama_index/assets/11935023/c2f0aa4b-2bca-414e-8318-8abc94ef8182)


Why do different nodes of the same source file have different ref_doc_id? How should I delete it later?

**Comment by logan-markewich** [comment]
You should set the doc id to something memorable (like a file path) before inserting 

You can also set a flag `SimpleDirectoryReader(..., filename_as_is=True)`

**Comment by FWiner** [comment]
I've tried set flag use `SimpleDirectoryReader(..., filename_as_is=True)`
I found in the vector db is the same result like the image above.
I can see two nodes with different document_id like "/xxx/xxx/agent_list.pdf_part_0", "/xxx/xxx/agent_list.pdf_part_1","/xxx/xxx/agent_list.pdf_part_2". and the ref_doc_id value is same with their document_id and doc_id.
we must to store three ref_doc_id and call three times `index.delete_ref_doc()`
Is there any way to set the same ref_doc_id for the same file ?
