### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.tools'

### ISSUE THREAD

**Issue by babs207** [run-llama/llama_index#13687]
### Bug Description

from llama_index.tools.brave_search import BraveSearchToolSpec
ModuleNotFoundError: No module named 'llama_index.tools'

### Version

llama-index=0.10.38

### Steps to Reproduce

I do not know

### Relevant Logs/Tracbacks

```shell
from llama_index.tools.brave_search import BraveSearchToolSpec
ModuleNotFoundError: No module named 'llama_index.tools'
```

**Comment by RussellLuo** [comment]
Hi @babs207, have you installed the corresponding package? If not, try:

```
pip install llama-index-tools-brave-search
```

**Comment by GoodGuyGregory** [comment]
just for general knowledge this also solves the problems with `uv` 

I had a similar issue with DuckDuckGo Search. 

`from llama_index.tools.duckduckgo import DuckDuckGoSearchToolSpec`was throwing an annoying and frustrating 😠 error. 

this solved the issue right away thanks @RussellLuo 

`uv add llama-index-tools-duckduckgo`

Now I am quacking along 🦆  👋
