### ISSUE TITLE
[Bug]: Support for "gpt-4" Model in Llama Index (AzureOpenAIMultiModal) 

### ISSUE THREAD

**Issue by mrtsnd97** [run-llama/llama_index#13696]
### Bug Description

Hello,

I am currently using Llama Index for a project that requires multimodal generation with the Azure OpenAI service. I have deployed the model "gpt-4-turbo-2024-04-09" on Azure, which is displayed in the Azure portal with the model name "gpt-4" and version "2024-04-09".

When I try to use this model with Llama Index, I encounter the following error:

ValueError: Invalid model gpt-4. Available models are: ['gpt-4-vision-preview', 'gpt-4-turbo-2024-04-09', 'gpt-4-turbo', 'gpt-4o', 'gpt-4o-2024-05-13']

It appears that the Llama Index library does not recognize "gpt-4" as a valid model name, even though this is how the model is identified in the Azure portal. To resolve this issue, I kindly request that support for the "gpt-4" model name be added to the default models in Llama Index.

Details:

Azure Model Name: gpt-4
Azure Version: turbo-2024-04-09
Actual Model Deployed: gpt-4-turbo-2024-04-09

Thank you for your support and assistance.

### Version

0.10.38

### Steps to Reproduce

mm_llm = AzureOpenAIMultiModal( 
                model = "gpt-4",
                deployment_name = "gpt-4-turbo-vision",
     
                azure_endpoint = endpoint,
                api_key = key,
                openai_api_type="azure",
                openai_api_version = '2023-05-15',
                temperature=0
                )

response_img = mm_llm.complete(
    prompt="Can you describe the image",
    image_documents=image_path_
)

### Relevant Logs/Tracbacks

```shell
ValueError: Invalid model gpt-4. Available models are: ['gpt-4-vision-preview', 'gpt-4-turbo-2024-04-09', 'gpt-4-turbo', 'gpt-4o', 'gpt-4o-2024-05-13']
```

**Comment by mrtsnd97** [comment]
@dosu it does not work

**Comment by logan-markewich** [comment]
@mrtsnd97 did you update the package? I think it should be `pip install -U llama-index-llms-openai`
