### ISSUE TITLE
[Feature Request]: Add function calling tool for LLMs on AWS Bedrock

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_index#13707]
### Feature Description

I am trying to instantiate an agentworker from tools with my AWS Bedrock LLM. However I received the error

```ValueError: Model name mistral.mixtral-8x7b-instruct-v0:1 does not support function calling API.```

It would be great if llamaindex could add this feature for LLMs in cloud platforms!

### Value of Feature

There are many LLMs stored within cloud platforms today, and some organizations only have access to LLMs gated within these cloud platforms (for e.g. Azure OpenAI instead of OpenAI, Claude Opus through AWS Bedrock instead of Anthropic) so it would be great if llamaindex could add these enhancements.

**Comment by logan-markewich** [comment]
This means the llm has to support tools/functions directly in the client api. From my understanding persuading, bedrock doesn't really offer this yet for any of their llms?

You can use a react agent worker instead

**Comment by alecl** [comment]
Official tool use through Bedrock does actually work in with the very recent Converse API

> Converse API supports Tool use (function calling), which for supported models (Anthropic's Claude 3 model family including Claude 3 Opus, Claude 3 Sonnet, and Claude 3 Haiku; Mistral Large; and Cohere’s Command R and R+)

https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-bedrock-new-converse-api/

https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html
