### ISSUE TITLE
[Question]: How to do a text-based RAG using AzureOpenAIMultiModal and gpt-4o

### ISSUE THREAD

**Issue by mballav** [run-llama/llama_index#13727]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to use gpt-4o as my model for RAG on PDF/txt documents. Could someone please provide an example of how I can do that? 

Do I need to use AzureOpenAIMultiModal class or AzureOpenAI?

When I use AzureOpenAI, it complains about the model not supported. Here is my code:

```
        return AzureOpenAI(
            model="gpt-4o-2024-05-13",
            deployment_name="gpt4o",
            azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT"),
            api_key=os.getenv("AZURE_OPENAI_API_KEY"),
            openai_api_type="azure",
            openai_api_version='2024-05-13',
            temperature=0
        )
```

And, here is the error message:

```
ValueError: Unknown model 'gpt-4o-2024-05-13'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-
preview, gpt-4-vision-preview, gpt-4-1106-vision-preview, gpt-4-turbo-2024-04-09, gpt-4-turbo, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k,
 gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-0125, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613
```

**Comment by mballav** [comment]
@dosu If I were to create MultiModalVectorStoreIndex from nodes, how would I do that?

**Comment by logan-markewich** [comment]
@mballav its supported on the LLM, but you need to update probably

`pip install -U llama-index-llms-azure-openai llama-index-llms-openai`

**Comment by mballav** [comment]
Thanks alot, @logan-markewich! You saved my day.

**Comment by szcc** [comment]
Hi @dosu 
I ran :pip install -U llama-index-llms-azure-openai llama-index-llms-openai
and this line:
  index = MultiModalVectorStoreIndex.from_documents(documents, storage_context=storage_context)

give me AssertionError:
llama_index/legacy/vector_stores/qdrant.py:188, in QdrantVectorStore._build_points(self, nodes)
    180     sparse_indices, sparse_vectors = self._sparse_doc_fn(
    181         [
    182             node.get_content(metadata_mode=MetadataMode.EMBED)
    183             for node in node_batch
    184         ],
    185     )
    187 for i, node in enumerate(node_batch):
--> 188     assert isinstance(node, BaseNode)
    189     node_ids.append(node.node_id)
    191     if self.enable_hybrid:

AssertionError:
