### ISSUE TITLE
[Question]: LlamaIndex Multi-Document Agents 

### ISSUE THREAD

**Issue by dragoa** [run-llama/llama_index#13728]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I'm following the documentation at [](https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents/) but instead of using OpenAI I'm using Mistral 7b via HuggingFaceLLM 

```llm = HuggingFaceLLM(
    context_window=4096,
    max_new_tokens=256,
    generate_kwargs={"temperature": 0.0, "do_sample": False},
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="mistralai/Mistral-7B-Instruct-v0.3",
    model_name="mistralai/Mistral-7B-Instruct-v0.3",
    device_map="auto",
    stopping_ids=[50278, 50279, 50277, 1, 0],
    tokenizer_kwargs={"max_length": 4096},
    # uncomment this if using CUDA to reduce memory usage
    model_kwargs={"torch_dtype": torch.float16}
)

Settings.llm = llm
Settings.chunk_size = 1024
```

Now at the end when I'm calling the ```response = top_agent.chat("Tell me about the status of Confezioni Simmy 2014 company")```
I receive the following error:
```TemplateError: Conversation roles must alternate user/assistant/user/assistant/...```
I used as promt 

```# setup prompts
from llama_index.core import PromptTemplate

SYSTEM_PROMPT = """You are an AI assistant that answers questions in a friendly manner, based on the given source documents. Here are some rules you always follow:
- Generate human readable output, avoid creating output with gibberish text.
- Generate only the requested output, don't include any other language before or after the requested output.
- Never say thank you, that you are happy to help, that you are an AI agent, etc. Just answer directly.
- Generate professional language typically used in business documents in North America.
- Never generate offensive or foul language.
"""

query_wrapper_prompt = PromptTemplate(
    "[INST]<<SYS>>\n" + SYSTEM_PROMPT + "<</SYS>>\n\n{query_str}[/INST] "
)
```

so is the user that correctly start it. 

Do you know what I could fix to make it work?

Thank you!

**Comment by JensPMB** [comment]
Hi, for some reason the HuggingFaces tokenizer has an old template for Mistral-7B-Instruct-v0.2 / Mistral-7B-Instruct-v0.3 (and I believe Mistral-7B-Instruct-v0.1 genuinely didn't support system prompt) To get around the problem you have to write your own messages_to_prompt and pass in or use a tokenizer that works e.g. llama-2 chat. 🤷

e.g. 

def mistralv2_messages_to_prompt(messages):
            conversation = ""
            bos_token = "<s>"
            eos_token= "</s>"
            if messages[0].role ==  MessageRole.SYSTEM:
                loop_messages = messages[1:]
                system_message = messages[0].content
            else:
                loop_messages = messages
                system_message = False

            for index, message in enumerate(loop_messages):
                if (message.role == MessageRole.USER) != (index % 2 == 0):
                    raise Exception('Conversation roles must alternate user/assistant/user/assistant/...')
                if index == 0 and system_message != False:
                    content = '<<SYS>>\n' + system_message + '\n<</SYS>>\n\n' + message.content
                else:
                    content = message.content
                if message.role == MessageRole.USER:
                    conversation += bos_token + '[INST] ' + content.strip() + ' [/INST]'
                elif message.role == MessageRole.ASSISTANT:
                    conversation += ' ' + content.strip() + ' ' + eos_token

            return (conversation)
