### ISSUE TITLE
[Bug]:  I can't load a document's to ondemandloadertool to use it as a tool

### ISSUE THREAD

**Issue by bhuvanweb3** [run-llama/llama_index#13732]
### Bug Description

I wanted to give my local document as a query engine to langchain agents. So, I loaded my pdf with simple directory reader and give it to ondemandloadertool

### Version

llama-index==0.10.4

### Steps to Reproduce

from llama_index.core import (
    SimpleDirectoryReader,
    VectorStoreIndex,
    StorageContext,
    load_index_from_storage,
)
from llama_index.core.tools.ondemand_loader_tool import OnDemandLoaderTool
from typing import List

from pydantic import BaseModel
from llama_index.core.tools import QueryEngineTool, ToolMetadata
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.huggingface import HuggingFaceInferenceAPI
import os
from llama_index.readers.wikipedia import WikipediaReader
from getpass import getpass
from huggingface_hub import login
reader = SimpleDirectoryReader(input_files= ["C:/Users/as/Downloads/1249004.pdf"])
tool = OnDemandLoaderTool.from_defaults(reader,name="RAG Tool",description="Reasearch paper on graphology science")

**Comment by logan-markewich** [comment]
What's the error?

**Comment by bhuvanweb3** [comment]
> What's the error?

![image](https://github.com/run-llama/llama_index/assets/156995407/c1a35648-3aac-4aa1-8c6f-68ac6cf0a736)

**Comment by bhuvanweb3** [comment]
reader = SimpleDirectoryReader(input_files= ["C:/Users/as/Downloads/1249004.pdf"])
from pydantic import BaseModel

class TestSchemaSpec(BaseModel):
    query_str: str
test_schema_spec_instance = TestSchemaSpec(query_str="")
tool = OnDemandLoaderTool.from_defaults(
    reader=reader,
    index_cls=VectorStoreIndex,
    index_kwargs={"service_context": None,"embed_model":HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5"),"llm":HuggingFaceInferenceAPI(model_name="mistralai/Mixtral-8x7B-Instruct-v0.1", token=HF_TOKEN)},  # Adjust as needed
    name="RAG Tool",
    description="Research paper on graphology science",
    fn_schema=test_schema_spec_instance)
tool_args_schema = ToolArgsSchema(query_str="")
lc_tool = tool.to_langchain_structured_tool(verbose=True,args_schema=tool_args_schema)

![image](https://github.com/run-llama/llama_index/assets/156995407/948c2f47-b8d7-4c36-82c6-003793cc408b)

**Comment by bhuvanweb3** [comment]
> Entering new AgentExecutor chain...
Thought: I can use the RAG Tool to provide information on the Big Five personalities.
Action:
```
{
  "action": "RAG Tool",
  "action_input": {
    "is_remote": true,
    "query_str": "Big Five personalities"
  }
}
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[46], line 1
----> 1 agent.run("What are the big 5 personalities?")

File c:\Users\as\anaconda3\Lib\site-packages\langchain_core\_api\deprecation.py:148, in deprecated.<locals>.deprecate.<locals>.warning_emitting_wrapper(*args, **kwargs)
    146     warned = True
    147     emit_warning()
--> 148 return wrapped(*args, **kwargs)

File c:\Users\as\anaconda3\Lib\site-packages\langchain\chains\base.py:595, in Chain.run(self, callbacks, tags, metadata, *args, **kwargs)
    593     if len(args) != 1:
    594         raise ValueError("`run` supports only one positional argument.")
--> 595     return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
    596         _output_key
    597     ]
    599 if kwargs and not args:
    600     return self(kwargs, callbacks=callbacks, tags=tags, metadata=metadata)[
    601         _output_key
    602     ]

File c:\Users\as\anaconda3\Lib\site-packages\langchain_core\_api\deprecation.py:148, in deprecated.<locals>.deprecate.<locals>.warning_emitting_wrapper(*args, **kwargs)
    146     warned = True
    147     emit_warning()
--> 148 return wrapped(*args, **kwargs)
...
    134     query_str = kwargs.pop(self._query_str_kwargs_key)
--> 136 docs = self._loader(*args, **kwargs)
    138 return query_str, docs

TypeError: SimpleDirectoryReader.load_data() got an unexpected keyword argument 'is_remote'

**Comment by bhuvanweb3** [comment]
@dosu
