### ISSUE TITLE
[Bug]: Metadata filters not working with VectorIndexRetriever for Milvus

### ISSUE THREAD

**Issue by mballav** [run-llama/llama_index#13742]
### Bug Description

Here is my code that creates and adds filters
```
            # configure filters
            filters = MetadataFilters(filters=[MetadataFilter(key="file_name", value=filename),
                                               MetadataFilter(key="topic_id", value=topic.topic)],
                                      condition=FilterCondition.AND)
            # configure retriever
            retriever = VectorIndexRetriever(
                service_context=self.service_context,
                index=index,
                similarity_top_k=6,
                filters=filters
            )
            
            nodes = retriever.retrieve(query)
```

When run, it throws the following error:
```
MilvusException: (code=1100, message=failed to create query plan: cannot parse expression: file_name == "Lohmod 2024-03-1.pdf"topic_id in [\'XYZ\'] and and topic_id == "XYZ", error: invalid expression: file_name == "Lohmod 2024-03-1.pdf"topic_id in [\'XYZ\'] and and topic_id == "XYZ": invalid parameter)>
```

### Version

0.10.37

### Steps to Reproduce

- Create a vector index using Milvus as vector store
- Try to filter nodes using VectorIndexRetriever
- Use multiple metadata filters "and"-ed. (Single filter works fine)

**Comment by RussellLuo** [comment]
Hi @mballav, it seems that you are not using the latest version of `llama-index-vector-stores-milvus`, try installing the latest one and see how it goes:

```
pip install llama-index-vector-stores-milvus==0.1.14
```

Additionally, what's the value of `topic.topic`? Is it a list of string? It will be more helpful if you could provide a minimal and runnable code snippet :)

**Comment by mballav** [comment]
@RussellLuo Thanks for the tip. I did that, though the issue really had to do with the implementation of _to_milvus_filter(). 

The bot really pointed out what needed to be done!

Now I have my own version of MilvusVectorStore and it works beautifully.

Thanks alot!
