### ISSUE TITLE
[Question]: sentence-spliter's randomness

### ISSUE THREAD

**Issue by guangyuli-uoe** [run-llama/llama_index#13753]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

hi,

i just wanna if the split-results of one specific sentence will be the same if we instantiated two sentence-spliter with the same initial-args ?

looking forward to your reply 
best,

**Comment by logan-markewich** [comment]
@guangyuli-uoe it should be the same? Is there a case where its not?
