### ISSUE TITLE
[Bug]: I am not able to run the custom functioned agents as I am getting this error : AttributeError: 'str' object has no attribute 'message'

### ISSUE THREAD

**Issue by bhuvanweb3** [run-llama/llama_index#13770]
### Bug Description

I have made full pipeline of custom tools and used in agents, which was working fine 2 days ago. Now, It's not working.

### Version

0.10.39

### Steps to Reproduce

First create your custom tools
![image](https://github.com/run-llama/llama_index/assets/156995407/d26bcaae-a214-4628-95d3-82abaa0653fd)
After that, intilaize your agents
![image](https://github.com/run-llama/llama_index/assets/156995407/fa077de8-9dd0-42f3-84ff-c0728283ee02)

**Comment by logan-markewich** [comment]
Ah I see, just reproduced, its an issue with return direct

**Comment by bhuvanweb3** [comment]
This is why, I prefer Langchain agents over Llamaindex agents. Sorry for
being rude.
