### ISSUE TITLE
[BUG]: The instance variable response_mode of AutoPrevNextNodePostprocessor cannot use the constants TREE_SUMMARIZE or GENERATION.

### ISSUE THREAD

**Issue by minglu7** [run-llama/llama_index#13796]
![Snipaste_2024-05-29_14-16-40](https://github.com/run-llama/llama_index/assets/104314597/a6df92a6-9e38-4347-80f4-8f402473126f)
![Snipaste_2024-05-29_14-17-19](https://github.com/run-llama/llama_index/assets/104314597/55d1f2e3-de4d-4675-82c6-02de11c550fa)

![Snipaste_2024-05-29_14-17-33](https://github.com/run-llama/llama_index/assets/104314597/efa3482a-702b-4cc6-bcbf-ec92fab3a605)
          
@nerdai @logan-markewich 
The reason I am changing the default response mode to refine instead of tree_summarize is because the subsequent code needs to check if the response contains the words "next", "previous", or "none". In fact, if the tree_summarize response mode is used, the LLM will use the summarize prompt, and its returned response does not meet the requirements of the following method _parse_prediction, which means it does not contain "previous", "next", or "none", resulting in an error.
![image](https://github.com/run-llama/llama_index/assets/104314597/2b13b633-2480-4f91-b25a-56d02220d0bf)

I have attached actual debug test screenshots to give you a more intuitive view of the issue.
![1](https://github.com/run-llama/llama_index/assets/104314597/d1ae4e29-b7af-4b22-b14c-cdb69ac7966f)

_Originally posted by @minglu7 in https://github.com/run-llama/llama_index/pull/13771#discussion_r1618045552_

**Comment by logan-markewich** [comment]
I think this is just an issue for a specific case? You can still override the response mode in the constructor

The tree summarize prompt is nearly the same as the refine prompt fyi

**Comment by minglu7** [comment]
> I think this is just an issue for a specific case? You can still override the response mode in the constructor
> 
> 
> 
> The tree summarize prompt is nearly the same as the refine prompt fyi
@logan-markewich 
In the constructor of the `autoprevnextnodeprocessor` class, the default `prompt` templates: `textqa_template` and `tefine_template` are passed. If the `tree_summarize` or `generation` response modes are passed by default, these two parameters will not be used.

**Comment by logan-markewich** [comment]
You guys know you can change the mode in the constructor right? 

`AutoPrevNextNodePostprocessor(..., response_mode="compact")`

Or you could have made another PR? 😅 

Fixed in the above
