### ISSUE TITLE
[Bug]: Metadata length (236) is close to chunk size (256). Resulting chunks are less than 50 tokens. Consider increasing the chunk size or decreasing the size of your metadata to avoid this.

### ISSUE THREAD

**Issue by sarathsurpur** [run-llama/llama_index#13792]
### Bug Description

When ingesting the text chunks in to locally hosted qdrant db it throws this warnings message, and number of text chunks obtained increased exponentially. And its taking forever to ingest the data in to vector db.

### Version

0.9.19

### Steps to Reproduce

create text chunks with 256 token size of and ingesting this data in to vector db throws this message

**Comment by logan-markewich** [comment]
either decrease the amount of text you are putting into metadata, 

`document.metadata = {}`  (or some smaller subset)

or set the metadata excludes on your input nodes/documents.

`document.excluded_llm_metadata_keys = ["key1", ...]`
`document.excluded_embed_metadata_keys = ["key1", ...]`

Its taking forever beasuse its probably creating a ton of nodes 😓
