### ISSUE TITLE
[Bug]: KnowledgeGraphIndex not returning triplets in networkx when using documentation example

### ISSUE THREAD

**Issue by csaiedu** [run-llama/llama_index#13806]
### Bug Description

When running : https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/knowledge_graph2/

The networkx graph return is displayed blank. No triplet seem to be passed to the knowledge graph. 
The extract_triplet function seem incorrect: Replacing by hugging face recommended function for extraction works with logged debug showing triplers are extracted
> Extracted triplets: [{'head': 'Attention Mechanisms', 'type': 'subclass of', 'tail': 'attention mechanisms'}]

However, still nothing is returned when calling 
`g = index.get_networkx_graph()`

```
def extract_triplets(input_text):
    text = triplet_extractor.tokenizer.batch_decode(
        [
            triplet_extractor(
                input_text, return_tensors=True, return_text=False
            )[0]["generated_token_ids"]
        ]
    )[0]

    triplets = []
    relation, subject, relation, object_ = '', '', '', ''
    text = text.strip()
    current = 'x'
    for token in text.replace("<s>", "").replace("<pad>", "").replace("</s>", "").split():
        if token == "<triplet>":
            current = 't'
            if relation != '':
                triplets.append({'head': subject.strip(), 'type': relation.strip(),'tail': object_.strip()})
                relation = ''
            subject = ''
        elif token == "<subj>":
            current = 's'
            if relation != '':
                triplets.append({'head': subject.strip(), 'type': relation.strip(),'tail': object_.strip()})
            object_ = ''
        elif token == "<obj>":
            current = 'o'
            relation = ''
        else:
            if current == 't':
                subject += ' ' + token
            elif current == 's':
                object_ += ' ' + token
            elif current == 'o':
                relation += ' ' + token
    if subject != '' and relation != '' and object_ != '':
        triplets.append({'head': subject.strip(), 'type': relation.strip(),'tail': object_.strip()})
    return triplets

```

### Version

0.10.40

### Steps to Reproduce

Trying to run the referred code form the manual

**Comment by csaiedu** [comment]
This return an error. Within the initialisation of KnowledgeGraphIndex, which according to the suggestions are separated from the from_documents function call: ValueError: **One of nodes, objects, or index_struct must be provided.**

**Comment by csaiedu** [comment]
This is not helping

**Comment by logan-markewich** [comment]
@csaiedu your extract_triplets function is incorrect

It should be returning a list of tuples (`subject`, `relation`, `object`), not a list of dicts
