### ISSUE TITLE
[Question]: Multi-agent capability - using agents as tools for other agents

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#13821]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there an existing interface that permits readily exposing agents as tools for other agents, thereby establishing a readily available multi-agent capability?  Or, would it requiring defining a new ToolSpec?

FWIW, it appears [AutoGen](https://github.com/microsoft/autogen/pull/2816) is poised to address this in the near future for LlamaIndex.

**Comment by logan-markewich** [comment]
@brycecf maybe I'm missing something, but it should be as simple as wrapping an agent into a function tool? 

Of course, there could always be a helper for this too, `agent.as_tool()` oe something, but setting up a function tool is also straightforward and easy to customize
