### ISSUE TITLE
[Bug]: OpenAI max_retries not working

### ISSUE THREAD

**Issue by vignesh-arivazhagan** [run-llama/llama_index#13826]
### Bug Description

I mentioned max_retries as 1, but i am getting 5 retries always
![image](https://github.com/run-llama/llama_index/assets/133187870/0ea914a4-e768-45a4-8bcd-e652ff20fc07)

### Version

0.10.34

### Steps to Reproduce

execute the below code

```python
from llama_index.llms.openai import OpenAI

llm = OpenAI(
    api_key=os.getenv("OPEN_AI_API_KEY"),
    model="gpt-3.5-turbo",
    timeout=0.1,
    max_retries=1
)

llm.complete("hi")
```

**Comment by RussellLuo** [comment]
I found that there are two retry mechanisms for `OpenAI`.

The first one is he `max_retries` parameter, which is [supported by the `openai-python` library](https://github.com/openai/openai-python#retries):

https://github.com/run-llama/llama_index/blob/b18470a6b3c415a32265dcb19ac0d2b24706325d/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L189

And the second one is the `@llm_retry_decorator` decorator, which was introduced by #11867:

https://github.com/run-llama/llama_index/blob/b18470a6b3c415a32265dcb19ac0d2b24706325d/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L80-L86

The above two mechanisms will operate separately, thus the retry count will increase.

@logan-markewich To my understanding, the `@llm_retry_decorator` decorator is not necessary here. Maybe we should remove this decorator, thoughts?

**Comment by logan-markewich** [comment]
@RussellLuo tbh, I'd rather keep the retry decorator, it's better and more customizable  than what the openai client is doing

**Comment by RussellLuo** [comment]
> ..., it's better and more customizable than what the openai client is doing

Agreed. Then maybe it's better to pass `max_retries` as a parameter to the decorator (instead of openai client)?

**Comment by ngu-khoi** [comment]
@logan-markewich Is there a way to disable the retry behavior or at least call the openai client without retries? the retry decorator looks good, but as implemented isn't customizable and is restrictive

For context I have custom retry behavior and i need to be able to catch the openai error directly, but looks like another error is being raised - tenacity client raises an error that's not handled correctly after max retries? i was just updating library to use the gpt4o model and saw the retry warnings despite setting it to 0, so i'm still reading if what im seeing is just an unrelated issue. even then, i don't want retries

![CleanShot 2024-06-02 at 14 20 04@2x](https://github.com/run-llama/llama_index/assets/85835085/3d4c61be-46d6-4ad2-9356-871a5bec5a93)
