### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Banjomaestro** [run-llama/llama_index#13834]
### Bug Description

The 
    vector_store = TimescaleVectorStore.from_params(
    service_url=TIMESCALE_SERVICE_URL,
    table_name=namespace,
    )
function from llama-index-time-scale-vector package doesnt work anymore and returns 

Python(50484,0x7ff845a3d7c0) malloc: *** error for object 0x16: pointer being freed was not allocated
Python(50484,0x7ff845a3d7c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6

### Version

llama-index==0.10.40

### Steps to Reproduce

just use the function, I am on mac intel. 

### Relevant Logs/Tracbacks

```shell
Python(50484,0x7ff845a3d7c0) malloc: *** error for object 0x16: pointer being freed was not allocated
Python(50484,0x7ff845a3d7c0) malloc: *** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by logan-markewich** [comment]
@Banjomaestro this seems like an issue with either your env or the [timescale vector store package](https://github.com/timescale/python-vector). Maybe you are missing some core libraries (i.e. not python libraries, but system libraries) on the machine you are running on?

It works fine on google colab
https://colab.research.google.com/drive/1krUnNZ6q47B0KoCkTAIWdE9t-oVaIUd5?usp=sharing
