### ISSUE TITLE
[Question]: SmartPDFLoader does not work as a file_extractor

### ISSUE THREAD

**Issue by chewbm05** [run-llama/llama_index#13846]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

file_path = "Armenia - Croatia Treaty.pdf"
loader = SmartPDFLoader(llmsherpa_api_url = llmsherpa_api_url )
docs = loader.load_data(file_path)

This would work. However, when I load SmartPDFLoader as a file_extractor:

pdf_reader = SmartPDFLoader(llmsherpa_api_url = llmsherpa_api_url)
file_extractor = {".pdf": pdf_reader}
reader = SimpleDirectoryReader(input_files=[file_path],
                               required_exts=[".pdf"],
                                file_extractor=file_extractor)
documents = reader.load_data()
Failed to load file Armenia - Croatia Treaty.pdf with error: 'WindowsPath' object has no attribute 'decode'. Skipping...

Why is this so? The purpose of using SimpleDirectoryReader is so I can load the files in a directory recursively.
Please help!

**Comment by logan-markewich** [comment]
@chewbm05 the pdf reader class just isn't handling the path objects that simple directory reader passes in. Easy bug fix in a pr

**Comment by chewbm05** [comment]
Thanks! I managed to do a workaround by creating a class based on SimpleDirectoryReader:

class CustomSimpleDirectoryReader(SimpleDirectoryReader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def load_data(self):
        documents = []
        for input_file in self.input_files:
            input_file_str = str(input_file)  # Ensure the path is a string
            try:
                doc = self.file_extractor[".pdf"].load_data(input_file_str)
                documents.extend(doc)
            except Exception as e:
                print(f"Failed to load file {input_file} with error: {e}. Skipping...")
        return documents

**Comment by chewbm05** [comment]
However, this poses another issue:

# Use the CustomSimpleDirectoryReader
reader = CustomSimpleDirectoryReader(
    input_dir=data_path,
    required_exts=[".pdf"],
    file_extractor=file_extractor,
    recursive=True
)

# Load documents
documents = reader.load_data()
Failed to load file [C:\Users\chewb\DTA\data\Countries_samples\Armenia\Armenia-Cyprus](file:///C:/Users/chewb/DTA/data/Countries_samples/Armenia/Armenia-Cyprus) Treaty.pdf with error: No host specified.. Skipping...
Failed to load file [C:\Users\chewb\DTA\data\Countries_samples\Armenia\ArmeniaCroatiaTreaty.pdf](file:///C:/Users/chewb/DTA/data/Countries_samples/Armenia/ArmeniaCroatiaTreaty.pdf) with error: No host specified.. Skipping...

Does anyone know what the issue is?

**Comment by logan-markewich** [comment]
@chewbm05 I think you need to specify the `llmsherpa_api_url` ? (I have no idea how this reader works)
