### ISSUE TITLE
[Bug]: Graph Index with Azure OpenAI is impossible to query

### ISSUE THREAD

**Issue by aganiezgoda** [run-llama/llama_index#13842]
### Bug Description

I've been mostly following this tutorial: https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_basic/#querying

```
llm = AzureOpenAI(
    engine="chat2",
    model="gpt-35-turbo-16k",
    temperature=0.0,
    azure_endpoint="https://xxx.openai.azure.com/",
    api_key="xxx",
    api_version="2023-07-01-preview",
)

embeddings = AzureOpenAIEmbedding(
    engine = "text-embedding-ada-002",
    model = "text-embedding-ada-002",
    azure_endpoint="https://xxx.openai.azure.com/",
    api_key="xxx", 
    api_version="2023-12-01-preview",
    )

index = PropertyGraphIndex.from_documents(
    documents,
    llm = llm,
    embed_model=embeddings,
    show_progress=True,
    graph_store=SimplePropertyGraphStore() 
)
```
The graph is created - I can display it. I've also checked whether the connection is correct by using "llm" and "embeddings" for response generation/ embedding generation respectively and both return valid responses.

However, when I add the following code to the mix, it starts failing:

```
retriever = index.as_retriever(
    include_text=False, 
)

nodes = retriever.retrieve("What happened at Interleaf and Viaweb?")

for node in nodes:
    print(node.text)
```

The error message returned:

```
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 9f*************a847. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}} 
```

It seems to be still trying to connect to OpenAI instead of Azure OpenAI. Why is that and how to counteract it?

### Version

0.10.40

### Steps to Reproduce

Code is included in the bug description

**Comment by logan-markewich** [comment]
Hmm, it might not be passing the embeddings from the parent index properly

Try this is a workaround: `index.as_retriever(...., embed_model=embeddings)`
