### ISSUE TITLE
[Bug]: minor doc issue with MLX

### ISSUE THREAD

**Issue by namin** [run-llama/llama_index#13851]
### Bug Description

The README here: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/llms/llama-index-llms-mlx
as well as the the in-code example here: https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-mlx/llama_index/llms/mlx/base.py#L81
say to have the parameter `tokenizer_name=...`, but the code actually rejects such a parameter, and fills it itself with the `model_name`.

Once I removed this parameter, everything seems to work! I am happy to send a pull request to update the README and the doc snippet, or perhaps you're envisioning another fix. Just let me know. Thanks!

### Version

main

### Steps to Reproduce

`pip install llama-index-llms-mlx`
then try
```
from llama_index.llms.mlx import MLXLLM

llm = MLXLLM(
    model_name="microsoft/phi-2",
    tokenizer_name="microsoft/phi-2",
    context_window=3900,
    max_new_tokens=256,
    generate_kwargs={"temp": 0.7, "top_p": 0.95},
)

response = llm.complete("What is the meaning of life?")
print(str(response))
```
like in the README https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/llms/llama-index-llms-mlx

### Relevant Logs/Tracbacks

```shell
llm = MLXLLM(
          ^^^^^^^
TypeError: MLXLLM.__init__() got an unexpected keyword argument 'tokenizer_name'
```
```

**Comment by logan-markewich** [comment]
Yea lets just update the docs to remove mention of that param 🙏🏻
