### ISSUE TITLE
[Bug]: index.ref_doc_info does not work with chromadb

### ISSUE THREAD

**Issue by Rust-Ninja-Sabi** [run-llama/llama_index#13860]
### Bug Description

Using index.ref_doc_info does not work with chromadb. You receive an error.

### Version

0.10.41

### Steps to Reproduce

Start index.ref_doc_info

### Relevant Logs/Tracbacks

```shell
**none**
```

**Comment by Rust-Ninja-Sabi** [comment]
@dosu When will it work with Chromadb? I use llama index to have one api for all available stores. But as far as I understand document management is not available for chromadb. Is ist available for any Vector database? Thanks.

**Comment by Rust-Ninja-Sabi** [comment]
@dosu vector_store.get_notes() is not implemented. Can you show me the query to get all nodes? Thanks.

**Comment by digglife** [comment]
> [@Rust-Ninja-Sabi](https://github.com/Rust-Ninja-Sabi) this is correct. `ref_doc_info` relies on having a docstore, but most vector dbs disable the docstore because they are storing all the nodes in the vector db (simplifies storage)
> 
> I'd recommend using an ingestion pipeline with a vector store and docstore attached
> 
> ```
> pipeline = IngestionPipeline(
>   transformations=[SentenceSplitter(), OpenAIEmbedding()], 
>   docstore=docstore, 
>   vector_store=vector_store
> )
> 
> pipeline.run(documents=documents)
> ```
> 
> https://docs.llamaindex.ai/en/stable/module_guides/loading/ingestion_pipeline/?h=ingestion

Thanks. It helps.
