### ISSUE TITLE
[Bug]: Connection with chromadb (ChromaVectorStore) returns a type error

### ISSUE THREAD

**Issue by aganiezgoda** [run-llama/llama_index#13885]
### Bug Description

I've been trying to persist the vector part of my property graph.

```
from llama_index.core.graph_stores import SimplePropertyGraphStore
from llama_index.vector_stores.chroma import ChromaVectorStore
import chromadb

client = chromadb.PersistentClient("./chroma_db")
collection = client.get_or_create_collection("my_graph_vector_db")

index = PropertyGraphIndex.from_documents(
    documents,
    embed_model=OpenAIEmbedding(model_name="text-embedding-3-small"),
    graph_store=SimplePropertyGraphStore(),
    vector_store=ChromaVectorStore(collection=collection),
    show_progress=True,
)

index.storage_context.persist(persist_dir="./storage")

The error reads:

```
client = chromadb.HttpClient(host=host, port=port, ssl=ssl, headers=headers)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\.venv\Lib\site-packages\chromadb\__init__.py", line 178, in HttpClient
    port = int(port)
           ^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```
```

### Version

0.10.40

### Steps to Reproduce

See above.

**Comment by logan-markewich** [comment]
@aganiezgoda you have a typo

`vector_store = ChromaVectorStore(chroma_collection=collection)` 

Although, I think `ChromaVectorStore` needs to be updated to handle duplicate IDs 🤔 (I got some error about that)

**Comment by aganiezgoda** [comment]
> (chroma_collection=collection)

Do you mean (collection=collection) should be (chroma_collection=collection)?

I've tried both and it neither works.

**Comment by logan-markewich** [comment]
@aganiezgoda worked fine for me here
https://colab.research.google.com/drive/1tLBvXNYbX_yK_6pJNwwPb5xpFi9Z3Nsk?usp=sharing

**Comment by aganiezgoda** [comment]
> @aganiezgoda worked fine for me here https://colab.research.google.com/drive/1tLBvXNYbX_yK_6pJNwwPb5xpFi9Z3Nsk?usp=sharing

I'm receiving:
```
storage_context.vector_store = vector_store
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: property 'vector_store' of 'StorageContext' object has no setter
```
The only difference vs. what you do is: I'm using the Azure versions of the embedding and llm model. So it's actually:

```
llm = AzureOpenAI(
    engine="xxx",
    model="gpt-35-turbo-16k",
    temperature=0.0,
    azure_endpoint="https://xx.openai.azure.com/",
    api_key="xxxx",
    api_version="2023-07-01-preview",
)

embeddings = AzureOpenAIEmbedding(
    engine = "xxx",
    model = "text-embedding-ada-002",
    azure_endpoint="https://xxx.openai.azure.com/",
    api_key="xxx", 
    api_version="2023-12-01-preview",
    )

index = PropertyGraphIndex.from_documents(
    documents,
    embed_model=embeddings,
    llm = llm,
    graph_store=SimplePropertyGraphStore(),
    vector_store=ChromaVectorStore(collection=collection),
    show_progress=True,
)
```


It works when I don't persist the graph and vector so it should make no difference.

**Comment by logan-markewich** [comment]
Update your library, this error was fixed 

`pip install -U llama-index-core`

**Comment by aganiezgoda** [comment]
The update solves the issue.
