### ISSUE TITLE
Can not load StorageContext on 0.6.0alpha1 and older ver

### ISSUE THREAD

**Issue by yudataguy** [run-llama/llama_index#1388]
documentation: https://gpt-index.readthedocs.io/en/latest/guides/primer/usage_pattern.html#reusing-nodes-across-index-structures

`can not load StorageContext`

Error:
```
ImportError: cannot import name 'StorageContext' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)
```

I also tried `from llama_index.storage.storage_context import StorageContext`

Error:
```
ModuleNotFoundError: No module named 'llama_index.storage'
```

Also, the documentation is outdated, ref: https://gpt-index.readthedocs.io/en/latest/reference/storage.html

**Comment by smbanaie** [comment]
you can update the llamaindex version to 6 (pip install llama-index==0.6.0a3)

**Comment by abhilashahyd** [comment]
This error got solved for me by installing - pip install llama-index==0.6.2
