### ISSUE TITLE
[Question]: Recommended method to build a stable Docker image with Llamaindex

### ISSUE THREAD

**Issue by c64er4ever** [run-llama/llama_index#13887]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,
I am building a docker image for a prod environment, containing Llama-index core and some integration modules (embeddings, postprocessors etc.). I am specifying in requirements.txt the exact version that I need for every module, in order to build a consistent and stable version. However, I have discovered that in some cases, pre-requisites in these integration modules are being modified without bumping a version. So, for example, I might use llama-index-embeddings-cohere 0.1.6, which required llama-index-core 0.10.38 till yesterday, and then the next day it requires llama-index-core 0.10.41. This is causing my version to be non-consistent and possibly unstable. What is the recommended way to work in order to avoid this issue?
Maybe it would be better if every time such pre-requisite is changed, a version for that module is bumped as well?
Thanks
Guy

**Comment by c64er4ever** [comment]
@dosu here is an example where prerequisites were modified without a version bump: https://github.com/run-llama/llama_index/commit/54b08c9c55d62ce5937bbb18cb928d3883b1b534

**Comment by logan-markewich** [comment]
@c64er4ever pretty confused how that happened

The same version of a package cannot have changing requirements, versions published to pypi are static 🤔

In any case, specifying exact versions is the way to do. I can only think a req that you didn't have pinned updated
