### ISSUE TITLE
[Documentation]: Property Graph Index

### ISSUE THREAD

**Issue by tituslhy** [run-llama/llama_index#13900]
### Documentation Issue Description

1. The second last cell of the documentation should be "chroma_collection=collection" and not "collection=collection"
2. I was following the code using an open-sourced tool stack - I was using Groq's LLaMA3 70Bn as my LLM and the "BAAI/bge-small-en" embeddings model. When executing the same cell in point 1 (i.e. the creation of the property graph index using chroma as the vectorDB), I got a "DuplicateIDError" raised by ChromaDB. I think there might be something wrong with the interaction of the graph and vector stores?

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/property_graph/property_graph_basic/

**Comment by tituslhy** [comment]
When testing with qdrant (I enabled hybrid search on this) I got a different error:

```
UnexpectedResponse: Unexpected Response: 400 (Bad Request)
Raw response content:
b'{"status":{"error":"Format error in JSON body: value Paul graham is not a valid point ID, valid values are either an unsigned integer or a UUID"},"time":0.0}'
```

Can I check if this is related?

Here's how I defined my qdrant vector store:
```
from llama_index.vector_stores.qdrant import QdrantVectorStore
from qdrant_client import QdrantClient, AsyncQdrantClient

client = QdrantClient(host="localhost", port=6333)
aclient = AsyncQdrantClient(host="localhost", port=6333)
vector_store = QdrantVectorStore(
    collection_name = "graph_collection",
    client = client,
    aclient = aclient,
    enable_hybrid = True,
    batch_size = 20
)
```

**Comment by tituslhy** [comment]
Sorry @logan-markewich I'm still facing the same error but the issue has been marked as closed. I did see that the files on the main branch have been updated and I did pip install -U llama-index just in case.

**Comment by logan-markewich** [comment]
@tituslhy try updating again, it should be relased (the prs close issues on merge, but sometimes it can take a day or two to release, especially changes in core)
