### ISSUE TITLE
[Question]:  If manually adding nodes and triplets, what is the role of the chunk of text encapsulated in node?

### ISSUE THREAD

**Issue by EXJUSTICE** [run-llama/llama_index#13909]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[In the tutorial](https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/KnowledgeGraphDemo/#optional-try-building-the-graph-and-manually-add-triplets) on the construction and use of Knowledge Graphs in LLamaIndex, there is a section on building the graph and manually adding triplets, which was very useful, but a few questions arose from it.

- If we use a NodeParser from a document to generate nodes, and add our own triplets that in no-way represent the chunk (i.e. the chunk talks about programming, we add a triplet("people", "love", "ice-cream"), how would be reflected in graph indexing and querying? Querying would only be based on the triplets, and the underlying text is ignored, correcT?
- The networkx visualizations do not represent the nodes, but triplets, correct? The author adds two separate parsed nodes (indexed as 0 and 1). In the visualization, these would show up as two triplets. If one instead kept adding triplets to the same node (the docs state if Node already exists, only triplet will be added), we would still see more triplets, possibly connected or not, but all would be associated to the same underlying TextNode?

**Comment by logan-markewich** [comment]
There is a mode in the KnowledgeGraphIndex retriever (`include_text=True`) where the text source for matching triplets is used during a query instead of the triplets themselves

This is usually desirable, because triplets alone typically lack a lot of context
