### ISSUE TITLE
[Question]: Could we add OpenSearch to the DocStore and IndexStore catalog?

### ISSUE THREAD

**Issue by kobiche** [run-llama/llama_index#13907]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Analogous to MongoDB, I see OpenSearch as a potential DB for storing and querying nodes. Llama-index already supports OpenSearch as VectorStore and thus save node information (text, metadata, etc.). So, why not use it as docstore or indexstore?

**Comment by logan-markewich** [comment]
Sure, someone just needs to make a contribution for it :)
