### ISSUE TITLE
[Question]: Which similarity Metric is used to retrieve Chunks in RAG operations

### ISSUE THREAD

**Issue by JMT800** [run-llama/llama_index#13913]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was facing a similar issue to the one reported #12461 .

I am performing a RAG operation using the default vector store stored locally and i am getting less relevant nodes retrieved as a result. For instance, when in the answer, it is stated that the query is "out of context" and no relevant documents could be found, the RAG operation is retrieving chunks from the vector store.

I am using llama version: 0.9.40.

Hence i had the following questions in mind:

-  what is the distance metric used to measure the similarity between the chunks and the query with the default vector store? can we change it ?
- why does it also provide "high" similarity scores (around 0.7) for non relevant queries, even when trying nonsensical queries like "aaaaaa a a a"? (cause this complicates the use of the threshold_cutoff attribute within the optimizer.)
- Also, what is the default prompt used when performing the RAG operation ? how does it take into incorporate the retrieved chunks?

cheers & thanks in advance

**Comment by AnasKhan-12** [comment]
how does the similarity metric depend on the embedding model being used?
