### ISSUE TITLE
[Feature Request]: Support AWS Bedrock Converse API for tool use (function calling) and conversational history / memory in FunctionCallingAgentWorker

### ISSUE THREAD

**Issue by alecl** [run-llama/llama_index#13921]
### Feature Description

Anthropic, Mistral, and Cohere have specific tool use API conventions that improve their success rate and reduce hallucinations and chat history formats. The AWS Bedrock Converse API abstracts those differences, allowing easier switching and usage between the models on AWS Bedrock.

> This API also simplifies managing multi-turn conversations by enabling developers to provide conversational history in a structured way as part of the API request. Converse API supports Tool use (function calling), for supported models (Anthropic's Claude 3 model family including Claude 3 Opus, Claude 3 Sonnet, and Claude 3 Haiku; Mistral Large; and Cohere’s Command R and R+).

https://aws.amazon.com/about-aws/whats-new/2024/05/amazon-bedrock-new-converse-api/

https://docs.aws.amazon.com/bedrock/latest/userguide/tool-use.html

### Reason

LlamaIndex has Anthropic specific tool usage but that doesn't carry over to usage through AWS Bedrock which has risen significantly in popularity as a serverless model platform.

Using just the ReAct Agent built into LllamaIndex is more prone to hallucinations than direct tool support.

Instead, allowing the LlamaIndex [FunctionCallingAgentWorker](https://github.com/run-llama/llama_index/blob/75289a212a1b00787f1fddf29be2a6f01c3a8159/llama-index-core/llama_index/core/agent/function_calling/step.py#L83) to support the Bedrock Converse API is expected to improve the success of agent tasks and the flexibility of switching between Bedrock LLMs.

### Value of Feature

Supporting a variety of model providers and full feature support makes LlamaIndex a more valuable ecosystem. Otherwise, people will have to build outside of it to get the optimal agentic / tool-use experience.

**Comment by alecl** [comment]
This was brought up in #13707 by @titusly and @logan-markewich

**Comment by AndreCNF** [comment]
I'm trying to integrate this Converse API through this PR https://github.com/run-llama/llama_index/pull/14055. I'll be grateful for any help to get this through! 🙏

**Comment by AndreCNF** [comment]
> I'm trying to integrate this Converse API through this PR #14055. I'll be grateful for any help to get this through! 🙏

My PR is now ready for review. It's working in my tests ✅

**Comment by ryann-sportsbet** [comment]
@AndreCNF  I'm trying to install llama-index-llms-bedrock-converse but I got this error 
`ERROR: Could not find a version that satisfies the requirement llama-index-llms-bedrock-converse (from versions: none)
ERROR: No matching distribution found for llama-index-llms-bedrock-converse
WARNING: There was an error checking the latest version of pip.
`

Also, will it work with Sonnet model?

**Comment by AndreCNF** [comment]
> Also, will it work with Sonnet model?

Yes ✅ It should work on the following models:

- `amazon.titan-text-express-v1`
- `amazon.titan-text-lite-v1`
- `amazon.titan-text-premier-v1:0`
- `anthropic.claude-instant-v1`
- `anthropic.claude-v1`
- `anthropic.claude-v2`
- `anthropic.claude-v2:1`
- `anthropic.claude-3-sonnet-20240229-v1:0`
- `anthropic.claude-3-haiku-20240307-v1:0`
- `anthropic.claude-3-opus-20240229-v1:0`
- `ai21.j2-mid-v1`
- `ai21.j2-ultra-v1`
- `cohere.command-text-v14`
- `cohere.command-light-text-v14`
- `cohere.command-r-v1:0`
- `cohere.command-r-plus-v1:0`
- `meta.llama2-13b-chat-v1`
- `meta.llama2-70b-chat-v1`
- `meta.llama3-8b-instruct-v1:0`
- `meta.llama3-70b-instruct-v1:0`
- `mistral.mistral-7b-instruct-v0:2`
- `mistral.mixtral-8x7b-instruct-v0:1`
- `mistral.mistral-large-2402-v1:0`
- `mistral.mistral-small-2402-v1:0`

But only these support function calling:
- `anthropic.claude-3-sonnet-20240229-v1:0`
- `anthropic.claude-3-haiku-20240307-v1:0`
- `anthropic.claude-3-opus-20240229-v1:0`
- `cohere.command-r-v1:0`
- `cohere.command-r-plus-v1:0`
- `mistral.mistral-large-2402-v1:0`
