### ISSUE TITLE
[Question]: Is there a threshold when we use knowledge graph index to extract entities

### ISSUE THREAD

**Issue by DataNoob0723** [run-llama/llama_index#13922]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a threshold when we use knowledge graph index to extract entities?

**Comment by logan-markewich** [comment]
You might have to give me info here

What code/modules are you using? Do you mean a prediction threshold?

**Comment by DataNoob0723** [comment]
> You might have to give me info here
> 
> What code/modules are you using? Do you mean a prediction threshold?

I am using KnowledgeGraphIndex, I am wondering is there any threhold this functions uses when extracting entities for the knowledge graph.

**Comment by logan-markewich** [comment]
its using the LLM to extract, so there is no threshold. Just an LLM outputting text that is then parsed
