### ISSUE TITLE
[Question]: Image from Readme not embedded in LlamaHub page

### ISSUE THREAD

**Issue by ossaleon** [run-llama/llama_index#13932]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone! recently we added [WordLift Vector Store](https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/vector_stores/llama-index-vector-stores-wordlift) to the integrations. Checking the [LlamaHub page of the WordLift Vector Store](https://llamahub.ai/l/vector_stores/llama-index-vector-stores-wordlift?from=) I noticed that the logo from the readme is not rendered. How can I fix this?

**Comment by logan-markewich** [comment]
I suggest linking to a publicly hosted image instead -- llamahub is just pulling readmes from the GitHub repo, pulling images as well would be quite a bit more complex 😅
