### ISSUE TITLE
[Bug]: KVDocumentStore generates many duplicate Node_IDs in ref_doc_info collection for both Redis and Mongo docstore

### ISSUE THREAD

**Issue by RainDong911** [run-llama/llama_index#13945]
### Bug Description

When I followed the examples on llamaindex document site - https://docs.llamaindex.ai/en/stable/examples/docstore/MongoDocstoreDemo/ , it always generated many duplicated node_ids in ref_doc items of ref_doc_info collection, when creating summary_index/vectorstore_index and keyword_table_index based on same document. 

### Version

llama-index-storage-docstore-mongodb - 0.1.3

### Steps to Reproduce

Just follow the examples in https://docs.llamaindex.ai/en/stable/examples/docstore/MongoDocstoreDemo/ or RedisDocStoreDemo, this will reproduce.  It seems like below function in KVDocumentStore just extend the node_ids list, without considering duplicated node_ids. 

    def _merge_ref_doc_kv_pairs(self, ref_doc_kv_pairs: dict) -> List[Tuple[str, dict]]:
        merged_ref_doc_kv_pairs = []
        for key, kv_pairs in ref_doc_kv_pairs.items():
            merged_node_ids = []
            metadata = {}
            for kv_pair in kv_pairs:
                merged_node_ids.extend(kv_pair[1].get("node_ids", []))
                metadata.update(kv_pair[1].get("metadata", {}))
            merged_ref_doc_kv_pairs.append(
                (key, {"node_ids": merged_node_ids, "metadata": metadata})
            )

        return merged_ref_doc_kv_pairs

So I added  <merged_node_ids = list(dict.fromkeys(merged_node_ids))> after <merged_node_ids.extend(kv_pair[1].get("node_ids", []))>, which seemed being able to get rid of this issue.

**Comment by logan-markewich** [comment]
I'm not 100% sure what you mean here. Can you give some code to replicate?

For example, I did this:

```python
from llama_index.core import Document
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.storage.docstore import SimpleDocumentStore

documents = [Document(text="as it was told "*1000), Document(text="once upon a time "*1000), Document(text="in a land far away "*1000)]

nodes = SentenceSplitter(chunk_size=256, chunk_overlap=20)(documents)   

docstore = SimpleDocumentStore()
docstore.add_documents(nodes)

print(docstore._kvstore._data["docstore/ref_doc_info"])
```

but  seemed fine to me, no duplicates

**Comment by RainDong911** [comment]
I mean the MongoDocumentStore and RedisDocumentStore, which both inherit from KVDocumentStore. Below example can reproduce it,

from llama_index.core import SimpleDirectoryReader, StorageContext
from llama_index.core import SummaryIndex
from llama_index.core.node_parser import SentenceSplitter

reader = SimpleDirectoryReader("./data/paul_graham/")
documents = reader.load_data()
nodes = SentenceSplitter().get_nodes_from_documents(documents)
len(nodes)

MONGO_URI = "mongodb://xxxxxx:27017/"
DB_NAME = "docsdb"

from llama_index.storage.docstore.mongodb import MongoDocumentStore
from llama_index.storage.index_store.mongodb import MongoIndexStore

storage_context = StorageContext.from_defaults(
    docstore=MongoDocumentStore.from_uri(uri=MONGO_URI, db_name=DB_NAME),
    index_store=MongoIndexStore.from_uri(uri=MONGO_URI, db_name=DB_NAME),
)

storage_context.docstore.add_documents(nodes)
summary_index = SummaryIndex(nodes, storage_context=storage_context)

**Comment by logan-markewich** [comment]
@RainDong911 simple document store should reproduce it too though, they all inherit from kvdocumentstore 🤔 

I'll try and use mongodb I guess

**Comment by RainDong911** [comment]
Before creating the summary_index, there has no duplicate. While creating summary index will invoke the add_documents again and cause duplication in ref_doc_info collection's node_ids list. This does not cause duplication in data or metadata collections.
