### ISSUE TITLE
get_networkx_graph() from KnowledgeGraphIndex is not working 

### ISSUE THREAD

**Issue by nikhitaKanoj** [run-llama/llama_index#13949]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to visualize the entire document in the form of knowledge graph , 
for this i am using KnowledgeGraphIndex(0 from llama index : https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/KnowledgeGraphDemo/

I am getting answers for the query asked but when i try to visualize it using : 
from pyvis.network import Network
g = index.get_networkx_graph()
and then i use g in networkx to draw the graph .

But Issue is , the get_networkx_graph() is not giving the relevant nodes , 
the output for g.nodes() is : NodeView(("subject','object','alice','bob','cofffee shop')) , my document is large so it should have lot of nodes, but only these nodes will be displayed .

This is how I am constructing Knwoledge Index : 
from llama_index.core import StorageContext
graph_store = SimpleGraphStore()
storage_context = StorageContext.from_defaults(graph_store=graph_store)
index = KnowledgeGraphIndex.from_documents(
    documents,
    max_triplets_per_chunk=2,
    storage_context=storage_context,
)

How can I visualize my entire document as nodes and edges (relations between nodes) in the form of knowledge graph ?

**Comment by csaiedu** [comment]
Same unresolve issue as https://github.com/run-llama/llama_index/issues/13806?

**Comment by nikhitaKanoj** [comment]
@dosu , you gave the same solution as I have already tried , Kindly help me to resolve the issue with get_networkx_graph() method , 
It does work for me with openAI LLms and Huggingface API called LLMs  ,
I am using Zephyr locally in Jupyter Notebook , I am not getting it .
The entire code is same , just the LLMs are different , not sure what is the exact issue

**Comment by csaiedu** [comment]
Have you tried the new PropertyGraphIndex. It works for Ollama, had to go down that route, not sure if KnowledgeGraphIndex is getting much traction from Llamaindex?

**Comment by nikhitaKanoj** [comment]
@csaiedu , yea i tried using it , got import errors ..did you manage to get results using PropertyGraphIndex ?

**Comment by csaiedu** [comment]
Yes that works fine with Ollama on the tutorial examples, make sure to install the newest llama index libraries.

**Comment by logan-markewich** [comment]
It could be that zephyr is not properly extracting any triplets here. This is the initial code the index is running to get the data needed to build the nx graph

```
subjs = list(index.index_struct.table.keys())

# add edges
rel_map = index._graph_store.get_rel_map(subjs=subjs, depth=1, limit=limit)
```

You could try running that and see what the resulting rel map looks like

knowledge graph index is basically on life support right now, since the property graph index was introduced (and the property graph index is a way better design imo)

**Comment by quartermaine** [comment]
@dosubot

I am using the code you provided (see below) and I am getting a totally irrelevant graph

** Code

```
from pyvis.network import Network

g = index.get_networkx_graph(limit=500)
net = Network(notebook=True, 
              cdn_resources="remote",
              directed=True
              )

net.from_nx(g)
net.save_graph("my_graph.html")

from IPython.display import HTML
HTML(filename="my_graph.html")
```

**Comment by quartermaine** [comment]
@dosubot

I am using the following code with the **KnowledgeGraphIndex** how to change the code to use the **PropertyGraphIndex**

**Code**

```
from llama_index.core import (
    SimpleDirectoryReader,
    KnowledgeGraphIndex,
    StorageContext,
    ServiceContext,
)
from llama_index.core import Document

from llama_index.core import StorageContext

from llama_index.core.graph_stores import SimpleGraphStore

from llama_index.core import Settings


Settings.llm = llm

Settings.chunk_size = 512

graph_store = SimpleGraphStore()

storage_context = StorageContext.from_defaults(graph_store=graph_store)

llama_documents = [Document(page_content=text,
                           doc_id="unique_document_id"
                           )
]

index = KnowledgeGraphIndex.from_documents(
    llama_documents,
    max_triplets_per_chunk=10,
    storage_context=storage_context,
    
)

query_engine = index.as_query_engine(
    include_text=True,
    response_mode="tree_summarize",
    embedding_mode="hybrid",
    similarity_top_k=5,
)

response = query_engine.query(
    "Explain me ...?",
)

```
