### ISSUE TITLE
[Bug]: While using the AzureAIVectorStore for retrieval options via existing index, it's failing due to "the JSON object must be str, bytes or bytearray, not dict"

### ISSUE THREAD

**Issue by techthiyanes** [run-llama/llama_index#13967]
### Bug Description

The below details are related to vector store config:

vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    filterable_metadata_field_keys=metadata_fields,
    index_management=IndexManagement.VALIDATE_INDEX,
    id_field_key="id",
    chunk_field_key="content",
    embedding_field_key="content_vector",
    embedding_dimensionality=1536,
    metadata_string_field_key="metadata",
    doc_id_field_key="id",
)

### Version

Recent version

### Steps to Reproduce

1) We are using managed services option to ingest our data into Azure Indexes. The current class might require few changes on the code. So we have utilized the Azure Index API calls to ingest the documents.
2) While using the above config via existing index options, the above error message is popping up at while asking the query.
3) Earlier I have used the search index key, using the keys ingested the document then did search. This was working. 
4) Now we have search options via defaultazurekeycredentials.Using the existing index options, we are unable to retrieve the results.

**Comment by techthiyanes** [comment]
Ingested metadata is already dict but the vector retriever is working from e2e flow since ingesting to retrieval if we pass keys.
Here I have ingested data into Azure Indexes using managed identity options but for an existing index, still i'm getting the same error.
My config:

![image](https://github.com/run-llama/llama_index/assets/25921035/8d178bee-5ba2-4fef-83d9-29e35b441074)

**Comment by logan-markewich** [comment]
@techthiyanes if you have the full traceback, that would be more helpful

**Comment by techthiyanes** [comment]
I'm able to connect the existing vector store after making metadata as string where metadata object called as json.dumps
