### ISSUE TITLE
[Question]: llama-index-embeddings-huggingface without torch and cudnn librarires

### ISSUE THREAD

**Issue by pavluka6** [run-llama/llama_index#13975]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a way to install [llama-index-embeddings-huggingface](https://pypi.org/project/llama-index-embeddings-huggingface/) without installing large torch and nvidia cudnn libraries?

My embedding functions will be called from external API and thus I don't need to have these bloated libraries and packages on my deployment server.

**Comment by logan-markewich** [comment]
@pavluka6 the latest version does not include torch or cuda
https://colab.research.google.com/drive/1YaH_Y99RKFHk9YvEqJjRYqdz3qg_0eIJ?usp=sharing

**Comment by pavluka6** [comment]
You are right. This was infact issue due to llama-index-embeddings-huggingface, and I only want to use HuggingFaceInferenceAPIEmbedding. 

Here it installs all the mentioned libraries above.

Sorry once again for the confusion

**Comment by pavluka6** [comment]
Any updates on this, besides rewriting the entire HuggingFaceAPI?

**Comment by logan-markewich** [comment]
@pavluka6 

https://github.com/run-llama/llama_index/pull/14013
