### ISSUE TITLE
Elasticsearch embedding retireval issue

### ISSUE THREAD

**Issue by chirantandatta** [run-llama/llama_index#13971]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I created elasticsearch persistent embedding using the following code:
vector_store = ElasticsearchStore(
    index_name="dense_index_new",
    es_url="http://localhost:9200"
    )
 if not os.path.exists("./elastic_db"):
            storage_context = StorageContext.from_defaults(vector_store=vector_store)
            vector_index = VectorStoreIndex(
                documents, service_context=service_context, show_progress=True,storage_context=storage_context
            )
            self.vector_index.storage_context.persist(persist_dir="./elastic_db")
        else:
           storage_context = StorageContext.from_defaults(persist_dir="./elastic_db")
            vector_index=load_index_from_storage(storage_context)
 
 I am able to create persistent embeddings in folder named as elastic_db but for the else conditon I am getting the issue:
  return self.vector_stores[DEFAULT_VECTOR_STORE]
KeyError: 'default'
My aim is to create the embeddings folder one time and share it to other person so that other person can use the embeddings using the else condition.How to resolve the error?

**Comment by chirantandatta** [comment]
@dosu 
query_engine=vector_index.query_engine()
response=query_engine.query(question)
For response generation,I am getting this error
--> 352     raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
    353         message=message, meta=meta, body=resp_body
    354     )
    356 # 'X-Elastic-Product: Elasticsearch' should be on every 2XX response.
    357 if not self._verified_elasticsearch:
    358     # If the header is set we mark the server as verified.

BadRequestError: BadRequestError(400, 'parsing_exception', 'Unknown key for a START_OBJECT in [knn].')

How to solve this

**Comment by chirantandatta** [comment]
@dosu 
this is an internal python file. I can't change that. Is there any other way to solve the problem

**Comment by chirantandatta** [comment]
@dosu
I am not using elasticsearchembeddings and any model of elasticsearch for response generation.I am using different model and different embedding and elasticsearch I am using for storage_context purpose only.
How to resolve that error with this condition

**Comment by chirantandatta** [comment]
@dosu that problem is solved by upgrading elasticsearch version.now getting this error
ValueError: Query id f53e054e-57f1-418e-9b2e-a9b22050d6b8 not found in either `retriever_dict` or `query_engine_dict`.
I am using retrieverqueryengine for response generation.how to solve this error

**Comment by logan-markewich** [comment]
@chirantandatta if you are using elastic search, everything is saved inside elastic search. In fact, you'll probably find the files in the saved folder rather empty

Just create the vector store object, and do `VectorStoreIndex.from_vector_store(vector_store)`
