### ISSUE TITLE
Elasticsearch persistence

### ISSUE THREAD

**Issue by chirantandatta** [run-llama/llama_index#13979]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to make persistence storage of elasticsearch just like we can do for chromadb using llama index

**Comment by logan-markewich** [comment]
elastic search is a server. It persists automatically.

**Comment by chirantandatta** [comment]
> elastic search is a server. It persists automatically.
> 
> To reconnect to an elastic store, just setup the vector_store and do `VectorStoreIndex.from_vector_store(vector_store)`

In case of chromadb, we can create a folder. Can we do the same for elasticsearch?

**Comment by logan-markewich** [comment]
No. It's a completely different system. Elastic search is a server that you typically run in a docker container. Chroma runs locally

**Comment by chirantandatta** [comment]
> No. It's a completely different system. Elastic search is a server that you typically run in a docker container. Chroma runs locally

We want to create embeddings for a document and store it in elasticsearch and like to share those embeddings to other user to decrease time consumption.Let me know is there any solution to share these embeddings either in docker or any other alternative solution.Please do the needfu

**Comment by chirantandatta** [comment]
> elastic search is a server. It persists automatically.
> 
> To reconnect to an elastic store, just setup the vector_store and do `VectorStoreIndex.from_vector_store(vector_store)`

And second time while entering a query to generate response, I am getting this error
Query id 40b9d01f-b211-413d-b3d4-a799eff700d6 not found in either `retriever_dict` or `query_engine_dict`.
How to resolve this error?
