### ISSUE TITLE
[Question]: How to write production grade code 

### ISSUE THREAD

**Issue by picografix** [run-llama/llama_index#13985]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am building a RAG and Agentic application over my company data using llama-index but I am having difficult time in creating a persistent pipeline, are there any opensource projects which have well written code and use llama index?

**Comment by picografix** [comment]
@dosu I want to create a persistant data ingestion pipeline using milvus db and redis cache and fetch data from jira, whenever I fetch data it should automatically identify if its new data or old one

**Comment by Nikzzzzz-de-coder** [comment]
@dosu I want to import data from online apis which return them in json, index the json and query it using groq. I dont have open ai subs
