### ISSUE TITLE
[Question]: sent-len of sentence-spliter

### ISSUE THREAD

**Issue by guangyuli-uoe** [run-llama/llama_index#13982]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

there is one arg of SentenceSplitter: chunk_size, i assume this could control the length of each split-sentence, but i found that sentence-length can be larger than the chunk_size, i want to know why this happens

**Comment by logan-markewich** [comment]
@guangyuli-uoe the sentence splitter splits into chunks, while trying to respect sentence boundaries. It does not split and return single sentences.

**Comment by guangyuli-uoe** [comment]
@logan-markewich thanks !
