### ISSUE TITLE
API key for content summarization

### ISSUE THREAD

**Issue by MrJo305** [run-llama/llama_index#13984]
### Feature Description

i would like to shorten the reading time on newsletter by summarizethe article.  

### Value of Feature

Because it can save my time.

**Comment by logan-markewich** [comment]
This is not a helpful post 😅 

If you want to summarize stuff, we have many guides. Here's one
https://docs.llamaindex.ai/en/stable/examples/response_synthesizers/tree_summarize/

`TreeSummarize(llm=llm, use_async=True, ...)`
