### ISSUE TITLE
[Bug]: MongoDBAtlasVectorSearch & VectorStoreIndex.from_vector_store are not working as expected

### ISSUE THREAD

**Issue by elahea2020** [run-llama/llama_index#13990]
### Bug Description

Hi 
I have been using MongoDBAtlasVectorSearch for my project and this is my simple code to load the store_index:

For some reason `vector_store_index` is empty even when the index in MongoDB is not. This was working for me before so I'm not sure if this is a bug in one of the newer versions or not. I am also not getting any errors or exceptions. 

I would extremely appreciate any help with this. Since if this is not working I would have to change my project entirely to not use llama_index.

Here is the code
```
atlas_vector_search = MongoDBAtlasVectorSearch(
            mongo_client=index_client,
            db_name = index_db,
            collection_name = index_collection,
            index_name = index_name
        )
    
vector_store_index = VectorStoreIndex.from_vector_store(vector_store=atlas_vector_search)
```

### Version

0.10.26

### Steps to Reproduce

have a mongodb atlast vector search with at least one data. and then run this

**Comment by logan-markewich** [comment]
Can you explain more what's not working?

**Comment by logan-markewich** [comment]
@elahea2020 I just went through the entire flow, and it worked fine.

I made some notes here
https://colab.research.google.com/drive/1xQ4EucEG20rPVu_F37RiaEXCEDv7mnbp?usp=sharing

Basically, make sure you are providing the correct index name, db name, and collection name on the llama-index side.

On the mongodb side, make sure you have a vector search index configured for a db+index+collection that matches the details provided from the llama-index side

You may have to edit or recreate the search index in mongodb if some details are incorrect, or you might have to update the fields you are specifying on the llama-index side.

Either way, it appears to work fine assuming the steps are closely followed

**Comment by elahea2020** [comment]
I appreciate your help! 
I still have the same issue. I even tried to add a fake document to my search_index and I see it added in my MongoDB but when I iterate over vector_store_index it's empty. 

```
atlas_vector_search = MongoDBAtlasVectorSearch(
            mongo_client=client,
            db_name = DB_NAME,
            collection_name = COLLECTION_NAME,
            index_name = INDEX_NAME
        )
    
    vector_store_context = StorageContext.from_defaults(vector_store=atlas_vector_search)

    index = VectorStoreIndex.from_documents([Document(
            text="This is a test from python script",
            metadata={"id": id}
            )], storage_context=vector_store_context, show_progress=True
            )



    vector_store_index = VectorStoreIndex.from_vector_store(vector_store=atlas_vector_search)
    
    print("Printing documents from docstore:")
    for doc_id, doc in vector_store_index.docstore.docs.items():
        print(f"Document ID: {doc_id}, Document: {doc}")
```

**Comment by elahea2020** [comment]
I believe I realize what was going on. It appears that 
`vector_store_index = VectorStoreIndex.from_vector_store(vector_store=atlas_vector_search)
` only works for Documents that we add when we are creating the `vector_store_index`. However, I am interested in creating a `vector_store_index` from the existing embedded data in my MongoDBAtlastVectorSearch. Do you know how/ if that's possible by any chance?

**Comment by logan-markewich** [comment]
@elahea2020 I guess you mean you inserted data outside of llamaindex (I.e. not using from_documents() or insert())

You need to specify a few keys on the class constructor. This is what llamaindex is using as defaults, but you can override 

https://github.com/run-llama/llama_index/blob/7b14500fa41a37faff764742741cca4c6406e580/llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py#L106

Probably most important is the text key
