### ISSUE TITLE
[Bug]: async functions do not work..

### ISSUE THREAD

**Issue by mdciri** [run-llama/llama_index#14004]
### Bug Description

I have a created a RAG with automerging retriver. it works and I am trying to evaluate it, but every time I call the functions as:
   
    from llama_index.core.evaluation.eval_utils import get_responses, get_results_df
    from llama_index.core.evaluation import BatchEvalRunner

that need:

    import nest_asyncio
    nest_asyncio.apply()

it breaks (see picture in attached), as: 

    pred_responses = get_responses(questions, automerging_engine, show_progress=True)

![Screenshot from 2024-06-07 17-30-51](https://github.com/run-llama/llama_index/assets/59966344/99a4183c-b095-434f-ada5-e0dc308b83f4)

Nevertheless, I can generate a response simply doing:

    response = automerging_engine.query(query)

It works even if I do a loop like:

    preds = []
    for q in questions:
        preds.append(automerging_engine.query(q))
        
        
Same thing if I use:

    eval_results = await batch_runner.evaluate_responses(
        questions, responses=pred_responses, reference=ref_responses
    )

I am following the example in https://docs.llamaindex.ai/en/stable/examples/retrievers/auto_merging_retriever/.

what is the problem? can you help me, please?

### Version

0.10.43

### Steps to Reproduce

    import nest_asyncio
    nest_asyncio.apply()    

    from llama_index.core.evaluation.eval_utils import get_responses, get_results_df
    from llama_index.core.evaluation import BatchEvalRunner

    pred_responses = get_responses(questions, automerging_engine, show_progress=True)
    eval_results = await batch_runner.evaluate_responses(
        questions, responses=pred_responses, reference=ref_responses
    )

**Comment by mdciri** [comment]
my retriver is build with the class from `AutoMergingRetriever` from `llama_index.core.retrievers` which is a `BaseRetriever`, as in: https://docs.llamaindex.ai/en/stable/examples/retrievers/auto_merging_retriever/.

**Comment by logan-markewich** [comment]
@mdciri I just tried the notebook using the latest version of llama-index, and all functions run fine, including get_responses and evaluate

Please see the notebook here
https://colab.research.google.com/drive/1evtawQnzZRuP4OksVUiyabPylCVlxFiu?usp=sharing

Not sure how you got to this state if nest_asyncio is applied

**Comment by mdciri** [comment]
You need to give me access to the notebook.
May it be the llm? I am using Bedrock provider and not OpenAI

**Comment by mdciri** [comment]
I see. So, it is the Bedrock provider the problem. Indeed it was strange that it was not working. Please, let me know when the issue is resolved and I can try again.

thanks a lot.

**Comment by mdciri** [comment]
@logan-markewich do you have any news?

**Comment by logan-markewich** [comment]
@MarcoWorms we don't have access to bedrock to test right now. I welcome a contribution. You'd just need to implement the same as the sync methods, but using async boto3 sessions/clients

**Comment by mdciri** [comment]
@logan-markewich unfortunately I think I need a bit more help 😅
