### ISSUE TITLE
[Question]: Embeddings In ElasticSearch

### ISSUE THREAD

**Issue by LikhithRishi** [run-llama/llama_index#14046]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

We want to create embeddings for a document and store it in elasticsearch and like to share those embeddings to other user to decrease time consumption.Let me know is there any solution to share these embeddings either in docker or any other alternative solution.

**Comment by logan-markewich** [comment]
We have full docs for elastic search
https://docs.llamaindex.ai/en/stable/examples/vector_stores/ElasticsearchIndexDemo/?h=elastic
