### ISSUE TITLE
[Question]: I want to highlight the souce of extracted data for a pdf, what are the metadata required ?

### ISSUE THREAD

**Issue by Hritesh-Hexaware** [run-llama/llama_index#14045]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am parsing a pdf file and extracting information from it, i want to have a source_link, on click of which the pdf opens up , jumps to specific page no. and source node highlighted

**Comment by logan-markewich** [comment]
the `response.source_nodes` contains the nodes used to make a response

There, you can access the metadata (which might have the page number). To highlight in a PDF, I would use some fuzzy matching library to compare against the original PDF text, like fuse.js
