### ISSUE TITLE
ImportError: Cannot import name "PropertyGraphIndex" from "llama_index.core"

### ISSUE THREAD

**Issue by nikhitaKanoj** [run-llama/llama_index#14051]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to implement - https://docs.llamaindex.ai/en/latest/examples/property_graph/property_graph_basic/
I am getting ImportError : ImportError: Cannot import name "PropertyGraphIndex" from "llama_index.core"

**Comment by nikhitaKanoj** [comment]
@dosu , Upon Implementing this , i got this error : 
ModuleNotFoundError: No module named " llama_index.core.indices.property_graph.base"

**Comment by jackyeo** [comment]
I tried using this **pip install llama-index llama-index-graph-stores-neptune llama-index-llms-bedrock llama-index-embeddings-bedrock**
