### ISSUE TITLE
[Question]: local model files location

### ISSUE THREAD

**Issue by aclifton314** [run-llama/llama_index#14059]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

- Ubuntu 22.04
- Python 3.11.9
- LlamaIndex 0.10.36

I was wanting to know where the model files might be located if someone is offline? For instance, I have done the following:
- set up and activate venv
- install relevant llama_index libraries
- run a simple query to a standalone weaviate db using `HuggingFaceEmbedding` while connected to internet.
- disconnected from internet
- run same code and get response.

This makes me think that maybe the embedding model had been downloaded to my local machine. However, when I check `~/.cache/huggingface/hub` or `/tmp/llamaindex` I don't see any files there. 

If I am disconnected from the internet and run the same code, where might the embedding model files be stored? Thanks in advance for your help!!

**Comment by logan-markewich** [comment]
@aclifton314 `/tmp/llama_index` -- you can specify it on the class otherwise `HuggingFaceEmbedding(..., cache_folder="<path>")`
