### ISSUE TITLE
[Feature Request]: Azure Serverless Endpoint Support

### ISSUE THREAD

**Issue by farkas93** [run-llama/llama_index#14058]
### Feature Description

I just deployed my first Azure ML Studio Serverless endpoint and I had to realise, that there is no matching LLM type in llama_index. Am I missing something? Or does llama_index not support Azure LLMs in general, but the Open AI Resources?

### Value of Feature

If this feature is indeed missing, this would need to be implemented so llama_index has support for all the llms available on azure.

**Comment by logan-markewich** [comment]
There's only support for azure openai yea.

I don't know what the api for azure serverless looks like, but if it's just implementing openai's api, then it's already supported

**Comment by farkas93** [comment]
Good point, did not manage to figure out what api they are actually implementing yet and if it is model dependent in the end. However, let's assume it is openai api, which LLM wrapper would you recommend? I feel like there is a lot that could be used for that.

**Comment by logan-markewich** [comment]
@farkas93 if it is openai compatible, you can use the OpenAILike llm class

**Comment by farkas93** [comment]
For now I could not make it work with neither AzureOpenAI or OpenAI Like. I will provide more insights on the endpoint implementation if I find the time to research it :)

For AzureOpenAI it requires me to have a valid openAI model set.

For OpenAI like i get:
INFO:httpx:HTTP Request: POST URI_TO_MY_ENDPOINT/completions "HTTP/1.1 405 Method Not Allowed"

**Comment by farkas93** [comment]
https://learn.microsoft.com/en-us/azure/ai-studio/reference/reference-model-inference-chat-completions

This is what i found and for now i am using it with my own code. However, it feels to me like it should be/could be possible to use the OpenAILike class. Can anyone confirm who knows more about the implementation of the OpenAILike class?

**Comment by farkas93** [comment]
I do not believe that it is possible to interface with Serverless Azure Endpoints. It would be amazing if we could use Phi3 from within llama index over an Azure Serverless Endpoint. Please convert it to a feature request :)
