### ISSUE TITLE
PropertyGraphIndex : ValidationError: 1 validation error for SimpleLLMPathExtractor , llm Cant instantiate abstract class LLM without an implementation for abstract methods 'achat','acomplete','astream_chat' etc

### ISSUE THREAD

**Issue by nikhitaKanoj** [run-llama/llama_index#14060]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to Implement this https://docs.llamaindex.ai/en/latest/examples/property_graph/property_graph_basic/ 
using my local LLM : 
model_id = 'NHL2-13b-chat-Llama2-ct2'
tokenizer_id = 'Nous-Hermes-Llama2-13b'
llm=CTranslate(model_path=model_id,tokenizer_name=tokenizer_id,device="auto",compute_type="int8)

index = PropertyGraphIndex.from_documents(
    documents,
    llm=llm,
    embed_model=embed_model,
    show_progress=True,
)
When I run this code i get this error : 
ValidationError: 1 validation error for SimpleLLMPathExtractor , llm Cant instantiate abstract class LLM without an implementation for abstract methods 'achat','acomplete','astream_chat' etc

**Comment by logan-markewich** [comment]
What is CTranslate? I don't think that's an llm from llamaindex?

**Comment by nikhitaKanoj** [comment]
@logan-markewich  its from this : 
from langchain_community.llms import CTranslate2
model_id = 'NHL2-13b-chat-Llama2-ct2'
tokenizer_id = 'Nous-Hermes-Llama2-13b'
llm=CTranslate2(model_path=model_id,tokenizer_name=tokenizer_id,device="auto",compute_type="int8)

**Comment by logan-markewich** [comment]
You can't use a langchain llm in llamaindex without the wrapper 

`pip install llama-index-llms-langchain`

```
from llama_index.llms.langchain import LangChainLLM

llm = LangChainLLM(Ctranslate(...))
```

**Comment by nikhitaKanoj** [comment]
@logan-markewich  thanks it works
