### ISSUE TITLE
[Bug]: `IngestionPipeline` with docstore not outputting nodes when loaded from local cache and using a new docstore

### ISSUE THREAD

**Issue by theta-lin** [run-llama/llama_index#14068]
### Bug Description

After running a `IngestionPipeline` with a docstore attached and storing its cache locally with `pipeline.persist()`, running another pipeline loaded with the stored cache by calling `pipeline.load()` before running it on the same documents would yield no output (no nodes are returned). Note that no documents would be returned from the second pipeline even when no docstore are attached to it. And if a docstore is attached to the second pipeline, no documents would be loaded into that docstore.

**I suspect that the docstore stored in the cache is used as opposed to the new docstore attached to the second pipeline.**

### Version

0.10.38

### Steps to Reproduce

See https://github.com/run-llama/llama_index/issues/14068#issuecomment-2162386439

**Edit: Refine the issue to be about how using both caching and docstore would cause the problem.**

**Comment by logan-markewich** [comment]
@theta-lin you'll have to give something more reproducible. This code works fine for me, a node is returned every time

```python
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document

pipeline = IngestionPipeline(
    transformations=[SentenceSplitter()]
)

nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")
nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")

pipeline.persist()

pipeline = IngestionPipeline(
    transformations=[SentenceSplitter()]
)
pipeline.load()
nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")
nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")
nodes = pipeline.run(documents=[Document(text="hello world")])
print(f"Got {len(nodes)} nodes")

```

**Comment by theta-lin** [comment]
@logan-markewich Really appreciate that you looked into it. Yes, I should not be in such a hurry and provide more concretely reproducible code in the issue. After experimenting more, I found that just `pipeline.persist()` and `pipeline.load()` are not sufficient to trigger the bug. Instead, I think it has something to do with how caching interacts with docstore.

Adding only a docstore does cause some issue:
```python
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document
from llama_index.core.storage.docstore import SimpleDocumentStore

pipeline = IngestionPipeline(
    transformations=[SentenceSplitter()], docstore=SimpleDocumentStore()
)

nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")  # should be 1
nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")  # should be 0

pipeline.persist()

pipeline = IngestionPipeline(
    transformations=[SentenceSplitter()], docstore=SimpleDocumentStore()
)
pipeline.load()
nodes = pipeline.run(documents=[Document(text="hello")])
print(f"Got {len(nodes)} nodes")  # should be 1
nodes = pipeline.run(documents=[Document(text="hello"), Document(text="hello world")])
print(f"Got {len(nodes)} nodes")  # should be 1
``` 
The output of `nodes` lengths are `1, 0, 0, 1`. I think the third `run()` is problematic as the output is `0` instead of `1`. According to [the documentation](https://docs.llamaindex.ai/en/stable/module_guides/loading/ingestion_pipeline/#document-management), attaching a docstore will make ingestion pipeline skip duplicate documents. However, as I am using a new docstore, it should not consider adding `"hello"` again as a duplicate. If either `pipeline.load()` is not called, or docstore is not attached, the issue will not occur.

Adding both docstore and vector store is not really ifferent from the previous example:
```python3
from llama_index.core.ingestion import IngestionPipeline
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core import Document
from llama_index.core.storage.docstore import SimpleDocumentStore
from llama_index.core.vector_stores.simple import SimpleVectorStore
from llama_index.embeddings.huggingface import HuggingFaceEmbedding

transformations = [
    SentenceSplitter(),
    HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5", trust_remote_code=True),
]

pipeline = IngestionPipeline(
    transformations=transformations,
    docstore=SimpleDocumentStore(),
    vector_store=SimpleVectorStore(),
)

nodes = pipeline.run(documents=[Document(text="hello", doc_id="1")])
print(f"Got {len(nodes)} nodes")  # should be 1
nodes = pipeline.run(documents=[Document(text="hello", doc_id="1")])
print(f"Got {len(nodes)} nodes")  # should be 0

pipeline.persist()

pipeline = IngestionPipeline(
    transformations=transformations,
    docstore=SimpleDocumentStore(),
    vector_store=SimpleVectorStore(),
)
pipeline.load()
nodes = pipeline.run(documents=[Document(text="hello", doc_id="1")])
print(f"Got {len(nodes)} nodes")  # should be 1
nodes = pipeline.run(
    documents=[
        Document(text="hello", doc_id="1"),
        Document(text="hello world", doc_id="2"),
    ]
)
print(f"Got {len(nodes)} nodes")  # should be 1
```
The same output of `nodes` lengths `1, 0, 0, 1` can be seen again. Note that according to [the documentation](https://docs.llamaindex.ai/en/stable/module_guides/loading/ingestion_pipeline/#document-management), it is necessary to add `doc_id` so that the deduplication of the documents would still occur.

Therefore, it seems that adding an embedding transform and vector store so far does not affect whether this issue would occur or not.  Also, I have not discovered the minimum condition for the following to occur:

> Then, running it again (if you use a vector store, reset it or delete it before each run) with the same documents and same transformations, different documents and same transformations, and same documents and different transformations would all produce no output from the pipeline.

I guess it might have something to do with how documents are read in my project, so I am currently trying to isolate the factors and see whether actually reading the documents from the disk would make a difference as compared to simply creating `Document` objects.
