### ISSUE TITLE
[Question]: Not able to install llama-index-storage-chat-store-azure

### ISSUE THREAD

**Issue by SiddharthMurjani** [run-llama/llama_index#14069]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to install `AzureChatStore` using 
> pip install llama-index-storage-chat-store-azure

But getting this issue

```python
ERROR: Could not find a version that satisfies the requirement llama-index-storage-chat-store-azure (from versions: none)
ERROR: No matching distribution found for llama-index-storage-chat-store-azure
``` 

I checked [GitHub code for AzureChatStore](https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/storage/chat_store/llama-index-storage-chat-store-azure) there it shows a pipeline failure.

**Comment by SiddharthMurjani** [comment]
Still doesn't work

**Comment by logan-markewich** [comment]
Hmm, seems like our CICD failed to publish

Just published it
https://pypi.org/project/llama-index-storage-chat-store-azure/
