### ISSUE TITLE
[Question]: I want to store the chat_history in a postgresql that is installed locally on my machine.

### ISSUE THREAD

**Issue by SiddharthMurjani** [run-llama/llama_index#14073]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So, I am trying to create a chatbot that performs RAG over documents of different companies.
I what to store chat_session in a postgres table using `chat_session_id`.

Also, when I retrive the data back from the table, I wany to convert it into 
```python
[List[ChatMessage]]
``` 

and pass it to my `ContextChatEngine`

```python
chat_engine = ContextChatEngine.from_defaults(
        memory=memory,
        retriever=index.as_retriever(),
    )
```

**Comment by logan-markewich** [comment]
@SiddharthMurjani you can convert your chat history to json / string, then store it wherever you need

Something like
```
chat_history_dicts = [x.dict() for x in chat_engine.chat_history]
chat_history_blob = json.dumps(chat_history_dicts)

chat_history_dicts = json.loads(chat_history_blob)
chat_history = [ChatHistory.parse_obj(x) for x in chat_history_dicts]

chat_engine.chat("Hello", chat_history=chat_history)
```

**Comment by SiddharthMurjani** [comment]
Thankyou @logan-markewich !
