### ISSUE TITLE
[Question]: Metadata filtering in chat engine.

### ISSUE THREAD

**Issue by Prem-Nitin** [run-llama/llama_index#14075]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a way to add metadata filtering in context chat engine. The metadata filtering would be different for users based on their roles. Do anyone have idea on how to do this?

**Comment by logan-markewich** [comment]
Same way you filter a query engine

`index.as_chat_engine(..., filters=filters)`

**Comment by logan-markewich** [comment]
The filters just get passed into the retriever under the hood

**Comment by Prem-Nitin** [comment]
@dosu @logan-markewich 

```
chat_engine = ContextChatEngine.from_defaults(
        retriever = retriever,
        node_postprocessors=get_node_postprocessor(),
        system_prompt=chat_engine_system_prompt,
        context_template=context_prompt,
        chat_history=initial_chat_history,
        llm = Settings.llm,
        memory=memory,
    )
```

 so can i add filters as a parameter in the above code directly

**Comment by marketneutral** [comment]
How do I change metadata filters on a chat_engine which is already instantiated?

The user pattern is like:
1) instantiate chat_engine with no filters
2) user issues a query: "for AAPL, what is the ..."
3) we set the metadata filters in the chat_engine to filter documents only about AAPL and issue the query; chat engine returns response
4) user issues a query, "ok, and for NVDA, ..."
3) we set the metadata filters in the chat_engine to filter documents only about NVDA and issue the query; chat engine returns response
