### ISSUE TITLE
[Question]: Retriever search depth in a custom node relationship environment 

### ISSUE THREAD

**Issue by whoo9112** [run-llama/llama_index#14096]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I use llama-index to configure custom nodes and create parent-child correlations between them.

However, it was confirmed that only the depth immediately above and below the node retrieved when as_query_engine was referenced.
I want to increase the reference range because I have nodes that have very short top-down relationships.

Is there a way to adjust the options related to this?

**Comment by logan-markewich** [comment]
What index are you using? What retriever?

**Comment by whoo9112** [comment]
> What index are you using? What retriever?

i'm using index = VectorStoreIndex , and  index.as_query_engine()

**Comment by logan-markewich** [comment]
The default vector store index and query engine does not follow or use the node relationships 👀 you'd have to introduce a node postprocessor to use them

**Comment by whoo9112** [comment]
1. 

> The default vector store index and query engine does not follow or use the node relationships 👀 you'd have to introduce a node postprocessor to use them

So what method should I use to refer to relocationship when retrever? Is there an example? I'm thinking about faiss, chroma, etc. as vector db right now.
