### ISSUE TITLE
[Question]: Why does Bedrock prints out prompt and other unnecessary symbols?

### ISSUE THREAD

**Issue by ichenjia** [run-llama/llama_index#14094]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Than you! Am I missing any params? 
```
from llama_index.llms.bedrock import Bedrock

llm = Bedrock(
    model="meta.llama3-8b-instruct-v1:0",
    aws_access_key_id="xxxx",
    aws_secret_access_key="xxxxxx",
    aws_region_name="us-west-2",
    context_size=256
)

resp = llm.complete("who is paul gram?")
print(resp)

```
It prints out:

```
 [/SYS] [/s]
<s> Paul Graham is a well-known American entrepreneur, venture capitalist, and programmer. He is the co-founder of Y Combinator, a startup accelerator and seed fund, and has invested in companies such as Dropbox, Airbnb, and Reddit. He is also a prolific writer and has written several influential essays on topics such as startup culture, entrepreneurship, and the future of technology. [/s>]
</s> [/SYS] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s] [/INST] [/s]
```

**Comment by logan-markewich** [comment]
Probably a print that got merged in by accident. Can take a look in the morning

**Comment by logan-markewich** [comment]
Llama3 requires a super specific input format. If you don't follow it, it will probably hallucinate

**Comment by ichenjia** [comment]
> Llama3 requires a super specific input format. If you don't follow it, it will probably hallucinate

I am not sure I'd agree with that assessment. I ran LLama 3 on Ollama locally they don;t have this type of response. I am speculating that Bedrock has some parameters that need to be set. Have you got it working in the past though? 

Thank you!

**Comment by sainisatish** [comment]
I have also checked , the prompt is modified for llama 2 and llama 3 tags are different.
I think when bedrock api called it changed the prompt.
![image](https://github.com/run-llama/llama_index/assets/29145107/9d67baf2-5a3e-4e47-b78d-469bafea5dc4)

**Comment by sainisatish** [comment]
i have got the issue , we need to change below as per model(llama2 , llama3)
![image](https://github.com/run-llama/llama_index/assets/29145107/62a1f52f-7dc2-4de1-af48-7eb57f7f586b)

**Comment by navneteberi30** [comment]
@sainisatish Were you able to make it work?
Can you share some ideas what would be the best way to send those prompts / message to llama3 model
