### ISSUE TITLE
[Question]: Further explanation of total embedding token usage

### ISSUE THREAD

**Issue by ihgumilar** [run-llama/llama_index#14090]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

I have used this code https://docs.llamaindex.ai/en/stable/examples/callbacks/TokenCountingHandler/ to count for embedding token usage. However, I would like to get a further clarification or explanation do you have any specific breakdown about total embedding token usage in LlamaIndex ?

Does it mean the usage token for query and answer ? Further explanation is much appreciated about embedding token usage in LlamaIndex.

Thanks

**Comment by logan-markewich** [comment]
I'm not sure what you are looking for?

Indexing uses tokens to embed all your documents.

Querying uses much less, as it only needs to embed the query text

**Comment by ihgumilar** [comment]
Thanks for the explanation. Basically, I am trying to understand this
![image](https://github.com/run-llama/llama_index/assets/49016400/2ac3b678-181e-457b-a8f5-dde8307d3397)

What does 8 (embedding tokens) represent ?

**Comment by logan-markewich** [comment]
It means to run the query, 8 tokens were sent to the embedding model (I.e it sent the query text to the embedding model)
