### ISSUE TITLE
[Bug]: ReplicateError: Unauthenticated 

### ISSUE THREAD

**Issue by rinmy23** [run-llama/llama_index#14106]
### Bug Description

I just use the code from llamaindex doc: https://docs.llamaindex.ai/en/latest/api_reference/llms/replicate/
![image](https://github.com/run-llama/llama_index/assets/109497516/90b97570-94a2-4800-ac99-2cab1a21a082)
**I use my api_key,but it still don't work.
My key can be used , I have tested :**
![image](https://github.com/run-llama/llama_index/assets/109497516/e3a7894b-3867-4583-a26d-fac1a2e44185)
![image](https://github.com/run-llama/llama_index/assets/109497516/fbfe5240-ec6c-4f0a-b5dc-c648607ab847)

**_It just I cannot using the example code to create Replicate LLM_**

### Version

the newest

### Steps to Reproduce

I want you to answer me! I waste a lot of time in this !!!!!

**Comment by logan-markewich** [comment]
You are able to use the same model as well outside of llama-index? (The screenshots use different models)

Not sure what to tell you, my replicate key works for me 😅

**Comment by rinmy23** [comment]
yes, i can use the same model when i use replicate=Client(api_token) defined in first function
![image](https://github.com/run-llama/llama_index/assets/109497516/3ce2e605-3fa6-428f-a90a-906e42f7d5e9)
![image](https://github.com/run-llama/llama_index/assets/109497516/2bb78894-f69a-4125-a4c7-c9c5111f7663)
**I can use the replicate Client in my code , I just cannot use the replicate LLM** But I have to use replicate LLM in query_engine , If I just use replicate Client, after I get the retrieved nodes, I have to write prompt myself rather than using prompt and response mode in query_engine

**Comment by rinmy23** [comment]
yes, i can use the same model when i use replicate=Client(api_token) define a replicate Client
![image](https://github.com/run-llama/llama_index/assets/109497516/40fbb12a-c145-4eba-b3ef-f072db4e2073)

**I can use the replicate Client in my code , I just cannot use the replicate LLM But I have to use replicate LLM in query_engine , If I just use replicate Client, after I get the retrieved nodes, I have to write prompt myself rather than using prompt and response mode in query_engine**

**Comment by rinmy23** [comment]
Oh, now it works
