### ISSUE TITLE
[Bug]: llama-index-llms-langchain is not working with latest lanchain

### ISSUE THREAD

**Issue by tomaszZdunek** [run-llama/llama_index#14125]
### Bug Description

Llama is not working with latest langchain using llama-index-llms-langchain package and because of this there is an issue with using tiktoken 0.7.0 that is required for gpt-4o

### Version

0.10.44

### Steps to Reproduce

tiktoken = { version = ">=0.7.0,<1.0" }
langchain = { version = ">=0.1.5,<1.0", extras = ["openai"], optional = true }
langchain-openai = ">=0.1.3,<1.0"
llama-index = { version = ">=0.10.4,<1.0", optional = true}
llama-index-embeddings-azure-openai = { version = ">=0.1.1,<1.0", optional = true}
llama-index-llms-azure-openai = { version = ">=0.1.1,<1.0", optional = true}
llama-index-embeddings-langchain = { version = ">=0.1.1,<1.0", optional = true}
llama-index-llms-langchain = { version = ">=0.1.1,<1.0", optional = true}

**Comment by logan-markewich** [comment]
I don't really see how tiktoken is the issue here, llamaindex depends on tiktoken `>=0.3.3`

Here's your test as a pyproject.toml

```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["test"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = { version = ">=0.1.5,<1.0", extras = ["openai"], optional = true }
langchain-openai = ">=0.1.3,<1.0"
llama-index = { version = ">=0.10.4,<1.0", optional = true}
llama-index-embeddings-azure-openai = { version = ">=0.1.1,<1.0", optional = true}
llama-index-llms-azure-openai = { version = ">=0.1.1,<1.0", optional = true}
llama-index-embeddings-langchain = { version = ">=0.1.1,<1.0", optional = true}
llama-index-llms-langchain = { version = ">=0.1.1,<1.0", optional = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

And then running `poetry shell` -> `poetry lock` -> `poetry install` works fine. I also tried removing all the optionals and rerunning the process, it also works fine.

(btw, not sure the reason for using langchain here, llamaindex has an openai llm as well)

**Comment by tomaszZdunek** [comment]
to have support for tokenizer for gpt-4o you need to have tiktoken>=0.7.0 and this is supported only by langchain>=0.2.0 and llama-index-llms-langchain have "^0.1.0", so 0.2.0 is not supported.

Why we are using llama-index-llms-langchain - we have many different GenAI pipelines developed, initially all of them was build using Llama (and we contributed some functionality needed for us like support for custom headers in Langchain gemini library), but recently we also added some pipelines, where llamaindex was better choice but we want to have our llm factory class to be unified for whole solution and as we are supporting many models (gpt, gemini, cloude and more) we don't won't to duplicate this functionality for llamaindex.

**Comment by Tibiritabara** [comment]
Unfortunately, I am facing the same issue. I am currently limited by llama-index to upgrade my langchain dependencies.
