### ISSUE TITLE
[Question]: Why is JSONalyze using `columns_dict` of the `sqlite_utils`?

### ISSUE THREAD

**Issue by mvilrokx** [run-llama/llama_index#14139]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

See https://github.com/run-llama/llama_index/blob/f17513961505c43391851b364fba0494ee329496/llama-index-core/llama_index/core/query_engine/jsonalyze_query_engine.py#L89

I am wondering why `columns_dict` was chosen to return the schema? This returns a python "_dictionary representing columns in this table or view._" This is then passed to the LLM, together with the user's question, prompt and table_name.

However, I would assume that most text2sql models are trained or fine-tuned to use a DB schema represtened by DDL (`CREATE TABLE ...`), not a python dictionary.

There is a `schema` property in the `sqlite_utils` which seems to be doing just that so my question is, why was the choice made to use `columns_dict` instead of `schema`?

**Comment by logan-markewich** [comment]
I think this was made with the assumption of a general purpose LLM (openai, llama3, etc.) And not a specific text 2 sql model.

But also, was probably an arbitrary decision, it was community contributed 🤷🏻

**Comment by mvilrokx** [comment]
Does anybody mind if I submit a PR that allows the user to pick between `column_dict` and `schema`? I can leave `column_dict` the default choice so it doesn't impact existing users.
