### ISSUE TITLE
[Question]: cannot download sharepoint file

### ISSUE THREAD

**Issue by BBjie** [run-llama/llama_index#14130]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using the code below to download files from the SharePoint folder. I confirmed those credentials are correct, but it didn't work as expected and returned None value. Just wondering what causes this
```
from llama_index.readers.microsoft_sharepoint import SharePointReader

loader = SharePointReader(
    client_id="<Client ID of the app>",
    client_secret="<Client Secret of the app>",
    tenant_id="<Tenant ID of the Microsoft Azure Directory>",
)

documents = loader.load_data(
    sharepoint_site_name="<Sharepoint Site Name>",
    sharepoint_folder_path="<Folder Path>",
    recursive=True,
)
```

**Comment by Th0h0** [comment]
@dosu Your solution seems wrong!
