### ISSUE TITLE
[Question]: Cannot import name 'DEFAULT HUGGING FACE EMBEDDING MODEL from 'llama_index.embeddings' (/usr/local/lib/python3.11/site-packages/llama_index/embeddings/__init__.py)

### ISSUE THREAD

**Issue by AndrewJVRensburg** [run-llama/llama_index#14156]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Trying to run:
```
from llama_index.core import (
    ListIndex,
    VectorStoreIndex,
    SimpleDirectoryReader,
    ServiceContext,
    StorageContext,
    Settings
)
```

Full Traceback error:
```
Traceback (most recent call last):
  File "/home/project/__init__.py", line 16, in <module>
    from amchat import AmChat
  File "/home/project/amchat.py", line 9, in <module>
    from llama_index.core import (
  File "/usr/local/lib/python3.11/site-packages/llama_index/__init__.py", line 20, in <module>
    from llama_index.indices.keyword_table import (
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/keyword_table/__init__.py", line 4, in <module>
    from llama_index.indices.keyword_table.base import (
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/keyword_table/base.py", line 18, in <module>
    from llama_index.indices.base import BaseIndex
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/base.py", line 6, in <module>
    from llama_index.chat_engine.types import BaseChatEngine, ChatMode
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/__init__.py", line 1, in <module>
    from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/condense_question.py", line 5, in <module>
    from llama_index.chat_engine.types import (
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/types.py", line 12, in <module>
    from llama_index.tools import ToolOutput
  File "/usr/local/lib/python3.11/site-packages/llama_index/tools/__init__.py", line 6, in <module>
    from llama_index.tools.query_plan import QueryPlanTool
  File "/usr/local/lib/python3.11/site-packages/llama_index/tools/query_plan.py", line 7, in <module>
    from llama_index.response_synthesizers import BaseSynthesizer, get_response_synthesizer
  File "/usr/local/lib/python3.11/site-packages/llama_index/response_synthesizers/__init__.py", line 3, in <module>
    from llama_index.response_synthesizers.accumulate import Accumulate
  File "/usr/local/lib/python3.11/site-packages/llama_index/response_synthesizers/accumulate.py", line 5, in <module>
    from llama_index.indices.service_context import ServiceContext
  File "/usr/local/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 17, in <module>
    from llama_index.embeddings import (
ImportError: cannot import name 'DEFAULT_HUGGINGFACE_EMBEDDING_MODEL' from 'llama_index.embeddings' (/usr/local/lib/python3.11/site-packages/llama_index/embeddings/__init__.py)
```

Environment details:
Python 3.11.0
Packages:
Package                             Version
----------------------------------- ----------
aiohttp                             3.8.6
aiosignal                           1.3.1
anyio                               4.4.0
async-timeout                       4.0.2
attrs                               23.1.0
beautifulsoup4                      4.12.3
blinker                             1.6.2
certifi                             2023.7.22
cffi                                1.15.1
charset-normalizer                  3.2.0
click                               8.1.6
cryptography                        41.0.3
dataclasses-json                    0.5.14
Deprecated                          1.2.14
dirtyjson                           1.0.8
distro                              1.9.0
docx2txt                            0.8
filelock                            3.15.1
Flask                               2.3.2
Flask-Cors                          4.0.0
frozenlist                          1.4.0
fsspec                              2023.6.0
gpt-index                           0.7.18
greenlet                            2.0.2
h11                                 0.14.0
httpcore                            1.0.5
httpx                               0.27.0
huggingface-hub                     0.23.4
idna                                3.4
itsdangerous                        2.1.2
Jinja2                              3.1.2
joblib                              1.4.2
langchain                           0.0.251
langsmith                           0.0.18
llama-index                         0.10.0
llama-index-agent-openai            0.1.7
llama-index-core                    0.10.44
llama-index-embeddings-huggingface  0.2.1
llama-index-embeddings-openai       0.1.10
llama-index-legacy                  0.9.48
llama-index-llms-openai             0.1.22
llama-index-multi-modal-llms-openai 0.1.6
llama-index-program-openai          0.1.6
llama-index-question-gen-openai     0.1.3
llama-index-readers-file            0.1.25
llamaindex-py-client                0.1.19
MarkupSafe                          2.1.3
marshmallow                         3.20.1
minijinja                           2.0.1
mpmath                              1.3.0
multidict                           6.0.4
mypy-extensions                     1.0.0
mysql-connector                     2.2.9
nest-asyncio                        1.5.8
networkx                            3.3
nltk                                3.8.1
numexpr                             2.8.4
numpy                               1.25.2
nvidia-cublas-cu12                  12.1.3.1
nvidia-cuda-cupti-cu12              12.1.105
nvidia-cuda-nvrtc-cu12              12.1.105
nvidia-cuda-runtime-cu12            12.1.105
nvidia-cudnn-cu12                   8.9.2.26
nvidia-cufft-cu12                   11.0.2.54
nvidia-curand-cu12                  10.3.2.106
nvidia-cusolver-cu12                11.4.5.107
nvidia-cusparse-cu12                12.1.0.106
nvidia-nccl-cu12                    2.18.1
nvidia-nvjitlink-cu12               12.5.40
nvidia-nvtx-cu12                    12.1.105
openai                              1.23.3
openapi-schema-pydantic             1.2.4
packaging                           23.1
pandas                              2.0.3
pillow                              10.3.0
pip                                 23.2.1
pycparser                           2.21
pydantic                            1.10.12
pyodbc                              4.0.39
pypdf                               4.2.0
python-dateutil                     2.8.2
python-dotenv                       1.0.0
pytz                                2023.3
PyYAML                              6.0.1
regex                               2023.6.3
requests                            2.31.0
safetensors                         0.4.3
scikit-learn                        1.5.0
scipy                               1.13.1
sentence-transformers               2.7.0
setuptools                          65.5.1
six                                 1.16.0
sniffio                             1.3.1
soupsieve                           2.4.1
SQLAlchemy                          2.0.19
striprtf                            0.0.26
sympy                               1.12.1
tenacity                            8.2.2
threadpoolctl                       3.5.0
tiktoken                            0.4.0
tokenizers                          0.19.1
torch                               2.1.2
tqdm                                4.66.1
transformers                        4.41.2
triton                              2.1.0
typing_extensions                   4.7.1
typing-inspect                      0.9.0
tzdata                              2023.3
urllib3                             1.26.16
Werkzeug                            2.3.6
wheel                               0.38.4
wrapt                               1.16.0
yarl                                1.9.2

**Comment by logan-markewich** [comment]
@AndrewJVRensburg seems like you might have recently migrated to v0.10.x?

Try installing in a completely fresh venv

Alternatively, uninstall and reinstall an llamaindex package. A helpful command for uninstalling everything 
`pip freeze | grep llama_index | xargs pip uninstall -y`

**Comment by AndrewJVRensburg** [comment]
Thanks @logan-markewich - definately a dependancy issue here. I was using a docker that had been created previously, and no matter how I changed the package requirements, there was always some error. Doing what you said, starting from scratch and basically ONLY installing llama-index, it works. Thanks
