### ISSUE TITLE
[Question]: way to emit similarity score from the retriever?

### ISSUE THREAD

**Issue by vkaul11** [run-llama/llama_index#14157]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When we use a retriever VectorIndexRetriever and find the top k similarity matches vector_retriever=VectorIndexRetriever(index=index,similarity_top_k=4)
vector_retriever.retrieve
how do I ask it to also emit similarity scores?

**Comment by logan-markewich** [comment]
Each node has the score

```
nodes = retriever.retrieve("query")
print(nodes[0].score)
```
