### ISSUE TITLE
[Question]: is default in VectorIndexRetriever semantic search 

### ISSUE THREAD

**Issue by vkaul11** [run-llama/llama_index#14155]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is the VectorIndexRetriever same as semantic search here 
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/vector_stores/types.py#L46 ?

**Comment by logan-markewich** [comment]
Yes, by default it's top-k search based on embeddings
