### ISSUE TITLE
[Bug]: Text match filter doesn't work with PostgreSQL filter search and gives unknown operator error.

### ISSUE THREAD

**Issue by BurnyCoder** [run-llama/llama_index#14173]
### Bug Description

I have PostgreSQL db with Llamaindex and I am doing filter search over it. Many operators work but text match filter doesnt work. I have newest version of Llamaindex. List of filter operators including text match: https://docs.llamaindex.ai/en/v0.10.17/api/llama_index.core.vector_stores.FilterOperator.html

### Version

llama-index-0.10.45

### Steps to Reproduce

My code:
```Python
        filters = MetadataFilters(
            filters=[
                MetadataFilter(key="title", 
                operator=FilterOperator.TEXT_MATCH,        
                value="Graph RAG")
            ]
        )
```
Alternatively:
```operator="text_match"```
Rest of code is basically like https://docs.llamaindex.ai/en/stable/examples/vector_stores/postgres/

### Relevant Logs/Tracbacks

```shell
It gives this error: 
 operator: FilterOperator.TEXT_MATCH, fallback to '='
```

**Comment by logan-markewich** [comment]
That filter type just isn't implemented right now, someone should have to make a PR to add that
