### ISSUE TITLE
[None page in Documentation]: Sub category shows None under data connectors page, reroutes to blank.

### ISSUE THREAD

**Issue by safimuhammad** [run-llama/llama_index#14178]
### Bug Description

In the LLamaIndex documentation for python, Under Examples section, in data connectors category shows None category, which reroutes to blank page.
![image](https://github.com/run-llama/llama_index/assets/50509290/5cf83b46-b444-4dd1-a8ac-219475180031)

![image](https://github.com/run-llama/llama_index/assets/50509290/719c8ff5-a77c-49a6-9375-53080241b975)

### Version

stable

### Steps to Reproduce

visit : https://docs.llamaindex.ai/en/stable/examples/  -> Data Connectors -> None

**Comment by safimuhammad** [comment]
@dosu the indentation seems to be right, its the link that's broken

**Comment by logan-markewich** [comment]
Probably either we just need to remove the link in the yml (must have got in from the WIP branch)

**Comment by safimuhammad** [comment]
should i open a pull request and remove this.

**Comment by logan-markewich** [comment]
@safimuhammad go for it

**Comment by safimuhammad** [comment]
@logan-markewich  Opened it please review.
