### ISSUE TITLE
[Feature Request]:  Neptune Support for PropertyGraphStore

### ISSUE THREAD

**Issue by hypernovas** [run-llama/llama_index#14186]
### Feature Description

Curious, if there will (or already) a Neptune support for PropertyGraph? There seems to only have Neo4j support for `PropertyGraphStore`

### Reason

We are currently using AWS service and do not have any Neo4j subscription, which is quite common I think. 

### Value of Feature

This can help a lot of users who are in the AWS ecosystem quickly adopt Llama-index's new knowledge graph framework.

**Comment by logan-markewich** [comment]
Nebula is also supported. I welcome any contributions though 🙏🏻

**Comment by hypernovas** [comment]
Thanks! 

Got it. I'll look into it to see how I can contribute.

**Comment by logan-markewich** [comment]
This has been added
