### ISSUE TITLE
[Bug]: llama-index-indices-managed-dashscope can't be found in pypi

### ISSUE THREAD

**Issue by PhantomGrapes** [run-llama/llama_index#14184]
### Bug Description

I've merged [llama-index-indices-managed-dashscope](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/indices/llama-index-indices-managed-dashscope/pyproject.toml) into llama_index main branch, but package can't be found in pypi.

### Version

0.10.17

### Steps to Reproduce

```shelll
pip install llama-index-indices-managed-dashscope -i https://pypi.org/simple
```

```
 ERROR: Could not find a version that satisfies the requirement llama-index-indices-managed-dashscope (from versions: none)
ERROR: No matching distribution found for llama-index-indices-managed-dashscope
```

### Relevant Logs/Tracbacks

```shell
ERROR: Could not find a version that satisfies the requirement llama-index-indices-managed-dashscope (from versions: none)
ERROR: No matching distribution found for llama-index-indices-managed-dashscope
```

**Comment by justinzyw** [comment]
not sure the requirement but the dashscope package llama-index-llms-dashscope works for me.
