### ISSUE TITLE
[Question]: is there a way to emit all the chunks and similarity score from llamaindex ?

### ISSUE THREAD

**Issue by vkaul11** [run-llama/llama_index#14183]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wanted to get all the chunks with similarity score using VectorStoreIndex. Is it possible?

**Comment by logan-markewich** [comment]
Set the top k to 10000 and retrieve?

```
retriever = index.as_retriever(similarity_top_k=10000)
nodes = retriever.retrieve("query")
```

**Comment by vkaul11** [comment]
Doesn't work

**Comment by logan-markewich** [comment]
What do you mean doesn't work lol? You'll have to give more info than that
