### ISSUE TITLE
[Documentation]: Qdrant Vector Store - Metadata Filter Cosmetic Error

### ISSUE THREAD

**Issue by pavanjava** [run-llama/llama_index#14192]
### Documentation Issue Description

Multiple places in the `Qdrant Vector Store - Metadata Filter` page, documentation quotes `Pinecone` but the page is refering to `Qdrant`. please find the attached image for reference.
<img width="1117" alt="Screenshot 2024-06-17 at 5 07 25 PM" src="https://github.com/run-llama/llama_index/assets/25398886/946b5bb7-b699-43cb-9ebc-cfa070908956">

I have a fix ready for this, how can I contribute back ?

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/vector_stores/Qdrant_metadata_filter/

**Comment by schiaro98** [comment]
Opened pull request to correct this https://github.com/run-llama/llama_index/pull/14446
