### ISSUE TITLE
[Bug]: AutomerginRetriever raises an error when run against a ChromaDB VectorStorage

### ISSUE THREAD

**Issue by SuperBobRob** [run-llama/llama_index#14239]
### Bug Description

Hi there,

I want to save a vectorstoreindex to a chromaDB (thats what happens in the initialization script) and then - in another script - i want to read the vectorstoreindex from the chromaDB again and query it via an automergingretriever. The automergingretriever works fine in the initialization script. in the query script however, i receive the error shown in the traceback section. querying the vectorstoreindex without an automergingretriever works fine. but when using the automergingretriever it seems like the parent nodes wouldn't be stored in the chromaDB or so? I've checked the doc_id which is referred to in the error message. in the embedding_metadata table within the chroma.sqlite3 file this doc_id exists (even 5 times). 

am i missing anything when setting up the chromaDB-VectorStore or when passing it to the AutoMergingRetriever?
any ideas someone?

Thank in advance,
Robert

### Version

0.10.43

### Steps to Reproduce

Initialization Script :

import chromadb
from llama_index.core import VectorStoreIndex 

from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core.retrievers.auto_merging_retriever import AutoMergingRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from llama_index.core.prompts import PromptTemplate
from llama_index.core.storage.docstore import SimpleDocumentStore

from llama_index.core import StorageContext

from pathlib import Path
import sys

ROOT_PATH = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT_PATH))

from lib.load_models import load_models_GPT4 
from lib.automergingRetrivalFuncs import (
    load_docs,
    get_nodes,
)

print("0")
service_context = load_models_GPT4()
from constants.prompts import DAX_template_str

print("1")
# load some documents
orig_docs, merged_docs = load_docs(docs_dir=Path("./documents/DAX Auszug/ShortSample/"))
nodes, leaf_nodes = get_nodes(chunk_sizes=[2048, 512, 128], original_docs=orig_docs, merged_docs=merged_docs)

print("2")
# initialize client, setting path to save data
db = chromadb.PersistentClient(path="./chroma_db/ShortSample/")

print("3")
# create collection
chroma_collection = db.get_or_create_collection("ShortSample")

print("4")
# assign chroma as the vector_store to the context
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
#vector_store.stores_text = True

print("5")
# define storage context 
storage_context = StorageContext.from_defaults(vector_store=vector_store)
storage_context.docstore.add_documents(leaf_nodes)
storage_context.docstore.add_documents(nodes)
#storage_context.docstore.add_documents(orig_docs)
#storage_context.docstore.add_documents(merged_docs)

print("6")
# create your index
index = VectorStoreIndex(leaf_nodes, storage_context=storage_context, show_progress=True, service_context=service_context, store_nodes_override=True)
#index.vector_store.persist
#index.docstore.add_documents(nodes)
#index.docstore.persist

base_retriever = index.as_retriever(similarity_top_k=10) # one may experiment with this number
retriever = AutoMergingRetriever(base_retriever, index.storage_context, verbose=True)

#initializing the reranker model
#rerank = SentenceTransformerRerank(top_n=6, model="BAAI/bge-reranker-base") # top_n open for experimentation

print("7")
#setup the query engine
query_engine = RetrieverQueryEngine.from_args(
    retriever, 
    #node_postprocessors=[rerank],
    service_context=service_context,
    #text_qa_template= PromptTemplate(DAX_template_str),
)

print("8")
#query
query = "what is the revenue of Brenntag?"
print(query)
response = query_engine.query(query)
print(response)

Query Script:

import chromadb
from llama_index.core import VectorStoreIndex
from llama_index.vector_stores.chroma import ChromaVectorStore
from llama_index.core import StorageContext
from llama_index.core.retrievers import AutoMergingRetriever
from llama_index.core.query_engine import RetrieverQueryEngine
from pathlib import Path
import sys

ROOT_PATH = Path(__file__).parents[1]
sys.path.insert(0, str(ROOT_PATH))

from constants.prompts import DAX_template_str
from lib.load_models import load_models_GPT4 

print("0")
service_context = load_models_GPT4()

print("1")
# initialize client
db = chromadb.PersistentClient(path="./chroma_db/ShortSample/")

print("2")
# get collection
chroma_collection = db.get_or_create_collection("ShortSample")

print("3")
# assign chroma as the vector_store to the context
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

print("4")
storage_context = StorageContext.from_defaults(vector_store=vector_store)

print("5")
# load your index from stored vectors
index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)

print("6")
# create a retriever
base_retriever = index.as_retriever(similarity_top_k=10) # one may experiment with this number
#storage_context = StorageContext.from_defaults(index_store=index, docstore=index.docstore)
retriever = AutoMergingRetriever(base_retriever, index.storage_context, verbose=True)

print("7")
#setup the query engine
query_engine = RetrieverQueryEngine.from_args(
   retriever, 
#   #node_postprocessors=[rerank],
   service_context=service_context,
#   #text_qa_template= PromptTemplate(DAX_template_str),
)
query_engine = index.as_query_engine()

print("8")
#query
response = query_engine.query("what is the revenue of airbus?")
print(response)
response = query_engine.query("what is the revenue of Brenntag?")
print(response)
response = query_engine.query("what is the revenue of Zalando?")
print(response)

### Relevant Logs/Tracbacks

```shell
PS D:\GenAI-Repos\GenAI-DMS-2> & d:/GenAI-Repos/GenAI-DMS-2/.venv-GenAI-DMS-2/Scripts/python.exe d:/GenAI-Repos/GenAI-DMS-2/src/UI/Doc_Intel_DAX_readOnly.py
0
1
2
3
4
5
6
7
8
Traceback (most recent call last):
  File "d:\GenAI-Repos\GenAI-DMS-2\src\UI\Doc_Intel_DAX_readOnly.py", line 58, in <module>
    response = query_engine.query("what is the revenue of airbus?")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 223, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\base\base_query_engine.py", line 51, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 223, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 189, in _query
    nodes = self.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\query_engine\retriever_query_engine.py", line 144, in retrieve
    nodes = self._retriever.retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 223, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\base\base_retriever.py", line 242, in retrieve
    nodes = self._retrieve(query_bundle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\retrievers\auto_merging_retriever.py", line 173, in _retrieve
    cur_nodes, is_changed = self._try_merging(initial_nodes)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\retrievers\auto_merging_retriever.py", line 162, in _try_merging
    nodes, is_changed_1 = self._get_parents_and_merge(nodes)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\retrievers\auto_merging_retriever.py", line 64, in _get_parents_and_merge
    parent_node = self._storage_context.docstore.get_document(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GenAI-Repos\GenAI-DMS-2\.venv-GenAI-DMS-2\Lib\site-packages\llama_index\core\storage\docstore\keyval_docstore.py", line 354, in get_document
    raise ValueError(f"doc_id {doc_id} not found.")
ValueError: doc_id 778fcb4e-8775-4965-abde-77d558a395f6 not found.
```

**Comment by SuperBobRob** [comment]
@dosu: thanks a lot, but it didn't resolve the issue. I've used the provided scripts...
any other hint?

**Comment by logan-markewich** [comment]
@SuperBobRob the auto merging retriever requires a docstore. But most vector dbs disable this to make storage easier.

You can override 
`index = VectorStoreIndex(...., store_nodes_override=True)`

But then you need to take care of saving/loading the docstore.

**Comment by SuperBobRob** [comment]
Hi @logan-markewich,

Thanks a lot for the clarification! How can I achieve the storing/loading of the docstore? I think the storing should already be done by this:

storage_context.docstore.add_documents(leaf_nodes)
storage_context.docstore.add_documents(nodes)
storage_context.docstore.persist()  # Persist the document store

So, I guess I need to change the Query-Script in order to load the docstore, right?

Thanks again and have a nice day,
Robert

**Comment by SuperBobRob** [comment]
maybe @dosu can answer this?
