### ISSUE TITLE
[Bug]: 'verbose=True' is invalid in ReactAgent's constructor

### ISSUE THREAD

**Issue by gogoriver** [run-llama/llama_index#14234]
### Bug Description

agent = ReActAgent.from_tools([], verbose=True)
some info couldn't be print out, for example, in /agent/base/runner.py:

if self.verbose:
            print(f"> Running step {step.step_id}. Step input: {step.input}")

This message failed to print out.

### Version

all

### Steps to Reproduce

Please check the source file of /main/llama-index-core/llama_index/core/agent/react/base.py line83~88:
        super().__init__(
            step_engine,
            memory=memory,
            llm=llm,
            callback_manager=callback_manager,
        )
'verbose' should be included in the params, isn't it?

**Comment by logan-markewich** [comment]
@gogoriver it supports verbose just fine

https://colab.research.google.com/drive/1j6iZlJhSHT2XNjXQdyJxGzg8h5n3ewK1?usp=sharing
