### ISSUE TITLE
[Bug]: sql_retriever = SQLRetriever(sql_database) calls str() on text nodes resulting in outputs with ... instead of full text in the node

### ISSUE THREAD

**Issue by nspielbe** [run-llama/llama_index#14240]
### Bug Description

When calling sql_retriever = SQLRetriever(sql_database) the resulting output contained ... instead of the full text contained in the node with the sql response. This code was from the intro sql tutorial online. In the code run within the SQLRetreiver we hit [this code](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/base/query_pipeline/query.py#L61-L62) in the validate and convert stringable method which calls the str(Node) which as a text node performs truncation. 

### Version

0.10.46

### Steps to Reproduce

Execute the sql retreiver with a text node with more than 350 characters and see the ... appear and str() method of the text node called.

**Comment by nspielbe** [comment]
This does not seem correct as the format method is not hit when the return raw flag is set:

    def retrieve_with_metadata(
        self, str_or_query_bundle: QueryType
    ) -> Tuple[List[NodeWithScore], Dict]:
        """Retrieve with metadata."""
        if isinstance(str_or_query_bundle, str):
            query_bundle = QueryBundle(str_or_query_bundle)
        else:
            query_bundle = str_or_query_bundle
        raw_response_str, metadata = self._sql_database.run_sql(query_bundle.query_str)
        if self._return_raw:
            return [NodeWithScore(node=TextNode(text=raw_response_str))], metadata
        else:
            # return formatted
            results = metadata["result"]
            col_keys = metadata["col_keys"]
            return self._format_node_results(results, col_keys), metadata

**Comment by logan-markewich** [comment]
A fix for this was merged and released in v0.10.47
