### ISSUE TITLE
[Bug]: There are 2 selections, please use .inds.

### ISSUE THREAD

**Issue by uniltone** [run-llama/llama_index#14258]
### Bug Description

I am working on a solution which Combining Text-to-SQL with Semantic Search. Query engine is not working as expected some times. It throws error - "There are 2 selections, please use .inds."
It works some time. In some cases it throws error.
i am using  for local vector_index and sqlite for database, SQLAutoVectorQueryEngine for queryEngine.

### Version

0.10.37

### Steps to Reproduce

https://github.com/run-llama/llama_index/issues/6982

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "/home/zwf_llama3_2.py", line 344, in <module>
    response = query_engine.query(text)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 274, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py", line 53, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/query_engine/sql_join_query_engine.py", line 312, in _query
    if result.ind == 0:
       ^^^^^^^^^^
  File "/usr/local/anaconda/lib/python3.11/site-packages/llama_index/core/base/base_selector.py", line 31, in ind
    raise ValueError(
ValueError: There are 2 selections, please use .inds.
```

**Comment by logan-markewich** [comment]
The LLM is supposed to pick one option. For some reason, it was ambiguous and picked two

**Comment by uniltone** [comment]
def load_SQLAutoVectorQueryEngine(sql_tool,vector_tool):
    query_engine = SQLAutoVectorQueryEngine(
        sql_query_tool = sql_tool,
        vector_query_tool = vector_tool,
        selector=LLMSingleSelector.from_defaults(
            prompt_template_str="Some choices are given below. It is provided in a numbered list "
                                "(1 to {num_choices}), "
                                "where each item in the list corresponds to a summary.\n"
                                "---------------------\n"
                                "{context_list}"
                                "\n---------------------\n"
                                "Using only the choices above and not prior knowledge, return "
                                "the choice most relevant to the question: '{query_str}'\n",
            output_parser=RobustSelectionOutputParser(),
        ),
        sql_vector_synthesis_prompt=DEFAULT_SQL_VECTOR_SYNTHESIS_PROMPT,
        callback_manager=callback_manager
    )
    return query_engine

**Comment by uniltone** [comment]
My prompt words are limited and I can only choose one. The problem is solved.
"choose only the one most relevant to the question: '{query_str}'\n",
