### ISSUE TITLE
[Bug]: ValueError: Failed to find python package for class MixtureOfAgentsPack

### ISSUE THREAD

**Issue by efenocchi** [run-llama/llama_index#14265]
### Bug Description

Hi @ravi03071991,
I tried to download the Mixture-Of-Agents package but got the following error: 
```
raise ValueError(f"Failed to find python package for class {llama_pack_class}")
ValueError: Failed to find python package for class MixtureOfAgents
```

### Version

0.10.47

### Steps to Reproduce

run `llamaindex-cli download-llamapack MixtureOfAgentsPack --download-dir ./mixture_of_agents_pack` or try downloading the package from code

**Comment by ravi03071991** [comment]
@efenocchi Thanks for pointing it out. I will update the readme.

Yeah, `pip install llama-index-packs-mixture-of-agents` should ideally work.

**Comment by efenocchi** [comment]
@ravi03071991 Thank you!

**Comment by efenocchi** [comment]
Hi @ravi03071991, I saw your PR, be careful that this doesn't solve the problem.

The errors are here:
`llamaindex-cli download-llamapack MixtureOfAgentsPack --download-dir ./mixture_of_agents_pack`

and here:
```python
from llama_index.core.llama_pack import download_llama_pack

# download and install dependencies
MixtureOfAgentsPack = download_llama_pack(
    "MixtureOfAgentsPack", "./mixture_of_agents_pack"
)
```

The solution is:
1) install the package with `pip install llama-index-packs-mixture-of-agents`
2) call it directly from `llama_index.packs.mixture_of_agents`:
```python
from llama_index.packs.mixture_of_agents import MixtureOfAgentsPack
from llama_index.llms.openai import OpenAI
from llama_index.llms.mistralai import MistralAI

# Add OPENAI_API_KEY and MISTRAL_API_KEY to your env variable

mixture_of_agents_pack = MixtureOfAgentsPack(
    llm=OpenAI(model="gpt-4"),  # Aggregator
    reference_llms=[
        OpenAI(model="gpt-3.5-turbo"),
        MistralAI(model="mistral-medium"),
    ],  # Proposers
    num_layers=3,
    temperature=0.1,
)
response = mixture_of_agents_pack.run("What is LlamaIndex?")
```

**Comment by logan-markewich** [comment]
the download syntax is very annoying to maintain -- we need a better way to manage it I think

**Comment by guptadhaval18** [comment]
Hi @logan-markewich, have anything in mind? Would like to work on this task. Else can send a simple fix for by updating given mapping/

**Comment by logan-markewich** [comment]
This is fixed, was just a simple update to a mappings file
