### ISSUE TITLE
Support for Multiple Vector Stores in Image Vector Store

### ISSUE THREAD

**Issue by Leonschmitt** [run-llama/llama_index#14274]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 I have a question regarding the Image Vector Store. Is Qdrant and LanceDB the only options for the Image Vector Store, or can other vector stores also be used? If other vector stores are supported, could you please provide some exampe

**Comment by logan-markewich** [comment]
I think any vector store should work?
