### ISSUE TITLE
[Question]: request_timeout problems.

### ISSUE THREAD

**Issue by arthurbrenno** [run-llama/llama_index#14285]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

I'm using gemini and constantly having 504 DEADLINE EXCEEDED problems using it.

I did not found in the documentation neither on the discord server. How can I handle such problems. In code, I've seen that Gemini model has "**generate_kwargs", but it's not used anywhere. Will this be implemented for all models?

Problematic lines:
When getting the response:
`response: ChatResponse = await self.llm.achat(messages)`

or

When instantiating the model
```py
 Gemini(
            model_name="models/gemini-1.5-flash",
            temperature=0.85,
            max_tokens=4096,
            safety_settings={
                HarmCategory.HARM_CATEGORY_HATE_SPEECH: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_HARASSMENT: HarmBlockThreshold.BLOCK_NONE,
                HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT: HarmBlockThreshold.BLOCK_NONE,
            },
        )
```

**Comment by logan-markewich** [comment]
Seems like the generate kwargs should just be used

You can set a timeout like this for example it seems 
https://stackoverflow.com/questions/78276786/gemini-python-api-deadline-exceeded
