### ISSUE TITLE
[Feature Request]: Bedrock Converse API Claude Sonnet 3.5 Support

### ISSUE THREAD

**Issue by alecl** [run-llama/llama_index#14284]
### Feature Description

This new model id was released today anthropic.claude-3-5-sonnet-20240620-v1:0

https://docs.aws.amazon.com/bedrock/latest/userguide/model-ids.html

I found it in us-east-1 region for now.

@AndreCNF did a great job with the initial PR here #14055 

### Reason

There's two allow lists of model id's that cause an error trying to use something not in the list.

BEDROCK_MODELS
BEDROCK_FUNCTION_CALLING_MODELS

### Value of Feature

Claude Sonnet 3.5 is ranked higher than Claude 3 Opus and GPT-4o while being lower cost and is a very exciting SOTA model to use in llama index

**Comment by alecl** [comment]
I added the 2 lines and confirmed it worked and then saw it was in place for the last so closing this. Thank you.

**Comment by andre94** [comment]
Hi Ale, it seems you didn't add the Claude Sonnet 3.5 model id, but the Claude 3. Can you please review it? Thanks
