### ISSUE TITLE
[Question]: doesn't even install

### ISSUE THREAD

**Issue by JohnOstrowick** [run-llama/llama_index#14298]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi  sorry. When I try pip install it gives this error for everything relating to this repo. I do not understand because python-devel is installed.

      
        × Preparing metadata (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [23 lines of output]
            + /usr/bin/python3.11 /tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef/vendored-meson/meson/meson.py setup /tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef /tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef/.mesonpy-ucsk3gmw -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --native-file=/tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef/.mesonpy-ucsk3gmw/meson-python-native-file.ini
            The Meson build system
            Version: 1.2.99
            Source dir: /tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef
            Build dir: /tmp/pip-install-4d2u2j0g/numpy_abd2e8ff71514fbea7f84a00a17270ef/.mesonpy-ucsk3gmw
            Build type: native build
            Project name: NumPy
            Project version: 2.0.0
            C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
            C linker for the host machine: cc ld.bfd 2.38
            C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
            C++ linker for the host machine: c++ ld.bfd 2.38
            Cython compiler for the host machine: cython (cython 3.0.10)
            Host machine cpu family: x86_64
            Host machine cpu: x86_64
            Program python found: YES (/usr/bin/python3.11)
            Found pkg-config: /usr/bin/pkg-config (0.29.2)
            Run-time dependency python found: YES 3.11
            Has header "Python.h" with dependency python: NO
      
            ../meson.build:44:2: ERROR: Problem encountered: Cannot compile `Python.h`. Perhaps you need to install python-dev|python-devel

**Comment by logan-markewich** [comment]
Seems like a weird install issue with python? Or a general machine issue? I would just reinstall python tbh. This isn't related to llamaindex though? (You can see here it's trying to install numpy, I think)

**Comment by perfectra1n** [comment]
Yeah the error tells you what you need on your machine:
```
Perhaps you need to install python-dev|python-devel
```

You'll need to use `apt` to install either `python-dev` or `python-devel`:
```sh
sudo apt update
sudo apt install python-dev
sudo apt install python-devel
```

**Comment by JohnOstrowick** [comment]
Hi Thanks. I did in fact do that and it doesn't help for some reason. I'm
just wondering what pip package is breaking and what it depends on. It does
this with many of the dependencies.

**Comment by JohnOstrowick** [comment]
> Seems like a weird install issue with python? Or a general machine issue? I would just reinstall python tbh. This isn't related to llamaindex though? (You can see here it's trying to install numpy, I think)

Thanks for this suggestion. I tried that as well :( But I get that it's not specific to llama_index now.
