### ISSUE TITLE
[Bug]: llama_index run graphstore persist without any error. However, there is no json file in persist dir

### ISSUE THREAD

**Issue by zydmtaichi** [run-llama/llama_index#14294]
### Bug Description

use Neo4jGraphStore to initial a graphstore then persist to local dir. the program exit with no error but the dir is still empty.
neo4j database is online and has 88 nodes.
seems the persist method fails and raise nothing

### Version

0.10.46

### Steps to Reproduce

import nest_asyncio
nest_asyncio.apply()

from llama_index.graph_stores.neo4j import Neo4jGraphStore

graph_store = Neo4jGraphStore(
    username="neo4j",
    password="neo4j",
    url="bolt://localhost:7687",
    database="graphstore",
)

graph_store.persist(persist_path="F:/gstore/gstore.json")

run the code above and you'll find no json created under persist_path

**Comment by logan-markewich** [comment]
@zydmtaichi there is nothing to persist, the data is all in neo4j already.

The persist method is merely `pass`, so that when you call persist on the storage context, everything else can save without error 

Since it's all in neo4j already, you can just connect back to it 
https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_neo4j/?h=neo4j#loading-from-an-existing-graph

**Comment by zydmtaichi** [comment]
> @zydmtaichi there is nothing to persist, the data is all in neo4j already.
> 
> The persist method is merely `pass`, so that when you call persist on the storage context, everything else can save without error
> 
> Since it's all in neo4j already, you can just connect back to it https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_neo4j/?h=neo4j#loading-from-an-existing-graph

@logan-markewich the link above can only use for graph created by PropertyGraphIndex. other kinds of graphs created by KnowledgeGraphIndex or maybe manually edited in neo4j can not load from existing neo4j database. that's why i try to export my KnowledgeGraphIndex graph to local using persist method. unfortunately it's still not working. pls tell me how to load these graph as llama index?

**Comment by nick-youngblut** [comment]
> Check Dependencies: Ensure all prerequisites for Neo4jGraphStore are met, including the installation of the neo4j Python package and the APOC plugin in your Neo4j database

This is not in the [Neo4jKGIndexDemo docs](https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo). I'm going to create a separate issue for this lack-of-docs issue.

**Comment by WQL782795** [comment]
@logan-markewich 
---

Indeed, KnowledgeGraphIndex only has from_documents, and not from_existing.
I have a few questions:
1. What is the difference between KnowledgeGraphIndex and PropertyGraphIndex, and which one should I use if I want to create a knowledge graph-based question and answer system?
2. If I choose to use KnowledgeGraphIndex for a knowledge graph question and answer system, how should I import existing data from neo4j? PropertyGraphIndex can import, but this is not applicable for KnowledgeGraphIndex.
I hope to receive your reply soon, thank you very much!

---

**Comment by zydmtaichi** [comment]
+1, I also want to get the answer about @WQL782795 's question. /assign logan-markewich   pls reopen this issue
