### ISSUE TITLE
[Bug]: UnstructuredElementNodeParser can't parse Table Element in html

### ISSUE THREAD

**Issue by hrhrng** [run-llama/llama_index#14301]
### Bug Description

I’m trying to run `docs/docs/examples/query_engine/sec_tables/tesla_10q_table.ipynb`, but no tables are being parsed. After debugging the source code, I found that the condition
```
if "unstructured.documents.html.HTMLTable" in str(type(element)):
```
in `llama_index/core/node_parser/relational/unstructured_element.py:110` is not being satisfied. It appears that the unstructured library returns a `unstructured.elements.Table` object instead of `unstructured.documents.html.HTMLTable` when it recognize a table element in html file. I suspect this discrepancy is causing the tables to not be recognized and parsed correctly. Could this be due to the version of my unstructured library, or other reasons?

### Version

0.10.47

### Steps to Reproduce

pip install unstructured and run `docs/docs/examples/query_engine/sec_tables/tesla_10q_table.ipynb`

**Comment by logan-markewich** [comment]
Probably due to unstructured changing how their types work over time. Would need a PR to fix

**Comment by tibor-reiss** [comment]
@hrhrng Could you please check if the linked PR fixes this?
