### ISSUE TITLE
[Documentation]: Neo4jKGIndexDemo lacks info on neo4j APOC dependency

### ISSUE THREAD

**Issue by nick-youngblut** [run-llama/llama_index#14332]
### Documentation Issue Description

[Neo4jKGIndexDemo](https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo/) lacks info on the need to install APOC for neo4j. This is crucial information in order to run the [Neo4jKGIndexDemo](https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo/)  code.

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo/

**Comment by logan-markewich** [comment]
The Neo4jGraphStore is slightly deprecated at this point fyi, replaced by the newer property graph index and Neo4jPropertyGraphStore

The need for APOC is mentioned (albeit implicitly) in the docker command here
https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_neo4j/?h=neo4jproperty#docker-setup

Happy to accept a PR to update any documentation to be more explicit

**Comment by nick-youngblut** [comment]
Thanks for the quick resply and info! 

> Happy to accept a PR to update any documentation to be more explicit

I would, but as naive user of llama-index and neo4j, I'm not a good choice for writing the documentation, given that I would likely introduce errorenous/incomplete information to the docs. Of course, you could potentially identify errors in the PR, but then that's about the same amount of work as directly writing the PR.
