### ISSUE TITLE
[Bug]: ChromaVectorStore ._get() function extracts only the first character of the node id_

### ISSUE THREAD

**Issue by Timotheevin** [run-llama/llama_index#14355]
### Bug Description

When calling the _get() function of a ChromaVectorStore object, the id_ of the node(s) extracted is only the first character of the id, instead of the entire string. Therefore, this triggers id duplication issues.

### Version

0.10.39.post1

### Steps to Reproduce

Code to reproduce :
```
vector_store = ChromaVectorStore(chroma_collection=vector_store.collection)
node vector_store._get(limit=1, where={}).nodes
```

In the source code, in llama_index/chroma/base.py:370 in _get():
```
for node_id, text, metadata in zip(
            results["ids"][0], results["documents"], results["metadatas"]
        ):
```

It seems the instruction `results["ids"][0]` only takes the first character

**Comment by Timotheevin** [comment]
```
for node_id, text, metadata in zip(
        results["ids"][0], results["documents"], results["metadatas"]
    )
```
This part of the code seems wrong to me as it takes the first element of the list results["ids"] but it should take the entire list instead.

**Comment by Timotheevin** [comment]
@dosu 

Yes, that would be perfect. Is it going to get fixed in the source code then ?

**Comment by logan-markewich** [comment]
This issue was fixed earlier today and merged.
