### ISSUE TITLE
[Bug]:  Something needs to be updated with chromadb

### ISSUE THREAD

**Issue by startakovsky** [run-llama/llama_index#14361]
### Bug Description

https://github.com/chroma-core/chroma/issues/2407#issuecomment-2187494105

### Version

Latest

### Steps to Reproduce

`import chromadb`

**Comment by logan-markewich** [comment]
Install numpy < 2.0

We have numpy pinned in llama-index-core already, but only in latest versions.

**Comment by logan-markewich** [comment]
Not really a llama-index issue per say here

**Comment by startakovsky** [comment]
https://github.com/chroma-core/chroma/issues/2407#issuecomment-2187899426

**Comment by startakovsky** [comment]
I see, so the dependencies here are listed below, curious why I seem to end up at `chroma 0.5.0` when installing from scratch with no preference. I will try to fix it by explicitly stating the version.

https://github.com/run-llama/llama_index/blob/962853b4039b8465a12dad745c12e769aadc3322/llama-index-integrations/vector_stores/llama-index-vector-stores-chroma/pyproject.toml#L32-L35
