### ISSUE TITLE
[Question]: HuggingFace model from local file path

### ISSUE THREAD

**Issue by lyie28** [run-llama/llama_index#14367]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can I load a local fine-tuned model with HF framework from a local file path, rather than uploading it to the hub and using the HF hub slug?

**Comment by lyie28** [comment]
Hi @dosu

Basically I am using a framework that expects a LlamaIndex LLM, but I have a local fine-tuned model using the HF framework. I wanted to know if I can create a LlamaIndex LLM object from the local model without needing to upload the HF local model to the hub.

I have only seen examples of HF integrations like the following which use the HF hub slug.

```python
from llama_index.llms.huggingface import HuggingFaceLLM
llm = HuggingFaceLLM(model_name="HuggingFaceH4/zephyr-7b-alpha")
```

**Comment by logan-markewich** [comment]
Dosu is correct above
