### ISSUE TITLE
[Feature Request]: llama-index can't reduce the dim of embedding vector, need to add option to control num of vec features

### ISSUE THREAD

**Issue by zydmtaichi** [run-llama/llama_index#14394]
### Feature Description

I initial a vector store by `MilvusVectorStore` and set the dim as 128. my program use the embedding model `milkey/gte:large-zh-f16` through `OllamaEmbedding` which returns 1024 features in embed vector. it raised a error when the dim between store and embedding mechanism is not equal. I want to know if there is some method to apply option to change the dim of embedding vector.

**Comment by logan-markewich** [comment]
You need to recreate the vector store from scratch, it can't be changed on the fly
