### ISSUE TITLE
[Bug]: KnowledgeGraphIndex.from_documents ignoring set llm

### ISSUE THREAD

**Issue by mackenziedott** [run-llama/llama_index#14430]
### Bug Description

While attempting to load documents into a KnowledgeGraphIndex, i keep timing out on _openAI completion call, Checking my path to the OpenAILike and running a different method, it seems to be executing just fine otherwise. I've set my OpenAIKey to 'fake' as I don't want any communication to OpenAI. I'm unsure what could be causing this issue as my normal RAG pipeline using the same model is working fine. 

### Version

0.10.50

### Steps to Reproduce

```shell
from llama_index.llms.openai_like import OpenAILike
llmProp = configs['llm_properties']
  
print(configs['llm'])
llm = OpenAILike(
              
                model=llmProp['model'],
                api_base = configs['llm'].replace('/completions', ''),
                api_key="fake",
                max_tokens=llmProp['max_tokens'],
                logprobs=llmProp['logprobs'],
                temperature=llmProp['temperature'],
                top_p=llmProp['top_p'],
                top_k=llmProp['top_k'],
                additional_kwargs = {'echo':llmProp['echo']},
                )
Settings.llm = llm
graph_store = Neo4jGraphStore(
    username=username,
    password=password,
    url=url,
    database=database,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

reader = SimpleDirectoryReader(
   input_files=pdfs
)
Settings.chunk_overlap=50
Settings.chunk_size=512
docs = reader.load_data(show_progress=True, )


index = KnowledgeGraphIndex.from_documents(
    docs,
    storage_context=storage_context,
    llm=llm,
    max_triplets_per_chunk=10
)
```
### Relevant Logs/Tracbacks

```shell
INFO:openai._base_client:Retrying request to /completions in 0.802545 seconds
Retrying request to /completions in 0.802545 seconds
INFO:openai._base_client:Retrying request to /completions in 1.782454 seconds
Retrying request to /completions in 1.782454 seconds
INFO:openai._base_client:Retrying request to /completions in 3.479021 seconds
Retrying request to /completions in 3.479021 seconds
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._complete in 0.25277889074673177 seconds as it raised APIConnectionError: Connection error..
Retrying llama_index.llms.openai.base.OpenAI._complete in 0.25277889074673177 seconds as it raised APIConnectionError: Connection error..
INFO:openai._base_client:Retrying request to /completions in 0.799029 seconds
Retrying request to /completions in 0.799029 seconds
INFO:openai._base_client:Retrying request to /completions in 1.908156 seconds
Retrying request to /completions in 1.908156 seconds
INFO:openai._base_client:Retrying request to /completions in 3.990974 seconds
Retrying request to /completions in 3.990974 seconds
WARNING:llama_index.llms.openai.utils:Retrying llama_index.llms.openai.base.OpenAI._complete in 1.2667151135404542 seconds as it raised APIConnectionError: Connection error..
Retrying llama_index.llms.openai.base.OpenAI._complete in 1.2667151135404542 seconds as it raised APIConnectionError: Connection error..
INFO:openai._base_client:Retrying request to /completions in 0.881817 seconds
Retrying request to /completions in 0.881817 seconds
INFO:openai._base_client:Retrying request to /completions in 1.745545 seconds
Retrying request to /completions in 1.745545 seconds
INFO:openai._base_client:Retrying request to /completions in 3.904172 seconds
Retrying request to /completions in 3.904172 seconds
```

**Comment by mackenziedott** [comment]
UPDATE: I think I determine the issue. I use Settings.embed_model = HuggingfaceEmbedding, and once i set embed_model=embed_model in the KnowledgeGraphIndex.fromDocuments, it works. This appears to be that the function is not reading in the Settings.embed_model.

**Comment by mackenziedott** [comment]
@dosu

The issue is that I've set my LLM and Embedmodel to models that don't require an OpenAI key

**Comment by mackenziedott** [comment]
@dosu
Other functions (such as query_engine) that are set-up similarly do not suffer this issue

**Comment by logan-markewich** [comment]
@mackenziedott you are using openai-like, which uses the openai client 🤔 

I'm not sure what the issue is here, but you can check the llm attached to the index with `print(index._llm)`. This is the llm used for extracting triplets
<img width="824" alt="image" src="https://github.com/run-llama/llama_index/assets/22285038/b134cc8e-4d81-4358-97bc-d391cf06370f">

**Comment by mackenziedott** [comment]
@dosu
I want to try something. How do i turn off async document loading?

**Comment by mackenziedott** [comment]
> @mackenziedott you are using openai-like, which uses the openai client 🤔 so the logs about using openai are kind of expected?
> 
> I'm not sure what the issue is here, but you can check the llm attached to the index with `print(index._llm)`. This is the llm used for extracting triplets <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/22285038/343867058-b134cc8e-4d81-4358-97bc-d391cf06370f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MDczMjUsIm5iZiI6MTcxOTUwNzAyNSwicGF0aCI6Ii8yMjI4NTAzOC8zNDM4NjcwNTgtYjEzNGNjOGUtNGQ4MS00MzU4LTk3YmMtZDM5MWNmMDYzNzBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDE2NTAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOThmNTZkNjdiZTI3ZDQ4ZDMxODA0MjE2ZWQwY2Y1NmNiNTU3ZGNjZTRlZGVmYjJmZTZlYmQ2YmE2NTAwYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6BJPXVYB5tcIAdjKS5ozAGpx0VUyUKBvVEnD7yIdFZM">

Thanks! I think I might know the issue, I wonder if i'm overloading my API with aysnc calls. Its weird, because i can call the endpoints with other functions (standard RAG completion) just fine. I experimented with the PropertyGraphIndex, which i run into the same issue after it parses the nodes and starts attempting to extract from text, it can do up to 6 before running into the same issue.
