### ISSUE TITLE
[Documentation]: The llamaindex.ai page directs to 404 Not Found Page for Examples

### ISSUE THREAD

**Issue by abdul-1996** [run-llama/llama_index#14447]
### Documentation Issue Description

llamaindex.ai currently directs to: https://github.com/jerryjliu/llama_index/blob/main/examples/

But the location examples seems to be changed and new location is: https://github.com/run-llama/llama_index/tree/main/docs/docs/examples

### Documentation Link

https://github.com/jerryjliu/llama_index/blob/main/examples/

**Comment by logan-markewich** [comment]
I'm kind of lost, where is this linked from? What page?

**Comment by abdul-1996** [comment]
@logan-markewich,  Sorry I should have been more clear, 

on this [documentation](https://docs.llamaindex.ai/en/stable/understanding/putting_it_all_together/q_and_a/ ) page, under Guides section the hyperlinks for Notebooks are broken and as mentioned the correct link should be https://github.com/run-llama/llama_index/tree/main/docs/docs/examples
