### ISSUE TITLE
  kg_extractor = SchemaLLMPathExtractor(   File "/home/cdhd/PythonCode/pythonProject/.venv/lib/python3.10/site-packages/llama_index/core/indices/property_graph/transformations/schema_llm.py", line 235, in __init__     super().__init__(   File "/home/cdhd/PythonCode/pythonProject/.venv/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__     raise validation_error pydantic.v1.error_wrappers.ValidationError: 1 validation error for SchemaLLMPathExtractor kg_validation_schema   value is not a valid dict (type=type_error.dict)[Question]: 

### ISSUE THREAD

**Issue by li-hhhh** [run-llama/llama_index#14481]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

我在使用neo4j进行图像构造时，使用的validation_schema为官网上的列表形式，如下：validation_schema = [
    ("ORGANIZATION", "HAS", "PERSON"),
    ("PERSON", "WORKED_AT", "ORGANIZATION"),
    ("PERSON", "WORKED_WITH", "PERSON"),
    ("PERSON", "WORKED_ON", "ORGANIZATION"),
    ("PERSON", "PART_OF", "ORGANIZATION"),
    ("ORGANIZATION", "PART_OF", "ORGANIZATION"),
    ("PERSON", "WORKED_AT", "PLACE"),
]
但是运行时报错，表示需要字典形式，但是我希望使用列表形式，去表示实体-关系-实体。应该如何去成功的调用。

**Comment by li-hhhh** [comment]
> To successfully call the with your preferred list format for the , you need to ensure that the is provided as a list. The code will automatically convert this list into the required dictionary format with a "relationships" key.`SchemaLLMPathExtractor``validation_schema``validation_schema`
> 
> Here is an example of how you can call the :`SchemaLLMPathExtractor`
> 
> ```python
> from llama_index.core.indices.property_graph.transformations.schema_llm import SchemaLLMPathExtractor
> 
> # Define your preferred list format for the validation schema
> validation_schema = [
>     ("ORGANIZATION", "HAS", "PERSON"),
>     ("PERSON", "WORKED_AT", "ORGANIZATION"),
>     ("PERSON", "WORKED_WITH", "PERSON"),
>     ("PERSON", "WORKED_ON", "ORGANIZATION"),
>     ("PERSON", "PART_OF", "ORGANIZATION"),
>     ("ORGANIZATION", "PART_OF", "ORGANIZATION"),
>     ("PERSON", "WORKED_AT", "PLACE"),
> ]
> 
> # Initialize the SchemaLLMPathExtractor
> extractor = SchemaLLMPathExtractor(
>     llm=your_llm_instance,  # Replace with your LLM instance
>     extract_prompt=your_extract_prompt,  # Replace with your extract prompt if any
>     kg_validation_schema=validation_schema,
>     num_workers=4,  # Adjust the number of workers as needed
>     max_triplets_per_chunk=10,  # Adjust the max triplets per chunk as needed
>     strict=True  # Set strict mode as needed
> )
> 
> # Call the extractor with your nodes
> nodes = [your_node_list]  # Replace with your list of nodes
> extracted_nodes = extractor(nodes, show_progress=True)
> ```
> 
> In this example, the is provided as a list of triplets. The will handle the conversion to the required dictionary format internally `validation_schema``SchemaLLMPathExtractor`[[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/property_graph/transformations/schema_llm.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._


谢谢你的建议，我的代码部分如下：
entities = Literal["有数据无曲线", "数据正常采集，但是导出没有数据，硬盘也够用", "查看硬盘容量是否正常,如果满了,表示数据能正常采集,但无法存到硬盘上,因而无法展示曲线.尝试清理硬盘或更换硬盘", "1.可能是数据中间有错误数据(比如中间有大于当前时间的数据，导至数据检索错误)解决办法:用数据修复工具修复就可以了； 2.数据采集间隔是否为1秒，如果大于1秒会出现断点曲线不连接的情况，设置曲线断点连接跨度大一些，不能整点时间显示曲线。"]
relations = Literal["ANSWER","QUESTION"]
validation_schema = [
    ("有数据无曲线", "ANSWER", "查看硬盘容量是否正常,如果满了,表示数据能正常采集,但无法存到硬盘上,因而无法展示曲线.尝试清理硬盘或更换硬盘"),
    ("数据正常采集，但是导出没有数据，硬盘也够用", "ANSWER", "1.可能是数据中间有错误数据(比如中间有大于当前时间的数据，导至数据检索错误)解决办法:用数据修复工具修复就可以了； 2.数据采集间隔是否为1秒，如果大于1秒会出现断点曲线不连接的情况，设置曲线断点连接跨度大一些，不能整点时间显示曲线。"),

]

kg_extractor = SchemaLLMPathExtractor(
    llm=llm,
    possible_entities=entities,
    possible_relations=relations,
    kg_validation_schema=validation_schema,
    # if false, allows for values outside of the schema
    # useful for using the schema as a suggestion
    strict=True,
)
在这里运行报错：表示validation_schema需要是字典类型，但是我希望能正常使用列表，或者如果使用字典，应该如何表示出我想要的实体-关系-实体这样的关系呢

**Comment by logan-markewich** [comment]
@li-hhhh do you have the latest version? `pip install -U llama-index` or `pip install -U llama-index-core`
