### ISSUE TITLE
[Bug]: text_embedding_inference. JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by nitskoh** [run-llama/llama_index#14487]
### Bug Description

I tried running the code snippet in this example 
https://docs.llamaindex.ai/en/stable/examples/embeddings/text_embedding_inference/

I got the following error
```
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-26-a7c0f9477fcc> in <cell line: 13>()
     11 
     12 
---> 13 embeddings = embed_model.get_text_embedding("Hello World!")
     14 print(len(embeddings))
     15 print(embeddings[:5])

8 frames
/usr/lib/python3.10/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Version

Using the colab notebook provided

### Steps to Reproduce

Running the colab notebook here

https://docs.llamaindex.ai/en/stable/examples/embeddings/text_embedding_inference/

**Comment by nitskoh** [comment]
This does not help. As I am using your example

**Comment by SID262000** [comment]
@nitskoh Looks like the very first step is to deploy the embedding server which sounds like a paid option as described [here](https://huggingface.co/blog/inference-endpoints-embeddings).
cc: @namin @tobi

**Comment by logan-markewich** [comment]
Its not paid, but you need to deploy it somewhere before you can use it (local docker, was, etc.)

**Comment by SID262000** [comment]
Thanks for the note, @logan-markewich. Which of the deployment methods have you used?
