### ISSUE TITLE
[Question]: Is it possible to add a new document after the RAPTOR is constructed?

### ISSUE THREAD

**Issue by silviachen46** [run-llama/llama_index#14506]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My document tree is very large, and I wonder if it's possible to avoid re-constructing the whole tree everytime a new document comes in. I read through the implementation of insert function in base.py, but it seems this one only insert high-level nodes instead of adding new leaf node. If I want to build a new function that inserts new document as leaf node, are there any specific parts in current code that might be helpful?

**Comment by silviachen46** [comment]
@dosu, what does this line cur_nodes = run_transformations(documents, transformations, in_place=False) do? Is it a SentenceSplitter(chunk_size=400, chunk_overlap=50) that chunks the document into small pieces and encapsulates them into leaf text nodes?

**Comment by silviachen46** [comment]
@dosu what does the in_place bool value do here? Does it means that we create a copy of the original documents and split on them?
will I be able to track the original document from each of the text node if they are retrieved? if so, can you provide an example on how to do so?

**Comment by silviachen46** [comment]
@dosu is the curr_nodes returned here a list of text nodes that each of them contains the whole document but after being splitted OR each of the text nodes contains a chunk of one of the documents?

**Comment by logan-markewich** [comment]
@silviachen46 its not implemented currently, mostly because its complicated to do

If I was to do it, I might keep track of how many documents I've inserted since the last time everything was re-clustered. And after some threshold, actually recluster everything

If under the threshold, you just have to insert into the bottom level cluster that best matches that new document (not entirely sure how to do that though)

**Comment by silviachen46** [comment]
> @silviachen46 its not implemented currently, mostly because its complicated to do
> 
> If I was to do it, I might keep track of how many documents I've inserted since the last time everything was re-clustered. And after some threshold, actually recluster everything
> 
> If under the threshold, you just have to insert into the bottom level cluster that best matches that new document (not entirely sure how to do that though)

@logan-markewich Thanks! I've been trying to work on this feature. Instead of doing recluster, I was thinking of re-summarize from the leaf nodes changed to the parent nodes and all the way to the root cuz in my case there's about 7000+ documents and re-summarize all of them would be slow and expensive. It is complicated to do :)
