### ISSUE TITLE
[Feature Request]: Add support for LiteLLM

### ISSUE THREAD

**Issue by david1542** [run-llama/llama_index#14509]
### Feature Description

Hi everyone,

We're currently working on an [open-source](https://github.com/merlinn-co/merlinn) project that uses llama-index in order to ingest + embed some data into ChromaDB.

Initially we were coupled to OpenAI and used solely the `OpenAIEmbedding` class in our ingestion pipeline. However, we were requested to add support to other LLM providers & instances. That made us use [LiteLLM Proxy Server](https://docs.litellm.ai/docs/simple_proxy).

We have written a new class internally that inherits from `BaseEmbedding` and communicates with the proxy server, and we were thinking this can be a nice contribution to llama-index, so more users can communicate with their LiteLLM proxy server.

You can see our implementation [here](https://github.com/merlinn-co/merlinn/blob/main/services/data-processor/src/embeddings.py). We've called the new class `LiteLLMEmbedding`

### Reason

Allow llama-index to use LiteLLM as an embedding proxy to other vendors.

### Value of Feature

More users could abstract their embedding vendor and create an agnostic code.

**Comment by logan-markewich** [comment]
@david1542 you could propose a PR with this new class?

**Comment by david1542** [comment]
@logan-markewich Created a PR [here](https://github.com/run-llama/llama_index/pull/14523). Lemme know what you think. Tested it locally with my own LiteLLM proxy server, and added some unit tests.
