### ISSUE TITLE
[Documentation]: Llama3-Instruct HuggingFaceLLM docs should specify it is a chat model.

### ISSUE THREAD

**Issue by jdwh08** [run-llama/llama_index#14516]
### Documentation Issue Description

_**Hello world!**_

The Llama3 Cookbook for Llama3-8b-Instruct **should specify that Instruct is a chat model**; this is particularly **important for ResponseSynthesizer/QueryEngine use cases to avoid missing end-of-turn tokens** and long prompt overruns.

**Currently, we have:**
```python
llm = HuggingFaceLLM(
    model_name="meta-llama/Meta-Llama-3-8B-Instruct",
    model_kwargs={
        "token": hf_token,
        "torch_dtype": torch.bfloat16,  # comment this line and uncomment below to use 4bit
        # "quantization_config": quantization_config
    },
    generate_kwargs={
        "do_sample": True,
        "temperature": 0.6,
        "top_p": 0.9,
    },
    tokenizer_name="meta-llama/Meta-Llama-3-8B-Instruct",
    tokenizer_kwargs={"token": hf_token},
    stopping_ids=stopping_ids,
    # missing 'is_chat_model'=True
)
```

**We can see the issues of not specifying the chat format when we run**
```python
response = llm.complete("Who is Paul Graham?")
print(response)
```
which outputs 
```
Paul Graham is an American entrepreneur, venture capitalist, and author. He is the co-founder of the venture capital firm Y Combinator, which has backed companies such as Airbnb, Dropbox, and Reddit...
What is Y Combinator? Y Combinator is a venture capital firm that provides seed funding and support to early-stage startups. [continued for several more sections...]
```

Notice how this results in a huge prompt overrun in the output, where the model starts generating new questions that are less relevant to the initial user prompt (_What is Y Combinator_, _What are some of the companies that Y Combinator has backed?_) and continues answering beyond the original prompt.

\
**Why is this the case?**
Recall that Llama3-8b-Instruct has a special format (https://github.com/meta-llama/llama-recipes), of the form
```
<|begin_of_text|><|start_header_id|>system<|end_header_id|>

{{ system_prompt }}<|eot_id|><|start_header_id|>user<|end_header_id|>

{{ user_message_1 }}<|eot_id|><|start_header_id|>assistant<|end_header_id|>

{{ model_answer_1 }}<|eot_id|><|start_header_id|>user<|end_header_id|>
```
This special format **strongly suggests we should use the chat format from the model's tokenizer** (i.e., `apply_chat_template`). 

\
\
**Why does this matter?**
Llama3-8B-Instruct is currently an important model because it fills the niche of being high quality, small, reputable, and instruction-tuned.

When we use Llama3-8B in a ReponseSynthesizer as part of a QueryEngine, e.g., Refine
(https://github.com/run-llama/llama_index/blob/ff235407bd32a6ae82e55a9edf73a099cb132459/llama-index-core/llama_index/core/response_synthesizers/refine.py#L202)

it is running `get_program_for_llm`, which I believe eventually gets a `LLMTextCompletionProgram`, which eventually leads to this choice: 
(https://github.com/run-llama/llama_index/blob/ff235407bd32a6ae82e55a9edf73a099cb132459/llama-index-core/llama_index/core/program/llm_program.py#L90)

We probably want to be sure that Llama Index is running any queries through the `.chat` process, and not the `.complete` process, to ensure the AutoTokenizer chat format is being applied, so that there aren't any major prompt overruns due to the <|eot_token|> tag not generating from bad input format.

This was a major cause of suboptimal output due to prompt overruns in our RAG system based on LlamaIndex/Llama3-8B-Instruct.

\
Thanks!
`- jdwh08`

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/cookbooks/llama3_cookbook/

**Comment by Timotheevin** [comment]
Hey, thanks for the issue @jdwh08 !

I wanted to open an issue on the same topic but I'll use this one to ask my question.
I am using LLama-3-8B-Instruct outside of the Cookbook and I am loading is from HuggingFace using the HuggingFaceLLM object just as in the cookbook. I was wondering if it was possible to set the attribute 'is_chat_model' automatically to True as the tokenizer given as argument to HuggingFaceLLM actually has a "apply_chat_template" attribute.

This would help a lot because as @jdwh08 mentioned, if you forget to specify 'is_chat_model' = True when creating the HuggingFaceLLM object, then when using the LLM for query engine/response synthesizer, the output doesn't have the right formatting for LLama-3 instructions.

Many thanks !
