### ISSUE TITLE
[Question]: ReACT agent talking to itself and hallucinating

### ISSUE THREAD

**Issue by fawazPhc** [run-llama/llama_index#14520]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm new to creating a custom ReACT agent to query my data using the RAG technique.
It turns out that my locally running LLama2 7B model(Using Ollama) does fine with questions about my data(I added the retriever as a Queryengine tool) but for casual conversations, it ends up calling the tool nevertheless and hallucinates.
To overcome I created a separate index for casual conversations and added the retriever as another query engine tool. As expected when I start the casual conversation it does end up calling the specified tool but later hallucinates by talking to itself(at least that's what I think).
Is it because I'm using a lightweight local model or do I have to change how I approach it?
Here is my code. Since the ReACT used to call tools if I started a casual convo, I had to add another index of casual conversations in the pinecone db. The data I used,is also attached.

I want the model to use its already pre-built-in knowledge like casual convo and reply based on that instead of relying on a tool, even if it does rely on the tool it doesn't use the information I provided. Its like the agent is using the information it retrieves as part of its internal thinking process and mistakenly treating it as a new input rather than forming a final response.You can view the attached image for more clarity.Agent is able to respod to a "hi" using the tool but it hallucinates when I ask "how are you doing?"

![Screenshot 2024-06-29 164412](https://github.com/run-llama/llama_index/assets/170261891/6fb99aba-5dca-4d61-a825-a98d6e80507e)
![Screenshot 2024-07-02 120600](https://github.com/run-llama/llama_index/assets/170261891/942a8b52-0e1c-43b0-996b-f22cf05ce822)

```python
index_name = "custom-data"
pinecone_index = pc.Index(index_name)
pinecone_index_2 = pc.Index("casualconversation")

vector_store = PineconeVectorStore(pinecone_index=pinecone_index)
vector_store_2 = PineconeVectorStore(pinecone_index=pinecone_index_2)

vector_index = VectorStoreIndex.from_vector_store(vector_store=vector_store)
vector_index_2 = VectorStoreIndex.from_vector_store(vector_store=vector_store_2)


llm = Ollama(model="llama3", request_timeout=1000000)
retriever = VectorIndexRetriever(index=vector_index, similarity_top_k=5)
retriever_2 = VectorIndexRetriever(index=vector_index_2, similarity_top_k=5)


tools = [
    QueryEngineTool(
        query_engine=RetrieverQueryEngine(retriever=retriever),
        metadata=ToolMetadata(
            name="phc_data",
            description="this has data for the company XYZ ",
        ),
    ),
    QueryEngineTool(
        query_engine=RetrieverQueryEngine(retriever=retriever_2),
        metadata=ToolMetadata(
            name="casualconversation",
            description="Use this whenever the user asks a casual question or for casual conversations",
        ),
    ),
]
agent = ReActAgent.from_tools(
    tools=tools,
    llm=llm,
    verbose=True,
    # context=context
)



response = agent.chat("Hi")
print(str(response))
response=agent.chat("How are you doing?")
print(str(response))

```

**Comment by VictorAny** [comment]
+ 1 on this. I had to talk to the raw llm and add my previous messages to the raw query string, instead of using ReactAgent since it kept doing the weirdest/most unnecessary looping to a simple "Hi"

**Comment by ujitkumar1** [comment]
any fix for this, In my case, the Agent is posing a question but attempts to process the response on its own instead of directing it to the user for input?
