### ISSUE TITLE
[Bug]: ImportError: cannot import name 'Settings' from 'llama_index.core' (unknown location)

### ISSUE THREAD

**Issue by WSDzju** [run-llama/llama_index#14530]
### Bug Description

like the title

### Version

 0.10.51

### Steps to Reproduce

import os
import os.path
import logging
from typing import Any, List
import tiktoken
from llama_index.core import Settings
from llama_index.core.schema import QueryBundle
from llama_index.core.embeddings import BaseEmbedding
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.embeddings.openai import OpenAIEmbeddingModelType
from llama_index.core.callbacks import CallbackManager, TokenCountingHandler
from llama_index.core import (VectorStoreIndex, SimpleDirectoryReader, StorageContext, load_index_from_storage)

**Comment by logan-markewich** [comment]
Uninstall completely or start with a new venv 

I might do 

```
pip freeze | grep llama_index | xargs pip uninstall -y
pip install llama-index 
```

**Comment by WSDzju** [comment]
> Uninstall completely or start with a new venv
> 
> I might do
> 
> ```
> pip freeze | grep llama_index | xargs pip uninstall -y
> pip install llama-index 
> ```

I start a new venv，THK！
