### ISSUE TITLE
[Bug]: No module named 'llama_index.retrievers'

### ISSUE THREAD

**Issue by BarryYin** [run-llama/llama_index#14542]
### Bug Description

when I import the BM25Retriever...
from llama_index.retrievers.bm25 import BM25Retriever
show the error
 from llama_index.retrievers.bm25 import BM25Retriever
ModuleNotFoundError: No module named 'llama_index.retrievers'

### Version

0.10.50

### Steps to Reproduce

from llama_index.retrievers.bm25 import BM25Retriever

**Comment by logan-markewich** [comment]
@BarryYin every integration is a package, so you'd have to install it first

`pip install llama-index-retrievers-bm25`
