### ISSUE TITLE
[Question]: Can we split query engine's query 

### ISSUE THREAD

**Issue by pulkitmehtaworkmetacube** [run-llama/llama_index#14559]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 I have a inference pipeline deployed on serverless google cloud function where i am getting stored index from a cloud bucket and then it has alibaba nlp embedding model and llama3 llm .
My problem is that while doing inference I need to set embedding model in settings.embed_model . My embedding model is hosted on vertex ai , now to fulfil this requirement , i need to again load the model and this adds up in each inference. Is there a way I can just get the embeddings of query and get the response ?

**Comment by logan-markewich** [comment]
I'm not sure what you mean?

Initializing a vertex ai embedding model should be zero cost. It's just creating a client?

And in any case, you need the embedding model to get the embeddings of the query no?

**Comment by pulkitmehtaworkmetacube** [comment]
so , embedding model( Alibaba NLP gte-large-en) is deployed on vertex ai . Using vertex ai sdk and initializing client  , we wont get the model object itself which needs to be set up in Settings . So , extra time will be spent in loading the model again . Please let me know if it is clear now .

**Comment by logan-markewich** [comment]
So what do you want instead?

(Ideally you only have to initialize it once, and again, its not setting up anything except an api connection)
