### ISSUE TITLE
[Question]: Prompt used by RAPTOR to generate final answers to users' query

### ISSUE THREAD

**Issue by ZN1010** [run-llama/llama_index#14552]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

In the RAPTOR paper, the authors did not seem to provide prompts they used to generate final answers to users' queries. In their code, I found some of the prompts they used. I am wondering whether the llama_index implementation of RAPTOR used the same prompts as the authors. 

Are you able to pinpoint me the location within llama_index where the prompts used to generate final answers were specified? Thanks a lot!

**Comment by logan-markewich** [comment]
RAPTOR is just a retrieval method

In the example implementation, the main method exposed is `retrieve`
https://github.com/run-llama/llama_index/blob/589b3054e22535fc7a43baa2bbd52aacc439b4f7/llama-index-packs/llama-index-packs-raptor/llama_index/packs/raptor/base.py#L285

If you were to put this retriever into a `RetrieverQueryEngine` or chain it manually with a response synthesizer, then it would use the standard text qa template (and possibly the refine template, depending on number of nodes and LLM context size)

```
from llama_index.core.query_engine import RetrieverQueryEngine

query_engine = RetrieverQueryEngine.from_args(retriever, llm=llm, response_mode="compact")
```

Then you can use the methods dosu mentioned above to inspect and modify the prompts
