### ISSUE TITLE
[Feature Request]: Support Claude 3.5 Sonnet Multimodal

### ISSUE THREAD

**Issue by IngLP** [run-llama/llama_index#14568]
### Feature Description

Support Support Claude 3.5 Sonnet as Multimodal LLM in llama-index-multi-modal-llms-anthropic

### Reason

llama-index-multi-modal-llms-anthropic does not support Claude 3.5 Sonnet.

### Value of Feature

Enables using Claude 3.5 Sonnet to process images.

**Comment by diicellman** [comment]
created a PR #14932
