### ISSUE TITLE
[Question] : How can I specify embedding dimension with `DocumentSummaryIndex`?

### ISSUE THREAD

**Issue by keonho-kim** [run-llama/llama_index#14582]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, guys.

While dealing with `DocumentSummaryIndex`, I found that a param, `embed_dim` in VectoreSotreIndex is not supported.

In this case, how can I control embedding dimension? - I think it would be troublesome when I working with several vectorstores, which have different embedding dimension from DocumentSummaryIndex.

Any ideas?

**Comment by logan-markewich** [comment]
Embed dim goes to the vector store, not the index

Whether your need it or not depends on the vector db you ate using

**Comment by keonho-kim** [comment]
@logan-markewich Thank you Logan! 
What I'm confusing is that, what DocumentSumamryIndex returns.

Is it docstore?

**Comment by logan-markewich** [comment]
document summary index is not related to the code you posted?
