### ISSUE TITLE
[Bug]: Unnecessary Expensive Operation during Pipeline UPSERTS Ingestion

### ISSUE THREAD

**Issue by headyin** [run-llama/llama_index#14597]
### Bug Description

`self.docstore.get_all_document_hashes()` in the `_handle_upserts` method is every expensive.
But its return value is only used in the UPSERTS_AND_DELETE case.

https://github.com/run-llama/llama_index/blob/08989d4ff07340ebaeff3a6cfb0d9c12abf630c2/llama-index-core/llama_index/core/ingestion/pipeline.py#L429

### Version

0.10.50.post1

### Steps to Reproduce

Sorry, I cannot share the code here.

But basically follow these steps:
1. Create a Ingestion Pipeline with doc_store, cache and vector_store and UPSERTS strategy
2. prepare lot of documents, in my cases 1.5k+ 
3. use pipeline run to load all of the documents
4. get a new document, and use pipeline run to load the new document only.

Because there are already 1.5k+ documents in the doc_store,  the `get_all_document_hashes` method will be either very slow or very expensive depending on doc store backend.
In my cases I tested with DynamoDB doc_store and S3KVStore backed KVDocStore:
in the case of DynamoDB, it needs to do a full table scan
In the case of S3 backend, it takes 7 minutes to get all of the hashes.

But this is totally not necessary, as during UPSERT operation, we don't need to get all of the documents.

To workaround this issue, I implemented my own doc_store class that returns empty dict from `get_all_document_hashes` method, and the entire pipeline works correctly and much master

**Comment by logan-markewich** [comment]
This has since been fixed
