### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by medhsv** [run-llama/llama_index#14602]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Does anyone have fix to the following issue:

ImportError                               Traceback (most recent call last)
[<ipython-input-11-01248340565b>](https://localhost:8080/#) in <cell line: 16>()
     14 #from llama_index.prompts import SimpleInputPrompt
     15 # Import the llama index HF Wrapper
---> 16 from llama_index.llms import HuggingFaceLLM
     17 # Bring in embeddings wrapper
     18 from llama_index.embeddings import LangchainEmbedding

ImportError: cannot import name 'HuggingFaceLLM' from 'llama_index.llms' (unknown location)

I need it fixed urgently
searched everywhere no fix found

**Comment by medhsv** [comment]
I am also facing the following issue:

ImportError                               Traceback (most recent call last)
[<ipython-input-22-2b8a2ee64c3f>](https://localhost:8080/#) in <cell line: 12>()
     10 from llama_index.embeddings.langchain import LangchainEmbedding
     11 
---> 12 from llama_index import ServiceContext, set_global_service_context
     13 
     14 # Import transformer classes for generation

ImportError: cannot import name 'ServiceContext' from 'llama_index' (unknown location)

**Comment by medhsv** [comment]
For

> You should import `ServiceContext` from `llama_index.legacy.service_context` instead:
> 
> ```python
> from llama_index.legacy.service_context import ServiceContext
> from llama_index import set_global_service_context
> ```
> 
> This should resolve the `ImportError` you are experiencing [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/indices/service_context.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

For this fix issued
I am facing the following error

[nltk_data] Downloading package stopwords to
[nltk_data]     /usr/local/lib/python3.10/dist-
[nltk_data]     packages/llama_index/legacy/_static/nltk_cache...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to
[nltk_data]     /usr/local/lib/python3.10/dist-
[nltk_data]     packages/llama_index/legacy/_static/nltk_cache...
[nltk_data]   Unzipping tokenizers/punkt.zip.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-30-ab4fce859b18>](https://localhost:8080/#) in <cell line: 20>()
     18 
     19 from llama_index.legacy.service_context import ServiceContext
---> 20 from llama_index import set_global_service_context
     21 
     22 

ImportError: cannot import name 'set_global_service_context' from 'llama_index' (unknown location)

**Comment by logan-markewich** [comment]
@medhsv you are using several old imports from v0.9.x, which no longer work. In v0.10
.x, every integration is a package. Check out the latest docs for installs and imports 

So far from what I read, you need

`pip install llama-index llama-index-llms-huggingface`

```
from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core import ServiceContext, set_global_service_context 
```

Note that service context is deprecated, but still works (again, do checkout the docs at https://docs.llamaindex.ai)
