### ISSUE TITLE
[Question]: Set the frequency_penalty when using openailike

### ISSUE THREAD

**Issue by mashuk999** [run-llama/llama_index#14616]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to set the frequency_penalty and other model parameters when using openailike?

I am currently setting as below:
`Settings.llm = OpenAILike(model="meta-llama/Meta-Llama-3-8B-Instruct", api_base=openai_api_base, api_key="",
 max_tokens=2000, 
 frequency_penalty=0.8,
 presence_penalty=0.5 ,
 top_p=0.9,
 stop=stop_phrases,
 model_kwargs={
    "frequency_penalty": 1.0,
  })`

But when checking on my vllm server (On a different instance hence using OpenAILike) it shows 0 as frequency_penalty.

**Comment by logan-markewich** [comment]
Set it under additional kwargs 

additional_kwargs={...}

**Comment by mashuk999** [comment]
@logan-markewich Many thanks, It works perfectly
