### ISSUE TITLE
[Question]: how dose llama_index work with Chinese text?

### ISSUE THREAD

**Issue by lizeyubuaa** [run-llama/llama_index#14618]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

how dose llama_index work with Chinese text?
in documentation, code is as follows:
![image](https://github.com/run-llama/llama_index/assets/35723288/501060ee-d647-4e09-92cb-a471c4ea15c5)
as for my data is Chinese, i translate the entities into Chinese, however, it doesn't work. I can't get any output. If i use the default settings without changing the entities, there is an output graph.
![image](https://github.com/run-llama/llama_index/assets/35723288/4294174f-ca0a-4796-985d-2549285e8d64)

so, does llama_index work with Chinese text well?

**Comment by ouyangtu** [comment]
the Dosu assistant did provide some useful information!
Anything on the roadmap that would better support Chinese and/or other East Asian languages?
