### ISSUE TITLE
[Question]: Way to save observation,actions,thoughts of ReAct agent

### ISSUE THREAD

**Issue by shazil-ahmed** [run-llama/llama_index#14628]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The ReAct agent shows the thoughts,actions,observations on the terminal when it is performing the task. But once it is completed and the agent returns a response object, the observations,thoughts,actions that it took to complete that task are not part of that response object. I would like to output these on my application.
Is there a way to access the observations/thoughts/actions/steps taken by the agent to complete a given task ?

**Comment by logan-markewich** [comment]
This is already possible if you use the lower level api, or use callbacks.

Here's an example with the low level api
https://colab.research.google.com/drive/1hiDkBbAJcO3RDrS7CD2ZeQEHGqNv07pq?usp=sharing

**Comment by anasim1** [comment]
@logan-markewich , how did you do it with callbacks?
