### ISSUE TITLE
[Bug]: Add claude 3.5 sonnet support to Bedrock InvokeAPI 

### ISSUE THREAD

**Issue by nfrnunes** [run-llama/llama_index#14624]
### Bug Description

There is a missing comma, that prevents the usage of streaming for haiku and sonnet3.5 models:
from llama_index.llms.bedrock.utils import STREAMING_MODELS
STREAMING_MODELS

{'amazon.titan-text-express-v1',
'amazon.titan-tg1-large',
'anthropic.claude-3-5-sonnet-20240620-v1:0anthropic.claude-3-haiku-20240307-v1:0',
'anthropic.claude-3-opus-20240229-v1:0',
'anthropic.claude-3-sonnet-20240229-v1:0',
'anthropic.claude-instant-v1',
'anthropic.claude-v1',
'anthropic.claude-v2',
'anthropic.claude-v2:1',
'meta.llama2-13b-chat-v1',
'mistral.mistral-7b-instruct-v0:2',
'mistral.mistral-large-2402-v1:0',
'mistral.mixtral-8x7b-instruct-v0:1'}

ValueError: Model anthropic.claude-3-5-sonnet-20240620-v1:0 does not support streaming

### Version

v0.10.0

### Steps to Reproduce

from llama_index.llms.bedrock.utils import STREAMING_MODELS
STREAMING_MODELS

{'amazon.titan-text-express-v1',
'amazon.titan-tg1-large',
'anthropic.claude-3-5-sonnet-20240620-v1:0anthropic.claude-3-haiku-20240307-v1:0',
'anthropic.claude-3-opus-20240229-v1:0',
'anthropic.claude-3-sonnet-20240229-v1:0',
'anthropic.claude-instant-v1',
'anthropic.claude-v1',
'anthropic.claude-v2',
'anthropic.claude-v2:1',
'meta.llama2-13b-chat-v1',
'mistral.mistral-7b-instruct-v0:2',
'mistral.mistral-large-2402-v1:0',
'mistral.mixtral-8x7b-instruct-v0:1'}

### Relevant Logs/Tracbacks

```shell
from llama_index.llms.bedrock.utils import STREAMING_MODELS
STREAMING_MODELS

{'amazon.titan-text-express-v1',
'amazon.titan-tg1-large',
'anthropic.claude-3-5-sonnet-20240620-v1:0anthropic.claude-3-haiku-20240307-v1:0',
'anthropic.claude-3-opus-20240229-v1:0',
'anthropic.claude-3-sonnet-20240229-v1:0',
'anthropic.claude-instant-v1',
'anthropic.claude-v1',
'anthropic.claude-v2',
'anthropic.claude-v2:1',
'meta.llama2-13b-chat-v1',
'mistral.mistral-7b-instruct-v0:2',
'mistral.mistral-large-2402-v1:0',
'mistral.mixtral-8x7b-instruct-v0:1'}
```

**Comment by logan-markewich** [comment]
This has since been added

`pip install -U llama-index-llms-bedrock`
