### ISSUE TITLE
[Bug]: UnstructuredReader does not respect `encoding` and `errors` in the `SimpleDirectoryReader` inputs

### ISSUE THREAD

**Issue by Alavi1412** [run-llama/llama_index#14635]
### Bug Description

I am reading some files from my local using this code:
```
loader = SimpleDirectoryReader(
    local_folder,
    encoding='utf-8',
    file_extractor={
        '.pdf': UnstructuredReader(),
        '.png': UnstructuredReader(),
        '.jpg': UnstructuredReader(),
        '.pptx': UnstructuredReader(),
        '.ppt': UnstructuredReader(),
        '.docx': UnstructuredReader(),
        '.doc': UnstructuredReader(),
        '.xlsx': UnstructuredReader(),
        '.xls': UnstructuredReader(),
        '.txt': UnstructuredReader(),
    },
    required_exts=required_exts,
    recursive=True
)
documents = loader.load_data()
return documents
```
The problem is, inside the `partition_text` method of `unstructured` the `encoding` is null, and even the `errors` parameter is not even passed into the place where the file is being opened.

I have attached the debugger from `unstructured.partition.text.partition_text` which indicates the encoding is `none`

![image](https://github.com/run-llama/llama_index/assets/20519538/05ec0afc-c490-46be-b8a7-7dc4bfeca9a5)

### Version

0.10.42

### Steps to Reproduce

Set the `encoding` in the `SimpleDirectoryReader` and use `UnstructuredReader` as file_extractor, and you'll see that the encoding wouldn't even be used.

**Comment by logan-markewich** [comment]
These should be args on the actual UnstructuredReader class, but currently, it's not supported. Would need a PR to add that
