### ISSUE TITLE
[Bug]: `SimpleDirectoryReader` not functioning as expected.

### ISSUE THREAD

**Issue by martinb-ai** [run-llama/llama_index#14640]
### Bug Description

Suddenly loading txt documents from a directory does not work. 

Here is a simple example using Colab to show:

![image](https://github.com/run-llama/llama_index/assets/105685594/2fc2c192-2ebb-4a3d-a5aa-837bfe5018a2)

This is with the latest `pip install llama-index`

![image](https://github.com/run-llama/llama_index/assets/105685594/59dfe2cd-89df-4af7-82c7-87c4e9987997)

### Version

0.10.53

### Steps to Reproduce

`pip install llama-index`

```python 
from llama_index.core import VectorStoreIndex, SimpleDirectoryReader

# load `data` folder with `txt` files.
documents = SimpleDirectoryReader("data").load_data()
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query("summary of the essay")
print(response)

```

**Comment by logan-markewich** [comment]
@martinb-ai Try restarting your notebook?

**Comment by martinb-ai** [comment]
Hi @logan-markewich , still does not work. I only show it on Colab just for PR purposes. It also does not work on a `env` within my IDE or even restarting the `env` after clean `pip install` with no `cache`.
