### ISSUE TITLE
[Question]: neo4j.exceptions.ClientError

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#14647]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

neo4j.exceptions.ClientError: {code: Neo.ClientError.Procedure.ProcedureNotFound} {message: There is no procedure with the name `apoc.meta.data` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.}

**Comment by logan-markewich** [comment]
You need to make sure apoc procedures are installed/enabled.

I'm not a neo4j expert, but I just have this in my docker command when launching neo4j

```bash
docker run \
    -p 7474:7474 -p 7687:7687 \
    -v $PWD/data:/data -v $PWD/plugins:/plugins \
    --name neo4j-apoc \
    -e NEO4J_apoc_export_file_enabled=true \
    -e NEO4J_apoc_import_file_enabled=true \
    -e NEO4J_apoc_import_file_use__neo4j__config=true \
    -e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
    neo4j:latest
```

**Comment by colombod** [comment]
this doesn't work with docker images

**Comment by Jayj1997** [comment]
> You need to make sure apoc procedures are installed/enabled.
> 
> I'm not a neo4j expert, but I just have this in my docker command when launching neo4j
> 
> docker run \
>     -p 7474:7474 -p 7687:7687 \
>     -v $PWD/data:/data -v $PWD/plugins:/plugins \
>     --name neo4j-apoc \
>     -e NEO4J_apoc_export_file_enabled=true \
>     -e NEO4J_apoc_import_file_enabled=true \
>     -e NEO4J_apoc_import_file_use__neo4j__config=true \
>     -e NEO4JLABS_PLUGINS=\[\"apoc\"\] \
>     neo4j:latest

this works on my with macbook pro m1pro
