### ISSUE TITLE
[Feature Request]: LLMRerank using with vLLM

### ISSUE THREAD

**Issue by robustor123** [run-llama/llama_index#14643]
### Feature Description

when use LLMRerank with a model which is not openai model, but it is using same openai sdk.
we can use none openai model but openai sdk by vLLM serving.
but current LLMRerank produces error when postprocess_nodes.

### Reason

in openai_modelname_to_contextsize function.
it accepts only openai model . because "if modelname not in ALL_AVAILABLE_MODELS" means that accepting only openai model names.

### Value of Feature

nowadays, many open source llm have been developed . 
more chances to use those models with openai sdk

**Comment by logan-markewich** [comment]
@robustor123 you can use OpenAILike for this

```
pip install llama-index-llms-openai-like
```

```python
from llama_index.llms.openai_like import OpenAILike

llm = OpenAILike(model="my model", api_base="https://hostname.com/v1", api_key="fake")

response = llm.complete("Hello World!")
print(str(response))

reranker = LLMRerank(..., llm=llm)
```
