### ISSUE TITLE
[Question]: assistant api v2 support

### ISSUE THREAD

**Issue by Mracobes9** [run-llama/llama_index#14659]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Good morning. Is it planned to support v2 assistants api ?

**Comment by logan-markewich** [comment]
Probably eventually, it's been on the todo list for a while. Happy to accept a PR if you have time though

**Comment by Mracobes9** [comment]
Thank you

**Comment by pythiantech** [comment]
Would be great to have this. In the current version I am unable to upload files using the `files` parameter
