### ISSUE TITLE
[Feature Request]: Integration with BM25s

### ISSUE THREAD

**Issue by dhuynh95** [run-llama/llama_index#14650]
### Feature Description

There is a new BM25 technique ([BM25s](https://github.com/xhluca/bm25s))  that seems to perform quite well.
I think it could be great to have an integration with Llama Index and compare results on different benchmarks.

### Value of Feature

This could help a lot the community to have faster and better retrieval

**Comment by logan-markewich** [comment]
We already have this, BM25Retriever 

`pip install llama-index-retrievers-bm25`

**Comment by logan-markewich** [comment]
https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever/?h=bm25

**Comment by dhuynh95** [comment]
There is a new implementation that seems relevant : 

![image](https://github.com/run-llama/llama_index/assets/36925557/fb066405-70bc-4fe9-a2cc-4023d6d21067)
