### ISSUE TITLE
[Question]: Streamlitcallbackhandler 

### ISSUE THREAD

**Issue by KhyatiNinad** [run-llama/llama_index#14664]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to integrate llamaindex with streamlit with streaming chat using Agents. I would want to understand how do I also display Thoughts or intermediate output of agents in UI with streamlit chat

**Comment by logan-markewich** [comment]
Thoughts/actions can be accessed if you execute an agent in stepwise mode
https://colab.research.google.com/drive/1hiDkBbAJcO3RDrS7CD2ZeQEHGqNv07pq?usp=sharing

**Comment by KhyatiNinad** [comment]
@dosu let me clarify. Agents are running fine, giving their output in a streamlit app. But there are hierarchical agents running. So as intermediate steps, I want to show status in streamlit UI. Similar to how LangChain does with streamlitcallbackhandler.
How to achieve that

**Comment by KhyatiNinad** [comment]
@dosu Super. And how to implement the same with OpenAI agent with streaming as True

**Comment by KhyatiNinad** [comment]
@dosu thanks. What if I want to decouple Streamlitcallbackhandler class with streamlit st. How can I abstract this
