### ISSUE TITLE
[Question]: Content not loading after package updates.

### ISSUE THREAD

**Issue by JoseGHdz** [run-llama/llama_index#14684]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I need some help with an issue I'm facing. I was using a set of packages on my local machine, and everything was working fine. But after moving to AWS Cloud9, I had to update those packages due to compatibility issues.

Now, my problem is that my vectorized content is taking an extremely long time to load. On my local machine, it used to take about 12 minutes, but on Cloud9, I waited for over an hour and a half and it still wasn't done.

Could this be related to the package updates, or is there something else that could be causing this? Any insights would be appreciated.

Previous Packages:
llama-index==0.10.4
llama-index-agent-openai==0.1.1
llama-index-core==0.10.36
llama-index-embeddings-adapter==0.1.0
llama-index-embeddings-openai==0.1.9
llama-index-finetuning==0.1.0
llama-index-legacy==0.9.48
llama-index-llms-gradient==0.1.0
llama-index-llms-openai==0.1.19
llama-index-multi-modal-llms-openai==0.1.1
llama-index-postprocessor-cohere-rerank==0.1.0
llama-index-program-openai==0.1.1
llama-index-question-gen-openai==0.1.1
llama-index-readers-file==0.1.3
llamaindex-py-client==0.1.19

Updated Packages:
llama-index==0.10.54
llama-index-agent-openai==0.2.8
llama-index-cli==0.1.12
llama-index-core==0.10.53.post1
llama-index-embeddings-adapter==0.1.3
llama-index-embeddings-openai==0.1.10
llama-index-finetuning==0.1.10
llama-index-indices-managed-llama-cloud==0.2.4
llama-index-legacy==0.9.48
llama-index-llms-gradient==0.1.2
llama-index-llms-mistralai==0.1.17
llama-index-llms-openai==0.1.25
llama-index-multi-modal-llms-openai==0.1.7
llama-index-postprocessor-cohere-rerank==0.1.7
llama-index-program-openai==0.1.6
llama-index-question-gen-openai==0.1.3
llama-index-readers-file==0.1.29
llama-index-readers-llama-parse==0.1.6
llama-parse==0.4.6
llamaindex-py-client==0.1.19

The code that is taking forever to load is:
```
storage_context = StorageContext.from_defaults(persist_dir="/home/ubuntu/environment/revised-Project/Sources/Indexed Docs3/azure")
azure_index = load_index_from_storage(storage_context, show_progress=True)

storage_context = StorageContext.from_defaults(persist_dir="/home/ubuntu/environment/revised-Project/Sources/Indexed Docs3/assessment")
assessment_index = load_index_from_storage(storage_context, show_progress=True)

storage_context = StorageContext.from_defaults(persist_dir="/home/ubuntu/environment/revised-Project/Sources/Indexed Docs3/control")
control_index = load_index_from_storage(storage_context, show_progress=True)

storage_context = StorageContext.from_defaults(persist_dir="/home/ubuntu/environment/revised-Project/Sources/Indexed Docs3/questionaire")
questionaire_index = load_index_from_storage(storage_context, show_progress=True)
        
storage_context = StorageContext.from_defaults(persist_dir="/home/ubuntu/environment/revised-Project/Sources/Indexed Docs3/AWS Docs")
aws_index = load_index_from_storage(storage_context, show_progress=True)
```
My local machine is MacOS and the system in Cloud9 is Ubuntu 22.04.

**Comment by logan-markewich** [comment]
Could be a difference in CPU/hardware?

I would suggest not using saving to disk if you have a lot of data. Should be using some actual vector db after a certain point (qdrant, weaviate, pinecone, chroma, etc.)

**Comment by JoseGHdz** [comment]
> not using saving to disk if you have a lot of

For the hardware it could be. My Cloud9 instance is m5.2xlarge (32 GiB RAM + 8 vCPU) meanwhile my Mac is a 10 Core M2 Pro with 16GB of RAM. 

I was setting up a Chroma DB but since I didn't have lots of data I stopped setting it up. But then I started getting lots of data so it might be good for me to finish setting that up.
