### ISSUE TITLE
[Bug]: llama-agents human-in-the-loop quickstart does not work

### ISSUE THREAD

**Issue by KapteinKraft** [run-llama/llama_index#14682]
### Bug Description

Got attribute error

### Version

0.0.3.post1

### Steps to Reproduce

Run this quickstart: https://github.com/run-llama/llama-agents/blob/main/examples/pipeline_human_local_single.py

### Relevant Logs/Tracbacks

```shell
site-packages\llama_agents\orchestrators\pipeline.py", line 34, in get_service_component_message
    if module.module_type == ModuleType.AGENT:
       ^^^^^^^^^^^^^^^^^^
AttributeError: 'RouterComponent' object has no attribute 'module_type'
```

**Comment by logan-markewich** [comment]
I just fixed this. `pip install -U llama-agents`, you are several versions behind actually 
https://github.com/run-llama/llama-agents/pull/118

Also, llama-agents has it'd own repo/issues. Would make sense to open over there in the future 👍
