### ISSUE TITLE
[Bug]: LLMTextCompletionProgram outputs correct answer, but causes ValueError

### ISSUE THREAD

**Issue by jakubstrawa1** [run-llama/llama_index#14700]
### Bug Description

When using LLMTextCompletionProgram to incorporate the pydantic modelling for my output i get a very strange result. The error indicates that the output is proper (134436839ABCDFG), but it still throws an error that it cannot extract json string from output. 
There's no way to get the values, because i have to call the llm_completion() method and it throws an error.

LLM im using is gpt 3.5 turbo

```
prompt_template =  """You are an AI expert in extracting data from documents. Below is a document extract from a Know Your Customer document. Consider this extract as context to the prompt and answer the below question. Question: {question} Context: {context}."""

question= "Extract the 'ABC' for the company from the text. The 'ABC' should be in the format XXXXXXXXXXXXXXXXXXXX, where X can be either a number or an uppercase letter (e.g., 529900QF6F5IB9WQCL03). Please respond with only the LEI and no additional information. Return 'No info' if no ABC is found."

prompt= json_val['prompts']['prompt_template'].format(question=question, context=processed_document)
llm_completion = LLMTextCompletionProgram.from_defaults(
    llm=llm,
    output_cls=ABC,
    prompt_template_str=prompt,
    verbose=True,
)

x = llm_completion()
```

```
class ABC(BaseModel):

    abc: str = Field(..., description="The 'ABC' or 'No info' if it doesn't exist.")

    @validator("abc")
    def validate_abc_code(cls, v):
        if v.lower() != "no info" and not re.match(r"^[0-9]{4}[0]{2}[A-Z0-9]{12}[0-9]{2}$", v):
            raise ValueError("Invalid ABC code format")
        return v
```

### Version

0.10.54

### Steps to Reproduce

I tested it on gpt 3.5 llm. The processed file is a string of a random document that im trying to extract information from.

### Relevant Logs/Tracbacks

```shell
ValueError: Could not extract json string from output: "abc": "134436839ABCDFG"
File <command-1015110231477814>, line 1
----> 1 llm_completion()
File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/llama_index/core/output_parsers/utils.py:112, in extract_json_str(text)
    110 match = re.search(r"\{.*\}", text.strip(), re.MULTILINE | re.IGNORECASE | re.DOTALL)
    111 if not match:
--> 112     raise ValueError(f"Could not extract json string from output: {text}")
    114 return match.group()
```

**Comment by jakubstrawa1** [comment]
@dosu This does not work. I dont see the how i can get the response that is required for parse_pydantic_from_guidance_program from the LLMTextCompletionProgram.

**Comment by logan-markewich** [comment]
@jakubstrawa1 the result has no brackets, so it cannot be parsed into JSON

**Comment by jakubstrawa1** [comment]
@logan-markewich That's really interesting, because i have 10 pydantic classes, and with llm.complete (without using pydantic), only the prompt and llm i get proper outputs. But then when i use LLMTextCompletionProgram i get errors that they cannot be parsed. All the inputs are the same and in the same format (str)

**Comment by jakubstrawa1** [comment]
And also there isn't any possiblity to see what response we got back from llm using LLMTextCompletionProgram.from_defaults()
i can only presume that llm.complete(prompt) will give me approximately the same answer. So how can i know if its sent with or without brackets.
