### ISSUE TITLE
Can RecursiveRetriever be used with QueryFusionRetriever?

### ISSUE THREAD

**Issue by hingkan** [run-llama/llama_index#14713]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

DATA: Split the document data into multiple "parent" chunks, and then further subdivide each block into "child" chunks.

I originally wanted to first build a hybrid recursive search using the RecursiveRetriever retriever and the QueryFusionRetriever retriever together. Enter RecursiveRetriever in QueryFusionRetriever.

CODE:
`
from llama_index.core.retrievers import QueryFusionRetriever

retriever = QueryFusionRetriever(
    [recursive_retriever1, recursive_retriever2, ...],
    similarity_top_k=2,
    num_queries=4,  # set this to 1 to disable query generation
    use_async=True,
    verbose=True,
    # query_gen_prompt="...",  # we could override the query generation prompt here
)
`

ERROR: ValueError: Query id 23ca7db4-1f10-4236-88c9-b0102081b8b1 not found in either `retriever_dict` or `query_engine_dict`.

**Comment by logan-markewich** [comment]
It can, but it seems like something is wrong with one of your recursive retrievers

I bet you'd get a similar error with `recursive_retriever1.retrieve("query")`

**Comment by hingkan** [comment]
> It can, but it seems like something is wrong with one of your recursive retrievers
> 
> I bet you'd get a similar error with `recursive_retriever1.retrieve("query")`

Sure, and indeed it has already gone wrong in RecursiveRetriever.
I found the problem, RecursiveRetriever must pass the "node_dict" argument. 
Thank you.

**Comment by hingkan** [comment]
RecursiveRetriever in return only the retrieval of cases, how to use together with PrevNextNodePostprocessor, for how can achieve the same function as PrevNextNodePostprocessor.

Prerequisite: RecursiveRetriever is used together with QueryFusionRetriever.

**Comment by logan-markewich** [comment]
Postprocessors are generally used after retrieval. So you run your query fusion retriever. Then run your postprocessor on the results

If you want to postprocess individual retrievers inside the query fusion retriever, i would write a custom retriever

**Comment by hingkan** [comment]
> Postprocessors are generally used after retrieval. So you run your query fusion retriever. Then run your postprocessor on the results
> 
> If you want to postprocess individual retrievers inside the query fusion retriever, i would write a custom retriever

How does CustomRetriever implement a single retriever postprocess in QueryFusionRetriever.
