### ISSUE TITLE
[Bug]: keyword_index.as_retriever seems it cannot be set similarity_top_K = int , it is doesnt worked

### ISSUE THREAD

**Issue by gawxyz** [run-llama/llama_index#14724]
### Bug Description

keyword_index.as_retriever seems it cannot be set similarity_top_K = int , it is doesnt worked

### Version

Name: llama-index Version: 0.10.50 

### Steps to Reproduce

```
keyword_index = RAKEKeywordTableIndex(nodes)

RAKE_5_keyword_retriever = keyword_index.as_retriever(similarity_top_k=5,)
RAKE_10_keyword_retriever = keyword_index.as_retriever(similarity_top_k=10,)
RAKE_15_keyword_retriever = keyword_index.as_retriever(similarity_top_k=15,)

for message in messagelist:
    print('-----------')
    RAKE_5_nodes = RAKE_5_keyword_retriever.retrieve(message)
    RAKE_10_nodes = RAKE_10_keyword_retriever.retrieve(message)
    RAKE_15_nodes = RAKE_15_keyword_retriever.retrieve(message)
    print(f'set similarity_top_k=5: {len(RAKE_5_nodes)};\nset similarity_top_k=10: {len(RAKE_10_nodes)};\nset similarity_top_k=15: {len(RAKE_15_nodes)}',)

```

![image](https://github.com/user-attachments/assets/fe2dba64-f28c-4450-9afd-2546f644f4ec)

### Relevant Logs/Tracbacks

```shell
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
-----------
set similarity_top_k=5: 10;
set similarity_top_k=10: 10;
set similarity_top_k=15: 10
```

**Comment by logan-markewich** [comment]
@gawxyz there is no similarity, its keywords. Either a keyword matches or it doesn't. 

You can set `num_chunks_per_query=10` instead

**Comment by gawxyz** [comment]
Oh, I see. thank you for your reply. 
---- Replied Message ----
From ***@***.***> Date 07/12/2024 23:52 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [run-llama/llama_index] [Bug]: keyword_index.as_retriever seems it cannot be set similarity_top_K = int , it is doesnt worked (Issue #14724) 
@gawxyz there is no similarity, its keywords. Either a keyword matches or it doesn't.
You can set num_chunks_per_query=10 instead
