### ISSUE TITLE
[Bug]: OpenWeatherMapToolSpec throws error when called for weather forecast

### ISSUE THREAD

**Issue by alexander-fischer** [run-llama/llama_index#14744]
### Bug Description

OpenWeatherMapToolSpec which is part of the llama-index agent tool `llama-index-tools-weather` throws an error whenever the agent call the function `forecast_tommorrow_at_location`.

The error message is: `UnauthorizedError: Invalid API Key provided`

This is a known issue for newer API keys for OpenWeatherMap, which don't support the old API endpoints anymore: https://github.com/csparpa/pyowm/issues/316

### Version

0.10.53

### Steps to Reproduce

Install the tool: `llama-index-tools-weather`

After installation use the following code to reproduce:

```python
from llama_index.tools.weather import OpenWeatherMapToolSpec

print(OpenWeatherMapToolSpec("your-api-key").forecast_tommorrow_at_location("Berlin"))
```

**Comment by jmfallone** [comment]
Hi @alexander-fischer - are you familiar with the API? I took a look into this one and saw the recommendation for using one_call in the issue you linked, but I still get the invalid api key when I use one_call. I looked on their website and get the sense that it isn't included in the free plan. Some details here: https://openweathermap.org/price#weather

**Comment by alexander-fischer** [comment]
fixed here: https://github.com/run-llama/llama_index/pull/14745
