### ISSUE TITLE
[Question]: How to insert/delete document to/from VectorStoreIndex when using IngestionPipeline?

### ISSUE THREAD

**Issue by deval-aiml** [run-llama/llama_index#14756]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am confused on how does insertion and deletion work with `VectorStoreIndex` along with `qdrant` vector db @logan-markewich 

Method definitions used in the code
```
# Vector Store Init
self.vector_store = QdrantVectorStore(
    collection_name=collection_name,
    # client=self._client,
    aclient=self._aclient,
    enable_hybrid=True,
    batch_size=self.vectordb_config.batch_size,
    hybrid_fusion_fn=self.relative_score_fusion
)
```

```
# Index Init
self.index = VectorStoreIndex.from_vector_store(
    self.vector_store,
    Settings.embed_model,
    store_nodes_override = True
 )
 ```
 ```
 # Function to insert nodes in a index
 async def add_nodes_to_index_async(self, nodes):
    await self.index._async_add_nodes_to_index(
        self.index.index_struct,
        nodes,
        show_progress = True
)
```

```
 # Function to init ingestion pipeline
    docstore = RedisDocumentStore.from_host_and_port(
        host=config.redis_config.host, 
        port=config.redis_config.port, 
        namespace="llamasearch"
    )
    parser = SentenceSplitter()
    print(f"Creating new ingestion pipeline")
    ingestion = IngestionPipeline(
        transformations=[parser],
        docstore=docstore,
        vector_store=qdrant_search.vector_store,
        cache=IngestionCache(
            cache=RedisCache.from_host_and_port(
                host=config.redis_config.host, 
                port=config.redis_config.port
            ),
            collection="redis_cache",
        ),
        docstore_strategy=DocstoreStrategy.UPSERTS,
    )
 ```
 
 ```
 # Snippet to load a document from file path and insert into index
    documents = SimpleDirectoryReader(input_files=[file_path], filename_as_id=True).load_data()
    for doc in documents:
        print(f"Processing Document ID: {doc.id_}")
        docs.append(doc.id_)
    nodes = await ingestion.arun(documents=documents)
    print(f"Ingesting {len(nodes)} nodes for {len(ingestion.docstore.docs)} chunks")
    await self.add_nodes_to_index_async(nodes)
    ----
```

This code works but I am unsure if it creates proper parent child relationships with document id and is in sync with vector db (qdrant)

Also, how to delete the document. 

```self.index.delete_ref_doc(doc_id, delete_from_docstore=True)```

**Query**: This command deletes from vector db but does not delete from docstore even though I am passing `True` in the argument, what could be the reason?
**Query**: The doc_id passed is the document_id (in my case I am using filename_as_id) or is it doc chunk id? Does it delete a given doc chunk (related nodes) or all nodes associated to that document?
**Query**: Which is standard way of maintaining CRUD updates for documents that is consistent across docstore and vector db?

**Comment by dvlshah** [comment]
Deletion is not very intuitive from the documentation. I want to use native methods from llamaindex API to consistently delete document using `ref_doc_id` from docstore and vector db. The other doubt is how do I now the ref_doc_id

Can I fetch the mapping using a defined property or do I need to maintain the mapping on my own?

@dosu
