### ISSUE TITLE
[Question]: Unable to understand how document storage works in case nodes are deleted

### ISSUE THREAD

**Issue by BalasubramanyamEvani** [run-llama/llama_index#14767]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

My use case is as follows: When I create a vector store index (ChromaVectorStore) and persist the storage context, how should one go about deleting the nodes later? Let's say I want to delete all the nodes.

I can probably get all the IDs in the ChromaDB collection and then delete them, but as far as I understand, the deleted node IDs should be removed from the docstore.json when the storage context is persisted. How should one handle this? Or is there a way LlamaIndex handles it automatically?

Any pointers regarding this would be helpful

Thank you

**Comment by Avinash-Raj** [comment]
@dosu but `index._store_nodes_override` has  to be set in-order to remove entries from docstore.
