### ISSUE TITLE
[Feature Request]: Version pinning for sub packages

### ISSUE THREAD

**Issue by B-Step62** [run-llama/llama_index#14788]
### Feature Description

Hi team! 

I have an index created with non-latest version of llama-index (0.10.0). When I tried to reproduce the result in different environment by installing the same version of llama-index, I realized that the sub packages don't conform to the version specified for the root package.

For example, I ran the following command to install llama-index 0.10.0.
```
pip install llama-index==0.10.0
```

However, this installs `llama-index-core` with `0.10.55` and other sub packages with the latest versions. This cause compatibility issue like `Module not found: xxx`. 

It would be nice if LlamaIndex root package can pin the maximum version to the latest version **at the moment of it is released**, so that users don't need to maintain sub packages versions to avoid forward compatibility issues.

### Reason

The inability to install the sub packages at specific point of time is a gap for reproducibility. While it's possible to extract and save all sub packages versions from `pip freeze`, it is tedious to maintain the list of 10> sub packages.

### Value of Feature

Users can install the non-lated version of llama-index without compatibility concern with sub packages.

**Comment by logan-markewich** [comment]
Newer versions of llama-index pin the version of core. We can't update past releases though.

Although I highly recommend pinning specific packages, rather than the top level llama-index wrapper

**Comment by B-Step62** [comment]
@logan-markewich Oh I see, yea I can see it start to pin the core package since [0.10.41](https://github.com/run-llama/llama_index/blame/v0.10.41/pyproject.toml#L60). That would resolve the future issue. Thank you for the pointer!
