### ISSUE TITLE
How should the dim parameter value of MilvusVectorStore be calculated?

### ISSUE THREAD

**Issue by hingkan** [run-llama/llama_index#14781]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What does dim relate to, the maximum length of the embedding model?

**Comment by pavluka6** [comment]
Yes, dim relates to the **length of the embedding vector** of the given embedding model. 

You should be able to find it within the model card or API docs.

**Comment by hingkan** [comment]
> The `dim` parameter value of `MilvusVectorStore` should be set to the dimension of the embedding vectors that you are using for the collection. This is required if you are creating a new collection. For example, if you are using OpenAI's embeddings, the dimension might be 1536 [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-milvus/llama_index/vector_stores/milvus/base.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/vector_stores/milvus.py)[[3]](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb).
> 
> Example usage:
> 
> ```python
> vector_store = MilvusVectorStore(
>     dim=1536,  # Set this to the dimension of your embedding vectors
>     collection_name="your_collection_name",
>     uri="http://milvus_address:port",
>     token="your_milvus_token_here",
>     overwrite=True
> )
> ```
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I load the native embedding model, which is a variable-length vectorized model. dimension is in [1024, 1792], but the MilvusVectorStore tells me dim=5376.
