### ISSUE TITLE
I wonder how to use llama_index to retrieve the Milvus collection after it is created and indexed using the MilvusVectorStore.

### ISSUE THREAD

**Issue by hingkan** [run-llama/llama_index#14790]
In the following code, the index can be retrieved using llama_index.
`
vector_store = MilvusVectorStore(uri="http://localhost:19530/", dim=1792, overwrite=True, index_config={
    'metric_type': 'IP',
    'index_type': "FLAT",
})

storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context
)
`

But how should llama index load the Milvus index?My idea is as follows:
`
vector_store = MilvusVectorStore(uri="http://localhost:19530/", dim=1792, overwrite=False, index_config={
    'metric_type': 'IP',
    'index_type': "FLAT",
})
storage_context = StorageContext.from_defaults(vector_store=vector_store)	# rebuild storage context
index = load_index_from_storage(storage_context)	# load index	
`
But there was an unexpected error.
ERROR:`ValueError: No index in storage context, check if you specified the right persist_dir.`

I would like to know how to use llama_index to retrieve Milvus' existing data.

**Comment by hingkan** [comment]
> ```python
> index = load_index_from_storage(storage_context=storage_context)
> ```

But 'load_index_from_storage()' will report an error, error message 'ValueError: No index in storage context, check if you specified the right persist_dir.'

**Comment by hingkan** [comment]
> To retrieve data from an existing Milvus index using `llama_index`, you need to ensure that the `MilvusVectorStore` is correctly initialized and that the `StorageContext` is properly set up to load the index. Here is how you can do it:
> 
> 1. Initialize the `MilvusVectorStore` with the appropriate parameters.
> 2. Create a `StorageContext` with the `vector_store`.
> 3. Use the `load_index_from_storage` function to load the index from the storage context.
> 
> Here is an example code snippet:
> 
> ```python
> from llama_index.indices.loading import load_index_from_storage
> from llama_index.storage import StorageContext
> from llama_index.vector_stores.milvus import MilvusVectorStore
> 
> # Initialize the MilvusVectorStore
> vector_store = MilvusVectorStore(
>     uri="http://localhost:19530",  # replace with your Milvus instance URI
>     dim=1792,  # replace with the dimension of your embeddings
>     overwrite=False,  # set to False to use an existing collection
>     index_config={
>         'metric_type': 'IP',
>         'index_type': "FLAT",
>     }
> )
> 
> # Create a StorageContext with the vector store
> storage_context = StorageContext.from_defaults(vector_store=vector_store)
> 
> # Load the index from the storage context
> index = load_index_from_storage(storage_context=storage_context)
> 
> # Now you can use the index to retrieve data
> query_vector = [0.1, 0.2, 0.3]  # Example query vector
> documents = index.as_retriever().retrieve(query_vector)
> 
> # Print the retrieved documents
> for doc in documents:
>     print(f"Document ID: {doc.id_}, Text: {doc.text}")
> ```
> 
> This code will connect to the Milvus instance, load the existing index, and allow you to retrieve documents using a query vector. Make sure to replace the `uri`, `dim`, and `query_vector` with your actual values [[1]](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/vector_stores/MilvusIndexDemo.ipynb)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/storage/storage_context.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

But 'load_index_from_storage()' will report an error, error message 'ValueError: No index in storage context, check if you specified the right persist_dir.'

**Comment by hingkan** [comment]
Does llama_index only define Milvus' join and index creation, but not Milvus' data loading and corresponding index generation?

**Comment by hingkan** [comment]
> To correctly load and retrieve data from an existing Milvus index using , you need to ensure that the index has been properly persisted and that the is correctly configured to point to the right storage directory. Here is a more detailed approach:`llama_index``StorageContext`
> 
> 1. **Persist the Index**: Ensure that the index is saved to a persistent storage directory.
> 2. **Load the Index**: Use the  function to load the index from the storage context.`load_index_from_storage`
> 
> Here is an example of how to persist and then load the index:
> 
> ### Persisting the Index
> ```python
> from llama_index.vector_stores.milvus import MilvusVectorStore
> from llama_index.core import StorageContext, VectorStoreIndex, SimpleDirectoryReader
> 
> # Initialize the MilvusVectorStore
> vector_store = MilvusVectorStore(
>     uri="http://localhost:19530",  # Replace with your Milvus instance URI
>     dim=1792,  # Replace with the dimension of your embeddings
>     overwrite=True,
>     index_config={
>         'metric_type': 'IP',
>         'index_type': "FLAT",
>     }
> )
> 
> # Create a StorageContext with the vector store
> storage_context = StorageContext.from_defaults(vector_store=vector_store)
> 
> # Load documents
> documents = SimpleDirectoryReader(
>     input_files=["./data/your_data_file.txt"]
> ).load_data()
> 
> # Create an index over the documents
> index = VectorStoreIndex.from_documents(
>     documents, storage_context=storage_context
> )
> 
> # Persist the index
> storage_context.persist(persist_dir="./storage")
> ```
> 
> ### Loading the Index
> ```python
> from llama_index.indices.loading import load_index_from_storage
> from llama_index.storage import StorageContext
> from llama_index.vector_stores.milvus import MilvusVectorStore
> 
> # Initialize the MilvusVectorStore
> vector_store = MilvusVectorStore(
>     uri="http://localhost:19530",  # Replace with your Milvus instance URI
>     dim=1792,  # Replace with the dimension of your embeddings
>     overwrite=False,
>     index_config={
>         'metric_type': 'IP',
>         'index_type': "FLAT",
>     }
> )
> 
> # Create a StorageContext with the vector store
> storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir="./storage")
> 
> # Load the index from the storage context
> index = load_index_from_storage(storage_context=storage_context)
> 
> # Now you can use the index to retrieve data
> query_vector = [0.1, 0.2, 0.3]  # Example query vector
> documents = index.as_retriever().retrieve(query_vector)
> 
> # Print the retrieved documents
> for doc in documents:
>     print(f"Document ID: {doc.id_}, Text: {doc.text}")
> ```
> 
> This approach ensures that the index is first persisted to a directory and then loaded from that directory. Make sure to replace the , , and with your actual values `uri``dim``query_vector`[[1]](https://github.com/run-llama/llama_index/issues/8498)[[2]](https://github.com/run-llama/llama_index/issues/3177).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

If you use 'storage_context.persist(persist_dir="./storage")' to save the index, isn't loading similar to disk perpetuation?

**Comment by hingkan** [comment]
If you save the index to disk, there is no difference between using the Milvus vector library and not using the Milvus vector library

**Comment by hingkan** [comment]
> To correctly load and retrieve data from an existing Milvus index using `llama_index`, you need to ensure that the index has been properly persisted and that the `StorageContext` is correctly configured to point to the right storage directory. Here is a more detailed approach:
> 
> 1. **Persist the Index**: Ensure that the index is saved to a persistent storage directory.
> 2. **Load the Index**: Use the `load_index_from_storage` function to load the index from the storage context.
> 
> Here is an example of how to persist and then load the index:
> 
> ### Persisting the Index
> ```python
> from llama_index.vector_stores.milvus import MilvusVectorStore
> from llama_index.core import StorageContext, VectorStoreIndex, SimpleDirectoryReader
> 
> # Initialize the MilvusVectorStore
> vector_store = MilvusVectorStore(
>     uri="http://localhost:19530",  # Replace with your Milvus instance URI
>     dim=1792,  # Replace with the dimension of your embeddings
>     overwrite=True,
>     index_config={
>         'metric_type': 'IP',
>         'index_type': "FLAT",
>     }
> )
> 
> # Create a StorageContext with the vector store
> storage_context = StorageContext.from_defaults(vector_store=vector_store)
> 
> # Load documents
> documents = SimpleDirectoryReader(
>     input_files=["./data/your_data_file.txt"]
> ).load_data()
> 
> # Create an index over the documents
> index = VectorStoreIndex.from_documents(
>     documents, storage_context=storage_context
> )
> 
> # Persist the index
> storage_context.persist(persist_dir="./storage")
> ```
> 
> ### Loading the Index
> ```python
> from llama_index.indices.loading import load_index_from_storage
> from llama_index.storage import StorageContext
> from llama_index.vector_stores.milvus import MilvusVectorStore
> 
> # Initialize the MilvusVectorStore
> vector_store = MilvusVectorStore(
>     uri="http://localhost:19530",  # Replace with your Milvus instance URI
>     dim=1792,  # Replace with the dimension of your embeddings
>     overwrite=False,
>     index_config={
>         'metric_type': 'IP',
>         'index_type': "FLAT",
>     }
> )
> 
> # Create a StorageContext with the vector store
> storage_context = StorageContext.from_defaults(vector_store=vector_store, persist_dir="./storage")
> 
> # Load the index from the storage context
> index = load_index_from_storage(storage_context=storage_context)
> 
> # Now you can use the index to retrieve data
> query_vector = [0.1, 0.2, 0.3]  # Example query vector
> documents = index.as_retriever().retrieve(query_vector)
> 
> # Print the retrieved documents
> for doc in documents:
>     print(f"Document ID: {doc.id_}, Text: {doc.text}")
> ```
> 
> This approach ensures that the index is first persisted to a directory and then loaded from that directory. Make sure to replace the `uri`, `dim`, and `query_vector` with your actual values [[1]](https://github.com/run-llama/llama_index/issues/8498)[[2]](https://github.com/run-llama/llama_index/issues/3177).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

If I use 'storage_context.persist(persist_dir="./storage")' to save the index, do I just need to store index store.json?

**Comment by alexandruakkol** [comment]
@dosu Can't I just use Milvus's own storage and indexing that exists already? I don't want to persist the data in my project, but still use llamaindex for the retrieval/query engine framework.

**Comment by Meshinfo** [comment]
@hingkan did you find out the solution? I met the same problems, it seems that a local persist directory is still needed which is silly.....

**Comment by ranjanj1** [comment]
@Meshinfo did you fine any solutions ?

**Comment by ycd** [comment]
Here is a complete example for future readers to follow:

```python
documents = SimpleDirectoryReader(
    input_files=["./example.txt"]
).load_data()

persist_dir = "./my_index"

index: VectorStoreIndex
if not os.path.exists(persist_dir):
    vector_store = MilvusVectorStore(
        uri="./dummy.db",
        dim=768,
        overwrite=False,
        batch_size=500,
    )
    storage_context = StorageContext.from_defaults(
        vector_store=vector_store
    )
    index = VectorStoreIndex.from_documents(
        documents, storage_context=storage_context, show_progress=True, use_async=True
    )
    index.storage_context.persist(persist_dir=persist_dir)
else:
    vector_store = MilvusVectorStore(
        uri="./dummy.db",
        dim=768,
        overwrite=False,
        batch_size=500,
    )
    index = load_index_from_storage(
        StorageContext.from_defaults(
            persist_dir=persist_dir, vector_store=vector_store
        ),
    )

query_engine = index.as_query_engine(similarity_top_k=1, response_mode="context_only")
res = query_engine.query("Your query")
```

Also if you don't want to use local file system, you can pass a file system such as S3 FS etc, see the [documentation](https://docs.llamaindex.ai/en/stable/module_guides/storing/save_load/) @Meshinfo
