### ISSUE TITLE
[Question]: Why is pydantic v1 used as default?

### ISSUE THREAD

**Issue by spreeni** [run-llama/llama_index#14807]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently, Pydantic v1 is used as default (llama-index-core==0.10.47) for all models in the bridge:
https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/bridge/pydantic.py

Why is the default not Pydantic v2 with the option to use v1? This is frustrating as I am working with FastAPI and either have to define all schemas in v1, or re-implement them in v2, as the generated OpenAPI API docs do not allow mixing between the versions.

Pydantic also has a code migration tool from v1 to v2, if that is helpful:
https://docs.pydantic.dev/latest/migration/

**Comment by logan-markewich** [comment]
I agree it's annoying, but using v2 as the default requires a pretty huge lift in a ton of classes and implementations. Hoping to move to it for v0.11.x

For now with fastapi, just don't use llama-index types as api inputs or outputs, then all the schemas and docs will generate fine
