### ISSUE TITLE
[Bug]:how to retrieve when using DynamicLLMPathExtractor

### ISSUE THREAD

**Issue by Johnbathappully** [run-llama/llama_index#14827]
### Bug Description

**currently ingestion happens**

kg_extractor = DynamicLLMPathExtractor(
    llm=llm,
    max_triplets_per_chunk=20,
    num_workers=4,
    allowed_entity_types=None,  # Let the LLM infer entities and their labels (types) on the fly
    allowed_relation_types=None,  # Let the LLM infer relationships on the fly
)

dynamic_index = PropertyGraphIndex.from_documents(
    documents,
    llm=llm,
    embed_kg_nodes=False,
    kg_extractors=[kg_extractor],
    show_progress=True,
    property_graph_store=graph_store,    
)

**however i cant retrieve using this below method of  LLMSynonymRetriever..pls note im able to retrieve when i ingest using simplellmpathextractor...my concern is in dynmicpathextractor there are labels coming in neo4j bolt which is not there in other method**

import nest_asyncio
nest_asyncio.apply()

from llama_index.core.indices.property_graph import (
    PGRetriever,
    VectorContextRetriever,
    LLMSynonymRetriever,
)

sub_retrievers = [
    LLMSynonymRetriever(graph_store),
]

retriever = PGRetriever(sub_retrievers=sub_retrievers)

nodes = retriever.retrieve("Insurbridge Connects to")

for node in nodes:
  print(node.text)

from llama_index.core import PropertyGraphIndex
index = PropertyGraphIndex.from_existing(
      property_graph_store=graph_store
  )

query_engine = index.as_query_engine(sub_retrievers=[retriever], llm=llm)

response = query_engine.query("Insurbridge Connects to")
print(str(response))

### Version

llama-cloud                             0.0.9 llama-index                             0.10.55 llama-index-agent-openai                0.2.8 llama-index-cli                         0.1.12 llama-index-core                        0.10.55 llama-index-embeddings-openai           0.1.10 llama-index-graph-stores-neo4j          0.2.7 llama-index-indices-managed-llama-cloud 0.2.5 llama-index-legacy                      0.9.48 llama-index-llms-openai                 0.1.25 llama-index-multi-modal-llms-openai     0.1.7 llama-index-program-openai              0.1.6 llama-index-question-gen-openai         0.1.3 llama-index-readers-file                0.1.30 llama-index-readers-llama-parse         0.1.6 llama-parse                             0.4.7

**Comment by logan-markewich** [comment]
The synonym retriever generates keywords and synonyms based on your query. If none of those match entities in your graph, then nothing is retrieved.

Usually this retriever alone is not enough, I always combine it with a vector retriever
