### ISSUE TITLE
[Bug]: FunctionTool.from_defaults() broken. Raises pydantic error due to the fn_schema being passed in its ToolMetadata parameter.

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#14866]
### Bug Description

Passing in a ToolMetadata object, particularly the function schema(fn_schema) raises a pydantic validation error. This is a really huge problem as all the agents I had initialized with the ToolMetadata are now stuck in error loops.

### Version

0.10.56

### Steps to Reproduce

Use the code from this example notebook: https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent_tool_call_parser/

def multiply(a: int, b: int) -> int:
    """Multiply two integers and returns the result integer"""
    return a * b

class MultiplyToolSchema(BaseModel):
   a: int
   b: int

class AddToolSchema(BaseModel):
  a: int
  b: int

//multiply_tool = FunctionTool.from_defaults(fn=multiply, )
multiply_tool = FunctionTool.from_defaults(
                    fn=multiply,
                    tool_metadata=ToolMetadata(
                        name="multiply",
                        fn_schema=MultiplyToolSchema,
                        description="Multiply two integers and returns the result integer",
                        return_direct=False,  #
                    ),
                )
               def add(a: int, b: int) -> int:
    """Add two integers and returns the result integer"""
    return a + b

//add_tool = FunctionTool.from_defaults(fn=add)
add_tool = FunctionTool.from_defaults(
                    fn=add,
                    tool_metadata=ToolMetadata(
                        name="add",
                        fn_schema=AddToolSchema,
                        description="Add two integers and returns the result integer",
                        return_direct=False,  #
                    ),
                ) 

from typing import Dict
from llama_index.llms.openai.utils import OpenAIToolCall
import re

def custom_tool_call_parser(tool_call: OpenAIToolCall) -> Dict:
    r"""Parse tool calls that are not standard json.
    Also parses tool calls of the following forms:
    variable = \"\"\"Some long text\"\"\"
    variable = "Some long text"'
    variable = '''Some long text'''
    variable = 'Some long text'
    """
    arguments_str = tool_call.function.arguments
    if len(arguments_str.strip()) == 0:
        # OpenAI returns an empty string for functions containing no args
        return {}
    try:
        tool_call = json.loads(arguments_str)
        if not isinstance(tool_call, dict):
            raise ValueError("Tool call must be a dictionary")
        return tool_call
    except json.JSONDecodeError as e:
        # pattern to match variable names and content within quotes
        pattern = r'([a-zA-Z_][a-zA-Z_0-9]*)\s*=\s*["\']+(.*?)["\']+'
        match = re.search(pattern, arguments_str)

        if match:
            variable_name = match.group(1)  # This is the variable name
            content = match.group(2)  # This is the content within the quotes
            return {variable_name: content}
        raise ValueError(f"Invalid tool call: {e!s}")

from llama_index.agent.openai import OpenAIAgent
from llama_index.llms.openai import OpenAI
from google.colab import userdata

llm = OpenAI(model="gpt-4o-mini", api_key=userdata.get("OPENAI_KEY"))
agent = OpenAIAgent.from_tools(
    [multiply_tool, add_tool],
    llm=llm,
    verbose=True,
    tool_call_parser=custom_tool_call_parser,
)

response = agent.chat("What is (121 * 3) + 42?")
print(str(response))

Note that when add tool and multiply tool are initialized with just the fn parameter(as in the original notebook and in the commented code above) the code works. But this is limiting as I can no longer control the description and the fn_schema by passing in the ToolMetadata.

### Relevant Logs/Tracbacks

```shell
Added user message to memory: What is (121 * 3) + 42?
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-35-fc7034a39228> in <cell line: 1>()
----> 1 response = agent.chat("What is (121 * 3) + 42?")
      2 print(str(response))

12 frames
/usr/local/lib/python3.10/dist-packages/pydantic/v1/main.py in __init__(__pydantic_self__, **data)
    339         values, fields_set, validation_error = validate_model(__pydantic_self__.__class__, data)
    340         if validation_error:
--> 341             raise validation_error
    342         try:
    343             object_setattr(__pydantic_self__, '__dict__', values)

ValidationError: 1 validation error for AgentToolCallEvent
tool -> fn_schema
  subclass of BaseModel expected (type=type_error.subclass; expected_class=BaseModel)
```

**Comment by gich2009** [comment]
This also affects the ReactAgent. I haven't seen it affect the other agents types: lats, coa, llm_compiler etc...
But the ReactAgent and OpenAIAgent are the most common anyway.

**Comment by logan-markewich** [comment]
@gich2009 where did you import basemodel from? `from pydantic import BaseModel` or `from pydantic.v1 import BaseModel` ? I would expect the latter to work

**Comment by gich2009** [comment]
Ah yes it does. from pydantic.v1 works perfectly. Thanks for the fix @logan-markewich.
