### ISSUE TITLE
[Bug]: GoogleDocsReader and other Google readers using dynamic redirect URIs

### ISSUE THREAD

**Issue by lawrenceztang** [run-llama/llama_index#14865]
### Bug Description

I'm getting the following error on the Google sign-in page when trying to use GoogleDocsReader:

> Error 400: redirect_uri_mismatch
> 
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
> 
> If you're the app developer, register the redirect URI in the Google Cloud Console.
> Request details: redirect_uri=http://localhost:64096/ flowName=GeneralOAuthFlow

The problem is the port on the redirect_uri changes every time I run the program, meaning even when I register the redirect URI once it changes the next time.

### Version

 0.10.55

### Steps to Reproduce

```
from llama_index.readers.google import GoogleDocsReader

# Specify the document IDs you want to load
document_ids = ["Information Central"]

# Load data from Google Docs
documents = GoogleDocsReader().load_data(document_ids=document_ids)
```

**Comment by lawrenceztang** [comment]
It turns out the issue is that a Desktop application rather than Web Application should be selected in the GCP console.

The tutorial on LlamaIndex has a mistake.

**Comment by logan-markewich** [comment]
Feel free to make a PR :)
