### ISSUE TITLE
[Bug]: PydanticSelector fails when used with LangChainLLM

### ISSUE THREAD

**Issue by jordanparker6** [run-llama/llama_index#14874]
### Bug Description

PydanticSelector validation fails as it expects a LlamaIndex OpenAI llm. An OpenAILike llm can be provided as a LangChainLLM so this validation shouldn't limit these llms from use in the selector.

### Version

^0.10.55

### Steps to Reproduce

```py
LangChainLLM(
    ChatOpenAI(
         model=DEFAULT_FAST_MODEL,
         max_tokens=512,
         api_key=config.openai.api_key,
         base_url=config.openai.api_base,
         model_kwargs={
              "extra_body": {
              "customer_identifier": auth.user_id,
               "metadata": {"service": "retrieval"},
               }
           },
        )
    )
}
LLMSingleSelector.from_defaults(llm=llm)
```

**Comment by logan-markewich** [comment]
Langchain llm is a generic wrapper, it doesn't know what the underlying llm is. 

Since the langchain llm class does not implement function calling, it can't be used as a pydantic selector. You'll need to use the regular llm selector, or use the openai llm from llamaindex
