### ISSUE TITLE
Query Pipeline generating random links

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#14877]
### Bug Description

I am using query pipeline by llama_index
My pipeline looks like this, but for some reason, the input and join modules are getting linked. What is the reason behind it and this is affecting my pipeline. 

pipeline.add_link("input", "source1")
pipeline.add_link("input", "source1")
pipeline.add_link("input","source2")

pipeline.add_link("source1", "source3")

pipeline.add_link("source3", "source4")

pipeline.add_link("source2", "join", dest_key="1")

pipeline.add_link("source4", "join", dest_key="2")

### Version

0.10.29

### Steps to Reproduce

pipeline.add_link("input", "source1")
pipeline.add_link("input", "source1")
pipeline.add_link("input","source2")

pipeline.add_link("source1", "spurce3")

pipeline.add_link("source3", "source4")

pipeline.add_link("source2", "join", dest_key="1")

pipeline.add_link("source4", "join", dest_key="2")

### Relevant Logs/Tracbacks

```shell
> Running module join with input:
```

**Comment by logan-markewich** [comment]
@arnavroh45 that log doesn't mean that the input is connected to join. It's saying it's running the join component with some input data -- not specifically the input component

**Comment by arnavroh45** [comment]
@logan-markewich 
if i print the module keys after the run state, I am getting ['input', 'join'] as the output, why is that I want only "input" to be the next module after the run state and I want "join" to come later into the picture, I don't think there is a problem in the addition of links as well.

This is the code that I ran to print the module keys
run_state = pipeline.get_run_state(input)
next_module_keys = pipeline.get_next_module_keys(run_state)
print(next_module_keys)
