### ISSUE TITLE
[Bug]: GPT 4o Mini not working after package updates

### ISSUE THREAD

**Issue by JoseGHdz** [run-llama/llama_index#14886]
### Bug Description

Good afternoon folks,

I am attempting to run GPT 4o mini in my RAG AI system. I ran package updates to the following packages:

pip install --upgrade openai llama-index llama-index-agent-openai llama-index-embeddings-openai llama-index-llms-openai llama-index-multi-modal-llms-openai llama-index-program-openai llama-index-question-gen-openai

As well as uninstalled the packages and reinstalled but I am still having an error that says:

Error! Attempt failed with error Unknown model ‘gpt-4o-mini’. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-1106-vision-preview, gpt-4-turbo-2024-04-09, gpt-4-turbo, gpt-4o, gpt-4o-2024-05-13, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-0125, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613. Retrying attempt.

Any guidance or assistance is highly appreciated.
The environment that I am using is AWS Cloud 9.

### Version

0.10.54

### Steps to Reproduce

Install the Packages for:
openai 
llama-index 
llama-index-agent-openai 
llama-index-embeddings-openai 
llama-index-llms-openai 
llama-index-multi-modal-llms-openai 
llama-index-program-openai 
llama-index-question-gen-openai

### Relevant Logs/Tracbacks

```shell
Error! Attempt failed with error Unknown model ‘gpt-4o-mini’. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-0125-preview, gpt-4-turbo-preview, gpt-4-vision-preview, gpt-4-1106-vision-preview, gpt-4-turbo-2024-04-09, gpt-4-turbo, gpt-4o, gpt-4o-2024-05-13, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0125, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-0125, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613. Retrying attempt.
```

**Comment by logan-markewich** [comment]
The correct update command is `pip install --upgrade ...` or `pip install -U ...`, you missed the `-` character

So in this case, `pip install -U llama-index-llms-openai ...`

**Comment by JoseGHdz** [comment]
> The correct update command is `pip install --upgrade ...` or `pip install -U ...`, you missed the `-` character
> 
> So in this case, `pip install -U llama-index-llms-openai ...`

I mistyped it here but I did --upgrade. I spoke to OpenAI and they're saying that the error is due to the permissions and age of my API key which fixed the issue. Thank you for your assistance.
