### ISSUE TITLE
[Bug]: Can find 4o-mini after upgrade

### ISSUE THREAD

**Issue by liu941125** [run-llama/llama_index#14894]
### Bug Description

After I update llama-index-llms-openai，I try to use 4o-mini model, but there is a exception: **ValueError: Unknown model 'gpt-4o-mini'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613**  
The version of llama-index is 0.10.56,  llama-index-llms-openai is 0.1.26

### Version

0.10.56

### Steps to Reproduce

update llama-index and then usr 4o-mini model

### Relevant Logs/Tracbacks

```shell
**ValueError: Unknown model 'gpt-4o-mini'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo, gpt-35-turbo-1106, gpt-35-turbo-0613, gpt-35-turbo-16k-0613**
```

**Comment by logan-markewich** [comment]
Are you running in a notebook? If so, make sure you restart it.  If not, make a fresh venv.

It works fine for me. And the source code also includes it
https://github.com/run-llama/llama_index/blob/a961dfbf387a70ad4f5eb54219fc4aedcf63b87f/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/utils.py#L50
