### ISSUE TITLE
[Bug]: OpenAI not working

### ISSUE THREAD

**Issue by arnavroh45** [run-llama/llama_index#14898]
### Bug Description

I am using version 0.10.29, and yesterday this command was working fine, but after today's commit in the latest version. I am getting this error. 

Code: llm=OpenAI(api_key="api_key", temperature=0.1)
TypeError: Can't instantiate abstract class OpenAI with abstract method _prepare_chat_with_tools

### Version

0.10.29

### Steps to Reproduce

from llama_index.llms.openai import OpenAI
llm=OpenAI(api_key="api_key", temperature=0.1)

### Relevant Logs/Tracbacks

```shell
TypeError: Can't instantiate abstract class OpenAI with abstract method _prepare_chat_with_tools
```

**Comment by logan-markewich** [comment]
Make sure you also update the openai integration -- `pip install -U llama-index llama-index-llms-openai`

Works fine here
https://colab.research.google.com/drive/1gsFQxrWbyxX5UaUJJHcCeUxGGRTO0PDR?usp=sharing

**Comment by EtienneNL** [comment]
> Make sure you also update the openai integration -- `pip install -U llama-index llama-index-llms-openai`
> 
> Works fine here https://colab.research.google.com/drive/1gsFQxrWbyxX5UaUJJHcCeUxGGRTO0PDR?usp=sharing

This indeed works for me. Thanks for sharing!

**Comment by 8throok** [comment]
> Make sure you also update the openai integration -- `pip install -U llama-index llama-index-llms-openai`
> 
> Works fine here https://colab.research.google.com/drive/1gsFQxrWbyxX5UaUJJHcCeUxGGRTO0PDR?usp=sharing

This works like a charm!!
