### ISSUE TITLE
[Documentation]: Correct the formatting of reference

### ISSUE THREAD

**Issue by dxtym** [run-llama/llama_index#14903]
### Documentation Issue Description

I'm not sure if that's an issue, but I think the following line should be formatted as a hyperlink to the article about embeddings. Please, correct me if I'm wrong. Attaching the line to be revised:

> The API calls to create the **{ref}embeddings \<what-is-an-embedding>** in a VectorStoreIndex can be expensive in terms of time and money, so you will want to store them to avoid having to constantly re-index things.

If so, I believe the link should point to the following [page](https://docs.llamaindex.ai/en/stable/understanding/indexing/indexing/#what-is-an-embedding). Thank you.

### Documentation Link

https://docs.llamaindex.ai/en/stable/understanding/storing/storing/

**Comment by logan-markewich** [comment]
Feel free to make a PR!
