### ISSUE TITLE
[Question]:  Do I have the correct version; what is the correct import statement for GPT Index? 

### ISSUE THREAD

**Issue by Farihawaheed** [run-llama/llama_index#14912]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Parent Child relationship is incorrect with my import statement (faiss, llama_index, GPT Index) Do I have the correct version; what is the correct import statement for GPT Index? 

Input:
from django.shortcuts import render
from django.http import JsonResponse
import faiss
import numpy as np
from llama_index import GPTIndex

# Sample documents
documents = [
    "Document 1 content",
    "Document 2 content",
    "Document 3 content"
]

 

Output And/OR Error:
Cannot find reference 'GPTIndex' in 'imported module llama_index' :5

**Comment by logan-markewich** [comment]
GPTIndex is an oooooollld import from like.... v0.3 😅 

Please see the latest docs, probably a good time to revisit 
https://docs.llamaindex.ai/en/stable/getting_started/starter_example/

`from llama_index.core import VectorStoreIndex

**Comment by Farihawaheed** [comment]
Is `from llama_index.core import VectorStoreIndex the correct and newer version of GPTIndex ? Or is it just another import ?

**Comment by logan-markewich** [comment]
Yes its the correct and newer version
