### ISSUE TITLE
[Bug]: PandasQueryEngine cannot execute simple pandasframe code, giving error "NameError: name 'pd' is not defined"

### ISSUE THREAD

**Issue by tytung2020** [run-llama/llama_index#14926]
### Bug Description

NameError: name 'pd' is not defined

![image](https://github.com/user-attachments/assets/5ecc329a-07e2-45a5-b5e9-d8d61d11e099)

### Version

llama-index-llms-openai - (0.1.27)

### Steps to Reproduce

in colab:

```
!pip install llama-index-llms-openai


from llama_index.llms.openai import OpenAI

llm = OpenAI(model="gpt-4o")

df = pd.read_csv("<some csv file with data>")

query_engine = PandasQueryEngine(df=df, verbose=True, llm=llm)

response = query_engine.query(
    "<some query about the data>",
)
```

**Comment by tytung2020** [comment]
this code is generated by llamaindex pandas query engine, and should be executed by it automatically, and should not require our interference in the code.

**Comment by justbane** [comment]
I hjave the same issue and my tracing back to the cause has lead me to line 33 in llama-index-experimental/llama_index/experimental/query_engine/pandas/output_parser.py

Specifically the pd variable is set restricted for the safe_eval method.

I would also add this make any queries with dates completely unusable.

for instance for a query of "What month has the most streamed songs?"

The query returns these pandas commands.
```
df['Release Date'] = pd.to_datetime(df['Release Date'])
df['Release Month'] = df['Release Date'].dt.month
df['Release Month'].value_counts().idxmax()
```

Note the call to 'pd.' - This fails every time.
