### ISSUE TITLE
[Question]: can i save a summary index? 

### ISSUE THREAD

**Issue by whoo9112** [run-llama/llama_index#14928]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I used Multi docs agent in llamaindex. 

Multi docs agent is save the vector index. but, not save summary index. 
Because of this, I have to recreate the nodes for the summary index every time.
Is there a way to save the summary index?

**Comment by whoo9112** [comment]
@dosu no DocumentSummaryIndex, i said SummaryIndex

**Comment by homerokzam** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[110], [line 3](vscode-notebook-cell:?execution_count=110&line=3)
      [1](vscode-notebook-cell:?execution_count=110&line=1) # Save
      [2](vscode-notebook-cell:?execution_count=110&line=2) summary_storage_context = StorageContext.from_defaults()
----> [3](vscode-notebook-cell:?execution_count=110&line=3) summary_index.save_to_storage(summary_storage_context)
      [4](vscode-notebook-cell:?execution_count=110&line=4) summary_storage_context.persist(persist_dir="./storage")

AttributeError: 'SummaryIndex' object has no attribute 'save_to_storage'
