### ISSUE TITLE
VectorStoreIndex + transformations not working as expected

### ISSUE THREAD

**Issue by erlebach** [run-llama/llama_index#14921]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Consider the following code: 
```

def create_index(*, persist_dir, transformations: list | None = None):
    if not os.path.exists(persist_dir):
        splitter = text_splitter
        _nodes = splitter.get_nodes_from_documents(docs)
        print("nb nodes: ", len(_nodes))
        if transformations is None:
            transf: list = [text_splitter]
        else:
            transf: list = [text_splitter] + transformations
        _index = VectorStoreIndex(docs, transformations=transf)
        # save index to disk
        _index.storage_context.persist(persist_dir)
    else:
        # rebuild storage context
        storage_context = StorageContext.from_defaults(persist_dir=persist_dir)
        # load index
        _index = load_index_from_storage(storage_context)
    return _index
    ```
  When calling this function as: 
  ```
  index = create_index(persist_dir="./storage", transformations=None)
index_trans = create_index(
    persist_dir="./storage_trans", transformations=[title_extractor, qa_extractor]
)
```
I find that the transformations are not applied to the documents (and not to the nodes if I replace documents by nodes in the first argument of VectorStoreIndex. Could somebody please explain the relationship between the first argument of VectorStoreIndex and the `transformations` argument? Thanks.
    
    
  ```

**Comment by logan-markewich** [comment]
Transformations are applied to documents, not nodes

`VectorStoreIndex(nodes, ..)` is saying you already parsed your documents into nodes

`VectorStoreIndex.from_documents(docs)` and `index.insert(doc)` apply transformations 

If you want to pass in nodes, and you want those nodes to still run through transformations, you can do that outside of the index

**Comment by erlebach** [comment]
Thank you, Logan. But documents are a subclass of `TextNode`. What is it about the Node structure that prevents transformations from being applied? Thanks.

**Comment by logan-markewich** [comment]
there's nothing preventing it, its just a design decision of the index.

`VectorStoreIndex(nodes=nodes)` will assume that you've already run all the transformations and parsing that you want. It will index what you pass in directly. This means a user can be assured that nothing is applied to what they pass in.

There is a transformations argument there because its still used during `index.insert(doc)`

**Comment by erlebach** [comment]
Thank you, Logan.
