### ISSUE TITLE
Groq integration broken with latest llama-index version 

### ISSUE THREAD

**Issue by doolingdavidrs21** [run-llama/llama_index#14922]
### Bug Description

this will not work anymore:
```python
from llama_index.llms.groq import Groq
llm = Groq(model="llama3-70b-8192", temperature=0)
Settings.llm = llm
```

### Version

had to revert to earlier version

### Steps to Reproduce

from llama_index.llms.groq import Groq
llm = Groq(model="llama3-70b-8192", temperature=0)
Settings.llm = llm

**Comment by logan-markewich** [comment]
What's the error? You tried with updating to latest?

`pip install -U llama-index-llms-groq llama-index` ?

**Comment by doolingdavidrs21** [comment]
The error is in an old notebook, but it was something about some abstract class not being able to talk to Groq, etc.   if I have latest packages like you indicate above, it does not work. the latest llama-index-llm-groq + the most recent bersion of llama-index work. but not with this new release of llama-index, the one within the last 24 hrs.

**Comment by doolingdavidrs21** [comment]
I'll try to recreate in moment and put the traceback here.

**Comment by logan-markewich** [comment]
@doolingdavidrs21 I think actually you need `pip install -U llama-index-llms-openai` 👀

**Comment by logan-markewich** [comment]
https://colab.research.google.com/drive/1bSM1kz2IQlVi4qxxVxDmSMut01v9kHUB?usp=sharing

I don't have an API key, but I think I know what caused the error, and it probably shows up when instantiating. With latest packages, no issue there

**Comment by doolingdavidrs21** [comment]
here it is: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[1], line 36
     32 print(hf_token)
     35 from llama_index.llms.groq import Groq
---> 36 llm = Groq(model="llama3-70b-8192", temperature=0)
     37 Settings.llm = llm

TypeError: Can't instantiate abstract class Groq with abstract method _prepare_chat_with_tools
```

**Comment by doolingdavidrs21** [comment]
@logan-markewich YES! updating the llama-index-llms-openai package fixed my issue.      So with all the latest and greatest versions, groq is functioning again... Thank you!
