### ISSUE TITLE
[Bug]: TypeError: Can't instantiate abstract class AzureAICompletionsModel with abstract method _prepare_chat_with_tools

### ISSUE THREAD

**Issue by DanielDIQA** [run-llama/llama_index#14930]
### Bug Description

example from [https://docs.llamaindex.ai/en/stable/api_reference/llms/azure_inference/?h=llama_index.llms.azure_inference#llama_index.llms.azure_inference.AzureAICompletionsModel](url) returns an error.

Code:
`from llama_index.core import Settings
from llama_index.core.llms import ChatMessage
from llama_index.llms.azure_inference import AzureAICompletionsModel

llm = AzureAICompletionsModel(
    endpoint="https://[your-endpoint].inference.ai.azure.com",
    credential="your-api-key",
    temperature=0
)`

returns:
`TypeError: Can't instantiate abstract class AzureAICompletionsModel with abstract method _prepare_chat_with_tools`

Reason:
AzureAICompletionsModel in package https://pypi.org/project/llama-index-llms-azure-inference/ (v 0.1.0) is missing the implementation of method _prepare_chat_with_tools. Apparently the author forgot to checking in this method.

### Version

0.10.57

### Steps to Reproduce

run:
``from llama_index.core import Settings
from llama_index.core.llms import ChatMessage
from llama_index.llms.azure_inference import AzureAICompletionsModel

llm = AzureAICompletionsModel(
endpoint="https://[your-endpoint].inference.ai.azure.com",
credential="your-api-key",
temperature=0
)``

**Comment by B-Step62** [comment]
Facing the same issue with OpenAI `TypeError: Can't instantiate abstract class OpenAI with abstract method _prepare_chat_with_tools`

**Comment by mbrunel** [comment]
Our repo https://github.com/lavague-ai/LaVague is also broken because of this, we pin to 0.10.56 for now, but hopefully we can work out a better solution soon.

**Comment by logan-markewich** [comment]
@mbrunel @DanielDIQA `pip install -U llama-index-llms-openai`

**Comment by Daniar-git** [comment]
the same issua wuth cloudy
