### ISSUE TITLE
[Bug]: Can't instantiate abstract class AzureOpenAI with abstract method _prepare_chat_with_tools

### ISSUE THREAD

**Issue by gazambuja** [run-llama/llama_index#14942]
### Bug Description

I am using version 0.10.57, and yesterday this command was working fine, but after today's commit in the latest version. I am getting this error.

pip freeze |grep llama
llama-index==0.10.57
llama-index-core==0.10.57
llama-index-embeddings-azure-openai==0.1.10
llama-index-llms-azure-openai==0.1.10
llama-index-llms-openai==0.1.24
...

Code: llm=AzureOpenAI(...)
TypeError: Can't instantiate abstract class AzureOpenAI with abstract method _prepare_chat_with_tools

Relevant Logs/Tracbacks
TypeError: Can't instantiate abstract class OpenAI with abstract method _prepare_chat_with_tools

### Version

0.10.57

### Steps to Reproduce

llm = AzureOpenAI(
            model=self.model,
            deployment_name=self.deployment_name,
            api_key=self.api_key,
            azure_endpoint=self.azure_endpoint,
            api_version=self.api_version,
        )

TypeError: Can't instantiate abstract class AzureOpenAI with abstract method _prepare_chat_with_tools

**Comment by logan-markewich** [comment]
@gazambuja `pip install -U llama-index-llms-openai`

**Comment by logan-markewich** [comment]
I'll have to bump the top-level dependency in `llama-index` -- too many people running into this lol
