### ISSUE TITLE
[Bug]: Llama-index ChatSummaryBuffer didn't summarise the chat history

### ISSUE THREAD

**Issue by eatesaam-digital-diraction** [run-llama/llama_index#14958]
### Bug Description

ChatSummaryBuffer didn't summarize the chat history.

### Version

0.10.57

### Steps to Reproduce

import os

os.environ["OPENAI_API_KEY"] = "sk-"

from llama_index.core.memory import ChatSummaryMemoryBuffer
from llama_index.core.llms import ChatMessage, MessageRole
from llama_index.llms.openai import OpenAI
import tiktoken

chat_history = [
    ChatMessage(role=MessageRole.USER, content="What is LlamaIndex?"),
    ChatMessage(
        role=MessageRole.ASSISTANT,
        content="LlamaaIndex is the leading data framework for building LLM applications",
    ),
    ChatMessage(role=MessageRole.USER, content="Can you give me some more details?"),
    ChatMessage(
        role=MessageRole.ASSISTANT,
        content="""LlamaIndex is a framework for building context-augmented LLM applications. Context augmentation refers to any use case that applies LLMs on top of your private or domain-specific data. Some popular use cases include the following: 
        Question-Answering Chatbots (commonly referred to as RAG systems, which stands for "Retrieval-Augmented Generation"), Document Understanding and Extraction, Autonomous Agents that can perform research and take actions
        LlamaIndex provides the tools to build any of these above use cases from prototype to production. The tools allow you to both ingest/process this data and implement complex query workflows combining data access with LLM prompting.""",
    ),
]

model = "gpt-4-0125-preview"
summarizer_llm = OpenAI(model_name=model, max_tokens=256)
tokenizer_fn = tiktoken.encoding_for_model(model).encode
memory = ChatSummaryMemoryBuffer.from_defaults(
    chat_history=chat_history,
    llm=summarizer_llm,
    token_limit=1000,
    tokenizer_fn=tokenizer_fn,
)

history = memory.get()

print(history)

**Comment by logan-markewich** [comment]
@eatesaam-digital-diraction in your example, the data you put into the memory doesn't exceed the token limit, so no summarization is done

**Comment by eatesaam-digital-diraction** [comment]
@logan-markewich Thank you for your assistance and for highlighting the issue. I got your point.
