### ISSUE TITLE
[Question]: Will the extra_info be concatenated with the text content and then encoded using the embedding model?

### ISSUE THREAD

**Issue by OKC13** [run-llama/llama_index#14956]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Will the extra_info be concatenated with the text content and then encoded using the embedding model?
I used KeywordExtractor in index = VectorStoreIndex.from_documents(documents, transformations=transformations). I am not sure if the keywords obtained in extra_info will be encoded. If they are encoded, how will they be encoded?

**Comment by logan-markewich** [comment]
It does. You can read more about this in the docs https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/#advanced-metadata-customization (this applies to both documents and nodes)

Metadata is included by default
