### ISSUE TITLE
[Question]: mixture of Agents inside React Agent

### ISSUE THREAD

**Issue by NeethanShetty07** [run-llama/llama_index#14962]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
How can we include mixture of Agents inside the React agents??
Please if any body knows let me know.

**Comment by logan-markewich** [comment]
You could implement a `CustomLLM` that implements the mixture of agents. Then you can use that LLM in react (or anywhere else)

**Comment by logan-markewich** [comment]
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/usage_custom/?h=customllm#example-using-a-custom-llm-model-advanced
