### ISSUE TITLE
[Bug]: TypeError: Can't instantiate abstract class Groq with abstract method _prepare_chat_with_tools

### ISSUE THREAD

**Issue by Hicham-e** [run-llama/llama_index#14969]
### Bug Description

i'm using groq as llm, it used to work just fine but now i get that error

### Version

Version: 0.10.58

### Steps to Reproduce

from llama_index.llms.groq import Groq
GROQ_API_KEY = "key"
llm = Groq(model="llama3-70b-8192", api_key=GROQ_API_KEY)

**Comment by logan-markewich** [comment]
`pip install -U llama-index-llms-openai`

**Comment by Hicham-e** [comment]
> `pip install -U llama-index-llms-openai`

works for openai not for groq i tried it

**Comment by logan-markewich** [comment]
Grow extends openai. There's almost no implementation
https://github.com/run-llama/llama_index/blob/ebbc5124b05f60ae24afab08c06e79c7628b181c/llama-index-integrations/llms/llama-index-llms-groq/llama_index/llms/groq/base.py#L7

As you can see, openai implements the methods it is complaining about
https://github.com/run-llama/llama_index/blob/ebbc5124b05f60ae24afab08c06e79c7628b181c/llama-index-integrations/llms/llama-index-llms-openai/llama_index/llms/openai/base.py#L827

So you should just have to run the command above, and it works with `llama-index-llms-openai` v0.1.27 (or greater)

Are you running in a notebook? You'd have to restart after updating.

**Comment by Hicham-e** [comment]
> e you running in a notebook? You'd have to restart after updating.

yeah it worked after restarting the notebook. Thanks

**Comment by logan-markewich** [comment]
Great!
