### ISSUE TITLE
[Bug]: Hugging Face Inference API Fails to Extract Entities with SchemaLLMPathExtractor

### ISSUE THREAD

**Issue by Get-Rect** [run-llama/llama_index#14978]
### Bug Description

When using a HuggingFaceInferenceAPI LLM to build a property graph using the SchemaLLMPathExtractor, no entities or relations are extracted.

I have tried testing this with different models, extract prompts, and settings and have not been able to get it to work, despite the HuggingFaceInferenceAPI LLM working when using a SimpleLLMPathExtractor.

### Version

0.10.52

### Steps to Reproduce

Clone the example repo here and run it, https://github.com/Get-Rect/property_graph_schema_hugging_face

Or, create a Property Graph Store using a HuggingFaceInferenceAPI LLM and a SchemaLLMPathExtractor. I have only tested this with a connection to a locally run Neo4J server, but it may persist for other data stores.

**Comment by logan-markewich** [comment]
@Get-Rect the model you are using is probably just not good enough to output consistent pydantic objects

I recommend not using this module for open-source LLMs, unless its like llama3.1 70b

**Comment by Get-Rect** [comment]
@logan-markewich Thank you for the advice. I have tried it with much bigger models like llama3.1-405b and had the same empty results. I have even set Strict=False as Dosu recommended. What's weird is that I'm only running llama3 7b locally with Ollama and getting much better results than any model when I use the inference api.

I will keep trying custom prompts and parsing functions and check the logs as Dosu recommended. Any other tips you can offer would be greatly appreciated.
