### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by oomarish** [run-llama/llama_index#14971]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi! I am a new user of llama-index, I appreciate the work done here, but I have a question about VectorStoreIndex object coming from llama_index.core.indices.vector_store.base.py, the functioning of from_documents function is very abstract that I can not see the content of this object, I mean the vectors created after the tokenization and the embedding. And how to make it persist in the vector database? I tried to check for newly inserted data but there is nothing. If any one can also explain me how does the query engine work and what relation does it have with the index because i found it a bit complicated. Thanks in advance.

**Comment by OmarD-ctrl** [comment]
The persist function actually saves the data to the local pc, although I've already made a pgvector connected to a postgresql database in a docker container.
