### ISSUE TITLE
[Bug]: ValueError: Got a larger chunk overlap (20) than chunk size (100), should be smaller.

### ISSUE THREAD

**Issue by sby-a-izumi** [run-llama/llama_index#14985]
### Bug Description

from llama_index.core.node_parser import SentenceSplitter

SentenceSplitter(chunk_size=100, chunk_overlap=20, separator='\n')

Splitter = SentenceSplitter(chunk_size=chunk_size, chunk_overlap=chunk_overlap, separator=separator)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

ValueError: Got a larger chunk overlap (20) than chunk size (100), should be smaller.

### Version

0.10.43

### Steps to Reproduce

as the same with bug description.

**Comment by sby-a-izumi** [comment]
@dosubot how to fix this error?

**Comment by logan-markewich** [comment]
Not able to reproduce 
https://colab.research.google.com/drive/1-3RMZ0Mx2Yz-kVO0RcMOJaTj53G-2LV3?usp=sharing

**Comment by sby-a-izumi** [comment]
This error often occurred when performing an operation that overwrites the same address.
The solution was to cast the type so that the error did not occur.
