### ISSUE TITLE
[Feature Request]: Support for Metadata Filtering using native Python functions

### ISSUE THREAD

**Issue by arun04cbe** [run-llama/llama_index#14982]
### Feature Description

Currently, we use the `MetadataFilters` class for filtering operations. Few vectors in the `llama index` have the MetadataFiltering supported.(Qdrant, Weaviate). But few don't have. (Faiss, Chroma). Llama Index restricts this feature for some vector stores.

Solution for this would be to have metadata filters as the pre-existing one and in addition to that we could also have filtering using native python functions. This makes the developer more flexible enough in developing AI applications.

**Comment by logan-markewich** [comment]
I don't think I really understand the proposal.

The idea is to provide a unified interface for metadat filtering. If a vector store is missing support, the community is welcome to add it. But tbh these days most support things well

(FYI faiss is impossible to support it, some vector stores don't give the option)

**Comment by arun04cbe** [comment]
When you consider langchain, by default even though Metadata Filtering is not supported in Faiss, we have the filtering available through native Python functions. Here is an implementation https://github.com/langchain-ai/langchain/blob/master/libs/community/langchain_community/vectorstores/faiss.py. @logan-markewich

**Comment by logan-markewich** [comment]
This can't really be applied to every vector store Though can it? A callable can be anything. Vector stores expect certain syntax.

**Comment by arun04cbe** [comment]
Instead of all the vector stores, we could have this functionality atleast for vector stores which does not have Metadata Filtering by default.
