### ISSUE TITLE
[Bug]: MetadataFilters.legacy_filters() breaks with nesting

### ISSUE THREAD

**Issue by spreeni** [run-llama/llama_index#14986]
### Bug Description

The `OpensearchVectorClient` uses `filters.legacy_filters()` to parse given `MetadataFilters`. These should allow nesting of `MetadataFilters`, but when presented with a nested filter, there will be a
```
AttributeError: 'MetadataFilters' object has no attribute 'operator'
```
It probably should throw an error if presented with a nested object. Ideally, `OpensearchVectorClient._parse_filters` could be adjusted to the `MetadataFilters` structure.

Implementation in `MetadataFilters`:
https://github.com/run-llama/llama_index/blob/d15f45bcec205a4cd0c8f2a4b7c829385e2910e1/llama-index-core/llama_index/core/vector_stores/types.py#L175-L185

Implementation in `OpensearchVectorClient`:
https://github.com/run-llama/llama_index/blob/d15f45bcec205a4cd0c8f2a4b7c829385e2910e1/llama-index-integrations/vector_stores/llama-index-vector-stores-opensearch/llama_index/vector_stores/opensearch/base.py#L213-L222

### Version

llama-index-core==0.10.47; llama-index-vector-stores-opensearch==0.1.12

### Steps to Reproduce

Create a nested `MetadataFilters` instance and call `legacy_filters()`.
```python
from llama_index.core.vector_stores.types import MetadataFilters, MetadataFilter

MetadataFilters(
    filters=[
        MetadataFilters(
            filters=[
                MetadataFilter(key="key", value="value")
            ]
        )
    ]
).legacy_filters()
```

**Comment by logan-markewich** [comment]
legacy filters do not allow nesting I think? Its just a flat list of exact match filters

tbh opensearch should be updated to move off of legacy filters at some point. I welcome a PR

**Comment by spreeni** [comment]
Yeah, legacy filters do not allow nesting and only equality comparison, as far as I can see. I implemented my own parser for it for now, will try to submit it as a PR soon then.
