### ISSUE TITLE
[Question]: Retriever documents, embeddings = None

### ISSUE THREAD

**Issue by Shiro-LK** [run-llama/llama_index#14996]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I have a question regarding the embeddings, when using .retrieve, I got a list of NodeWithScore, however the embedding is always set to None. I am wondering why? 

Here my code to create the retriever:

```
index = VectorStoreIndex.from_documents([doc], embed_model=embedding_model, transformations=[TokenTextSplitter(
    chunk_size=128, chunk_overlap=50, id_func=my_id_func 
)]  )
 


base_retriever = VectorIndexRetriever(
    index=index,
    similarity_top_k=15,
)

r = base_retriever.retrieve(query)
```

**Comment by logan-markewich** [comment]
Most vector stores will have it set to none to save memory and processing from passing around large vectors.

Tbh, some vector stores will return It, some won't, this should probably be more consistent and configurable

**Comment by logan-markewich** [comment]
With the default vector store, you can use `index.vector_store.get(node.node_id)` to get the associated embedding
