### ISSUE TITLE
[Bug]: parsing glossary across pages in pdf breaks up definition

### ISSUE THREAD

**Issue by gitcagey** [run-llama/llama_index#14991]
### Bug Description

using llamaparse api to parse a pdf into text. 

take this pdf: https://www.aphis.usda.gov/sites/default/files/hawaii.pdf

this definition is across 2 pages in pdf:
![image](https://github.com/user-attachments/assets/4794f157-614e-4d75-831f-c52de47c7985)

but when parsed it looks like this:
![image](https://github.com/user-attachments/assets/1471ea22-4761-4371-9135-6f6c6fd3462c)

this is problematic as using gemini 1.5 pro to provide me the glossary terms and results in a RECITATION stop reason in their API. Bottom line is if I fix the broken parsed term/definition manually I don't get the problem in GEMINI. But the issue is invalid parsed text out of llamaparse.

### Version

!pip install llama-parse 

### Steps to Reproduce

all above

**Comment by logan-markewich** [comment]
You should probably open this on the llama-parse repo: https://github.com/run-llama/llama_parse

Joining tables across pages is pretty hard, but something that is being worked on

**Comment by gitcagey** [comment]
oops, thanks. posted on llama parse repo.
