### ISSUE TITLE
[Bug]: llama-index-embeddings-fastembed should use latest fastembed that is 0.3.4 but it is using 0.2.7 

### ISSUE THREAD

**Issue by pydv9991** [run-llama/llama_index#15002]
### Bug Description

llama-index-embeddings-fastembed should use latest fastembed that is 0.3.4 but it is using 0.2.7 which caused library conflicts.

### Version

0.0.79.post1

### Steps to Reproduce

install fastembed-gpu or only fastembed latest that is 0.3.4
then install  llama-index-embeddings-fastembed it used fastemebed 0.2.7 which causes conflicts

### Relevant Logs/Tracbacks

```shell
conflict is caused by:
15.53     The user requested fastembed==0.3.4
15.53     llama-index-embeddings-fastembed 0.1.6 depends on fastembed<0.3.0 and >=0.2.2
15.53     The user requested fastembed==0.3.4
```

**Comment by Ashufet** [comment]
How to update the pyproject.toml while installing the package and how we can do the same through docker also.

**Comment by pydv9991** [comment]
How to update the pyproject.toml while installing the package with requirements.txt and how we can do the same through docker also.

**Comment by pydv9991** [comment]
@dosu the code you shared is giving error 
 ValueError: /llama_index does not contain any element
