### ISSUE TITLE
Unusual errors

### ISSUE THREAD

**Issue by godofecht** [run-llama/llama_index#15004]
### Bug Description

`ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index'`

I think this is good enough of a reason to move away from llama_index

### Version

Latset

### Steps to Reproduce

Just try to import `SimpleDirectoryReader `from `llama_index`.

**Comment by logan-markewich** [comment]
It's not unusual. Please check the official docs for current usage.

`from llama_index.core import SimpleDirectoryReader`

https://docs.llamaindex.ai/en/stable/#getting-started

**Comment by logan-markewich** [comment]
For more information, s8nce v0.10.x, llama-index was split into several namespaced packages to make dependency management more sane and the library more modular.

The `llama-index` "package" is just a dummy package around several starter packages 
`llama-index-core`, `llama-index-llms-openai`, etc.

**Comment by godofecht** [comment]
How recent was this? Seems like a surprise.

**Comment by logan-markewich** [comment]
About 2 months ago @godofecht ?

We had a blog post and multiple Twitter and discord announcements about it. We recently just removed the banner about the migration guide from our docs front page, but the migration guide itself is still there
https://docs.llamaindex.ai/en/stable/getting_started/v0_10_0_migration/?h=

**Comment by godofecht** [comment]
Thanks for getting back to me with this information.
