### ISSUE TITLE
Starter Tutorial (Local Models): TypeError 

### ISSUE THREAD

**Issue by sixshakybones** [run-llama/llama_index#15017]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I am following the starter tutorial from the site using Jupyter and Anaconda environment on my local machine with Ollama and Llama3 and getting a TypeError, am i doing something incorrectly or is there some sort of issue you might help me identify ? Ive tried with and without streaming its the same error

![image](https://github.com/user-attachments/assets/3fb5d883-bcc4-47cf-87f7-44a2cd2151a5)

**Comment by sixshakybones** [comment]
Thanks for that, however i am not supplying any 'tools keyword arguments' or any additional code. I am copying and pasting the example code from the website , this error is happening internally in the function calls, i can see the tools parameters defined in the llamaindex codebase. Modules were install through pip install and imported accordingly.

**Comment by logan-markewich** [comment]
`pip install-U "ollama>=0.3.0"` I think (a little weird that it didn't install the latest?)

**Comment by sixshakybones** [comment]
Thanks logan, i have spent the past few hours rebuilding a new environment ... and its working now, im not sure what has happened
