### ISSUE TITLE
[Question]: Can we use `TokenCountingHandler` with different models. 

### ISSUE THREAD

**Issue by paulpalmieri** [run-llama/llama_index#15020]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello! 

Let's say I use a multimodal modal like `gpt-4o` and a text model like `gemini`. 

How can I best use `TokenCountingHandler` to listen for calls from each models and count tokens with the proper tokenizer each time ? 

It seems that declaring two handlers like this: 
```python
mm_llm_token_counter = TokenCountingHandler(
    tokenizer=gpt_tokenizer,
    event_starts_to_ignore=[CBEventType.EMBEDDING],
    event_ends_to_ignore=[CBEventType.EMBEDDING],
)
llm_token_counter = TokenCountingHandler(
    tokenizer=gemini_tokenizer,
    event_starts_to_ignore=[CBEventType.EMBEDDING],
    event_ends_to_ignore=[CBEventType.EMBEDDING],
)
```

Results in only one of the handler recording the calls. 

Thanks a lot!

**Comment by logan-markewich** [comment]
You'd have to attach each handler to the LLM

`OpenAI(..., callback_manager=CallbackManager([mm_llm_token_counter])`

`Gemini(..., callback_manager=CallbackManager([llm_token_counter])`
