### ISSUE TITLE
[Feature Request]: Add LMStudio Embeddings

### ISSUE THREAD

**Issue by abhishekbhakat** [run-llama/llama_index#15021]
### Feature Description

Related: #13556

We do have LLM by: `llama-index-llms-lmstudio` module
It would be nice to have one for embeddings as well.

### Reason

Basically, LMStudio replicates OpenAI endpoints. 
So, If I do:
```python
from llama_index.embeddings.openai import OpenAIEmbedding
embed_model = OpenAIEmbedding(
    api_key="whatever-is-in-lmstudio", 
    api_base="http://localhost:8080/v1", 
    model="nomic-ai/nomic-embed-text-v1.5-GGUF"
)
```

I get:
```python
ValueError: 'nomic-ai/nomic-embed-text-v1.5-GGUF' is not a valid OpenAIEmbeddingModelType
```

On the flip side, if I don't configure any model, then it thinks it's `OpenAIEmbeddingModelType.TEXT_EMBED_ADA_002` and requests goes through.

### Value of Feature

Mostly for standards. And probable customizations which may or may not be possible with `llama-index-embeddings-openai`.

**Comment by logan-markewich** [comment]
Actually, the code example would work if you did `model_name=` instead of `model=`

**Comment by abhishekbhakat** [comment]
That worked. Feel free to close this issue.
