### ISSUE TITLE
[Question]: 使用llama-index，在调用 KnowledgeGraphIndex.from_documents()方法是报错

### ISSUE THREAD

**Issue by GOOD-N-LCM** [run-llama/llama_index#15033]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

使用llama-index，在调用 KnowledgeGraphIndex.from_documents()方法是报错
报错内容如下：
Traceback (most recent call last):
  File "D:\code_llm\LLama-Index\lcm3.py", line 56, in <module>
    kg_index = KnowledgeGraphIndex.from_documents(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 145, in from_documents
    return cls(
           ^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\knowledge_graph\base.py", line 109, in __init__
    super().__init__(
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 94, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\base.py", line 216, in build_index_from_nodes
    return self._build_index_from_nodes(nodes, **build_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\knowledge_graph\base.py", line 215, in _build_index_from_nodes
    triplets = self._extract_triplets(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\knowledge_graph\base.py", line 159, in _extract_triplets
    return self._llm_extract_triplets(text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\indices\knowledge_graph\base.py", line 163, in _llm_extract_triplets
    response = self._llm.predict(
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\llms\llm.py", line 559, in predict
    chat_response = self.chat(messages)
                    ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\core\llms\callbacks.py", line 172, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\llms\ollama\base.py", line 261, in chat
    response = self.client.chat(
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\ollama\_client.py", line 235, in chat
    return self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\ollama\_client.py", line 98, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\ollama\_client.py", line 74, in _request
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError
Exception ignored in: <function NebulaGraphStore.__del__ at 0x000002D6D22E2840>
Traceback (most recent call last):
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\llama_index\graph_stores\nebula\nebula_graph_store.py", line 242, in __del__
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\nebula3\gclient\net\SessionPool.py", line 326, in close
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\nebula3\gclient\net\Session.py", line 351, in _sign_out
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\nebula3\gclient\net\Connection.py", line 262, in signout
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\nebula3\graph\GraphService.py", line 1603, in signout
  File "C:\Users\gogoLcm\.conda\envs\llama-index\Lib\site-packages\nebula3\graph\GraphService.py", line 1606, in send_signout
AttributeError: 'NoneType' object has no attribute 'CALL'

我的代码：
`documents = SimpleDirectoryReader(
    "data"
).load_data()

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags
)

storage_context = StorageContext.from_defaults(graph_store=graph_store)

kg_index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=10,
    include_embeddings=True,
)
print('>>>  kg_index : ', kg_index )`

**Comment by GOOD-N-LCM** [comment]
> ```python
> service_context = ServiceContext()
> ```
请问  service_context = ServiceContext()  这一步是必须的么？ 
使用llama-index + nebula ，  在 nebula社区代码里没有发现这个参数。

**Comment by GOOD-N-LCM** [comment]
> 是的，`service_context = ServiceContext()`使用 Nebula 时此步骤是必需的`llama-index`。它会初始化所需的组件，以`KnowledgeGraphIndex`确保其正常运行。
> 
> 以下是如何设置的示例`ServiceContext`：
> 
> ```python
> from llama_index.core.service_context_elements.llm_predictor import LLMPredictor
> from llama_index.core.base.embeddings.base import BaseEmbedding
> from llama_index.core.indices.prompt_helper import PromptHelper
> from llama_index.core.node_parser.interface import NodeParser
> from llama_index.core.service_context_elements.llama_logger import LlamaLogger
> from llama_index.core.callbacks.base import CallbackManager
> from llama_index.core.schema import TransformComponent
> from llama_index.core.service_context import ServiceContext
> 
> # Initialize the components
> llm_predictor = LLMPredictor()
> embed_model = BaseEmbedding()
> prompt_helper = PromptHelper()
> node_parser = NodeParser()
> llama_logger = LlamaLogger()
> callback_manager = CallbackManager()
> 
> # Create the ServiceContext
> service_context = ServiceContext(
>     llm_predictor=llm_predictor,
>     prompt_helper=prompt_helper,
>     embed_model=embed_model,
>     transformations=[node_parser],
>     llama_logger=llama_logger,
>     callback_manager=callback_manager
> )
> 
> # Set the global service context
> set_global_service_context(service_context)
> ```
> 
> 此设置确保所有必要的组件都已初始化并可用于该`KnowledgeGraphIndex.from_documents()`方法正常工作[[1] ](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/service_context.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/base.py)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

好的，是我看文档的问题。确实需要这个service_context。
将您的代码加入到我的代码中  NodeParser 这个类的实例化我没有解决成功，请问这个是什么原因呀？

Traceback (most recent call last):
  File "D:\code_llm\LLama-Index\lcm3.py", line 68, in <module>
    node_parser = NodeParser()
                  ^^^^^^^^^^^^
TypeError: Can't instantiate abstract class NodeParser with abstract method _parse_nodes

**Comment by GOOD-N-LCM** [comment]
> 您遇到的错误是因为`NodeParser`是抽象类，无法直接实例化。您需要使用它的具体实现之一，例如`HTMLNodeParser`、`JSONNodeParser`、`MarkdownNodeParser`或`SimpleFileNodeParser`。
> 
> 下面是一个如何实例化的示例`SimpleFileNodeParser`：
> 
> ```python
> from llama_index.core.node_parser.file.simple_file import SimpleFileNodeParser
> 
> # Instantiate the SimpleFileNodeParser
> node_parser = SimpleFileNodeParser.from_defaults()
> 
> # Now you can use this node_parser in your ServiceContext
> service_context = ServiceContext(
>     llm_predictor=llm_predictor,
>     prompt_helper=prompt_helper,
>     embed_model=embed_model,
>     transformations=[node_parser],
>     llama_logger=llama_logger,
>     callback_manager=callback_manager
> )
> 
> # Set the global service context
> set_global_service_context(service_context)
> ```
> 
> `SimpleFileNodeParser`如果需要，请用任何其他特定实现替换`NodeParser`，例如`HTMLNodeParser`、`JSONNodeParser`或`MarkdownNodeParser` [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/node_parser/__init__.py)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

抱歉  ，按照您的方法 ，依旧是那个错误  T_T

**Comment by GOOD-N-LCM** [comment]
> 错误仍然存​​在，因为`NodeParser`是抽象类，无法直接实例化。您需要使用它的具体实现之一。以下是使用的示例`SimpleFileNodeParser`：
> 
> ```python
> from llama_index.core.node_parser.file.simple_file import SimpleFileNodeParser
> from llama_index.core.service_context import ServiceContext
> from llama_index.core.service_context_elements.llm_predictor import LLMPredictor
> from llama_index.core.base.embeddings.base import BaseEmbedding
> from llama_index.core.indices.prompt_helper import PromptHelper
> from llama_index.core.service_context_elements.llama_logger import LlamaLogger
> from llama_index.core.callbacks.base import CallbackManager
> 
> # Instantiate the SimpleFileNodeParser
> node_parser = SimpleFileNodeParser.from_defaults()
> 
> # Initialize other components
> llm_predictor = LLMPredictor()
> embed_model = BaseEmbedding()
> prompt_helper = PromptHelper()
> llama_logger = LlamaLogger()
> callback_manager = CallbackManager()
> 
> # Create the ServiceContext
> service_context = ServiceContext(
>     llm_predictor=llm_predictor,
>     prompt_helper=prompt_helper,
>     embed_model=embed_model,
>     transformations=[node_parser],
>     llama_logger=llama_logger,
>     callback_manager=callback_manager
> )
> 
> # Set the global service context
> set_global_service_context(service_context)
> ```
> 
> 如果需要，请确保`SimpleFileNodeParser`用任何其他特定`NodeParser`实现进行替换，例如`HTMLNodeParser`、`JSONNodeParser`或`MarkdownNodeParser` [[1] ](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/node_parser/interface.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/node_parser/__init__.py)。
> 
> _要继续与[Dosu](https://dosu.dev)交谈，请提及@dosu。_

感谢您的帮助。以上问题我已经解决了
但是我在运行它报错了  是nebula不允许我写入的意思吗？ 
我依照建立的
edge_types, rel_prop_names = ["type"], ["description"]
tags = ["1"]
进行写入

会报错：
Query failed. Query: INSERT VERTEX `1`(name)   VALUES "Philz":("Philz");INSERT VERTEX `1`(name)   VALUES "Berkeley":("Berkeley");INSERT EDGE `type`(`description`)   VALUES "Philz"->"Berkeley"@-4425215382545939561:("Founded in");, Param: {}Error message: Query failed. Query: INSERT VERTEX `1`(name)   VALUES "Philz":("Philz");INSERT VERTEX `1`(name)   VALUES "Berkeley":("Berkeley");INSERT EDGE `type`(`description`)   VALUES "Philz"->"Berkeley"@-4425215382545939561:("Founded in");, Param: {}Error message: SemanticError: No schema found for `1'

我一定要优先建立nebula的点才能写入成功吗？

**Comment by GOOD-N-LCM** [comment]
> Yes, you need to predefine the schema in Nebula before writing data. To avoid the error "SemanticError: No schema found for `1`", you should ensure that the tags and edge types are defined in the NebulaGraph space.
> 
> Here is how you can set up the schema:
> 
> 1. **Define Tags and Properties:**
>    Use the `CREATE TAG` statement to define tags and their properties.
>    ```sql
>    CREATE TAG `1`(name string);
>    ```
> 2. **Define Edge Types and Properties:**
>    Use the `CREATE EDGE` statement to define edge types and their properties.
>    ```sql
>    CREATE EDGE `type`(description string);
>    ```
> 3. **Refresh the Schema:**
>    Use the `refresh_schema` method to refresh the schema in your NebulaGraph store.
>    ```python
>    def refresh_schema(self) -> None:
>        """
>        Refreshes the NebulaGraph Store Schema.
>        """
>        tags_schema, edge_types_schema, relationships = [], [], []
>        for tag in self.execute("SHOW TAGS").column_values("Name"):
>            tag_name = tag.cast()
>            tag_schema = {"tag": tag_name, "properties": []}
>            r = self.execute(f"DESCRIBE TAG `{tag_name}`")
>            props, types, comments = (
>                r.column_values("Field"),
>                r.column_values("Type"),
>                r.column_values("Comment"),
>            )
>            for i in range(r.row_size()):
>                property_defination = (
>                    (props[i].cast(), types[i].cast())
>                    if comments[i].is_empty()
>                    else (props[i].cast(), types[i].cast(), comments[i].cast())
>                )
>                tag_schema["properties"].append(property_defination)
>            tags_schema.append(tag_schema)
>        for edge_type in self.execute("SHOW EDGES").column_values("Name"):
>            edge_type_name = edge_type.cast()
>            edge_schema = {"edge": edge_type_name, "properties": []}
>            r = self.execute(f"DESCRIBE EDGE `{edge_type_name}`")
>            props, types, comments = (
>                r.column_values("Field"),
>                r.column_values("Type"),
>                r.column_values("Comment"),
>            )
>            for i in range(r.row_size()):
>                property_defination = (
>                    (props[i].cast(), types[i].cast())
>                    if comments[i].is_empty()
>                    else (props[i].cast(), types[i].cast(), comments[i].cast())
>                )
>                edge_schema["properties"].append(property_defination)
>            edge_types_schema.append(edge_schema)
>    ```
> 
> By following these steps, you can ensure that the schema is correctly set up in NebulaGraph, and you can avoid the "SemanticError: No schema found for `1`" error [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_graph_store.py)[[2]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/graph_stores/llama-index-graph-stores-nebula/llama_index/graph_stores/nebula/nebula_property_graph.py)[[3]](https://github.com/run-llama/llama_index/blob/main/llama-index-legacy/llama_index/legacy/graph_stores/nebulagraph.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

OHHHHH!  Thanks!!!!!!!!!!!!!  非常感觉您这一系列的帮助！代码已经能够全部正常运行了！！

**Comment by logan-markewich** [comment]
I'm glad dosu could help!
