### ISSUE TITLE
[Question]: llm not set, when specified in `get_response_synthesizer`

### ISSUE THREAD

**Issue by ivholmlu** [run-llama/llama_index#15042]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When using the get_response_synthesizer from `llama_index.core.response_synthesizers.factory` i am running into the issue:

"""
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
"""

I want to run with a local model, so want to specify the llm.

My usage:
```
ollama_llm = Ollama(model=DataPipelineConfig_Evaluation.DATA_MODEL_LLM, request_timeout=5000)
context_synthesizer = get_response_synthesizer( 
    llm=ollama_llm,  
    response_mode="no_text",
)
```

Same error is thrown, with both None or a llm specified.
Have searched elsewehere online for explanation/answer but not been able to find. Appreciate the help!

Version: 0.10.58

**Comment by logan-markewich** [comment]
Ah, I see the llm is not passed into the no-text response synthesizer (even though it doesn't use it)

Workaround for now is just change the global default
```
from llama_index.core import Settings

Settings.llm = Ollama(...)
```

**Comment by ivholmlu** [comment]
Copy, thanks for the quick reply!
