### ISSUE TITLE
[Question]: Splitting of metadata in `CompactAndRefine`

### ISSUE THREAD

**Issue by theta-lin** [run-llama/llama_index#15054]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When using `CompactAndRefine` as a response synthesizer, suppose that I have retrieved a document/node, which consists of two parts, `metadata` and `text`. When presenting the node to `CompactAndRefine`, one possible situation is the the node is too large to fit in the context window, and therefore got split in the middle of the `text`. Thus, the first LLM call might look like this:

```
prompt
metadata
text part 1
```

And the second LLM call would look like this:

```
prompt
previous summary
text part 2
```

However, this would mean that the second LLM call does not actually provide the LLM with the metadata of the node (unless the LLM is smart enough to keep it in the previous summary). Ideally, I think the second LLM call should look like this:

```
prompt
previous summary
metadata
text part 2
```

The relevant code are the follows. You can see that the nodes are simply converted to texts, concatenated together, then split into chunks.
https://github.com/run-llama/llama_index/blob/d3abf789800f4366fec7f607be15804a4a72ee52/llama-index-core/llama_index/core/response_synthesizers/base.py#L251-L257
https://github.com/run-llama/llama_index/blob/d3abf789800f4366fec7f607be15804a4a72ee52/llama-index-core/llama_index/core/response_synthesizers/compact_and_refine.py#L50-L57
https://github.com/run-llama/llama_index/blob/d3abf789800f4366fec7f607be15804a4a72ee52/llama-index-core/llama_index/core/indices/prompt_helper.py#L276-L280

I think
https://github.com/run-llama/llama_index/blob/d3abf789800f4366fec7f607be15804a4a72ee52/llama-index-core/llama_index/core/node_parser/text/token.py#L109-L110
might be intended for this purpose. However, this method is not actually used anywhere in the code besides the tests.

Therefore, what would be the best way to preserve node metadata after splitting a node across multiple chunks in implementation and how `CompactAndRefine` might be improved?

**Comment by logan-markewich** [comment]
Since by the time it splits, all it has is text, there's no easy way really to ensure metadata doesn't get split. Overall though I think this is mostly a lower-priority edge case? Especially as LLM inputs get larger and larger

**Comment by theta-lin** [comment]
Yes, I agree that this is of a lower priority when the LLM has a larger context window. However, I think it is still possible to take metadata into account when splitting, but this either requires `CompactAndRefine` to use `split_text_metadata_aware()` directly or support the handling of metadata in `PromptHelper`. I would work on a solution if needs arise.
