### ISSUE TITLE
[Question]: Embedding class in Llama Index for a general endpoint request

### ISSUE THREAD

**Issue by aalbersk** [run-llama/llama_index#15062]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I'm using Torchserve to get embeddings for my pipeline. I would like to use some Embedding class in Llama Index that would just receive an endpoint and return embeddings. I tried using TextEmbeddingsInference class for this, but it adds a "/embed" suffix to the self.base_url, so when I have an endpoint looking like this: `http://localhost:8090/predictions/all-MiniLM-L6-v2` it obviously doesn't work.

![image](https://github.com/user-attachments/assets/1cfbe692-d9de-4da2-a9a7-a92aebb075d3)

Does Llama Index support general endpoint request e.g. through Torchserve? If not, what is currently best known approach to use for such cases?

**Comment by logan-markewich** [comment]
@aalbersk there is no generic class, since the api endpoint and the returned result could be anything.

The best approach here is just implementing the base class
https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings/#custom-embedding-model

**Comment by aalbersk** [comment]
> @aalbersk there is no generic class, since the api endpoint and the returned result could be anything.
> 
> The best approach here is just implementing the base class https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings/#custom-embedding-model

Thanks for the reply! Do you plan to implement such Embeddings class in the future? If not, why?
