### ISSUE TITLE
[Documentation]: 

### ISSUE THREAD

**Issue by Maneesh9063** [run-llama/llama_index#15097]
### Documentation Issue Description

The documentation page 
https://docs.llamaindex.ai/en/stable/
is reloading automatically and showing web page inactive in mobile

please check 

### Documentation Link

https://docs.llamaindex.ai/en/stable/

**Comment by logan-markewich** [comment]
Its working fine for me 🤔 I have a feeling it might be mendable

**Comment by Maneesh9063** [comment]
Even I felt the same,
It auto reloads frequently and after some time it gives “Aww Snap” error
