### ISSUE TITLE
[Feature Request]:  Support adding previously generated embedding to index

### ISSUE THREAD

**Issue by suung** [run-llama/llama_index#15112]
### Feature Description

I can generate embeddings for my nodes and then add the nodes to the VectorStoreIndex.
They are added to the vector store
There are no embeddings gnerated for them, because they already exist

### Reason

https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/indices/vector_store/base.py

Here in multiple places embeddings already set in nodes are ignored and new embeddings are generated

### Value of Feature

Much easier and consistent way to deal with self generated embeddings
Avoidance of possible extra compuation

**Comment by logan-markewich** [comment]
@suung this is already supported

https://github.com/run-llama/llama_index/blob/769e76a28aa497ec9885975a09eb8eec24713597/llama-index-core/llama_index/core/indices/utils.py#L132

If `node.embedding` is not none, the embedding will not be computed

**Comment by logan-markewich** [comment]
The vector index calls the above function here
https://github.com/run-llama/llama_index/blob/769e76a28aa497ec9885975a09eb8eec24713597/llama-index-core/llama_index/core/indices/vector_store/base.py#L145

**Comment by suung** [comment]
Hey @logan-markewich 

thanks for getting back so real quick :)

 Looks right and I might have missed it.
I was coming across this, because I was adding my own embeddings, adding the documents to the store and then by chance realised, that the open ai embeddings were called by default still.

If I come across it again, I will take a better look.
