### ISSUE TITLE
[Bug]: package does not provide version information via llama_index.__version__

### ISSUE THREAD

**Issue by johann-petrak** [run-llama/llama_index#15115]
### Bug Description

```
import llama_index
print(llama_index.__version__)
```
Does not work and it really should, this is a useful and very widely accepted convention to provide the software version to users of the package. 
Why has this not been added?

### Version

hah! all of them? More difficult to find out without llama_index.__version__

### Steps to Reproduce

See above

**Comment by logan-markewich** [comment]
llama_index is not actually a package, it's a collection of namespaced python packages: llama-index-core, llama-index-llms-openai, etc.

You can get the version for core with `llama_index.core.__version__`

AFAIK, there is no way to add the version to the top level while maintaining the namespaced import package structure

**Comment by johann-petrak** [comment]
Just for anyone who may hit this issue, the correct way to find out the version for both the namespace package and the included packages is like this:
```
from importlib.metadata import version
print("llama_index:", version("llama_index"))
print("llama_index.core", version("llama_index.core"))
print("llama)index.llms.openai", version("llama_index.llms.openai"))
```
