### ISSUE TITLE
[Bug]: Connection error when using OctoAIEmbedding with llama-index

### ISSUE THREAD

**Issue by alouiadel** [run-llama/llama_index#15135]
### Bug Description

Using OctoAIEmbedding from llama-index-embeddings-octoai (llama-index==0.10.59) results in the following issues:

Error message about missing OpenAI API key, even when using OctoAI.
Setting a fake OpenAI key leads to an APIConnectionError.
Final error: openai.APIConnectionError: Connection error.

### Version

0.10.59

### Steps to Reproduce

Use OctoAIEmbedding with llama-index==0.10.59
Attempt to create a VectorStoreIndex

### Relevant Logs/Tracbacks

```shell
Initial error :

Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.

Subsequent error after setting a fake OpenAI key:
Retrying llama_index.embeddings.openai.base.get_embeddings in 0.3866544700197091 seconds as it raised APIConnectionError: Connection error..

Final error and traceback:

Traceback (most recent call last):
  ...
  File "C:\Users\adel\AppData\Local\pypoetry\Cache\virtualenvs\fast-api-branch-P5O1GFhU-py3.11\Lib\site-packages\openai\_base_client.py", line 1007, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.

Key intermediate error:
httpx.LocalProtocolError: Illegal header value b'Bearer '
```

**Comment by logan-markewich** [comment]
Code sample? Probably just missing a spot to pass the embed model

**Comment by alouiadel** [comment]
it worked few days a go , and pushed to a branch , but tried testing it now , and got that error , here is how i am doing it 
(sample):

from llama_index.embeddings.octoai import OctoAIEmbedding
from llama_index.llms.octoai import OctoAI

octoai_api_key = os.environ.get('OCTOAI_TOKEN')

octoai = OctoAI(model="meta-llama-3.1-70b-instruct", token=octoai_api_key, max_tokens=4096)
Settings.llm = octoai
embed_model = OctoAIEmbedding(api_key=octoai_api_key)
Settings.embed_model = embed_model

**Comment by logan-markewich** [comment]
As long as thats at the start of your code (before you do anything else), I don't see why that would cause issues.
