### ISSUE TITLE
[Documentation]: Recommend a separation for openai related installations to avoid unintentional use of openai related packages

### ISSUE THREAD

**Issue by HarikrishnanK9** [run-llama/llama_index#15137]
### Documentation Issue Description

when somebody uses pip install llama-index-core it will automatically installs openai related dpendencies automatically.for example i have created a new environment named index_env and tried pip install llama-index-core,not only installed llama-index-core==0.10.60 but also openai==1.38.0 ;So when a user uses open source llms by keeping openai key in his .env had no direct idea about this because there is another installation recommended in your github page " pip install llama-index-llms-openai " to install openai related dependencies seperately!!. if i use pip install llama-index-core and separately deletes openai,after that when i installs pip install llama-index-llms-openai then also i get both the openai==1.38.0 and llama-index-llms-openai==0.1.27 ;so i request you to separate openai installation from pip install llama-index-core otherwise user can directly istall openai separately.Remember this is just a suggestion to overcome to avoid unintentional use or installation of openai that sometimes user may not aware it exists or not while trying with open source llms while keeping OPENAI_API_KEY in there .env files.But identified that if we pass path to such .env files some of the llamindex tool such as SubQuestionQuery Engine will utilizes openai without user permission,eventhoug opensource llms details specified in variables and in Setting.llm=llm as opensource.Its a serious matter of concern an dpossiblity for conflicts that may lead to affect confidentiality if somebody use openai that lead to confidential data leakage

Another thing i have noticed that if just try pip install llama-index it will install several openai related dependencies including llama-index-embeddings-openai==0.1.11,llama-index-llms-openai==0.1.27,llama-index-multi-modal-llms-openai==0.1.8,llama-index-program-openai==0.1.7,llama-index-question-gen-openai==0.1.3,openai==1.38.0

i recommend openai related dependncies must be separated and must have a separate installation otherwise if user forgot to check by pip freeze,everything will be up to you.

### Documentation Link

https://github.com/run-llama/llama_index

**Comment by logan-markewich** [comment]
`llama-index` is a starter package around several sub-packages. You can always install core and whatever else you need.

There is a `Settings` object that controls global defaults. If you don't want to use openai, set these to something else.
