### ISSUE TITLE
[Documentation]: LM Format Enforcer Regular Expression Generation is obsolete, needs import fix.

### ISSUE THREAD

**Issue by Ajith-Shenoy** [run-llama/llama_index#15143]
### Documentation Issue Description

The reference to  lm-format-enforcer is obsolete.

```python 
from llama_index.core.prompts.lmformatenforcer_utils import (
    activate_lm_format_enforcer,
    build_lm_format_enforcer_function,
)
```
Should be 

```python
from llama_index.program.lmformatenforcer.utils import (
    activate_lm_format_enforcer,
    build_lm_format_enforcer_function,
)
```

For the imports to work the users also need to install:
```pip install llama-index-program-lmformatenforcer```

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/output_parsing/lmformatenforcer_regular_expressions/

**Comment by Ajith-Shenoy** [comment]
@dosu can you make the changes?

**Comment by logan-markewich** [comment]
I welcome a pr @Ajith-Shenoy
