### ISSUE TITLE
[Question]: Getting a list of Document content from SimpleDirectoryReader

### ISSUE THREAD

**Issue by aclifton314** [run-llama/llama_index#15178]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

llama-index: 0.10.36
python: 3.11.9
Ubunutu 22.04

Suppose I am using a `SimpleDirectoryReader` in the following manner:

```python
docs = SimpleDirectoryReader("/path/to/my/data").load_data()
```

I can see that `docs` is a list of `Document` objects. What is the most efficient way to create a list that contains the content of each one of those `Document` objects?

**Comment by logan-markewich** [comment]
`texts = [doc.text for doc in documents]`

**Comment by aclifton314** [comment]
@logan-markewich thanks!
