### ISSUE TITLE
How can I use astream_chat method with chatEngine,

### ISSUE THREAD

**Issue by VedantR3907** [run-llama/llama_index#15171]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I use astream_chat method with chatEngine, How can I use it with API (fastapi) to stream my response to there where it should be asynchronous.

**Comment by VedantR3907** [comment]
How can I yield response from this function to the api

**Comment by fariazz** [comment]
> how can it be done without using websocket I mean to say, using SSE

Did you find a working example?

**Comment by akabeera** [comment]
@SurajKrSmitch @fariazz did you guys find a solution for astream_chat with SSE?  I'm also trying to do this but running into issues.

**Comment by fariazz** [comment]
@akabeera I don't/care if this is good practice but it works for us in a FastAPI app (we use `OpenAILike` as the LLM):

```
@app.post('/chatStream')
async def chatStream(
    request: Request,
.....
):
....
        streaming_response = await engine.astream_chat(message=user_msg_content, chat_history=formatted_history)

        async def generate():

            full_response = ""

            async for chunk_item in streaming_response.async_response_gen():
                if chunk_item is None:
                    continue
                
                full_response += chunk_item
                yield f"data: {json.dumps({'content': chunk_item})}\n\n"
```
