### ISSUE TITLE
[Question]: Issues with GraphRAG Implementation with LlamaIndex - V2 Tutorial

### ISSUE THREAD

**Issue by ulan-yisaev** [run-llama/llama_index#15173]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Issues with `GraphRAG Implementation with LlamaIndex - V2` Tutorial

Hello LlamaIndex team,

I recently followed your excellent tutorial on [GraphRAG Implementation with LlamaIndex - V2](https://docs.llamaindex.ai/en/latest/examples/cookbooks/GraphRAG_v2/) and encountered a few issues during my implementation. Here are the details of my setup and the problems I faced:

**Setup**:
- LLM: AzureOpenAI using `gpt-4o-mini`
- Embeddings: `text-embedding-3-small`

**Issues**:

1. **Entity and Relationship Patterns**:
   The existing `entity_pattern` and `relationship_pattern` were returning empty results in my setup. To resolve this, I had to replace them with the following patterns:
   ```python
   entity_pattern = r'\("entity"\$\$\$\$(.+?)\$\$\$\$(.+?)\$\$\$\$(.+?)\)'
   relationship_pattern = r'\("relationship"\$\$\$\$(.+?)\$\$\$\$(.+?)\$\$\$\$(.+?)\$\$\$\$(.+?)\)'
   ```

2. **Prompt Duplications**:
   The `KG_TRIPLET_EXTRACT_TMPL` prompt sometimes generates duplicate outputs because it prints the entities and relationships in the steps as well as in the final output. To address this, I modified the prompt to ensure only the final output is printed, without the steps.

These modifications helped me resolve the issues I was facing and improved the accuracy of the outputs. I hope this feedback helps in enhancing the tutorial further.

Thank you for providing such a comprehensive guide!

**Comment by jamesfebin** [comment]
@ulan-yisaev can you please also add the prompt update you made, or give a hint as to how you modified. Thank you

**Comment by ulan-yisaev** [comment]
@jamesfebin , certainly! I just asked not to display the steps:
```
KG_TRIPLET_EXTRACT_TMPL = """
-Goal-
Given a text document, identify all entities and their entity types from the text and all relationships among the identified entities.
Given the text, extract up to {max_knowledge_triplets} entity-relation triplets.

-Steps-
1. Identify all entities. For each identified entity, extract the following information:
- entity_name: Name of the entity, capitalized
- entity_type: Type of the entity
- entity_description: Comprehensive description of the entity's attributes and activities
Format each entity as ("entity"$$$$<entity_name>$$$$<entity_type>$$$$<entity_description>)

2. From the entities identified in step 1, identify all pairs of (source_entity, target_entity) that are *clearly related* to each other.
For each pair of related entities, extract the following information:
- source_entity: name of the source entity, as identified in step 1
- target_entity: name of the target entity, as identified in step 1
- relation: relationship between source_entity and target_entity
- relationship_description: explanation as to why you think the source entity and the target entity are related to each other

Format each relationship as ("relationship"$$$$<source_entity>$$$$<target_entity>$$$$<relation>$$$$<relationship_description>)

3. When finished, output only the extracted entities and relationships without including the steps.

-Real Data-
######################
text: {text}
######################
output:"""
```

**Comment by clxyder** [comment]
At first I was getting no relationships, but once I updated  `entity_pattern`, `relationship_pattern` and `KG_TRIPLET_EXTRACT_TMPL` accordingly it all worked for me. Thank you!

**Comment by Qutubullah1** [comment]
@ulan-yisaev  Did you also changed something in the retrieval as I am not getting the response as I am able to do indexing but at the time of querying response is empty. I checked in the code and found at this place it is not getting the regex matching.

nodes_retrieved = self.index.as_retriever(
        similarity_top_k=similarity_top_k
    ).retrieve(query_str)
pattern = r"(\w+(?:\s+\w+)*)\s*\({[^}]*}\)\s*->\s*([^(]+?)\s*\({[^}]*}\)\s*->\s*(\w+(?:\s+\w+)*)"

**Comment by Deepak12345-coder** [comment]
@clxyder I am also not getting any relationships. Could you please provide the updated details for entity_pattern, relationship_pattern, and KG_TRIPLET_EXTRACT_TMPL

**Comment by aman-toLearn** [comment]
Hi, Lets say i am already using neo4j as db for product , not dealing with documents In that case how i should approach graphrag.  @ulan-yisaev @clxyder @jamesfebin @Titan43210 @Deepak12345-coder
