### ISSUE TITLE
PandasAIReader.__init__() got an unexpected keyword argument 'llm'[Bug]: 

### ISSUE THREAD

**Issue by Rumeysakeskin** [run-llama/llama_index#15211]
### Bug Description

```
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AwqConfig

model_id = "hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4"

llm = HuggingFaceLLM(
    context_window=8192, #4096
    max_new_tokens=512,
    generate_kwargs={"temperature": 0, "do_sample": False},
    system_prompt=system_prompt,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name=model_id,
    model_name=model_id,
    device_map="auto",
    tokenizer_kwargs={"max_length": 8192} # 4096
)
```

```
from llama_index.readers.pandas_ai import PandasAIReader

loader = PandasAIReader(llm=llm)
```

I get below error:

```
----> 5 loader = PandasAIReader(llm=llm)

TypeError: PandasAIReader.__init__() got an unexpected keyword argument 'llm'
```

### Version

llama-index                             0.10.61 llama-index-agent-openai                0.2.9 llama-index-cli                         0.1.13 llama-index-core                        0.10.61 llama-index-embeddings-huggingface      0.2.2 llama-index-embeddings-openai           0.1.11 llama-index-indices-managed-llama-cloud 0.2.7 llama-index-legacy                      0.9.48 llama-index-llms-huggingface            0.2.5

### Steps to Reproduce

I noticed that `PandasAIReader `is generally used with OpenAI's LLM. Am I getting errors because I use it with HuggingFace? How can I resolve this issue?

**Comment by logan-markewich** [comment]
Pandasai expects an LLM from the pandasai package, not from the llama-index package (confusing I know)
