### ISSUE TITLE
[Feature Request]: Store-agnostic interface for retrieving document embeddings from vector index

### ISSUE THREAD

**Issue by namedgraph** [run-llama/llama_index#15230]
### Feature Description

I'm thinking about a simple `VectorStore` method like:
```python
get(doc_id: str) -> BaseNode # assuming it contains embeddings?
```
or smth like that

### Reason

I was using this code with `VectorStoreIndex` and the default vector store:
```python
for doc_id, doc in vector_index.docstore.docs.items():
    embedding = vector_index._vector_store._data.embedding_dict[doc_id]
```
Using the private `_vector_index` field was already smelly, and then this approach broke when I switched to the `FaissVectorStore`, because it has no attribute `_data`.

### Value of Feature

There are use cases such as vector index cross-linking which requires iterating documents in one index, retrieving their embeddings and then querying the other index using those embeddings

**Comment by logan-markewich** [comment]
There is already a `get_nodes` method on the base class. That could probably be updated to ensure that it actually returns embeddings (note that this method doesn't work on the default vector store, because the default vector store isn't storing embeddings)

**Comment by namedgraph** [comment]
@logan-markewich isn't it? What was I getting from the default vector store this way then? It sure looked like embeddings :)
```python
vector_index._vector_store._data.embedding_dict
```
> ensure that it actually returns embeddings

I think this is the crucial part. 

[`SimpleVectorStore.get(text_id)`](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/vector_stores/simple.py#L235) looks like the method I need. Getting embedding of a single document would be fine.
The problem is that this method is not present in the `VectorStore` superclass, therefore 3rd party vector store implementations (like FAISS) do not implement it :/ Isn't that so?

**Comment by logan-markewich** [comment]
That just returns the embeddings, not the node (in the issue above, it looked like you were describing a method to get nodes + embeddings)

**Comment by logan-markewich** [comment]
The base class is `BasePydanticVectorStore` in latest versions, `VectorStore` is deprecated (and even removed? I forget)

**Comment by namedgraph** [comment]
Yes I see [`BasePydanticVectorStore.get_nodes()`](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/vector_stores/types.py#L333) now, thanks. But it's not implemented :)
```python
NotImplementedError: get_nodes not implemented
```
