### ISSUE TITLE
[Bug]: MistralAI chat_completion  API broken

### ISSUE THREAD

**Issue by schirrmacher** [run-llama/llama_index#15250]
### Bug Description

Our build pipeline broke without doing any changes to the dependency versions.

```
        "llama-index-core==0.10.55",
        "llama-index-llms-mistralai==0.1.17",
        "llama-index-llms-gemini==0.1.11",
        "llama-index==0.10.55",
```

Error, since yesterday:

```
    from security_army_knife.models.mistral_model import MistralModel
security_army_knife/models/mistral_model.py:4: in <module>
    from llama_index.llms.mistralai import MistralAI
sak/lib/python3.11/site-packages/llama_index/llms/mistralai/__init__.py:1: in <module>
    from llama_index.llms.mistralai.base import MistralAI
sak/lib/python3.11/site-packages/llama_index/llms/mistralai/base.py:40: in <module>
    from mistralai.models.chat_completion import ToolCall
E   ModuleNotFoundError: No module named 'mistralai.models.chat_completion'
```

### Version

0.10.55

### Steps to Reproduce

Import `from llama_index.llms.mistralai import MistralAI`

**Comment by logan-markewich** [comment]
It's already fixed, mistrals client updated

`pip install -U llama-index-llms-mistralai`

**Comment by htcd-regan** [comment]
+1 Also experiencing this same issue.

**Comment by logan-markewich** [comment]
@htcd-regan this is fixed, `pip install -U llama-index-llms-mistralai`

**Comment by WAS-PlaiLabs** [comment]
This isn't working for me. I can use `-U --force-reinstall` on llama-index, get no later versions, and the same for `pip install -U --force-reinstall llama-index-llms-mistralai` and still receive the error. Did the fix get removed accidentally in latest-latest? hehe

**Comment by WAS-PlaiLabs** [comment]
I figured out my issue. Well, I didn't actually figure it out, but deleting the whole venv, and starting over worked. I don't understand why the packages were listing correct, but it was like I was accessing old code.

**Comment by kimbstocker** [comment]
You need to add the below packages as well for this to work
```
%pip install llama-index-llms-mistralai
%pip install llama-index-embeddings-mistralai
```
