### ISSUE TITLE
[Question]: llama_index.llms.openai.base.OpenAI._achat raised APIConnectionError: Connection error..

### ISSUE THREAD

**Issue by arose26** [run-llama/llama_index#15268]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Have consistent issues with connecting to OpenAI API using achat:
`llama_index.llms.openai.base.OpenAI._achat in 0.3866686329223322 seconds as it raised APIConnectionError: Connection error..
`
I'm using gpt-4o-mini. I have confirmed that it connects correctly via something like self.llm.achat_with_tools in the basic workflow example so I know it's not my API access that is the problem.
Here is the minimal code to raise the above error:
```

from llama_index.llms.openai import OpenAI
from llama_index.core.workflow import (
	Context,
	Workflow,
	StartEvent,
	StopEvent,
	step,
)

class OpenAIGenerator(Workflow):
    @step()
    async def generate(self, ev: StartEvent) -> StopEvent:
        llm = OpenAI(model="gpt-4o-mini")
        response = await llm.acomplete(ev.query)
        return StopEvent(result=str(response))


async def main():
	w = OpenAIGenerator(timeout=10, verbose=False)
	result = await w.run(query="What's LlamaIndex?")
	print(result)


if __name__ == "__main__":
	import asyncio
	asyncio.run(main())
```

Which produces error:
`Retrying llama_index.llms.openai.base.OpenAI._achat in 0.3866686329223322 seconds as it raised APIConnectionError: Connection error..`

**Comment by arose26** [comment]
I set host to https://api.openai.com/v1/chat/completions and api_key to the correct key (already set in environment but just to be sure), and I still get a connection error.

**Comment by alouiadel** [comment]
I had the same issue. I fixed it by deleting my Poetry config file, creating a new one, and then adding the libraries one by one. It might be that some of your libraries are outdated.

**Comment by arose26** [comment]
Thanks @alouiadel ! I upgraded to openai-1.40.3, and now it does work. 
One note is that it only works when I manually set the host= and api_key= in the OpenAI call, which is weird because that key is in my environment already, but hey if it works it works.

**Comment by alouiadel** [comment]
I also had to set the OpenAI key, even though I wasn’t using it (another api provider). I think it’s because they’re using OpenAI Like API Approach. My guess is that the OpenAI library isn’t fully optimized in general. Also, if your issue is fixed, close the issue to save the devs from overwhelm, lol.

**Comment by arose26** [comment]
I wanted to do one last test before closing:
I put OPENAI_BASE_API=https://api.openai.com/v1/completions in the .env file and now don't have to provide api_key and host in the OpenAI() call. 
Thanks again for the help.
