### ISSUE TITLE
[Feature Request]: Better API for `Context`

### ISSUE THREAD

**Issue by masci** [run-llama/llama_index#15276]
### Feature Description

Implement a get/set API for the `Context` instance instead of accessing the underlying `data` dictionary directly, e.g. `context.get("foo")` instead of `context.data["foo"]`

### Reason

Using a vanilla dict for context data is limiting and not very intuitive. This change would also allow for more flexible data persistence strategies, as the context data wouldn't be confined to in-memory storage in the current process.

**Comment by logan-markewich** [comment]
We do already have a kvstore abstraction. I wonder if that could be looped in a in at some point
