### ISSUE TITLE
[Feature Request]: Support for google/gemma-2-2b-it Model in LlamaIndex

### ISSUE THREAD

**Issue by AnandUgale** [run-llama/llama_index#15281]
Hello,

I am trying to access the google/gemma-2-2b-it model by downloading it locally (not using Ollama) and using it within LlamaIndex. However, due to the model's use of special tokens like `<start_of_turn>` and `<end_of_turn>`, I'm encountering difficulties in effectively integrating it.

Could you please point me to any available tutorials or cookbooks that demonstrate how to use this model with LlamaIndex? Alternatively, could you guide me on how to correctly format and process prompts for this model within the LlamaIndex framework?

**Comment by logan-markewich** [comment]
If you aren't using ollama, what llm class are you using? 

Ollama handles all the prompt formatting which makes it so easy to use 

If you are using llamacpp or hughingface, there is a messages_to_prompt argument that takes a function to transform messages into your model specific prompt

**Comment by AnandUgale** [comment]
@logan-markewich 

I am using HuggingFace's `HuggingFaceLLM` to interact with the `gemma-2-2b-it` model.

Yes, I tried defining `messages_to_prompt` and `query_wrapper_prompt`, and I am getting responses with `llm.complete` and `llm.chat`. However, when it comes to using it with the Chat Engine with Chat History, I am not getting the expected results, and the results are not correct. Below is the code I am currently using:

```python
from llama_index.llms.huggingface import HuggingFaceLLM
import torch
from transformers import BitsAndBytesConfig
from transformers import AutoModelForCausalLM, AutoTokenizer, pipeline

# Quantize to save memory
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)

# Function to generate messages to prompt
def messages_to_prompt(messages):
    prompt = "<bos>"
    for message in messages:
        if message.role == "user":
            prompt += f"<start_of_turn>user\n{message.content}<end_of_turn>"
        elif message.role == "model":
            prompt += f"<start_of_turn>model\n{message.content}<end_of_turn>"
        else:
            prompt += f"<start_of_turn>model\n{message.content}<end_of_turn>"
    return prompt

# Initialize HuggingFaceLLM
llm = HuggingFaceLLM(
    model_name="/home/anand/Testing/llm_utility/gemma-2-2b-it/",
    model_kwargs={"quantization_config": quantization_config},
    generate_kwargs={"do_sample": True, "temperature": 0.1},
    tokenizer_name="/home/anand/Testing/llm_utility/gemma-2-2b-it/",
    max_new_tokens=2048,
    query_wrapper_prompt=(
        "<bos><start_of_turn>model\n"
        "You are a helpful AI assistant.<end_of_turn>\n"
        "<start_of_turn>user\n"
        "{query_str}<end_of_turn>\n"
        "<start_of_turn>model"
    ),
    messages_to_prompt=messages_to_prompt,
    is_chat_model=True,
)
```
