### ISSUE TITLE
[Bug]: Latest versions of `llama-index-multi-modal-llms-gemini` and `llama-index-llms-gemini` are not compatible with each other

### ISSUE THREAD

**Issue by ashishb** [run-llama/llama_index#15284]
### Bug Description

llama-index-multi-modal-llms-gemini (0.1.7) depends on llama-index-llms-gemini (>=0.1.9,<0.2.0)
 and src depends on llama-index-llms-gemini (0.2.0), llama-index-multi-modal-llms-gemini is forbidden.
So, because src depends on llama-index-multi-modal-llms-gemini (0.1.7), version solving failed.

### Version

0.10.62

### Steps to Reproduce

```
pip install llama-index-llms-gemini = "0.2.0"
llama-index-multi-modal-llms-gemini = "0.1.7"
```

### Relevant Logs/Tracbacks

```shell
llama-index-multi-modal-llms-gemini (0.1.7) depends on llama-index-llms-gemini (>=0.1.9,<0.2.0)
 and src depends on llama-index-llms-gemini (0.2.0), llama-index-multi-modal-llms-gemini is forbidden.
So, because src depends on llama-index-multi-modal-llms-gemini (0.1.7), version solving failed.
```

**Comment by ashishb** [comment]
This is still broken with the new release on `llama-index-multi-modal-llms-gemini`.

I am getting `llama-index-multi-modal-llms-gemini (0.1.8) depends on llama-index-llms-gemini (>=0.1.9,<0.2.0)`

**Comment by logan-markewich** [comment]
It was a pretty straightfoward fix, would have welcomed a pr 🤷🏻
