### ISSUE TITLE
[EPIC] v0.11

### ISSUE THREAD

**Issue by nerdai** [run-llama/llama_index#15328]
- [x] #15329
- [x] #15371

**Comment by masci** [comment]
@nerdai can we close this?

**Comment by nerdai** [comment]
Yeah, we should be able to close this. There is still the mypy issue tho #15330. @logan-markewich: is mypy stuff done, or maybe this issue should't be under v0.11 epic at all

**Comment by nerdai** [comment]
agreed --- ripped out :)
