### ISSUE TITLE
[EPIC] WorkflowsMigration

### ISSUE THREAD

**Issue by nerdai** [run-llama/llama_index#15332]
Epic for tracking migration of llama-index abstractions to `Workflow`s

Legend:
🟢 - create “from-scratch” notebook
🔵 - migrate the abstraction itself to use workflows (most modules should do this)

- **query engines:**
    - [ ] #15392 🔵
    - [ ] #15391 🔵
    - [ ] #15390 🟢🔵
    - [ ] #15389 🔵
    - [ ] #15388 🔵
    - [ ] #15387 🔵
    - [ ] #15386 🟢🔵
    - [ ] #15385 🔵
    - [ ] #15384 🟢🔵
    - [ ] #15383 🟢🔵
    - [ ] #15382 🟢🔵
    - [ ] #15381 🟢🔵
    - [ ] #15380 🟢🔵
    - [ ] #15379 🟢🔵
    - [ ] #15378 🟢🔵
    - [ ] #15377 🟢🔵
    - [ ] #15376 🔵
    - [ ] #15374 🟢🔵

- **retrievers:**
    - [ ] #15334
    - [ ] #15335
    - [ ] #15336
    - [ ] #15337
    - [ ] #15338
    - [ ] #15339
    - [ ] #15340
    - [ ] #15341
    - [ ]  [don’t migrate?] index retrievers
        - [ ]  vector
        - [ ]  summary
        - [ ]  graph
        - [ ]  tree and everything else (?)
 
- **agents**
    - [ ] #15342
    - [ ] #15343
    - [ ] #15344

**Comment by logan-markewich** [comment]
This is no longer a direct effort we want to make
