### ISSUE TITLE
[Bug]: Empty sources for Agentic RAG using Llamaindex 0.10.65, working well on 0.10.56

### ISSUE THREAD

**Issue by jnardosp** [run-llama/llama_index#15349]
### Bug Description

When performing a simple Agentic RAG with a vectorQueryTool on some PDF documents; when I perform a query, and try to extract the source_nodes from the response I get [ ], what I understand is that my Agent is calling my vectorQueryTool 2 or 3 times depending on query, using it's memory and when merging the function returns it doesn't have "sources" I checked and method "run_step" in llama_index.core.agent.function_calling.step.py was changed so "agent_response" attributes are different, I don't know if that is the reason but that's my hypothesis.

### Version

0.10.65

### Steps to Reproduce

Here is a view of my Agent vectorQueryTool:
````
def getDocTools(
    file_path: str,
    name: str,
) -> str:

    documents = SimpleDirectoryReader(input_files=[file_path]).load_data()
    splitter = SentenceSplitter(chunk_size=1024)
    nodes = splitter.get_nodes_from_documents(documents)
    vectorIndex = VectorStoreIndex(nodes)
    
    def vectorQuery(
        query: str, 
    ) -> str:
        """It's used to answer questions about a topic in a document. 
  
        Args:
            query (str): text query to pass to the embedding.
        
        """
        
        query_engine = vectorIndex.as_query_engine(
            similarity_top_k=3,
        )

        response = query_engine.query(query)
        return response
        
    
    vector_query_tool = FunctionTool.from_defaults(
        name=f"vector_tool_{name}",
        fn=vectorQuery,
        description=(
            f"Useful to answer specific questions about information found in {name}"
        )
    )

    return vector_query_tool
````

And here is my Agent:
````
objIndex = ObjectIndex.from_objects(
    all_tools,
    index_cls=VectorStoreIndex,
)

objRetriever = objIndex.as_retriever(similarity_top_k=3)

agentWorker = FunctionCallingAgentWorker.from_tools(
    tool_retriever=objRetriever,
    llm=llm,
    verbose=True
)
agent = AgentRunner(agentWorker)
````

Performing this (Of course with a query):
````
response = agent.chat(query)
 print(response.source_nodes[0].get_content(metadata_mode="all"))
````
Results on an index out of range error, because source_nodes is empty.

**Comment by logan-markewich** [comment]
If there's no source nodes, that usually means no tools were called

`response.sources` will have all tool calls (if any)

**Comment by jnardosp** [comment]
Thank you all for your responses, as logan-markewich mentions, I think that the problem is that my agent is "not calling" any tool when merging all previous tool-function calling, for now I will use 0.10.56.
