### ISSUE TITLE
[Question]: Future of Query Engines?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#15351]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

With the feature freeze of query pipelines, what is the roadmap for query engines with regards to workflows (given their dispersion throughout the codebase)?

Should workflows be wrapped up as query engines to support broader compatibility with LlamaIndex, as you could with query engines, or are they intended to be a replacement?

**Comment by logan-markewich** [comment]
We have plans to convert query engines to workflows yes 👍 This should be undisruptive for users though, just under the hood changes

**Comment by brycecf** [comment]
@logan-markewich Any inkling of what that may look like?  Is it intended to go through the existing `CustomQueryEngine` class or would this be something new entirely?

**Comment by brycecf** [comment]
@logan-markewich In that case, the existing `QueryEngine` classes would remain but their underlying would become workflows?

**Comment by logan-markewich** [comment]
@brycecf exactly 👍🏻 The reason for doing this is, its non-breaking for users, but also opens up interesting optimizations for the future (i.e. any feature from workflows would be available in any query engine)
