### ISSUE TITLE
[Bug]: Azure Search Client does not get propagated via VectorStoreIndex

### ISSUE THREAD

**Issue by psureshmagadi17** [run-llama/llama_index#15350]
### Bug Description

vector_store_address= <azure endpoint>
vector_store_password= <azure api key>
search_client = SearchClient(
    endpoint=vector_store_address,
    index_name=INDEX_NAME,
    credential=AzureKeyCredential(vector_store_password)
)
# Define a query that matches all documents
query = "*"
# Set the API version
api_version = <api version>

search_mode = "all"

# Search for documents with the query
response = search_client.search(
search_text=query,
search_mode=search_mode
)

docs = [i for i in response]

llama_docs = []

for doc in docs:
    llama_docs.append(
        llama_doc(
            id_=doc['id'],
            text= doc['content'],
            metadata={                    
                    "filename": doc['filename'],
                    "file_path": doc['file_path'],
                    "a": doc['a'],
                    "b": doc['b'],
                    "c": doc['c'],
                    "page_number": doc['page_number'],
                },
            )
        )

Settings.embed_model = AzureOpenAIEmbedding(
    model=conf.openai_embedding_model,
    deployment_name=conf.openai_embedding_model,
    api_key=conf.openai_api_key,
    api_base=conf.openai_endpoint,
    azure_endpoint=conf.openai_endpoint,
    api_version=conf.openai_version,
    async_http_client=httpx.AsyncClient(proxies=<proxy>),
    http_client=httpx.Client(proxies=<proxy>),
    )

Settings.llm = AzureOpenAI(
        engine=OPENAI_GPT_4,
        model=OPENAI_GPT_4,
        temperature=0.0,
        azure_endpoint=conf.openai_endpoint,
        api_key=conf.openai_api_key,
        api_version=conf.openai_version,
        http_client=httpx.Client(proxies=<proxy>),
    )

sample_llama_docs = random.sample(llama_docs, 50)

llama_vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    filterable_metadata_field_keys=['filename', 'a', 'b', 'c'],
    id_field_key="id",
    chunk_field_key="content",
    embedding_field_key="content_vector",
    doc_id_field_key="id",
    metadata_string_field_key="metadata"
    )

  storage_context = StorageContext.from_defaults(vector_store=llama_vector_store)
  
  index = VectorStoreIndex.from_documents(
      [],
      storage_context=storage_context,
      embed_model=Settings.embed_model,
  )

relevant_ids = [i for i in dict(qa_dataset)['relevant_docs'].keys()]

g,s,f=qa_dataset.relevant_docs[relevant_ids[0]][0].split('_')[:3]

a_filter = MetadataFilter(key=a, operator=FilterOperator.EQUAL_TO, value=g)
b_filter = MetadataFilter(key=b, operator=FilterOperator.EQUAL_TO, value=s)
c_filter = MetadataFilter(key=c, operator=FilterOperator.EQUAL_TO, value=f)

filter_names = [a_filter, b_filter, c_filter]
filters = MetadataFilters(filters=filter_names, condition=FilterCondition.AND)

test_llama_retriver = index.as_retriever(similarity_top_k=3, filters=filters)

# this works
print(test_llama_retriver.retrieve('Whats the name?'))
print("\n\n")

retriever_evaluator = RetrieverEvaluator.from_metric_names(
["mrr", "hit_rate", "precision", "recall"], retriever=test_llama_retriver
)

sample_id=relevant_ids[0]
sample_query = qa_dataset.queries[sample_id]
sample_expected = qa_dataset.relevant_docs[sample_id]

nest_asyncio.apply()

eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)

print(eval_result)

Issue: `eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)` triggers "AttributeError: 'NoneType' object has no attribute 'search'

After tracing the code, the below function causes the issue -

`async def _acreate_query_result(
        self, search_query: str, vectors: Optional[List[Any]]
    ) -> VectorStoreQueryResult:
        results = await self._search_client.search(
            search_text=search_query,
            vector_queries=vectors,
            top=self._query.similarity_top_k,
            select=self._select_fields,
            filter=self._odata_filter,
        )

        id_result = []
        node_result = []
        score_result = []

        async for result in results:
            node_id = result[self._field_mapping["id"]]
            metadata_str = result[self._field_mapping["metadata"]]
            metadata = json.loads(metadata_str) if metadata_str else {}
            score = result["@search.score"]
            chunk = result[self._field_mapping["chunk"]]

            try:
                node = metadata_dict_to_node(metadata)
                node.set_content(chunk)
            except Exception:
                # NOTE: deprecated legacy logic for backward compatibility
                metadata, node_info, relationships = legacy_metadata_dict_to_node(
                    metadata
                )

                node = TextNode(
                    text=chunk,
                    id_=node_id,
                    metadata=metadata,
                    start_char_idx=node_info.get("start", None),
                    end_char_idx=node_info.get("end", None),
                    relationships=relationships,
                )

            logger.debug(f"Retrieved node id {node_id} with node data of {node}")

            id_result.append(node_id)
            node_result.append(node)
            score_result.append(score)

        logger.debug(
            f"Search query '{search_query}' returned {len(id_result)} results."
        )

        return VectorStoreQueryResult(
            nodes=node_result, similarities=score_result, ids=id_result
        )
`

This is because I need to convert `AzureAISearchVectorStore` to a `VectorStoreIndex` object to use `as_retriever` and the `search_client` passed to instantiate `AzureAISearchVectorStore` does not get propagated to VectorStoreIndex

I even tried manually overriding `index._search_client = search_client` but does not work

llama-index versions:

| Package                                 	| Version 	|
|-----------------------------------------	|---------	|
| llama-index                             	| 0.10.62 	|
| llama-index-agent-openai                	| 0.2.9   	|
| llama-index-cli                         	| 0.1.13  	|
| llama-index-core                        	| 0.10.62 	|
| llama-index-embeddings-azure-openai     	| 0.1.11  	|
| llama-index-embeddings-openai           	| 0.1.11  	|
| llama-index-indices-managed-llama-cloud 	| 0.2.7   	|
| llama-index-legacy                      	| 0.9.48  	|
| llama-index-llms-azure-openai           	| 0.1.10  	|
| llama-index-llms-openai                 	| 0.1.29  	|
| llama-index-multi-modal-llms-openai     	| 0.1.9   	|
| llama-index-program-openai              	| 0.1.7   	|
| llama-index-question-gen-openai         	| 0.1.3   	|
| llama-index-readers-file                	| 0.1.32  	|
| llama-index-readers-llama-parse         	| 0.1.6   	|
| llama-index-vector-stores-azureaisearch 	| 0.1.13  	|

@dosubot 

### Version

0.10.62

### Steps to Reproduce

vector_store_address= <azure endpoint>
vector_store_password= <azure api key>
search_client = SearchClient(
    endpoint=vector_store_address,
    index_name=INDEX_NAME,
    credential=AzureKeyCredential(vector_store_password)
)
# Define a query that matches all documents
query = "*"
# Set the API version
api_version = <api version>

search_mode = "all"

# Search for documents with the query
response = search_client.search(
search_text=query,
search_mode=search_mode
)

docs = [i for i in response]

llama_docs = []

for doc in docs:
    llama_docs.append(
        llama_doc(
            id_=doc['id'],
            text= doc['content'],
            metadata={                    
                    "filename": doc['filename'],
                    "file_path": doc['file_path'],
                    "a": doc['a'],
                    "b": doc['b'],
                    "c": doc['c'],
                    "page_number": doc['page_number'],
                },
            )
        )

Settings.embed_model = AzureOpenAIEmbedding(
    model=conf.openai_embedding_model,
    deployment_name=conf.openai_embedding_model,
    api_key=conf.openai_api_key,
    api_base=conf.openai_endpoint,
    azure_endpoint=conf.openai_endpoint,
    api_version=conf.openai_version,
    async_http_client=httpx.AsyncClient(proxies=<proxy>),
    http_client=httpx.Client(proxies=<proxy>),
    )

Settings.llm = AzureOpenAI(
        engine=OPENAI_GPT_4,
        model=OPENAI_GPT_4,
        temperature=0.0,
        azure_endpoint=conf.openai_endpoint,
        api_key=conf.openai_api_key,
        api_version=conf.openai_version,
        http_client=httpx.Client(proxies=<proxy>),
    )

sample_llama_docs = random.sample(llama_docs, 50)

llama_vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    filterable_metadata_field_keys=['filename', 'a', 'b', 'c'],
    id_field_key="id",
    chunk_field_key="content",
    embedding_field_key="content_vector",
    doc_id_field_key="id",
    metadata_string_field_key="metadata"
    )

  storage_context = StorageContext.from_defaults(vector_store=llama_vector_store)
  
  index = VectorStoreIndex.from_documents(
      [],
      storage_context=storage_context,
      embed_model=Settings.embed_model,
  )

relevant_ids = [i for i in dict(qa_dataset)['relevant_docs'].keys()]

g,s,f=qa_dataset.relevant_docs[relevant_ids[0]][0].split('_')[:3]

a_filter = MetadataFilter(key=a, operator=FilterOperator.EQUAL_TO, value=g)
b_filter = MetadataFilter(key=b, operator=FilterOperator.EQUAL_TO, value=s)
c_filter = MetadataFilter(key=c, operator=FilterOperator.EQUAL_TO, value=f)

# filter the retriever to respond from relevant document chunks
filter_names = [a_filter, b_filter, c_filter]
filters = MetadataFilters(filters=filter_names, condition=FilterCondition.AND)

test_llama_retriver = index.as_retriever(similarity_top_k=3, filters=filters)

# this works
print(test_llama_retriver.retrieve('Whats the patients name?'))
print("\n\n")

retriever_evaluator = RetrieverEvaluator.from_metric_names(
["mrr", "hit_rate", "precision", "recall"], retriever=test_llama_retriver
)

sample_id=relevant_ids[0]
sample_query = qa_dataset.queries[sample_id]
sample_expected = qa_dataset.relevant_docs[sample_id]

nest_asyncio.apply()

eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)

print(eval_result)

**Comment by psureshmagadi17** [comment]
@dosu - please see the example below for how I have instantiated `AzureAISearchVectorStore`

1. Create search client

```
vector_store_address= "https://app00236465-ai-search-service-nc-prod.search.windows.net"
    vector_store_password= decrypt(os.environ['AZURE_AI_SEARCH_KEY'])
    search_client = SearchClient(
        endpoint=vector_store_address,
        index_name=INDEX_NAME,
        credential=AzureKeyCredential(vector_store_password)
    )
    # Define a query that matches all documents
    query = "*"
    # Set the API version
    api_version = "2024-07-01"

    search_mode = "all"

    # Search for documents with the query
    response = search_client.search(
    search_text=query,
    search_mode=search_mode
    )

    docs = [i for i in response]

```
2. Create an instance of `AzureAISearchVectorStore`. Note that in this step, I can access the `search_client` and run queries. 

```
llama_vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    filterable_metadata_field_keys=['filename', 'a', 'b', 'c'],
    id_field_key="id",
    chunk_field_key="content",
    embedding_field_key="content_vector",
    doc_id_field_key="id",
    metadata_string_field_key="metadata"
    )
```

I cannot use `llama_vector_store.as_retriever()` directly. Hence, I did step 3 below

3. ```
storage_context = StorageContext.from_defaults(vector_store=llama_vector_store)
    
    index = VectorStoreIndex.from_documents(
        [],
        storage_context=storage_context,
        embed_model=Settings.embed_model,
    )

relevant_ids = [i for i in dict(qa_dataset)['relevant_docs'].keys()]

g,s,f=qa_dataset.relevant_docs[relevant_ids[0]][0].split('_')[:3]

a_filter = MetadataFilter(key=a, operator=FilterOperator.EQUAL_TO, value=g)
b_filter = MetadataFilter(key=b, operator=FilterOperator.EQUAL_TO, value=s)
c_filter = MetadataFilter(key=c, operator=FilterOperator.EQUAL_TO, value=f)

filter_names = [a_filter, b_filter, c_filter]
filters = MetadataFilters(filters=filter_names, condition=FilterCondition.AND)

test_llama_retriver = index.as_retriever(similarity_top_k=3, filters=filters)
```
4. Pass retriever to `RetriverEvaluator`
```
    retriever_evaluator = RetrieverEvaluator.from_metric_names(
    ["mrr", "hit_rate", "precision", "recall"], retriever=test_llama_retriver
    )
    sample_id=relevant_ids[0]
    sample_query = qa_dataset.queries[sample_id]
    sample_expected = qa_dataset.relevant_docs[sample_id]

    nest_asyncio.apply()

    eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)
    
    print(eval_result)

```

But, the problem here is, once `llama_vector_store` is converted into an `index` of type `VectorStoreIndex` to be able to configure a `retriever`, it does not propagate the `search_client`. The `test_llama_retriver` does not have an attribute `search_client`.

**Comment by psureshmagadi17** [comment]
@dosu - all the above steps are already tested and I confirm that I can access `search_client` attribute of `AzureAISearchVectorStore`

```
llama_vector_store._search_client

prints - <SearchClient [endpoint=<index end point >, index=INDEX_NAME]>
```

However, I do not see any attribute called `search_client` in `test_llama_retriver` which is of type `llama_index.core.indices.vector_store.retrievers.retriever.VectorIndexRetriever` derived from `index` which is of type `llama_index.core.indices.vector_store.base.VectorStoreIndex`

Note that it's essential to pass `test_llama_retriever` to the `RetrieverEvaluator`

**Comment by psureshmagadi17** [comment]
@dosu 

I confirm that running below code produces `<SearchClient [endpoint=<index end point >, index=INDEX_NAME]>` 

```
# Ensure the search client is accessible in the retriever
assert test_llama_retriever._vector_store.client is not None
print(test_llama_retriever._vector_store.client)
```

I debugged the code further and noticed that when I run below code, I see that `self._search_client` gets set appropriately for the `llama_index.vector_stores.azureaisearch.base.AzureQueryResultSearchDefault` object in the `_acreate_query_result` function (llama-index/vector_stores/azureaisearch/base.py - AzureQueryResultSearchBase /_acreate_query_result)

```
retriever_evaluator = RetrieverEvaluator.from_metric_names(
    ["mrr", "hit_rate", "precision", "recall"], retriever=test_llama_retriver
)
```

But when below code runs, the `self._search_client` is wiped out

`eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)`

**Comment by psureshmagadi17** [comment]
@dosu

Apologies for the oversight. It looks like `self._search_client` is set accurately when I run below code :

```
test_llama_retriver = index.as_retriever(similarity_top_k=3, filters=filters)

print(test_llama_retriver.retrieve('Can you get me the name?'))
```

but the self._search_client does not seem to be set when I setup `RetrieverEvaluator`

**Comment by psureshmagadi17** [comment]
I have provided the trace of all the internal calls to llama_index made from my code. All the recommended steps have been followed already. Could you please check the trace / code flow and let me know what the issue could be? 

Please note the package versions I am using:


Package | Version
-- | --
llama-index | 0.10.62
llama-index-agent-openai | 0.2.9
llama-index-cli | 0.1.13
llama-index-core | 0.10.62
llama-index-embeddings-azure-openai | 0.1.11
llama-index-embeddings-openai | 0.1.11
llama-index-indices-managed-llama-cloud | 0.2.7
llama-index-legacy | 0.9.48
llama-index-llms-azure-openai | 0.1.10
llama-index-llms-openai | 0.1.29
llama-index-multi-modal-llms-openai | 0.1.9
llama-index-program-openai | 0.1.7
llama-index-question-gen-openai | 0.1.3
llama-index-readers-file | 0.1.32
llama-index-readers-llama-parse | 0.1.6
llama-index-vector-stores-azureaisearch | 0.1.13




```
llama_vector_store = AzureAISearchVectorStore(
    search_or_index_client=search_client,
    filterable_metadata_field_keys=['filename', 'a', 'b', 'c'],
    id_field_key="id",
    chunk_field_key="content",
    embedding_field_key="content_vector",
    doc_id_field_key="id",
    metadata_string_field_key="metadata"
    ) 
    
    -> [internal call] llama_index/vector_stores/azureaisearch/base.py (AzureAISearchVectorStore/init)
		    -> self._search_client = cast(SearchClient, search_or_index_client)
    -> test_llama_retriver = index.as_retriever(similarity_top_k=3, filters=filters)
    -> print(test_llama_retriver.retrieve('Whats the name?'))
    -> [internal call] llama_index/core/indices/vector_store/retrievers/retrievers.py (VectorIndexRetriever/_build_vector_store_query)
		    -> return VectorStoreQuery(
            query_embedding=query_bundle_with_embeddings.embedding,
            similarity_top_k=self._similarity_top_k,
            node_ids=self._node_ids,
            doc_ids=self._doc_ids,
            query_str=query_bundle_with_embeddings.query_str,
            mode=self._vector_store_query_mode,
            alpha=self._alpha,
            filters=self._filters,
            sparse_top_k=self._sparse_top_k,
        )
		    -> _build_vector_store_query
				    return VectorStoreQuery(
            query_embedding=query_bundle_with_embeddings.embedding,
            similarity_top_k=self._similarity_top_k,
            node_ids=self._node_ids,
            doc_ids=self._doc_ids,
            query_str=query_bundle_with_embeddings.query_str,
            mode=self._vector_store_query_mode,
            alpha=self._alpha,
            filters=self._filters,
            sparse_top_k=self._sparse_top_k,
        )
        
    -> [internal call] llama_index/vector_stores/azureaisearch/base.py (AzureAISearchVectorStore/query)
		    -> odata_filter = None
        if query.filters is not None:
            odata_filter = self._create_odata_filter(query.filters)
            
        -> azure_query_result_search: AzureQueryResultSearchBase = (
            AzureQueryResultSearchDefault(
                query, self._field_mapping, odata_filter, self._search_client
            )
        )
        
        -> return azure_query_result_search.search()
        
        Note that in this step, I can still access `self._search_client`
    
    -> retriever_evaluator = RetrieverEvaluator.from_metric_names(
    ["mrr", "hit_rate", "precision", "recall"], retriever=test_llama_retriver
    )
    
    -> eval_result = retriever_evaluator.evaluate(sample_query,sample_expected)

		-> [internal call] llama_index/embeddings/azure_openai/base.py (AzureOpenAIEmbedding/_get_aclient)
				-> if not self.reuse_client:
            return AsyncAzureOpenAI(**self._get_credential_kwargs(is_async=True))

        if self._aclient is None:
            self._aclient = AsyncAzureOpenAI(
                **self._get_credential_kwargs(is_async=True)
            )
        return self._aclient
        
        -> [internal call] llama_index/core/indices/vector_store/retrievers/retriever.py (VectorIndexRetriever/_aretrieve)
        -> async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        embedding = query_bundle.embedding
        if self._vector_store.is_embedding_query:
            if query_bundle.embedding is None and len(query_bundle.embedding_strs) > 0:
                embed_model = self._embed_model
                embedding = await embed_model.aget_agg_embedding_from_queries(
                    query_bundle.embedding_strs
                )
        return await self._aget_nodes_with_embeddings(
            QueryBundle(query_str=query_bundle.query_str, embedding=embedding)
        )
        
        -> llama_index/core/indices/vector_store/retrievers/retriever.py (VectorIndexRetriever)
        ->        async def _aget_nodes_with_embeddings(
        self, query_bundle_with_embeddings: QueryBundle
    ) -> List[NodeWithScore]:
        query = self._build_vector_store_query(query_bundle_with_embeddings)
        query_result = await self._vector_store.aquery(query, **self._kwargs)
        return self._build_node_list_from_query_result(query_result)
				-> def _build_vector_store_query(
        self, query_bundle_with_embeddings: QueryBundle
    ) -> VectorStoreQuery:
        return VectorStoreQuery(
            query_embedding=query_bundle_with_embeddings.embedding,
            similarity_top_k=self._similarity_top_k,
            node_ids=self._node_ids,
            doc_ids=self._doc_ids,
            query_str=query_bundle_with_embeddings.query_str,
            mode=self._vector_store_query_mode,
            alpha=self._alpha,
            filters=self._filters,
            sparse_top_k=self._sparse_top_k,
        )
        
        -> async def _acreate_query_result(
        self, search_query: str, vectors: Optional[List[Any]]
    ) -> VectorStoreQueryResult:
        results = await self._search_client.search(
            search_text=search_query,
            vector_queries=vectors,
            top=self._query.similarity_top_k,
            select=self._select_fields,
            filter=self._odata_filter,
        )

        id_result = []
        node_result = []
        score_result = []

        async for result in results:
            node_id = result[self._field_mapping["id"]]
            metadata_str = result[self._field_mapping["metadata"]]
            metadata = json.loads(metadata_str) if metadata_str else {}
            score = result["@search.score"]
            chunk = result[self._field_mapping["chunk"]]

            try:
                node = metadata_dict_to_node(metadata)
                node.set_content(chunk)
            except Exception:
                # NOTE: deprecated legacy logic for backward compatibility
                metadata, node_info, relationships = legacy_metadata_dict_to_node(
                    metadata
                )

                node = TextNode(
                    text=chunk,
                    id_=node_id,
                    metadata=metadata,
                    start_char_idx=node_info.get("start", None),
                    end_char_idx=node_info.get("end", None),
                    relationships=relationships,
                )

            logger.debug(f"Retrieved node id {node_id} with node data of {node}")

            id_result.append(node_id)
            node_result.append(node)
            score_result.append(score)

        logger.debug(
            f"Search query '{search_query}' returned {len(id_result)} results."
        )

        return VectorStoreQueryResult(
            nodes=node_result, similarities=score_result, ids=id_result
        )

    def search(self) -> VectorStoreQueryResult:
        search_query = self._create_search_query()
        vectors = self._create_query_vector()
        return self._create_query_result(search_query, vectors)

    async def asearch(self) -> VectorStoreQueryResult:
        search_query = self._create_search_query()
        vectors = self._create_query_vector()
        return await self._acreate_query_result(search_query, vectors)


class AzureQueryResultSearchDefault(AzureQueryResultSearchBase):
    def _create_query_vector(self) -> Optional[List[Any]]:
        """Query vector store."""
        from azure.search.documents.models import VectorizedQuery

        if not self._query.query_embedding:
            raise ValueError("Query missing embedding")

        vectorized_query = VectorizedQuery(
            vector=self._query.query_embedding,
            k_nearest_neighbors=self._query.similarity_top_k,
            fields=self._field_mapping["embedding"],
        )
        vector_queries = [vectorized_query]
        logger.info("Vector search with supplied embedding")
        return vector_queries


class AzureQueryResultSearchSparse(AzureQueryResultSearchBase):
    def _create_search_query(self) -> str:
        if self._query.query_str is None:
            raise ValueError("Query missing query string")

        search_query = self._query.query_str

        logger.info(f"Hybrid search with search text: {search_query}")
        return search_query

```

**Comment by psureshmagadi17** [comment]
@dosu 

Can you provide more detailed steps on how to explicitly pass the search_client to the asynchronous context (Specifically to be able to use `RetrieverEvaluator`)? 
Or be able to make sure `AzureQueryResultSearchBase` class and its derived classes correctly maintain the `self._search_client` throughout the asynchronous calls?

**Comment by psureshmagadi17** [comment]
@dosu 

I do not see any code changes in `AzureQueryResultSearchBase`. What should I modify?

**Comment by psureshmagadi17** [comment]
@dosu that does not help at all. The async method `_acreate_query_result` is already being called.

**Comment by ZumelzuR** [comment]
I didn't have time to read all the code but the main problem is when you use reactAgents or Subquery tools, if you inside of this tool or agent need to call an index that was setup previously using Azure plugin, you will lost in memory your credentials when the subagent subtool try to call the instance. I solved putting out from any class (means in main global memory of the python file) all the initializations of Azure and the use this or pass this in the constructor of the classes or tools.
