### ISSUE TITLE
[Question]: UnpicklingError in Sentence Embedding Optimizer

### ISSUE THREAD

**Issue by narenSb1837** [run-llama/llama_index#15368]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

In Citation query engine, I am using rerank = SentenceEmbeddingOptimizer(embed_model=Settings.embed_model, percentile_cutoff=0.5, threshold_cutoff=0.85) it works fine for most of the cases but for some cases I am getting 

UnpicklingError: global 'copy_reg._reconstructor' is forbidden error

As i further analysed the error I found it in the line ,

        if tokenizer_fn is None:
            import nltk.data

 ----> tokenizer = nltk.data.load("tokenizers/punkt/english.pickle")
            tokenizer_fn = tokenizer.tokenize

which goes to 

class RestrictedUnpickler(pickle.Unpickler):
    """
    Unpickler that prevents any class or function from being used during loading.
    """

    def find_class(self, module, name):
        raise pickle.UnpicklingError(f"global '{module}.{name}' is forbidden")

which in nltk is coded to restrict any unpickler 

how can we unblock this and what are the possible values of tokenizer_fn that can be passed as an attribute in SentenceEmbeddingOptimizer

**Comment by logan-markewich** [comment]
Nltk updated to fix a CVE. Will have to investigate a workaround

**Comment by narenSb1837** [comment]
Got it thanks 👍
