### ISSUE TITLE
[Feature Request]: Handle human-in-the-loop

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_index#15373]
### Feature Description

Workflows should likely provide some more dedicated mechanism for human-in-the-loop

My main concern here is that the asyncio timeouts will not play nice once you add the latency of an actual person needed into respond. I almost wonder if there should be some generic human-in-the-loop helper/abstraction that we provide to work with workflows.

(As for human-on-the-loop, that needs to happen on top of a workflow, likely in tandem with stepwise execution)

### Reason

Human in the loop is a valuable feature for any agentic framework

### Value of Feature

LLMs make mistakes, humans can correct them

**Comment by nerdai** [comment]
Going to take this on, as I need to also work on the hitloop for Snowflake/Streamlit demo again lol

**Comment by nerdai** [comment]
https://github.com/nerdai/snowflake-cybersyn-demo

**Comment by nerdai** [comment]
Alright: I think we can close this ticket?

We've got two examples of how to implement human in the loop with Workflows. Still TBD how to make it happen in llama-deploy @logan-markewich but maybe that is its own ticket? Perhaps with the scoping of how to easily deploy these two human in the loop patterns.

**Comment by nerdai** [comment]
Closing this too given that @logan-markewich landed the 3rd way to implement HITL with Workflows when streaming events:

https://github.com/run-llama/llama_index/pull/16220
