### ISSUE TITLE
[Bug]: poetry add llama-index failing for v0.10.65

### ISSUE THREAD

**Issue by VyoJ** [run-llama/llama_index#15402]
### Bug Description

Tried installing llama-index on a new poetry shell and encountered an error with v0.10.65.

```
Because no versions of llama-index match >0.10.65,<0.11.0
 and llama-index (0.10.65) depends on llama-index-core (>=0.10.65,<0.11.0), llama-index (>=0.10.65,<0.11.0) requires llama-index-core (>=0.10.65,<0.11.0).
And because no versions of llama-index-core match >0.10.65,<0.11.0
 and llama-index-core (0.10.65) depends on nltk (>=3.8.2), llama-index (>=0.10.65,<0.11.0) requires nltk (>=3.8.2).
So, because no versions of nltk match >=3.8.2
 and [my_project_name] depends on llama-index (^0.10.65), version solving failed.
```

Seems to be an issue of llama-index-core having a dependency on nltk v3.8.2 but as of writing the latest version of [nltk on PyPI](https://pypi.org/project/nltk/) is v3.8.1.

![image](https://github.com/user-attachments/assets/ac142b60-5650-411e-97f2-4b63938d7cfd)

Probably can be fixed by just updating the nltk requirements in the pyproject.toml in [llama-index-core](https://github.com/run-llama/llama_index/blob/main/llama-index-core/pyproject.toml).

### Version

0.10.65

### Steps to Reproduce

1. Initialize a [new poetry project](https://python-poetry.org/docs/basic-usage/#project-setup).
2. Run ```poetry shell``` and ```poetry add llama-index``` (this automatically selected v0.10.65 as the latest version)

### Relevant Logs/Tracbacks

```shell
Because no versions of llama-index match >0.10.65,<0.11.0
 and llama-index (0.10.65) depends on llama-index-core (>=0.10.65,<0.11.0), llama-index (>=0.10.65,<0.11.0) requires llama-index-core (>=0.10.65,<0.11.0).
And because no versions of llama-index-core match >0.10.65,<0.11.0
 and llama-index-core (0.10.65) depends on nltk (>=3.8.2), llama-index (>=0.10.65,<0.11.0) requires nltk (>=3.8.2).
So, because no versions of nltk match >=3.8.2
 and bosch-vta-agentic depends on llama-index (^0.10.65), version solving failed.
```

**Comment by logan-markewich** [comment]
Hmm what, I could have sworn ntlk was updated just the other day 🤔

**Comment by logan-markewich** [comment]
We even updated all the lock files

**Comment by logan-markewich** [comment]
Will take a look

**Comment by logan-markewich** [comment]
Aha
https://github.com/nltk/nltk/issues/3301

**Comment by VyoJ** [comment]
Ah ok cool, makes sense.
Will use llama-index v0.10.64 for now till you guys update your pyproject.toml to the older (or wait for the newer) version of NLTK.
Thanks!
