### ISSUE TITLE
[Question]: Data disappear after build vector store with VectorStoreIndex.from_documents()

### ISSUE THREAD

**Issue by beety0527** [run-llama/llama_index#15416]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have load 10 .docx files using SimpleDirectoryReader(), and pretty sure it has loaded all 10 files.
However, after building vector store with VectorStoreIndex.from_documents(), it only took two files in the nodes. 
Do you know why this happened? or any possible tests I could write to check?

**Comment by logan-markewich** [comment]
How do you know it only used two?

**Comment by logan-markewich** [comment]
The default top k is 2 when retrieving, you might be referring to that

**Comment by beety0527** [comment]
> How do you know it only used two?

After I run query, only two source_nodes in the Response
And also the result output  for the query is only related to two files.

**Comment by beety0527** [comment]
> The default top k is 2 when retrieving, you might be referring to that

Good point!! Thanks for this idea, I am going to try to change the top-k config

**Comment by logan-markewich** [comment]
Yea you can set like `index.as_query_engine(similarity_top_k=2)`

**Comment by beety0527** [comment]
> Yea you can set like `index.as_query_engine(similarity_top_k=2)`

It works, thanks for helping me out
