### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#15412]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The documentation for persisting and storing index's isn't clear. 

For example I get the error `Cannot initialize from a vector store that does not store text.` when all the documents are that is loaded is `.md` files, or in otherwords text. I can't seem to find much help on the topic, and the documentation shows the usage just how I use it save for the service context -- and isn't clear what can and cannot be stored. 

I store like:

```python
        temp = folder_paths.get_temp_directory()
        vector_path = os.path.join(temp, str(uuid.uuid4()))
        
        llm_index.storage_context.persist(persist_dir=vector_path)
```

And load like:

```python
        if not os.path.exists(vector_store_path) or not os.path.isdir(vector_store_path):
            raise Exception(f"Invalid vector store path: {vector_store_path}")
        
        storage_context = StorageContext.from_defaults(persist_dir=vector_store_path)
        llm_index = VectorStoreIndex.from_vector_store(
            vector_store=storage_context.vector_store,
            storage_context=storage_context,
            service_context=llm_service_context
        )
```

**Comment by logan-markewich** [comment]
You should be loading with 

`index = load_index_from_storage(storage_context, service_context=service_context)`

**Comment by WAS-PlaiLabs** [comment]
Ohh! Well that would do it. Thanks for the prompt reply!
