### ISSUE TITLE
[Bug]: VectorStoreIndex.build_index_from_nodes() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by WAS-PlaiLabs** [run-llama/llama_index#15417]
### Bug Description

I've tracked this for a few versions. I thought it was a simple mistake and was going to be quickly fixed so didn't make a report, but I'm now on `llama-index-core==0.10.66` off `llama-index==0.10.65`

### Version

0.10.65

### Steps to Reproduce

create a instance of VectorStoreIndex with nodes

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "K:\ComfyUI_win\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "K:\ComfyUI_win\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "K:\ComfyUI_win\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "K:\ComfyUI_win\custom_nodes\SaltAI_Language_Toolkit\nodes\core.py", line 268, in index
    index = VectorStoreIndex.build_index_from_nodes(
TypeError: VectorStoreIndex.build_index_from_nodes() missing 1 required positional argument: 'self'
```
```

**Comment by logan-markewich** [comment]
@WAS-PlaiLabs `build_index_from_nodes` is neither a class method nor a method that we expose to users anywhere in our documentation (except probably the API reference). It's not really meant to be used by users.

But also, it's not a bug either. If you wanted to use this method, you need an instance of the index. Dosu had the right idea above actually.

```
index = VectorStoreIndex(nodes=[], ...).build_index_from_nodes(nodes)
```

But at that point, I would just pass the nodes into the constructor 🤷🏻Or if you want to add nodes after the index is instantiated, `index.insert_nodes(nodes)` is also there

**Comment by WAS-PlaiLabs** [comment]
So basically -- it would be like **adding nodes** to a index already instantiated with documents?

**Comment by logan-markewich** [comment]
Pretty much. It's actually called inside the constructor, which is probably why the method has that name

**Comment by WASasquatch** [comment]
Well thanks for the clarification. It helps.

**Comment by WAS-PlaiLabs** [comment]
Thanks for the clarification. That helps. Makes sense.
