### ISSUE TITLE
[Bug]: NeptuneAnalyticsPropertyGraphStore incorrectly assigning the embedding to the chunk instead of the entity

### ISSUE THREAD

**Issue by bechbd** [run-llama/llama_index#15414]
### Bug Description

On this line: https://github.com/run-llama/llama_index/blob/5c9306ae150993c46d4005cac0f831bb16d1977c/llama-index-integrations/graph_stores/llama-index-graph-stores-neptune/llama_index/graph_stores/neptune/analytics_property_graph.py#L174

This should be changed to set the embedding on the entity, not the chunk
```
--WITH c, row.embedding as e
--CALL neptune.algo.vectors.upsert(c, e)
++WITH e, row.embedding as em
++CALL neptune.algo.vectors.upsert(e, em) 
```

### Version

0.10.65

### Steps to Reproduce

See line above

**Comment by logan-markewich** [comment]
Feel free to make a PR! 👍🏻
