### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.legacy.finetuning.gradient'

### ISSUE THREAD

**Issue by ShengqinYang** [run-llama/llama_index#15432]
### Bug Description

![WechatIMG93](https://github.com/user-attachments/assets/7300dbde-ea8b-41b3-a05f-d452faa571ab)

### Version

v0.10.65

### Steps to Reproduce

This bug occurs when I write: 
from llama_index.legacy.finetuning import generate_qa_embedding_pairs 
![Uploading WechatIMG94.jpg…]()

**Comment by logan-markewich** [comment]
Workaround would be to migrate off of legacy no?

**Comment by ShengqinYang** [comment]
> Workaround would be to migrate off of legacy no?
Yes，I have seen the result of your modification, thank you!
