### ISSUE TITLE
[Feature Request]: Allow to `run` a workflow instance multiple times, without waiting for the previous one to finish

### ISSUE THREAD

**Issue by logan-markewich** [run-llama/llama_index#15455]
### Feature Description

Once a workflow instance is running, you can't start another run on the instance until the previous run is done.

For example, this will break:

```python
w =Workflow()
asyncio.gather(w.run(), w.run())
```

Why is this a problem? It's a pretty common pattern to attach a workflow to a class, and run it with several different inputs.

A solid example of this is our sub question query engine, which runs several queries on the same query engine. A version of this with workflows will not work currently.

A possible solution here could be adding a `.fork()` or `.spawn()` method to create a "copy" of the workflow.

There's probably other solutions, but need to be mindful of handling the state between workflow runs (i.e. imagine doing this with a cht engine workflow)

### Reason

Running a workflow with multiple inputs is a common pattern.

**Comment by masci** [comment]
What's wrong with creating multiple instances of the same workflow class?
```py
tasks = [Workflow().run(x) for x in inputs]
results = await asyncio.gather(*tasks)
```
Workflows are designed to be lightweight (the heavy lifting of attaching and validating steps is done at class definition time) and it should never be a problem creating multiple instances.

If we don't like the syntax above, an alternative might be introducing a factory method that does exactly that:

```py
results = await Workflow.run_multi(inputs). # under the hood: asyncio.gather(*[cls().run(x) for x in inputs])
```

> need to be mindful of handling the state between workflow runs 

This is a yellow flag to me, because this problem doesn't exist using different instances

**Comment by logan-markewich** [comment]
So, to draw a parallel to existing code:

- a user creates a query engine
- they give it to sub question query engine (note: it's already initialized)
- the sub question query engine needs to use that workflow to generate answers to many sub questions
- it does this using asyncio.gather()

This pattern doesn't actually work currently. And not being able to map reduce a workflow without instansiating each instance feels slightly... janky? 🤔

**Comment by logan-markewich** [comment]
Basically, this feels like a ux blocker if we really want to migrate all our existing query engines to use workflows

**Comment by jerryjliu** [comment]
+1 to @logan-markewich 's point i think it could be reasonable to "duplicate" a workflow (e.g. `workflow.clone()`) but if the user is treating a Workflow as a "compute graph" then they'll want to compose it on top of higher-level query engines/worfklows (e.g. Workflow3(workflow1, workflow2)) and it feels weird to instantiate multiple instances for map-reduce behavior

**Comment by masci** [comment]
Ok got it. 
Honestly I wouldn't go down the path of adding an API to "clone" or "fork" a workflow instance, even talking about "sessions" looks unnecessary to me at this level of the stack, it leaks many implementation details and it would be hard to learn and teach. I would rather make possible to invoke`run()` multiple times without raising the `Workflow is already running` error.

**Comment by jerryjliu** [comment]
> Ok got it. Honestly I wouldn't go down the path of adding an API to "clone" or "fork" a workflow instance, even talking about "sessions" looks unnecessary to me at this level of the stack, it leaks many implementation details and it would be hard to learn and teach. I would rather make possible to invoke`run()` multiple times without raising the `Workflow is already running` error.

i think that's reasonable. but that just means you'd need to maintain the concept of a session in the Workflow `init` itself right? to maintain the task queue for each separate run call

**Comment by masci** [comment]
> but that just means you'd need to maintain the concept of a session in the Workflow

Correct, the workflow instance would be responsible to internally "clone" or "fork" its own runtime
