### ISSUE TITLE
[Bug]: loading SimpleVectorStore.from_persist_dir() doesn't work when called directly

### ISSUE THREAD

**Issue by markally** [run-llama/llama_index#15451]
### Bug Description

When calling `SimpleVectorStore.from_persist_dir('./storage')` directly it fails, though it works when called implicitly `StorageContext.from_defaults(persist_dir="./storage")`. Unfortunately the first pattern is what's in the documentation for [loading data](https://docs.llamaindex.ai/en/stable/module_guides/storing/save_load/#loading-data)

It seems like it is looking for a file called `vector_store.json` which has instead been saved to `default__vector_store.json`

This may be what caused https://github.com/run-llama/llama_index/issues/12582 

### Version

0.10.65

### Steps to Reproduce

https://colab.research.google.com/drive/1sthKXrJ59lPEhm9igLD4bxj360_Uc-vu?usp=sharing

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-d5497c54b97e> in <cell line: 3>()
      2 
      3 ctx = StorageContext.from_defaults(
----> 4     vector_store=SimpleVectorStore.from_persist_dir(
      5         persist_dir="./storage")
      6 )

1 frames
/usr/local/lib/python3.10/dist-packages/llama_index/core/vector_stores/simple.py in from_persist_path(cls, persist_path, fs)
    406         fs = fs or fsspec.filesystem("file")
    407         if not fs.exists(persist_path):
--> 408             raise ValueError(
    409                 f"No existing {__name__} found at {persist_path}, skipping load."
    410             )

ValueError: No existing llama_index.core.vector_stores.simple found at ./storage/vector_store.json, skipping load.
```

**Comment by logan-markewich** [comment]
Feel free to open a pr, would be a simple update to the default fille name to look for both files

**Comment by KalyanKumarPichuka** [comment]
@logan-markewich shall work on the issue?
