### ISSUE TITLE
[Question]: What is the core difference and ideology between the abstractions "VectorStoreIndex", "StorageContext", "VectorStore". 

### ISSUE THREAD

**Issue by falakic** [run-llama/llama_index#15475]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I see index is created using a storagecontext which usually is created using nothing but a vectorstore. Also, there is usually a client or collection used to create a vectorstore. I'm confused by the number of abstractions and would like to know the distinctions between all.

**Comment by logan-markewich** [comment]
A vector store is just a class that wraps any vector store (chroma, qdrant, etc.)

The storage context bundles the vector store, plus other storage layers (docstore, etc.)

The `VectorStoreIndex` handles chunking, insertion, and shortcuts to creating chat engines and query engines, It works on top of a storage context
