### ISSUE TITLE
[Question]: Custom Index for RedisVectorStore

### ISSUE THREAD

**Issue by Taoudi** [run-llama/llama_index#15481]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When I started working on my project, it was possible to setup a RedisVectorStore with default settings. However, this is no longer possible as you now have to define a Custom Index.

This is the received error when you do not define a custom index.
`ValueError: Deprecated kwarg, index_name, found upon initialization. RedisVectorStore now requires an IndexSchema object. See the documentation for a complete example: https://docs.llamaindex.ai/en/stable/examples/vector_stores/RedisIndexDemo/`

What is even the purpose of this update? Why would you remove the option to use default settings for the index setup?? These types of updates completely kill the usability of the framework, now I have an index that is unusable unless I figure out how the default index structure USED to look like in the llama-index version I was using when I started the project. 

Sources:
https://docs.llamaindex.ai/en/latest/examples/vector_stores/RedisIndexDemo/

**Comment by logan-markewich** [comment]
Redis themselves updated the vector store to use their official RedisVL library
 
The docs make it pretty clear how easy it is to change this setting, and imo, is much more flexible

https://docs.llamaindex.ai/en/stable/examples/vector_stores/RedisIndexDemo/?h=redis#use-a-custom-index-schema

**Comment by logan-markewich** [comment]
This is a breaking change for existing indexes (i think?) which is why the version was bumped quite a but higher. Feel free to not udpdate and continue using v0.1.x as well

**Comment by Taoudi** [comment]
> Redis themselves updated the vector store to use their official RedisVL library
> 
> The docs make it pretty clear how easy it is to change this setting, and imo, is much more flexible
> 
> https://docs.llamaindex.ai/en/stable/examples/vector_stores/RedisIndexDemo/?h=redis#use-a-custom-index-schema

Understood, Ill go and complain to them instead 😄 

Thanks for the response.
