### ISSUE TITLE
[Feature Request]: Metadata filter doesn't support array as filter value and IN operator for filter searching

### ISSUE THREAD

**Issue by VRSupriya** [run-llama/llama_index#15484]
### Feature Description

I wanted to use a array as a value to my metadata filer for one of my projects. Locally I could run it by commenting couple of validations.

llama_index/core/vector_stores/types.py
--------------------------------------------
def legacy_filters(self) -> List[MetadataFilter]:
        """Convert MetadataFilters to legacy ExactMatchFilters."""
        filters = []
        for filter in self.filters:
            # if filter.operator != FilterOperator.EQ:
            #     raise ValueError(
            #         "Vector Store only supports exact match filters. "
            #         "Please use ExactMatchFilter or FilterOperator.EQ instead."
            #     )
            filters.append(MetadataFilter(key=filter.key, value=filter.value))
        return filters

llama_index/core/vector_stores/utils.py
---------------------------------------------
def _validate_is_flat_dict(metadata_dict: dict) -> None:
    """
    Validate that metadata dict is flat,
    and key is str, and value is one of (str, int, float, None).
    """
    for key, val in metadata_dict.items():
        if not isinstance(key, str):
            raise ValueError("Metadata key must be str!")
        # if not isinstance(val, (str, int, float, type(None))):
        #     raise ValueError(
        #         f"Value for metadata {key} must be one of (str, int, float, None)"
        #     )

is there any way I can use array as filter value or could you please provide this functionality so that I can use llama_index and mongodb vectorsearch for my project.

**Comment by logan-markewich** [comment]
I'm not sure why you had to comment out the legacy filters, the latest version of the package is not using legacy filters at all

https://github.com/run-llama/llama_index/blob/0ea7eec644d130b4a48389ea6fe47340b50bc094/llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/pipelines.py#L57

The only change needed in the framework would be to set flat_metadata=False on the class attribute of the vector store

**Comment by tdtu981** [comment]
Hi @logan-markewich, thanks you for your clarification. Is there any chance that we can have something like: `self.flat_metadata = flat_metadata` in this
https://github.com/run-llama/llama_index/blob/0ea7eec644d130b4a48389ea6fe47340b50bc094/llama-index-integrations/vector_stores/llama-index-vector-stores-mongodb/llama_index/vector_stores/mongodb/base.py#L92
