### ISSUE TITLE
[Feature Request]: Remove hard dependencies to CUDA and OpenAI

### ISSUE THREAD

**Issue by chaudhariatul** [run-llama/llama_index#15526]
### Feature Description

Request to remove hard dependencies that require CUDA and OpenAI python packages to be downloaded.

### Reason

Llamaindex defaults to use CUDA and OpenAI and so when developing with non CUDA devices and using different embedding models there are many packages and dependencies downloaded in the python virtual environment.

A docker image created with these requirements often uses upto 9GB and a local python environment uses 5GB or more. 

```
llama-index-embeddings-huggingface==0.2.2
llama-index-llms-ollama==0.2.2

```

### Value of Feature

1. Distributing docker images with small size will reduce cost in container registry
2. Reduce bandwidth used when downloading images
3. Enable faster deployments
4. Vulnerabilities and security risks are reduced with not including packages that are not used

**Comment by logan-markewich** [comment]
The heavy dependency here is certainly not ollama 

Hughingface embeddings have a singular dep essentially, which is sentence transformers 
https://github.com/run-llama/llama_index/blob/a51150c96f956f7c25a77738338579eedcc01798/llama-index-integrations/embeddings/llama-index-embeddings-huggingface/pyproject.toml#L36

Whether or not sentence transformers provides a installation option without cuda, I have no idea

**Comment by chaudhariatul** [comment]
Thanks for a quick response and reference!
