### ISSUE TITLE
[Bug]: use of MetadataMode within embed_nodes

### ISSUE THREAD

**Issue by bubl-ai** [run-llama/llama_index#15559]
### Bug Description

I was noticing that my embeddings didn't match when I created them with LlamaIndex compared to when I was creating them directly with a Vector Store client.

I noticed that the metadata of a TextNode (have't checked for ImageNode) is included as part of the text to be embedded.

The function `embed_nodes` within `core.indices.utils` uses `MetadataMode.EMBED` when getting the content of the node. Shouldn't this be configurable by the user? Metadata can skew significantly the embeddings and seems that this is something that the user should be able to control.

What are your thoughts?

### Version

llama-index = "0.10.65"

### Steps to Reproduce

when using `VectorStoreIndex` to create an index with nodes
```python
index = VectorStoreIndex(nodes)
```

It produces a different embedding for
```python
nodes = [
    TextNode(
        text=text,
        metadata={...}
    )
]
```

Produces a different embedding than
```python
nods = [
    TextNode(
        embeding=Settings.embed_model.get_text_embedding(text),
        metadata={...}
    )
]
```

**Comment by logan-markewich** [comment]
This is intentional and configurable 

You can configure the metadata to exclude for both embeddings and llm calls

https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents/#advanced-metadata-customization

**Comment by bubl-ai** [comment]
Amazing @logan-markewich. 
Thanks so much for the quick reply.
