### ISSUE TITLE
[Question]: ImportError: cannot import name 'root_validator' from 'llama_index.core.bridge.pydantic' 

### ISSUE THREAD

**Issue by avisheka93** [run-llama/llama_index#15583]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Code was working fine till yesterday
now receiving error 
ImportError: cannot import name 'root_validator' from 'llama_index.core.bridge.pydantic' 

(C:\Users\XX\OneDrive - XX\Documents\XX\test\.venv\Lib\site-packages\llama_index\core\bridge\pydantic.py)

while trying to build for Azure functions

contents of .venv\Lib\site-packages\llama_index\core\bridge\pydantic.py

import pydantic
from pydantic import (
    ConfigDict,
    BaseModel,
    GetJsonSchemaHandler,
    GetCoreSchemaHandler,
    Field,
    PlainSerializer,
    PrivateAttr,
    StrictFloat,
    StrictInt,
    StrictStr,
    create_model,
    model_validator,
    field_validator,
    ValidationInfo,
    ValidationError,
    TypeAdapter,
    WithJsonSchema,
    BeforeValidator,
    SerializeAsAny,
    WrapSerializer,
    field_serializer,
    Secret,
    SecretStr,
    model_serializer,
)
from pydantic.fields import FieldInfo
from pydantic.json_schema import JsonSchemaValue

__all__ = [
    "pydantic",
    "BaseModel",
    "ConfigDict",
    "GetJsonSchemaHandler",
    "GetCoreSchemaHandler",
    "Field",
    "PlainSerializer",
    "PrivateAttr",
    "model_validator",
    "field_validator",
    "create_model",
    "StrictFloat",
    "StrictInt",
    "StrictStr",
    "FieldInfo",
    "ValidationInfo",
    "TypeAdapter",
    "ValidationError",
    "WithJsonSchema",
    "BaseConfig",
    "parse_obj_as",
    "BeforeValidator",
    "JsonSchemaValue",
    "SerializeAsAny",
    "WrapSerializer",
    "field_serializer",
    "Secret",
    "SecretStr",
    "model_serializer",
]

Kindly check

**Comment by avisheka93** [comment]
@dosu Azure Open AI embeddings are trying to use root validator which is deprecated in pydantic latest version

 File "c:\Users\XX\OneDrive - EY\Documents\XXX\test\backend.py", line 22, in <module>
    from llama_index.embeddings.azure_openai import AzureOpenAIEmbedding
  File "C:\Users\XX\OneDrive - EY\Documents\XXX\test\.venv\Lib\site-packages\llama_index\embeddings\azure_openai\__init__.py", line 1, in <module>
    from llama_index.embeddings.azure_openai.base import (
  File "C:\Users\XX\OneDrive - EY\Documents\XXX\test\.venv\Lib\site-packages\llama_index\embeddings\azure_openai\base.py", line 4, in <module>
    from llama_index.core.bridge.pydantic import Field, PrivateAttr, root_validator
ImportError: cannot import name 'root_validator' from 'llama_index.core.bridge.pydantic' (C:\Users\XX\OneDrive - EY\Documents\XXX\test\.venv\Lib\site-packages\llama_index\core\bridge\pydantic.py)

**Comment by pavankumarchowdary35** [comment]
> ### Question Validation
> * [x]  I have searched both the documentation and discord for an answer.
> 
> ### Question
> Code was working fine till yesterday now receiving error ImportError: cannot import name 'root_validator' from 'llama_index.core.bridge.pydantic'
> 
> (C:\Users\XX\OneDrive - XX\Documents\XX\test.venv\Lib\site-packages\llama_index\core\bridge\pydantic.py)
> 
> while trying to build for Azure functions
> 
> contents of .venv\Lib\site-packages\llama_index\core\bridge\pydantic.py
> 
> import pydantic from pydantic import ( ConfigDict, BaseModel, GetJsonSchemaHandler, GetCoreSchemaHandler, Field, PlainSerializer, PrivateAttr, StrictFloat, StrictInt, StrictStr, create_model, model_validator, field_validator, ValidationInfo, ValidationError, TypeAdapter, WithJsonSchema, BeforeValidator, SerializeAsAny, WrapSerializer, field_serializer, Secret, SecretStr, model_serializer, ) from pydantic.fields import FieldInfo from pydantic.json_schema import JsonSchemaValue
> 
> **all** = [ "pydantic", "BaseModel", "ConfigDict", "GetJsonSchemaHandler", "GetCoreSchemaHandler", "Field", "PlainSerializer", "PrivateAttr", "model_validator", "field_validator", "create_model", "StrictFloat", "StrictInt", "StrictStr", "FieldInfo", "ValidationInfo", "TypeAdapter", "ValidationError", "WithJsonSchema", "BaseConfig", "parse_obj_as", "BeforeValidator", "JsonSchemaValue", "SerializeAsAny", "WrapSerializer", "field_serializer", "Secret", "SecretStr", "model_serializer", ]
> 
> Kindly check

Even I facing the same error today. Did you find any solution ?

**Comment by pavankumarchowdary35** [comment]
still not working

**Comment by avisheka93** [comment]
solved by changing the versions of below 2 to this:
 llama-index-embeddings-azure-openai==0.1.11
llama-index-embeddings-openai==0.1.11

check ur versions using pip freeze

**Comment by logan-markewich** [comment]
@pavankumarchowdary35 as @avisheka93 po8ntee out, please make sure all your packages are up to date. 

V0.11 of core came out, which moved to pydantic v2. You'll need to update most integrations.
