### ISSUE TITLE
[Bug]: OpenAIEmbedding has no attribute `__pydantic_private__`

### ISSUE THREAD

**Issue by philmui** [run-llama/llama_index#15623]
### Bug Description

Just tried using OpenAIEmbedding and ran into this pydantic validation error.  Seems that this class (`llama_index.embeddings.openai.base.py`) needs to add this pydantic_private attribute.

    embedding_model = OpenAIEmbedding(model=OpenAIEmbeddingModeModel.TEXT_EMBED_3_LARGE)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/llama_index/embeddings/openai/base.py", line 313, in __init__
    self._query_engine = get_engine(mode, model, _QUERY_MODE_MODEL_DICT)
    ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py", line 820, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py", line 808, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAIEmbedding' object has no attribute '__pydantic_private__'

### Version

0.11.1

### Steps to Reproduce

Try to instantiate `OpenAIEmbedding()`:

```
from llama_index.embeddings.openai import (
        OpenAIEmbedding,
        OpenAIEmbeddingModeModel
    )
EMBEDDING_MODEL_DIM = 3072 # 1536
embedding_model = OpenAIEmbedding(model=OpenAIEmbeddingModeModel.TEXT_EMBED_3_LARGE)
```

### Relevant Logs/Tracbacks

```shell
.../app/globals.py", line 25, in <module>
    embedding_model = OpenAIEmbedding(model=OpenAIEmbeddingModeModel.TEXT_EMBED_3_LARGE)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/llama_index/embeddings/openai/base.py", line 313, in __init__
    self._query_engine = get_engine(mode, model, _QUERY_MODE_MODEL_DICT)
    ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py", line 820, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pydantic/main.py", line 808, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'OpenAIEmbedding' object has no attribute '__pydantic_private__'
```

**Comment by logan-markewich** [comment]
This should be fixed 

`pip install -U llama-index-embeddings-openai`

**Comment by nerdai** [comment]
Hey @philmui just confirming that you're using the latest version of llama-index-embeddings-openai?

**Comment by philmui** [comment]
You are right: I exited my poetry shell and was in an old system environment.

All good now.  This bug report can be closed.  Thank you!

**Comment by philmui** [comment]
Bug fixed already : just needed to update my old llama-index-embeddings-openai
