### ISSUE TITLE
[Feature Request]: Specify inference parameters for Huggingface models using HuggingfaceInferenceAPI

### ISSUE THREAD

**Issue by strwberry-smggls** [run-llama/llama_index#15659]
### Feature Description

Ideally, it should be possible to specify inference parameters (such as temperature, top_k, top_p, repetition_penalty...)  when instantiating the HuggingfaceInferenceAPI class, which in turn should pass these parameters to the huggingface API. 

### Reason

Currently, there seems to be no straightforward way to specify inference parameters for models loaded with the HuggingfaceInferenceAPI. An exception to this is number of tokens with the "num_output" parameter.

### Value of Feature

Parameter tuning is important for good model performance. Different tasks may require different parameter settings, e.g. it may be desirable for RAG to be less "creative" than other generation tasks.

**Comment by AkashParua** [comment]
Working on It !
