### ISSUE TITLE
[Bug]: Mistral interface expects two different types for Mistral

### ISSUE THREAD

**Issue by fbpo23** [run-llama/llama_index#15687]
### Bug Description

I am getting a validation error for Mistral AI interface, complaining about the random seed.
On inspecting the code (`base.py`file) I found that random seed is defined this way (line 126-128):
```
random_seed: str = Field(
    default=None, description="The random seed to use for sampling."
)
```
and on the init  it is this way (line 143):
```
random_seed: Optional[int] = None,
```
So it seems there is some error here, with random seed both being considered a int and a string.

Furthermore, even though this field is marked as optional, and has a default value, if I leave it empty I get a pydantic validation error, saying it needs to be a valid string.

### Version

llama-index-core==0.11.2 and llama-index-llms-mistralai==0.2.1

### Steps to Reproduce

```
from llama_index.llms.mistralai import MistralAI

MistralAI(api_key="something")
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/francisco/.local/share/virtualenvs/caiser-mVJ7jDme/lib/python3.12/site-packages/llama_index/llms/mistralai/base.py", line 168, in __init__
    super().__init__(
  File "/home/francisco/.local/share/virtualenvs/caiser-mVJ7jDme/lib/python3.12/site-packages/pydantic/main.py", line 193, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MistralAI
random_seed
  Input should be a valid string [type=string_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/string_type
```

**Comment by logan-markewich** [comment]
Yea, the pydantic type should be marked as optional

pydantic v1 handled this, seems pydantic v2 caused this bug to be exposed
