### ISSUE TITLE
[Question]: "ChatMemoryBuffer" Stores Data in Redis but Fails to Retrieve It with "VectorStoreIndex" Query Engine

### ISSUE THREAD

**Issue by mohilmakwana31** [run-llama/llama_index#15711]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

I am using the `ChatMemoryBuffer` with the `SimpleChatEngine`, and it works as expected. The conversation is stored in Redis cache and can be retrieved correctly.

Sample code : 
```
chat_store = RedisChatStore(redis_url="redis://localhost:6379", ttl=1000)

chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=30000,
    chat_store=chat_store,
    chat_store_key="roy",
)

chat_engine = SimpleChatEngine(
    memory=memory, llm=Settings.llm, prefix_messages=[]
)
response = chat_engine.chat("Hello.")
```

In contrast, when using the `ChatMemoryBuffer` with the `VectorStoreIndex` query engine, the data is stored in Redis cache but is not retrieved properly. 

Here is the code for the `VectorStoreIndex` setup:
```
from pinecone import Pinecone
from llama_index.core import VectorStoreIndex
from llama_index.vector_stores.pinecone import PineconeVectorStore

pc = Pinecone(api_key=<api_key>)
pinecone_index = pc.Index(<index_name>)

chat_store = RedisChatStore(redis_url="redis://localhost:6379", ttl=1000)

vector_store = PineconeVectorStore(
    pinecone_index=pinecone_index
)

chat_memory = ChatMemoryBuffer.from_defaults(
    token_limit=30000,
    chat_store=chat_store,
    chat_store_key="roy",
)

query_engine = VectorStoreIndex.from_vector_store(vector_store).as_chat_engine(
    similarity_top_k=5,chat_memory = chat_memory
)
```

My first query : 
```
response = query_engine .query('My name is Roy')
response
```
Output : 
`Response(response='Hello Roy! How can I assist you today?', source_nodes=[], metadata=None)`

Second query : 
```
response = query_engine .query("What's my name?")
print(response)
```
Output : 
`I am an expert Q&A system.`

**Comment by mohilmakwana31** [comment]
@dosu But issue it when I query with query engine first my redis cache should be checked whether the question is already asked by user or not. If the question is asked it should use the existing answer otherwise it should query vector database and save new question and answer in redis cache and return it to user.

**Comment by logan-markewich** [comment]
@mohilmakwana31 the query engine/vector store does not use chat history at all. You need to use a chat engine or agent with the index//vector store

**Comment by mohilmakwana31** [comment]
@logan-markewich , thank you for the information. If possible, could you please share any documentation or reference materials that might assist further?

**Comment by BrianMwas** [comment]
I don't think this should be closed, I have been facing the same issue.. and can't seem to find an answer

**Comment by mohilmakwana31** [comment]
Yes, @BrianMwas,

I know I wasn't supposed to close this issue, but the maintainer didn't respond, and I closed it.

Here is a solution I have tried so far:

I implemented [**SimpleComposable memory**](https://docs.llamaindex.ai/en/stable/examples/agent/memory/composable_memory/). It's trying to be a mix of **VectorMemory** and **ChatMemoryBuffer**. These work pretty well for my personal projects. Please feel free to test them and let me know if you run into problems.

However, it has a problem: if it reaches a certain limit of vector memory (I am not sure what the exact number is), then even after reinitializing the memory, it throws a strange error at times. To be safe, you have to clear the memory manually.

For example, I used pgVector as my secondary memory, and it seems like fine for what I want it to do.

**Comment by BrianMwas** [comment]
Cool thanks a lot, is it possible to share a gist for the code @mohilmakwana31
