### ISSUE TITLE
[Bug]: Ingestion Pipeline absurdly slow.

### ISSUE THREAD

**Issue by AlbertoMQ** [run-llama/llama_index#15722]
### Bug Description

Even with tiny documents, ingestion pipeline takes forever to do anything. We're talking 30 minutes going by on a 3 page document without finishing. By contrast when I do a VectorStoreIndex.from_documents it finishes quite quickly.

### Version

0.10.65

### Steps to Reproduce

Relevant part of code. I also set Settings.llm to a zephyr model.

`
# set embedding model
Settings.embed_model = HuggingFaceEmbedding(
    model_name="BAAI/bge-small-en"
)

# load data
documents = SimpleDirectoryReader(input_files=[input_file]).load_data()

# Split document into sentences
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=150, chunk_overlap=0),
        TitleExtractor(),
        Settings.embed_model,
    ]
)
nodes = pipeline.run(documents=documents, show_progress=True)
`

**Comment by logan-markewich** [comment]
Well, you've sent the chunk size to be 150, and then are also running title extractor, so that's going be a LOT of compute

**Comment by logan-markewich** [comment]
You are also using a local llm for the title extractor, which will be even slower, especially without a gpu

**Comment by AlbertoMQ** [comment]
Ah yes, its the title extractor taking up all the time. When I take it out its almost instantaneous even with the chunk size. I am using a Titan X gpu

**Comment by logan-markewich** [comment]
Ideally, if you want the most speed with local models, run your model in a server (tgi, vllm, etc), then you are able to utilize async properly, which should result in a decent speedup

The title extractor tries to run things concurrently under the hood, but when running a model in the same process, everything is compute bound and therefore sequential
