### ISSUE TITLE
[Feature Request]: Hybrid Search with DatabricksVectorSearch()

### ISSUE THREAD

**Issue by jacob-hein** [run-llama/llama_index#15738]
### Feature Description

Databricks has released into GA its [hybrid search functionality](https://www.databricks.com/blog/announcing-hybrid-search-general-availability-mosaic-ai-vector-search) and if this LlamaIndex [vector stores table](https://docs.llamaindex.ai/en/stable/module_guides/storing/vector_stores/#vector-store-options-feature-support) is still up to date, it seems the hybrid search compatability with LlamaIndex is still missing.

Hybrid search with my ``databricks.vector_search.index.VectorSearchIndex`` index from their latest release works:

![image](https://github.com/user-attachments/assets/61b852b5-55b3-4760-a7df-bd2f8474954c)

But searching documents with my ``llama_index.core.indices.vector_store.base.VectorStoreIndex`` index does not seem to be hybrid searching to retrieve the most relevant documents:

![image](https://github.com/user-attachments/assets/2f35ddaf-cf5e-4044-9ae3-e10c9d005172)

Where 
```python 
delta_sync_index_columns = [
    "doc_id", 
    "id",
    "text",
    "page_label",
    "file_name",
    "file_path",
    "file_type",
    "file_size",
    "creation_date",
    "last_modified_date",
    "__db_text_vector"
]

databricks_vector_store = DatabricksVectorSearch(
    index=dbx_idx,
    text_column="text",
    columns=delta_sync_index_columns,
) 
index = VectorStoreIndex.from_vector_store(databricks_vector_store)
```

### Reason

Enable hybrid search with Databricks

### Value of Feature

Better document retrieval

**Comment by jacob-hein** [comment]
This feature request is already implemented in LangChain, the issue has been merged and closed [here](https://github.com/langchain-ai/langchain/pull/23528#pullrequestreview-2169140447). I suppose the implementation in LlamaIndex would have a very strong resemblance.

**Comment by jacob-hein** [comment]
This feature request is already implemented in LangChain, the issue has been merged and closed https://github.com/langchain-ai/langchain/pull/23528#pullrequestreview-2169140447. I suppose the implementation in LlamaIndex would have a very strong resemblance.

**Comment by hershelm** [comment]
sorry for the delay, but this feature is still critical to our company. any chance to open it back up?

**Comment by bubl-ai** [comment]
@jacob-hein In your original message you show proof that `llama_index.core.indices.vector_store.base.VectorStoreIndex`  does not seem to be hybrid searching to retrieve the most relevant documents. Based on your image I didn't understand how you got to that conclusion. Can you explain that to me?

Really interested in this functionality, big fan of llamaindex and would love to test this.

**Comment by rmanansa** [comment]
+1 to hershelm. we also need this feature in our org.
