### ISSUE TITLE
[Feature Request]: llama parse in open web ui

### ISSUE THREAD

**Issue by cee-aman** [run-llama/llama_index#15731]
### Feature Description

how can i integrate lamma parse in open web ui to use it locally

**Comment by logan-markewich** [comment]
You can make the API calls directly if you want
https://docs.cloud.llamaindex.ai/category/API/parsing

There is no option to run it locally though

**Comment by cee-aman** [comment]
These API calls will be going to llamacloud right? means there is no way to make these calls locally also right?
