### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.evaluation'

### ISSUE THREAD

**Issue by gowrijsuria** [run-llama/llama_index#15774]
### Bug Description

Evaluation module not found in llama index for usage.

### Version

llama_index-0.11.3

### Steps to Reproduce

Import the below line in a file
```from llama_index.evaluation import DatasetGenerator```

### Relevant Logs/Tracbacks

```shell
from llama_index.evaluation import DatasetGenerator
ModuleNotFoundError: No module named 'llama_index.evaluation'
```

**Comment by logan-markewich** [comment]
Did you run `pip install llama-index-evaluation` ?

**Comment by logan-markewich** [comment]
Dosu is right @gowrijsuria -- that import is old and invalid

**Comment by gowrijsuria** [comment]
Yes , I tried `pip install llama-index-evaluation`. However, that did not work. The import statement suggestion by Dosu worked.
Thank you!
