### ISSUE TITLE
[Question]: Workflows example with chat history/memory?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#15803]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is there a Workflows example with chat history/memory?

**Comment by logan-markewich** [comment]
https://docs.llamaindex.ai/en/stable/examples/workflow/react_agent/

https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/
