### ISSUE TITLE
[Bug]: Inconsistent response times from OpenAIAgent

### ISSUE THREAD

**Issue by moreno1123** [run-llama/llama_index#15804]
### Bug Description

Very inconsistent response times with RAG on OpenAIAgent. Sometimes it stops before the function call and sometimes after the function call but before the result.

MODEL=gpt-4o-mini

![image](https://github.com/user-attachments/assets/12d09a86-d79c-4709-b35b-7846061c13f9)

### Version

llama-index==0.11.3 llama-index-agent-openai==0.3.0

### Steps to Reproduce

```python
def get_agent(language:str = ""):
    logger = logging.getLogger("uvicorn")
    logger.info("Get chat agent")
    logger.info("Set Qdrant client")
    client = qdrant_client.QdrantClient(
        qdrant_link,
        api_key=qdrant_api_key,
        https=True,
        port=None
    )

    logger.info("Get Qdrant Vector Store")
    vector_store = QdrantVectorStore(client=client, collection_name=vdb_collection_name)
    index_basic_info = VectorStoreIndex.from_vector_store(
        vector_store=vector_store
    )
    query_engine_basic_info = index_basic_info.as_query_engine(similarity_top_k=4)
    
    query_engine_tools = [
        QueryEngineTool(
            query_engine=query_engine_basic_info,
            metadata=ToolMetadata(
                name="general_information",
                description=(
                    "Provides information about company."
                ),
            ),
        )
    ]

    tools = query_engine_tools

    logger.info("Set Open AI Agent")
    agent = OpenAIAgent.from_tools(
        tools=tools, 
        llm=OpenAI(model=model),
        verbose=True,
        system_prompt=get_system_prompt(language),
        max_function_calls=2
    )

    return agent
```
    
    
```python
response = agent.stream_chat(lastMessage.content, messages)
```

**Comment by logan-markewich** [comment]
Responses depend on
- how busy openai is
- how bug the input is
- how much the llm generates

If i had to guess, the slower responses when the query engine tool gets used (you have a top k of 4, not sure what the chunk size is)

**Comment by logan-markewich** [comment]
Overall I've noticed 4o-mini isn't nearly as fast as 3.5-turbo (yet)

**Comment by moreno1123** [comment]
Chunk size is default 1024. I've tried to lower the top k to 2, but didn't saw some major improvements :/
I thought so too, that it's on openai... They are not really that consistent.
Thanks for answering tho.
