### ISSUE TITLE
[Bug]: ImportError: cannot import name 'ConfigDict' from 'llama_index.core.bridge.pydantic' 

### ISSUE THREAD

**Issue by skyler22wilson** [run-llama/llama_index#15814]
### Bug Description

Trying to implement a Text2SQL using your google collab cookbook and apply it for my own use case. Everything leading up to the workflow call works find but when i try and run the code below it fails and i receive the import error:

from llama_index.core.workflow import (
    Workflow,
    StartEvent,
    step,
    Context,
    Event,
)

class TableRetrieveEvent(Event):
    """Result of running table retrieval."""

    table_context_str: str
    query: str

class TextToSQLEvent(Event):
    """Text-to-SQL event."""

    sql: str
    query: str

class TextToSQLWorkflow(Workflow):
    """Text-to-SQL Workflow that does query-time table retrieval."""

    def __init__(
        self,
        obj_retriever,
        text2sql_prompt,
        sql_retriever,
        llm,
        *args,
        **kwargs
    ) -> None:
        """Init params."""
        super().__init__(*args, **kwargs)
        self.obj_retriever = obj_retriever
        self.text2sql_prompt = text2sql_prompt
        self.sql_retriever = sql_retriever
        self.llm = llm
        self.parse_response_to_sql = parse_response_to_sql

    @step
    def retrieve_tables(
        self, ctx: Context, ev: StartEvent
    ) -> TableRetrieveEvent:
        """Retrieve tables."""
        table_schema_objs = self.obj_retriever.retrieve(ev.query)
        table_context_str = get_table_context_and_rows_str(
            ev.query, table_schema_objs, verbose=self._verbose
        )
        return TableRetrieveEvent(
            table_context_str=table_context_str, query=ev.query
        )

    @step
    def generate_sql(
        self, ctx: Context, ev: TableRetrieveEvent
    ) -> TextToSQLEvent:
        """Generate SQL statement."""
        fmt_messages = self.text2sql_prompt.format_messages(
            query_str=ev.query, schema=ev.table_context_str
        )
        chat_response = self.llm.chat(fmt_messages)
        sql = parse_response_to_sql(chat_response)
        return TextToSQLEvent(sql=sql, query=ev.query)
        
        

### Version

0.11.4

### Steps to Reproduce

from llama_index.core.workflow import (
    Workflow,
    StartEvent,
    step,
    Context,
    Event,
)

### Relevant Logs/Tracbacks

```shell
ImportError                               Traceback (most recent call last)
Cell In[55], line 1
----> 1 from llama_index.core.workflow import (
      2     Workflow,
      3     StartEvent,
      4     step,
      5     Context,
      6     Event,
      7 )
      9 class TableRetrieveEvent(Event):
     10     """Result of running table retrieval."""

File ~/miniconda3/envs/copilot/lib/python3.12/site-packages/llama_index/core/workflow/__init__.py:1
----> 1 from llama_index.core.workflow.context import Context
      2 from llama_index.core.workflow.decorators import step
      3 from llama_index.core.workflow.drawing import (
      4     draw_all_possible_flows,
      5     draw_most_recent_execution,
      6 )

File ~/miniconda3/envs/copilot/lib/python3.12/site-packages/llama_index/core/workflow/context.py:6
      3 from collections import defaultdict
      4 from typing import Dict, Any, Optional, List, Type, TYPE_CHECKING, Set, Tuple
----> 6 from .decorators import StepConfig
...
---> 20 from llama_index.core.bridge.pydantic import BaseModel, ConfigDict
     22 from .events import Event, EventType
     23 from .errors import WorkflowValidationError
```

**Comment by skyler22wilson** [comment]
I would like to preface that this is my first bug submission to an open source project like this so if i failed to follow the correct rules/protocol I apologize

**Comment by logan-markewich** [comment]
@skyler22wilson seems like your venv doesn't have pydantic v2 installed? try `pip install -U pydantic` (although be aware some other component you have installed might be relying on pydantic v1?)

I would recommend a fresh venv if the above doesn't fix it

**Comment by skyler22wilson** [comment]
Running pip install -U pydantic worked thank you so much @logan-markewich
