### ISSUE TITLE
[Question]: Correct way to store and load a property graph locally

### ISSUE THREAD

**Issue by abrudaglio** [run-llama/llama_index#15822]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to create a minimal code to obtain the following: read a document, create a property graph index from it using only SimpleGraphStore and no external stores, dump the result to the disk, load it again and being able to use the graph index for any retrieve/query purpose.

My code:

```
llm = ....
vector_store = ....
embed_model = ....
kg_extractor = ....
if os.path.exists('./graph'):
  index = PropertyGraphIndex.from_existing(
            property_graph_store=SimplePropertyGraphStore.from_persist_path('./graph'),
            vector_store=vector_store,
            embed_model=embed_model,
            llm=llm,
            kg_extractors=[kg_extractor]
        )
else:
  index = PropertyGraphIndex.from_documents(
            documents,
            llm=llm,
            embed_model=embed_model, 
            kg_extractors=[kg_extractor],
            vector_store=vector_store,
            show_progress=True
            )
  index.property_graph_store.persist('./graph')
    
#do retrieve or query or whatever

```

What I expect is to have "index" behaving exactly the same way, both if it was just created in the "else" branch and if it was just loaded from disk in the "if" branch.

What I see is that the just created index is working and I can use it to put queries for example. When I try to load the the index from disk, instead, I receive an error: "ValueError: Could not infer node type for data: ..." followed by the raw json content of the graph.

From here I realised that       index.property_graph_store.persist('./graph') is actually using pydantic "model_dump_json" on the "graph" attribute of the property_graph_store. Doing this the nodes here contained are not properly dumped, in particular the ChunkNodes are losing the "text" attribute and the EntityNodes are losing the "name" attribute. When reloaded from disk the parser "SimplePropertyGraphStore.from_dict" is complaining of the missing fields.
Relevant libraries installed in my Venv are:

llama-cloud                              0.0.15      
llama-index                              0.11.1      
llama-index-agent-openai                 0.3.0       
llama-index-cli                          0.3.0       
llama-index-core                         0.11.4      
llama-index-embeddings-openai            0.2.4       
llama-index-graph-stores-neo4j           0.3.1       
llama-index-indices-managed-llama-cloud  0.3.0       
llama-index-legacy                       0.9.48.post3
llama-index-llms-openai                  0.2.1       
llama-index-multi-modal-llms-openai      0.2.0       
llama-index-program-openai               0.2.0       
llama-index-question-gen-openai          0.2.0       
llama-index-readers-file                 0.2.0       
llama-index-readers-llama-parse          0.3.0       
llama-index-vector-stores-chroma         0.2.0       
llama-parse                              0.5.1       
pydantic                                 2.8.2       
pydantic_core                            2.20.1      

My question is: what am I doing wrong?

**Comment by abrudaglio** [comment]
Hello @dosu

tried to reproduce your suggestion.

Code:
```
import os
from llama_index.core.graph_stores.simple_labelled import SimplePropertyGraphStore
from llama_index.core.graph_stores.types import EntityNode, Relation

persist_path = "./graph.json"
if not os.path.exists(persist_path):    

    # Create an instance of SimplePropertyGraphStore
    graph_store = SimplePropertyGraphStore()

    # Add nodes and relations to the graph_store as needed
    e1 = EntityNode(name="e1")
    e2 = EntityNode(name="e2")
    r = Relation(label="r", source_id=e1.id, target_id=e2.id)
    graph_store.upsert_nodes([e1, e2])
    graph_store.upsert_relations([r])

    # Persist the graph to a file
    graph_store.persist(persist_path)

else:
    graph_store = SimplePropertyGraphStore.from_persist_path(persist_path)
```

With no "./graph.json" it runs. When executed again with the file "./graph.json" written by previous execution it raises the same error:
```
Traceback (most recent call last):
  File "****/dosu.py", line 22, in <module>
    graph_store = SimplePropertyGraphStore.from_persist_path(persist_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "****/.venv/lib/python3.11/site-packages/llama_index/core/graph_stores/simple_labelled.py", line 184, in from_persist_path
    return cls.from_dict(data)
           ^^^^^^^^^^^^^^^^^^^
  File "****/.venv/lib/python3.11/site-packages/llama_index/core/graph_stores/simple_labelled.py", line 212, in from_dict
    raise ValueError(f"Could not infer node type for data: {node_dict!s}")
ValueError: Could not infer node type for data: {'label': 'entity', 'embedding': None, 'properties': {}}
```

**Comment by abrudaglio** [comment]
Last suggestion didn't work. The problem of missing fields is still there given the fact that "custom_serialize" function still relies on pydantic model_dump.

I changed it a little having it working, this is my code:
```
import os
import json
from llama_index.core.graph_stores.simple_labelled import SimplePropertyGraphStore
from llama_index.core.graph_stores.types import EntityNode, Relation, ChunkNode

persist_path = "./graph.json"


# Custom serialization function
def custom_serialize(graph_store, path):
    data = graph_store.graph.model_dump_json(serialize_as_any=True)
    with open(path, "w") as f:
        f.write(data)

# Custom deserialization function
def custom_deserialize(path):
    with open(path, "r") as f:
        data = json.load(f)
    return SimplePropertyGraphStore.from_dict(data)

if not os.path.exists(persist_path):    

    # Create an instance of SimplePropertyGraphStore
    graph_store = SimplePropertyGraphStore()

    # Add nodes and relations to the graph_store as needed
    e1 = EntityNode(name="e1")
    e2 = EntityNode(name="e2")
    r = Relation(label="r", source_id=e1.id, target_id=e2.id)
    graph_store.upsert_nodes([e1, e2])
    graph_store.upsert_relations([r])

    # # Persist the graph to a file
    custom_serialize(graph_store, persist_path)

else:
    graph_store = custom_deserialize(persist_path)

print(graph_store.get())
```

With or without the file the result is the same. 
serialize_as_any pedantic flag is able to force pedantic to use duck typing in serialisation so preserving all the fields from ChunkNode and EntityNode.
I know this could lead to a slower serialisation, but it works.

I hope a human from the team will read this and confirm if my solution is ok or is there something better.

**Comment by logan-markewich** [comment]
Yea the pydantic v2 migration is seems stopped the nodes from saving properly 🤔 Should be an easy fix
