### ISSUE TITLE
[Question]: How to use Vertex AI Llama 3 endpoint on GCP using Llamaindex?

### ISSUE THREAD

**Issue by abhirooptalasila** [run-llama/llama_index#15825]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm following [this](https://docs.llamaindex.ai/en/stable/examples/llm/vertex/) page to integrate a Llama 3 endpoint into my existing workflow using chat engines. 
I've added my service account JSON credentials, and while trying to instantiate a Vertex instance, I can see that the only model options are `chat-bison, chat-bison-32k, chat-bison@001, ... etc.`.
Using the default `text-bison` model name, I can create an instance, and the completion API works, too. 

But that shouldn't work. I don't have a PaLM 2 instance deployed. Is there any other logic making it default to an available LLM?

**Comment by abhirooptalasila** [comment]
@dosu I got that, but I don't have any OpenAI keys in my env.
```
llm = Vertex(model="text-bison", temperature=0, additional_kwargs={}, project=credentials.project_id, credentials=credentials)
llm.complete("Hello this is a sample text").text
```

I still get a completed output when I try out the above code using the GCP JSON credentials. 
Please check the `llama_index/llms/vertex/base.py` file for class implementation details.

**Comment by abhirooptalasila** [comment]
Then how do I use a Llama 3 model instead?

**Comment by abhirooptalasila** [comment]
@dosu "llama-3" is not an available option in the Vertex class.

**Comment by abhirooptalasila** [comment]
@logan-markewich Any idea how I can find out which model it is defaulting to? I don't have any other models deployed on GCP. I've compared outputs from local and online GCP, both are different.

**Comment by logan-markewich** [comment]
The source code is here:
https://github.com/run-llama/llama_index/blob/6645910050125e9485c927f17fbdcccafe64b4ac/llama-index-integrations/llms/llama-index-llms-vertex/llama_index/llms/vertex/base.py#L98

**Comment by abhirooptalasila** [comment]
I did go through that but as you must've noticed, the Llama models are not included in the models list. 
What can I do now?
