### ISSUE TITLE
[Question]: how to use router query engine or retriver with open source llm

### ISSUE THREAD

**Issue by JINO-ROHIT** [run-llama/llama_index#15821]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When i run the examples for router query engine or retriever, it asks for openai llm, how can i use with open source llms

**Comment by JINO-ROHIT** [comment]
No, im trying to run this code from the docs https://docs.llamaindex.ai/en/stable/examples/query_engine/RouterQueryEngine/

**Comment by JINO-ROHIT** [comment]
ValueError: model name “” doesnot support function calling API

**Comment by JINO-ROHIT** [comment]
ValueError: model name “llama-7b-instruct” doesnot support function calling API, this is a different error

**Comment by JINO-ROHIT** [comment]
dont all models support function calling?

**Comment by logan-markewich** [comment]
@JINO-ROHIT all models do NOT support function calling. It depends on the LLM class you are using supporting tool calls directly in their API

In this case, don't using the pydantic selector, use the LLM selector, which doesn't use tool calling and instead directly prompts an LLM

```python
from llama_index.core.selectors import LLMSingleSelector, LLMMultiSelector


query_engine = RouterQueryEngine(
    selector= LLMSingleSelector.from_defaults(llm=llm),
    query_engine_tools=[
        list_tool,
        vector_tool,
    ],
)
```
