### ISSUE TITLE
[Bug]: QdrantVectorStore 404 Not Found 

### ISSUE THREAD

**Issue by mirallm** [run-llama/llama_index#15830]
### Bug Description

The code coming from llamaindex documentation is giving an error 404 Not Found. 

`client = qdrant_client.QdrantClient(
    # you can use :memory: mode for fast and light-weight experiments,
    # it does not require to have Qdrant deployed anywhere
    # but requires qdrant-client >= 1.1.1
    # location=":memory:"
    # otherwise set Qdrant instance address with:
    # url="http://:"
    # otherwise set Qdrant instance with host and port:
    host="localhost",
    port=6333
    # set API KEY for Qdrant Cloud
    # api_key="",
)

vector_store = QdrantVectorStore(client=client, collection_name="paul_graham")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
)

query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)`

I have 
**ERROR:qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 404 (Not Found)**

Although

curl http://localhost:6333/collections works very well 
{"result":{"collections":[{"name":"my_collection"},{"name":"paul_graham"}]},"status":"ok","time":6.466e-6}

### Version

latest

### Steps to Reproduce

you need to take the code from here https://docs.llamaindex.ai/en/stable/examples/vector_stores/QdrantIndexDemo/

**Comment by mirallm** [comment]
That's the weird thing, when i call collection_exists, it shows 404 Not found. but when i cal http://localhost:6333 i can see well my two collections. The name are the same.

**Comment by mirallm** [comment]
with memory client, it works but not with localhost:6333 although it does contain the collections

**Comment by mirallm** [comment]
@dosu can you send me the code for doing RAG with qdrant please

**Comment by mirallm** [comment]
# Initialize Qdrant client and vector store
client = qdrant_client.QdrantClient(location=":memory:")

I dont want with memory , i want with localhost:6333

@dosu

**Comment by logan-markewich** [comment]
@mirallm maybe your deployed version of the qdrant server is not the latest? I would try ensuring you have the latest version of the qdrant docker image, and the latest version of qdrant client. 

The code works for me 🤔

**Comment by mirallm** [comment]
@logan-markewich  you are totally right. it worked now. i had an older version of qdrant docker image. thanks a lot.
