### ISSUE TITLE
[Question]: Input should be an instance of AgentRunner [type=is_instance_of, input_value=<multi_agent_app.agent_se...bject at 0x7f2abaa18fa0>, input_type=ReActAgent]

### ISSUE THREAD

**Issue by Rohith-Scalers** [run-llama/llama_index#15841]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i am trying use workflow react agent class as a AgentService . 
```
 react_agent1 = ReActAgent(llm=OpenAI(model="gpt-4o-mini"), tools=tools, timeout=120, verbose=True)
 agent_server = AgentService(
    agent=react_agent1,...)
```
how can i change reactagent to  a Agentrunner instance

**Comment by logan-markewich** [comment]
AgentService is llama-agents right?

Don't even worry about this actually 😅 Huge refactor coming soon to llama-agents to work solely with workflows
https://github.com/run-llama/llama-agents/tree/v0.1.0

**Comment by Rohith-Scalers** [comment]
yes it is llama agents . ```Don't even worry about this actually 😅 Huge refactor coming soon to llama-agents to work solely with workflows``` 🥳🎉
