### ISSUE TITLE
[Documentation]: CypherTemplateRetriever Example Runtime Error

### ISSUE THREAD

**Issue by kinano** [run-llama/llama_index#15885]
### Documentation Issue Description

I followed the instructions/code sample for [CypherTemplateRetriever](https://docs.llamaindex.ai/en/latest/module_guides/indexing/lpg_index_guide/#cyphertemplateretriever) and ran into a runtime error every time I tried to query the retriever: `type object 'TemplateParams' has no attribute 'model_json_schema'`.

I was able to resolve the error by modifying the import statement from:
```
# NOTE: current v1 is needed
from pydantic.v1 import BaseModel, Field
```
to:
```
from pydantic import BaseModel, Field
```
I wonder if we should correct the documentation if pydantic.v1 is no longer needed/useable.  

### Documentation Link

https://docs.llamaindex.ai/en/latest/module_guides/indexing/lpg_index_guide/#cyphertemplateretriever

**Comment by logan-markewich** [comment]
yea just import `from pydantic import BaseModel, Field`

Will update the docs
