### ISSUE TITLE
[Bug]: ReActAgent.astream_chat() throws AssertionError after updating to the lastest version

### ISSUE THREAD

**Issue by dzmitrysyrtsou** [run-llama/llama_index#15883]
### Bug Description

After updating to the latest version, ReActAgent.astream_chat() throws AssertionError: assert isinstance(chat_response, StreamingAgentChatResponse).
This seems to be related to a new assertion added to **llama-index-core/llama_index/core/agent/runner/base.py**, namely:

![image](https://github.com/user-attachments/assets/676770f7-b866-4b32-9880-814c1945aee8)

Isn't the logic now conflicting?

![image](https://github.com/user-attachments/assets/a56422d6-a1d4-4e42-a340-b37a3c47ab01)

Looks like a bug....

### Version

latest

### Steps to Reproduce

Create a ReActAgent and call astream_chat() method.

**Comment by dzmitrysyrtsou** [comment]
Hey, I'm pretty sure we're using the Agent correctly. Here is a chunk of our code:

```
 async def get_assistant_response(self, request_text: str):
        agent = self._create_agent()
        chat_history = self._get_chat_history()
        llm_response = (
            await agent.astream_chat(
                message=request_text, chat_history=chat_history
            )
        )
        response_stream = llm_response.async_response_gen()

```
We are deeply convinced that the problem is not with the way the agent is used, but rather with the implementation of astream_chat() method.

**Comment by dzmitrysyrtsou** [comment]
We're not using a custom implementation of _achat() method. We're using a built-in implementation from Llama.

**Comment by logan-markewich** [comment]
Its definitely a bug lol
