### ISSUE TITLE
[Bug]: Pydantic models numeric validation is not working

### ISSUE THREAD

**Issue by Nitro963** [run-llama/llama_index#15959]
### Bug Description

Pydantic models have incorrect definition for numeric fields validation. For instance, `temperature` in `OpenAI` llm is defined as 

```python
    temperature: float = Field(
        default=DEFAULT_TEMPERATURE,
        description="The temperature to use during generation.",
        gte=0.0,
        lte=1.0,
    )
```

where it should be

```python
    temperature: float = Field(
        default=DEFAULT_TEMPERATURE,
        description="The temperature to use during generation.",
        ge=0.0,
        le=1.0,
    )
```

Notice the change of `gte`, `lte` to `ge`, `le` respectively. See [Pydantic Docs](https://docs.pydantic.dev/latest/concepts/fields/#numeric-constraints).

### Version

0.11.7

### Steps to Reproduce

```python
import warnings
warnings.simplefilter('always')

from llama_index.llms.openai import OpenAI

llm = OpenAI(max_retries=-5)
```

The previous snippet should raise `ValidtionError` due to invalid value `max_retries < 0`

### Relevant Logs/Tracbacks

```shell
/usr/local/lib/python3.11/dist-packages/pydantic/fields.py:826: PydanticDeprecatedSince20: Using extra keyword arguments on `Field` is deprecated and will be removed. Use `json_schema_extra` instead. (Extra keys: 'gte'). Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
```

**Comment by logan-markewich** [comment]
Feel free to make a PR, pretty low hanging fruit

**Comment by zzhsaga** [comment]
Hi. I encountered the same problem and submitted a PR that fixes the Pydantic numeric validation in `openai/base.py` by changing `gte` to `ge` and `lte` to `le`.

I've also noticed similar issues in other areas (such as the Gemini class), and I plan to address those in a future PR once this one is merged.
