### ISSUE TITLE
[Question]: Problem with DynamoDB Index Store - Maximum Allowed Size

### ISSUE THREAD

**Issue by dgallitelli** [run-llama/llama_index#15963]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey there! I'm trying to use Amazon DynamoDB for both Index Store and DocStore. However, when trying to load documents, I get the following error:

`ClientError: An error occurred (ValidationException) when calling the PutItem operation: Item size has exceeded the maximum allowed size`

Llama Index does not provide any further indication at which point of the `VectorStoreIndex.from_documents()` call this was generated, therefore I have no idea how much data is already in the table. 

1. Is there a way to figure out where this got stuck without having to wait again 1h+ for the embedding to be created again? 
2. Can I reuse the existing embedding, and just recreate the IndexStore/DocStore in DDB?
3. Has anyone got into a similar maximum item size issue before, and what was the solution?

Thanks!

**Comment by dgallitelli** [comment]
@dosu which chunk size should I set to avoid exceeding DynamoDB's maximum item size?

**Comment by dgallitelli** [comment]
How do I figure out whether it's a problem of the size of the document or a size of the metadata without having to reload the full dataset into the vector store index?

**Comment by logan-markewich** [comment]
I'm sure the full traceback would probably indicate if this issue was the index store or the doc store?

**Comment by logan-markewich** [comment]
The way the index store works, I can imagine a large amount of nodes creating a very large key-val pair

Its organized by index id -> list of node ids in that index

Imo you really don't need the index store? Especially if you use a vector store integration that supports storing text

**Comment by dgallitelli** [comment]
> I'm sure the full traceback would probably indicate if this issue was the index store or the doc store?

Is there a way to do this? I'm not sure what API to use after `from_documents()` to check the full traceback. Maybe @dosu knows?

**Comment by dgallitelli** [comment]
> Imo you really don't need the index store? Especially if you use a vector store integration that supports storing text

I'm using FAISS, so unfortunately that's not the case :\

**Comment by dgallitelli** [comment]
In the end:

1. I could figure that the IndexStore was causing issues, not the DocStore
2. I decided to move the IndexStore to the local directory, as it's not huge and should be easily loaded in memory by an AWS Lambda
3. I ended up also moving the DocStore out of DynamoDB. Not sure why, but it's just easier this way.

Closing for now, even though it's not exactly solved.
