### ISSUE TITLE
[Question]: 1] ImportError: cannot import name 'session' from 'llama_index.core.workflow' 

### ISSUE THREAD

**Issue by Tisha-linkenite** [run-llama/llama_index#15968]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

cannot import session from the standard 'llama_index.core.workflow' 

Error message : 1] ImportError: cannot import name 'session' from 'llama_index.core.workflow' (/venv/lib/python3.11/site-packages/llama_index/core/workflow/__init__.py)

**Comment by logan-markewich** [comment]
@Tisha-linkenite where did you see this import? This concept was removed, everything is bundled into the `Context` object now
