### ISSUE TITLE
[Bug]: RetrieverQueryEngine.from_args does not support callback_managers passed in as kwargs

### ISSUE THREAD

**Issue by Tshimanga** [run-llama/llama_index#15989]
### Bug Description

RetrieverQueryEngine.from_args does not support callback_managers passed in as kwargs

`from_args` is hardcoded to expect callback_manager provided through `Settings`

### Version

0.11.8

### Steps to Reproduce

https://github.com/run-llama/llama_index/blob/1363aade493d272b55f2bacd3ba08cb1b2586775/llama-index-core/llama_index/core/query_engine/retriever_query_engine.py#L111

**Comment by logan-markewich** [comment]
feel free to make a PR, easy win

**Comment by Tshimanga** [comment]
@logan-markewich here you go! https://github.com/run-llama/llama_index/pull/15990
