### ISSUE TITLE
[Question]:AttributeError: 'AzureOpenAI' object has no attribute 'generate'

### ISSUE THREAD

**Issue by adityamity** [run-llama/llama_index#16041]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to generate response from AzureOpenAI gpt4 model by passing my prompt to it, but i am getting below error 👍 
`AttributeError: 'AzureOpenAI' object has no attribute 'generate'`

below is my code:

```
llm = AzureOpenAI(
                api_key=self.az_openai_key,
                azure_endpoint=self.az_openai_endpoint,
                model=model_specs["model_name"],
                deployment_name=model_specs["deply_name"],
                api_version=model_specs["api_version"],
                temperature=0,
            )

response = llm.generate(prompt = 'my_prompt')

AttributeError: 'AzureOpenAI' object has no attribute 'generate'
```

**Comment by logan-markewich** [comment]
@adityamity indeed, it does not have that method. I don't think any of our docs show a generate method.

Dosu is right, you can use `complete()`. Or, you can pass in a list of `ChatMessage` objects and use `.chat()`

```
from llama_index.core.llms import ChatMessage

llm.chat([ChatMessage(role="user", content="hello")])
```
