### ISSUE TITLE
[Bug]: Workflows "hasattr" not functioning as intended.

### ISSUE THREAD

**Issue by gsikes0501** [run-llama/llama_index#16063]
### Bug Description

I was working through the Workflows Cookbook "Maintaining state between events" section. When I run the code on the website the check for the data attribute is not passed. 

The data variable is set within the context variable in the setup step. This data is not recognized as an attribute when checked for within the query step. 

I cannot get the script to recognize the attribute and output the part 3 from the example. 

part 1
---
part 2
---
Running step query
Step query produced event StopEvent
Running step setup
Step setup produced event StopEvent
Got the data Yes you can

### Version

0.11.6

### Steps to Reproduce

``` 
class WaitExampleFlow(Workflow):
    @step
    async def setup(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "data"):
            await ctx.set("data", ev.data)

        return StopEvent(result=None)

    @step
    async def query(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "query"):
            # do we have any data?
            if hasattr(self, "data"):
                data = await ctx.get("data")
                return StopEvent(result=f"Got the data {data}")
            else:
                # there's non data yet
                return None
        else:
            # this isn't a query
            return None
```
            
 ## Running Code 
```
w = WaitExampleFlow(verbose=True)
result = await w.run(query="Can I kick it?")
if result is None:
    print("No you can't")
print("---")
result = await w.run(data="Yes you can")
print("---")

result = await w.run(query="Can I kick it?")
print(result)
```

## Output
Running step query
Step query produced no event
Running step setup
Step setup produced event StopEvent
No you can't
---
Running step query
Step query produced no event
Running step setup
Step setup produced event StopEvent
---
Running step query
Step query produced no event
Running step setup
Step setup produced event StopEvent
None

**Comment by gsikes0501** [comment]
The suggested code errors out without ever entering the second iteration. It does not find the data attribute and returns ValueError

```
result = await w.run(data="Yes you can") 
```

output:
Running step query
Running step setup
Step setup produced event StopEvent

ValueError: Key 'data' not found in Context

**Comment by logan-markewich** [comment]
Yea this should be updated, seems like a bug?

Here's what it should look like

```python
class WaitExampleFlow(Workflow):
    @step
    async def setup(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "data"):
            self.data = data  # <- notice that this gets set on self

        return StopEvent(result=None)

    @step
    async def query(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "query"):
            # do we have any data?
            if hasattr(self, "data"):
                data = self.data
                return StopEvent(result=f"Got the data {data}")
            else:
                # there's non data yet
                return None
        else:
            # this isn't a query
            return None
```

In the latest version `v0.11.10` we also made this possible to do without using self

Here's how I might do this in the latest release, reusing the existing context between runs

```python
class WaitExampleFlow(Workflow):
    @step
    async def setup(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "data"):
            await ctx.set("data", data)

        return StopEvent(result=None)

    @step
    async def query(self, ctx: Context, ev: StartEvent) -> StopEvent:
        if hasattr(ev, "query"):
            # do we have any data?
            data = await ctx.get("data", default=None)
            if data is not None:
                return StopEvent(result=f"Got the data {data}")
            else:
                # there's non data yet
                return None
        else:
            # this isn't a query
            return None
            
            
w = WaitExampleFlow(verbose=True)
handler = w.run(query="Can I kick it?")
result = await handler
if result is None:
    print("No you can't")
print("---")
handler = w.run(ctx=handler.ctx, data="Yes you can")
_ = await handler
print("---")

result = await w.run(ctx=handler.ctx, query="Can I kick it?")
print(result)
```

**Comment by gsikes0501** [comment]
@dosu AttributeError: 'Context' object has no attribute 'has'

**Comment by gsikes0501** [comment]
@logan-markewich  I tried the first version. When I run the line that passes data I get: NameError: name 'data' is not defined

I upgraded my llama-index version to v0.11.10 and tried the second suggestion but receive the following: ValueError: Key 'data' not found in Context

**Comment by sharathe100111** [comment]
This issue should be fixed once my pull-request is completed by maintainers. [Fixed issue with default value set as None for get method](https://github.com/run-llama/llama_index/pull/16756/commits/02b9b133b5c80a17d0385814a1d49810be0217d1)
