### ISSUE TITLE
[Bug]: Index persist takes 4x time to save to storage than index generation

### ISSUE THREAD

**Issue by hafezmg48** [run-llama/llama_index#16088]
### Bug Description

Hi and thank you for your great contribution.

I am trying to index a large dataset of about 30GB of documents. But first to do a test I indexed a relatively small part of dataset (10MB) of .md documents with about 5000 chunks using the huggingface bge-base-en-v1.5 embedding model. The process of generating these vector indices takes about 90 secs which is reasonable. But when trying to store this data on HD using persist() method, it takes about 380 secs (4x the time it took to generate the indices) to store the data into a .json file. 

Given the fact that the generated vectorindex take only 120MB on storage this is a huge amount of time! This just makes the whole idea of storing the results impractical because it would take much less to generate these indices again than the time it takes to store or load them. Is it possible to just store the indices in raw format to not take this much time generating the json files?

Thanks again

### Version

0.11.9

### Steps to Reproduce

```
import os
os.environ['HF_HOME'] = '~/.cache/huggingface/'

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, Settings
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.ollama import Ollama
from llama_index.core import StorageContext, load_index_from_storage


# Define the path to your dataset directory
dataset_directory = '~/datasets/mydataset'
subdirectories =[]
try:
    entries = os.listdir(dataset_directory)
    subdirectories = [entry for entry in entries if os.path.isdir(os.path.join(dataset_directory, entry))]
except FileNotFoundError:
    print(f"The directory {dataset_directory} does not exist.")
except PermissionError:
    print(f"Permission denied to access {dataset_directory}.")

# load the dataset from the subdirectories
print("Loading dataset documents:")
dataset=[]
for n, subdir in enumerate(subdirectories):
    dataset.append(SimpleDirectoryReader(os.path.join(dataset_directory, subdir) , required_exts=[".md"], recursive=True).load_data())
    print(f"{subdir} loaded with {len(dataset[n])} pages.")


# load embedding model
Settings.embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5", device="cuda")

# Create the directory for vectorindex datasets
vec_directory='~/VectorIndexDatasets/mydataset/'
try:
    os.makedirs(vec_directory, exist_ok=True)  # Creates the directory and any necessary parent directories
    print(f"Directory created at: {vec_directory}")
except Exception as e:
    print(f"Error creating directory: {e}")

# generate vectorindex (this takes only 90 secs)
index_list =[]
for dataset_part, subdir in zip(dataset, subdirectories):
    index_list.append(VectorStoreIndex.from_documents(dataset_part))
    print(f"{subdir} vector index generated with {len(index_list[-1].docstore.docs)} nodes.")

# store the vector indices to storage (this takes a long time of about 380 secs)
for n, (dataset_part, subdir) in enumerate(zip(dataset, subdirectories)):
    index_list[n].storage_context.persist(os.path.join(vec_directory,subdir))
    print(f"{subdir} vector index saved to storage.")

```

**Comment by logan-markewich** [comment]
@hafezmg48 for this much data, you should be using a real vector store integration -- qdrant, chroma, etc.

**Comment by hafezmg48** [comment]
@logan-markewich Thank you for this. I will look up those integrations here then: [vector store integrations](https://docs.llamaindex.ai/en/stable/community/integrations/vector_stores/ )

I believe that this was not a bug then. Sorry, I am new to this. I will close this post.

**Comment by logan-markewich** [comment]
No worries! We should have docs on how use every vector store integration -- that should help quite a bit
