### ISSUE TITLE
[Bug]: AttributeError: __pydantic_private__

### ISSUE THREAD

**Issue by yithuang123** [run-llama/llama_index#16094]
### Bug Description

Got an AttributeError: __pydantic_private__ when i use customized Embedding Model. Here is the code:

````
from typing import Optional, List, Mapping, Any
from llama_index.core.base.embeddings.base import (
    BaseEmbedding,
    Embedding,
)
from llama_index.legacy.bridge.pydantic import PrivateAttr
import requests
import numpy as np
_EMBEDDING_URL = "https://XXX"

class MLServerEmbedding(BaseEmbedding):
    _model: str = PrivateAttr()
    _url: str = PrivateAttr()
    def __init__(
        self,
        model_name: str,
        **kwargs: Any,
    ) -> None:
        self._model = model_name
        self._url = _EMBEDDING_URL.format(embedding_model=model_name)
        super().__init__(**kwargs)
    @classmethod
    def class_name(cls) -> str:
        return "CustomEmbeddings"
    @staticmethod
    def _wrap_payload(text_list):
        return {
            "inputs": [
                {
                    "name": "input",
                    "shape": [len(text_list)],
                    "datatype": "str",
                    "data": text_list
                }
            ]
        }
    def _get_embedding(self, text_list: List[str]) -> List[List[float]]:
        return self._parse_response(requests.post(url=self._url,
                                                  json=self._wrap_payload(text_list),
                                                  headers={"Content-Type": "application/json"},
                                                  params={}))
    def _get_query_embedding(self, query: str) -> Embedding:
        vector = self._get_embedding([query])
        return vector
    async def _aget_query_embedding(self, query: str) -> Embedding:
        pass
    def _get_text_embedding(self, text: str) -> Embedding:
        vector = self._get_embedding([text])
        return vector
    def _get_text_embeddings(self, texts: List[str]) -> List[Embedding]:
        vector = self._get_embedding(texts)
        return vector
    
    @staticmethod
    def _parse_response(response):
        if response.status_code != 200:
            raise Exception(response)
        outputs = response.json()["outputs"][0]
        return np.array(outputs["data"]).reshape(outputs["shape"]).tolist()


if __name__ == '__main__':
    embed_model = MLServerEmbedding(model_name="all-minilm-l6-v-0438f")
``


### Version

0.11.8

### Steps to Reproduce

````
from typing import Optional, List, Mapping, Any
from llama_index.core.base.embeddings.base import (
    BaseEmbedding,
    Embedding,
)
from llama_index.legacy.bridge.pydantic import PrivateAttr
import requests
import numpy as np
_EMBEDDING_URL = "https://XXX"

class MLServerEmbedding(BaseEmbedding):
    _model: str = PrivateAttr()
    _url: str = PrivateAttr()
    def __init__(
        self,
        model_name: str,
        **kwargs: Any,
    ) -> None:
        self._model = model_name
        self._url = _EMBEDDING_URL.format(embedding_model=model_name)
        super().__init__(**kwargs)
    @classmethod
    def class_name(cls) -> str:
        return "CustomEmbeddings"
    @staticmethod
    def _wrap_payload(text_list):
        return {
            "inputs": [
                {
                    "name": "input",
                    "shape": [len(text_list)],
                    "datatype": "str",
                    "data": text_list
                }
            ]
        }
    def _get_embedding(self, text_list: List[str]) -> List[List[float]]:
        return self._parse_response(requests.post(url=self._url,
                                                  json=self._wrap_payload(text_list),
                                                  headers={"Content-Type": "application/json"},
                                                  params={}))
    def _get_query_embedding(self, query: str) -> Embedding:
        vector = self._get_embedding([query])
        return vector
    async def _aget_query_embedding(self, query: str) -> Embedding:
        pass
    def _get_text_embedding(self, text: str) -> Embedding:
        vector = self._get_embedding([text])
        return vector
    def _get_text_embeddings(self, texts: List[str]) -> List[Embedding]:
        vector = self._get_embedding(texts)
        return vector
    
    @staticmethod
    def _parse_response(response):
        if response.status_code != 200:
            raise Exception(response)
        outputs = response.json()["outputs"][0]
        return np.array(outputs["data"]).reshape(outputs["shape"]).tolist()

if __name__ == '__main__':
    embed_model = MLServerEmbedding(model_name="all-minilm-l6-v-0438f")
``

**Comment by logan-markewich** [comment]
@yithuang123 in pydantic v2, the super init has to come before accessing self variables

**Comment by yithuang123** [comment]
@logan-markewich Thank you! It works for me.
