### ISSUE TITLE
Difference between `CondenseQuestionChatEngine` and `CondensePlusContextChatEngine`

### ISSUE THREAD

**Issue by RakeshReddyKondeti** [run-llama/llama_index#16098]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

As I understand, the primary difference between the `CondenseQuestionChatEngine` and `CondensePlusContextChatEngine` is that the former uses the `query_engine` to generate a response, while the latter directly generates responses from the retrieved context from the retriever. Apart from this, the general workflow remains the same.

When the `query_engine` is involved, the user can choose the `response_synthesis` module, which is crucial (at least in my case). For example, if I ask a summarization question to `CondensePlusContextChatEngine`, all the text chunks are retrieved and added to the system prompt, which can exceed the context window of the LLM.

Could you please provide a way to handle response synthesis in `CondensePlusContextChatEngine` similar to `CondenseQuestionChatEngine` to avoid exceeding the context window?

Thank you!

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/pull/16017
