### ISSUE TITLE
[Question]: Not able to create PropertyGraphIndex using SemanticSplitterNodeParser

### ISSUE THREAD

**Issue by nilu4u** [run-llama/llama_index#16163]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to create PropertyGraphIndex using smaller chunk size instead of using the whole page. For that I am trying to split the documents into chunks using SemanticSplitterNodeParser but when I put the splitter nodes into PropertyGraphIndex.from_documents, I am getting an error:
AttributeError: 'TextNode' object has no attribute 'get_doc_id'

Here is my code:

reader = SimpleDirectoryReader(input_dir=DOCUMENT_DIR_PATH)
documents = reader.load_data()

splitter = SemanticSplitterNodeParser(
    buffer_size=1, 
    breakpoint_percentile_threshold=95, 
    embed_model=embed_model,
    include_metadata=True,
    include_prev_next_rel=True
    )
nodes = splitter.get_nodes_from_documents(documents)

entities = Literal[
    "APPLICATION",
    "EMPLOYEE",
    "EVENT",
    "LOCATION",
    "OBJECT",
    "ORGANIZATION",
    "PARTNER",
    "PRODUCT",
    "RULE",
    "SCOPE",
]

relations = Literal[
    # "ACQUISITION",
    "APPLIES_TO",
    "COMPETITOR_TO",
    "HAPPENED_AT",
    "HAS_EVENT",
    "HAS_SCOPE",
    "IN_LOCATION",
    # "PARTNERSHIP",
    "PERTAINS_TO",
    "PRODUCES",
    "SUBSIDIARY_OF",
    "SUPPLIER_OF",
    "WORKS_AT",
]

schema_kg_extractor = SchemaLLMPathExtractor(
    llm=llm,
    possible_entities=entities,
    possible_relations=relations,
    kg_validation_schema=validation_schema,
    max_triplets_per_chunk=20,
    num_workers=4,
    # if false, allows for values outside of the schema (useful for using the schema as a suggestion)
    strict=False,
)

index = PropertyGraphIndex.from_documents(
                    nodes,
                    kg_extractors=[schema_kg_extractor],
                    llm=llm,
                    embed_model=embed_model,
                    property_graph_store=graph_store,
                    show_progress=True,
                    use_async=False # defaults to True
                )

**Comment by logan-markewich** [comment]
@nilu4u don't use `from_documents` when passing in nodes

I think you probably meant to do

```
index = PropertyGraphIndex(
  nodes=nodes,
  kg_extractors=[schema_kg_extractor],
  llm=llm,
  embed_model=embed_model,
  property_graph_store=graph_store,
  show_progress=True,
  use_async=False # defaults to True
)
```
