### ISSUE TITLE
[Bug]: It is not possible to create a redis chat store

### ISSUE THREAD

**Issue by calii23** [run-llama/llama_index#16183]
### Bug Description

When trying to instantiate the `RedisChatStore` class there is an pydantic validation error.

When looking into the code, it seems like that the `redis_client` and `aredis_client` fields are set after the pydantic initializer is called. This leads to pydantic raising this exception.

The changes were made here: https://github.com/run-llama/llama_index/commit/df79186317cabd80f75e93bdd35aee6f1edbed7b#diff-5d6e644882e8b450925ea30d2fc7b049a34f3f2b621f3e7b40a150a5903b115dR49-R52

### Version

llama-index==0.11.12 llama-index-storage-chat-store-redis==0.3.0

### Steps to Reproduce

Pretty much just try to instantiate the `RedisChatStore`. Here an example:
```
_chat_store = RedisChatStore(
    redis_client=redis_sync_client,
    aredis_client=redis_async_client,
    ttl=2 * 60 * 60,
)
```

### Relevant Logs/Tracbacks

```shell
_chat_store = RedisChatStore(
                  ^^^^^^^^^^^^^^^
  File "<path>/.venv/lib/python3.11/site-packages/llama_index/storage/chat_store/redis/base.py", line 49, in __init__
    super().__init__(ttl=ttl)
  File "<path>/.venv/lib/python3.11/site-packages/pydantic/main.py", line 212, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 1 validation error for RedisChatStore
redis_client
  Field required [type=missing, input_value={'ttl': 7200}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.9/v/missing
```

**Comment by logan-markewich** [comment]
I published a fix for this in this PR
https://github.com/run-llama/llama_index/pull/16190
