### ISSUE TITLE
[Question]: Complex pdf parsing

### ISSUE THREAD

**Issue by vishnu020** [run-llama/llama_index#16185]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi i have ncert book as my pdf now it conain text,table and images now i want to extract them by mainting data quality .Can you please suggest some solution

**Comment by vishnu020** [comment]
i am not able to import PDFMarkerReader it is giving error no module llama_index.readers.pdf_marker

**Comment by logan-markewich** [comment]
[LlamaParse](https://github.com/run-llama/llama_parse) is a pretty ideal solution. Lots of multi-modal examples with llama-parse here

https://github.com/run-llama/llama_parse/tree/main/examples/multimodal

**Comment by vishnu020** [comment]
I am using llamaparse and i trying to store it but while retrieving the storage i am getting error can you please help me to solve it 

recursive_index.storage_context.persist('file_storage')
from llama_index.core import StorageContext,load_index_from_storage

from llama_index.storage.docstore.simple_docstore import SimpleDocumentStore
from llama_index.storage.vector_store.simple_vector_store import SimpleVectorStore
from llama_index.storage.index_store.simple_index_store import SimpleIndexStore

storage_context = StorageContext.from_defaults(
    docstore=SimpleDocumentStore.from_persist_dir(persist_dir="file_storage"),
    vector_store=SimpleVectorStore.from_persist_dir(
        persist_dir="file_storage"
    ),
    index_store=SimpleIndexStore.from_persist_dir(persist_dir="file_storage"),
)       


the error i am encountring is that 

ModuleNotFoundError: No module named 'llama_index.storage'

**Comment by hquynh-dot** [comment]
If you still use PDFMarkerReader, you need to install package: llama-index-readers-pdf-marker
