### ISSUE TITLE
[Question]: How do I make llamaindex installation slimmer and discard unnecessary stuffs, especially the nvidia CUDA part, where I know I dont have GPU

### ISSUE THREAD

**Issue by Curiosity007** [run-llama/llama_index#16224]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently I am using older version of llamaindex and that have lower version of torch, cuda etc. So, the download speed is very slow. Is there any way, I can simply install very slim package, without these, and be done with it?

**Comment by logan-markewich** [comment]
What packages are you currently installing?
