### ISSUE TITLE
[Bug]: llama-index-core 0.10.68.post1 looks for punkt instead of punkt-tab

### ISSUE THREAD

**Issue by tsdaemon** [run-llama/llama_index#16300]
### Bug Description

Not sure why, but when a package of said version installed, it is still looking for `punkt` which is considered deprecated in NLTK. In llama_index/core/utils.py I observe:
```        
try:
    nltk.data.find("tokenizers/punkt")
except LookupError:
    nltk.download("punkt_tab", download_dir=self._nltk_data_dir)
```
Even though I see that in https://github.com/run-llama/llama_index/pull/15557 `"tokenizers/punkt"` was replaced with `"tokenizers/punkt_tab"` which was released as version `0.10.68.post1`.

### Version

0.10.68.post1

### Steps to Reproduce

```
python -m venv .venv
source .venv/bin/activate
pip install llama_index_core==0.10.68.post1
head -n 100 .venv/lib/python3.11/site-packages/llama_index/core/utils.py
```

**Comment by logan-markewich** [comment]
@tsdaemon Probably just an issue with how that version got published

Try any newer version and it works fine -- I can't go back and edit past versions sadly

**Comment by tsdaemon** [comment]
@logan-markewich I don't think there is any larger versions of `llama-index-core` as of now

**Comment by logan-markewich** [comment]
@tsdaemon we have all the way to v0.11.14 👀

**Comment by logan-markewich** [comment]
some other requirement in your deps may be limiting the version -- v0.11 requires a bump in every `llama-index-*` package

**Comment by tsdaemon** [comment]
oh. well, sorry for the noise then!

**Comment by logan-markewich** [comment]
No worries! let me know if you need a hand with your deps
