### ISSUE TITLE
[Question]: Incorporate history in query engine

### ISSUE THREAD

**Issue by Tejaswgupta** [run-llama/llama_index#16303]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I need to use a custom query engine with history. Only two options are incorporating history manually with query engine or using the custom query engine with chat engine. I couldn't find resources for either of those.

**Comment by Tejaswgupta** [comment]
We're building a RAG chatbot so a retriever is needed but it's missing in your response.

**Comment by logan-markewich** [comment]
@Tejaswgupta use a chat engine -- I prefer the CondensePlusContextChatEngine

```
from llama_index.core.chat_engine import CondensePlusContextChatEngine

chat_engine = CondensePlusContextChatEngine.from_defaults(retriever, llm=llm, ....)
```

**Comment by logan-markewich** [comment]
Hmm, tbh I would just build my own thing from lower-level abstractions if you need maximum flexibility

This is what workflows are made for
https://docs.llamaindex.ai/en/stable/module_guides/workflow/#workflows

Something like a function-calling agent is one example of this, but probably more complicated than what your needs currently are.
https://colab.research.google.com/drive/1wVCkvX7oQu1ZwrMSAyaJ8QyzHyfR0D_j?usp=sharing

But, more than enough in both those links to build out something cool
