### ISSUE TITLE
[Question]: Should MetadataFilters for vector stores support nesting?

### ISSUE THREAD

**Issue by RasmusAntons** [run-llama/llama_index#16310]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I would like to use nested filter logic with the Milvus vector store (e.g. (A and (B or C))). I saw in the MetadataFilters type hints that filters can be of type MetadataFilters, but the Milvus implementation doesn't support that.

I tried to add a quick fix for that in [d2c4c72](https://github.com/RasmusAntons/llama_index/commit/d2c4c72223728e985c44e24d4045a464e3e4f575), I can make a PR but I didn't test if it actually works yet, so I thought I'd ask if this is intended first.

Also, would it be possible to extend the MetadataFilter schema to allow boolean values? That would probably break compatibility with other vector stores, but that's already not guaranteed.

**Comment by logan-markewich** [comment]
Probably makes sense to update milvus to support nested filters

The MetatadatFilters object already has a place for and/or values
