### ISSUE TITLE
[Feature Request]: Install https://github.com/openai/CLIP.git together with llama-index-embeddings-clip

### ISSUE THREAD

**Issue by bubl-ai** [run-llama/llama_index#16324]
### Feature Description

I have been using llama-index-embeddings-clip for some time. One requirement is to execute always `pip install
git+https://github.com/openai/CLIP.git` to make use of the embedding model.

Would it make sense to include this as a dependency in the [pyproject.toml](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/embeddings/llama-index-embeddings-clip/pyproject.toml)?

What about including in within the `[tool.poetry.dependencies]`  as shown below (last line of the next snippet)

```
[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
torch = "^2.1.2"
pillow = "^10.2.0"
torchvision = "^0.17.0"
ftfy = "^6.1.3"
llama-index-core = "^0.11.0"
clip = {git = "https://github.com/openai/CLIP.git", branch = "main"}
```

**Comment by logan-markewich** [comment]
You can't publish packages to pypi with github sources (at least, the last time I tried, that's what happened)

**Comment by bubl-ai** [comment]
That's good to know. Thanks so much for the clarification @logan-markewich
