### ISSUE TITLE
[Bug]: kwargs not being used in CondensePlusContextChatEngine

### ISSUE THREAD

**Issue by clickrlin** [run-llama/llama_index#16322]
### Bug Description

The `CondensePlusContextChatEngine.from_defaults` accepts `**kwargs` but it is not used anywhere in the method: https://github.com/run-llama/llama_index/blob/254c683afb505f89f390f0b29d9cc120c53c6aeb/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L139. I think it should be passed into https://github.com/run-llama/llama_index/blob/254c683afb505f89f390f0b29d9cc120c53c6aeb/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L149-L161 at the very least?

### Version

0.10.65

### Steps to Reproduce

See code references in bug description.

**Comment by logan-markewich** [comment]
Its only there because `index.as_chat_engine` abuses kwargs between the retriever and chat engine

Its fine that its not used -- its not needed anywhere afaik

**Comment by clickrlin** [comment]
I wanted to use it for passing in a `callback_manager` without needing to define a global one via `Settings.callback_manager` while using `from_defaults`. I thought maybe the `**kwargs` was intended to allow such a thing.

**Comment by logan-markewich** [comment]
Nope. Attach the callback manager to your llm and your index/retriever (and possibly the embedding model if using one)
