### ISSUE TITLE
[Feature Request]: Adding More Lenguage support for bm25 algorithm

### ISSUE THREAD

**Issue by marco-bertelli** [run-llama/llama_index#16333]
### Feature Description

Hi guys i test the bm25 custom retriver implementation:

`def create_embedding_retriever(index, areaId, similarity_top_k):
    retriever = index.as_retriever(
        service_context=service_context,
        filters=MetadataFilters(
            filters=[
                ExactMatchFilter(
                    key="areaId",
                    value=areaId,
                )
            ]
        ),
        similarity_top_k=similarity_top_k,
    )

    return retriever

def create_bm25_retriever(nodes_, areaId, similarity_top_k):
    """Function to create a bm25 retriever for a list of nodes"""

     # ! here we filter nodes that have in the metadata the areaId
    nodes_ = [node for node in nodes_ if node.metadata.get("areaId") == areaId]

    # ! if nodes are empty pass null
    if not nodes_:
        return None
    
    if len(nodes_) < similarity_top_k:
        similarity_top_k = len(nodes_)
    
    bm25_retriever = BM25Retriever.from_defaults(
        nodes=nodes_,
        similarity_top_k=similarity_top_k,
        stemmer=Stemmer.Stemmer("english"),
    )

    return bm25_retriever

class EmbeddingBM25RerankerRetriever(BaseRetriever):
    """Custom retriever that uses both embedding and bm25 retrievers and reranker"""

    def __init__(
        self,
        vector_retriever: VectorIndexRetriever,
        bm25_retriever: BM25Retriever,
        reranker: CohereRerank,
    ) -> None:
        """Init params."""

        self._vector_retriever = vector_retriever
        self.bm25_retriever = bm25_retriever
        self.reranker = reranker

        super().__init__()

    def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve nodes given query."""

        vector_nodes = self._vector_retriever.retrieve(query_bundle)

        bm25_nodes = []

        if self.bm25_retriever:
            bm25_nodes = self.bm25_retriever.retrieve(query_bundle)

        vector_nodes.extend(bm25_nodes)

        retrieved_nodes = self.reranker.postprocess_nodes(
            vector_nodes, query_bundle
        )

        return retrieved_nodes`

but as now i can't take a full advance of that in my language (italian) and as now only english is supported (i think is an algorithm problem not your's) but i am wondering if as now i can take advance of that in any language except english, because as now for italian only the retriever + reranking is better and faster than that.

Thanks in advice for the attention @logan-markewich maybe because you are the master of that thing you know a workaround, the response may be as now nope hahahha

### Reason

but as now i can't take a full advance of that in my language (italian) and as now only english is supported (i think is an algorithm problem not your's) but i am wondering if as now i can take advance of that in any language except english, because as now for italian only the retriever + reranking is better and faster than that.

Thanks in advice for the attention @logan-markewich maybe because you are the master of that thing you know a workaround, the response may be as now nope hahahha

**Comment by logan-markewich** [comment]
@marco-bertelli the underlying bm25s library added expanded language support, the above PR will bump the dependencies when it merges/publishes
