### ISSUE TITLE
[Question]: IndexNode.obj is erased.When i use index.storage_context.persist

### ISSUE THREAD

**Issue by nmhjklnm** [run-llama/llama_index#16346]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I create an `indexnode` as follows:

```python
indexnode = IndexNode.from_text_node(node, index_id=node.id_)
indexnode.id_ = str(uuid.uuid4())
indexnode.obj = node
```

Then, I use the following code:

```python
from llama_index.core import StorageContext
storage_context = StorageContext.from_defaults()
index = VectorStoreIndex(
    storage_context=storage_context,
    objects=index_nodes,
)
index.set_index_id("index")
index.storage_context.docstore.add_documents(nodes)
index.storage_context.persist()
```

However, after running the above code, `index.storage_context.docstore.docs['xxxx'].obj` is erased and cannot be restored by assignment.
This causes my Retriever to be unable to automatically enter into the `textNode`.

**Comment by nmhjklnm** [comment]
<img width="723" alt="image" src="https://github.com/user-attachments/assets/29ea4940-ae6c-4eda-92f4-cee77741655e">


obj is very important to me, so how can I implement Store the obj attribute separately ,and How can I combine the two parts back together?

I tried a simple approach:

```python
for i in list(index.storage_context.docstore.docs.values()):
    i.obj = [n for n in nodes if n.id_ == i.index_id][0]
```

I wanted to use this to restore `obj`, but `obj` is still `None` and it didn't work.

**Comment by nmhjklnm** [comment]
<img width="732" alt="image" src="https://github.com/user-attachments/assets/4e7057d2-e337-48f6-95ad-28b9cf5b12d6">
<img width="466" alt="image" src="https://github.com/user-attachments/assets/bee67e24-6e58-4fa2-bcef-fb862af112ef">
Let's do a quick test. As shown, I think the method you just suggested might be ineffective, just like my previous attempt.

**Comment by logan-markewich** [comment]
@nmhjklnm you can just pass it in like any other node, no need to use `objects=`

`VectorStoreIndex(nodes=<list of index nodes>)`

objects is generally there for stuff that isn't serializable

**Comment by nmhjklnm** [comment]
@logan-markewich Thank you so much for your suggestion! I tried passing the nodes directly as you mentioned, and it worked perfectly. Really appreciate your help!
<img width="718" alt="image" src="https://github.com/user-attachments/assets/5b724b15-bfb3-493d-9e9c-840ff83bb001">
