### ISSUE TITLE
[Bug]: ERROR: No matching distribution found for llama-index-multi-modal-llms-huggingface

### ISSUE THREAD

**Issue by Pentar0o** [run-llama/llama_index#16355]
### Bug Description

Hey, I've tried to install llama-index-multi-modal-llms-huggingface via the pip command and I got the error ERROR: No matching distribution found for llama-index-multi-modal-llms-huggingface

### Version

0.11.15

### Steps to Reproduce

pip install llama-index-multi-modal-llms-huggingface

### Relevant Logs/Tracbacks

```shell
ERROR: Could not find a version that satisfies the requirement llama-index-multi-modal-llms-huggingface (from versions: none)
ERROR: No matching distribution found for llama-index-multi-modal-llms-huggingface
```

**Comment by logan-markewich** [comment]
I just manually published it, should work now
https://pypi.org/project/llama-index-multi-modal-llms-huggingface/

**Comment by Pentar0o** [comment]
I have this issue as I've upgraded to the latest version of llama-index : llama-index-multi-modal-llms-huggingface 0.1.0 requires llama-index-core<0.11.0,>=0.10.0, but you have llama-index-core 0.11.15 which is incompatible
Do I have to uninstall all packages and force the install to 0.11.0 ?
