### ISSUE TITLE
[Bug]: Lincensing information is missing for llama-cloud lib dependency at PYPI

### ISSUE THREAD

**Issue by onazaruk** [run-llama/llama_index#16363]
### Bug Description

Hi,
After llama-index ver 0.10.55 the verification of the package fails on pip install at our org. It says the licensing information is missing for **llama-cloud** dependency. And indeed it is not there at PYPI.

Can it be added for **llama-cloud** please?
For llama-index it is: 
_Meta
License: MIT License (MIT)_

### Version

0.11.15

### Steps to Reproduce

1. Go to https://pypi.org/project/llama-cloud/
2. Check meta section
3. It is missing licensing

**Comment by logan-markewich** [comment]
Added
https://pypi.org/project/llama-cloud/

**Comment by onazaruk** [comment]
Thanks a ton for a lightening turn around! You are the best!
