### ISSUE TITLE
[Feature Request]: Llama-3.2-11B-Vision-Instruct support in llama_index.multi_modal_llms.huggingface and streamchat

### ISSUE THREAD

**Issue by Pentar0o** [run-llama/llama_index#16368]
### Feature Description

Being able to use  Llama-3.2-11B-Vision-Instruct model with the llama_index.multi_modal_llms.huggingface and being able to set up a streamchat instance with it.

**Comment by Pentar0o** [comment]
Just tried this code : 

from llama_index.multi_modal_llms.huggingface import HuggingFaceMultiModal
from llama_index.core.schema import ImageDocument

# Initialize the model
model = HuggingFaceMultiModal.from_model_name("meta-llama/Llama-3.2-11B-Vision-Instruct")

# Prepare your image and prompt
image_document = ImageDocument(image_path="Printer.jpg")
prompt = "Décris moi en détail cette image."

# Generate a response
response = model.complete(prompt, image_documents=[image_document])

print(response.text)

And got this error : 
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Traceback (most recent call last):
  File "/Users/penta/Desktop/Cortana_HF_Multimodal/Test.py", line 5, in <module>
    model = HuggingFaceMultiModal.from_model_name("meta-llama/Llama-3.2-11B-Vision-Instruct")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/llama_index/multi_modal_llms/huggingface/base.py", line 227, in from_model_name
    return MllamaMultiModal(model_name=model_name, **kwargs)
           ^^^^^^^^^^^^^^^^
NameError: name 'MllamaMultiModal' is not defined. Did you mean: 'LlamaMultiModal'?

**Comment by Pentar0o** [comment]
and for the streamchat I got this error : 
    Settings.llm = HuggingFaceMultiModal(
                   ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class HuggingFaceMultiModal without an implementation for abstract method 'stream_chat'

**Comment by Georgehe4** [comment]
@g-hano

**Comment by g-hano** [comment]
Hey @Pentar0o , I will fix the Llama3.2 support problem today. Right now HuggingFaceMultiModal does not support streaming but I will add it very soon.

**Comment by Pentar0o** [comment]
Thx so much ! And could you check the version problem as the module requires llama-index < 0.10 and the current version is >0.11 ?
