### ISSUE TITLE
[Bug]: AttributeError: 'Neo4jGraphStore' object has no attribute 'supports_vector_queries'

### ISSUE THREAD

**Issue by solarslurpi** [run-llama/llama_index#16383]
### Bug Description

calling PropertyGraphIndex while using Neo4jGraphStore causes the exception AttributeError: 'Neo4jGraphStore' object has no attribute 'supports_vector_queries'

### Version

Version: 0.11.11

### Steps to Reproduce

call PropertyGraphIndex

**Comment by logan-markewich** [comment]
@solarslurpi you should be using `Neo4jPropertyGraphStore` instead (its importable from the same package)

**Comment by solarslurpi** [comment]
Thank you.
