### ISSUE TITLE
[Question]: How can I specify the ability(metadata) of llm model? 

### ISSUE THREAD

**Issue by 912100012** [run-llama/llama_index#16428]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

The llm like DASHSCOPE has the ability of function call,but the package named llms in the llamaindex set the is_function_calling_model of metadata of all the DASHSCOPE model for False default so that it make the error "ValueError: Model name qwen-max does not support function calling API. "
So how can i  fix this problem such as specifying the is_function_calling_model  variables to True.(Attetion ,is_function_calling_model  
 is read-only decorating by @property)

**Comment by logan-markewich** [comment]
@912100012 the LLM needs to implement specific function calling logic (i.e subclassing FunctionCallingLLLM, implementing a few new methods)

It is not as simple as flipping a metadata value
