### ISSUE TITLE
[Question]: Roadmap for `IngestionPipeline`?

### ISSUE THREAD

**Issue by brycecf** [run-llama/llama_index#16429]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`IngestionPipeline` classes are components which are also shared by (the now deprecated) `QueryPipeline` class, such as a `TransformComponent`.

Are those components and the `IngestionPipeline` also to be deprecated, on the expectation that they should be rewritten as workflows or is that to remain supported?

**Comment by logan-markewich** [comment]
Actually, the query pipeline and ingestion pipeline are completely unrelated, despite the naming

Ingestion pipeline transformations inherit from the TransformComponent class, which just forces to implement `__call__` and `acall` methods. This is neither deprecated, nor shared with query pipelines (query pipelines implement a run_component and arun_component method)

I wouldn't expect to see the ingestion pipeline removed anytime soon. It's quite popular.

What i would expect is the docs to de-emphasize it, in favor of just implementing it yourself with workflows.

At some point the ingestion pipeline might be converted to use workflows under the hood, but it's not terribly urgent
