### ISSUE TITLE
MemoryBuffer is being ignored in index.as_uery_engine 

### ISSUE THREAD

**Issue by Danana1** [run-llama/llama_index#16442]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

[Question]: I am experimenting with the implementation of LlamIndex RAG.
When I call 

> index.**as_chat_engine**( memory=my_chat_memory, other parames) 

the memory buffer is filled, but when using the index in 

> index.**as_query_engine**(memory=my_chat_memory, other parames)

 the memory is not filled.
 
 Is it a bug on my hand or the standard behavior? If this is the standard behavior, What is the best method to fill in the MemoryBuffer manually

**Comment by logan-markewich** [comment]
Query engines are stateless, they do not use memory

Use any chat engine -- ContextChatEngine, CondensePlusContextChatEngine, or an agent
