### ISSUE TITLE
[Bug]: Wrong usage of generate_qa_embedding_pairs in Finetune Embeddings

### ISSUE THREAD

**Issue by kenmasumitsu** [run-llama/llama_index#16479]
### Bug Description

The example in [finetune_embedding](https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb) shows below.

```python
from llama_index.llms.openai import OpenAI

# No output_path argument. So, default output_path (qa_finetune_dataset.json) is used.
# It saves data in qa_finetune_dataset.json.
train_dataset = generate_qa_embedding_pairs(
    llm=OpenAI(model="gpt-3.5-turbo"), nodes=train_nodes
)

# No output_path argument. So, default output_path (qa_finetune_dataset.json) is used.
# It loads data from qa_finetune_dataset.json, that is created by train_nodes.
val_dataset = generate_qa_embedding_pairs(
    llm=OpenAI(model="gpt-3.5-turbo"), nodes=val_nodes
)

train_dataset.save_json("train_dataset.json")
val_dataset.save_json("val_dataset.json")
```

`generate_qa_embedding_pairs` does not provide `output_path` argument. So, the default value ("qa_finetune_dataset.json") is used as the `output_path`.

`generate_qa_embedding_pairs` loads `output_path` and then add generated QA.

So, the seconds `generate_qa_embedding_pairs` for val_dataset includes train_dataset.
Evaluation with the val_dataset is not effective.

Could you fix the example?

### Version

v0.11.17

### Steps to Reproduce
Run the https://github.com/run-llama/llama_index/blob/main/docs/docs/examples/finetuning/embeddings/finetune_embedding.ipynb

And compare train_dataset.json and val_dataset.json.

**Comment by logan-markewich** [comment]
@kenmasumitsu i don't think i get what the issue is?

`generate_qa_embedding_pairs()` does not have an output path yes

`save_json()` saves it to the path provided

What's the issue there? The second generate_qa_embedding_nodes only passes in the val nodes, so it does not contain the train nodes

**Comment by kenmasumitsu** [comment]
> What's the issue there? The second generate_qa_embedding_nodes only passes in the val nodes, so it does not contain the train nodes

The second `generate_qa_embedding_nodes` only passes in the val nodes. It is yes, but it takes the default output_path (`qa_finetune_dataset.json`). 

`qa_finetune_dataset.json` was generated by the first `generate_qa_embedding_nodes`, it contains the trains nodes.
And the second `generate_qa_embedding_nodes` loads the `qa_finetune_dataset.json`. 
As the result, the `val_dataset` includes the trains nodes.


https://github.com/run-llama/llama_index/blob/58c00bdb4f9be6cd9a84549a0b81ef05ee0b4987/llama-index-finetuning/llama_index/finetuning/embeddings/common.py#L122
```python
def generate_qa_embedding_pairs(
    nodes: List[TextNode],
    llm: LLM,
    qa_generate_prompt_tmpl: str = DEFAULT_QA_GENERATE_PROMPT_TMPL,
    num_questions_per_chunk: int = 2,
    retry_limit: int = 3,
    on_failure: str = "continue",  # options are "fail" or "continue"
    save_every: int = 500,
    output_path: str = "qa_finetune_dataset.json",
    verbose: bool = True,
) -> EmbeddingQAFinetuneDataset:

    ## HERE, load the `qa_finetune_dataset.json`
    queries, corpus, relevant_docs = load_existing_data(output_path)
```

**Comment by kenmasumitsu** [comment]
This issue is introduce by https://github.com/run-llama/llama_index/pull/14054

**Comment by kenmasumitsu** [comment]
PR: https://github.com/run-llama/llama_index/pull/16544
