### ISSUE TITLE
BadRequestError: Unsupported data type when using SimpeDirectoryReader Output

### ISSUE THREAD

**Issue by Jothimalar1997** [run-llama/llama_index#16488]
### Bug Description

When we read any pdf file using SimpleDirectoryReader() function, when ever we pass the output document to any function like VectorStoreIndex.from_documents() or generator.generate_with_llamaindex_docs() , it is giving BadRequestError: Unsupported data type

### Version

llama-index 0.11.17

### Steps to Reproduce

documents = SimpleDirectoryReader("data_ragas").load_data()
vector_index = VectorStoreIndex.from_documents(documents)

(or)

testset = generator.generate_with_llamaindex_docs(
    documents,
    test_size=50,
    distributions={simple: 0.5, reasoning: 0.25, multi_context: 0.25},
)

### Relevant Logs/Tracbacks

```shell
BadRequestError                           Traceback (most recent call last)
Cell In[11], line 6
      4 Settings.llm = generator_llm
      5 Settings.embed_model = embed_model
----> 6 vector_index = VectorStoreIndex.from_documents(documents)
      8 query_engine = vector_index.as_query_engine()

File c:\Users\jothimalar.p.lv\Documents\LLM POCS\TestSet generation\testsetenv\Lib\site-packages\llama_index\core\indices\base.py:119, in BaseIndex.from_documents(cls, documents, storage_context, show_progress, callback_manager, transformations, **kwargs)
    110     docstore.set_document_hash(doc.get_doc_id(), doc.hash)
    112 nodes = run_transformations(
    113     documents,  # type: ignore
    114     transformations,
    115     show_progress=show_progress,
    116     **kwargs,
    117 )
--> 119 return cls(
    120     nodes=nodes,
    121     storage_context=storage_context,
    122     callback_manager=callback_manager,
    123     show_progress=show_progress,
    124     transformations=transformations,
    125     **kwargs,
    126 )
...
   (...)
   1066     retries_taken=retries_taken,
   1067 )

BadRequestError: Unsupported data type
```

**Comment by logan-markewich** [comment]
Your error is truncated (notice the `(...)`, so its hard to say what the actual issue here is

I've personally never encountered this. Maybe something to do with your embedding model or Llm setup

**Comment by logan-markewich** [comment]
Without a google colab notebook or similar to reproduce, this will be near impossible to fix

**Comment by Jothimalar1997** [comment]
@logan-markewich,

Thanks much for the tips and I managed to fix the issue now. The problem is related to using old embedding API and when I updated it, it is working as expected. Appreciate your pointer on this!
