### ISSUE TITLE
[Bug]: Qdrant fastembed sparse encoder model name typo

### ISSUE THREAD

**Issue by manfredwang093** [run-llama/llama_index#16493]
### Bug Description

There is a typo in the default sparse encoder model name

there is an 'i' missing from `[prithivida/Splade_PP_en_v1](https://huggingface.co/prithivida/Splade_PP_en_v1)`

https://github.com/run-llama/llama_index/blob/58c00bdb4f9be6cd9a84549a0b81ef05ee0b4987/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/utils.py#L68

def fastembed_sparse_encoder(
    model_name: str = "prithvida/Splade_PP_en_v1",
    batch_size: int = 256,
    cache_dir: Optional[str] = None,
    threads: Optional[int] = None,
) -> SparseEncoderCallable:

### Version

0.11.17

### Steps to Reproduce

https://github.com/run-llama/llama_index/blob/58c00bdb4f9be6cd9a84549a0b81ef05ee0b4987/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/utils.py#L68

**Comment by logan-markewich** [comment]
Feel free to make a PR!

**Comment by manfredwang093** [comment]
Thanks Logan for your quick response, tried to push my branch, but got message saying "you don't have write access to run-llama/llama_index", is there a better way for me to create a PR, or how may I request write access? Thanks.


In a separate thread regarding LanceDB, there is a bug I shared there earlier regarding issues in data ingestion process. Could you take a look when have time? Thank you.
https://github.com/run-llama/llama_index/issues/14435#issuecomment-2364081499

**Comment by logan-markewich** [comment]
@manfredwang093 normally you need to fork the repo, push changes to your fork, and then propose a PR with your fork

**Comment by manfredwang093** [comment]
> @manfredwang093 normally you need to fork the repo, push changes to your fork, and then propose a PR with your fork

Thank you @logan-markewich , just opened this PR
https://github.com/run-llama/llama_index/pull/16494
