### ISSUE TITLE
[Question]: How can I retain the source text when I use the TopicParse?

### ISSUE THREAD

**Issue by 912100012** [run-llama/llama_index#16498]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I face one problem ，When I use the TopicNodeParse, the text property of node after parsing will convert to the summary by llm ,which cause the source text losing,how can I catch the source in the parsing process and retain it to the matedata?

**Comment by logan-markewich** [comment]
@912100012 fyi you pasted your openai token, might want to revoke that. Going to delete your message
