### ISSUE TITLE
[Bug]: ImageDocument can not work with local images

### ISSUE THREAD

**Issue by whisper-bye** [run-llama/llama_index#16524]
### Bug Description

According to the documentation, https://docs.llamaindex.ai/en/stable/examples/multi_modal/dashscope_multi_modal/#use-images-from-local-files

The image is read incorrectly when constructing an ImageDocument using load_local_images because of the following

https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/multi_modal_llms/llama-index-multi-modal-llms- dashscope/llama_index/multi_modal_llms/dashscope/base.py#L152

Always use image_document.image_url

### Version

latest

### Steps to Reproduce

as same as the document

**Comment by logan-markewich** [comment]
Seems like a PR is needed to load images from local (unless dashscope doesn't allow that)

**Comment by whisper-bye** [comment]
it would be better if ImageDocument support directly constructed from base64 or PIL.Image

**Comment by whisper-bye** [comment]
After reviewing some documentation, this problem can be solved with the following methods.
https://help.aliyun.com/zh/model-studio/user-guide/vision#647c6397db430

```python
def chat_with_image(query_text: str, image: Image) -> Generator[CompletionResponse, None, None]:
    image_file = BytesIO()
    image.save(image_file, format="JPEG")
    image_base64 = base64.b64encode(image_file.getvalue()).decode("ascii")

    image_urls = [
        f"data:image/jpeg;base64,{image_base64}"
    ]

    image_documents = load_image_urls(image_urls)

    dashscope_multi_modal_llm = DashScopeMultiModal(
        model_name=DashScopeMultiModalModels.QWEN_VL_MAX,
    )

    return dashscope_multi_modal_llm.stream_complete(
        prompt=query_text,
        image_documents=image_documents,
    )
```

**Comment by 9ovn** [comment]
got this error ```shell
pydantic_core._pydantic_core.ValidationError: 2 validation errors for ChatMessage
blocks.0
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'image': 'data:image/jpe...sC9ckAAAAASUVORK5CYII='}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/union_tag_not_found
blocks.1
  Unable to extract tag using discriminator 'block_type' [type=union_tag_not_found, input_value={'text': 'extract the data from the image i gived'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.10/v/union_tag_not_found``` using the code provide by @whisper-bye,hope somebody give me a hint or just tell why...
