### ISSUE TITLE
[Bug]: Response time problem in Retriever with PgVectorStore

### ISSUE THREAD

**Issue by dogukanuhn** [run-llama/llama_index#16561]
### Bug Description

```
self.vector_store = PGVectorStore.from_params(
            database=os.environ["DB_NAME"],
            host=os.environ["DB_HOST"],
            password=os.environ["DB_PASS"],
            port=5432,
            user=os.environ["DB_USER"],
            table_name="test_bot",
            embed_dim=1536,
            hnsw_kwargs={
                "hnsw_m": 16,
                "hnsw_ef_construction": 150,
                "hnsw_ef_search": 30,
                "hnsw_dist_method": "vector_l2_ops",
            },
            
         vector_index = VectorStoreIndex.from_vector_store(
                vector_store=self.vector_store,
                embed_model=OpenAIEmbedding(model="text-embedding-3-small"),
            )
            return vector_index.as_query_engine(
                verbose=True,
                filters=filters,
                similarity_top_k=1,
                response_mode=ResponseMode.CONTEXT_ONLY,
            )
```
When I perform a vector search using OpenAIAgent, the response time is typically between 2-4 seconds. To improve performance, I disabled the response synthesizer.

Upon debugging the source code, I found that the _query_with_score function in PgVectorStore executes in milliseconds. However, when the retriever is activated, the response time increases to 2-3 seconds.

### Version

0.11.12

### Steps to Reproduce

1- Embed document
2- Define an OpenAIAgent
3- Ask a question to agent

**Comment by logan-markewich** [comment]
@dogukanuhn I don't think you are comparing the same things here

`vector_index.as_query_engine` creates a retriever + response synthesizer. The response synthesis will take by far the most amount of time

By contrast, `vector_index.as_retriever` would create purely a retriever, which would run quickly

You can compare like

```
query_engine = index.as_query_engine()
retriever = index.as_retriever()

resp = query_engine.query("...")
print(resp)

retriever = index.as_retriever()
nodes = retriever.retrieve("...")
print(nodes)
```

**Comment by dogukanuhn** [comment]
@logan-markewich thank you for answer, My OpenAIAgent is working with function call. So when i set tool_retriever with retriever engine, it says "you can not use both". What is the correct approach for this situation?

**Comment by dogukanuhn** [comment]
<img width="658" alt="image" src="https://github.com/user-attachments/assets/acf683c3-e6f0-4c9f-a6e5-38610123de8b">

 i made necessary changes from `QueryEngineTool.from_defaults` to `RetrieverTool.from_defaults` but response time is still too much. Is this response time okey?

**Comment by logan-markewich** [comment]
Seems fine to me/expected 👀 

You can always make your own agent from scratch with workflows, if you want more control over how things are called 
https://docs.llamaindex.ai/en/stable/module_guides/workflow/#workflows
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/
