### ISSUE TITLE
[Question]: How to use OpenAI's tool calling in the chat engine?

### ISSUE THREAD

**Issue by whisper-bye** [run-llama/llama_index#16578]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Currently, there seems to be no direct support for tool calling in the chat engine.

```python
reader = SimpleDirectoryReader("data", required_exts=[".md"], recursive=True)
documents = reader.load_data()
index = VectorStoreIndex.from_documents(documents)
chat_engine = index.as_chat_engine(chat_mode=ChatMode.CONTEXT)  # tools=[tool] ???
```

**Comment by whisper-bye** [comment]
@dosu How do I register my own tools? For example a tool to get the current weather.

**Comment by whisper-bye** [comment]
@dosu It's not what I expected.

**Comment by logan-markewich** [comment]
Use a FunctionCallingAgent
https://docs.llamaindex.ai/en/stable/examples/cookbooks/oreilly_course_cookbooks/Module-6/Agents/#functioncallingagent-with-rag-queryenginetools

Or build your own agent with workflows for more control

https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/

**Comment by whisper-bye** [comment]
@logan-markewich 
These links are helpful, but it would be better with simpler support, enabling the chat engine to directly invoke tools.

**Comment by logan-markewich** [comment]
@whisper-bye that's exactly what the function calling agent does. It's just a chat engine that has access to tools
