### ISSUE TITLE
[Question]: How can I not add metadata?

### ISSUE THREAD

**Issue by Kai-Chen00** [run-llama/llama_index#16621]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

For the below given code, how can I not add metadata?
class EntitySplitter(NodeParser):

```
    def _parse_nodes(self, documents, show_progress=False, **kwargs):
        """
        parse the documents into nodes
        """
        nodes = []
        for doc in documents:
          entities = doc.text.split('\n')
          for e in entities:
            cleaned_entity = e.strip()
            if cleaned_entity != "":
                nodes.append(TextNode(text=cleaned_entity, metadata=doc.metadata))
        return nodes
```

**Comment by logan-markewich** [comment]
A metadata extract adds metadata to a node -- thats how it works 😅 

You can always post-process the resulting nodes an remove the metadata yourself though
