### ISSUE TITLE
[Feature Request]: Add Support for Claude 3.5 Sonnet V2

### ISSUE THREAD

**Issue by chrismgonzalez** [run-llama/llama_index#16681]
### Feature Description

With the latest release of Claude Sonnet 3.5 V2, it would be nice to have this supported in the the `llama-index-llms-bedrock-converse` package.  It supports messages and tool use, so we can use it with those existing features of the package.

For good measure, we can update the `llama-index-llms-bedrock`, as well.

### Reason

One could in theory download the package, update the model, and bundle it.  But that only works for an individual.  Not ideal!

### Value of Feature

It adds the latest foundation model from Anthropic for Amazon Bedrock into the library.  This will enable those of us on developing greenfield applications the ability to use the latest models.

**Comment by chrismgonzalez** [comment]
I'm happy to take on this task!

**Comment by logan-markewich** [comment]
The above PR will release a new version of both the bedrock and bedrock converse integration packages when it merges. Added support for the new sonnet model
