### ISSUE TITLE
[Bug]: No module named 'llama_index.retrievers'

### ISSUE THREAD

**Issue by fgy624** [run-llama/llama_index#16687]
### Bug Description

Hi, here i want to use following code:
`from llama_index.retrievers import BaseRetriever, VectorIndexRetriever, KeywordTableSimpleRetriever`
but I met an error:No module named 'llama_index.retrievers'
Please tell me how can I solve this

### Version

0.11.19

### Steps to Reproduce

maybe use 'from llama_index.retrievers import BaseRetriever, VectorIndexRetriever, KeywordTableSimpleRetriever
'

**Comment by logan-markewich** [comment]
That is indeed not an import. Are you following a very old blog post?

Please see our docs for latest imports: https://docs.llamaindex.ai

The correct import here is
```
from llama_index.core.retrievers import ...
```
