### ISSUE TITLE
[Bug]: ImportError: cannot import name 'ResponseSynthesizer' from 'llama_index' (unknown location)

### ISSUE THREAD

**Issue by fgy624** [run-llama/llama_index#16714]
### Bug Description

Hi, here i want to use following code:
from llama_index import ResponseSynthesizer
but I met an error:ImportError: cannot import name 'ResponseSynthesizer' from 'llama_index' (unknown location)
Please tell me how can I solve this

### Version

0.11.19

### Steps to Reproduce

maybe use 'llama_index import ResponseSynthesizer'

**Comment by fgy624** [comment]
OK! But I met another Error: cannot import name 'LLMPredictor' from 'llama_index' (unknown location)

**Comment by fgy624** [comment]
could you tell me how to solve it?

**Comment by fgy624** [comment]
If I must use "LLMPredictor", which version of llama_index should I use?

**Comment by logan-markewich** [comment]
LLMPredictor was removed a long time ago. Like, anything before v0.10.x will have it.

I really recommend reading the latest docs and using the latest versions of the library though

**Comment by logan-markewich** [comment]
In latest versions, you can just pass the llm in directly

`index.as_query_engine(llm=llm)`

Or set a global default
```
from llama_index.core import Settings

Settings.llm = llm
```
