### ISSUE TITLE
[Bug]: ImportError: cannot import name 'VideoAudioParser' from 'llama_index.readers.file.video_audio'

### ISSUE THREAD

**Issue by fgy624** [run-llama/llama_index#16730]
### Bug Description

ImportError: cannot import name 'VideoAudioParser' from 'llama_index.readers.file.video_audio'

### Version

0.6.0

### Steps to Reproduce

ImportError: cannot import name 'VideoAudioParser' from 'llama_index.readers.file.video_audio'

**Comment by logan-markewich** [comment]
The correct import is 

`from llama_index.readers.file.video_audio import VideoAudioReader`

https://colab.research.google.com/drive/1TH-BGpdWIS3mPePf7GASpXVb8sK6IfCH?usp=sharing
