### ISSUE TITLE
[Bug]: How can I use LangchainEmbedding

### ISSUE THREAD

**Issue by fgy624** [run-llama/llama_index#16732]
### Bug Description

How can I use LangchainEmbedding

### Version

0.11.20

### Steps to Reproduce

How can I use LangchainEmbedding

**Comment by fgy624** [comment]
whar about GPTVectorStoreIndex?

**Comment by logan-markewich** [comment]
GPTVectorStoreIndex is a super old name

It would be

```
from llama_index.core import VectorStoreIndex

index = VectorStoreIndex.from_documents(documents, embed_model=embed_model)
```

As always, our docs have the latest examples and usage for everything
