### ISSUE TITLE
[Bug]: generate_question_context_pairs generates unexpected questions

### ISSUE THREAD

**Issue by licheng0794** [run-llama/llama_index#16745]
### Bug Description

I was using llama 3.2 as llm and generated questions based on nodes. 

I am using the code below
qa_dataset_sub = generate_question_context_pairs(
    nodes,
    llm=llm,
    num_questions_per_chunk=2
)

**when I set number_questions_per_chunck=1, qa_dataset_sub.queries were below:** 

{'80a171c7-aad5-4e0a-94d4-95aa816229bb': "Here's a question that can be formed from the given context:"}

**when I set number_questions_per_chunck=2, qa_dataset_sub.queries were below:** 

{'858fe794-0bf4-47c1-bcee-15312b7c5ba5': 'Here are two potential questions based on the provided context information:',
 '8b338045-7e69-4cb9-9ea6-f901121b26ed': 'What type of bacteria has been proposed as a suitable indicator of contamination of water supplies?'}

**when I set number_questions_per_chunck=3, qa_dataset_sub.queries were below:** 

{'d4ef604c-6b2c-4d85-99e6-e0a68ddc97b0': 'Here are three questions based on the given context information:',
 '1819932b-99ad-430c-9bec-f4cbdab34134': 'What type of bacteria has been proposed as a suitable indicator of contamination of water supplies?',
 '1e08f2f5-3116-4bc0-b07a-e5dd0d7e39b4': 'According to the USEPA, what is Bacteroides used as in faecal source tracking?'}

It is obvious the first question is not right. If I directly feed these questions to the Evaluators, the metric (such as hit rate) is very low. 

What is the reason causing the issue? Can it be fixed in future? 

### Version

0.11.19

### Steps to Reproduce

qa_dataset_sub = generate_question_context_pairs(
    nodes,
    llm=llm,
    num_questions_per_chunk=2
)

I was using llama3.2 as llm

**Comment by logan-markewich** [comment]
@licheng0794 pretty sure you just need to update the prompt?

It's assuming there's a question on every line basically 

https://github.com/run-llama/llama_index/blob/3b72de8986a3219b1852b500dc5601f89157d35f/llama-index-finetuning/llama_index/finetuning/embeddings/common.py#L98

https://github.com/run-llama/llama_index/blob/3b72de8986a3219b1852b500dc5601f89157d35f/llama-index-finetuning/llama_index/finetuning/embeddings/common.py#L162

Either that, or filter the results to remove the questions that have preamble

**Comment by licheng0794** [comment]
@logan-markewich 

Changing the prompt seems work. Thank you.
