### ISSUE TITLE
[Bug]: SentenceTransformerRerank changes score type on NodeWithScore from float to np.float32

### ISSUE THREAD

**Issue by carlsonscottbah** [run-llama/llama_index#16743]
### Bug Description

Using SentenceTransformerRerank, when it rewrites the nodes for postprocessing retrieval, writes a numpy float32 score value on NodeWithScore.score field which is defined as Optional[float]. This breaks the contract when Pydantic evaluates the node.

### Version

0.11.1

### Steps to Reproduce

1. Create vector store retrieval engine
2. Add SentenceTransformerRerank as a postprocessor
3. Query the retrieval engine
4. Return the Response object to FastAPI
5. FastAPI parses the NodeWithScore object and blows up when it can't read np.float32

### Relevant Logs/Tracbacks

```shell
c:\...\.venv\Lib\site-packages\llama_index\core\schema.py:79: UserWarning: Pydantic serializer warnings:
  Expected `float` but got `float32` - serialized value may not be as expected
  data = handler(self)
ERROR:    2024-10-29 14:42:47 - Unable to serialize unknown type: <class 'numpy.float32'>
INFO:     127.0.0.1:61794 - "POST /api/query HTTP/1.1" 500 Internal Server Error
```

**Comment by logan-markewich** [comment]
@carlsonscottbah its already a float
https://github.com/run-llama/llama_index/blob/306e4fecff30adca537c4345035ad62dd43e7403/llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py#L106

What version of `llama-index-postprocessor-sbert-rerank` do you have? The latest is v0.2.0

**Comment by carlsonscottbah** [comment]
> @carlsonscottbah its already a float
> 
> https://github.com/run-llama/llama_index/blob/306e4fecff30adca537c4345035ad62dd43e7403/llama-index-integrations/postprocessor/llama-index-postprocessor-sbert-rerank/llama_index/postprocessor/sbert_rerank/base.py#L106
> 
> What version of `llama-index-postprocessor-sbert-rerank` do you have? The latest is v0.2.0

I'm running 0.2.1 as per my pyproject.toml.

I'm using the import string mentioned in https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/SentenceTransformerRerank/, which looks like is using the [sbert_rerank.py file inside llamaindex.core](https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/postprocessor/sbert_rerank.py), not the one you linked in llama-index-integrations. 

https://github.com/run-llama/llama_index/blob/306e4fecff30adca537c4345035ad62dd43e7403/llama-index-core/llama_index/core/postprocessor/sbert_rerank.py#L89

I'll move my import over to that version. Thank you!

**Comment by carlsonscottbah** [comment]
@logan-markewich Thanks for the help.

The issue is fixed when using 
```from llama_index.postprocessor.sbert_rerank import SentenceTransformerRerank```

instead of what is listed on https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/SentenceTransformerRerank/:
```from llama_index.core.postprocessor import SentenceTransformerRerank```
