### ISSUE TITLE
[Question]: openAI agent with query engine tools generating wrong input

### ISSUE THREAD

**Issue by mirallm** [run-llama/llama_index#16757]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when I use OpenAI agent tools with stream_chat engine

example

`

        list_query_engine = summary_index.as_query_engine(llm=llm,  use_async=True,  text_qa_template=text_qa_template, refine_template=refine_template,    pre_filters={
                              "filters": [{"conversation_id":conversation_id, "scenario":scenario}]} , streaming=True,
                              response_mode="tree_summarize"  )
          vector_query_engine = vector_index.as_query_engine(llm=llm, similarity_top_k=6,   text_qa_template=text_qa_template, refine_template=refine_template,     pre_filters={
                          "filters": [{"conversation_id":conversation_id, "scenario":scenario}]} , streaming=True, use_async=True)
                      

        query_engine_tools = [
            QueryEngineTool(
                query_engine=list_query_engine,
                metadata=ToolMetadata(
                    name="list_doc",
                    description=(
                  use for summarisation questions
                    ),
                ),
            ),
            QueryEngineTool(
                query_engine=vector_query_engine,
                metadata=ToolMetadata(
                    name="vector_doc",
                    description=(
                      use for specific questions
                    ),
                ),
            ),
        ]

        agent = OpenAIAgent.from_tools(
                            query_engine_tools,
                            
                            llm=llm,
                            use_async=True,
                    
                        
                            verbose=True,
                            
                            
                            system_prompt=f"""\
                    
                    You must try to use one of the tools provided when answering user's question; if you don't know what to use, use list_doc tool as argument. Do not rely on prior knowledge if the question is not related.
                    However, ask the user to generate a new topic by writing the keyword 'newtopic' if the question is not related to the context, document \
                    """,
                        )

        response= await agent.astream_chat(text)
        
`

what happens is that when i ask let's say: summarise the document which is the text variable, output is
=== Calling Function ===
Calling function: vector_doc with args: {
  "input": ""the document"
}
and hence this affect the answer because it doesn't identify the right keyword which is summarise. How to avoid these problems please?

**Comment by mirallm** [comment]
Hello, the problem is I did that, but when calling the function the input is selected wrong. In this scenario, it selected the document instead of summarise. @dosubot

**Comment by logan-markewich** [comment]
Write a better tool description? Give examples of how to call tools in your system prompt?

**Comment by mirallm** [comment]
@logan-markewich I have already provided my system prompt. Is there another way? what @dosu suggest is similar to mine, I do not see the difference

**Comment by mirallm** [comment]
@dosu yes ok but this cannot work for all words in the world. How can i avoid that the input argument is taken as it is and not only half of it , like this case
=== Calling Function ===
Calling function: vector_doc with args: {
"input": ""the document"
}

**Comment by mirallm** [comment]
@dosu the input parsing is done in llama index library. thats the problem thats why i am asking you

**Comment by logan-markewich** [comment]
@mirallm There is no other way really -- write a better system prompt and tool descriptions. These are very powerful.

Alternatively, if you need more control somehow, you could implement the agent loop yourself with workflows

This is a decent example: https://github.com/run-llama/multi-agent-concierge/blob/main/video_tutorial_materials/01_basic_agent.ipynb
From this video: https://www.youtube.com/watch?v=wuuO04j4jPc

**Comment by lmaddox** [comment]
Have you tried testing it without a custom prompt? I spent all last night hassling my ReAct agent about the correct response format, only to `set_global_handler('simple')`, and subsequently realize that the retriever works, the ReAct agent precisely gives the correct query, and yet the QueryEngineTool returns nothing.

Have you tested without streaming? Also, I think OpenAI's models handle tool-calling natively, and I'm not sure how that might interact with the custom prompts.

**Comment by mirallm** [comment]
I had to change the prompt of queryengine to 
            
        query_engine_tools = [
            QueryEngineTool(
                query_engine=list_query_engine,
                metadata=ToolMetadata(
                    name="list_doc",
                    description=(
                    os.getenv('SUMMARIZATION_'+scenarioName)  +' Use a detailed plain text question as input to the tool.'
                    ),
                ),
            ),
            QueryEngineTool(
                query_engine=vector_query_engine,
                metadata=ToolMetadata(
                    name="vector_doc",
                    description=(
                        os.getenv('VECTOR_'+scenarioName)  +' Use a detailed plain text question as input to the tool.'
                    ),
                ),
            ),
        ]


specified Use a detailed plain text question as input to the tool.'
