### ISSUE TITLE
[Bug]: PyMuPDF loader not working with SimpleDirectoryReader

### ISSUE THREAD

**Issue by vikrantdeshpande09876** [run-llama/llama_index#16758]
### Bug Description

Trying to execute:
```python
from llama_index.core import SimpleDirectoryReader
from llama_index.readers.file import PyMuPDFReader

reader_config = SimpleDirectoryReader(
    input_dir="../data/raw/rag-data",
    recursive=True,
    file_extractor={
        '.pdf' : PyMuPDFReader
    }
)
documents = reader_config.load_data()
```

### Version

llama-index==0.11.19 llama-index-agent-openai==0.3.4 llama-index-cli==0.3.1 llama-index-core==0.11.19 llama-index-embeddings-huggingface==0.3.1 llama-index-embeddings-openai==0.2.5 llama-index-indices-managed-llama-cloud==0.4.0 llama-index-legacy==0.9.48.post3 llama-index-llms-langchain==0.4.2 llama-index-llms-openai==0.2.16 llama-index-llms-openai-like==0.2.0 llama-index-llms-openllm==0.3.1 llama-index-multi-modal-llms-openai==0.2.3 llama-index-program-openai==0.2.0 llama-index-question-gen-openai==0.2.0 llama-index-readers-file==0.2.2 llama-index-readers-llama-parse==0.3.0 llama-index-vector-stores-postgres==0.2.6

### Steps to Reproduce

Shouldn't this [line](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/pymu_pdf/base.py#L15) be `file: Union[Path, str],` instead?
Am I missing something obvious here, or is there some version inconsistency?

### Relevant Logs/Tracbacks

```shell
Failed to load file /Users/myPC/../data/raw/rag-data/file1(en).pdf with error: PyMuPDFReader.load_data() missing 1 required positional argument: 'file_path'. Skipping...
Failed to load file /Users/myPC/../data/raw/rag-data/file2.pdf with error: PyMuPDFReader.load_data() missing 1 required positional argument: 'file_path'. Skipping...
Failed to load file /Users/myPC/../data/raw/rag-data/file3.pdf with error: PyMuPDFReader.load_data() missing 1 required positional argument: 'file_path'. Skipping...
Failed to load file /Users/myPC/../data/raw/rag-data/file4.pdf with error: PyMuPDFReader.load_data() missing 1 required positional argument: 'file_path'. Skipping...
```

**Comment by logan-markewich** [comment]
Yea pretty sure you need to instantiate the reader like dosu suggested

**Comment by vikrantdeshpande09876** [comment]
Man 🤦.
Okay closing this out.
