### ISSUE TITLE
[Question]: OpenAIAgent not retrieving data from VectorStore

### ISSUE THREAD

**Issue by yehiasalam** [run-llama/llama_index#16788]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,

I'm getting a very weird behavior from the OpenAIAgent with a tool from a query engine provided with a vectorstore. I have a vector store up and running with the embeddings, and the query engine works perfectly fine on its own:

```
def get_answer_from_local_query_engine(query_text):

    index = index_storage.index()
    local_query_engine = index.as_query_engine(
        response_synthesizer=get_response_synthesizer(
            response_mode=ResponseMode.NO_TEXT
        ),
        node_postprocessors=[SimilarityPostprocessor(similarity_cutoff=SIMILARITY_CUTOFF)]   
     )

    local_query_response = local_query_engine.query(query_text)
    logger.debug("Local Query Results:")
    if len(local_query_response.source_nodes) > 0:
        matched_node = local_query_response.source_nodes[0]
        matched_question = matched_node.text
        for n in local_query_response.source_nodes:
            logger.debug(f"Score ({n.score}) - {n.text}")
        #logger.debug(f"Found matched question from index: {matched_question}")
        return matched_question
    else:
        logger.debug("No local results")
        return None
```

I'm getting two results with score > .8 as expected. The problem is when I use this query engine with the OpenAIAgent, its not retrieving any results from the query engine, as if it's not querying it, and I keep getting no matches from my local query engine. Not sure what im doing wrong? My code is as below:

```
    query_engine_tools = [
        QueryEngineTool.from_defaults(
            query_engine=local_query_engine, # same query engine as aboe
            name="local_query_engine",
            description="Queries from a knowledge base consists of typical questions that a customer might ask",
        )
    ]
    chat_llm = OpenAI(
        temperature=0,
        model=index_storage.current_model,
        streaming=False,
        max_tokens=100,
    )

    chat_history = [ChatMessage(role=c.role, content=c.content) for c in history]
    chat_engine= OpenAIAgent.from_tools(
        tools=query_engine_tools,
        llm=chat_llm,
        chat_history=chat_history,
        verbose=True,
        system_prompt=SYSTEM_PROMPT_TEMPLATE_FOR_CHAT_ENGINE
   )
  res = chat_engine.chat(question)

```

And prompt is:

```
SYSTEM_PROMPT_TEMPLATE_FOR_CHAT_ENGINE = (
    "Your are a friendly support agent helping customers. Always greet customers when they say Hi or Hello. You can find relevant information using the tools at your disposal. \n"
    "The tools can access a knowledge base the customer might inquire on.\n"
    "You may need to combine the chat history to fully understand the query of the user, but don't repeat the same previous answers.\n"
    "If the user's query doesn't match any of those typical questions, please answer " + f"'{get_default_answer_id()}' and if the next user response was yes or ok, please answer {get_liveagent_answer_id()}. \n"
    "If the user is requesting to talk to a live agent, please answer " + f"'{get_liveagent_answer_id()}'."
    "Respond to genereal knowledge questions outside the tools at your disposal by saying" + f"'{get_default_answer_id()}'"
)
```

**Comment by logan-markewich** [comment]
The combination of system prompt, tool name, tool description, and chat history will all influence if a tool gets called or no
I would suggest a better tool name and description here
name="customer_qa"
description="Useful for finding answers to common questions a customer might ask"

The default openai model is gpt-3.5, which also isn't the best agent. Maybe use 4o or 4o-mini

**Comment by yehiasalam** [comment]
yup i’m using GPT 4o, ahh so you mean i should be referring to the tool by name (customer_qa) in system prompt , something like 

‘’’
SYSTEM_PROMPT_TEMPLATE_FOR_CHAT_ENGINE = (
    "Your are a friendly support agent helping customers. Always greet customers when they say Hi or Hello. You can find relevant information using the tool customer_qa at your disposal. \n"
    "You may need to combine the chat history to fully understand the query of the user, but don't repeat the same previous answers.\n"
    "If the user's query doesn't match any of those typical questions, please answer " + f"'{get_default_answer_id()}' and if the next user response was yes or ok, please answer {get_liveagent_answer_id()}. \n"
    "If the user is requesting to talk to a live agent, please answer " + f"'{get_liveagent_answer_id()}'."
    "Respond to genereal knowledge questions outside the tools at your disposal by saying" + f"'{get_default_answer_id()}'"
)
‘’’

**Comment by logan-markewich** [comment]
That might help yes! Any way to make it more obvious how the agent should act, the better

**Comment by yehiasalam** [comment]
Thanks for the tip. What really helped as well is setting the `tool_choice` to required, as in `response = agent.chat(
    "What is 5 + 2?", tool_choice="auto"
)`

More on https://docs.llamaindex.ai/en/stable/examples/agent/openai_forced_function_call/ and https://platform.openai.com/docs/api-reference/chat/create#chat-create-tool_choice
