### ISSUE TITLE
[Bug]: llama-index-readers-upstage 0.2.1 version hasn't been updated

### ISSUE THREAD

**Issue by cyzhzhd** [run-llama/llama_index#16791]
### Bug Description

Hi Llama Index Team,

We've been working to update llama-index-readers-upstage to version 0.2.1, as outlined in this [pull request](https://github.com/run-llama/llama_index/pull/16099/files#diff-f87a69331ead40592e24527cbb715dc6589453f2d6cc7d7b0af55cd6fe4434a5). However, it appears the version has not been updated on [PyPI](https://pypi.org/project/llama-index-readers-upstage/).

Could you advise on any steps we might need to take, or if there’s any way we could facilitate updating the version on PyPI?

Thank you for your assistance!

### Version

v0.11.21

### Steps to Reproduce

1. install depedency `pip install llama-index-readers-upstage`
2. import UpstageDocumentParseReader

```
import os

os.environ["UPSTAGE_API_KEY"] = "YOUR_API_KEY"


from llama_index.readers.upstage import UpstageDocumentParseReader

file_path = "/PATH/TO/YOUR/FILE.pdf"

reader = UpstageDocumentParseReader()

# For improved memory efficiency, consider using the lazy_load_data method to load documents page by page.
docs = reader.load_data(file_path=file_path)

for doc in docs[:3]:
    print(doc)
```
and we've got ImportError for UpstageDocumentParseReader

**Comment by logan-markewich** [comment]
The publish failed because two packages were updated -- one that depended on the other being updated first.

I've manually published the reader package just now
https://pypi.org/project/llama-index-readers-upstage/

**Comment by cyzhzhd** [comment]
Thank you for your help!

Could you also guide us on where to locate any failed actions or logs? This would be helpful for troubleshooting in case of future deployment issues.
