### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.llms.sambanova'

### ISSUE THREAD

**Issue by hherpa** [run-llama/llama_index#16797]
### Bug Description

[docs](https://docs.llamaindex.ai/en/stable/examples/llm/sambanova/)
![image](https://github.com/user-attachments/assets/999654b2-2a64-4de8-a2e4-5c3cfcc08152)

![image](https://github.com/user-attachments/assets/9fd01bd9-8048-487f-8caf-123dcfd6c51f)

### Version

llama-index 0.11.20 | llama-index-llms-sambanova==0.0.1

### Steps to Reproduce

https://colab.research.google.com/drive/10cwJdOQmt0-i5KHOIKXRebNCaN0lk9EP?usp=sharing

**Comment by logan-markewich** [comment]
Seems like something wacky, the source code does not match that notebook at all

Fix incoming
https://github.com/run-llama/llama_index/blob/e26b2f3741eddf3026dee62083fd5a7d242918aa/llama-index-integrations/llms/llama-index-llms-sambanova/llama_index/llms/sambanova/base.py#L64

**Comment by logan-markewich** [comment]
Ah, this just merged. Docs aren't on stable yet. Its on latest

https://docs.llamaindex.ai/en/latest/examples/llm/sambanova/

**Comment by logan-markewich** [comment]
That was a fun one. Contributor published the package themselves instead of letting us publish it 😢 Renamed package + updated docs in the above PR @hherpa
