### ISSUE TITLE
[Question]: Question on Enabling Streaming Mode for `ReActAgent` in LlamaIndex

### ISSUE THREAD

**Issue by Xphi310302** [run-llama/llama_index#16815]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I’m currently working with the `ReAct` agent from `llama_index.core.agent`, but I’ve found it challenging to adapt it to my specific use case. To increase flexibility, I switched to the `ReActAgent` written in the Workflow module, which I found easier to customize. 

There’s a [guide on using ReActAgent in Workflow](https://docs.llamaindex.ai/en/stable/examples/workflow/react_agent/) that provides an example setup. However, I’m struggling to enable streaming mode for the final response of `ReActAgent`. In the example, all steps, including reasoning and the final output step, use the `achat` method to output responses. My goal is to use `astream_chat` specifically for the final response step so that I can stream the output to the UI in real time.

Is there a way to set this up?

### Additional Context

I want to:
1. Use `achat` for all intermediate steps to keep reasoning concise and synchronous.
2. Enable `astream_chat` only for the final step to allow for streaming and real-time updates in the UI.

Thank you for any suggestions or solutions!

**Comment by Xphi310302** [comment]
@dosu Here is the code snippet for `ReActAgent` written in Workflow. I want to adjust the agent’s output so that:

- If the response is the **final output**, it streams using `astream_chat`.
- For **intermediate steps**, it uses `achat` to provide synchronous responses.

This approach would let me stream the final answer to the UI, enhancing real-time user interaction, while keeping intermediate reasoning concise.

from typing import Any, List

from llama_index.core.agent.react import ReActChatFormatter, ReActOutputParser
from llama_index.core.agent.react.types import (
    ActionReasoningStep,
    ObservationReasoningStep,
)
from llama_index.core.llms.llm import LLM
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.tools.types import BaseTool
from llama_index.core.workflow import (
    Context,
    Workflow,
    StartEvent,
    StopEvent,
    step,
)
from llama_index.llms.openai import OpenAI


class ReActAgent(Workflow):
    def __init__(
        self,
        *args: Any,
        llm: LLM | None = None,
        tools: list[BaseTool] | None = None,
        extra_context: str | None = None,
        **kwargs: Any,
    ) -> None:
        super().__init__(*args, **kwargs)
        self.tools = tools or []

        self.llm = llm or OpenAI()

        self.memory = ChatMemoryBuffer.from_defaults(llm=llm)
        self.formatter = ReActChatFormatter(context=extra_context or "")
        self.output_parser = ReActOutputParser()
        self.sources = []

    @step
    async def new_user_msg(self, ctx: Context, ev: StartEvent) -> PrepEvent:
        # clear sources
        self.sources = []

        # get user input
        user_input = ev.input
        user_msg = ChatMessage(role="user", content=user_input)
        self.memory.put(user_msg)

        # clear current reasoning
        await ctx.set("current_reasoning", [])

        return PrepEvent()

    @step
    async def prepare_chat_history(
        self, ctx: Context, ev: PrepEvent
    ) -> InputEvent:
        # get chat history
        chat_history = self.memory.get()
        current_reasoning = await ctx.get("current_reasoning", default=[])
        llm_input = self.formatter.format(
            self.tools, chat_history, current_reasoning=current_reasoning
        )
        return InputEvent(input=llm_input)

    @step
    async def handle_llm_input(
        self, ctx: Context, ev: InputEvent
    ) -> ToolCallEvent | StopEvent:
        chat_history = ev.input

        response = await self.llm.achat(chat_history)

        try:
            reasoning_step = self.output_parser.parse(response.message.content)
            (await ctx.get("current_reasoning", default=[])).append(
                reasoning_step
            )
            if reasoning_step.is_done:
                self.memory.put(
                    ChatMessage(
                        role="assistant", content=reasoning_step.response
                    )
                )
                return StopEvent(
                    result={
                        "response": reasoning_step.response,
                        "sources": [*self.sources],
                        "reasoning": await ctx.get(
                            "current_reasoning", default=[]
                        ),
                    }
                )
            elif isinstance(reasoning_step, ActionReasoningStep):
                tool_name = reasoning_step.action
                tool_args = reasoning_step.action_input
                return ToolCallEvent(
                    tool_calls=[
                        ToolSelection(
                            tool_id="fake",
                            tool_name=tool_name,
                            tool_kwargs=tool_args,
                        )
                    ]
                )
        except Exception as e:
            (await ctx.get("current_reasoning", default=[])).append(
                ObservationReasoningStep(
                    observation=f"There was an error in parsing my reasoning: {e}"
                )
            )

        # if no tool calls or final response, iterate again
        return PrepEvent()

    @step
    async def handle_tool_calls(
        self, ctx: Context, ev: ToolCallEvent
    ) -> PrepEvent:
        tool_calls = ev.tool_calls
        tools_by_name = {tool.metadata.get_name(): tool for tool in self.tools}

        # call tools -- safely!
        for tool_call in tool_calls:
            tool = tools_by_name.get(tool_call.tool_name)
            if not tool:
                (await ctx.get("current_reasoning", default=[])).append(
                    ObservationReasoningStep(
                        observation=f"Tool {tool_call.tool_name} does not exist"
                    )
                )
                continue

            try:
                tool_output = tool(**tool_call.tool_kwargs)
                self.sources.append(tool_output)
                (await ctx.get("current_reasoning", default=[])).append(
                    ObservationReasoningStep(observation=tool_output.content)
                )
            except Exception as e:
                (await ctx.get("current_reasoning", default=[])).append(
                    ObservationReasoningStep(
                        observation=f"Error calling tool {tool.metadata.get_name()}: {e}"
                    )
                )

        # prep the next iteraiton
        return PrepEvent()

**Comment by logan-markewich** [comment]
@Xphi310302 Streaming with react is pretty hard, especially if you only want to stream the final step.

You can use `llm.astream_chat()` `ctx.write_event_to_stream()` to expose streaming events that contain the streaming llm response. But if you only want to stream the final step, you need check for `Answer:` in the stream, which indicates when the final response is starting

```python
...
response_gen = await llm.astream_chat(chat_history)

response_str = ""
found_answer = False
async for resp in response_gen:
  response_str += resp.delta or ""
  if found_answer:
    ctx.write_event_to_stream(MyStreamingEvent(delta=resp.delta))

  if `Answer:` in response_str:
   found_answer = True
...
```

Then when you call the workflow

```
handler = workflow.run(...)
async for ev in handler.stream_events:
  if isinstance(ev, MyStreamingEvent):
    print(ev.delta, end="", flush=True)

result = await handler
```

**Comment by phinx-orient** [comment]
@logan-markewich Thank you! I successfully implemented streaming for the final response. May I ask another question? I noticed that the code from the guide does not include an input slot for a `system prompt` in the `ReActAgent`. Could you advise on how I might modify the code to allow the `ReActAgent` using `Workflow` to accept a `system prompt` as input?

**Comment by logan-markewich** [comment]
@phinx-orient the system prompt is already there, you can inspect the `chat_history` being used in the llm call

The formatter inserts the system prompt which has details on how the react loop should work.

If you want to add additional context/instructions to this system prompt, you can set the `extra_context` variable, which injects extra context into the existing system prompt

`ReActChatFormatter(context=extra_context or "")`
