### ISSUE TITLE
[Bug]: Breaking changes: CondensePlusContextChatEngine - used to take PromptTemplate as the context_prompt parameter until 0.11.10

### ISSUE THREAD

**Issue by mingqxu7** [run-llama/llama_index#16810]
### Bug Description

Up until 0.11.10, one can create CondensePlusContextChatEngine by passing PromptTemplate as the context_prompt variable.  The advantage of this ability over longchain is that one can introduce additional mapping vars and functions, without limiting to only context_str and query_str.  Here's what I do:

LANG_CONTEXT_TEMPLATE = (
    "Context information is below."
    "\n--------------------\n"
    "{web_results_str}\n"
    "{context_str}"
    "\n--------------------\n"
    "Given the context information and not prior knowledge, provide a concise, accurate, and informative response to the query.\n"
    "{emotion_str}\n"
    "\n--------------------\n"
    "Query: {query_str}\n"
    "Answer in {language_str}:\n"
)
...
        context_template = PromptTemplate(
            LANG_CONTEXT_TEMPLATE,
            function_mappings={
                "language_str": format_language_fn, 
                "emotion_str": format_emotion_fn,
            }
        )

then create the chat engine:

        chat_engine = CondensePlusContextChatEngine.from_defaults(
                retriever=retriever, 
                llm=self.llm,
                system_prompt=self.system_prompt,
                node_postprocessors=node_postprocessors,
                context_prompt=context_template,
                condense_prompt=CONDENSE_PROMPT_TEMPLATE,
            )

This would work up until 0.11.10.  After that, the code will break at

  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 329, in stream_chat
    synthesizer, context_source, context_nodes = self._run_c3(
                                                 ^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 265, in _run_c3
    response_synthesizer = self._get_response_synthesizer(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/chat_engine/condense_plus_context.py", line 219, in _get_response_synthesizer
    qa_messages = get_prefix_messages_with_context(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/rag/lib/python3.11/site-packages/llama_index/core/chat_engine/utils.py", line 23, in get_prefix_messages_with_context
    context_str_w_sys_prompt = context_template + system_prompt.strip()
                               ~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'PromptTemplate' and 'str'

It's incredibly disheartening to find my code broken by this unexpected change to context_template.  The fact that it's now simply a string, when it used to be a PromptTemplate object, has completely disrupted my workflow, and I'm struggling to find any viable workarounds.

One of the main reasons I chose LlamaIndex over Langchain was precisely for this level of customization – the ability to go beyond simply defining a basic string template.  Langchain's limitations in this area were a major showstopper, and LlamaIndex offered a breath of fresh air.  This change feels like a significant step backward, negating a key advantage that drew me to LlamaIndex in the first place.

To be frank, this breaking change makes me question the value of continuing to use LlamaIndex. I strongly urge the development team to reconsider this decision and prioritize the needs of users who rely on the fine-grained control that made LlamaIndex so appealing.

### Version

any version above 0.11.10

### Steps to Reproduce

See bug description.  

### Relevant Logs/Tracbacks

_No response_

**Comment by logan-markewich** [comment]
The reason for this change was so that if a user retrieves more than the context window of the LLM, the chat engine uses a response synthesizer under the hood to avoid context window errors

Due to how this works, yes, it was simplified to strings. 

Looking at this again, it may be able to bring back prompt templates. I'll take a look.

**Comment by logan-markewich** [comment]
@mingqxu7 Actually, even in your example, there is an error, since query_str was never in the context prompt (See here the code from v0.11.9: https://github.com/run-llama/llama_index/blob/703a970bbe634f21723aefd62715297af09ebc8b/llama-index-core/llama_index/core/chat_engine/condense_plus_context.py#L27) -- query_str would never be formatted 

Beyond that, I can bring back support for handling prompt template types in the PR below

**Comment by mingqxu7** [comment]
Thank you for reinstating prompt template support!

**Comment by mingqxu7** [comment]
thank you for pointing out the bug, much appreciated!
