### ISSUE TITLE
[Bug]: cannot import name 'DataBricks' from 'llama_index.llms.databricks

### ISSUE THREAD

**Issue by hoangpnhat** [run-llama/llama_index#16867]
### Bug Description

from llama_index.llms.databricks import DataBricks ImportError: 
ImportError: cannot import name 'DataBricks' from 'llama_index.llms.databricks'

### Version

0.11.17

### Steps to Reproduce

from llama_index.llms.databricks import DataBricks

### Relevant Logs/Tracbacks

```shell
from llama_index.llms.databricks import DataBricks
ImportError: cannot import name 'DataBricks' from 'llama_index.llms.databricks'
```

**Comment by logan-markewich** [comment]
@hoangpnhat you have a typo, as dosu mentioned 

```
from llama_index.llms.databrics import Databricks
```
https://colab.research.google.com/drive/1mxWWgcnrHueDUAA5_eEDSDWAzO4S_oHf?usp=sharing
