### ISSUE TITLE
[Feature Request]: update tenacity to 9.0.0 to fix conflict with GraphRAG

### ISSUE THREAD

**Issue by eriklee1895** [run-llama/llama_index#16876]
### Feature Description

When my project use llama-index and [GraphRAG](https://github.com/microsoft/graphrag), there is a tenacity depends:

```
The conflict is caused by:
    graphrag 0.4.0 depends on tenacity<10.0.0 and >=9.0.0
    llama-index-core 0.11.22 depends on tenacity!=8.4.0, <9.0.0 and >=8.2.0
```
Here are the release notes for tenacity 9 (https://github.com/jd/tenacity/releases/tag/9.0.0)
And I found langchain has already updated tenacity version:
https://github.com/langchain-ai/langchain/pull/27201

Now, I wish llama-index can do the same change.

### Reason

My project is used GraphRAG and llamaindex both, and now the depends has tenacity conflict.

**Comment by lalitlal** [comment]
+ 1, this is also causing issue with Instructor python package.

**Comment by qedpi** [comment]
+1 for instructor

**Comment by 19920716** [comment]
+1

**Comment by Digma** [comment]
+1 would be super helpful for us as well

**Comment by eriklee1895** [comment]
I found the problem has been solved in https://github.com/run-llama/llama_index/commit/33ca8d3f8e4e2bc3c0e40a1fa778e4324fcfeaff
