### ISSUE TITLE
[Bug]: Can‘t setting global tokenizer

### ISSUE THREAD

**Issue by pzc163** [run-llama/llama_index#16902]
### Bug Description

Can‘t setting global tokenizer as below code

from llama_index.core.utils import get_tokenizer, set_global_tokenizer
import tiktoken

set_global_tokenizer(tiktoken.encoding_for_model("gpt-4o").encode)

<img width="848" alt="image" src="https://github.com/user-attachments/assets/a1147512-e948-42b4-b722-be671a121285">

### Version

0.11.22

### Steps to Reproduce

from llama_index.core.utils import get_tokenizer, set_global_tokenizer
from llama_index.core.settings import Settings
import tiktoken

set_global_tokenizer(tiktoken.encoding_for_model("gpt-4o").encode)

**Comment by logan-markewich** [comment]
What python or pydantic version do you have? This works fine for me

**Comment by logan-markewich** [comment]
If you can reproduce in Google colab, that'd be helpful

**Comment by pzc163** [comment]
> What python or pydantic version do you have? This works fine for me

Python==3.10，pydantic==2.9.2

my device is MacBookpro M3 silicon

**Comment by logan-markewich** [comment]
Works fine on google colab with with same
https://colab.research.google.com/drive/1uSq5njwifr7fwRgLbZTi4SA9qlGgGnCm?usp=sharing

And runs fine on my mac with the same

Try a fresh venv maybe

**Comment by pzc163** [comment]
> Works fine on google colab with with same https://colab.research.google.com/drive/1uSq5njwifr7fwRgLbZTi4SA9qlGgGnCm?usp=sharing
> 
> And runs fine on my mac with the same
> 
> Try a fresh venv maybe

thank u a lot！
