### ISSUE TITLE
[Question]: is it possible to use ollama is LLM and ReActAgent in Neo4jQueryToolSpec instead of openai models?

### ISSUE THREAD

**Issue by bright-arparwut** [run-llama/llama_index#16925]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

from llama_index.tools.neo4j import Neo4jQueryToolSpec
from llama_index.llms import Ollama
from llama_index.agent import ReActAgent

# Initialize Ollama LLM

llm = Ollama(
    model="llama2",
    temperature=0,
    base_url="http://localhost:11434"  # default Ollama server URL
)

# Initialize Neo4j database connection
gds_db = Neo4jQueryToolSpec(
    url="neo4j-url",
    user="neo4j-user",
    password="neo4j-password",
    llm=llm,
    database="neo4j",
)

# Create tools list
tools = gds_db.to_tool_list()

# Initialize ReActAgent instead of OpenAIAgent
# ReActAgent is more compatible with various LLM providers
agent = ReActAgent.from_tools(
    tools,
    llm=llm,
    verbose=True,
    max_iterations=3  
)

**Comment by logan-markewich** [comment]
@bright-arparwut yea of course. Is there a specific issue with your code?

Note that open-source LLMs make for pretty bad agents in most cases 😓 llama3.1 is probably the best I've tried so far. Maybe there are newer ones too that I've missed
