### ISSUE TITLE
[Question]: Conflict in packages versions using llama-index-packs-node-parser 0.1.2 

### ISSUE THREAD

**Issue by Danana1** [run-llama/llama_index#16929]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I am trying to use a few llama-index packages and found out there isn't a matching version.
Seems like llama-index-packs-node-parser 0.1.2 depends on llama-index-core<0.11.0 and >=0.10.1
This is an older llama-index-core version. Other packages I use require a newer version:

 The conflict is caused by:
The user requested llama-index-core==0.11.21
llama-index 0.11.5 depends on llama-index-core<0.12.0 and >=0.11.5
llama-index-agent-openai 0.3.0 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-cli 0.3.0 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-embeddings-huggingface 0.3.1 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-embeddings-instructor 0.2.1 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-embeddings-nvidia 0.2.1 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-llms-nvidia 0.2.6 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-llms-openai 0.2.2 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-llms-openai-like 0.2.0 depends on llama-index-core<0.12.0 and >=0.11.0
llama-index-multi-modal-llms-openai 0.2.0 depends on llama-index-core<0.12.0 and >=0.11.0
**llama-index-packs-node-parser 0.1.2 depends on llama-index-core<0.11.0 and >=0.10.1**
What are my options to keep on using the node parser? are there alternatives?

**Comment by logan-markewich** [comment]
Seems like a stale pack that was missed being updated. Easy PR to fix

**Comment by Danana1** [comment]
Hey @logan-markewich , this is correct. I think it makes sense to update this pack as well for version parity!

**Comment by logan-markewich** [comment]
Ah, this has already been fixed. The original package also had the wrong name, its been renamed to `llama-index-packs-node-parser-semantic-chunking` and it should work fine with the latest versions of things
