### ISSUE TITLE
[Question]: Is it possible to use the Weaviate hybrid search parameter "max_vector_distance" with a LlamaIndex retriever?

### ISSUE THREAD

**Issue by torbenw** [run-llama/llama_index#16940]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to use the parameter "max_vector_distance" for the Weaviate hybrid search with a LlamaIndex retriever, but I do not see any way to pass this parameter. Is it possible to use this parameter with a LlamaIndex retriever?

See here: https://weaviate.io/developers/weaviate/search/hybrid#vector-search-parameters

**Comment by awskhd** [comment]
is not working , i have tried to do this in llamaindex corde directly
  try:
            query_result = collection.query.hybrid(
                query=query.query_str,
                vector=vector,
                alpha=alpha,
                limit=limit,
                filters=filters,
                return_metadata=return_metatada,
                return_properties=all_properties,
                max_vector_distance=0.2,
                include_vector=True,
            )

**Comment by torbenw** [comment]
Is it possible to use max_vector_distance without having to change code of LlamaIndex?

**Comment by logan-markewich** [comment]
Fixed by https://github.com/run-llama/llama_index/pull/16954
