### ISSUE TITLE
[Bug]: PropertyGraph Index

### ISSUE THREAD

**Issue by sreenivasanm6** [run-llama/llama_index#16959]
### Bug Description

We are using property graph index for KG parts and we are processing it by keeping the graph in memory. Will it have any impact in accuracy in comparison to storing the graphs in graph DB like Neo4j. 

### Version

latest

### Steps to Reproduce

Read the description

**Comment by logan-markewich** [comment]
Yea the default graph store is not optimized for memory usage, it's just an in-memory dict essentially. As your graph grows, you will need more RAM

How that specifically compares to stuff like neo4j, I'm not sure, but I'm sure its better than an in-memory dict 👍🏻

**Comment by sreenivasanm6** [comment]
Thanks @logan-markewich . To make sure below is the process that is happening with property graph index in llama index.
Given unstructured data, llama index property graph index extracts nodes, edges and avoid duplication using llm.
Post to this, we will store this in neo4j. So, as per your comment, storing the data will impact based on RAM availability. Other than that it may not impact the retrieval parts whether its in memory or neo4j database. Please confirm.

Also, it would be good to know the difference between graphstore index and property graph index.
