### ISSUE TITLE
[Feature Request]: Consider supporting BM25opt

### ISSUE THREAD

**Issue by jankovicsandras** [run-llama/llama_index#16964]
### Feature Description

Hi,

LlamaIndex uses [rank_bm25](https://github.com/dorianbrown/rank_bm25) under the hood. I made an optimized variant, that has 30-40x faster search speed and fixes some of the issues of rank_bm25, while being score compatible: https://github.com/jankovicsandras/bm25opt
Please consider supporting it, I can help adapting it.

Thanks for your attention!

**Comment by logan-markewich** [comment]
They have a technical report here if you are interested
https://arxiv.org/pdf/2407.03618

**Comment by jankovicsandras** [comment]
Thanks, bm25s looks cool!

**Comment by jankovicsandras** [comment]
Closing the issue.
