### ISSUE TITLE
[Question]: 'NoneType' object has no attribute 'create_collection'

### ISSUE THREAD

**Issue by mirallm** [run-llama/llama_index#16977]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

          async def create_index_nodes(self, nodes,embed_model, vector_store):
              """
              Asynchronously creates an index in Qdrant based on the provided nodes.
              
              :param nodes: List of TextNodes to index.
              :param vector_store: The Qdrant vector store instance.
              """
              storage_context = StorageContext.from_defaults(vector_store=vector_store)
             
              vector_index =  VectorStoreIndex(
                  nodes=nodes,
                  embed_model=embed_model,
                  storage_context=storage_context
              )
              return vector_index
              
              
self._client.create_collection(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'create_collection'

please help. @dosubot

**Comment by logan-markewich** [comment]
I'm assuming this is qdrant? Make sure you pass in both the client and aclient 

`QdrantVectorStore(..., client=QdrantClient(...), aclient=AsyncQdrantClient(...))`
