### ISSUE TITLE
[Question]: Confluence Reader page content

### ISSUE THREAD

**Issue by elia-bracci-hs** [run-llama/llama_index#16980]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### **Issue Description**

When using the LlamaIndex Confluence reader to retrieve page content, the output includes unwanted sections such as "Recent updates," "Blog stream," and dynamically generated metadata like contributors and timestamps. 

I want to filter out these sections to focus only on the core content, such as the introductory text and final messages, while excluding unnecessary details: this is how Atlassian API works by giving only the page content.

Example: 
llama-index-reader-confluence:
```
Say hello to your colleagues who want to know your name, pronouns, role, team\nand location (or if you\'re remote).\n\n## 📄 Recent pages that I\'ve worked on\n\n## Recent updates\n\n  * LLM BOT Test page 2\n\nNov 08, 2024 • contributed by Elia Bracci\n\n  * LLM BOT test page\n\nNov 08, 2024 • contributed by Elia Bracci\n\n  * Overview\n\nSept 02, 2024 • contributed by Elia Bracci\n\n  * Elia Bracci\n\nSept 02, 2024 • contributed by Elia Bracci\n\n## Blog stream\n\nCreate a blog post to share news and announcements with your team and company.\n\nCreate blog post\n\n## 🖐 Get in touch\n\n✉️\n\n💼\n\n🔗\n\n👤\n\nEnd with a bang! Some options are: "I am so grateful to be here at <Insert\ncompany name> and very excited to get started!" or "Looking forward to meeting\nall of you!" or "Can\'t wait to get to know all of you!"
```

Atlassian Confluence API:
```
Say hello to your colleagues who want to know your name, pronouns, role, team and location (or if you're remote). 📄 Recent pages that I've worked on 5 5 titles 🖐 Get in touch ✉️ Insert your email here 💼 Insert your LinkedIn URL here 🔗 Insert your Twitter handle here 👤 Insert your Medium profile here End with a bang! Some options are: "I am so grateful to be here at <Insert company name> and very excited to get started!" or "Looking forward to meeting all of you!" or "Can't wait to get to know
```

**Comment by logan-markewich** [comment]
There are a LOT of options on this reader. Not 100% sure what they all do, but the source code might be helpful. Maybe there's an easy PR here
https://github.com/run-llama/llama_index/blob/293709e725718e70f1976870dd2462fd83d7a727/llama-index-integrations/readers/llama-index-readers-confluence/llama_index/readers/confluence/base.py#L108
