### ISSUE TITLE
[Bug]: Unable to get filters to work in llama-index-vector-stores-elasticsearch 

### ISSUE THREAD

**Issue by shriram1998** [run-llama/llama_index#16990]
### Bug Description

Vector store queries created with "filters", when transformed to elastic search filter is transformed to the below format. Filter in this format does not work when executed in elastic search index. Sorry if the issue already has a fix or a workaround.
```
return {
            "term": {
                f"metadata.{filter.key}.keyword": {
                    "value": filter.value,
                }
            }
        }
```
The following format works correctly:
```
return {
            "term": {
                f"metadata.{filter.key}": filter.value, # or just filter.key as the key
            }
        }
```
Function that's causing the issue: `_to_elasticsearch_filter` in https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py

**Versions used:**
elasticsearch==8.14.0 
llama-index==0.10.63 
llama-index-vector-stores-elasticsearch==0.2.5

### Version

0.10.63

### Steps to Reproduce

1. Create a vector store query with filters
2. Run the query in elastic search

**Comment by logan-markewich** [comment]
@shriram1998 this might be fixed? There are many new versions ahead of the version you are using (but they might requiring you updating to v0.11.x)
<img width="716" alt="image" src="https://github.com/user-attachments/assets/53044dd2-d771-4f40-995e-d28328e8edc9">

**Comment by logan-markewich** [comment]
@shriram1998 Seems this PR added the `.keyword` suffix https://github.com/run-llama/llama_index/pull/16519

Seems like, by default, this should be working, at least with latest versions?

**Comment by shriram1998** [comment]
@logan-markewich Thank you for the response. I updated to the latest versions of the packages as you suggested and found that the above issue is resolved, when using the new function parameter mentioned in #16519  to customize the metadata keyword.
