### ISSUE TITLE
[Bug]: llama-index is only compatible with pydantic version <2.10.0 

### ISSUE THREAD

**Issue by sarahwooders** [run-llama/llama_index#17017]
### Bug Description

We have a llama-index dependency which was throwing errors for some users with the error: 
```
  File "/Users/sarahwooders/Library/Caches/pypoetry/virtualenvs/letta-uyfZJ7Lr-py3.12/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 515, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for typing.AsyncGenerator[str, NoneType]. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.
```
We found that we had to constrain our package dependencies to `pydantic = ">=2.7.4,<2.10.0"` to be able to install llama-index issue. We'd recommend updating the llama-index `pyproject.toml` to also include the `<2.10.0` constraint. 

### Version

^0.11.9

### Steps to Reproduce

Install `llama-index` after installing pydantic==2.10.0

**Comment by logan-markewich** [comment]
@sarahwooders I've already released `llama-index-core==0.12.1` which pins `pydantic<2.10`

Either update to v0.12.1 of core, or pin your pydantic version. Should be resolved fully in a few days, but will take some time for issues on pydantic's side to get figured out
