### ISSUE TITLE
[Question]: Query engine returns 'empty response' from pinecone

### ISSUE THREAD

**Issue by kxu-prosera** [run-llama/llama_index#17019]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been searching and scratching my head more than a week.

Scenario:

Having markdown and text files stored to pinecone, and would like to read those vectors from pinecone in the future.

Issues:

The markdown files and text files are vectorized and stored to pinecone successfully, but when I retrieve them back as query. It shows empty response.

Code:

Setting up connection.

```python
pc = Pinecone(api_key=PINECONE_API_KEY)

pc.create_index(
        name = 'index-data',
        dimension = 1536,
        metric = 'cosine',
        spec = ServerlessSpec(
            cloud = 'aws',
            region = AWS_REGION_NAME,
        )
    )

pc_index = pc.Index('index-data')
``` 

There are multiple files stored as individual namespaces.

```python
                namespace = file_name.rsplit('.', 1)[0]
                reader = SimpleDirectoryReader(input_files=[file_path])
                documents = reader.load_data()
                parser = SimpleNodeParser()
                nodes = parser.get_nodes_from_documents(documents)
                vector_store = PineconeVectorStore(pinecone_index=pc_index, namespace=namespace)
                storage_context = StorageContext.from_defaults(vector_store=vector_store)
                index = VectorStoreIndex(nodes, service_context=Settings, storage_context=storage_context)
``` 

This is code loading vectors from pinecone.

```python
vector_store = PineconeVectorStore(pinecone_index=pc_index)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_vector_store(vector_store, service_context = Settings, storage_context=storage_context, embedding_model=Settings.embed_model)

``` 

This shows all files are vectorized and stored to pinecone.

```python
{'dimension': 1536,
 'index_fullness': 0.0,
 'namespaces': {'A': {'vector_count': 193},
                'B': {'vector_count': 42},
                'C': {'vector_count': 82},},
 'total_vector_count': 361}
``` 

This is query retriever, which shows empty response.

```python
user_prompt = "what is acoustic"
query_engine = index.as_query_engine()
init_response = query_engine.query(user_prompt)
result_str = str(init_response)
print (result_str)
``` 
 --> Empty Response

Question:

How can I vectorize file and store to the pinecone? 
How can I retrieve vectors from pinecone?
What is the best way to write prompt query?

Thanks

**Comment by logan-markewich** [comment]
This looks correct to me. But note that pinecone serverless takes like a minute or more  between indexing and querying before you can use it

**Comment by kxu-prosera** [comment]
Thank you for commenting. I just wonder if there are anything I did wrongly?

I am able to see the vectors in the pinecone, but the issue is that I can not retrieve anything from query prompt.

To echo your point, I did wait for long time.

Any other potential issues we can think about?

**Comment by logan-markewich** [comment]
Hmm, probably unrelated maybe, but `service_context=Settings` is not correct. Either set the models on the settings directly, or pass in the models directly
```
VectorStoreIndex(...  embed_model=embed_model)
...
index.as_query_engine(.., llm=llm)
```

Also, you probably shouldn't pass the storage context into `from_vector_store`

**Comment by kxu-prosera** [comment]
Let me modify and give a shot of those two places.

Just for your reference. Here are settings.

```python
Settings.llm = llm_model
Settings.embed_model = embed_model
Settings.chunk_size = 512
```

**Comment by kxu-prosera** [comment]
Hummm no lucky.

However, just some reference here. I am able to retrieve response back, if I use llamaindex in-memory vectoring storage -- load_index_from_storage.

Here is the code.

```python
if not os.path.exists(PERSIS_DIR):
    #create the new index
    reader = SimpleDirectoryReader(input_dir=input_directory, recursive=True)
    documents = reader.load_data()
    parser = SimpleNodeParser()
    nodes = parser.get_nodes_from_documents(documents)
    Settings.llm = llm_model
    Settings.embed_model = embed_model
    Settings.chunk_size = 512
    storage_context = StorageContext.from_defaults()
    index = VectorStoreIndex(nodes, service_context = Settings, storage_context=storage_context)
    index.storage_context.persist(persist_dir=PERSIS_DIR)
else:
    Settings.llm = llm_model
    Settings.embed_model = embed_model
    Settings.chunk_size = 512
    storage_context = StorageContext.from_defaults(persist_dir=PERSIS_DIR)
    index = load_index_from_storage(service_context = Settings, storage_context=storage_context)

```

**Comment by kxu-prosera** [comment]
@docu
