### ISSUE TITLE
[Bug]: tool_choice added twice for openai structured output for pydantic_program_mode=PydanticProgramMode.OPENAI

### ISSUE THREAD

**Issue by xucian** [run-llama/llama_index#17050]
### Bug Description

for openai structured output I get:

> llama_index.llms.openai.base.OpenAI.achat() got multiple values for keyword argument 'tool_choice'

--
call is inside llamaindex files:
```Python
        chat_response = await self._llm.achat(
            messages=messages,
            tools=[openai_fn_spec],
            tool_choice=self._tool_choice,
            **llm_kwargs,
        )
```

--

I don't understand why, but  tool_choice=self._tool_choice and **llm_kwargs both have the tool_choice arg
first (source self._tool_choice) has: {'function': {'name': '[my-pydantic-class-REDACTED]'}, 'type': 'function'}
second has (contents of llm_kwargs): {'tool_choice': 'required'}

openai's base OpenAI class from llamaindex has this:
```Python
    @dispatcher.span
    async def astructured_predict(
        self, *args: Any, llm_kwargs: Optional[Dict[str, Any]] = None, **kwargs: Any
    ) -> BaseModel:
        """Structured predict."""
        llm_kwargs = llm_kwargs or {}
        llm_kwargs["tool_choice"] = (
            "required" if "tool_choice" not in llm_kwargs else llm_kwargs["tool_choice"]
        )
        # by default structured prediction uses function calling to extract structured outputs
        # here we force tool_choice to be required
        return await super().astructured_predict(*args, llm_kwargs=llm_kwargs, **kwargs)
```

this is how I'm constructing the OpenAI llm:
```Python
        self.llm = OpenAI(
            model=self.persona.meta.llm_model,
            temperature=temperature,
            max_tokens=max_output_tokens,
            api_key=OpenAiPersonaLlm.TOKEN,
            # timeout=300
            timeout=60,
            # This is important to use openai's native structured output
            # pydantic_program_mode=PydanticProgramMode.DEFAULT,
            pydantic_program_mode=PydanticProgramMode.OPENAI,
        )
```

I'm calling as `llm.astructured_predict([pydantic class REDACTED], PromptTemplate(prompt))`

it seems the openai'd base class on structured outputs blindly adds the tool_choice instead of checking if next components downstream will add the more specific tool_choice

the reason I'm passing pydantic_program_mode=PydanticProgramMode.OPENAI is because I debugged the calls and it seems that you guys don't use openai's built-in json mode on structured predict, which is weird for me. I mean, I'd expect to get the best possible quality by default when calling structured predict (which I assume pydantic_program_mode=PydanticProgramMode.OPENAI achieves?), as if I'd call the API's 'natively', otherwise these wrappers are nothing but empty shells

### Version

0.11.21

### Steps to Reproduce

see description

**Comment by logan-markewich** [comment]
That's fair. As a work around, set the mode to function calling, its essentially the same thing

**Comment by xucian** [comment]
also, the reason I'm exploring this is I want to make sure I'm properly using openai's json mode (or whatever they're calling it). because I'm sometimes getting a string instead of a structured output, even though their api guarantees that you'll get a json except if a moderation filter is triggered and llm refuses to answer, and here it shouldn't be the case (it happens pretty often, like in 30% of cases). 
is there a mismatch between what llamaindex calls and the lastest openai structured output "mode"?

**Comment by logan-markewich** [comment]
@xucian FunctionCallingProgram was introduced later on. As more LLMs support function calling than just openai, the `FunctionCallingLLM` base class was introduced. It uses the function calling API specific to the llm being used. In this case, the same as the openai program for openai.

OpenAI has a "strict" mode, but it only works for a subset of json/tool schemas. You can activate it with `OpenAI(..., strict=True)`

Feel free to check out the docs page for the various ways to get structured outputs out of an llm
https://docs.llamaindex.ai/en/stable/understanding/extraction/
