### ISSUE TITLE
[Question]: Installation Issue with OpenAILike in llama_index Version 0.10 and Later

### ISSUE THREAD

**Issue by OKC13** [run-llama/llama_index#17053]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

It seems that OpenAILike from llama_index.core.openai_like is no longer valid in version 0.10 and later. How should I install it in newer versions?

**Comment by logan-markewich** [comment]
@OKC13 in v0.10.x and onwards, every integration is a package.

In this case

```
pip install llama-index-llms-openai-like
```

```
from llama_index.llms.openai_like import OpenAILike
```

You can see all integrations on llamahub
https://llamahub.ai/
