### ISSUE TITLE
[Documentation]: Sambanova Integration Issues: Package Names Mismatch and Import Errors

### ISSUE THREAD

**Issue by hherpa** [run-llama/llama_index#17084]
### Documentation Issue Description

# Reliability of llama-index Out of the Box

## Import Error №1

* [GitHub Issue](https://github.com/run-llama/llama_index/issues/16774)

At one point, a simple line of code like `from llama_index.llms.fireworks import Fireworks` could result in three errors simultaneously:

1. `cannot import name 'global_handler' from 'llama_index.core'`
2. `ImportError: cannot import name 'Secret' from 'pydantic'`
3. `ValueError: Did not find api_key, please add an environment variable FIREWORKS_API_KEY which contains it, or pass api_key as a named parameter.`

## Cause

1. It turned out that the code in the documentation (on several pages) contained errors that had gone unnoticed.

## Fix

Thanks to @logan-markewich, a [PR](https://github.com/run-llama/llama_index/pull/16794) was released to address the issue.

---

## Import Error №2

* After successfully integrating Fireworks through llama-index into my project, I moved to a new LLM API provider—Sambanova. However, I encountered a `ModuleNotFoundError`, specifically:  
  `No module named 'llama_index.llms.sambanova'`

* [GitHub Issue](https://github.com/run-llama/llama_index/issues/16797)

## Cause

1. The `llama-index-llms-sambanova` package was published not by the official developers but by a third-party contributor.
2. During development, the package was accidentally renamed to `sambanova`.

## Fix

Thanks to @logan-markewich, a [PR](https://github.com/run-llama/llama_index/pull/16799) was released:

1. The package was renamed back to `llama-index-llms-sambanovacloud`.
2. The documentation was updated to reflect these changes.

---

## Import Error №3

For a long time, everything worked with the standard installation:  
`pip install llama-index "llama-index-llms-sambanovacloud>=0.3" sseclient-py`.  

I even managed to integrate SambanovaCloud through llama-index into my project, but over time, I began receiving numerous errors that I couldn't understand.  

After two weeks of searching for errors in my project (unaware the issue wasn't on my side), I finally left a comment on the open [issue](https://github.com/run-llama/llama_index/issues/16520).  

Upon revisiting the problem, I decided to check for documentation updates and found that the [previous page](https://docs.llamaindex.ai/en/stable/examples/llm/sambanova/) we had edited was removed.  

Instead, a new [page](https://docs.llamaindex.ai/en/latest/examples/llm/sambanovasystems/) appeared, as the package was renamed to `llama-index-llms-sambanovasystems`.

---

I don't understand why the package name changes so frequently, as this can cause significant issues for developers using it.  

Now this page needs to be edited again because the error persists:  
`No module named 'llama_index.llms.sambanovasystems'`  

This issue arises even after following the installations in the [documentation](https://docs.llamaindex.ai/en/latest/examples/llm/sambanovasystems/):

```bash
!pip install llama-index-llms-sambanovacloud
!pip install sseclient-py
```

or 

```bash
%pip install "llama-index-llms-sambanova"
%pip install sseclient-py
```

The documentation doesn't mention `pip install llama-index-llms-sambanovasystems`, and this package leads to another error:
`User Warning: Field "model_kwargs" in Samba Studio hack conflict with protected namespace "model_".`

Now we have three package names, none of which work:

1. llama-index-llms-sambanovacloud
2. llama-index-llms-sambanova
3. llama-index-llms-sambanovasystems

- [notebook №1](https://colab.research.google.com/drive/1RsH7x82-fKV-xq9V2H55akpMPksZkKTl?usp=sharing)
- [notebook №2](https://colab.research.google.com/drive/1yi_4bblmeLyZpdUYXNSI1TqPxPJBpTsH?usp=sharing)

## Conclusion

Over the past month, the following critical issues have been observed:

1. Basic integration with the Sambanova API via llama-index remains non-functional.  
2. Frequent package renaming (three different names) causes confusion and breaks backward compatibility.  
3. Documentation fails to keep up with changes.  
4. Significant time is spent debugging and creating issues instead of productive development.  

### Recommendations for the llama-index team:
- Stabilize package naming conventions.  
- Implement automated testing for examples in the documentation.  
- Improve the PR review process for changes affecting documentation. 

@logan-markewich 

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/llm/sambanovasystems/

**Comment by logan-markewich** [comment]
@hherpa regretably i did not want to change the package name either. But I'm also going to abide by the actual people who work at samba 
https://github.com/run-llama/llama_index/pull/16930#discussion_r1838863470

It's a newer package (and not used at all [1](https://pypistats.org/packages/llama-index-llms-sambanovacloud) [2](https://pypistats.org/packages/llama-index-llms-sambanovasystems)), so impact to a rename was minimal 

Your "error" about the pydantic fields is just a warning, it's benign but yes could be cleaned up. It does not effect usage.

Lately, I'll take a look at the import issue

**Comment by logan-markewich** [comment]
The import works fine for me
https://colab.research.google.com/drive/1As1dOmRaVdZBGYJOg6CvQ9qxaCgQ2hn0?usp=sharing

But try a fresh env, or removing all previous versions of the samba package first before continuing. 

Opening an issue shortly to clean up a few nits.

I'd love to have automated testing for examples, but thats not possible when everything relies on external systems, api keys, etc.

**Comment by hherpa** [comment]
> @hherpa regretably i did not want to change the package name either. But I'm also going to abide by the actual people who work at samba [#16930 (comment)](https://github.com/run-llama/llama_index/pull/16930#discussion_r1838863470)
> 
> It's a newer package (and not used at all [1](https://pypistats.org/packages/llama-index-llms-sambanovacloud) [2](https://pypistats.org/packages/llama-index-llms-sambanovasystems)), so impact to a rename was minimal
> 
> Your "error" about the pydantic fields is just a warning, it's benign but yes could be cleaned up. It does not effect usage.
> 
> Lately, I'll take a look at the import issue

Yes, you’re correct that 

```bash
pip install llama-index-llms-sambanovasystems
```

displays a warning at the end rather than an error—it seems I’ve been overworking myself 😅.

However, my point was different: the installation commands listed in the documentation were only:

```bash
!pip install llama-index-llms-sambanovacloud
!pip install sseclient-py
```

And:

```bash
%pip install "llama-index-llms-sambanova"
%pip install sseclient-py
```

These, in fact, lead to an error because the package has been renamed. That’s why I filed my issue as [Doc] rather than [Bug].

Thank you for the PR and responsiveness!
