### ISSUE TITLE
[Question]: How to use WikipediaToolSpec with local Ollama

### ISSUE THREAD

**Issue by evar18** [run-llama/llama_index#17096]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How do I use WikipediaToolSpec with local Ollama agent rather than OpenAI? The example on llama hub is as follows:
https://llamahub.ai/l/tools/llama-index-tools-wikipedia?from=all
```python
from llama_index.tools.wikipedia import WikipediaToolSpec
from llama_index.agent.openai import OpenAIAgent

tool_spec = WikipediaToolSpec()

agent = OpenAIAgent.from_tools(tool_spec.to_tool_list())

agent.chat("Who is Ben Afflecks spouse?")
```

And the code I wrote to attempt to use it with ollama running locally is as follows:
NOTE: I was able to get this working with TS Llama Index but strugging with Llama Index in python.
```python
from llama_index.tools.wikipedia import WikipediaToolSpec
from llama_index.llms.ollama import Ollama
from llama_index.core import Settings
from llama_index.agent.openai import OpenAIAgent
from llama_index.embeddings.huggingface import HuggingFaceEmbedding


Settings.llm = Ollama(
	model="gemma2:latest",
	temperature=0.1,
	config={
		"host": "http://ai.local:11434",
	}
)

Settings.embed_model = HuggingFaceEmbedding(
	model_name="BAAI/bge-small-en-v1.5"
);


tool_spec = WikipediaToolSpec()

agent = OpenAIAgent.from_tools(tool_spec.to_tool_list())


def handleQueryWikipedia(request):
	response = agent.chat("Who is Ben Afflecks spouse?")
	print(response)


```

When I run my code I get the following error:
```
Traceback (most recent call last):
  File "src/earn_server_python/src/handlers/wikipedia.py", line 23, in <module>
    agent = OpenAIAgent.from_tools(tool_spec.to_tool_list())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src/earn_server_python/.py-earn_server_python/lib64/python3.12/site-packages/llama_index/agent/openai/base.py", line 111, in from_tools
    raise ValueError("llm must be a OpenAI instance")
ValueError: llm must be a OpenAI instance

```

**Comment by evar18** [comment]
Hello Dosubot,

I tried the above but I'm unable to get it to work because Ollama does not
have the from_tools function.

Regards,
Eva Rose Nalesso.

**Comment by logan-markewich** [comment]
Use FunctionCallinAgent (if using a function calling llm from ollama like llama3.1), otherwise, use a react agent

Note that open source llms are pretty bad at being agents, so performance may vary

The two agents I listed have the same interface as the openai agent, just different imports 

```
from llama_index.core.agent import ReActAgent, FunctionCallingAgent

agent = ReActAgent.from_tools(tools, llm=llm, ...)
```

**Comment by evar18** [comment]
Hey @logan-markewich

Thanks for the above information! I was able to get it working with `llama3.1:latest"` and ReActAgent.

Thanks :)
