### ISSUE TITLE
[Question]: UndefinedTable Error When Using PGVectorStore with LlamaIndex

### ISSUE THREAD

**Issue by MananPatel13** [run-llama/llama_index#17094]
I encountered a `psycopg2.errors.UndefinedTable` error while attempting to store data using `PGVectorStore` in LlamaIndex. Below is the code I am using to set up the vector store and store data:  

**Code:**  

```python
from llamaindex import PGVectorStore, StorageContext, VectorStoreIndex

def get_vector_store(db: str, host: str, password: str, port: str, user: str, collection: str, isHybrid: bool) -> PGVectorStore:
    return PGVectorStore.from_params(
        database=db,
        host=host,
        password=password,
        port=port,
        user=user,
        table_name=collection,
        embed_dim=1536,  # OpenAI embedding dimension
        hybrid_search=isHybrid,
        text_search_config="english"
    )

def store_in_vector_db(text_nodes, vector_store, db):
    storage_context = StorageContext.from_defaults(vector_store=vector_store)
    index = VectorStoreIndex(
        text_nodes, storage_context=storage_context, show_progress=True
    )
    return True
```

When I call the `store_in_vector_db` function to store data, I receive the following error:  

```
(psycopg2.errors.UndefinedTable) relation "<table_name>" does not exist
```
Could Anyone please clarify if any additional setup is required for creating the table or if there are specific configurations I need to check?

**Edit:**
I suspect that this issue is related to [this commit](https://github.com/run-llama/llama_index/commit/8e5ad9f1ba338f0c83f2b6a50d18f4d40a3057d5). My code worked correctly before this commit, and I haven't made any changes to it.

**Comment by MananPatel13** [comment]
@logan-markewich Could you please take a look at this issue? If there’s anything incorrect or missing in my code, kindly let me know.

**Comment by IanGYan** [comment]
I found another table with prefix 'data_<table_name>' is created but not use the specific table name. BTW, perform_setup=true is necessary if you don't want to create table by hand.

I added: actual_table_name=f"data_{table_name}". And create the table by hand. It works.
