### ISSUE TITLE
[Bug]: New Anthropic tokenizer (PR #16909) breaks the Tokenizer protocol

### ISSUE THREAD

**Issue by Shura1oplot** [run-llama/llama_index#17115]
### Bug Description

This part of the code doesn't comply with Tokenizer protocol and breaks token counting logic.

```python
    @property
    def tokenizer(self) -> Tokenizer:
        def _count_tokens(text: str) -> int:
            return self._client.beta.messages.count_tokens(
                messages=[{"role": "user", "content": text}],
                model=self.model,
            ).input_tokens

        return _count_tokens
```

### Version

0.12.2

### Steps to Reproduce

The Tokenizer should be a class with the `encode` method which returns `List[int]`. The current implementation returns a callable object which returns an int (number of tokens, not a vector). It breaks `TokenCountingHandler` logic.

**Comment by logan-markewich** [comment]
This doesn't break anything AFAIK

The token counting handler takes a callable that takes in a string and returns a list
https://github.com/run-llama/llama_index/blob/7c6b1e01d5a4c740049fb8e908c7a0d852f0caab/llama-index-core/llama_index/core/callbacks/token_counting.py#L152

**Comment by logan-markewich** [comment]
Oh lol I see the issue, it returns an int instead of a string

This will require some change to the token counting handler

**Comment by jeffreyling** [comment]
Hi! Big fan of LlamaIndex and first time contributor. I made a PR here that addresses by returning a list of mock ints, PTAL: https://github.com/run-llama/llama_index/pull/17201
