### ISSUE TITLE
[Bug]: Authentication Error when Using PropertyGraphIndex with LlamaIndex

### ISSUE THREAD

**Issue by mahamatnoumai** [run-llama/llama_index#17124]
### Bug Description

I encountered the following error when trying to use the PropertyGraphIndex class in LlamaIndex:

`TypeError: "Could not resolve authentication method. Expected either api_key or auth_token to be set. Or for one of the `X-Api-Key` or `Authorization` headers to be explicitly omitted"`

This issue arises when attempting to initialize the PropertyGraphIndex with custom documents and an LLM model.

Below is how I calling the PropertyGraphIndex

I am using a custom embedding from Hugging face and tested and it works fine too. 

`from llama_index.embeddings.huggingface import HuggingFaceEmbedding
`
I am using claude antropic models for the LLM 

```
from llama_index.core import PropertyGraphIndex


index = PropertyGraphIndex.from_documents(
    documents,
    llm=model,
    embed_model=embed_model,
    show_progress=True,
)

```

Questions:
Do I need to provide an API key or auth_token specifically for LlamaIndex, or can it work with any LLM models without requiring a special LlamaIndex key?
If LlamaIndex requires its own API key, where can I obtain it, and how should I integrate it into my code to resolve the authentication error?

Any help or clarification would be greatly appreciated.

Thank you

**Comment by logan-markewich** [comment]
@mahamatnoumai without the traceback, its hard to know which component raised this error

Using ollama, i'm unable to reproduce. If you need to, you can also set global defaults with settings
```
from llama_index.core import Settings
Settings.llm = llm
Settings.embed_model = embed_model
```

**Comment by mahamatnoumai** [comment]
> @mahamatnoumai without the traceback, its hard to know which component raised this error
> 
> Using ollama, i'm unable to reproduce. If you need to, you can also set global defaults with settings
> 
> ```
> from llama_index.core import Settings
> Settings.llm = llm
> Settings.embed_model = embed_model
> ```

Hello 

Thanks for your answer 

I found a solutions here [https://github.com/run-llama/llama_index/issues/14060#issuecomment-2159624969](here)


Thank you
