### ISSUE TITLE
[Bug]: SentenceTransformerRerank does not have 'trust_remote_code' parameter, making it unable to load some models

### ISSUE THREAD

**Issue by Nau-git** [run-llama/llama_index#17131]
### Bug Description

I am trying to load jina reranker model (https://huggingface.co/jinaai/jina-reranker-v2-base-multilingual) but unable to do so due to 'trust_remote_code':
![image](https://github.com/user-attachments/assets/6d94e757-7388-4175-891e-852deef12eda)

'trust_remote_code' argument is not available in SentenceTransformerRerank class:
![image](https://github.com/user-attachments/assets/0c6f22f1-48b7-473d-9245-c5b9cc243535)

### Version

0.12.2

### Steps to Reproduce

from llama_index.core.indices.postprocessor import SentenceTransformerRerank
SentenceTransformerRerank(model="jinaai/jina-reranker-v2-base-multilingual", trust_remote_code=True)

**Comment by logan-markewich** [comment]
This has since been fixed
