### ISSUE TITLE
[Bug]: `UnstructuredReader` uses filename for `_id` and `doc_id`, which causes document ID collision

### ISSUE THREAD

**Issue by theta-lin** [run-llama/llama_index#17144]
### Bug Description

As shown here
https://github.com/run-llama/llama_index/blob/112d307505a44c5f7cf88089b23d4136686f58ec/llama-index-integrations/readers/llama-index-readers-file/llama_index/readers/file/unstructured/base.py#L203-L204
`UnstructuredReader` uses filename for `_id` and `doc_id` of the documents. This is problematic when loading files having the same filename but different path, such as `a/1.html` and `b/1.html`.

The impact of this bug can be observed when, for example, loading from a directory `d`, which contains subdirectories `d/a` and `d/b`, and the subdirectories contain the files `d/a/1.html` and `d/b/1.html`. Then, when passing the loaded documents to a `SentenceSplitter`, the resulting nodes will have the wrong metadata.

I think this can be easily avoided by using `str(uuid.uuid4())` as the IDs, which is done pretty everywhere else. I wonder why it is not used here.

### Version

llama-index==0.11.23; llama-index-readers-file==0.3.0

### Steps to Reproduce

Create a directory containing files with the same name, but residing in different subdirectories. Then set `input_dir` to this directory and run the following:

```python
from llama_index.core import SimpleDirectoryReader
from llama_index.readers.file import UnstructuredReader
from llama_index.core.node_parser import SentenceSplitter

reader = UnstructuredReader()
documents = SimpleDirectoryReader(
    # Your directory here
    input_dir=,
    recursive=True,
    file_extractor={
        ".htm": reader,
        ".html": reader,
    },
).load_data()

# Notice ID collision here
for doc in documents:
    print(doc.doc_id)

print()
print("*" * 10)
print()

splitter = SentenceSplitter()
nodes = splitter.get_nodes_from_documents(documents)

# Notice that some nodes will have the wrong `file_path`
for node in nodes:
    print(node.metadata["file_path"])
    print()
    print(node.text)
    print("---")

```

**Comment by logan-markewich** [comment]
This is to enable deduplication later on. Ideally instead of filename, it should just have the actual file path
