### ISSUE TITLE
[Question]: Questions About the Algorithm and Embeddings in TreeSummarize

### ISSUE THREAD

**Issue by LikhithRishi** [run-llama/llama_index#17146]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 have a few questions regarding the TreeSummarize functionality in llama-index:

Algorithm:
What specific algorithm or approach is being used in the TreeSummarize function? Is it based on a particular research paper or a custom implementation?

Embeddings:
Does the TreeSummarize functionality create embeddings during its process?
If yes, how can we store these embeddings for reuse in future summarizations or other related tasks?

Reference:
Could you please share any research papers, documentation, or references that explain the theoretical background or implementation details of the TreeSummarize functionality?

**Comment by logan-markewich** [comment]
Tree summarize doesn't use embeddings. It assumes you've already done retrieval and passed in some top-k (or maybe you just passed in all your text, thats fine too)

It just takes X number of text chunks, compacts them (i.e. putting as much text into each LLM call as possible) and recursively builds a tree summarizing each chunk from the bottom up. 

If you ignore the compact part, you can visualize it like

```python
         a_b_c_d
        /             \
     a_b         c_d       
   /       \        /      \
 a         b    c        d
```

Where each level in a tree is a summary of whats below it

Feel free to check out the source code
https://github.com/run-llama/llama_index/blob/1da8437ab8fd41eed3a4f11fe4e3bc6fe70cc13a/llama-index-core/llama_index/core/response_synthesizers/tree_summarize.py#L61

There's no reference for this really, its a common map-reduce pattern. This was among the first algorithms in the repo back in late 2022.
