### ISSUE TITLE
[Question]: Faiss Vector Store adding and updating new data

### ISSUE THREAD

**Issue by git-hamza** [run-llama/llama_index#17154]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using Faiss vector store and created it using the following code.

```python3
    embed_dim = 768
    faiss_index = faiss.IndexFlatL2(embed_dim)
    vector_store = FaissVectorStore(faiss_index=faiss_index)
    storage_context = StorageContext.from_defaults(
        vector_store=vector_store)

    index = VectorStoreIndex(
        nodes=all_nodes,
        storage_context=storage_context,
        use_async=True,
        show_progress=True,
        insert_batch_size=4096
    )
        index.storage_context.persist(
        persist_dir="index")
```

I have created the nodes manually and also assigned relationship between them.

Now what I want is how can I load this current indexes and  add, update and delete data from it and save it again.

I think right now the delete functionality is not support but how can I add data to it.

Currently, I am loading the index and extracting nodes from it and then recreating index but since the embedding is None, the code generated embeddings for all the data which is not very efficient.
Does Faiss not store the embeddings which can be looked into?

**Comment by logan-markewich** [comment]
FAISS does not support deleting. Otherwise though, dosu is correct

**Comment by git-hamza** [comment]
One more questions, since Faiss store embeddings and not the text. How can I access embeddings of each node from faiss vector store.
