### ISSUE TITLE
[Question]: Why do I get proxies error while trying to generate questions using RagDatasetGenerator?

### ISSUE THREAD

**Issue by SL2226799** [run-llama/llama_index#17190]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I get proxies error while trying to generate questions using RagDatasetGenerator

My code is 
`from llama_index.core.llama_dataset.generator import RagDatasetGenerator
from llama_index.core import SimpleDirectoryReader
from llama_index.readers.file import FlatReader

def get_metadata(filepath):
    return METADATA[filepath]

documents = SimpleDirectoryReader(
    input_files=local_files,
    file_metadata=get_metadata,
    file_extractor={'.md':FlatReader()}
)

docs = documents.load_data()

llm = OpenAI(api_key=openai.api_key, temperature=0.0)

eval_documents = docs[:5]

data_generator = RagDatasetGenerator.from_documents(
    documents=eval_documents,
    llm=llm,
    num_questions_per_chunk=40, 
    show_progress=True
)

eval_questions = data_generator.generate_questions_from_nodes()
print(eval_questions)`

The error I get is 
0%|          | 0/12 [00:00<?, ?it/s]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-30-1a4c8b0bde79>](https://localhost:8080/#) in <cell line: 12>()
     10 )
     11 # Generate questions
---> 12 eval_questions = data_generator.generate_questions_from_nodes()
     13 print(eval_questions)

46 frames
[/usr/local/lib/python3.10/dist-packages/openai/_base_client.py](https://localhost:8080/#) in __init__(self, **kwargs)
   1333         kwargs.setdefault("limits", DEFAULT_CONNECTION_LIMITS)
   1334         kwargs.setdefault("follow_redirects", True)
-> 1335         super().__init__(**kwargs)
   1336 
   1337 

TypeError: AsyncClient.__init__() got an unexpected keyword argument 'proxies'

**Comment by logan-markewich** [comment]
OpenAI broke their package, and google colab pre-installs a broken version of openai + httpx
https://github.com/openai/openai-python/issues/1902

Solution is just `pip install -U openai` -- will add some more specific deps to llama-index-core though
