### ISSUE TITLE
[Bug]: Validation errors for ChatMessage

### ISSUE THREAD

**Issue by haniehm** [run-llama/llama_index#17212]
### Bug Description

the code below used to work fine on Friday December 6th, however today, it is giving an unexpected error:

Environment detail:  
[packages.txt](https://github.com/user-attachments/files/18065658/packages.txt)

``` python
from llama_index.multi_modal_llms.openai import OpenAIMultiModal
from llama_index.core import SimpleDirectoryReader

# put your local directore here
image_documents = SimpleDirectoryReader("/content/drive/MyDrive/Omdena_Challenge/new_LK_tea_dataset/Guideline/with_Figure/images/").load_data()

openai_mm_llm = OpenAIMultiModal(
    model="gpt-4o", api_key=os.environ["OPENAI_API_KEY"], max_new_tokens=1500
)

response_1 = openai_mm_llm.complete(
    prompt="Describe the images as an alternative text",
    image_documents=image_documents,
)

print(response_1)

```

### Version

0.12.4

### Steps to Reproduce

 as an example, you can see it following your own tutorial: https://colab.research.google.com/github/run-llama/llama_index/blob/main/docs/docs/examples/multi_modal/gpt4v_multi_modal_retrieval.ipynb#scrollTo=4a8e3f9a

**Comment by logan-markewich** [comment]
Already working on it @haniehm, thanks
