### ISSUE TITLE
[Bug]: TypeError: Client.__init__() got an unexpected keyword argument 'proxies' (even for Groq)

### ISSUE THREAD

**Issue by haniehm** [run-llama/llama_index#17215]
### Bug Description

I assume due to aftermaths of this issue (https://community.openai.com/t/error-with-openai-1-56-0-client-init-got-an-unexpected-keyword-argument-proxies/1040332), parts of llamaindex implementations are affected as well. 

The shared code used to work flawlessly but recently it generates: 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-7cef20b284e1> in <cell line: 1>()
----> 1 response = query_engine.query(
      2     "What is title of this document?"
      3 )
      4 print(str(response))

/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py in wrapper(func, instance, args, kwargs)
    319 
    320             try:
--> 321                 result = func(*args, **kwargs)
    322                 if isinstance(result, asyncio.Future):
    323                     # If the result is a Future, wrap it

/usr/local/lib/python3.10/dist-packages/llama_index/core/base/base_query_engine.py in query(self, str_or_query_bundle)
     50             if isinstance(str_or_query_bundle, str):
     51                 str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 52             query_result = self._query(str_or_query_bundle)
     53         dispatcher.event(
     54             QueryEndEvent(query=str_or_query_bundle, response=query_result)

/usr/local/lib/python3.10/dist-packages/llama_index/core/instrumentation/dispatcher.py in wrapper(func, instance, args, kwargs)
    319 
    320             try:
...
--> 755         super().__init__(**kwargs)
    756 
    757 

TypeError: Client.__init__() got an unexpected keyword argument 'proxies'`

 ```python


from llama_index.llms.groq import Groq
from llama_index.core import SummaryIndex, VectorStoreIndex
from llama_index.embeddings.fastembed import FastEmbedEmbedding

# Set up the Groq class with the required model and API key
llm = Groq(model="llama3-70b-8192", api_key= os.environ['GROQ_API_KEY'], temperature=0.0)
embed_model = FastEmbedEmbedding(model_name="BAAI/bge-small-en-v1.5")



!pip install llama-index-embeddings-huggingface

from llama_index.embeddings.huggingface import HuggingFaceEmbedding # Import from the correct submodule
from llama_index.core import SummaryIndex, VectorStoreIndex
import os

# Use HuggingFaceEmbedding instead of FastEmbedEmbedding
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

summary_index = SummaryIndex(nodes)
vector_index = VectorStoreIndex(nodes, embed_model=embed_model) # Pass the embedding model to the VectorStoreIndex



#Pass the Groq LLM to the query engine
summary_query_engine = summary_index.as_query_engine(
    llm=llm, # Use Groq as the LLM
    response_mode="tree_summarize",
    use_async=True,
)
vector_query_engine = vector_index.as_query_engine(llm=llm,response_mode="refine") # Use Groq as the LLM

from llama_index.core.tools import QueryEngineTool


summary_tool = QueryEngineTool.from_defaults(
    query_engine=summary_query_engine,
    description=(
        "Useful for summarization questions related to a document"
    ),
)

vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description=(
        "Useful for retrieving specific context from a document."
    ),
)

from llama_index.core.query_engine.router_query_engine import RouterQueryEngine
from llama_index.core.selectors import LLMSingleSelector


query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(llm=llm), # Pass the Groq LLM to the selector
    query_engine_tools=[
        summary_tool,
        vector_tool,
    ],
    verbose=True,
    llm=llm # Explicitly set the llm parameter here
)

response = query_engine.query(
    "What is title of this document?"
)
print(str(response))
```

### Version

Version: 0.12.4

### Steps to Reproduce

```python


from llama_index.llms.groq import Groq
from llama_index.core import SummaryIndex, VectorStoreIndex
from llama_index.embeddings.fastembed import FastEmbedEmbedding

# Set up the Groq class with the required model and API key
llm = Groq(model="llama3-70b-8192", api_key= os.environ['GROQ_API_KEY'], temperature=0.0)
embed_model = FastEmbedEmbedding(model_name="BAAI/bge-small-en-v1.5")



!pip install llama-index-embeddings-huggingface

from llama_index.embeddings.huggingface import HuggingFaceEmbedding # Import from the correct submodule
from llama_index.core import SummaryIndex, VectorStoreIndex
import os

# Use HuggingFaceEmbedding instead of FastEmbedEmbedding
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")

summary_index = SummaryIndex(nodes)
vector_index = VectorStoreIndex(nodes, embed_model=embed_model) # Pass the embedding model to the VectorStoreIndex



#Pass the Groq LLM to the query engine
summary_query_engine = summary_index.as_query_engine(
    llm=llm, # Use Groq as the LLM
    response_mode="tree_summarize",
    use_async=True,
)
vector_query_engine = vector_index.as_query_engine(llm=llm,response_mode="refine") # Use Groq as the LLM

from llama_index.core.tools import QueryEngineTool


summary_tool = QueryEngineTool.from_defaults(
    query_engine=summary_query_engine,
    description=(
        "Useful for summarization questions related to a document"
    ),
)

vector_tool = QueryEngineTool.from_defaults(
    query_engine=vector_query_engine,
    description=(
        "Useful for retrieving specific context from a document."
    ),
)

from llama_index.core.query_engine.router_query_engine import RouterQueryEngine
from llama_index.core.selectors import LLMSingleSelector


query_engine = RouterQueryEngine(
    selector=LLMSingleSelector.from_defaults(llm=llm), # Pass the Groq LLM to the selector
    query_engine_tools=[
        summary_tool,
        vector_tool,
    ],
    verbose=True,
    llm=llm # Explicitly set the llm parameter here
)

response = query_engine.query(
    "What is title of this document?"
)
print(str(response))
```

**Comment by logan-markewich** [comment]
@haniehm this is a python openai issue. Install a newer version for now

`pip install -U openai`

**Comment by logan-markewich** [comment]
Will patch the openai llm class to not install these broken versions of their client soon

**Comment by haniehm** [comment]
> @haniehm this is a python openai issue. Install a newer version for now
> 
> `pip install -U openai`

Thanks for you help even with the upgrade of open ai, I get the below error. I assume it is due to LLMSingleSelector implementation. 
![image](https://github.com/user-attachments/assets/e40c179a-0216-477f-be65-ad25c52c7073)

**Comment by logan-markewich** [comment]
not related to LLMSingleSelector, but related to some ChatMessage refactors. Seems like openai's docs weren't 100% up to date, making some changes as well to address this

**Comment by haniehm** [comment]
> not related to LLMSingleSelector, but related to some ChatMessage refactors. Seems like openai's docs weren't 100% up to date, making some changes as well to address this

thank you!
