### ISSUE TITLE
[Bug]: Text Generation Inference Context Window Error

### ISSUE THREAD

**Issue by xlinzh** [run-llama/llama_index#17251]
### Bug Description

There are two problems:

- (1) When using `TextGenerationInference` LLM the **context window** will always be the default one (i.e. 3900) when using TGI >= 2.1.0 (I checked and from this version the /info endpoint does not return `max_input_length` but `max_input_tokens`.
  -  Look at the TGI repository code [v2.1.0](https://github.com/huggingface/text-generation-inference/blob/v2.1.0/router/src/server.rs#L1725) vs [v2.0.4](https://github.com/huggingface/text-generation-inference/blob/v2.0.4/router/src/server.rs#L1568).
  - TGI documentation says `max_input_length` is legacy [here](https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher#maxinputlength).
- (2) According to my assumption employing `max_input_length` (`max_input_tokens`) instead of `max_total_tokens` may be an error.
  - The `_get_available_context_size` function from the llama-index `PromptHelper` raises an error when it shouldn't (check in steps to reproduce). The function implementation is correct.

### Version

llama-index-core==0.12.0, llama-index-llms-huggingface==0.4.0, llama-index-llms-text-generation-inference==0.3.0, llama-index-embeddings-huggingface==0.4.0

### Steps to Reproduce

First, we launch a TGI instance with a model that supports >= 7800 context length. With the following settings:
- `max_input_tokens` = 3900
- `max_total_tokens` = 7800

We want to use half the context window for input tokens and the other halt for generation.

In my  case I get the following result when calling for /info:
![image](https://github.com/user-attachments/assets/0aecde20-47db-4821-99cd-29fe35b46435)

I'm executing TGI in the port 8000.

Then, we execute the following code:
```python
from llama_index.core import Settings, StorageContext, VectorStoreIndex
from llama_index.core.node_parser import SentenceSplitter
from llama_index.core.schema import Document
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.text_generation_inference import TextGenerationInference

Settings.embed_model = HuggingFaceEmbedding(
  model_name="BAAI/bge-small-en-v1.5"
)
Settings.llm = TextGenerationInference(
  "http://0.0.0.0:8000", 
  model_name="ModelCloud/Llama-3.2-3B-Instruct-gptqmodel-4bit-vortex-v3", 
  max_tokens=3900
) 
# Context window should be 7800. Below is the output of Settings.llm.metadata
# LLMMetadata(context_window=3900, num_output=3900, is_chat_model=True, is_function_calling_model=True, model_name='ModelCloud/Llama-3.2-1B-Instruct-gptqmodel-4bit-vortex-v2.5', system_role=<MessageRole.SYSTEM: 'system'>)

documents = [Document.example()]
parser = SentenceSplitter()
nodes = parser.get_nodes_from_documents(documents)
storage_context = StorageContext.from_defaults()
vector_index = VectorStoreIndex(nodes, storage_context=storage_context)
query_engine = vector_index.as_query_engine()
query_engine.query("test") # <- error in PromptHelper
```

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/base/base_query_engine.py", line 52, in query
    query_result = self._query(str_or_query_bundle)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/query_engine/retriever_query_engine.py", line 179, in _query
    response = self._response_synthesizer.synthesize(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/response_synthesizers/base.py", line 241, in synthesize
    response_str = self.get_response(
                   ^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 311, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/response_synthesizers/compact_and_refine.py", line 42, in get_response
    new_texts = self._make_compact_text_chunks(query_str, text_chunks)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/response_synthesizers/compact_and_refine.py", line 57, in _make_compact_text_chunks
    return self._prompt_helper.repack(max_prompt, text_chunks, llm=self._llm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/prompt_helper.py", line 292, in repack
    text_splitter = self.get_text_splitter_given_prompt(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/prompt_helper.py", line 247, in get_text_splitter_given_prompt
    chunk_size = self._get_available_chunk_size(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/prompt_helper.py", line 230, in _get_available_chunk_size
    available_context_size = self._get_available_context_size(num_prompt_tokens)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/llama_index/core/indices/prompt_helper.py", line 153, in _get_available_context_size
    raise ValueError(
ValueError: Calculated available context size -96 was not non-negative.
```

**Comment by logan-markewich** [comment]
@xlinzh Just to confirm, in our api
- context_window refers to the max input size
- max_tokens refers to the maximum output size

The context window is set with the function here
https://github.com/run-llama/llama_index/blob/ac21520eb153de24978d83aed7fef0353c06214b/llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/utils.py#L30

If this needs an update, I welcome a PR

**Comment by xlinzh** [comment]
Hi Logan, thanks for the fast response!

Yes! I'm doing a PR right now.

About what you are saying, the context_window should be max_total_tokens, right?

Like here
https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py#L243-L252
When setting up a local LLM the context_window is the max_position_embeddings, checking the TGI documentation the default `max_total_tokens` is indeed the max_position_embeddings of the model ("Default to min(max_position_embeddings, 4096)" [reference](https://huggingface.co/docs/text-generation-inference/basic_tutorials/launcher#maxtotaltokens)
