### ISSUE TITLE
[Bug]: Azure CosmosDB NoSQL indexing fails with TypeError: Object of type date is not JSON serializable

### ISSUE THREAD

**Issue by JeffreyEnglish** [run-llama/llama_index#17287]
### Bug Description

Uploading a text node to a Azure CosmosDB NoSQL vector store fails with the error:
`TypeError: Object of type date is not JSON serializable`

The same code using an Azure AI Search document store is successful. I'm using the version:
- llama-index-core==0.12.5
- llama-index-vector-stores-azureaisearch==0.2.1
- llama-index-vector-stores-azurecosmosnosql==1.2.0

### Version

0.12.5

### Steps to Reproduce

Common ingestion code
```
def index_nodes(nodes, embed_model, vector_store=None, show_progress=True, step_size=256):
    """Creates embeddings and an index from the loaded documents. Use the provided embedding model to generating embeddings.
    If the vector store already exists, the new documents will be added to this store without checking for duplicates.

    Args:
        documents (list[Document]): List of LlamaIndex documents
        embed_model (llama_index.embeddings): Embedding model, such as AzureOpenAIEmbedding
        vector_store (llamaindex.vector_store): Vector store to use for storing results. Defauls to None (local in-memory storage)
        show_progress (bool, optional): True will show a progress bar for generating embeddings. Defaults to True.

    Returns:
        VectorStoreIndex: An indexed vector store of the documents
    """
    steps = range(step_size, len(nodes), step_size)
    index = VectorStoreIndex(nodes[:step_size], 
                             show_progress=show_progress, 
                             vector_store=vector_store,
                             storage_context=StorageContext.from_defaults(vector_store=vector_store),
                             embed_model=embed_model)
    last_step = step_size
    for s in steps:
        index.insert_nodes(nodes[last_step:s], show_progress=show_progress)
        last_step = s
    index.insert_nodes(nodes[last_step:], show_progress=show_progress)
```

For CosmosDB Instance:
```index_id = "abcd1234"   
URI = azure_credentials["CosmosDB"]["URI"]   
KEY = azure_credentials["CosmosDB"]["Key"]  
client = CosmosClient(URI, credential=KEY)   
indexing_policy = {  
    "indexingMode": "consistent",  
    "includedPaths": [{"path": "/*"}],  
    "excludedPaths": [{"path": '/"_etag"/?'}],  
    "vectorIndexes": [{"path": "/embedding", "type": "diskANN"}],  
}  
vector_embedding_policy = {  
    "vectorEmbeddings": [  
        {  
            "path": "/embedding",  
            "dataType": "float32",  
            "distanceFunction": "cosine",  
            "dimensions": 3072, # 3072 for text-embedding-2-large  
        }  
    ]  
}  
full_text_policy = {  
    "defaultLanguage": "en-US",  
    "fullTextPaths": [   
        {  
            "path": "/text",  
            "language": "en-US"
        }
    ]
}
partition_key = PartitionKey(path="/id")
cosmos_container_properties_test = {"partition_key": partition_key}  
cosmos_database_properties_test = {}  
store = AzureCosmosDBNoSqlVectorSearch(  
    cosmos_client=client,  
    vector_embedding_policy=vector_embedding_policy,  
    indexing_policy=indexing_policy,  
    full_text_policy=full_text_policy,  
    cosmos_container_properties=cosmos_container_properties_test,  
    cosmos_database_properties=cosmos_database_properties_test,  
    create_container=True,  
    container_name=index_id  
)  
nodes = [TextNode(text='Hello World')]  
index_nodes(nodes, embed_model, vector_store=store, step_size=1)  
```

For AI Search code:

```
vector_store = AzureAISearchVectorStore(
        search_or_index_client=index_client,
        index_name=name,
        embedding_dimensionality=dimensionality,
        index_management=index_management,
        id_field_key="id",
        chunk_field_key="chunk",
        embedding_field_key="embedding",
        metadata_string_field_key="metadata",
        doc_id_field_key="doc_id",
        **vector_store_kwargs
    )
index_nodes(nodes, embed_model, vector_store=vector_store, step_size=1)
```

**Comment by JeffreyEnglish** [comment]
> The error `TypeError: Object of type date is not JSON serializable` occurs because the code attempts to insert a `date` object into the Azure CosmosDB NoSQL vector store, which requires data to be JSON serializable. In your code, the `add` method includes a line that sets a `timeStamp` field using `date.today()`, which is a `date` object. This is likely causing the issue.
> 
> To resolve this, you should convert the `date` object to a string or a `datetime` object, which is JSON serializable. You can modify the line to:
> 
> ```python
> "timeStamp": date.today().isoformat(),  # Converts the date to a string
> ```
> 
> This change will ensure that the `timeStamp` field is JSON serializable, preventing the `TypeError` [[1]](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosmongo/llama_index/vector_stores/azurecosmosmongo/base.py).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/a862f57d-46cb-4916-ae91-c16171b4a40a?feedback_type=other)

There is no "add" method in the code I provided. Could you specify which field needs to be converted?

**Comment by JeffreyEnglish** [comment]
@dosu There is no `timeStamp` field in `AzureCosmosDBNoSqlVectorSearch`

**Comment by JeffreyEnglish** [comment]
I was able to trace the error and dosubot was somewhere correct. In the file [llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py](https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/vector_stores/llama-index-vector-stores-azurecosmosnosql/llama_index/vector_stores/azurecosmosnosql/base.py) there is the offending code on lines 287-193

```
            entry = {
                self._id_key: node.node_id,
                self._embedding_key: node.get_embedding(),
                self._text_key: node.get_content(metadata_mode=MetadataMode.NONE) or "",
                self._metadata_key: metadata,
                "timeStamp": date.today(),
            }
```

Simply changing the "timeStamp" field to date.today().isoformat() resolves the issue. As does removing the timeStamp field entirely.

**Comment by logan-markewich** [comment]
@JeffreyEnglish thanks for debugging with dosu! I will review a PR once you open it
