### ISSUE TITLE
[Question]: Help with RAG and LlamaIndex Response Synthesis

### ISSUE THREAD

**Issue by lolapirespintopolarys** [run-llama/llama_index#17283]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello ! 

I’m working on a project where I have a **dataset of social media comments** (thousands of them) stored in a Qdrant vector database. I’m using a Retrieval-Augmented Generation (RAG) approach to answer data analysis questions. 

For each question, there might be hundreds of relevant comments (or very few). My goal is **to synthesize a coherent response from all the comments that answer a given question.**

I’ve explored the response modes in LlamaIndex and found options like compact or tree summarize, which seem potentially useful for my use case. Here’s what I’ve implemented so far:

```
response_synthesizer = get_response_synthesizer(response_mode="compact")
query_engine = index.as_query_engine(response_synthesizer=response_synthesizer)
response = query_engine.query(user_request)
```

However, I’ve noticed that the output automatically considers only two nodes per query. I would like it to select all nodes relevant to the query and synthesize a response from all of them. I’m not sure if I’m approaching this the right way.

Could you advise me on how to adapt this setup so it processes all relevant nodes for a question and generates a synthesized response effectively?

Thanks !

**Comment by logan-markewich** [comment]
Actually I just read dosu's answer, it's great
