### ISSUE TITLE
[Question]: Async with AgentCallback and OpenAIAgent

### ISSUE THREAD

**Issue by akabeera** [run-llama/llama_index#17339]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, 

I'm new to python asyncio so sorry if this is an obvious question.  I am attempting to make my python service async.  I hitting OpenAIAgent and I'm calling the `async achat(...)` method.

I also setup an custom callback manager which simply inherits from `CallbackManager` to track the progress of the agent by overriding `def on_event_start(...)` and `def on_event_end(...)` and storing some of the events in my DB.  

My DB updates is now async, so now I'm wondering if my setup will still work since the callback methods are not async.  I tried searching the docs of async version of `on_event_start` and `on_event_end`, if that made any sense.  Also trying looking at current github issues but didn't find anything.

my current setup:
```
class AgentCallbackManager(CallbackManager):
    def __init__(self, my_db_interface : DBInterface):
        super().__init__()
        self.events: Dict[str, Any] = dict()
        self.my_db_interface = my_db_interface 
        
        
def on_event_end(
        self,
        event_type: CBEventType,
        payload: Optional[Dict[str, Any]] = None,
        event_id: Optional[str] = None,
        **kwargs: Any,
    ) -> None:
    # ....... do some process.........
    self.my_db_interface.update_progress(....)
    return super().on_event_end(event_type=event_type, payload=payload, event_id=event_id, **kwargs)
```

I'd like to update the db update to be:

```
await self.my_db_interface.update_progress(....)
```

Which will require updating the on_event_end to async as well:

```
async def on_event_end(....)
```

But I'm not sure what implications this will have on the internal executing of the `achat(...)` call.

**Comment by akabeera** [comment]
@dosubot That answers my question about the internal implications of making the `on_event_end` async, I guess some followup questions I have now are:
1. Is there an async version of `CallbackManager`
2. Are there alternative ways I can track the progress of my OpenAIAgent?

**Comment by logan-markewich** [comment]
@akabeera I would re-implement the agent with a workflow
- async first
- no need to use callbacks
- way more customization opportunity 

There's a nice example of this here
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/

If you are new to workflows: https://docs.llamaindex.ai/en/stable/module_guides/workflow/#workflows

**Comment by akabeera** [comment]
Thanks @logan-markewich I was planning to look into workflows eventually.  Thought could do async changes then workflow changes in stages but it looks like doing it at the same time can resolve some of my async issues.

**Comment by logan-markewich** [comment]
Ah yea, that vector store doesn't have the async methods contributed. The nice thing about the workflow approach though, is you can force things to be async with `asyncio.to_thread`

So if the agent invokes a tool you know won't have proper async, its a decent work around

**Comment by akabeera** [comment]
I was also evaluating `asyncio.to_thread`, thanks for the confirmation.  I think I have all the information I need for this query.
