### ISSUE TITLE
[Question]: Why there's no InputEvent in workflows?

### ISSUE THREAD

**Issue by akabeera** [run-llama/llama_index#17350]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm trying to implement workflows following the guides here:
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/

and in the sample code, there's no import for `InputEvent` that's reference in `prepare_chat_history`

```

from typing import Any, List

from llama_index.core.llms.function_calling import FunctionCallingLLM
from llama_index.core.memory import ChatMemoryBuffer
from llama_index.core.tools.types import BaseTool
from llama_index.core.workflow import Workflow, StartEvent, StopEvent, step

async def prepare_chat_history(self, ev: StartEvent) -> InputEvent:
```

In the `llama_index.core.workflow` package, I noticed there is an `InputRequiredEvent`.  It this event supposed to replace InputEvent?

**Comment by logan-markewich** [comment]
@akabeera it's defined as a custom event in the notebook
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/#the-workflow-events

**Comment by akabeera** [comment]
I'm an idiot, I just realized the event class is at the beginning of the guide.  
https://docs.llamaindex.ai/en/stable/examples/workflow/function_calling_agent/#the-workflow-events
