### ISSUE TITLE
[Question]: how to customize the query sent to embedding query?

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#17370]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am using a VectorStoreIndex and its as_query_engine() to query my RAG.
There is a problem that the query I use is normally complex and is not good for embedding query. I wonder whether there is a way to firstly convert the original query to a condensed question to query embeddings, and finally combine the retrieved and original query to get the final answer.

**Comment by logan-markewich** [comment]
@justinzyw 

```
from llama_index.core.schema import QueryBundle

query_engine.query(QueryBundle(query_str="my query text", custom_embedding_strs=["some embedding string"]))
```

https://docs.llamaindex.ai/en/stable/api_reference/schema/#llama_index.core.schema.QueryBundle

**Comment by justinzyw** [comment]
@logan-markewich ，many thanks! I will give a try.

Here is another related suggestion regarding condensed mode of chat engine. I think it can generate more accurate response to user the original question:
![image](https://github.com/user-attachments/assets/76945f34-ab39-4c9f-a0b3-ec90d7c12ddd)

**Comment by justinzyw** [comment]
> @justinzyw
> 
> ```
> from llama_index.core.schema import QueryBundle
> 
> query_engine.query(QueryBundle(query_str="my query text", custom_embedding_strs=["some embedding string"]))
> ```
> 
> https://docs.llamaindex.ai/en/stable/api_reference/schema/#llama_index.core.schema.QueryBundle

works like a charm. closing

**Comment by justinzyw** [comment]
@dosu, I also noticed that the VectorStoreIndex 's query engine always return the node metadata (such as file_path and questions_this_excerpt_can_answer) which are further sent to llm for query. How can I exclude the metadata after retrieved from futther query to llm?

**Comment by justinzyw** [comment]
@dosu, I noticed that VectorIndexRetriever has a parm named filters (Optional[[MetadataFilters] which seems to be able to filter out "file_path" and "questions_this_excerpt_can_answer". Could you please help to check whether it works in my scenario? If yes, could you please provide me the sample code to exclude  "file_path" and "questions_this_excerpt_can_answer"?
