### ISSUE TITLE
I want to use Llama-index for document classification. How can I use multiple indexes with it?

### ISSUE THREAD

**Issue by AkshitChugh787** [run-llama/llama_index#1986]
Like I got two PDF files in different directories. I load them with the following:
`doc1 = SimpleDirectoryReader('file1').load_data()`
`doc2 = SimpleDirectoryReader('file2.').load_data()`

Then I created indexes for each:
`index1 = GPTTreeIndex.from_documents(doc1)`
`index2 = GPTTreeIndex.from_documents(doc2)`
`index1_summary = "<summary1>"`
`index1_summary = str(summary1)` 

> same done for index2

`all_indices = [index1, index2]`
`index_summaries = [index1_summary, index2_summary]`

`graph = ComposableGraph.from_indices(GPTTreeIndex, all_indices, index_summaries=index_summaries)`

`index = ComposableGraph.load_from_disk("graph.json")`
`query_configs = [
    {
        "index_struct_type": "simple_dict",
        "query_mode": "default",
        "query_kwargs": {
            "similarity_top_k": 3,
            "response_mode": "tree_summarize"
        }
    },
]`

`response = index.query(text, query_configs=query_configs)`

is this approach correct or do I have to make changes? Can this classify both the indexes and queries asked related to them?
Thanks!

**Comment by asadabbas09** [comment]
@AkshitChugh787 I have exactly the same question. Is this the right approach? Have you figured it out?
