### ISSUE TITLE
Possible to load a 4 bit quantized model ?

### ISSUE THREAD

**Issue by LucasBordanave** [run-llama/llama_index#3159]
I am a begginer in all that coding stuff and I am looking to run a 7B Llama model quantized in 4 bit with llama-index.

The thing is that I need to load the .pt file of it and it's been a few days now that I am completely lost with the multiple errors... 

This code is full of error and unuseful stuff that I can handle with. But I would like to know if some of you had run a 4 bit model with llama-idex, is that just possible ?

`class CustomLLM(LLM):
    tokenizer = LlamaTokenizer.from_pretrained("/home/lucas/AI/Model/LLaMA-HFv2")
    model = LlamaForCausalLM.from_pretrained("/home/lucas/AI/Model/LLaMA-HFv2")

    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)

        # only return newly generated tokens
        return response[prompt_length:]

    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": self.llm}

    @property
    def _llm_type(self) -> str:
        return "custom"`

**Comment by yingxiaolu** [comment]
I try to
```
    model = LlamaForCausalLM.from_pretrained(
        base_model,
        # load_in_8bit=load_8bit,
        load_in_4bit=True,
        # torch_dtype=torch.float16,
        device_map="auto",
    )
```
then Error： undefined symbol: cquantize_blockwise_fp16_fp4
