### ISSUE TITLE
Querying GPTPandasIndex is failing when requires to perform mathematical calculations on data

### ISSUE THREAD

**Issue by ghane100** [run-llama/llama_index#3241]
Using GPTPandasIndex I created an index on a dataset (pandas drataframes) which I loaded from a csv file. By initializing query engine on this index, I am asking a query that requires some mathematical calculations to do (internally) on DOB/Age column value and the program is failing with below error (in file pandas_query.py) :

----------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\Users\<User>\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\struct_store\pandas_query.py", line 58, in default_output_processor
    raise e
  File "c:\Users\<User>\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\indices\struct_store\pandas_query.py", line 56, in default_output_processor
    return str(eval(module_end_str, {}, local_vars))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'pd' is not defined

----------------------------------------------------------------------------

**Note:** This issue does exist from version in which "GPTPandasIndex" is introduced.

**Comment by himanshu-msft** [comment]
Hi, 
I am using the version "llama-index==0.8.20"
while using prompt which requires some calculation using pandas, it is giving me the error "NameError: name 'pd' is not defined"

**Comment by logan-markewich** [comment]
@himanshu-msft I think `pd` just has to be added on this line

https://github.com/jerryjliu/llama_index/blob/fe8ef6658a8b0fc64368ba84adad25afe86dc1c9/llama_index/query_engine/pandas_query_engine.py#L65

I can make the fix in a bit, but feel free to tackle it for easy PR points in the meantime!
