### ISSUE TITLE
GPTDocumentSummaryIndex query use Chinese has errors

### ISSUE THREAD

**Issue by wsf1990** [run-llama/llama_index#3258]
The latest llama-index version is: 0.6.5
When query use chinese it raise some errors,Such as:

1. invalid literal for int() with base 10: '相关度10'

2. list index out of range
```
print(retriever.retrieve('hi'))
  File "venv/lib/python3.10/site-packages/llama_index/indices/base_retriever.py", line 21, in retrieve
    return self._retrieve(str_or_query_bundle)
  File "venv/lib/python3.10/site-packages/llama_index/indices/document_summary/retrievers.py", line 128, in _retrieve
    raw_choices, relevances = self._parse_choice_select_answer_fn(
  File "venv/lib/python3.10/site-packages/llama_index/indices/document_summary/retrievers.py", line 69, in default_parse_choice_select_answer_fn
    answer_num = int(line_tokens[0].split(":")[1].strip())
IndexError: list index out of range
```

3. integer division or modulo by zero

Do I miss sth?
Thanks!

**Comment by mykytamykhailenko** [comment]
Actually, I encounter this kind of error quite a lot for the `GPTDocumentSummaryIndex` a lot.

```---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-21-b1cc05e6abbf>](https://localhost:8080/#) in <cell line: 1>()
----> 1 response = summaries[1].as_query_engine().query("""\
      2 You need to analyze customer reviews.
      3 Your goal is to recognize positive and negative aspects of the product.
      4 List all positive and negative aspects you have seen.
      5 Each positive or negative experience should be a separate line.

4 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/indices/query/base.py](https://localhost:8080/#) in query(self, str_or_query_bundle)
     21             if isinstance(str_or_query_bundle, str):
     22                 str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23             response = self._query(str_or_query_bundle)
     24             return response
     25 

[/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/retriever_query_engine.py](https://localhost:8080/#) in _query(self, query_bundle)
    138 
    139         retrieve_id = self.callback_manager.on_event_start(CBEventType.RETRIEVE)
--> 140         nodes = self._retriever.retrieve(query_bundle)
    141         self.callback_manager.on_event_end(
    142             CBEventType.RETRIEVE, payload={"nodes": nodes}, event_id=retrieve_id

[/usr/local/lib/python3.10/dist-packages/llama_index/indices/base_retriever.py](https://localhost:8080/#) in retrieve(self, str_or_query_bundle)
     19         if isinstance(str_or_query_bundle, str):
     20             str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 21         return self._retrieve(str_or_query_bundle)
     22 
     23     @abstractmethod

[/usr/local/lib/python3.10/dist-packages/llama_index/indices/document_summary/retrievers.py](https://localhost:8080/#) in _retrieve(self, query_bundle)
     79                 query_str=query_str,
     80             )
---> 81             raw_choices, relevances = self._parse_choice_select_answer_fn(
     82                 raw_response, len(summary_nodes)
     83             )

[/usr/local/lib/python3.10/dist-packages/llama_index/indices/utils.py](https://localhost:8080/#) in default_parse_choice_select_answer_fn(answer, num_choices, raise_error)
     98                     "answer_num: <int>, answer_relevance: <float>"
     99                 )
--> 100         answer_num = int(line_tokens[0].split(":")[1].strip())
    101         if answer_num > num_choices:
    102             continue

IndexError: list index out of range```

**Comment by wsf1990** [comment]
> Actually, I encounter this kind of error quite a lot for the `GPTDocumentSummaryIndex` a lot.
> 
> ```
> IndexError                                Traceback (most recent call last)
> [<ipython-input-21-b1cc05e6abbf>](https://localhost:8080/#) in <cell line: 1>()
> ----> 1 response = summaries[1].as_query_engine().query("""\
>       2 You need to analyze customer reviews.
>       3 Your goal is to recognize positive and negative aspects of the product.
>       4 List all positive and negative aspects you have seen.
>       5 Each positive or negative experience should be a separate line.
> 
> 4 frames
> [/usr/local/lib/python3.10/dist-packages/llama_index/indices/query/base.py](https://localhost:8080/#) in query(self, str_or_query_bundle)
>      21             if isinstance(str_or_query_bundle, str):
>      22                 str_or_query_bundle = QueryBundle(str_or_query_bundle)
> ---> 23             response = self._query(str_or_query_bundle)
>      24             return response
>      25 
> 
> [/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/retriever_query_engine.py](https://localhost:8080/#) in _query(self, query_bundle)
>     138 
>     139         retrieve_id = self.callback_manager.on_event_start(CBEventType.RETRIEVE)
> --> 140         nodes = self._retriever.retrieve(query_bundle)
>     141         self.callback_manager.on_event_end(
>     142             CBEventType.RETRIEVE, payload={"nodes": nodes}, event_id=retrieve_id
> 
> [/usr/local/lib/python3.10/dist-packages/llama_index/indices/base_retriever.py](https://localhost:8080/#) in retrieve(self, str_or_query_bundle)
>      19         if isinstance(str_or_query_bundle, str):
>      20             str_or_query_bundle = QueryBundle(str_or_query_bundle)
> ---> 21         return self._retrieve(str_or_query_bundle)
>      22 
>      23     @abstractmethod
> 
> [/usr/local/lib/python3.10/dist-packages/llama_index/indices/document_summary/retrievers.py](https://localhost:8080/#) in _retrieve(self, query_bundle)
>      79                 query_str=query_str,
>      80             )
> ---> 81             raw_choices, relevances = self._parse_choice_select_answer_fn(
>      82                 raw_response, len(summary_nodes)
>      83             )
> 
> [/usr/local/lib/python3.10/dist-packages/llama_index/indices/utils.py](https://localhost:8080/#) in default_parse_choice_select_answer_fn(answer, num_choices, raise_error)
>      98                     "answer_num: <int>, answer_relevance: <float>"
>      99                 )
> --> 100         answer_num = int(line_tokens[0].split(":")[1].strip())
>     101         if answer_num > num_choices:
>     102             continue
> 
> IndexError: list index out of range```
> ```

Yeah, I'm using `GPTDocumentSummaryIndex` too

**Comment by EvgenKrava** [comment]
The same problem!

**Comment by sheresaidon** [comment]
same problem

**Comment by Alone749-i** [comment]
Has this BUG been fixed?

**Comment by JPMoresmau** [comment]
I have the same issue using Llama2 chat model, doing exactly the same as in the Document Summary Index doc page. The code expects a formatted answer with answer index and relevance, and I seem to just get the actual LLM answer on each document.

**Comment by petersenjoern** [comment]
Same problem with DocumentSummaryIndex and Llama2 chat model.

**Comment by mohamednihal** [comment]
This issue is still there

**Comment by ray-008** [comment]
Consider custom parsing methods [parse_choice_select_answer_fn](https://github.com/run-llama/llama_index/issues/11093#issuecomment-1965737622)
