### ISSUE TITLE
 ValueError: invalid literal for int() with base 10: '$640'

### ISSUE THREAD

**Issue by nazkhan-8451** [run-llama/llama_index#3443]
From: https://github.com/jerryjliu/llama_index/blob/main/docs/examples/node_postprocessor/LLMReranker-Gatsby.ipynb

**Code**

```
new_nodes = get_retrieved_nodes(
    custom_query, vector_top_k=3, with_reranker=False
)

visualize_retrieved_nodes(new_nodes)
```

**Error**
```
ValueError                                Traceback (most recent call last)
<command-3433144466079443> in <module>
----> 1 new_nodes = get_retrieved_nodes(
      2     custom_query, vector_top_k=10, reranker_top_n=3, with_reranker=True
      3 )
      4 print(new_nodes)

<command-3433144466078678> in get_retrieved_nodes(query_str, vector_top_k, reranker_top_n, with_reranker)
     23         # configure reranker
     24         reranker = LLMRerank(choice_batch_size=5, top_n=reranker_top_n, service_context=service_context)
---> 25         retrieved_nodes = reranker.postprocess_nodes(retrieved_nodes, query_bundle)
     26 
     27     return retrieved_nodes

/local_disk0/.ephemeral_nfs/envs/pythonEnv-10da9aab-5927-4007-895d-ab2a25ffe5bd/lib/python3.8/site-packages/llama_index/indices/postprocessor/llm_rerank.py in postprocess_nodes(self, nodes, query_bundle)
     61             )
     62 
---> 63             raw_choices, relevances = self._parse_choice_select_answer_fn(
     64                 raw_response, len(nodes_batch)
     65             )

/local_disk0/.ephemeral_nfs/envs/pythonEnv-10da9aab-5927-4007-895d-ab2a25ffe5bd/lib/python3.8/site-packages/llama_index/indices/utils.py in default_parse_choice_select_answer_fn(answer, num_choices, raise_error)
     98                     "answer_num: <int>, answer_relevance: <float>"
     99                 )
--> 100         answer_num = int(line_tokens[0].split(":")[1].strip())
    101         if answer_num > num_choices:
    102             continue

ValueError: invalid literal for int() with base 10: '$60'
```

**Comment by AndrewJVRensburg** [comment]
Bump.

I'm using the LLMReRank as a second-step retriever, very similarly to your Gatsby notebook.
The use case is a query that can be answered with the Prompt(template_str), for example "What is your name". 

The reranker (correctly) returns no relevant documents and relevance, but cannot move further to the index.as_query_engine as :invalid literal for int() with base 10: 'None'"

**Some code:**

`llm_predictor_gpt3 = LLMPredictor(llm=OpenAI(temperature=0.1, model_name="gpt-3.5-turbo", openai_api_key=api_key,
                                             streaming=True))
service_context_gpt3 = ServiceContext.from_defaults(llm_predictor=llm_predictor_gpt3, chunk_size=512)


documents = SimpleDirectoryReader('Documents').load_data()

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context_gpt3)
index.storage_context.persist()

template_str = (
    "Pretend you are a AI Assistant and representative of [redacted] called AmChat."
    "We have provided the [redacted] policy information below. \n"
    "{context_str}"
    "\n----------------------------------------------\n"
    "Given this information and not prior knowledge, please answer the question received from a potential or existing client: {query_str}\n"
    "If the previous answer remains the same, repeat it verbatim. \n"
    "Never reference the new context or my previous query directly. \n"
    "Do not mention 'original answer'. \n"
    "If the query relates to premium or cost of a Product, you must include both the family and senior cost. \n"
    "Gap Supreme is not available for Seniors over the age of 65 \n"
    "If the query is eligbility of a child dependant, define all the eligibility requirements of being a child dependant. \n"
    "If the query relates to an upgrade of a product, make sure to mention which additional benefits will have a benefit waiting period. \n"
    "If the query requests information on if something is covered, list all products in which that benefit corresponds too. If the event is an exclusion, only respond with the exclusion. \n"
    "If you are unable to find the information within the context information, please only respond with: \n"
    "I apologize, but I am not certain. Kindly contact your Broker or Ambledown Financial Services for further assistance. \n"
)
qa_template = Prompt(template_str)

query_str = "Who are you?"
query_bundle = QueryBundle(query_str)

vector_top_k=10
reranker_top_n=3

# configure retriever
retriever = VectorIndexRetriever(
    index=index, 
    similarity_top_k=vector_top_k,
)
retrieved_nodes = retriever.retrieve(query_bundle)

# configure reranker
reranker = LLMRerank(choice_batch_size=5, top_n=reranker_top_n, service_context=service_context_gpt3)
retrieved_nodes = reranker.postprocess_nodes(retrieved_nodes, query_bundle)

query_engine = index.as_query_engine(
    similarity_top_k=10,
    node_postprocessors=[reranker],
    response_mode="compact",
    text_qa_template=qa_template,
    verbose=True
)
response = query_engine.query(query_str)`

**Error:**
`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 16
     14 # configure reranker
     15 reranker = LLMRerank(choice_batch_size=5, top_n=reranker_top_n, service_context=service_context_gpt3)
---> 16 retrieved_nodes = reranker.postprocess_nodes(retrieved_nodes, query_bundle)
     18 query_engine = index.as_query_engine(
     19     similarity_top_k=10,
     20     node_postprocessors=[reranker],
   (...)
     23     verbose=True
     24 )
     25 response = query_engine.query(query_str)

File [c:\Users\andrewj\Anaconda3\envs\gpt\Lib\site-packages\llama_index\indices\postprocessor\llm_rerank.py:63](file:///C:/Users/andrewj/Anaconda3/envs/gpt/Lib/site-packages/llama_index/indices/postprocessor/llm_rerank.py:63), in LLMRerank.postprocess_nodes(self, nodes, query_bundle)
     56 # call each batch independently
     57 raw_response, _ = self._service_context.llm_predictor.predict(
     58     self._choice_select_prompt,
     59     context_str=fmt_batch_str,
     60     query_str=query_str,
     61 )
---> 63 raw_choices, relevances = self._parse_choice_select_answer_fn(
     64     raw_response, len(nodes_batch)
     65 )
     66 choice_idxs = [int(choice) - 1 for choice in raw_choices]
...
--> 100 answer_num = int(line_tokens[0].split(":")[1].strip())
    101 if answer_num > num_choices:
    102     continue

ValueError: invalid literal for int() with base 10: 'None'`

**Comment by AndrewJVRensburg** [comment]
Bump.

I'm using the LLMReRank as a second-step retriever, very similarly to your Gatsby notebook.
The use case is a query that can be answered with the Prompt(template_str), for example "What is your name". 

The reranker (correctly) returns no relevant documents and relevance, but cannot move further to the index.as_query_engine as :invalid literal for int() with base 10: 'None'"

**Some code:**

```
llm_predictor_gpt3` = LLMPredictor(llm=OpenAI(temperature=0.1, model_name="gpt-3.5-turbo", openai_api_key=api_key,
                                             streaming=True))
service_context_gpt3 = ServiceContext.from_defaults(llm_predictor=llm_predictor_gpt3, chunk_size=512)


documents = SimpleDirectoryReader('Documents').load_data()

index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context_gpt3)
index.storage_context.persist()

template_str = (
    "Pretend you are a AI Assistant and representative of [redacted] called AmChat."
    "We have provided the [redacted] policy information below. \n"
    "{context_str}"
    "\n----------------------------------------------\n"
    "Given this information and not prior knowledge, please answer the question received from a potential or existing client: {query_str}\n"
    "If the previous answer remains the same, repeat it verbatim. \n"
    "Never reference the new context or my previous query directly. \n"
    "Do not mention 'original answer'. \n"
    "If the query relates to premium or cost of a Product, you must include both the family and senior cost. \n"
    "Gap Supreme is not available for Seniors over the age of 65 \n"
    "If the query is eligbility of a child dependant, define all the eligibility requirements of being a child dependant. \n"
    "If the query relates to an upgrade of a product, make sure to mention which additional benefits will have a benefit waiting period. \n"
    "If the query requests information on if something is covered, list all products in which that benefit corresponds too. If the event is an exclusion, only respond with the exclusion. \n"
    "If you are unable to find the information within the context information, please only respond with: \n"
    "I apologize, but I am not certain. Kindly contact your Broker or Ambledown Financial Services for further assistance. \n"
)
qa_template = Prompt(template_str)

query_str = "Who are you?"
query_bundle = QueryBundle(query_str)

vector_top_k=10
reranker_top_n=3

# configure retriever
retriever = VectorIndexRetriever(
    index=index, 
    similarity_top_k=vector_top_k,
)
retrieved_nodes = retriever.retrieve(query_bundle)

# configure reranker
reranker = LLMRerank(choice_batch_size=5, top_n=reranker_top_n, service_context=service_context_gpt3)
retrieved_nodes = reranker.postprocess_nodes(retrieved_nodes, query_bundle)

query_engine = index.as_query_engine(
    similarity_top_k=10,
    node_postprocessors=[reranker],
    response_mode="compact",
    text_qa_template=qa_template,
    verbose=True
)
response = query_engine.query(query_str)
```
**Error:**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[21], line 16
     14 # configure reranker
     15 reranker = LLMRerank(choice_batch_size=5, top_n=reranker_top_n, service_context=service_context_gpt3)
---> 16 retrieved_nodes = reranker.postprocess_nodes(retrieved_nodes, query_bundle)
     18 query_engine = index.as_query_engine(
     19     similarity_top_k=10,
     20     node_postprocessors=[reranker],
   (...)
     23     verbose=True
     24 )
     25 response = query_engine.query(query_str)

File [c:\Users\andrewj\Anaconda3\envs\gpt\Lib\site-packages\llama_index\indices\postprocessor\llm_rerank.py:63](file:///C:/Users/andrewj/Anaconda3/envs/gpt/Lib/site-packages/llama_index/indices/postprocessor/llm_rerank.py:63), in LLMRerank.postprocess_nodes(self, nodes, query_bundle)
     56 # call each batch independently
     57 raw_response, _ = self._service_context.llm_predictor.predict(
     58     self._choice_select_prompt,
     59     context_str=fmt_batch_str,
     60     query_str=query_str,
     61 )
---> 63 raw_choices, relevances = self._parse_choice_select_answer_fn(
     64     raw_response, len(nodes_batch)
     65 )
     66 choice_idxs = [int(choice) - 1 for choice in raw_choices]
...
--> 100 answer_num = int(line_tokens[0].split(":")[1].strip())
    101 if answer_num > num_choices:
    102     continue

ValueError: invalid literal for int() with base 10: 'None' 
```

**Comment by matthiaskern** [comment]
looks like `gpt-3.5-turbo` is not always consistently following the instructions. you can pass in a custom prompt to make it more robust for this model!

**Comment by AlbertoMQ** [comment]
This is still happening

**Comment by kumailkhan1** [comment]
Still happening with LLMRerank on Mistral7b being run locally using Ollama...
