### ISSUE TITLE
Request: allow multiple Langchain prompt template keys

### ISSUE THREAD

**Issue by tnunamak** [run-llama/llama_index#346]
As I understand it, [Langchain](https://langchain.readthedocs.io/en/latest/reference/modules/chains.html?highlight=LLMChain#langchain.chains.LLMChain) supports multiple prompt template keys.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1095217/215842038-740e4b33-5d07-403b-b1dd-31c662d9c78c.png">

When GPT-Index is used for memory, this is reduced to one:

https://github.com/jerryjliu/gpt_index/blob/f6a985241f388a9b7513ef5405025e6e2324e01e/gpt_index/langchain_helpers/memory_wrapper.py#L22

It would be useful if multiple prompt template keys and GPT-Index could be used together.

**Comment by noble-varghese** [comment]
Is this issue resolved ? If not is it possible for me to take this up. Let me know the status of the issue and I can take a look at it :)

**Comment by Vydruth** [comment]
@nerdai Wondering about the status for this issue. If it is not fixed yet. I am happy to take a look and contribute a fix.

**Comment by nerdai** [comment]
spoke with the team @Vydruth, and we don't believe its fixed yet. If you like to take this on please just mark it as "In Progress" and submit the PR whenever you're ready -- much thanks!

**Comment by Vydruth** [comment]
Thanks for checking @nerdai, understood. I am looking into this now. However, looks like I don't have the permissions to assign the issue to myself. Could you assign it to me please? 

Also, could anyone help me with some background: 

1. How to reproduce this issue running llama_index locally? (I've checkout the code and reviewed the  contributing.md file I am able to successfully run the `poetry install --with dev,docs` and `make test` locally)

2. Also, could you provide some context on the why the original code was copied from [langchain directly](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/utils.py)  and what is the expected behaviour of the code once the change is made

Thanks in advance, excited to get start here.

**Comment by Disiok** [comment]
Hey @Vydruth  thanks for offering to help! I just assigned the ticket to you!

**Comment by Vydruth** [comment]
@nerdai and @Disiok: Could one of you help me with how to reproduce the issue and test this change locally? I've made some changes based on the description provided and my understanding of the existing code. 

I placed the PR in `Draft` for now until I am able to reproduce and test my code thoroughly. Moreover the file `llama_index/langchain_helpers/memory_wrapper.py` does not have any unit tests to begin with. So running `make test` does not help. I can try to add unit tests for this file but that does not help with testing the correctness of the code. Want to make sure I test it correctly before publishing any changes.

**Comment by nerdai** [comment]
> @nerdai and @Disiok: Could one of you help me with how to reproduce the issue and test this change locally? I've made some changes based on the description provided and my understanding of the existing code.
> 
> I placed the PR in `Draft` for now until I am able to reproduce and test my code thoroughly. Moreover the file `llama_index/langchain_helpers/memory_wrapper.py` does not have any unit tests to begin with. So running `make test` does not help. I can try to add unit tests for this file but that does not help with testing the correctness of my code. Want to make sure I test it correctly before publishing any changes.

Hey @Vydruth, please do add unit relevant tests to our test suite for this if you can think of any. In terms of reproducing this issue, one way you can do this locally is to spin up a jupyter notebook running your current llama-index virtualenv (see [here](https://www.geeksforgeeks.org/using-jupyter-notebook-in-virtual-environment/) for how you can use a venv in a jupyter notebook). Another option is to write a script and just execute it in your command line terminal. Does this help?

**Comment by Vydruth** [comment]
Thanks @nerdai, I am adding unit tests  to the `memory_wrapper.py` file. Will get back if I have any other questions or concerns. Found a few other changes to make in the process. I will update code accordingly.

Thank you for the link to setup llama-index locally on virtualenv. I was able to set it up will test it out.
