### ISSUE TITLE
Google reader and Notion reader are not working

### ISSUE THREAD

**Issue by Ashish5869** [run-llama/llama_index#3777]
Google docs is working but google drive reader is not working 

```
from llama_index import download_loader

GoogleDriveReader = download_loader('GoogleDriveReader')

loader = GoogleDriveReader()
documents = loader.load_data(file_ids=['file_id'])

OUTPUT:
TypeError: GoogleDriveReader._load_from_file_ids() takes 2 positional arguments but 3 were given
```

Notion reader is also giving an error.

```
from llama_index import GPTListIndex, NotionPageReader
from IPython.display import Markdown, display
import os
integration_token = 'notion_integration_token'
page_ids = ["page_id"]
notion_reader = NotionPageReader(integration_token=integration_token)
documents = notion_reader.read_page(page_id=page_ids)

OUTPUT:
~/.local/lib/python3.10/site-packages/llama_index/readers/notion.py in _read_block(self, block_id, num_tabs)
     58             data = res.json()
     59 
---> 60             for result in data["results"]:
     61                 result_type = result["type"]
     62                 result_obj = result[result_type]

KeyError: 'results'
```
How to resolve this error?

**Comment by livelikeabel** [comment]
You can check this PR https://github.com/jerryjliu/llama_index/pull/6721

**Comment by livelikeabel** [comment]
1. Did you get token from here?
<img width="884" alt="image" src="https://github.com/jerryjliu/llama_index/assets/29794325/1de501de-8016-4a63-954c-5a874d6dfbb6">
2. Than you should `add connection` with your own token on your notion page
<img width="473" alt="image" src="https://github.com/jerryjliu/llama_index/assets/29794325/23102ef1-1927-4791-af20-ca9dc8d8c7cf">

**Comment by abhinav-adtechs** [comment]
After adding connection, still it doesn't work. Getting the same error.

> 

> KeyError                                  Traceback (most recent call last)
> Cell In[5], line 3
>       1 integration_token = os.getenv("NOTION_INTEGRATION_TOKEN")
>       2 page_ids = ["All-In-Capital-512240051c104b048b3f768c71a2709b"]
> ----> 3 documents = NotionPageReader(integration_token=integration_token).load_data(
>       4     page_ids=page_ids
>       5 )
> 
> File [/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:161](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:161), in NotionPageReader.load_data(self, page_ids, database_id)
>     159 else:
>     160     for page_id in page_ids:
> --> 161         page_text = self.read_page(page_id)
>     162         docs.append(Document(text=page_text, metadata={"page_id": page_id}))
>     164 return docs
> 
> File [/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:95](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:95), in NotionPageReader.read_page(self, page_id)
>      93 def read_page(self, page_id: str) -> str:
>      94     """Read a page."""
> ---> 95     return self._read_block(page_id)
> 
> File [/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:60](https://file+.vscode-resource.vscode-cdn.net/opt/homebrew/lib/python3.9/site-packages/llama_index/readers/notion.py:60), in NotionPageReader._read_block(self, block_id, num_tabs)
>      55 res = requests.request(
>      56     "GET", block_url, headers=self.headers, json=query_dict
>      57 )
> ...
> ---> 60 for result in data["results"]:
>      61     result_type = result["type"]
>      62     result_obj = result[result_type]
> 
> KeyError: 'results'

**Comment by Ashish5869** [comment]
@livelikeabel  After adding the connections. i am still getting the same error

**Comment by sidhartha-roy** [comment]
Adding the connection worked for me

**Comment by amindadgar** [comment]
I have the same problem but just for the `NotionPageReader`. Followed the instructions by "livelikeabel" but still getting the `KeyError: 'results'`. I did change the capabilities of the integration in notion setting but not working. @sidhartha-roy Could you specify which capabilities your integration had, that it worked for you?

**Comment by Rahmat711** [comment]
@livelikeabel can you please help how you solved the notion issue ?

**Comment by sebi5000** [comment]
Hi,
for me it worked after the steps above: adding the Connection. But one important hint: Only use the "hash" as page-id. In my example the page-id is exported as following:

https://www.notion.so/SuccessFactors-To-P-I-Loga-Replication-74c9b1046e614e78870b23f8f6b4df6d?pvs=4

So the page-id to set for the notion_loader is only "74c9b1046e614e78870b23f8f6b4df6d". I get the same error as you did, if I used it with Page Title included.

regards

**Comment by drewzeee** [comment]
Thank you @sebi5000. This got me functional.
