### ISSUE TITLE
The response take too long when get full response and get truncated when not

### ISSUE THREAD

**Issue by dinhan92** [run-llama/llama_index#3945]
I want to ask about llama_index, I use Vietnamese, the response take too long (about 30 seconds) when get full response and get truncated when not:

    from llama_index import SimpleDirectoryReader, ResponseSynthesizer, LangchainEmbedding, JSONReader, GPTListIndex, ServiceContext, GPTVectorStoreIndex, LLMPredictor, PromptHelper, SimpleMongoReader, StorageContext, load_index_from_storage
    from langchain.chat_models import ChatOpenAI
    import gradio as gr
    import sys
    import os
    from pymongo import MongoClient
    from llama_index.retrievers import VectorIndexRetriever
    from llama_index.query_engine import RetrieverQueryEngine
    from llama_index.indices.postprocessor import SimilarityPostprocessor
    from llama_index.llm_predictor.chatgpt import ChatGPTLLMPredictor
    
    os.environ["OPENAI_API_KEY"] = 'api-key'
    
    max_input_size = 4096
    num_outputs = 512
    max_chunk_overlap = 20
    chunk_size_limit = 600
    
    prompt_helper = PromptHelper(max_input_size, num_outputs, max_chunk_overlap, chunk_size_limit=chunk_size_limit)
    
    llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=num_outputs))
    
    service_context = ServiceContext.from_defaults(
            llm_predictor = llm_predictor,
            prompt_helper = prompt_helper)
    
    def construct_index(directory_path):
        documents = SimpleDirectoryReader(directory_path).load_data()
        index = GPTVectorStoreIndex.from_documents(documents, service_context=service_context)
    
        index.storage_context.persist(persist_dir='./storage')
    
        return index
    
    def chatbot(input_text):
        # rebuild storage context
        storage_context = StorageContext.from_defaults(persist_dir='./storage')
        
        # load index
        index = load_index_from_storage(storage_context = storage_context, 
        service_context = service_context)
    
        # configure retriever
        retriever = VectorIndexRetriever(
            index=index, 
            similarity_top_k=2,
        )
        
        # configure response synthesizer
        response_synthesizer = ResponseSynthesizer.from_args(
            node_postprocessors=[
                SimilarityPostprocessor(similarity_cutoff=0.7)
            ]
        )
        
        # assemble query engine
        query_engine = RetrieverQueryEngine(
            retriever=retriever,
            response_synthesizer=response_synthesizer,
        )
    
        fullResponse = ''
        while True:
            resp = query_engine.query(input_text + '\n\n' + fullResponse)
            if resp.response != "Empty Response":
                fullResponse += resp.response
            else:
                break
        return fullResponse
    
    iface = gr.Interface(fn=chatbot,
                         inputs=gr.components.Textbox(lines=7, label="Enter your text"),
                         outputs="text",
                         title="Custom-trained AI Chatbot")
    
    index = construct_index("docs")
    iface.launch(share=True)

I have tried to find some errors here, but with no result. When I try the old version of gpt_index (llama_index) (0.4.24), it runs fine, however, I also want to use with Mongo. Can someone help me with this? Thanks a lot!!!

**Comment by Disiok** [comment]
Hey curious, why are you doing the while loop to query multiple times? Is it just because the output gets truncated?

If so, I think the correct thing to do is to change the `num_outputs` to a higher value, so that output is not truncated.

**Comment by dinhan92** [comment]
Even I change the num_outputs, it still get truncated, it seems it was because of this: max_tokens=num_outputs and 
this: 
 # configure retriever
    retriever = VectorIndexRetriever(
        index=index, 
        similarity_top_k=2,
    )
    
    # configure response synthesizer
    response_synthesizer = ResponseSynthesizer.from_args(
        node_postprocessors=[
            SimilarityPostprocessor(similarity_cutoff=0.7)
        ]
    )
    
    # assemble query engine
    query_engine = RetrieverQueryEngine(
        retriever=retriever,
        response_synthesizer=response_synthesizer,
    )

**Comment by dinhan92** [comment]
Is there a way to set max tokens? I set it and the response get truncated

**Comment by dinhan92** [comment]
@Disiok I set the max token to 512 and it's still get truncated. I don't want the answer to have too many tokens.

**Comment by ahmed-bhs** [comment]
@dinhan92 any solution ?

**Comment by dinhan92** [comment]
@ahmed-bhs I just dont put in the max tokens...
