### ISSUE TITLE
[Bug]: Qdrant named vectors are not working

### ISSUE THREAD

**Issue by wodka** [run-llama/llama_index#6567]
### Bug Description

When named vectors are used, it must be defined where to do the distance search. If no vector name is passed, then a error is shown:

```
Wrong input: Default vector params are not specified in config
```

### Version

0.6.31

Qdrant as of version 0.10.0 has named vectors:
> Available as of v0.10.0
> If the collection was created with multiple vectors, each vector data can be provided using the vector’s name:

### Steps to Reproduce

1. Create a collection in qdrant
2. Add an entry with a vector name
3. use https://github.com/jerryjliu/llama_index/blob/48f5460b24e43ae1fe4540ce2fefa37ea6cc1c76/docs/examples/vector_stores/QdrantIndexDemo.ipynb to try to access the vector name

**Comment by logan-markewich** [comment]
Our vector store integrations are really mostly intended to be used with vector dbs created by llama index (I.e llama index was the one to insert vectors)

Working on improving this in the future, but for now it makes sense that this doesn't work

**Comment by wodka** [comment]
it would still be relevant, but makes sense that it is not a priority for llamaindex

**Comment by wodka** [comment]
it would still be relevant, but makes sense that it is not a priority for llamaindex

**Comment by wodka** [comment]
it would still be relevant, but makes sense that it is not a priority for llamaindex

... bots are becoming annoying - also a bit schizophrenic? 
![image](https://github.com/run-llama/llama_index/assets/385731/a3009f5f-4c3b-4012-86f6-2ffd966b1cd9)
