### ISSUE TITLE
LLM中文应用交流微信群

### ISSUE THREAD

**Issue by Anna10071** [run-llama/llama_index#6589]
LLM中文应用和技术交流群，如果二维码过期可加微信备注LLM应用：yydsa0007

![1acaa4cf83de26d556929f1f6ef94ca](https://github.com/jerryjliu/llama_index/assets/90118245/b96ae364-99ea-4aec-b14a-e5dfacdfb9ab)

**Comment by milely** [comment]
二维码过期了，可以再发一下吗，微信也添加不上

**Comment by bidada-bcr** [comment]
确实二维码过期了，麻烦重新发一下
