### ISSUE TITLE
[Feature Request]: Create MLFlow Callback handler

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6617]
### Feature Description

As an intermediate step to designing a robust callback system meant for tracing, logging, metrics collection in an async and concurrent setting, let's first implement more consumers of the callback system. 

MLFlow is a good first step.

Other candidates:
1. CometML
2. ClearML
3. `Evaluator`, a new component of `LlamaIndex` that provides various mechanisms for collecting human feedback on output quality

I will also attempt to better understand the requirements for callbacks, and perhaps think of more use-cases, outside of those mentioned.

**Comment by diego898** [comment]
Not sure why this issue was closed? Is this a "wont-implement" for llama-index?
