### ISSUE TITLE
[Feature Request]: Human-In-The-Loop Multistep Query

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6673]
### Feature Description

As a basic implementation of https://github.com/jerryjliu/llama_index/issues/6671, let's implement a simpler alternative requiring less engineering to work well - human in the loop multistep query.

Basic paradigm and rationale:
1. LLM response takes a long time >> network latency / button clicking
2. From UX perspective, humans like recommendations, but to retain control. Humans also do not like to wait for a long time for a process over which they have no control, especially when it goes awry.

This suggests query engine which prompts the user to select from competing query plans (if there is ambiguity) and to provide early feedback and corrections before a long, autonomous multi-step query is commited to.

See also: https://github.com/jerryjliu/llama_index/issues/6644 which requests more observability into query plan.

Implementation:
1. State is held somewhere for ongoing query. Similar to conversational buffer.
2. Execute based on follow up inputs.
3. Define clear action space and basic prompt engineering.

UI possibilities:
```python
Here is my proposed query plan.
[Continue, Edit Plan, Run All, Generate More Options]

I will now perform ___ step. 
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
```

More detailed example:
```python
"What are the number layoffs in 2023 for big tech companies compared with their total headcount?"

"Here is my proposed query plan."
"1. Search the web for number of layoffs in 2023 for big tech"
"2. Search the web for headcount in 2023 for big tech"
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> continue

Output: "I will now search the web for number of layoffs in 2023 for big tech"
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> continue

Output: "Here are the layoffs for big tech: ..."
"I will now search the web for headcount in 2023 for big tech" 
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> edit

Output: "I will now search the web for headcount in 2023 for the companies identified" 
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> continue

Output:
"""
Here is my subquery plan:
1. Generate query template for each entity in question.
2. Query [Websearch] for each entity in question
"""
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> edit query plan

"""
1. Query [Websearch] for number of layoffs in 2023 for big tech

If there are headcounts that cannot be determined:
1. Identify missing entities.
2. Generate query template over entities.
3. Query [Websearch] for the remainding entities in question
"""
[Continue, Edit Step, Run All, Generate More Options]
Advanced Options (Click to Expand): [Regenerate Remaining Plan, Edit Query Plan, Restart Query From Checkpoint]
-> run all

Output:
"""
-> Using [Web Search]: Here are the headcounts for big tech for 2023: Nvidia - ...
-> LLM eval: Here are the missing entities: Google, Amazon, Apple, ...
-> Using template generation. Template: "What was the headcount for {company_str} (company) in 2023?"
-> Applying template to the entities: ["Google", "Amazon", "Apple", "Salesforce", ...]
  -> Result from [Web Search]: "What was the headcount for Google (company) in 2023?"
  -> Result from [Web Search]: "What was the headcount for Amazon (company) in 2023?"
  ...
"""
```

### Caveats
1. Not sure if this is veering to far into the realm of chatbots. However, I think it is in the domain of LlamaIndex - which is to provide a query layer over unstructured data for conversational interface.
2. The particular UI above is extremely UI-specific.
3. Furthermore, there are many questions about UX that are unclear. Some of the advanced features (like editing query plan) may not be friendly in some cases. There should be some tiering of the features.
4. This is an "advanced" use-case that competes directly with proprietary tech for search etc perplexity, google, neeva, and also perhaps competing e.g. with Snowflake, Databricks, Elasticsearch - Enterprise search/data exploration use-case.

**Comment by jma7889** [comment]
This will be awesome! For debug mode, if metadata (e.g. which model is used, and its config, which query templates are used, etc.) can be included will be even better. Thank you!

**Comment by llermaly** [comment]
+1
