### ISSUE TITLE
Difference between vector store and index. 

### ISSUE THREAD

**Issue by pradeepdev-1995** [run-llama/llama_index#6700]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the difference between **vector store** and index in **llamaindex**. 
What is the basic conecpt behind this? Also, share the situations to use each over other.

vectore stores found at
```
llama_index.vector_stores
```
Indices found at
```
from llama_index.indices.vector_store
```

**Comment by logan-markewich** [comment]
An index is a way to structure your data (list, graph, vector store, etc.)

A vector store itself is just the place to store vector data. LlamaIndex supports a basic in-memory vector store by default, but there are also tons of integrations for vector dbs like weaviate and chroma etc. Basically, you'd usually use one of these when you are planning to index a LOT of data

**Comment by pradeepdev-1995** [comment]
@logan-markewich  So what is the exact difference between **vector store, vector db** and **index?**
suppose I need to store the unstructured data with embeddings(say pdf) then which method i should choose a vector store or a vector db or an index? and why?

my understanding is , if I have a small amount of data then, go with index, otherwise go with vector store. Is this correct?
And hope vector store and vector DBS are the same.
