### ISSUE TITLE
[Discussion]: Multi-threaded/multi-process scale-out

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6703]
### Feature Description

So far, we've discussed about async-compatibility. Even under the async scenario, we need to be careful about designing the tracing infra as tracing is known to put a high load on systems.

We also need to consider beyond single-threaded async concurrency. In the serving case, one is likely to have to use multiprocess due to python GIL. In this case, there are many in-memory structures that may benefit from being shared. For instance indices. 

In the serving case, it is likely that the index ought to be some kind of external service hosted on an external process. So this may not be a problem. 

So the open question is: in the high-load multi process scenario, what are the challenges that need to be anticipated, so that we can keep it in mind while designing some of the systems? 

To my mind, the best scenario is if llama-index serving is a simple logic layer with minimal statefulness that orchestrates other services (see e.g.  https://github.com/jerryjliu/llama_index/issues/6692). One should horizontally scale each process as though it were an isolated shard, without any cross-process communication.

**Comment by jma7889** [comment]
My intuition is llama-index shall not deal with scalability directly. That should be part of application architecture of the system that uses llama-index. lama-index shall give some guideline on its thread safety, process model, etc. that can help users to properly architect their own system.

**Comment by jon-chuang** [comment]
> That should be part of application architecture of the system that uses llama-index.

I am inclined to agree, but I think that the technology used will place restrictions on the application architecture. Due to Python's limitation of GIL, the single-node scale out is most likely in my opinion to be multiprocessed/containerized with no cross-shard communication (except control signal from orchestrator). We should design with the usage in mind, use that in a default serving layer. 

I am inclined to believe that a single user session for serving should never need to scale beyond a single process.

**Caveat:**
- single-process scale-out is not necessarily the right paradigm for other functionality like ingest. It should be investigated if large scale ingest is a valid use-case and whether independent processes writing to/reading from an external backing index will cause any issues

> lama-index shall give some guideline on its thread safety, process model, etc. that can help users to properly architect their own system.

Could you give an example of what you mean? How else might one implement scale out or what other application architecture may exist?

**Comment by jma7889** [comment]
My misunderstanding, thanks for clarification.

**Comment by MarcSkovMadsen** [comment]
To add to the context. There is something between the 

- single process and single process used for development
- highly scalable system deployed in individual docker containers.

That is the case where users want to deploy their Streamlit, Gradio, Panel etc. data apps. They are not experts in deployment or might not have access to scaling via docker containers on a Kubernetes cluster. For them its easiest to deploy on a single server or in a single docker container but applying threads and/ or processes.

Those kind of users will be very confused if the llama index classes are not thread safe.
