### ISSUE TITLE
[Feature Request]: retrieve all nodes who's similarity score is greater than some threshold

### ISSUE THREAD

**Issue by LytixDev** [run-llama/llama_index#6725]
### Feature Description

Functionality to retrieve all nodes who's similarity score is greater than some threshold. This could work in tandem with the similarity_top_k argument used in the Retriever classes. 

This feature would require some changes to the response synthesizer. The response synthesizer assumes there will always be context. This may not be the case if all nodes' scores are lower than the defined threshold. The solution I have come up with is just to have a fallback `text_qa_template` prompt that does not take in any context_str.

### Reason

You can sort of do this. You can set similarity_top_k to a large value and then manually filter out all nodes who's score is lower than some threshold. This is kind of janky though.

### Value of Feature

Say you have a chat bot. You retrieve the top k most similar nodes in the database, but at last, non of the nodes happened to be relevant. This will trip up the chat bot as it receives a lot of context that it has to ignore. You can get around this by good "prompt engineering", but ultimately you are wasting tokens by sending the context to the LLM.

Example:
I send "Hello" to the chat bot.
There may not be any relevant context, but since the response synthesizer must take in context, the most similar (yet very dissimilar) context that is not relevant must be submitted to the LLM request. This makes it difficult for the response of the chat bot to simply be "Hello, how can I help you?" (or something like that), as the chat bot gets confused by the context provided.

**Comment by LytixDev** [comment]
I am willing to implement this feature request if the authors/community want this 😄

**Comment by jon-chuang** [comment]
Could you produce pseudocode for the `SimpleVectorIndex`, and discuss possible implementations for other vector indices?
