### ISSUE TITLE
[Question]: how to get hypothethetical answer used in HyDE method in the response object?

### ISSUE THREAD

**Issue by sid8491** [run-llama/llama_index#6734]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to use HyDE query transform, and I need the intermediate hypothetical answer generated by the answer for embedding matching. How can I get that?

**Comment by devstein** [comment]
_[Answer generated by a 🤖](https://github.com/apps/dosu-beta)_

### Answer

To get the hypothetical answer generated by the HyDE method, you can use the `HyDEQueryTransform` object's `_run` method on the `QueryBundle` object. This will return a new `QueryBundle` object, which contains the hypothetical document used for embedding lookup. You can access this hypothetical document using the `custom_embedding_strs` attribute of the `QueryBundle` object. Here is the code snippet:
```python
hyde = HyDEQueryTransform(include_original=True)
query_bundle = QueryBundle(query_str=query_str)
new_query_bundle = hyde._run(query_bundle, extra_info={})
hyde_doc = new_query_bundle.custom_embedding_strs[0]
```
In this code, query_str is the query string you want to transform. The HyDEQueryTransform object hyde is used to transform the query string into a hypothetical document. The hypothetical document is then stored in hyde_doc.
This is demonstrated in the context provided:
```python
new_query_bundle = hyde._run(query_bundle, extra_info={})
hyde_doc = new_query_bundle.custom_embedding_strs[0]
```
```python
hyde_doc
```
> After graduating from the Rhode Island School of Design (RISD) in 1985, Paul Graham went on to pursue a career in computer programming. He worked as a software developer for several companies, including Viaweb, which he co-founded in 1995. Viaweb was eventually acquired by Yahoo in 1998, and Graham used the proceeds to become a venture capitalist. He founded Y Combinator in 2005, a startup accelerator that has helped launch over 2,000 companies, including Dropbox, Airbnb, and Reddit. Graham has also written several books on programming and startups, and he continues to be an active investor in the tech industry.

### Sources
- [docs/examples/query_transformations/HyDEQueryTransformDemo.ipynb](https://github.com/jerryjliu/llama_index/blob/-/docs/examples/query_transformations/HyDEQueryTransformDemo.ipynb)
- [llama_index/indices/query/query_transform/base.py](https://github.com/jerryjliu/llama_index/blob/-/llama_index/indices/query/query_transform/base.py)

---
This response is meant to be useful, save you time, and share context. It is **not meant to be a precise solution**, but rather a starting point for your own research.

Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
