### ISSUE TITLE
[Bug]: Updating/Refreshing documents not working correctly with supabase Vector Store

### ISSUE THREAD

**Issue by Daniel199438** [run-llama/llama_index#6735]
### Bug Description

When I retrieve documents from Notion pages via page ids,

`documents = reader.load_data(page_ids=page_ids)`

 each document gets a new unique id each time, 

    # TODO: A lot of backwards compatibility logic here, clean up
    id_: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique ID of the node.",
        alias="doc_id",
    )

 
    

but there is also a page id stored in the meta field. These documents are stored in a vector store (in my case Supabase) including the meta data.

`docs.append(Document(text=page_text, extra_info={"page_id": page_id}))`

Now when I get the same pages from Notion again on the next call, each document is stored with unique ids again. 

So I can't really update my Notion pages, but instead they are always reinserted into the vectorstore. 

![tmp_51](https://github.com/jerryjliu/llama_index/assets/16019073/05610f71-b3cf-4bf6-b108-454a33b3563d)

It would be enough for me if I could pass the page id as document id instead when creating the documents (I use a customized NotionPageReader) or if I could update a specific document via the meta field instead of the document id.

### Version

0.7.0

### Steps to Reproduce

1. Load a page from NotionPageReader
2. Process the page to a document and store it into vector database
3. Repeat it

**Comment by Disiok** [comment]
Thanks for surfacing this @Daniel199438! 

We should definitely improve this to make it more intuitive (I'd also expect the documents to be identified to be the same if they have the same page ID).

I wonder if a good solution here is just to have our default `NotionPageReader` set the doc id to `page_id`. 

cc @logan-markewich  do you see any concerns with this?

**Comment by Daniel199438** [comment]
@Disiok Thank you for your reply. 

I kept working on this issue and had instead searched for existing documents in the vector store by their respective page id in the metadata but yes, that could be a much simpler solution. 

But another issue I currently have is that I would like to use the refresh_documents method, which updates (deletes and re-adds if the document hash is different) existing documents and adds new ones. 

My problem is that the hash is not saved of the documents from the vectorstore. I've seen in the docs that there is the possibility to keep a document store with Redis or MongoDB, but does it make sense to have a document store next to a vector database? 
Couldn't you also store the hash as a metadata key and exclude the key for embedding and indexing?

I'm leaning towards just writing my own logic and running the insert_doc and update_doc functions myself. But if you have any tips, I would really appreciate it.

But anyway thank you for your help :)

**Comment by Disiok** [comment]
RE not saving hash in the vector store. This is mostly because we didn't implement a `get_by_id` interface for the vector stores, (and some of them don't support this). You are right that it's probably easiest to just store the hash in qdrant as well (in your case).

If you are interested in helping improving the library, would love to have better support on qdrant implemented!

**Comment by Daniel199438** [comment]
Hi @Disiok, yes sure, I would be happy to improve the library. I work with Supabase, but there is no "get_by_id" interface either. I'll take a closer look and try to implement one. I find the vec library a bit more complicated than e.g. the native Supabase library, but I'll have a look at the documentation and create a PR.
