### ISSUE TITLE
[Question]: how to set the temperature for local LLM

### ISSUE THREAD

**Issue by stl2015** [run-llama/llama_index#6746]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

For custom LLM using LLMPredictor to define index, is it possible to define the temperature in predicting? In definition of LLMPredictor, I only found following where it is possible in OpenAI interface? Thanks.

```
        self._llm = llm or OpenAI(
            temperature=0, model_name="text-davinci-003", max_tokens=-1
        )
```

**Comment by logan-markewich** [comment]
If you are using a custom LLM, how to set the temperature will be up to how you create the LLM right? What are you trying to use?

**Comment by stl2015** [comment]
It makes sense. I'm trying to make sure to have deterministic response for any prompt. For example, HuggingFaceLLMPredictor in llama-index has no option for temperature - it will give deterministic response, right? In my case I was trying to use a Vicuna model from HF.

**Comment by logan-markewich** [comment]
You have to set that in generate kwargs, since huggingface models have endless parameters to change they all go into generate kwargs 

`HuggingFaceLLMPredictor(..., generate_kwargs={"temperature": 0})`
