### ISSUE TITLE
[Feature Request]: Dynamically selecting from multiple prompts

### ISSUE THREAD

**Issue by 123zzw** [run-llama/llama_index#6748]
### Feature Description

Hello, I have an idea. Can we create a Dynamically selecting from multiple prompts based on the Retriever Router Query Engine for different problem types, such as

physics_template = """You are a very smart physics professor. \
You are great at answering questions about physics in a concise and easy to understand manner. \
When you don't know the answer to a question you admit that you don't know.
Here is a question:
{input}"""

math_template = """You are a very good mathematician. You are great at answering math questions. \
You are so good because you are able to break down hard problems into their component parts, \
answer the component parts, and then put them together to answer the broader question.
Here is a question:
{input}"""

**Comment by jon-chuang** [comment]
Could you explain what is the variable on which to dynamically select? Do you mean to simply control it manually from a top-level context, without building out two separate pipelines? 

I believe this feature is required to implement things like prompt auto-tuning (see: https://github.com/jerryjliu/llama_index/issues/6713) so stay tuned. I think that controlling prompts externally is definitely something we would want, including a yml-style config to make it easy to specify, with every prompt in the pipeline corresponding to some key.

**Comment by timbmg** [comment]
Is there a solution/workaround meanwhile for selecting prompt templates dynamically without having to define an engine per prompt?
