### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by sumanthp** [run-llama/llama_index#6754]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

What is the reason for milvus vector store to persist the data to local machine when the collections should be persisted in milvus?
Currently I am persisting the index/collection created in milvus to local storage. When I try to use milvus sdk methods to list collections, those are not available. Are there any alternatives for this

**Comment by sumanthp** [comment]
I am also facing issue when I try to load the milvus index persisted locally and try to load the index and query using that,
Error: Milvus instance is not available.
`selected_folder = st.selectbox("Select Index", folder_names)
            vector_store = MilvusVectorStore(collection_name=selected_folder,
                host='localhost',
                port=19530,
                overwrite=False
            )
            storage_context = StorageContext.from_defaults(vector_store=vector_store,persist_dir=f"{temp_dir}/{selected_folder}")
            index = load_index_from_storage(storage_context, service_context=service_context)
            query_engine = index.as_query_engine(response_mode='refine',storage_context=storage_context, service_context=service_context)
            query = st.text_input("Enter your query here:")
            if st.button("Search"):
                response = query_engine.query(query)
                st.write(response.response)`
                
                
![milvus_error](https://github.com/jerryjliu/llama_index/assets/11244510/934e8be0-d22c-434b-9e88-669125819982)

**Comment by logan-markewich** [comment]
You don't need to call persist when using milvus -- it will be automatically persisted in milvus for you

Usage Example
```python
from llama_index.vector_stores import MilvusVectorStore
from llama_index import VectorStoreIndex, SimpleDirectoryReader, StorageContext

documents = SimpleDirectoryReader("./data").load_data()

# you probably want to overwrite when first creating the index, just in case
vector_store = MilvusVectorStore(..., overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

# create the index
index = VectorStoreIndex.from_documents(documents, storage_context=storage_context)

# "load"/re-connect the index for later
# Now, we don't want to overwrite
vector_store = MilvusVectorStore(..., overwrite=False)

index = VectorStoreIndex.from_vector_store(vector_store)
```

**Comment by marvelliu** [comment]
> ```python
> vector_store
> ```

This is exactly what I need, unfortunately I have been looking for how to load the milvus database for weeks, but no result, even in the official pages of llama-index(https://docs.llamaindex.ai/en/stable/examples/vector_stores/MilvusIndexDemo/), this should be written down because vectors should be loaded from a database rather than from docments
