### ISSUE TITLE
[Feature Request]: Implement Hugging Face Embedding (local) model

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6802]
### Feature Description

There are many low-cost embeddings available on Hugging Face that are supposedly better than OpenAI's. 

In fact, it is a mystery to me why anyone would use OpenAI's embeddings.

For dense models, these are good defaults:
- [ ] https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2/tree/main
- [ ] https://huggingface.co/sentence-transformers/all-mpnet-base-v2/tree/main

I will use the latter as the local default 

If and when the [MTEB benchmark page](https://huggingface.co/spaces/mteb/leaderboard) loads, we can also try to see if there are any good models run locally that can handle long context lengths.

### References
- [langchain impl of hugging face embeddings](https://github.com/hwchase17/langchain/blob/560c4dfc98287da1bc0cfc1caebbe86d1e66a94d/langchain/embeddings/huggingface.py). Note that we should not use langchain impls for any defaults since we do not want it to be a default dependency. But we still need `sentence_transformers` installed.

**Comment by choltha** [comment]
Did anyone ever take a look at the quality of embeddings that can be generated by default llm models?
https://github.com/ggerganov/llama.cpp/tree/master/examples/embedding

**Comment by nerdai** [comment]
Closing this as there is `HuggingFaceEmbedding` now in the library for local HF embeddings.
