### ISSUE TITLE
[Feature Request]: Parallelize `MetadataExtractor`

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6803]
### Feature Description

Metadata extractor is single concurrency and very slow. 

Should we parallelize with new async APIs for node parser, or use sync parallelization approach (see: https://github.com/jerryjliu/llama_index/issues/6708)?

Please advise on which is the preferred route @jerryjliu @logan-markewich

**Comment by logan-markewich** [comment]
I think it makes sense have something similar to our other other async stuff (either adding "a" versions of functions or adding a use_async boolean)

**Comment by Whisht** [comment]
Is there any new progress on async `MetadataExtractor`? I noticed it is difficult for a user to custom an async `NodeParser`. Who must with multi-level overrides from `LLM.acomplete()`, `MetadataExtractor.extract`  to `parser.get_nodes_from_document`. An ideal parser could be parallel in multiple extractors and multiple queries for a single extractor.

**Comment by logan-markewich** [comment]
@Whisht no progress yet.

If you want to tackle it, we need to implement `aextract` on each metadata extractor, and add `aprocess_nodes` and `acall` to the `BaseExtractor` class

THEN we need to update the ingestion pipeline to parallelize across nodes in async. Preferably with a lock pool so we don't hit rate loots and limit the amount of running jobs.

Kind of a lot of work, haven't prioritized it yet

**Comment by Whisht** [comment]
@logan-markewich Thanks for your reply.
I am working on a minimal version of the parallel extractor with 'aiohttp request". But I am got stuck to the global shared
ClientSession" now. After browsing the source code of  [`openai-python' ](https://github.com/openai/openai-
python/blob/f7ccce126325ea35b65224ab954652c97a74896/openai/_init_py#L68), it leaves it to the user to maintain
this. So, if you do not manually do it, the results will be a new session for every single request. 

I have tried some methods, but there is either a connection error or an explicit assignment and close of `ClientSession`. Do you have any idea about how to achieve this for automatically managing the global session?

**Comment by Whisht** [comment]
I wrote a minimal custom [Async MetadataExtractor](https://github.com/Whisht/AsyncMetadataExtractor) with llama_index 0.8.59. Hope this will be helpful for you if you have the same problem.
