### ISSUE TITLE
[Question]:How can I speed up the pipeline?

### ISSUE THREAD

**Issue by wyzhhhh** [run-llama/llama_index#6817]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Every time I  use the pipline to load the local model ,it will take about 20 mins.How can i accelerate it .
Is it possible to speed up this process by calling multiple GPUs? How do I do that?
At the same time, it also takes a lot of time when generating answers to questions.
There are my codes below.

`model_name = "vicuna-chinese"
pipeline = pipeline("text-generation", model=model_name, device="cuda:1", model_kwargs={"torch_dtype": torch.bfloat16})

class CustomLLM(LLM):
    def _call(self, prompt: str, stop: Optional[List[str]] = None) -> str:
        prompt_length = len(prompt)
        response = pipeline(prompt, max_new_tokens=num_output,temperature=0)[0]["generated_text"]
        # only return newly generated tokens
        return response[prompt_length:]
    @property
    def _identifying_params(self) -> Mapping[str, Any]:
        return {"name_of_model": model_name}
    @property
    def _llm_type(self) -> str:
        return "custom"

llm_predictor = LLMPredictor(llm=CustomLLM())
from sentence_transformers import SentenceTransformer
from langchain.embeddings.huggingface import HuggingFaceEmbeddings
#embed_model= SentenceModel('./text2vec-base-chinese')
embed_model = LangchainEmbedding(HuggingFaceEmbeddings(model_name='./text2vec-base-chinese'))
#embed_model = SentenceTransformer("./text2vec-base-chinese")
prompt_helper = PromptHelper(
    context_window=4000,
    num_output=512,
    chunk_size_limit=512,
    chunk_overlap_ratio=0.1,
)
service_context = ServiceContext.from_defaults(
    llm_predictor=llm_predictor,
    embed_model=embed_model,
    prompt_helper=prompt_helper,
    chunk_size_limit=512
)

#new_index = VectorStoreIndex.from_documents(documents, service_context=service_context,)

from llama_index import SimpleDirectoryReader
documents = SimpleDirectoryReader('./data').load_data()

from llama_index.node_parser import SimpleNodeParser
parser = SimpleNodeParser()
nodes = parser.get_nodes_from_documents(documents)

from llama_index import GPTVectorStoreIndex,VectorStoreIndex
index = GPTVectorStoreIndex(nodes, service_context=service_context)
query_engine = index.as_query_engine()`

**Comment by jon-chuang** [comment]
To my understanding, local model is very slow.

**Comment by wyzhhhh** [comment]
> To my understanding, local model is very slow. There is nothing we can do about it. Recommended to use OpenAI APIs for now.
> 
> What is your GPU model?

I want to see how well the local model's answer works, and whether I can increase the pipeline loading speed or the model generation answer speed by calling multiple GPUs in parallel

My GPU model is A800

**Comment by jon-chuang** [comment]
It is not possible to call multiple GPUs unless you can shard the model using pytorch FSDP or Alpa or similar. You can check huggingface support for this. I also don't believe loading takes so long. Are you sure you were not just downloading the model? Perhaps try again and loading should be near instant.

**Comment by jon-chuang** [comment]
Perhaps try logging? I would guess that it is the generation.  

```python
import logging

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
```

What is the number of parameters? 13B?

**Comment by wyzhhhh** [comment]
> Perhaps try logging? I would guess that it is the generation.
> 
> ```python
> import logging
> 
> logging.basicConfig(stream=sys.stdout, level=logging.INFO)
> logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
> ```
> 
> What is the number of parameters? 13B?

yes it's 13B.
In addition to the long time, I also encountered another problem, the answer of the local model is '---', there is no text answer, is it related to setting the hyperparameters of the model,?how do I set the temperature of the model?

**Comment by jon-chuang** [comment]
This could be due to the tokenizer, we encountered similar issues when using Chinese tokenizer before. Could you try running the huggingface pipeline on a small prompt?

**Comment by jon-chuang** [comment]
If you can get the hugginface stats like tokens/s that would be nice as well

**Comment by wyzhhhh** [comment]
> This could be due to the tokenizer, we encountered similar issues when using Chinese tokenizer before. Could you try running the huggingface pipeline on a small prompt?

How do you solve this problem?  can it generate the text answer now? Is it due to the size of the prompt?

**Comment by jon-chuang** [comment]
It was when passing Latin alphabet into Chinese tokenizer, somehow it resulted in weird artifacts.

**Comment by jon-chuang** [comment]
Recommend you test individual components of your pipeline first  for instance swap out the llm_predictor for OpenAIPredictor.

**Comment by wyzhhhh** [comment]
> Recommend you test individual components of your pipeline first for instance swap out the llm_predictor for OpenAIPredictor.

ok I‘ll try it! Thank you
