### ISSUE TITLE
[Question]: Metafilter 

### ISSUE THREAD

**Issue by malinphy** [run-llama/llama_index#6846]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Indexes can be created in various ways. Metadata, in document format, can be also stored in the index. However, I am looking for metadata filtering. I want to share the example code (I could not figure out metafiltering)
```
nrows = 10
df = pd.read_csv('https://raw.githubusercontent.com/malinphy/datasets/main/bbc_news_uk/bbc_news.csv', nrows = nrows)
df.head(3)
list_of_documents = []
for i in range(len(df)):
    list_of_documents.append(Document(text = df['title'][i], metadata = {'region' : df['region'][i]}))
index = VectorStoreIndex.from_documents(list_of_documents)

query_engine = index.as_query_engine()
response = query_engine.query("heroin, methadone", metadata = {'region' : 'Health'}  )   
```
Thanks in advance!
![image](https://github.com/jerryjliu/llama_index/assets/55249305/b8dbbd09-6e9e-40b1-9bf9-ec0fc8a5cff2)

**Comment by logan-markewich** [comment]
Yea, this answer looks correct. I will note that the default vector store built into llama-index doesn't support metadata filters (you'd have to write a custom retriever or node postprocessor to filter in that case)

**Comment by muhammad-ahsan099** [comment]
@logan-markewich how can we write custom retriever or node postprocessor to implement filter.

**Comment by logan-markewich** [comment]
@muhammad-ahsan099 I definitely misspoke, a custom node postprocessor would only filter nodes AFTER they are retrieved. A custom retriever wouldn't really help either, if the underlying vector store doesn't support metadata filtering 

Just use something with llama index that supports it to make your life easier (qdrant, chroma, pinecone, weaviate)

**Comment by nicomenza** [comment]
any idea on how to include multiple values for a metadata key on the filter?
I mean something like :
filters = MetadataFilters(filters=[ExactMatchFilter(key="colours", value=["red", "blue"])]) 
That actually works.

**Comment by nicomenza** [comment]
> @nicomenza I think you can just create a filter for each value instead
like this?
filters = MetadataFilters(filters=[ExactMatchFilter(key="colours", value="red"), ExactMatchFilter(key="colours", value="blue")])
I tried it but it takes into account only the last filter when i do that

**Comment by logan-markewich** [comment]
Hmm seems like a limitation on the vector store then? 🤷🏻‍♂️

**Comment by daniazzam** [comment]
@nicomenza, I am facing the same issue, the filter only takes into account the last key. Did you find a solution?

**Comment by jonmach** [comment]
I also have exactly this issue, but I am trying to allow a user to constrain a query down to a number of source documents, rather than all of them, or a single one.

E.g.

```
    filters=MetadataFilters(
                            filters=[ExactMatchFilter(key="file_name", value=[fileNames])]
                        )
```
Unfortunately, value currently doesn't take an array/list type.  It seems like a reasonable thing to add though.

**Comment by nicomenza** [comment]
> @nicomenza, I am facing the same issue, the filter only takes into account the last key. Did you find a solution?
> 

No, unfortunately I didn't. I ended up hardcoding queries without llamaindex.

**Comment by logan-markewich** [comment]
@jonmach  @daniazzam we've updated the filtering support for popular vector dbs. This should be possible now I think?

Here's an example. Using the operator IN or NIN should be possible
https://docs.llamaindex.ai/en/stable/examples/vector_stores/chroma_metadata_filter.html#multiple-metadata-filters-with-or-condition

**Comment by logan-markewich** [comment]
(Also @nicomenza ^)

**Comment by jonmach** [comment]
I'm there Logan - but it seems that there is no 'IN' recognised.  I kept getting an attribute error.

Your sample code provided what I needed, because using the MetadataFilter primitive wasn't an obvious choice for me.

It might be useful to add some sample code to the documentation to show this.

Here is what I did:

```
fnfilters = []
        for f in filenames:
            fnfilters.append(MetadataFilter(key='file_name', value = f))

query_engine = index.as_query_engine(
        service_context=service_context,
        similarity_top_k=3,
        vector_store_query_mode="default",
        filters=MetadataFilters(
            filters=fnfilters,
            condition=FilterCondition.OR,
        ),
        alpha=None,
        doc_ids=None,
    )
```

If you try this with a FilterCondition.IN, you'll see that it errors as follows:

```
    condition=FilterCondition.IN,
              ^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/enum.py", line 784, in __getattr__
    raise AttributeError(name) from None
AttributeError: IN

```

So, even though I used an OR, it behaves like an IN if I manually build a list of MetadataFilters.

**Comment by nicofuru** [comment]
I am using the following code for filtering on the retriever with the same structure as you. It is working if I only pass one file name but it breaks when I send 2 or more.
base_retriever = automerging_index.as_retriever(similarity_top_k=similarity_top_k, filters=fnfilters)

**Comment by jonmach** [comment]
It sounds like it's behaving like an AND

**Comment by nicofuru** [comment]
Exactly, have you experienced the same?

**Comment by jonmach** [comment]
Well, you're missing the OR condition. Add it like in my code.

**Comment by nicofuru** [comment]
I had it like this:

list_of_names = ['example1', 'example2']

filters_list = []

for document_name in list_of_names:

  filter = MetadataFilter(key="filename", value=document_name)
  filters_list.append(filter)
        
filters = None if len(filters_list) == 0 else  MetadataFilters(filters=filters_list, condition=FilterCondition.OR)

This works for 1 document in list of names but not for 2 or more.

**Comment by ralarconm** [comment]
> I had it like this:
> 
> list_of_names = ['example1', 'example2']
> 
> filters_list = []
> 
> for document_name in list_of_names:
> 
> filter = MetadataFilter(key="filename", value=document_name) filters_list.append(filter)
> 
> filters = None if len(filters_list) == 0 else MetadataFilters(filters=filters_list, condition=FilterCondition.OR)
> 
> This works for 1 document in list of names but not for 2 or more.

MetadataFilters are not working using the default VectorIndexRetriever. This may be a workaround:

```
# File name filters
file_names = ["file_name_1", "file_name_2"]

# 1. Load Vector Index
path_vector_store = "path_storage"
vector_index = load_index_from_storage(StorageContext.from_defaults(persist_dir=path_vector_store))

# 2. Get node IDs by metadata file_name
node_ids = [n.node_id for n in vector_index.docstore.docs.values() if n.metadata['file_name'] in filters]

# 3. Load VectorIndexRetriever using node_ids as filter
retriever = VectorIndexRetriever(vector_index, node_ids=node_ids, similarity_top_k=10)

# 4. Query  & check the retrieved file_names
nodes = retriever.retrieve(query)
for node in nodes:
    print(node.metadata['file_name'])
```

I'm testing this currently and seems to be working on my case. I correctly see the desired file names in the retrieved nodes.

**Comment by teis-e** [comment]
> @nicofuru:
> 
> > I had it like this:
> > list_of_names = ['example1', 'example2']
> > filters_list = []
> > for document_name in list_of_names:
> > filter = MetadataFilter(key="filename", value=document_name) filters_list.append(filter)
> > filters = None if len(filters_list) == 0 else MetadataFilters(filters=filters_list, condition=FilterCondition.OR)
> > This works for 1 document in list of names but not for 2 or more.
> 
> MetadataFilters are not working using the default VectorIndexRetriever. This may be a workaround:
> 
> ```
> # File name filters
> file_names = ["file_name_1", "file_name_2"]
> 
> # 1. Load Vector Index
> path_vector_store = "path_storage"
> vector_index = load_index_from_storage(StorageContext.from_defaults(persist_dir=path_vector_store))
> 
> # 2. Get node IDs by metadata file_name
> node_ids = [n.node_id for n in vector_index.docstore.docs.values() if n.metadata['file_name'] in filters]
> 
> # 3. Load VectorIndexRetriever using node_ids as filter
> retriever = VectorIndexRetriever(vector_index, node_ids=node_ids, similarity_top_k=10)
> 
> # 4. Query  & check the retrieved file_names
> nodes = retriever.retrieve(query)
> for node in nodes:
>     print(node.metadata['file_name'])
> ```
> 
> I'm testing this currently and seems to be working on my case. I correctly see the desired file names in the retrieved nodes.

This doesn't work for me, maybe because its qdrant. 

What did you fill in here as query?

**Comment by shreyash-99** [comment]
i

> This doesn't work for me, maybe because its qdrant.
> 
> What did you fill in here as query?

i am also using qdrant and this doesn't work, have you figured out any solution?

**Comment by teis-e** [comment]
No I managed to my project a whole other way. I tried everything from the docs according to metafilter nothing is working. Not even in the new update i think

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/blob/751565537c74fd4649f8c7f0833f055cb7da3052/llama-index-integrations/vector_stores/llama-index-vector-stores-qdrant/llama_index/vector_stores/qdrant/base.py#L580

**Comment by teis-e** [comment]
> @teis-e metadata filters are working fine last I tried 
> 
> 
> 
> If you really need to, you can pass in the filters using qdrant syntax as well
> 
> 
> 
> `as_query_engine(vector_store_kwargs={"qdrant_filters": <qdrant_syntax>})`

For just 1 it works for me. But using multiple filters with the OR operator never worked for me. 

I will try the qdrant syntax, thnx for that suggestion.

**Comment by joofio** [comment]
did the qdrant syntax worked for you?

**Comment by teis-e** [comment]
> did the qdrant syntax worked for you?

No sadly not, but didn't check in the newest update yet. Altough i still get replies on the issue on this I have opened. Lot of people want it.

**Comment by joofio** [comment]
it worked for me with qdrant filters. but take into account it needs the python syntax.
helpfull reading:
https://docs.llamaindex.ai/en/stable/examples/vector_stores/Qdrant_using_qdrant_filters/
https://qdrant.tech/documentation/concepts/filtering/
