### ISSUE TITLE
[Feature Request]: Support HuggingFace self-hosted LLM endpoint

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6859]
### Feature Description

Some users may want to deploy their own LLM endpoint based on open source. Huggingface's infra for doing so may not be a bad choice. We can integrate with it. https://github.com/huggingface/text-generation-inference

Not sure if it can handle embedding inference too. (Guess not, but see: https://github.com/huggingface/text-generation-inference/issues/199). Hopefully it can extract good util from the device. For instance the right amount of concurrent embeddings to perform given the GPU memory.

**Comment by logan-markewich** [comment]
We do technically support it since LangChain also supports it.

Are there any benefits to having a native integration for this, other than one less langchain dependency?
