### ISSUE TITLE
feat(evaluation): Add more BEIR examples comparing Retrievers along different settings

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6878]
### Feature Description

Dimensions:
- [ ] Node content: chunk size, chunk overlap, presence/absence of metadata (e.g. title, url)
- [ ] Approximate similarity metric: SVM, MMR, Faiss ANN (IVF, HNSW)
- [ ] Compare dense retrieval v.s. retrieval + rerank v.s. lexical methods v.s. neural + lexical methods

Tuning:
- [ ] [Instruction-tuned](https://github.com/jerryjliu/llama_index/issues/6805)
- [ ] [Linear-projection tuned](https://blog.vespa.ai/tailoring-frozen-embeddings-with-vespa/)

**Comment by alan-m-thomas** [comment]
chunk size variable
