### ISSUE TITLE
feat(context length): Cross-Node Ranking, Pruning and Marginalization

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6884]
### Feature Description

So far, we've only considered inter-node (node reranking) and intra-node (sub-node sentence pruning) methods to select for relevant info into the LLM context. We should optimize over the entire sentence set or chunk set of all of the nodes, as some nodes may be more dense in relevant information than others. For the lack of a better term, we refer to this as "cross-node".

Furthermore, we may want to marginalize sentences that contain similar semantic content to others (using a symmetric embedding). 

Questions: 
1. on which level should the marginalization be performed? (inter-node v.s. cross-node)
2. how to combine marginalization with pruning? One option is to first perform pruning (either intra-node or cross-node), then perform inter-node marginalization. Or, perhaps any combination as per one's intuition or whim.

Tasks:
- [ ] abstraction for cross-node post-processing (combine current ones)
- [ ] share abstraction between inter-node rerank, cross-node, and intra-node
- [ ] marginalization

**Comment by jon-chuang** [comment]
I think that once we have good sub-node pruning, it may actually be possible to have decent performance on some local LLMs, especially for simple RAG QnA tasks, since most of the information is already relevance-pruned and the model just needs to synthesize a summary.

**Comment by JainVidit12** [comment]
Maybe we can apply variable pruning? We can retain more from the nodes which are densely packed. One option can be to use the BeforeAfterContext to implement this.
