### ISSUE TITLE
[Question]: Querying pdf data using fiass vector store

### ISSUE THREAD

**Issue by sumanthp** [run-llama/llama_index#6887]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Facing issue while trying to create and query fiass vector store on pdf documents. It is not able to find index_id used while creating the index. Is there an option to provide index name while creating the index.

Code:
`index_name = st.text_input("Enter the Index name",key="faiss_index")
        if st.button("Create Index",key="faiss_button"):
            st.session_state.faiss_index_list.append(index_name)
            documents = SimpleDirectoryReader(dir_path).load_data()

            # create a Faiss vector store
            vector_store = FaissVectorStore(faiss_index)
            storage_context = StorageContext.from_defaults(vector_store=vector_store)
                                                        #    ,persist_dir="/home/azureuser/streamlit/Fiass/"+index_name)
            index = VectorStoreIndex.from_documents(documents, service_context=service_context)
            index.set_index_id(index_name)
            index.storage_context.persist("/home/azureuser/streamlit/Fiass/"+index_name)
            index = load_index_from_storage(storage_context=storage_context,index_id=index_name,service_context=service_context)
            query_engine = index.as_query_engine(response_mode='refine', service_context=service_context)
            query = st.text_input("Enter your query here:",key="query_fiass")
        if st.button("Search",key="search_faiss"):
            response = query_engine.query(query)
            st.write(response.response)`

**Comment by jon-chuang** [comment]
Yes 

```python
# save index to remote blob storage
index.set_index_id("vector_index")
# this is {bucket_name}/{index_name}
index.storage_context.persist('llama-index/storage_demo', fs=s3)

# load index from s3
sc = StorageContext.from_defaults(persist_dir='llama-index/storage_demo', fs=s3)
index2 = load_index_from_storage(sc, 'vector_index'
```

Source: https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/storage/save_load.html

**Comment by sumanthp** [comment]
![08a5a816-1e8c-4795-8e37-3758b94fc907](https://github.com/jerryjliu/llama_index/assets/11244510/f7e7ce2f-7a30-41e9-9134-816f85b8502d)

**Comment by logan-markewich** [comment]
Faiss is a little weird to work with (admittedly it doesn't get used often, so the interface is a little janky)

See the docs here for loading/saving. Notice that the vector store is loaded separately from the entire storage context
https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/FaissIndexDemo.html#load-documents-build-the-vectorstoreindex

**Comment by sumanthp** [comment]
I did try out the code as per documentation, it didn't work. Also, I wanted to provide index_id or index_name with storage context to maintain multiple indexes. Could you help if this is a possibility in faiss?
