### ISSUE TITLE
[Bug]: Search_params default values are not properly set from index_params when creating collection and index in MilvusVectorStore

### ISSUE THREAD

**Issue by faileon** [run-llama/llama_index#6890]
### Bug Description

Consider the following code snippet
```py
index_params = {
    "index_type": "HNSW",
    "metric_type": "L2",
    "params": {
        "M": 8,
        "efConstruction": 64
    }
}
vector_store = MilvusVectorStore(collection_name="myindex", index_params=index_params, host="localhost", port="19530", overwrite=True)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex.from_documents(documents, service_context=service_context, storage_context=storage_context)
query_engine = index.as_query_engine()
response = query_engine.query("Some question")
```
Will fail with the following error:
> metric type not match: expected=L2, actual=IP: invalid parameter

I am overriding a collection and creating an index with some parameters. If I run a query on this store, it will fail, because search_params did not get the right metric_type set. Search_params will default to IP, despite index being created with L2.

The workaround currently is to set the search_params explicitly such as
```py
index_params = {
    "index_type": "HNSW",
    "metric_type": "L2",
    "params": {
        "M": 8,
        "efConstruction": 64
    }
}

search_params = {
    "metric_type": "L2",
}
vector_store = MilvusVectorStore(collection_name="virtllamaindexlinda", index_params=index_params, search_params=search_params, host="localhost", port="19530", overwrite=True)
```

However tracing the source code I believe this [line](https://github.com/jerryjliu/llama_index/blob/fc3eed13b1334278e85fb4120d46759081a5ad66/llama_index/vector_stores/milvus.py#L155C7-L155C7) should be an `if` instead of `elif` and the bug will be resolved without any side effects?

### Version

0.7.6

### Steps to Reproduce

Create a collection and index in Milvus - specify custom index_params.
Observe search_params are not being created correctly according to index_params. Instead defaulting to default_search_params.

**Comment by Disiok** [comment]
Hey @faileon , thanks for the bug report and good catch. Definitely not super intuitive that the metric type for index does not carry over to the search param.

Would you be interested in contributing a PR on this? Seems like a straightforward enough change. :D 

I'm not sure if your one-liner will work, since we are setting `search_params` to default value given index_type, rather than one specified one (in `_create_index` method).

**Comment by faileon** [comment]
Hi @Disiok thanks for the quick reply. I don't mind getting my hands dirty and submit the PR. I admit I haven't given the proposed solution too much thought. I will study the code a little more and submit a PR with a more solid solution :]
