### ISSUE TITLE
[Feature Request]: Improve Embeddings for Hugging Face - differentiate between query and passage embeddings

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#6903]
### Feature Description

Purpose: support asymmetric embeddings e.g.
https://www.sbert.net/examples/applications/semantic-search/README.html. We will test on BEIR.

I think that to deal with this correctly, we should define our own `HuggingFaceEmbedding`s. @logan-markewich 

Not entirely sure how things work with openai, seems there are some models that are asymmetric but `text-embedding-ada-002` seems to be symmetric.

**Comment by kevinlu1248** [comment]
Not familiar with asymmetric embeddings but gave this a shot using Sweep at https://github.com/kevinlu1248/llama_index/pull/15.

**Comment by jon-chuang** [comment]
Thanks for the attempt @kevinlu1248 but I think the sweep bot fundamentally misunderstood the task.

**Comment by kevinlu1248** [comment]
@jon-chuang Sorry I think I didn't understand the task completely either: I believe the attempt is for the indexing system to support search systems where queries and contexts are embedded by different models. Is that correct?

**Comment by jon-chuang** [comment]
Well, not quite, the encoders are actually two parts of a whole, since they need to be alongside the other. You may take a look at the old openai embeddings (*-001) for what I mean.

**Comment by jon-chuang** [comment]
Anw, this is only worth doing if there are any asymmetric (search) embeddings whose accuracy/throughput tradeoff is better or comparable to the symmetric ones.
