### ISSUE TITLE
[Feature Request]: Is there a way to generate images a long with text?

### ISSUE THREAD

**Issue by dinhan92** [run-llama/llama_index#6905]
### Feature Description

As I learn from this link: https://github.com/jerryjliu/llama_index/blob/main/examples/multimodal/Multimodal.ipynb
It only generates images, so I wonder if there is a way generating both images and text when the users ask something like: "Descriptions and images of this cat" ?

### Reason

That will make the messages look more flexible

**Comment by jon-chuang** [comment]
You can directly look at the `response.source_nodes` to see the image caption for the image.

**Comment by dinhan92** [comment]
@jon-chuang does this work with OpenAIAgent  agent_stream = await agent.astream_chat ? I don't see source_nodes is hinted
