### ISSUE TITLE
Document Insertion with time-weighted postprocessor

### ISSUE THREAD

**Issue by adiagarwalrock** [run-llama/llama_index#6914]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to insert a document (initially text like pdf, docx, etc.) into an existing index w/ [Time-Weighted Rerank](https://gpt-index.readthedocs.io/en/latest/examples/node_postprocessor/TimeWeightedPostprocessorDemo.html).

The index is already created with metadata for time-stamping, How can the insertion be conducted for any new data(docs) to insert in the existing one.

**Comment by kevinlu1248** [comment]
Hey @jerryjliu, this is Kevin Lu we met a while back at the open-source event and the GPT-4  hackathon! I'm currently building, an AI junior dev. I tried tackling this issue by prompting Sweep and it generated the PR at https://github.com/kevinlu1248/llama_index/pull/10. You can also write a PR reply or comment in the code to suggest changes. Would appreciate any feedback on how well Sweep did!

I also made a PR directly to Llama Index's main at https://github.com/jerryjliu/llama_index/pull/6926.
