### ISSUE TITLE
[Question]: How do I load an already existing index created using NebulaGraphStore for querying instead of running KnowledgeGraphIndex.from_documents every time?

### ISSUE THREAD

**Issue by sridharac93** [run-llama/llama_index#6952]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How do I load an already existing index created using NebulaGraphStore for querying instead of running KnowledgeGraphIndex.from_documents every time?
In documentation there is clarification about this and also there is no loader/ reader for nebula graph db
There is no clear way to use an already loaded index.

**Comment by logan-markewich** [comment]
You'll need to persist and load the index. Tbh the graph store is pretty new, but I thiiiink this is how it works.

```python
index.storage_context.persist(persist_dir="./storage")

from llama_index import StorageContext, load_index_from_storage
graph_store = [setup NebulaGraphStore]
storage_context = StorageContext.from_defaults(persist_dir="./storage", graph_store=graph_store)
index = load_index_from_storage(storage_context)
```

**Comment by aetherwu** [comment]
> ```python
> load_index_from_storage
> ```

May I ask for how to do it in RedisVectorStore?
I can also help to submit it to document after I validate the way.

**Comment by logan-markewich** [comment]
@aetherwu If you are using RedisVectorStore, the entire index is stored in the vector store.

You can setup the vector store object to connect to the existing vector store, and then do this

```
index = VectorStoreIndex.from_vector_store(vector_store)
```
