### ISSUE TITLE
[Question]: Using Pinecone and S3 to update my index.

### ISSUE THREAD

**Issue by kylemassimilian** [run-llama/llama_index#7046]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to create a Q&A chatbot over a large set of documents. I'm holding my data in an S3 bucket, as I have a Zapier integration that updates my bucket every time someone uploads a new file to Egnyte (where we keep all our files). Originally, I had a demo working where I loaded a small # of docs from the S3 bucket, created a vector index, and used a chat_engine. Using the Llamaindex's VectorStoreIndex temporarily downloads the file to your local disk (as far as I understand). Therefore, to scale this to a large number of files, I need to use a different approach. My plan is to connect my bucket to Pinecone, configure the index using llama, and use that as the backbone of my app. It's important that I create a solution where my index updates with new docs. Do I need to create embeddings for my data using a model (myself) each time there's a new file and then upload this to Pinecone? Do I need to create a Lambda function w/ an event to update my Pinecone index when new files are added to my S3 bucket? Apologies, I am new to Pinecone/vector dbs. Could someone please tell me if I am thinking about this correctly and/or there's a better way? Thank you.

**Comment by tyre** [comment]
Yes your architecture looks about right:

1. AWS Lambda function executed when a new document enters the S3 bucket
2. Pull that file locally and load into a set of LlamaIndex `Document`s
3. Use the `PineconeVectorStore` to add the new documents to Pinecone

For (2) there is [an S3 reader on llamahub](https://llamahub.ai/l/s3) that looks like it can do the loading part in a couple lines of code.

For (3) there is an [example in the docs](https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/PineconeIndexDemo.html) about customizing the storage layer to use Pinecone.

Does that make sense?
