### ISSUE TITLE
[Question]: Is index/storage context loaded a global variable?

### ISSUE THREAD

**Issue by AravAct** [run-llama/llama_index#7055]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is the index created by GPTVectorestoreindex set gloabally?
Context : I am building an app, where relevant answers for a question must be shown by each file(and each file is an vector index). For this I construct a table and each row is a file, when a user asks a question I identify the relevant files (diff fn) and for each file I trigger the query engine.
```
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor,embed_model=embeddings,chunk_size=4000)#chunk_size_limit=6000,
set_global_service_context(service_context)
# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir=f'./{folderhex_name}/',)
# load index
index = load_index_from_storage(storage_context, index_id="vector_index",service_context=service_context)
response_synthesizer = get_response_synthesizer(response_mode='compact',use_async=True,service_context=service_context)
print("Loaded the index, Querying the question")
query_engine = index.as_query_engine(response_synthesizer=response_synthesizer)
response = query_engine.query(question)
    
```
Now this code is triggered ||ly for each row(async calls). But based on the responses and their time, I am unable to understand if there are really ||. Check the timings for the below example of 3 rows
![image](https://github.com/jerryjliu/llama_index/assets/122975761/23d7bab4-dae1-4059-9aa2-32a688f0be10)

This timing has been consistent for any number of rows I have, ~multiples of first response time.So my question:  Is the index loaded a global variable? Or my understanding is wrong?

**Comment by Disiok** [comment]
It shouldn't be a global variable. 
Are you setting different persist_dir for the different indices? If not, they get persisted to the same vector store, which might affect things.

**Comment by AravAct** [comment]
Thanks for the reply.
Yes, the persist_dir is different for each index. I am saving each vector store index in a diff folder (eg folder_a, folder_b,folder_c)
And while loading the index, there are 3 parallel async calls to each folder using
```
storage_context = StorageContext.from_defaults(persist_dir=f'./{folderhex_name}/',)
```
What else can I check in this case to resolve the issue?

**Comment by AravAct** [comment]
Thanks for the reply.
Yes, the persist_dir is different for each index. I am saving each vector store index in a diff folder (eg folder_a, folder_b,folder_c)
And while loading the index, there are 3 parallel async calls to each folder using
```
storage_context = StorageContext.from_defaults(persist_dir=f'./{folderhex_name}/',)
```
