### ISSUE TITLE
[Documentation]: The documentation jupyter notebook for OpenAI Query Planning is a bit vague and contains wrong output

### ISSUE THREAD

**Issue by aerickson-clt** [run-llama/llama_index#7064]
### Documentation Issue Description

https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent_query_plan.html#openai-function-agent-with-a-query-plan-tool

https://github.com/jerryjliu/llama_index/blob/779e7fc56cfff1edcd926c22a296d4813ba76117/docs/examples/agent/openai_agent_query_plan.ipynb#L340C1-L341C1

This line in the above doc contains references to france and italy and is generally confusing as to where it comes from.

Generally this notebook could be improved to help explain how the query planning agent works.

### Documenation Link

https://gpt-index.readthedocs.io/en/latest/examples/agent/openai_agent_query_plan.html#openai-function-agent-with-a-query-plan-tool

**Comment by aerickson-clt** [comment]
There is a bit more to this than I originally realized.  I ran the notebook (after modifying it to work with Azure OpenAI) and indeed found the referenced line without output about italy and france does not even run, but furthermore found a problem with the final query that uses more than one function.

![image](https://github.com/jerryjliu/llama_index/assets/32244272/09f85703-8fee-4d4f-9491-c065f7a084c8)

```
File C:\Copperleaf\git-repos\llama_index\llama_index\tools\query_plan.py:215, in QueryPlanTool.__call__(self, *args, **kwargs)
    213 root_nodes = self._find_root_nodes(nodes_dict)
    214 if len(root_nodes) > 1:
--> 215     raise ValueError("Query plan should have exactly one root node.")
    217 return self._execute_node(root_nodes[0], nodes_dict)
```


For info, the former issue results in this error

```
Cell In[28], line 3
      1 from llama_index.tools.query_plan import QueryPlan
----> 3 query_plan = QueryPlan(
      4     **{
      5         "root": {
      6             "query_str": "risk factors",
      7             "tool_name": "sept_2022",
      8             "child_nodes": [],
      9         }
     10     }
     11 )

File C:\Copperleaf\git-repos\llama_index\venv\Lib\site-packages\pydantic\main.py:341, in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for QueryPlan
nodes
  field required (type=value_error.missing)
```

**Comment by Disiok** [comment]
The "references to france and italy" is part of the few-shot examples defined as part of the query plan tool.

**Comment by Disiok** [comment]
Are you using GPT-4 via Azure? We observed that this kind of query planning capability is only possible with the high capability models.

**Comment by aerickson-clt** [comment]
Yes, I am using GPT-4 from Azure, yes.  The query plan tool is not working well for my use case though.  The agent sometimes does not call the query plan tool, and then I have yet to see the query plan tool create a root node in its plan.  I give it three sources of information and some instructions about migrating some source code.  It sometimes plans to get the information, but does not plan to do anything with it (no root node).

Another problem is that if my QueryEngineTools have more than a few words in their descriptions then the query_plan_tool description is too long and the LLM throws an error.

**Comment by aerickson-clt** [comment]
My set up is pretty much like the jupyter notebook, with my own sources of information. 

I build my agent with

```
agent = OpenAIAgent.from_tools([query_plan_tool],
                               max_function_calls=10,
                               llm=azure_openai,
                               verbose=True,
                               system_prompt="system\nYou are an AI agent that helps migrate code from [redacted].  You always use the query_plan_tool function.")
```

I have a query string that's something like this:

```
query_template = """The Target Entity, "{target_entity}", has front-end UI pages written in <some instructions about a code migration>....  Your task is to look at the "Working File", below, determine how to improve it and what information is needed to accomplish that, and bring it all together to write an updated and self-contained version of the "Working File".  The available information sources are described in the Query Plan Tool function.

Write as much code as possible, even if it may not be correct, because a developer will take up the task from where you leave off and it is much easier for them to delete portions of the code than to write them from scratch.

________________________
Working File:

{working_file_contents}

"""
```

And I use it to make the following query

```
query_str=query_template.format(
    target_entity=target_entity,
    example_entity=example_entity,
    working_file_contents=working_file_contents).replace('{', '{{').replace('}', '}}',)
agent.query(query_str)
```
