### ISSUE TITLE
Using a custom tokenizer for SentenceEmbeddingOptimizer

### ISSUE THREAD

**Issue by nitky** [run-llama/llama_index#707]
`SentenceEmbeddingOptimizer` is a fantastic job! I would be happy if it could support not only nltk but also other custom tokenizers. Thanks!

**Comment by jerryjliu** [comment]
@nitky this is a good idea! will add soon

**Comment by karan1508** [comment]
Can I take this up ?

**Comment by NickNYU** [comment]
I send a PR and see if it works for what you guys are expecting

**Comment by nitky** [comment]
I'm sorry. I missed the notification. 

I have confirmed that this function works as expected in my environment.
Thank you so much!
