### ISSUE TITLE
[Bug]: ReAct agent Action Input parser does not handle multiline input

### ISSUE THREAD

**Issue by aerickson-clt** [run-llama/llama_index#7074]
### Bug Description

I am using the ReAct agent with a complex tool that requires many lines of input.  The agent succesfully generates the Agent Input, but it's on multiple lines, and the regex does not handle that.

https://github.com/jerryjliu/llama_index/blob/9fd16c9e809e8146f2663709003fe4c5d235e4f5/llama_index/agent/react/output_parser.py#L20

![image](https://github.com/jerryjliu/llama_index/assets/32244272/4593f5b0-7bb1-4cbf-bd23-abae0c126291)

### Version

0.7.13

### Steps to Reproduce

```
from llama_index.agent.react.output_parser import extract_tool_use

test_str = """\
Thought: Now that I have both the pre-migration and post-migration code... I will use the code_writer tool to write the initial code.
Action: code_writer
Action Input: {
  "working_file": "",
  "instructions": "do stuff",
  "context": "some context {"key": "maybe there's a nested json here"}
}
let's add some garbage in here too.
"""

extract_tool_use(test_str)
```

output:

```
('Now that I have both the pre-migration and post-migration code... I will use the code_writer tool to write the initial code.',
 'code_writer',
 '{')
```

A different implementation the simple regexs the outermost {} after Action Input might be better.

```
from typing import Tuple
import re
def my_extract_tool_use(input_text: str) -> Tuple[str, str, str]:
    pattern = r"\s*Thought:(.*?)Action:(.*?)Action Input:\s*(\{.*\})"

    match = re.search(pattern, input_text, re.DOTALL)
    if not match:
        raise ValueError(
            "Could not extract tool use from input text: {}".format(input_text)
        )

    thought = match.group(1).strip()
    action = match.group(2).strip()
    action_input = match.group(3).strip()
    return thought, action, action_input

print(my_extract_tool_use(test_str))
```

```
('Now that I have both the pre-migration and post-migration code... I will use the code_writer tool to write the initial code.', 'code_writer', '{\n  "working_file": "",\n  "instructions": "do stuff",\n  "context": "some context {"key": "maybe there\'s a nested json here"}\n}')
```

**Comment by Disiok** [comment]
Thanks for raising this bug! 

One concern with the proposed change. This would assume the action input is always surrounded by braces right?
This might be too strict for other tools that take arbitrary str input.

**Comment by aerickson-clt** [comment]
`pattern = r"\s*Thought:(.*?)Action:(.*?)Action Input:\s*(\{.*\})`

Yes, this would greedily match `{...}` after Action Input: and any amount of whitespace, but given that it's in the ReAct tool subfolder, it makes sense to customize it for that purpose.  The ReAct tools is instructed to to format its output as follows:

```
Thought: I need to use a tool to help me answer the question.
Action: tool name (one of {tool_names})
Action Input: the input to the tool, in a JSON format representing the kwargs (e.g. {{"text": "hello world", "num_beams": 5}})
```
Please use a valid JSON format for the action input. Do NOT do this {{'text': 'hello world', 'num_beams': 5}}.
