### ISSUE TITLE
[Bug]: Response cut off

### ISSUE THREAD

**Issue by ethayu** [run-llama/llama_index#7085]
### Bug Description

Query response is cut off. Last 2 sentences of response look like this:
The contrast between good and evil is discussed, as well as the idea of power and strength. The idea of self-fulfillment is also discussed, and it is suggested that the modern world is oppressive and that it is difficult to achieve self-fulfillment due to the
fabricated ideals of turning weakness into accomplishment and

I'm wondering if this is because I reached the token limit, but I the output text is only about 2100 tokens.

### Version

0.7.11.post1

### Steps to Reproduce

Index is created as follows:

```python
def construct_index(directory_path):
    documents = SimpleDirectoryReader(directory_path).load_data()
    metadata_extractor = MetadataExtractor(
        extractors=[
            TitleExtractor(nodes=5),
            QuestionsAnsweredExtractor(questions=3),
            SummaryExtractor()
            #SummaryExtractor(['self', 'prev', 'next'])
        ],
    )
    parser = SimpleNodeParser.from_defaults(chunk_size=512, chunk_overlap=20, metadata_extractor=metadata_extractor)
    nodes = parser.get_nodes_from_documents(documents)
    llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=51200))
    service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
    index = ListIndex(nodes, show_progress=True, service_context=service_context)
    index.storage_context.persist(persist_dir="persist")
    return index
``` 

Response function is here:
```python
def generate_notes():
    input_text = "Make extremely-detailed college-level notes from everything you know, this document, which is a transcript from a video lecture. Supplement each statement with reasoning or evidence. output in html style."
    storage_context = StorageContext.from_defaults(persist_dir="persist")
    index = load_index_from_storage(storage_context=storage_context)
    query_engine = index.as_query_engine(response_mode="tree_summarize", LLMPredictor=OpenAI(temperature=0.7, model_name="gpt-3.5-turbo", max_tokens=51200))
    response = query_engine.query(input_text)
    return response.response
```

**Comment by logan-markewich** [comment]
You've set max_tokens to 51200, but gpt-3.5 has a max context window of 4096 👀

max tokens can't really go much higher than 3000. Every increase to max tokens decreases how many tokens can be used in the input. LLMs generate one token at a time, add it to the input, and generate the next token.

**Comment by ethayu** [comment]
I see! My input text is quite long, but I'm trying to create a detailed response (ie detailed notes from the transcript). How would I go about this. I was thinking about using an agent to incrementally prompt lecture sections, but are there other (possibly more suitable) ways to do this?
