### ISSUE TITLE
[Feature Request]: Function-calling query engines

### ISSUE THREAD

**Issue by SlapDrone** [run-llama/llama_index#7094]
### Feature Description

Hey folks,

Is there yet implemented a way to integrate function calling APIs with a good old fashioned query engine?

It would be amazing if we had (have?) something like the [OpenAI Pydantic Program](https://gpt-index.readthedocs.io/en/latest/examples/output_parsing/openai_pydantic_program.html), but where the function calling + pydantic native output templating was available for complex response synthesizers.

### Reason

I don't think there's anything stopping this. In fact it may be in already and just not well documented since things are moving so fast.

I'm currently working with a use-case where I have a query engine that's refining an answer over a large corpus, where the answer is a complex JSON containing an array of objects (currently using the vanilla pydantic + output parser approach). The formatting instructions eat up a huge chunk of my token budget, so this would be a godsend.

**Comment by logan-markewich** [comment]
This isn't implemented yet, but I think it makes sense to have at some point! Something like a `PydanticQueryEngine` that extracts data for a certain pydantic class as it goes? I guess the exact details would need to be worked out.

Like for example, do I define a class like `Person(name, number)` and the query engine returns a list of those?

**Comment by SlapDrone** [comment]
Maybe can sketch something out to see if it makes sense. The current single-prompt version from the docs is:

```python
prompt_template_str = """\
Generate an example album, with an artist and a list of songs. \
Using the movie {movie_name} as inspiration.\
"""
program = OpenAIPydanticProgram.from_defaults(
    output_cls=Album,
    prompt_template_str=prompt_template_str,
    verbose=True,
)
output = program(movie_name="The Shining")
```

Perhaps we could aim to mirror this API, maybe something like:

```python
class Albums(BaseModel):
    albums: list[Album] = Field(description="list of Albums")

query_str = """\
From every movie that you encounter in the list, generate an example 
album inspired by its title, with an artist and a list of songs.\
"""

index = ... # some big collection of imdb lists, or something
response_synthesizer = get_response_synthesizer(
    # might require some merging of models for cumulative modes 
    response_mode="compact" 
)
query_engine = RetrieverQueryEngine(
    retriever=index.as_retriever(),
    response_synthesizer=response_synthesizer,
)
# would be nice if we could provide the schema at query time, so we can tweak it without rebuilding the whole query engine?
output  = query_engine.query(query_str, output_cls=Albums)
```

At first glance, `ResponseSynthesizer` might be the place that needs to be made aware of the `output_cls` (since the common buck seems to stop at `BaseSynthesizer.get_response`, which delegates down to `LLMPredictor.predict` in various ways depending on the `response_mode`). 

But it looks like the query engine code is still using `LLMPredictor` which doesn't look like it supports `functions` and `function_call` like `LLM` does, so maybe some deeper refactoring to integrate `LLM` everywhere would be a prerequisite...

**Comment by SlapDrone** [comment]
> But it looks like the query engine code is still using LLMPredictor which doesn't look like it supports functions and function_call like LLM does, so maybe some deeper refactoring to integrate LLM everywhere would be a prerequisite...

Since `LLMPredictor` is deprecated, I started experimenting replacing the it in the response synthesizers with the new `LLM` class (and using `complete` instead of `predict`) over here https://github.com/jerryjliu/llama_index/compare/main...SlapDrone:llama_index:llm-predictor. Very much WIP, tests/mocks need to be updated as well.

Do you maintainers feel this is a helpful change once it works? And if so, should I open a draft PR with this work so there's expert input/feedback?

**Comment by mphipps2** [comment]
This was marked as completed. Was this actually completed? If so, can you point me to the solution?

**Comment by logan-markewich** [comment]
@mphipps2 yea, you can do this now, see here
https://docs.llamaindex.ai/en/stable/optimizing/advanced_retrieval/structured_outputs/query_engine.html
