### ISSUE TITLE
[Bug]: Indexing error after deleting then re-adding a page

### ISSUE THREAD

**Issue by Audino723** [run-llama/llama_index#7147]
### Bug Description

I am exploring a CRUD system using the llama index. The system utilizes the refresh_ref_docs() function. First I tried to delete a page from a document, and the system works. But after re-adding the deleted page, the system crashed because of KeyError. crashed

### Version

0.6.31

### Steps to Reproduce

`from llama_index import SimpleDirectoryReader, LLMPredictor, GPTVectorStoreIndex, load_index_from_storage
from llama_index.storage.storage_context import StorageContext
from llama_index.indices.service_context import ServiceContext
from llama_index import set_global_service_context
from langchain.chat_models import ChatOpenAI
import openai
import gradio as gr
import sys, os
import logging

from dotenv import load_dotenv
load_dotenv()

openai.api_key = os.environ["OPENAI_API_KEY"]

# enable INFO level logging
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

#define LLM service
llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.0, model_name="gpt-3.5-turbo"))
service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor)
set_global_service_context(service_context)

def load_index(directory_path):
     
    documents = SimpleDirectoryReader(directory_path, filename_as_id=True).load_data()
    print(f"loaded documents with {len(documents)} pages")
    
    try:
        # Rebuild storage context
        storage_context = StorageContext.from_defaults(persist_dir="./storage")
        # Try to load the index from storage
        index = load_index_from_storage(storage_context)
        logging.info("Index loaded from storage.")
    except FileNotFoundError:
        # If index not found, create a new one
        logging.info("Index not found. Creating a new one...")
        index = GPTVectorStoreIndex.from_documents(documents)
        # Persist index to disk
        index.storage_context.persist()
        logging.info("New index created and persisted to storage.")

    # Run refresh_ref_docs method to check for document updates
    refreshed_docs = index.refresh_ref_docs(documents, update_kwargs={"delete_kwargs": {'delete_from_docstore': True}})
    print(refreshed_docs)
    print('Number of newly inserted/refreshed docs: ', sum(refreshed_docs))

    index.storage_context.persist()
    logging.info("Index refreshed and persisted to storage.")

    return index, documents

def data_querying(input_text):
    # Load index
    index, documents = load_index("data")

    #queries the index with the input text
    response = index.as_query_engine().query(input_text)
    
    return response.response
`
1. Select a document
2. Use it as initial document
3. Delete a page
4. Then re-add that page
5. It will resulted in key error

**Comment by Audino723** [comment]
I tried to tweak your library by adding a try-catch in the refresh_ref_docs() function, like this
`def refresh_ref_docs(
        self, documents: Sequence[Document], **update_kwargs: Any
    ) -> List[bool]:
        "Refresh an index with documents that have changed.

        This allows users to save LLM and Embedding model calls, while only
        updating documents that have any changes in text or extra_info. It
        will also insert any documents that previously were not stored.
        """
        with self._service_context.callback_manager.as_trace("refresh"):
            refreshed_documents = [False] * len(documents)
            for I, document in enumerate(documents):
                try:
                    existing_doc_hash = self._docstore.get_document_hash(
                        document.get_doc_id()
                    )
                except for KeyError:
                    continue
                if existing_doc_hash != document.get_doc_hash():
                    self.update_ref_doc(
                        document, **update_kwargs.pop("update_kwargs", {})
                    )
                    refreshed_documents[i] = True
                elif existing_doc_hash is None:
                    self.insert(document, **update_kwargs.pop("insert_kwargs", {}))
                    refreshed_documents[i] = True

            return refreshed_documents`

Is this correct? Or only works for my circumstances

**Comment by logan-markewich** [comment]
@Audino723 you are using a pretty old version of llama-index. I think this works a little better in the latest versions 🤔 But there will be some minor breaking changes if you upgrade (I think? although maybe not)

**Comment by Audino723** [comment]
My bad, I forgot to upgrade my llama_index version. However, is there any way to update the docstore only by changing the document .pdf themselves? Without specifically calling the deleted pages

**Comment by logan-markewich** [comment]
As long as you set consistent doc_id's for the document objects, you should be able to use `index.refresh_ref_docs(documents)` (note that this only works with the base vector/docstores right now)
