### ISSUE TITLE
[Bug]: SubQuestionQueryEngine getting openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### ISSUE THREAD

**Issue by Yackadaisical** [run-llama/llama_index#7167]
### Bug Description

Question
My set up works for all other kinds of queries I been working on, but today I was trying to add SubQuestionQueryEngine to my code, and keep getting this error:

openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

This is basic outline of my code:

```
llm = AzureOpenAI(engine="try2", model="gpt-3.5-turbo-16k", temperature=0.2)

embedding_llm = LangchainEmbedding(
    OpenAIEmbeddings(
        model="text-embedding-ada-002",
        deployment="embedding_try1",
        openai_api_key=openai.api_key,
        openai_api_base=openai.api_base,
        openai_api_type=openai.api_type,
        openai_api_version=openai.api_version,
    ),
    embed_batch_size=1,
)

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embedding_llm,
)

set_global_service_context(service_context)

storage_context = StorageContext.from_defaults(
    persist_dir="docs_index_storage"
)

vector_query_engine = load_index_from_storage(
    storage_context=storage_context, 
    service_context=service_context
    ).as_query_engine()

query_engine_tools = [
    QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name="tissue_research", description="Provide information on consumer tissue paper."
        ),
    ),
]

query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context
)

answer = query_engine.query("What is the latest trends on tissue paper")

print(answer.get_formatted_sources())
```

I am using gpt-3.5-turbo-16k,, changed to gpt-3.5-turbo, but still giving me the same error. Updated llama-index to latest version, still same issue. 

I have used the exact same initializations as the SubQuestionQueryEngine documentation, the only difference is that I'm using Azure OpenAI LLM and embedding, yet ihenever I run .query it would raise openai.error.InvalidRequestError: Unrecognized request argument supplied: functions

### Version

0.7.17

**Comment by devstein** [comment]
@Yackadaisical `functions` is only supported by  by the [2023-07-01-preview api version](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference

**Comment by Yackadaisical** [comment]
Yes I am using the 2023-07-01-preview in my system variable for my openai api version already. Still getting the same error:

```
InvalidRequestError                       Traceback (most recent call last)
Cell In[9], line 3
      1 simple_question = "What are the files about?"
----> 3 answer = query_engine.query(simple_question)
      4 print(answer.get_formatted_sources())

File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\indices\query\base.py:23](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/indices/query/base.py:23), in BaseQueryEngine.query(self, str_or_query_bundle)
     21 if isinstance(str_or_query_bundle, str):
     22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23 response = self._query(str_or_query_bundle)
     24 return response

File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\query_engine\sub_question_query_engine.py:126](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/query_engine/sub_question_query_engine.py:126), in SubQuestionQueryEngine._query(self, query_bundle)
    122 def _query(self, query_bundle: QueryBundle) -> RESPONSE_TYPE:
    123     with self.callback_manager.event(
    124         CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    125     ) as query_event:
--> 126         sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
    128         colors = get_color_mapping([str(i) for i in range(len(sub_questions))])
    130         if self._verbose:

File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\question_gen\openai_generator.py:77](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/question_gen/openai_generator.py:77), in OpenAIQuestionGenerator.generate(self, tools, query)
     75 tools_str = build_tools_text(tools)
     76 query_str = query.query_str
...
    764         rbody, rcode, resp.data, rheaders, stream_error=stream_error
    765     )
    766 return resp

InvalidRequestError: Unrecognized request arguments supplied: function_call, functions
```

**Comment by Yackadaisical** [comment]
I am also getting error when using the OpenAIQuestionGenerator with Azure OpenAI, i suspect it also has to do with llama-index function call compatibility

```
InvalidRequestError                       Traceback (most recent call last)
Cell In[13], line 3
      1 simple_question = "How was financial performance in first half of 2023?"
----> 3 sub_questions = question_gen.generate(
      4     tools=tools,
      5     query=QueryBundle(simple_question),
      6 )
      8 print(sub_questions)

File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\question_gen\openai_generator.py:77](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/question_gen/openai_generator.py:77), in OpenAIQuestionGenerator.generate(self, tools, query)
     75 tools_str = build_tools_text(tools)
     76 query_str = query.query_str
---> 77 question_list = self._program(query_str=query_str, tools_str=tools_str)
     78 question_list = cast(SubQuestionList, question_list)
     79 return question_list.items

File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\program\openai_program.py:101](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/program/openai_program.py:101), in OpenAIPydanticProgram.__call__(self, *args, **kwargs)
     97 formatted_prompt = self._prompt.format(**kwargs)
     99 openai_fn_spec = to_openai_function(self._output_cls)
--> 101 chat_response = self._llm.chat(
    102     messages=[ChatMessage(role=MessageRole.USER, content=formatted_prompt)],
    103     functions=[openai_fn_spec],
    104     function_call=self._function_call,
    105 )
...
     87         )
     88 else:
     89     if model is None and engine is None:

InvalidRequestError: Must provide an 'engine' or 'deployment_id' parameter to create a
```

**Comment by Shubham-Sahay** [comment]
@devstein @Yackadaisical were you guys able to get resoution of this issue as i am facing same.

**Comment by akshaydigheQ** [comment]
> @devstein Yes I am using the 2023-07-01-preview in my system variable for my openai api version already. Still getting the same error:
> 
> ```
> InvalidRequestError                       Traceback (most recent call last)
> Cell In[9], line 3
>       1 simple_question = "What are the files about?"
> ----> 3 answer = query_engine.query(simple_question)
>       4 print(answer.get_formatted_sources())
> 
> File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\indices\query\base.py:23](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/indices/query/base.py:23), in BaseQueryEngine.query(self, str_or_query_bundle)
>      21 if isinstance(str_or_query_bundle, str):
>      22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
> ---> 23 response = self._query(str_or_query_bundle)
>      24 return response
> 
> File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\query_engine\sub_question_query_engine.py:126](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/query_engine/sub_question_query_engine.py:126), in SubQuestionQueryEngine._query(self, query_bundle)
>     122 def _query(self, query_bundle: QueryBundle) -> RESPONSE_TYPE:
>     123     with self.callback_manager.event(
>     124         CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
>     125     ) as query_event:
> --> 126         sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
>     128         colors = get_color_mapping([str(i) for i in range(len(sub_questions))])
>     130         if self._verbose:
> 
> File [c:\Users\jeffr\miniconda3\lib\site-packages\llama_index\question_gen\openai_generator.py:77](file:///C:/Users/jeffr/miniconda3/lib/site-packages/llama_index/question_gen/openai_generator.py:77), in OpenAIQuestionGenerator.generate(self, tools, query)
>      75 tools_str = build_tools_text(tools)
>      76 query_str = query.query_str
> ...
>     764         rbody, rcode, resp.data, rheaders, stream_error=stream_error
>     765     )
>     766 return resp
> 
> InvalidRequestError: Unrecognized request arguments supplied: function_call, functions
> ```

Which  gpt-3.5-turbo-16k model version are you using?
For me changing model version from 0301 to 0613 helped to resolve this issue

**Comment by fchenGT** [comment]
This is not a bug, your just need to set your azure deployment's model version to the latest, that supports openai's function call.
