### ISSUE TITLE
Enhancement Request: Weighted Edges for RAG on Biased Knowledge Graph

### ISSUE THREAD

**Issue by Baavro** [run-llama/llama_index#7201]
### Feature Description

We propose an enhancement to the Llama Index's **RAG over Knowledge Graph**  where weights can be assigned to the edges in the graph. This could potentially be achieved through two methods:

-Allowing manual input of weights to individual edges.
-Implementing an automated system that assigns weights based on predefined criteria or rules.

Additionally, we propose the ability to apply filters during retrieval, such as only retrieving edges with weights greater than a certain threshold.

### Reason

Our social media platform, which uses the Retrieval Augmented Generation provided by Llama Index, has unique requirements due to the nature of our data. Specifically, we need to bias our knowledge graph so that certain information, like user profile data, is given more weight than other data, such as user interactions with the platform.

### Value of Feature

The ability to assign weights to edges would greatly enhance the flexibility and applicability of Llama Index for various use-cases, especially those requiring a bias in data retrieval. This feature would not only benefit our social media platform but would also be advantageous to other users of Llama Index. With the ability to weight edges, users could apply filters during retrieval, such as only retrieving edges with weights greater than a certain threshold. This could improve the relevance and accuracy of the data retrieved, leading to better user experiences and outcomes across many applications.

**Comment by Disiok** [comment]
These seem like great ideas! @Baavro any interest in contributing some of these for the community? 😃

**Comment by heeyjunaid** [comment]
@Baavro are you working on PR for this feature? If not I can take this up.

**Comment by Baavro** [comment]
Sure you can take this up. Feel free to reach out to me if you need any help from my side
