### ISSUE TITLE
[Bug]: Index.vector_store.add uses old id

### ISSUE THREAD

**Issue by luka5132** [run-llama/llama_index#7267]
### Bug Description

I was rerunning some code that I wrote a couple months ago and got the following error when trying to add nodes to a docstore :
```python
AttributeError: 'TextNode' object has no attribute 'id'
````
The function I called was: 
```python 
first_index.docstore.add_documents(editted_nodes)
````

I saw that in `llama_index.schema.TextNode` _"id"_ was changed to _"id\_"_.  
However this is not updated in `llama_index.vector_stores.simple` .

### Version

0.8.2.post1

### Steps to Reproduce

```python
# data is a folder where some .txt files are stored
documents = SimpleDirectoryReader('data').load_data()
index = GPTVectorStoreIndex.from_documents([documents[0]])
index2 = GPTVectorStoreIndex.from_documents([documents[1]])
```

```python
# Get the docstore and nodes from the second index
index_nodes = index2.index_struct
nodes_dict = index_nodes.nodes_dict
cur_docstore = index2.docstore

#Store nodes in list 
#(Taken from function which also does other things)
editted_nodes = []
for node in nodes_dict:
  doc_node = cur_docstore.get_node(node)
  editted_nodes.append(doc_node)

#Try to add the nodes
index.vector_store.add(editted_nodes)
```

**Comment by logan-markewich** [comment]
@luka5132 `vector_store.add` expects a `NodeWithEmbedding` object, but you are inserting regular nodes.

I would probably advise to use `index.insert_nodes(edited_nodes)` or convert your nodes to the `NodeWithEmbedding` class before adding to the vector store

**Comment by luka5132** [comment]
@logan-markewich

Ah okay, that makes sense, thank you for your reply I'll change my code accordingly!
