### ISSUE TITLE
[Feature Request]: Framework and guide on creating datasets for {e2e, retrieval, LLM}

### ISSUE THREAD

**Issue by jon-chuang** [run-llama/llama_index#7310]
### Feature Description

Tasks:
- [ ] Add `Dataset` class

**Comment by nerdai** [comment]
Thanks @jon-chuang. Would you mind elaborating what you mean here by `Dataset` class. Are you trying to take in document and prepare it for the e2e pipeline: index -> retrieve -> query with and LLM?
