### ISSUE TITLE
How to concat GPTSimpleVectorIndex?

### ISSUE THREAD

**Issue by kenoharada** [run-llama/llama_index#737]
Hi!
I want to combine two GPTSimpleVectorIndex to one GPTSimpleVectorIndex.

List index is one way to do, but ListIndex queries each GPTSimpleVectorIndex.

I want to call one query over two GPTSimpleVectorIndex, so i want to combine two GPTSimpleVectorIndex to one two GPTSimpleVectorIndex. Is there any procedures?

Thanks!

**Comment by Disiok** [comment]
Hey @kenoharada, we don't have great support for this yet.

Is there reason that prevent you from building a new GPTSimpleVectorIndex over both set of documents you have? (Obviously this would be slightly costlier since you have to re-embed the documents).

**Comment by chrischjh** [comment]
It's because connecters such as pptx or docx only support to build index one by one file?

**Comment by ctle-vn** [comment]
@Disiok is it not possible to combine these indexes using a tree index? Something like: 

```
from llama_index import GPTTreeIndex, GPTSimpleVectorIndex

# Create subindices for books and lectures
books_index = GPTSimpleVectorIndex(books_documents)
lectures_index = GPTSimpleVectorIndex(lectures_documents)

# Set summary text for each subindex
books_index.set_text("summary_books")
lectures_index.set_text("summary_lectures")

# Create a tree index for routing
combined_index = GPTTreeIndex([books_index, lectures_index])

# Query the combined index
response = combined_index.query(
    "Your query here",
    mode="recursive",
    query_configs=...
)
```

**Comment by jerryjliu** [comment]
> It's because connecters such as pptx or docx only support to build index one by one file?

connectors such as .pptx or .docx just return Document objects ,and an index takes in a list of Document objects. so you can ingest these documents into one index

**Comment by ymansurozer** [comment]
Makes sense. But I am having a similar issue where my users are uploading documents and when they want to query multiple documents at once, I need to construct a ListIndex and send the query to it. However, ListIndex seems to not work as a `concat` but rather it is returning the most relevant index in its source nodes (but I am looking for most relevant chunks in the sub indices).

**Comment by kenoharada** [comment]
@Disiok Thank you for the reply.
>Is there reason that prevent you from building a new GPTSimpleVectorIndex over both set of documents you have? (Obviously this would be slightly costlier since you have to re-embed the documents).

I was hoping to find a more cost-effective solution for this issue. It's good to know that, as of now, there doesn't seem to be another method available and building a new GPTSimpleVectorIndex over both sets of documents is the current approach. 

Thank you very much

**Comment by thiswillbeyourgithub** [comment]
Also relevant in this issue so copy pasting :  
Surprisingly, the exact feature we seem to be looking for is mentionned here in langchain : https://python.langchain.com/en/latest/modules/indexes/vectorstores/examples/faiss.html
