### ISSUE TITLE
[Bug]: TreeIndex performance degraded badly since 0.8.0

### ISSUE THREAD

**Issue by jma7889** [run-llama/llama_index#7380]
### Bug Description

[#7236 ](https://github.com/jerryjliu/llama_index/pull/7236) contains the changes, likely the prompt changes that made the tree index query performance degrade to an unusable state. 

For my Q&A feature that uses Tree GPT35turbo before, it worked well up to 0.7.24, starting 0.8.0, it returns a lot more false positive results. For example, instead of having 10 yes for a bunch of questions, I saw 50 yes now, 40 were false positive. 

Here are some code snippets. They work well until #7236 and I did set default model to gpt3.5 all along. So it's not model change issue. 
```python
       ModelChoice.GPT35: {"model_name": "gpt-3.5-turbo", "chunk_size": 1024},

       predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.01, model_name=model_settings["model_name"]))

        retriever = TreeSelectLeafRetriever(index=self.index, child_branch_factor=self.tree_child_branch_factor)
        reader = SimpleDirectoryReader(input_dir=self.input_dir)
        documents = reader.load_data()
        index = TreeIndex.from_documents(documents, service_context=service_context)

``` 

### Version

llama-index-0.8.5

### Steps to Reproduce

Do some treeindex based queries and compare the results between 0.7.24 and 0.8.x, the 0.8.x performs much worse

**Comment by jma7889** [comment]
It's nice to see ai bot can analyze the bug. However, in this case, it might not be right because inserter.py change was not in the break point PR. It's likely prompts issues.

**Comment by logan-markewich** [comment]
@jma7889 Yea the bot did it's best haha

Can you provide anything more specific? Like a reproducible test case would help immensely. I'm using a few of our test documents but so far it seems to work fine for me

**Comment by logan-markewich** [comment]
Can you also maybe explain your use case for the tree index? We are trying to collect the ways that people use it, the index itself is very tech-debt ridden, and we've been considering deprecating it if other features support the same use-case :)

**Comment by jma7889** [comment]
@logan-markewich Thanks for pointing to response synthesis. I will do some investigation on that. I don't  currently have a simple way to distill the code and data to repeat the issue since the way it works involving combining doc, context and questions in a dynamic way.

**Comment by logan-markewich** [comment]
@jma7889 Right, but if it was possible to share the document and question(s) that cause the issue, I can also help debug :)

**Comment by jma7889** [comment]
From conversion with @logan-markewich : 
hmmm so here's something fun

If I take just the context (the thing between the `----` bars) from the working message 0.7.24 message, and paste it into the 0.8.10 message, then the answer is correct

One thing I'm noticing here is that the context itself is slightly different. In newer versions of llama-index, the default text-splitter changed to a sentence splitter.

So, now the retrieved context is more complete (i.e sentences are not cut off) whereas before the context is chapped off on the front and back.

You can still modify the node_parser to use the old text splitter. Likely the cutoff sentences were making it feel less unsure?

But maybe more generically, my suggestion is to use a custom prompt template here, since this use case seems extremely specific?

A quick change to the system prompt made the query work for this task

```python
ChatMessage(role="system", content="You are an expert Q&A system that is trusted around the world.\nAlways answer the query using the provided context information, and not prior knowledge. Your answers will always be either 'yes' or 'no'. If you are not sure about the answer, please respond 'no'."),
```

You can setup prompt templates like this in the latest version of llama_index, using the system prompt I described above

```python
from llama_index.llms.base import ChatMessage
from llama_index.prompts.base import ChatPromptTemplate

text_qa_messages = [
    ChatMessage(role="system", content="You are an expert Q&A system that is trusted around the world.\nAlways answer the query using the provided context information, and not prior knowledge. Your answers will always be either 'yes' or 'no'. If you are not sure about the answer, please respond 'no'."),
    ChatMessage(
        content=(
            "Context information is below.\n"
            "---------------------\n"
            "{context_str}\n"
            "---------------------\n"
            "Given the context information and not prior knowledge, "
            "answer the query.\n"
            "Query: {query_str}\n"
            "Answer: "
        ),
        role=MessageRole.USER,
    ),
]

text_qa_template = ChatPromptTemplate(message_templates=TEXT_QA_PROMPT_TMPL_MSGS)
...
query_engine = index.as_query_engine(text_qa_template=text_qa_template)
```

**Comment by jma7889** [comment]
Continued conversation with Logan:

Well, I think the root of the issue is actually the change in the text splitter. 

But yes, changing that prompt to be slightly more custom seems to help! And you could have a different system prompt for each type of task too, which would probably more your program more reliable 🙂
----
got it, but since splitter change is the right thing to do, we have to seek alternative prompts to make the gpt more affirmative on its response.
----
the custom prompt is in, seems it's better than before, but not yet the same as 7.24. The 1st question still returns yes. Do you still have the prompt or log that make it No with 8.11?  
I will try to tune it based on yours  'Business process is described as People, systems, and processes that assist or accomplish an organizational goal. Does the above describe a service that needs to be performed by the contractor?'

On the other hand, maybe now it's more true to the questions, so the bug might really be the questions.

**Comment by jma7889** [comment]
As a summary, upgrading to 0.8.x may have great impact of responses for treeindex queries due to text splitter and prompts change. The system tends to become very sensitive to the content and prompts. Using custom prompts and questions may align the results more towards the 0.7.x behavior. 

Since the changes in 0.8.x are right things to do, this issue is not a bug. However, I do hope future versions would tweak default prompt template further so that the response is more correct for a wider range of queries (to be truly better than 0.7.x). 

Many thanks to @logan-markewich for his help, I hereby close the issue.

**Comment by jma7889** [comment]
I think I have enough evidence to reopen the issue.

Hi @logan-markewich Logan,
I have closed the issue in github, but am still investigating. I found many fact based questions are degraded too and found something interesting.

Tested question: 
query_template=Context: If you are not sure about the answer, please respond step by step
Question: How many years and months is the base period of performance? How many option years?

Correct answer:
The base period of performance is 12 months, including a 60-day transition period. There are four option years in addition to the base period.

Tree index, factor 2, gpt3.5 turbo, rests are all default.
What I found:
0.8.13: answer not found
0.7.24: correct answer
0.8.13 with tree index created in 0.7.24: correct answer

Seems something is not right in the index after 0.8.0. Index that is created with 0.7.24 works well with 8.13 code, but the index created with 8.13 does not work well. Does it imply a bug in index related code? Maybe a text splitter issue? 
I can give you the original txt document if it helps.

**Comment by jma7889** [comment]
Yes, the issue still exists with 0.9.13
