### ISSUE TITLE
[Bug]: Module not found

### ISSUE THREAD

**Issue by deboboy** [run-llama/llama_index#7417]
### Bug Description

Getting this error trying the Google Calendar agent example:

ModuleNotFoundError: No module named 'llama_index'

### Version

0.7.8

### Steps to Reproduce

Deployment via streamlit; here’s the requirements.txt:
pip install llama-index==0.7.8 llama-hub

**Comment by deboboy** [comment]
Your recommendations fixed the llama_index error...

But now I'm getting this error:
"ModuleNotFoundError: No module named 'llama_hub'"

FYI: the app is deployed on Streamlit; here's my requirements.text:
llama-hub
llama-index
langchain
streamlit
bs4
html2text
openai
tiktoken
faiss-cpu
hyperlink

**Comment by deboboy** [comment]
The llama_hub not found error resolved with a Streamlit app reboot...

Now getting this error:
ModuleNotFoundError: No module named 'googleapiclient'

FYI that this is the Llama Index sample I'm attempting to build:
https://github.com/emptycrown/llama-hub/blob/main/llama_hub/tools/notebooks/google_calendar.ipynb

**Comment by logan-markewich** [comment]
you'll need to add `googleapiclient` to your reqs as well

**Comment by aizzataffero** [comment]
did u resolve it? i have same issue as well

**Comment by logan-markewich** [comment]
@aizzataffero I think solutions for both issues in this thread work. Have you tried them?

**Comment by milinaire25** [comment]
I am getting this error message but when i run pip install llama_index the requirement is already satisfied
  import llama_index
ModuleNotFoundError: No module named 'llama_index'

**Comment by logan-markewich** [comment]
Use a fresh venv, and make sure you have no files or folders named `llama_index`

```
python -m venv venv
source venv/bin/activate
pip install llama_index 
```

**Comment by wang-ailing** [comment]
If you use VScode and Anaconda, you can try:
1. Open the cmd outside VScode
2. Activate the virtual environment you created in the cmd
3. Pip install the package
4. Use "pip show llama_index" to valid
5. You will see:
![图片](https://github.com/run-llama/llama_index/assets/128135735/aa2aa9ed-7146-4cd9-b6c8-41ecb8525405)

Then fresh your VScode and use the correct Python Interrept
Over!
