### ISSUE TITLE
[Feature Request]: Mask PII in SQL result before synthesizing response

### ISSUE THREAD

**Issue by Liam-Coyle** [run-llama/llama_index#7457]
### Feature Description

The current implementation of `BaseSQLTableQueryEngine` uses an LLM in 2 places:

1. Text query -> SQL query
2. SQL result -> Synthesised response

The input data in either of these cases could contain PII data which you may not want to pass to the LLM for compliance reasons. 

This feature would mask PII data in:

1. The text query (for example using a `query_transform`)
2. The SQL result (and also un-mask the response after synthesis)

Hacky examples for each to illustrate further:

1. Something _like_ this (which uses a method like in `NERPIINodePostprocessor`):
```python
class PIIQueryTransform(BaseQueryTransform):
    """PII query transform.

    Mask the PII in the query.

    """

    def _mask_pii(self, text: str) -> Tuple[str, Dict]:
        """Mask PII in text."""
        new_text = text
        ner = pipeline("ner", grouped_entities=True) # Would load this once somewhere, not every time
        response = ner(text)
        mapping = {}
        for entry in response:
            entity_group_tag = f"[{entry['entity_group']}_{entry['start']}]"
            new_text = new_text.replace(entry["word"], entity_group_tag).strip()
            mapping[entity_group_tag] = entry["word"]
        return new_text, mapping

    def _run(self, query_bundle: QueryBundle, metadata: Dict) -> QueryBundle:
        """Run query transform."""
        query_str, _ = self._mask_pii(query_bundle.query_str)
        return QueryBundle(
            query_str=query_str,
            custom_embedding_strs=query_bundle.custom_embedding_strs,
        )
```

2. Something _like_ this:
```python
raw_response_str, metadata = self._sql_database.run_sql(sql_query_str)
raw_response_str, mapping = _mask_pii(raw_response_str)
...
response_str = _unmask_pii(response_str, mapping)
response = Response(response=response_str, metadata=metadata)
return response
```

### Reason

No post-processing step currently exists after a SQL query is run, and the existing `NERPIINodePostprocessor` is not applicable to query engines which interact with a database. This means any SQL results (and text queries to be converted to SQL) which contain PII are sent to the LLM as context, which may be a compliance issue in some cases.  

### Value of Feature

This would stop (or at least reduce) PII data being sent to an LLM when using a SQL query engine.

**Comment by Liam-Coyle** [comment]
I've just started using Llamaindex, so I'm not very familiar with the codebase and don't know what the preferred way to implement this would be. In the case of the SQL result masking, I'm guessing some sort of callback would be preferable. Any suggestions?

**Comment by Gunnvant** [comment]
Is this still open, I can pick it up.

**Comment by Liam-Coyle** [comment]
> Is this still open, I can pick it up.

Hi, yes I've not got a chance to work on this just yet so feel free to pick it up.

**Comment by Gunnvant** [comment]
@logan-markewich any guidance on, which module this functionality should go and the recommended approach to adding tests

**Comment by logan-markewich** [comment]
@Gunnvant Tests might be tricky, but they can go here:
https://github.com/jerryjliu/llama_index/blob/main/tests/indices/struct_store/test_sql_query.py

The actual implementation should probably be in the base query engine here
https://github.com/jerryjliu/llama_index/blob/3c427fc727eb3127cd2bcd4931f41b72c3d13ea9/llama_index/indices/struct_store/sql_query.py#L215

**Comment by Gunnvant** [comment]
@logan-markewich The feature would require additional dependencies such as hugging face or spacy for ner. Are we okay with it?

**Comment by logan-markewich** [comment]
@Gunnvant see the existing PII modules as an example maybe

https://github.com/jerryjliu/llama_index/blob/70138110658850e15d1e7ecb78cb396fb1661e55/llama_index/indices/postprocessor/pii.py#L102

Optional dependencies are done as try/except imports
