### ISSUE TITLE
[Feature Request]: Add native support for Amazon Bedrock embeddings and LLM models

### ISSUE THREAD

**Issue by xrtechspot** [run-llama/llama_index#7507]
### Feature Description

It is possible to add native support for Amazon Bedrock embeddings and LLM models (https://aws.amazon.com/bedrock/), to ramain in Llamaindex ecosystem and not use Langchain for this ?

https://python.langchain.com/docs/integrations/providers/bedrock

Thank you

### Reason

Use Llamaindex ecosystem and not load other libraries

**Comment by acastro2** [comment]
Hey, supporting it natively would be beautiful. However, I finally managed to make it work using the latest changes Amazon pushed to `langchain` and `boto3`:

```python
    bedrock = Bedrock(model_id='amazon.titan-text-express-v1')

    llm = LangChainLLM(llm=bedrock)

    embed_model = BedrockEmbeddings(model_id='amazon.titan-embed-text-v1')

    service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)

    set_global_service_context(service_context)
```

**Comment by krrishdholakia** [comment]
Hey @xrtechspot this is possible via the LlamaIndex/LiteLLM integration - https://docs.llamaindex.ai/en/stable/examples/llm/litellm.html#litellm-supports-100-llm-apis-anthropic-replicate-huggingface-togetherai-cohere-etc-complete-list

```python
from llama_index.llms import LiteLLM

messages = [
    ChatMessage(
        role="system", content="You are a pirate with a colorful personality"
    ),
    ChatMessage(role="user", content="Tell me a story"),
]

llm = LiteLLM("bedrock/anthropic.claude-v2")
resp = llm.stream_chat(messages)
```

Llama Index docs: https://docs.llamaindex.ai/en/stable/examples/llm/litellm.html#litellm-supports-100-llm-apis-anthropic-replicate-huggingface-togetherai-cohere-etc-complete-list

LiteLLM docs: https://docs.litellm.ai/docs/
