### ISSUE TITLE
[Optimization]: Speed up the function inside `VectorIndexRetriever` class (`_build_node_list_from_query_result`)

### ISSUE THREAD

**Issue by A-baoYang** [run-llama/llama_index#7515]
### System Info
- OS: `Darwin CFH00509436 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64`
- Python version: `3.8.12`
- package version: `llama-index==0.8.12`

### Situation
- Slow when running `query_engine.query()` and found out the bottleneck in `VectorIndexRetriever._build_node_list_from_query_result`
- Need 30 seconds when running `self._docstore.docs` (it'll load all the articles from database or local index directory)

<img width="1157" alt="image" src="https://github.com/jerryjliu/llama_index/assets/9716977/9f0c454d-2d15-414b-89cb-fcf1aef7e179">

### Solution
Revise to 
```
if (not self._vector_store.stores_text) or (
    isinstance(query_result.nodes[i], (ImageNode, IndexNode))
):
```
solution as the same in https://github.com/jerryjliu/llama_index/pull/3435/commits/51bec97118c10dbc2fd7e98e3181a69de5b3e302

after revising the code, it became fast and almost finished in 1 second:

<img width="1164" alt="image" src="https://github.com/jerryjliu/llama_index/assets/9716977/4aeab853-5661-41c9-82ec-15f19fe64e49">

### Version

0.8.12

### Steps to Reproduce

```python
query_engine = RetrieverQueryEngine.from_args(
    retriever=retriever,
    response_synthesizer=response_synthesizer,
    response_mode="simple_summarize",
    text_qa_template=my_template,
    service_context=service_context,
    streaming=True,
)
query_engine.query("some text...")
```

##### Before

Slow when running `query_engine.query()` and found out the bottleneck in `VectorIndexRetriever._build_node_list_from_query_result`

<img width="1157" alt="image" src="https://github.com/jerryjliu/llama_index/assets/9716977/9f0c454d-2d15-414b-89cb-fcf1aef7e179">

##### After 

Became fast and almost finished in 1 second

<img width="1164" alt="image" src="https://github.com/jerryjliu/llama_index/assets/9716977/4aeab853-5661-41c9-82ec-15f19fe64e49">

**Comment by logan-markewich** [comment]
@A-baoYang Thanks for the analysis here! I definitely encourage you to open a PR 💪🏻

**Comment by A-baoYang** [comment]
@logan-markewich  Yes, I opened a PR here: https://github.com/jerryjliu/llama_index/pull/7516
