### ISSUE TITLE
[Question]: nl2graphquery.

### ISSUE THREAD

**Issue by ghost** [run-llama/llama_index#7583]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

@wey-gu 
While using the nl2graphquery i am getting this error. For the context i havent index anything but this nl2graphquery suppose to give the answer from the knowledge graph itself or do I need to index some document for reference. Please help to find the solution

Param: {}Error message: Error found in optimization stage: IndexNotFound: No valid index found
Thanks.

**Comment by logan-markewich** [comment]
@yashdeepyds you need to have some existing knowledge graph to connect to. Can you share more details?

**Comment by wey-gu** [comment]
Could you plz share your code? In case it’s kgquery engine no index should be required indeed.

**Comment by yashdeepyds** [comment]
Before doing this i have created a knowledge graph.

from llama_index.query_engine import RetrieverQueryEngine
from llama_index.retrievers import KnowledgeGraphRAGRetriever
from llama_index.storage.storage_context import StorageContext
from llama_index.graph_stores import NebulaGraphStore
from llama_index.llms import OpenAI
from IPython.display import Markdown, display

space_name = "abc"
edge_types = ["has_column"]
tags = ["table", "column"]

graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

graph_rag_retriever_with_nl2graphquery = KnowledgeGraphRAGRetriever(
    storage_context=storage_context,
    service_context=service_context,
    llm=llm,
    verbose=True,
    with_nl2graphquery=True,
)

query_engine_with_nl2graphquery = RetrieverQueryEngine.from_args(
    graph_rag_retriever_with_nl2graphquery, service_context=service_context
)

response = query_engine_with_nl2graphquery.query(
    "what is this graph about",
)
display(Markdown(f"<b>{response}</b>"))

**Comment by yashdeepyds** [comment]
Hi @wey-gu 
Any suggestions on this .
Thanks.
