### ISSUE TITLE
[Feature Request]: LLMs without function calling (e.g. Llama 2) doesn't work out of the box with JSON Query Engine

### ISSUE THREAD

**Issue by weilintuye95** [run-llama/llama_index#7587]
### Feature Description

Create a thin wrapper around [`json_path_response_str`](https://github.com/jerryjliu/llama_index/blob/644c034a249fa359181f8ebe988b8c2b93401814/llama_index/indices/struct_store/json_query.py#L105) to either:
1) help user parse the .predict() output to extract the json path 
2) or raise a less cryptic error about the LLM output being wrongly formatted.

The fix could also go within the function `default_output_processor`: https://github.com/jerryjliu/llama_index/blob/644c034a249fa359181f8ebe988b8c2b93401814/llama_index/indices/struct_store/json_query.py#L48 #

### Reason

I'm getting an error trying to use Llama 2 + JSON Query Engine (running the example here with pretty much everything the same except service_context where I use my Llama 2 pipeline https://gpt-index.readthedocs.io/en/latest/examples/query_engine/json_query_engine.html).
The error looks something like `Exception: Parse error at 1:4 near token` which hints that there is some parsing issue somewhere.

Looking at the source code, it's because Llama 2 doesn't have function calling and [this line](https://github.com/jerryjliu/llama_index/blob/644c034a249fa359181f8ebe988b8c2b93401814/llama_index/indices/struct_store/json_query.py#L105) uses the LLM to create json_path_response_str (which should be a jsonpath query). 

Without function calling, Llama 2 is returning a long string, which means Llama Index will error out with a not-too-useful exception. Users need to be aware of this issue before they realize that it can be tackled by creating new output_processor to make their LLM output concise (even this doesn't always work)

### Value of Feature

Make it clearer for users to troubleshoot their errors when using JSON Query Engine or just help them deal with the issue directly (maybe regex?)

**Comment by weilintuye95** [comment]
[ parse(llm_output)](https://github.com/run-llama/llama_index/blob/644c034a249fa359181f8ebe988b8c2b93401814/llama_index/indices/struct_store/json_query.py#L48) attempts to parse the llm_output but llm_output with llama 2 can often contain additional text e.g. (Sure, I'm happy to help, blablabla).

You're gonna want to a) make the prompt strict so that the LLM outputs the same additional text most of the time, and b) add some additional code to remove those additional words before it hits the `parse(llm_output)` line

**Comment by dylan1218** [comment]
@nerdai if no one is actively working on this one I can take this one up:

Will address two concepts:
(1) An attempt to parse/find the JSON if more than JSON is returned from the LLM. (maybe an optional flag should be implemented to let the user decide if they want this operation to be performed?, tbd on the flag.)
(2) Clearer error handling if (1) fails (or if flag is implemented straight to a clear error if non-JSON is passed)
