### ISSUE TITLE
[Bug]: Query does not work when adding metadata using QdrantVectorStore

### ISSUE THREAD

**Issue by matteosdocsity** [run-llama/llama_index#7698]
### Bug Description

When adding metadata via every method listed [here](https://gpt-index.readthedocs.io/en/latest/core_modules/data_modules/documents_and_nodes/usage_documents.html#customizing-documents), the query does not return the correct node. Without metadata everything works fine.

### Version

0.8.27

### Steps to Reproduce

adding document.metadata = {'filename': '<doc_file_name>', 'id': '<doc_id>', 'subject': '<doc_subject>'}, makes the query not working anymore. Without passing metadata the retrieval from the query is fine and the result as expected.
Tried also to test via excluded_embed_metadata_keys and/or excluded_llm_metadata_keys, but nothing changed.

Using OpenAI completion_model="gpt-3.5-turbo" and embed_model="text-embedding-ada-002", and QdrantVectorStore

**Comment by matteosdocsity** [comment]
nothing changed @dosu-bot, basically it appears that metadata wrongly influence the query result. My goal is to use metadata only as MetadataFilters, not to be queried by default nothing than document text

**Comment by matteosdocsity** [comment]
@dosu-bot the problem is related also for new indexes. so first method does not work. How to change the _build_query_filter in order to exclude metadata from influencing the query results?

**Comment by bmax** [comment]
@matteosdocsity Can you post a full reproducible code snippet?

**Comment by matteosdocsity** [comment]
@bmax basically is what I shared, after passing any document.metadata queries tested before without metadata stop working and give no results

**Comment by yasyf** [comment]
I think I'm seeing this too. Adding any metadata to nodes -> 0 results from Qdrant. Weirdly, if I remove the default filter that llama index adds for the set of IDs, this bug goes away.
