### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#7704]
### Feature Description

Make llama-index compartible with nemoguardrails. 

Link: https://github.com/NVIDIA/NeMo-Guardrails

### Reason

Guardrails add a layer before the input prompt is passed to the LLM where the programmer can design a conversational flow in a deterministic manner. Especially for applications like abusive language and inappropriate prompts. The layer added before the query_engine class wrapping the llm could give developers using llama-index freedom to do much more. It will also give the library a competitive edge. 
The library is compartible with langchain llms already.

### Value of Feature

It will offer developers a way to handle some user input in a predictable or deterministic way instead of relying on system messages which may not work in every case or fine-tuning which is expensive. Developers can also design their own conversational flows using the library!

**Comment by nerdai** [comment]
Thanks for the suggestion @gich2009! Going to discuss with the team on this, but the timing is about right as we're considering improvements to our Prompting methods.
