### ISSUE TITLE
[Bug]: Error when running MetadataExtractionSEC.ipynb

### ISSUE THREAD

**Issue by huangjia2019** [run-llama/llama_index#7720]
### Bug Description

llama_index\docs\examples\metadata_extraction\MetadataExtractionSEC.ipynb -- this is a demo program, my llama-index    version is    0.8.29.post1

hitting error --- 

Traceback (most recent call last):
  File "c:\Users\MetaData\With_Metadata.py", line 123, in <module>
    response = final_engine.query(
               ^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\indices\query\base.py", line 23, in query
    response = self._query(str_or_query_bundle)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\query_engine\sub_question_query_engine.py", line 126, in _query
    sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\question_gen\llm_generators.py", line 56, in generate
    prediction = self._llm_predictor.predict(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\llm_predictor\base.py", line 140, in predict
    messages = prompt.format_messages(llm=self._llm, **prompt_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\prompts\base.py", line 105, in format_messages
    prompt = self.format(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\prompts\base.py", line 97, in format
    prompt = self.output_parser.format(prompt)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Venv\llamaindex_venv\Lib\site-packages\llama_index\question_gen\output_parser.py", line 17, in format
    raise NotImplementedError()
NotImplementedError

### Version

0.8.29.post1

### Steps to Reproduce

Just run

### Relevant Logs/Tracbacks

```shell
refer to the main track
```

**Comment by huangjia2019** [comment]
This is a GPT generated answer, not real answer.
Need to show me code.

**Comment by DanDesignLi** [comment]
Having the same issue

----> [1](vscode-notebook-cell:/home/**/Desktop/llamaindex_test/llama.ipynb#X43sZmlsZQ%3D%3D?line=0) nodes = vector_auto_retriever.retrieve("*question*")

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/base_retriever.py:22](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/base_retriever.py:22), in BaseRetriever.retrieve(self, str_or_query_bundle)
     20 if isinstance(str_or_query_bundle, str):
     21     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 22 return self._retrieve(str_or_query_bundle)

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py:83](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/auto_retriever.py:83), in VectorIndexAutoRetriever._retrieve(self, query_bundle)
     80 schema_str = VectorStoreQuerySpec.schema_json(indent=4)
     82 # call LLM
---> 83 output = self._service_context.llm_predictor.predict(
     84     self._prompt,
     85     schema_str=schema_str,
     86     info_str=info_str,
     87     query_str=query_bundle.query_str,
     88 )
     90 # parse output
     91 assert self._prompt.output_parser is not None

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/llm_predictor/base.py:140](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/llm_predictor/base.py:140), in LLMPredictor.predict(self, prompt, **prompt_args)
    137 self._log_template_data(prompt, **prompt_args)
    139 if self._llm.metadata.is_chat_model:
--> 140     messages = prompt.format_messages(llm=self._llm, **prompt_args)
    141     messages = self._extend_messages(messages)
    142     chat_response = self._llm.chat(messages)

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/prompts/base.py:105](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/prompts/base.py:105), in PromptTemplate.format_messages(***failed resolving arguments***)
    103 """Format the prompt into a list of chat messages."""
    104 del llm  # unused
--> 105 prompt = self.format(**kwargs)
    106 return prompt_to_messages(prompt)

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/prompts/base.py:97](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/prompts/base.py:97), in PromptTemplate.format(***failed resolving arguments***)
     95 prompt = self.template.format(**all_kwargs)
     96 if self.output_parser is not None:
---> 97     prompt = self.output_parser.format(prompt)
     98 return prompt

File [~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/output_parser.py:18](https://file+.vscode-resource.vscode-cdn.net/home/**/Desktop/llamaindex_test/~/miniconda3/envs/ai/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/auto_retriever/output_parser.py:18), in VectorStoreQueryOutputParser.format(***failed resolving arguments***)
     16 def format(self, prompt_template: str) -> str:
     17     del prompt_template
---> 18     raise NotImplementedError()

NotImplementedError:

**Comment by Ashish5869** [comment]
I was following this doc [Extracting Metadata for Better Document Indexing and Understanding](https://gpt-index.readthedocs.io/en/stable/examples/metadata_extraction/MetadataExtractionSEC.html)

Here we are using code for question_gen 

```from llama_index.question_gen.llm_generators import LLMQuestionGenerator
from llama_index.question_gen.prompts import DEFAULT_SUB_QUESTION_PROMPT_TMPL

service_context = ServiceContext.from_defaults(llm=llm, node_parser=node_parser)
question_gen = LLMQuestionGenerator.from_defaults(
    service_context=service_context,
    prompt_template_str="""
        Follow the example, but instead of giving a question, always prefix the question 
        with: 'By first identifying and quoting the most relevant sources, '. 
        """
    + DEFAULT_SUB_QUESTION_PROMPT_TMPL,
)
```
remove this code or don't pass question_gen then there is no error.

**Comment by jeremi** [comment]
This seems to have been fixed and worked well for me.
