### ISSUE TITLE
[Bug]: RedisVectorStore cannot set a redis_url with a password

### ISSUE THREAD

**Issue by checkking** [run-llama/llama_index#7782]
### Bug Description

I use redis as my llama-index vector store. When I start with RedisVectorStore with no password redis, it is ok. But, when I set a password, I got an error. Here is my code:
1) no password ok
`        redisURL = "redis://localhost:6379"
        index_name = "yd_vector"
        vector_store = RedisVectorStore(
            index_name=index_name,
            index_prefix="llama",
            redis_url=redisURL,
            overwrite=True,
        )`

2) when redis need password(the password I set is correct), no ok:
`        #redisURL = "redis://:redis20230901@localhost:6379"
        redisURL = "redis://localhost:6379"
        index_name = "yd_vector"
        vector_store = RedisVectorStore(
            index_name=index_name,
            index_prefix="llama",
            redis_url=redisURL,
            overwrite=True,
        )`

a error accurred:

redis.exceptions.AuthenticationError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
<img width="1465" alt="image" src="https://github.com/jerryjliu/llama_index/assets/3713123/f90d6257-c8e2-47a2-a21b-8c330d770f2a">

There my has a bug, please help me.

### Version

0.8.29.post1

### Steps to Reproduce

just use  the class RedisVectorStore and with a password redis-url, like 
`        redisURL = "redis://localhost:6379"
        index_name = "yd_vector"
        vector_store = RedisVectorStore(
            index_name=index_name,
            index_prefix="llama",
            redis_url=redisURL,
            overwrite=True,
        )``

### Relevant Logs/Tracbacks

```shell
vector_store = RedisVectorStore(
                   ^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/llama_index/vector_stores/redis.py", line 112, in __init__
    check_redis_modules_exist(self._redis_client)
  File "/data/anaconda3/lib/python3.11/site-packages/llama_index/readers/redis/utils.py", line 46, in check_redis_modules_exist
    installed_modules = client.module_list()
                        ^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/commands/core.py", line 5885, in module_list
    return self.execute_command("MODULE LIST")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/client.py", line 505, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/data/anaconda3/lib/python3.11/site-packages/redis/connection.py", line 271, in connect
    self.on_connect()
  File "/data/anaconda3/lib/python3.11/site-packages/redis/connection.py", line 335, in on_connect
    auth_response = self.read_response()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/connection.py", line 493, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 15, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/anaconda3/lib/python3.11/site-packages/redis/_parsers/resp2.py", line 38, in _read_response
    raise error
redis.exceptions.AuthenticationError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
```

**Comment by checkking** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for bringing this issue to our attention. It seems like there's a misunderstanding about how to use the password with Redis in the LlamaIndex.
> 
> In the LlamaIndex codebase, the `RedisVectorStore` class does support password authentication for Redis. However, the password should be included in the `redis_url` string itself, not as a separate parameter.
> 
> Here is how you should format your `redis_url`:
> 
> ```python
> redisURL = "redis://:your_password@localhost:6379"
> ```
> 
> Replace `your_password` with your actual Redis password. This URL includes the password for the Redis instance, which is specified after a colon and before the `@` symbol.
> 
> Here is how you can use it in your code:
> 
> ```python
> redisURL = "redis://:your_password@localhost:6379"
> index_name = "yd_vector"
> vector_store = RedisVectorStore(
>     index_name=index_name,
>     index_prefix="llama",
>     redis_url=redisURL,
>     overwrite=True,
> )
> ```
> 
> Please give this a try and let us know if you continue to experience any issues.
> 
> As a side note, I'm unable to view the image you've attached as I can't process images. In the future, please provide any error messages or logs as text.
> 
> Best, Dosu
> 
> ## Sources
> * [llama_index/vector_stores/redis.py](https://github.com/jerryjliu/llama_index/blob/main/llama_index/vector_stores/redis.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

The answer you given is not work, as I have tried before and got a error. Please Help me.

**Comment by tylerhutcherson** [comment]
@checkking is your database configured to need a password? How so?

**Comment by tylerhutcherson** [comment]
This happens typically when your database does not require a password. You'd need to configure it to do so.
