### ISSUE TITLE
[Feature Request]: vLLM support for faster inference using llama-index

### ISSUE THREAD

**Issue by DivyanshuMishra123** [run-llama/llama_index#7818]
### Feature Description

I was finding a workaround to load LLM through the vLLM Library for faster inference. But when i was trying to initialize the HuggingFaceLLM from llama-index i was not able to give this pretrained model.Below is the code to load the model through vLLM and initialize it through HuggingFaceLLM from llama-index .

from vllm import LLM, SamplingParams
llm = LLM(model='meta-llama/Llama-2-7b-hf')

name = "meta-llama/Llama-2-7b-hf"
tokenizer = AutoTokenizer.from_pretrained(name, use_auth_token=auth_token)

from llama_index.llms import HuggingFaceLLM 
llm = HuggingFaceLLM(context_window=4096,
                    max_new_tokens=1024,
                    system_prompt=system_prompt,
                    query_wrapper_prompt=query_wrapper_prompt,
                    model=llm,
                    tokenizer=tokenizer)

The error logs for the same  ::

AttributeError                            Traceback (most recent call last)
Cell In[13], line 5
      2 from llama_index.llms import HuggingFaceLLM
      3 # Create a HF LLM using the llama index wrapper 
      4 #from langchain.llms import SelfHostedHuggingFaceLLM
----> 5 llm = HuggingFaceLLM(context_window=4096,
      6                     max_new_tokens=1024,
      7                     system_prompt=system_prompt,
      8                     query_wrapper_prompt=query_wrapper_prompt,
      9                     model=llm,
     10                     tokenizer=tokenizer
     11                  #   generate_kwargs={"temperature": 0.7, "do_sample": False},
     12                 #    tokenizer_kwargs={"max_length": 4096},
     13                     )
     14                    # generate_kwargs={"return_dict_in_generate":True})

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/llms/huggingface.py:56, in HuggingFaceLLM.__init__(self, context_window, max_new_tokens, system_prompt, query_wrapper_prompt, tokenizer_name, model_name, model, tokenizer, device_map, stopping_ids, tokenizer_kwargs, tokenizer_outputs_to_remove, model_kwargs, generate_kwargs, callback_manager)
     51 self.model = model or AutoModelForCausalLM.from_pretrained(
     52     model_name, device_map=device_map, **model_kwargs
     53 )
     55 # check context_window
---> 56 config_dict = self.model.config.to_dict()
     57 model_context_window = int(
     58     config_dict.get("max_position_embeddings", context_window)
     59 )
     60 if model_context_window and model_context_window < context_window:
AttributeError: 'LLM' object has no attribute 'config'

Is there any workaround for this??

**Comment by DivyanshuMishra123** [comment]
I modified the code to add config attribute.But now getting error as below :: 


AttributeError                            Traceback (most recent call last)
File <timed exec>:1

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/indices/query/base.py:23, in BaseQueryEngine.query(self, str_or_query_bundle)
     21 if isinstance(str_or_query_bundle, str):
     22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23 response = self._query(str_or_query_bundle)
     24 return response

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py:175, in RetrieverQueryEngine._query(self, query_bundle)
    169         nodes = self.retrieve(query_bundle)
    171         retrieve_event.on_end(
    172             payload={EventPayload.NODES: nodes},
    173         )
--> 175     response = self._response_synthesizer.synthesize(
    176         query=query_bundle,
    177         nodes=nodes,
    178     )
    180     query_event.on_end(payload={EventPayload.RESPONSE: response})
    182 return response

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/response_synthesizers/base.py:125, in BaseSynthesizer.synthesize(self, query, nodes, additional_source_nodes)
    120     query = QueryBundle(query_str=query)
    122 with self._callback_manager.event(
    123     CBEventType.SYNTHESIZE, payload={EventPayload.QUERY_STR: query.query_str}
    124 ) as event:
--> 125     response_str = self.get_response(
    126         query_str=query.query_str,
    127         text_chunks=[
    128             n.node.get_content(metadata_mode=MetadataMode.LLM) for n in nodes
    129         ],
    130     )
    132     additional_source_nodes = additional_source_nodes or []
    133     source_nodes = list(nodes) + list(additional_source_nodes)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/response_synthesizers/compact_and_refine.py:34, in CompactAndRefine.get_response(self, query_str, text_chunks, **response_kwargs)
     30 # use prompt helper to fix compact text_chunks under the prompt limitation
     31 # TODO: This is a temporary fix - reason it's temporary is that
     32 # the refine template does not account for size of previous answer.
     33 new_texts = self._make_compact_text_chunks(query_str, text_chunks)
---> 34 response = super().get_response(
     35     query_str=query_str, text_chunks=new_texts, **response_kwargs
     36 )
     37 return response

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py:49, in Refine.get_response(self, query_str, text_chunks, **response_kwargs)
     45 for text_chunk in text_chunks:
     46     if prev_response_obj is None:
     47         # if this is the first chunk, and text chunk already
     48         # is an answer, then return it
---> 49         response = self._give_response_single(
     50             query_str,
     51             text_chunk,
     52         )
     53     else:
     54         response = self._refine_response_single(
     55             prev_response_obj, query_str, text_chunk
     56         )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/response_synthesizers/refine.py:80, in Refine._give_response_single(self, query_str, text_chunk, **response_kwargs)
     78 for cur_text_chunk in text_chunks:
     79     if response is None and not self._streaming:
---> 80         response = self._service_context.llm_predictor.predict(
     81             text_qa_template,
     82             context_str=cur_text_chunk,
     83         )
     84     elif response is None and self._streaming:
     85         response = self._service_context.llm_predictor.stream(
     86             text_qa_template,
     87             context_str=cur_text_chunk,
     88         )

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/llm_predictor/base.py:91, in LLMPredictor.predict(self, prompt, **prompt_args)
     89 else:
     90     formatted_prompt = prompt.format(llm=self._llm, **prompt_args)
---> 91     response = self._llm.complete(formatted_prompt)
     92     output = response.text
     94 logger.debug(output)

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/llms/base.py:256, in llm_completion_callback.<locals>.wrap.<locals>.wrapped_llm_predict(_self, *args, **kwargs)
    251 with wrapper_logic(_self) as callback_manager:
    252     event_id = callback_manager.on_event_start(
    253         CBEventType.LLM, payload={EventPayload.PROMPT: args[0]}
    254     )
--> 256     f_return_val = f(_self, *args, **kwargs)
    257     if isinstance(f_return_val, Generator):
    258         # intercept the generator and add a callback to the end
    259         def wrapped_gen() -> CompletionResponseGen:

File ~/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/llama_index/llms/huggingface.py:123, in HuggingFaceLLM.complete(self, prompt, **kwargs)
    120     full_prompt = f"{self._system_prompt} {full_prompt}"
    122 inputs = self.tokenizer(full_prompt, return_tensors="pt")
--> 123 inputs = inputs.to(self.model.device)
    125 # remove keys from the tokenizer if needed, to avoid HF errors
    126 for key in self._tokenizer_outputs_to_remove:

AttributeError: 'LLM' object has no attribute 'device'.


Below is my modified code:

from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.llms import HuggingFaceLLM
from transformers import AutoConfig
from vllm import LLM, SamplingParams

name = "meta-llama/Llama-2-7b-chat-hf"
llm = LLM(model='meta-llama/Llama-2-7b-chat-hf')
tokenizer = AutoTokenizer.from_pretrained(name, use_auth_token=auth_token)
config = AutoConfig.from_pretrained(name, use_auth_token=auth_token)
llm.config = config
llm = HuggingFaceLLM(context_window=4096,
                    max_new_tokens=1024,
                    system_prompt=system_prompt,
                    query_wrapper_prompt=query_wrapper_prompt,
                    model=llm,
                    tokenizer=tokenizer,
                    device_map={'':0}
                    )
embeddings=LangchainEmbedding(
    HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2"))
service_context = ServiceContext.from_defaults(
    chunk_size=2048,
    llm=llm,
    embed_model=embeddings)
set_global_service_context(service_context)

documents = loader.load(file_path=Path('macquarie_broker-credit-guidelines.pdf'), metadata=True)
index = VectorStoreIndex.from_documents(documents)
query_engine = index.as_query_engine()
response = query_engine.query('What is the credit guidelines of genuine savings requirement \
                                in Contributions & Genuine Savings section?')

What should be my next approach?

**Comment by DivyanshuMishra123** [comment]
Even after removing the parameter   -->device_map={'':0}   inside HuggingFaceLLM classs iam still facing the same error
AttributeError: 'LLM' object has no attribute 'device'

**Comment by nerdai** [comment]
Hey @DivyanshuMishra123, I think maybe you can try creating your own `CustomLLM` around vLLM interface. https://github.com/run-llama/llama_index/blob/main/llama_index/llms/custom.py

**Comment by vikramsoni2** [comment]
You can run the VLLM as OpenAI Compatible API, and then just use the OpenAILike like this:

`
from llama_index.llms import OpenAILike

base_url = "https://your-vllm-openai-compatible-server-url/v1"
model    = "TheBloke/Llama-2-13B-chat-AWQ" # incase using this mdoel, you can query the vllm url for /v1/models to see the model name

vllm = OpenAILike(
    api_key="EMPTY",
    api_base=base_url,
    model = model ,
    max_tokens=4096,
    stream=True
)`
