### ISSUE TITLE
[Feature Request]: Support for DeepInfra

### ISSUE THREAD

**Issue by shauryr** [run-llama/llama_index#7824]
### Feature Description

[DeepInfra](https://deepinfra.com/) is pay per use service like OpenAI but way cheaper - 50% cheaper than gpt3.5-turbo for llama 2

Right now they support [openai python api.](https://deepinfra.com/meta-llama/Llama-2-70b-chat-hf/api?example=openai-python)

So I tried to test my luck, what happens if you use it with llama-index.

```python
llm = OpenAI(model="meta-llama/Llama-2-70b-chat-hf")
service_context = ServiceContext.from_defaults(llm=llm)
```

You get this trace of error -

```
-> service_context = ServiceContext.from_defaults(llm=llm)

[llama_index/indices/service_context.py:168]
prompt_helper = prompt_helper or _get_default_prompt_helper(
--> 168     llm_metadata=llm_predictor.metadata,
    169     context_window=context_window,
    170     num_output=num_output,
    171 )

[llama_index/llm_predictor/base.py:119]
--> 119     return self._llm.metadata

[llama_index/llms/openai.py:113]
--> 113         context_window=openai_modelname_to_contextsize(self._get_model_name()),

[llama_index/llms/openai_utils.py:192]
--> 192     raise ValueError(
ValueError: Unknown model: meta-llama/Llama-2-70b-chat-hf. Please provide a valid OpenAI model name.Known models are: gpt-4, gpt-4-32k, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo
```

### Reason

DeepInfra seems like it is fairly new to the game. 

### Value of Feature

Their product is great! and it is much cheaper than gpt-4 with similar performance. As they add more models to their endpoints I imagine more and more people start using them as a better and cheaper alternative to OAI's GPT.

**Comment by logan-markewich** [comment]
@shauryr you maybe need to change the api_base parameter to point to deepinfra?

**Comment by shauryr** [comment]
yup I did that above this.

**Comment by prince-paulraj** [comment]
I am interested in this as well, llama_index with deepInfra - llama 2 model...

The following code snippet from deepInfra working fine but want the integration from llama_index. Can we get this feature ASAP?

`
import openai
import os

# Point OpenAI client to our endpoint
openai.api_key = "#"
openai.api_base = "https://api.deepinfra.com/v1/openai"

chat_completion = openai.ChatCompletion.create(
    model="meta-llama/Llama-2-70b-chat-hf",
    messages=[{"role": "user", "content": "Hello"}],
)

print(chat_completion.choices[0].message.content)
`

**Comment by nerdai** [comment]
Closing this as I believe this can be implemented using `OpenAILike` https://github.com/run-llama/llama_index/blob/main/llama_index/llms/openai_like.py
