### ISSUE TITLE
[Bug]: Cannot find metadata from RetrieverQueryEngine

### ISSUE THREAD

**Issue by playerjamesbattleground** [run-llama/llama_index#7825]
### Bug Description

I'm trying to use the sql join query engine, by using a sql query engine and a vector store engine together. The example I'm following is this link

https://gpt-index.readthedocs.io/en/stable/examples/query_engine/SQLJoinQueryEngine.html#define-query-engines-set-as-tools

When configuring the RetrieverQueryEngine for the vector store with below snippet

```
query_engine = SQLJoinQueryEngine(
    s_engine_tool, retriever_query_engine, service_context=service_context
)
s_engine_tool.metadata
retriever_query_engine.metadata
```

the retriever_query_engine in type of RetrieverQueryEngine doesn't have a `metadata` attribute, hence the code errors out 

This is referring to the code from repo, as shown, it looks like always assuming other query tool would have metadata set, however in this case, there is none

https://github.com/jerryjliu/llama_index/blob/b8699461cc922a9302df9cc3690131e596fa2470/llama_index/query_engine/sql_join_query_engine.py#L284

### Version

0.8.30

### Steps to Reproduce

configure the vector store retriever as

```
storage_context = StorageContext.from_defaults(vector_store=vector_store)
vector_index = VectorStoreIndex([], storage_context=storage_context)
vector_retriever = VectorIndexAutoRetriever(index=vector_index, vector_store_info=vector_store_info)
retriever_query_engine = RetrieverQueryEngine.from_args(
  retriever=vector_retriever,
  service_context=service_context,
)
```

Up to the step from the document about configuring 

```
query_engine = SQLJoinQueryEngine(
    s_engine_tool, retriever_query_engine, service_context=service_context
)
```

then it would error out saying `'RetrieverQueryEngine' object has no attribute 'metadata'`

**Comment by playerjamesbattleground** [comment]
I'm actually referring to this line

```
 # TODO: see if this can be consolidated with logic in RouterQueryEngine
        metadatas = [self._sql_query_tool.metadata, self._other_query_tool.metadata]
```

where the _other_query_tool doesn't have metadata as an attribute from their types

**Comment by logan-markewich** [comment]
The fix here is just wrapping the retriever query engine with the QueryEngineTool class

**Comment by logan-markewich** [comment]
Although I swear I just ran this notebook yesterday, will double check

**Comment by playerjamesbattleground** [comment]
> Collaborator

Can confirm this way works, might be just an extra line to be added to notebook. 

fix sinppet

```
r_engine_tool = QueryEngineTool.from_defaults(
  query_engine=retriever_query_engine,
  description="functionality the retriver_query_engine can provide"
)
```
