### ISSUE TITLE
[Feature Request]: `HuggingFaceLLM` supporting Hugging Face Inference API or GGUF file type

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#7905]
### Feature Description

I am trying to use https://huggingface.co/TheBloke/Llama-2-13B-Ensemble-v5-GGUF/blob/main/llama-2-13b-ensemble-v5.Q4_K_M.gguf with `HuggingFaceLLM(model_name="insert GGUF model")` from `llama_index==0.8.36`.

When trying to use a GGUF model:

1. `HuggingFaceLLM` outsources to `transformers.AutoModelForCausalLM`
2. `transformers.AutoModelForCausalLM` throws this error:

```none
OSError: <model> does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack.
```

So GGUF and I also believe the Hugging Face Inference API isn't supported.

The request: support Hugging Face Inference API (what I really want) or local GGUF files behind `HuggingFaceLLM`.

### Reason

It's useful to be able to stay close to Hugging Face.

### Value of Feature

Developers on laptops can't always run larger models or multiple models locally.

**Comment by logan-markewich** [comment]
Does huggingace load gguf files? Isn't that for stuff like llama.cpp?

**Comment by jamesbraza** [comment]
I guess, ignore the local file usage, I am most interested in Inference API.  I think Hugging Face Inference API doesn't care if it's GGUF, GGML, etc. unless I am wrong.

https://huggingface.co/docs/api-inference/quicktour sorta implies any model can work.

**Comment by logan-markewich** [comment]
Oh, `HuggingFaceLLM` isn't the inference api, it's downloading and running a model locally in most cases

**Comment by logan-markewich** [comment]
It's using AutoModel and AutoTokenizer

Or you can optionally load the model/tokenizer yourself and pass that in

**Comment by jamesbraza** [comment]
Yeah sorry, I had a misunderstanding there per `HuggingFaceLLM`.

Just to confirm, if I wanted to have LlamaIndex hit the Hugging Face Inference API, is that supported yet?  If yes, can you link any docs on it?

**Comment by logan-markewich** [comment]
@jamesbraza not supported yet. I don't see support for it in langchain either actually.

You'd have to implement a CustomLLM class to call that properly

**Comment by jamesbraza** [comment]
Looks like we need a new LLM subclass for [`huggingface_hub.InferenceClient`](https://huggingface.co/docs/huggingface_hub/main/en/guides/inference) to access models over the internet
