### ISSUE TITLE
[Feature Request]: example for `LocalAI`

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#7907]
### Feature Description

[`LocalAI`](https://localai.io/) has an OpenAI compatible API.  So one can game an `OpenAI` wrapper to work with `LocalAI`. In fact, that's how [`langchain` does it](https://github.com/langchain-ai/langchain/blob/v0.0.305/libs/langchain/langchain/embeddings/localai.py#L123).

I think to support `LocalAI`, one just needs to use `llama_index.llms.OpenAI(api_base="http://localhost:8080/v1", api_key="stub")` or `OPENAI_API_BASE` environment variable.

It would be cool if there was a brief demo IPython Notebook for this, somewhere in LlamaIndex.

### Reason

`LocalAI` is a nice alternative to `Ollama` or `Llama.cpp` for running models from Hugging Face.

### Value of Feature

Lots of people use `LocalAI`. It was also previously requested [here](https://github.com/jerryjliu/llama_index/issues/1772#issuecomment-1628735329).

**Comment by jamesbraza** [comment]
Actually trying this out, I am getting denied by [`openai_modelname_to_contextsize`](https://github.com/jerryjliu/llama_index/blob/v0.8.36/llama_index/llms/openai_utils.py#L189) lookup.  Will need to make a backdoor for this

**Comment by jamesbraza** [comment]
@logan-markewich do you mind re-opening this one until I get an example created for `LocalAI`?

**Comment by logan-markewich** [comment]
@jamesbraza open!

**Comment by nerdai** [comment]
Closing this since it seems that PR #7913 resolved this.

**Comment by jamesbraza** [comment]
@nerdai no this is blocked by https://github.com/run-llama/llama_index/pull/8241, there's not a `LocalAI` demo yet
