### ISSUE TITLE
[Feature Request]: `extras_require` in `setup.py`

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#7944]
### Feature Description

You can install packages with `pip install package[extra]` or `pip install package[extra1,extra2]`.

This is enabled via "extras": https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies.  For reference, check SQL Alchemy's list: https://github.com/sqlalchemy/sqlalchemy/blob/rel_2_0_21/setup.cfg#L43

It would be cool to add these to LlamaIndex, so we can do things like `pip install llama-index[llama-cpp-python,ollama]` which will add `requests` and `llama-cpp-python` to the installation list.

### Reason

Convenience of installs, and letting LlamaIndex take care of dependency ranges.

### Value of Feature

- Benefitting end users integrating LlamaIndex into their `requirements` files.
- Upstreaming `data_requirements.txt` into `setup.py`, removing a file from the repo

```python
setup(
    ...,
    extras_require={
        "google": ["google-api-python-client", "google-auth-httplib2", "google-auth-oauthlib"],
        "vellum": ["vellum-ai==0.0.15"]
    }
)
```

**Comment by logan-markewich** [comment]
This is on my todo list :) In fact, we need to migrate to a full pyproject.toml setup and move off of setup.py

**Comment by jamesbraza** [comment]
+1 to `pyproject.toml` only! Glad to hear this is on your list 👍

**Comment by jamesbraza** [comment]
https://github.com/huggingface/transformers/blob/v4.34.0/setup.py#L97 has a DRY way of specifying dependency ranges that work for both `install_requires` and `extras_require`, just sharing

**Comment by nerdai** [comment]
I think we're good to close this right, as we've moved to `pyproject.toml`. Just confirming?

**Comment by jamesbraza** [comment]
No, I think we don't have many extras in use, there's just `local_models`, `postgres`, and `query_tools`.  Ideally there's an `extra` present for each LLM type.

**Comment by logan-markewich** [comment]
I feel like thats a bit overboard, especially since many integrations are a single package? Just my two cents

**Comment by jamesbraza** [comment]
Yeah it's up to you!  It enables clients to have super readable requirements 😄 :

```
llama-index[openai,huggingface-inference]
```

Like it's very clear what LLM subsets are being used.

We can also close this, in favor of people just adding them overtime

**Comment by jamesbraza** [comment]
Hi @dosubot thanks. I think this is still a valid request, but I can defer to others on the matter

**Comment by sansmoraxz** [comment]
Might want to refer to how langchain does it

https://github.com/langchain-ai/langchain/blob/da7bca21785490acc5d8307245e24d574b86da48/libs/langchain/pyproject.toml#L205-L227
