### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'llama_index.utilities'

### ISSUE THREAD

**Issue by MrKimmich** [run-llama/llama_index#7958]
### Bug Description

After installing llama-index and trying to import SimpleDirectoryReader getting **ModuleNotFoundError: No module named 'llama_index.utilities'**

### Version

0.8.39

### Steps to Reproduce

1. install llama-index using` pip install llama-index`
2. try importing SimpleDirectoryReader as  from `llama_index import SimpleDirectoryReader`

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-a501c962bf85> in <cell line: 1>()
----> 1 from llama_index import SimpleDirectoryReader
      2 
      3 reader = SimpleDirectoryReader(input_files=["data_processed.txt"])
      4 docs = reader.load_data()
      5 for doc in docs:

1 frames
/usr/local/lib/python3.10/dist-packages/llama_index/indices/common/struct_store/base.py in <module>
     21 from llama_index.schema import BaseNode, MetadataMode
     22 from llama_index.text_splitter import TextSplitter
---> 23 from llama_index.utilities.sql_wrapper import SQLDatabase
     24 from llama_index.utils import truncate_text
     25 

ModuleNotFoundError: No module named 'llama_index.utilities'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

**Comment by xiongjian79** [comment]
from llama_hub.tools.database import DatabaseToolSpec

db_spec = DatabaseToolSpec(
    scheme="postgresql",  # Database Scheme
    host="localhost",  # Database Host
    port="5432",  # Database Port
    user="postgres",  # Database User
    password="x",  # Database Password
    dbname="your_db",  # Database Name
)

tools = db_spec.to_tool_list()
for tool in tools:
    print(tool.metadata.name)
    print(tool.metadata.description)
    print(tool.metadata.fn_schema)

Using from llama_hub will meet this problem ,how to avoid it?

Traceback (most recent call last):
  File "/Users/xiongjian/PycharmProjects/MyAgent/app/tools/db_connector.py", line 8, in <module>
    from llama_hub.tools.database import DatabaseToolSpec
  File "/Users/xiongjian/miniconda3/lib/python3.11/site-packages/llama_hub/tools/database/__init__.py", line 2, in <module>
    from llama_hub.tools.database.base import (
  File "/Users/xiongjian/miniconda3/lib/python3.11/site-packages/llama_hub/tools/database/base.py", line 5, in <module>
    from llama_index.utilities.sql_wrapper import SQLDatabase
ModuleNotFoundError: No module named 'llama_index.utilities'

Process finished with exit code 1
