### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShyamFaguna** [run-llama/llama_index#7962]
### Bug Description

Hi,
I'm having trouble importing the GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext classes from the llama_index package. I've installed the package using pip, but I'm getting an ImportError when trying to import the classes, it was working fine till yesterday. Is there any known issue or workaround for this problem? I've followed the documentation, but I can't seem to resolve the ImportError.

Used :
pip install llama-index
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext

Error:
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-8-3ce7d01dd77c> in <cell line: 7>()
      5 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
      6 
----> 7 from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext
      8 from llama_index.llms import HuggingFaceLLM
      9 

1 frames

/usr/local/lib/python3.10/dist-packages/llama_index/indices/common/struct_store/base.py in <module>
     21 from llama_index.schema import BaseNode, MetadataMode
     22 from llama_index.text_splitter import TextSplitter
---> 23 from llama_index.utilities.sql_wrapper import SQLDatabase
     24 from llama_index.utils import truncate_text
     25 

ModuleNotFoundError: No module named 'llama_index.utilities'

### Version

(0.8.39)

### Steps to Reproduce

pip install llama-index
from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext

### Relevant Logs/Tracbacks

```shell
ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-8-3ce7d01dd77c> in <cell line: 7>()
      5 logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
      6 
----> 7 from llama_index import GPTVectorStoreIndex, SimpleDirectoryReader, ServiceContext
      8 from llama_index.llms import HuggingFaceLLM
      9 

1 frames

/usr/local/lib/python3.10/dist-packages/llama_index/indices/common/struct_store/base.py in <module>
     21 from llama_index.schema import BaseNode, MetadataMode
     22 from llama_index.text_splitter import TextSplitter
---> 23 from llama_index.utilities.sql_wrapper import SQLDatabase
     24 from llama_index.utils import truncate_text
     25 

ModuleNotFoundError: No module named 'llama_index.utilities'
```

**Comment by jerryjliu** [comment]
we're patching it soon, sorry about that. was a broken release

**Comment by aadhil96** [comment]
facing same issue ? when it will be solved ?

**Comment by jerryjliu** [comment]
try `pip install llama-index==0.8.39.post2`

**Comment by avinashag7878** [comment]
It is fixed now. Thanks.

**Comment by ShyamFaguna** [comment]
Thanks for the quick resolution @jerryjliu working now.

**Comment by aadhil96** [comment]
why am getting this error ? 

index = VectorStoreIndex.from_documents(documents, chunk_size=512)

`RetryError: RetryError[<Future at 0x7cc47a020df0 state=finished raised RateLimitError>] `

**Comment by logan-markewich** [comment]
@whyusharthwhy try a clean reinstall or a fresh venv. Also make sure you have no file or folder named `llama_index` in your current working directory

@aadhil96 either you have a ton of documents, or you don't have a paid openai account (the free tokens are severely rate limited)
