### ISSUE TITLE
[Bug]:" JsonPathParserError" when using "JSONQueryEngine"

### ISSUE THREAD

**Issue by terilias** [run-llama/llama_index#7975]
### Bug Description

Hello, 
Thank you for your great work on LlamaIndex and for open-sourcing it along with examples and videos! 
I am trying to use the "JSONQueryEngine" with my JSON file following the steps described in the [relative example](https://gpt-index.readthedocs.io/en/latest/examples/query_engine/json_query_engine.html). In the step of using the engine to query the index, I get this error: `JsonPathParserError: Parse error at 1:37 near token & (&)`
I search for the error and I saw that maybe it's due to the [library import](https://stackoverflow.com/questions/66951665/jsonpath-error-when-making-a-filter-query-parse-error-at-ss-near-token-s). Am I doing something wrong?

### Version

0.8.39.post2

### Steps to Reproduce

1. Read a JSON object from a file using JSON module: `with open('file.json', 'r') as f:  json_value = json.load(f)` Use this as the json_value parameter of the JSONQueryEngine constructor.
2. Provide a string that contains the json schema. Then convert it to dict using `json.loads(json_schema_string)`
3. Create a JSONQueryEngine using the two dictionaries from the steps above.
4. Use query() method on the JSONQueryEngine.

### Relevant Logs/Tracbacks

```shell
File ~/anaconda3/lib/python3.11/site-packages/jsonpath_ng/parser.py:83, in JsonPathParser.p_error(self, t)
     82 def p_error(self, t):
---> 83     raise JsonPathParserError('Parse error at %s:%s near token %s (%s)'
     84                               % (t.lineno, t.col, t.value, t.type))

JsonPathParserError: Parse error at 1:37 near token & (&)
```

**Comment by terilias** [comment]
@dosu-bot the query string I am passing to the query engine is "Suggest me five pillows. Keep in mind that I love nature and especially the mountains." Strangerly the error does not generate when I use another query.

**Comment by EmanuelCampos** [comment]
The documentation example ran successfully, can you share your JSON schema and JSON value mocked and some code snippets, then we can reproduce your example

**Comment by terilias** [comment]
Hello,
Yes, I am sending you a PDF file generated from a Jupyter Notebook that contains all of them.
[Example with error.pdf](https://github.com/run-llama/llama_index/files/12847571/Example.with.error.pdf)

**Comment by EmanuelCampos** [comment]
@terilias instead of the PDF can you send the notebook file please?

**Comment by terilias** [comment]
Yes. GitHub doesn't support notebook uploading, so I am sending you a WeTransfer link: https://we.tl/t-YLBOFae0ew
