### ISSUE TITLE
MockLLMPredictor is not showing last_token_usage

### ISSUE THREAD

**Issue by kashiftriffort** [run-llama/llama_index#7976]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I am trying to find last_token_usage using MockLLMPredictor. Below is my code, however somehow running this code shows that last_token_usage is not found in MockLLMPredictor.

```
BASE_DIR: str = os.path.dirname(__file__)

documents = SimpleDirectoryReader(os.path.join(BASE_DIR, "data")).load_data()
print(documents)

llm_model_name = "gpt-4"
llm_predictor_mock = MockLLMPredictor(max_tokens=256, llm=OpenAI(temperature=0, model_name=llm_model_name))
embed_model_mock = MockEmbedding(embed_dim=1536)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor_mock, embed_model=embed_model_mock)


# Vector is cheaper than raw indexed data
# index = GPTSimpleVectorIndex.from_documents(documents, service_context=service_context)
index = GPTListIndex.from_documents(documents, service_context=service_context)

# Run the mock call first
# You can *predict* how many tokens each GPT Index operation
# (build index, query index) can consume! (within 5-10% error)
query_str = "Why was Ketanji Brown Jackson nominated?"

print("query_str = {}".format(query_str))

response = index.query(query_str, service_context=service_context)

print(response)

# In this example, after querying the index, you can access the last_token_usage attribute
# of the MockLLMPredictor instance to get the number of tokens used in the query.
last_token_usage = llm_predictor_mock.last_token_usage

last_embedding_usage = embed_model_mock.last_token_usage
```

**Comment by logan-markewich** [comment]
@kashiftriffort the bot is pretty much correct -- MockLLMPredictor is not maintained, and you should use MockLLM and the token counting handler

https://gpt-index.readthedocs.io/en/stable/core_modules/supporting_modules/cost_analysis/usage_pattern.html

**Comment by Jgerardopine** [comment]
The link you provided does not exist. Whay is the new attributes? and why is LlamaINdex documentaiton still containing MockLLMPredictor and exmaples:

https://gpt-index.readthedocs.io/en/v0.6.8/reference/service_context/llm_predictor.html

**Comment by logan-markewich** [comment]
@Jgerardopine my link works fine? You arr linking to v0.6.8 docs. We are on 0.8.65 now

**Comment by logan-markewich** [comment]
You should be using MockLLM these days 

from llama_index.llms import MockLLM
