### ISSUE TITLE
[Bug]: Metadata length is not a good proxy for maximum chunk size

### ISSUE THREAD

**Issue by aerickson-clt** [run-llama/llama_index#7980]
### Bug Description

I have a `Document` defined below with a metadata field `extra_info` that is often quite long.  This is important in my RAG application because the user needs to see some meta info about the source that should not be part of retrieval or synthesis.

```
Document(text=row['Answer_Response'],
                  ret.append(Document(text=row['Answer_Response'],
                            metadata={"question": row["Question"], "source": "asource", "source_uid": row["ID"],
                                      "extra_info": extra_info},
                   excluded_llm_metadata_keys=['extra_info', 'source_uid', 'source'],
                   excluded_embed_metadata_keys=['extra_info', 'source_uid', 'source'],
                   metadata_template="{key}: {value}",
                   text_template="{metadata_str}\n{content}"))
```

The sentence splitter does not like this document because the metadata is too long for the chunk size. Since this fields is excluded from LLM and EMBED, I don't think it should be counted.

### Version

839post1

### Steps to Reproduce

Make a document with long metadata, give a smaller chunk size, split the nodes with the sentence splitter (or other meta-data aware splitter).

**Comment by logan-markewich** [comment]
I agree, been meaning to address this

**Comment by logan-markewich** [comment]
@aerickson-clt the tricky part is, there's two metadata modes to consider, LLM and Embed

My take is that every embed model either handles truncation fine (i.e. local huggingface models) or has a huge context window (openai is 8196)

So, splitting should mostly concern LLM metadata? Or this could be configurable too I suppose

**Comment by aerickson-clt** [comment]
I think that both the size of `node.get_content(metadata_mode=MetadataMode.LLM)` and `node.get_content(metadata_mode=MetadataMode.EMBED)` are quite important when designing a system.  Embedding too much text may dilute some semantic you are trying to capture, while stuffing too much into the context will make your synthesizer do things it wasn't designed to do.  It's all a bit loosey-goosey though, since you can break this with node postprocessing, but starting out with node.get_content behaving in a predictable way is helpful.

Perhaps ideally you would have a maximum chunk size for each of these, but a simpler solution would be to just make sure they are both small enough.  Minimally fixing the code below you could pass `node.get_metadata_str(metadata_mode=MetadataMode.LLM` and `node.get_metadata_str(metadata_mode=MetadataMode.EMBED)` (as well as `text`).  Your effective chunk size is then `chunk_size - max(metadata_llm_len, metadata_embed_len)`.

    def split_text_metadata_aware(self, text: str, metadata_str: str) -> List[str]:
        metadata_len = len(self.tokenizer(metadata_str))
        effective_chunk_size = self.chunk_size - metadata_len
        if effective_chunk_size <= 0:
            raise ValueError(
                f"Metadata length ({metadata_len}) is longer than chunk size "
                f"({self.chunk_size}). Consider increasing the chunk size or "
                "decreasing the size of your metadata to avoid this."
            )
        elif effective_chunk_size < 50:
            print(
                f"Metadata length ({metadata_len}) is close to chunk size "
                f"({self.chunk_size}). Resulting chunks are less than 50 tokens. "
                "Consider increasing the chunk size or decreasing the size of "
                "your metadata to avoid this.",
                flush=True,
            )

        return self._split_text(text, chunk_size=effective_chunk_size)

gets called from here

```            
def get_nodes_from_node(
    node: BaseNode,
    text_splitter: SplitterType,
    include_metadata: bool = True,
    include_prev_next_rel: bool = False,
    ref_doc: Optional[BaseNode] = None,
) -> List[TextNode]:
    """Get nodes from document."""
    if include_metadata:
        if isinstance(text_splitter, MetadataAwareTextSplitter):
            text_splits = text_splitter.split_text_metadata_aware(
                text=node.get_content(metadata_mode=MetadataMode.NONE),
                metadata_str=node.get_metadata_str(),
            )
```

**Comment by logan-markewich** [comment]
@aerickson-clt great idea. Will try to get that in before lunch 😉
