### ISSUE TITLE
[Bug]: sub_nodes from nodes or documents?

### ISSUE THREAD

**Issue by kevon217** [run-llama/llama_index#7986]
### Bug Description

I'm trying to implement the recursive retriever as documented on https://gpt-index.readthedocs.io/en/stable/examples/retrievers/recursive_retriever_nodes.html, but when I get my sub_nodes, they don't seem to actually comprise chunks smaller than the parent base_node. When I look at the text field of a sub_node, it is the same as the base_node. Maybe I'm misunderstanding something about chunk references, but was hoping for a little guidance.

### Version

0.8.31

### Steps to Reproduce

I pretty much employed the same steps as demonstrated in the LlamaIndex docs. Although, it seemed odd that you call get_nodes_from_documents() on the base_node. Should it be using get_node_from_nodes() ? 

```
node_parser = SimpleNodeParser.from_defaults(chunk_size=1024)
base_nodes = node_parser.get_nodes_from_documents(docs)
# set node ids to be a constant
for idx, node in enumerate(base_nodes):
    node.id_ = f"node-{idx}"

sub_chunk_sizes = [128, 256, 512]
sub_node_parsers = [
    SimpleNodeParser.from_defaults(chunk_size=c) for c in sub_chunk_sizes
]

all_nodes = []
for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)

    # also add original node to node
    original_node = IndexNode.from_text_node(base_node, base_node.node_id)
    all_nodes.append(original_node)
```

**Comment by kevon217** [comment]
Seems my problem was that I was passing a text_splitter to SimpleNodeParser rather than just specifying chunk_size. I'm able to successfully get different chunk sizes now.

```
    def init_sub_node_parsers(self):
        self.sub_chunk_sizes = self.config.text_splitter.sub_chunk_size
        self.sub_node_parsers = []
        for c in self.sub_chunk_sizes:
            self.sub_node_parsers.append(
                SimpleNodeParser.from_defaults(
                    chunk_size=c,
                    # text_splitter=self.tokentext_splitters[c]
                )
            )
```

I do have another question though about the llamaindex docs example below. Should the original_node be a TextNode instead of an IndexNode? Maybe I'm still not understanding how the recursive parser and retriever work, but my impression was that the IndexNodes are used to find the TextNode which is what will ultimately be given to the LLM.

```
sub_chunk_sizes = [128, 256, 512]
sub_node_parsers = [
    SimpleNodeParser.from_defaults(chunk_size=c) for c in sub_chunk_sizes
]

all_nodes = []

for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)

    # also add original node to node
    original_node = IndexNode.from_text_node(base_node, base_node.node_id)
    all_nodes.append(original_node)
```

**Comment by Othmane796** [comment]
+1 
The use of recursive retriever is clear in this [Recursive Retriever + Query Engine Demo](https://docs.llamaindex.ai/en/stable/examples/query_engine/pdf_tables/recursive_retriever.html). But I'm also missing something  on the example of [small-to-big retriever](https://docs.llamaindex.ai/en/stable/examples/retrievers/recursive_retriever_nodes.html#). 

Curious, why should both type of nodes (small and big) be indexed ? Are IndexNode are ignored during indexing? otherwise that might mess with the retrieval accuracy no ?
