### ISSUE TITLE
[Question]: How can I specify to use Azure openAI model for finetunning in `OpenAIFinetuneEngine`

### ISSUE THREAD

**Issue by AchintyaX** [run-llama/llama_index#8004]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I wanted to finetune a model on Azure OpenAI, but I am not seeing any way in the documentation to specify to use Azure OpenAI for finetuning. 
I can see that we can directly using `AzureOpenAI` for LLM to be passed but can't see a way to specify the same for the finetuning job

**Comment by AchintyaX** [comment]
Hey @logan-markewich 
yes they just started supporting it last month, you can find documentation here
 https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/fine-tuning?pivots=programming-language-studio

**Comment by AchintyaX** [comment]
Hey @logan-markewich 
any update or support you can provide here?
any plans as to when you would be able to add the support for Azure?

**Comment by Disiok** [comment]
Hey @AchintyaX thanks for the question. I took a quick look but Azure doesn't seem to support finetuning via API yet.

**Comment by nariman-zk** [comment]
Hi @AchintyaX,

I was wondering now that `Azure` [supports fine-tuning](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/fine-tuning?tabs=turbo%2Cpython&pivots=programming-language-python) of OpenAI models, does `llama-index` have a wrapper around it?
