### ISSUE TITLE
[Question]: DataException: expected 1536 dimensions, not 768 

### ISSUE THREAD

**Issue by axz91** [run-llama/llama_index#8005]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

how to solve this when using postgresml vector database

**Comment by axz91** [comment]
i use vector_store = TimescaleVectorStore.from_params(, it does not have  embed_dim
I

**Comment by logan-markewich** [comment]
@axz91 for timescale, it looks like the correct kwarg is `num_dimensions=768`
