### ISSUE TITLE
[Feature Request]: Citations on chat engine

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#8015]
### Feature Description

Please Add a list of source_nodes or metadata to the chat_engine() similar to the one in query_engine()

### Reason

To make extracting references easier

### Value of Feature

Increase bot credibility when necessary.

**Comment by logan-markewich** [comment]
It does actually, at least for most chat engines

`response.soucre_nodes` 

What chat engine are you using?

**Comment by gich2009** [comment]
The default chat_engine. 
index.as_chat_engine()
the chat_mode is "react"
The index is from a pinecone vector store.
When I run the code, my sources are empty:



chat_engine = index.as_chat_engine(
        show_progress=True,
        chat_mode='react', 
        memory=memory
    )
    response = chat_engine.chat(input_text)
    memories[chat_id] = chat_engine._memory  # Update memory
    print("\n\nCitations: ", response.source_nodes)
    return response.response


It answers pretty accurately but it doesnt give me back the sources:
Citations:  []
The European Union's Emission Trading System (ETS) is a cap-and-trade system that was established in 2005. It is the largest carbon emissions market in terms of turnover and market capitalization. The ETS covers around 10,000 installations in sectors such as power generation, energy-intensive industries, and flights between participating countries. Companies in these sectors are required to comply with the emission cap set by the EU and can buy emission permits or receive free allowances based on industry benchmarks. The ETS aims to reduce total emissions over time by decreasing the emission cap each year. The current target is to reduce carbon dioxide emissions by 43% by 2030 from 2005 levels.

**Comment by gich2009** [comment]
When I use chat_mode='context', the relevant source_nodes are returned. Thanks @logan-markewich. Is it possible to implement response.metadata that has just the filename and the pagenumber as a list like for a query engine? It would be super handy.
