### ISSUE TITLE
[Bug]: Unable to get node from Azure Cognitive Vector Store Index using node_id

### ISSUE THREAD

**Issue by zachlim98** [run-llama/llama_index#8031]
### Bug Description

I created a Azure Cognitive Search Index store following the guide on the documentation. 

```py
vector_store = CognitiveSearchVectorStore(  
    search_or_index_client=index_client,  
    index_name=index_name,  
    filterable_metadata_field_keys=metadata_fields,  
    index_management=IndexManagement.CREATE_IF_NOT_EXISTS,  
    id_field_key="id",  
    chunk_field_key="content",  
    embedding_field_key="content_vector",  
    metadata_string_field_key="metadata",  
    doc_id_field_key="doc_id",  
)
```

I then performed a search as follows and retrieved the node id from the node

```py
vector_node = index.as_retriever().retrieve("Some query")
id = vector_node[0].node.id_
```

I then tried to retrieve this from the index doc store

```py
index.docstore.get_node(id)
```

which returns the error that `id` is not found. 

I have also tried 

```py
index.docstore.get_document(id)
```

which returns the same error. 

Additionally, I have tried defining `id` as: 
```py
id = list(vector_node[0].node.relationships.values())[0].node_id
```

which returns the node_id rather than the doc_id. However, this still returns the error as mentioned above, wherein the node cannot be found.

### Version

0.8.36

### Steps to Reproduce

As described above.

**Comment by logan-markewich** [comment]
@zachlim98 when a vector db integration is used, by default, the docstore and index store are not used, since all the node info is serialized and put into the vector db

This makes saving/loading much easier, but at the cost of not being able to perform the operation you mentioned above.

You can override this behaviour though

```
index = VectorStoreIndex.from_documents(..., store_nodes_override=True)
```

this will force the docstore to be populated.

**Comment by zachlim98** [comment]
@logan-markewich Understood, thanks for your help!
