### ISSUE TITLE
[Bug]: No module named 'llama_index.embeddings.adapter' after update

### ISSUE THREAD

**Issue by DaveScream** [run-llama/llama_index#8033]
### Bug Description

After update Iam getting error No module named 'llama_index.embeddings.adapter'

### Version

Successfully installed llama-index-0.8.41

### Steps to Reproduce

import llama_index

### Relevant Logs/Tracbacks

```shell
Exception has occurred: ModuleNotFoundError       (note: full exception trace is shown but execution is paused at: <module>)
No module named 'llama_index.embeddings.adapter'
  File "F:\Projects\SharikAI\My_llama_index.py", line 1, in <module> (Current frame)
    import llama_index
ModuleNotFoundError: No module named 'llama_index.embeddings.adapter'
```

**Comment by logan-markewich** [comment]
@DaveScream it's definitely still there
https://github.com/run-llama/llama_index/blob/main/llama_index/embeddings/__init__.py

Maybe try a fresh venv?

**Comment by DaveScream** [comment]
@logan-markewich 
Thank you. This helped:
1. Restart  VSCode
2. Reinstall llama-index
3. add import llama_index.embeddings.adapter  as first line (not shure)
