### ISSUE TITLE
[Bug]: 'Llama' object has no attribute 'context_params'

### ISSUE THREAD

**Issue by DaveScream** [run-llama/llama_index#8034]
### Bug Description

Im getting error 'Llama' object has no attribute 'context_params' here:
`service_context = ServiceContext.from_defaults(llm=llm, embed_model="local")`

Here is merged pull request containing this fix: https://github.com/run-llama/llama_index/pull/7945

But Im on latest version now (pip install llama-index --upgrade) and its not working.

### Version

llama_index-0.8.41

### Steps to Reproduce

import llama_index.embeddings.adapter
import llama_index

from llama_index import (
    SimpleDirectoryReader,
    VectorStoreIndex,
    ServiceContext,
    #KeywordTableIndex,
    #LLMPredictor
)
from llama_index.llms import LlamaCPP

....

llm = LlamaCPP(
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path='C:/LLMs/oobabooga_windows/text-generation-webui/models/openorca-platypus2-13b.Q4_K_M.gguf',
    temperature=0.75,
    # The maximum number of tokens to generate.
    max_new_tokens=256,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,
    #max_tokens=3900,
    # kwargs to pass to __call__()
    generate_kwargs={"top_p": 1,},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    model_kwargs={"n_gpu_layers": 32, "n_batch": 512, "n_threads": 10},
    #n_gpu_layers=32,
    #n_batch=512
    #n_threads=10,
    
    #callback_manager=callback_manager,
    verbose=True,

    # transform inputs into Llama2 format
    # The function to convert messages to a prompt
    messages_to_prompt=messages_to_prompt,
    # The function to convert a completion to a prompt.
    completion_to_prompt=completion_to_prompt,
    )
# load data and build index
service_context = ServiceContext.from_defaults(llm=llm, embed_model="local")

### Relevant Logs/Tracbacks

```shell
Exception has occurred: AttributeError
'Llama' object has no attribute 'context_params'
  File "F:\Projects\SharikAI\My_llama_index.py", line 65, in <module>
    service_context = ServiceContext.from_defaults(llm=llm, embed_model="local")
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Llama' object has no attribute 'context_params'
```

**Comment by logan-markewich** [comment]
@DaveScream try updating your llama-cpp-python installation

**Comment by DaveScream** [comment]
Thank you It helped.
