### ISSUE TITLE
[Feature Request]: Configurable `retry time` for LLM calls

### ISSUE THREAD

**Issue by ravi03071991** [run-llama/llama_index#8039]
### Feature Description

Currently, the `min_seconds` and `max_seconds` for retrying an LLM call have a fixed default value. Allowing users to configure these values can provide more flexibility in different scenarios.

Reference:

`https://github.com/run-llama/llama_index/blob/f4c14c331b62a9d25b80cf63fe1d5cdf2abe4a1d/llama_index/llms/openai_utils.py#L111`

### Value of Feature

Different applications might have varying requirements for retry mechanisms. By allowing users to set their desired retry times, the LLM can be more adaptable to a broader range of applications.

**Comment by nerdai** [comment]
thanks for the suggestion @ravi-theja!

**Comment by aaronjimv** [comment]
Hello, I am new to open source collaboration, I want to know if I understood the feature requirements.

If I change the min and max_seconds variables for parameters in the function, would it meet the requirements? 

Example:
`def _create_retry_decorator(max_retries: int, min_seconds: int = 4, max_seconds: int = 10) -> Callable[[Any], Any]:`

Thank you.

**Comment by nerdai** [comment]
done in #8627 closing this.
