### ISSUE TITLE
[Feature Request]:  Add user specific items inside the JSON in the LLMSingSelector

### ISSUE THREAD

**Issue by terilias** [run-llama/llama_index#8044]
### Feature Description

Let's say that we use LLMSingleSelector in the RouterQueryEngine. According to the [documentation](https://docs.llamaindex.ai/en/stable/examples/query_engine/RouterQueryEngine.html#llmsingleselector) we ask LLM to choose between some query engines by providing it with their descriptions. We ask LLM to give its answer in  JSON format. The format of the JSON is defined using an output parser and we can find it in the [selection.py](https://github.com/run-llama/llama_index/blob/main/llama_index/output_parsers/selection.py). Then the LLMSingleSelector reads this JSON and choose the query engine that will use. 

But what if we need some extra information from the LLM? In my use case I want to ask LLM one more thing when using LLMSingleSelector. I need to ask for example "If your choise is to use the query about the plants of my garden, please give me the optimal K that I need to use if I want to perform KNN similarity search to answer the user's query. Give me the choise of K in a key-value pair."

Maybe I have understand something wrong. Or probably the value of the feature is very minor but I decided to report it just in case that you consider it useful. Thank you anyway for the time and effort you put to make LlamaIndex!

### Reason

I am thinking that I can send a different call to LLM to ask for K. But this requires an extra call. Maybe it is a good idea to have it inside the Selection process.

### Value of Feature

To avoid making an extra LLM call.

**Comment by terilias** [comment]
@logan-markewich great, thank you for taking the time to explain it to me! Could you please help me with a similar problem that I need to solve?

 I am using a RouterQueryEngine to compose two QueryEngineTools that are created from two vector indices. Whenever the router selects the one of these two query tools, I need to run a function that reads the query and use it to find the optimal K for KNN search (as the original example I wrote). 

Do you know how to change the K parameter dynamically whenever the specific query engine it is activated on the QueryEngineTool - inside the function as_query_engine() ? I understand that this specific problem it may be solved if I will manage to implement your directions. But if you know how to change the K parameter after the construction of the objects it will be useful. I didn't found on the documentation a way to do this.

I thought that I can re-create the RouterQueryEngine (with a new value for the K) every time that the user inputs a new query. But the problem is that I use the RouterQueryEngine as a component inside a SQLJoinQueryEngine.

**Comment by logan-markewich** [comment]
I think in this case, you'd want to subclass the query engine tool class to perform the operations you need 🤔

**Comment by terilias** [comment]
Thank you again for your time! If you think that there is a possibility of someone being involved to this thread can we leave it open? Otherwise you can close it, as you answered to my question...
