### ISSUE TITLE
[Bug]: Chat Prompts Customization

### ISSUE THREAD

**Issue by malinphy** [run-llama/llama_index#8045]
### Bug Description

version llama_index

### Version

0.8.42

### Steps to Reproduce

first example at Chat Prompts Customization: https://gpt-index.readthedocs.io/en/v0.7.11/examples/customization/prompts/chat_prompts.html

llama_index gives the following error at following versions.
![image](https://github.com/run-llama/llama_index/assets/55249305/72aefd6e-6bc7-4409-b5b5-a18f49f4943b)

However, It works for the combination of llama_index==0.6.15  & langchain==0.0.200

### Relevant Logs/Tracbacks

```shell
AttributeError                            Traceback (most recent call last)

<ipython-input-7-c40219eb336e> in <cell line: 24>()
     22 ]
     23 chat_text_qa_msgs_lc = ChatPromptTemplate.from_messages(chat_text_qa_msgs)
---> 24 text_qa_template = Prompt.from_langchain_prompt(chat_text_qa_msgs_lc)

AttributeError: type object 'PromptTemplate' has no attribute 'from_langchain_prompt'
```

**Comment by logan-markewich** [comment]
@malinphy your link is to a very old version of the docs (v0.7.11)

See the latest here
https://gpt-index.readthedocs.io/en/stable/examples/customization/prompts/chat_prompts.html
