### ISSUE TITLE
[Question]: Can chat engine be enabled for graph index?

### ISSUE THREAD

**Issue by sumitsahoo** [run-llama/llama_index#8047]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have gone through the document but my use case is to use a graph index. In short, I have multiple sources of information i.e. Database, File, and Directory. Hence I created a ListIndex for each and combine them to store it as a graph index. Now the issue is Graph index does not have `chat_engine` option i.e. `index.as_chat_engine(...)`.  It only has `query_engine`.

I need the `chat_engine` option because I want to retain history and query from history which acts like memory while is same is not available for `query_engine`. Example below:

```
stream_response = chat_engine.stream_chat(message, chat_history=message_history)
```
Here `message_history` is an array of `ChatMessage`. 

Any recommendations, please? What is the best way to have index from different sources and use `chat_engine` to have a memory as well?

**Comment by logan-markewich** [comment]
The bot is almost correct 

You can create an agent (the default chat engine) with your graph query engine
https://gpt-index.readthedocs.io/en/stable/examples/agent/openai_agent_with_query_engine.html

**Comment by sumitsahoo** [comment]
@logan-markewich Thanks a bunch. I will try this out. I just want to make sure that I am on right path.

**Comment by sumitsahoo** [comment]
@dosu-bot May I know if I should combine my multiple `ListIndex` and create a `ComposableGraph` then store it to disk or is there a better way? The goal is to combine multiple indexes then save them to disk then retrieve them to use for `chat_engine`. 

Below is the snippet I used to save the index.

```
graph = ComposableGraph.from_indices(GPTTreeIndex, index_list, index_summaries=summary_list)
graph.root_index.set_index_id("my_id")
graph.root_index.storage_context.persist(persist_dir=os.environ["INDEX_DIR"])
```

**Comment by sumitsahoo** [comment]
@dosu-bot `ComposableGraph` has no attribute `load`

**Comment by sumitsahoo** [comment]
@dosu-bot Is it a good idea to store individual indexes in storage then retrieve then build a `graph` instead of saving graph in storage? I was having issues in query after retrieving the graph from storage but then the graph is built from indexes it works just fine.

Sample code to store indexes:

```
index1.storage_context.persist(persist_dir=os.environ["INDEX_DIR"] + "/index1")
index2.storage_context.persist(persist_dir=os.environ["INDEX_DIR"] + "/index2")
index3.storage_context.persist(persist_dir=os.environ["INDEX_DIR"] + "/index3")
```

**Comment by sumitsahoo** [comment]
@dosu-bot How do we configure `KnowledgeGraphRAGRetriever` from a `ComposableGraph` index?

**Comment by sumitsahoo** [comment]
@dosu-bot Getting below error and unable to instantiate `memory`. Below is the error.
```
memory = BaseMemory()
         ^^^^^^^^^^^^
TypeError: Can't instantiate abstract class BaseMemory with abstract methods from_defaults, get, get_all, put, reset, set
```

**Comment by sumitsahoo** [comment]
@dosu-bot Sorry, I am still a bit confused. Consider I have a `ComposableGraph` and how exactly I can create a `chat_engine` from this `ComposableGraph` object.

```
graph = ComposableGraph.from_indices(GPTTreeIndex, index_list, index_summaries=summary_list)
```

Also, what is the difference between `ComposableGraph` and `KnowledgeGraphIndex`?

**Comment by sumitsahoo** [comment]
> _🤖_
> 
> Hello,
> 
> To create a `chat_engine` from a `ComposableGraph` object in the LlamaIndex framework, you can use the `as_query_engine` method of the `ComposableGraph` class. Here is how you can do it:
> 
> ```python
> from llama_index.indices.composability.graph import ComposableGraph
> 
> # Assuming you have a ComposableGraph object named `graph`
> chat_engine = graph.as_query_engine()
> ```
> 
> In the context shared, the `as_query_engine` method of the `ComposableGraph` class is used to create a `ComposableGraphQueryEngine` instance. This method also accepts additional arguments to be passed to the `ComposableGraphQueryEngine`.
> 
> Regarding your question about the difference between `ComposableGraph` and `KnowledgeGraphIndex`, the `ComposableGraph` is a class that represents a graph of indices that can be composed together. It provides methods to get an index from an index struct id and to create a query engine from the graph.
> 
> On the other hand, `KnowledgeGraphIndex` is a specific type of index that is used to store and retrieve information in a knowledge graph format. It is used to build a Knowledge Graph from given documents with the help of Llama Index and LLM defined. It can be created from documents and can include embeddings. Once created, it can be queried using the `KnowledgeGraphQueryEngine` which can generate queries in natural language.
> 
> Here is an example of how to create a `KnowledgeGraphIndex`:
> 
> ```python
> kg_index = KnowledgeGraphIndex.from_documents(
>     documents,
>     storage_context=storage_context,
>     max_triplets_per_chunk=10,
>     service_context=service_context,
>     space_name=space_name,
>     edge_types=edge_types,
>     rel_prop_names=rel_prop_names,
>     tags=tags,
>     include_embeddings=True,
> )
> ```
> 
> And here is how to query it using the `KnowledgeGraphQueryEngine`:
> 
> ```python
> query_engine = KnowledgeGraphQueryEngine(
>     storage_context=storage_context,
>     service_context=service_context,
>     llm=llm,
>     verbose=True,
> )
> 
> response = query_engine.query(
>     "Tell me about Peter Quill?",
> )
> ```
> 
> Please note that the exact differences would depend on the specific implementation of these classes in the LlamaIndex framework.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [[Question]: Connectiing multiple index to create one chat engine](https://github.com/run-llama/llama_index/issues/7674)
> * [[Question]: I have a list of vectorstore indices how do i create one chat engine using those indices](https://github.com/run-llama/llama_index/issues/7662)
> * [llama_index/indices/composability/graph.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/composability/graph.py)
> * [llama_index/query_engine/graph_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama_index/query_engine/graph_query_engine.py)
> * [docs/examples/query_engine/knowledge_graph_query_engine.ipynb](https://github.com/run-llama/llama_index/blob/main/docs/examples/query_engine/knowledge_graph_query_engine.ipynb)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot But in above example you have created a `query_engine` which does not support `chat_history`. How can I create a `chat_engine` instead of `query_ingine` from `ComposableGraph`? `chat_engine` also has a nice method `stream_chat` using which we can stream the tokens.

**Comment by sumitsahoo** [comment]
@dosu-bot I was actually trying to create a `ContextChatEngine` from `ComposableGraph` and have a `chat_engine` to do stream chat which could also support `chat_history` along with streaming response.

**Comment by sumitsahoo** [comment]
> _🤖_
> 
> Hello,
> 
> To create a `ContextChatEngine` from a `ComposableGraph` object in the LlamaIndex framework that supports `chat_history` and streaming responses, you can follow these steps:
> 
> 1. Load your data and build your index:
> 
> ```python
> from llama_index import VectorStoreIndex, SimpleDirectoryReader
> 
> data = SimpleDirectoryReader(input_dir="your_data_directory").load_data()
> index = VectorStoreIndex.from_documents(data)
> ```
> 
> 2. Configure your chat engine with a memory buffer to limit the chat history:
> 
> ```python
> from llama_index.memory import ChatMemoryBuffer
> from llama_index.chat_engine.context import ContextChatEngine
> 
> memory = ChatMemoryBuffer.from_defaults(token_limit=1500)
> 
> chat_engine = ContextChatEngine.from_defaults(
>     service_context=service_context,
>     memory=memory,
>     system_prompt="Your system prompt here.",
> )
> ```
> 
> 3. For streaming support, set up a service context and use the `stream_chat` method:
> 
> ```python
> from llama_index import (
>     ServiceContext,
>     set_global_service_context,
> )
> from llama_index.llms import OpenAI
> 
> service_context = ServiceContext.from_defaults(
>     llm=OpenAI(model="gpt-3.5-turbo", temperature=0)
> )
> set_global_service_context(service_context)
> 
> response = chat_engine.stream_chat("Your question here")
> for token in response.response_gen:
>     print(token, end="")
> ```
> 
> Please replace `"your_data_directory"` with the path to your data, `"Your system prompt here."` with your system prompt, and `"Your question here"` with your question.
> 
> However, based on the provided context, it's not clear how the `ComposableGraph` object interacts with the `ContextChatEngine`. The `ComposableGraph` object is used as a data structure in the `ComposableGraphQueryEngine` class, which operates over a `ComposableGraph` and can take in custom query engines for its sub-indices. But there's no mention of any interaction between the `ComposableGraph` object and a `ContextChatEngine`.
> 
> If you need more help or if there's something I misunderstood, please provide more details.
> 
> Best, Dosu
> 
> ## Sources
> * [Support to add  conversation history  in the prompt](https://github.com/run-llama/llama_index/issues/6574)
> * [docs/examples/chat_engine/chat_engine_context.ipynb](https://github.com/run-llama/llama_index/blob/main/docs/examples/chat_engine/chat_engine_context.ipynb)
> * [llama_index/chat_engine/context.py](https://github.com/run-llama/llama_index/blob/main/llama_index/chat_engine/context.py)
> * [llama_index/chat_engine/simple.py](https://github.com/run-llama/llama_index/blob/main/llama_index/chat_engine/simple.py)
> * [llama_index/chat_engine/**init**.py](https://github.com/run-llama/llama_index/blob/main/llama_index/chat_engine/__init__.py)
> * [llama_index/query_engine/graph_query_engine.py](https://github.com/run-llama/llama_index/blob/main/llama_index/query_engine/graph_query_engine.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

@dosu-bot Sorry I do not see `ComposableGraph` used in the example. The question was, how do I get a `ContextChatEngine` using `ComposableGraph`.

**Comment by sumitsahoo** [comment]
@dosu-bot I am curious if there is a way to add memory to `BaseQueryEngine`?
