### ISSUE TITLE
[Question]: Why is pickling the query engine not working, and how can I pickle it?

### ISSUE THREAD

**Issue by Idank96** [run-llama/llama_index#8048]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, 
I would like to be able to pickle the query engine variable if the folder of documents did not change, for efficiency and cost savings. This would allow me to avoid rebuilding the index every time I want to query the documents.

I have the following code:
```
        #  Loads a collection of documents from a directory
        documents = SimpleDirectoryReader("data").load_data()
        # Creates a vector store index
        index = VectorStoreIndex.from_documents(documents) 
        # Creates a query engine
        query_engine = index.as_query_engine()
        # Pickle the query_engine
        with open("query_engine.pkl", "wb") as file:
            pickle.dump(query_engine, file)
```

I've tried with Pickle library and dll library but I got this error:
`TypeError: cannot pickle 'builtins.CoreBPE' object
`

How to save the query_engine variable? (its also occurs with index variable)

Also, if there is another solution for cost savings let please me know.

Thanks,
Idan

**Comment by Idank96** [comment]
This:
```
# Convert the query_engine to a JSON object
query_engine_json = json.dumps(query_engine.to_dict())
```
is not working because I got this error:
`AttributeError: 'RetrieverQueryEngine' object has no attribute 'to_dict'
`

**Comment by logan-markewich** [comment]
@Idank96 you can't pickle a query engine, there are too many unpicklable dependencies right now

You can save your index to disk and load it later to avoid rebuilding though

```
index.storage_context.persist(persist_dir="./storage")

from llama_index import StorageContext, load_index_from_storage
storage_context = StorageContext.from_defaults(persist_dir="./storage")

# optionally pass in service context
loaded_index = load_index_from_storage(storage_context, service_context=service_context)
```

**Comment by Idank96** [comment]
Hi Thanks. 
For more explanation for everyonego to:
https://gpt-index.readthedocs.io/en/stable/getting_started/starter_example.html

**Comment by brenkehoe** [comment]
This also stops you from using the initial_app_loader with trulens when using TruLlama
