### ISSUE TITLE
[Question]: Custom Callback when error is triggered by query response Azure OpenAI

### ISSUE THREAD

**Issue by skanda1005** [run-llama/llama_index#8062]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am looking to create and call a custom callback handler function which is triggered when AzureOpenAI RetrieverQueryResponse fails due to an error in AzureOpenAI. This should be handled by returning an empty string.
I am using RetrieverQueryResponse with response mode as 'accumulate' and sometimes AzureOpenAI triggers an error which I would like to manually catch and handle by returning an empty string for the query response

**Comment by logan-markewich** [comment]
I think you are misunderstanding how the callbacks work

They don't handle errors or other scenarios, they simply report data
