### ISSUE TITLE
[Question]: cannot import name 'VectorStoreIndex' from 'llama_index'

### ISSUE THREAD

**Issue by DataLearnerGitHub** [run-llama/llama_index#8063]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,
I'm having trouble importing the VectorStoreIndex class from the llama_index package. I've installed the package using pip, but I'm getting an ImportError when trying to import the class. Is there any known issue or workaround for this problem? I've followed the documentation, but I can't seem to resolve the ImportError.

Used :
pip install llama-index
from llama_index import VectorStoreIndex

**Comment by logan-markewich** [comment]
The bot is correct, please ensure you have no files or folders named llama_index

**Comment by DataLearnerGitHub** [comment]
Thanks for your quick reply.

But it still doesn't work even when I tried from llama_index.indices.vector_store.base import VectorStoreIndex

Plus, I can find the file in the directory (...\Local\miniconda3\lib\site-packages\llama_index\indices\vector_store\base.py)

Please find details in the attachment.

Best,

<img width="665" alt="error information" src="https://github.com/run-llama/llama_index/assets/139040169/c0149fa0-b3db-41ba-b986-28f8499ffcfe">

**Comment by logan-markewich** [comment]
Try using an actual venv 

```
python -m venv venv
source venv/bin/activate
pip install llama-index
```

**Comment by DataLearnerGitHub** [comment]
It works now. Many thanks.
