### ISSUE TITLE
[Feature Request]: Lazy loading of external blobs

### ISSUE THREAD

**Issue by laurens-gs** [run-llama/llama_index#8071]
### Feature Description

To avoid any issues in offline installations or restricted environments, any external dependencies that need to be downloaded should be downloaded lazily once they are required. Ideally, it should be possible to manually provide the blobs if necessary. This restricted scenario should be included in the test suite, to ensure that people can import this package in all environments and still use the most basic features using local models.

### Reason

I work for a large firm where production environments and even development environments are strictly secured behind a firewall. I cannot even import the package because `tiktoken` immediately attempts to load binaries for OpenAIs GPT2 tokenizer. I am required to run all my models locally, so any optional OpenAI stuff should not need to be loaded at all.

### Value of Feature

The MIT license allows for commercial use, but for many firms commercial application of this library is not possible if it cannot be run behind a firewall. Adding this feature would open up this library to all potential users.

**Comment by logan-markewich** [comment]
technically, tiktoken is a core dependency (i.e. not optional)

Would love a PR to make that more configurable though
https://github.com/run-llama/llama_index/blob/a3609580d57e2603b23dd66434b349559bc9986c/llama_index/utils.py#L42

**Comment by laurens-gs** [comment]
> technically, tiktoken is a core dependency (i.e. not optional)
> 
> It's used in a few places I think, but this is the main culprit. Would love a PR to make that more configurable though
> 
> https://github.com/run-llama/llama_index/blob/a3609580d57e2603b23dd66434b349559bc9986c/llama_index/utils.py#L42

Having a globals helper for setting defaults is not bad, even if it is fetched fetched over the internet. However the loading of this tokenizer should only occur if the tokenizer is actually about to be used.

Upon importing the library, the default tokenizer is requested many times to populate `_tokenizer` fields in several calss instances despite not being used. If we can defer the loading until the tokenizer is actually being used would solve the problem.
