### ISSUE TITLE
[Question]: BM25 Hybrid Retriever

### ISSUE THREAD

**Issue by yashdeepyds** [run-llama/llama_index#8083]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

@jerry
How to use the BM25 hybrid retriever using the already indexed milvus collection.

**Comment by logan-markewich** [comment]
Short answer: you can't (easily)

Long answer: you need all the nodes/documents from Milvus. Then, put those in a docstore. Then, put that in a bm25 retriever
