### ISSUE TITLE
[Feature Request]: Sources with ReAct agent

### ISSUE THREAD

**Issue by vishhvak** [run-llama/llama_index#8084]
### Feature Description

Currently, the ReAct agent does not return sources with nodes in its response, like the OpenAI Agent does. This can be accomplished with simple additions in the codebase for the ReAct agent.

**Comment by nerdai** [comment]
Thanks @vishhvak for the suggestion. Are you envisioning this being printed in just the final response or the verbose ReAct output (or both)?

**Comment by nerdai** [comment]
thanks @BrianMcBrayer — I believe you are correct! Closing this.
