### ISSUE TITLE
[Documentation]: Advanced Text-to-SQL guide does not add other tables

### ISSUE THREAD

**Issue by AbhiPawar5** [run-llama/llama_index#8088]
### Documentation Issue Description

In the guide, there is no code to add the other tables except city_stats in the SQL database. And the guide mentions it can search on large number of tables to get the SQL from natural query. However, we see only a single table is added to the SQL DB instance in the following line:
```
sql_database = SQLDatabase(engine, include_tables=["city_stats"])
```

Can you please post the correct code before updating the documentation? Thanks.
P.S New to Llama Index.

### Documentation Link

https://gpt-index.readthedocs.io/en/latest/examples/index_structs/struct_indices/duckdb_sql_query.html#advanced-text-to-sql-with-our-sqltableretrieverqueryengine

**Comment by AbhiPawar5** [comment]
> _🤖_
> 
> Hello,
> 
> Thank you for bringing this to our attention. You're correct that the guide currently only shows how to add a single table to the SQL database. However, you can add multiple tables by creating a new `Table` object for each table you want to add, and then adding them to the `MetaData` object using `metadata_obj.create_all(engine)`. Here's an example of how you can add two tables, `city_stats` and `country_stats`:
> 
> ```python
> # create city SQL table
> table_name1 = "city_stats"
> city_stats_table = Table(
>     table_name1,
>     metadata_obj,
>     Column("city_name", String(16), primary_key=True),
>     Column("population", Integer),
>     Column("country", String(16), nullable=False),
> )
> 
> # create country SQL table
> table_name2 = "country_stats"
> country_stats_table = Table(
>     table_name2,
>     metadata_obj,
>     Column("country_name", String(16), primary_key=True),
>     Column("population", Integer),
>     Column("continent", String(16), nullable=False),
> )
> 
> metadata_obj.create_all(engine)
> ```
> 
> Then, when you create the `SQLDatabase` object, you need to include both table names in the `include_tables` parameter:
> 
> ```python
> sql_database = SQLDatabase(engine, include_tables=["city_stats", "country_stats"])
> ```
> 
> And when you create the `NLSQLTableQueryEngine` object, you also need to include both table names in the `tables` parameter:
> 
> ```python
> query_engine = NLSQLTableQueryEngine(
>     sql_database=sql_database,
>     tables=["city_stats", "country_stats"],
> )
> ```
> 
> Finally, when you create the `ObjectIndex`, you need to create a `SQLTableSchema` object for each table:
> 
> ```python
> table_schema_objs = [SQLTableSchema(table_name="city_stats"), SQLTableSchema(table_name="country_stats")]
> ```
> 
> And pass them to the `ObjectIndex.from_objects` method:
> 
> ```python
> obj_index = ObjectIndex.from_objects(
>     table_schema_objs,
>     table_node_mapping,
>     VectorStoreIndex,
> )
> ```
> 
> In the context shared, you can also add additional context information for each table schema you define:
> 
> ```python
> # manually set context text
> city_stats_text = (
>     "This table gives information regarding the population and country of a given city.\n"
>     "The user will query with codewords, where 'foo' corresponds to population and 'bar'"
>     "corresponds to city."
> )
> 
> table_node_mapping = SQLTableNodeMapping(sql_database)
> table_schema_objs = [
>     (SQLTableSchema(table_name="city_stats", context_str=city_stats_text))
> ]
> ```
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [docs/end_to_end_tutorials/structured_data/sql_guide.md](https://github.com/run-llama/llama_index/blob/main/docs/end_to_end_tutorials/structured_data/sql_guide.md)
> * [docs/examples/index_structs/struct_indices/SQLIndexDemo.ipynb](https://github.com/run-llama/llama_index/blob/main/docs/examples/index_structs/struct_indices/SQLIndexDemo.ipynb)
> * [llama_index/utilities/sql_wrapper.py](https://github.com/run-llama/llama_index/blob/main/llama_index/utilities/sql_wrapper.py)
> * [llama_index/indices/struct_store/sql_query.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/struct_store/sql_query.py)
> * [llama_index/indices/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/base.py)
> * [llama_index/indices/keyword_table/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/keyword_table/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.


How can I index and add hundreds or thousands of tables? Is there any to simplify the above process?

**Comment by sbisen** [comment]
@dosu-bot Is there a way to add multiple table from different database and schema in SQLDatabase? Presently these tables are from 1 database:
sql_database = SQLDatabase(engine, include_tables=["city_stats", "country_stats"])
if we have 2 different database, how to include tables in that case?
