### ISSUE TITLE
[Question]: About llamaCPP

### ISSUE THREAD

**Issue by shun010409** [run-llama/llama_index#8093]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was building llamaCPP , but the following error message appeared when setting up the query engine.
where is context_params?

error message: 'Llama' object has no attribute 'context_params'

**Comment by shun010409** [comment]
thank you!
i will try.

**Comment by logan-markewich** [comment]
@shun010409 you need to update your llamacpp installation actually -- the lastest versions added that `context_params` attribute
