### ISSUE TITLE
[Feature Request]: Vespa VectorDB Connection

### ISSUE THREAD

**Issue by Unristricted** [run-llama/llama_index#8099]
### Feature Description

My team is using Vespa as our VectorDB solution and we wanted to start using LLamaIndex in our project. We would just need to create a connector that can work with existing Vespa deployments so it would be a seamless connection with the library. I could work on this if possible.

### Reason

No such connector exists at the moment.

### Value of Feature

This would add to the already robust arsenal of Vector Databases supported by LLamaIndex and would allow our team to start using this library as well.

**Comment by jobergum** [comment]
This [notebook](https://github.com/vespa-engine/pyvespa/blob/master/docs/sphinx/source/examples/scaling-personal-ai-assistants-with-streaming-mode-cloud.ipynb) might be a good start for retriever abstraction.
