### ISSUE TITLE
[Bug]:  site-packages/llama_cpp/llama.py", line 1658, in __del__

### ISSUE THREAD

**Issue by Khan-Tzar** [run-llama/llama_index#8101]
### Bug Description

I follow starter instructions here [starter_example.html ](https://gpt-index.readthedocs.io/en/stable/getting_started/starter_example.html )

I put these lines in mytry.py file 
```
from llama_index import VectorStoreIndex, SimpleDirectoryReader

documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
```
I receive this error:
```
Exception ignored in: <function Llama.__del__ at 0xffff84018360>
Traceback (most recent call last):
  File "/mywork/.local/lib/python3.11/site-packages/llama_cpp/llama.py", line 1658, in __del__
TypeError: 'NoneType' object is not callable
```
I work in Docker container:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
 Python 3.11.5

Could you help to fix this problem, please?

### Version

0.8.42

### Steps to Reproduce

My Docker file 
```
FROM  python:3.11.5 as python-sdk
# Install packages
RUN apt update && apt install -y git vim sudo rsync
RUN git clone https://github.com/jerryjliu/llama_index.git && \
	cd llama_index && pip install --upgrade pip && \
	pip install -e . && \
	pip install oci docx2txt llama-index llama-cpp-python pypdf torch transformers python-pptx Pillow sentence_transformers && \
	pip install -r requirements.txt 
``` 
My steps into the container 
```bash
git clone https://github.com/jerryjliu/llama_index.git
cd llama_index/examples/paul_graham_essay
```
vi my_example.py
```python
from llama_index import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
```
```bash
python ./my_example.py
```

**Comment by Khan-Tzar** [comment]
Any news on this issue?

**Comment by devstein** [comment]
Hey @Khan-Tzar what would have been a better response from Dosu?

**Comment by Khan-Tzar** [comment]
I am saying that your [started ](https://gpt-index.readthedocs.io/en/stable/getting_started/starter_example.html) doesn't work. 
You can easily reproduce it and it. The code form Git of your repository and  llama-cpp-python library plus your starter example doesn't work straight forward.

**Comment by logan-markewich** [comment]
@Khan-Tzar this is not actually an error. This happens sometimes when programs that use llama cpp shutdown. I think you'll find the actual code ran fine if you use the index
