### ISSUE TITLE
[Bug]:issue with redis vector store index?

### ISSUE THREAD

**Issue by ashokrayapati** [run-llama/llama_index#8117]
### Bug Description

set_global_service_context(service_context = service_context)
vector_store=RedisVectorStore(index_name=folderpath[i],index_prefix="llama_index",redis_url=configdata["REDIS_URL"],overwrite=False)
loaded_index = VectorStoreIndex.from_vector_store(vector_store,service_context=service_context)
query_engine = loaded_index.as_query_engine(similarity_top_k= 3,streaming=True)    
response = query_engine.query(input_txt)    
 https://gpt-index.readthedocs.io/en/latest/examples/vector_stores/RedisIndexDemo.html

### Version

0.8.44

### Steps to Reproduce

Retriever = loading_index.as_retriever()
Retriever.retrieve(input_txt)

**Comment by logan-markewich** [comment]
What is the issue you are having?

**Comment by ashokrayapati** [comment]
Exception Details : Exception occured in single document query in redis. details :Property `vector_score` not loaded nor in schema

**Comment by ashokrayapati** [comment]
Thank you so much for the support with the above snippet.
Now i have a query that what is is meant by vector_score exactly and do we have any specific or default value for that Vector_Score parameter while loading or extracting  the data to the redis?
