### ISSUE TITLE
[Bug]: from llama_index.embeddings import OpenAIEmbedding taking too long to import

### ISSUE THREAD

**Issue by MrKimmich** [run-llama/llama_index#8118]
### Bug Description

import statement `from llama_index.embeddings import OpenAIEmbedding` taking too long. Because of that getting timeouts in aws python lambda

### Version

0.8.41

### Steps to Reproduce

1. Install llama-index in aws python lambda 
2. try importing OpenAIEmbedding from llama_index.embeddings
3. Also place logs to check before and after import statement to check import time. Sharing my import time here
 [INFO]	2023-10-13T15:00:52.013Z		OpenAIEmbedding imported in 11.241815567016602 seconds

**Comment by logan-markewich** [comment]
I think this is an issue with any import from llama-index -- the very first import is always slow 🤔

**Comment by MrKimmich** [comment]
Issue resolved after increasing memory of my aws lambda
