### ISSUE TITLE
[Bug]: the custom id_ for Document is not displayed in Pinecone

### ISSUE THREAD

**Issue by bilyalov** [run-llama/llama_index#8123]
### Bug Description

When I save a document to pinecone with my custom ID -  I don't see my ID in pinecone. Instead, I see the ID that llama creates by default (uuid4 string)

### Version

0.8.14

### Steps to Reproduce

1. Create a Document with custom id_ (by default, this is the uuid4 string).
```
doc = Document(id_="aHR0cHM6Ly9jaGFpbmZ", ...)

VectorStoreIndex.from_documents([doc], service_context=service_context, storage_context=storage_context)
```
2. After uploading the Document to Pinecone via VectorStoreIndex, in the Pinecone panel I see that the document has an ID as a uuid4 string instead of my custom ID, but the other id fields (doc_id, document_id, ref_doc_id) they have my own ID

_"_node_content" also has the same ID that the vector has, but it's not my own ID._

Result from Pinecone:
```
ID
76445bd0-8688-4e63-b805-96e373335b6f

VALUES
-0.00946603529, 0.016899189, -0.0179087

_node_content: "{\"id_\": \"76445bd0-8688-4e63-b805-96e373335b6f\", ...
chunk_id: 4
doc_id: "aHR0cHM6Ly9jaGFpbmZ"
document_id: "aHR0cHM6Ly9jaGFpbmZ"
ref_doc_id: "aHR0cHM6Ly9jaGFpbmZ"
```

As you may have already noticed, a new ID appeared from somewhere as a UUID-4 string, and at the same time this ID is also in `_node_content`. But My Own ID is saved into doc_id, document_id and ref_doc_id, although it is expected from the sources that this `id_` will be used as Record ID when inserting a document into Pinecone

**Comment by logan-markewich** [comment]
When you call from_documents, the document is parsed into nodes

Each node has its own new ID, and `node.ref_doc_id` points to the parent document ID, which is also in the metadata

If you call VectorStoreIndex([doc], ...) then it won't be chunked

**Comment by logan-markewich** [comment]
You can use the node parser to chunk into nodes ahead of time, and set your own node ids

**Comment by bilyalov** [comment]
> When you call from_documents, the document is parsed into nodes
> 
> Each node has its own new ID, and `node.ref_doc_id` points to the parent document ID, which is also in the metadata
> 
> If you call VectorStoreIndex([doc], ...) then it won't be chunked

But Document class inherits from TextNode, which inherits from BaseNode.
If we look at the property methods, we can see that they all take the id_ field:
def node_id - takes self.id_
def ref_doc_id - takes self.node_id
def doc_id - takes self.id_
def get_doc_id - takes self.id_ (deprecated)

Or do you want to say that a document that is already a TextNode will again be divided into TextNode fragments that will reference my custom ID?

---
Okay, if I understood you correctly, can I send my Documents to the insert_nodes method so that my Documents are not split, since I already divide them in chunks myself at the previous stage and link them through relationship?
