### ISSUE TITLE
[Documentation]: documenting why GPT instruct in ReActAgent

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8127]
### Documentation Issue Description

Just looking to understand the details of the `ReActAgent` notebook.

The request is to add comments explaining why one uses `gpt-3.5-turbo-instruct` vs `gpt-3.5-turbo-0613` with the `ReActAgent`.

Thanks in advance!  Happy to open a PR if someone just comments why

### Documentation Link

https://gpt-index.readthedocs.io/en/stable/examples/agent/react_agent_with_query_engine.html#setup-react-agent

**Comment by logan-markewich** [comment]
@jamesbraza You can use any LLM with the react agent.

The react agent follows the react prompting loop, where the LLM reads the chat history + set of tools it has access to, makes an observation, optionally calls a tool, makes another observation, etc. Until it reaches a final answer and returns that to the user

The notebook is comparing the performance between the two. The instruct model uses a completion endpoint, while normal gpt-3.5-turbo uses a chat endpoint. In my experience, the instruct model does not do well as a react agent

**Comment by jamesbraza** [comment]
Ah, I see @logan-markewich, I think in my semi-skimming, I got confused. I appreciate your support here! 👍 

Changing the ordering of cells will make this notebook be more intuitive, I opened a PR to do that
