### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by dougsmithstpete** [run-llama/llama_index#8129]
### Bug Description

Multi-Document Agents. 

You need to add additional code for OpenAI Key under setup and demo

Current:
llm = OpenAI(temperature=0, model="gpt-3.5-turbo")
service_context = ServiceContext.from_defaults(llm=llm)

Recommended:
import openai

# Set the API key
openai.api_key = <Your secret key>

llm = OpenAI(temperature=0, model="gpt-3.5-turbo")

service_context = ServiceContext.from_defaults(llm=llm)

### Version

llama_index-0.8.44-py3-none-any.whl

### Steps to Reproduce

Run

llm = OpenAI(temperature=0, model="gpt-3.5-turbo")
service_context = ServiceContext.from_defaults(llm=llm)

will throw an error of no API Key

**Comment by dougsmithstpete** [comment]
Adding the following will address the issue.

import openai

# Set the API key
openai.api_key = <add your secret key from OpenAI - you will need to setup and OpenAI account to get one>

**Comment by Disiok** [comment]
Thanks for raising the issue! A lot of the notebook right now assume user has OpenAI API key configured as part of the environment variables. 

If you are up for it, would love to have your help on making this more explicit. Feel free to directly make PR against the file, should be here (https://github.com/run-llama/llama_index/blob/main/docs/examples/agent/multi_document_agents.ipynb).
