### ISSUE TITLE
[Bug]: Static Value from Example Showing up in Sub Question Query Engine without using Example Data

### ISSUE THREAD

**Issue by scottrpoulin** [run-llama/llama_index#8130]
### Bug Description

Receiving KeyError: 'uber_10k'
Error occurs when trying to query sub question query engine. Collection of Sub Question Query Engines were NOT built with any example documents.

### Version

0.8.43

### Steps to Reproduce

list_of_values = ['a','b','c']
query_engine_tools = []
llm = LlamaCPP(
        model_url="https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf",
        temperature=0.01,
        max_new_tokens=256,
        context_window=3900,
        generate_kwargs={},
        model_kwargs={"n_gpu_layers": 0},
        verbose=True,
    )
service_context = ServiceContext.from_defaults(llm=llm, embed_model=embeddings)

for value in list_of_values:
        docs = SimpleDirectoryReader(cfg.PATH_TO_DATA+"/"+value).load_data()
        vector_index = VectorStoreIndex.from_documents(docs,service_context=service_context)
        query_engine = vector_index.as_query_engine()
        query_engine_tool = QueryEngineTool(
            query_engine=query_engine,
            metadata=ToolMetadata(name=f"{value}",
                                  description="Provides information on value" + value)
        )
        query_engine_tools.append(query_engine_tool)

response_synthesizer = get_response_synthesizer(
        response_mode=ResponseMode.COMPACT,
    )

final_query_engine = SubQuestionQueryEngine.from_defaults(query_engine_tools=query_engine_tools,
                                                            service_context=service_context,
                                                            response_synthesizer=response_synthesizer,
                                                            use_async=False)
query = "What documents use the word hello?"
final_query_engine.query(query)

### Relevant Logs/Tracbacks

```shell
/llama_index/indices/query/base.py", line 23, in query
return self._query(str_or_query_bundle)
/llama_index/query_engine/sub_question_query_engine.py", line 141, in _query
qa_pairs_all = [
/llama_index/query_engine/sub_question_query_engine.py", line 142, in <listcomp>
self._query_subq(sub_q, color=colors[str(ind)])
/llama_index/query_engine/sub_question_query_engine.py", line 245, in _query_subq
query_engine = self._query_engines[sub_q.tool_name]
KeyError: 'uber_10k'
```

**Comment by logan-markewich** [comment]
llama2 is not great at structured outputs (like the sub-question query engine). In fact, nearly every open-source LLM is not great at this task, very unreliable. 

It's likely copying from the few-shot prompt in the question generator

https://github.com/run-llama/llama_index/blob/3147cfc891e9b3738bcfcd7cac7dce6e23588123/llama_index/question_gen/prompts.py#L26

**Comment by scottrpoulin** [comment]
That makes sense! Thank you!
