### ISSUE TITLE
[Bug]: response_syntesizers throws an error when asking a question that retrieves 

### ISSUE THREAD

**Issue by mikeldking** [run-llama/llama_index#8132]
### Bug Description

When using an index as a query_engine and you ask a question that is not pertained in the index, a stack trace occurs.
<img width="1899" alt="Screenshot 2023-10-13 at 6 26 50 PM" src="https://github.com/run-llama/llama_index/assets/5640648/bb8d69d2-4814-4042-a299-301f881404d1">

### Version

0.8.45.post1

### Steps to Reproduce

Follow this notebook and ask a silly question like "Why should I work?"
https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

### Relevant Logs/Tracbacks

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-34-bc77f716f3fb> in <cell line: 1>()
----> 1 response = query_engine.query("Why should I go to work")
      2 print(response)

3 frames
/usr/local/lib/python3.10/dist-packages/llama_index/response_synthesizers/base.py in _prepare_response_output(self, response_str, source_nodes)
    114                 metadata=response_metadata,
    115             )
--> 116         if isinstance(response_str, self._output_cls):
    117             return PydanticResponse(
    118                 response_str, source_nodes=source_nodes, metadata=response_metadata

TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

**Comment by logan-markewich** [comment]
@mikeldking which notebook should I follow for this?

**Comment by mikeldking** [comment]
@logan-markewich updated the issue! https://colab.research.google.com/github/Arize-ai/phoenix/blob/main/tutorials/tracing/llama_index_tracing_tutorial.ipynb

Not sure it's urgent - just thought I'd query for something silly and noticed the stack trace.

**Comment by logan-markewich** [comment]
Interesting! The traceback is super weird, since it's happening on a line of code I wouldn't expect.

I'll let you know what I find

**Comment by Kirushikesh** [comment]
I was facing the same issue.
