### ISSUE TITLE
[Feature Request]: better abstraction for embeddings vs LLMs

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8134]
### Feature Description

The Hugging Face Inference API supports chat, complete, and embedding capabilities.

It would be nice to be able to define one `class` that can do both what `LLM` and `BaseEmbedding` do.

So it means better structuring `LLM` and `BaseEmbedding` so one can:
- Use multiple inheritance (e.g. making embeddings and chat stuff a mixin)
    - This is how LangChain does it: [`Embeddings`](https://github.com/langchain-ai/langchain/blob/v0.0.314/libs/langchain/langchain/schema/embeddings.py#L6)
- Compose in entities that handle separate behaviors (e.g. think how `ReActAgent` handles tools)
    - Model can be given an "embedder" and a "chatter"

### Reason

The current state, duplicating the same `InferenceClient`/`AsyncInferenceClient` behaviors, leads to less test coverage and more code.

### Value of Feature

- Avoid duplication between `llms` and `embeddings` modules
- Clearer separation of what an embedding model needs vs what a chat model needs

**Comment by logan-markewich** [comment]
I think the division between embeddings and LLMs is pretty clear? One makes text, the other makes lists of floats.

In a majority of the best performing systems I've seen, these are always two different models. 

I think it's fine for a provider to provide all these services through a single API (Im not sure how common this is), but in a RAG system, there are clear responsibilities for each type of model no? 🤔

Maybe there could be a lower level "base model inference" class or something, but that really only provides value for this single huggingface API

**Comment by jamesbraza** [comment]
Thanks for sharing thoughts!

> In a majority of the best performing systems I've seen, these are always two different models.
> 
> I think it's fine for a provider to provide all these services through a single API (Im not sure how common this is), but in a RAG system, there are clear responsibilities for each type of model no? 🤔

As far as "thought overhead" it's good to think in terms of behaviors, not types.  I think having one type vs two types doesn't impact runtime performance, it's more of an organization kind of thing.  I may be wrong here, but in OOP it's one-function to one-responsibility, not one-type to one-responsibility.

I would say in my experience, powerful frameworks takes burden off of a developer.  Currently, if one API supports both chat and embeddings, LlamaIndex has some boiler plate associated with that is all.

> Maybe there could be a lower level "base model inference" class or something, but that really only provides value for this single huggingface API

I would say being able to use one class to support multiple behaviors is useful for any remote entity exposing endpoints (e.g. OpenAI, Llama.cpp, Ollama, Hugging Face Inference API, Clarifai, etc).  It lets you share connection creation logic and API-specific helper functions.

**Comment by Disiok** [comment]
You can use utility functions to share code, it's more flexible than inheritance. 

Not super sure if there's strong enough motivation to create a class that does both embedding and LLM. They are fundamentally very different things.

**Comment by jamesbraza** [comment]
I discovered that if one mixes in LangChain's `Embeddings`, then when used in LlamaIndex's `llama_index.embeddings.utils.resolve_embed_model` it will be auto-paired with `LangchainEmbedding`.  So to accomplish what I was posing here, one can simply mix in LangChain's `Embeddings`.

If this request isn't thought to be worthwhile, then feel free to close this out 👌
