### ISSUE TITLE
[Documentation]:  Paul Graham Essay example - data path issue

### ISSUE THREAD

**Issue by nickknyc** [run-llama/llama_index#8139]
### Documentation Issue Description

I was getting weird quota errors when running the Paul_graham_essay example
https://docs.llamaindex.ai/en/stable/getting_started/starter_example.html

Docs say...
We now want to navigate to the following folder:
$ cd examples/paul_graham_essay
.... (** NOTE: the explicit instructions to get into the examples/paul_graham_essay folder. The user will create the new .py file in that folder,**)....
Build and Query Index
Create a new .py file with the following:
from llama_index import VectorStoreIndex, SimpleDirectoryReader
documents = SimpleDirectoryReader('data').load_data()
index = VectorStoreIndex.from_documents(documents)
documents = SimpleDirectoryReader('data').load_data()

The problem seems to stem from the path to data. Perhaps the docs assume (which it should not) that the user is using a jupyter notebook. On windows, I was able to get it running by changing 

documents = SimpleDirectoryReader('data').load_data()
to 
documents = SimpleDirectoryReader('examples\paul_graham_essay\data').load_data()

### Documentation Link

https://docs.llamaindex.ai/en/stable/getting_started/starter_example.html

**Comment by logan-markewich** [comment]
The docs assume that you change your working directory to first to "examples/paul_graham_essay", and then run the command. 

This page assumes you are running in a terminal.

Of course if you are on windows or not using WSL, then you'll need to use the proper slashes and cd appropriately

**Comment by nickknyc** [comment]
Even more complicated if you are running in a venv that is set to the root of LI project.
