### ISSUE TITLE
[Bug]: ctransformers not supported as OSS LLM models (from Huggingface)

### ISSUE THREAD

**Issue by geoHeil** [run-llama/llama_index#8140]
### Bug Description

ctransformer is not working with the HF adapter of llamaindex:

AutoModelForCausalLM.from_pretrained('TheBloke/leo-hessianai-7B-chat-GGUF', model_file="leo-hessianai-7b-chat.Q4_K_M.gguf",  model_type="llama") 

this is currently failing with TheBloke/leo-hessianai-7B-chat-GGUF does not appear to have a file named pytorch_model.bin, tf_model.h5, model.ckpt or flax_model.msgpack. for the AutoModelForCausalLM which is coming from the normal transformers library which is used by llamaindex?

When instead loading the model by hand: 

```
model = <load model from ctransformers>
llm = HuggingFaceLLM(model=model, ...)
```

```
123 config_dict = self._model.config.to_dict()
    124 model_context_window = int(
    125     config_dict.get("max_position_embeddings", context_window)
    126 )
    127 if model_context_window and model_context_window < context_window:

AttributeError: 'Config' object has no attribute 'to_dict'
```

https://github.com/run-llama/llama_index/blob/31d132c56b1836603d48e02786cd29a74a28f527/llama_index/llms/huggingface.py#L136

Probably the huggingface llm class  needs to be extended and write the init to work

### Version

0.8.41

### Steps to Reproduce

```
from llama_index.llms import HuggingFaceLLM
from ctransformers import AutoModelForCausalLM

model = AutoModelForCausalLM.from_pretrained('TheBloke/leo-hessianai-7B-chat-GGUF', model_file="leo-hessianai-7b-chat.Q4_K_M.gguf",  model_type="llama") 
HuggingFaceLLM(model=model)

```

### Relevant Logs/Tracbacks

```shell
llm_model.config.__dict__

llm_model.config.to_dict()
```

**Comment by geoHeil** [comment]
However, even if this is fixed the next line will fail:

max_position_embeddings (https://github.com/run-llama/llama_index/blob/31d132c56b1836603d48e02786cd29a74a28f527/llama_index/llms/huggingface.py#L137-L139) is not part of the config: 

```
{'top_k': 40,
 'top_p': 0.95,
 'temperature': 0.8,
 'repetition_penalty': 1.1,
 'last_n_tokens': 64,
 'seed': -1,
 'batch_size': 8,
 'threads': -1,
 'max_new_tokens': 256,
 'stop': None,
 'stream': False,
 'reset': True,
 'context_length': -1,
 'gpu_layers': 0,
 'mmap': True,
 'mlock': False}


```

**Comment by geoHeil** [comment]
For now, I am monkey-patching it with:

```
# Step 1: Define a to_dict function
        def to_dict_method(self):
            result = {attr: getattr(self, attr) for attr in dir(self) if not callable(getattr(self, attr)) and not attr.startswith("__")}
            result['max_position_embeddings'] = 8000
            return result
        
        # Step 2: Assign this function as a method of the instance
        llm_model.config.to_dict = to_dict_method.__get__(llm_model.config)
        
        # Step 3: Call the method when needed
        print(llm_model.config.to_dict())  # Output: {'attr1': 'value1', '
        llm_model = HuggingFaceLLM(model=llm_model)


```

**Comment by geoHeil** [comment]
More patching is needed though when trying to run the LLM

AttributeError: 'LLM' object has no attribute 'device'

**Comment by Disiok** [comment]
Thanks for raising the issue. The current `HuggingFaceLLM` doesn't explicitly support `ctransformers` quite.

Would love to have a contribution to add the support here if you are up for it. Otherwise, we will probably get to it soon enough!

**Comment by geoHeil** [comment]
@Disiok When trying to run the aforementioned model (GUF) with llamacpp it fails for me with: invalid magic number 20200a7b

How could I use it there instead?

**Comment by geoHeil** [comment]
but even when using AttributeError: 'Llama' object has no attribute 'metadata' -->  123 config_dict = self._model.config.to_dict()
    124 model_context_window = int(
    125     config_dict.get("max_position_embeddings", context_window)
    126 )
    127 if model_context_window and model_context_window < context_window:


AttributeError: 'Llama' object has no attribute 'config'  llm_model = Llama(model_path, model_type="llama", . it looks like llama_cpp python is also not fully supported?
