### ISSUE TITLE
Denodo connector for Llama-index

### ISSUE THREAD

**Issue by zzadiues** [run-llama/llama_index#8150]
### Feature Description

I am unable to find a way of connecting a denodo database to llamaindex. I see that there are database connectors for mysql, postgres, redshift etc but not for denodo. 
A functionality like this (see below) 

![image](https://github.com/run-llama/llama_index/assets/64059206/730b7bee-db9d-4a31-939b-86209e9fd859)

### Reason

Perhaps denodo is not so popular as other data virtualization platforms. it is rather niche. 

### Value of Feature

many organizations now use denodo for storing massive datasets , providing denodo connectivity will greatly enhance the reach of llamaindex and add immense value

**Comment by VijayKalmath** [comment]
I see this issue is on the Starter contribution level on the request contribution board.  
I would like to give it a shot. 

Can someone assign this issue to me?
