### ISSUE TITLE
[Feature Request]: using line length of 79 in `docs/`

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8151]
The IPython notebooks in `docs/` currently (as of `llama_index==0.8.42`) use 88 chars (default of `black`).

However, in `docs/` rendering, this means one has to scroll left/right a lot. For example, see the last block in https://gpt-index.readthedocs.io/en/stable/examples/agent/react_agent_with_query_engine.html#build-query-engine-tools

It would be nice if one didn't have to scroll for the rendered code blocks:

- Default code renderings to 88 char width
- `black` uses [PEP 8's 79-char width](https://peps.python.org/pep-0008/#maximum-line-length),

**Comment by nerdai** [comment]
Thanks for the request @jamesbraza. Just to clarify, you're request is about formatting the code blocks and not their associated output blocks? Using black as you suggest here, I believe only can format the code blocks and not the output blocks.

@Disiok @logan-markewich:
We can apply 79 char limit to just the notebooks in `docs/examples` via
```
black docs/examples/* --preview -l 79
```
Not sure if we want to apply this char width rule throughout the rest of the code base. If we do, then we'd just add the following to our `pyproject.toml`
```
[tool.isort]
profile = "black"
line_length = 79
```

NOTES:
1. This will not apply to long comments, so if there is a long comment, then the user will still have to scroll to read it all.
2. The `--preview` argument will split long strings to multiple lines. Without this, long strings will not be altered via black even with the default 88 char width (see for e.g. [here](https://gpt-index.readthedocs.io/en/stable/examples/vector_stores/chroma_auto_retriever.html#defining-some-sample-data))

**Comment by jamesbraza** [comment]
My request was mainly about code blocks, though great thinking per handling the printed outputs too. There may be a way to wrap lines of output via Sphinx (as opposed to using `black`/`isort`).

I agree `black --preview`'s new string wrapping is useful.  One comment is `isort` is done via `ruff`, so its line length will be configured through `ruff`.

**Comment by nerdai** [comment]
@logan-markewich:
I submitted a PR which adds the command to format out docs notebooks in our Makefile. And have gone ahead and executed that command. I also took a quick look at Sphinx and `myst_nb` configuration and I couldn't find anywhere yet to format outputs. Going to mark this output block formatting as a thing to do at a later date.

@jamesbraza: thanks for your input and help on this!

**Comment by jamesbraza** [comment]
Nice @nerdai, I dig your before/after screenshots in the PR view 👍

**Comment by jamesbraza** [comment]
@nerdai are you a member of LlamaIndex, like as an employee?  Just wondering

**Comment by nerdai** [comment]
> @nerdai are you a member of LlamaIndex, like as an employee?  Just wondering (trying to figure out if I can add you as a reviewer to some PRs sometime 😄 )

@jamesbraza yes, just joined the company yesterday officially :). Please do tag me as a reviewer in some future PRs. Cheers 🍻
