### ISSUE TITLE
[Question]: Can I run LlamaIndex with structured data using a local Llama-2 model and completely on cpu?

### ISSUE THREAD

**Issue by utility-aagrawal** [run-llama/llama_index#8152]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to use text-to-sql feature of LlamaIndex. However, I can't use openai API because of the confidentiality of my data/schema. Neither will I have access to a gpu in the target deployment environment. I am running it using a local Llama-2 7B chat model via huggingface. Is it possible to run everything on a cpu?

I tried setting device_map to "cpu" when I instantiate HuggingFaceLLM but it doesn't work. Appreciate your help!

**Comment by logan-markewich** [comment]
@utility-aagrawal it will be very slow, but it is possible!

I suggest using llamacpp for this, it will be more optimized than huggingface for CPU inference
https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html
