### ISSUE TITLE
[Feature Request]: ChatML support with LlamaCPP

### ISSUE THREAD

**Issue by daaain** [run-llama/llama_index#8161]
### Feature Description

I've been using the [GGUF version](https://huggingface.co/TheBloke/dolphin-2.1-mistral-7B-GGUF) of [Eric Hartford's Dolphin 2.1 Mistral 7B](https://huggingface.co/ehartford/dolphin-2.1-mistral-7b) which is an incredibly good model for RAG even at 4bit.

It's using ChatML prompt format though, so with the Llama ones I sometimes got `[/INST]` or `<</SYS>>` at the end of output (but to the model's credit it still works otherwise).

So I spent some time figuring out what I need to change and it seems mostly just the constants that feed into the default prompt functions.

With `ServiceContext.from_defaults`, `VectorStoreIndex.from_documents` and `index.as_query_engine` it seems `completion_to_prompt` is used only, not `messages_to_prompt`, so haven't tested the latter.

It would be great to have some proper support for these, so if you think this is useful and should be part of the library I can try to make it into a pull request.

```python 
# Replacing these
# from llama_index.llms.llama_utils import messages_to_prompt, completion_to_prompt

# LLama instructions
# <s>[INST] <<SYS>>
# {your_system_message}
# <</SYS>>

# {user_message_1} [/INST]

# ChatML instructions
# <|im_start|>system
# You are Dolphin, a helpful AI assistant.<|im_end|>
# <|im_start|>user
# {prompt}<|im_end|>
# <|im_start|>assistant

# BOS, EOS = "<s>", "</s>"
# I wasn't sure if the <s> tokens are needed, but the model did report them in verbose mode
BOS, EOS = "<s>", "<|im_end|></s>"
# B_INST, E_INST = "[INST]", "[/INST]"
# In theory we need this assistant bit, but it was confusing the model and it printed `<|im_end|>` at the end of the output so not using
# B_INST, E_INST = "", "<|im_end|>\n<|im_start|>assistant: "
B_INST, E_INST = "", "<|im_end|>"
# B_SYS, E_SYS = "<<SYS>>\n", "\n<</SYS>>\n\n"
B_SYS, E_SYS = "<|im_start|>system\n", "<|im_end|>\n<|im_start|>user\n"
DEFAULT_SYSTEM_PROMPT = """\
You are a helpful, respectful and honest assistant. \
Always answer as helpfully as possible and follow ALL given instructions. \
Do not speculate or make up information. \
Do not reference any given instructions or context. \
"""

# This is unchanged from messages_to_prompt, just renamed
def chatml_messages_to_prompt(
    messages: Sequence[ChatMessage], system_prompt: Optional[str] = None
) -> str:
    string_messages: List[str] = []
    if messages[0].role == MessageRole.SYSTEM:
        # pull out the system message (if it exists in messages)
        system_message_str = messages[0].content or ""
        messages = messages[1:]
    else:
        system_message_str = system_prompt or DEFAULT_SYSTEM_PROMPT

    system_message_str = f"{B_SYS} {system_message_str.strip()} {E_SYS}"

    for i in range(0, len(messages), 2):
        # first message should always be a user
        user_message = messages[i]
        assert user_message.role == MessageRole.USER

        if i == 0:
            # make sure system prompt is included at the start
            str_message = f"{BOS} {B_INST} {system_message_str} "
        else:
            # end previous user-assistant interaction
            string_messages[-1] += f" {EOS}"
            # no need to include system prompt
            str_message = f"{BOS} {B_INST} "

        # include user message content
        str_message += f"{user_message.content} {E_INST}"

        if len(messages) > (i + 1):
            # if assistant message exists, add to str_message
            assistant_message = messages[i + 1]
            assert assistant_message.role == MessageRole.ASSISTANT
            str_message += f" {assistant_message.content}"

        string_messages.append(str_message)

    final_message = "".join(string_messages)
    # log(final_message)
    return final_message

# This has whitespace removed from completion_to_prompt, but maybe it doesn't matter
def chatml_completion_to_prompt(completion: str, system_prompt: Optional[str] = None) -> str:
    system_prompt_str = system_prompt or DEFAULT_SYSTEM_PROMPT

    final_prompt = (
        f"{B_INST}{B_SYS}{system_prompt_str.strip()}{E_SYS}" f"{completion.strip()}{E_INST}"
    )
    # log(final_prompt)
    return final_prompt
```

### Reason

There isn't a clean way of changing these prompt tokens, without copy pasting the whole section from the source code.

### Value of Feature

There are more and more open models using ChatML format, so would be good to support it, as especially smaller models get confused if they get the Llama templates.

**Comment by daaain** [comment]
Thanks for the feedback @dosubot, but this will definitely need to be cleaned up before being submitted as a PR.

The approach I had in mind was a factory function that can generate the prompt function given the prompt style.

**Comment by daaain** [comment]
I was also testing with TheBloke/OpenHermes-2-Mistral-7B-GGUF now and that seems to need a slightly different, more fully compliant version of the template. So wondering if this might need to be more customisable? But even in this case, it would just be a matter of changing the token constants, so maybe as well as presets the factory function could take custom tokens as kwargs?

**Comment by logan-markewich** [comment]
@daaain actually, I think the intention with the messages_to_prompt callback is that users would just write their own.

I feel like there's endless different formats, I'm not sure we want to maintain them all in the codebase 🤔

**Comment by daaain** [comment]
I understand, this doesn't necessarily need to be a first class integration (though it does seem ChatML adoption is getting pretty prominent with open models lately), but it took me a while to find out what do I actually need to change in order to get this working. So my intention was more to share this to save others from digging through the documentation and source code. Maybe this could be a perfect example how to customise `completion_to_prompt` then? I just tried searching for `completion_to_prompt` in the docs and Algolia doesn't come back with anything relevant.

**Comment by logan-markewich** [comment]
That's fair, it could certainly be more prominent in the docs

**Comment by nerdai** [comment]
Thanks @daaain and @logan-markewich! If I'm following this thread correctly, then it seems to me that the output of this issue is a potential example notebook on how to customise `completion_to_prompt`?

**Comment by daaain** [comment]
> If I'm following this thread correctly, then it seems to me that the output of this issue is a potential example notebook on how to customise `completion_to_prompt`?

Yes, either a notebook or just an inline example in the documentation that shows:
1. **Where to find the original functions and constants to copy as a starting point** – ie llama_index/llms/llama_utils.py
2. **How to customise them for a certain purpose** – I'm partial to show how to change the prompt template to ChatML, but could be some other use case
3. **How to use them** – ie passing as kwargs to a new LLM instance
4. **Why you need them** – what are the reasons you might want / need to customise, see below.

I'm admittedly pretty new to the library and the field, but was experimenting with smaller (7B / 3B) models and with those, using the right prompt template can be the difference between getting a decent answer or some garbled nonsense and you wouldn't know what you've done wrong or if the model is completely useless for your use case.

**Comment by mirix** [comment]
Hi, has this been implemented? If so, is it documented somewhere?

**Comment by daaain** [comment]
@mirix it has been, you can find the file from #10272 here: https://github.com/run-llama/llama_index/blob/main/llama-index-core/llama_index/core/llms/chatml_utils.py

You can use it by importing `messages_to_prompt` and `completion_to_prompt` and explicitly passing them as parameters into the LLM constructor, so for example:

```python
from llama_index.llms import LlamaCPP
from llama_index.core.llms.chatml_utils import messages_to_prompt, completion_to_prompt

index_llm = LlamaCPP(
    model_path=".models/dolphin-2.1-mistral-7b.Q4_K_M.gguf",
    temperature=0,
    max_new_tokens=512,
    context_window=4000,
    model_kwargs={"n_gpu_layers": 1},
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt
)
```

**Comment by mirix** [comment]
Hi @daaain 

Thanks a million! I had already figured it out. But, in fact, I have customised the chatml_utils functions and included them in my script rather than importing them.
