### ISSUE TITLE
[Bug]: Litellm tokeniser issue

### ISSUE THREAD

**Issue by smyja** [run-llama/llama_index#8176]
### Bug Description

i keep getting this error
`'Could not automatically map together_ai/togethercomputer/llama-2-70b-chat to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'`

i think the issue was mentioned [here also ](https://github.com/BerriAI/litellm/issues/590)

### Version

0.8.44

### Steps to Reproduce

from llama_index.llms import LiteLLM
llm = LiteLLM("together_ai/togethercomputer/llama-2-70b-chat")
embed_model = OpenAIEmbedding(embed_batch_size=42)
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model)

**Comment by logan-markewich** [comment]
@smyja try setting `max_tokens` in the LLM init, leaving at as None only works for openai models

**Comment by smyja** [comment]
> @smyja try setting `max_tokens` in the LLM init, leaving at as `None` only works for openai models (at least, that's my best guess from looking at the source code)

A pr has been created to resolve this. I'll close once it's merged 
 https://github.com/BerriAI/litellm/issues/590#issuecomment-1768964334
