### ISSUE TITLE
Only works with Llama 2?

### ISSUE THREAD

**Issue by Sequential-circuits** [run-llama/llama_index#8182]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Trying to read from a MariaDB database, but apparently it only works if the model is llama2

Any other model imported by ollama such as mistral, codellama, etc generates the error 
  File "/root/anaconda3/lib/python3.9/site-packages/llama_cpp/llama.py", line 1658, in __del__
TypeError: 'NoneType' object is not callable

The code is:
from sqlalchemy import select, create_engine, MetaData, Table
from llama_index import SQLDatabase
from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine
from llama_index import StorageContext, load_index_from_storage
from IPython.display import Markdown, display
from llama_index.llms import Ollama

engine = create_engine('mariadb+pymysql://user:$password@server:port/database')
sql_database = SQLDatabase(engine)
metadata = MetaData()
table = Table("users", metadata, autoload_with=engine)
stmt = select(table.columns)
with engine.connect() as connection:
  results = connection.execute(stmt).fetchone()
  print(results)

llm = Ollama(model="llama2:70b")
query_engine = NLSQLTableQueryEngine(sql_database=sql_database,tables=["pictures"],)
query_str = ("how many records are there in the table users")
try:
 response = query_engine.query(query_str)
 response_md = str(response)
 sql_query = response.metadata["sql_query"]
 print("sql_query=",sql_query)
 print("response_md=",response_md)
except Exception as ex:
 response_md = "Error"
 display(Markdown(f"ERROR: {str(ex)}"))_

**Comment by logan-markewich** [comment]
@Sequential-circuits that is not an error. That is a benign warning coming from llamacpp when the program is shutting down and already completed
