### ISSUE TITLE
[Question]: How to print out SQL from  GPTSQLStructStoreIndex

### ISSUE THREAD

**Issue by Iwannabanana** [run-llama/llama_index#8183]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone, just a quick question：
I have been querying the GPTSQLStructStoreIndex and the response gives me the final result. Is there a method that I can inspect the in-process SQL llama is using to query the database? Many thanks.

**Comment by logan-markewich** [comment]
The SQL is also in the generated response object

`response.metadata['sql_query']`
