### ISSUE TITLE
Query Neo4j graph database without any documents involved 

### ISSUE THREAD

**Issue by zzadiues3338** [run-llama/llama_index#8191]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

the sample documentation in the website (https://gpt-index.readthedocs.io/en/latest/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo.html) involves creating a database from corpus of documents. followed by querying the graph db. 

I already have a populated graph database (the movies database in neo4j aura instance) and need to query that database using LLM, no documents involved in the process. 

I tried using a blank list for documents in the following code but it did not work, and told me that I exceeded my openAI quota. 

![image](https://github.com/run-llama/llama_index/assets/65094709/5d028e9e-b3fa-4ef4-9ca5-f5250cf355fd)

How can i query a pre existing graph in neo4j ? please help ! Thanks :)

**Comment by logan-markewich** [comment]
Use this thingy
https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html
