### ISSUE TITLE
[Question]: Can a locally stored TensorFlow model be used with llamaindex?

### ISSUE THREAD

**Issue by iriye** [run-llama/llama_index#8201]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Can a locally stored TensorFlow model be used with llamaindex?

**Comment by logan-markewich** [comment]
@iriye yes, but you'd have to implement it as a customLLM class

https://docs.llamaindex.ai/en/stable/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced
