### ISSUE TITLE
[Question]: can tensorflow model be used with llamaindex ?

### ISSUE THREAD

**Issue by iriye** [run-llama/llama_index#8202]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

can tensorflow model be used with llamaindex ? model extension .ckpt , give a example used tensorflow model?

**Comment by logan-markewich** [comment]
Yes, but you need to implement as a custom LLM class

https://docs.llamaindex.ai/en/stable/core_modules/model_modules/llms/usage_custom.html#example-using-a-custom-llm-model-advanced
