### ISSUE TITLE
[Bug]: QueryFusionRetriever doesn't work in async context

### ISSUE THREAD

**Issue by ryanpeach** [run-llama/llama_index#8204]
### Bug Description

If you run QueryFusionRetriever with an await and aretrieve you get an error related to there already being an async loop. I have tried two solutions for your review, one works one doesn't.

Doesn't work, but it'd be nice to fix it at this level. However, this function is only used one place. Note, you can't even reach nest_asyncio unless show_progress is True, which is default False and never overwritten:

https://github.com/OnScale/llama_index/pull/5

Works but has a lot of code duplication:

https://github.com/OnScale/llama_index/pull/6

### Version

v0.8.42

### Steps to Reproduce

```python
async def main():
    await QueryFusionRetriever(
            retrievers=...,
            llm=...,
            similarity_top_k=2,
            num_queries=4,
            async=True,
            verbose=True,
        ).aretrieve(query.content)

asyncio.run(main())
```

```python
async def main():
    QueryFusionRetriever(
            retrievers=...,
            llm=...,
            similarity_top_k=2,
            num_queries=4,
            async=True,
            verbose=True,
        ).retrieve(query.content)

asyncio.run(main())
```

Neither of these will work.

### Relevant Logs/Tracbacks

```shell
At this point I've lost the failure logs.
```

**Comment by logan-markewich** [comment]
@ryanpeach Isn't the solution just 

```
import nest_asyncio
nest_asyncio.apply()
```
?

**Comment by ryanpeach** [comment]
I'm not familiar with nest_asyncio, where would I put it?

https://github.com/OnScale/llama_index/pull/5/files

didn't work.

**Comment by ryanpeach** [comment]
Oh, this might be it, I also didn't install nest_asyncio. That's probably why https://github.com/OnScale/llama_index/pull/5/files fails.

**Comment by Disiok** [comment]
Looks like it's resolved.

**Comment by ryanpeach** [comment]
Actually that didn't fix it @Disiok

**Comment by ryanpeach** [comment]
Ok nvm, this works:

```python
import os
import openai

openai.api_key = os.environ["OPENAI_API_KEY"]

from llama_index import SimpleDirectoryReader

documents_1 = SimpleDirectoryReader(
    input_files=["docs/community/integrations/vector_stores.md"]
).load_data()
documents_2 = SimpleDirectoryReader(
    input_files=["docs/core_modules/data_modules/storage/vector_stores.md"]
).load_data()

from llama_index import VectorStoreIndex

index_1 = VectorStoreIndex.from_documents(documents_1)
index_2 = VectorStoreIndex.from_documents(documents_2)

QUERY_GEN_PROMPT = (
    "You are a helpful assistant that generates multiple search queries based on a "
    "single input query. Generate {num_queries} search queries, one on each line, "
    "related to the following input query:\n"
    "Query: {query}\n"
    "Queries:\n"
)

from llama_index.retrievers import QueryFusionRetriever

retriever = QueryFusionRetriever(
    [index_1.as_retriever(), index_2.as_retriever()],
    similarity_top_k=2,
    num_queries=4,  # set this to 1 to disable query generation
    use_async=True,
    verbose=True,
    # query_gen_prompt="...",  # we could override the query generation prompt here
)

async def main():
    nodes_with_scores = retriever.retrieve("How do I setup a chroma vector store?")
    print(nodes_with_scores)

if __name__ == "__main__":
    import asyncio
    import nest_asyncio

    nest_asyncio.apply()

    asyncio.run(main())
```

**Comment by ryanpeach** [comment]
Oh actually it's a problem specifically with fastapi and uvicorn

[#1496](https://github.com/tiangolo/fastapi/issues/1496)

`ValueError: Can't patch loop of type <class 'uvloop.Loop'>`

**Comment by ryanpeach** [comment]
I really would recommend [this as best practice](https://github.com/OnScale/llama_index/pull/6)

**Comment by srufino-irius** [comment]
but @ryanpeach , youurr solution / workaround was applied only to your fork? and llama index people did  solve this not using supeer bad nest_asyncio.apply()?
