### ISSUE TITLE
[Documentation]: more info on `set_index_id` in S3 notebook

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8205]
### Documentation Issue Description

> ```python
> # save index to remote blob storage
> index.set_index_id("vector_index")
> ```

Why is this `set_index_id` call in the S3 remote backend notebook?

Happy to add this to the notebook, but I am thinking it's unnecessary

### Documentation Link

https://docs.llamaindex.ai/en/stable/core_modules/data_modules/storage/save_load.html#using-a-remote-backend

**Comment by logan-markewich** [comment]
@jamesbraza its only needed if you are storing more than one index in the same storage context

**Comment by jamesbraza** [comment]
Oh interesting.  Didn't know that was possible.  I will open a PR for this sometime in coming week

**Comment by jamesbraza** [comment]
PR is open btw, closing this out
