### ISSUE TITLE
[Bug]: index.as_chat_engine

### ISSUE THREAD

**Issue by XariZaru** [run-llama/llama_index#8206]
### Bug Description

VectoreStoreIndex.as_chat_engine method not taking Streaming, k_similarity, or qa_template parameters anymore.

Not sure if this was a recent update, but none of those initializer parameters are working anymore.

### Version

0.8.46

### Steps to Reproduce

Create a VectoreStoreIndex. Call as_chat_engine method on the index.

```python
sc = StorageContext.from_defaults(persist_dir=PERSIST_DIR)

    try:
        key = drum.RuntimeParameters.get("OPENAI_API_KEY")["apiToken"]
    except:
        key = os.environ["OPENAI_API_KEY"]
    
    try:
        index = load_index_from_storage(storage_context=sc, index_id='vector_index')
    
        template_str = """We have provided context information below. If you don't know the answer, just say you don't know. Don't make up an answer. Do not mention you are an AI language model. 
        Always say to refer to the respective department for extra information. Don't mention anything about the provided context in your response. \n"
        "---------------------\n"
        "{context_str}"
        "\n---------------------\n"
        "Do not give me an answer if it is not mentioned in the context as a fact. Given this information, please answer the question: {query_str}\n"""
    
        qa_template = Prompt(template_str)
        model = index.as_chat_engine(streaming=False
                                                  ,similarity_top_k=2
                                                  , text_qa_template=qa_template)
```

### Relevant Logs/Tracbacks

```shell
Error: __init__() got an unexpected keyword argument 'streaming'
```

**Comment by logan-markewich** [comment]
@XariZaru just remove the streaming kwarg, you don't need to pass this to chat engines since they have `chat()` and `stream_chat()` endpoints

**Comment by XariZaru** [comment]
> @XariZaru just remove the streaming kwarg, you don't need to pass this to chat engines since they have `chat()` and `stream_chat()` endpoints

When I remove the streaming kwarg, it complains about the next kwarg.

Error has occurred loading model from vector store index
__init__() got an unexpected keyword argument 'similarity_top_k'

**Comment by logan-markewich** [comment]
@XariZaru  Do you have the full traceback?

**Comment by XariZaru** [comment]
> @XariZaru Do you have the full traceback?

Error has occurred loading model from vector store index
Traceback (most recent call last):
  File "/tmp/ipykernel_24/2984667311.py", line 31, in load_model
    model = index.as_chat_engine(similarity_top_k=2
  File "/etc/system/kernel/.venv/lib64/python3.9/site-packages/llama_index/indices/base.py", line 393, in as_chat_engine
    return ReActAgent.from_tools(
  File "/etc/system/kernel/.venv/lib64/python3.9/site-packages/llama_index/agent/react/base.py", line 95, in from_tools
    return cls(
TypeError: __init__() got an unexpected keyword argument 'similarity_top_k'

**Comment by logan-markewich** [comment]
Ah, the `ReActAgent.from_tools` just needs to be updated to accept `**kwargs`

**Comment by XariZaru** [comment]
> Ah, the `ReActAgent.from_tools` just needs to be updated to accept `**kwargs`

Okay cool. I'll just wait for the change to be made and redownload llama_index right?

**Comment by XariZaru** [comment]
Hi,

This issue has returned again after being fixed.

**Comment by nerdai** [comment]
> Hi,
> 
> This issue has returned again after being fixed.
> 
> @logan-markewich

🤔 oh no. Can you confirm that you're on the latest release of `llama-index v0.8.51`?

I just now used a slightly modified version of your script on the latest release and I didn't encounter the `unexpected keyword` error.

**Comment by XariZaru** [comment]
> > Hi,
> > This issue has returned again after being fixed.
> > @logan-markewich
> 
> 🤔 oh no. Can you confirm that you're on the latest release of `llama-index v0.8.51`?
> 
> I just now used a slightly modified version of your script on the latest release and I didn't encounter the `unexpected keyword` error.

Oh, no I am on `v0.8.46`. I will update to the latest release. I was staying at `v0.8.46` because it was working on that release and didn't want to introduce any additional changes.

I'll update my package and get back to you.

**Comment by XariZaru** [comment]
> > Hi,
> > This issue has returned again after being fixed.
> > @logan-markewich
> 
> 🤔 oh no. Can you confirm that you're on the latest release of `llama-index v0.8.51`?
> 
> I just now used a slightly modified version of your script on the latest release and I didn't encounter the `unexpected keyword` error.

Hi,

The error is was on my end. It went away after updating to the latest package. Thank you.

**Comment by nerdai** [comment]
That's great @XariZaru! Happy that the BUG has been resolved. 🍻
