### ISSUE TITLE
[Feature Request]: integrate `setuptools_scm` for better versioning from Git

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8207]
### Feature Description

Currently, there's two versioning systems:

1. Git repo tags (lagging right now at v0.8.42)
2. Manual versioning by editing `pyproject.toml`

Lets sync these two by using `setuptools_scm` :rocket

### Reason

I like to use Git tags in my links, to ensure they always work (whereas `main` branch-based links may not always work).

It would be nice to keep these in sync

### Value of Feature

You use GitHub releases to publish new versions, instead of manually changing the version in `pyproject.toml`.  It's more automated and seamless.  Also, no need to manually create `CHANGELOG`, it's just done with GitHub releases.

**Comment by logan-markewich** [comment]
@jamesbraza A key point of the current changelog -- it's written by humans, for humans. I would rather not automate this step :) https://keepachangelog.com/en/1.1.0/

Also yea, the GitHub tags are lagging, need to figure that out lol

But the current tag system works well enough internally

**Comment by jamesbraza** [comment]
I think a `CHANGELOG` in the form of GitHub releases is still human readable. Why do you think something like https://github.com/astral-sh/ruff/releases isn't human readable? Imo that's more human friendly than the current `CHANGELOG.md`, because:
- It autolinks GitHub PRs
- It's standard across all GitHub

I think it'd would be excellent to remove the per-PR manual `CHANGELOG` creation step, in favor of well-worded PR descriptions. The #1 area of rework from working in LlamaIndex is having to deal with `CHANGELOG` conflicts each rebase.

Here's a nice workflow:

1. GitHub release: hit "generate release notes" button
    - This removes manual `CHANGELOG` per-PR step
    - A human can adjust as needed then
2. Release triggers a GitHub action that copies the release notes to `CHANGELOG.md`

**Comment by jamesbraza** [comment]
And most importantly you can do emoji reactions to the releases.  Check how many reactions Hugo gets each release: https://github.com/gohugoio/hugo/releases

**Comment by david20571015** [comment]
Maybe [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) is a good choice since we are using poetry?

**Comment by jamesbraza** [comment]
Looks to be somewhat equivalent to `setuptools_scm`, and is actively maintained, so it's also a viable option! 👍

**Comment by jamesbraza** [comment]
Personally, I think it would be nice to not have to manually change `pyproject.toml` every release, so @dosubot let's keep this open. Up to the LlamaIndex team though

**Comment by logan-markewich** [comment]
__version__ and it's associated file has been deleted, so no issue syncing these files

Mayne more annoying though now is trying to manage releases for 400+ packages... working on a github action to help manage this soon
