### ISSUE TITLE
[Bug]: llama_new_context_with_model: ggml_metal_init() failed

### ISSUE THREAD

**Issue by steve36871** [run-llama/llama_index#8217]
### Bug Description

This bug seems related to the Macbook GPU. I have attached the Github issue from llama-cpp-python that I think is relevant. Still filing it here as well, because I am not sure how to configure llama-index such that it works (even if only using the CPU).

### Version

0.8.47

### Steps to Reproduce

Query a VectorStoreEngine

### Relevant Logs/Tracbacks

```shell
https://github.com/ggerganov/llama.cpp/issues/3129
```

**Comment by logan-markewich** [comment]
You can see the full config for llama cpp here

https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html

Just set num_gpu_layers tk zero

It's likely a probably with your installation? It works fine on my M2 (but maybe you have intel)

Anyways,  closing this then.
