### ISSUE TITLE
[Feature Request]: SpeedUp chatGPT training and Q&A process using GPU

### ISSUE THREAD

**Issue by gaurang12041999** [run-llama/llama_index#8219]
### Feature Description

Hii Jerry Liu,

I am doing ChatGPT integration with my chatbot and I am using the Llama index for it. But the big question is speed. It's taking too much time to answer the questions. It would be great if you could add GPU support to the library. 

Thanks,
Gaurang Dealvadiya

**Comment by logan-markewich** [comment]
There is GPU support for local models.

However, the bulk of speed is just the limit to API calls. Each LLM call to openai takes 2-3s right now, and there is no way around that. A GPU won't improve that
