### ISSUE TITLE
[Feature Request]: Support for pydantic v2

### ISSUE THREAD

**Issue by ierehon1905** [run-llama/llama_index#8221]
### Feature Description

Migrate to pydantic v2. I noticed there is already a feature branch with related name. https://github.com/run-llama/llama_index/tree/support-pydantic-v2 . But I do not know if its alive

### Reason

I do not know.

### Value of Feature

Pydantic v1 iss absolete

**Comment by logan-markewich** [comment]
It's technically supported through the backwards compat layer right now (`from pydantic.V1 import ...`)

Although there might be one or two areas to clean up, I forget 😅

We will likely migrate fully some time early January? It depends on langchain as well right now

**Comment by ierehon1905** [comment]
Hi @logan-markewich, thanks for ressponse.
Langchain seems to have supported pydantic v2 just recently.
https://github.com/langchain-ai/langchain/issues/6841#issuecomment-1682996914

**Comment by logan-markewich** [comment]
@ierehon1905 they are using the compatibility layer, same as us. I think there's just one or two bugs to work out
