### ISSUE TITLE
[Feature Request]: How to use the multimodal example with llava-13b

### ISSUE THREAD

**Issue by smyja** [run-llama/llama_index#8222]
### Feature Description

An example on using llava-13b and llamaindex would be great, Here is the model available on [replicate](https://replicate.com/yorickvp/llava-13b/)

**Comment by Disiok** [comment]
Thanks for the request [smyja](https://github.com/smyja)! We are actively working on this.

**Comment by smyja** [comment]
> Thanks for the request [smyja](https://github.com/smyja)! We are actively working on this.

I've seen the jupyter notebook, that example is for running it locally. Not with something like replicate, it also doesn't mention how to batch multiple images to get their description. https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb

**Comment by jerryjliu** [comment]
cc @hatianzhang !

**Comment by hatianzhang** [comment]
@smyja batch images understanding and Multi-modal LlamaIndex API is on my TODO list.
Please stay tuned and I will ping you once it is done.
thanks for your feedback!!


Btw as I mentioned in the notebook:
we need to wait https://github.com/abetlen/llama-cpp-python/pull/821/files is merge so that we can serve LLamaCPP with LLaVa model in llamaindex.

**Comment by hatianzhang** [comment]
@smyja please check out https://github.com/run-llama/llama_index/pull/8539
We already support Llava-13 B with replicate
Please see this example: https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb

**Comment by smyja** [comment]
> @smyja please check out https://github.com/run-llama/llama_index/pull/8539
> We already support Llava-13 B with replicate
> Please see this example: https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/llava_multi_modal_tesla_10q.ipynb

Thanks, just checked. Is it possible to use a list of images or a directory of images?

**Comment by hatianzhang** [comment]
@smyja good call out.
You can but you need to pass image one by one to Llava model to get output.
Bc Llava model only support 1 image at this time.

For other models like gpt4v, if they support multi images input at one time, I will make an example and send to you when they are ready

**Comment by smyja** [comment]
> @smyja good call out.
> You can but you need to pass image one by one to Llava model to get output.
> Bc Llava model only support 1 image at this time.
> 
> For other models like gpt4v, if they support multi images input at one time, I will make an example and send to you when they are ready

Great, thank you very much.
