### ISSUE TITLE
[Bug]: multi_document_agents - - - top_agent.chat("my_message")

### ISSUE THREAD

**Issue by ElioErrico** [run-llama/llama_index#8239]
### Bug Description

Hello,

I followed the documentation on [https://gpt-index.readthedocs.io/en/stable/examples/agent/multi_document_agents.html](url).
Everything is working correctly just cooping and pasting.
But if i try to change from:
`response=top_agent.query("tell me more about boston?")`
to:
`response=top_agent.chat("tell me more about boston?")`

it gives me some errors if I don't explicit the topic in my next message once that the topic should be defined.

I start with:
`response=top_agent.chat("tell me more about boston?")`
 I get the answer correctly calling the boston tool.

than this is the chat history:
`[
ChatMessage(role=<MessageRole.USER: 'user'>, content='Ciao mi dici di più su boston?', additional_kwargs={}), 
ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content=None, additional_kwargs={'function_call': <OpenAIObject at 0x1eaf6deb230> JSON: {
  "name": "tool_Boston",
  "arguments": "{\n\"input\": \"overview\"\n}"
}}), 
ChatMessage(role=<MessageRole.FUNCTION: 'function'>, content="Boston ... bla bla bla.", additional_kwargs={'name': 'tool_Boston'}), 
ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content="Boston ... bla bla bla", additional_kwargs={})]`

but then if I ask somithing like:
what can you tell me about art:
`response = top_agent.chat(what about art?)`
it gives me the following error reported in the traceback.
it seems that it can not find anymore the tool.

let me know.

### Version

0.8.48

### Steps to Reproduce

- follow the documentation on [https://gpt-index.readthedocs.io/en/stable/examples/agent/multi_document_agents.html](url).

change from:
`response=top_agent.query("tell me more about boston?")`
to:
`response=top_agent.chat("tell me more about boston?")`

start chatting with out giving topic reference after the first message.

### Relevant Logs/Tracbacks

```shell
ValueError                                Traceback (most recent call last)
c:\Users\erric\Desktop\Python\17-llama-index-experiments.py\00-llama_index_notebooks\04_multi_documents_chat.ipynb Cell 18 line 7
      5 print(last_used_tool)
      6 new_question=question_from_user+last_used_tool
----> 7 response = top_agent.chat("what about art?")
      9 print (response)

File c:\Users\erric\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\callbacks\utils.py:39, in trace_method.<locals>.decorator.<locals>.wrapper(self, *args, **kwargs)
     37 callback_manager = cast(CallbackManager, callback_manager)
     38 with callback_manager.as_trace(trace_id):
---> 39     return func(self, *args, **kwargs)

File c:\Users\erric\AppData\Local\Programs\Python\Python311\Lib\site-packages\llama_index\agent\openai_agent.py:342, in BaseOpenAIAgent.chat(self, message, chat_history, function_call)
    331 @trace_method("chat")
    332 def chat(
    333     self,
   (...)
    336     function_call: Union[str, dict] = "auto",
    337 ) -> AgentChatResponse:
    338     with self.callback_manager.event(
    339         CBEventType.AGENT_STEP,
    340         payload={EventPayload.MESSAGES: [message]},
    341     ) as e:
--> 342         chat_response = self._chat(
...
     38 if name not in name_to_tool:
---> 39     raise ValueError(f"Tool with name {name} not found")
     40 return name_to_tool[name]

ValueError: Tool with name tool_Boston not found
```

**Comment by ElioErrico** [comment]
Hello, answer not so usefull, by the way I solved like this:

```

def extract_tool_name_from_penultimate_message(chat_history):
    
    # Verifica se ci sono abbastanza messaggi nella lista
    if len(chat_history) < 2:
        return None

    # Ottiene il penultimo messaggio
    penultimate_message = chat_history[-2]

    # Ottiene il campo 'additional_kwargs' del penultimo messaggio
    additional_kwargs = penultimate_message.additional_kwargs

    # Cerca il campo 'name' in 'additional_kwargs'
    tool_name = additional_kwargs.get('name')
    if tool_name==None:
        return ""
    else:
        return tool_name
```


```
def answer(top_agent, question_from_user):
    try:
        chat_history = top_agent.chat_history
        print("\n --- \n")
        print(chat_history)
        print("\n --- \n")
        last_used_tool = extract_tool_name_from_penultimate_message(chat_history)
        print(last_used_tool)
        response = top_agent.chat(question_from_user)
    except ValueError as e:
        error_message = str(e)
        if "not found" in error_message:
            print("Errore: Tool not found. Procedo con il codice alternativo.")
            chat_history = top_agent.chat_history
            print("\n --- \n")
            print(chat_history)
            print("\n --- \n")
            last_used_tool_after_error= extract_tool_name_from_penultimate_message(chat_history)
            print(f"Ultimo tool utilizzato dopo errrore: {last_used_tool_after_error} ")
            print(f"Ultimo tool utilizzato: {last_used_tool}")
            question = f"{question_from_user}. ({last_used_tool})"
            print(f"Nuova domanda: {question}")
            response = top_agent.chat(question)
        else:
            # Gestione di altri ValueError non riconosciuti
            print("Errore sconosciuto:", e)
    else:
        print("Nessun errore riscontrato.")
        # Codice da eseguire se non ci sono errori

    return response

```

it  will use a new tool if it is defined in the message while it while take the previous tool if it is not defined in the message.
I think it is not really clean but this is the solution I found let me know.
Working for me... for now

```

response=answer(top_agent, " qualche curiosità?")
print(str(response))

```

**Comment by Disiok** [comment]
Thanks for raising the issue @ElioErrico! Looping in @nerdai to take a quick look

**Comment by noviljohnson** [comment]
Hi [ElioErrico](https://github.com/ElioErrico)
i am also following the same Multi-Document Agents  : [https://gpt-index.readthedocs.io/en/stable/examples/agent/multi_document_agents.html](https://github.com/run-llama/llama_index/issues/url)

did u face any issue like description is too long

=== Calling Function ===
Calling function: 2311_17815_pdf with args: {
  "input": "sections"
}
STARTING TURN 1
---------------

Got output: Error: Error code: 400 - {'error': {'message': "'Useful for questions related to specific aspects of the following listed .........................................
 - HPZMO, 5.4 HLS-based Design Flows for Deep Learning, 6 DEEP LEARNING COMPILERS, Approximate computing approaches, Source code compilation'  is too long  - 'tools.0.function.description'", 'type': 'invalid_request_error', 'param': 
None, 'code': None}}

do you know how to solve.


thanks.
