### ISSUE TITLE
[Question]: PGVectorStore’s QueryResult always returns saved Node as TextNode. Is this intended?

### ISSUE THREAD

**Issue by jacepark12** [run-llama/llama_index#8240]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, I am running the ["Joint tabular/semantic QA"](https://github.com/run-llama/llama_index/blob/main/docs/examples/query_engine/sec_tables/tesla_10q_table.ipynb) example from the documentation, which creates two types of nodes. In this example, `UnstructuredElementNodeParser` creates `IndexNode` and `TextNode`, with `IndexNode` capturing the caption of tabular data and saving the `TextNode`'s ID containing raw tabular data. Everything works fine without additional changes. However, when I add an external storage context (Postgres vector store for this case), IndexNode is not properly processed by `RecursiveRetriever`, since every retrieved nodes are TextNode.

I have found that the problem arises because when querying from `PGVectorStore`, it always returns nodes as `TextNode`. I assume other vector stores behave similarly, as the `metadata_dict_to_node` function from `vector_stores.utils` consistently returns `TextNode`.

I wonder if this behavior is intentional. 
Also, if this behavior is intentional, what would be the best approach to persist IndexNode? I have considered using another storage method for IndexNode, but since it needs to be queried alongside other nodes, I have temporarily customized the PGVectorStore code for my needs.

Thank you!

**Comment by Disiok** [comment]
Hey @pRivAte12, thanks for raising this. Looks like a bug. Will look into it for a fix soon!
