### ISSUE TITLE
Improvements to Slack Reader

### ISSUE THREAD

**Issue by mulka** [run-llama/llama_index#8245]
### Feature Description

Wondering if the Slack Reader should be improved. The context doesn't seem to have the real channel name nor the users names who post there.

```
Context information is below.
---------------------
channel: CAMPGT6R3

hi

<@U062YH5FXCG> has joined the channel
---------------------
Given the context information and not prior knowledge, answer the query.
Query: <query here>
Answer: 
```

**Comment by Disiok** [comment]
Thanks for the suggestion @mulka ! The Slack reader probably needs some love. 

AFAIK, we have a more up-to-date version via LlamaHub: https://llamahub.ai/l/slack
Maybe check if that satisfies your use-case.

We always welcome community contribution to continuously improve these!
