### ISSUE TITLE
[Bug]:  Getting "Importing PromptTemplate from langchain root module is no longer supported." when I import PromptTemplate from llama-index

### ISSUE THREAD

**Issue by kaushalpowar** [run-llama/llama_index#8247]
### Bug Description

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/langchain/__init__.py:24: UserWarning: Importing PromptTemplate from langchain root module is no longer supported.

### Version

0.8.35

### Steps to Reproduce

from llama_index.prompts import PromptTemplate
 shows this mentioned error.

**Comment by Disiok** [comment]
Try upgrading to the latest version of llama index, I think this is fixed a couple versions ago!
