### ISSUE TITLE
llama_index , SimpleDirectoryReader , chunk size and overlap

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8253]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi ,

I wonder why SimpleDirectoryReader doesn't have chunk size and overlap parameters similar to LangChain ?
If any optimization is performed during parsing file to Documents ?
If any has experience to combine Langchain's SimpleDirectoryReader and llama_index's documents handling ?

Thanks,
Nissim

**Comment by Disiok** [comment]
Hey @snassimr, the document reading step doesn't actually split the documents into smaller chunks. 

The splitting step is performed later when we run `index.from_documents(docs)`, which calls the node parser under the hood.
