### ISSUE TITLE
[Bug]: not skipping `test_s3_kvstore` in CI

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#8264]
### Bug Description

https://github.com/run-llama/llama_index/issues/8242 could exist because it's currently entirely skipped in CI.

Can we make it such that it's not skipped in CI?

### Version

0.8.48

### Steps to Reproduce

https://github.com/run-llama/llama_index/actions/runs/6619499991/job/17980163809?pr=8263

See "Run testing" section

### Relevant Logs/Tracbacks

```shell
tests/storage/kvstore/test_s3_kvstore.py ssssss                          [ 75%]
```

**Comment by jamesbraza** [comment]
Imo, the common practice of `skipif` for many tests that didn't have the `pip install` leads to problems like this surfacing over time, because tens of test cases aren't actually being run in CI.

It would be good to pay down the tech debt, and remove the `skipif`s in testing. Use of `unittest.mock.patch` is the way 🚢

**Comment by Disiok** [comment]
ya at a high-level I agree, it's just a matter of creating the right right dependency group for CI testing. Just haven't gotten around to 😅 , would love any help here!) 

(we already use mocks `from moto import mock_s3` so should already work in CI environment).

**Comment by jamesbraza** [comment]
@dosubot this issue remains relevant because the tests are still skipped in CI, so it's not stale
