### ISSUE TITLE
[Feature Request]: Change the return type of `BaseReader.load_data` from `list` to `Iterable`

### ISSUE THREAD

**Issue by david20571015** [run-llama/llama_index#8454]
### Feature Description

The proposal is to change the return type of the [`BaseReader.load_data`](https://github.com/run-llama/llama_index/blob/91649e1d7f0a97461ede59191e7da1413672c242/llama_index/readers/base.py#L14) method from `List[Document]` to `Iterable[Document]`.

before:

```python
def load_data(self) -> List[Document]:
    documents = []
    for file in files:
        doc = read_file(file)
        documents.append(doc)
    return documents
```

after:

```python
def load_data(self) -> Iterable[Document]:
    for file in files:
        doc = read_file(file)
        yield doc
```

This change might be considered a *breaking change*.

before:

```python
docs = reader.load_data()
print(docs[0])
```

after:

```python
docs = list(reader.load_data())
print(docs[0])
```

### Reason

The current implementation of [`BaseReader.load_data`](https://github.com/run-llama/llama_index/blob/0c938097aa1415ad297dddc26fe2b616e2bb7f40/llama_index/readers/base.py#L14) returns `List[Document]`, which loads all data into memory at once, potentially causing memory exhaustion and `MemoryError`.

### Value of Feature

Changing the return type to `Iterable` and implementing lazy loading using a generator can significantly reduce memory usage.

**Comment by Disiok** [comment]
Thanks for the suggestion! I think this would be too much of a breaking change if we directly change the endpoint. Would be a good idea to expose a separate endpoint for returning an iterator though.

**Comment by david20571015** [comment]
How about adding a function `BaseReader.lazy_load_data` and delegating `BaseReader.load_data` to it?

```python
class BaseReader(ABC):

    def lazy_load_data(self, *args: Any, **load_kwargs: Any) -> Iterable[Document]:
        """Load data from the input directory lazily."""
        raise NotImplementedError(f"{self.__class__.__name__} does not provide lazy_load_data method currently")

    def load_data(self, *args: Any, **load_kwargs: Any) -> List[Document]:
        """Load data from the input directory."""
        return list(self.lazy_load_data(*args, **load_kwargs))
```

This approach ensures backward compatibility and allows us to gradually update existing classes.

**Comment by nerdai** [comment]
Thanks @david20571015!

I think the addition of a `lazy_load_data` function and delegating it to `load_data` for backwards compatibility is a good idea.
