### ISSUE TITLE
[Question]: Clarity on managing document stored in Vector stores that store embeddings and text

### ISSUE THREAD

**Issue by OliverFarren** [run-llama/llama_index#8458]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, we've recently moved from using the disk based SimpleVectorStore to using the PineconeVectorStore and with that change there are some aspects of our document management I am no longer clear how I should be managing.

Specifically around how I aught to go about deleting a specific document and or checking for it's existence. Let me go through a rough example.

Suppose I had a 10 page pdf document called 'super-awesome.pdf' we'd first load into some documents:
``` python
from pathlib import Path
from typing import Optional
from llama_hub.file.pdf.base import PDFReader
from llama_index import Document

def load_file_into_document_pdf(
    file_path: Path, extra_info: Optional[dict] = None
) -> list[Document]:
    loader = PDFReader()
    pdf: list[Document] = loader.load_data(file=file_path, extra_info=extra_info)
    return pdf
```

This would return an array of 10 Documents, each containing some metadata including the `page_label` and `file_name`. The doc_id is a randomly generated uuid4. 

We then add each of these to the index like:
``` python
index: VectorStoreIndex = get_index()
pdf = load_file_into_document_pdf(file_path)
for page in pdf:
    index.insert(page)
```

With the change to Pinecone my understanding is that we're not really using (or needing to use) the `docstore` or `index_store` and the `index.ref_doc_info` property is no longer implemented so i'm unsure what the standard way is of avoiding uploading the same document twice? Or subsequently deleting a document based on it's filename. 

I could manage this myself with a simple kv store, and store the doc-ids under a file-name key or something but it sort of feels like there should be a way within llama-index to do this. It seems I could also following an insert to the index, invoke:
``` python
nodes = index.service_context.node_parser.get_nodes_from_documents(
    [page]
)
index.docstore.add_document(nodes)
```

And then maybe the metadata gets stored? But then i'm also storing my nodes in my k-v store AND in my vector store, when really all I want is the metadata-id mapping. 

Is this something I could get clarity on?

**Comment by OliverFarren** [comment]
Thankyou for clarifying. It looks like the management hinges on knowing the document-id and there's nothing currently within llama index to manage the mapping between document-ids and corresponding metadata. Which i'm a bit surprised at, given these would surely be a common usage pattern?

Essentially what I want is a way to use something like the `RedisDocumentStore` but to store only the metadata and not the nodes. 

For now i'll write my own.

**Comment by logan-markewich** [comment]
Actually there is a way! But it's a little hidden, but here's a link to our discord where I explained this

https://discord.com/channels/1059199217496772688/1163880111074971790/1163900056718553169

**Comment by logan-markewich** [comment]
@OliverFarren ^^

**Comment by OliverFarren** [comment]
Hi Logan, thanks for the link, I had a read through but i'm not sure it resolves my issue because my usage pattern is around the filename. For now i'll be trying something like this
``` python
        document_pages = load_file_into_document(source_path, extra_info)
        page_count = 0
        for page in document_pages:
            file_name = page.extra_info['file_name']
            nodes = index.service_context.node_parser.get_nodes_from_documents(
                [page]
            )
            index.insert_nodes(nodes)
            # store the node-ids against the file_name so we can manage later
            for node in nodes:
                store.sadd(key=file_name, value=str(node.node_id))
```

**Comment by OliverFarren** [comment]
And just to further clarify. Previously we would have managed the deletion of a file based on it's filename using the `ref_doc_info`

``` python
def get_ref_docs_for_file(
    index: VectorStoreIndex, file_name: str
) -> dict[str, RefDocInfo]:
    """
    Returns the subset of documents and their document info that relate to a given file_name

    Typically, this is will be a dictionary of len(N) where N == number of pages in the original file.
    Where each document represents a page.
    """
    ref_doc_info_by_doc_id_all: dict[str, RefDocInfo] = index.ref_doc_info

    ref_doc_info_by_doc_id: dict[str, RefDocInfo] = dict()
    for doc_id, ref_doc_info in ref_doc_info_by_doc_id_all.items():
        file_name_in_index = ref_doc_info.metadata["file_name"]
        if file_name_in_index == file_name:
            ref_doc_info_by_doc_id[doc_id] = ref_doc_info

    return ref_doc_info_by_doc_id

def remove_source_documents_for_file(index, file_name: str) -> int:
    """
    Removes documents from the index that match the specified file name.

    Args:
        index: The loaded index for document removal
        file_name (str): The name of the file that was originally uploaded

    Returns:
        int: The count of documents that were removed from the index.
    """

    ref_doc_info_by_doc_id = get_ref_docs_for_file(index, file_name)
    count = 0
    for doc_id, ref_doc in ref_doc_info_by_doc_id.items():
        index.delete_ref_doc(doc_id, delete_from_docstore=True)
        page_label = ref_doc.metadata["page_label"]
        logger.debug(f"Deleted {file_name!r} - page: {page_label!r}")
        count += 1

    log_message = f"{count} documents removed for {file_name=}"
    logger.info(log_message) if count else logger.warning(log_message)
    return count
```
