### ISSUE TITLE
[Documentation]: Mistyped word In Install documentation. (aronund -> around)

### ISSUE THREAD

**Issue by davidearlyoung** [run-llama/llama_index#8461]
### Documentation Issue Description

There is a mistyped word in your documentation. (LlamaIndex version 0.8.50, current stable branch as of time of creation of this issue.)

It can be found at: https://docs.llamaindex.ai/en/stable/getting_started/installation.html#local-environment-setup  ("Local Environment Setup" header at the bottom of the page.)  Second paragraph, last sentence of that second paragraph.

"This will use aronund 11.5GB of memory across the CPU and GPU." is the sentence in question. And "aronund" is the word that is mistyped. I'm assuming that the writer means "around" based off of the surrounding context.

I'm not interested in taking time to make the adjustments myself. So please don't ask me to correct it my self using cloning and PR methods.

I hope that this helps. Thanks for your time.

### Documentation Link

https://docs.llamaindex.ai/en/stable/getting_started/installation.html#local-environment-setup

**Comment by Disiok** [comment]
Thanks for raising the issue!

**Comment by davidearlyoung** [comment]
You are welcome.
