### ISSUE TITLE
[Feature Request]: Extend PGVectorStore to Support Custom Schemas and Tables

### ISSUE THREAD

**Issue by darkovelkoski** [run-llama/llama_index#8471]
### Feature Description

Ideally PGVectorStore should be flexible enough to work with custom schemas and tables.
It should allow for integration with existing projects that have predefined database structures, without enforcing the use of specific tables or schemas.

### Reason

We are trying to integrate llama_index into our existing project that is based on Python, PostgreSQL, pgvector, SQLAlchemy, and Alembic. Our database consists of several tables with custom schema. We want to leverage the advanced functionalities of llama_index, such as hybrid search, metadata filtering, etc., however, it seems that llama_index primarily works on the public schema and operates on predefined tables within the library's code, making it challenging to apply its functionalities directly to our custom tables and schema.

### Value of Feature

Customization and Flexibility

Users with existing database structures won’t need to modify their schemas or table designs to accommodate llama_index. This makes the library more adaptable and easier to integrate into existing projects.

The library’s functionalities would become applicable in a wider range of scenarios and use-cases, given its increased compatibility with various database designs.

With increased flexibility, the library is likely to see broader adoption in the developer community, as it could be applied in a more diverse range of projects and use-cases.

Projects can scale more efficiently without being constrained by rigid library schemas and table structures.

**Comment by nerdai** [comment]
@Disiok This seems like a worthwhile add. I did a quick search on this (so there could be better solutions), but it looks like we can configure the engine to connect to a specific set of schemas.

```py
dbschema='schema1,schema2,public' # Searches left-to-right
engine = create_engine(
    'postgresql+psycopg2://dbuser@dbhost:5432/dbname',
    connect_args={'options': '-csearch_path={}'.format(dbschema)})
```
