### ISSUE TITLE
[Feature Request]: Global manager for default promt templates.

### ISSUE THREAD

**Issue by Inkorak** [run-llama/llama_index#8473]
### Feature Description

I would really like to have a global manager in which you can change the default templates for prompts, rather than manually entering them for each llama index object that use them. This will be especially useful for localization into other languages, since if you need to use llama_index and chatgpt (or other models) to work with text and chat in other languages, almost all the templates need to be changed so that the model adheres to this language without problems.

**Comment by nerdai** [comment]
Thanks @Inkorak! This is something that we've been very recently thinking about how to better incorporate into our library.

More to come on soon on this.

(CC: @jerryjliu)
