### ISSUE TITLE
[Documentation]: Missing Link to Blog Post

### ISSUE THREAD

**Issue by bllchmbrs** [run-llama/llama_index#8476]
### Documentation Issue Description

Missing documentation link to the blog post on [the tools page](https://docs.llamaindex.ai/en/stable/core_modules/agent_modules/tools/root.html#blog-post).

> For full details, please check out our detailed blog post.

The problem is, there is no link to the blog post.

I assume [this](https://blog.llamaindex.ai/building-better-tools-for-llm-agents-f8c5a6714f11) is the blog post but not 100% sure.

### Documentation Link

https://docs.llamaindex.ai/en/stable/core_modules/agent_modules/tools/root.html#blog-post

**Comment by aaronjimv** [comment]
Hello @bllchmbrs. I just checked the blog post in question and the link is there, and works correctly. I think we can close this issue.

![Screenshot 2023-11-06 182929](https://github.com/run-llama/llama_index/assets/67152883/a0708fb6-d287-491a-9d7e-f7f437548d4b)
