### ISSUE TITLE
Open source aalternative for OpenAIAgent

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8482]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello ,

I have code some pipeline that contain the code : 

`
function_llm = OpenAI(model = 'gpt-3.5-turbo-16k')

agent = OpenAIAgent.from_tools(
    query_engine_tools,
    llm=function_llm,
    verbose=True, 
)
`

I guess OpenAI in function_llm can be rerplaced by HuggingFaceLLM

Any open source alternative for OpenAIAgent ?

Thanks

**Comment by logan-markewich** [comment]
You can hook any LLM into a react agent (note that you'll need a pretty large LLM to be reliable, 70B or so)

https://gpt-index.readthedocs.io/en/stable/core_modules/agent_modules/agents/usage_pattern.html

**Comment by snassimr** [comment]
[@logan-markewich](https://github.com/logan-markewich) I learned a little bit about ReactAgent you've proposed . I pretty understand why we need 70b model . Happy as we go we already have 7b models that take over some 70b models -:)

I reviewed [this](https://gpt-index.readthedocs.io/en/latest/examples/chat_engine/chat_engine_react.html) and I wonder if the example there can be extended to 2 query engine tools (technically) and if chat engine able to choose between two QueryEngineTools ?
