### ISSUE TITLE
How can I select specific documents for question-answering after completing the vectorization (embedding) of all documents?[Question]: 

### ISSUE THREAD

**Issue by FreeRotate** [run-llama/llama_index#8488]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I select specific documents for question-answering after completing the vectorization (embedding) of all documents?

**Comment by Disiok** [comment]
Do you mean that you want to do semantic search only within a document?

**Comment by FreeRotate** [comment]
> 您的意思是只在文档中进行语义搜索吗？

I currently want to retrieve background knowledge and perform question-answering based on one of the documents in the document library, without involving other files in the document library. And there is no need to vectorize this file again, as all the files in the document library have already been vectorized when using VectorStoreIndex.from_documents.
