### ISSUE TITLE
[Bug]: Type for output_cls in BaseSynthesizer.__init__() should be Optional[Type[BaseModel]]

### ISSUE THREAD

**Issue by pikalaw** [run-llama/llama_index#8506]
### Bug Description

In [llama_index/response_synthesizers/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/response_synthesizers/base.py#L41), the argument `output_cls` is currently typed as `BaseModel`:

```python
    def __init__(
        self,
        service_context: Optional[ServiceContext] = None,
        streaming: bool = False,
        output_cls: BaseModel = None,
    ) -> None:
```

I think it should be `Optional[Type[BaseModel]]` instead:

```python
    def __init__(
        self,
        service_context: Optional[ServiceContext] = None,
        streaming: bool = False,
        output_cls: Optional[Type[BaseModel]] = None,
) -> None:
```

To make the type checker happy, [line 123](https://github.com/run-llama/llama_index/blob/main/llama_index/response_synthesizers/base.py#L123) should be changed from:

```python
        if isinstance(response_str, self._output_cls):
```

to

```python
        if self._output_cls is not None and isinstance(response_str, self._output_cls):
```

### Version

0.8.48

### Steps to Reproduce

I wrote this code:

```python
class SynthesizedResponse(BaseModel):
    answer: str
    attributed_passages: List[str]
    answerability_probability: float


class MyTextSynthesizer(BaseSynthesizer):
    def __init__(self, **kwargs: Any):
        super().__init__(output_cls=SynthesizedResponse, **kwargs)
```

**Comment by Disiok** [comment]
Good catch, I'm not sure why our linter didn't catch this.

**Comment by pikalaw** [comment]
It’s not a big issue. Just minor annoyance with the type checker. Since I discovered it and it’s not a big deal to fix, please assign it to me. I’ll be happy to provide a PR to fix it.

I tried to assign it to myself, but the github UI won’t let me.
