### ISSUE TITLE
[Bug]: Top_k score issue with ElasticSearch Vector DB

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#8510]
### Bug Description

Hi,
I have a set of documents for which i have created embeddings and stored it in ElasticSearch vector db.
Now when i am loading the index from ES and retrieving the top_k for a query i am always getting the score as 1.00 or .99 which is very high. I compared exact same replica storing in different vector DB like Faiss etc. The retrieved docs are same but score vary, i get reasonable score in Faiss like .7 etc. But not sure whats wrong with ElasticSearch it always gives ~1.0 score for top k docs. Any idea how to fix the score with ES?

storage_context_ins_es = StorageContext.from_defaults(vector_store=vector_store_ins)
index_ins_es = VectorStoreIndex.from_vector_store(
    vector_store=vector_store_ins,
    storage_context=storage_context_ins_es,
    service_context=service_context_ins_es
    )
top_k=3 #for top hit
##ES retriever
retriever = index_ins_es.as_retriever(similarity_top_k=top_k)
nodes_with_scores = retriever.retrieve("xyz")

![image](https://github.com/run-llama/llama_index/assets/39477047/ec10d156-bb92-40fe-b25b-37f5ed6a4dcb)

### Version

8.48

### Steps to Reproduce

attached code snippet above.

**Comment by Disiok** [comment]
Hey @amitguptadumka , thanks for raising this issue. Right now there's a fixed step in the implementation where we normalize the score of the retrieved nodes:

```
def _to_llama_similarities(scores: List[float]) -> List[float]:
    scores_to_norm: np.ndarray = np.array(scores)
    return np.exp(scores_to_norm - np.max(scores_to_norm)).tolist()
``` 

In the case where the returned nodes have very similar scores, they'd get mapped to all close to 1.
If you like, feel free to create a PR to make this normalization configurable so users can choose how to interpret the scores.

**Comment by psoucy** [comment]
I also believe this is a bug and this should be reopened. I don't think the normalization should be configurable: it shouldn't be done at all. Normalizing similarity scores results in values that aren't similarities anymore. Also, any normalization makes this vectorstore behavior different from other vectores in llama-index, such as Chromadb.
