### ISSUE TITLE
[Bug]: Not able to use BM25Retriever with ElasticSearch Vector DB

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#8511]
### Bug Description

Hi,
BM25 retriever works fine if i store the embeddings in local or Faiss vector db. But when i am storing it in ES vector db it starts giving below error:

from llama_index.retrievers import BM25Retriever
bm25_retriever = BM25Retriever.from_defaults(docstore=index_ins_es.docstore, similarity_top_k=3)

![image](https://github.com/run-llama/llama_index/assets/39477047/5069400e-7683-484a-a09f-5af38330dcb9)

How to fix this please?

### Version

8.48

### Steps to Reproduce

from llama_index.retrievers import BM25Retriever
bm25_retriever = BM25Retriever.from_defaults(docstore=index_ins_es.docstore, similarity_top_k=3)
with ElasticSearch vector DB

**Comment by amitguptadumka** [comment]
> _🤖_
> 
> Hello @amitguptadumka,
> 
> I'm here to assist you with your issue. From the information you've provided, it seems like you're trying to use the BM25Retriever with embeddings stored in ElasticSearch Vector DB. However, the BM25Retriever in LlamaIndex version 8.48 does not support embeddings. This is evident from the warning message in the `_retrieve` method of the `BM25Retriever` class:
> 
> ```python
> if query_bundle.custom_embedding_strs or query_bundle.embedding:
>     logger.warning("BM25Retriever does not support embeddings, skipping...")
> ```
> 
> This means that if you try to use embeddings with the BM25Retriever, it will simply skip them and log a warning message.
> 
> To resolve this issue, you would need to use a different retriever that supports embeddings, or modify the BM25Retriever to support embeddings, which could be a complex task requiring a deep understanding of both the BM25 algorithm and how embeddings work.
> 
> If you want to continue using the BM25Retriever, you should avoid using embeddings and instead rely on the text-based retrieval capabilities of the BM25 algorithm.
> 
> You can find more details in the [source code](https://github.com/run-llama/llama_index/blob/main/llama_index/retrievers/bm25_retriever.py).
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> Best, Dosu
> 
> ## Sources
> * [llama_index/retrievers/bm25_retriever.py](https://github.com/run-llama/llama_index/blob/main/llama_index/retrievers/bm25_retriever.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

But i am able to use it with Faiss vector DB. Basically i am trying to use hybrid way of lexical+semantic retrieval.
Can you please help me how to create a hybrid retriever as above. If BM is not supported what should i use for lexical?

**Comment by amitguptadumka** [comment]
@dosu-bot
The exact error message is as below:
ZeroDivisionError                         Traceback (most recent call last)
Cell In[6], line 4
      1 from llama_index.retrievers import BM25Retriever
      2 #nodes = service_context.node_parser.get_nodes_from_documents(documents)
      3 #nodes = service_context.node_parser.get_nodes_from_documents(documents)
----> 4 bm25_retriever = BM25Retriever.from_defaults(docstore=index_ins_es.docstore, similarity_top_k=3)

File ~/anaconda3/envs/llama_index_venv/lib/python3.10/site-packages/llama_index/retrievers/bm25_retriever.py:58, in BM25Retriever.from_defaults(cls, index, nodes, docstore, tokenizer, similarity_top_k)
     53 assert (
     54     nodes is not None
     55 ), "Please pass exactly one of index, nodes, or docstore."
     57 tokenizer = tokenizer or globals_helper.tokenizer
---> 58 return cls(
     59     nodes=nodes,
     60     tokenizer=tokenizer,
     61     similarity_top_k=similarity_top_k,
     62 )

File ~/anaconda3/envs/llama_index_venv/lib/python3.10/site-packages/llama_index/retrievers/bm25_retriever.py:32, in BM25Retriever.__init__(self, nodes, tokenizer, similarity_top_k)
     29 self._similarity_top_k = similarity_top_k
     30 self._corpus = [self._tokenizer(node.get_content()) for node in self._nodes]
---> 32 self.bm25 = BM25Okapi(self._corpus)

File ~/anaconda3/envs/llama_index_venv/lib/python3.10/site-packages/rank_bm25.py:83, in BM25Okapi.__init__(self, corpus, tokenizer, k1, b, epsilon)
     81 self.b = b
     82 self.epsilon = epsilon
---> 83 super().__init__(corpus, tokenizer)

File ~/anaconda3/envs/llama_index_venv/lib/python3.10/site-packages/rank_bm25.py:27, in BM25.__init__(self, corpus, tokenizer)
     24 if tokenizer:
     25     corpus = self._tokenize_corpus(corpus)
---> 27 nd = self._initialize(corpus)
     28 self._calc_idf(nd)

File ~/anaconda3/envs/llama_index_venv/lib/python3.10/site-packages/rank_bm25.py:52, in BM25._initialize(self, corpus)
     48             nd[word] = 1
     50     self.corpus_size += 1
---> 52 self.avgdl = num_doc / self.corpus_size
     53 return nd

ZeroDivisionError: division by zero

**Comment by Disiok** [comment]
Hey @amitguptadumka, to use hybrid search with elastic search, you should directly use the `hybrid search` query mode on the `ElasticsearchStore` itself.

**Comment by amitguptadumka** [comment]
> Hey @amitguptadumka, to use hybrid search with elastic search, you should directly use the `hybrid search` query mode on the `ElasticsearchStore` itself.
> 
> For example:
> 
> ```
> query_engine = index.as_query_engine(vector_store_query_mode="hybrid")
> ```

@Disiok : So here i'm not exactly using query_engine to generate response rather my focus is just on the retriever for context. So while doing that i am not able to use hybrid way (semantic+lexical) with ES, since according to bot BM25 is not supported with elastic. just want to know how to build the lexical retriever to make it hybrid with ES?

**Comment by Disiok** [comment]
you can pass the same option for retriever:
`retriever = index.as_retriever(vector_store_query_mode="hybrid")`

**Comment by amitguptadumka** [comment]
> vector_store_query_mode="hybrid"

Sure @Disiok Thanks. Also wanted to know which retriever it usages internally for the lexical/keyword search and what ratio for top_k is being retrieved from both.

**Comment by chrispangg** [comment]
I am also getting division by zero using Chromadb. Sadly, ChromaDB doesn't support Hybrid search so I can't use the solution above...
