### ISSUE TITLE
How is DataGenerator working ?

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8516]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi ,

I wonder what all sub-tools are used by DataGenerator and should be defined in ServiceContext ?

For example , I saw this snippet below and looks like it's possible to define custom llm 

documents = SimpleDirectoryReader('./data').load_data()
from llama_index.evaluation import DatasetGenerator
data_generator = DatasetGenerator.from_documents(documents, service_context=service_context)
eval_questions = data_generator.generate_questions_from_nodes()

But ServiceContext can contain other sub-definitions : SimpleNodeParser, Embed Model and etc.

How I know what should be define for DataGenerator ? Any reference is more than welcome.

Thanks

**Comment by snassimr** [comment]
After searching on https://github.com/run-llama/llama_index/blob/main/llama_index/indices/service_context.py and  [llama_index/evaluation/dataset_generation.py](https://github.com/run-llama/llama_index/blob/main/llama_index/evaluation/dataset_generation.py) it looks like only llm and node parser from ServiceContext actually used by DatasetGenerator ...

**Comment by ravi03071991** [comment]
@snassimr Yeah, only LLM and node parser are used as internally we use SummaryIndex for generating questions which does not need any embedding model.
