### ISSUE TITLE
[Bug]: custom prompt not working for sql query as expected , it's not able to pick the instructed column 

### ISSUE THREAD

**Issue by akashkumar398** [run-llama/llama_index#8517]
### Bug Description

When formulating a query, the SQL query encounters difficulties in comprehending the requested column from the prompt

selecting non relevant column 

### Version

latest 

### Steps to Reproduce

llm = OpenAI(temperature=0.1, model="gpt-3.5-turbo")

service_context = ServiceContext.from_defaults(
  llm=llm,callback_manager=callback_manager
)

from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine

query_engine = NLSQLTableQueryEngine(
    sql_database=sql_database,
    service_context=service_context
)

custom_prompt = """
follow the instructions if needed:
    When given an inquiry of id, select the 'status' column"
"""

token_counter.reset_counts()
query_str = "What is the inqiry of id 1234?"
response = query_engine.query(custom_prompt + " " + query_str)
print(response.response)
print('token_counter:',token_counter.total_llm_token_count)

**Comment by Disiok** [comment]
Hey @akashkumar398, the sql query engine could be fairly sensitive to model and prompt. Best to try with gpt-4 (or another LLM with high reasoning capability like Claude-2).
