### ISSUE TITLE
[Bug][Retriever]: ValueError: You must provide either query embeddings or query texts, but not both

### ISSUE THREAD

**Issue by vincentteyssier** [run-llama/llama_index#8523]
### Bug Description

chromadb==0.4.14
llama_index==0.8.45.post1

```
import chromadb
from chromadb.config import Settings
from llama_index.vector_stores import ChromaVectorStore
...

db = chromadb.PersistentClient(path="./chroma_db", settings=Settings(anonymized_telemetry=False))
chroma_collection = db.get_or_create_collection("cc")
vector_store= ChromaVectorStore(chroma_collection=chroma_collection)

res = vector_store.query(
        VectorStoreQuery(
            query_embedding=None, 
            similarity_top_k=2, 
            doc_ids=None, 
            node_ids=None, 
            query_str='', 
            output_fields=None, 
            embedding_field=None, 
            mode=VectorStoreQueryMode.DEFAULT, 
            alpha=None, 
            filters=MetadataFilters(filters=[ExactMatchFilter(key='location', value='France')]), 
            mmr_threshold=None, 
            sparse_top_k=None
        )
    )
```

For info this is the standard query generated by the autoretriever function:
```
retriever = VectorIndexAutoRetriever(index, vector_store_info=vector_store_info)
response = retriever.retrieve(input)
```

I try to send that vectorstorequery to Chroma but it fails with the following.
I've tried adding text in the query_str field, or remove most of the fields including removing query_embedding, but nothing works and I get the following error:

_Error:
"  File "//venv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 200, in query
    raise ValueError(
ValueError: You must provide either query embeddings or query texts, but not both"_

### Version

0.8.45.post1

### Steps to Reproduce

Run code above

### Relevant Logs/Tracbacks

```shell
_Error:
"  File "//venv/lib/python3.10/site-packages/chromadb/api/models/Collection.py", line 200, in query
    raise ValueError(
ValueError: You must provide either query embeddings or query texts, but not both"_
```

**Comment by vincentteyssier** [comment]
From what I see in Chroma code the error comes because of this:

```
if (query_embeddings is None and query_texts is None) or (
            query_embeddings is not None and query_texts is not None
        ):
            raise ValueError(
                "You must provide either query embeddings or query texts, but not both"
            )
```

However I don't find where query_str from llama_index query is mapped to query_texts.
I guess the issue is somewhere there.

**Comment by vincentteyssier** [comment]
The query function in the vector_store/chroma.py doesn't seem to support query strings, but if the autoretriever doesn't find a query string, it will not generate any embedding and therefore query_embeddings will be None and query_texts not passed:

```
results = self._collection.query(
            query_embeddings=query.query_embedding,
            n_results=query.similarity_top_k,
            where=where,
            **kwargs,
        )
```

The query_str generated by the autoretriever should therefore be passed as query_texts in the query function of the chroma connector. Am I correct?
Not competent enough to fix it and submit a PR though

**Comment by vincentteyssier** [comment]
I think ultimately what we would want is to be able to do a wildcard text query to chroma if there is no query string output from the LLM, or a similarity search if we have a query string that can be transformed into embedding.

**Comment by vincentteyssier** [comment]
I've dig a bit more and it's slightly more complex to fix than I thought.

In Chroma for example, if you don't have a query_str or a query_embed, then you do not use the query method, you use the get method. But the get method is not implemented in the chroma connector.

I'm ending up writing a custom autoretriever where I check the presence of the query_str and use a direct get to chroma if empty, but that doesn't work for other vectorstore, so can't submit a PR there.

**Comment by Disiok** [comment]
Thanks for the discussion on this issue folks! Yea it's indeed a bit tricky.

The auto retriever code right now expects the LLM to output a query string. It's set as a mandatory param, but the LLM can still output an empty string, and this triggers the issue of having no query embeddings.

**Comment by Disiok** [comment]
> I think ultimately what we would want is to be able to do a wildcard text query to chroma if there is no query string output from the LLM, or a similarity search if we have a query string that can be transformed into embedding.

This makes sense to me. I think it's possible to implement this within the `ChromaVectorStore` class, instead of at the `VectorIndexAutoRetriever` level. This way we can still keep the chroma specific logic (e.g. in accessing get method when there's no query embedding).

**Comment by vincentteyssier** [comment]
I'm not sure about other vectorstore but I would assume this is an issue with others too, hence why I think it should be handled upstream.

**Comment by dtthanh1971** [comment]
@vincentteyssier 
I had the same problem.

```
If neither query_embeddings nor query_texts are provided, or both are provided, raise an error
    [196](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:196) if (query_embeddings is None and query_texts is None) or
    [197](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:197)     query_embeddings is not None and query_texts is not None
    [198](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:198) ):
--> [199](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:199)     raise ValueError(
    [200](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:200)         "You must provide either query embeddings or query texts, but not both."
    [201](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:201)     )
    [203](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:203) If query_embeddings are not provided, we need to compute them from the query_texts
    [204](file:///C:/Users/dttha/AppData/Local/Programs/Python/Python310/lib/site-packages/chromadb/api/models/Collection.py:204) if query_embeddings is None:

ValueError: You must provide either query embeddings or query texts, but not both
```
