### ISSUE TITLE
[Bug]: ValueError: Job ftjob-q9473swriULcraETTpC4HbPg does not have a finetuned model id ready yet.

### ISSUE THREAD

**Issue by BadrinathMJ** [run-llama/llama_index#8527]
### Bug Description

When I tried to use PDF other than mentioned in documentation. It is throwing ValueError: Job ftjob-q9473swriULcraETTpC4HbPg does not have a finetuned model id ready yet. I have referred this documentation link 
https://gpt-index.readthedocs.io/en/latest/examples/finetuning/knowledge/finetune_knowledge.html#fine-tuning-to-memorize-knowledge.

### Version

0.8.50

### Steps to Reproduce

`fp = open("data/qa_pairs_train.jsonl", "r")
out_fp = open("data/qa_pairs_openai.jsonl", "w")
# TODO: try with different system prompts
system_prompt = {
    "role": "system",
    "content": (
        "You are a helpful assistant helping to answer questions about the"
        " Llama 2 paper."
    ),
}
for line in fp:
    qa_pair = json.loads(line)
    user_prompt = {"role": "user", "content": qa_pair["query"]}
    assistant_prompt = {"role": "assistant", "content": qa_pair["response"]}
    out_dict = {
        "messages": [system_prompt, user_prompt, assistant_prompt],
    }
    out_fp.write(json.dumps(out_dict) + "\n")
from llama_index.finetuning import OpenAIFinetuneEngine

finetune_engine = OpenAIFinetuneEngine(
    "gpt-3.5-turbo",
    "data/qa_pairs_openai.jsonl",
    # start_job_id="<start-job-id>"  # if you have an existing job, can specify id here
)

finetune_engine.finetune()
`

### Relevant Logs/Tracbacks

----> [1](vscode-notebook-cell:/d%3A/Data_Llama2/FineTuning_with_OpenAI/fine_tuning_gpt3.5_turbo2.ipynb#X45sZmlsZQ%3D%3D?line=0) ft_model = finetune_engine.get_finetuned_model()

File [d:\Users\Mayur1\envs\llama\lib\site-packages\llama_index\finetuning\openai\base.py:112](file:///D:/Users/Mayur1/envs/llama/lib/site-packages/llama_index/finetuning/openai/base.py:112), in OpenAIFinetuneEngine.get_finetuned_model(self, **model_kwargs)
    109 model_id = current_job["fine_tuned_model"]
    111 if model_id is None:
--> 112     raise ValueError(
    113         f"Job {job_id} does not have a finetuned model id ready yet."
    114     )
    115 if status != "succeeded":
    116     raise ValueError(f"Job {job_id} has status {status}, cannot get model")

ValueError: Job ftjob-q9473swriULcraETTpC4HbPg does not have a finetuned model id ready yet.

**Comment by BadrinathMJ** [comment]
@dosu-bot Actually I am not getting the what is the file format is located at  `data_path` which is then uploaded OpenAI server due to insufficient documentation. If there is any link about this detailed explanation please let me know. Thank you for your help...

**Comment by Disiok** [comment]
Hey @BadrinathMJ , did you generate a dataset and launch a finetune job already? The error suggests that the finetune job is completed yet, so probably issues at earlier part of the notebook.

**Comment by BadrinathMJ** [comment]
@Disiok I already generated dataset in jsonl format and tried to finetune using following line of code 
`finetune_engine.get_current_job()`

When I tried to get the fine_tuned_model using
`ft_model = finetune_engine.get_finetuned_model()`

I got above error i.e. 
ValueError: Job ftjob-q9473swriULcraETTpC4HbPg does not have a finetuned model id ready yet.
