### ISSUE TITLE
[Bug]:  UnstructuredElementNodeParser doesn't pass llm/embed model to internally generated service_context

### ISSUE THREAD

**Issue by moshewe** [run-llama/llama_index#8536]
### Bug Description

I'm creating a `llm` and `embed_model` **_without_** setting the OpenAI environment variables for security reasons. 
I've passed in the `llm` constructor parameter to `UnstructuredElementNodeParser`. I get the message: `Could not load OpenAIEmbedding.` Looking deeper into the code I found that `UnstructuredElementNodeParser` creates an ad-hoc service context without the `embed_model` parameter, which I've also thought about passing in to its constructor but that isn't possible.

I think it's good practice to allow the parser to use given llm and embed models rather than force it to recreate these objects. WDYT?

### Version

0.8.5.post2

### Steps to Reproduce

```python
llm = AzureOpenAI(engine="query-engine-model",
                  mode="gpt-35-turbo",
                  temperature=0.0,
                  embedding_llm=embedding_llm,
                  api_key=get_openai_api_key(),
                  api_base=openai.api_base,
                  api_type=openai.api_type,
                  api_version="2023-03-15-preview")

node_parser = UnstructuredElementNodeParser(llm=llm)
raw_nodes = node_parser.get_nodes_from_documents([Document(text=str(pf.getvalue()), metadata={
    "filename": pf.name,
    "extension": pf.type
}) for pf in pdf_files])
base_nodes, node_mappings = node_parser.get_base_nodes_and_mappings(raw_nodes)
```

### Relevant Logs/Tracbacks

```shell
File "/Users/user/my_project/my_script.py", line 54, in with_unstructured
    raw_nodes = node_parser.get_nodes_from_documents([Document(text=str(pf.getvalue()), metadata={
File "/Users/user/Library/Caches/pypoetry/virtualenvs/my-venv/lib/python3.11/site-packages/llama_index/node_parser/unstructured_element.py", line 290, in get_nodes_from_documents
    nodes = self.get_nodes_from_node(document)
File "/Users/user/Library/Caches/pypoetry/virtualenvs/my-venv/lib/python3.11/site-packages/llama_index/node_parser/unstructured_element.py", line 264, in get_nodes_from_node
    extract_table_summaries(table_elements, self.llm, self.summary_query_str)
File "/Users/user/Library/Caches/pypoetry/virtualenvs/my-venv/lib/python3.11/site-packages/llama_index/node_parser/unstructured_element.py", line 113, in extract_table_summaries
    service_context = ServiceContext.from_defaults(llm=llm)
File "/Users/user/Library/Caches/pypoetry/virtualenvs/my-venv/lib/python3.11/site-packages/llama_index/indices/service_context.py", line 163, in from_defaults
    embed_model = resolve_embed_model(embed_model)
File "/Users/user/Library/Caches/pypoetry/virtualenvs/my-venv/lib/python3.11/site-packages/llama_index/embeddings/utils.py", line 43, in resolve_embed_model
```

**Comment by Disiok** [comment]
Thanks for raising this issue @moshewe . This is indeed quite unexpected. 

I think the best solution is to set the service context globally to disable openai related config. See how to do this: https://docs.llamaindex.ai/en/stable/module_guides/supporting_modules/service_context.html#setting-global-configuration

Once you've done that, the local config will default to the global config, which should use the correct embedding model.

**Comment by moshewe** [comment]
I'll try your solution, sounds like it should work.

I still think the parser should accept a service context as a parameter or all possible inputs to the service context to allow maximum flexibility. Deferring to the global service context is not a solution to all cases.

**Comment by moshewe** [comment]
Setting the global service context didn't work. `unstructured_element:110(extract_table_summaries)` will still try to create a new `OpenAI` before getting to the service context handling (where the global default kicks in). Maybe initializing the parser's `ServiceContext` can more easily be done at construction time and then passed to the various functions it uses?

Would you like me to create a PR for the `UnstructuredElementNodeParser` to accept a `service_context` and/or `ServiceContext` parameters in its constructor?

**Comment by gameveloster** [comment]
Any updates on this issue? I am also encountering this.
