### ISSUE TITLE
[Question]: How to use sagemaker endpoint in service_context 

### ISSUE THREAD

**Issue by jc1518** [run-llama/llama_index#8542]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello, I am trying to use sagemaker endpoint (for both llm and embedding) in service_context, but no luck so far. Here is my code, any ideas what I missed?

```python
"""SageMaker Service Context"""
import json

import boto3
from langchain.llms.sagemaker_endpoint import SagemakerEndpoint, LLMContentHandler
from langchain.embeddings import SagemakerEndpointEmbeddings
from langchain.embeddings.sagemaker_endpoint import EmbeddingsContentHandler
from llama_index import LLMPredictor, ServiceContext, VectorStoreIndex
from llama_index.callbacks import CallbackManager, LlamaDebugHandler
from llama_hub.web.simple_web.base import SimpleWebPageReader


class ContentHandler(LLMContentHandler):
    """Text model content handler"""

    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt, model_kwargs):
        input_str = json.dumps({"inputs": prompt, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output):
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json[0]["generated_text"]


class EmbedContentHandler(EmbeddingsContentHandler):
    """Embedding model content handler"""

    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt, model_kwargs):
        input_str = json.dumps({prompt: prompt, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output):
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json["vectors"]


sagemaker_text_endpoint = "jumpstart-dft-hf-llm-mistral-7b-instruct"
sagemaker_embed_endpoint = "jumpstart-dft-hf-textembedding-gpt-j-6b-fp16"

session = boto3.Session()
boto3_sagemaker = session.client(service_name="sagemaker-runtime")

llm = SagemakerEndpoint(
    client=boto3_sagemaker,
    endpoint_name=sagemaker_text_endpoint,
    content_handler=ContentHandler(),
    verbose=True,
)

embedding = SagemakerEndpointEmbeddings(
    client=boto3_sagemaker,
    endpoint_name=sagemaker_embed_endpoint,
    content_handler=EmbedContentHandler(),
)

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

service_context = ServiceContext.from_defaults(
    llm_predictor=LLMPredictor(llm),
    embed_model=embedding,
    callback_manager=callback_manager,
)

reader = SimpleWebPageReader(html_to_text=True)
docs = reader.load_data(
    urls=["https://blog.llamaindex.ai/llamaindex-update-2023-10-10-3718a3d19fb9"]
)

index = VectorStoreIndex.from_documents(
    docs, service_context=service_context, show_progress=True
)
query_engine = index.as_query_engine()
print(query_engine.query("What are the updates?"))

```

**Comment by Farhad-at** [comment]
> Hello, I am trying to use sagemaker endpoint (for both llm and embedding) in service_context, but no luck so far. Here is my code, any ideas what I missed?
> 
> ```python
> """SageMaker Service Context"""
> import json
> 
> import boto3
> from langchain.llms.sagemaker_endpoint import SagemakerEndpoint, LLMContentHandler
> from langchain.embeddings import SagemakerEndpointEmbeddings
> from langchain.embeddings.sagemaker_endpoint import EmbeddingsContentHandler
> from llama_index import LLMPredictor, ServiceContext, VectorStoreIndex
> from llama_index.callbacks import CallbackManager, LlamaDebugHandler
> from llama_hub.web.simple_web.base import SimpleWebPageReader
> 
> 
> class ContentHandler(LLMContentHandler):
>     """Text model content handler"""
> 
>     content_type = "application/json"
>     accepts = "application/json"
> 
>     def transform_input(self, prompt, model_kwargs):
>         input_str = json.dumps({"inputs": prompt, **model_kwargs})
>         return input_str.encode("utf-8")
> 
>     def transform_output(self, output):
>         response_json = json.loads(output.read().decode("utf-8"))
>         return response_json[0]["generated_text"]
> 
> 
> class EmbedContentHandler(EmbeddingsContentHandler):
>     """Embedding model content handler"""
> 
>     content_type = "application/json"
>     accepts = "application/json"
> 
>     def transform_input(self, prompt, model_kwargs):
>         input_str = json.dumps({prompt: prompt, **model_kwargs})
>         return input_str.encode("utf-8")
> 
>     def transform_output(self, output):
>         response_json = json.loads(output.read().decode("utf-8"))
>         return response_json["vectors"]
> 
> 
> sagemaker_text_endpoint = "jumpstart-dft-hf-llm-mistral-7b-instruct"
> sagemaker_embed_endpoint = "jumpstart-dft-hf-textembedding-gpt-j-6b-fp16"
> 
> session = boto3.Session()
> boto3_sagemaker = session.client(service_name="sagemaker-runtime")
> 
> llm = SagemakerEndpoint(
>     client=boto3_sagemaker,
>     endpoint_name=sagemaker_text_endpoint,
>     content_handler=ContentHandler(),
>     verbose=True,
> )
> 
> embedding = SagemakerEndpointEmbeddings(
>     client=boto3_sagemaker,
>     endpoint_name=sagemaker_embed_endpoint,
>     content_handler=EmbedContentHandler(),
> )
> 
> llama_debug = LlamaDebugHandler(print_trace_on_end=True)
> callback_manager = CallbackManager([llama_debug])
> 
> service_context = ServiceContext.from_defaults(
>     llm_predictor=LLMPredictor(llm),
>     embed_model=embedding,
>     callback_manager=callback_manager,
> )
> 
> reader = SimpleWebPageReader(html_to_text=True)
> docs = reader.load_data(
>     urls=["https://blog.llamaindex.ai/llamaindex-update-2023-10-10-3718a3d19fb9"]
> )
> 
> index = VectorStoreIndex.from_documents(
>     docs, service_context=service_context, show_progress=True
> )
> query_engine = index.as_query_engine()
> print(query_engine.query("What are the updates?"))
> ```

It appears that your code is intended to use SageMaker endpoints for language model (LLM) and embedding tasks within a larger application context. The provided code looks mostly correct, but there are a few potential issues and improvements to consider:

Verify SageMaker Endpoints: Make sure that the SageMaker endpoints, sagemaker_text_endpoint and sagemaker_embed_endpoint, are active and correctly configured. Ensure that the model endpoints exist and are accessible from your AWS account.

Check IAM Permissions: Verify that your AWS IAM (Identity and Access Management) role associated with your SageMaker execution environment has the necessary permissions to invoke SageMaker endpoints. It should have permissions to the sagemaker:InvokeEndpoint action.

Content Handler Improvements: The transform_input and transform_output methods in your ContentHandler and EmbedContentHandler classes should be implemented correctly based on the expected input and output formats of your SageMaker models. Ensure that the transformation logic is accurate.

Error Handling: Your code currently doesn't include error handling or exception handling for issues that might occur when calling SageMaker endpoints. You should add error handling to gracefully handle potential issues, such as network errors or endpoint availability.

Verbose Output: You've set verbose=True for your SageMaker endpoints. While this can be useful for debugging, you may want to adjust the level of verbosity based on your needs and the production environment.

Endpoint Naming: Confirm that the endpoint names, such as sagemaker_text_endpoint and sagemaker_embed_endpoint, are correctly defined and match the actual SageMaker endpoint names you intend to use.

Web Page Reading: The code also seems to be loading and processing web page content. Ensure that this part of the code is functioning as expected and that the docs variable contains the expected data.

Llama Index Configuration: The code related to the Llama Index and query engine appears to be set up correctly, but make sure it aligns with your specific use case and requirements.

**Comment by jc1518** [comment]
I have figured it out, the issue was cause by the changes have been made to inference.py. Following are the working version.

```python
"""SageMaker Service Context"""
import json

import boto3
from langchain.llms.sagemaker_endpoint import SagemakerEndpoint, LLMContentHandler
from langchain.embeddings import SagemakerEndpointEmbeddings
from langchain.embeddings.sagemaker_endpoint import EmbeddingsContentHandler
from llama_index import LLMPredictor, ServiceContext, VectorStoreIndex
from llama_index.callbacks import CallbackManager, LlamaDebugHandler
from llama_hub.web.simple_web.base import SimpleWebPageReader


class ContentHandler(LLMContentHandler):
    """Text model content handler"""

    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt, model_kwargs):
        input_str = json.dumps({"inputs": prompt, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output):
        response_json = json.loads(output.read().decode("utf-8"))
        return response_json[0]["generated_text"]


class EmbedContentHandler(EmbeddingsContentHandler):
    """Embedding model content handler"""

    content_type = "application/json"
    accepts = "application/json"

    def transform_input(self, prompt, model_kwargs):
        input_str = json.dumps({"text_inputs": prompt, **model_kwargs})
        return input_str.encode("utf-8")

    def transform_output(self, output):
        # print(output)
        response_json = json.loads(output.read().decode("utf-8"))
        # print(response_json)
        return response_json["embedding"]


sagemaker_text_endpoint = "jumpstart-dft-hf-llm-mistral-7b-instruct"
sagemaker_embed_endpoint = "jumpstart-dft-hf-textembedding-gpt-j-6b-fp16"

session = boto3.Session()
boto3_sagemaker = session.client(service_name="sagemaker-runtime")

llm = SagemakerEndpoint(
    client=boto3_sagemaker,
    endpoint_name=sagemaker_text_endpoint,
    content_handler=ContentHandler(),
    verbose=True,
)

# Test llm
# print(llm.predict("hello!"))

embedding = SagemakerEndpointEmbeddings(
    client=boto3_sagemaker,
    endpoint_name=sagemaker_embed_endpoint,
    content_handler=EmbedContentHandler(),
)

# Test embedding
# print(embedding.embed_query("hello!"))


llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

service_context = ServiceContext.from_defaults(
    llm_predictor=LLMPredictor(llm),
    embed_model=embedding,
    callback_manager=callback_manager,
)

reader = SimpleWebPageReader(html_to_text=True)
docs = reader.load_data(
    urls=["https://blog.llamaindex.ai/llamaindex-update-2023-10-10-3718a3d19fb9"]
)

index = VectorStoreIndex.from_documents(
    docs, service_context=service_context, show_progress=True
)
query_engine = index.as_query_engine()
print(query_engine.query("What are the updates?"))

```
