### ISSUE TITLE
[Feature Request]: Pass Metadata Filters to the Auto Retriever to append to the filter list

### ISSUE THREAD

**Issue by cwysong85** [run-llama/llama_index#8543]
### Feature Description

Add `append_filters` to `VectorIndexAutoRetriever` class to always append said filters even if the LLM comes back with filters.

### Reason

Currently, the auto retriever does a great job in extracting what filters need to be dynamically added to a retriever. However, if I have a set of `ExactMatch` filters that I want to use always, that functionality isn't available today. Currently, I'm able to "trick" the LLM into doing this by appending the filters I want to use to the end of the input message:

`Give me a summary of this document. Filter by documentId: {documentId}`

This works! However, the LLM now outputs the filter back to me in the final response even though the default prompt states to not do this. `... Any conditions in the filter should not be mentioned in the query as well.`

### Value of Feature

Allows more control and granularity for developers to filter.

**Comment by cwysong85** [comment]
A possible hack could also be to take the default template and pass those filters there but I think an overall solution would be to append filters.

**Comment by logan-markewich** [comment]
@cwysong85 this is actually already possible `VectorIndexAutoRetriever(... extra_filters=filters)`
