### ISSUE TITLE
[Bug]: Cannot query more than 10 documents at a time.

### ISSUE THREAD

**Issue by Ayfri** [run-llama/llama_index#8553]
### Bug Description

Hello, I'm trying to create a query from a `VectorStoreIndex` with more than 10 of `similarity_top_k`, but it always result in a response having `response.source_nodes` being equal to 10.
I need to query a large quantity of documents where information can be parsed among a lot of them so this is crucial to my project, I'm required to create multiple sub prompts to gather all the information I need for a final prompt. Using one prompt with a very high top_k would help avoid doing this.
So, what am I doing wrong ?

### Version

0.8.22 (slowly updating to more recent versions)

### Steps to Reproduce

1. Create a new VectorStoreIndex.
2. Create a BaseQueryEngine from the index with a `similarity_top_k` of for example 20.
3. Query the engine with a prompt.
4. Log `len(response.source_nodes)`.
5. See that it was "reverted" to 10.

**Comment by Ayfri** [comment]
@dosu-bot From what I've seen the `VectorIndexAutoRetriever` class is only used for `SQLAutoVectorQueryEngine`, so this can't be the source of my issue.
Tell me if I'm wrong.

**Comment by Ayfri** [comment]
@dosu-bot After more search, I found where the 10 is coming from, it's from Redis itself, as I'm using a `RedisVectorStore`.
In the `ft(index).search(...)` function, there is a limit of `10` by default, defined by a field named `_num` in the `Query` object.
But there's currently no way to change this number, as the query is happening entirely inside `llama_index` code and there's no `**kwargs` or similar things.
So I guess this requires an update from `llama_index` itself to fix this behavior. @jerryjliu

**Comment by Disiok** [comment]
Hey @Ayfri, could you post a snippet on how to reproduce this?

**Comment by Ayfri** [comment]
```py
import openai
from llama_index import Document, StorageContext, VectorStoreIndex
from llama_index.vector_stores import RedisVectorStore

from environment import OPENAI_API_KEY, REDIS_HOST, REDIS_PORT # variables to define


def main() -> None:
	openai.api_key = OPENAI_API_KEY

	vector_store = RedisVectorStore(
		index_name="test",
		redis_url=f"redis://{REDIS_HOST}:{REDIS_PORT}",
	)

	storage_context = StorageContext.from_defaults(
		vector_store=vector_store
	)

	index = VectorStoreIndex.from_documents(
		[
			Document(text=f"Test document {i}") for i in range(1000)
		],
		storage_context=storage_context,
	)

	engine = index.as_query_engine(similarity_top_k=20)

	response = engine.query("Test document 1")
	print(f"{len(response.source_nodes) = }") # Should be 20 but prints 10
	print(response.response)


if __name__ == '__main__':
	main()
```
Here is a simple script for reproducing this bug.
