### ISSUE TITLE
[Question]: How to retrieve full content of document in case it is chunked into multiple nodes.

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#8569]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Suppose my document content exceeds the 512 chunk length and it is divided into 3 sub chunks. Now while retrieval if one particular leaf chunk is retrieved in top k for a input query but i want to get the entire content of the actual parent/root node (sub chunk1+subchunk2 +subchunk3). How to get that?
The reason is i dont want to break my passage and pass as input rather i want to have entire actual document content as input even if part of it is retrieved as top k. Kindly help.

**Comment by amitguptadumka** [comment]
@dosu-bot
Thanks for the information. To use this function what all are pre-requisite. Say i have built an index and stored it in Elastic search and  using the same for retrieval. Do i need to create a docstore and pass it in index similar to service context while building the index. Can you give me complete picture/sample code of it before using this function what all needs to be done while creating index?My code for creating index and storing goes below:
vector_store = ElasticsearchStore(
    es_url="https:"
    es_api_key='==',
    es_user="",
    es_password="123",
    index_name="index_name")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
service_context = ServiceContext.from_defaults(llm_predictor=llm,embed_model=embed_model)
index = VectorStoreIndex.from_documents(documents, service_context=service_context,storage_context=storage_context)

Also post index creation say while retrieving top k i am getting the details as below from retriever, what details with reference to this i have to pass in above function retrieve_full_document() so as to get entire document content?

Example top k output:

NodeWithScore(node=TextNode(id_='1fb22f76-0620-4351-944e-ec8eab8c8a64', embedding=None, metadata={}, excluded_embed_metadata_keys=[], excluded_llm_metadata_keys=[], relationships={<NodeRelationship.SOURCE: '1'>: RelatedNodeInfo(node_id='bfdb6ed6-f411-4f20-9fcc-ada6538a3920', node_type=None, metadata={}, hash='bb3bb8f48548ea53692aad238040733568567d6e6cf114d9b6803aafd9f98f61'), <NodeRelationship.PREVIOUS: '2'>: RelatedNodeInfo(node_id='41461ef7-d1e6-4711-9c02-876499d2c786', node_type=None, metadata={}, hash='43e082d0fb6428993ef7f5af49c4e46c8088db2dafb50e2b9c11158ebf5dec33'), <NodeRelationship.NEXT: '3'>: RelatedNodeInfo(node_id='daff6a89-73f8-4f8e-a28a-46ef0932a43e', node_type=None, metadata={}, hash='a5690ed63e8a68b662231584b5276149470f6dbcf72af37cf4bfce0437a157d7')}, hash='e327609c2f7cc1cf6affca397bfb864cd6f156718d9160d91cfe3a00e4045acd', text='sample sub chunk goes here.........', start_char_idx=None, end_char_idx=None, text_template='{metadata_str}\n\n{content}', metadata_template='{key}: {value}', metadata_seperator='\n'), score=1.2470622)

With reference to this please explain how to retrieve full content of this sub chunk?

**Comment by amitguptadumka** [comment]
@Disiok 
Can you please help here?

**Comment by amitguptadumka** [comment]
@nerdai Tagging for some help here please.

**Comment by nerdai** [comment]
Hi @amitguptadumka, in general you can trace the source of every `BaseNode` type. So for the node (chunk) that get's retrieved, you can call `node.source_node.node_id`.

```py
from llama_index.readers.file import SimpleDirectoryReader
from llama_index import VectorStoreIndex

documents = SimpleDirectoryReader(...)
index = VectorStoreIndex.from_documents(documents=documents)

...
node = ... # retrieve nodes from a query
doc_id = node.source_node.node_id
```
Then you can search for the `d` in `documents` that has that same id as `doc_id`. I.e., `d.node_id == doc_id`, then `d` is your document.

**Comment by amitguptadumka** [comment]
> Hi @amitguptadumka, in general you can trace the source of every `BaseNode` type. So for the node (chunk) that get's retrieved, you can call `node.source_node.node_id`.
> 
> ```python
> from llama_index.readers.file import SimpleDirectoryReader
> from llama_index import VectorStoreIndex
> 
> documents = SimpleDirectoryReader(...)
> index = VectorStoreIndex.from_documents(documents=documents)
> 
> ...
> node = ... # retrieve nodes from a query
> doc_id = node.source_node.node_id
> ```
> 
> Then you can search for the `d` in `documents` that has that same id as `doc_id`. I.e., `d.node_id == doc_id`, then `d` is your document.

This worked for me: source_node = node.node.source_node.node_id
