### ISSUE TITLE
[Documentation]: broken links (404)

### ISSUE THREAD

**Issue by ronaldpetty** [run-llama/llama_index#8595]
### Documentation Issue Description

From https://docs.llamaindex.ai/en/stable/, these do not seem to work:

* "how to read these docs" - https://docs.llamaindex.ai/getting_started/reading.html
* The "edit" button - https://github.com/run-llama/llama_index/edit/031b3518f3f89c5bd2837ecea77028758358536d/docs/index.rst

Took a swing to edit on fork, but I didn't RST renderer at hand. Compared to other links, it seems to be missing the branch "en/stable".

### Documentation Link

https://docs.llamaindex.ai/en/stable/

**Comment by Disiok** [comment]
The `how to read the docs` link seems to be working for me. But yes the edit button is definitely broken. Thanks so much for pointing these out. Going to fix this soon!

**Comment by ronaldpetty** [comment]
Interesting, wonder how its working for you.  Just to make sure are on the same link, its the bottom right here (not left nav -- which does work).

<img width="810" alt="image" src="https://github.com/run-llama/llama_index/assets/1390435/da5a86d6-81c0-44d6-b9fa-ed9ce8f50d3c">

<img width="719" alt="image" src="https://github.com/run-llama/llama_index/assets/1390435/4b514fd0-eed2-4ce5-bba0-26df1c9122b1">

**Comment by logan-markewich** [comment]
The `how to read the docs` link was actually also broken for me, but I just [merged a PR](https://github.com/run-llama/llama_index/pull/8697) that fixes it and a few other links (they have to be relative links in rst files I guess)

**Comment by logan-markewich** [comment]
The edit button seems to only work for maintainers of the main repo. Not sure how to go about fixing that 🤔
