### ISSUE TITLE
[Question]: Is it possible to have the agent not interpret FUNCTION tool output?

### ISSUE THREAD

**Issue by ElioErrico** [run-llama/llama_index#8604]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello everybody,
thank you again for your support.

My question is:
if I write a function tool were the output is a string, here an example:
```

def temperature_management(season: str=None, 
                           new_air_temperature: float=None,
                           incoming_air_temperature: float=None,
                           extracted_air_temperature: float=None,
                           expelled_air_temperature: float=None) -> str:
    
    """
    This tool should be used when the user asks a question related to the four temperatures,
    it evaluates temperatures based on seasonality and the provided temperature values.
    The user will provide either 'winter' or 'summer' seasonality, 
    the new air temperature, the expelled air temperature, the extracted air temperature, and the expelled air temperature.

    Args:
        season: "winter" or "summer"
        new_air_temperature: New air temperature
        incoming_air_temperature: Incoming air temperature
        extracted_air_temperature: Extracted air temperature
        expelled_air_temperature: Expelled air temperature
    """

    code
    ... the output of this code is a string containg informations of what the user have to do ...
    return " you have to do this and this"

temperature_management_tool = FunctionTool.from_defaults(fn=temperature_management)

```

Is it possible to have the agent to not interpret this answer but just to copy the output without adding personal interpretation?

**Comment by ElioErrico** [comment]
I tryied to study the answer but I'm not able to understand how to use the `.call `method in order to have a function that returns a string without interpretation in `agent.chat`.

With this tool:

`temperature_management_tool = FunctionTool.from_defaults(fn=temperature_management)`

My goal is to call `temperature_management_tool `  in:

```
llm = OpenAI(model="gpt-3.5-turbo-0613",temperature=0)
agent = OpenAIAgent.from_tools(
    temperature_management_tool, llm=llm, verbose=True,
    system_prompt=custom_system_prompt
)
```

than when I chat with the agent I would like to get an answer without interpretation.

`response=agent.chat("can you evaluate temperatures with this inputs ...?") `
`response=" string output of the tool without interpretation"`

let me know.
thanks again
Elio

**Comment by tagamma** [comment]
I'm also very interested in this.

Based on the implementation of BaseOpenAgent, it seems that this is not possible right now. But I'd appreciate someone more familiar with the codebase to confirm.
