### ISSUE TITLE
[Bug]: Multi-Document Agents throws InvalidRequestError: Unrecognized request argument supplied: functions

### ISSUE THREAD

**Issue by akshaydigheQ** [run-llama/llama_index#8607]
### Bug Description

Multi-Documents agent example in llamaindex documentation(https://docs.llamaindex.ai/en/latest/examples/agent/multi_document_agents-v1.html) gives "Unrecognized request argument supplied: functions" error.
Tried different versions of llamaindex from 0.8.48 to latest ones.
Initially it gave me error that engine or deployment_id is required. I resolved this error by making change in source code. That is by adding engine as argument in openai/api_resources/chat_completion.py. After this change i get above mentioned error when i execute "top_agent.query()"

### Version

0.8.56

### Steps to Reproduce

https://docs.llamaindex.ai/en/latest/examples/agent/multi_document_agents-v1.html

Getting error while executing top_agent.query()

**Comment by Disiok** [comment]
Are you using Azure OpenAI? what API version are you using? It looks like you might be using an old version that doesn't have function calling support.

**Comment by akshaydigheQ** [comment]
> Are you using Azure OpenAI? what API version are you using? It looks like you might be using an old version that doesn't have function calling support.

I am using Azure OpenAI with model gpt-35-turbo 0301 and api version 2023-08-01-preview

**Comment by akshaydigheQ** [comment]
> > Are you using Azure OpenAI? what API version are you using? It looks like you might be using an old version that doesn't have function calling support.
> 
> I am using Azure OpenAI with model gpt-35-turbo 0301 and api version 2023-08-01-preview

Changing model version from gpt-35-turbo 0301 to gpt-35-turbo 0613 helped to resolve Unrecognizeed request argument issue
