### ISSUE TITLE
[Bug]:  not able to install llama_index libraries on aws lambda and getting timeout error 

### ISSUE THREAD

**Issue by akashkumar398** [run-llama/llama_index#8611]
### Bug Description

when creating aws lambda using llama_index getting a timeout error

### Version

llama_index: 0.8.52

### Steps to Reproduce

from llama_index import ServiceContext, SQLDatabase
from llama_index.llms import OpenAI
from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine

tried importing these modules of llama_index resulting in timeout error

**Comment by nerdai** [comment]
I just ran install `llama-index==0.8.52` on a fresh python 3.10 venv and didn't have any issues with your listed import statements.

**Comment by akashkumar398** [comment]
my AWS lambda is of 128 MB

**Comment by nerdai** [comment]
@akashkumar398 have you tried increasing the timeout from the default 3 secs (see [here](https://docs.aws.amazon.com/lambda/latest/operatorguide/configurations.html#timeouts))? Perhaps that might work for you.

Not to sure of your specific use-case here, but maybe [this](https://repost.aws/knowledge-center/lambda-import-module-error-python) would be useful if increasing timeout doesn't fix your issue.

**Comment by akashkumar398** [comment]
I tried increasing the lambda size from 128 MB to
