### ISSUE TITLE
[Documentation]: Broken links in nearly all "getting started" docs

### ISSUE THREAD

**Issue by ifrit98** [run-llama/llama_index#8624]
### Documentation Issue Description

https://github.com/run-llama/llama_index/blob/main/docs/getting_started/concepts.md

All of these links contained in this document give 404.

When I try to manually parse through the repo to find where they have been moved, (e.g. chatbots)
https://github.com/run-llama/llama_index/blob/main/docs/use_cases/chatbots.md

The links here also give 404.

Please have someone go through and update the user documentation so those who want to get up to speed quickly can do so.

Best,
Phil

### Documentation Link

https://github.com/run-llama/llama_index/blob/main/docs/getting_started/concepts.md

**Comment by nerdai** [comment]
Thanks for raising @ifrit98!

**Comment by Disiok** [comment]
The links should work on the compiled version of the docs at https://docs.llamaindex.ai/en/stable/getting_started/concepts.html
