### ISSUE TITLE
[Question]: is there a way to reduce the time to rebuild storage context 

### ISSUE THREAD

**Issue by antoan** [run-llama/llama_index#8629]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I build the storage context the following way:

`storage_context = StorageContext.from_defaults(persist_dir="./storage")`

I noticed the code ends up spends a lot of time [here](https://github.com/run-llama/llama_index/blob/f780e6272fb9ad75c294ba0cee074d38853bf7e5/llama_index/vector_stores/simple.py#L269)

Would switching to another vector store help. 
Contents of storage  [storage.zip](https://github.com/run-llama/llama_index/files/13231589/storage.zip)

Any thoughts would be much appreciated.

**Comment by Disiok** [comment]
hey @antoan, are you indexing a large number of documents? If so, we'd recommend using a dedicated vectorDB for it.
