### ISSUE TITLE
[Bug]: While using hybrid retriever with Elastic Search not able to retrieve for top_k>10

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#8635]
### Bug Description

I have my embeddings stored in ELastic search and i am using hybrid retriever to retrieve top_k docs based on hybrid similarity using below command:
retriever = VectorIndexRetriever(index=index,vector_store_query_mode="hybrid" ,similarity_top_k=15) 

Now , its working fine if similarity_top_k<=10 but as soon as i try to retrieve more than 10 nodes it gives below error:

BadRequestError: BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: [rank] requires [window_size: 10] be greater than or equal to [size: 15];')

Can someone help me how to retrieve >10 chunks since i have to do reranking on top of this.
Thanks. 

### Version

0.8.48

### Steps to Reproduce

retriever = VectorIndexRetriever(index=index,vector_store_query_mode="hybrid" ,similarity_top_k=15) 
retriever.retrieve(query_bundle)

### Relevant Logs/Tracbacks

```shell
BadRequestError: BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: [rank] requires [window_size: 10] be greater than or equal to [size: 15];')
```

**Comment by Disiok** [comment]
Hmm, took a quick look. I don't think the dosu bot is right here. The elasticsearch limit could be much higher at 10,000: https://www.alibabacloud.com/help/en/es/use-cases/use-the-knn-search-feature-of-elasticsearch

**Comment by amitguptadumka** [comment]
> Hmm, took a quick look. I don't think the dosu bot is right here. The elasticsearch limit could be much higher at 10,000: https://www.alibabacloud.com/help/en/es/use-cases/use-the-knn-search-feature-of-elasticsearch.

@Disiok Thanks for reply but how to fix my actual issue which is, if i put similarity_top_k >10 it throws error. I need to fetch atleast 20 docs for hybrid retrieval. Any help would be appreciated. Thanks.
