### ISSUE TITLE
[Bug]: AzureOpenAI : Sub Question Query Engine is not working

### ISSUE THREAD

**Issue by vipinap98** [run-llama/llama_index#8641]
### Bug Description

Was trying to do the Subquestion query engine
Got this error

InvalidRequestError: Unrecognized request argument supplied: functions

is it an issue from the Azure Openai itself? because the deployment is gpt-35-turbo-0301 not the 0613 model

### Version

0.8.57

### Steps to Reproduce

Follow the subquestion query engine with azure openai service
ps:it works with openai service

**Comment by logan-markewich** [comment]
@vipinap98 you need to make sure you use the latest version of OPENAI_API_VERSION, I think the august preview added support for function calling
