### ISSUE TITLE
[Question]: Retrieval with LlamaIndex

### ISSUE THREAD

**Issue by 4entertainment** [run-llama/llama_index#8661]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi. I want to read data. And answer my questions about data with retrieval architecture. I want to do this with llama-index techs.
Within the scope of this task:

--- Any model should not be used. 
--- Only vector store and retrieval mechanisms should be used.

Can you give me code for this task?

**Comment by logan-markewich** [comment]
@4entertainment you need a model to embed data. In any case, you could do something like

```python
from llama_index import SimpleDirectoryReader, VectorStoreIndex, ServiceContext

documents = SimpleDirectoryReader("./data").load_data()

service_context = ServiceContext.from_defaults(llm=None, embed_model="local:BAAI/bge-base-en-v1.5")

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

retriever = index.as_retriever(similarity_top_k=2)

nodes = retriever.retrieve("cats")
```

**Comment by 4entertainment** [comment]
@logan-markewich thank you so much for your reply. Is there any way I can do this without using a model?

**Comment by logan-markewich** [comment]
@4entertainment if you are using embeddings, you need a model or API to generate embeddings, there's no way around that.

You could look into using bm25 instead. But that's more of a keyword search

**Comment by 4entertainment** [comment]
So what if I don't prefer to use embeddings:
Can I develop an application with a retrieval mechanism where I give my document and question with llama-index without using models? This is my task. Or what can I do regarding this task?

**Comment by logan-markewich** [comment]
@4entertainment bm25 is what you want, it's not really a model and lightweight
