### ISSUE TITLE
[Question]: Download and Setup

### ISSUE THREAD

**Issue by 4entertainment** [run-llama/llama_index#8662]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi! Please help me about my following problem.

I want to download and setup llama_index to my personal computer locally. Then i should run a simple task with llama-index. My computer is ready. Can you please write in detail step by step what I should do?

**Comment by logan-markewich** [comment]
@4entertainment please refer to our docs! They offer a pretty good guide/introduction. https://docs.llamaindex.ai/en/stable/getting_started/installation.html
