### ISSUE TITLE
[Documentation]: Zephyr-7b-beta seems tested on 4-bit where there is 5-bit version possible

### ISSUE THREAD

**Issue by gorkemgoknar** [run-llama/llama_index#8664]
### Documentation Issue Description

Found post on linkedin about evalution about Zephyr-7b-beta.
https://docs.llamaindex.ai/en/latest/module_guides/models/llms.html#open-source-llms

I saw that 4 bit quantization was used , and given I know there are 5 bit quantized version there (which we use on https://huggingface.co/spaces/coqui/voice-chat-with-zephyr  already, ) so I tested LlamaIndex Zephyr colab with 5-bit GGUF version.

Here is result notebook , hoping someone will validate results, as I am not sure when you set a test pass or fail

https://colab.research.google.com/drive/1ULelRgpKbCNIJwdP1vBvZtA7yTTHRwzK?usp=sharing

**Quick edit here in case notebook fails to load:**

GGUF version can be run on CUDA with following (zephyr-beta 5bit uses ~8Gb memory total), everything else on test same just llm replaced. Note that sometimes there are json parser errors and rarely produced prompt passes 3600 tokens , but I does rerun and pass.
Note that I did not change prompt, that is why there may be new lines on Q/A , but I guess we are checking final response only.
```

# need to install llama-cpp-python with cublas to make affective GPU usage
#!CMAKE_ARGS="-DLLAMA_CUBLAS=on" pip install llama-cpp-python

from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import completion_to_prompt


llm = LlamaCPP(
    model_url="https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q5_K_M.gguf",
    
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    # first download will download into /tmp/llama_index/models/zephyr-7b-beta.Q5_K_M.gguf on colab
    model_path=None,
    
    temperature = 0.7, # set same as on original test
    
    max_new_tokens=256, # set same as on original test
    
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=3900,  # note, this sets n_ctx in the model_kwargs below, so you don't need to pass it there.
    
    # kwargs to pass to __call__()
    generate_kwargs={"top_k":50, "top_p" : 0.95}, # set same as on original test
     
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU  (depends on model for LLama base usually 35 total)
    model_kwargs={"n_gpu_layers": 35}, # 35 is full GPU, set 10-15 if you have lower VRAM , make sure llama_cpp compiled with cublas for better GPU speed
    
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt, # this is overriden above
    #completion_to_prompt=completion_to_prompt, # imported via llama_utils
    verbose=True, # must be set True to use on llama_index
)
```

### Documentation Link

https://docs.llamaindex.ai/en/latest/module_guides/models/llms.html#open-source-llms

**Comment by logan-markewich** [comment]
@gorkemgoknar thanks for contributing this notebook! Feel free to make a PR to add it to our docs :) 

I would edit some of the text to make it more correct (i.e. you are using a 5bit model with llama.cpp)

In terms of passing, it seems like all seem to work initially!
