### ISSUE TITLE
[Question]: generate related questions from the context in the generated response

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#8678]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

query_str = "here is the question?"
response = query_engine.query(query_str)
print(str(response))

How do I make use of the response or response metadata that is provided above and get N 'related questions' based on the response context, are there any inbuilt methods? This question generation should not search the vector store.

**Comment by logan-markewich** [comment]
@ram510 there's no built in method, but here's a quick and easy way that I would use.

```python
from llama_index import Document, SummaryIndex

response = query_engine.query("query")

sources = []
for node in response.source_nodes:
  sources.append(Document(text=node.text))

summary_index = SummaryIndex.from_documents(sources)
questions = summary_index.as_query_engine(response_mode="tree_summarize").query("Write a list of 5 related questions this text could answer.")
```
