### ISSUE TITLE
[Question]:  Query against structured data in datastore and Redis

### ISSUE THREAD

**Issue by tytung2020** [run-llama/llama_index#8688]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

My database are in both sql and nosql databases (cloud datastore, Redis). Currently llamaindex can perform text to sql query, but how does it has the same functionality to query nosql databases?
I see Redis has been incorporated into llamaindex, but only as a vector database for semantic search. Semantic search is great for long textual articles, but not accurate enough for database queries. So I cannot use this to query Redis databases.

**Comment by logan-markewich** [comment]
Querying nosql would require a PR. But it would be very similar to querying SQL -- give the LLM some info about the fields in the DB, ask it to write a query for a given user message, and optionally get the LLM to interpret that response after executing the query.
