### ISSUE TITLE
[Feature Request]: Support for OpenAI gpt-3.5-turbo-1106 and gpt-4-1106-preview models

### ISSUE THREAD

**Issue by niels-bosman** [run-llama/llama_index#8710]
### Feature Description

As of right now, these new models are not supported because they are not in the list of options for the OpenAI wrapper.

### Reason

These models are the newest and will be very popular.

### Value of Feature

This is going to be the new standards for ChatGPT models.

**Comment by matthiaskern** [comment]
added in #8713

**Comment by logan-markewich** [comment]
This has been added and released on pypi in 0.8.63.post2
