### ISSUE TITLE
[Bug]: download_loader("WikipediaReader") throws InvalidURL

### ISSUE THREAD

**Issue by jayh-aa** [run-llama/llama_index#8720]
### Bug Description

Hi, am trying to make use of WikipediaReader to load data from a Wikipedia article. The following code results in an error:

from llama_index import download_loader
WikipediaReader = download_loader("WikipediaReader")

InvalidURL: Invalid URL 'https:\\raw.githubusercontent.com\\run-llama\\llama-hub\\main\\llama_hub/library.json': No host supplied

### Version

0.8.62

### Steps to Reproduce

from llama_index import download_loader
WikipediaReader = download_loader("WikipediaReader")

**Comment by qxpf666** [comment]
pip install --upgrade llama-index==v0.8.63.post1
The latest version has resolved this issue

**Comment by jayh-aa** [comment]
> pip install --upgrade llama-index==v0.8.63.post1 The latest version has resolved this issue

Thank you, this
