### ISSUE TITLE
[Feature Request]: ObjectIndex save

### ISSUE THREAD

**Issue by nick-youngblut** [run-llama/llama_index#8728]
### Feature Description

Creating an ObjectIndex of 100's of table schema objects (as in the [text-to-sql guide](https://docs.llamaindex.ai/en/stable/examples/index_structs/struct_indices/SQLIndexDemo.html#part-2-query-time-retrieval-of-tables-for-text-to-sql)), the process is quite slow. As far as I can tell, the resulting ObjectIndex object cannot be saved (or simply pickled). It would be helpful to be able to save this object to disk in order to obviate the need to continuously recreate the ObjectIndex object.

### Reason

Creating an ObjectIndex can be very slow for large sql databases with 100's of tables.

### Value of Feature

llama-index's text-to-sql workflow would be more scalable for databases with large schemas.

**Comment by logan-markewich** [comment]
I think saving the underlying index is easy, but saving the node-to-object mapping is a little harder 🤔 Especially since the objects could be anything. Thoughts on this? Just pickle and pray?

**Comment by logan-markewich** [comment]
Yea I meant if we implemented it, undwe the hood pickling the node-to-object mapping maybe 🤔 the underlying index could be saved as usual, but the mapping needs to be handled as well

**Comment by Boxiang7JC** [comment]
I feel you Nick. This is a much needed feature since it seems ObjectIndex is the only viable way to create an index from tables. We definitely need to store the index after building it for hours

**Comment by Boxiang7JC** [comment]
@nick-youngblut I resolved this issue using a dirty way. You can access the index object through the private variable of ObjectIndex and revise its storage context.

# build a save vector store index
obj_index = ObjectIndex.from_objects(
        table_schema_objs,
        table_node_mapping,
        VectorStoreIndex
    )
obj_index._index._storage_context.persist(persist_dir='some place')

# in the future, simply load the vector store index. But when building the ObjectIndex, you need to pass the object_node_mapping. 
storage_context = StorageContext.from_defaults(persist_dir='your place')
index = load_index_from_storage(storage_context)
obj_index = ObjectIndex(index=index, object_node_mapping=table_node_mapping)

**Comment by nick-youngblut** [comment]
@Boxiang7JC thanks for the "dirty" solution! Hopefully, a clean solution can be implemented soon.
