### ISSUE TITLE
[Question]: Retrieval with LlamaIndex 

### ISSUE THREAD

**Issue by 4entertainment** [run-llama/llama_index#8737]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I mentioned that I wanted to do this in the linket issue(https://github.com/run-llama/llama_index/issues/8661  but closed) and @logan-markewich  was very helpful.

Thinking back, I thought I could do it this way:
1) I send my file.
2) In the data ingestion section, I divide it into chunks and save it to a vector db. Here I should try chroma, deeplake, qdrant and see their performance.
3) I perform similarity checks on embeddings consisting of files. I will send the answer to the input given according to the similarity checking results.

I would be very pleased if there is someone who has knowledge about this task that I need to do and can provide code and explanation.

**Comment by logan-markewich** [comment]
@4entertainment the process you described is exactly what a `VectorStoreIndex` does. The bot actually gave a pretty good example.

You can see details for all vector stores here (links at the bottom)
https://docs.llamaindex.ai/en/stable/module_guides/storing/vector_stores.html

**Comment by nerdai** [comment]
Thanks @4entertainment. Based on the responses from both @logan-markewich and dosubot, I'm closing this issue. If you feel it needs to be re-opened please let us know.
