### ISSUE TITLE
[Bug]:  `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. 

### ISSUE THREAD

**Issue by zhongli1990** [run-llama/llama_index#8740]
### Bug Description

Current version 0.8.63-post2 doesn't work with OpenAI 1.1 yet. 

Today morning I happened to restart my dockers, and since I didn't fix any openai and llama_index package version in requirements.txt (bad habit due to multi-tasking too much), it got the following issue:

penai             | =============Building GPTVectorStoreIndex ======
openai             | Traceback (most recent call last):
openai             |   File "/app/app.py", line 148, in <module>
openai             |     llamaindex = load_index() 
openai             |   File "/app/app.py", line 140, in load_index
openai             |     index = load_index_from_storage(storage_context, service_context=create_service_context())
openai             |   File "/app/app.py", line 100, in create_service_context
openai             |     llm_predictor = LLMPredictor(llm=ChatOpenAI(temperature=0.5, model_name="gpt-4", max_tokens=num_outputs)) #gpt-3.5-turbo
openai             |   File "/usr/local/lib/python3.10/site-packages/langchain/load/serializable.py", line 97, in __init__
openai             |     super().__init__(**kwargs)
openai             |   File "/usr/local/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
openai             |     raise validation_error
openai             | pydantic.v1.error_wrappers.ValidationError: 1 validation error for ChatOpenAI
openai             | __root__
openai             |   `openai` has no `ChatCompletion` attribute, this is likely due to an old version of the openai package. Try upgrading it with `pip install --upgrade openai`. (type=value_error)

It's not really a big issue, but since it took me whole morning to realise it might be just due to langchain is not working with openai 1.1 etc by default yet. I simply changed it back to openai==0.86.1, then all restored.  So just a quick note here in case others stumbled on it too.

### Version

 0.8.63-post2

### Steps to Reproduce

don't fix any version in requirements.txt for a python 3.10-slim-buster docker.

**Comment by logan-markewich** [comment]
@zhongli1990 you are using a langchain LLM. I'm not sure if langchain has updated properly to support the latest client, but that's where the error is coming from.

I would advise you to just use a llama-index LLM instead

```python
from llama_index.llms import OpenAI

llm_predictor = LLMPredictor(llm=OpenAI(temperature=0.5, model="gpt-4", max_tokens=num_outputs)) 
```
