### ISSUE TITLE
[Bug]: TokenTextSplitter does not split when using huggingface tokenizer

### ISSUE THREAD

**Issue by manuelrech** [run-llama/llama_index#8741]
### Bug Description

I think this code in `TokenTextSplitter` is built around the tokenizer from tiktoken. Indeed when we call `self.tokenizer(text)` with a tokenizer from tiktoken we get as a result a list of tokens. However, when we use a tokenizer from the `transformers` library (in my case `mistralai/Mistral-7B-Instruct-v0.1`) the output of the `self.tokenizer(text)` is not a the list of tokens but a dictionary with two keys: `input_ids` and `attention_mask`. The `input_ids` contain the list of tokens as if it was generated by `self.tokenizer(text)` with a tiktoken tokenizer.

### Version

 0.8.61

### Steps to Reproduce

from transformers import AutoTokenizer
from llama_index.node_parser import SimpleNodeParser
from llama_index.text_splitter import TokenTextSplitter
tokenizer = AutoTokenizer.from_pretrained("mistralai/Mistral-7B-Instruct-v0.1")
text_splitter = TokenTextSplitter(
  separator=" ",
  chunk_size=300,
  chunk_overlap=5,
  backup_separators=["\n"],
  tokenizer=tokenizer
)
node_parser = SimpleNodeParser.from_defaults(
        text_splitter=text_splitter
        )
base_nodes = node_parser.get_nodes_from_documents(**any list of llama index documents**, show_progress=True)
print(len(**any list of llama index documents**.text))
print('---')
print(len(base_nodes[0].text))

**Comment by manuelrech** [comment]
It's a workaround but this is a bug. That function self.tokenizer(text) is called 5 times and some logic not to have to worry about which tokenizer you choose would be better.

**Comment by logan-markewich** [comment]
@manuelrech  the intention of the `tokenizer` argument is to actually just be any callable that takes string and returns a list.

For huggingface tokenizers, you just need to set `tokenizer=hf_tokenizer.encode`, no need to edit source code
