### ISSUE TITLE
[Question]: How to use PyTorch_MPS_HIGH_WATERMARK_RATIO?

### ISSUE THREAD

**Issue by taynotfound** [run-llama/llama_index#8743]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to use PyTorch_MPS_HIGH_WATERMARK_RATIO?

```
index = VectorStoreIndex.from_documents(
    documents, storage_context=storage_context, service_context=service_context, PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
) 
```
Makes  it crash with following error
`RuntimeError: MPS backend out of memory (MPS allocated: 2.44 GB, other allocations: 4.34 GB, max allowed: 6.77 GB). Tried to allocate 10.58 MB on private pool. Use PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 to disable upper limit for memory allocations (may cause system failure).`

**Comment by taynotfound** [comment]
@dosu-bot PyTorch Version: 2.1.0
Hardware: MacBook Pro 2,3 GHz 8-Core Intel Core i9 8th gen. Radeon Pro Vega 20 4 GB
Intel UHD Graphics 630 1536 MB. 32 GB 2400 MHz DDR4

I am working with multiple PDF's 134.657.334 bytes (134,7 MB on disk) for 48 items

**Comment by logan-markewich** [comment]
@taynotfound this is an environment variable actually (and also not really related to llama-index)

In a terminal, I would do something like `export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0` before running my program to apply that setting
