### ISSUE TITLE
[Question]: I am unable to determine the number of API calls and the cost associated with llama_index and GPT-3.5 Turbo calls. I'm trying to optimize the cost for one of my models.

### ISSUE THREAD

**Issue by akashkumar398** [run-llama/llama_index#8750]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Steps to Reproduce:
llm = OpenAI(temperature=0.1, model="gpt-3.5-turbo")

service_context = ServiceContext.from_defaults(
llm=llm,callback_manager=callback_manager
)

from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine

query_engine = NLSQLTableQueryEngine(
sql_database=sql_database,
service_context=service_context
)

custom_prompt = """
follow the instructions if needed:
When given an inquiry of id, select the 'status' column"
"""

token_counter.reset_counts()
query_str = "What is the inqiry of id 1234?"
response = query_engine.query(custom_prompt + " " + query_str)
print(response.response)
print('token_counter:',token_counter.total_llm_token_count)

this is printing the token counts but i need to print api calls and cost for api call

**Comment by logan-markewich** [comment]
The token counts are actually tracked per API call, and `total_llm_token_count` is just adding them up

You can access `token_counter.llm_token_counts` and `token_counter.embedding_token_counts` for a list
