### ISSUE TITLE
[Question]: Finetune embedding without OpenAI

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#8752]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have been following the documentation and trying to finetune embedding but stuck in the corpus generation.

**The documentation** -: https://gpt-index.readthedocs.io/en/stable/examples/finetuning/embeddings/finetune_embedding_adapter.html

**Code expected** -: 

train_dataset = generate_qa_embedding_pairs(train_nodes)
train_dataset.save_json("train_dataset.json")

This by default expects an openAI api key but I want to use my own model to generate corpus.

**My code**-:

llm = AutoModelForCausalLM.from_pretrained("lmsys/vicuna-13b-v1.5",
                                            device_map='auto',
                                            torch_dtype=torch.float16
                                            #low_cpu_mem_usage=False
)

train_dataset = generate_qa_embedding_pairs(train_nodes,llm)

**The error**-: AttributeError: 'LlamaForCausalLM' object has no attribute 'complete'

**Function generate_qa_embedding_pairs** :

def generate_qa_embedding_pairs(
    nodes: List[TextNode],
    llm: Optional[LLM] = None,
    qa_generate_prompt_tmpl: str = DEFAULT_QA_GENERATE_PROMPT_TMPL,
    num_questions_per_chunk: int = 2,
) -> EmbeddingQAFinetuneDataset:
    """Generate examples given a set of nodes."""
    node_dict = {
        node.node_id: node.get_content(metadata_mode=MetadataMode.NONE)
        for node in nodes
    }

    llm = llm or OpenAI(model="gpt-3.5-turbo")

    queries = {}
    relevant_docs = {}
    for node_id, text in tqdm(node_dict.items()):
        query = qa_generate_prompt_tmpl.format(
            context_str=text, num_questions_per_chunk=num_questions_per_chunk
        )
        response = llm.complete(query)

        result = str(response).strip().split("\n")
        questions = [
            re.sub(r"^\d+[\).\s]", "", question).strip() for question in result
        ]
        questions = [question for question in questions if len(question) > 0]

        for question in questions:
            question_id = str(uuid.uuid4())
            queries[question_id] = question
            relevant_docs[question_id] = [node_id]

**Comment by logan-markewich** [comment]
@Aekansh-Ak you'll need to use one of our LLM classes, not the raw huggingface API

Here's an example of setting up zephyr https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

**Comment by Aekansh-Ak** [comment]
@logan-markewich  thank you so much for the suggestion.

How do I find out what all models are supported by llama_index.llms, the example you shared used "HuggingFaceH4/zephyr-7b-beta"

**Comment by Aekansh-Ak** [comment]
@logan-markewich 

I tried the code from colab notebook you shared. I don't understand this error.

Traceback (most recent call last):
  File "/home/seceon/dalm/dalm.py", line 53, in <module>
    llm = HuggingFaceLLM(
  File "/usr/local/lib/python3.9/site-packages/llama_index/llms/huggingface.py", line 131, in __init__
    self._model = model or AutoModelForCausalLM.from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 461, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/usr/local/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/usr/local/lib/python3.9/site-packages/transformers/models/auto/configuration_auto.py", line 710, in __getitem__
    raise KeyError(key)
KeyError: 'mistral'

**Comment by Aekansh-Ak** [comment]
Thank you so much @logan-markewich, it worked.

**Comment by Aekansh-Ak** [comment]
> @Aekansh-Ak Can you please share your working code implementation please with a non OpenAi open-source model. Thankyou. I am not able to find the source code for generate_qa_embedding_pairs() function to customize it. I too have the same usecase as you.

import pdfplumber
import torch
# from trial import new_add
import os
from llama_index import SimpleDirectoryReader
from llama_index.node_parser import SimpleNodeParser
from llama_index.schema import MetadataMode
import re
import uuid
import tqdm
import torch
from llama_index.finetuning import (
    generate_qa_embedding_pairs,
    EmbeddingQAFinetuneDataset,
)
from llama_index.llms import HuggingFaceLLM
from llama_index.prompts import PromptTemplate
from transformers import BitsAndBytesConfig

directory='/home/seceon/lm_index/new_freshdesk_index'

TRAIN_FILES=[]

for filename in os.listdir(directory):
    path = os.path.join(directory, filename)
    # checking if it is a file
    TRAIN_FILES.append(path)

def load_corpus(files, verbose=False):
    if verbose:
        print(f"Loading files {files}")

    reader = SimpleDirectoryReader(input_files=files)
    docs = reader.load_data()
    if verbose:
        print(f"Loaded {len(docs)} docs")
    reader = SimpleDirectoryReader(input_files=files)
    docs = reader.load_data()
    if verbose:
        print(f"Loaded {len(docs)} docs")

    parser = SimpleNodeParser.from_defaults()
    nodes = parser.get_nodes_from_documents(docs, show_progress=verbose)

    if verbose:
        print(f"Parsed {len(nodes)} nodes")

    return nodes

quantization_config = BitsAndBytesConfig(
    load_in_8bit=True,
    bnb_8bit_compute_dtype=torch.float32,
    bnb_8bit_quant_type="nf4",
    bnb_8bit_use_double_quant=True,
)

train_nodes = load_corpus(TRAIN_FILES, verbose=True)
llm = HuggingFaceLLM(
    model_name="lmsys/vicuna-13b-v1.5",
    tokenizer_name="lmsys/vicuna-13b-v1.5",
    context_window=3900,
    max_new_tokens=350,
    model_kwargs={"quantization_config": quantization_config},
    # tokenizer_kwargs={},
    device_map="auto",
)

train_dataset = generate_qa_embedding_pairs(train_nodes,llm)
train_dataset.save_json("train_dataset.json")
