### ISSUE TITLE
[Question]: APIConnectionError: Connection error

### ISSUE THREAD

**Issue by 4entertainment** [run-llama/llama_index#8765]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I want to run the following starter code with llama-index:

`
> import os
> from silly import  no_ssl_verification
> with no_ssl_verification():
>     os.environ["HUGGINGFACEHUB_API_TOKEN"] = "my_token"
>     from llama_index import VectorStoreIndex, SimpleDirectoryReader
>     documents = SimpleDirectoryReader("./docs/examples/data/paul_graham").load_data()
>     index = VectorStoreIndex.from_documents(documents)
>     query_engine = index.as_query_engine()
>     response = query_engine.query("What did the author do growing up?")
>     print(response)

`

I get the following error:

`raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.`

**Comment by 4entertainment** [comment]
@dosu-bot 
I didn't use any database connection. I just do starter task named "starter.py" at the documentation. 
`raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.`

**Comment by 4entertainment** [comment]
"Connection error" you're encountering is likely due to incorrect or missing environment variables related to the Azure OpenAI API." according to this statement, what can i do? i have llama-index project folder taken with git clone (from https://github.com/run-llama/llama_index)

**Comment by logan-markewich** [comment]
@4entertainment openai is having some API issues lately. It will probably be a lately shakey for the next day or two
