### ISSUE TITLE
[Question]: General Question

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#8768]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Is anyone else getting this response from an engine?:

'The context provided is a long string of numbers, specifically the number 7 repeated multiple times. It is unclear what the purpose or meaning of this string of numbers is.'

**Comment by gich2009** [comment]
This happens when streaming from a chat_engine using the stream_chat() method.

**Comment by logan-markewich** [comment]
That sounds extremely strange. I have not seen this.

Maybe double check what is in your index?

```
index.as_retriever().retrieve("query")
```

**Comment by gich2009** [comment]
Hi @logan-markewich, I figured out what the issue was. I was using a pinecone client as my vector store and the index had somehow invalidated itself. So it was returning a string of 7s. Please inform any other person with a similar issue to check the validity of their index.
