### ISSUE TITLE
[Feature Request]: When using elasticsarch to store vectors, can specify the analyzer for the content field.

### ISSUE THREAD

**Issue by czhcc** [run-llama/llama_index#8770]
### Feature Description

When using elasticsarch to store vectors, can specify the analyzer for the content field.
example:
self.text_field: {"type": "text", "analyzer": "ik_smart"}

**Comment by nerdai** [comment]
Thanks @czhcc! Are you looking to set this setting at index creation time? I did some quick [digging](https://stackoverflow.com/questions/73582432/how-to-update-change-the-existing-field-type-in-a-mapping-of-an-index-in-elastic) and it doesn't seem like one can update the settings of an existing index.

**Comment by czhcc** [comment]
Thanks, just set it when creating the index

**Comment by nerdai** [comment]
@czhcc thanks for the clarification. Okay, so our stuff only creates an index if when trying to add docs/nodes to the vector store for the first time. If the index does not exist then it will create one with a hard-coded `index_settings`.

We could expose a param in the construction of the vector store for users to supply a custom `index_settings`, though I am not sure how we would validate these yet outside of just trying to see if they work.

The alternative would be to create the index outside of the llama-index, and connect to it after the fact.

In your use case, are you creating index for the first time when you use llama-index?
