### ISSUE TITLE
[Question]: Customizing chat engines

### ISSUE THREAD

**Issue by lucijaSub** [run-llama/llama_index#8771]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have an issue with writing custom prompts for a chat engine. I have a vector index with my custom knowlage. 
I am using CondenseQuestionChatEngine as my query engine. I want to add a custom prompt that will tell my chat bot "You are an expert on X topic, answer correctly and don't hallucinate" but I am confused on how to do it.

When I do it like this:
```
query_engine_base = self.vector_index.as_query_engine(text_qa_template=qa_template)

self.base_chat_engine = CondenseQuestionChatEngine.from_defaults(
    query_engine=query_engine_base,
    verbose=True,
    service_context=self.service_context)

```
The bot answers correctly, but it doesn't remember chat history. How is this supposed to be done? I searched in the documentation and it has been confusing, I can't find a solution that does what I want.

**Comment by ravi03071991** [comment]
@lucijaSub did you check low level composition in chat engine - https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/usage_pattern.html . Should give an idea on how to customize your prompt.

**Comment by logan-markewich** [comment]
@lucijaSub you can add a system prompt

```
self.base_chat_engine = CondenseQuestionChatEngine.from_defaults(
    query_engine=query_engine_base,
    verbose=True,
    service_context=self.service_context,
    system_prompt="You are a ..."
)
```

**Comment by ram510** [comment]
Did not answer the second part of the question, The bot answers correctly, but it doesn't remember chat history. How is this supposed to be done? I searched in the documentation and it has been confusing, I can't find a solution that does what I want.?

**Comment by logan-markewich** [comment]
@ram510 if you are using a chat engine (not a query engine) it should be keeping track.

You can confirm by checking `chat_engine.memory.get()` -- this will fetch the current chat window from the buffer 

`chat_engine.chat_history` will fetch the full history, regardless of token limits

**Comment by ram510** [comment]
Thanks @logan-markewich

**Comment by lucijaSub** [comment]
> @ram510 if you are using a chat engine (not a query engine) it should be keeping track.
> 
> You can confirm by checking `chat_engine.memory.get()` -- this will fetch the current chat window from the buffer
> 
> `chat_engine.chat_history` will fetch the full history, regardless of token limits

Thanks for the answer. I tried this and you are right, all the messages are kept in chat history, but for some reason when I ask the bot what was my last question he doesn't know how to answer. Maybe it uses the history just to formulate a question and not for the context for answering the query? Is this how it is supposed to be?

**Comment by ambikeshsingh** [comment]
why chat engine is giving response out side the context . Even I have done system prompting as well . My chat mode is "Context".
please help.

**Comment by YogeshMirpuri** [comment]
> why chat engine is giving response out side the context . Even I have done system prompting as well . My chat mode is "Context". please help.

i am also facing the same problem, did you find a solution?
