### ISSUE TITLE
[Feature Request]: Digital ocean storage for remote backend

### ISSUE THREAD

**Issue by smyja** [run-llama/llama_index#8776]
### Feature Description

I'd like to see an example on using digital ocean to store the Vectors and retrieve also.

**Comment by nerdai** [comment]
@smyja I think you mean connecting to a vector DB that you have managed on DigitalOcean cloud infra? If so, then I believe you can stand up PGVector and use LlamaIndex `PGVectorStore` to connect to it by specifying the appropriate `connection_string`

**Comment by smyja** [comment]
> @smyja I think you mean connecting to a vector DB that you have managed on DigitalOcean cloud infra? If so, then I believe you can stand up PGVector and use LlamaIndex `PGVectorStore` to connect to it by specifying the appropriate `connection_string`

Actually i meant a remote backend like [this](https://docs.llamaindex.ai/en/stable/module_guides/storing/save_load.html#using-a-remote-backend) I think using digitalocean might work since its s3 compatible, i'll try it and update.

**Comment by nerdai** [comment]
@smyja thanks for clarification - my bad! Yeah I just saw https://www.digitalocean.com/products/spaces this about digital ocean being s3 compatible. Please do let us know if it works out!

**Comment by smyja** [comment]
> @smyja thanks for clarification - my bad! Yeah I just saw https://www.digitalocean.com/products/spaces this about digital ocean being s3 compatible. Please do let us know if it works out!

yes, it worked. but it creates a llamaindex file in addition. Its empty. 
<img width="1224" alt="Screenshot 2023-11-12 at 10 45 22" src="https://github.com/run-llama/llama_index/assets/20070770/a94259e9-6614-4c69-9a08-82b08f1a3cf3">

**Comment by nerdai** [comment]
oh strange — i'm not sure what's happening there... i don't see our stuff persisting any sort of files like that by default. Perhaps something on digital-ocean end.

I'm glad it all but works perfectly (outside of this empty file business). Going to close this now.
