### ISSUE TITLE
[Question]: How to use the finetuned embedding model?

### ISSUE THREAD

**Issue by Aekansh-Ak** [run-llama/llama_index#8780]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was able to finetune the model using this documentation: 

https://gpt-index.readthedocs.io/en/stable/examples/finetuning/embeddings/finetune_embedding.html

It created a folder "model_output_test" with files-:
config.json  pytorch_model.bin

The original embedding model downloaded from hugging face has these files-:
config_sentence_transformers.json  pytorch_model.bin  sentence_bert_config.json  tokenizer_config.json  vocab.txt
config.json  modules.json                       README.md          special_tokens_map.json    tokenizer.json

I am currently using the embedding model like this-: 
embed_model = HuggingFaceInstructEmbeddings(model_name="BAAI/bge-large-en-v1.5",
                                                model_kwargs={"device": "cpu"})
                                                
How do I use the one which is finetuned on my data since it is in a folder, plus is it okay for it to just have those two files?

**Comment by logan-markewich** [comment]
If the model is in a folder, you should be able to just set the model_name as the path to the folder

**Comment by Aekansh-Ak** [comment]
Error: ValueError: Unrecognized model in /home/seceon/dalm/model_output_test. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, camembert, canine, chinese_clip, clap, clip, clipseg, codegen, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, data2vec-audio......

This is all that is in model_ouput_test.

{"in_features": 1024, "out_features": 1024, "bias": false}

**Comment by GEN200J** [comment]
> Error: ValueError: Unrecognized model in /home/seceon/dalm/model_output_test. Should have a `model_type` key in its config.json, or contain one of the following strings in its name: albert, align, altclip, audio-spectrogram-transformer, autoformer, bark, bart, beit, bert, bert-generation, big_bird, bigbird_pegasus, biogpt, bit, blenderbot, blenderbot-small, blip, blip-2, bloom, bridgetower, camembert, canine, chinese_clip, clap, clip, clipseg, codegen, conditional_detr, convbert, convnext, convnextv2, cpmant, ctrl, cvt, data2vec-audio......
> 
> This is all that is in model_ouput_test.
> 
> {"in_features": 1024, "out_features": 1024, "bias": false}

I got the same issue with a fine tuned bge m3 model
