### ISSUE TITLE
Recursive Retriever with BM25

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8786]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello , 

I think my RAG would be more successful with keyword based retrieval like [BM25](https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever.html) .

I am using [Recursive Retriever](https://gpt-index.readthedocs.io/en/latest/examples/query_engine/recursive_retriever_agents.html)

How I can change Recursive Retriever to add an option for BM25Retriever for single document

**Comment by logan-markewich** [comment]
@snassimr I don't think you want to add BM25 to the recusive retriever, but rather, combine both into a single retriever.

For this, the easiest is probably just combining both into a custom retriever
https://docs.llamaindex.ai/en/stable/examples/query_engine/CustomRetrievers.html#retriever-query-engine-with-custom-retrievers-simple-hybrid-search

Or using query fusion (you can disable the extra question generation to improve speed)
https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#simple-fusion-retriever
