### ISSUE TITLE
How to retreive ReAct agent history

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8790]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi , 

I wonder if it's possible to get the content of ReAct agent history in some structured or semi-structured way ?

The example for history is below : 

![image](https://github.com/run-llama/llama_index/assets/6830626/18647da8-c9e6-42ac-8ce0-77639f07fbe5)

**Comment by nerdai** [comment]
Yup, you should be able to retrieve it with `chat_history` property

**Comment by snassimr** [comment]
Looks like chat_history contains only first and last messages and thoughts/actions just logged without storing it in some object

chat_history : 

![image](https://github.com/run-llama/llama_index/assets/6830626/09068203-437d-41e6-a166-235005f486fe)
