### ISSUE TITLE
[Bug]: GPTListIndex Object incorrectly creates a SummaryIndex Object

### ISSUE THREAD

**Issue by Jgerardopine** [run-llama/llama_index#8798]
### Bug Description

I created an object of GPTListIndex, bur when using it it says it is a SummaryIndex Object and I can't use  the query attribute

Code:
``` 
index = GPTListIndex.from_documents(mock_document, service_context=service_context)
```

I call the query: 
```
response = index.query(example_query, mode="default", service_context=service_context)
```

and I get this error:
`'SummaryIndex' object has no attribute 'query'`

### Version

0.8.65

### Steps to Reproduce

Import Llama Index GPTListIndex

`from llama_index import  GPTListIndex, SimpleDirectoryReader`

I am using MockLLMPredicto  and MOck Ebed as well for th efull excercise, as I create a ServiceContext. You cna create it as well. Here are all the lines of code:

```
llm_model_name = "gpt-3.5-turbo"
llm=OpenAI(temperature=0, model_name=llm_model_name))
    llm_predictor_mock = MockLLMPredictor(max_tokens=256, llm=llm_model_name)
    embed_model_mock = MockEmbedding(embed_dim=1536)

service_context = ServiceContext.from_defaults(llm_predictor=llm_predictor_mock, embed_model=embed_model_mock)
```

Load a Document, create the index and call the index with a query (any query string will do)

```
index = GPTListIndex.from_documents(mock_document, service_context=service_context)

query_str = """ WHat's the end of life of Lenovo ABC"""

print(index)
response = index.query(example_query, mode="default", service_context=service_context)
print(response)
```

### Relevant Logs/Tracbacks

```shell
WARNING:py.warnings:/home/src/aithentic_optimus/transformers/semantic_list_and_cost.py:71: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.

  ' and characteristics ' + df['BPM_ProductDescriptionUpdate'].str.replace('|', ' ')



Total Tokens: 1212

EMbedding Cost in USD: 0.000485

<llama_index.indices.list.base.SummaryIndex object at 0x7f5482fc4100>


---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

/home/src/aithentic_optimus/transformers/semantic_list_and_cost.py in transform(data, *args, **kwargs)

    144      """

    145     print(index)

--> 146     response = index.query(example_query, mode="default", service_context=service_context)

    147     print(response)

    148 


AttributeError: 'SummaryIndex' object has no attribute 'query'
```

**Comment by logan-markewich** [comment]
@Jgerardopine GPTListIndex (a very old name) is the same as SummaryIndex, just a rename

You can query with the following code

```
query_engine = index.as_query_engine()
response = query_engine.query("my query")
```

I suggest refreshing yourself with our docs as well 👍🏻 
https://docs.llamaindex.ai/en/stable/getting_started/starter_example.html

**Comment by Jgerardopine** [comment]
It worked. But now I have a very different problem. 
I am using MockLLMPRedictor to simulate and check token usage (and calculate total cost). But now MockLLMPredictor does not have the attribute last_token_usage:

The documentation in the webpage says it should exist, but in my code is not bieng called.

https://gpt-index.readthedocs.io/en/v0.6.8/reference/service_context/llm_predictor.html

**Comment by logan-markewich** [comment]
Use MockLLM now

**Comment by logan-markewich** [comment]
from llama_index.llms import MockLLM
