### ISSUE TITLE
[Question]: Is there an exmaple of cost analysis that works? MockLLMPRedictor is not working

### ISSUE THREAD

**Issue by Jgerardopine** [run-llama/llama_index#8799]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

 I am looking for a Cost Analysis example that I can use without calling OpenAI, so I can get an approximate cost of a specific use case I have. I've seen the xamples and I got my code working almost to the end, but the MockLLMPRedictor library apparently is not working anymore for the newest versions.

I used this example: `https://betterprogramming.pub/how-to-calculate-and-optimize-chatgpt-costs-using-langchain-9599354f0e2c`
I go tit almost working except the total_token_usage, as that function is no longer working.  I also looked into the documentation, and they have the same exmaples, and none is working:

https://gpt-index.readthedocs.io/en/v0.6.8/reference/service_context/llm_predictor.html
https://gpt-index.readthedocs.io/en/v0.6.8/how_to/analysis/cost_analysis.html

**Comment by logan-markewich** [comment]
The documentation you linked is very old.

The latest example of token counting is here
https://docs.llamaindex.ai/en/stable/examples/callbacks/TokenCountingHandler.html

**Comment by Jgerardopine** [comment]
Awesome. this indeed worked. Thanks for the support.
