### ISSUE TITLE
[Question]:  Conversational chat agent with history and previous responses as context.

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#8802]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Here is the code where I implemented a RAG agent,

def chat_app(query_str):    
    query_str = query_str 
    chat_agent = CondenseQuestionChatEngine.from_defaults(query_engine=query_engine,service_context=service_context)
    chat_resp = chat_agent.chat(query_str)
    return chat_resp
chat_resp = chat_app("query_str")
while True:
    query_str = input("User: ")
    if query_str == "exit":
        break
    response = chat_app(query_str)
    
    print(f"Agent: {response}")
    print()
    
    how do I pass previous responses and context to the CondenseQuestionChatEngine.from_defaults so that the user need not be specific about the details or need to supply the context every time

**Comment by logan-markewich** [comment]
It looks like you are re-creating the chat engine on every message, which erases the chat history

**Comment by ram510** [comment]
Hi @logan-markewich using the example provided  in [https://gpt-index.readthedocs.io/en/v0.8.47/examples/low_level/oss_ingestion_retrieval.html](Building RAG from Scratch) I have created a retriever. But the VectorDBRetriever class has an undefined query_str, to mitigate that I have introduded query_str in the class. Below is the code
`from typing import Any, List, Optional

from llama_index.retrievers import BaseRetriever
from llama_index.schema import NodeWithScore
from llama_index.vector_stores import VectorStoreQuery

from llama_index import QueryBundle
from llama_index.vector_stores import PGVectorStore
from one import embed_model


class VectorDBRetriever(BaseRetriever):
    """Retriever over a postgres vector store."""

    def __init__(
        self,
        vector_store: PGVectorStore,
        embed_model: Any,
        query_str: str,
        query_mode: str = "default",
        similarity_top_k: int = 2,
    ) -> None:
        """Init params."""
        self._vector_store = vector_store
        self._embed_model = embed_model
        self._query_mode = query_mode
        self._similarity_top_k = similarity_top_k
        **self._query_str = query_str**

    def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve."""
        query_embedding = embed_model.get_query_embedding(self.**_query_str**)
        vector_store_query = VectorStoreQuery(
            query_embedding=query_embedding,
            similarity_top_k=self._similarity_top_k,
            mode=self._query_mode,
        )
        query_result = self._vector_store.query(vector_store_query)

        nodes_with_scores = []
        for index, node in enumerate(query_result.nodes):
            score: Optional[float] = None
            if query_result.similarities is not None:
                score = query_result.similarities[index]
            nodes_with_scores.append(NodeWithScore(node=node, score=score))

        return nodes_with_scores
`
now for every query I have to create a new objects for retriever, query_engine and chat_agent as they are independent 
`        if "query" in data:
            **query_str** = data["query"]

            # Create a VectorDBRetriever and a RetrieverQueryEngine
            retriever = VectorDBRetriever(
                vector_store,
                embed_model,
                **query_str**,
                query_mode=query_mode,
                similarity_top_k=similarity_top_k,
            )

            query_engine = RetrieverQueryEngine.from_args(
                **retriever**, service_context=service_context
            )
            chat_agent = CondenseQuestionChatEngine.from_defaults(
                query_engine=**query_engine**, service_context=service_context
            )
            response = chat_agent.chat(query_str)`
please help

**Comment by nerdai** [comment]
Hi @ram510. Sorry, I'm a bit confused as to what you're trying to achieve here. Are you trying to pass off the chat_history of one agent to another agent/query_engine?

**Comment by lucijaSub** [comment]
I believe I have the same issue. I have a CondenseQuestionChatEngine and it keeps chat history okay. So if I ask it a follow up question, it will form a new question based on the history and it will give a good answer. 
However, if I ask it "What was my last question?" it will not know how to answer. So, I suppose, it is using the history to generate the query it sends to the LLM, but it is not using the history for the answer syntesis part. Is this how it is supposed to work?

**Comment by nerdai** [comment]
HI @lucijaSub, can you kindly provide code to replicate the issue you've described?

**Comment by lucijaSub** [comment]
> HI @lucijaSub, can you kindly provide code to replicate the issue you've described?

Yes, of course.

Here is the first init version:

   ```
 def initBaseChat(self):
        if self.vector_index is None:
            return AgentChatResponse("Index is not initialized!")

        query_engine_base = self.vector_index.as_query_engine(text_qa_template=qa_template)

        self.base_chat_engine = CondenseQuestionChatEngine.from_defaults(
            query_engine=query_engine_base, verbose=True, service_context=self.service_context
        )
```

Here is my other init version:
```
def initBaseChat2(self):
        if self.vector_index is None:
            return AgentChatResponse("Index is not initialized!")

        query_engine_base = self.vector_index.as_query_engine()

        self.base_chat_engine = CondenseQuestionChatEngine.from_defaults(
            query_engine=query_engine_base,
            condense_question_prompt=custom_prompt,
            chat_history=custom_chat_history,
            verbose=True,
            service_context=self.service_context,
        )
```

and the prompts, instead of Bot initialization prompt in my code is the prompt for how my bot should behave:


```
template = (
    """ *Bot initialization prompt*
We have included context information below. \n"""
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Given this information, please answer the question: {query_str}\n"
)
qa_template = PromptTemplate(template)

custom_prompt = PromptTemplate(
    """\
Given a conversation (between Human and Assistant) and a follow up message from Human, \
rewrite the message to be a standalone question that captures all relevant context \
from the conversation.

<Chat History>
{chat_history}

<Follow Up Message>
{question}

<Standalone question>
"""
)

# list of `ChatMessage` objects
custom_chat_history = [
    ChatMessage(
        role=MessageRole.SYSTEM,
        content=""" *Bot initialization prompt* """,
    ),
    ChatMessage(role=MessageRole.ASSISTANT, content="Okay, sounds good."),
]
```

And with both init versions I get the same behaviour, if I ask them something that should include chat history they know how to format the question so I get the full answer, but they do not know how to get the answer if it is in the chat history itself.

**Comment by Vishnu-add** [comment]
from llama_index.chat_engine.condense_question import CondenseQuestionChatEngine


chat_agent = CondenseQuestionChatEngine.from_defaults(
    query_engine=graph_engine,
    service_context=service_context,
    verbose=True
)

chat_agent.chat("What is bayesian learning?")


Error: 
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-109-0a19bfcd8375>](https://localhost:8080/#) in <cell line: 1>()
----> 1 chat_agent.chat("What is bayesian learning?")

5 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/agent/react/output_parser.py](https://localhost:8080/#) in format(self, output)
     95     def format(self, output: str) -> str:
     96         """Format a query with structured output formatting instructions."""
---> 97         raise NotImplementedError

NotImplementedError:



I'm getting this error. I'm using composable graph as query engine.

**Comment by logan-markewich** [comment]
@Vishnu-add what version of llama-index do you have?
