### ISSUE TITLE
[Question]:  How do I add topical safety and content safety to my application.

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#8804]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Here is my retriever and query engine, How do I apply content and topical safety to my application.
Is there a way I can implement demo guard rails into my application.

from llama_index import QueryBundle
from llama_index.retrievers import BaseRetriever
from typing import Any, List
from llama_index.vector_stores import VectorStoreQuery
from llama_index.schema import NodeWithScore
from typing import Optional

class VectorDBRetriever(BaseRetriever):
    """Retriever over a postgres vector store."""

    def __init__(
        self,
        vector_store: PGVectorStore,
        embed_model: Any,
        query_mode: str = "default",
        similarity_top_k: int = 2,
    ) -> None:
        """Init params."""
        self._vector_store = vector_store
        self._embed_model = embed_model
        self._query_mode = query_mode
        self._similarity_top_k = similarity_top_k

    def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve."""
        query_embedding = embed_model.get_query_embedding(query_str)
        vector_store_query = VectorStoreQuery(
            query_embedding=query_embedding,
            similarity_top_k=self._similarity_top_k,
            mode=self._query_mode,
        )
        query_result = vector_store.query(vector_store_query)

        nodes_with_scores = []
        for index, node in enumerate(query_result.nodes):
            score: Optional[float] = None
            if query_result.similarities is not None:
                score = query_result.similarities[index]
            nodes_with_scores.append(NodeWithScore(node=node, score=score))

        return nodes_with_scores
    
    retriever = VectorDBRetriever(
    vector_store, embed_model, query_mode="default", similarity_top_k=2
)
    
query_engine = RetrieverQueryEngine.from_args(
    retriever, service_context=service_context

)

**Comment by ram510** [comment]
@dosu-bot Idea here is to restrict the LLM to answering questions that are not related to the context.
LLM should answer only the questions that are based on the context derived from vector store

**Comment by nerdai** [comment]
> @dosu-bot Idea here is to restrict the LLM to answering questions that are not related to the context. LLM should answer only the questions that are based on the context derived from vector store

Hey @ram510 have you tried customizing the prompt that the LLM is using to accomplish this? Here's a guide for how to do that: https://gpt-index.readthedocs.io/en/stable/examples/prompts/prompts_rag.html#viewing-customizing-prompts
