### ISSUE TITLE
[Bug]: SQLAutoVectorQueryEngine Tutorial error

### ISSUE THREAD

**Issue by tamanna037** [run-llama/llama_index#8815]
### Bug Description

I am trying to run SQLAutoVectorQueryEngine Tutorial , https://github.com/run-llama/llama_index/blob/main/docs/examples/query_engine/SQLAutoVectorQueryEngine.ipynb. but 
response = query_engine.query(
    "Tell me about the arts and culture of the city with the highest"
    " population"
)

is showing this error. It was working fine 2-3 days ago. Have you changed anything?
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-53-29d7f42332ec>](https://localhost:8080/#) in <cell line: 1>()
----> 1 response = query_engine.query(
      2     "Tell me about the arts and culture of the city with the highest"
      3     " population"
      4 )

4 frames
[/usr/local/lib/python3.10/dist-packages/llama_index/program/openai_program.py](https://localhost:8080/#) in __call__(self, *args, **kwargs)
    123         message = chat_response.message
    124         if "function_call" not in message.additional_kwargs:
--> 125             raise ValueError(
    126                 "Expected function call in ai_message.additional_kwargs, "
    127                 "but none found."

ValueError: Expected function call in ai_message.additional_kwargs, but none found.

### Version

0.8.65

### Steps to Reproduce

Run the tutorial.

**Comment by logan-markewich** [comment]
@tamanna037 this should be fixed in the next release

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/pull/8816

Should be on pypi shortly
