### ISSUE TITLE
Poor performance of of vector retriever/engine on queries with keywords

### ISSUE THREAD

**Issue by snassimr** [run-llama/llama_index#8824]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi , 

The question objective isn't llama_index per se.

I have simple code  up to query engine : 

`
from llama_index.embeddings import OpenAIEmbedding
embed_model = OpenAIEmbedding(model='text-embedding-ada-002',
                              embed_batch_size=10)

node_parser = SimpleNodeParser.from_defaults(chunk_size = 128,
                                             chunk_overlap = 16,
                                             include_metadata = True)

service_context = ServiceContext.from_defaults(llm=llm,
                                               embed_model=embed_model,
                                               node_parser=node_parser)

    # Build vector index
    vector_index = VectorStoreIndex.from_documents(documents,  service_context=service_context)

...
`

I want to present a title of Figure 2 with query = "Present title of Figure 2"

The top node is retrieved has score > 0.8 and contains text : ". . . . . . . . . . . . . . . . . . 2 ."

I tried to use SimpleKeywordTableIndex , but with no success.

Any clue how I can improve retrieving nodes in this case ?

Thanks

**Comment by logan-markewich** [comment]
@snassimr try using bm25, or even combine bm25 with the vector index
https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#simple-fusion-retriever
