### ISSUE TITLE
[Bug]:  Constant timeouts after multiple calls with async

### ISSUE THREAD

**Issue by Inkorak** [run-llama/llama_index#8833]
### Bug Description

Constant timeouts after multiple asynchronous calls to openai. It was discovered when use async methods, constant timeouts begin. If you do this without async or with async, but on the old version like 0.8.55 and openai 0.28, then there are no problems.

### Version

0.8.66

### Steps to Reproduce

Use any async methods. Like evaluators multiple times in row.

**Comment by logan-markewich** [comment]
tbh, the openai api has been a little unstable the past few days
