### ISSUE TITLE
[Question]: How to work with query_wrapper_prompt=PromptTemplate()?

### ISSUE THREAD

**Issue by kiasar** [run-llama/llama_index#8834]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,
I find it difficult to understand how to work with `query_wrapper_prompt=PromptTemplate()`.

Is there any example in the documents for it? I was not able to find any.

For example, can you help me find out how to write this template from [zephyr-7b](https://huggingface.co/HuggingFaceH4/zephyr-7b-beta) using your API?
```python
messages = [
    {
        "role": "system",
        "content": "You are a friendly chatbot who always responds in the style of a pirate",
    },
    {"role": "user", "content": "How many helicopters can a human eat in one sitting?"},
]
prompt = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
```

**Comment by kiasar** [comment]
@dosubot It is still unclear to me how can I write the format of the examples prompt template in your API.

```python
messages = [
    {
        "role": "system",
        "content": "You are a friendly chatbot who always responds in the style of a pirate",
    },
    {"role": "user", "content": "How many helicopters can a human eat in one sitting?"},
]
prompt = pipe.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
```

**Comment by kiasar** [comment]
@dosu-bot It seems that there is no "{context_str}". I get this error!

```
KeyError: 'context_str'
```

**Comment by logan-markewich** [comment]
@kiasar we have a guide for zephyr here
https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

Found from this page
https://docs.llamaindex.ai/en/stable/module_guides/models/llms.html#open-source-llms

But also, recent updates to the HuggingFaceLLM class will automatically use the tokenizer.apply_chat_template functionality when possible instead

**Comment by kiasar** [comment]
Thank you, Logan. I'll check it out.

**Comment by logan-markewich** [comment]
Just for reference too, here's the line of code that uses `apply_chat_template()`
https://github.com/run-llama/llama_index/blob/cddea481967499f079190e405307646ce2be8afa/llama_index/llms/huggingface.py#L234

**Comment by kiasar** [comment]
@logan-markewich Is the guide for Zephyr that you provided outdated? It seems that the function `messages_to_prompt` isn't being called anymore. Am I right?

**Comment by logan-markewich** [comment]
@kiasar if it's provided, it's still used. The tokenizer is just a fallback

https://github.com/run-llama/llama_index/blob/cddea481967499f079190e405307646ce2be8afa/llama_index/llms/huggingface.py#L197
