### ISSUE TITLE
[Question]: Setting global service_context

### ISSUE THREAD

**Issue by utility-aagrawal** [run-llama/llama_index#8839]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi All, I have a question about using global service context. I have built a RAG Q&A pipeline using Llamaindex and it has 2 components: 1) Indexing documents every time a directory is updated 2) Query the index. I am using local models for embedding and LLM so I am setting service_context separately for both of these components. That takes about 4 seconds each time. I am trying to reduce the time my pipeline takes to answer a question. Is it something setting global service_context can help with?

If yes, do I need to set it once on a machine? I am trying to understand how does global service_context work. Thanks!

**Comment by logan-markewich** [comment]
Shared this on discord, but

```
Global service context just changes the "default" service context essentially 

set_global_service_context(service_context) will just change the result of any ServiceContext.from_defaults() calls later on

So you could set a global LLM and then still override the embedding model later

Or you can set the global once and not have to worry about setting any other service context

Since you are running code in two files separately, the global service context cant help in th
```

```
I would suggest setting up your app such-that it's more like a server, so that you only have to set things up once and then can leave it running
```
