### ISSUE TITLE
[Bug]: Fallback to `llama2-chat-13B` doesn't seem to be working

### ISSUE THREAD

**Issue by rtorrero** [run-llama/llama_index#8856]
### Bug Description

By following the documentation it looks that if `OPENAI_API_KEY` is not set, llama-index will not attempt to use `gpt-3.5-turbo` and will instead fallback to `llama2-chat-13B`, but in my case, it leads to the following error when following the starter tutorial:

```
╰─$ python starter.py 
... (supressed output)
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/openai/_base_client.py", line 897, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

### Version

 0.8.64

### Steps to Reproduce

- Followed https://gpt-index.readthedocs.io/en/latest/getting_started/installation.html#local-model-setup and https://gpt-index.readthedocs.io/en/latest/examples/llm/llama_2_llama_cpp.html to get LlamaCPP using CLBLAST optimized for AMD GPUs.

- Created a `data` directory where I place a markdown document that I want to be able to query

After that, I try to run:

```
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

import os.path
from llama_index import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
)

# check if storage already exists
if not os.path.exists("./storage"):
    # load the documents and create the index
    documents = SimpleDirectoryReader("data").load_data()
    index = VectorStoreIndex.from_documents(documents)
    # store it for later
    index.storage_context.persist()
else:
    # load the existing index
    storage_context = StorageContext.from_defaults(persist_dir="./storage")
    index = load_index_from_storage(storage_context)

# either way we can now query the index
query_engine = index.as_query_engine()
response = query_engine.query("What gatherer could I use to check the available filesystems?")
print(response)
```

with `python starter.py` after installing the requirements.

I'm assuming something else needs to be done on my side, but by following the documentation I'm not understanding what additional step is required.

### Relevant Logs/Tracbacks

```shell
╰─$ python starter.py
Traceback (most recent call last):
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/httpcore/_sync/http11.py", line 142, in _send_request_headers
    event = h11.Request(
            ^^^^^^^^^^^^
....
(Suppressed very similar output)
...
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/openai/_base_client.py", line 890, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/openai/_base_client.py", line 925, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/rtorrero/Workspace/llamaindex-tutorial/venv/lib/python3.11/site-packages/openai/_base_client.py", line 897, in _request
    raise APIConnectionError(request=request) from err
openai.APIConnectionError: Connection error.
```

**Comment by rtorrero** [comment]
@dosu-bot but in the docs, specifically in the "Installation and setup" section, I can read:
>If you don’t wish to use OpenAI, the environment will automatically fallback to using LlamaCPP and llama2-chat-13B for text generation and BAAI/bge-small-en for retrieval and embeddings. These models will all run locally.

How can I run LlamaIndex using my local llama2 model using LlamaCPP?

**Comment by logan-markewich** [comment]
@rtorrero yea I have a PR here to fix the documentation. This feature had to be removed because automatically downloading a 10GB model is not really nice to do to the user.

https://github.com/run-llama/llama_index/pull/8819

See here for details on how to setup LlamaCPP so that you can put it in the service context

https://gpt-index.readthedocs.io/en/latest/examples/llm/llama_2_llama_cpp.html
