### ISSUE TITLE
[Question]: Building RAG from scratch example code issue, help

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#8857]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi @logan-markewich using the example provided  in [https://gpt-index.readthedocs.io/en/v0.8.47/examples/low_level/oss_ingestion_retrieval.html](Building RAG from Scratch) I have created a retriever. But the VectorDBRetriever class has an undefined query_str, to mitigate that I have introduded query_str in the class. Below is the code
`from typing import Any, List, Optional

from llama_index.retrievers import BaseRetriever
from llama_index.schema import NodeWithScore
from llama_index.vector_stores import VectorStoreQuery

from llama_index import QueryBundle
from llama_index.vector_stores import PGVectorStore
from one import embed_model

class VectorDBRetriever(BaseRetriever):
    """Retriever over a postgres vector store."""

    def __init__(
        self,
        vector_store: PGVectorStore,
        embed_model: Any,
        query_str: str,
        query_mode: str = "default",
        similarity_top_k: int = 2,
    ) -> None:
        """Init params."""
        self._vector_store = vector_store
        self._embed_model = embed_model
        self._query_mode = query_mode
        self._similarity_top_k = similarity_top_k
        self._query_str = query_str // CHECK HERE

    def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
        """Retrieve."""
        query_embedding = embed_model.get_query_embedding(self._query_str) // CHECK HERE
        vector_store_query = VectorStoreQuery(
            query_embedding=query_embedding,
            similarity_top_k=self._similarity_top_k,
            mode=self._query_mode,
        )
        query_result = self._vector_store.query(vector_store_query)

        nodes_with_scores = []
        for index, node in enumerate(query_result.nodes):
            score: Optional[float] = None
            if query_result.similarities is not None:
                score = query_result.similarities[index]
            nodes_with_scores.append(NodeWithScore(node=node, score=score))

        return nodes_with_scores
`
now for every query I have to create a new objects for retriever, query_engine and chat_agent as they are independent 
`        if "query" in data:
            query_str = data["query"]

            # Create a VectorDBRetriever and a RetrieverQueryEngine
            retriever = VectorDBRetriever(
                vector_store,
                embed_model,
                query_str, // CHECK HERE
                query_mode=query_mode,
                similarity_top_k=similarity_top_k,
            )

            query_engine = RetrieverQueryEngine.from_args(
                retriever, service_context=service_context // RETRIEVER DEPENDENCY
            )
            chat_agent = CondenseQuestionChatEngine.from_defaults(
                query_engine=query_engine, service_context=service_context // QUERY ENGINE DEPENDECY
            )
            response = chat_agent.chat(query_str)`
please help

**Comment by logan-markewich** [comment]
The bots response appears to be correct

To be clear, it's this line of code that was changed to fix the issue

`query_embedding = self._embed_model.get_query_embedding(query_bundle.query_str)`

**Comment by ram510** [comment]
Yeah, it worked thanks @logan-markewich
