### ISSUE TITLE
[Question]: callback_manager can not get message for `StreamingAgentChatResponse` on `event.on_end`

### ISSUE THREAD

**Issue by azurewtl** [run-llama/llama_index#8879]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Current callback for `ReAct` agent will produce multiple `LLM` event/span at the same level.
A more elegant way is to wrap all event in a `parent event`, so that one conversation(`agent.chat(xx)`) will shown in one line. 
`chat` or `achat` entry point works fine, the problem is in `stream_chat`.
### following show the traditional way of wrapping one conversation in a event/span
```python
@trace_method("chat")
def stream_chat(self, message, chat_history) -> StreamingAgentChatResponse:
    with self.callback_manager.event(CBEventType.CHAT) as event:
      ```lots of agent logic```
      chat_stream_response = StreamingAgentChatResponse(chat_stream=response_stream)
      event.on_end(payload={EventPayload.MESSAGE: ‼️ how_can_I_get_message‼️ })
    return chat_stream_response
```
The issue is in the second last line, when the event ends, how am I suppose to get `chat_response.context`, with return `chat_stream_response`.`response_gen` is a generator.

In `llama_index/llms/base.py`, there is a decorator `llm_chat_callback()`. However our return value`chat_stream_response` has generator in it's attribute, so we can not `yield` by decorator
```python
def wrapped_gen() -> ChatResponseGen:
      last_response = None
      for x in f_return_val:
          yield cast(ChatResponse, x)
          last_response = x

      callback_manager.on_event_end(
          CBEventType.LLM,
          payload={
              EventPayload.MESSAGES: messages,
              EventPayload.RESPONSE: last_response,
          },
          event_id=event_id,
      )
  return wrapped_gen()
```

screen shot shows before and after in phoenix 
![scs](https://github.com/run-llama/llama_index/assets/5175672/10fad734-b276-4d62-8df6-bbdb0f1e7632)

**Comment by logan-markewich** [comment]
Feel free to make a PR with these changes @azurewtl 

Its a good idea!

**Comment by azurewtl** [comment]
> Feel free to make a PR with these changes @azurewtl
> 
> Its a good idea!

But how can I get response content in stream_chat as mentioned in the main thread?

**Comment by logan-markewich** [comment]
@azurewtl you would need to call `event.on_end` once the stream is exhausted 

So, wrapping the generator with another generator that yields and calls on_end() when it's finished maybe? We do something similar for catching streamed LLM responses in LLM events -- it's a little tricky but possible

**Comment by azurewtl** [comment]
> @azurewtl you would need to call `event.on_end` once the stream is exhausted
> 
> So, wrapping the generator with another generator that yields and calls on_end() when it's finished maybe? We do something similar for catching streamed LLM responses in LLM events -- it's a little tricky but possible

> `llama_index/llms/base.py`, there is a decorator `llm_chat_callback()`. However our return value`chat_stream_response` >has generator in it's attribute, so we can not `yield` by decorator
>```python
>def wrapped_gen() -> ChatResponseGen:
>      last_response = None
>      for x in f_return_val:
>          yield cast(ChatResponse, x)
>          last_response = x
>     callback_manager.on_event_end(
>          CBEventType.LLM,
>          payload={
>              EventPayload.MESSAGES: messages,
>              EventPayload.RESPONSE: last_response,
>          },
>          event_id=event_id,
>      )
>  return wrapped_gen()
>```
I guess you are talking about the above **catching and yield** approach, However we can't wrap `chat_stream_response` because it's not a generator, the actual generator is in `chat_stream_response`.`response_gen`

**Comment by logan-markewich** [comment]
Right, so maybe wrap that an reassign it to the response object?

Dealing with streamed results is pretty tricky, as you can see

**Comment by azurewtl** [comment]
> Right, so maybe wrap that an reassign it to the response object?
> 
> Dealing with streamed results is pretty tricky, as you can see

I see! I need to dynamically get `response_gen` inside `chat_stream_response`( it's already wrapped by LLM callback), wrap it with another level of callback, and then reassign `response_gen` in `chat_stream_response ` before returning it.
