### ISSUE TITLE
[Feature Request]: Fusion_RAG + Semi_Structured_RAG?

### ISSUE THREAD

**Issue by Lauorie** [run-llama/llama_index#8884]
### Feature Description

There are a lot of tables and text in my data. First of all, I have tried Fusion_RAG, which is much better than the baseline, but it is limited to the text, and the table can not be processed, so I wondered if there a way could combine [Semi_Structured_RAG](https://github.com/langchain-ai/langchain/blob/master/cookbook/Semi_Structured_RAG.ipynb) and [Fusion_RAG](https://github.com/run-llama/llama_index/blob/main/docs/examples/low_level/fusion_retriever.ipynb) so that I could deal with both text and table at the same time. ^-^

**Comment by logan-markewich** [comment]
I think there are definitely ways to do this in LlamaIndex right now, just a matter of making some tutorial for it :) 

I think ideally you would create your table nodes so that the summary is the node text, and the raw table is in the metadata.

```
from llama_index.schema import TextNode

node = TextNode(
  text="table summary", 
  metadata={"raw_table": "..."}, 
  excluded_llm_metadata_keys=["raw_table"], 
  excluded_embed_metadata_keys=["raw_table"]
)
```

Then, just use the metadata-replacement node postprocessor in your query engine

```
query_engine = RetrieverQueryEngine.from_args(
    retriever=retriever,
    node_postprocessors=[
        MetadataReplacementPostProcessor(target_metadata_key="raw_table")
    ],
)
```

This will replace the text of retrieved nodes with the specified key (if it exists) before sending to the LLM

**Comment by Lauorie** [comment]
> I think there are definitely ways to do this in LlamaIndex right now, just a matter of making some tutorial for it :)
> 
> I think ideally you would create your table nodes so that the summary is the node text, and the raw table is in the metadata.
> 
> ```
> from llama_index.schema import TextNode
> 
> node = TextNode(
>   text="table summary", 
>   metadata={"raw_table": "..."}, 
>   excluded_llm_metadata_keys=["raw_table"], 
>   excluded_embed_metadata_keys=["raw_table"]
> )
> ```
> 
> Then, just use the metadata-replacement node postprocessor in your query engine
> 
> ```
> query_engine = RetrieverQueryEngine.from_args(
>     retriever=retriever,
>     node_postprocessors=[
>         MetadataReplacementPostProcessor(target_metadata_key="raw_table")
>     ],
> )
> ```
> 
> This will replace the text of retrieved nodes with the specified key (if it exists) before sending to the LLM

Can I have the full script/ notebook please?

**Comment by logan-markewich** [comment]
Might have time later this week. That's more than enough to get anyone started though 👍

**Comment by Lauorie** [comment]
> Might have time later this week. That's more than enough to get anyone started though 👍

Hi,still waiting😃
