### ISSUE TITLE
[Question]: Merge storage_context

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#8885]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I build the index from the documents, then I can store all the 'data' in the storage_context. But if I use storage_context = StorageContext.from_defaults(persist_dir=save_index_dir), then I can only get the storage_context for each document individually.
In this case, how to merge the storage_context loaded from multiple documents into the same one?

**Comment by logan-markewich** [comment]
@SCUT-ChenBD it's not (easily) possible to merge storage contexts.

I would encourage using `index.insert()` functionality rather than creating an index for each new document
