### ISSUE TITLE
[Question]: Chat Engines don't support kwargs for chat methods?

### ISSUE THREAD

**Issue by OliverFarren** [run-llama/llama_index#8886]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

With the recent OpenAI update i'd like to be able use JSON output and based on the one [notebook](https://github.com/run-llama/llama_index/blob/29ef306ae0536de44840ca5acfdf93d84b9a560c/docs/examples/llm/openai_json_vs_function_calling.ipynb#L317) for this it seems like I can pass to my LLM `response_format={"type": "json_object"}`. 

But, i'm not using my LLM directly, instead i'm using one of the abstractions: The ContextChatEngine. Looking at the method signature for `chat` and `achat` neither seem to support **kwargs which means If I want to use this feature, I either need to make a custom chat engine and essentially copy and maintain the chat method, or no longer use this abstraction. 

My question is, is there a design reason that **kwargs are not passed in to these methods and subsequently propagated down into the llm's chat method? The [documentation](https://gpt-index.readthedocs.io/en/latest/module_guides/deploying/chat_engines/usage_pattern.html) is a little terse in this area

Ideally what I want is a change to the `achat` and `chat` methods from what is there currently:
``` python
    @trace_method("chat")
    def chat(
        self, message: str, chat_history: Optional[List[ChatMessage]] = None
    ) -> AgentChatResponse:
    ...
    chat_response = self._llm.chat(all_messages)
    ...
```

To:
``` python
    @trace_method("chat")
    def chat(
        self, message: str, chat_history: Optional[List[ChatMessage]] = None, **kwargs
    ) -> AgentChatResponse:
    ...
    chat_response = self._llm.chat(all_messages, **kwargs)
    ...
```

Is there a reason this wouldn't be a good idea? Happy to open a PR if not but seems like there'd have been a reason.

**Comment by logan-markewich** [comment]
@OliverFarren it seems like a fine idea to me. 

Tbh, I would also like to see something similar for query engines, but I think that's a much more complicated change 😅

**Comment by OliverFarren** [comment]
Hi, this is still an issue, the ContextChatEngine chat, achat, stream and astream don't support kwargs when they could.
