### ISSUE TITLE
[Question]: Two Questions, One Answer

### ISSUE THREAD

**Issue by jamessdixon** [run-llama/llama_index#8888]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I asked the same question on discord here:  https://discord.com/channels/1059199217496772688/1173654034641584249

Here is my base code:

model_url = "https://huggingface.co/TheBloke/Llama-2-13B-chat-GGUF/resolve/main/llama-2-13b-chat.Q4_0.gguf"
llm = LlamaCPP(model_url=model_url,temperature=0.1,max_new_tokens=256,context_window=3900,generate_kwargs={},model_kwargs={"n_gpu_layers": 1},verbose=True,)
PyMuPDFReader = download_loader("PyMuPDFReader")
loader = PyMuPDFReader()
pdfs = loader.load_data(file_path=Path('test_invoice.pdf'), metadata=False)
pdf = pdfs[0]
pdf_text = pdf.text
documents = [Document(text=pdf_text)]

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model,)
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
query_engine = index.as_query_engine()

When I run this I get the correct answer:
response = query_engine.query("Does it have an Invoice #?")

When I run this I get the correct answer:
response = query_engine.query("Does it have an Invoice Amount?")

When I run this, the first answer is correct and the second is always "Empty Response"
response = query_engine.query("Does it have an Invoice #?")
response = query_engine.query("Does it have an Invoice Amount?")

What am I doing wrong?
Thanks in advance

**Comment by nerdai** [comment]
@jamessdixon Do you mind printing out logs and sharing here what you see in the second query call?

Add to top of script:
```
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
```

**Comment by jamessdixon** [comment]
OK, here is addition to the new script

```
embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-small-en-v1.5")
service_context = ServiceContext.from_defaults(llm=llm,embed_model=embed_model,)
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
query_engine = index.as_query_engine()
response = query_engine.query("How much is the recomended amount?")
print(response)

#add per GitHib help
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
response = query_engine.query("what is the invoice number?")
print(response)

```

And here is the output

 Based on the provided invoice information, the recommended amount is $17,455.00.
DEBUG:llama_index.indices.utils:> Top 1 nodes:
> [Node 9f9a6056-1e71-43ec-9826-6129346576dd] [Similarity score:             0.594873] ABC/
Invoice
PRIN12345
DEF on behalf of HIJ
Date
6/26/2023
...
> Top 1 nodes:
> [Node 9f9a6056-1e71-43ec-9826-6129346576dd] [Similarity score:             0.594873]ABC/
Invoice
PRIN12345
DEF on behalf of HIJ
Date
6/26/2023
...
DEBUG:llama_index.llm_predictor.base:

Empty Response

**Comment by jamessdixon** [comment]
we noticed if we create an array of llms, it works up to a point.  Could the problem be in LLAMACPP?
