### ISSUE TITLE
[Bug]: LlamaCPP on CPU n_threads not working

### ISSUE THREAD

**Issue by pabl-o-ce** [run-llama/llama_index#8894]
### Bug Description

I'm trying to use CPU LlamaCPP

but whenever I add n_threads to use on limited number of threads it  wont work keep using all threads.

how can this been supported better or maybe I'm doing something wrong

### Version

^0.8.55

### Steps to Reproduce

```python
llm = LlamaCPP(
      model_path=f"/mnt/v1/ai-models/{model}",
      temperature=temperature,
      max_new_tokens=max_new_tokens,
      context_window=context_window,
      generate_kwargs={
        "top_k": top_k,
        "top_p": top_p,
        "repeat_penalty": repeat_penalty
      },
      model_kwargs={
        "n_threads": 4
      },
      messages_to_prompt=messages_to_prompt,
      completion_to_prompt=completion_to_prompt,
      verbose=True,
    )
```

**Comment by pabl-o-ce** [comment]
thanks bot haha I update the version also and improve the consumption of the server in a better way! i don't know if this should be okay to leave it open to the maintainers can determine is worth to be able to select  `n_threads`

**Comment by NeilBotelho** [comment]
I think you've passed it in wrong. Don't pass model kwargs as a dictionary. Just pass in n_threads=4 as an argument. That should fix it
