### ISSUE TITLE
[Question]: How to retrieve only?

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#8901]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

In a Graph Index with a tree index at the bottom and a list index at the top, how can I only return the search results without conducting LLM questions and answers?

**Comment by logan-markewich** [comment]
Don't use a graph (it's quite unmaintained at the moment lol)

If you have a list index on top, use something like a fusion retriever. 
https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#simple-fusion-retriever

Or just use `index.as_retriever()` for each of your sub indexes.

**Comment by SCUT-ChenBD** [comment]
@logan-markewich Thank you for your quick reply, very useful to me~
