### ISSUE TITLE
[Question]: Why doesn't response metadata capture the information always?

### ISSUE THREAD

**Issue by ram510** [run-llama/llama_index#8904]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have used the basic chunking and loading the data to Postgres database with the code from the example - https://gpt-index.readthedocs.io/en/v0.8.47/examples/low_level/oss_ingestion_retrieval.html

Here is the the code
```
from llama_index.schema import TextNode

nodes = []
for idx, text_chunk in enumerate(text_chunks):
    node = TextNode(
        text=text_chunk,
    )
    src_doc = documents[doc_idxs[idx]]
    node.metadata = src_doc.metadata
    nodes.append(node)
```
```
text_chunks = []
# maintain relationship with source doc index, to help inject doc metadata in (3)
doc_idxs = []
for doc_idx, doc in enumerate(documents):
    cur_text_chunks = text_splitter.split_text(doc.text)
    text_chunks.extend(cur_text_chunks)
    doc_idxs.extend([doc_idx] * len(cur_text_chunks))
```
`for node in nodes:
    node_embedding = embed_model.get_text_embedding(
        node.get_content(metadata_mode="all")
    )
    node.embedding = node_embedding
vector_store.add(nodes)`
Here the issue I am facing, after the retrieval of the context from the database, it is not returning the metadata or the documents name it extracted the information from 
response_1.sourcenode[0].metadata =
[NodeWithScore(node=TextNode(id_='0fb55059-e6cf-403e-89f0-3a5560437afb', embedding=None, metadata={'file_name': 'covid census and mortality protocol v2.docx'},....] // has document name

response_2.sourcenode[0].metadata = [NodeWithScore(node=TextNode(id_='be4ac130-a4eb-47b6-8cac-e9c652b109ba', embedding=None, metadata={},] // no document name

both the response_1 and response_2 - contexts are chunked and stored in Postgres in with same logic
hoverever metadata is being populated for smaller datasets and it is not happening for larger datasets
is there anything I am missing?

**Comment by logan-markewich** [comment]
@ram510 I am confused maybe, I don't see you setting any metadata in your nodes in the provided code samples?
