### ISSUE TITLE
[Bug]: Cannot import Nodewithscore from llama_index.data_structs

### ISSUE THREAD

**Issue by sarathsurpur** [run-llama/llama_index#8909]
### Bug Description

when importing the below code getting the below error
`from llama_index.data_structs import NodeWithScore`

Error: ImportError: cannot import name 'NodeWithScore' from 'llama_index.data_structs'

### Version

Version: 0.8.64.post1

### Steps to Reproduce

Import the above statement in specified version

**Comment by OliverFarren** [comment]
Would this work?
```
from llama_index.schema import NodeWithScore
```

**Comment by logan-markewich** [comment]
@sarathsurpur yea that import is extremely outdated. The above suggestion by @OliverFarren is correct (thanks!)
