### ISSUE TITLE
[Question]: FnRetrieverOpenAIAgent support non-OpenAI agent？

### ISSUE THREAD

**Issue by RangRun** [run-llama/llama_index#8913]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

FnRetrieverOpenAIAgent support non-OpenAI agent？
I want to uses object retriever module to retrieve non-openAI  agent, what should I do?

**Comment by sapekshsuman** [comment]
The above solution doesn't resolve the problem. To be more specific I am using the Azure OpenAI key and I set the set_global_service_context but still get connection error whereas the base_query_retreiver works in the multi_document_agents_v1 example
