### ISSUE TITLE
[Bug]: PandasQueryEngine with llama ccp bug unexpected indent (<unknown>, line 1)

### ISSUE THREAD

**Issue by giancarloerra** [run-llama/llama_index#8919]
### Bug Description

When using PandasQueryEngine with Llama CCP, whatever prompt I always get the same error.
Example code below:
`from llama_index.query_engine import PandasQueryEngine
query_engine = PandasQueryEngine(df=df, verbose=True, llm=llm, service_context=service_context)
response = query_engine.query(
    "What is the size of this dataframe?",
)
display(response)`

and error:

`Llama.generate: prefix-match hit

> Pandas Instructions:
```
  To convert the input query "What is the size of this dataframe?" into executable Python code using Pandas, we can use the following approach:
1. Extract the relevant information from the `df` dataframe. In this case, we need to know the number of rows and columns in the dataframe.
2. Use the `shape` attribute of the dataframe to get the number of rows and columns. The shape attribute is a tuple containing the number of rows and columns in the dataframe.
3. Convert the number of rows and columns into a Python expression that can be evaluated using the `eval()` function. We can use the following formula: `len(df.index) * len(df.columns)`.
Here's the code:
```
# Extract relevant information from df dataframe
rows = len(df.index)
cols = len(df.columns)

# Convert to Python expression for evaluation using eval() function
size = rows * cols

# Print the result as a solution to the query
print("The size of this dataframe is:", size)
```
Now, let's break down each line of the code:
1. `len(df.index)` and `len
```
> Pandas Output: There was an error running the output as Python code. Error message: unexpected indent (<unknown>, line 1)

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/llama_index/query_engine/pandas_query_engine.py", line 60, in default_output_processor
    tree = ast.parse(output)
  File "/usr/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    To convert the input query "What is the size of this dataframe?" into executable Python code using Pandas, we can use the following approach:
IndentationError: unexpected indent

Response(response='There was an error running the output as Python code. Error message: unexpected indent (<unknown>, line 1)', source_nodes=[], metadata={'pandas_instruction_str': '  To convert the input query "What is the size of this dataframe?" into executable Python code using Pandas, we can use the following approach:\n1. Extract the relevant information from the `df` dataframe. In this case, we need to know the number of rows and columns in the dataframe.\n2. Use the `shape` attribute of the dataframe to get the number of rows and columns. The shape attribute is a tuple containing the number of rows and columns in the dataframe.\n3. Convert the number of rows and columns into a Python expression that can be evaluated using the `eval()` function. We can use the following formula: `len(df.index) * len(df.columns)`.\nHere\'s the code:\n```\n# Extract relevant information from df dataframe\nrows = len(df.index)\ncols = len(df.columns)\n\n# Convert to Python expression for evaluation using eval() function\nsize = rows * cols\n\n# Print the result as a solution to the query\nprint("The size of this dataframe is:", size)\n```\nNow, let\'s break down each line of the code:\n1. `len(df.index)` and `len'})`

Whatever I ask, I always receive the same error:

`There was an error running the output as Python code. Error message: unexpected indent (<unknown>, line 1)`

### Version

0.2.18

### Steps to Reproduce

Using PandasQueryEngine on an dataframe created from a CSV.

**Comment by logan-markewich** [comment]
@giancarloerra the LLM did not follow instructions, and we could not easily parse the actual pandas code out of the response

In general, open-source LLMs are not really well-suited to this task. Llama2 is especially verbose. I would try using zephyr-beta maybe

**Comment by giancarloerra** [comment]
> @giancarloerra the LLM did not follow instructions, and we could not easily parse the actual pandas code out of the response
> 
> In general, open-source LLMs are not really well-suited to this task. Llama2 is especially verbose. I would try using zephyr-beta maybe

Thanks, is it something I can try fixing with a different output_processor?
