### ISSUE TITLE
[Bug]: why use async with fusion  + FastAPI is so slow

### ISSUE THREAD

**Issue by batman-do** [run-llama/llama_index#8921]
### Bug Description

why  i use fusion + fastapi follow up by document in llama-index but response very slow

my code:
`import asyncio
        from enum import Enum
        from pathlib import Path
        from typing import Dict, List, Optional, Tuple
        
        from llama_index import (
            SimpleDirectoryReader,
            VectorStoreIndex,
            download_loader,
        )
        from llama_index.async_utils import run_async_tasks
        from llama_index.constants import DEFAULT_SIMILARITY_TOP_K
        from llama_index.indices.query.schema import QueryBundle
        from llama_index.llms.base import ChatMessage, MessageRole
        from llama_index.llms.utils import LLMType, resolve_llm
        from llama_index.prompts.base import ChatPromptTemplate
        from llama_index.query_engine import RetrieverQueryEngine
        from llama_index.retrievers import BaseRetriever
        from llama_index.schema import NodeWithScore
        
        QUERY_GEN_PROMPT = (
            "You are a helpful assistant that generates multiple search queries based on a "
            "single input query in Vietnamese of Owen men's fashion brand. Generate {num_queries} search queries, one on each line, "
            "related to the following input query:\n"
            "Query: {query}\n"
            "Queries:\n"
        )
        
        TEXT_QA_SYSTEM_PROMPT = ChatMessage(
            content=(
                "You are an expert Q&A system of Owen men's fashion brand that is trusted around the world.\n"
                "Always answer the query in Vietnamese using the provided context information, "
                "Your answer in Vietnamese must be full of information, not contradict the following context.\n"
            ),
            role=MessageRole.SYSTEM,
        )
        
        TEXT_QA_PROMPT_TMPL_MSGS = [
            TEXT_QA_SYSTEM_PROMPT,
            ChatMessage(
                content=(
                    "Context information is below.\n"
                    "---------------------\n"
                    "{context_str}\n"
                    "---------------------\n"
                    "Given the context information and not prior knowledge, "
                    "answer the query.\n"
                    "Some rules to follow:\n"
                    "1. Never directly reference the given context in your answer.\n"
                    "2. Avoid statements like 'Based on the context, ...' or "
                    "'The context information ...' or anything along "
                    "those lines."
                    "3. Answer MUST in Vietnamese language."
                    "4. DON'T reference to SOURCE data (data/...)."
                    "\n\n"
                    "Question: {query_str}\n"
                    "Answer: "
                ),
                role=MessageRole.USER,
            ),
        ]
        
        
        def index_documents(service_contenxt, path):
            UnstructuredReader = download_loader("UnstructuredReader")
            dir_reader = SimpleDirectoryReader(
                Path(path),
                file_extractor={
                    ".txt": UnstructuredReader(),
                },
            )
            documents = dir_reader.load_data()
            index = VectorStoreIndex.from_documents(
                documents, service_contenxt=service_contenxt, show_progress=True
            )
            return index
        
        
        class FUSION_MODES(str, Enum):
            RECIPROCAL_RANK = "reciprocal_rerank"  
            SIMPLE = "simple"  
        
        
        class QueryFusionRetriever(BaseRetriever):
            def __init__(
                self,
                retrievers: List[BaseRetriever],
                llm: Optional[LLMType] = "default",
                query_gen_prompt: Optional[str] = QUERY_GEN_PROMPT,
                mode: FUSION_MODES = FUSION_MODES.RECIPROCAL_RANK,
                similarity_top_k: int = DEFAULT_SIMILARITY_TOP_K,
                num_queries: int = 4,
                use_async: bool = True,
                verbose: bool = False,
            ) -> None:
                self.num_queries = num_queries
                self.query_gen_prompt = query_gen_prompt
                self.similarity_top_k = similarity_top_k
                self.mode = mode
                self.use_async = use_async
                self.verbose = verbose
                self._retrievers = retrievers
                self._llm = resolve_llm(llm)
        
            def _get_queries(self, original_query: str) -> List[str]:
                prompt_str = self.query_gen_prompt.format(
                    num_queries=self.num_queries - 1,
                    query=original_query,
                )
                response = self._llm.complete(prompt_str)
        
                # assume LLM proper put each query on a newline
                queries = response.text.split("\n")
                if self.verbose:
                    queries_str = "\n".join(queries)
                    print(f"Generated queries:\n{queries_str}")
                return response.text.split("\n")
        
            def _reciprocal_rerank_fusion(
                self, results: Dict[Tuple[str, int], List[NodeWithScore]]
            ) -> List[NodeWithScore]:
                """Apply reciprocal rank fusion.
        
                The original paper uses k=60 for best results:
                https://plg.uwaterloo.ca/~gvcormac/cormacksigir09-rrf.pdf
                """
                k = 60.0  # `k` is a parameter used to control the impact of outlier rankings.
                fused_scores = {}
                text_to_node = {}
        
                # compute reciprocal rank scores
                for nodes_with_scores in results.values():
                    for rank, node_with_score in enumerate(
                        sorted(nodes_with_scores, key=lambda x: x.score or 0.0, reverse=True)
                    ):
                        text = node_with_score.node.get_content()
                        text_to_node[text] = node_with_score
                        if text not in fused_scores:
                            fused_scores[text] = 0.0
                        fused_scores[text] += 1.0 / (rank + k)
        
                # sort results
                reranked_results = dict(
                    sorted(fused_scores.items(), key=lambda x: x[1], reverse=True)
                )
        
                # adjust node scores
                reranked_nodes: List[NodeWithScore] = []
                for text, score in reranked_results.items():
                    reranked_nodes.append(text_to_node[text])
                    reranked_nodes[-1].score = score
        
                return reranked_nodes
        
            def _simple_fusion(
                self, results: Dict[Tuple[str, int], List[NodeWithScore]]
            ) -> List[NodeWithScore]:
                """Apply simple fusion."""
                # Use a dict to de-duplicate nodes
                all_nodes: Dict[str, NodeWithScore] = {}
                for nodes_with_scores in results.values():
                    for node_with_score in nodes_with_scores:
                        text = node_with_score.node.get_content()
                        all_nodes[text] = node_with_score
        
                return sorted(all_nodes.values(), key=lambda x: x.score or 0.0, reverse=True)
        
            def _run_nested_async_queries(
                self, queries: List[str]
            ) -> Dict[Tuple[str, int], List[NodeWithScore]]:
                tasks, task_queries = [], []
                for query in queries:
                    for i, retriever in enumerate(self._retrievers):
                        tasks.append(retriever.aretrieve(query))
                        task_queries.append(query)
        
                task_results = run_async_tasks(tasks)
        
                results = {}
                for i, (query, query_result) in enumerate(zip(task_queries, task_results)):
                    results[(query, i)] = query_result
        
                return results
        
            async def _run_async_queries(
                self, queries: List[str]
            ) -> Dict[Tuple[str, int], List[NodeWithScore]]:
                tasks, task_queries = [], []
                for query in queries:
                    for i, retriever in enumerate(self._retrievers):
                        tasks.append(retriever.aretrieve(query))
                        task_queries.append(query)
        
                task_results = await asyncio.gather(*tasks)
        
                results = {}
                for i, (query, query_result) in enumerate(zip(task_queries, task_results)):
                    results[(query, i)] = query_result
        
                return results
        
            def _run_sync_queries(
                self, queries: List[str]
            ) -> Dict[Tuple[str, int], List[NodeWithScore]]:
                results = {}
                for query in queries:
                    for i, retriever in enumerate(self._retrievers):
                        results[(query, i)] = retriever.retrieve(query)
        
                return results
        
            def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
                if self.num_queries > 1:
                    queries = self._get_queries(query_bundle.query_str)
                else:
                    queries = [query_bundle.query_str]
        
                if self.use_async:
                    results = self._run_nested_async_queries(queries)
                else:
                    results = self._run_sync_queries(queries)
        
                if self.mode == FUSION_MODES.RECIPROCAL_RANK:
                    return self._reciprocal_rerank_fusion(results)[: self.similarity_top_k]
                elif self.mode == FUSION_MODES.SIMPLE:
                    return self._simple_fusion(results)[: self.similarity_top_k]
                else:
                    raise ValueError(f"Invalid fusion mode: {self.mode}")
        
            async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
                if self.num_queries > 1:
                    queries = self._get_queries(query_bundle.query_str)
                else:
                    queries = [query_bundle.query_str]
        
                results = await self._run_async_queries(queries)
        
                if self.mode == FUSION_MODES.RECIPROCAL_RANK:
                    return self._reciprocal_rerank_fusion(results)[: self.similarity_top_k]
                elif self.mode == FUSION_MODES.SIMPLE:
                    return self._simple_fusion(results)[: self.similarity_top_k]
                else:
                    raise ValueError(f"Invalid fusion mode: {self.mode}")
        
        
        def answer(query, retriever, post_procesor):
            prompt = ChatPromptTemplate(message_templates=TEXT_QA_PROMPT_TMPL_MSGS)
            if post_procesor is not None:
                query_engine = RetrieverQueryEngine.from_args(
                    retriever=retriever,
                    node_postprocessors=[post_procesor],
                    text_qa_template=prompt,
                )
            else:
                query_engine = RetrieverQueryEngine.from_args(
                    retriever=retriever,
                    text_qa_template=prompt,
                )
            response = query_engine.aquery(query)
            return response

`

api.py
 `
    import os
    
    import openai
    import utils
    import uvicorn
    from fastapi import FastAPI, Response, Request
    from llama_index import ServiceContext
    from llama_index.embeddings import OpenAIEmbedding
    from llama_index.llms import OpenAI
    from llama_index.response.pprint_utils import pprint_response
    from llama_index.retrievers import BM25Retriever
    from pydantic import BaseModel
    
    
    class QAInput(BaseModel):
        question: str
    
    
    app = FastAPI()
    
    
    @app.middleware("http")
    async def cors_handler(request: Request, call_next):
        response: Response = await call_next(request)
        response.headers["Access-Control-Allow-Credentials"] = "true"
        response.headers["Access-Control-Allow-Origin"] = "*"
        response.headers["Access-Control-Allow-Methods"] = "*"
        response.headers["Access-Control-Allow-Headers"] = "*"
        return response
    
    
    @app.post("/QA_system/generate_answer")
    async def answer(item: QAInput):
        retriever = utils.QueryFusionRetriever(
            retrievers=[vector_retriever, bm25_retriever],
            llm=llm,
            similarity_top_k=5,
            verbose=True,
            num_queries=3,
            use_async=True,
        )
        response = await utils.answer(
            query=item.question,
            retriever=retriever,
            post_procesor=None,
        )
        pprint_response(response, show_source=True)
        ai_message = response.response
        return {"data": ai_message}
    
    
    if __name__ == "__main__":
        import nest_asyncio
    
        nest_asyncio.apply()
    
        openai.api_key = os.environ["OPENAI_API_KEY"]
        llm = OpenAI(
            model="gpt-4",
            max_tokens=1024,
            temperature=0,
            max_retries=1,
            request_timeout=50,
        )
        embed_model = OpenAIEmbedding()
    
        # service context
        service_contenxt = ServiceContext.from_defaults(
            chunk_size=1024, embed_model=embed_model, llm_predictor=llm, chunk_overlap=128
        )
        index_documents = utils.index_documents(service_contenxt, "data/")
    
        vector_retriever = index_documents.as_retriever(similarity_top_k=5)
    
        bm25_retriever = BM25Retriever.from_defaults(
            docstore=index_documents.docstore, similarity_top_k=5
        )
    
        uvicorn.run(app, host=..., port=...)
`

### Version

0.8.69.post2

### Steps to Reproduce

![image](https://github.com/run-llama/llama_index/assets/77484083/19b5762c-46ee-4617-9536-ad03ed1445bd)

**Comment by logan-markewich** [comment]
@batman-do do you have a lot of documents? I know bm25 can be quite slow once you add a lot of data
