### ISSUE TITLE
[Question]: About QueryFusionRetriever

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#8922]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If I have five vector indexes, how can I retrieve the topk relevant texts among these five? When retrieving using **QueryFusionRetriever**, the relevant content will be returned evenly from each vector index.

**Comment by SCUT-ChenBD** [comment]
In the above example, what I hope to get is topk texts in five documents, rather than averagely getting topk texts from each document.

**Comment by dolwinf** [comment]
Did the above work? I'm on the latest version of llama index and not able to import QueryFusionRetriever. I looked through the source code from VSCode and this github repo and seems like fusion_retriever is missing.
