### ISSUE TITLE
[Question]: How to combine multiple vector indexes into one vector index?

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#8923]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to combine multiple vector indexes into one vector index?

**Comment by Deepansharora27** [comment]
Hi, Is MultiModalVectorIndex present as a Class in LlamaIndex. I did not seem to find anything about it in Documentation ?

**Comment by rk-spirinova** [comment]
> _🤖_
> 
> To combine multiple vector indexes into one vector index, you can use the `GPTListIndex` or the `MultiModalVectorStoreIndex` class depending on your specific use case.
> 
> If you have two separate indexes and you want to merge them, you can use the `GPTListIndex`. Here is a code snippet:
> 
> ```python
> from llama_index import GPTListIndex
> 
> index = GPTListIndex([index1, index2])
> ```
> 
> After merging the indices, you can build a graph and save it to disk:
> 
> ```python
> from llama_index import ComposableGraph
> 
> all_indices = [index1, index2, index3, index4]
> index_summaries=[index1_summary, index2_summary, index3_summary, index4_summary]
> 
> graph = ComposableGraph.from_indices(GPTTreeIndex, all_indices, index_summaries=index_summaries)    
> graph.save_to_disk("graph.json")
> ```
> 
> To load the merged index from the disk, you can use:
> 
> ```python
> index = ComposableGraph.load_from_disk("graph.json")
> ```
> 
> If you have two documents and you want to add them to the same index, you can use the `MultiModalVectorStoreIndex` class. Here is a simplified example:
> 
> ```python
> # Assuming `node1` and `node2` are your nodes
> nodes = [node1, node2]
> 
> # Create an instance of your index
> index = MultiModalVectorStoreIndex(nodes=nodes)
> 
> # Add the nodes to the index
> index._add_nodes_to_index(index.index_struct, nodes)
> ```
> 
> In this example, the `_add_nodes_to_index` method is used to add nodes to the index. For each node, the method checks if it's an `ImageNode` or a text node, then it embeds the nodes accordingly. After all nodes have been embedded, the method adds the nodes to the vector store and updates the index structure in the index store.
> 
> Please note that the actual structure of the nodes (i.e., `node1` and `node2` in the example) depends on the schema of your index. You can create a node for each document using the `BaseNode` class or one of its subclasses.
> 
> You can find more information about this in the following solved issues:
> 
> * [[Question]: Merge vectore index](https://github.com/run-llama/llama_index/issues/8883)
> * [[Question]: Merging Vector Indexes from Multiple Milvus Databases](https://github.com/run-llama/llama_index/issues/6963)
> * [How can merge multi index file](https://github.com/run-llama/llama_index/issues/1063)
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> ## Sources
> * [[Question]: Merge vectore index](https://github.com/run-llama/llama_index/issues/8883)
> * [[Question]: Merging Vector Indexes from Multiple Milvus Databases](https://github.com/run-llama/llama_index/issues/6963)
> * [How can merge multi index file](https://github.com/run-llama/llama_index/issues/1063)
> * [llama_index/indices/multi_modal/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/indices/multi_modal/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

What is index_summaries here. What if i only have the indexes?
