### ISSUE TITLE
Impossible to use any other LLM than openai for querying SQL

### ISSUE THREAD

**Issue by tekntrash** [run-llama/llama_index#8925]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

It is impossible to use any other LLM than OpenAI for querying SQL

Even though the manual says you can use ollama to load other LLMs such as Llama 2 and use the following commands to use it:
_llm = Ollama(model="llama2")
service_context = ServiceContext.from_defaults(llm=llm)_

As soon it finds and openai.api_key it just uses openAI and disregards the above. Also, it downloads the BAAI--bge-small-en model for no reason, as it cannot use it if we remove the open ai key, as it throws the message:
_Exception ignored in: <function _LlamaContext.__del__ at 0x7f4d507ddaf0>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/llama_cpp/llama.py", line 422, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaModel.__del__ at 0x7f4d507dbb80>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/llama_cpp/llama.py", line 240, in __del__
TypeError: 'NoneType' object is not callable
Exception ignored in: <function _LlamaBatch.__del__ at 0x7f4d507dfe50>
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.9/site-packages/llama_cpp/llama.py", line 670, in __del__
TypeError: 'NoneType' object is not callable_

It looks like this is an incomplete product

**Comment by tekntrash** [comment]
You did not understand. If I remove the open ai key it downloads its own llama even though I said to use the LLM loaded from ollama, and even then it does not work either as it throws the error message I put in my post

**Comment by logan-markewich** [comment]
I believe we solved this on discord, closing for now.

For reference, the solution is to pass the service context into the index/query engine you are using, as well as setting or disabling the embedding model

```
service_context = ServiceContext.from_defaults(llm=llm, embed_model="local:BAAI/bge-base-en-v1.5")
query_engine = NLSQLTableQueryEngine(sql_database=sql_database, tables=["users",], service_context=service_context)
```

**Comment by giusca** [comment]
For anybody struggling with llamaindex defaulting to OpenAI despite the Settings.llm value, checkout:

https://docs.llamaindex.ai/en/stable/api_reference/llms/openai_like/
https://www.dataleadsfuture.com/how-to-connect-llamaindex-with-private-llm-api-deployments/
