### ISSUE TITLE
[Feature Request]: GCP Matching Engine Support

### ISSUE THREAD

**Issue by tambulkar** [run-llama/llama_index#8931]
### Feature Description

I would like to add  support for GCP Matching Engine as a vector store.

### Reason

I don't see GCP listed in https://github.com/run-llama/llama_index/tree/main/llama_index/vector_stores . We would have to write a custom vector store, but I feel like it could be include in the repo.

### Value of Feature

Allow Google Cloud Users to easily integrate with Llamaindex.

**Comment by logan-markewich** [comment]
@tambulkar does GCP have it's own vectordb? Can you link some docs if so?

**Comment by tambulkar** [comment]
Yeah its part of their vertex ai product:
https://cloud.google.com/vertex-ai/docs/vector-search/overview
https://cloud.google.com/vertex-ai/docs/vector-search/create-manage-index
https://cloud.google.com/vertex-ai/docs/vector-search/query-index-public-endpoint

**Comment by nick-youngblut** [comment]
@tambulkar does GCP Matching Engine support upserting? I don't see any docs on iteratively updating the database, or is the database iteratively updated as new docs are added to the `contentsDeltaUri` location?

**Comment by tambulkar** [comment]
I think it requires an update request: https://cloud.google.com/vertex-ai/docs/vector-search/update-rebuild-index
