### ISSUE TITLE
[Bug][llama_index-0.9.1]: ValueError: "AzureOpenAI" object has no field "_http_client"

### ISSUE THREAD

**Issue by tonydeep** [run-llama/llama_index#8944]
### Bug Description

ValueError: "AzureOpenAI" object has no field "_http_client"

### Version

0.9.1

### Steps to Reproduce

Line 96 in ../site-packages/llama_index/llms/azure_openai.py:96).

`# Use the custom httpx client if provided.`
`# Otherwise the value will be None.`
`self._http_client = http_client`

**Comment by sapekshsuman** [comment]
I am also facing the same issue

**Comment by andrePankraz** [comment]
Same - yes i can copy class and adapt, but it's not ideal and a bit strange for this very popular method for OpenAI model access. Automatic tests?

**Comment by logan-markewich** [comment]
I think this is a pydantic v1 vs v2 issue -- all our tests are using v2 now

**Comment by tonydeep** [comment]
Fixed in #8955 .
Thanks.

**Comment by Arokamal** [comment]
Is the issue fixed for AzureOpenai?

**Comment by logan-markewich** [comment]
@Arokamal yes you can pass in http_client in the latest version of llama index
