### ISSUE TITLE
[Question]: How to get the raw SQL queries generated when using SubQuery Engine?

### ISSUE THREAD

**Issue by sumitsahay68** [run-llama/llama_index#8953]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have built Natural Language to SQL-based ChatBot for a dataset I'm having by utilizing LlamaIndex's `SubQuestionQueryEngine`. I'm able to get the response to my complex queries as well. However, even after analyzing the run logs and extracting from the response object, I'm NOT able to find the **raw SQL query** that was run against my table.

I have tried setting `synthesize_response=False` while creating the `SQLTableRetrieverQueryEngine`, however, it is throwing a key error if I try to extract the query from metadata as suggested in this discord [thread](https://discord.com/channels/1059199217496772688/1131630431398281226/1131630575753633912). 

Here's my code for reference:

```
# Create an instance of the SQLTableRetrieverQueryEngine class using the SQLDatabase object and object index
sql_query_engine = SQLTableRetrieverQueryEngine(sql_database, 
                                                obj_index.as_retriever(similarity_top_k=1),
                                                synthesize_response=False
                                                )

# Define a list of query engine tools
query_engine_tools = [
    QueryEngineTool(
        query_engine=sql_query_engine,
        metadata=ToolMetadata(
            name="Customer Loan Database",
            description="Database containing the Loan Application Data table"
        )
    )
]

# Create a subquery engine using the query engine tools, service context, and enabling asynchronous execution
subquery_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context,
    use_async=True
)
```
Please help me print the individual SQL queries too. Thanks!

**Comment by CruddyInstance** [comment]
Hello sumit did you find answer on how to do this?
