### ISSUE TITLE
[Bug]: OpensearchVectorStore is not BasePydanticVectorStore

### ISSUE THREAD

**Issue by andrePankraz** [run-llama/llama_index#8954]
### Bug Description

According to blog this should work:

`vector_store = QdrantVectorStore(client=client, collection_name="test_store")
pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=25, chunk_overlap=0),
        TitleExtractor(),
        OpenAIEmbedding(),
    ],
    cache=IngestionCache(cache=RedisCache(), collection="test_cache"),
    vector_store=vector_store,
)
pipeline.run(documents=[Document.example()])`

This doesn't work with OpensearchVectorStore, because it's still a normal VectorStore and not refactored into BasePydanticVectorStore

### Version

0.9.1

### Steps to Reproduce

Just try a pipeline with an OpensearchVectorStore

**Comment by andrePankraz** [comment]
I think, this whole class / abstraction is quite unusable.
The delete function is also not working at all and all kind of OpenSearch client exceptions leak through.
This seems totally wrong:

OpensearchVectorClient
    def delete_doc_id(self, doc_id: str) -> None:
        self._os_client.delete(index=self._index, id=doc_id)

It tries to delete by ID, which is not document ID, but the generated node chunk UUID.
It must delete "by query" with "doc_id".

Many architectures already contain an OpenSearch stack - so it would be nice to really support this Software as good as other more exotic stuff...    Plz check the paper "Lucene is all you need" for vector indices.

**Comment by blade2005** [comment]
well crap, encountered this today. this breaks my plans.

**Comment by blade2005** [comment]
@dosu-bot What other classes inherit from BasePydanticVectorStore that are able to run in AWS and locally?

**Comment by collindutter** [comment]
@andrePankraz the behavior you described seems to be related to the changes made in [this PR](https://github.com/run-llama/llama_index/pull/10043). Since `_id` is auto-generated, llama index doesn't properly track which document to delete.

> It must delete "by query" with "doc_id".

Is delete by query supported on AOSS?

**Comment by blade2005** [comment]
Yes it is. I'm using that on another project

**Comment by collindutter** [comment]
@blade2005 are you able to share any information on how you're using `_delete_by_query`? I've not been able to get it working, and am facing the same issues described [here](https://repost.aws/questions/QUzT6LZt1qRGKNyPJQRV20PQ/does-opensearch-serverless-support-delete-by-query).

**Comment by blade2005** [comment]
```
from opensearchpy import OpenSearch

host: str
port: str
client = OpenSearch(
        hosts=[{"host": host, "port": int(port)}],
        http_auth=auth
    )
index_name: str
url: str # s3 bucket url
response = client.delete_by_query(
    index=index_name, body={"query": {"match": {"url": url}}}
)
```

**Comment by sumeshmr** [comment]
Hello,

I am also planning to use IngestionPipeline with AWS OpenSearch Serverless(AOSS) which is not compatible at the moment. Any plan to implement this?

**Comment by brycecf** [comment]
@sumeshmr With the latest refactoring announced for v0.10, we seem to be officially on our own for supporting the "integrations" now.

**Comment by sumeshmr** [comment]
@dosu-bot I tried the new version v0.10, still IngestionPipeline is not compatible with opensearch
