### ISSUE TITLE
[Question]: Changing the host / baseURL

### ISSUE THREAD

**Issue by Danielg212** [run-llama/llama_index#8958]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can I change the host to our internal gpt proxy server? I don't see this option in the class.
What am I missing?

**Comment by Danielg212** [comment]
Thanks Dosu, but I am using Typescript and I can't find in the docs.

**Comment by Danielg212** [comment]
Thanks @dosu-bot., but I am using Typescript (Node.js) and I can't find it in the docs.

**Comment by logan-markewich** [comment]
Please open an issue on the TS package @Danielg212 

Looking at the source code, I'm guessing the base_url is part of the client options object from openai 

https://github.com/run-llama/LlamaIndexTS/blob/b64716d3f7e41e0b8db7421b7150cafd13026843/packages/core/src/llm/openai.ts#L13

**Comment by zouweidong91** [comment]
os.environ['OPENAI_API_KEY'] = "sk-xxxxxx"
os.environ['OPENAI_API_BASE'] = "https://xxxxxx/v1"
