### ISSUE TITLE
[Bug]: Pydantic compatibility layer is not used everywhere in the codebase

### ISSUE THREAD

**Issue by martinkozle** [run-llama/llama_index#8959]
### Bug Description

If I understand correctly the compatibility bridge `from llama_index.bridge.pydantic import ...` should be used everywhere in the code for Pydantic 2 compatibility, but there are 8 places in the repository where `from pydantic import ...` is used. This causes some parts of the library to not work at all with Pydantic 2. One such case that I came across was using `CustomQueryEngine`.
I am aware that according to #8221 LlamaIndex will fully migrate to Pydantic v2 soon, but this should be temporarily fixed in the meantime.

### Version

0.9.1

### Steps to Reproduce

```console
$ grep -r --exclude='*' --include='*.py' --exclude='bridge/pydantic.py' '^from pydantic' .
./tests/indices/response/test_tree_summarize.py:from pydantic import BaseModel
./llama_index/param_tuner/base.py:from pydantic import BaseModel, Field
./llama_index/evaluation/dataset_generation.py:from pydantic import BaseModel, Field
./llama_index/evaluation/retrieval/metrics_base.py:from pydantic import BaseModel, Field
./llama_index/query_engine/custom.py:from pydantic import BaseModel
./llama_index/node_parser/relational/unstructured_element.py:from pydantic import BaseModel, ValidationError
./llama_index/prompts/base.py:from pydantic import Field
./llama_index/finetuning/rerankers/dataset_gen.py:from pydantic import BaseMode
```

**Comment by logan-markewich** [comment]
@martinkozle yea it sneaks in sometimes. Feel free to make a PR, otherwise I can fix it at some point today
