### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShyamFaguna** [run-llama/llama_index#8974]
### Bug Description

Hi,
I'm having trouble importing the LangchainEmbedding, ServiceContext classes from the llama_index package. I've installed the package using pip, but I'm getting an ImportError when trying to import the classes, it was working fine till yesterday. Is there any known issue or workaround for this problem? I've followed the documentation, but I can't seem to resolve the ImportError.

Used :
pip install llama-index
from llama_index import LangchainEmbedding, ServiceContext

Error:
ImportError                               Traceback (most recent call last)
<ipython-input-12-cf78bfce5182> in <cell line: 3>()
      1 import torch
      2 from langchain.embeddings.huggingface import HuggingFaceEmbeddings
----> 3 from llama_index import LangchainEmbedding, ServiceContext
      4 from llama_index.llms import HuggingFaceLLM
      5 

ImportError: cannot import name 'LangchainEmbedding' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

### Version

0.9.2

### Steps to Reproduce

pip install llama-index
from llama_index import LangchainEmbedding, ServiceContext

### Relevant Logs/Tracbacks

```shell
ImportError                               Traceback (most recent call last)
<ipython-input-12-cf78bfce5182> in <cell line: 3>()
      1 import torch
      2 from langchain.embeddings.huggingface import HuggingFaceEmbeddings
----> 3 from llama_index import LangchainEmbedding, ServiceContext
      4 from llama_index.llms import HuggingFaceLLM
      5 

ImportError: cannot import name 'LangchainEmbedding' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.
```

**Comment by logan-markewich** [comment]
@ShyamFaguna we have moved some minor imports to be a) clearer about where imports are coming from and b) reduce the bloat in the root `__init__.py` file

The bot has listed the correct import, but it could also be even shorter

`from llama_index.embeddings import LangchainEmbedding`
