### ISSUE TITLE
[Bug]: OpenAI agent call gives API Connection Error when connecting with AzureOpenAI key

### ISSUE THREAD

**Issue by sapekshsuman** [run-llama/llama_index#8975]
### Bug Description

I am trying to run the Multi Document Agent example provided in here using Azure OpenAI key - https://docs.llamaindex.ai/en/latest/examples/agent/multi_document_agents.html

But Top agent when called gives below error - 
<img width="735" alt="image" src="https://github.com/run-llama/llama_index/assets/58976261/eb9c01d5-f11e-4f59-87da-8287440d035e">

Top agent is defined as below - 
<img width="404" alt="image" src="https://github.com/run-llama/llama_index/assets/58976261/68050e36-c9ca-47d7-bf9d-f94a6966dd7b">

I also defined Top agent using openAIAgent but the same error comes up.

FYI - Base agent query runs and produces the results as given in the example
<img width="308" alt="image" src="https://github.com/run-llama/llama_index/assets/58976261/8973e25e-7728-4cb3-9e90-31a21276906b">

Also, I have set global service context as below -  

from llama_index import set_global_service_context

set_global_service_context(service_context)

### Version

0.8.69.post1

### Steps to Reproduce

llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="<>",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="<>",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

from llama_index import set_global_service_context

service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embed_model,
)

set_global_service_context(service_context)

###
###Skipping between codes
###

from llama_index.agent import FnRetrieverOpenAIAgent

top_agent = FnRetrieverOpenAIAgent.from_retriever(
    obj_index.as_retriever(similarity_top_k=3),
    system_prompt=""" \
You are an agent designed to answer queries about a set of given cities.
Please always use the tools provided to answer a question. Do not rely on prior knowledge.\

""",
    verbose=True,
)

response = top_agent.query("Tell me about the arts and culture in Boston")

**Comment by logan-markewich** [comment]
@sapekshsuman global service context is really only for query engines

You still need to pass the LLM into the agent itself

`top_agent = FnRetrieverOpenAIAgent.from_retriever(..., llm=llm)`

**Comment by sapekshsuman** [comment]
If I apply the above change i.e., top_agent = FnRetrieverOpenAIAgent.from_retriever(..., llm=llm)
I get the below error - 
<img width="561" alt="image" src="https://github.com/run-llama/llama_index/assets/58976261/32576006-a2a5-4f72-890b-f3703dff1889">

**Comment by ravi03071991** [comment]
@logan-markewich Just wondering if Azure OpenAI supports OpenAI agent?

**Comment by logan-markewich** [comment]
@ravi03071991 it sure does.

@sapekshsuman what api_version are you using? Make sure to use the latest preview possible

**Comment by cyhsieh** [comment]
Thanks to @logan-markewich!
set_global_service_context is not enough.
Not only pass llm parameter to top_agent, but also pass llm to each agent in "agents" dict is needed.

**Comment by sapekshsuman** [comment]
@logan-markewich - I am currently using 2023-08-01-preview as api_version. I also tried it with another version, but the error remained the same.

@cyhsieh - I pass ll parameter in each agents as well infact its already present in the sample code. Below is the screenshot - 
<img width="730" alt="image" src="https://github.com/run-llama/llama_index/assets/58976261/2825189d-b581-4995-a873-e4e7de08b721">

As you can see even the agent throws out the same error while calling. FYI - I have tried it using both GPT-3.5 and GPT 4 but error remained same.

**Comment by cyhsieh** [comment]
Maybe you check env settings

It's seems that original OPENAI_API_BASE should be replaced by AZURE_OPENAI_ENDPOINT when using azure openai with openai > 1.0.0 (required by recent version of llama-index)

**Comment by sapekshsuman** [comment]
llm = AzureOpenAI(
model="gpt-35-turbo",
deployment_name="<>",
api_key=api_key,
azure_endpoint=azure_endpoint,
api_version=api_version,
)

I am passing azure endpoint as parameter. I pass the above parameters. Also since my base query engine works I am guessing my env setting is correct. As soon as tools are passed the code breaks.
![image](https://github.com/run-llama/llama_index/assets/58976261/ab6e4b58-09cb-4e9c-8a6e-3b21ee802c8a)

@cyhsieh - Are you able to run the multi document agent code using Azure OpenAI key ?

**Comment by cyhsieh** [comment]
@sapekshsuman Yes, I can run. (notebook: https://colab.research.google.com/github/run-llama/llama_index/blob/main/docs/examples/agent/multi_document_agents.ipynb)

In addition to parameters of ```llm=AzureOpenAI```, there are some settings in the beginning of my code:

```python
os.environ["OPENAI_API_KEY"] = os.getenv("OPENAI_API_KEY")
# os.environ["OPENAI_API_BASE"] = os.getenv("OPENAI_API_BASE")
os.environ["AZURE_OPENAI_ENDPOINT"] = os.getenv("AZURE_OPENAI_ENDPOINT")
```

**Comment by sapekshsuman** [comment]
I believe I am doing exactly the same as you are doing, @cyhsieh. Will you be available to meet over a call, or can you send me a copy of your code after hiding the keys, etc. ?

**Comment by logan-markewich** [comment]
@sapekshsuman this works fine for me

Azure setup
```python
from llama_index.llms import AzureOpenAI
from llama_index.embeddings import AzureOpenAIEmbedding

api_key = "..."
azure_endpoint = "https://test-simon.openai.azure.com/"
api_version = "2023-07-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo-16k",
    deployment_name="my-custom-llm",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="my-custom-embedding",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

from llama_index import set_global_service_context, ServiceContext

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
set_global_service_context(service_context)
```

Load data
```python
storage_context = StorageContext.from_defaults(
    persist_dir="./storage/lyft"
)
lyft_index = load_index_from_storage(storage_context, service_context=service_context)

storage_context = StorageContext.from_defaults(
    persist_dir="./storage/uber"
)
uber_index = load_index_from_storage(storage_context, service_context=service_context)
```

Setup tools
```
query_engine_tools = [
    QueryEngineTool(
        query_engine=lyft_engine,
        metadata=ToolMetadata(
            name="lyft_10k",
            description=(
                "Provides information about Lyft financials for year 2021. "
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
    QueryEngineTool(
        query_engine=uber_engine,
        metadata=ToolMetadata(
            name="uber_10k",
            description=(
                "Provides information about Uber financials for year 2021. "
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
]
```

Call agent
```python
from llama_index.agent import OpenAIAgent

agent = OpenAIAgent.from_tools(query_engine_tools, llm=llm)
response = await agent.chat("How did Uber and Lyft compare in revenue growth in 2021?")
print(response)
```

**Comment by cyhsieh** [comment]
@sapekshsuman What's the model version of your deployment? Function Calling starts from gpt-35-turbo-0613 (16K), and api version 2023-07-01-preview

**Comment by sapekshsuman** [comment]
Got it working. Thanks @logan-markewich  and @cyhsieh . 
I was using gpt-35-turbo-0613 but as soon as I used 16k one it worked and also I was using GPT-4-0613 which gave error whereas it worked on GPT-4-1106-Preview 

Closing this issue now.

**Comment by sapekshsuman** [comment]
Closing
