### ISSUE TITLE
Azure OpenAI REST URLs constructed incorrectly [Bug]: 

### ISSUE THREAD

**Issue by hjfeldy** [run-llama/llama_index#8989]
### Bug Description

I just updated to the recent release, and all the API calls were failing. I looked at the debug logs and saw this:
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/deployments/<my-resource>/chat/completions', 'files': ...

I was able to get everything working by patching the low level request functions in the openai library, but that is far from ideal. Should be a quick fix for anyone familiar with the codebase.

### Version

v0.9.3.post1

### Steps to Reproduce

Instantiate an AzureOpenAI object according to the documentation specs (existing code which worked in the prior version), and make any LLM request

### Relevant Logs/Tracbacks

```shell
DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/deployments/<my-resource>/chat/completions', 'files': ...
```

**Comment by logan-markewich** [comment]
@hjfeldy the kwargs may have changed slightly, have you checked this page?
https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html

**Comment by logan-markewich** [comment]
I just ran this on the latest install, and it worked fine for me

```
api_key = "..."
azure_endpoint = "https://<your-resource-name>.openai.azure.com/"
api_version = "2023-07-01-preview"

llm = AzureOpenAI(
    model="gpt-35-turbo-16k",
    deployment_name="my-custom-llm",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="my-custom-embedding",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)
```

**Comment by hjfeldy** [comment]
Didn't see the documentation update, my bad y'all. Maybe it would be a good idea to raise an error when passing unsupported kwargs? I've noticed that passing in unsupported kwargs sometimes doesn't raise any errors in other prats of the library, so maybe it's more of an architectural problem
