### ISSUE TITLE
[Feature Request]: Pass ssl certificate to AzureOpenAi

### ISSUE THREAD

**Issue by fcasalen** [run-llama/llama_index#8990]
### Feature Description

hability to pass a SSL certificate or a http client with a valid certificate to AzureOpenAI class

### Reason

Some models in Azure require a SSL certificate to be passed or a http client with a valid certificate

**Comment by logan-markewich** [comment]
You can pass an httpx client to the AzureOpenAI LLM class, it is a kwarg

**Comment by logan-markewich** [comment]
https://github.com/run-llama/llama_index/blob/adb054429f642cc7bbfcb66d4c232e072325eeab/llama_index/llms/azure_openai.py#L78

**Comment by fcasalen** [comment]
> https://github.com/run-llama/llama_index/blob/adb054429f642cc7bbfcb66d4c232e072325eeab/llama_index/llms/azure_openai.py#L78

Tried that:

```
llm = AzureOpenAI(
    model = 'gpt-4-32k',
    engine = chat_gpt_azure_name,
    api_key = api_key,
    api_version = api_version,
    azure_endpoint = azure_endpoint,
    http_client = http_client
)
embed_model = AzureOpenAIEmbedding(
    deployment_name = embed_azure_name,
    api_key = api_key,
    api_version = api_version,
    azure_endpoint = azure_endpoint,
    http_client = http_client
)
service_context = ServiceContext.from_defaults(llm = llm, embed_model = embed_model)
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
```

It stills throws an ssl error.

When I use AzureOpenAI from openai package, it works fine passing the httpx client as above.
