### ISSUE TITLE
[Bug]: AttributeError: 'Document' object has no attribute 'get_doc_id'

### ISSUE THREAD

**Issue by newsta-ai** [run-llama/llama_index#8993]
### Bug Description

In the file 
llama_index/indices/base.py", line 97, in from_documents

docstore.set_document_hash(doc.get_doc_id(), doc.hash) gives an attribute error:
AttributeError: 'Document' object has no attribute 'get_doc_id'

This is triggered by calling the following using default values.
VectorStoreIndex.from_documents(documents=documents, storage_context=storage_context)

### Version

v0.9.3.post1

### Steps to Reproduce

There has been a change in the Document class in schemas file, where a new property doc_id has been added. However, in the file indices/base.py it still references get_doc_id(), which as a matter of fact exists in the Document class in schema, but still throws an error.

**Comment by newsta-ai** [comment]
Given your suggestion, it still runs into the error - 

This is the replacement as adviced:
docstore.set_document_hash(doc.doc_id, doc.hash)

This is the error:
AttributeError: 'Document' object has no attribute 'doc_id'

in the following file: llama_index/indices/base.py", line 97, in from_documents

**Comment by newsta-ai** [comment]
@dosu-bot 

Given your suggestion, it still runs into the error -

This is the replacement as adviced:
docstore.set_document_hash(doc.doc_id, doc.hash)

This is the error:
AttributeError: 'Document' object has no attribute 'doc_id'

in the following file: llama_index/indices/base.py", line 97, in from_documents

**Comment by nerdai** [comment]
Hi @newsta-ai,

Can you kindly provide the code that you're running which is producing these errors? The method `get_doc_id` is indeed deprecated in favour of the property `doc_id`, but there is backwards compatibility and the deprecated method should still work.

My sample script below runs without a hitch:

```python
from llama_index import ServiceContext, VectorStoreIndex
from llama_index.schema import Document
from llama_index.llms import OpenAI


def main():
    # make sure to set OPENAI_API_KEY env var
    doc = Document(text="Hi")
    llm = OpenAI(model="gpt-3.5-turbo", temperature=0.3)
    sc = ServiceContext.from_defaults(llm=llm, embed_model="local")
    index = VectorStoreIndex.from_documents(documents=[doc])
    print(index)


if __name__ == "__main__":
    main()
```

**Comment by Red-Caesar** [comment]
Hello, @nerdai 
Your code doesn't work for me either. It has error:
```
pydantic.v1.error_wrappers.ValidationError: 1 validation error for Document
page_content
```
And when I change code to 
```python
doc = Document(page_content="Hi")
sc = ServiceContext.from_defaults(llm=llm, embed_model="local")
index = VectorStoreIndex.from_documents(documents=[doc], service_context=sc)
```
It still has error:
`AttributeError: 'Document' object has no attribute 'get_doc_id'
`
Which version of library did you use?
Me: llama-index 0.9.4

**Comment by Red-Caesar** [comment]
> Hello, @nerdai Your code doesn't work for me either. It has error:
> 
> ```
> pydantic.v1.error_wrappers.ValidationError: 1 validation error for Document
> page_content
> ```
> 
> And when I change code to
> 
> ```python
> doc = Document(page_content="Hi")
> sc = ServiceContext.from_defaults(llm=llm, embed_model="local")
> index = VectorStoreIndex.from_documents(documents=[doc], service_context=sc)
> ```
> 
> It still has error: `AttributeError: 'Document' object has no attribute 'get_doc_id' ` Which version of library did you use? Me: llama-index 0.9.4

Oh, I'm sorry. I find the problem in my case. I'm using 
`from langchain.schema import Document`
instead of 
`from llama_index.schema import Document`

**Comment by nerdai** [comment]
ah, no worries @Red-Caesar! Glad we were able to get to bottom of this. Closing this issue now that it has been resolved on your end. Cheers.
