### ISSUE TITLE
[Question]: document already tokenized

### ISSUE THREAD

**Issue by patrickocal** [run-llama/llama_index#9001]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

If my document is already tokenised by BART, T5 or Llama2, how do I now use LlamaIndex to create a datastore or KnowledgeGraphIndex?

Alternatively, if the document is already chunked, how would I use LlamaIndex to create a KG and store in a KGIndex?

Also, are the KG triples (head, relation, tail) stored as a single vector in a KGIndex class?

**Comment by patrickocal** [comment]
Confused about whether or not I can implement the KnowledgeGraphIndex class. Please clarify.

Thanks for the RedisDocumentStore pointer.

**Comment by logan-markewich** [comment]
1. Tokenized text is not really helpful or used in llama-index (we use a tokenizer only for token counting)

2. You can directly create node objects and throw it into a kg index. By default, it uses the LLM to generate triplets
```
from llama_index.schema import TextNode

nodes = [TextNode(text=text) for text in texts]

index = KnowledgeGraphIndex(nodes, ...)
```

3. Yea the entire triplet is embedded (if you enable embeddings)
