### ISSUE TITLE
[Bug]: vector.control: No such file or directory

### ISSUE THREAD

**Issue by hemanth** [run-llama/llama_index#9004]
### Bug Description

Unable to connect to remote pd DB via connection string

### Version

v0.9.3

### Steps to Reproduce

```python
# !pip install llama_index asyncpg pgvector -q

from llama_index.indices.vector_store import VectorStoreIndex
from llama_index.vector_stores import PGVectorStore
from llama_index import ServiceContext

vector_store = PGVectorStore.from_params(connection_string="postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}", table_name="foobar")

service_context = ServiceContext.from_defaults(llm=llm, embed_model="local:BAAI/bge-base-en-v1.5",chunk_size=800, chunk_overlap=20)

index = VectorStoreIndex.from_vector_store(vector_store=vector_store, service_context=service_context)

query_engine = index.as_query_engine()

print(query_engine.query("Describe the table"))
```

results in :

```
UndefinedFile: could not open extension control file "/usr/share/postgresql/11/extension/vector.control": No such file or directory


The above exception was the direct cause of the following exception:

OperationalError                          Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/sqlalchemy/engine/default.py](https://localhost:8080/#) in do_execute(self, cursor, statement, parameters, context)
    920 
    921     def do_execute(self, cursor, statement, parameters, context=None):
--> 922         cursor.execute(statement, parameters)
    923 
    924     def do_execute_no_params(self, cursor, statement, context=None):

OperationalError: (psycopg2.errors.UndefinedFile) could not open extension control file "/usr/share/postgresql/11/extension/vector.control": No such file or directory

[SQL: CREATE EXTENSION IF NOT EXISTS vector]

```

^ The server is on elephantsql.

**Comment by logan-markewich** [comment]
@hemanth this error means you don't have pgvector installed in your db I think

**Comment by hemanth** [comment]
@logan-markewich was thinking the same and was trying it out with alternative libs and the below [works fine](https://h3manth.com/notes/SQLDatabaseChain/). 


https://github.com/run-llama/llama_index/assets/18315/dd87836e-c503-46f1-8330-414ad810c8b4

**Comment by hemanth** [comment]
@logan-markewich was thinking the same and was trying it out with alternative libs and the below [works fine](https://h3manth.com/notes/SQLDatabaseChain/). 

P.S: I am using exactly the same `connection_string`


https://github.com/run-llama/llama_index/assets/18315/dd87836e-c503-46f1-8330-414ad810c8b4

**Comment by logan-markewich** [comment]
@hemanth that demo isn't using vector retrieval it seems. Look up how to install pgvector and it should work then

**Comment by logan-markewich** [comment]
Or use a pgvector docker image (that's what I always do)

**Comment by hemanth** [comment]
I had done a `!pip install pgvector` this is on colab. Is there anything specific that is needed? Or the pgdb should have pgvector enabled?

**Comment by logan-markewich** [comment]
Yea the pgdb needs to have it installed, it's a little complicated (which is why I always used the docker image lol)

**Comment by hemanth** [comment]
Ah! Okies. I am doubtful if elephantDB has that option, maybe I should stick to pinecone or likes. 

If I were to query a non-vector db, like Vallina pg, what would be the options?
