### ISSUE TITLE
[Bug]: ChromaReader incorrect indexing of result in create_documents

### ISSUE THREAD

**Issue by dylan1218** [run-llama/llama_index#9006]
### Bug Description

The result of a chroma.query method are key values pairs where the values are nested arrays. In order to appropriately zip/loop through the values you need to first access the list of values themselves.

chroma.query id sample results:
![image](https://github.com/run-llama/llama_index/assets/28288488/e5caf348-2af5-45e5-8469-7264597b88e8)

Currentlly create_documents zips through the unested list, resulting in only one document being returned from the method call.

### Version

v0.9.3

### Steps to Reproduce

Call .load_data method on an initialized ChromaReader object where your chroma db contains more than one result.

What happens:
- only one document is returned

What is expected:
- a document for each record result returned from the chroma.query method

**Comment by dylan1218** [comment]
submitted pull request here: https://github.com/run-llama/llama_index/pull/9007. I took a different approach than the bot.

**Comment by logan-markewich** [comment]
Fixed in https://github.com/run-llama/llama_index/pull/9007
