### ISSUE TITLE
[Feature Request]: Implicit service_context creation

### ISSUE THREAD

**Issue by hemanth** [run-llama/llama_index#9009]
### Feature Description

It would be beneficial if we could implicitly create a `service_context` using the `llm` and `embedding` model for non-OpenAI based API in `VectorStoreIndex`, or any other place where `service_context` is necessary.

### Reason

Overhead of creating `service_context`.

For example: 

Instead of:

```python
service_context = ServiceContext.from_defaults(llm=llm, embed_model="local:BAAI/bge-base-en-v1.5",chunk_size=800, chunk_overlap=20)

index = VectorStoreIndex.from_vector_store(vector_store=vector_store, service_context=service_context)
```

the below will be useful? 
```python
index = VectorStoreIndex.from_vector_store(vector_store=vector_store,llm=llm, embed_model="local:BAAI/bge-base-en-v1.5",chunk_size=800, chunk_overlap=20)
```

I totally understand 

### Value of Feature

I totally understand that `service_context` container is a utility container and is an integral part of the design, thinking out lout on how we can make the API bit more simpler.

**Comment by logan-markewich** [comment]
@hemanth you can set a global service context (although this doesn't cover features that use an LLM directly, without a service context)

from llama_index import set_global_service_context 

set_global_service_context(service_context)

**Comment by logan-markewich** [comment]
In the meantime, we are working on a better solution in the future where we would like to remove the service context :)

**Comment by hemanth** [comment]
@logan-markewich nods on `set_global_service_context` but yeah +1 to remove service context :)
