### ISSUE TITLE
[Question]: Retrieve returns nodes that has nothing common with query text.

### ISSUE THREAD

**Issue by SuperMasterBlasterLaser** [run-llama/llama_index#9015]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello everyone.

I'm trying to check what kind of nodes are being retrieved by my query text like this:

```python
llm = OpenAI(temperature=0.1, model="gpt-4")
service_context = ServiceContext.from_defaults(llm=llm)
storage_context = StorageContext.from_defaults(persist_dir='./index/combined')
index = load_index_from_storage(storage_context=storage_context, service_context=service_context)

retriever = index.as_retriever(similarity_top_k=2)

query_text = "LOLLOLOL"

retrieved_nodes = retriever.retrieve(text)

for node in retrieved_nodes:
    print(node.node_id)
    print(node.score)
    print()
```
It returned to me this:

    41a167ee-bb9b-4f85-96a0-9a9f8b39dd6a
    0.769665012950761
    
    a599a73f-737e-4305-98d7-c605118c5090
    0.7669407729248501

The problem is that i sent random text which should have no conneciton to any of those nodes, and it still returns nodes with high scores.

The main idea is to prevent application from answering if user asks something that is not on knowledge vector index. Then why this is happening?

**Comment by logan-markewich** [comment]
Anything around 0.75 is a pretty common "neutral" score I've found for embeddings.

This isn't the fault of the retrieval system. This is mostly because you've input a very short query while the emebddimgs model is splitting that into 1536 dimensions (that's a lot of dimensions for very short text)

Try fiddling with the emebddings model or consider a Similarty cutoff postprocessor

**Comment by SuperMasterBlasterLaser** [comment]
@logan-markewich Sometimes it retrives nodes with 0.83 score when user asks about service prices, while there are no prices mentioned in vectors.

I have that kind of an idea. First I'm going to add similarity cutoff for 0.75 score. Then I'm going to add common question answer **that should not be answered in vector** and just hardcode their ID's, if it is similarity higher than 0.75 but it is in one of those nodes, I will ignore them.
