### ISSUE TITLE
[Question]: How to speed up index loading time

### ISSUE THREAD

**Issue by SCUT-ChenBD** [run-llama/llama_index#9019]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

In actual use, I found that the process of loading the index takes a long time, which greatly affects the real-time performance of the retrieval. Is there any way to speed it up? Or can it be converted into other more efficient storage methods (faiss, pgvector)?

**Comment by logan-markewich** [comment]
@SCUT-ChenBD I would use a db integration to speed this up for sure. Qdrant and Chroma are easy to get started with

**Comment by asiri77** [comment]
# To load multiple indices from storage
indices = load_indices_from_storage(storage_context, index_ids=['index_id1', 'index_id2'])
how to use this indices for quary engin?
chat_engine = indices.as_chat_engine( )
this not work and get error
