### ISSUE TITLE
[Feature Request]: add from_existing method to OpenAIAssistantAgent

### ISSUE THREAD

**Issue by ton77v** [run-llama/llama_index#9021]
### Feature Description

OpenAIAssistantAgent could currently be initialized using from_new class method.

This method performs API call to create a new assistant. Later on we access self._assistant.id to execute Run

I propose adding a new method, e.g. "from_existing" with assistant_id (string) as an only parameter. Instead of storing the whole Assistant instance we could only store this ID; it will be [returned by "create" API endpoint](https://platform.openai.com/docs/api-reference/assistants/createAssistant)

### Reason

At the moment the only solution to achieve this functionality is to subclass OpenAIAssistantAgent and implement additional method, mocking the self._assistant to use the .id for Runs or [retrieving the whole assistant](https://platform.openai.com/docs/api-reference/assistants/getAssistant)

### Value of Feature

We will perform less API calls and instead of creating a new Assistant every time, we re-use existing one saving time and resources. If Open AI limits the Assistants number this will be especially useful.

The same functionality is already [implemented by LangChain](https://python.langchain.com/docs/modules/agents/agent_types/openai_assistants#using-existing-assistant)

**Comment by logan-markewich** [comment]
@ton77v A PR for this would be great :)

**Comment by ton77v** [comment]
> @ton77v A PR for this would be great :) 

Cool, I should start working on a project involving Llama Index and Assistants API in a few days so I'll create one a bit later
