### ISSUE TITLE
[Bug]: exception events are inconsistently placed in the callback trace map

### ISSUE THREAD

**Issue by axiomofjoy** [run-llama/llama_index#9070]
### Bug Description

LlamaIndex's callback system passes exception events that are distinct from the events from which the error arose. Callback implementers must infer from which callback event the exception arose from the `trace_map` passed to `end_trace`. However, the position of the exception event in the trace map relative to the event from which the exception arose is not consistent. Most of the time, the exception event is a sibling of the event from which it arose, but when the exception arises from a node post-processor like the Cohere re-ranker, it is a child. This makes it difficult for callback implementations to consistently attribute the exception to the correct event.

Ideally, exception information would always be attributable to an easily identifiable event in the trace map. There are several options:

- Exception events are siblings of the event causing the error (how it currently works most of the time)
- Exception events are children of the event causing the error (how it works for node post-processors)
- Exceptions are not distinct callback events. Instead, exception information is passed to the `on_event_end` hook of the event in which the exception occurred (this might be the easiest to handle from the perspective of the callback implementation)

### Version

latest `main` (a31d3c89)

### Steps to Reproduce

[This script](https://github.com/Arize-ai/phoenix/compare/main...llama-index-exception-event-repro#diff-b0d832da586f945968cc95d49ac013714c461c96abff7e547f4d29d3bab6e0ec) shows how exception events can be siblings of the events causing the exception. It mocks a error from the OpenAI chat completions API and produces this output:

```
└── query
    ├── retrieve
    │   └── embedding
    └── synthesize
        ├── templating
        ├── llm
        ├── exception
        ├── exception
        └── exception
```

[This script](https://github.com/Arize-ai/phoenix/compare/main...llama-index-exception-event-repro#diff-efc27da6c2218b1476d363b1355077a3a52d121e87a7d3f38c3883486cffeaea) shows how exception events can be children of the event causing the exception. It mocks a `CohereAPIError` on the reranker client and produces the following output:

```
└── query
    ├── retrieve
    │   └── embedding
    └── reranking
        ├── exception
        ├── exception
        └── exception
```

**Comment by axiomofjoy** [comment]
Related to this ticket: https://github.com/Arize-ai/phoenix/issues/1618

**Comment by logan-markewich** [comment]
I like the idea of attaching to the on-end of the actual event 🤔 It would also solve the issue of duplicate error events

**Comment by logan-markewich** [comment]
I think I have a fix!

The sibling script prints this now:
```
└── query
    ├── retrieve
    │   └── embedding
    └── synthesize
        ├── templating
        ├── llm
        └── exception
```

The child script print this now:
```
└── query
    ├── retrieve
    │   └── embedding
    └── reranking
        └── exception
```

Will open a PR in a sec :)

**Comment by logan-markewich** [comment]
Ok been exploring a few fixes -- I think the root issue here is that at some point we specified that LLM events (and a few others) are `LEAF_EVNTS` -- meaning they can't have children, hence, the odd sibling vs. child issue.

**Comment by logan-markewich** [comment]
Ok, decided to attach the error to the event. 

With a slight change to the example scripts to check the payload of events, the traces look like this

"sibling" script check

```
└── query
    ├── retrieve
    │   └── embedding
    └── synthesize (error)
        ├── templating
        └── llm
```

"child" script check

```
└── query
    ├── retrieve
    │   └── embedding
    └── reranking (error)
```

**Comment by logan-markewich** [comment]
If an error happens outside of an event, but still within a trace, it will get logged as an actual exception event as before (But this should be extremely rare I think)

**Comment by axiomofjoy** [comment]
Awesome, thanks for the quick fix @logan-markewich!

**Comment by axiomofjoy** [comment]
> Ok, decided to attach the error to the event.
> 
> With a slight change to the example scripts to check the payload of events, the traces look like this
> 
> "sibling" script check
> 
> ```
> └── query
>     ├── retrieve
>     │   └── embedding
>     └── synthesize (error)
>         ├── templating
>         └── llm
> ```
> 
> "child" script check
> 
> ```
> └── query
>     ├── retrieve
>     │   └── embedding
>     └── reranking (error)
> ```

@logan-markewich Thanks for the quick fix on this! Exception events arising from the Cohere re-ranker are now attached to the re-ranker spans! See the image below:

<img width="1576" alt="Screenshot 2023-11-27 at 10 05 52 PM" src="https://github.com/run-llama/llama_index/assets/15664869/67deef88-4a8f-4e30-a1eb-551b402db991">

For a rate-limit error, I think the exception information should be associated with the LLM callback event rather than the synthesis event. Is it possible to change to this behavior?

In the [example script](https://github.com/Arize-ai/phoenix/compare/main...llama-index-exception-event-repro#diff-b0d832da586f945968cc95d49ac013714c461c96abff7e547f4d29d3bab6e0ec), the output would look like:

```
└── query
    ├── retrieve
    │   └── embedding
    └── synthesize
        ├── templating
        └── llm (exception)
```

**Comment by logan-markewich** [comment]
Oof. It's not easy to fix/change that I think 😅

**Comment by axiomofjoy** [comment]
> Oof. It's not easy to fix/change that I think 😅

Got it, no worries @logan-markewich. It's a small issue.
