### ISSUE TITLE
[Question]: HuggingFaceEmbedding and SentenceTransformer different results with the same model

### ISSUE THREAD

**Issue by mim201820** [run-llama/llama_index#9074]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Code that I'm using:
```
from sentence_transformers import SentenceTransformer
from llama_index.embeddings import HuggingFaceEmbedding

embed_model = HuggingFaceEmbedding(
    model_name="sentence-transformers/distiluse-base-multilingual-cased-v1",
)
model = SentenceTransformer('sentence-transformers/distiluse-base-multilingual-cased-v1')

embedding_1 = embed_model.get_text_embedding("Test")
embedding_2 = model.encode("Test")
```

when I check the length of each output. the HuggingFaceEmbedding returns 768 and SentenceTransfirmer returns 512

why do we have this difference, for the same model and the same query?

**Comment by mim201820** [comment]
Is it possible to change the Pooling strategy for the HuggingFaceEmbedding model?

**Comment by logan-markewich** [comment]
@mim201820 yes, you can do `HuggingFaceEmbedding(pooling="mean")` or `HuggingFaceEmbedding(pooling="cls")`
