### ISSUE TITLE
[Question]:  How do I pass a system prompt to a CondensePlusContextChatEngine?

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#9085]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How do I pass a system prompt to a CondensePlusContextChatEngine?
I have tried passing system_message as a keyword argument to a chat_engine with the condense_plus_context chat mode but it is not taking effect. How do I ensure it follows the system prompt?

**Comment by gich2009** [comment]
Is there a way to update the existing context_prompt instead of overwriting it?

**Comment by gich2009** [comment]
I actually tried to pass the default context_template with a few additions but the update did not take effect.

**Comment by logan-markewich** [comment]
@gich2009 Here's the default context_prompt

```
DEFAULT_CONTEXT_PROMPT_TEMPLATE = """
  The following is a friendly conversation between a user and an AI assistant.
  The assistant is talkative and provides lots of specific details from its context.
  If the assistant does not know the answer to a question, it truthfully says it
  does not know.

  Here are the relevant documents for the context:

  {context_str}

  Instruction: Based on the above documents, provide a detailed answer for the user question below.
  Answer "don't know" if not present in the document.
  """
```

Then, you just have to pass it in like


```
index.as_chat_engine(chat_mode="condense_plus_context", context_prompt=my_prompt, ...)
```

Or you can init from scratch

```
chat_engine = CondensePlusContextChatEngine.from_defaults(index.as_retriever(), context_prompt=my_prompt, service_context=service_context, ...)
```
