### ISSUE TITLE
[Bug]: Change in name of files saved when persist index locally

### ISSUE THREAD

**Issue by dioschuarz** [run-llama/llama_index#9086]
### Bug Description

Since last version, the file name vector_store.json changed to default__vector_store.json, this kind of changes make old folders when overwrited get now vector_store.json and default__vector_store.json what makes compability problems with another microservices which uses that files.

I suppose that is bug, if is not why need to create a new file name to vector_store? Is there possible keep with previous name vector_store.json only?

### Version

0.9.2

### Steps to Reproduce

Build a vector store and persist it in any folder locally, the name of the file vector_store.json changed.

**Comment by logan-markewich** [comment]
@dioschuarz it's not a bug. We added a "namespaces" concept to our vector stores to support multiple vector stores under different namespaces, in the same storage context.
