### ISSUE TITLE
[Bug]: start_char_idx and end_char_idx for TextNode is empty

### ISSUE THREAD

**Issue by philipk19238** [run-llama/llama_index#9101]
### Bug Description

I'm extracting chunks from my directory like this:

```python
loader = UnstructuredReader()
documents = loader.load_data(file=Path('./data/36C25723Q1179_1.docx'))

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=1024, chunk_overlap=40),
        QuestionsAnsweredExtractor(),
    ]
)

# run the pipeline
nodes = pipeline.run(documents=documents, llm=None)
```

However, I noticed that the start and end index attributes are None. I inspected the code base and didn't see anywhere where the attributes are being set. Is this intended behavior (where we're expected to implement this code) or is this a bug? 

### Version

0.9.6

### Steps to Reproduce

```python
loader = UnstructuredReader()
documents = loader.load_data(file=Path('./data/36C25723Q1179_1.docx'))

pipeline = IngestionPipeline(
    transformations=[
        SentenceSplitter(chunk_size=1024, chunk_overlap=40),
        QuestionsAnsweredExtractor(),
    ]
)

# run the pipeline
nodes = pipeline.run(documents=documents, llm=None)
```

**Comment by logan-markewich** [comment]
@philipk19238 We removed tracking for start/end_char_idx. But needed to slightly keep it for backwards compatibility in case people persisted nodes with these attributes

I was frequently not correct, and was also making development of new text splitters/node parsers more complicated than it was worth.

A simple fuzzy search is probably the easiest drop-in replacement.

**Comment by philipk19238** [comment]
What would be the best way to merge nodes? Was going for an approach where if distance between start/end indexes is less than N then merge.
