### ISSUE TITLE
[Bug]: SQLAutoVectorQueryEngine - Unrecognized request arguments supplied: tool_choice, tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}

### ISSUE THREAD

**Issue by ideasvijay1** [run-llama/llama_index#9118]
### Bug Description

I am trying to follow this https://gpt-index.readthedocs.io/en/v0.7.14/examples/query_engine/SQLAutoVectorQueryEngine.html example using AzureOpenAI services. I am using below code:

-----------------------------------------------------------------------------------------------------------------------------------------------
llm = AzureOpenAI(
    model="gpt-4",
    deployment_name="gpt-4",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="text-embedding-ada-002",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)
 I am getting BadRequest error
![error](https://github.com/run-llama/llama_index/assets/108950956/bc5b83c6-4a1c-4570-8fde-593c4b2633fe)

### Version

llama-index        0.9.6.post2

### Steps to Reproduce

Follow the sample - https://gpt-index.readthedocs.io/en/v0.7.14/examples/query_engine/SQLAutoVectorQueryEngine.html  with AzureOpenAI Services

`-----------------------------------------------------------------------------------------------------------------------------```

connection_string = os.environ["DB_CONN_STRING"]
db_name = os.environ["DB_NAME"]
url = make_url(connection_string)
vector_store = PGVectorStore.from_params(database=db_name,host=url.host,password=url.password,port=url.port,user=url.username,
                                           table_name="XXXX", embed_dim=1536,)  # openai embedding dimension

storage_context = StorageContext.from_defaults(vector_store=vector_store)
vector_index = VectorStoreIndex([], storage_context=storage_context)

api_key = os.environ["OPENAI_API_KEY"]
azure_endpoint = os.environ["OPENAI_API_BASE"]
api_version = os.environ["OPENAI_API_VERSION"]
print(azure_endpoint)
llm = AzureOpenAI(
    model="gpt-4",
    deployment_name="gpt-4",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

# You need to deploy your own embedding model as well as your own chat completion model
embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name="text-embedding-ada-002",
    api_key=api_key,
    azure_endpoint=azure_endpoint,
    api_version=api_version,
)

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model,)

from llama_index.indices.struct_store.sql_query import NLSQLTableQueryEngine
engine = create_engine(os.environ["SQL_DB_CONN"], future=True)

sql_database = SQLDatabase(engine, include_tables=["XXXX"])
sql_query_engine = NLSQLTableQueryEngine(sql_database=sql_database,tables=["XXXX"],)

#Define Query Engines, Set as Tools
from llama_index.query_engine import (SQLAutoVectorQueryEngine,RetrieverQueryEngine,)
from llama_index.tools.query_engine import QueryEngineTool
from llama_index.indices.vector_store import VectorIndexAutoRetriever

from llama_index.indices.vector_store.retrievers import (
    VectorIndexAutoRetriever,
)
from llama_index.vector_stores.types import MetadataInfo, VectorStoreInfo
from llama_index.query_engine.retriever_query_engine import (
    RetrieverQueryEngine,
)

vector_store_info = VectorStoreInfo(
    content_info="XXXX",
    metadata_info=[
        MetadataInfo(
            name="XXX", type="str", description="XXXX"
        ),
    ],
)
vector_auto_retriever = VectorIndexAutoRetriever(
    vector_index, vector_store_info=vector_store_info
)

retriever_query_engine = RetrieverQueryEngine.from_args(
    vector_auto_retriever, service_context=service_context
)

#tools
sql_tool = QueryEngineTool.from_defaults(
    query_engine=sql_query_engine,     
    description=(
        f"Useful for translating a natural language query into a SQL query over a table XXX." ),
)

vector_tool = QueryEngineTool.from_defaults(
    query_engine=retriever_query_engine,
    description=(
        f"Useful for answering semantic questions."
    ),
)

query_engine = SQLAutoVectorQueryEngine(
    sql_tool, vector_tool, service_context=service_context
)

try:
    response = query_engine.query(
        f"some query"
    )
except json.decoder.JSONDecodeError as e:
    print(e)

print(str(response))
``

**Comment by logan-markewich** [comment]
This has been solved a few times.

You need to adjust your deployed API version, or use a newer version of gpt-4 on azure 

https://github.com/run-llama/llama_index/issues/9084#issuecomment-1822924126

**Comment by ideasvijay1** [comment]
I will try this. Thank you.
