### ISSUE TITLE
[Question]: `StorageContext.from_dict` take too much time when generated embedding model is large

### ISSUE THREAD

**Issue by avipaghadar-maruti** [run-llama/llama_index#9128]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I Have issue in `**StorageContext.from_dict**` method.  When I Have large Embedding Model creating index is taking too much time and further process of Question/Answer is very slow using llm-index.

`storage_context = StorageContext.from_dict(content)`
`ai_index = load_index_from_storage(storage_context)`

I have 1.5 core CPU & 5 GB memory but still not affecting the speed,

**Comment by logan-markewich** [comment]
This is purely dependent on your disk (SSD, HDD, etc.) and not CPU or memory

If your index is large, you should consider using a vector db integration like qdrant, chroma, etc. 

If you aren't using a vector index, consider a remote backend like redis or mongodb
