### ISSUE TITLE
[Question]: Is it possible to ask a index list as one index

### ISSUE THREAD

**Issue by wsf1990** [run-llama/llama_index#9145]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi, Is it possible to ask a index list(every one is a VectorStoreIndex) as just ask a VectorStoreIndex? Which means fetch the top similar for the list then request the answer.

**Comment by logan-markewich** [comment]
Try this

https://docs.llamaindex.ai/en/stable/examples/retrievers/simple_fusion.html#simple-fusion-retriever

**Comment by wsf1990** [comment]
@logan-markewich Thanks! This solved my question very well.
