### ISSUE TITLE
[Question]: 

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#9150]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to run llama index with LM studio.

I tried with plain OpenAI setup, but it is complaining about API key and obviously going to OpenAI web API

I tried creating custom local LLM definition based on OpenAI, but it also produces the same error.
This is sample code used:

```
api_key  = "A"
api_base = "http://localhost:1234/v1"
model_name = "local-model"
os.environ['OPENAI_API_KEY'] = "111"
openai.api_key = os.environ.get('OPENAI_API_KEY')
max_tokens=50000

class OHllm(OpenAI):
    @property
    def metadata(self) -> LLMMetadata:
        return LLMMetadata(
            context_window=50000,
            num_output=self.max_tokens or -1,
            is_function_calling_model=False,
            model_name=self.model,
        )

llm = OHllm(model_name=model_name, openai_api_base=api_base, openai_api_key=api_key, temperature=0, max_tokens=max_tokens)
```

it fails on 
service_context = ServiceContext.from_defaults(llm=llm)
with error
ERROR: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 111.

**Comment by grabani** [comment]
I may look like an idiot for posting this, but here goes...

As I have set my OpenAI key as an environment variable, the way I import it into my program with:

```
import os
OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
```

I am not sure why if you endpoint is the localhost why you need your openai key :(

**Comment by dinonovak** [comment]
> I may look like an idiot for posting this, but here goes...
> 
> As I have set my OpenAI key as an environment variable, the way I import it into my program with:
> 
> ```
> import os
> OPENAI_API_KEY = os.environ["OPENAI_API_KEY"]
> ```
> 
> I am not sure why if you endpoint is the localhost why you need your openai key :(
> 
> PS - I am also interested in using LMStudio as a means of access my local LLM. But i would also like to know how I can use/reference my local downloaded LLM (downloaded usingLMstudio) via Llamaindex.

as per error: ERROR: Error code: 401 - {'error': {'message': 'Incorrect API key provided: 111.
llama index is able to find api key "111", but it looks like it is using it to access OPENAI API, not local LLM

**Comment by jblogs** [comment]
You should set both base_url and api_base to local to make it work.

```
from llama_index.llms.openai import OpenAI

llm = OpenAI(base_url="http://localhost:1234/v1", api_base="http://localhost:1234/v1", api_key="not-needed", temperature=0)

Settings.llm = llm

```

**Comment by DanteTheCreator** [comment]
> You should set both base_url and api_base to local to make it work.
> 
> ```
> from llama_index.llms.openai import OpenAI
> 
> llm = OpenAI(base_url="http://localhost:1234/v1", api_base="http://localhost:1234/v1", api_key="not-needed", temperature=0)
> 
> Settings.llm = llm
> ```

THANK YOU! <3
