### ISSUE TITLE
[Bug]: The 0.9.8 version can't support AZURE_TURBO_MODELS named gpt-35-turbo-1106

### ISSUE THREAD

**Issue by coderyjr** [run-llama/llama_index#9155]
### Bug Description

In my company,we used AzureOpenAI model. The 0.9.8 version throws ValueError:Unknown model 'gpt-35-turbo-1106' when I start my project by using model_name='gpt-35-turbo-1106'.
Because the AZURE_TURBO_MODELS in openai_utils does not contain it,but it should support.You can find it on the Azure website:https://learn.microsoft.com/zh-cn/azure/ai-services/openai/whats-new

please add it soon,thanks!

### Version

0.9.8

### Steps to Reproduce

    llm = OpenAI(model="gpt-35-turbo-1106", api_key=OPENAI_API_KEY, api_base=STREAM_OPENAI_API_BASE,
                 additional_kwargs={"extra_headers": headers})

**Comment by logan-markewich** [comment]
@coderyjr I think the model name is still `gpt-35-turbo`, but you select the version when deploying in azure no?
![image](https://github.com/run-llama/llama_index/assets/22285038/86022f9a-c47a-410d-9bbf-962d08c1edac)

**Comment by logan-markewich** [comment]
(Also, definitely use the azure openai LLM module)
https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html
