### ISSUE TITLE
BUG: llms.AzureOpenAI() `azure_deployment` constructor arg not aliased

### ISSUE THREAD

**Issue by janaka** [run-llama/llama_index#9173]
## Current
When instantiating AzureOpenAI class with arg `azure_deployment` it throws the error `Error: You must specify an `engine` parameter`

## Expected
It should be possible to set this argument and not have to set `engine`.

https://github.com/run-llama/llama_index/blob/218392bc3006c344dc2a3407feaf10a61b8193b8/llama_index/llms/azure_openai.py#L70-L70

Adding `azure_deployment` here should resolve. `AzureOpenAIEmbedding` class appears to alias as expected.
https://github.com/run-llama/llama_index/blob/218392bc3006c344dc2a3407feaf10a61b8193b8/llama_index/llms/azure_openai.py#L81-86

**Comment by janaka** [comment]
I created a quick PR #9174 to get started. It's not tested.

**Comment by logan-markewich** [comment]
Merged the PR, will be out in the next release (or you can install from source)
