### ISSUE TITLE
[Bug]: HierarchicalNodeParser not using include_metadata argument

### ISSUE THREAD

**Issue by dmonterom** [run-llama/llama_index#9175]
### Bug Description

The include_metadata argument is not passed to the SentenceSplitter node parsers created by default, and therefore, the metadata is always included in the nodes.

Probably this is because in previous versions this argument was passed in the get_nodes_from_documents function (it is still in the docstring)

### Version

0.9.8

### Steps to Reproduce

Create a hierarchical node parser and set include_metadata to false and you can check that the argument is ignored.

`
HierarchicalNodeParser.from_defaults(
    chunk_sizes=[1024, 256],
    include_metadata=False
)
`

**Comment by dmonterom** [comment]
Excuse my insistence but I think include_metadata argument should be passed to the SentenceSplitters, otherwise, it is useless.

**Comment by logan-markewich** [comment]
Don't mind the bot lol 

easy PR
