### ISSUE TITLE
[Bug]: store_nodes_override attribute of VectorStoreIndex not working

### ISSUE THREAD

**Issue by yash2mehta** [run-llama/llama_index#9177]
### Bug Description

store_nodes_override attribute of VectorStoreIndex not working, when being set equal to True.

Essentially, when there is no tables in the document, it shows this error:

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[109], line 7
      4 start_time = time.time()
      6 # Individual prompting - in case, you don't want to use loop and check for specific value
----> 7 response = query_engine.query(
      8     
      9     '''
     10     
     11     performance 2.93% in which month?
     12     
     13 
     14        
     15     '''
     16 )
     18 # Calculate and print elapsed time for this iteration with an empty table
     19 calculate_elapsed_time = time.time() - start_time

File ~/anaconda3/lib/python3.11/site-packages/llama_index/indices/query/base.py:23, in BaseQueryEngine.query(self, str_or_query_bundle)
     21 if isinstance(str_or_query_bundle, str):
     22     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 23 return self._query(str_or_query_bundle)

File ~/anaconda3/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py:171, in RetrieverQueryEngine._query(self, query_bundle)
    164 with self.callback_manager.event(
    165     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    166 ) as query_event:
    167     with self.callback_manager.event(
    168         CBEventType.RETRIEVE,
    169         payload={EventPayload.QUERY_STR: query_bundle.query_str},
    170     ) as retrieve_event:
--> 171         nodes = self.retrieve(query_bundle)
    173         retrieve_event.on_end(
    174             payload={EventPayload.NODES: nodes},
    175         )
    177     response = self._response_synthesizer.synthesize(
    178         query=query_bundle,
    179         nodes=nodes,
    180     )

File ~/anaconda3/lib/python3.11/site-packages/llama_index/query_engine/retriever_query_engine.py:123, in RetrieverQueryEngine.retrieve(self, query_bundle)
    122 def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
--> 123     nodes = self._retriever.retrieve(query_bundle)
    124     return self._apply_node_postprocessors(nodes, query_bundle=query_bundle)

File ~/anaconda3/lib/python3.11/site-packages/llama_index/indices/base_retriever.py:22, in BaseRetriever.retrieve(self, str_or_query_bundle)
     20 if isinstance(str_or_query_bundle, str):
     21     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 22 return self._retrieve(str_or_query_bundle)

File ~/anaconda3/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:185, in RecursiveRetriever._retrieve(self, query_bundle)
    184 def _retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
--> 185     retrieved_nodes, _ = self._retrieve_rec(query_bundle, query_id=None)
    186     return retrieved_nodes

File ~/anaconda3/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:161, in RecursiveRetriever._retrieve_rec(self, query_bundle, query_id, cur_similarity)
    158         nodes = obj.retrieve(query_bundle)
    159         event.on_end(payload={EventPayload.NODES: nodes})
--> 161     nodes_to_add, additional_nodes = self._query_retrieved_nodes(
    162         query_bundle, nodes
    163     )
    165 elif isinstance(obj, BaseQueryEngine):
    166     sub_resp = obj.query(query_bundle)

File ~/anaconda3/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:99, in RecursiveRetriever._query_retrieved_nodes(self, query_bundle, nodes_with_score)
     94     if self._verbose:
     95         print_text(
     96             "Retrieved node with id, entering: " f"{node.index_id}\n",
     97             color="pink",
     98         )
---> 99     cur_retrieved_nodes, cur_additional_nodes = self._retrieve_rec(
    100         query_bundle,
    101         query_id=node.index_id,
    102         cur_similarity=node_with_score.score,
    103     )
    104 else:
    105     assert isinstance(node, TextNode)

File ~/anaconda3/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:149, in RecursiveRetriever._retrieve_rec(self, query_bundle, query_id, cur_similarity)
    146 query_id = query_id or self._root_id
    147 cur_similarity = cur_similarity or 1.0
--> 149 obj = self._get_object(query_id)
    150 if isinstance(obj, BaseNode):
    151     nodes_to_add = [NodeWithScore(node=obj, score=cur_similarity)]

File ~/anaconda3/lib/python3.11/site-packages/llama_index/retrievers/recursive_retriever.py:129, in RecursiveRetriever._get_object(self, query_id)
    127 if query_engine is not None:
    128     return query_engine
--> 129 raise ValueError(
    130     f"Query id {query_id} not found in either `retriever_dict` "
    131     "or `query_engine_dict`."
    132 )

ValueError: Query id pandas0 not found in either `retriever_dict` or `query_engine_dict`.`

Was able to fix it in the end, using this code which just creates empty dataframe, pandas0, but wanted to know if there is a more robust solution and if its a bug in the library:

# If this dictionary is empty
if not df_id_query_engine_mapping:
    
    empty_table_df = pd.DataFrame()
    df_query_engine = PandasQueryEngine(empty_table_df, service_context=service_context)
    
    # Insert the key-value pair into the dictionary
    df_id_query_engine_mapping["pandas0"] = df_query_engine

### Version

0.8.44

### Steps to Reproduce

Please use this source code here: https://github.com/yash2mehta/langchain_debug

Please use this pdf document placed in the documents directory (where root level is the .py file from above source code): https://drive.google.com/drive/folders/1PqPjPg65vA6EpD-zUdTTE1O0L4z70ulp?usp=sharing

**Comment by logan-markewich** [comment]
I don't think this is a bug? It seems like it's caused by not finding any tables in a document (which can definitely happen)

You've hardcoded the summaries to a list of 1. So no matter how many tables you find, it won't have a summary for each table 🤔 

I think a better fix is checking that you actually found any tables before doing anything related to pandas, and skipping creating df_nodes and df_id_query_engine_mapping if no tables are found
