### ISSUE TITLE
[Bug]: EOS token appears in streaming response text for HuggingFaceLLM models

### ISSUE THREAD

**Issue by sfriedowitz** [run-llama/llama_index#9184]
### Bug Description

When using a `HuggingFaceLLM` with streaming generation in the query engine, the EOS tokens appear in the output text. This notably occurs in the Mistral Instruct models, where the `</s>` EOS token shows up in the response text generation. This only occurs with a streaming response.

It appears that the stopping criteria for the streaming response is explicitly including the EOS token, rather than just everything before it.

### Version

0.9.5

### Steps to Reproduce

- Use an OSS HuggingFaceLLM model, such as Mistral Insturct 7B, or even a tiny model like distilgpt2
- Create a query engine with `streaming = True` for generation
- Run a query and examine the generated text, which will contain the EOS token ID.

### Relevant Logs/Tracebacks

This is with the `distilgpt2` model which I use for local debugging. The response is not expected to make logical sense, but just show that the EOS token is appearing in the generated text when streaming is enabled. 

```shell
** Prompt: **
Answer the following Question based on the provided Context.

Question:
What are you doing today?

Answer:
**************************************************
** Completion: **

I am a student at University of California, Berkeley and I'm currently studying in English with my PhD from UC Davis (and also an undergraduate degree) as well! My thesis is about how to build relationships between students who have been taught by their peers for years or so through different disciplines such that they can learn more quickly than others without having any problems learning anything new while still being able "learn" what's going wrong."<|endoftext|>
**************************************************
```

**Comment by logan-markewich** [comment]
Unless you can see whats wrong with the source code, I'm not really sure how to fix this.

There's already `skip_special_tokens=True` --- maybe the LLM is actually generating this token, and it's not a special token in the tokenizer?

https://github.com/run-llama/llama_index/blob/13de48523cec5f2019a4edb2d0d2b8e30ff9d8a4/llama_index/llms/huggingface.py#L307

One fix might be adding `</s>` as a special token in the tokenizer, and then passing in the tokenizer directly as a kwarg to the LLM

**Comment by sfriedowitz** [comment]
So far I've observed this issue with Mistral 7B (instruct and non-instruct versions), and the tiny model distilgpt2 that I often use for local debugging.

Here is the model loading code:

```
model = AutoModelForCausalLM.from_pretrained(
    "distilgpt2",
    torch_dtype=torch.float16,
    device_map="auto",
)
tokenizer = AutoTokenizer.from_pretrained("distilgpt2")
llm = HuggingFaceLLM(
      model=model,
      tokenizer=tokenizer,
      context_window=tokenizer.model_max_length
 )
```

I can keep trying to poke at the internal options to see if I can find a way to stop inclusion of those tokens. They are definitely the EOS tokens for the given tokenizers being used, but yeah, unsure why they are included if the `skip_special_tokens` is internally set to True.

**Comment by BarryRun** [comment]
I solved the problem through this way:
Change the code in llama-index-integrations/llms/llama-index-llms-huggingface/llama_index/llms/huggingface/base.py line 314-318:
```
streamer = TextIteratorStreamer(
            self._tokenizer,
            skip_prompt=True,
            decode_kwargs={"skip_special_tokens": True},
        )
```
to
```
streamer = TextIteratorStreamer(
            self._tokenizer,
            skip_prompt=True,
            skip_special_tokens=True
        )
```

It seems that there was an issue with passing the parameters.

I hope it can help you @sfriedowitz @logan-markewich
