### ISSUE TITLE
[Bug]: TypeError when importing aiostream while importing RetrieverQueryEngine

### ISSUE THREAD

**Issue by jmizgajski** [run-llama/llama_index#9187]
### Bug Description

`Python: 3.9.16

This is the lowest level failure of importing a class from llama_index that depends on import from aiostream somwhere down the call stack. The offending line is `class OperatorType(Protocol[P, T]):` where P and T are ParamSpecs

I tried installing the different versions of `typing-extentions` but that does not change anything.

Expected behavior: imports without TypeError

### Version

0.9.8.post1

### Steps to Reproduce

```
from llama_index.query_engine import RetrieverQueryEngine
```

### Relevant Logs/Tracbacks

```shell
File "/home/jan/.virtualenvs/ml-for-research-39/lib/python3.9/site-packages/aiostream/__init__.py", line 18, in <module>
    from . import stream, pipe
  File "/home/jan/.virtualenvs/ml-for-research-39/lib/python3.9/site-packages/aiostream/stream/__init__.py", line 3, in <module>
    from .create import *
  File "/home/jan/.virtualenvs/ml-for-research-39/lib/python3.9/site-packages/aiostream/stream/create.py", line 21, in <module>
    from ..stream import time
  File "/home/jan/.virtualenvs/ml-for-research-39/lib/python3.9/site-packages/aiostream/stream/time.py", line 6, in <module>
    from ..core import streamcontext, pipable_operator
  File "/home/jan/.virtualenvs/ml-for-research-39/lib/python3.9/site-packages/aiostream/core.py", line 260, in <module>
    class OperatorType(Protocol[P, T]):
  File "/usr/lib/python3.9/typing.py", line 277, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.9/typing.py", line 997, in __class_getitem__
    raise TypeError(
TypeError: Parameters to Protocol[...] must all be type variables
```

**Comment by logan-markewich** [comment]
@jmizgajski I think this is an issue with your env?

Just tried in colab (with a fresh env) and it works fine 
https://colab.research.google.com/drive/14sAtcMp3xOpbEq7ABPgfMNIPLrLTX3m7?usp=sharing

Also, all our unit tests test python 3.8, 3.9, and 3.10 -- so this would have been caught in CI if it was an issue

I suggest creating a fresh venv

**Comment by jmizgajski** [comment]
ok, I'll try that and let you know

**Comment by jmizgajski** [comment]
there is one more interesting development - the full code runs without problem when I simply run it in Pycharm - the problem only occurs when I use the debugger. I tried setting `PYDEVD_USE_CYTHON=NO` which can sometimes resolve similar problems, but it did not change anything. So it does not seem this is purely an issue of the environment and your test in jupyter @logan-markewich is probably not conclusive here (also you've run it on a different version of python).

**Comment by logan-markewich** [comment]
(the version of python doesn't really matter, especially when our CI uses python3.8, 3.9, and 3.10)

If you can figure out a fix for this, feel free to make a PR -- but this doesn't feel easy to reproduce.

Running my own pycharm debugger, I do not encounter this (python3.9, fresh venv, PyCharm Community 2020 (I never use pycharm often lol)
