### ISSUE TITLE
[Documentation]: MongoDB Atlas-ServerSelectionTimeoutError: SSL handshake failed: ac-6cvehze-shard-00-01.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR]

### ISSUE THREAD

**Issue by andysingal** [run-llama/llama_index#9191]
### Documentation Issue Description

Tried:
<img width="795" alt="Screenshot 2023-11-28 at 7 02 05 PM" src="https://github.com/run-llama/llama_index/assets/20493493/f0b0c0a2-03cc-4437-8ced-7e015cf87515">

And 
Mongodb COmpass:
<img width="1422" alt="Screenshot 2023-11-28 at 7 02 33 PM" src="https://github.com/run-llama/llama_index/assets/20493493/49f98c27-eb6f-464f-80ab-91b6daaf2f1f">

but still got error when running the code:
```
import pymongo
from llama_index import VectorStoreIndex
from llama_index.storage.storage_context import StorageContext
from llama_index.vector_stores.mongodb import MongoDBAtlasVectorSearch

mongo_uri = "mongodb+srv://andysingal:{password}@cluster0.r6r1wbj.mongodb.net/?retryWrites=true&w=majority"
mongodb_client = pymongo.MongoClient(mongo_uri)
store = MongoDBAtlasVectorSearch(mongodb_client)
storage_context = StorageContext.from_defaults(vector_store=store)
nomi = VectorStoreIndex.from_documents(
           documents, storage_context=storage_context, service_context=service_context
        )
```
error:
```
ServerSelectionTimeoutError: SSL handshake failed: ac-6cvehze-shard-00-01.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-6cvehze-shard-00-00.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms),SSL handshake failed: ac-6cvehze-shard-00-02.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6566181950393696aaf35e83, topology_type: ReplicaSetNoPrimary, servers: [<ServerDescription ('ac-6cvehze-shard-00-00.r6r1wbj.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-6cvehze-shard-00-00.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007) (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>, <ServerDescription ('ac-6cvehze-shard-00-01.r6r1wbj.mongodb.net', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('SSL handshake failed: ac-6cvehze-shard-00-01.r6r1wbj.mongodb.net:27017: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1007)
```

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/vector_stores/MongoDBAtlasVectorSearch.html#

**Comment by andysingal** [comment]
> _🤖_
> 
> Hi @andysingal! Good to see you again here. I hope you're doing well. Let's get into your issue.
> 
> The `ServerSelectionTimeoutError` and SSL handshake failure you're encountering when trying to connect to MongoDB Atlas using the LlamaIndex library could be due to a few reasons:
> 
> 1. Incorrect MongoDB URI: Ensure that the MongoDB URI you're using is correct. The URI should be set in the environment variable `MONGO_URI`.
> 2. Network Issues: Ensure that your network allows connections to MongoDB Atlas. Some networks may block outgoing connections.
> 3. SSL/TLS Configuration: MongoDB Atlas requires SSL/TLS for all connections. You may need to configure your MongoClient to use SSL.
> 
> To resolve these issues, you can try the following:
> 
> 1. Check your MongoDB URI: Make sure that the MongoDB URI you're using is correct. You can usually find this in the MongoDB Atlas dashboard under the "Connect" option.
> 2. Check your network: If you're on a network that restricts outgoing connections, you may need to adjust your network settings or contact your network administrator.
> 3. Configure SSL/TLS: You can configure your MongoClient to use SSL by adding `tls=true` and `tlsCertificateKeyFile=<path_to_pem_file>` to your MongoDB URI. If you're using a self-signed certificate, you may also need to include `tlsAllowInvalidCertificates=true`.
> 
> Here's how you can modify the MongoClient initialization in the LlamaIndex library to use SSL:
> 
> ```python
> self._mongodb_client = MongoClient(
>     os.environ["MONGO_URI"],
>     driver=DriverInfo(name="llama-index", version=version("llama-index")),
>     tls=True,
>     tlsCertificateKeyFile='<path_to_pem_file>',
>     tlsAllowInvalidCertificates=True
> )
> ```
> 
> Please replace `<path_to_pem_file>` with the path to your .pem file.
> 
> Remember to handle your certificates securely, especially if you're allowing invalid certificates.
> 
> As for your question about whether the LlamaIndex library supports SSL/TLS configuration for MongoDB connections out of the box, I wasn't able to find an answer within the repository. It's possible that this feature is not supported out of the box and needs to be manually configured by the user. However, I recommend checking the official LlamaIndex documentation or reaching out to the maintainers for a definitive answer.
> 
> I hope this helps! If you have any other questions, feel free to ask.
> 
> Best, [Dosu](https://dosu.dev)
> 
> ## Sources
> * [llama_index/vector_stores/mongodb.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/mongodb.py)

I tried using the isrgrootx1.pem file but still got the same error as shared in the snapshots

**Comment by andysingal** [comment]
> _🤖_
> 
> Based on the error message you provided, it seems like the SSL handshake is failing when trying to connect to your MongoDB Atlas cluster. This could be due to a few reasons, but let's try to narrow it down.
> 
> Firstly, ensure that your MongoDB URI is correctly formatted and includes the correct username, password, and cluster address. It should look something like this: `mongodb+srv://<username>:<password>@cluster0.mongodb.net/myFirstDatabase?retryWrites=true&w=majority`.
> 
> Next, in MongoDB Atlas, you need to whitelist your IP address to allow connections from your server to the MongoDB Atlas cluster. This can be done in the Network Access section of the MongoDB Atlas dashboard.
> 
> Regarding your SSL/TLS settings, if you're using a self-signed certificate, you might need to include it in your MongoClient configuration. However, since you're connecting to MongoDB Atlas, you should be using their CA certificate instead of a self-signed one. You can download the CA certificate from the MongoDB Atlas Connect dialog.
> 
> Also, ensure that you're using a compatible version of pymongo. The LlamaIndex library is compatible with pymongo version 4.5.0. You can check the version by running `pip show pymongo` in your terminal.
> 
> Lastly, ensure that your server has a stable network connection and can reach the MongoDB Atlas servers. You can test this by trying to connect to your MongoDB Atlas cluster using the mongo shell or another MongoDB client.
> 
> If you're still encountering issues after checking these points, please provide more specific details about the error message you're receiving, your MongoDB Atlas configuration, and your LlamaIndex configuration. This will help in diagnosing and resolving the issue.
> 
> For reference, here are the relevant parts of the LlamaIndex codebase and documentation:
> 
> * [llama_index/vector_stores/mongodb.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/mongodb.py)
> * [pyproject.toml](https://github.com/run-llama/llama_index/blob/main/pyproject.toml)
> 
> I hope this helps! If you have any other questions or need further clarification, feel free to ask.
> 
> ## Sources
> * [llama_index/vector_stores/mongodb.py](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/mongodb.py)
> * [pyproject.toml](https://github.com/run-llama/llama_index/blob/main/pyproject.toml)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I tried all of the tasks including 
```
!pip install pymongo -q
import pymongo
from llama_index.storage.storage_context import StorageContext
from llama_index.vector_stores.mongodb import MongoDBAtlasVectorSearch

mongo_uri = "mongodb+srv://{username}:{password}@cluster0.r6r1wbj.mongodb.net/?retryWrites=true&w=majority&**tlsCAFile=isrgrootx1.pem**"
mongodb_client = pymongo.MongoClient(mongo_uri)
store = MongoDBAtlasVectorSearch(mongodb_client)
# service_context = ServiceContext.from_defaults(
#             llm=llm,
#             embedding=embed_model,
#         )
storage_context = StorageContext.from_defaults(vector_store=store)
nomi = VectorStoreIndex.from_documents(
           documents, storage_context=storage_context, service_context=service_context
        )
```

**Comment by andysingal** [comment]
@hatianzhang @dosubot  can you please look into it

**Comment by qniksefat** [comment]
Hey, you should simply whitelist the IP address. 

Login to you MongoDB Atlas account, choose 'Network Access' on the left panel and just 'Add IP Address' from there. If it's not a sensitive dataset, you may wanna add `0.0.0.0/0` which grants access to everyone.

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">


<img width="1440" alt="Screenshot 2024-03-02 at 12 22 31 PM" src="https://github.com/run-llama/llama_index/assets/18231294/bd1fea69-af38-48d1-a650-ab69c81daa94">

**Comment by djacquensf9** [comment]
Old topic, @qniksefat provided the correct solution. 👍

However, from a security perspective, instead of adding 0.0.0.0/0, I recommend using your own public IP address, which you can find by running:

`curl ifconfig.me`

Then, if the returned IP is 1.2.3.4, you should whitelist 1.2.3.4/32 in MongoDB Atlas network access.

Thanks ;)
