### ISSUE TITLE
[Bug]: sub_question query engine does not work on Azure OpenAI

### ISSUE THREAD

**Issue by mingqxu7** [run-llama/llama_index#9195]
### Bug Description

Run a python code shown in the "Steps to Reproduce" under the Azure OpenAI environment will get the following error:

(ragqa) mingqxu: utils % python sub_question_query.py
**********
Trace: index_construction
    |_CBEventType.NODE_PARSING ->  0.071401 seconds
      |_CBEventType.CHUNKING ->  0.068678 seconds
    |_CBEventType.EMBEDDING ->  0.581044 seconds
    |_CBEventType.EMBEDDING ->  0.581065 seconds
**********
**********
Trace: query
    |_CBEventType.QUERY ->  0.341761 seconds
      |_CBEventType.LLM ->  0.0 seconds
**********
Traceback (most recent call last):
  File "/Users/mingqxu/Projects/chat-sop/utils/sub_query.py", line 80, in <module>
    response = query_engine.query(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/core/base_query_engine.py", line 30, in query
    return self._query(str_or_query_bundle)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/query_engine/sub_question_query_engine.py", line 132, in _query
    sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/question_gen/openai_generator.py", line 88, in generate
    SubQuestionList, self._program(query_str=query_str, tools_str=tools_str)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/program/openai_program.py", line 167, in __call__
    chat_response = self._llm.chat(
                    ^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/llms/base.py", line 187, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/llms/openai.py", line 200, in chat
    return chat_fn(messages, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/llama_index/llms/openai.py", line 254, in _chat
    response = self._client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/openai/_utils/_utils.py", line 301, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/mingqxu/miniforge3arm64/envs/ragqa/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Unrecognized request arguments supplied: tool_choice, tools', 'type': 'invalid_request_error', 'param': None, 'code': None}}
(ragqa) mingqxu: utils % pip list|grep llama-index
llama-index                    0.9.8.post1
(ragqa) mingqxu: utils % pip list |grep openai
openai                         1.3.6

### Version

0.9.8.post1

###  sub_question_query.py ######
# set environment variables in the /content/config.env
# file, which has the format of VAR=VALUE --- don't use single quote to quote the VALUE
import os
with open("../config.env", "r") as f:
    for line in f:
        if line.startswith("#"):
            continue
        var = line.strip().split("=")
        if len(var) == 2:
            os.environ[var[0]] = var[1]

import nest_asyncio
nest_asyncio.apply()

from llama_index.embeddings.langchain import LangchainEmbedding
from langchain.embeddings import OpenAIEmbeddings, AzureOpenAIEmbeddings

embed_model = LangchainEmbedding(
                AzureOpenAIEmbeddings(
                    model='text-embedding-ada-002',
                    deployment='text-embedding-ada-002',
                    api_key=os.environ["AZURE_OPENAI_API_KEY"],
                    azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
                    api_version=os.environ["OPENAI_API_VERSION"],
                ),
                embed_batch_size=16,
            )

from llama_index.llms import OpenAI, AzureOpenAI
llm = AzureOpenAI(model='gpt-3.5-turbo-16k', 
                  engine='gpt-35-turbo-16k',
                  api_key=os.environ["AZURE_OPENAI_API_KEY"],
                  azure_endpoint=os.environ["AZURE_OPENAI_ENDPOINT"],
                  api_version=os.environ["OPENAI_API_VERSION"],
)

from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.tools import QueryEngineTool, ToolMetadata
from llama_index.query_engine import SubQuestionQueryEngine
from llama_index.callbacks import CallbackManager, LlamaDebugHandler
from llama_index import ServiceContext

# Using the LlamaDebugHandler to print the trace of the sub questions
# captured by the SUB_QUESTION callback event type
llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

service_context = ServiceContext.from_defaults(
                llm=llm,
                embed_model=embed_model,
                chunk_size=1024,
                callback_manager=callback_manager   
            )

# load data
pg_essay = SimpleDirectoryReader(input_dir="./data/paul_graham/").load_data()

# build index and query engine
vector_query_engine = VectorStoreIndex.from_documents(
    pg_essay, use_async=True, service_context=service_context
).as_query_engine()

# setup base query engine as tool
query_engine_tools = [
    QueryEngineTool(
        query_engine=vector_query_engine,
        metadata=ToolMetadata(
            name="pg_essay",
            description="Paul Graham essay on What I Worked On",
        ),
    ),
]

query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context,
    use_async=True,
)

response = query_engine.query(
    "How was Paul Grahams life different before, during, and after YC?"
)

**Comment by logan-markewich** [comment]
@mingqxu7 you need to make sure you have the latest api_vesrion on your azure deployment. Some people have also noted you need to use new versions of some models (microsofts support on this is a little wacky)

https://github.com/run-llama/llama_index/issues/9118#issuecomment-1824967644
