### ISSUE TITLE
[Question]:  what is difference between ref doc id and node id? will there be ref doc id if i directly create index from nodes instead of documents?

### ISSUE THREAD

**Issue by pavansandeep2910** [run-llama/llama_index#9209]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

what is difference between ref doc id and node id? will there be ref doc id if i directly create index from nodes instead of documents?

**Comment by logan-markewich** [comment]
ref_doc_id is created when using a node parser to split documents into nodes.

If you use from_documents, or `node_parser.get_node_from_documents()`, nodes will have a ref_doc_id that points to the ID of the parent document
