### ISSUE TITLE
[Documentation]: Automated Metadata Extraction for Better Retrieval + Synthesis Nodes Reusage Question

### ISSUE THREAD

**Issue by aliozts** [run-llama/llama_index#9210]
### Documentation Issue Description

In your  [metadata extraction](https://docs.llamaindex.ai/en/stable/examples/metadata_extraction/MetadataExtraction_LLMSurvey.html#automated-metadata-extraction-for-better-retrieval-synthesis) documentation

You are creating the `nodes` utilizing the `node_parser` with

```python
orig_nodes = node_parser.get_nodes_from_documents(docs)
# take just the first 8 nodes for testing
nodes = orig_nodes[20:28]
```

Then the `ingestion_pipeline` is created with

`pipeline = IngestionPipeline(transformations=[node_parser, *extractors_1])`

Finally, it's being run with

```python
nodes_1 = pipeline.run(nodes=nodes, in_place=False, show_progress=True)
```

does not this run the `node_parser` on the inputs again?

### Documentation Link

https://docs.llamaindex.ai/en/stable/examples/metadata_extraction/MetadataExtraction_LLMSurvey.html#automated-metadata-extraction-for-better-retrieval-synthesis

**Comment by aliozts** [comment]
@dosu-bot `run_transformations` method uses the instance variable `self.transformations` which has the `node_parser` in it. `NodeParser` class' `__call__` method calls the `get_nodes_from_documents` method so it might be running. I did not find any type checks in the code as well.

**Comment by aliozts** [comment]
I still need feedback on this, it seems that it's called twice?

**Comment by aliozts** [comment]
ping

**Comment by logan-markewich** [comment]
@ravi03071991 yea just a bug, didn't mean to parse the nodes twice
