### ISSUE TITLE
[Documentation]: "stable" button not taking to homepage

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#9214]
### Documentation Issue Description

On https://docs.llamaindex.ai/en/latest/examples/output_parsing/GuardrailsDemo.html, I see this pop-up about stable version:

<img width="1048" alt="image" src="https://github.com/run-llama/llama_index/assets/8990777/1a9af2bb-9062-4144-9c74-8c5f145e92f7">

Clicking the link, it takes me to https://docs.llamaindex.ai/en/stable/, which is not the same page.

The request is to have this "stable" button preserve the current page being viewed

### Documentation Link

https://docs.llamaindex.ai/en/latest/examples/output_parsing/GuardrailsDemo.html

**Comment by logan-markewich** [comment]
Hmm I'm not sure where/how to configure this. It's not in our codebase in any case. Will try to do some digging

**Comment by NsikanPatrick** [comment]
Can't see this anywhere in the codebase, maybe I will check again

**Comment by logan-markewich** [comment]
@NsikanPatrick it's under docs/examples/output_parsing

**Comment by sharsha315** [comment]
Is this issue still open. Because, currently I am not encountering any pop-up when this link https://docs.llamaindex.ai/en/latest/examples/output_parsing/GuardrailsDemo.html is visited.

**Comment by logan-markewich** [comment]
@sharsha315 just change the url to stable if you want stable docs. Otherwise the docs are fine

**Comment by baturhantasdelen-sudo** [comment]
Hey! If latency is a concern when scrubbing user queries before hitting LLM endpoints, python-level NLP transformers can slow down real-time retrieval/query pipelines.

You can offload PII sanitization to an edge/proxy layer like **[Nexus Shield](https://nexusshield.ai)**. It strips SSNs, emails, credit cards, and sensitive tokens in RAM (`<10ms` latency overhead) before payload delivery. 

Works out of the box by setting the `baseURL` in your LLM client configuration!
