### ISSUE TITLE
[Question]: How to append a newly created KG index to an existing KG index using llama index?

### ISSUE THREAD

**Issue by patukuri** [run-llama/llama_index#9218]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Let's say I created a query engine/bot and asked a question with a  single pdf file(File 1) and I asked some questions to the query bot and it answered my questions from the created KG index for that pdf file(File 1). Now I will ask questions by giving another pdf file(File 2) , now it will create a new KG index but what I am looking for is the newly created index(For File 2) shouldn't override the existing KG index of the old pdf document(File 1)**(I need to append the new KG index to the old KG index)**, is this possible with llama index?

**Comment by TianyuFan0504** [comment]
@dosu-bot
How to directly append a new KnowledgeGraphIndex to a current KnowledgeGraphIndex?
The example you offered using 'upsert_triplet' and 'add_node' to merge two KnowledgeGraphIndex, however, it need to manually extract triplet&nodes from new KnowledgeGraphIndex.

Besides, in the 'add_node' function, what is the role of keywords? Can you give me some examples of ‘keywords’?
