### ISSUE TITLE
[Documentation]: rendering example notebooks in `docs/examples/`

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#9223]
### Documentation Issue Description

Can we have the example notebooks actually show up on https://docs.llamaindex.ai/en/stable/api_reference/example_notebooks.html?

There's a lot of content there that I think would be great to have indexed in the doc's search functionality.

### Documentation Link

https://docs.llamaindex.ai/en/stable/api_reference/example_notebooks.html

**Comment by logan-markewich** [comment]
@jamesbraza I don't think that will be easy to do. But all our notebooks are searchable now, thanks to this sneaky sitemap

https://github.com/run-llama/llama_index/blob/main/docs/_static/sitemap.xml

Algolia was only indexing notebooks that were linked somewhere. But adding this stiemap allows agolia to index ALL unlinked content/notebooks

Was there a specific notebook not searchable?

**Comment by jamesbraza** [comment]
Searching for "LocalAI" the example notebook I had made isn't showing up 😢 

![screenshot of LocalAIsearch](https://github.com/run-llama/llama_index/assets/8990777/27a92a1e-c83d-4915-a736-78223522e7e5)

Any idea why algolia isn't picking it up? If it's because it's not hyperlinked elsewhere, I will open a new PR to fix it

**Comment by logan-markewich** [comment]
@jamesbraza ideally, the reviewer should have noticed the notebook wasn't linked in `docs/module_guides/models/llms.md` 😉

**Comment by jamesbraza** [comment]
Yeah that is a solution, but I feel that's hard on reviewers. It would be nice to have automated controls for this sort of stuff. For reference, in my own repos, I use Sphinx's `apidoc` to auto-update docs sources each PR
