### ISSUE TITLE
Successful but Extremely Slow Response Time from LLM 

### ISSUE THREAD

**Issue by grabani** [run-llama/llama_index#9225]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am able to successfully receive a response running the following code, however, the response takes 4m 44.9s. When I use the same embeddings database but direct to openAI it is instance. Any ideas why the local LLM is taking so long!!
 
```
from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.vector_stores import ChromaVectorStore
from llama_index.storage.storage_context import StorageContext
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.llms import OpenAI
from IPython.display import Markdown, display
import chromadb

# define embedding function

embed_model = HuggingFaceEmbedding(model_name="BAAI/bge-base-en-v1.5")

# Load LLM

from llama_index import (
    SimpleDirectoryReader,
    VectorStoreIndex,
    ServiceContext,
)
from llama_index.llms import LlamaCPP
from llama_index.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)

llm = LlamaCPP(
    # You can pass in the URL to a GGML model to download it automatically
    #model_url=model_url,
    # optionally, you can set the path to a pre-downloaded model instead of model_url
    model_path=r"C:\Users\Home\.cache\lm-studio\models\TheBloke\Mistral-7B-Instruct-v0.1-GGUF\mistral-7b-instruct-v0.1.Q6_K.gguf",
    temperature=0.1,
    max_new_tokens=4048,
    # llama2 has a context window of 4096 tokens, but we set it lower to allow for some wiggle room
    context_window=8000,
    # kwargs to pass to __call__()
    generate_kwargs={},
    # kwargs to pass to __init__()
    # set to at least 1 to use GPU
    #model_kwargs={"n_gpu_layers": 1},
    # transform inputs into Llama2 format
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose=True,
)

# load embeddings from disk

db2 = chromadb.PersistentClient(path="./data/jhoward_L4/chroma_db")

chroma_collection = db2.get_or_create_collection("DB_collection")

vector_store = ChromaVectorStore(chroma_collection=chroma_collection)

service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model,
                                               chunk_size=100,
                                               chunk_overlap=20)

index = VectorStoreIndex.from_vector_store(
    vector_store,
    service_context=service_context,
)
# Response synthesis
query_engine = index.as_query_engine()

response = query_engine.query("What is lesson about?")

display(Markdown(f"{response}"))
```

**Comment by logan-markewich** [comment]
Your LlamaCPP runs on CPU. You can also compile llama-cpp-python to run on GPU, but even then, it will be much slower than OpenAI.

If you want a faster local LLM, you need a good GPU and probably need to use an optimized service like vLLM or HuggingFace text-generation-interface

**Comment by rawkintrevo** [comment]
![image](https://github.com/run-llama/llama_index/assets/5852441/291a897d-83aa-4db9-8ebc-7c89dbd9d097)
> Debugging isn't useful either

is not a useful gripe- so there is a screenshot of the debugging output- it took 25m on first run, 4m on second run.

**Comment by rawkintrevo** [comment]
LlamaCPP stand alone - 38s
![image](https://github.com/run-llama/llama_index/assets/5852441/cd5b8678-b080-4783-9fe9-5fc8df081708)

**Comment by rawkintrevo** [comment]
Further @logan-markewich - the issue seems to be something happening in the background- Once it starts going, it works as expected, its just that it take 24m/3m for it to get things together and start printing output.

**Comment by rawkintrevo** [comment]
now this is more for the next person on the search (ie me next week), than part of a bug report. when moving from streaming to normy query, the debugging is more useful. 
![image](https://github.com/run-llama/llama_index/assets/5852441/9f4dca6d-8edc-4ca3-b97a-784a46ef9798)

**Comment by rawkintrevo** [comment]
Is there anyway to turn up the fidelity on the logs and find out what is taking so long in `_llm` ?

**Comment by logan-markewich** [comment]
Not really tbh

In your example of using llamacpp standalone,  you are only passing in a very short prompt, and not generating very many tokens.

You can check out the source code here to compare or investigate. But llamaindex isn't really doing anything special, just calling the LLM with possibly large inputs 
https://github.com/run-llama/llama_index/blob/e3591ba9d856168273e9f74432829ae1718f8a5b/llama_index/llms/llama_cpp.py#L96

**Comment by logan-markewich** [comment]
You can also enable logging to see every llm input and output
https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html#simple-llm-inputs-outputs

**Comment by rawkintrevo** [comment]
OK, I played with it some more when I got home and thanks so much for the pointers and reply @logan-markewich 

I got it to a point where it's at least usable for my usecase. Some tips for anyone else who happens this way:
1. Make super baby chunk sizes via `TextSplitter`
2. Be prepared to tinker with the response synthesizer, at least grok the ResponseModes
3. Keep your top_k as low as you dare. 
4. It _will_ still be a dog compared to OpenAI or some fancy service with GPUs or GPUs on your own machine, but if you have some time to learn it, and not just copy paste a recipe, you _can_ make this work in a Cloud Function, and by that I mean getting responses in < 4 min.

@logan-markewich if y'all would take a drive-by commit of docs on hypermilling eg running lamma-index effectively on CPU _only_ I'd be happy to write something up, let me know where to drop it. If not, here is a (sloppy/hacked up) colab of my adventures, designed to help the next person. 

Also, in either event, great work and thanks so much for such a great product!

https://colab.research.google.com/drive/1VXcD9YBLCap7CT23V8qF-UCm0h9wIlrB?usp=sharing

**Comment by grabani** [comment]
Share my test results and thoughts:

Note:
1) I used your @rawkintrevo's colab
2) Used the `OpenAIEmbedding ` embeddings model & the `mistral-7b-instruct-v0.1.Q6_K.gguf` LLM model.
3) Retrieved my data (Index) from an existing `ChromadB` collection. Note when the index was created it included the ServiceContext parameter `node_parser=sentence_node_parser`
4) Added Token Counter Handling:
```
token_counter = TokenCountingHandler(
verbose=True,  # set to true to see usage printed to the console
)

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug,token_counter])
```
5) My results:
![image](https://github.com/run-llama/llama_index/assets/25469154/cbfeaf8d-b63c-4779-a65e-a926b44e2159)

6) This is the output of the counter handling:

![image](https://github.com/run-llama/llama_index/assets/25469154/4f858f1a-3dbe-4791-8da8-9b87084c6972)

7) The overall time for the two LLM queries is:

![image](https://github.com/run-llama/llama_index/assets/25469154/16795d86-8cd7-4a5e-94d7-629d941eeca6)

8) Then as a comparison I used `LM Studio`. Used the same LM Model as in the colab. Set up my `system prompt` (see as per the details captured in `point #6`).

9) My results on `LM Studio` directly were:

![image](https://github.com/run-llama/llama_index/assets/25469154/4f14ec08-015c-4c3d-95c6-59c79ffad131)

I am running with windows 11 , intel i5 (12th Gen), 16GB RAM, GPU (Intel Iris(R).

**CONCLUSION**

The time taken to run the query via Llamaindex was **NOT** significantly longer than when ran using LM Studio. Seems that Llamindex itself does not cause unnecessary delay. As can be seen from the `CBEevent `times, the pre LLM times are insignificant.
