### ISSUE TITLE
[Bug]: HuggingFaceLLM not working for HuggingFaceH4/zephyr-7b-beta   Key Error mistral (or load_in_8bit=True) error depending on transformer version

### ISSUE THREAD

**Issue by defiways** [run-llama/llama_index#9230]
### Bug Description

ImportError: Using `load_in_8bit=True` requires Accelerate: `pip install accelerate` and the latest version of bitsandbytes `pip install -i https://test.pypi.org/simple/ bitsandbytes` or pip install bitsandbytes` 

But this can only be corrected by downgrading to transformers=4.30  and when that is done it introduces another error

KeyError                                  Traceback (most recent call last)

[<ipython-input-7-bb690c4074f5>](https://localhost:8080/#) in <cell line: 8>()
      6 )
      7 
----> 8 llm = HuggingFaceLLM(
      9     model_name="HuggingFaceH4/zephyr-7b-beta",
     10     tokenizer_name="HuggingFaceH4/zephyr-7b-beta",

3 frames

[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py](https://localhost:8080/#) in __getitem__(self, key)
    669             return self._extra_content[key]
    670         if key not in self._mapping:
--> 671             raise KeyError(key)
    672         value = self._mapping[key]
    673         module_name = model_type_to_module_name(key)

KeyError: 'mistral'

This model must have the latest transformers to run

### Version

latest

### Steps to Reproduce

!pip install llama-index transformers==4.30 accelerate bitsandbytes

#run this without downgrade of transformers and you will see error above. 

quantization_config = BitsAndBytesConfig(
  load_in_4bit=True,
  bnb_4bit_compute_dtype=torch.float16,
  bnb_4bit_quant_type="nf4",
  bnb_4bit_use_double_quant=True
)

llm = HuggingFaceLLM(
    model_name="HuggingFaceH4/zephyr-7b-beta",
    tokenizer_name="HuggingFaceH4/zephyr-7b-beta",
    query_wrapper_prompt=PromptTemplate("<|system|>\n</s>\n<|user|>\n{query_str}</s>\n<|assistant|>\n"),
    context_window=3900,
    max_new_tokens=256,
    model_kwargs={"quantization_config": quantization_config},
    # tokenizer_kwargs={},
    generate_kwargs={"temperature": 0.7, "top_k": 50, "top_p": 0.95},
    messages_to_prompt=messages_to_prompt,
    device_map="auto",
)

### Relevant Logs/Tracbacks

```shell
KeyError                                  Traceback (most recent call last)

<ipython-input-7-bb690c4074f5> in <cell line: 8>()
      6 )
      7 
----> 8 llm = HuggingFaceLLM(
      9     model_name="HuggingFaceH4/zephyr-7b-beta",
     10     tokenizer_name="HuggingFaceH4/zephyr-7b-beta",

3 frames

/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py in __getitem__(self, key)
    669             return self._extra_content[key]
    670         if key not in self._mapping:
--> 671             raise KeyError(key)
    672         value = self._mapping[key]
    673         module_name = model_type_to_module_name(key)

KeyError: 'mistral'
```

**Comment by logan-markewich** [comment]
@defiways sorry, but this is not a bug with LlamaIndex? This is just HuggingFace usage.

I have an example of using zephyr here in any case that runs fine in colab
https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

Going to close, but let me know if otherwise.

**Comment by defiways** [comment]
I think that was the notebook I was running when I got the error. trying it again and now this is what I see:

[/usr/local/lib/python3.10/dist-packages/transformers/modeling_utils.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, config, cache_dir, ignore_mismatched_sizes, force_download, local_files_only, token, revision, use_safetensors, *model_args, **kwargs)
   3418                 }
   3419                 if "cpu" in device_map_without_lm_head.values() or "disk" in device_map_without_lm_head.values():
-> 3420                     raise ValueError(
   3421                         """
   3422                         Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit

ValueError: 
                        Some modules are dispatched on the CPU or the disk. Make sure you have enough GPU RAM to fit
                        the quantized model. If you want to dispatch the model on the CPU or the disk while keeping
                        these modules in 32-bit, you need to set `load_in_8bit_fp32_cpu_offload=True` and pass a custom
                        `device_map` to `from_pretrained`. Check
                        https://huggingface.co/docs/transformers/main/en/main_classes/quantization#offload-between-cpu-and-gpu
                        for more details.

**Comment by logan-markewich** [comment]
Yew this isnt really a small model -- 7B is quite big for most consumer hardware. 

If I wasn't running the quantization in the notebook (and instead running a pre-quantized model) the gpu reqs might be lower
