### ISSUE TITLE
[Question]: LLM response cache for decreasing payment

### ISSUE THREAD

**Issue by sjinwoo** [run-llama/llama_index#9243]
### Question Validation

- [x] I have searched both the documentation and discord for an answer.

### Question

Hi. I'm building an LLM-based RAG service, and I want to return a 'cached answer' without using a token when a question with the same content is entered.
The 'cache' argument to LLMPredictor seems to disappear as the version is upgraded.
Is there an alternative?
Thanks. :)

**Comment by sjinwoo** [comment]
I tried it by changing only LLM to Langchain, but I get an error in the callback.

Please see below.

>   File "C:\Users\jwson\Desktop\code\.venv\lib\site-packages\llama_index\callbacks\base.py", line 116, in on_event_end
    handler.on_event_end(event_type, payload, event_id=event_id, **kwargs)
  File "C:\Users\jwson\Desktop\code\.venv\lib\site-packages\llama_index\callbacks\token_counting.py", line 150, in on_event_end
    get_llm_token_counts(
  File "C:\Users\jwson\Desktop\code\.venv\lib\site-packages\llama_index\callbacks\token_counting.py", line 49, in get_llm_token_counts
    usage = response.raw["usage"]  # type: ignore
TypeError: 'NoneType' object is not subscriptable

**Comment by ravi03071991** [comment]
Hi @sjinwoo,

Did you check `portkey` as they offer semantic caching capability? You can check about it in the [docs](https://docs.llamaindex.ai/en/stable/examples/llm/portkey.html).
