### ISSUE TITLE
[Question]: How to delete nodes using node ids from index which is VectorStoreIndex instance when created directly using nodes instead of documents?

### ISSUE THREAD

**Issue by pavansandeep2910** [run-llama/llama_index#9245]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to delete nodes using node ids from the index which is a VectorStoreIndex instance when created directly using nodes instead of documents?

I tried the delete_nodes method to delete nodes using node IDs. but got the following error:

```
Traceback (most recent call last):
  File "/Users/pavan/Documents/GitHub/sentinel-ai-analytics-backend/scripts/create_few_shot_samples_embeddings.py", line 81, in <module>
    index.delete_nodes(deletableNodeIds)
  File "/Users/pavan/Documents/GitHub/sentinel-ai-analytics-backend/venv/lib/python3.11/site-packages/llama_index/indices/vector_store/base.py", line 286, in delete_nodes
    raise NotImplementedError(
NotImplementedError: Vector indices currently only support delete_ref_doc, which deletes nodes using the ref_doc_id of ingested documents.
```

**Comment by npulaparthi** [comment]
I am also face same issue to delete data in GPTVectorStoreIndex so used information given to solve but again I face issue to call the index to indexdict I called the vector_store.json assign it as IndexDict but I am getting type error 
how can I give the vector index that I have created to vector_store_index_instance   to delete the document nodes that I don't want

vector_store_index_instance  = GPTVectorStoreIndex(BaseIndex[IndexDict])

vector_store_index_instance.delete_ref_doc(ref_doc_id, delete_from_docstore=True)

TypeError("object of type '_GenericAlias' has no len()")

**Comment by mdhuzaifapatel** [comment]
> @pavansandeep2910 there is not. It needs fo be implemented.
> 
> Feel free to open a PR though

Hey, is it implemented now? Please let me know, I want to delete nodes.

**Comment by cydcydcyd** [comment]
@mdhuzaifapatel 
milvus vector store support delete nodes
