### ISSUE TITLE
[Question]: Can not load my index created locally

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#9268]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

thanks for the great framework, I’m having a lot of fun with it. I’m trying to setup a RAG app using only local LLMs. Specifically Zephyr 7b as LLM and Multilingual E5 large for embedding. I have also created a persistent chromadb index:

```

llm = LlamaCPP(
    model_path="./llms/zephyr-7b-alpha.Q5_K_M.gguf",
    temperature=0.0,
    max_new_tokens=1024,
    context_window=3900,  
    model_kwargs={"n_gpu_layers": 4}, 
)

from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large")

service_context = ServiceContext.from_defaults(
    llm=llm, 
    embed_model="local", 
    chunk_size=512, 
    chunk_overlap=20
)

import chromadb
from llama_index.vector_stores import ChromaVectorStore
chroma_client = chromadb.PersistentClient()
chroma_collection = chroma_client.create_collection("collection", get_or_create = True)
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
storage_context = StorageContext.from_defaults(vector_store=vector_store)

documents = SimpleDirectoryReader("data").load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context, storage_context=storage_context)
index.storage_context.persist()
   
```
So far so good. Now, my problem is that when I try to load this index when I re-run my app, I get an error coming from this line of code:

```
index = load_index_from_storage(storage_context, service_context=service_context)
```

```
File "\miniconda3\envs\llamaindex\lib\site-packages\llama_index\storage\storage_context.py", line 209, in vector_store
    return self.vector_stores[DEFAULT_VECTOR_STORE]
KeyError: 'default'
```

What am I doing wrong?

**Comment by logan-markewich** [comment]
@stephanedebove when you use a vector db, by default, all data is persisted in the vector store alone. So no need to call persist or load

To connect to an existing index created in chroma (or any vector store) , you can do

```
vector_store = <points to existing ChromaVectorStore>
index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)
```

**Comment by stephanedebove** [comment]
oh ok I missed that. I am not sure I really need Chromadb though. I switched to chromadb because when I was trying to load my index from storage with the default vector store, I was getting an error: "Could not load OpenAI model." (on this line: `index = load_index_from_storage(storage_context)` ).

But I don’t really understand why OpenAI is needed at this stage... So can I stick with the default vector store without using OpenAI, or should I switch to chromadb?
