### ISSUE TITLE
[Feature Request]: Adding Table(s) to Knowledge graph building using LLM's

### ISSUE THREAD

**Issue by Kirushikesh** [run-llama/llama_index#9269]
### Feature Description

Building the table(s) to knowledge graph with the help of LLM's. Happy to take lead and start working for the PR :)

### Reason

Querying and indexing the existing table is always a pain point with the size of table grows. As KnowledgeGraphIndex in llama-index is adapted for converting documents into knowledge graph, a similar advantages build when trying to convert a table into knowledge graph. 

### Value of Feature

With Table entities converted to knowledge graphs the implicit relations between the entities can be explicitly modelled, even the relations between different tables can be brought to a single graph which is easy to query and index compared to the tables.

**Comment by logan-markewich** [comment]
@Kirushikesh if you have an idea for how to implement this, would love to see it!

Would this be a new type of index for tables? Or something else? Curious what you think

I agree, tables are very tough for LLMs. They are hard to properly extract/identify, and they are hard for LLMs to reason over 😅

**Comment by Kirushikesh** [comment]
@logan-markewich thanks for the appreciation. I am thinking in the direction to use the existing KnowledgeGraphIndex to store the knowledge graph extracted from the table, so we already have`KnowledgeGraphIndex.from_documents()` which generates triplets from documents either using OpenAI model/REBEL if i am not wrong? Similarly we can extent it to `KnowledgeGraphIndex.from_table()` to extract triplets from a lets say a csv table.

Now, to extract triplets from a table, i was assuming to first convert table to text and using that with existing approaches to extract the triplets. I know this is a indirect route instead of directly extracting triplets from the table, i was just thinking aloud. Let me know if you think otherwise.
