### ISSUE TITLE
[Question]: RAG apps in other languages than english

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#9274]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi everyone,

this is not a question related to Llama-index specifically, but I think you’re the most qualified to answer with your experience in RAG apps.

Although I have now read a lot of documentation and seen a lot of videos about building RAG apps, I haven’t seen much about building RAG apps in other languages than english (specifically french in my case).

I have seen that some embedding models are "multilingual", and the best one on the HuggingFace leaderboard is currently "multilingual E5 large". Does anyone have experience about using it? Does it make a big difference compared to non-multilingual models?

And do you know if some LLMs used for response synthesis are better than others for dealing with non-english languages? This is never mentioned in their doc, but if we have multilingual models for embeddings, I don’t see why we wouldn’t have multilingual models for response synthesis too.

Do you know any good resource talking about this subject, or do you have experience in this?

**Comment by dinonovak** [comment]
Following the same topic, I am having the same struggles so would be nice to get some feedback from real cases.
I am also wondering on experience with difference models.

**Comment by last-Programmer** [comment]
I am also facing this issue i am using ollamaembedding with nomic-embed-text and with langchain rag i am getting reponse in portuguese. but when i try with llama index rag it always responds in english. i tried changing prompt templates to include like "you always answer in portuguese" it did not help either.
