### ISSUE TITLE
[Question]: PromptTemplate seems to mess up the answer

### ISSUE THREAD

**Issue by stephanedebove** [run-llama/llama_index#9277]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Following the documentation, I have been building a small app creating an index from a docx file (containing a FAQ) and then simply answering the question from the user. It works pretty well, except when I start to customize the prompt template. Then, instead of just giving me my answer, it gives me my answer as well as a couple of other questions and answers it found in my file.

So this is working well:

```
import logging
import sys
from llama_index.llms import LlamaCPP
from llama_index.prompts import PromptTemplate
import os.path
from llama_index import (
    VectorStoreIndex,
    SimpleDirectoryReader,
    StorageContext,
    load_index_from_storage,
    ServiceContext,
    PromptHelper,
)

llm = LlamaCPP(
    model_path="./llms/zephyr-7b-alpha.Q5_K_M.gguf",
    temperature=0.0,
    max_new_tokens=1024,
    context_window=3900, 
    model_kwargs={"n_gpu_layers": 4}, 
)

from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large")

service_context = ServiceContext.from_defaults(
    llm=llm, 
    embed_model="local:intfloat/multilingual-e5-large", 
    chunk_size=512, 
    chunk_overlap=20
)

if not os.path.exists("./storage"):
    documents = SimpleDirectoryReader("data").load_data()
    index = VectorStoreIndex.from_documents(documents, service_context=service_context, show_progress=True)
    index.storage_context.persist()
else:
    storage_context = StorageContext.from_defaults(persist_dir="./storage")
    index = load_index_from_storage(storage_context, service_context=service_context)

query_engine = index.as_query_engine( service_context=service_context, similarity_top_k=2,response_mode="compact")
response = query_engine.query("What is the meaning of life ?")
print(response)  
```

but if I add

```
template = (
    "Using this context : \n"
    "---------------------\n"
    "{context_str}"
    "\n---------------------\n"
    "Answer this question : {query_str}\n"
    "If the answer is not in the context, say 'I don’t know, sorry'. » "
)
qa_template = PromptTemplate(template)
```

and change the query_engine to:

`query_engine = index.as_query_engine( service_context=service_context, similarity_top_k=2,response_mode="compact",text_qa_template=qa_template)
`

it just starts giving me complicated and non-relevant outputs. Any idea why?

**Comment by logan-markewich** [comment]
@stephanedebove zephyr requires a very specific template format
https://huggingface.co/HuggingFaceH4/zephyr-7b-alpha#intended-uses--limitations

I recommend using the `messages_to_prompt` and `completion_to_prompt` kwargs that will format your inputs properly, 

(Alternatively, you'll need to modify the qa and refine templates, plus templates for other features you use, which is a lot more work)

**Comment by logan-markewich** [comment]
@stephanedebove replicate has the same kwargs

There's a small example here I made for zephyr in another notebook

```
def messages_to_prompt(messages):
  prompt = ""
  for message in messages:
    if message.role == 'system':
      prompt += f"<|system|>\n{message.content}</s>\n"
    elif message.role == 'user':
      prompt += f"<|user|>\n{message.content}</s>\n"
    elif message.role == 'assistant':
      prompt += f"<|assistant|>\n{message.content}</s>\n"

  # ensure we start with a system prompt, insert blank if needed
  if not prompt.startswith("<|system|>\n"):
    prompt = "<|system|>\n</s>\n" + prompt

  # add final assistant prompt
  prompt = prompt + "<|assistant|>\n"

  return prompt


def completion_to_prompt(completion):
  return "<|system|>\n</s>\n<|user|>\n{completion}</s>\n<|assistant|>\n".format(completion=completion)

llm = LlamaCPP(..., messages_to_prompt=messages_to_prompt, completion_to_prompt=completion_to_prompt)
```

This will take the template (or messages) and ensure they are formatted correctly. Most LLMs have a different format, this is for zephyr

In the llama-cpp examples, we have these functions for llama2 built-in and provided.
https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html#setup-llm

https://github.com/run-llama/llama_index/blob/b704423c76033d9ff4e6a2e6a67b60221360a4bb/llama_index/llms/llama_utils.py#L16
