### ISSUE TITLE
[Bug]: Chroma.py breaks when using InstructorEmbedding

### ISSUE THREAD

**Issue by mphipps2** [run-llama/llama_index#9286]
### Bug Description

I'm able to use faiss locally with either Instructor (InstructorEmbedding) or HuggingFace Embeddings (HuggingFaceEmbedding) models, and I'm able to use chroma locally with the HF models, but when I try to use it with the Instruct models I get value errors when chromadb does type checks on the embeddings in this function (chromadb/api/types.py):

def validate_embeddings(embeddings: Embeddings) -> Embeddings:
    """Validates embeddings to ensure it is a list of list of ints, or floats"""
    if not isinstance(embeddings, list):
        raise ValueError(f"Expected embeddings to be a list, got {embeddings}")
    if len(embeddings) == 0:
        raise ValueError(
            f"Expected embeddings to be a list with at least one item, got {embeddings}"
        )
    if not all([isinstance(e, list) for e in embeddings]):
        print('type: ', type(embeddings), ' type embeddings[0]: ' , type(embeddings[0]))
        raise ValueError(
            f"Expected each embedding in the embeddings to be a list, got {embeddings}"
        )
    for embedding in embeddings:
        if not all([isinstance(value, (int, float)) for value in embedding]):
            raise ValueError(
                f"Expected each value in the embedding to be a int or float, got {embeddings}"
            )
    return embeddings
    

This is triggered when adding both the context and query embeddings to chromadb in lines 243 and 287 from this file:
https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/chroma.py. In the context embedding case this is happening because chromadb wants the embeddings to be a list of lists, not a list of numpy arrays. Then in the query case, the query embeddings are being sent to chromadb as a list of np.float32. Chroma wants it as a list of list of native floats. 

To fix this problem I think you can do this (tested successfully with Chroma using either Instruct embeddings or HF):

in llama_index/vector_stores/chroma.py:

1) import numpy as np

2)     def add(self, nodes: List[BaseNode], **add_kwargs: Any) -> List[str]:
        """Add nodes to index.

        Args:
            nodes: List[BaseNode]: list of nodes with embeddings

        """
        if not self._collection:
            raise ValueError("Collection not initialized")

        max_chunk_size = MAX_CHUNK_SIZE
        node_chunks = chunk_list(nodes, max_chunk_size)

        all_ids = []
        for node_chunk in node_chunks:
            embeddings = []
            metadatas = []
            ids = []
            documents = []
            for node in node_chunk:
                embedding = node.get_embedding()
                # Convert the embedding to a list if it's a NumPy array
                if isinstance(embedding, np.ndarray):
                    embedding = embedding.tolist()
                embeddings.append(embedding)
                
3)       def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:
        """Query index for top k most similar nodes.

        Args:
            query_embedding (List[float]): query embedding
            similarity_top_k (int): top k most similar nodes

        """
        if query.filters is not None:
            if "where" in kwargs:
                raise ValueError(
                    "Cannot specify metadata filters via both query and kwargs. "
                    "Use kwargs only for chroma specific items that are "
                    "not supported via the generic query interface."
                )
            where = _to_chroma_filter(query.filters)
        else:
            where = kwargs.pop("where", {})

        # Convert query_embedding to the correct format
        query_embedding = query.query_embedding
        if isinstance(query_embedding, np.ndarray):
            query_embedding = query_embedding.tolist()
        if isinstance(query_embedding, list) and not isinstance(query_embedding[0], list):
            query_embedding = [query_embedding]

        # Convert each numpy.float32 element to a native Python float
        query_embedding = [[float(value) for value in emb] for emb in query_embedding]

        results = self._collection.query(
            query_embeddings=query_embedding,
            n_results=query.similarity_top_k,
            where=where,
            **kwargs,
        )

### Version

v0.9.11

### Steps to Reproduce

Set your embeddings model as "local:hkunlp/instructor-xl" and initialize your vector store as ChromaVectorStore:
        chroma_client = chromadb.EphemeralClient()
        chroma_collection = chroma_client.create_collection("quickstart")
        vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
        
Will result in ValueErrors from chromadb

**Comment by logan-markewich** [comment]
I just put a fix related to converting instructor embeddings to the correct type.

Are you sure you had 0.9.11 installed? It should be returning List[float] now

**Comment by mphipps2** [comment]
Great! I put the latest version because I'd just pulled recently. Let me repull then and try again
