### ISSUE TITLE
[Question]: How to use cosine similarity mode in VectorIndexRetriever?

### ISSUE THREAD

**Issue by pavansandeep2910** [run-llama/llama_index#9305]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I created an index which is of instance VectorStoreIndex with embeddings using the OpenAIEmbedding model. I am using a retriever which is of instance VectorIndexRetriever to get the top k similar nodes(which compares the embeddings). what is the default mode the retriever uses to get similar nodes? How can I use the cosine similarity mode if it does not use it as the default mode?

**Comment by logan-markewich** [comment]
The default is cosine similarity, and it is not configurable, at least for the base vector store. Other vector stores might offer ways to change this.
