### ISSUE TITLE
[Question]: Using Local LLM for Image to Image instead of openai

### ISSUE THREAD

**Issue by BakingBrains** [run-llama/llama_index#9309]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was trying out Image to Image Retrieval, can anyone suggest how can I use local LLM in place of openai for Image to Image Retrieval.

Regards

**Comment by BakingBrains** [comment]
@dosu-bot 

Can you give end to end demo example code

Regards

**Comment by ravi03071991** [comment]
Hi @BakingBrains ,

You can use following snippet to use open source LLM via Replicate.

```
import os
from llama_index.llms import Replicate

os.environ["REPLICATE_API_TOKEN"] = ""  # add your replicate api token here

multi_modal_llm = ReplicateMultiModal(
    model="yorickvp/llava-13b:2facb4a474a0462c15041b78b1ad70952ea46b5ec6ad29583c0b29dbd4249591",
    max_new_tokens=100,
    temperature=0.1,
    num_input_files=1,
    top_p=0.9,
    num_beams=1,
    repetition_penalty=1,
)

response = multi_modal_llm.complete(
    prompt="Given the first image as the base image, what the other images correspond to?",
    image_documents=image_documents,
)

print(response)
```

You can the [notebook](https://github.com/run-llama/llama_index/blob/main/docs/examples/multi_modal/replicate_multi_modal.ipynb) for more details.

**Comment by BakingBrains** [comment]
Thank you @ravi03071991 

Apart from replicate can I use any local vector DB.

Any suggestions here?

**Comment by Ashwariya2310** [comment]
@dosu-bot

I am using replicate api token to use llama2 hosted on replicate
however, I am facing error saying

You did not pass an authentication token

**Comment by tsantra** [comment]
@dosu-bot how do we use local multimodal llm for generation after retrieval?
