### ISSUE TITLE
[Bug]: Response is Empty

### ISSUE THREAD

**Issue by shivanandmn** [run-llama/llama_index#9311]
### Bug Description

https://github.com/run-llama/llama_index/blob/b7188a3423e094b509cda5845cbc04e83f99f144/llama_index/llms/huggingface.py#L278 on this line you are trimming predicted tokens with `inputs["input_ids"].size(1)`, but that is trimming all the predictions and hence I am getting empty response

### Version

0.8.68

### Steps to Reproduce

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
from llama_index.llms import HuggingFaceLLM

model = AutoModelForSeq2SeqLM.from_pretrained("google/flan-t5-large")
tokenizer = AutoTokenizer.from_pretrained("google/flan-t5-large")
hug_llm = HuggingFaceLLM(model=model, tokenizer=tokenizer)

prompt = \
"""'Answer based on context:\n\nI learned some useful things at Interleaf, though they were mostly about what not to do. I learned that it\'s better for technology companies to be run by product people than sales people (though sales is a real skill and people who are good at it are really good at it), that it leads to bugs when code is edited by too many people, that cheap office space is no bargain if it\'s depressing, that planned meetings are inferior to corridor conversations, that big, bureaucratic customers are a dangerous source of money, and that there\'s not much overlap between conventional office hours and the optimal time for hacking, or conventional offices and the optimal place for it.\n\nBut the most important thing I learned, and which I used in both Viaweb and Y Combinator, is that the low end eats the high end: that it\'s good to be the "entry level" option, even though that will be less prestigious, because if you\'re not, someone else will be, and will squash you against the ceiling. Which in turn means that prestige is a danger sign.\n\nWhat happened at interleaf?'
"""
hug_llm.complete(prompt)

**Comment by logan-markewich** [comment]
@shivanandmn this line of code works fine in LLMs I've tested.

HuggingFace LLMs that I've tested all output the original text PLUS predicted text. This code is trimming it so only predicted text is returned.

The only LLM I can see this being an issue with is something like T5, since its encoder-decoder and not decoder only. What LLM are you using?

**Comment by shivanandmn** [comment]
Currently I am trying to use custom like this

```
class CustomHuggingFaceLLM(HuggingFaceLLM):
    @llm_completion_callback()
    def complete(self, prompt: str, **kwargs: Any) -> CompletionResponse:
        """Completion endpoint."""
        full_prompt = prompt
        is_formatted = kwargs.pop("formatted", False)
        if not is_formatted:
            if self.query_wrapper_prompt:
                full_prompt = self.query_wrapper_prompt.format(query_str=prompt)
            if self.system_prompt:
                full_prompt = f"{self.system_prompt} {full_prompt}"

        inputs = self._tokenizer(full_prompt, return_tensors="pt")
        inputs = inputs.to(self._model.device)

        # remove keys from the tokenizer if needed, to avoid HF errors
        for key in self.tokenizer_outputs_to_remove:
            if key in inputs:
                inputs.pop(key, None)

        tokens = self._model.generate(
            **inputs,
            max_new_tokens=self.max_new_tokens,
            stopping_criteria=self._stopping_criteria,
            **self.generate_kwargs,
        )
        completion = self._tokenizer.decode(tokens[0], skip_special_tokens=True)

        return CompletionResponse(text=completion, raw={"model_output": tokens})
```
Is this okay?
