### ISSUE TITLE
[Question]: langchain integration demo 

### ISSUE THREAD

**Issue by cyliu0204** [run-llama/llama_index#9312]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

https://github.com/run-llama/llama_index/blob/main/examples/langchain_demo/LangchainDemo.ipynb 

when I run the second demo, I always get the result like follows:

> 
> Entering new AgentExecutor chain...
INFO:httpx:HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
Thought: Do I need to use a tool? No
AI: Hi Bob! It's nice to meet you. How can I assist you today?

> Finished chain.
Hi Bob! It's nice to meet you. How can I assist you today?
INFO:httpx:HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"

> Entering new AgentExecutor chain...
INFO:httpx:HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
Thought: Do I need to use a tool? Yes
Action: Named Entity Recognition (NER)
Action Input: "what's my bob's age?"
Observation: Named Entity Recognition (NER) is not a valid tool, try one of [].
Thought:INFO:httpx:HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://openai-oneapi.atompai.com/v1/chat/completions "HTTP/1.1 200 OK"
Do I need to use a tool? No
AI: I'm sorry, I don't have access to personal information such as Bob's age.

> Finished chain.
I'm sorry, I don't have access to personal information such as Bob's age.

I debug it and get it running normally by comment the  return_source=True line,；
and it was this line caused this issue:
`source_messages = [
                    m for id, m in self.id_to_message.items() if id in source_ids
                ]`

 can anyone give any explaination about this ?

**Comment by ravi03071991** [comment]
Hi @cyliu0204,

Which version of LlamaIndex and OpenAI are you on? can you help us replicate the issue?

**Comment by cyliu0204** [comment]
> Hi @cyliu0204,
> 
> Which version of LlamaIndex and OpenAI are you on? can you help us replicate the issue?

llama-index              0.9.11.post1
langchain                0.0.345
langchain-core           0.0.9
langchain-experimental   0.0.43

and the code is exactly the same as the demo

**Comment by cyliu0204** [comment]
@ravi03071991  Any  updates here?
