### ISSUE TITLE
[Question]: Does the Cohere llama-index interface support RAG

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#9313]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have tried to use Cohere as my llm for a RAG service context but the cohere llm doesn't seem to answer based on any retrieved information. It answers based on prior knowledge. What could be the issue?

**Comment by ravi03071991** [comment]
Hi @gich2009 ,

Haven't faced such issue in my experiments. One way to look is if you are able retrieve the right chunks? If not then there should be an issue with embedding model.

**Comment by gich2009** [comment]
Hi @ravi03071991, Let me try writing a script and see if I'll Replicate the issue and post it here. Thanks for the prompt help.

**Comment by gich2009** [comment]
Hi @ravi03071991, I've been able to trace the issue. So when the service_context has LLM as Cohere and embed_model as CohereEmbeddings, then it is passed into the query engine, it works pretty well. 

But when the same conditions are used but for a chat engine, the Cohere LLM uses it's prior knowledge. Let me give you the scripts then you can try and run them on your side: 

### Query Engine script:
import os   
import openai
from llama_index import (
  VectorStoreIndex,     #This is a database for embeddings.
  SimpleDirectoryReader,  #This takes the document and splits it into sections(nodes or chunks), then does embedding.
  StorageContext,         #This specifies which database to use for storing embeddings.
  load_index_from_storage, #This is a function that helps you load embeddings from your vector store
  ServiceContext,
  set_global_service_context
)
from llama_index.embeddings import CohereEmbedding, OpenAIEmbedding
from llama_index.llms import Cohere
from llama_index.prompts import PromptTemplate
from dotenv import load_dotenv
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

load_dotenv()
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
model = "command"
temperature = 0.5

COHERE_API_KEY = os.getenv('COHERE_API_KEY')   

# embed_model = CohereEmbedding(cohere_api_key=COHERE_API_KEY)
embed_model = OpenAIEmbedding(api_key=OPENAI_API_KEY)

service_context = ServiceContext.from_defaults(llm=Cohere(model=model, temperature=temperature, api_key=COHERE_API_KEY), embed_model=embed_model)
set_global_service_context(service_context)



# check if storage already exists
if (not os.path.exists('./storage')):
    documents = SimpleDirectoryReader('data').load_data()
    index = VectorStoreIndex.from_documents(documents=documents, service_context=service_context)
    index.storage_context.persist()
else:
    # load the existing index
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
    index = load_index_from_storage(storage_context)


query_engine = index.as_query_engine(service_context=service_context)


def query_bot(prompt: str):
    response = query_engine.query(prompt)
    # print(response.__repr__())
    return response.response



if __name__=='__main__':
    test_prompts = [
        #Insert test prompts
    ]
    for test_prompt in test_prompts:
        response = query_bot(prompt=test_prompt)
        print(response)



### Chat Engine    
import os   
import openai
from llama_index import (
  VectorStoreIndex,     #This is a database for embeddings.
  SimpleDirectoryReader,  #This takes the document and splits it into sections(nodes or chunks), then does embedding.
  StorageContext,         #This specifies which database to use for storing embeddings.
  load_index_from_storage, #This is a function that helps you load embeddings from your vector store
  ServiceContext,
  set_global_service_context
)
from llama_index.llms import Cohere
from llama_index.embeddings import CohereEmbedding, OpenAIEmbedding
from dotenv import load_dotenv
import logging
import sys
logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

load_dotenv()
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')
model = "command"
temperature = 0.5

COHERE_API_KEY = os.getenv('COHERE_API_KEY')   

embed_model = CohereEmbedding(cohere_api_key=COHERE_API_KEY)
# embed_model = OpenAIEmbedding(api_key=OPENAI_API_KEY)

service_context = ServiceContext.from_defaults(llm=Cohere(model=model, temperature=temperature, api_key=COHERE_API_KEY), embed_model=embed_model)
set_global_service_context(service_context)



# check if storage already exists
if (not os.path.exists('./storage')):
    documents = SimpleDirectoryReader('data').load_data()
    index = VectorStoreIndex.from_documents(documents=documents, service_context=service_context)
    index.storage_context.persist()
else:
    # load the existing index
    storage_context = StorageContext.from_defaults(persist_dir='./storage')
    index = load_index_from_storage(storage_context)


chat_engine = index.as_chat_engine(service_context=service_context, chat_mode="condense_plus_context")

def chat_bot(prompt: str):
    response = chat_engine.chat(prompt)
    # print(response.__repr__())
    return response.response



if __name__=='__main__':
    test_prompts = [
        # Insert test prompts
    ]
    for test_prompt in test_prompts:
        response = chat_bot(prompt=test_prompt)
        print(response)

**Comment by gich2009** [comment]
Hi @ravi03071991 , please remember to investigate this issue. There are a couple of issues I've seen that have been assigned to you but don't forget to check this out as well.

**Comment by gich2009** [comment]
This issue is fixed as of v0.9.16.post2.

**Comment by ozozozd** [comment]
I don't think this issue is fixed. Using Cohere as the LLM still responds without context. Very easy to repro with the code below. Not specifying Cohere as the LLM shows that OpenAI just works.
```#! /usr/bin/env python3
import logging
import os
import sys
from dotenv import load_dotenv
from llama_index import (ServiceContext, StorageContext, VectorStoreIndex,
                         load_index_from_storage, set_global_service_context, SimpleDirectoryReader)
from llama_index.llms import Cohere, OpenAI
from llama_index.embeddings import CohereEmbedding
from llama_index.text_splitter import SentenceSplitter

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
load_dotenv()
# check if storage already exists
PERSIST_DIR = "./storage"

embed_model = CohereEmbedding()
text_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=10)
service_context = ServiceContext.from_defaults(
    embed_model=embed_model, text_splitter=text_splitter, llm=Cohere())
set_global_service_context(service_context)

if os.path.exists(PERSIST_DIR):
    # load index from storage
    storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR)
    index = load_index_from_storage(storage_context)
else:
    documents = SimpleDirectoryReader(".").load_data()
    index = VectorStoreIndex.from_documents(documents)
    index.storage_context.persist()
chat_engine = index.as_chat_engine(
    chat_mode="condense_plus_context", verbose=True)
chat_engine.chat_repl()
```

**Comment by smlee-tech** [comment]
Hi, I had a similar problem. Has anyone solved it?
