### ISSUE TITLE
[Bug]: in pii.py file in postprocessing folder

### ISSUE THREAD

**Issue by amirgholipour** [run-llama/llama_index#9314]
### Bug Description

when I was testing this code for PII detection:
https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/PII.html
I encounter an issue in the line  74 of this code

https://github.com/run-llama/llama_index/blob/main/llama_index/postprocessor/pii.py

here is the error:

 File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/genai_venv/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/Llama_index_multitasks_app_watsonx_GA.py", line 399, in <module>
    masked_text = PII_Detector(llm,node )
  File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/Llama_index_multitasks_app_watsonx_GA.py", line 277, in PII_Detector
    new_nodes = processor.postprocess_nodes([NodeWithScore(node=node)])
  File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/genai_venv/lib/python3.10/site-packages/llama_index/postprocessor/types.py", line 48, in postprocess_nodes
    return self._postprocess_nodes(nodes, query_bundle)
  File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/genai_venv/lib/python3.10/site-packages/llama_index/postprocessor/pii.py", line 91, in _postprocess_nodes
    new_text, mapping_info = self.mask_pii(
  File "/Users/skasmani/Downloads/IBM/ibm-repo/RAG-Fusion-WatsonX/genai_venv/lib/python3.10/site-packages/llama_index/postprocessor/pii.py", line 78, in mask_pii
    json_dict = json.loads(json_str_output)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 3 column 1 (char 112)

### Version

0.9.11.post1

### Steps to Reproduce

I just used the IBM watsonx model (llama 2) as the model and has used the code which was in this link:
https://docs.llamaindex.ai/en/stable/examples/node_postprocessor/PII.html

I was able to solve it via adding line:
json_str_output = json_str_output.split('\n')[0]

**Comment by ravi03071991** [comment]
Hi @amirgholipour,

I just checked re-running the code and it worked fine for me. Possible to share the code to cross check?

**Comment by amirgholipour** [comment]
here is the code:
# Import environment loading library
from dotenv import load_dotenv

from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams

import tempfile
# from langchain.prompts import PromptTemplate

from llama_index import ServiceContext, LLMPredictor, OpenAIEmbedding, PromptHelper
from llama_index.llms import OpenAI
from llama_index.text_splitter import TokenTextSplitter
from llama_index.node_parser import SimpleNodeParser
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index import download_loader
from llama_index import VectorStoreIndex
from llama_index.prompts import Prompt
from llama_index import Document
from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.schema import Node
from llama_index.response_synthesizers import (
    ResponseMode,
    get_response_synthesizer,
)
from llama_index.response_synthesizers import TreeSummarize
# define recursive retriever
from llama_index.retrievers import RecursiveRetriever
from llama_index.query_engine import RetrieverQueryEngine
from llama_index.response_synthesizers import get_response_synthesizer
from llama_index.retrievers import VectorIndexRetriever
import tiktoken

from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams

from ibm_watson_machine_learning.foundation_models.utils.enums import ModelTypes, DecodingMethods
from ibm_watson_machine_learning.foundation_models.extensions.langchain import WatsonxLLM
from ibm_watson_machine_learning.metanames import GenTextParamsMetaNames as GenParams
from ibm_watson_machine_learning.foundation_models import Model
# import genai.extensions.langchain

# for file name generation
import random
# Import system libraries
import os
# Import streamlit for the UI 
import streamlit as st

# Load environment vars

from dotenv import load_dotenv
if not os.path.exists('temp'): os.mkdir('temp')
load_dotenv(".env",override=True)
def GetGenaiCreds():
    # load_dotenv(override=True)
    
    api_key = os.getenv("GENAI_KEY_WXGA", None)
    api_url = os.getenv("GENAI_API_WXGA", None)
    project_id =os.getenv("PROJECT_ID_WXGA", None)
    if api_key is None or api_url is None:
        print(
            "Either api_key or api_url is None. Please make sure your credentials are correct."
        )
    if api_url is not None:
        api_url = api_url.rstrip("/")
    creds = {
        "apikey": api_key,
        "url": api_url
    },
    return creds,api_key,api_url,project_id


def DefineParas ():
    ## Defining the model parameters

    # To display example params enter
    GenParams().get_example_values()
    print (os.getenv("MAX_NEW_TOKENS"), os.getenv("MIN_NEW_TOKENS"),os.getenv("TEMPERATURE"))
    generate_params = {
        GenParams.MAX_NEW_TOKENS: int(os.getenv("MAX_NEW_TOKENS")),
        GenParams.MIN_NEW_TOKENS: int(os.getenv("MIN_NEW_TOKENS")),
        GenParams.DECODING_METHOD: os.getenv("DECODING_METHOD"),
        GenParams.TEMPERATURE: float(os.getenv("TEMPERATURE")),
        GenParams.REPETITION_PENALTY: float(os.getenv("REPETITION_PENALTY"))
    }
    return generate_params
def LLM():
    generate_params = DefineParas()
    creds,api_key,api_endpoint,project_id = GetGenaiCreds()
    # # Defining the model id    
    model = Model(
        model_id=os.getenv("MODEL_ID"),
        params=generate_params,
        credentials={
            "apikey": api_key,
            "url": api_endpoint
        },
        project_id=project_id
    )
    model.get_details()


    model = WatsonxLLM(model=model)
    return model
    
def Service_Context(llm_model):
    service_context = ServiceContext.from_defaults(
        llm=llm_model,
        embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L12-v2"),
        chunk_size=1024,
        query_wrapper_prompt=Prompt("<s>[INST] {query_str} [/INST]"),
        system_prompt="<<SYS>> Answer just what you are asked, without being polite. Answer straight to the point, "
                        "do not use formalities nor greetings, don't start with Here. don't start with Sure<</SYS>>"
        )    
    return service_context
    
def Service_Context2(llm_model):
    service_context = ServiceContext.from_defaults(
        llm=llm_model,
        embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L12-v2"),
        # chunk_size=1024,
        query_wrapper_prompt=Prompt("<s>[INST] {query_str} [/INST]"),
        system_prompt="<<SYS>> Answer just what you are asked, without being polite. Answer straight to the point, "
                        "do not use formalities nor greetings, don't start with Here. don't start with Sure<</SYS>>"
        )    
    return service_context
        


# Custom CSS to change the sidebar background
def custom_css():
    st.markdown(
        """
        <style>
        .css-1lcbmhc {
            background-color: #ADD8E6;  # Example blue color, change as needed
        }
        </style>
        """,
        unsafe_allow_html=True
    )

# Injecting custom CSS
custom_css()

# Streamlit App title and description
st.title("Multiple Documents Processor 📚")


# Define the sidebar with emojis and custom text
# st.sidebar.title("Summarization Tasks 🚀")
# option = st.sidebar.radio(
#     "Choose Your Task",
#     ('📄 Summarize each document individually', '🔗 Summarize into a single resource', '📃 Summarize each page independently')
# )
# Define the sidebar with tabs for different functionalities
st.sidebar.title("Choose Your Task 🚀")
tab = st.sidebar.radio("Tabs", ('Summarisation', 'PII Detection & Masking'))


# Define your tasks
def summarize_pdfs_from_folder_separate(llm):
    service_context = Service_Context(llm) 
    summaries = []
    # Documents indexing
    documents = SimpleDirectoryReader('data',recursive=True,).load_data()
    
    
    doc_texts = {}

    for doc in documents:
        file_name = doc.metadata['file_name']
        if file_name not in doc_texts:
            doc_texts[file_name] = doc.text
        else:
            doc_texts[file_name] += "\n" + doc.text

    # Now, doc_texts dictionary contains each file's concatenated text
    for file_name, text in doc_texts.items():
        
        documents = [Document(text=text)]

        index = VectorStoreIndex.from_documents(documents, service_context=service_context)

        # Retrieval
        query_engine = index.as_query_engine(streaming=False, service_context=service_context)
        

        summary = query_engine.query("Act as professional editor. Can you please provide a concise and comprehensive summary of the document. This is very simportant to my career.")
        summaries.append(summary.response) 
        print("*" * 100)

    
    return summaries


def summarize_pdfs_from_folder_all(llm):
    service_context = Service_Context(llm) 
    summaries = []
    # Documents indexing
    documents = SimpleDirectoryReader('data',recursive=True,).load_data()
    
    
    

    index = VectorStoreIndex.from_documents(documents, service_context=service_context)

    # Retrieval
    query_engine = index.as_query_engine(streaming=False, service_context=service_context)
    

    summary = query_engine.query("Act as professional editor. Can you please provide a concise and comprehensive summary of the document. This is very simportant to my career.")
    summaries.append(summary.response) 
    print("*" * 100)

    
    return summaries


def summarize_pdfs_from_folder_separate_pdf_pages(llm):
    service_context = Service_Context(llm) 
    summaries = []
    meta_data = []
    # Documents indexing
    documents = SimpleDirectoryReader('data',recursive=True).load_data()
    
    

    for doc in documents:
        print("#" * 100)
        try:
            print ( doc.metadata['file_name'], doc.metadata['page_label'])
            meta_data.append([doc.metadata['file_name'], doc.metadata['page_label']])
        except:
            print ( doc.metadata['file_name'])
            meta_data.append([doc.metadata['file_name'], "None"])
        
        documents = [Document(text=doc.text)]
        index = VectorStoreIndex.from_documents(documents, service_context=service_context)

        # Retrieval
        query_engine = index.as_query_engine(streaming=False, service_context=service_context)
        

        # )
        summary = query_engine.query("Act as professional editor. Can you please provide a concise and comprehensive summary of the document. This is very simportant to my career.")
        summaries.append(summary.response) 
        
        print("*" * 100)

    
    return summaries,meta_data
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index.postprocessor import (
    PIINodePostprocessor,
    NERPIINodePostprocessor,
)
from llama_index.llms import HuggingFaceLLM
from llama_index import ServiceContext, Document, VectorStoreIndex
from llama_index.schema import TextNode
from llama_index.schema import NodeWithScore
# load documents
text = """
Hello Paulo Santos. The latest statement for your credit card account 1111-0000-1111-0000 was mailed to 123 Any Street, Seattle, WA 98109.
"""

def PII_Detector(llm,node):
    service_context = Service_Context2(llm) 
    
    processor = PIINodePostprocessor(service_context=service_context)

    

    new_nodes = processor.postprocess_nodes([NodeWithScore(node=node)])
    # view redacted text
    new_nodes[0].node.get_text()
    # print(new_nodes)
    # print ('@@@@'*30)
    # # view redacted text
    # # new_nodes[0].node.get_text()

    # # get mapping in metadata
    # # NOTE: this is not sent to the LLM!
    # # new_nodes[0].node.metadata["__pii_node_info__"]
    # # feed into index
    # index = VectorStoreIndex([n.node for n in new_nodes])
    # response = index.as_query_engine().query(
    #     "What address was the statement mailed to?"
    # )
    # # print(str(response))
    return new_nodes[0].node.get_text()


    
    

# Example of using emojis in your text
st.write("Click the button below to start summarization! 👇")



# Conditional rendering based on the selected tab
if tab == 'Summarisation':
    option = st.sidebar.radio(
            "Summarisation Options",
            ('📄 Summarize each document individually', '🔗 Summarize into a single resource', '📃 Summarize each page independently')
        )
    st.write("Easily summarize your PDF documents into concise and comprehensive summaries.")
    if st.button("Generate Summary"):
        # Streamlit App title and description for summarisation

        

        # Code for summarisation functionality
            # st.write("Summaries:")
        llm = LLM()
        meta_data = []
        # Display the content based on the selected task
        if option == '📄 Summarize each document individually':
            summaries =summarize_pdfs_from_folder_separate(llm)
        elif option == '🔗 Summarize into a single resource':
            summaries =summarize_pdfs_from_folder_all(llm)
        elif option == '📃 Summarize each page independently':
            summaries, meta_data =summarize_pdfs_from_folder_separate_pdf_pages(llm)
            
            
        if len(summaries)<=1:
            st.write(f"Summary for PDF:")
            st.write(summaries[0])
        else:    
            for i, summary in enumerate(summaries):
                if meta_data:
                    
                    st.write(f"Summary for "+meta_data[i][0]+ " page "+ meta_data[i][1])
                    # st.write(meta_data[i])
                    st.write(summary)
                    
                else:
                    st.write(f"Summary for PDF {i+1}:")
                    st.write(summary)


elif tab == 'PII Detection & Masking':
    # Streamlit App title and description for PII Detection
    st.title("PII Detection & Masking 🛡️")
    st.write("Detect and mask personally identifiable information in your documents.")

    # Text area for user to input text for PII detection
    user_input_text = st.text_area("Enter the text for PII detection", height=150)

    # Button to trigger PII detection
    if st.button("Detect PII"):
        llm = LLM()
        # Assuming PII_Detector function takes the text as an argument and returns masked text
        node = TextNode(text=user_input_text)
        masked_text = PII_Detector(llm,node )
        st.write("Detected and Masked Text:")
        st.write(masked_text)

**Comment by ravi03071991** [comment]
> import logging import sys
> 
> logging.basicConfig(stream=sys.stdout, level=logging.INFO) logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
> 
> from llama_index.postprocessor import ( PIINodePostprocessor, NERPIINodePostprocessor, ) from llama_index.llms import HuggingFaceLLM from llama_index import ServiceContext, Document, VectorStoreIndex from llama_index.schema import TextNode from llama_index.schema import NodeWithScore
> 
> def Service_Context2(llm_model): service_context = ServiceContext.from_defaults( llm=llm_model, embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L12-v2"), # chunk_size=1024, query_wrapper_prompt=Prompt("[INST] {query_str} [/INST]"), system_prompt="<> Answer just what you are asked, without being polite. Answer straight to the point, " "do not use formalities nor greetings, don't start with Here. don't start with Sure<>" ) return service_context
> 
> # load documents
> text = """ Hello Paulo Santos. The latest statement for your credit card account 1111-0000-1111-0000 was mailed to 123 Any Street, Seattle, WA 98109. """
> 
> def PII_Detector(llm,node): service_context = Service_Context2(llm)
> 
> ```
> processor = PIINodePostprocessor(service_context=service_context)
> 
> 
> 
> new_nodes = processor.postprocess_nodes([NodeWithScore(node=node)])
> # view redacted text
> new_nodes[0].node.get_text()
> 
> return new_nodes[0].node.get_text()
> ```
> 
> llm = LLM()
> 
> # Assuming PII_Detector function takes the text as an argument and returns masked text
> node = TextNode(text=user_input_text)

Not sure about the LLM you are using but with OpenAI LLM and following code with some changes, I can get the response with PII. 

```
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

from llama_index.postprocessor import (
    PIINodePostprocessor,
    NERPIINodePostprocessor,
)
from llama_index.llms import HuggingFaceLLM, OpenAI
from llama_index import ServiceContext, Document, VectorStoreIndex
from llama_index.schema import TextNode
from llama_index.schema import NodeWithScore
from llama_index.embeddings import HuggingFaceEmbedding

def Service_Context2(llm_model):
    service_context = ServiceContext.from_defaults(
        llm=llm_model,
        embed_model=HuggingFaceEmbedding(model_name="sentence-transformers/all-MiniLM-L12-v2"),
        )    
    return service_context 
```
    
# load documents

```
text = """
Hello Paulo Santos. The latest statement for your credit card account 1111-0000-1111-0000 was mailed to 123 Any Street, Seattle, WA 98109.
"""

def PII_Detector(llm,node):
    service_context = Service_Context2(llm) 
    
    processor = PIINodePostprocessor(service_context=service_context)

    

    new_nodes = processor.postprocess_nodes([NodeWithScore(node=node)])
    # view redacted text
    new_nodes[0].node.get_text()

    return new_nodes[0].node.get_text()
  
import os
os.environ['OPENAI_API_KEY'] = 'YOUR OPENAI API KEY'
llm = OpenAI()
# Assuming PII_Detector function takes the text as an argument and returns masked text
node = TextNode(text=text)

response_pii = PII_Detector(llm, node)
```

response_pii has 

> 'Hello [NAME1]. The latest statement for your credit card account [CREDIT_CARD_NUMBER] was mailed to [ADDRESS].'

**Comment by amirgholipour** [comment]
I tested based on IBM watsonx platform, with LLama2 70b chat model.
