### ISSUE TITLE
[Feature Request]:  Can support memgraph for graph indexing

### ISSUE THREAD

**Issue by kingle-zhuang** [run-llama/llama_index#9335]
### Feature Description

memgraph is high performance then others, so maybe we can support it

### Reason

high performance low cost, compatible with neo4j

**Comment by matea16** [comment]
Hi @kingle-zhuang, just saw your comment here and wanted to let you know that [Memgraph integration](https://github.com/run-llama/llama_index/pull/16345) has recently been added to LlamaIndex.
There's also an [usage example](https://docs.llamaindex.ai/en/stable/examples/property_graph/property_graph_memgraph/) available in the  docs. Are you working on something with Memgraph and Llama?
