### ISSUE TITLE
[Feature Request]: Ensure all generations are tracked as events in callback manager

### ISSUE THREAD

**Issue by anna-springbokai** [run-llama/llama_index#9346]
### Feature Description

Make sure that all LLM generations are passed as events to the callback manager to enable consistent tracing. At the moment some LLM generations (e.g. those by OpenAIQuestionGenerator) do not costitute callback events.

### Reason

We would like to be able to trace all events (generations, embedding, retrieval, etc.) using tools such as phoenix or langfuse. We can mostly do it via callbacks.
But some LLM generations (e.g. those by OpenAIQuestionGenerator) are not passed as events to the callback manager, which means they can't be traced together with other events. Would be useful to make sure everything can be traced uniformly.

### Value of Feature

Tracing of LLM usage with callbacks is only half useful if it does not trace all generations.

**Comment by logan-markewich** [comment]
@anna-springbokai Since the callback manager is directly attached to the base LLM object, all generations are captured.

Now, whether or not they are captured as standalone events vs. as part of some overall trace is a different story

**Comment by anna-springbokai** [comment]
You're right, my problem lies elsewhere. Sorry and thank you!
