### ISSUE TITLE
[Bug]: StorageContext is long to load

### ISSUE THREAD

**Issue by Cotum** [run-llama/llama_index#9347]
### Bug Description

Hello, I am new to Llama-index and apologize if the problem is trivial but I didn't find any related issue.
I am trying to load embedding vectors from a local saved directory using : 
```
storage_context = StorageContext.from_defaults(
        docstore=SimpleDocumentStore.from_persist_dir(persist_dir=storage_directory),
        vector_store=SimpleVectorStore.from_persist_dir(persist_dir=storage_directory, namespace = "default"),
        index_store=SimpleIndexStore.from_persist_dir(persist_dir=storage_directory),
    )
```
However, it seems that the loading of the storage context is very long compared to the number of chunk present in the directory :
6519 chunks in 50 seconds.
Is it a normal speed ? Is there a way to speed up the process, maybe by going through a vector database ?

### Version

0.9.4

### Steps to Reproduce

I have a set of 100 documents that is parsed into 6519 chunks and whose embedding is saved locally using the embed-model "int-float/multilingual-e5-base" through the HuggingFaceEmbedding class in the global service context.
Then loading the local database through a storagecontext using the same global service is pretty long.

**Comment by logan-markewich** [comment]
For an index of that size, that seems like a normal speed.

Definitely look into using a vector db integration

**Comment by logan-markewich** [comment]
List of all vector dbs at the bottom here 
https://docs.llamaindex.ai/en/stable/module_guides/storing/vector_stores.html

**Comment by Cotum** [comment]
Thank you very much for your answer and I will definitely look into vector database.

**Comment by wei-ann-Github** [comment]
> For an index of that size, that seems like a normal speed.
> 
> Definitely look into using a vector db integration

Hi @logan-markewich , will using vector db compared to using VectorStoreIndex lead to a much reduced storage context loading time?

**Comment by logan-markewich** [comment]
@wei-ann-Github yea, definitely. They are optimized for the task. You can integrate nearly any vector db into the VectorStoreIndex (qdrant, weaviate, pinecone, chroma, etc)
