### ISSUE TITLE
[Question]: Time consuming indexing .pdf files with VectorStoreIndex

### ISSUE THREAD

**Issue by debraj135** [run-llama/llama_index#9358]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using `VectorStoreIndex` to index .pdf files. My documents are being created using `SimpleDirectoryReader`. 

I end up with nearly 100,000 chunks. After completing `Generating embeddings:` for all chunks, the flow seems to be stuck under `VectorStoreIndex.from_documents` for nearly an hour. I was wondering what could be leading to it.

**Comment by hatianzhang** [comment]
@debraj135 which embedding are you using? openai?

**Comment by debraj135** [comment]
No, I'm using an off the shelf one from huggingface. And the embedding step of all chunks seems to have completed.

**Comment by edhenry** [comment]
Using a GPU under the hood? If you're not this will take quite some time.

You can also enable some debugging using [callbacks](https://docs.llamaindex.ai/en/stable/understanding/tracing_and_debugging/tracing_and_debugging.html#callback-handler). Specifically the [Debug Handler](https://docs.llamaindex.ai/en/stable/examples/callbacks/LlamaDebugHandler.html#llama-debug-handler).

This will show you tracing information related to your embedding calls [as shown here](https://docs.llamaindex.ai/en/stable/examples/callbacks/LlamaDebugHandler.html#trigger-the-callback-with-a-query).
