### ISSUE TITLE
[Question]: nebula close connection happened an exception !

### ISSUE THREAD

**Issue by gdonlyathw** [run-llama/llama_index#9368]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I runned the sample code：
https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html

I get the response from nebula successfully.

but when the code run finished, happed an exception:

Traceback (most recent call last):
  File "xxx\lib\site-packages\llama_index\graph_stores\nebulagraph.py", line 248, in __del__
  File "xxx\lib\site-packages\nebula3\gclient\net\SessionPool.py", line 273, in close
  File "xxx\lib\site-packages\nebula3\gclient\net\Session.py", line 288, in _sign_out
  File "xxx\lib\site-packages\nebula3\gclient\net\Connection.py", line 205, in signout
  File "xxx\lib\site-packages\nebula3\graph\GraphService.py", line 1603, in signout
  File "xxx\lib\site-packages\nebula3\graph\GraphService.py", line 1606, in send_signout
AttributeError: 'NoneType' object has no attribute 'CALL'

from the exception, I guess it caused by release nebula connection.,but I don't know how to resolve it !

I used  nebula3-python-3.4.0 and server nebula3.6.

**Comment by gdonlyathw** [comment]
> _🤖_
> 
> Hello @gdonlyathw,
> 
> Nice to meet you! I'm [Dosu](https://dosu.dev), a bot here to assist you with your issues, answer your questions, and guide you on how to contribute to this project. While we're waiting for a human maintainer to assist you, feel free to ask me anything you need help with. I'm here to make your experience with LlamaIndex smoother. Let's get started!
> 
> The error you're encountering, `AttributeError: 'NoneType' object has no attribute 'CALL'`, typically happens when a method is being called on an object that is `None`. This could mean that the object hasn't been properly initialized or that it's been set to `None` before the method call.
> 
> In your case, it seems like the error is occurring when you're trying to close a connection with Nebula. The traceback points to the `__del__` method in the `nebulagraph.py` file of the LlamaIndex library, which is likely where the Nebula connection is being closed.
> 
> Unfortunately, without the specific code where you're closing the Nebula connection, it's hard to provide a precise solution. However, you might want to check the part of your code where you're initializing and closing the Nebula connection. Make sure that the object you're calling the method on is not `None` before calling the method.
> 
> If you're still encountering the issue, could you please provide the specific part of your code where you're closing the Nebula connection and where the error occurs? This would help in identifying the exact cause of the issue and providing a more accurate solution.
> 
> For reference, you can check the [nebulagraph.py](https://github.com/run-llama/llama_index/blob/main/llama_index/graph_stores/nebulagraph.py) file in the LlamaIndex repository.
> 
> ## Sources
> * [llama_index/llms/vllm.py](https://github.com/run-llama/llama_index/blob/main/llama_index/llms/vllm.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.


I juest use the sample code:
```

space_name = "llamaindex"
edge_types, rel_prop_names = ["relationship"], [
    "relationship"
]  # default, could be omit if create from an empty kg
tags = ["entity"]  # default, could be omit if create from an empty kg


graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)
```

**Comment by sammichenVV** [comment]
> ### Question Validation
> * [x]  I have searched both the documentation and discord for an answer.
> 
> ### Question
> I runned the sample code： https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html
> 
> I get the response from nebula successfully.
> 
> but when the code run finished, happed an exception:
> 
> Traceback (most recent call last): File "xxx\lib\site-packages\llama_index\graph_stores\nebulagraph.py", line 248, in **del** File "xxx\lib\site-packages\nebula3\gclient\net\SessionPool.py", line 273, in close File "xxx\lib\site-packages\nebula3\gclient\net\Session.py", line 288, in _sign_out File "xxx\lib\site-packages\nebula3\gclient\net\Connection.py", line 205, in signout File "xxx\lib\site-packages\nebula3\graph\GraphService.py", line 1603, in signout File "xxx\lib\site-packages\nebula3\graph\GraphService.py", line 1606, in send_signout AttributeError: 'NoneType' object has no attribute 'CALL'
> 
> from the exception, I guess it caused by release nebula connection.,but I don't know how to resolve it !
> 
> I used nebula3-python-3.4.0 and server nebula3.6.

hello, excuse me，how to solve it ?

**Comment by Chengyang852** [comment]
I have the same problem, how can I solve it?

**Comment by santjc** [comment]
same here, does anyone find a solution?

**Comment by xangxiong** [comment]
In case it helps, if you close the `graph_store._session_pool` before your script stops, it prevents this error.  Something like:

```
graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)

....

graph_store._session_pool.close()
```

My assumption is that when the `__del__` function is called, most of the python environment is already cleared, resulting in the class `TMessageType` being `None`.

Not an ideal solution, but helps get around the exception.

**Comment by kui253** [comment]
> In case it helps, if you close the `graph_store._session_pool` before your script stops, it prevents this error. Something like:
> 
> ```
> graph_store = NebulaGraphStore(
>     space_name=space_name,
>     edge_types=edge_types,
>     rel_prop_names=rel_prop_names,
>     tags=tags,
> )
> storage_context = StorageContext.from_defaults(graph_store=graph_store)
> 
> ....
> 
> graph_store._session_pool.close()
> ```
> 
> My assumption is that when the `__del__` function is called, most of the python environment is already cleared, resulting in the class `TMessageType` being `None`.
> 
> Not an ideal solution, but helps get around the exception.

It works， Really appreciate.
