### ISSUE TITLE
[Question]: Configure context text for as_query_engine

### ISSUE THREAD

**Issue by debraj135** [run-llama/llama_index#9370]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

It seems that the context text includes the `page_label` and the `file_name` when I use a `VectorStoreIndex` as `as_query_engine`. What would be the appropriate way to remove this and only include the contents of the text?

**Comment by logan-markewich** [comment]
@debraj135 you can set the metadata keys to be used in LLM or Embedding calls 

```
document.excluded_llm_metadata_keys = ["page_label", "file_name"]
document.excluded_embed_metadata_keys = ["page_label", "file_name"]
```

The same functionality exists for nodes as well

Source:
https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_documents.html#advanced-metadata-customization
