### ISSUE TITLE
[Bug]: ContextChatEngine

### ISSUE THREAD

**Issue by ingracano** [run-llama/llama_index#9371]
### Bug Description

The functionality is compromised when using a version higher than 0.8.55. An error consistently arises in the chat/stream method whit this error:
```
    File"/usr/local/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 197, in stream_chat
    all_messages = prefix_messages + self._memory.get(
                                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 88, in get
    raise ValueError("Initial token count exceeds token limit")
ValueError: Initial token count exceeds token limit
```

### Version

0.9.13

### Steps to Reproduce

We create a chat engine with chat_mode='context' a system_prompt and mak_token sets to 1300. As model we use gpt4-32k with Azure OpenAI (AzureChatOpenAI class of langchain)

### Relevant Logs/Tracbacks

```shell
File"/usr/local/lib/python3.11/site-packages/llama_index/callbacks/utils.py", line 39, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/chat_engine/context.py", line 197, in stream_chat
    all_messages = prefix_messages + self._memory.get(
                                     ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/llama_index/memory/chat_memory_buffer.py", line 88, in get
    raise ValueError("Initial token count exceeds token limit")
ValueError: Initial token count exceeds token limit
```

**Comment by levy9527** [comment]
yeah, just increase your token_limit!

**Comment by HamedMP** [comment]
Increasing the token limit should solve it but shouldn't it trunk context to the specified token limit? Otherwise what's the purpose of the token limit?

**Comment by JanetaToncheva** [comment]
> I solved the bug. Problem was on setting variable token_limit on ChatMemoryBuffer. Thanks

I'm facing the same issue when reading a .json file

`(....) File "/mnt/c/users/username/desktop/privategpt/private-gpt/.venv/lib/python3.11/site-packages/llama_index/core/callbacks/utils.py", line 41, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/mnt/c/users/username/desktop/privategpt/private-gpt/.venv/lib/python3.11/site-packages/llama_index/core/chat_engine/context.py", line 170, in chat
    all_messages = prefix_messages + self._memory.get(
                                     ^^^^^^^^^^^^^^^^^

  File "/mnt/c/users/username/desktop/privategpt/private-gpt/.venv/lib/python3.11/site-packages/llama_index/core/memory/chat_memory_buffer.py", line 114, in get
    raise ValueError("Initial token count exceeds token limit")
**ValueError: Initial token count exceeds token limit`**

The codebase has changed since this issue was closed and I'm not sure where to increase the token limit now or alternatively decrease the chunks when reading from a .json file. Ay help will be appreciated.

P.S. same occurs if trying to read from an html file.

**Comment by git-hamza** [comment]
@JanetaToncheva 

If you don't pass the memory object to your ContextChatEngine, it will create a memory object and use your llm context window to set the token limit as it can be seen here:

https://github.com/run-llama/llama_index/blob/044a439dc2fda53c991e49a43e4e8e652dd8a735/llama-index-core/llama_index/core/chat_engine/context.py#L76-L78


Incase you create the memory object and then pass it to ContextChatEngine, 
In ChatMemoryBuffer, you can control the token limit but it is optional parameter. if you pass llm (it will set token limit from its context window), if you pass token limit( it will use that) and if you don't pass anything, it will use Default Token limit. You can see the code chunks below:

https://github.com/run-llama/llama_index/blob/044a439dc2fda53c991e49a43e4e8e652dd8a735/llama-index-core/llama_index/core/memory/chat_memory_buffer.py#L62-L66

https://github.com/run-llama/llama_index/blob/044a439dc2fda53c991e49a43e4e8e652dd8a735/llama-index-core/llama_index/core/memory/chat_memory_buffer.py#L15

**Comment by JanetaToncheva** [comment]
@git-hamza 

I tried to increase any default token limit I could find and no change. 
This however solved my issue

https://github.com/zylon-ai/private-gpt/issues/1701#issuecomment-1995891462

> I ran into this too. I created a larger memory buffer for the chat engine and this solved the problem. Why isn't the default ok?
> 
> Inside `llama_index` this is automatically set from the supplied LLM and the `context_window` size if `memory` is not supplied. [chat_engine.context](https://github.com/run-llama/llama_index/blob/af0c298665757a5927d1c5a2d402914e360b557d/llama-index-core/llama_index/core/chat_engine/context.py#L79) Cranking up the llm `context_window` would make the buffer larger. However that may have other unintended side-effects too.
> 
> chat_service.py
> 
> ```
>     from llama_index.core.memory import ChatMemoryBuffer
> 
>     def _chat_engine(
>         self,
>         system_prompt: str | None = None,
>         use_context: bool = False,
>         context_filter: ContextFilter | None = None,
>     ) -> BaseChatEngine:
>         if use_context:
>             vector_index_retriever = self.vector_store_component.get_retriever(
>                 index=self.index, context_filter=context_filter
>             )
>             **memory = ChatMemoryBuffer.from_defaults(token_limit=8192)  # <-- MORE TOKENS**
>             return ContextChatEngine.from_defaults(
>                 system_prompt=system_prompt,
>                 retriever=vector_index_retriever,
>                 **memory=memory,  #  <-- USE THE  LARGER BUFFER**
>                 llm=self.llm_component.llm,
>                 node_postprocessors=[
>                     MetadataReplacementPostProcessor(target_metadata_key="window"),
>                 ],
>             )
> ```

**Comment by git-hamza** [comment]
@JanetaToncheva 

But if your token limit is greater than your model's maximum context length, don't you think you would run into model's maximum context length limit error?
