### ISSUE TITLE
[Bug]: OpenAIFinetuneEngine uses deprecated OpenAI API and doesn't work

### ISSUE THREAD

**Issue by daleksandroff** [run-llama/llama_index#9375]
### Bug Description

Hi!
I've been trying to use `OpenAIFinetuneEngine` with model `gpt-3.5-turbo`. 
After I run command `finetune_engine.finetune()` it goes into `Waiting for file to be ready...` and then doesn't run further. If I force the notebook to Stop the command, then I can see the error saying:

> 'gpt-3.5-turbo can only be fine-tuned on the new fine-tuning API (`/fine_tuning/jobs`). This API (`/fine-tunes`) is being deprecated. Please refer to our documentation for more information: https://platform.openai.com/docs/api-reference/fine-tuning'

<img width="1069" alt="Screenshot 2023-12-07 at 16 10 14" src="https://github.com/run-llama/llama_index/assets/33901411/0c77b6cc-de15-42ab-99a6-338df67e23dd">
<img width="1184" alt="Screenshot 2023-12-07 at 16 10 27" src="https://github.com/run-llama/llama_index/assets/33901411/a3478c1b-4dbf-449e-8f77-15314ed28bbd">

---

If I try to use another model `davinci` which supposed to work with `/fine-tunes` API, then I'm getting an error that there is no `message` object in the training file (which is not there as per the format needed for davinci).

<img width="1204" alt="Screenshot 2023-12-07 at 16 14 57" src="https://github.com/run-llama/llama_index/assets/33901411/47483ffd-1f70-4bd0-beaa-afdeb9c188e6">

### Version

0.9.11.post1

### Steps to Reproduce

from llama_index.finetuning import OpenAIFinetuneEngine
finetune_engine = OpenAIFinetuneEngine(
    "gpt-3.5-turbo",
    "finetuning_corpus.jsonl",
)
finetune_engine.finetune()

### Relevant Logs/Tracbacks

```shell
BadRequestError: Error code: 400 - {'error': {'message': 'gpt-3.5-turbo can only be fine-tuned on the new fine-tuning API (`/fine_tuning/jobs`). This API (`/fine-tunes`) is being deprecated. Please refer to our documentation for more information: https://platform.openai.com/docs/api-reference/fine-tuning', 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by ravi03071991** [comment]
Hi @daleksandroff ,

Seems like the OpenAi API has been changed for finetuning jobs. We will update the the abstraction.

**Comment by ravi03071991** [comment]
Hey @daleksandroff,

We have updated the abstractions and you should be able to use it for finetuning jobs. You can check the necessary PR [here](https://github.com/run-llama/llama_index/pull/9564).

Thank You.
