### ISSUE TITLE
[Bug]: MetadataFilters does not allow condition = FilterCondition.OR

### ISSUE THREAD

**Issue by hlin-arrybyte** [run-llama/llama_index#9383]
### Bug Description

I added MetadataFilters to my query engine. The query engine seems fine when I'm using the default FilterCondition.AND. When I try to use FilterCondition.OR, the query engine returns 'Empty response'. It also disregards any format requirement in the query. 

### Version

0.9.13

### Steps to Reproduce

from llama_index.vector_stores.types import MetadataFilters, ExactMatchFilter
from llama_index import Document, VectorStoreIndex

raw = [{'yob': '1983', 'name': Elena}, {'yob': 'No info', 'name': 'Elena'}, {'yob': '1980', 'name': 'henz'}]

list_of_documents = [Document(metadata = {'yob' : r['yob']}, text = r['name']) for r in raw]

index = VectorStoreIndex.from_documents(list_of_documents, service_context=service_context)
filters = MetadataFilters(filters=[ExactMatchFilter(key="yob", value='1983'), ExactMatchFilter(key="yob", value='No info')], condition=FilterCondition.OR)
query_engine = index.as_query_engine(filters=filters, similarity_top_k=10)
query="Find records with name Elena."
response=query_engine.query(query)

---- Expect it to return record 1 and 2, instead return 'empty response'

**Comment by hlin-arrybyte** [comment]
> I believe when you want to do an `FilterCondition.OR` for multiple `ExactMatchFilter `with the same `key` this occurs. In other words, if you want to retrieve or do Q&A over a subset of possible `file_name`. I'm having a similar issue

I also tried 'FilterCondition.OR' with different 'key's. Seems I met the same issue. Are you able to make 'OR' successful on different keys?

**Comment by ms82119** [comment]
I also have the same need, to filter over a list of file_name values in the metadata.  I was trying to use the "IN" FilterOperator which seems like it should be doing an OR for the given key name, but I'm having trouble constructing the MetadataFilter object as I am trying to supply a list of string values into the value field, but it seems it only will accept a single str, int, or float.  I suppose it may be expected to create each value as a separate MetadataFilter and use "IN" as the operator for each... but then it may be a question of how the underlying vector store engine decides to handle it.  Some guidance perhaps on this usage example in the docs would be good as I wasn't able to find any example of the OR/IN case.

btw @hlin-arrybyte if you're using the SimpleVectorStore then I know from first hand experience that it can't support that query of multiple values on the same key.   I had find a bit of a hack to get around it quickly for my needs at the time, it might work for you.   Put the code below into a file and import MySimpleVectorStore into your code where you are creating your StorageContext.  Also at this point in the StorageContext creation replace "SimpleVectorStore" with "MySimpleVectorStore" (if you don't explicitly specify this store it's probably getting set as a default).   This new class is smart enough to detect when there are filters for the same field and applies them as an OR.

`import llama_index.vector_stores.simple
from llama_index.vector_stores.types import (MetadataFilters,VectorStoreQuery,VectorStoreQueryResult)
from llama_index.vector_stores.simple import SimpleVectorStore
from typing import Any, Callable, Mapping, Optional


def my_modified_build_metadata_OR_filter_fn(
    metadata_lookup_fn: Callable[[str], Mapping[str, Any]],
    metadata_filters: Optional[MetadataFilters] = None,
) -> Callable[[str], bool]:
    """Build metadata filter function with OR behavior for same keys."""
    filter_list = metadata_filters.filters if metadata_filters else []
    if not filter_list:
        return lambda _: True

    # Group filters by their keys
    grouped_filters = {}
    for filter_ in filter_list:
        if filter_.key not in grouped_filters:
            grouped_filters[filter_.key] = []
        grouped_filters[filter_.key].append(filter_.value)

    def filter_fn(node_id: str) -> bool:
        metadata = metadata_lookup_fn(node_id)
        for key, values in grouped_filters.items():
            metadata_value = metadata.get(key, None)
            if metadata_value is None:
                return False
            elif isinstance(metadata_value, list):
                # Check if any value in filter values matches
                if not any(value in metadata_value for value in values):
                    return False
            elif isinstance(metadata_value, (int, float, str, bool)):
                # Check if metadata value matches any of the filter values
                if metadata_value not in values:
                    return False
        return True

    return filter_fn

class MySimpleVectorStore(SimpleVectorStore):
    def query(self, query: VectorStoreQuery, **kwargs: Any) -> VectorStoreQueryResult:

        # Monkey patch the original function with my version that does the OR filter
        original_fn = llama_index.vector_stores.simple._build_metadata_filter_fn
        llama_index.vector_stores.simple._build_metadata_filter_fn = my_modified_build_metadata_OR_filter_fn

        # Now, call the original query method
        result = super().query(query, **kwargs)

        # Revert the monkey patching
        llama_index.vector_stores.simple._build_metadata_filter_fn = original_fn

        return result`

**Comment by phiweger** [comment]
> > I believe when you want to do an `FilterCondition.OR` for multiple `ExactMatchFilter `with the same `key` this occurs. In other words, if you want to retrieve or do Q&A over a subset of possible `file_name`. I'm having a similar issue
> 
> I also tried 'FilterCondition.OR' with different 'key's. Seems I met the same issue. Are you able to make 'OR' successful on different keys?

same problem

**Comment by raproth** [comment]
same here

**Comment by jimkleban** [comment]
Same here.

**Comment by teis-e** [comment]
Same here

**Comment by dm-shr** [comment]
Same problem.

**Comment by felipeary91** [comment]
Same here...llama_index v0.9.11 and not working
