### ISSUE TITLE
[Question]: Why do the retrieved nodes of a query engine and a retriever differ?

### ISSUE THREAD

**Issue by kouskouss** [run-llama/llama_index#9385]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I query the same index in two different ways, first I use the following retriever:

```
service_context = ServiceContext.from_defaults(
                                               embed_model=embed_model,
                                               llm=None, 
                                               chunk_size=512,
                                               chunk_overlap=50
)

# Load the vector index from the storage
index = load_index_from_storage(
    StorageContext.from_defaults(persist_dir=vi_out_path),
    service_context=service_context,
)

# MMR retriever.
retriever = index.as_retriever(
    similarity_top_k=5,
    vector_store_query_mode="mmr",    
)

retrieved_nodes = retriever.retrieve(query_str)
```

and then I used a query engine with llm=gpt-3.5-turbo-16k:

```
service_context = ServiceContext.from_defaults(
                                               embed_model=embed_model,
                                               llm=llm, 
                                               chunk_size=512,
                                               chunk_overlap=50
)

# Load the vector index from the storage
index = load_index_from_storage(
    StorageContext.from_defaults(persist_dir=vi_out_path),
    service_context=service_context,
)

# Query the index.
query_engine = index.as_query_engine(
    similarity_top_k=5,
    vector_store_query_mode="mmr",
    verbose=True,
)

response = query_engine.query(query_str)
response.source_nodes
```

**As a result the chunks that the two methods retrieved were different** (the _retrieved_nodes_ were different from _response.source_nodes_). I don't understand how is this happening, because the indices were formed with the same embedding model, chunk size and chunk overlap and the query string uses the same embedding in each case, so by using similarity search the same chunks should be retrieved.

The only explicit difference is the specification of the llm for the _service_context_, but, for my understanding, that difference shouldn't affect the retrieval part of the process but only the response creation happening after the chunks are retrieved.

Can somebody clarify why this difference in the results is obtained?

**Comment by logan-markewich** [comment]
I think mmr might be a tad unstable.

I would expect other query modes to be the same

**Comment by terilias** [comment]
Hello,

@logan-markewich, after some trials with @kouskouss, we found that the different retrieved nodes were due to the usage of two different wrapper classes around the same embedding model. One is from LangChain: `LangchainEmbedding(HuggingFaceEmbeddings(model_name='paraphrase-MiniLM-L6-v2')` , and the other is from the native wrapper class from LlamaIndex: `HuggingFaceEmbedding(model_name="sentence-transformers/paraphrase-MiniLM-L6-v2")`. 

While the embeddings model is the same, the embeddings (for the same sentence) are not. Based on my discussion with the LlamaIndex documentation bot and some code review of these two classes, I found that what differs is the initialization of some model parameters. Am I correct?

**Comment by logan-markewich** [comment]
@terilias technically they should be the same, although with the langchain class, it's using sentence transformers, and ours is using raw transformers. 

My guess is the pooling may be different. You can set pooling="mean" instead of letting it default to "cls" -- I'll confirm that in a bit
