### ISSUE TITLE
[Question]: stream output is empty

### ISSUE THREAD

**Issue by mistoFENG** [run-llama/llama_index#9394]
### Question Validation

- [ ] I have searched both the documentation and discord for an answer.

### Question

Verison : 
llama-index         0.9.13
vllm                     0.1.7

My code is as follows:
```python
from llama_index import VectorStoreIndex, SimpleDirectoryReader, ServiceContext, StorageContext, load_index_from_storage
from llama_index.llms.vllm import VllmServer
from llama_index.embeddings import HuggingFaceEmbedding
from llama_index.prompts import PromptTemplate
import torch


logging.basicConfig(stream=sys.stdout, level=logging.INFO)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

embed_model = HuggingFaceEmbedding(model_name="./gte-large-zh")
llm = VllmServer(
    api_url="http://localhost:36000/generate", max_new_tokens=512,
)
service_context = ServiceContext.from_defaults(
    chunk_size=512, llm=llm, embed_model=embed_model
)

documents = SimpleDirectoryReader("./data/paul_graham/").load_data()
index = VectorStoreIndex.from_documents(documents, service_context=service_context)

query_engine = index.as_query_engine(streaming=True)
streaming_response = query_engine.query("who are you?")
for text in streaming_response.response_gen:
    print("text: ", text)
```
Running the above code, the output is as follows:
```
INFO:torch.distributed.nn.jit.instantiator:Created a temporary directory at /tmp/tmpqobfqyyh
Created a temporary directory at /tmp/tmpqobfqyyh
INFO:torch.distributed.nn.jit.instantiator:Writing /tmp/tmpqobfqyyh/_remote_module_non_scriptable.py
Writing /tmp/tmpqobfqyyh/_remote_module_non_scriptable.py
INFO:llama_index.indices.loading:Loading all indices.
Loading all indices.
text:  
text:  
text:  
text:  
text:  
text:  
text:  
text:  
text:  
text:  
text: 
text:  
text:  
text:  
text:  
text:  
...
```
But I print the source code llama_index/llms/vllm.py:373  `data = json.loads(chunk.decode("utf-8"))` , there is output:
```
data:  
In the essay,
text:  
data:  
In the essay, the
text:  
data:  
In the essay, the author
text:  
data:  
In the essay, the author,
text:  
data:  
In the essay, the author, Paul
text:  
data:  
In the essay, the author, Paul Graham
text:  
data:  
In the essay, the author, Paul Graham,
text:  
data:  
In the essay, the author, Paul Graham, discusses
```
Please tell me how to solve the above problems. Is there something wrong with my usage? Looking forward to your answer, thanks！

**Comment by mistoFENG** [comment]
It doesn't work. The `read` function in llama_index/tools/tool_spec/load_and_search/base.py is not called, and the output is still empty.

**Comment by mistoFENG** [comment]
> It doesn't work. The `read` function in llama_index/tools/tool_spec/load_and_search/base.py is not called, and the output is still empty.

It doesn't work. The read function in llama_index/tools/tool_spec/load_and_search/base.py is not called, and the output is still empty.

**Comment by mistoFENG** [comment]
> _🤖_
> 
> Hey @mistoFENG! 👋 I'm [Dosu](https://dosu.dev), a friendly bot here to help you with your issues and queries about LlamaIndex, while waiting for a human maintainer. No bug is too pesky, no question too tricky. Let's squash those bugs together! 🐞😄
> 
> Based on the information you've provided, it seems like the `query_engine.query(query)` function is returning an empty response when used with the `streaming=True` parameter. This could be due to a few reasons:
> 
> 1. The index might not be populated with data. Ensure that you're calling the `load` method before the `read` method to populate the index with data.
> 2. The query might not match any data in the index. Ensure that the query matches the data in the index.
> 3. There could be an issue with the `query_engine.query(query)` function. It might be returning an empty response due to a bug or configuration issue.
> 
> Here is the relevant code:
> 
> ```python
> def read(self, query: str) -> Any:
>     # Query the index for the result
>     if not self._index:
>         return (
>             "Error: No content has been loaded into the index. "
>             f"You must call {self._metadata.name} first"
>         )
>     query_engine = self._index.as_query_engine()
>     response = query_engine.query(query)
>     return str(response)
> ```
> 
> You can find this in the [llama_index/tools/tool_spec/load_and_search/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/tools/tool_spec/load_and_search/base.py) file.
> 
> To debug this issue, you could add print statements or use a debugger to check the value of `self._index` and the response from `query_engine.query(query)`.
> 
> If you've already checked these and the issue persists, it would be helpful to have more information. Could you provide more details about the data you're trying to index and the exact query you're using? This could help in identifying the issue.
> 
> ## Sources
> * [llama_index/tools/tool_spec/load_and_search/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/tools/tool_spec/load_and_search/base.py)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

It doesn't work. The `read` function in llama_index/tools/tool_spec/load_and_search/base.py is not called, and the output is still empty.

**Comment by mistoFENG** [comment]
> _🤖_
> 
> Based on the information you've provided and the context from the LlamaIndex repository, it seems like the issue you're experiencing might be due to the `read` function in `llama_index/tools/tool_spec/load_and_search/base.py` not being called. This function is responsible for querying the index and returning the response. If it's not being called, no query is made and thus no response is returned.
> 
> The `read` function is only called if there is content loaded into the index. If no content has been loaded, the function returns an error message. Therefore, you should ensure that the `load` function is being called and that it is successfully loading content into the index before attempting to query the index.
> 
> Here's the relevant code from `llama_index/tools/tool_spec/load_and_search/base.py`:
> 
> ```python
> def load(self, *args: Any, **kwargs: Any) -> Any:
>     # Call the wrapped tool and save the result in the index
>     docs = self._tool(*args, **kwargs).raw_output
>     if self._index:
>         for doc in docs:
>             self._index.insert(doc, **self._index_kwargs)
>     else:
>         self._index = self._index_cls.from_documents(docs, **self._index_kwargs)
>     return (
>         "Content loaded! You can now search the information using read_{}".format(
>             self._metadata.name
>         )
>     )
> 
> def read(self, query: str) -> Any:
>     # Query the index for the result
>     if not self._index:
>         return (
>             "Error: No content has been loaded into the index. "
>             f"You must call {self._metadata.name} first"
>         )
>     query_engine = self._index.as_query_engine()
>     response = query_engine.query(query)
>     return str(response)
> ```
> 
> If the `load` function is being called and the content is being loaded into the index, but the `read` function is still not being called, there might be an issue with how you're calling the `read` function. Make sure you're calling it correctly and passing the correct arguments.
> 
> Regarding the `streaming=True` parameter in the `query_engine.query()` function, it is used to enable streaming of the query results. This means that the results are returned as they become available, rather than waiting for all results to be ready before returning them. This can be beneficial in situations where the query might take a long time to complete, as it allows you to start processing the results immediately, rather than having to wait for the entire query to finish.
> 
> The output of the function changes when streaming is enabled. Instead of returning a single response object, it returns a streaming response object. This object can be used to access the results as they become available. In the provided context, the `print_response_stream()` method is used to print the results as they are streamed.
> 
> Here is the relevant code:
> 
> ```python
> query_engine = index.as_query_engine(
>     streaming=True,
> )
> streaming_response = query_engine.query(
>     "What did the author do growing up?",
> )
> streaming_response.print_response_stream()
> ```
> 
> In this code, `streaming=True` is passed to `index.as_query_engine()` to enable streaming. Then, `query_engine.query()` is called with a query string, and the resulting streaming response object is stored in `streaming_response`. Finally, `streaming_response.print_response_stream()` is called to print the results as they are streamed.
> 
> I also found a similar issue in the LlamaIndex repository: [StableLM not returning response when querying with GPTSimpleVectorIndex](https://github.com/run-llama/llama_index/issues/1334). The suggested solution was to update to the latest version of LlamaIndex. If you haven't done so already, you might want to consider updating to the latest version, which is v0.9.14.post1.
> 
> I hope this helps! If you have any other questions or need further clarification, please let me know.
> 
> ## Sources
> * [StableLM not returning response when querying with GPTSimpleVectorIndex](https://github.com/run-llama/llama_index/issues/1334)
> * [llama_index/tools/tool_spec/load_and_search/base.py](https://github.com/run-llama/llama_index/blob/main/llama_index/tools/tool_spec/load_and_search/base.py)
> * [docs/module_guides/deploying/query_engine/usage_pattern.md](https://github.com/run-llama/llama_index/blob/main/docs/module_guides/deploying/query_engine/usage_pattern.md)
> 
> This response is meant to be useful and save you time. It is **not meant to be a precise solution**, but rather a starting point for your own research.
> 
> Help me be more useful! Please leave a 👍 if this is helpful and 👎 if it is irrelevant.
> 
> If you want to continue the conversation, start your reply with @dosu-bot.

I have updated to v0.9.14.post1
Additionally, non-streaming mode has results, but the stream is still empty
```
print("+++++++++++++++complete+++++++++++++++++++++")
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
print(response)

print("+++++++++++++++stream complete+++++++++++++++++++++")
query_engine = index.as_query_engine(streaming=True)
streaming_response = query_engine.query("What did the author do growing up?")
streaming_response.print_response_stream()

```
Return results:
```
+++++++++++++++complete+++++++++++++++++++++                                                 
1. The author lived with their father and grandfather.                                       
2. The author played lots of games.                                                          
3. The author liked to read about science and mathematics.                                   
+++++++++++++++stream complete+++++++++++++++++++++
```
Please help and take a look @logan-markewich

**Comment by Jeevi10** [comment]
I have the same issue! 
llama_index 0.9.19
vllm 0.2.7
Please let me know if this was fixed

**Comment by logan-markewich** [comment]
@Jeevi10 @mistoFENG as a workaround, you will likely have better results if you launch vLLM in openai compatible mode, and use OpenAILike

Adjust settings as needed
```
from llama_index.llms import OpenAILike

llm = OpenAILike(model="my_model"  api_base="http://127.0.0.1:8000/v1", context_window=3900, is_chat_model=False, ...)`
```

**Comment by Jeevi10** [comment]
@logan-markewich Thanks.

https://github.com/run-llama/llama_index/blob/main/llama_index/llms/llm.py in line 59

def stream_completion_response_to_tokens(
    completion_response_gen: CompletionResponseGen,
) -> TokenGen:
    """Convert a stream completion response to a stream of tokens."""

    def gen() -> TokenGen:
        for response in completion_response_gen:
            yield response.delta or ""

    return gen()
    
  default llmbase is yeilds response.delta or "" 
  
  However,
  https://github.com/run-llama/llama_index/blob/main/llama_index/llms/vllm.py line 360
  
   def stream_complete(
        self, prompt: str, formatted: bool = False, **kwargs: Any
    ) -> CompletionResponseGen:
        kwargs = kwargs if kwargs else {}
        params = {**self._model_kwargs, **kwargs}

        from vllm import SamplingParams

        # build sampling parameters
        sampling_params = SamplingParams(**params).__dict__
        sampling_params["prompt"] = prompt
        response = post_http_request(self.api_url, sampling_params, stream=True)

        def gen() -> CompletionResponseGen:
            for chunk in response.iter_lines(
                chunk_size=8192, decode_unicode=False, delimiter=b"\0"
            ):
                if chunk:
                    data = json.loads(chunk.decode("utf-8"))

                    yield CompletionResponse(text=data["text"][0])

        return gen()
        
  this code returns text, delta of this reponse is none. That's why its returning empty string. I made changes in source code to make it work but I would recommend to fix this bug in main branch.

**Comment by logan-markewich** [comment]
I'm not sure if I fully understand the issue or the change you made. BUT! I would really encourage you to make PR for this :)
