### ISSUE TITLE
[Question]: Similarity_top_k changes retriever nodes ordering

### ISSUE THREAD

**Issue by Cotum** [run-llama/llama_index#9401]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Dear all,
I have a problem concerning the ordering of the retrieved chunks. This ordering changes when I change the similarity_top_k value everytime I perform a retriever.retrieve(text) with the same text.

For example , with similarity_top_k = 3, the top three chunks texts filenames are 10202.txt, 10202.txt and 01627.txt.
But if I change it to similarity_top_k = 30, the top three changes and become 00234.txt, 10202.txt and 00234.txt.
I expect that this shouldn't happen, as the similarity_top_k gives the top scores within the total nodes of the collection and thus the ranking shouldn't depend on this value. Am I right ? 

I am using ChromaDB to save my embeddings and using HuggingFace model intfloat-multilingual-e5-base as embed_model.

**Comment by Cotum** [comment]
Yes definitely, this is the code that does the problem :

The initialisation of the index :
`
db = chromadb.PersistentClient(path="git/chroma_db/base",settings=Settings(anonymized_telemetry=False))

logging.basicConfig(stream=sys.stdout, level=logging.INFO)  # Change INFO to DEBUG if you want more extensive logging
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))

llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])

embed_model_name = "intfloat/multilingual-e5-base"
embed_model_name_local = "local:"+embed_model_name
set_global_service_context(None)
service_context = ServiceContext.from_defaults(embed_model=embed_model_name_local, 
                                               chunk_size=256)
set_global_service_context(service_context)

chroma_collection = db.get_or_create_collection("All_docs")
vector_store = ChromaVectorStore(chroma_collection=chroma_collection)
index = VectorStoreIndex.from_vector_store(
    vector_store,
)
`

Here is the part where I don't have the same ordering when I change similarity_top_k : 
`
retriever = index.as_retriever(similarity_top_k=20)
nodes_ = retriever.retrieve(text)
`

Then when doing `[nodes_[i].metadata['filename'] for i in range(5)]`, I obtain different filename for the differents similarity_top_k.

**Comment by logan-markewich** [comment]
Running the same code with chromadb, I get

```python
['bc1daa60-9056-417d-ac30-f0f62352e3b5', '13390675-61bd-468a-8c4a-67261f157ec7', '46a2a4d1-2826-4f3c-8516-349ab9cd5b37']
['bc1daa60-9056-417d-ac30-f0f62352e3b5', '13390675-61bd-468a-8c4a-67261f157ec7', '46a2a4d1-2826-4f3c-8516-349ab9cd5b37']
['bc1daa60-9056-417d-ac30-f0f62352e3b5', '13390675-61bd-468a-8c4a-67261f157ec7', '46a2a4d1-2826-4f3c-8516-349ab9cd5b37']
['bc1daa60-9056-417d-ac30-f0f62352e3b5', '13390675-61bd-468a-8c4a-67261f157ec7', '46a2a4d1-2826-4f3c-8516-349ab9cd5b37']
```

So actually, not sure what the issue is

**Comment by Cotum** [comment]
Dear all,
sorry for the late answer as I found the explanation earlier last week. 
This is indeed due to the algorithm used by ChromaDB.
Most of the issue refering to this problem lead to this issue : https://github.com/chroma-core/chroma/issues/1068 where it is explain that :

> This is a behavior of the Approximate Nearest Neighbors algorithm we use. Essentially, as you increase your n_results, you implicitly increase a search-time parameter of the index - ef_search - which you can think of as controlling how exhaustive your search is. The default ef_search is 10 (
> 
> [chroma/chromadb/segment/impl/vector/hnsw_params.py](https://github.com/chroma-core/chroma/blob/9d444d76e38cee87faaaafca1dadfa33e778f9d5/chromadb/segment/impl/vector/hnsw_params.py#L58)
> 
> Line 58 in [9d444d7](https://github.com/chroma-core/chroma/commit/9d444d76e38cee87faaaafca1dadfa33e778f9d5)
>  self.search_ef = int(metadata.get("hnsw:search_ef", 10)) 
> ).
> 
> However if you set n_results > 10, you will implictly increase your ef_search. If you want the behavior of these two calls to be consistent, you need to set ef_search to be consistent across calls.

Apparently, there is no clear solution to this problem except by decreasing the retrieval timing. Therefore I decided to switch to another database type.
Thank you again for your help on this issue !

**Comment by eugenepyvovarov** [comment]
I found for my self the solution is to update chromed connector and use bigger number for the n_results, but limit amount of output limit with n_results value.
