### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kindler-king** [run-llama/llama_index#9405]
### Bug Description

Until 4th December, 2023 my app used to work perfectly fine.
However, after I restarted my caprover server from AWS on 5th December, 2023 to solve an issue with the deployment. The service which was using Llama broke down with an **ERROR:  Exception in ASGI application** , The code was reaching till before the highlighted part and then failing here for some reason.

When running locally this was working but whenever I am trying to run it through my app, I am getting this ASGI exception in the logs. I would love to hear about any possible solutions as my app has been down for 4 days now due to this issue.

### Version

0.7.4

### Steps to Reproduce

![Capture](https://github.com/run-llama/llama_index/assets/53633591/3b1b4fd0-80e1-4ee8-8c3f-bab499229a66)

**Comment by logan-markewich** [comment]
@kindler-king the issue happens on v0.7.4?  Or you updated llama-index and it stopped working?

Which line exactly is breaking, it's not quite clear? Do you know what the underlying error/traceback is or you only know which line breaks?

**Comment by logan-markewich** [comment]
Maybe something is wrong with node text or metadata?

When you run locally, is it with the same nodes that the server is using?

**Comment by kindler-king** [comment]
Yeah @logan-markewich , I am sure it's independent of the node text. 
And yeah it's the same set of nodes both from the server and locally. 

Do you think there's any relation with using an older version of llama-index? 
I can update the codebase to the latest version, it's just wierd that it works when I test locally but doesn't work when I want to deploy.

Do let me know your thoughts.

**Comment by logan-markewich** [comment]
Hmmm yea this is super tricky. Without an actually traceback to follow, or a way to reproduce locally, this will be extremely hard to debug.

And that sucks, because 0.7.x -> 0.9.x will probably have a few (minor) changes needed

**Comment by kindler-king** [comment]
Hey @logan-markewich , apologies for the late update.
So after lots of back and forth, I updated to the latest llama-index version and the latest openai version.


`if llama:        
            ### CHANGING STUFF HERE TO SEND EXPANDED_UNITS TO LLAMAINDEX
            print("####### entering llama###########")
            num_units = len(expanded_units)
            nodes = []
            for i in range(num_units):
                unit = expanded_units[i]
                text = unit[2]
                url = unit[4]
                url = self.filename_to_url(url)
                metadata = {"title": url}
                node = Node(text= text, id = i, metadata = metadata)
                nodes.append(node)
            print("reached line 979")
            node_num = 0
            
            while node_num < num_units - 1:
                    current_node = nodes[node_num]
                    next_node = nodes[node_num+1]
                    
                   # current_node.relationships[DocumentRelationship.NEXT]=next_node.get_doc_id()
                   # next_node.relationships[DocumentRelationship.PREVIOUS]=current_node.get_doc_id()

                    current_node.relationships[NodeRelationship.NEXT] = RelatedNodeInfo(node_id=next_node.node_id)
                    next_node.relationships[NodeRelationship.PREVIOUS] = RelatedNodeInfo(node_id=current_node.node_id)

                    node_num += 1
            
            print("reached line 992")    
            ###index = GPTVectorStoreIndex([])
            
            index = VectorStoreIndex([])
            print("reached line 996")
            ###temporarily commenting out
            index.insert_nodes(nodes)
            #index.build_index_from_nodes(nodes)
            print("reached line 998")    
            from llama_index.query_engine import RetrieverQueryEngine
            print("reached line 1004")
#from llama_index.indices.postprocessor import SimilarityPostprocessor

            #from langchain import OpenAI

           # llm_predictor = LLMPredictor(llm=OpenAI(temperature=0, model_name="text-davinci-003"))
            ###llm = OpenAI(temperature=0, model="gpt-4", max_input_size = 4096, num_output = 256, max_overlap = 20)
            llm = OpenAI(model='gpt-3.5-turbo', temperature=0, max_tokens=3000)
            print("reached line 1014")
            embed_model = OpenAIEmbedding()
            text_splitter = TokenTextSplitter(
            separator=" ",
            chunk_size=1024,
            chunk_overlap=20,
            backup_separators=["\n"],
            tokenizer=tiktoken.encoding_for_model("gpt-3.5-turbo").encode
            )`

As you can see in the attached code, the new error I am getting is in the following line:
` llm = OpenAI(model='gpt-3.5-turbo', temperature=0, max_tokens=3000)`

![Screenshot from 2023-12-16 08-02-57](https://github.com/run-llama/llama_index/assets/53633591/797e5dd8-518f-45ea-9499-58e81faf7491)

For some reason, whenever I pass any parameter as in my code, it throws this weird error.
Now, I have run this piece of  code independently of my codebase, and the OpenAI line dosent throw any error. But for some reason, it throws this wierd error and dosen't want to accept any parameter given to it.

Any leads on what could be causing this wierd bug?

**Comment by logan-markewich** [comment]
Did you import OpenAI from llama index?

`from llama_index.llms import OpenAI`
