### ISSUE TITLE
[Bug]: type errors with `RedisVectorStore` after #9135

### ISSUE THREAD

**Issue by jamesbraza** [run-llama/llama_index#9407]
### Bug Description

https://github.com/run-llama/llama_index/pull/9135 moved `RedisVectorStore` to inherit from `BasePydanticVectorStore`. An unfortunate side effect here is now type checkers (`mypy==1.7.1`) fail for `RedisVectorStore`:

```none
a.py:130:26: error: Argument "vector_store" to "from_defaults" of "StorageContext" has incompatible type "RedisVectorStore"; expected "VectorStore | None"  [arg-type]
                vector_store=RedisVectorStore(index_name=index_name),
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
a.py:130:26: note: Following member(s) of "RedisVectorStore" have conflicts:
a.py:130:26: note:     Expected:
a.py:130:26: note:         def async_add(self, nodes: list[BaseNode], **kwargs: Any) -> Coroutine[Any, Any, list[str]]
a.py:130:26: note:     Got:
a.py:130:26: note:         def async_add(self, nodes: list[BaseNode]) -> Coroutine[Any, Any, list[str]]
```

### Version

0.9.11

### Steps to Reproduce

Pass a `RedisVectorStore` into `StorageContext.from_defaults`

**Comment by logan-markewich** [comment]
easy enough fix it looks like (although also not too urgent, since we aren't using that version of mypy yet)

**Comment by jamesbraza** [comment]
Something between 0.9.11 and 0.9.17 fixed this. Closing it out
