### ISSUE TITLE
[Question]: About setting the context_window and num_output

### ISSUE THREAD

**Issue by debraj135** [run-llama/llama_index#9408]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm wondering what is the right strategy to avoid running over the token limit after deploying llamaindex RAG in a Q&A setting. 

Is my understanding correct that context_window + number of tokens in the prompt template should be less than the max context_window of an llm?

**Comment by logan-markewich** [comment]
Context window is the absolute max the LLM can input.

num_output is how many tokens there should be room left to generate in the prompt (default is 256)

LlamaIndex does some token counting under the hood to try and make sure that every LLM prompt has room to generate `num_output` tokens.

**Comment by logan-markewich** [comment]
Remember, LLMs generate tokens one at a time, add it to the input, and generate the next.

This is why you need to "leave room" in the initial input to generate a certain number of tokens

**Comment by nbahar-intel** [comment]
@logan-markewich If we use `as_chat_engine`, with message history, how do we tell it to automatically cut older message history with the prompt, so that we don't eventually reach that limit?
Every conversation I have, will get to that limit in a point of time and just fail to prompt (negative token count error)

**Comment by augmentedstartups** [comment]
> @logan-markewich If we use `as_chat_engine`, with message history, how do we tell it to automatically cut older message history with the prompt, so that we don't eventually reach that limit? Every conversation I have, will get to that limit in a point of time and just fail to prompt (negative token count error)

I have the same issue. The history is adding too much context which needs to be truncated
