### ISSUE TITLE
[Bug]: OpenAI agent with query engine tools crashes while calling the tool

### ISSUE THREAD

**Issue by vaibhavp4** [run-llama/llama_index#9411]
### Bug Description

I setup an openai agent with query engine tools 

The agent was able to start and enter the chat repl

But it fails as soon as you submit a query
![image](https://github.com/run-llama/llama_index/assets/4822281/24d48085-80a4-47d5-8009-4c14238e195e)

(The editor also warns that agent code doesn't see query engine tools as a subclass of BaseTools)

### Version

0.9.13

### Steps to Reproduce

- setup openai agent with query tools engine as per this documentation https://docs.llamaindex.ai/en/stable/examples/agent/openai_agent_with_query_engine.html

- Run the agent - agent.chat_repl()

- Submit a query

### Relevant Logs/Tracbacks

```shell
raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "'Tesla April 2022 Valuation' does not match '^[a-zA-Z0-9_-]{1,64}$' - 'tools.0.function.name'", 'type': 'invalid_request_error', 'param': None, 'code': None}}
```

**Comment by logan-markewich** [comment]
As you can see from the error, the name you gave your tool is invalid 

It can only be alpha-numeric with dashes or underscores, but your tool name has spaces
