### ISSUE TITLE
[Bug]: Fetching source node of ObjectType DOCUMENT

### ISSUE THREAD

**Issue by dheerajiiitv** [run-llama/llama_index#9428]
### Bug Description

Why are we fetching ` ObjectType`: DOCUMENT, when source node is not None. As we are checking it node_id, it will not exists anyway. 

Current Code:
```
def _build_node_list_from_query_result(
        self, query_result: VectorStoreQueryResult
    ) -> List[NodeWithScore]:
           ....
            for i in range(len(query_result.nodes)):
                source_node = query_result.nodes[i].source_node
                if (not self._vector_store.stores_text) or (
                    source_node is not None and **source_node.node_type != ObjectType.TEXT**
                ):
                    node_id = query_result.nodes[i].node_id
                    if node_id in self._docstore.docs:
                        query_result.nodes[
                            i
                        ] = self._docstore.get_node(node_id)

        log_vector_store_query_result(query_result)

        node_with_scores: List[NodeWithScore] = []
        for ind, node in enumerate(query_result.nodes):
            score: Optional[float] = None
            if query_result.similarities is not None:
                score = query_result.similarities[ind]
            node_with_scores.append(NodeWithScore(node=node, score=score))

        return node_with_scores

```
`source_node.node_type != ObjectType.TEXT -> source_node.node_type != ObjectType.TEXT and source_node.node_type != ObjectType.DOCUMENT`

### Version

0.8.48

### Steps to Reproduce

While inserting nodes to the vector store, just add source node to type DOCUMENT. It will start looking for this obect in docstore, which is not use at all.

**Comment by logan-markewich** [comment]
This is old backwards compatibility code. If the source type is not text, we used to have to get the node from the docstore.

However, now we can store all node types in the vector store 
https://github.com/run-llama/llama_index/blob/aa6726706476e0f957a8d57a5ca89e519e93bad7/llama_index/vector_stores/utils.py#L68

This just needs to be cleaned up at some point, not a huge deal

**Comment by logan-markewich** [comment]
Also, the code you quoted does not actually exist anymore either -- it uses the much more efficient `document_exists` function 
https://github.com/run-llama/llama_index/blob/0858575c8cd192bec3c137ffffe5691e98d9f6e8/llama_index/indices/vector_store/retrievers/retriever.py#L138

I would remove it entirely, but still scared about breaking backwards compatibility lol

Going to close this for now
