### ISSUE TITLE
[Question]: How to access responses array in "accumulate" response mode?

### ISSUE THREAD

**Issue by r3shma** [run-llama/llama_index#9434]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am running a query on a set of source nodes in accumulate response mode and I get a string response that looks like:
![image](https://github.com/run-llama/llama_index/assets/109542613/e453f5b8-84a7-4667-9844-836d756079c9)
Is there any way to access this response in the form of an array? I have a use case where I need to map each response to it's source node id and save the mapping. 

Also, is it possible to run queries in parallel on the document nodes instead of having to query each node sequentially?
TIA.

**Comment by logan-markewich** [comment]
To run async, set `use_async=True` in either the `index.as_query_engine(..., use_async=True)` or response synthesizer directly

**Comment by r3shma** [comment]
Thank you!

**Comment by r3shma** [comment]
Sorry @logan-markewich, could you please help with another related question I had: 
Would the number of responses always be equal to the number of source nodes? I am basically trying to modify the text in the source node using an llm, so the response node should contain all the text in the source node plus some modifications. But, I see that the response is sometimes much shorter than the text in the source node. I am wondering why this happens and how to overcome this? If it is related to token limit - why? I assumed that llama index would take care of this by chunking internally. Adding my code here to explain what I mean:
```
    nodes = create_nodes() # creating TextNode list manually
    index = SummaryIndex(nodes, service_context=service_context_gpt)
    print(test_nodes[0].get_text)  # has the entire text
    query_engine = test_index.as_query_engine(response_mode="accumulate", use_async=True)
    query="You are a helpful assistant. Output a revised version of the text with the correct html line breaks (<br>)."
    query_engine.update_prompts(
        {"response_synthesizer:text_qa_template": text_qa_template}
    )
    response = query_engine.query(query) # response corresponding to the source node has text cut off
    ```
