### ISSUE TITLE
[Bug]: [nltk_data] Error loading punkt: <urlopen error [WinError 10060] A

### ISSUE THREAD

**Issue by umang299** [run-llama/llama_index#9435]
### Bug Description

I am using a vector Index which connects to a chromaDB client as my database. I have initialized the index as a chat engine. When the query the chat engine, two things happen:

1. The response time is nearly 2-3mins.
2. It throws the below warning

```
[nltk_data] Error loading punkt: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
```
 

### Version

0.9.8.post1

### Steps to Reproduce

Clone, setup and run the below repository: (Follow readme for instructions)
https://github.com/umang299/document-gpt

**Comment by aakashag1** [comment]
@umang299 - Are you using jiofiber by any chance?

Seems like jiofiber can't access punkt tokenizer. Try accessing this file - https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages/tokenizers/punkt.xml

If you are not able to open above file then connect with your mobile internet and run the process. It worked for me with Airtel 4G phone data.

**Comment by umang299** [comment]
@aakashag1 I was able to solve this problem. You are right it was a problem caused by JioFiber. Thanks for the response though.
