### ISSUE TITLE
[Bug]: Metadata filter not working with Elastic search indexing 

### ISSUE THREAD

**Issue by amitguptadumka** [run-llama/llama_index#9439]
### Bug Description

While retrieving from ES with multiple metadatafilter condition(OR/AND) its not taking it into account. It always performs an AND operation even if its explicitly mentioned OR.
Example below code should filter and retrieve only 'mafia' or "Stephen King" bit its not doing as expected.

filters = MetadataFilters(
    filters=[
        MetadataFilter(key="theme", value="Mafia"),
        MetadataFilter(key="author", value="Stephen King"),
    ],
    condition=FilterCondition.OR,
)

retriever = index.as_retriever(filters=filters)

### Version

0.9.13

### Steps to Reproduce

nodes = [
TextNode(
text="The Shawshank Redemption",
metadata={
"author": "Stephen King",
"theme": "Friendship",
},
),
TextNode(
text="The Godfather",
metadata={
"director": "Francis Ford Coppola",
"theme": "Mafia",
},
),
TextNode(
text="Inception",
metadata={
"director": "Christopher Nolan",
},
),
]

filters = MetadataFilters(
    filters=[
        MetadataFilter(key="theme", value="Mafia"),
        MetadataFilter(key="author", value="Stephen King"),
    ],
    condition=FilterCondition.OR,
)

retriever = index.as_retriever(filters=filters)

**Comment by logan-markewich** [comment]
We just recently added new metadata filters -- support for elastic is not fully added yet. 

Would definitely welcome a PR if you are familiar with elastic (I definitely am not haha)

**Comment by hatianzhang** [comment]
yea welcome to add a pr for supporting ES. We are not supporting ES yet
