### ISSUE TITLE
[Bug]: LlamaIndex incompatibility as of 0.9.14

### ISSUE THREAD

**Issue by anticorrelator** [run-llama/llama_index#9443]
### Bug Description

LlamaIndex refactored `llama_index.llms.base` breaking some of our type checking and tests. We need to investigate and update for compatibility.

### Version

0.9.14

### Steps to Reproduce

both type checks (`hatch run type:check`) and `pytest` fails

**Comment by logan-markewich** [comment]
@anticorrelator just curious, what was the issue? I can probably at least diagnose the problem on the other repo

**Comment by anticorrelator** [comment]
@logan-markewich we were using the `ChatResponse` and `ChatMessage` types to figure out how to format our logs. I haven't investigated too deeply but we're getting `mypy` errors suggesting that those types aren't explicitly defined anymore in `llama_index.llms.base` so our formatting logic is probably out of date
