### ISSUE TITLE
[Bug]: SubQuestionQueryEngine raises an error at line: query_engine = self._query_engines[sub_q.tool_name] KeyError:

### ISSUE THREAD

**Issue by wuzhongmiao** [run-llama/llama_index#9448]
### Bug Description

hi!
As always thanks to your amazing tools, I've been playing with SubQuestionQueryEngine, but the following problem occurred：

```python
File "D:\tools\Anaconda\install\envs\paddle_cpu\lib\site-packages\llama_index\query_engine\sub_question_query_engine.py", line 221, in _aquery_subq
    query_engine = self._query_engines[sub_q.tool_name]
KeyError: '信用观点1'
```
My code when I am using this is basically copy paste from tutorial:

```python
# define query engines and tools
xy_engine = get_query_engine(xy_index)
hg_engine = get_query_engine(hg_index)

query_engine_tools = [
    QueryEngineTool(
        query_engine=xy_engine,
        metadata=ToolMetadata(
            name="信用债观点1",
            description="提供了信用债观点和经济观点",
        ),
    ),
    QueryEngineTool(
        query_engine=hg_engine,
        metadata=ToolMetadata(
            name="宏观经济观点1",
            description="提供了宏观经济观点",
        ),
    )
]
query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools
)
```
I intercepted the debug message:
code：query_engine = self._query_engines[sub_q.tool_name]
![bug1](https://github.com/run-llama/llama_index/assets/60603266/7475c619-aa83-4c9d-9a3b-3deef60f55b9)
![bug2](https://github.com/run-llama/llama_index/assets/60603266/cdff0c70-9fea-473f-9338-b3a179261e9f)

### Version

0.9.13

### Steps to Reproduce

It seems that this does not support Chinese, and one of the words is missing. I have tried several times in both Chinese and English, but there is no problem, is that right?

**Comment by logan-markewich** [comment]
Yea the sub question query engine depends on the LLM spelling the name properly, but it seems that the LLM was not able to spell the name of the tool correctly.

This is kind of out of our hands? We prompt the LLM, and depend on it to do it's job properly 😅 

I think this will be an issue with most LLMs. I might write the tool names in English and see if performance improves.
