### ISSUE TITLE
[Bug]: Logging level overrides

### ISSUE THREAD

**Issue by aaronbannin** [run-llama/llama_index#9450]
## Overview
Logging configs in files over ride developer configs, leading to unexpected behavior. Repro included below.

## Possible Solutions
1. Have only one `logger.setLevel()` invocations in package.
2. Allow developer to configure log level with env var or singleton.
```LLAMA_INDEX_LOG_LEVEL=DEBUG```
```llama_index.logger.level = "DEBUG"```

Happy to help out here if there is preferred implementation.

### Version

0.9.13

### Steps to Reproduce

As a developer, I want to see debug level log lines to understand how Llama Index is working. I implement the following lines from the [documentation](https://docs.llamaindex.ai/en/stable/understanding/tracing_and_debugging/tracing_and_debugging.html#basic-logging):

```python
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
```

I expect to see the [this log line](https://github.com/run-llama/llama_index/blob/771219236021c9cf906c598bb6f750539c791e65/llama_index/agent/openai_agent.py#L366) in the console, but it does not appear.

If I remove the [logging config in the file](https://github.com/run-llama/llama_index/blob/771219236021c9cf906c598bb6f750539c791e65/llama_index/agent/openai_agent.py#L30), the debug configuration works as expected.

### Relevant Logs/Tracbacks

```shell
Logging excerpt AFTER removing the logging config override:

DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:openai._base_client:HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"
DEBUG:llama_index.agent.openai_agent:Break: should continue False
Break: should continue False
```

The last 2 lines do not appear in released library.
```

**Comment by logan-markewich** [comment]
tbh overall we have not done a great job even adding logs to the package.

At some point, this line of code was added to the library, which I disagree with quite a bit but haven't made it a priority to fix 
https://github.com/run-llama/llama_index/blob/771219236021c9cf906c598bb6f750539c791e65/llama_index/__init__.py#L89

If you have the time, would love to see a) setting the log level improved and b) actually adding a few more important debug logs (llm inputs/outputs, retrieved nodes, etc.)

**Comment by aaronbannin** [comment]
> which I disagree with quite a bit

Can you expand a bit? I'd love to understand the downsides.
