### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by jzhao62** [run-llama/llama_index#9453]
### Feature Description

Support for GraphDatabase like Neo4J ?

### Value of Feature

- graph database is gaining popularity these days and turned out to be more suitable than nosql or sql in many complex situations.
- graph database has an intrinsic relationship with LLM due to its network structure as opposed to tabular structure you see in sql or nosql

**Comment by logan-markewich** [comment]
We support neo4j, and a few other graph concepts

https://docs.llamaindex.ai/en/stable/examples/index_structs/knowledge_graph/Neo4jKGIndexDemo.html#neo4j-graph-store

https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_rag_query_engine.html

https://docs.llamaindex.ai/en/stable/examples/query_engine/knowledge_graph_query_engine.html
