### ISSUE TITLE
Facing issue with Sub Question Query Engine.

### ISSUE THREAD

**Issue by pranavbhat12** [run-llama/llama_index#9460]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey,

I am facing issue when implementing the sub question query engine.We have created separate elastic search indexes and hybrid retriever for each pdf docs.After this creating query engine tools and creating sub question query engine getting this error:

_ValueError                                Traceback (most recent call last)
File <timed exec>:4

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_query_engine.py:30, in BaseQueryEngine.query(self, str_or_query_bundle)
     28 if isinstance(str_or_query_bundle, str):
     29     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 30 return self._query(str_or_query_bundle)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/query_engine/sub_question_query_engine.py:132, in SubQuestionQueryEngine._query(self, query_bundle)
    128 def _query(self, query_bundle: QueryBundle) -> RESPONSE_TYPE:
    129     with self.callback_manager.event(
    130         CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    131     ) as query_event:
--> 132         sub_questions = self._question_gen.generate(self._metadatas, query_bundle)
    134         colors = get_color_mapping([str(i) for i in range(len(sub_questions))])
    136         if self._verbose:

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/question_gen/llm_generators.py:73, in LLMQuestionGenerator.generate(self, tools, query)
     66 prediction = self._llm_predictor.predict(
     67     prompt=self._prompt,
     68     tools_str=tools_str,
     69     query_str=query_str,
     70 )
     72 assert self._prompt.output_parser is not None
---> 73 parse = self._prompt.output_parser.parse(prediction)
     74 parse = cast(StructuredOutput, parse)
     75 return parse.parsed_output

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/question_gen/output_parser.py:13, in SubQuestionOutputParser.parse(self, output)
     11 json_dict = parse_json_markdown(output)
     12 if not json_dict:
---> 13     raise ValueError(f"No valid JSON found in output: {output}")
     15 sub_questions = [SubQuestion.parse_obj(item) for item in json_dict]
     16 return StructuredOutput(raw_output=output, parsed_output=sub_questions)

ValueError: No valid JSON found in output:_
__

**Code**:
def load_index_query_engine(llama_doc_list):
     query_engine_list={}
    for pdf_doc in doc_list:
           index = load_index_from_storage(storage_context) 
            vector_retriever = index.as_retriever(
            similarity_top_k=10,
        )
        nodes = service_context.node_parser.get_nodes_from_documents(llama_doc_list[pdf_doc])
        bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=10)       
        hybrid_retriever = HybridRetriever(vector_retriever, bm25_retriever)
        reranker = CohereRerank(api_key=api_key,top_n=3)
        query_engine = RetrieverQueryEngine.from_args(
            retriever=hybrid_retriever,
            node_postprocessors=[reranker],
            service_context=service_context,
        )     
        query_engine_list[pdf_doc]=query_engine           
return query_engine_list

for query_eng in query_engine_list:  

    query_tool=QueryEngineTool(
        query_engine=query_engine_list[query_eng],
        metadata=ToolMetadata(
            name=query_eng,
            description=(
                "Description",
            ),
        ),
    )
    query_engine_tools.append(query_tool)

sub_que_query_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools,
    service_context=service_context,
    use_async=False,  
)

with torch.no_grad() and torch.inference_mode():
    response = sub_que_query_engine.query("question")
    print(response)

How can we resolve this?

**Comment by logan-markewich** [comment]
What LLM are you using?

The subquestion query engine depends on the LLM writing correct JSON so that we can parse the questions and indexes it is directing questions to.

Really, the only open-source LLM I've seen this work reliably with is zephyr -- most other LLMs either do not follow instructions, or write JSON that is nearly impossible to parse

**Comment by pranavbhat12** [comment]
Llama 70B I am using.
