### ISSUE TITLE
[Feature Request]: Support AzureOpenAIMultiModal

### ISSUE THREAD

**Issue by mingqxu7** [run-llama/llama_index#9471]
### Feature Description

Azure OpenAI now has gpt-4-vision in their preview.  We should support AzureOpenAIMultiModal class.  

### Reason

My customers are using Azure OpenAI and would like to evaluate gpt-4-vision models.  

### Value of Feature

As llama-index have been supporting Azure models, it is self-evident that customers would be interested in evaluating the innovative capabilities that gpt-4-vision has to offer.

**Comment by mingqxu7** [comment]
You are referring to the AzureOpenAI Class not OpenAIMultiModal.  The latter class's constructor is as follows:

 super().__init__(
            model=model,
            temperature=temperature,

As you can see it does not support Azure OpenAI

**Comment by joelbarmettlerUZH** [comment]
Working on this @mingqxu7, PR coming this week (hopefully)
