### ISSUE TITLE
[Question]: I only want to chunk text, not metadata, how can I do that?

### ISSUE THREAD

**Issue by Plusholic** [run-llama/llama_index#9474]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

To use the RecursiveRetriver, I wrote the following
But ValueError: Metadata length (75) is longer than chunk size (64). Consider increasing the chunk size or decreasing the size of your metadata to avoid this. .
I have about 5000 files, each stored in different folders, so the metadata (file paths) are long. Is it possible to keep the metadata and only chunk the text? I have specified the include_metadata=False option, but it doesn't seem to work.

`Isub_chunk_sizes = [64,128]
sub_node_parsers = [
    SimpleNodeParser.from_defaults(chunk_size=c, chunk_overlap=0, include_metadata=False) for c in sub_chunk_sizes
]

all_nodes = []
for base_node in base_nodes:
    for n in sub_node_parsers:
        sub_nodes = n.get_nodes_from_documents([base_node])
        sub_inodes = [
            IndexNode.from_text_node(sn, base_node.node_id) for sn in sub_nodes
        ]
        all_nodes.extend(sub_inodes)

    # also add original node to node
    original_node = IndexNode.from_text_node(base_node, base_node.node_id)
    all_nodes.append(original_node)
    
all_nodes_dict = {n.node_id: n for n in all_nodes}`

**Comment by logan-markewich** [comment]
Since metadata is included in both LLM and embedding calls, we need to take the metadata into consideration to ensure the chunks are the requested size.

If you don't want metadata to be included in LLM or embedding calls, you can exclude it

```
for node in sub_nodes:
  node.excluded_llm_metadata_keys = list(node.metadata.keys())
  node.excluded_embed_metadata_keys=list(node.metadata.keys())
```

**Comment by anderson2805** [comment]
I believe this should be a bug, it is including metadata in chunksize counting even if we do not include it in embedding.

This should only be trigger if n.get_content(metadata_mode="all";

''' sentence.py
    def split_text_metadata_aware(self, text: str, metadata_str: str) -> List[str]:
        metadata_len = len(self._tokenizer(metadata_str))
        effective_chunk_size = self.chunk_size - metadata_len # Shold remove - metadata_len
        if effective_chunk_size <= 0:
            raise ValueError(
                f"Metadata length ({metadata_len}) is longer than chunk size "
                f"({self.chunk_size}). Consider increasing the chunk size or "
                "decreasing the size of your metadata to avoid this."
            )
"""

Correct me if my understanding is wrong.
