### ISSUE TITLE
[Bug]: ObjectIndex +VectorStoreIndex gets 'code': '404', 'message': 'Resource not found'

### ISSUE THREAD

**Issue by dgaoh** [run-llama/llama_index#9478]
### Bug Description

 directly run the first set of code in your object_index.ipynb, the provide code of ObjectIndex doesn't work well
 docs\examples\objects\object_index.ipynb

### Version

0.9.13

### Steps to Reproduce

1. directly run the first set of code in your object_index.ipynb, the provide code doesn't work well

```
object_index = ObjectIndex(
    index=VectorStoreIndex(nodes=nodes), object_node_mapping=obj_node_mapping
)

```
Get error:  openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

2. Slightly change to add llm, it goes to another error:
```
llm = AzureOpenAI(
    model="gpt-35-turbo-16k", 
    deployment_name="qagpt-35-turbo-16k", 
    api_key=os.environ["OPENAI_API_KEY"],
    azure_endpoint=os.environ["OPENAI_API_BASE"],
    api_version=os.environ["OPENAI_API_VERSION"],
)
service_context = ServiceContext.from_defaults(
    llm=llm,
    embed_model=embedding_llm)

# some really arbitrary objects
obj1 = {"input": "Hey, how's it going"}
obj2 = ["a", "b", "c", "d"]
obj3 = "llamaindex is an awesome library!"
arbitrary_objects = [obj1, obj2, obj3]

# object-node mapping
obj_node_mapping = SimpleObjectNodeMapping.from_objects(arbitrary_objects)
nodes = obj_node_mapping.to_nodes(arbitrary_objects)

# object index
object_index = ObjectIndex(
    index=VectorStoreIndex(nodes=nodes, service_context=service_context), object_node_mapping=obj_node_mapping
)
```
It gets another error:
openai.BadRequestError: Error code: 400 - {'error': {'message': 'Too many inputs. The max number of inputs is 1.  We hope to increase the number of inputs per request soon. Please contact us through an Azure support request at: https://go.microsoft.com/fwlink/?linkid=2213926 for further questions.', 'type': 'invalid_request_error', 'param': None, 'code': None}}

**Comment by dgaoh** [comment]
Tried again after ensuring internet connection, 401 is the error code

In your sample code, it doesn't specify a llm/embed_llm, then it leds to 401 error.
but it still failed with error 400(Too many inputs),  while using VectorStoreIndex(nodes=nodes, service_context=service_context).
why it doesn't allow to configure with our own LLM?


```
object_index = ObjectIndex(
    index=VectorStoreIndex(nodes=nodes), object_node_mapping=obj_node_mapping
)
```

Error:
AuthenticationError: Error code: 401 - {'error': {'message': 'The OpenAI account associated with this API key has been deactivated. If you are the developer for this OpenAI app, please check your email for more information. If you are seeing this error while using another app or site, please reach out to them for more help.', 'type': 'invalid_request_error', 'param': None, 'code': 'account_deactivated'}}
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?79a6e8b7-605a-49b4-a35e-b0e1b58f9291) or open in a [text editor](command:workbench.action.openLargeOutput?79a6e8b7-605a-49b4-a35e-b0e1b58f9291). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by dgaoh** [comment]
found the cause that is due to OpenAI limits

**Comment by logan-markewich** [comment]
Yea this seems to be issues with either limits or account issues with openai. Going to close this issue for now
