### ISSUE TITLE
[Question]: How to use multi modal large model in local env base llama_index?

### ISSUE THREAD

**Issue by llf10811020205** [run-llama/llama_index#9483]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How to use multi modal large model in local env base llama_index?

**Comment by hatianzhang** [comment]
you can use llama cpp to run some local models using llama.cpp 
For llava: https://github.com/abetlen/llama-cpp-python/blob/8e44a32075de4aba2fc9877d4a2a34a0e7314c0d/README.md?plain=1#L248

feel free to make a pr to add llama.cpp for supporting Llava model.
You can follow https://github.com/run-llama/llama_index/blob/main/llama_index/llms/llama_cpp.py
