### ISSUE TITLE
Connection Timeout with Elastic Search

### ISSUE THREAD

**Issue by pranavbhat12** [run-llama/llama_index#9492]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hey,
I am trying to use Query Fusion retriever on top of hybrid retriever.I am getting connection timeout error because for now multiple sub queries are generated for a single query.On troubleshooting I found that request_timeout value should be increased.If this is correct how can we achieve this via Llamaindex? Tried adding vector_store_kwargs while creating retriever but no help.

**Code**:
def load_index_query_engine(llama_doc_list):
 hybrid_retriever_list=[]
for pdf_doc in doc_list:
index = load_index_from_storage(storage_context)
vector_retriever = index.as_retriever(
similarity_top_k=10,
vector_store_query_mode="hybrid",
**vector_store_kwargs={"request_timeout":30}**
)
nodes = service_context.node_parser.get_nodes_from_documents(llama_doc_list[pdf_doc])
bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=10)
hybrid_retriever = HybridRetriever(vector_retriever, bm25_retriever)
hybrid_retriever_list.append(hybrid_retriever)
return hybrid_retriever_list

retriever = QueryFusionRetriever(   
    hybrid_retriever_list,
    similarity_top_k=2,
    num_queries=2,  
    use_async=True,
    verbose=True,
    llm=llm
    # query_gen_prompt="...",  # we could override the query generation prompt here
)

query_engine = RetrieverQueryEngine.from_args(
    retriever=retriever,
    # node_postprocessors=[reranker],
     service_context=service_context,
    # streaming=True
)
with torch.no_grad() and torch.inference_mode():
    response = query_engine.query(question)
    print(response)

**Error**:
ConnectionError                           Traceback (most recent call last)
File <timed exec>:4

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_query_engine.py:30, in BaseQueryEngine.query(self, str_or_query_bundle)
     28 if isinstance(str_or_query_bundle, str):
     29     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> 30 return self._query(str_or_query_bundle)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py:170, in RetrieverQueryEngine._query(self, query_bundle)
    166 """Answer a query."""
    167 with self.callback_manager.event(
    168     CBEventType.QUERY, payload={EventPayload.QUERY_STR: query_bundle.query_str}
    169 ) as query_event:
--> 170     nodes = self.retrieve(query_bundle)
    171     response = self._response_synthesizer.synthesize(
    172         query=query_bundle,
    173         nodes=nodes,
    174     )
    176     query_event.on_end(payload={EventPayload.RESPONSE: response})

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/query_engine/retriever_query_engine.py:126, in RetrieverQueryEngine.retrieve(self, query_bundle)
    125 def retrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
--> 126     nodes = self._retriever.retrieve(query_bundle)
    127     return self._apply_node_postprocessors(nodes, query_bundle=query_bundle)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_retriever.py:54, in BaseRetriever.retrieve(self, str_or_query_bundle)
     49 with self.callback_manager.as_trace("query"):
     50     with self.callback_manager.event(
     51         CBEventType.RETRIEVE,
     52         payload={EventPayload.QUERY_STR: query_bundle.query_str},
     53     ) as retrieve_event:
---> 54         nodes = self._retrieve(query_bundle)
     55         retrieve_event.on_end(
     56             payload={EventPayload.NODES: nodes},
     57         )
     58 return nodes

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/retrievers/fusion_retriever.py:166, in QueryFusionRetriever._retrieve(self, query_bundle)
    163     queries = [query_bundle.query_str]
    165 if self.use_async:
--> 166     results = self._run_nested_async_queries(queries)
    167 else:
    168     results = self._run_sync_queries(queries)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/retrievers/fusion_retriever.py:124, in QueryFusionRetriever._run_nested_async_queries(self, queries)
    121         tasks.append(retriever.aretrieve(query))
    122         task_queries.append(query)
--> 124 task_results = run_async_tasks(tasks)
    126 results = {}
    127 for i, (query, query_result) in enumerate(zip(task_queries, task_results)):

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/async_utils.py:49, in run_async_tasks(tasks, show_progress, progress_bar_desc)
     46 async def _gather() -> List[Any]:
     47     return await asyncio.gather(*tasks_to_execute)
---> 49 outputs: List[Any] = asyncio.run(_gather())
     50 return outputs

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/nest_asyncio.py:31, in _patch_asyncio.<locals>.run(main, debug)
     29 task = asyncio.ensure_future(main)
     30 try:
---> 31     return loop.run_until_complete(task)
     32 finally:
     33     if not task.done():

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/nest_asyncio.py:99, in _patch_loop.<locals>.run_until_complete(self, future)
     96 if not f.done():
     97     raise RuntimeError(
     98         'Event loop stopped before Future completed.')
---> 99 return f.result()

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception.with_traceback(self._exception_tb)
    202 return self._result

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/tasks.py:234, in Task.__step(***failed resolving arguments***)
    232         result = coro.send(None)
    233     else:
--> 234         result = coro.throw(exc)
    235 except StopIteration as exc:
    236     if self._must_cancel:
    237         # Task is cancelled right before coro stops.

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/async_utils.py:47, in run_async_tasks.<locals>._gather()
     46 async def _gather() -> List[Any]:
---> 47     return await asyncio.gather(*tasks_to_execute)

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/tasks.py:304, in Task.__wakeup(self, future)
    302 def __wakeup(self, future):
    303     try:
--> 304         future.result()
    305     except BaseException as exc:
    306         # This may also be a cancellation.
    307         self.__step(exc)

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/tasks.py:232, in Task.__step(***failed resolving arguments***)
    228 try:
    229     if exc is None:
    230         # We use the `send` method directly, because coroutines
    231         # don't have `__iter__` and `__next__` methods.
--> 232         result = coro.send(None)
    233     else:
    234         result = coro.throw(exc)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_retriever.py:72, in BaseRetriever.aretrieve(self, str_or_query_bundle)
     67 with self.callback_manager.as_trace("query"):
     68     with self.callback_manager.event(
     69         CBEventType.RETRIEVE,
     70         payload={EventPayload.QUERY_STR: query_bundle.query_str},
     71     ) as retrieve_event:
---> 72         nodes = await self._aretrieve(query_bundle)
     73         retrieve_event.on_end(
     74             payload={EventPayload.NODES: nodes},
     75         )
     76 return nodes

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_retriever.py:94, in BaseRetriever._aretrieve(self, query_bundle)
     88 async def _aretrieve(self, query_bundle: QueryBundle) -> List[NodeWithScore]:
     89     """Asynchronously retrieve nodes given query.
     90 
     91     Implemented by the user.
     92 
     93     """
---> 94     return self._retrieve(query_bundle)

Cell In[19], line 17, in HybridRetriever._retrieve(self, query, **kwargs)
     15 def _retrieve(self, query, **kwargs):
     16     bm25_nodes = self.bm25_retriever.retrieve(query, **kwargs)
---> 17     vector_nodes = self.vector_retriever.retrieve(query, **kwargs)
     19     # combine the two lists of nodes
     20     all_nodes = []

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/core/base_retriever.py:54, in BaseRetriever.retrieve(self, str_or_query_bundle)
     49 with self.callback_manager.as_trace("query"):
     50     with self.callback_manager.event(
     51         CBEventType.RETRIEVE,
     52         payload={EventPayload.QUERY_STR: query_bundle.query_str},
     53     ) as retrieve_event:
---> 54         nodes = self._retrieve(query_bundle)
     55         retrieve_event.on_end(
     56             payload={EventPayload.NODES: nodes},
     57         )
     58 return nodes

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py:88, in VectorIndexRetriever._retrieve(self, query_bundle)
     82     if query_bundle.embedding is None and len(query_bundle.embedding_strs) > 0:
     83         query_bundle.embedding = (
     84             self._service_context.embed_model.get_agg_embedding_from_queries(
     85                 query_bundle.embedding_strs
     86             )
     87         )
---> 88 return self._get_nodes_with_embeddings(query_bundle)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/indices/vector_store/retrievers/retriever.py:164, in VectorIndexRetriever._get_nodes_with_embeddings(self, query_bundle_with_embeddings)
    160 def _get_nodes_with_embeddings(
    161     self, query_bundle_with_embeddings: QueryBundle
    162 ) -> List[NodeWithScore]:
    163     query = self._build_vector_store_query(query_bundle_with_embeddings)
--> 164     query_result = self._vector_store.query(query, **self._kwargs)
    165     return self._build_node_list_from_query_result(query_result)

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/vector_stores/elasticsearch.py:452, in ElasticsearchStore.query(self, query, custom_query, es_filter, **kwargs)
    424 def query(
    425     self,
    426     query: VectorStoreQuery,
   (...)
    431     **kwargs: Any,
    432 ) -> VectorStoreQueryResult:
    433     """Query index for top k most similar nodes.
    434 
    435     Args:
   (...)
    450 
    451     """
--> 452     return asyncio.get_event_loop().run_until_complete(
    453         self.aquery(query, custom_query, es_filter, **kwargs)
    454     )

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/nest_asyncio.py:99, in _patch_loop.<locals>.run_until_complete(self, future)
     96 if not f.done():
     97     raise RuntimeError(
     98         'Event loop stopped before Future completed.')
---> 99 return f.result()

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception.with_traceback(self._exception_tb)
    202 return self._result

File ~/anaconda3/envs/python3/lib/python3.10/asyncio/tasks.py:234, in Task.__step(***failed resolving arguments***)
    232         result = coro.send(None)
    233     else:
--> 234         result = coro.throw(exc)
    235 except StopIteration as exc:
    236     if self._must_cancel:
    237         # Task is cancelled right before coro stops.

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/llama_index/vector_stores/elasticsearch.py:524, in ElasticsearchStore.aquery(self, query, custom_query, es_filter, **kwargs)
    521     logger.debug(f"Calling custom_query, Query body now: {es_query}")
    523 async with self.client as client:
--> 524     response = await client.search(
    525         index=self.index_name,
    526         **es_query,
    527         size=query.similarity_top_k,
    528         _source={"excludes": [self.vector_field]},
    529     )
    531 top_k_nodes = []
    532 top_k_ids = []

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/elasticsearch/_async/client/__init__.py:3735, in AsyncElasticsearch.search(self, index, aggregations, aggs, allow_no_indices, allow_partial_search_results, analyze_wildcard, analyzer, batched_reduce_size, ccs_minimize_roundtrips, collapse, default_operator, df, docvalue_fields, error_trace, expand_wildcards, explain, ext, fields, filter_path, from_, highlight, human, ignore_throttled, ignore_unavailable, indices_boost, knn, lenient, max_concurrent_shard_requests, min_compatible_shard_node, min_score, pit, post_filter, pre_filter_shard_size, preference, pretty, profile, q, query, rank, request_cache, rescore, rest_total_hits_as_int, routing, runtime_mappings, script_fields, scroll, search_after, search_type, seq_no_primary_term, size, slice, sort, source, source_excludes, source_includes, stats, stored_fields, suggest, suggest_field, suggest_mode, suggest_size, suggest_text, terminate_after, timeout, track_scores, track_total_hits, typed_keys, version)
   3733 if __body is not None:
   3734     __headers["content-type"] = "application/json"
-> 3735 return await self.perform_request(  # type: ignore[return-value]
   3736     "POST", __path, params=__query, headers=__headers, body=__body
   3737 )

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py:285, in BaseClient.perform_request(self, method, path, params, headers, body)
    282 else:
    283     target = path
--> 285 meta, resp_body = await self.transport.perform_request(
    286     method,
    287     target,
    288     headers=request_headers,
    289     body=body,
    290     request_timeout=self._request_timeout,
    291     max_retries=self._max_retries,
    292     retry_on_status=self._retry_on_status,
    293     retry_on_timeout=self._retry_on_timeout,
    294     client_meta=self._client_meta,
    295 )
    297 # HEAD with a 404 is returned as a normal response
    298 # since this is used as an 'exists' functionality.
    299 if not (method == "HEAD" and meta.status == 404) and (
    300     not 200 <= meta.status < 299
    301     and (
   (...)
    305     )
    306 ):

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/elastic_transport/_async_transport.py:258, in AsyncTransport.perform_request(self, method, target, body, headers, max_retries, retry_on_status, retry_on_timeout, request_timeout, client_meta)
    256 start_time = self._loop.time()
    257 try:
--> 258     resp = await node.perform_request(
    259         method,
    260         target,
    261         body=request_body,
    262         headers=request_headers,
    263         request_timeout=request_timeout,
    264     )
    265     _logger.info(
    266         "%s %s%s [status:%s duration:%.3fs]"
    267         % (
   (...)
    273         )
    274     )
    276     if method != "HEAD":

File ~/anaconda3/envs/python3/lib/python3.10/site-packages/elastic_transport/_node/_http_aiohttp.py:218, in AiohttpHttpNode.perform_request(self, method, target, body, headers, request_timeout)
    210         err = ConnectionError(str(e), errors=(e,))
    211     self._log_request(
    212         method="HEAD" if is_head else method,
    213         target=target,
   (...)
    216         exception=err,
    217     )
--> 218     raise err from None
    220 meta = ApiResponseMeta(
    221     node=self.config,
    222     duration=duration,
   (...)
    225     headers=HttpHeaders(response.headers),
    226 )
    227 self._log_request(
    228     method="HEAD" if is_head else method,
    229     target=target,
   (...)
    233     response=raw_data,
    234 )
ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ClientOSError([Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2702)))

**Comment by huangjiaheng** [comment]
chmod -R 777 folder_path
-v host_path:container_path:rw

**Comment by jcarletgo** [comment]
It doesnt look like keywords are passed to elasticsearch when querying https://github.com/run-llama/llama_index/blob/8ed753df970f068f6afc8a83fd51a1f40880de9e/llama-index-integrations/vector_stores/llama-index-vector-stores-elasticsearch/llama_index/vector_stores/elasticsearch/base.py#L534C30-L534C36 

A work around is to define the timeout when creating the vectorstore by passing an AsyncElasticsearch client
```
from elasticsearch import 
from llama_index.vector_stores.elasticsearch import ElasticsearchStore

es_client = AsyncElasticsearch(url, basic_auth=(), request_timeout=10)
vector_store = ElasticsearchStore(
    es_client = es_client, 
    index_name="<>",
)
```
See https://elasticsearch-py.readthedocs.io/en/v8.12.1/async.html#asyncelasticsearch
