### ISSUE TITLE
[Bug]: RedisVectorStore delete_ref_doc doesn't delete all nodes

### ISSUE THREAD

**Issue by josheschulz** [run-llama/llama_index#9509]
### Bug Description

`index.delete_ref_doc(ref_doc_id=doc_id)`

Won't delete all of the nodes of a document if there are more than 10.

Because [the code in delete](https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/redis.py#L199) does a search for nodes then deletes what it finds node by node.  However the query default is to limit to 10 items returned.  Documents created using SentenceSplitter often have more than 10 nodes.

I believe setting setting the limit explicitly in query_params passed to the search in that code, and putting that code in a loop that repeats until the number of nodes returned < limit would do it, but I don't know a lot about redis so there is probably a better way.

### Version

0.9.13

### Steps to Reproduce

1.  Index a doc with more than 10 nodes.
2. Delete the doc using index.delete_ref_doc(doc_id)
3. Verify nodes are still in the redis data store from that document.

**Comment by sunhs** [comment]
In `RedisVectorStore.delete`, maybe we should create a `redis.commands.search.query.Query` object, and modify its attributes (for example, `Query._num`) using values from the `delete_kwargs` parameter, and pass this `Query` object to `self._redis_client.ft(self._index_name).search`.

In this way, we can directly control the query behavior from the `delete_kwargs` parameter in `index.delete_ref_doc`.

However, I'm not sure what number should be set to `Query._num`.
