### ISSUE TITLE
[Question]: SQLAutoVectorQueryEngine ValueError: Invalid result.ind: -2

### ISSUE THREAD

**Issue by redswimmer** [run-llama/llama_index#9510]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

For some SQLAutoVectorQueryEngine queries I get the following error when calling `query_engine.query()`.  For example "Tell me about the author".  I'm using service_context to select gpt-4.  I've noticed if don't specify the service_context the error seems to go away.

`chunk_size = 1024`
`llm = OpenAI(temperature=1, model="gpt-4", streaming=True)`
`service_context = ServiceContext.from_defaults(chunk_size=chunk_size, llm=llm)`

`query_engine = SQLAutoVectorQueryEngine(`
`    sql_tool, vector_tool, service_context=service_context`
`)`

**ERROR BELOW**
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[101], [line 1](vscode-notebook-cell:?execution_count=101&line=1)
----> [1](vscode-notebook-cell:?execution_count=101&line=1) response = query_engine.query(
      [2](vscode-notebook-cell:?execution_count=101&line=2)     "Tell me about the author."
      [3](vscode-notebook-cell:?execution_count=101&line=3) )

File [c:\Python312\Lib\site-packages\llama_index\core\base_query_engine.py:30](file:///C:/Python312/Lib/site-packages/llama_index/core/base_query_engine.py:30), in BaseQueryEngine.query(self, str_or_query_bundle)
     [28](file:///C:/Python312/Lib/site-packages/llama_index/core/base_query_engine.py:28) if isinstance(str_or_query_bundle, str):
     [29](file:///C:/Python312/Lib/site-packages/llama_index/core/base_query_engine.py:29)     str_or_query_bundle = QueryBundle(str_or_query_bundle)
---> [30](file:///C:/Python312/Lib/site-packages/llama_index/core/base_query_engine.py:30) return self._query(str_or_query_bundle)

File [c:\Python312\Lib\site-packages\llama_index\query_engine\sql_join_query_engine.py:328](file:///C:/Python312/Lib/site-packages/llama_index/query_engine/sql_join_query_engine.py:328), in SQLJoinQueryEngine._query(self, query_bundle)
    [326](file:///C:/Python312/Lib/site-packages/llama_index/query_engine/sql_join_query_engine.py:326)     return response
    [327](file:///C:/Python312/Lib/site-packages/llama_index/query_engine/sql_join_query_engine.py:327) else:
--> [328](file:///C:/Python312/Lib/site-packages/llama_index/query_engine/sql_join_query_engine.py:328)     raise ValueError(f"Invalid result.ind: {result.ind}")

ValueError: Invalid result.ind: -2

**DEBUG CAPTURE BELOW**

DEBUG:openai._base_client:Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': <MessageRole.USER: 'user'>, 'content': "Some choices are given below. It is provided in a numbered list (1 to 2), where each item in the list corresponds to a summary.\n---------------------\n(1) Useful for translating a natural language query into a SQL query over a table containing the schedule of surgical procedures.\n\n(2) Useful for answering semantic questions about how to perform common surgical procedures.\n---------------------\nUsing only the choices above and not prior knowledge, generate the selection object and reason that is most relevant to the question: 'Tell me about the author.'\n"}], 'model': 'gpt-4', 'stream': False, 'temperature': 0.9, 'tool_choice': {'type': 'function', 'function': {'name': 'SingleSelection'}}, 'tools': [{'type': 'function', 'function': {'name': 'SingleSelection', 'description': 'A single selection of a choice.', 'parameters': {'title': 'SingleSelection', 'description': 'A single selection of a choice.', 'type': 'object', 'properties': {'index': {'title': 'Index', 'type': 'integer'}, 'reason': {'title': 'Reason', 'type': 'string'}}, 'required': ['index', 'reason']}}}]}}
Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': <MessageRole.USER: 'user'>, 'content': "Some choices are given below. It is provided in a numbered list (1 to 2), where each item in the list corresponds to a summary.\n---------------------\n(1) Useful for translating a natural language query into a SQL query over a table containing the schedule of surgical procedures.\n\n(2) Useful for answering semantic questions about how to perform common surgical procedures.\n---------------------\nUsing only the choices above and not prior knowledge, generate the selection object and reason that is most relevant to the question: 'Tell me about the author.'\n"}], 'model': 'gpt-4', 'stream': False, 'temperature': 0.9, 'tool_choice': {'type': 'function', 'function': {'name': 'SingleSelection'}}, 'tools': [{'type': 'function', 'function': {'name': 'SingleSelection', 'description': 'A single selection of a choice.', 'parameters': {'title': 'SingleSelection', 'description': 'A single selection of a choice.', 'type': 'object', 'properties': {'index': {'title': 'Index', 'type': 'integer'}, 'reason': {'title': 'Reason', 'type': 'string'}}, 'required': ['index', 'reason']}}}]}}
DEBUG:httpcore.connection:close.started
close.started
DEBUG:httpcore.connection:close.complete
close.complete
DEBUG:httpcore.connection:connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=60.0 socket_options=None
connect_tcp.started host='api.openai.com' port=443 local_address=None timeout=60.0 socket_options=None
DEBUG:httpcore.connection:connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000027891E40530>
connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000027891E40530>
DEBUG:httpcore.connection:start_tls.started ssl_context=<ssl.SSLContext object at 0x0000027891ED6ED0> server_hostname='api.openai.com' timeout=60.0
start_tls.started ssl_context=<ssl.SSLContext object at 0x0000027891ED6ED0> server_hostname='api.openai.com' timeout=60.0
DEBUG:httpcore.connection:start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000027893B7F440>
start_tls.complete return_value=<httpcore._backends.sync.SyncStream object at 0x0000027893B7F440>
DEBUG:httpcore.http11:send_request_headers.started request=<Request [b'POST']>
send_request_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_headers.complete
send_request_headers.complete
DEBUG:httpcore.http11:send_request_body.started request=<Request [b'POST']>
send_request_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:send_request_body.complete
send_request_body.complete
DEBUG:httpcore.http11:receive_response_headers.started request=<Request [b'POST']>
receive_response_headers.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Thu, 14 Dec 2023 00:23:24 GMT'), (b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'access-control-allow-origin', b'*'), (b'Cache-Control', b'no-cache, must-revalidate'), (b'openai-model', b'gpt-4-0613'), (b'openai-organization', b'user-vnoy76paarbktt519cuphchn'), (b'openai-processing-ms', b'1136'), (b'openai-version', b'2020-10-01'), (b'strict-transport-security', b'max-age=15724800; includeSubDomains'), (b'x-ratelimit-limit-requests', b'10000'), (b'x-ratelimit-limit-tokens', b'10000'), (b'x-ratelimit-limit-tokens_usage_based', b'10000'), (b'x-ratelimit-remaining-requests', b'9999'), (b'x-ratelimit-remaining-tokens', b'9843'), (b'x-ratelimit-remaining-tokens_usage_based', b'9843'), (b'x-ratelimit-reset-requests', b'8.64s'), (b'x-ratelimit-reset-tokens', b'942ms'), (b'x-ratelimit-reset-tokens_usage_based', b'942ms'), (b'x-request-id', b'b22b369ab64ca295b0930a9fea8edc2a'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Server', b'cloudflare'), (b'CF-RAY', b'83524c456f723508-SMF'), (b'Content-Encoding', b'gzip'), (b'alt-svc', b'h3=":443"; ma=86400')])
receive_response_headers.complete return_value=(b'HTTP/1.1', 200, b'OK', [(b'Date', b'Thu, 14 Dec 2023 00:23:24 GMT'), (b'Content-Type', b'application/json'), (b'Transfer-Encoding', b'chunked'), (b'Connection', b'keep-alive'), (b'access-control-allow-origin', b'*'), (b'Cache-Control', b'no-cache, must-revalidate'), (b'openai-model', b'gpt-4-0613'), (b'openai-organization', b'user-vnoy76paarbktt519cuphchn'), (b'openai-processing-ms', b'1136'), (b'openai-version', b'2020-10-01'), (b'strict-transport-security', b'max-age=15724800; includeSubDomains'), (b'x-ratelimit-limit-requests', b'10000'), (b'x-ratelimit-limit-tokens', b'10000'), (b'x-ratelimit-limit-tokens_usage_based', b'10000'), (b'x-ratelimit-remaining-requests', b'9999'), (b'x-ratelimit-remaining-tokens', b'9843'), (b'x-ratelimit-remaining-tokens_usage_based', b'9843'), (b'x-ratelimit-reset-requests', b'8.64s'), (b'x-ratelimit-reset-tokens', b'942ms'), (b'x-ratelimit-reset-tokens_usage_based', b'942ms'), (b'x-request-id', b'b22b369ab64ca295b0930a9fea8edc2a'), (b'CF-Cache-Status', b'DYNAMIC'), (b'Server', b'cloudflare'), (b'CF-RAY', b'83524c456f723508-SMF'), (b'Content-Encoding', b'gzip'), (b'alt-svc', b'h3=":443"; ma=86400')])
INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
DEBUG:httpcore.http11:receive_response_body.started request=<Request [b'POST']>
receive_response_body.started request=<Request [b'POST']>
DEBUG:httpcore.http11:receive_response_body.complete
receive_response_body.complete
DEBUG:httpcore.http11:response_closed.started
response_closed.started
DEBUG:httpcore.http11:response_closed.complete
response_closed.complete
DEBUG:openai._base_client:HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"
HTTP Request: POST https://api.openai.com/v1/chat/completions "200 OK"

**Comment by redswimmer** [comment]
@dosu-bot The question is provided by the user so I'm not sure how I would adjust the query since it's automatically generated.  Also, the vector data does contact information about the author so the query is relevant.

**Comment by sabir012** [comment]
Thank you @redswimmer  for raising this issue. I am also getting this error and no clear reason behind it. Would be great to hear explanation from contributors.

**Comment by Wishmitha** [comment]
Facing the same issue. Is there any reason why the error disappeared by re-running the same code again? It is not even query-specific it seems.
