### ISSUE TITLE
[Bug]: Metadata Filter won't work properly on HNSW PgVectorStore due to PgVector limitation

### ISSUE THREAD

**Issue by rendyfebry** [run-llama/llama_index#9519]
### Bug Description

There is an open issue on PgVector Repo which causes indexed embedding (HNSW) won't work properly when combined with a filter.
* https://github.com/pgvector/pgvector/issues/259
 
The query in question is similar to the one used by the PgVectorStore retriever.
```
SELECT id, text
FROM document
WHERE category = $1
ORDER BY embedding <-> $2
LIMIT 10;
```

PS: This problem only occurs when you index your PgVector table (with HNSW). The standard table or IFFlat indexed table won't face this issue, but you will hit a performance issue once you have a lot of data.

### Version

latest

### Steps to Reproduce

Query your PgVectorStore with and without metadata filtering, and you will notice something weird happening.

**Comment by GillesJ** [comment]
Just got burned by this in production. The HSNW index is not used with metadata filters.
