### ISSUE TITLE
[Question]: How hit rate and MRR are calculated in Retrieval Evaluation?

### ISSUE THREAD

**Issue by terilias** [run-llama/llama_index#9527]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hello,
I recently started to study the evaluation methods that LlamaIndex offers.
I read the following articles and resources:

- https://docs.llamaindex.ai/en/stable/module_guides/evaluating/root.html
- https://cookbook.openai.com/examples/evaluation/evaluate_rag_with_llamaindex
- https://blog.llamaindex.ai/evaluating-the-ideal-chunk-size-for-a-rag-system-using-llamaindex-6207e5d3fec5

 Thanks for publishing this work!
I have some questions regarding the hit rate and the MRR calculations. I know that we call the function on a dataset that has been generated with generate_question_context_pairs(). We expect to create some questions for each node.

1. I understand that we have a hit, if at least one of the retrieved nodes are relevant with the query.  What does this means? 
 Does it mean that at least one of the retrieved nodes must be the node for which the specific question has been generated?
2. How to change the embeddings model in the RetrieverEvaluator? I want it to use the same embedding model that I used for the indexing (hugging face embeddings). I tried to specify the embed_model but is uses the OpenAI embeddings. 
3. Does the MRR calculation use similarity calculation? Does it check if at the first rank we have the node for which the specific question has been generated?

**Comment by ravi03071991** [comment]
Hi @terilias,

1. Yes. 
2. It can be plugged-in while creating a retriever. Something in the following way.

```
embed_model = HuggingFaceEmbedding(model_name="HF MODEL NAME")
service_context=ServiceContext.from_defaults(embed_model=embed_model)
index = VectorStoreIndex.from_documents(documents, service_context=service_context)
retriever = index.as_retriever()
retriever_evaluator = RetrieverEvaluator.from_metric_names(
    ["mrr", "hit_rate"], retriever=retriever
)
eval_results = await retriever_evaluator.aevaluate_dataset(qa_dataset)
```
3. MRR calculation does not use similarity, it checks for rank of the retrieved node. You can check the code [here](https://github.com/run-llama/llama_index/blob/e7090975a1807b6c30c132c65464cb51dba3804a/llama_index/evaluation/retrieval/metrics.py#L45) to get more understanding.

Thank you.

**Comment by terilias** [comment]
Thank you @ravi03071991 for your answer! Now I can understand how it works.
