### ISSUE TITLE
[Bug]: The Gemini model streaming interface doesn't work as expected. 

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#9549]
### Bug Description

When using the new gemini llm interface with a query_engine or a chat_engine, the response is always None if it is streamed.

For the query engine, a none is returned on all queries. for the chat engine, an parsing error is thrown: 

### Version

0.9.15.post2

### Steps to Reproduce

Just run a query engine or a chat engine with gemini as the llm and llm = Gemini() 
service_context = ServiceContext.from_defaults(llm=llm) and ensure that the engine is set to stream.

### Relevant Logs/Tracbacks

```shell
##Query engine response for gemini with openai_embedding as the embed_model:

INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"


INFO:httpx:HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"
HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 200 OK"


Time taken: 14.811168895015726 seconds


None response is printed on the terminal.



##Chat engine:
/lib/python3.10/site-packages/llama_index/chat_engine/types.py", line 157, in response_gen
    self._unformatted_response += delta
TypeError: can only concatenate str (not "NoneType") to str
```

**Comment by hatianzhang** [comment]
cc @logan-markewich on it. 
I noticed a similar issue. now trying to check with Gemini side.

**Comment by hatianzhang** [comment]
Some query can give error
![image](https://github.com/run-llama/llama_index/assets/2142132/0ee33118-ebc5-4118-84e6-b83cbea27725)
Some query can give good results:
![image](https://github.com/run-llama/llama_index/assets/2142132/4938be36-b1aa-4676-b8df-c1003ef65d9e)

@markmcd do you know how to resolve  this issue?

**Comment by gich2009** [comment]
@hatianzhang, from my experiments, a dumped chat with Gemini works pretty reliably. I haven't encountered any case where the model has had an issue giving a reasonable response. But on streaming, the model just returns Nones.

The .query() and the .chat() methods may be of a lower priority than the .stream_chat() and the .query(streaming=True) methods since those don't work at all.

**Comment by hatianzhang** [comment]
@gich2009 stream_chat and stream_complete works me from the this example https://github.com/run-llama/llama_index/blob/main/docs/examples/llm/gemini.ipynb

![image](https://github.com/run-llama/llama_index/assets/2142132/bee343b6-7a6e-43c6-9cc3-b35d67193440)

Could you provide me some example where stream_chat does not work

**Comment by hatianzhang** [comment]
btw Gemini should have some rate limit. Is it bc rate limiting or do you have any error log?

**Comment by gich2009** [comment]
Hi @hatianzhang I think its because I'm using response.response_gen method. Is that no longer supported?

**Comment by gich2009** [comment]
![image](https://github.com/run-llama/llama_index/assets/83756959/c75cf929-ceb3-4376-9a3a-4500afd052c5)
Here is the log @hatianzhang

**Comment by gich2009** [comment]
Just upgraded to 0.9.16.post2 and gemini still doesn't work with response.response_gen.

**Comment by hatianzhang** [comment]
thanks @gich2009 that is potentially the reason. could you first do this way 
```for chunk in resp:
    print(chunk.message.content, end="")
```
we will figure out why response.response_gen not working for gemini

**Comment by gich2009** [comment]
Thank you @hatianzhang. I will tentatively do that as I wait for the fix.

**Comment by hatianzhang** [comment]
@gich2009 could you help check the issue has been fixed?

**Comment by gich2009** [comment]
On it @hatianzhang. Will respond shortly

**Comment by gich2009** [comment]
Hi @hatianzhang, I tested the fix on v0.9.17. It's not broken anymore. The streaming behaviour is a bit different from other models. The chunks are much longer than usual but other than that it works very well. Thanks for the fix. I'll keep an eye on it.

**Comment by gich2009** [comment]
Hi @hatianzhang. After running a couple of test rounds, I have noticed an issue. I am on v0.9.19 Please check the chat engine behavior for a **non-streaming/dumped response** for a gemini service context. The behavior is inconsistent and on certain occasions, the following exception is raised: 
![image](https://github.com/run-llama/llama_index/assets/83756959/cc19cb69-53cf-48d8-b9c0-270521034ec0)

Please note that this issue doesn't happen all the time. It occurs after a few test cycles and works well in the rest of the cases.

On the other hand, the streaming behavior is consistent and stable so far

**Comment by gich2009** [comment]
@logan-markewich, would you prefer to tentatively reopen the issue or should I create a new issue and refer to #9549

**Comment by hatianzhang** [comment]
@gich2009 I think this issue need to be addressed/understood from Gemini side. I encountered it before and we need to know why Gemini stop generate results. could be due to different reasons. at this point, I don't llamaindex side can do anything

**Comment by gich2009** [comment]
Hi @hatianzhang. Understood. The behaviour is as consistent as we can get it for now. Thanks again!

I'll keep testing the other LLM integrations to see how well their response_gen properties work.
