### ISSUE TITLE
[Bug]: cannot select model other than openai models in openai llm integration

### ISSUE THREAD

**Issue by yyefet** [run-llama/llama_index#9553]
### Bug Description

Many tools utilize OpenAI API specs to wrap local LLM such as vLLM.
When launching vLLM local model an OpenAI API server can be served along with it.

llama_index does not allow a user to configure OpenAI LLM using custom model (a model that is not native to OpenAI).

Error when setting non-openai model:
    resp = OpenAI(model="mistralai/Mixtral-8x7B-Instruct-v0.1").complete("Paul Graham is ")
<...redacted...>
    raise ValueError(
ValueError: Unknown model 'mistralai/Mixtral-8x7B-Instruct-v0.1'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo

Assuming these models hardcoded in the codebase somewhere.

Functionality should allow for any connection to OpenAI API specification regardless of model under the hood.

### Version

0.9.15.post2

### Steps to Reproduce

from llama_index.llms import OpenAI
resp = OpenAI(model="mistralai/Mixtral-8x7B-Instruct-v0.1").complete("Paul Graham is ")

### Relevant Logs/Tracbacks

```shell
ValueError: Unknown model 'mistralai/Mixtral-8x7B-Instruct-v0.1'. Please provide a valid OpenAI model name in: gpt-4, gpt-4-32k, gpt-4-1106-preview, gpt-4-vision-preview, gpt-4-0613, gpt-4-32k-0613, gpt-4-0314, gpt-4-32k-0314, gpt-3.5-turbo, gpt-3.5-turbo-16k, gpt-3.5-turbo-1106, gpt-3.5-turbo-0613, gpt-3.5-turbo-16k-0613, gpt-3.5-turbo-0301, text-davinci-003, text-davinci-002, gpt-3.5-turbo-instruct, text-ada-001, text-babbage-001, text-curie-001, ada, babbage, curie, davinci, gpt-35-turbo-16k, gpt-35-turbo
```

**Comment by logan-markewich** [comment]
Use OpenAILike  llm. Been meaning to add docs to this lol

https://github.com/run-llama/llama_index/blob/820ca6769e46e566c202d6666650930cfbc376cb/llama_index/llms/openai_like.py#L9

Example
I made a very quick example here (I also wanted to test out qwen-1.8B)
 
 https://colab.research.google.com/drive/1h-eHhoKUnkJQ2TTsw4HxOd0f1zVd97Ol?usp=sharing
 
But I couldn't find the proper prompt format for qwen 😅

**Comment by yyefet** [comment]
Found what i need with "OpenAILike" llm

from llama_index.llms import OpenAILike

Worked for me. can close this out
