### ISSUE TITLE
[Bug]: APIConnectionError: Connection error. due to the following error: LocalProtocolError: Illegal header value b'Bearer '

### ISSUE THREAD

**Issue by pgaods** [run-llama/llama_index#9566]
### Bug Description

Hi, I am trying to replicate the results using the BM25 hybrid retriever to perform RAG. I have 4 URls I want to store as texts, and then perform QA on those documents to retrieve the relevan information. The guide I am following is listed here:

   - https://docs.llamaindex.ai/en/stable/examples/retrievers/bm25_retriever.html#bm25-retriever.

In the last step, I am seeing an error APIConnectionError: Connection error. This is not the due to the openai API key or something. The failure happened on the last step of the script.

### Version

0.9.15.post2

### Steps to Reproduce

import numpy as np
import pandas as pd
import json, os, time, requests
import nest_asyncio
import openai, tiktoken

from pprint import pprint
from bs4 import BeautifulSoup as Soup
from pathlib import Path
from IPython.display import Markdown, display

from llama_index.embeddings import AzureOpenAIEmbedding
from llama_index.indices.base_retriever import BaseRetriever
from llama_index.indices.query.schema import QueryBundle
from llama_index.indices.service_context import ServiceContext
from llama_index.indices.vector_store.base import VectorStoreIndex
from llama_index.llms.azure_openai import AzureOpenAI
from llama_index.postprocessor import LLMRerank, SentenceTransformerRerank
from llama_index.query_engine.retriever_query_engine import RetrieverQueryEngine
from llama_index.readers import SimpleWebPageReader, SimpleDirectoryReader
from llama_index.response_synthesizers import get_response_synthesizer
from llama_index.retrievers import BM25Retriever, QueryFusionRetriever
from llama_index.schema import Document
from llama_index.storage.storage_context import StorageContext

nest_asyncio.apply()

# omitting all the parameters for AzureOpenAI for privacy

llm= AzureOpenAI(model="gpt-4", engine=azure_deployment, temperature=0)

embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name=azure_embedding_deployment,
    api_key=azure_openai_key,
    azure_endpoint=azure_openai_endpoint,
    api_version=azure_api_version
)
url_list=['https://www.abcam.com/products/primary-antibodies/red-blood-cells-antibody-ab34858.html', 'https://www.abcam.com/en-nl/products/primary-antibodies/red-blood-cells-antibody-ab34858', 'https://www.abcam.com/help/data-and-documents', 'https://www.biocompare.com/9776-Antibodies/326617-Red-Blood-Cells-antibody/']

manufacturer = 'Abcam' 
product_number = 'ab34858'

medical = 1 # if 1 then it's querying a medical supply, otherwise it's a general question.
general_query = "Who won the FIFA soccer world cup in 2022?"

if medical == 1:
    my_prompt = f"Below contains the information scraped from a webpage. Please answer the following question truthly based on the information provided below: given the product number='{product_number}' from the manufacturer '{manufacturer}', what's the medical product description?".format()
else:
    my_prompt =  "Please answer the following question truthly based on the web page information provided:\n"  + query
print(my_prompt)

if medical == 1:
    query = f"{manufacturer} product, product number={product_number}".format()
else:
    query = general_query
print(query)

docs = SimpleWebPageReader(html_to_text=True).load_data(url_list)

service_context = ServiceContext.from_defaults(chunk_size=256, llm=llm, embed_model=embed_model)
nodes = service_context.node_parser.get_nodes_from_documents(docs)
storage_context = StorageContext.from_defaults() # initializing storage context (by default it's in-memory)
storage_context.docstore.add_documents(nodes)
index = VectorStoreIndex(nodes, storage_context=storage_context, service_context=service_context)

vector_retriever = index.as_retriever(similarity_top_k=2)
bm25_retriever = BM25Retriever.from_defaults(nodes=nodes, similarity_top_k=2)

class HybridRetriever(BaseRetriever):
    def __init__(self, vector_retriever, bm25_retriever):
        self.vector_retriever = vector_retriever
        self.bm25_retriever = bm25_retriever
        super().__init__()

    def _retrieve(self, query, **kwargs):
        bm25_nodes = self.bm25_retriever.retrieve(query, **kwargs)
        vector_nodes = self.vector_retriever.retrieve(query, **kwargs)

        # combine the two lists of nodes
        all_nodes = []
        node_ids = set()
        for n in bm25_nodes + vector_nodes:
            if n.node.node_id not in node_ids:
                all_nodes.append(n)
                node_ids.add(n.node.node_id)
        return all_nodes
    
index.as_retriever(similarity_top_k=2)
hybrid_retriever = HybridRetriever(vector_retriever, bm25_retriever)

reranker = SentenceTransformerRerank(top_n=2, model="BAAI/bge-reranker-base")

nodes = hybrid_retriever.retrieve(my_prompt)
reranked_nodes = reranker.postprocess_nodes(nodes, query_bundle=QueryBundle(my_prompt))
print("Initial retrieval: ", len(nodes), " nodes")
print("Re-ranked retrieval: ", len(reranked_nodes), " nodes")

response_synthesizer = get_response_synthesizer(response_mode="compact", service_context=service_context)
query_engine = RetrieverQueryEngine.from_args(retriever=hybrid_retriever, node_postprocessors=[reranker], service_context=service_context, response_synthesizer=response_synthesizer)
response = query_engine.query(my_prompt)

**Comment by pgaods** [comment]
<img width="960" alt="Capture" src="https://github.com/run-llama/llama_index/assets/89472913/217a3147-0cf5-410e-9f7c-443a36288b51">

This is the issue I am seeing

**Comment by logan-markewich** [comment]
I noticed you didn't pass the api key to the LLM -- is it set in the env?

**Comment by pgaods** [comment]
hi @logan-markewich it is set in the env. The LLM part works if I just use a simple query-engine. Here is the snapshot:

# Embedding Params
azure_openai_key="blah"
azure_openai_endpoint="https://something.openai.azure.com/" # used for embedding
azure_embedding_deployment="text-embedding-ada-002"
os.environ["AZURE_OPENAI_API_KEY"] = azure_openai_key # used for embedding
os.environ["AZURE_OPENAI_ENDPOINT"] = azure_openai_endpoint # used for embedding
os.environ['OPENAI_API_VERSION'] = "2023-07-01-preview"


# ChatCompletion Params
azure_api_version="2023-07-01-preview"
azure_api_key_chat="blahblah"
azure_chat_endpoint="https://blah-temp-datascience-ncus-001-openai.openai.azure.com//"
azure_deployment="gpt-4"

**Comment by logan-markewich** [comment]
Maybe set a global service context, there might be some step I'm missing where it's not being passed in ?

```
from llama_index import set_global_service_context 
set_global_service_context(service_context)
```

**Comment by younes-io** [comment]
oh and make sure you remove trailing slashes at the end of your base URL in your `.env` file

**Comment by pgaods** [comment]
even if i remove the trailing dash, it's still not working, here is the detail of the log:

![image](https://github.com/run-llama/llama_index/assets/89472913/a7d7eb70-1e2b-4ce7-8b9a-0ed71607f134)

azure_embedding_api_version="2023-07-01-preview"
azure_embedding_api_key="blahblah" # used for embedding
azure_embedding_endpoint="https://blah-chatgpt.openai.azure.com/" # used for embedding
azure_embedding_deployment="text-embedding-ada-002"

azure_chat_api_version="2023-07-01-preview"
azure_chat_api_key="xxyyz"
azure_chat_endpoint="https://blah-temp-datascience-ncus-001-openai.openai.azure.com/"
azure_chat_deployment="gpt-4"

from llama_index.embeddings import AzureOpenAIEmbedding
from llama_index.llms.azure_openai import AzureOpenAI

llm= AzureOpenAI(model="gpt-4", engine=azure_chat_deployment, temperature=0)

embed_model = AzureOpenAIEmbedding(
    model="text-embedding-ada-002",
    deployment_name=azure_embedding_deployment,
    api_key=azure_embedding_api_key,
    azure_endpoint=azure_embedding_endpoint,
    api_version=azure_embedding_api_version
)

**Comment by pgaods** [comment]
@younes-io thank you, but i did tried the following and still doesn't work, is this what you meant?

#azure_chat_endpoint="https://blah-temp-datascience-ncus-001-openai.openai.azure.com/"
azure_chat_endpoint="https://blah-temp-datascience-ncus-001-openai.azure.com/"

**Comment by pgaods** [comment]
@logan-markewich  thank you for your suggestion. I tried that it didn't work either. It can also be related to databricks or my python version:

![image](https://github.com/run-llama/llama_index/assets/89472913/c2accff4-7066-4ea7-a017-a783d999ded9)

**Comment by pgaods** [comment]
I see the problem @younes-io @logan-markewich . It is related to my llm setting where there is a missing argument which caused this. This page has the right amount of arguments:

https://docs.llamaindex.ai/en/stable/examples/customization/llms/AzureOpenAI.html

Thank you all, really appreciate it!

**Comment by pgaods** [comment]
closing this.
