### ISSUE TITLE
Llama index does not support other OpenAI standard llms

### ISSUE THREAD

**Issue by silverdevelopper** [run-llama/llama_index#9568]
### Feature Description

Currently  OpenAI client objects is creating in **OpenAI LLM** with default settings and it is compatible with only Open AI models such as gpt-3.   However it does not support llm which has Open AI api standard. While we are able to do this with OpenAI client we should be able to do it with OpenAI LLM object
<img width="1081" alt="Screenshot 2023-12-17 at 10 59 16" src="https://github.com/run-llama/llama_index/assets/44099705/70548331-3b44-4a29-a878-3cd41d53c48b">

### Reason

There is no support

### Value of Feature

This features would provides interface all OpenAI standardised  APIs .

**Comment by logan-markewich** [comment]
See here
https://github.com/run-llama/llama_index/issues/9553#issuecomment-1858567809

**Comment by silverdevelopper** [comment]
Thanks worked for me
