### ISSUE TITLE
[Feature Request]: Text Embeddings Inference Reranker

### ISSUE THREAD

**Issue by brucethemoose** [run-llama/llama_index#9572]
### Feature Description

Hello, could we get a reranking class in the vein of `SentenceTransformerRerank` or `CohereRerank` for a Text Embeddings Inference server? 

### Reason

We are running into performance/scaling issues with the SentenceTransformerRerank class, even with hacks like BF16 precision and BetterTransformers applied. The Huggingface TEI server should yield much higher performance and can serve many reranking calls at once. 

### Value of Feature

This would allow call out reranking to a self hosted API, just like the TEI embeddings class.

**Comment by brucethemoose** [comment]
Yeah I just wrote my own class. Good bot.

**Comment by terilias** [comment]
I encounter the same issue. I think that a TEI implementation for the reranker models will be useful.  So maybe it's better to reopen the issue...

**Comment by Bearsaerker** [comment]
I'd love to see this as well!

**Comment by terilias** [comment]
@dosubot @brucethemoose Hello, as of my understanding there still no exist such a class in the newer version of LlamaIndex. We can see here in the [postproseccing](https://docs.llamaindex.ai/en/stable/module_guides/querying/node_postprocessors/node_postprocessors/) modules. Right?

**Comment by logan-markewich** [comment]
This has been added quite a while ago

`pip install llama-index-postprocessor-tei-rerank`

```
from llama_index.postprocessor.tei_rerank import TextEmbeddingInference as TEIR

reranker = TEIR(...)
```

https://docs.llamaindex.ai/en/stable/api_reference/postprocessor/tei_rerank/
