### ISSUE TITLE
[Question]: no validator found for <class 'llama_index.agent.types.Task'> when initialising query engine

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#9592]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

IWhen executing

query_engine = index.as_query_engine(service_context=service_context)

I am getting error:
no validator found for <class 'llama_index.agent.types.Task'>, see `arbitrary_types_allowed` in Config

how can I fix this issue? could it be pydantic version issue?

**Comment by jerryjliu** [comment]
sorry about this, fixing soon
