### ISSUE TITLE
[Bug]: Document has no attribute image_path 

### ISSUE THREAD

**Issue by XariZaru** [run-llama/llama_index#9600]
### Bug Description

Hi, just trying to use the new PDF table extract capabilities. I was following the code snippets and came across this issue when loading documents to be loaded as images.

`python
from llama_index.multi_modal_llms.openai import OpenAIMultiModal
from llama_index import SimpleDirectoryReader

# put your local directore here
documents_images_v2 = SimpleDirectoryReader("./llama2/").load_data()

image = Image.open(documents_images_v2[15].image_path).convert("RGB")

plt.figure(figsize=(16, 9))
plt.imshow(image)
`

I receive the following error: AttributeError: 'Document' object has no attribute 'image_path'

This makes sense, since in the API I do not see any reference field. I do, however, see it in **ImagePath**. I am not sure what the next step is.

### Version

0.9.16

### Steps to Reproduce

`python
from llama_index.multi_modal_llms.openai import OpenAIMultiModal
from llama_index import SimpleDirectoryReader

# put your local directore here
documents_images_v2 = SimpleDirectoryReader("./llama2/").load_data()

image = Image.open(documents_images_v2[15].image_path).convert("RGB")

plt.figure(figsize=(16, 9))
plt.imshow(image)
`

**Comment by logan-markewich** [comment]
Is the llama2 folder a folder of images?

**Comment by XariZaru** [comment]
> Is the llama2 folder a folder of images?

I passed it a single array of one PDF document. I'm referencing Experiment 2 of: https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pdf_tables.html

Sorry, I just realized I posted the sample code rather than the one I'm using as such.

```python
from llama_index import SimpleDirectoryReader

file = "Adobe Extract API Sample.pdf"

documents_images_v2 = SimpleDirectoryReader(
    input_files=[file]
).load_data()

print(f"Loaded {len(documents_images_v2)} docs")
image = Image.open(documents_images_v2[0].image_path).convert("RGB")

plt.figure(figsize=(16, 9))
plt.imshow(image)
```

**Comment by logan-markewich** [comment]
Following the notebook, `llama2` is folder that the notebook creates, full of `png` files

In your code, you just pointed towards a PDF.

Take another read through the notebook. I just ran it and confirmed it worked.

**Comment by logan-markewich** [comment]
Notice the setup here creates the `llama2` folder with images 
https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pdf_tables.html#setup

**Comment by XariZaru** [comment]
> Notice the setup here creates the `llama2` folder with images https://docs.llamaindex.ai/en/stable/examples/multi_modal/multi_modal_pdf_tables.html#setup

Oop, serves me right for jumping straight to the 2nd experiment. Thank you for taking the time to answer this.
