### ISSUE TITLE
[Feature Request]: Google Gemini model support via Vertex AI

### ISSUE THREAD

**Issue by nicoloboschi** [run-llama/llama_index#9607]
### Feature Description

Currently Gemini is available also via Vertex AI API. I'd like to be able to switch from 
```
from llama_index.llms import Vertex
Vertex(model="chat-bison")
```
to 
```
from llama_index.llms import Vertex
Vertex(model="gemini-pro")
```

It's also noteworthy that this is already doable in LangChain 0.0.350
```
from langchain_community.chat_models import ChatVertexAI
ChatVertexAI(model_name="gemini-pro")
```

### Reason

Mid term reason is to being able to switch existing VertexAI application to Gemini models
Short term reason is that Gemini API are blocked in many countries (EU-UK for example) but the usage with Vertex is allowed

**Comment by hatianzhang** [comment]
@nicoloboschi that is a good point. feel free to make a pr to support.
I think you can first try to directly using current Vertex to load gemini pro model to see whether it works

**Comment by nicoloboschi** [comment]
Hi @hatianzhang I opened a pr https://github.com/run-llama/llama_index/pull/9624
Please review
