### ISSUE TITLE
[Question]: Unable to run agents using azure openai 

### ISSUE THREAD

**Issue by Navanit-git** [run-llama/llama_index#9618]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
from llama_index.embeddings import resolve_embed_model
from llama_index.llms import AzureOpenAI
from llama_index import SimpleDirectoryReader, ServiceContext
from llama_index import VectorStoreIndex, SimpleDirectoryReader
from llama_index.langchain_helpers.agents import IndexToolConfig, LlamaIndexTool, LlamaToolkit
from llama_index.langchain_helpers.agents import create_llama_agent


llm = AzureOpenAI(
    model="gpt-35-turbo",
    deployment_name="custom",
    api_key="custom",
    azure_endpoint="custom",
    api_version="2023-07-01-preview")

embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")

from llama_index import set_global_service_context
service_context = ServiceContext.from_defaults(llm=llm,  embed_model=embed_model)
set_global_service_context(service_context)


march_2022 = SimpleDirectoryReader(input_files=["uber_10q_march_2022.pdf"]).load_data()
june_2022 = SimpleDirectoryReader(input_files=["uber_10q_june_2022.pdf"]).load_data()
sept_2022 = SimpleDirectoryReader(input_files=["uber_10q_sept_2022.pdf"]).load_data()

march_index =  VectorStoreIndex.from_documents(march_2022)
june_index =  VectorStoreIndex.from_documents(june_2022)
sept_index =  VectorStoreIndex.from_documents(sept_2022)

march_engine = march_index.as_query_engine(similarity_top_k=3)
june_engine = june_index.as_query_engine(similarity_top_k=3)
sept_engine = sept_index.as_query_engine(similarity_top_k=3)



# initializing zero-shot ReAct agent

uber_config_sept = IndexToolConfig(
    query_engine=sept_engine, 
    name=f"Uber 10Q September 2022",
    description=f"Provides information about Uber quarterly financials ending September 2022",
    tool_kwargs={"return_direct": False}
)
uber_config_june = IndexToolConfig(
    query_engine=june_engine, 
    name=f"Uber 10Q June 2022",
    description=f"Provides information about Uber quarterly financials ending June 2022",
    tool_kwargs={"return_direct": False}
)
uber_config_march = IndexToolConfig(
    query_engine=march_engine, 
    name=f"Uber 10Q March 2022",
    description=f"Provides information about Uber quarterly financials ending March 2022",
    tool_kwargs={"return_direct": False}
)

toolkit = LlamaToolkit(
    index_configs=[uber_config_sept, uber_config_june, uber_config_march],
)

# this is a light wrapper around `initialize_agent` in langchain (which defaults to zero-shot)
agent_chain = create_llama_agent(
    toolkit,
    llm = llm
)

agent_chain.run(input="Analyze Uber revenue growth over the last few quarters")
```

The error that I am getting is 
_ValidationError: 2 validation errors for LLMChain
llm
  instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)
llm
  instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)_

Not in this in multiple agents based work AZURE OPENAI is showing erro

**Comment by sakshi9729** [comment]
> ### Question Validation
> 
>     * [x]  I have searched both the documentation and discord for an answer.
> 
> 
> ### Question
> 
> ```
> from llama_index.embeddings import resolve_embed_model
> from llama_index.llms import AzureOpenAI
> from llama_index import SimpleDirectoryReader, ServiceContext
> from llama_index import VectorStoreIndex, SimpleDirectoryReader
> from llama_index.langchain_helpers.agents import IndexToolConfig, LlamaIndexTool, LlamaToolkit
> from llama_index.langchain_helpers.agents import create_llama_agent
> 
> 
> llm = AzureOpenAI(
>     model="gpt-35-turbo",
>     deployment_name="custom",
>     api_key="custom",
>     azure_endpoint="custom",
>     api_version="2023-07-01-preview")
> 
> embed_model = resolve_embed_model("local:BAAI/bge-small-en-v1.5")
> 
> from llama_index import set_global_service_context
> service_context = ServiceContext.from_defaults(llm=llm,  embed_model=embed_model)
> set_global_service_context(service_context)
> 
> 
> march_2022 = SimpleDirectoryReader(input_files=["uber_10q_march_2022.pdf"]).load_data()
> june_2022 = SimpleDirectoryReader(input_files=["uber_10q_june_2022.pdf"]).load_data()
> sept_2022 = SimpleDirectoryReader(input_files=["uber_10q_sept_2022.pdf"]).load_data()
> 
> march_index =  VectorStoreIndex.from_documents(march_2022)
> june_index =  VectorStoreIndex.from_documents(june_2022)
> sept_index =  VectorStoreIndex.from_documents(sept_2022)
> 
> march_engine = march_index.as_query_engine(similarity_top_k=3)
> june_engine = june_index.as_query_engine(similarity_top_k=3)
> sept_engine = sept_index.as_query_engine(similarity_top_k=3)
> 
> 
> 
> # initializing zero-shot ReAct agent
> 
> uber_config_sept = IndexToolConfig(
>     query_engine=sept_engine, 
>     name=f"Uber 10Q September 2022",
>     description=f"Provides information about Uber quarterly financials ending September 2022",
>     tool_kwargs={"return_direct": False}
> )
> uber_config_june = IndexToolConfig(
>     query_engine=june_engine, 
>     name=f"Uber 10Q June 2022",
>     description=f"Provides information about Uber quarterly financials ending June 2022",
>     tool_kwargs={"return_direct": False}
> )
> uber_config_march = IndexToolConfig(
>     query_engine=march_engine, 
>     name=f"Uber 10Q March 2022",
>     description=f"Provides information about Uber quarterly financials ending March 2022",
>     tool_kwargs={"return_direct": False}
> )
> 
> toolkit = LlamaToolkit(
>     index_configs=[uber_config_sept, uber_config_june, uber_config_march],
> )
> 
> # this is a light wrapper around `initialize_agent` in langchain (which defaults to zero-shot)
> agent_chain = create_llama_agent(
>     toolkit,
>     llm = llm
> )
> 
> agent_chain.run(input="Analyze Uber revenue growth over the last few quarters")
> ```
> 
> The error that I am getting is _ValidationError: 2 validation errors for LLMChain llm instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable) llm instance of Runnable expected (type=type_error.arbitrary_type; expected_arbitrary_type=Runnable)_
> 
> Not in this in multiple agents based work AZURE OPENAI is showing erro

I am facing the same error. Please check the same and give the clear solution.
