### ISSUE TITLE
[Feature Request]: When will llama-index implement adapt other FilterOperators other than EQual?

### ISSUE THREAD

**Issue by maherr13** [run-llama/llama_index#9635]
### Feature Description

Im looking forward to the implemention of all the FilterOperators as it will be very useful feature

**Comment by logan-markewich** [comment]
@maherr13 We have, but it has to be implemented per-vector store

So far, we added support for qdrant, chroma, weaviate, pinecone, astra, Cassandra, postgres

Here's an example with pinecone
https://docs.llamaindex.ai/en/stable/examples/vector_stores/pinecone_metadata_filter.html
