### ISSUE TITLE
[Question]: Maximum number of subquestions with SubQuestionQueryEngine?

### ISSUE THREAD

**Issue by paulommaia** [run-llama/llama_index#9652]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

How can we limit the number of subquestions generated with SubQuestionQueryEngine? I am facing an use case where in some scenarios it's generating up to 30 subquestions and it leads to rate limit errors.
Can we suggest it in the prompt or force it somehow?

**Comment by logan-markewich** [comment]
There's no hard limit, but it would be an easy parameter to add.

But a better solution is probably telling the model in your query. i.e. appending to your query like 

```
query_engine.query(query_str + " Only generate a maximum of 5 important sub-questions.")
```

You can also modify the internal prompt for the question generator and pass in the `question_gen` object as a kwarg, but this is a little more complex. 

I.e. this is the openai question generator: https://github.com/run-llama/llama_index/blob/0c20713952338ff625d8f43c1be30aabc9c862fe/llama_index/question_gen/openai_generator.py#L48

**Comment by paulommaia** [comment]
Thanks for the quick response @logan-markewich !

Is there any concern about adding that as part of the user query, not the system prompt?

And as an alternative, would it also work by changing the tool metadata description?

See the specific scenario below, answering documents for Apple. I have 30 years of history, but I have two scenarios:
- When the user doesn't specify the date, I want to consider 2023 as default.
- When the user asks for 20 years of data, I want to limit this to a maximum of 5 sub queries (for example, only the most recent years). 

`    query_engine=query_engine,
        metadata=ToolMetadata(
            name="sub_question_query_engine",
            description="useful for when you want to answer queries that require analyzing multiple SEC 10-K documents for Apple",
        ),
    )
`
