### ISSUE TITLE
[Question]: how to load an existing vector index in elastic search?

### ISSUE THREAD

**Issue by haolxx** [run-llama/llama_index#9654]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

how to load an existing vector index in elastic search? tried below which is not working - 

# vector_index = load_index_from_storage(
            # storage_context=storage_context,
            # service_context=service_context,
            # index_id = index_name
            # )

Thanks!

**Comment by haolxx** [comment]
need a vector index that can be used as query engineer:

query_engine = vector_index.as_query_engine(
        similarity_top_k=similarity_top_k, node_postprocessors=node_postprocessors,
        response_synthesizer=response_synthesizer
    )

**Comment by logan-markewich** [comment]
Existing vector dbs are loaded with

```
index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)
```

**Comment by haolxx** [comment]
> Existing vector dbs are loaded with
> 
> ```
> index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)
> ```

It worked! Thanks.
