### ISSUE TITLE
[Feature Request]: Support for remaining filters attribute in pinecone

### ISSUE THREAD

**Issue by dheerajiiitv** [run-llama/llama_index#9665]
### Feature Description

If you see, `llama-index` pinecone implementation, some metadata filters are missing. 

### Reason

So we are not able to fully use the `MetadataFilters` functionality of `llama-index` for pinecone vector store

### Value of Feature

Yes, this will make easy to use complex filters on pinecone vector store.

**Comment by hatianzhang** [comment]
@dheerajiiitv not sure which set of meta data filters we are missing for pinecone. please feel free to make a pr to add those missing ones

**Comment by dheerajiiitv** [comment]
sure @hatianzhang I'll pick this up

**Comment by dheerajiiitv** [comment]
@hatianzhang created this PR: https://github.com/run-llama/llama_index/pull/9674
I tried to follow the instruction, but might be wrong. PTAL

**Comment by hatianzhang** [comment]
@dheerajiiitv thanks! it works.
I tried this way https://github.com/codespell-project/codespell/issues/1212#issuecomment-1721152455 but somehow did not make it work.
