### ISSUE TITLE
[Bug]: openai required

### ISSUE THREAD

**Issue by thegallier** [run-llama/llama_index#9676]
### Bug Description

out of documentation: https://docs.llamaindex.ai/en/stable/module_guides/models/embeddings.html#modules

/===

from langchain.embeddings.huggingface import HuggingFaceBgeEmbeddings
from llama_index import ServiceContext

embed_model = HuggingFaceBgeEmbeddings(model_name="BAAI/bge-base-en")

service_context = ServiceContext.from_defaults(embed_model=embed_model)

gives

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/llms/utils.py](https://localhost:8080/#) in resolve_llm(llm)
     28             llm = OpenAI()
---> 29             validate_openai_api_key(llm.api_key)
     30         except ValueError as e:

4 frames
ValueError: No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/llama_index/llms/utils.py](https://localhost:8080/#) in resolve_llm(llm)
     29             validate_openai_api_key(llm.api_key)
     30         except ValueError as e:
---> 31             raise ValueError(
     32                 "\n******\n"
     33                 "Could not load OpenAI model. "

ValueError: 
******
Could not load OpenAI model. If you intended to use OpenAI, please check your OPENAI_API_KEY.
Original error:
No API key found for OpenAI.
Please set either the OPENAI_API_KEY environment variable or openai.api_key prior to initialization.
API keys can be found or created at https://platform.openai.com/account/api-keys

To disable the LLM entirely, set llm=None.
******

### Version

llama-index-0.9.21

### Steps to Reproduce

from langchain.embeddings.huggingface import HuggingFaceBgeEmbeddings
from llama_index import ServiceContext

embed_model = HuggingFaceBgeEmbeddings(model_name="BAAI/bge-base-en")

service_context = ServiceContext.from_defaults(embed_model=embed_model)

**Comment by logan-markewich** [comment]
The LLM defaults to openai 

Either set the LLM to something else, provide the openai key, or explicitly disable it with `ServiceContext.from_defaults(llm=None, ...)`

**Comment by tempdeltavalue** [comment]
@logan-markewich 

Whan you pass none for llm I got "LLM is explicitly disabled. Using MockLLM." what does it mean ? 
I want to do something like that:

embed_model = HuggingFaceEmbedding(MODEL_PATH)


service_context = ServiceContext.from_defaults(llm=None, embed_model=embed_model)

nodes = [TextNode(id_=id_, text=text) for id_, text in corpus.items()] 
index = VectorStoreIndex(
    nodes, 
    service_context=service_context, 
    show_progress=True
)
retriever = index.as_retriever(similarity_top_k=top_k)

**Comment by logan-markewich** [comment]
@tempdeltavalue  that just means if you tried to use a query engine, it would not work. Since you are only using a retriever it's fine

**Comment by tempdeltavalue** [comment]
@logan-markewich MockLLM a bit scared me ) sorry 

Thank you !
