### ISSUE TITLE
[Bug]: Getting incomplete responses in async mode with anthropic

### ISSUE THREAD

**Issue by rc19** [run-llama/llama_index#9678]
### Bug Description

Hello I am using llama-index (v0.9.16) and using async streaming apis (`achat_stream`) with the [simple chat engine](https://github.com/run-llama/llama_index/blob/ce75aa5d026524d9b36709769ea3f2e203ac5269/llama_index/chat_engine/simple.py#L141).

However it seems like when I use openai sdk (for anyscale and open models), I get full responses while if I use anthropic sdk (for claude) I get the error

```
<asyncio.locks.Event object at 0x13de7fe50 [unset]> is bound to a different event loop
```
I am confused as to if this is because of llama index or anthropic (given the same code works with openai call)

Any pointers?

### Version

0.9.16

### Steps to Reproduce

```
from llama_index.llms import Anthropic
from llama_index import ServiceContext
from llama_index.chat_engine import SimpleChatEngine


llm = Anthropic(
                model=model,
                temperature=temperature,
                api_key=api_key,
                max_tokens=max_tokens,
                base_url=base_url,
                timeout=timeout,
            )
            
service_context = ServiceContext.from_defaults(
        llm=llm,
    )
ce = SimpleChatEngine.from_defaults(service_context=service_context)
response = await ce.astream_chat(user_message, chat_history)
```

### Relevant Logs/Tracbacks

```shell
WARNING::llama_index.chat_engine.types::Encountered exception writing response to history: <asyncio.locks.Event object at 0x13de7fe50 [unset]> is bound to a different event loop
```

**Comment by Sammyjroberts** [comment]
@rc19 same issue

**Comment by ulan-yisaev** [comment]
Same issue, but with Cohere Async streaming

**Comment by DavidHazzard** [comment]
Has anyone made headway here? I'm experiencing a similar issue when using the BEST/CONTEXT chat mode.
