### ISSUE TITLE
retrieverFn doesn't work on GPT 3.5 1106

### ISSUE THREAD

**Issue by vikyw89** [run-llama/llama_index#9679]
### Bug Description

I tried vectorized Fn to store an arbitrary number of function / tool for gpt to use. It works well for gpt 3.5 turbo but doesn't work for gpt 3.5 turbo 1106

### Version

Stable as of 20231223

### Steps to Reproduce

Call openai agent using retriever of vectorized fn

**Comment by logan-markewich** [comment]
What doesn't work? What's the error? Sample code?

**Comment by vikyw89** [comment]
`from llama_index.tools import FunctionTool,BaseTool
from llama_index import VectorStoreIndex
from llama_index.objects import ObjectIndex, SimpleToolNodeMapping

def multiply(a: int, b: int) -> int:
    """Multiply two integers and returns the result integer"""
    return a * b


def add(a: int, b: int) -> int:
    """Add two integers and returns the result integer"""
    return a + b


def useless(a: int, b: int) -> int:
    """being useless"""
    pass


multiply_tool = FunctionTool.from_defaults(fn=multiply, name="multiply")
add_tool = FunctionTool.from_defaults(fn=add, name="add")
useless_tools = [
    FunctionTool.from_defaults(fn=useless, name=f"useless_{str(idx)}")
    for idx in range(28)
]

all_tools = [multiply_tool] + [add_tool] + useless_tools
all_tools_map = {t.metadata.name: t for t in all_tools}

tool_mapping = SimpleToolNodeMapping.from_objects(all_tools)
obj_index = ObjectIndex.from_objects(
    objects=all_tools,
    object_mapping=tool_mapping,
    index_cls=VectorStoreIndex,
)
from dotenv import load_dotenv
load_dotenv()
from llama_index.agent import OpenAIAgent, FnRetrieverOpenAIAgent
from llama_index.llms import ChatMessage, MessageRole, OpenAI
from tools import obj_index
import os


llm = OpenAI(model="gpt-3.5-turbo-1106", api_key=os.getenv("OPENAI_API_KEY"))
tool_retriever = obj_index.as_retriever()
from tools import all_tools
agent = OpenAIAgent.from_tools(
    tools=all_tools,
    tool_retriever=tool_retriever,
    chat_history=[],
    llm=llm,
    verbose=True,
)
async def gen():
    from agent import agent
    response = await agent.astream_chat(
        "What is 121 + 8? Once you have the answer, use that number to write a"
        " story about a group of mice."
    )

    response_gen = response.response_gen

    async for token in response.async_response_gen():
        print(token, end="")


import asyncio

loop = asyncio.new_event_loop()

loop.run_until_complete(gen())

`

**Comment by vikyw89** [comment]
using gpt-turbo-3.5-1106 will gives this result:
```
Added user message to memory: What is 121 + 8? Once you have the answer, use that number to write a story about a group of mice.
=== Calling Function ===
Calling function: useless_12 with args: {"a":121,"b":8}
Got output: None
========================

It seems that the tool I used to calculate 121 + 8 is not responding. Let me try using a different tool to perform the calculation.
```

**Comment by vikyw89** [comment]
and here is the result using the default gpt-turbo-3.5
```
Added user message to memory: What is 121 + 8? Once you have the answer, use that number to write a story about a group of mice.
The sum of 121 and 8 is 129.

Once upon a time, in a small village, there was a group of 129 mice living happily in a cozy little burrow. These mice were known for their intelligence and resourcefulness. They had created a tight-knit community where everyone looked out for each other.

One sunny morning, as the mice were going about their daily activities, they noticed a delicious aroma wafting through the air. Curiosity piqued, they followed the scent and discovered a bountiful feast of cheese and grains left unattended by the villagers.

Excited by their find, the mice quickly devised a plan to transport the food back to their burrow. They formed an organized line, with each mouse carrying a small portion of the feast. Working together, they managed to transport all the food safely back to their burrow.

With their bellies full and their spirits high, the mice decided to celebrate their successful mission. They gathered in the center of the burrow and began to dance and sing joyfully. Their tiny voices echoed through the tunnels, creating a harmonious melody that filled the air.

As the night fell, the mice settled down to rest, feeling grateful for their unity and teamwork. They knew that by working together, they could overcome any challenge that came their way. The mice drifted off to sleep, dreaming of more adventures and delicious feasts in the future.

And so, the group of 129 mice lived happily ever after, continuing to thrive in their close-knit community, always ready to face new challenges and celebrate their victories together.
```

**Comment by vikyw89** [comment]
conclusion, tools retriever doesn't work with GPT-3.5-turbo-1106, while it works with GPT-3.5-turbo

probable cause:
1. GPT 3.5-turbo-1106 uses tool and tool_call in their api as opposed to function and function_call
2. ... ?
