### ISSUE TITLE
[Documentation]: Links is not working in multiple docs page

### ISSUE THREAD

**Issue by aaronjimv** [run-llama/llama_index#9684]
### Documentation Issue Description

There are several links that are not working on the documentation pages:

`Agent page` [see here](https://docs.llamaindex.ai/en/stable/use_cases/agents.html):
>Learn more
Our Putting It All Together section has [more on agents](https://docs.llamaindex.ai/en/latest/use_cases/agents.html#/docs/understanding/putting_it_all_together/agents.md)
---
`Chatbots page` [see here](https://docs.llamaindex.ai/en/stable/use_cases/chatbots.html):
>[Building a chatbot](https://docs.llamaindex.ai/en/stable/use_cases/chatbots.html#/docs/understanding/putting_it_all_together/chatbots/building_a_chatbot.md) tutorial
---
`Q&A` [see here](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a.html):
>[Searching Pandas tables](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a.html#/examples/query_engine/pandas_query_engine.md)

>[Text to SQL](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a.html#/examples/index_structs/struct_indices/SQLIndexDemo.md)

>For further examples of Q&A use cases, see our [Q&A section in Putting it All Together](https://docs.llamaindex.ai/en/stable/use_cases/q_and_a.html#/understanding/putting_it_all_together/q_and_a.html).

### Documentation Link

https://docs.llamaindex.ai/en/stable/use_cases/agents.html
https://docs.llamaindex.ai/en/stable/use_cases/chatbots.html
https://docs.llamaindex.ai/en/stable/use_cases/q_and_a.html

**Comment by bL34cHig0** [comment]
Hi, I'd like to work on this issue. However, I could see that @0xDigest referenced this issue.
