### ISSUE TITLE
[Bug]: The IngestionPipeline does not take vector_store parameters constructed from TimescaleVectorStore and ElasticsearchVectorStore

### ISSUE THREAD

**Issue by gich2009** [run-llama/llama_index#9690]
### Bug Description

All other vector_stores(Qdrant, weaviate, pinecone, chroma) work well with the ingestion pipeline except for the TimescaleVectorStore and the ElasticsearchVectorStore

### Version

0.9.21

### Steps to Reproduce

# For Timescale
vector_store = TimescaleVectorStore(
                        service_url=timescale_config["service_url"],
                        table_name="default",
                        num_dimensions=timescale_config["dimension"],
                    )

documents: List[Document] = SimpleDirectoryReader(input_dir=directory_path).load_data()

pipeline = IngestionPipeline(
            transformations=[
                SentenceSplitter(),
                OpenAIEmbedding()
            ],
            vector_store=vector_store,
        )
        pipeline.run(documents=documents, show_progress=True)

#For Elastic search
es_client = Elasticsearch(
                    cloud_id=elasticsearch_config["cloud_id"],
                    api_key=elasticsearch_config["api_key"]
                )
                vector_store = ElasticsearchStore(
                    index_name=elasticsearch_config['index_name'],
                    es_client=es_client,
                    distance_strategy=elasticsearch_config["distance_strategy"],
                )

documents: List[Document] = SimpleDirectoryReader(input_dir=directory_path).load_data()

pipeline = IngestionPipeline(
            transformations=[
                SentenceSplitter(),
                OpenAIEmbedding()
            ],
            vector_store=vector_store,
        )
        pipeline.run(documents=documents, show_progress=True)

**Comment by logan-markewich** [comment]
It needs to use the new base class, just haven't switched it over yet.

**Comment by gich2009** [comment]
I had also noticed the same issue for MongoDB and Faiss.

**Comment by logan-markewich** [comment]
And again, some issue I mentioned above. Plz submit a pr to migrate the base class if you need it fixed now. Otherwise I'll get to it at some point 🫡

**Comment by gich2009** [comment]
Hey @logan-markewich, I've just migrated all the vector_stores to the new BasePydanticVectorStore but I don't have the rights to push the branch and make a PR. Could you point me in the right direction on how to go about this?

**Comment by logan-markewich** [comment]
@gich2009 you can fork the PR, make changes, and then contribute using your fork

**Comment by ravi03071991** [comment]
@logan-markewich @gich2009 Taking a look at it now and will raise PR accordingly.

**Comment by gich2009** [comment]
Hi @ravi03071991, much appreciation for this. I had taken an initial look, but my changes broke a few modules. I've been a bit held up so I couldn't pursue the issue further.

**Comment by sNug0** [comment]
Same issue when using LanceDBVectorStore

**Comment by patrickporto** [comment]
Same issue using MilvusVectorStore

**Comment by gich2009** [comment]
It's a migration issue @sNug0, @patrickporto. Most VectorStores need to be migrated to BasePydanticVectorStore but are still using the BaseVectorStore class.

**Comment by patrickporto** [comment]
I solved here by wrapping the MilvusVectorStore under BasePydanticVectorStore

**Comment by ravi03071991** [comment]
@patrickporto milvusvectorstore is migrated to BasePydanticVectorStore. You don’t need to wrap it.
