### ISSUE TITLE
About embeddings

### ISSUE THREAD

**Issue by 4entertainment** [run-llama/llama_index#9692]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I'm using llamaindex to develop RAG mechanism with chromadb. My relevant codes are below:

`  index = VectorStoreIndex.from_documents(documents, storage_context=storage_context, service_context=service_context)
`
or 
```
             query_engine = index.as_query_engine()

                 #prompt = input("ask:")
                 prompt = "some_searched_text"
                 response = query_engine.query(prompt)
```

I think we need to debug one of these parts. 

I need to find exactly where the embeddings are made and saved with the embedding function of the read files. I need to debug and access it, but I couldn't find it in llamaindex's project files. Please help me.

**Comment by logan-markewich** [comment]
I'm not 100% sure what you need. But here's an example of the lowest-level API

Here's how nodes and embeddings get generated when using `from_documents()` essentially
```
from llama_index import SimpleDirectoryReader
documents = SimpleDirectoryReader("./data").load_data()

from llama_index.node_parse.text import SentenceSplitter
splitter = SentenceSplitter()
nodes = splitter(documents)

from llama_index.embeddings import OpenAIEmbedding
from llama_index.schema import MetadataMode
embed_model = OpenAIEmbedding()
embeddings = embed_model.get_text_embedding_batch(
  [node.get_content(metadata_mode=MetadataMode.EMBED) for node in nodes]
)

for (node, embedding) in zip(nodes, embeddings):
  node.embedding = embedding
```

Then, you can create the index using the nodes directly
```python
from llama_index import VectorStoreIndex, StorageContext
from llama_index.vector_stores import ChromaVectorStore

vector_store = ChromaVectorStore(...)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = VectorStoreIndex(nodes, storage_context=storage_context)
```

The code in llama-index for this is mostly here
https://github.com/run-llama/llama_index/blob/2ab4c3045502ebce673960746561d44ff0dbc7b8/llama_index/indices/vector_store/base.py#L24

You can also check this page for other low-level APIs for querying
https://docs.llamaindex.ai/en/stable/understanding/querying/querying.html#customizing-the-stages-of-querying

**Comment by logan-markewich** [comment]
I'm pretty sure the above more than answers your question. Closing for now
