### ISSUE TITLE
[Bug]: npm run generate (VectoreStoreIndex) hangs on large files

### ISSUE THREAD

**Issue by fvkramer** [run-llama/llama_index#9693]
### Bug Description

I created a new NextJs app with `npx create-llama@latest` following steps here: https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama

No changes in code from starter template.

I added the usc tax code to the `./data` folder and reran `npm run generate` to create embeddings. When running the script, the script hangs after saying `Generating storage context...`.

I added basic console logging and looks like it hangs on this line:

```
await VectorStoreIndex.fromDocuments(documents, {
      storageContext,
      serviceContext,
    });
```

The pdf file I'm using is 17MB, or 7000 pages of text. No images in file.

I believe the script hangs instead of working slowly in background because I'm checking my API calls to OpenAI. Only an initial embedding call is done to generate the document metadata hash, but no subsequent API calls.

I tested by removing this large 17MB file and using a smaller PDF. Everything works fine.

Using `node 18.17.0`

### Version

latest

### Steps to Reproduce

Follow steps here to create NextJS app.
https://github.com/run-llama/LlamaIndexTS/tree/main/packages/create-llama

Add the US Tax Code to `./data`. PDF download file from here http://uscode.house.gov/download/download.shtml (Title 26)

Run `npm run generate`.

**Comment by logan-markewich** [comment]
That is indeed the line of code that embeds all your data.

Do you have a paid openai key? I've never really encountered this

Note that 17MB of text will take several minutes (or tens of minutes) to embed. It gets chunked into pieces of 1024 tokens.

You can try increasing the batch size on the embed model (default is 10)

```
from llama_index.embeddings import OpenAIEmbedding 
embed_model = OpenAIEmbedding(embed_batch_size=1000)
service_context = ServiceContext.from_defaults(..., embed_model 
=embed_model)
```

**Comment by fvkramer** [comment]
@logan-markewich I retried a few hours later and things worked. The previous failed run ran for about 15 minutes. It might just have not been long enough or I might have hit rate limits on OpenAI side, but can't be sure.

I'm going to close this out. Thanks for the response
