### ISSUE TITLE
[Bug]: pandas query engine triggers safe_eval

### ISSUE THREAD

**Issue by olyashok** [run-llama/llama_index#9696]
### Bug Description

Pandas query results in 
df['LOCATION'].value_counts().head()

It triggers File "/usr/local/lib/python3.10/dist-packages/llama_index/exec_utils.py", line 107, in _verify_source_safety
because it matches

pattern = r"_{1,2}\w+_{0,2}"

### Version

0.9.21

### Steps to Reproduce

Create PandasQueryEngine and query to trigger value_counts()

**Comment by tslmy** [comment]
TBH the only safe way to test whether the code contains a call to a dunder function is by parsing the code from text into an abstract syntax tree (AST):

```python
import ast


def contains_dunder_calls(code):

    class DunderCallVisitor(ast.NodeVisitor):
        result = False

        def visit_Call(self, node):
            if isinstance(node.func, ast.Name) and \
               node.func.id.startswith("_"):
                self.result = True

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        print(f"Syntax error in the code: {e}")
        return False

    dunder_call_visitor = DunderCallVisitor()
    dunder_call_visitor.visit(tree)
    return dunder_call_visitor.result


# Example usage
python_code = """
def example_function():
    _private_function()

example_function()
"""

print(contains_dunder_calls(python_code))
```

I suggest replacing the implementation of `_verify_source_safety` with this.

**Comment by tslmy** [comment]
@dosu-bot , methods that start with single underscores are also not safe to call, so let's not exclude them.

Plus, matching a regex in a code snippet isn't ideal anyway. If the code snippet contains comments / strings that happen to contain a method name that starts with an underscore (or two, for that matter), `_verify_source_safety` will also raise a false positive.

TBH the only safe way to test whether the code contains a call to a dunder function is by parsing the code from text into an abstract syntax tree (AST):

```python
import ast


def contains_dunder_calls(code):

    class DunderCallVisitor(ast.NodeVisitor):
        result = False

        def visit_Call(self, node):
            if isinstance(node.func, ast.Name) and \
               node.func.id.startswith("_"):
                self.result = True

    try:
        tree = ast.parse(code)
    except SyntaxError as e:
        print(f"Syntax error in the code: {e}")
        return False

    dunder_call_visitor = DunderCallVisitor()
    dunder_call_visitor.visit(tree)
    return dunder_call_visitor.result


# Example usage
python_code = """
def example_function():
    _private_function()

example_function()
"""

print(contains_dunder_calls(python_code))
```

I suggest replacing the implementation of `_verify_source_safety` with this.

**Comment by Hariprasath-AI** [comment]
Hi @olyashok. 

I've read the problem statement from your description. You've used --> df['LOCATION'].value_counts().head(). This means that you're trying to get only the head(first 5 as default) of distinct value with their counts. There is no chance of getting error for code you mentioned. So, please upgrade the pandas and check it. This is the suggestion from my side. Try it, then we will discuss. 

Best Regards,
Hariprasath G

**Comment by olyashok** [comment]
look here
https://github.com/run-llama/llama_index/blob/3b522159eeade961618e2de7411fff87356bd6cb/llama_index/exec_utils.py#L102C13-L102C13

this code aint right - it matches everything
![image](https://github.com/run-llama/llama_index/assets/50547198/937785ab-1f82-4444-9ba5-1715e421c1c7)
