### ISSUE TITLE
[Bug]: AI Search showing warning for index migration to vector profile

### ISSUE THREAD

**Issue by akashtalole** [run-llama/llama_index#9703]
### Bug Description

When I created and ingested data using llamaindex, AI search showing following warning and asking for migration.
`This index has vector fields created using the 2023-07-01-preview definition. It can't be edited using new API versions. We recommend that you migrate it to use vector profiles to restore full portal functionality. `

### Version

0.9.16

### Steps to Reproduce

Create index and ingest data using llamaindex.

### Relevant Logs/Tracbacks

```shell
This index has vector fields created using the 2023-07-01-preview definition. It can't be edited using new API versions. We recommend that you migrate it to use vector profiles to restore full portal functionality.
```

**Comment by akashtalole** [comment]
@dosu-bot this issue still persist

**Comment by logan-markewich** [comment]
I have not a single clue lol, no clue how azure stuff works. I do know the azure search stuff is getting updated/refactored soon since it's quite out of date
