### ISSUE TITLE
SQLTableRetrieverQueryEngine and database views instead of tables

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#9706]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to use SQLTableRetrieverQueryEngine to answer question about data stored in database.
As database structure is extremely complex I created database views with data that I would like to query.
Executing the code I am not getting any errors but on the other hand looks like obj_index is not really populated with table definitions and columns so querying over multiple tables in not possible and I am getting quite a lot of halucinations as there are non existent columns in queries.

Any hints if using views instead of tables is supported ?
and are there any adjustments required. 

I am justing just  simple code from example below:

from llama_index.objects import SQLTableNodeMapping, ObjectIndex, SQLTableSchema
from llama_index.indices.struct_store import SQLTableRetrieverQueryEngine

table_node_mapping = SQLTableNodeMapping(sql_database)
table_schema_objs = [(SQLTableSchema(table_name="city_stats")), ...] # one SQLTableSchema for each table

obj_index = ObjectIndex.from_objects(
    table_schema_objs,
    table_node_mapping,
    VectorStoreIndex,
)

query_engine = SQLTableRetrieverQueryEngine(
    sql_database, obj_index.as_retriever(similarity_top_k=1)
)
response = query_engine.query("Which city has the highest population?")
print(response)

**Comment by vjr** [comment]
@dinonovak have you set the option flag to enable view support like this:
`sql_database = SQLDatabase(sql_engine, view_support=True)` ?

**Comment by dinonovak** [comment]
I have enabled it and also listed only views that I would like to use
sql_database = SQLDatabase(engine, include_tables=['view1','view2'], view_support=True)
