### ISSUE TITLE
[Question]: Can I install the module for llama_index with Googlecolab?

### ISSUE THREAD

**Issue by YYana93** [run-llama/llama_index#9722]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

When running llama_index with Googlecolab, I am having trouble installing the module "QuestionAnswerPrompt" and the library "langchain". Is there anyone who can get it working with Googlecolab now? #Bug

**Comment by logan-markewich** [comment]
Can you give more explanation? You might have to downgrade langchain slightly if I had to guess

**Comment by YYana93** [comment]
Hi Logan,
Thank you for your reply.

The error log is below
----------------------
ImportError traceback (most recent call)
<ipython-input-1-e7a0a8e31193> in <cell row: 9>()
----> 9 from llama_index import QuestionAnswerPrompt, SimpleDirectoryReader, OpenAIEmbedding
ImportError: Cannot import name 'QuestionAnswerPrompt' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)
---------------------------

**Comment by logan-markewich** [comment]
@YYana93 I think you might be following an outdated guide. There is only one prompt type now

`from llama_index.prompts import PromptTemplate`

But you can achieve the equivalent import with `from llama_index.prompts.prompts import QuestionAnswerPrompt`

**Comment by logan-markewich** [comment]
https://docs.llamaindex.ai/en/stable/module_guides/models/prompts.html#prompts
