### ISSUE TITLE
[Question]: What is the default similarity algorithm for queries？

### ISSUE THREAD

**Issue by mistoFENG** [run-llama/llama_index#9723]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

```
query_engine = index.as_query_engine()
response = query_engine.query("What did the author do growing up?")
```
What is the default similarity algorithm for queries？

**Comment by logan-markewich** [comment]
Pairwise cosine similarity 

https://github.com/run-llama/llama_index/blob/e114f1fc4e8d7c337b5ec417f87d0b5c1f797cdb/llama_index/embeddings/base.py#L36
