### ISSUE TITLE
[Question]: ReAct agent, not passing action input correctly to tool, but hallucinating at first step

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#9725]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I created 2 different query engines, DB query engine and generic LLM query engine

```
# Define DB query engine

db_query_engine = SQLTableRetrieverQueryEngine(
    sql_database,
    obj_index.as_retriever(similarity_top_k=3),
    service_context=service_context,
    text_to_sql_prompt=text_to_sql_prompt,
)


# Define LLM query engine

qa_prompt = PromptTemplate(
    "Context information is below.\n"
    "---------------------\n"
    "{context_str}\n"
    "---------------------\n"
    "Given the context information and not prior knowledge, "
    "answer the query.\n"
    "Query: {query_str}\n"
    "Answer: "
)

class LLMStringQueryEngine(CustomQueryEngine):
    llm: OpenAILike
    qa_prompt: PromptTemplate

    def custom_query(self, query_str: str):
        response = self.llm.complete(query_str)
        
        return str(response)
    
llm_query_engine = LLMStringQueryEngine(
    llm=llm,
    qa_prompt=qa_prompt,
)
```
I created tools based on these query engines:
```
query_engine_tools = [
    QueryEngineTool(
        query_engine=db_query_engine,
        metadata=ToolMetadata(
            name="db_query",
            description=(
                "Provides information about entries from database"
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
    QueryEngineTool(
        query_engine=llm_query_engine,
        metadata=ToolMetadata(
            name="llm_query",
            description=(
                "Provides general information based on model knowledge"
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
]

```
I created agent based on these tools:
`agent = ReActAgent.from_tools(query_engine_tools, llm=llm, verbose=True)
`

When I am querying each query engine directly I am getting correct response,

But when I am asking agent to provide answer it looks like agent is hallucinating on agent decision,  instead of just passing the initial question to agent it is trying to construct SQL query as action input and is inventing table and column names
Strangely it was working for brief time, but then started this hallucinations.
I tried using agent.reset() as I thought that agent history can be issue, as sometime it started answering without going to database.
I am using Mixtral 7x8B as LLM accessed throught API (OpenAILike LLM definition). Could it be the case that it is Mixtral keeping it somehow in the history, is there any context reset that could be sent to LLM?

here is some generic question
```
response = agent.chat('use db_query to show me entry with latest ACTIVE status, display name and status date') 
print(response.response)
```

and verbose log:
Thought: I need to use the `db_query` tool to retrieve the information about the entries  with the latest ACTIVE status.
Action: db_query
Action Input: {'input': "SELECT entry_name, entry_date FROM Entries WHERE entry_status = 'ACTIVE' ORDER BY entry_date DESC LIMIT 1;"}
**********
Trace: chat
    |_CBEventType.AGENT_STEP ->  59.037927 seconds
      |_CBEventType.LLM ->  2.264976 seconds
      |_CBEventType.FUNCTION_CALL ->  56.771783 seconds
        |_CBEventType.RETRIEVE ->  0.098935 seconds
          |_CBEventType.EMBEDDING ->  0.098451 seconds
        |_CBEventType.TEMPLATING ->  8e-06 seconds
        |_CBEventType.LLM ->  1.885245 seconds
        |_CBEventType.SYNTHESIZE ->  54.518435 seconds
          |_CBEventType.TEMPLATING ->  2.6e-05 seconds
          |_CBEventType.LLM ->  2.995604 seconds
          |_CBEventType.TEMPLATING ->  2.4e-05 seconds
          |_CBEventType.LLM ->  1.347868 seconds
          |_CBEventType.TEMPLATING ->  3.2e-05 seconds
          |_CBEventType.LLM ->  1.226248 seconds
          |_CBEventType.TEMPLATING ->  1.9e-05 seconds
          |_CBEventType.LLM ->  2.022342 seconds
          |_CBEventType.TEMPLATING ->  2.7e-05 seconds
          |_CBEventType.LLM ->  1.039552 seconds
          |_CBEventType.TEMPLATING ->  1.9e-05 seconds
          |_CBEventType.LLM ->  0.996389 seconds
...
          |_CBEventType.LLM ->  3.137375 seconds
          |_CBEventType.TEMPLATING ->  2.3e-05 seconds
          |_CBEventType.LLM ->  0.0 seconds

**Comment by dinonovak** [comment]
I have discovered that it looks like issue can be agent definition, and initial query parsing from agent side.

when requesting from agent to process complex query like:
`response = agent.chat('list 10 persons from personstatus table with most recent ACTIVE status and MASTER rank, display person name, status date,  company, birthdate and full address')`

agent converts it to following:
```
Thought: To answer this question, I need to use the 'db_tool' tool to retrieve the required information from the 'personstatus' table.
Action: db_tool
Action Input: {'title': 'Query', 'description': 'The query to execute on the personstatus table', 'type': 'string'} 
```

this means that whole query is lost and not transferred to tool, can you somehow specify in agent definition that for this specific tool original query could be passed?
How do you display / modify agent prompt?

**Comment by logan-markewich** [comment]
I think you are slightly misunderstanding how agents work

They get a user message, look at a list of tools/descriptions, and decide whether to call a tool or respond directly. As part of this process, the LLM rewrites the input to the tool, following the schema of that tool.

If you want it to pass in the original user message, you kind of have to tell it to do that, either in a system prompt or tool description.

Also, Open-Source LLMs are (in my experience) not great at being agents right now (hence the hallucinating you described originally)

**Comment by dinonovak** [comment]
hi @logan-markewich,
as I am handing data stored in DB and some of it is considered sensitive privately hosted open source model is the only viable solution. I am using Mixtral 7x8b and I am pleasantly surprised how usable it is.

I managed to find the solution,
I am actually wrapping SQLTableRetrieverQueryEngine in CustomQueryEngine and creating DBStringQueryEngine(CustomQueryEngine). Then I am found out that when defining the tool you can instruct it I"nput is human language" and also tweeking is needed in text_to_sql_prompt for SQLTableRetrieverQueryEngine

query_engine_tools = [
    QueryEngineTool(
        query_engine=db_query_engine,
        metadata=ToolMetadata(
            name="fromRDBMS",
            description=(
                "Provides information about people from database. Input is human language"
                "Always ignore previous conversation history and fetch data from database unless told differently."
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
    QueryEngineTool(
        query_engine=llm_query_engine,
        metadata=ToolMetadata(
            name="fromModel",
            description=(
                "Provides general information based on model knowledge"
                "Use a detailed plain text question as input to the tool."
            ),
        ),
    ),
]

This way I managed to get input pretty much only as instruction text, despite the fact that sometimes it still suggest something that looks very similar to SQL query.

One thing that I found out is that agent keeps conversation and activity history. Despite this being usefull, sometimes this creates disastrous results, If there is for example specific person mentioned previously and any data relevant for him was already fetched, with next question system can hallucinate and not fetch data from database but present this false date straight up.

I know that I can reset get and agent.memory, but is there any other option to control QueryEngineTool itself.
I can see that question is routed to correct QueryEngineTool, but this QueryEngineTool then  despite being defined as SQLTableRetrieverQueryEngine does not fetch from DB but from some memory.
How can I purge this?

**Comment by tslmy** [comment]
Hi @dinonovak ,

Mine also hallucinates quite a bit, but I was able to alleviate the problem by overriding the system prompt.

```python
    # Override the default system prompt for ReAct chats.
    with open("system_prompt.md") as f:
        MY_SYSTEM_PROMPT = f.read()

    class MyReActChatFormatter(ReActChatFormatter):
        system_header = MY_SYSTEM_PROMPT

    chat_formatter = MyReActChatFormatter()
    return ReActAgent.from_tools(
        tools=all_tools,
        llm=local_llm,
        verbose=True,
        react_chat_formatter=chat_formatter,
    )
```

where [`system_prompt.md`](https://github.com/run-llama/llama_index/files/13796823/system_prompt.md) is my spin on the default prompt, with emphasis on tool usage.

Try if this helps. Good luck!
