### ISSUE TITLE
[Question]: How to use separator like "\n\n\n" to split texts in SentenceSplitter?

### ISSUE THREAD

**Issue by Lauorie** [run-llama/llama_index#9726]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I intended to get chunks like:
```
['Rotary Position Embedding',
'is a widely used',
'positional encoding technique',
'large language models']
```
but I got:

`['Rotary Position Embedding\n\n\nis a widely used\n\n\npositional encoding technique\n\n\nlarge language models']`

when using the following code:
```
import tiktoken
from llama_index.text_splitter import SentenceSplitter

text_splitter = SentenceSplitter(
    separator=" ",
    chunk_size=20,
    chunk_overlap=0,
    paragraph_separator="\n\n\n",
    secondary_chunking_regex="[^,.;。]+[,.;。]?",
    tokenizer=tiktoken.encoding_for_model("gpt-3.5-turbo").encode,
)
text_chunks = text_splitter.split_text('Rotary Position Embedding\n\n\nis a widely used\n\n\npositional encoding technique\n\n\nlarge language models')
text_chunks
```
So, how can I get what I want, thx.

**Comment by Lauorie** [comment]
Let me restate my original goal: I have a text file like this:
```
Rotary Position Embedding
is a widely used
positional encoding technique
large language models
```

I'd like to embed every single line as a single vector, then store it into the VectorStore, but when I use
```
from llama_index import VectorStoreIndex, ServiceContext
service_context = ServiceContext.from_defaults(chunk_size=20,chunk_overlap=0)
index = VectorStoreIndex.from_documents(documents, service_context=service_context,show_progress=True)
```
it embedded whole text, but I need like this: 
```
Rotary Position Embedding  [1,2,5,4,5421,1,1,21...]
is a widely used [1,2,5,4,5421,1,1,21...]
positional encoding technique [1,2,5,4,5421,1,1,21...]
large language models [1,2,5,4,5421,1,1,21...]
```
not 
```
Rotary Position Embedding is a widely used positional encoding technique large language models [1,2,5,4,5421,1,1,21...]
```
So can you help me with this?

**Comment by logan-markewich** [comment]
Splitters have two steps -- splitting, then merging

It splits using the separator, but then merges back up to your chunk size

I'd suggest just splitting the text the way you want and creating node objects to achieve the splitting you want

```
from llama_index.schema import TextNode

texts = text.split("\n\n\n")
nodes = [TextNode(text=text) for text in texts]

index = VectorStoreIndex(nodes, ...)
```

**Comment by qkxie** [comment]
@logan-markewich 

it raises an error: `AttributeError: 'TextNode' object has no attribute 'get_doc_id'`
