### ISSUE TITLE
[Bug]: Got this error while running the colab notebook GoogleDemo.ipynb

### ISSUE THREAD

**Issue by BuggieCoder** [run-llama/llama_index#9733]
### Bug Description

InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.FAILED_PRECONDITION
	details = "User location is not supported for the API use."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:173.194.69.95:443 {created_time:"2023-12-28T22:45:29.198630054+00:00", grpc_status:9, grpc_message:"User location is not supported for the API use."}"

### Version

not known

### Steps to Reproduce

running the colab notebook

**Comment by logan-markewich** [comment]
@BuggieCoder as the error states, it's only supported in certain countries.

For example, it's not supported in Canada. I'm also in Canada, I use a VPN to access the API lol

**Comment by BuggieCoder** [comment]
Thank you for your quick reply. I am in the US  though.

**Comment by logan-markewich** [comment]
Do you maybe have a VPN already running? 

Not sure what else could be the issue. But in any case it's not related to llama-index. Going to close out for now

**Comment by BuggieCoder** [comment]
Thanks! I do have VPN. Should I turn off VPN?

**Comment by logan-markewich** [comment]
Definitely worth a try!
