### ISSUE TITLE
[Documentation]: Docs of querying is outdated

### ISSUE THREAD

**Issue by wangyuxinwhy** [run-llama/llama_index#9736]
### Documentation Issue Description

The document has not been updated with the code. The default response_mode is now **compact**, but it is listed as **default** in the document.

### Documentation Link

https://docs.llamaindex.ai/en/stable/understanding/querying/querying.html#configuring-response-synthesis

**Comment by tslmy** [comment]
I think you can just open a PR for one-word changes like this without opening an issue beforehand. (I seldomly do with mine.) Maintainers of this repo are usually very welcoming towards PRs as such.

Cheers.

**Comment by Aryan8912** [comment]
Please assign to me so I can work on this issue

**Comment by logan-markewich** [comment]
@Aryan8912 no need to be assigned -- anyone can open a PR to fix any issue :)
