### ISSUE TITLE
[Question]: ImportError: cannot import name 'BASE_TRACE_EVENT' from 'llama_index.callbacks.schema'

### ISSUE THREAD

**Issue by pengchengliava** [run-llama/llama_index#9737]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

when I try use from llama_index  import download_loader showing below error

ImportError: cannot import name 'BASE_TRACE_EVENT' from 'llama_index.callbacks.schema' 

here is the code I am used

from llama_index  import download_loader
from llama_index.callbacks.schema import CBEventType
CJKPDFReader = download_loader("CJKPDFReader")

loader = CJKPDFReader()
documents = loader.load_data(file='data\test.pdf')
print(documents)

**Comment by logan-markewich** [comment]
That import definitely exists
https://github.com/run-llama/llama_index/blob/2b8f720d7cae705ff8effeabe133b4765689ea01/llama_index/callbacks/schema.py#L12

I'm not sure why you are importing CBEventType. Either remove that import or reinstall llama-index in a fresh venv, sounds like your installation is outdated/wonky
