### ISSUE TITLE
Please add support for database views in SQLDatabase

### ISSUE THREAD

**Issue by johanteekens** [run-llama/llama_index#9748]
### Feature Description

current situation: SQLDatabase(engine, include_tables=["city_stats"])
obj_index = ObjectIndex.from_objects(table_schema_objs,table_node_mapping,VectorStoreIndex,)
query_engine = SQLTableRetrieverQueryEngine(sql_database, obj_index.as_retriever(),)

preferred new option: SQLDatabase(engine, include_databaseobjects=["city_stats","myview1","mytable1","myview2"])

### Reason

My database tables are virtually unreadable for anything, but I can create views on top of my tables, that explain what is it is, convert julian dates, do lookups etc etc. I can't change the tables because that would break my application, but I can add views. 

### Value of Feature

SQLTableRetrieverQueryEngine becomes more flexible and powerful.

please........  ;-)

**Comment by logan-markewich** [comment]
I have no idea how table views would work the sqlalchemy, but I encourage you to take a stab at a PR if you are up to it.

The SQLDatabase code is here
https://github.com/run-llama/llama_index/blob/1736097a5902ef39fd289a645ad9765058f1c8b3/llama_index/utilities/sql_wrapper.py#L9

**Comment by johanteekens** [comment]
Looking at sql_wrapper.py, It looks like someone already build in support.

In sql_wrapper.py there is this bool: view_support: bool = False, it looks like it's as simple as toggling it.

**Comment by logan-markewich** [comment]
Give it a shot, see if it works 🫡

**Comment by johanteekens** [comment]
Created pull request #9802

Works perfectly fine for me at least
