### ISSUE TITLE
[Question]:  ValueError: Asking to pad but the tokenizer does not have a padding token.

### ISSUE THREAD

**Issue by itech001** [run-llama/llama_index#9763]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

`hf_model_name = 'StabilityAI/stablelm-tuned-alpha-3b'
tokenizer_kwargs = {'padding':'longest',"max_length": 4096}
tokenizer = AutoTokenizer.from_pretrained(hf_model_name,**tokenizer_kwargs)
if tokenizer.pad_token is None:
    tokenizer.add_special_tokens({'pad_token': '[PAD]'})
#tokenizer.add_special_tokens({'pad_token': '[PAD]'})
#tokenizer.pad_token = tokenizer.eos_token
#print(tokenizer)
set_global_tokenizer(tokenizer.encode)

llm = HuggingFaceLLM(model_name=hf_model_name,
    tokenizer_name=hf_model_name,
    tokenizer = tokenizer,
    context_window=4096,
    max_new_tokens=512,
    generate_kwargs={"temperature": 0.8, "do_sample": True, "top_p":0.95, "top_k":20},
    device_map="auto",
    #stopping_ids=[50278, 50279, 50277, 1, 0],
    model_kwargs={"trust_remote_code" : True},
    #tokenizer_kwargs=tokenizer_kwargs,
    # uncomment this if using CUDA to reduce memory usage
    #model_kwargs={"torch_dtype": torch.float16, "trust_remote_code" :True}
    )`

ValueError: Asking to pad but the tokenizer does not have a padding token. Please select a token to use as `pad_token` `(tokenizer.pad_token = tokenizer.eos_token e.g.)` or add a new pad token via `tokenizer.add_special_tokens({'pad_token': '[PAD]'})`.

**Comment by itech001** [comment]
@dosu-bot your previous answer doesn't work

**Comment by logan-markewich** [comment]
As the error mentions, you need a pad token.

Instantiate the tokenizer, and assign it like it suggests 

`tokenizer.pad_token = tokenizer.eos_token`

You can then pass in the tokenizer directly instead 
`HuggingFaceLLM(..., tokenizer=tokenizer)

**Comment by itech001** [comment]
> As the error mentions, you need a pad token.
> 
> Instantiate the tokenizer, and assign it like it suggests
> 
> `tokenizer.pad_token = tokenizer.eos_token`
> 
> You can then pass in the tokenizer directly instead `HuggingFaceLLM(..., tokenizer=tokenizer)

I also tried this change, but it doesn't work yet

**Comment by itech001** [comment]
Is it related with below? it seems that the global tokenizer is not correct?
set_global_tokenizer(tokenizer.encode)

**Comment by logan-markewich** [comment]
What tokenizer are you using?

**Comment by itech001** [comment]
> What tokenizer are you using?

tokenizer by same model name:

25 hf_model_name = 'StabilityAI/stablelm-tuned-alpha-3b'
 26 tokenizer_kwargs = {'padding':'longest',"max_length": 4096}
 27 tokenizer = AutoTokenizer.from_pretrained(hf_model_name,**tokenizer_kwargs)

**Comment by logan-markewich** [comment]
idk man, it works fine for me 

https://colab.research.google.com/drive/10OcOIw3VnIPQ3ckhWgy_uHwvWhg71kgD?usp=sharing

**Comment by logan-markewich** [comment]
its not the global tokenizer, that is just calling `tokenizer.encode()` on random strings. Only the LLM would apply padding.

You can see in the logs above, transformers automatically sets the pad token to the eos token anyways 🤔

**Comment by itech001** [comment]
what functions for stopping_ids=[50278, 50279, 50277, 1, 0],?
