### ISSUE TITLE
[Bug]: Limit cannot push down

### ISSUE THREAD

**Issue by sandernordeide** [run-llama/llama_index#9764]
### Bug Description

![image](https://github.com/run-llama/llama_index/assets/59870985/4b773401-a444-4c7e-8125-1408e78eba5f)
I have a nebula graph database instantiated with docker compose, and a simple match query with the keywords shown in the picture gives me three records.

I have filled my kg_index with the following logic:

```
space_name = "llamaindex"
edge_types, rel_prop_names = ["relationship"], [
    "relationship"
]  # default, could be omit if create from an empty kg
tags = ["entity"]  # default, could be omit if create from an empty kg


space_name = "llamaindex"
graph_store = NebulaGraphStore(
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
)
storage_context = StorageContext.from_defaults(graph_store=graph_store)


```
```
text_splitter = CustomTextSplitter(chunk_size=250, chunk_overlap=30)
texts = text_splitter.split_text(" ".join(texts))
documents = [Document(text=t) for t in texts]

documents = documents[:50]

kg_index = KnowledgeGraphIndex.from_documents(
    documents,
    storage_context=storage_context,
    max_triplets_per_chunk=10,
    space_name=space_name,
    edge_types=edge_types,
    rel_prop_names=rel_prop_names,
    tags=tags,
    include_embeddings=True,
)

kg_keyword_query_engine = kg_index.as_query_engine()
query = "World Health Organization"
kg_response = kg_keyword_query_engine.query(query)
```

This gives me an error message which stems from the Cypher-query found in 
`get_flat_rel_map` in `nebulagraph.py`. The error message is as follows:

ValueError: Query failed. Query: 

WITH map{`true`: '-[', `false`: '<-['} AS arrow_l,     map{`true`: ']->', `false`: ']-'} AS arrow_r,     map{`relationship`: "relationship"} AS edge_type_map MATCH p=(start)-[e:`relationship`*..2]-()   WHERE id(start) IN $subjs WITH start, id(start) AS vid, nodes(p) AS nodes, e AS rels,  length(p) AS rel_count, arrow_l, arrow_r, edge_type_map WITH   REDUCE(s = vid + '{', key IN [key_ in ['', 'name']     WHERE properties(start)[key_] IS NOT NULL]  | s + key + ': ' +       COALESCE(TOSTRING(properties(start)[key]), 'null') + ', ')      + '}'    AS subj,  [item in [i IN RANGE(0, rel_count - 1)|[nodes[i], nodes[i + 1],      rels[i], typeid(rels[i]) > 0, type(rels[i]) ]] | [    arrow_l[tostring(item[3])] +      item[4] + ':' +      REDUCE(s = '{', key IN SPLIT(edge_type_map[item[4]], ',') |         s + key + ': ' + COALESCE(TOSTRING(properties(item[2])[key]),        'null') + ', ') + '}'      +    arrow_r[tostring(item[3])],    REDUCE(s = id(item[1]) + '{', key IN [key_ in         ['', 'name'] WHERE properties(item[1])[key_]         IS NOT NULL]  | s + key + ': ' +         COALESCE(TOSTRING(properties(item[1])[key]), 'null') + ', ')        + '}'    ]  ] AS rels WITH   REPLACE(subj, ', }', '}') AS subj,  REDUCE(acc = collect(NULL), l in rels | acc + l) AS flattened_rels RETURN   subj,  REPLACE(REDUCE(acc = subj, l in flattened_rels | acc + ' ' + l),     ', }', '}')     AS flattened_rels  LIMIT 30
Param: {'subjs': Value(
    lVal=NList(
         values=[Value(
             sVal='World')]))}
Error message: Scan vertices or edges need to specify a limit number, or limit number can not push down.

From what I may percieve, the limit value is not effectively in use, as the subqueries beforehand are too expensive, but I am not sure how to correct this, tried inserting limits in several places of the query without luck,.

### Version

0.9.22

### Steps to Reproduce

1. Instantiate Nebula graph compose with docker desktop
2. Fill a kg_index as such, where documents are of type List[llama_index.schema.Document]
            ` kg_index = KnowledgeGraphIndex.from_documents(
                    documents,
                    storage_context=storage_context,
                    max_triplets_per_chunk=10,
                    space_name=space_name,
                    edge_types=edge_types,
                    rel_prop_names=rel_prop_names,
                    tags=tags,
                    include_embeddings=True,
                )` 
3. Run the following snippet:
              `kg_keyword_query_engine = kg_index.as_query_engine()
              query = "World Health Organization"
              kg_response = kg_keyword_query_engine.query(query)`

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "...\.venv\lib\site-packages\tenacity\__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
  File "...\.venv\lib\site-packages\llama_index\graph_stores\nebulagraph.py", line 275, in execute
    raise ValueError(
ValueError: Query failed. Query: WITH map{`true`: '-[', `false`: '<-['} AS arrow_l,     map{`true`: ']->', `false`: ']-'} AS arrow_r,     map{`relationship`: "relationship"} AS edge_type_map MATCH p=(start)-[e:`relationship`*..2]-()   WHERE id(start) IN $subjs WITH start, id(start) AS vid, nodes(p) AS nodes, e AS rels,  length(p) AS rel_count, arrow_l, arrow_r, edge_type_map WITH   REDUCE(s = vid + '{', key IN [key_ in ['', 'name']     WHERE properties(start)[key_] IS NOT NULL]  | s + key + ': ' +       COALESCE(TOSTRING(properties(start)[key]), 'null') + ', ')      + '}'    AS subj,  [item in [i IN RANGE(0, rel_count - 1)|[nodes[i], nodes[i + 1],      rels[i], typeid(rels[i]) > 0, type(rels[i]) ]] | [    arrow_l[tostring(item[3])] +      item[4] + ':' +      REDUCE(s = '{', key IN SPLIT(edge_type_map[item[4]], ',') |         s + key + ': ' + COALESCE(TOSTRING(properties(item[2])[key]),        'null') + ', ') + '}'      +    arrow_r[tostring(item[3])],    REDUCE(s = id(item[1]) + '{', key IN [key_ in         ['', 'name'] WHERE properties(item[1])[key_]         IS NOT NULL]  | s + key + ': ' +         COALESCE(TOSTRING(properties(item[1])[key]), 'null') + ', ')        + '}'    ]  ] AS rels WITH   REPLACE(subj, ', }', '}') AS subj,  REDUCE(acc = collect(NULL), l in rels | acc + l) AS flattened_rels RETURN   subj,  REPLACE(REDUCE(acc = subj, l in flattened_rels | acc + ' ' + l),     ', }', '}')     AS flattened_rels  LIMIT 30, Param: {'subjs': Value(
    lVal=NList(
         values=[Value(
             sVal='World')]))}Error message: Scan vertices or edges need to specify a limit number, or limit number can not push down.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\.venv\lib\site-packages\llama_index\core\base_retriever.py", line 54, in retrieve
    nodes = self._retrieve(query_bundle)
  File "...\.venv\lib\site-packages\llama_index\indices\knowledge_graph\retrievers.py", line 186, in _retrieve
    rel_map = self._graph_store.get_rel_map(
  File "...\.venv\lib\site-packages\llama_index\graph_stores\nebulagraph.py", line 488, in get_rel_map
    return self.get_flat_rel_map(subjs, depth, limit)
  File "...\.venv\lib\site-packages\llama_index\graph_stores\nebulagraph.py", line 457, in get_flat_rel_map
    result = self.execute(query, subjs_param)
  File "...\.venv\lib\site-packages\tenacity\__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
  File "...\.venv\lib\site-packages\tenacity\__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
  File "...\.venv\lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x29d4d08fdf0 state=finished raised ValueError>]
```

**Comment by dewasahu2003** [comment]
hi can i take a this issue if anybody mind ?
