### ISSUE TITLE
[Bug]: qdrant vector store does not handle nested payloads

### ISSUE THREAD

**Issue by olyashok** [run-llama/llama_index#9766]
### Bug Description

   function that parses the node ignores nested attributes:
 def parse_to_query_result(self, response: List[Any]) -> VectorStoreQueryResult:
   

-    node = metadata_dict_to_node(payload) does not do anything since payload metadata has no "_node_content" so it reverts to "deprecated legacy logic for backward compatibility" 

since qdrant returns nested metadata as List 
this line if isinstance(val, (str, int, float, type(None))):

probably hsould add a List to that

ignores that part of payload

also why do we have this - i had a metadata called doc_id and was expecting it back but it was stripped
   metadata.pop("id", None)
    metadata.pop("document_id", None)
    metadata.pop("doc_id", None)
    metadata.pop("ref_doc_id", None)

### Version

0.9.22

### Steps to Reproduce

try to query qdrant with nested metadata - it is not processed by vector_stores utils

**Comment by logan-markewich** [comment]
It's really intended to work best if there is a node_content field (I.e you built the index with llama-index)

Support beyond that is beta at best.

Those values are popped from the dict, because the function that transforms the node into a dict adds those (a symptom of some older backwards support)

**Comment by olyashok** [comment]
i think if you will looky here 
https://github.com/run-llama/llama_index/blob/3b522159eeade961618e2de7411fff87356bd6cb/llama_index/exec_utils.py#L102C13-L102C13

you will see that llama code is aint right

![image](https://github.com/run-llama/llama_index/assets/50547198/430bb6e9-d066-4901-a402-6a37f5a32515)

**Comment by olyashok** [comment]
oh well - not every vector database in the world is built with llama.
but you can keep building under that assumption - see where that takes you

**Comment by logan-markewich** [comment]
Please make a PR if you see room for improvement, there is certainly 101 thongs to work on and make better :)

**Comment by tslmy** [comment]
> oh well - not every vector database in the world is built with llama.
> but you can keep building under that assumption - see where that takes you

Maybe I'm misreading your tone here, but this doesn't sound helpful.

> Version
> 0.9.22

You are using a software with version <1, which implies there are a _lot_ of problems. It does **not** mean folks has ever built things under any assumption; it merely means many corners have been cut to make something you and I can use right away.

It's like talking to a toddler. If they make a grammatical mistake, you excuse them; you don't say "you can keep on with that baby talk and see whether that would land you with a Ph.D."

I myself also see imperfections regarding integrations between LlamaIndex with other components, even places where LlamaIndex went against conventions / standards (https://github.com/run-llama/llama_index/issues/9770), but I don't mindread.

Anyway, I wish you a happy new year, @olyashok .

**Comment by olyashok** [comment]
Obviously i want to help improve it - why else i would file bugs.

2 easy improvements in that class:

  *   Add List to if type check so that List parameters also get passed through
  *   Do not strip out common payload attributes like “id”, “doc_id”


Kind regards
Alex
________________________________

**Comment by logan-markewich** [comment]
@olyashok maybe see if the above change makes sense

**Comment by olyashok** [comment]
@logan-markewich - this will do it. thx!
