### ISSUE TITLE
[Bug]: Output from tool calls are not very observable

### ISSUE THREAD

**Issue by tslmy** [run-llama/llama_index#9770]
### Bug Description

# What seems wrong

I can't see responses from **function calls** in Arize Phoenix...

<img width="1143" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/1731d4e1-f85b-4893-8755-cec7297f1736">

... or in ChainLit:

<img width="821" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/f2c2503d-5cc9-4ecd-9f59-50b857816b2c">

# What I was expecting

I usually can see results from other types of Spans, such as `embedding` in Arize Phoenix...

<img width="1177" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/32c5b5ca-a032-4ef7-a281-a1cd824f2408">

... and Query Engines tools in ChainLit:

<img width="863" alt="image" src="https://github.com/run-llama/llama_index/assets/594058/45eafc65-f160-4f1a-bac1-8f2a4b9a8442">

so I was expecting the same level of observability for `FunctionTool`s.

# My guess

I think this is because `"function_call_response"`, the string LlamaIndex uses to identify responses from generic function calls with callback handlers, was non-standard to OpenInference Tracing conventions.

The `"function_call_response"` is defined here: https://github.com/run-llama/llama_index/blob/3b522159eeade961618e2de7411fff87356bd6cb/llama_index/callbacks/schema.py#L61 .

It is sent to callback managers here: https://github.com/run-llama/llama_index/blob/3b522159eeade961618e2de7411fff87356bd6cb/llama_index/agent/react/step.py#L230 .

And the conventions are [here](https://arize-ai.github.io/open-inference-spec/trace/spec/semantic_conventions.html). Indeed, Arize Phoenix doesn't know `"function_call_response"`, as shown here:

https://github.com/Arize-ai/phoenix/blob/363e8913a3a0f7dafca5dc6bba6bf0e9776c1158/app/src/openInference/tracing/semanticConventions.ts#L51-L58

### Version

0.9.23

### Steps to Reproduce

```python
from llama_hub.tools.wikipedia import WikipediaToolSpec
from llama_index.agent import ReActAgent
from llama_index.callbacks.base import CallbackManager
from llama_index.llms import OpenAILike
import chainlit as cl
import phoenix as px


# "Phoenix can display in real time the traces automatically collected from your LlamaIndex application."
# https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html
px.launch_app()


@cl.on_chat_start
async def factory():
    callback_manager = CallbackManager([cl.LlamaIndexCallbackHandler()])

    local_llm = OpenAILike(
        api_base="http://localhost:1234/v1",
        timeout=600,  # secs
        api_key="loremIpsum",
        # I'm using this: https://huggingface.co/HuggingFaceH4/zephyr-7b-beta .
        model="zephyr beta 7B q5_k_m gguf",
        is_chat_model=True,
        is_function_calling_model=True,
        context_window=32768,
        callback_manager=callback_manager,
    )

    tool_spec = WikipediaToolSpec()
    agent = ReActAgent.from_tools(
        tools=tool_spec.to_tool_list(),
        llm=local_llm,
        callback_manager=callback_manager,
    )
    cl.user_session.set("agent", agent)


@cl.on_message
async def main(message: cl.Message):
    """ChainLit provides a web GUI for this application."""
    agent: ReActAgent = cl.user_session.get("agent")
    response = await cl.make_async(agent.chat)(message.content)
    response_message = cl.Message(content="")
    response_message.content = response.response
    await response_message.send()
```

Save the script above as `main.py`. Run in terminal:

```shell
chainlit run main.py -w
```

Ask the Agent "Search Wikipedia and summarize what is a cheesecake", and observe.

**Comment by logan-markewich** [comment]
@tslmy do you have any idea on what the fix here would be? Looking at arize's spec, I actually have no idea 😆 We should be populating a `tool_calls` attribute?

**Comment by tslmy** [comment]
@logan-markewich , `tool_calls` is closers, but it also doesn't seem to have a conventional way to specify tool outputs.

I opened an Issue to the Open Inference Specifications repo above, where I asked maintainers there to come up with a conventional way to specify tool outputs. Let's see what they will say.

**Comment by tslmy** [comment]
@dosubot shall we wait till https://github.com/Arize-ai/open-inference-spec/issues/37 is closed before closing this?

**Comment by teis-e** [comment]
Hello, i am also trying to get a non OpenAI model working. Is OpenAILike the only way to do this, like you did. Or can i just use HuggingFaceLLM?

**Comment by logan-markewich** [comment]
@teis-e openailike is for models hosted on a server that has the same API as openai 

HuggingfaceLLM is specifically for running a model locally (no server, just in the same process/program as llamaindex)

**Comment by teis-e** [comment]
> @teis-e openailike is for models hosted on a server that has the same API as openai 
> 
> 
> 
> HuggingfaceLLM is specifically for running a model locally (no server, just in the same process/program as llamaindex)

Right! Thnx, but the openailike gives the opurtunity to run agents and function calling etc without OpenAI. So just a local model, like the Zypher from above?

**Comment by logan-markewich** [comment]
Using openailike does not magically give access to function calling (I wish haha)

The server running the api has to actually have this implemented to handle the tools kwarg when running the model

**Comment by ryann-sportsbet** [comment]
Hi @teis-e,

Do you have any update on this issue?

I'm experiencing the same problem while attempting to track token usage from LLM calls. I'm using Phoenix, and I'm finding it difficult to determine the precise number of input, output, and total tokens used for each LLM call. 
For context, I'm working with Bedrock Converse.
Any insights or progress on this matter would be greatly appreciated mate

**Comment by teis-e** [comment]
I think you can tokenize the messages and then the len() of that is the token amount.Op 14 okt 2024 om 05:15 heeft ryann-sportsbet ***@***.***> het volgende geschreven:﻿
Hi @teis-e,
Do you have any update on this issue?
I'm experiencing the same problem while attempting to track token usage from LLM calls. I'm using Phoenix, and I'm finding it difficult to determine the precise number of input, output, and total tokens used for each LLM call.
For context, I'm working with Bedrock Converse.
Any insights or progress on this matter would be greatly appreciated mate

**Comment by teis-e** [comment]
I can think you can tokenize the messaga and then the len() is the amount of tokens.
