### ISSUE TITLE
[Bug]: OpenAIPydanticProgram method failed (KeyError: 'description' missing)

### ISSUE THREAD

**Issue by FaresKi** [run-llama/llama_index#9777]
### Bug Description

While following the OpenAIPydanticProgram tutorial [here](https://docs.llamaindex.ai/en/stable/examples/output_parsing/openai_pydantic_program.html), I've ran into `KeyError('description')` errors.
After some extra investigation, it turns out that the problem is in the `to_openai_tool` method:
```py
def to_openai_tool(pydantic_class: Type[BaseModel]) -> Dict[str, Any]:
    """Convert pydantic class to OpenAI tool."""
    schema = pydantic_class.schema()
    function = {
        "name": schema["title"],
        "description": schema["description"],
        "parameters": pydantic_class.schema(),
    }
    return {"type": "function", "function": function}
```
The Pydantic schema that's passed down from `OpenAIPydanticProgram`'s `from_defaults` method doesn't contain the `description` property and current documentation doesn't describe how to pass it. I've also noticed that the type for `BaseModel` is Pydantic's v1 and not the latest Pydantic, so maybe the issue is located there?

### Version

0.9.15.post2

### Steps to Reproduce

Try the demo provided in the documentation. You should run into the same problem.

**Comment by FaresKi** [comment]
Following @logan-markewich comment else where, I've decided to add a docstring to my class.
I'd be happy to modify the documentation but can we think of a better solution? Like trying to solve the original "description" generation issue?

**Comment by logan-markewich** [comment]
@FaresKi the solution is indeed to add a docsting.

Probably we just need to raise a better error. I don't think defaulting to any other string is a good idea.

**Comment by FaresKi** [comment]
Better error management is definitely key. It was very obscure and required some deep debugging to pinpoint it. 
Maybe the `description` information could be passed thru an argument in the `from_defaults` method?

**Comment by logan-markewich** [comment]
yea a kwarg could be passed in to override the docstring, that works too

**Comment by FaresKi** [comment]
I've forked the repo, I'll start working on it.
