### ISSUE TITLE
[Question]: BM25 Retriever implementation without doc.store

### ISSUE THREAD

**Issue by codesridhar** [run-llama/llama_index#9794]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

We have successfully indexed various documents from diverse environments in Llama Index, but we are encountering challenges in persisting the data. Our goal is to implement BM25 search using the indexed documents stored in Milvus. Could you please provide guidance or advice on how to proceed with this implementation?

**Comment by logan-markewich** [comment]
You can do it without the docstore, but you need some method for getting and/or storing all the nodes.

As discussed on discord, the BM25 retriever relies on having access to all the nodes. This can be accomplished by
- Using a docstore (i.e. redis, MongoDB, or simple save to disk)
https://docs.llamaindex.ai/en/stable/module_guides/storing/docstores.html
- Doing a `retrieve` on your vector db with an absurdly high top-k to get all the nodes
```
retriever = index.as_retriever(similarity_top_k=10000)
source_nodes = retriever.retrieve("text")
nodes = [x.node for x in source_nodes]
```
- Storing the node objects somewhere else manually

Personally, I would bite the bullet and just maintain a docstore. It has quite a few nice advantages, and provides extra observability into your data.

Going to close this out for now though
