### ISSUE TITLE
[Feature Request]: Use `ServiceContext` whenever possible

### ISSUE THREAD

**Issue by sansmoraxz** [run-llama/llama_index#9822]
### Feature Description

There are instances where the code will resolve to trying to call OpenAI based services even if service context is set globally.

### Reason

Passing explicitly the objects required can be tedious and error prone. However sometimes that may not even be possible viz. trying to do with "HyDE Query Transform"

### Value of Feature

Make the code more modular and reduce coupling with OpenAI services, also prevent code breaking due to unexpected network calls to OpenAI.

**Comment by logan-markewich** [comment]
Totally understandable. The service context will be deprecated in the next few weeks in favor of a global settings object, like fastapi.

**Comment by sansmoraxz** [comment]
Also auto resolutions like these:

https://github.com/run-llama/llama_index/blob/main/llama_index/embeddings/utils.py#L45-L61

**Comment by logan-markewich** [comment]
The plan is to have a single source of truth for which settings to use, with room for local overrides per module

**Comment by sansmoraxz** [comment]
Can you link the corresponding PR/ Issue to this?

**Comment by logan-markewich** [comment]
It's not up yet, but I will link ot when it's ready (it's a HUGE change lol)

**Comment by sansmoraxz** [comment]
This can be closed right?

Since pydantic settings is the standard now.

**Comment by tslmy** [comment]
> This can be closed right?
> 
> Since pydantic settings is the standard now.

+1. @logan-markewich , can you help us close this one? Thanks.

**Comment by logan-markewich** [comment]
Yes! Thanks for catching this
