### ISSUE TITLE
Using custom embeddings and embeddingfunction with sentence transformers

### ISSUE THREAD

**Issue by dinonovak** [run-llama/llama_index#9823]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I would like to use custom embeddings function as I need specific sentence transformer for multilingual support:

This is howe I create embeddings function:
class MyEmbeddingFunction(EmbeddingFunction[Documents]):
    def __call__(self, input: Documents) -> Embeddings:
        #sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="bert-base-multilingual-uncased")
        sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(model_name="intfloat/multilingual-e5-large")
        embeddings = sentence_transformer_ef(input)
        return embeddings

custom = MyEmbeddingFunction()

and I can pass it to cromadb without any problems:
chroma_collection  = chroma_client.get_or_create_collection(name=f"MLRag", embedding_function=custom)

But in order to use it in query_engine I need to pass embed model to service context

# set service context
service_context = ServiceContext.from_defaults(
    chunk_size=768,
    llm=llm,
    embed_model=embed_model
)

how can I construct custom embed model that will use my custom transformers?

**Comment by logan-markewich** [comment]
You'll probably find this helpful. Just need to extend the base class

https://docs.llamaindex.ai/en/stable/examples/embeddings/custom_embeddings.html

**Comment by dinonovak** [comment]
I tried using:
embed_model = SentenceTransformerEmbeddings(model_name="intfloat/multilingual-e5-large")

# set service context
service_context = ServiceContext.from_defaults(
    chunk_size=768,
    llm=llm,
    embed_model=embed_model
)

but no luck

**Comment by dinonovak** [comment]
I also tried:
from llama_index.embeddings import HuggingFaceEmbedding
embed_model = HuggingFaceEmbedding(model_name="intfloat/multilingual-e5-large")

model is downloaded, but query_engine dies on search

**Comment by logan-markewich** [comment]
You can also use the langchain model if you want, but it needs a wrapper
https://docs.llamaindex.ai/en/stable/examples/embeddings/Langchain.html

Going to close out this issue then
