### ISSUE TITLE
[Question]: What's the recommended way to save summaries from multiple documents? 

### ISSUE THREAD

**Issue by kilimchoi** [run-llama/llama_index#9828]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I've been reading this https://docs.llamaindex.ai/en/stable/examples/usecases/City_Analysis-Decompose-KeywordTable.html and I've been trying to do something similar by using the index saved in the vector db. 
Is it generally recommended to save the document text as well as its summary in the metadata if we want to later fetch it to initialize a graph? 
Or is it better to use the same summary for each document regardless of the document's content? 
Is there a resource I can take a look to load the documents & summaries from the vector db?

**Comment by logan-markewich** [comment]
The composable graph has not been updated in a hot minute (and will likely be removed at a later date)

Current approaches for multi-doc revolve around a few things, mostly they boil down to providing methods to route queries to the proper locations

https://docs.llamaindex.ai/en/stable/module_guides/querying/router/root.html
https://docs.llamaindex.ai/en/stable/examples/query_engine/sub_question_query_engine.html
https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html
https://docs.llamaindex.ai/en/stable/examples/retrievers/recursive_retriever_nodes.html

**Comment by kilimchoi** [comment]
> The composable graph has not been updated in a hot minute (and will likely be removed at a later date)
> 
> Current approaches for multi-doc revolve around a few things, mostly they boil down to providing methods to route queries to the proper locations
> 
> https://docs.llamaindex.ai/en/stable/module_guides/querying/router/root.html https://docs.llamaindex.ai/en/stable/examples/query_engine/sub_question_query_engine.html https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html https://docs.llamaindex.ai/en/stable/examples/retrievers/recursive_retriever_nodes.html

Thanks
