### ISSUE TITLE
[Feature Request]: updated docs on streaming

### ISSUE THREAD

**Issue by nick-youngblut** [run-llama/llama_index#9829]
### Feature Description

https://docs.llamaindex.ai/en/stable/module_guides/deploying/query_engine/streaming.html#streaming only shows a simple example (mainly `index.as_query_engine(streaming=True, similarity_top_k=1)`, but does not show streaming with an Open AI agent (e.g., `astream_chat`) or other possible requirements to enable streaming. 

It is generally unclear when streaming is supported or not. For instance, `[a]stream_chat` is not [yet implemented](https://github.com/run-llama/llama_index/blob/cd892a51d31cc3aa47b7adf9db60e88d9ee96188/llama_index/agent/openai_assistant_agent.py#L538C1-L545C65) but it appears that the [streaming docs](https://docs.llamaindex.ai/en/stable/module_guides/deploying/query_engine/streaming.html#streaming) do not note that fact, and whether one can stream with an OpenAI agent or not.

The full example at https://docs.llamaindex.ai/en/stable/examples/customization/streaming/SimpleIndexDemo-streaming.html does not provide much extra information. 

This can easily lead to the error `object has no attribute 'response_gen'` when one naively tries to implement `index.as_query_engine(streaming=True, similarity_top_k=1)` (or similar).

### Reason

Streaming is a very useful feature, but there are complexities that do not seem to be fully discussed at https://docs.llamaindex.ai/en/stable/module_guides/deploying/query_engine/streaming.html#streaming

### Value of Feature

Streaming is a very useful feature, but there are complexities that do not seem to be fully discussed at https://docs.llamaindex.ai/en/stable/module_guides/deploying/query_engine/streaming.html#streaming

**Comment by logan-markewich** [comment]
The docs you linked are purely for query engines.

Docs on chat engines/agents are over here
https://docs.llamaindex.ai/en/stable/module_guides/deploying/chat_engines/usage_pattern.html#streaming

Of course, if streaming is not implemented for a particular LLM, an error is raised.

I realize the interface is different between an agent/chat_engine and a query engine, and we do note that on the link above.
