### ISSUE TITLE
[Bug]: APIConnectionError on a custom agents implementation with AzureOpenAI 

### ISSUE THREAD

**Issue by pansu7** [run-llama/llama_index#9834]
### Bug Description

Getting APIConnectionError while using custom agents implementation with AzureOpenAI LLM

### Version

0.9.24

### Steps to Reproduce

https://docs.llamaindex.ai/en/latest/examples/agent/custom_agent.html

<img width="715" alt="error" src="https://github.com/run-llama/llama_index/assets/11588195/120715ce-692e-4cd0-9537-34b5ab359c64">

**Comment by logan-markewich** [comment]
@pansu7 there are a few key places you need to pass in the LLM in order to switch to azure.

Let's walk through it in order

## Setup the llm and embed model
```
from llama_index import set_global_service_context
llm = <azure_llm>
embed_model = <azure embed_model>
```

## Handle Query Engines
```
service_context = ServiceContext.from_defaults(llm=llm, embed_model=embed_model)
set_global_service_context(service_context)
```

## Pydantic selector
```
self._router_query_engine = RouterQueryEngine(
    selector=PydanticSingleSelector.from_defaults(llm=llm),
    query_engine_tools=tools,
    verbose=kwargs.get("verbose", False),
)
```

## Use OpenAI program (or llm text completion if you want)
```
llm_program = LLMTextCompletionProgram.from_defaults(
    output_parser=PydanticOutputParser(output_cls=ResponseEval),
    prompt=chat_prompt_tmpl,
    llm=self.llm,
)

# or for function calling api
llm_program = OpenAIPydanticProgram.from_defaults(
    prompt=chat_prompt_tmpl,
    llm=self.llm,
    output_cls=ResponseEval,
)
```

## Be sure to pass the LLM into the final worker
```
agent_worker = RetryAgentWorker.from_tools(
    query_engine_tools,
    llm=llm,
    verbose=True,
    callback_manager=callback_manager,
)
```

**Comment by pansu7** [comment]
- Thanks @logan-markewich . This works for me now.
