### ISSUE TITLE
[Question]: Multi Document Agents 

### ISSUE THREAD

**Issue by noviljohnson** [run-llama/llama_index#9835]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

i am following multi document agent https://docs.llamaindex.ai/en/stable/examples/agent/multi_document_agents.html#setup-and-download-data

i got an issue, it is saying the description is too long.
So i tried reducing the description size, then i am not getting the correct answers.
so how do i increase the limit of description length.

=== Calling Function ===
Calling function: 2311_17815_pdf with args: {
  "input": "sections"
}
STARTING TURN 1
---------------

Got output: Error: Error code: 400 - {'error': {'message': "'Useful for questions related to specific aspects of the following listed ...............................................
computing approaches, Source code compilation'   is too long    - 'tools.0.function.description'", 'type': 'invalid_request_error', 'param': 
None, 'code': None}}
========================

STARTING TURN 2
---------------

=== Calling Function ===
Calling function: 2311_10805_reinforcementLearning_pdf with args: {
  "input": "sections"
}
STARTING TURN 1
---------------

Got output: I'm sorry, but your request is not clear. Could you please specify which sections of the document you are interested in or what information you are looking for?

**Comment by logan-markewich** [comment]
This error is coming directly from the openai client. I don't think there's any way to change that limit as far as I know.

My best guess is you need to get a little more creative with writing your descriptions while making them shorter.

**Comment by noviljohnson** [comment]
Thank You [logan-markewich](https://github.com/logan-markewich)
