### ISSUE TITLE
[Bug]: DocumentSummaryIndex over WeaviateVectorStore gives key error during retrieval

### ISSUE THREAD

**Issue by wdeaderick** [run-llama/llama_index#9850]
### Bug Description

I've built a `DocumentSummaryIndex` over an underlying `WeaviateVectorStore` as such:
```
vector_store = WeaviateVectorStore(weaviate_client=client, index_name=weaviate_class_name)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = DocumentSummaryIndex.from_documents(
    documents,
    service_context=service_context,
    storage_context=storage_context,
)
```
with a `service_context` that has been working well together with `VectorStoreIndex`. This seems to be working as expected; in particular, I'm able to run `index.get_document_summary()` for a given `doc_id` and get a reasonable summary of the document. However, when I try to run either of the following:
```
query_engine = index.as_query_engine(response_mode="tree_summarize")
response = query_engine.query('my query here')
```
or
```
retriever = DocumentSummaryIndexEmbeddingRetriever(index)
retrieved_nodes = retriever.retrieve('my query here')
```

I see `KeyError: '0'` occurring at `llama_index/indices/document_summary/retrievers.py:168` (`node_ids = self._index_struct.summary_id_to_node_ids[summary_id]`).

Digging further, it looks like my `index.index_struct.summary_id_to_node_ids.keys()` are hashes, e.g. `ccf4a9b9-d42a-4e1f-905c-0c63ed467b0a`. But when I run the following code (taken from `llama_index/indices/document_summary/retrievers.py`):
```
query_bundle = QueryBundle('my query here')
query_bundle.embedding = (
    index._service_context.embed_model.get_agg_embedding_from_queries(
        query_bundle.embedding_strs
    )
)
query = VectorStoreQuery(
    query_embedding=query_bundle.embedding,
    similarity_top_k=4,
)
query_result = index._vector_store.query(query)
print(query_result.ids)
```
The returned IDs are `['0', '1', '2', '3']`. So the retriever is using these as the `summary_id`s, while the `index.index_struct.summary_id_to_node_ids` contains hashes, leading to a `KeyError`.

Any idea what's going on? Am I missing something? I'm thinking it may have to do with the fact that my `index._vector_store` is a `WeaviateVectorStore`, which I haven't seen used with this type of index in any docs. Taking a look at https://github.com/run-llama/llama_index/blob/main/llama_index/vector_stores/weaviate.py#L346, it seems that this vector store just returns `str(i)` over `enumerate`d `i`s (rather than node IDs) for its `VectorStoreQueryResult.ids`.

### Version

0.9.24

### Steps to Reproduce

See issue description

**Comment by logan-markewich** [comment]
@wdeaderick here's what I did to get this to work (admittedly I was too lazy to boot up weaviate, so I used qdrant, but should be the same)


## Create storage context
```python
from llama_index.vector_stores import QdrantVectorStore
from llama_index import StorageContext
import qdrant_client

client = qdrant_client.QdrantClient(":memory:")
vector_store = QdrantVectorStore("test", client=client)

storage_context = StorageContext.from_defaults(vector_store=vector_store)
```

## Create index
```python
doc_summary_index = DocumentSummaryIndex.from_documents(
    city_docs,
    service_context=service_context,
    storage_context=storage_context,
    show_progress=True,
)
```

## Save/load it
```
doc_summary_index.storage_context.persist(persist_dir="./index")

from llama_index.indices.loading import load_index_from_storage
from llama_index import StorageContext

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="./index", vector_store=vector_store)
doc_summary_index = load_index_from_storage(storage_context)
```

## Query it
```
query_engine = doc_summary_index.as_query_engine(
    response_mode="tree_summarize", use_async=True
)

response = query_engine.query("What are the sports teams in Toronto?")
```

**Comment by wdeaderick** [comment]
@logan-markewich This looks basically identical to what I'm doing, but with qdrant instead of Weaviate. Do you mind trying with Weaviate? In the qdrant `query()` function I see the `ids` field of the `VectorStoreQueryResult` gets returned as `str(point.id)`, but in Weaviate it gets returned as `str(i)` over `enumerate`d `i`s. I'm thinking that this way in which `WeaviateVectorStore` sets the `ids` of its `VectorStoreQueryResult` object without looking at the actual node IDs that it retrieved is responsible for this issue, but want to verify.

**Comment by wdeaderick** [comment]
@logan-markewich of all the llama-index `vector_stores` I've looked at, Weaviate is the only one that seems to set its `ids` in this way. The generated `VectorStoreQueryResult` looks like:
```
VectorStoreQueryResult(nodes=[TextNode(id_='efc9572e-31cd-490b-bd6c-9c9cb389e891', embedding=[0.12219, ...], ...) , ... ], similarities=[0.634, 0.591, ...], ids=['0', '1', '2', '3'])
```

I'm guessing if `ids` instead corresponded to the `TextNode` `id_` fields, this might work.

**Comment by logan-markewich** [comment]
Hmm I see

Yea honestly, seems like this for loop should be updated in `weaviate.py`

```python
        for i, entry in enumerate(entries):
            if i < query.similarity_top_k:
                similarities.append(get_node_similarity(entry, similarity_key))
                nodes.append(to_node(entry, text_key=self.text_key))
                node_idxs.append(nodes[-1].node_id)  # <--- changed this line
            else:
                break

        return VectorStoreQueryResult(
            nodes=nodes, ids=node_idxs, similarities=similarities
        )
```

**Comment by logan-markewich** [comment]
Made a PR :)
