### ISSUE TITLE
[Question]: How to add a tool to perform a google search? 

### ISSUE THREAD

**Issue by kilimchoi** [run-llama/llama_index#9851]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi I saw that Llamaindex supports Tavily but when i try to import it using `from llama_hub.tools.tavily_research import TavilyToolSpec` it says, `llama_hub.tools.tavily_research` does not exist.

I was wondering if there's a way to create a tool that can call a third party api that handles web searching.

**Comment by logan-markewich** [comment]
@kilimchoi It imports fine for me

```
pip install --upgrade llama-hub
```

And then this works

```
>>> from llama_hub.tools.tavily_research import TavilyToolSpec
>>> 
```

We have several search tool integrations
https://llamahub.ai/l/tools-bing_search?from=tools
https://llamahub.ai/l/tools-google_search?from=tools
https://llamahub.ai/l/tools-metaphor?from=tools
https://llamahub.ai/l/tools-tavily_research?from=tools
https://llamahub.ai/l/tools-arxiv?from=tools
