### ISSUE TITLE
[Question]: Is it possible to include the function tool as part of the query engine?

### ISSUE THREAD

**Issue by kilimchoi** [run-llama/llama_index#9853]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

So far it seems that you can only include the function tool in the agent object like below:
```
tool_spec = BingSearchToolSpec(api_key='your-key')

agent = OpenAIAgent.from_tools(tool_spec.to_tool_list())
```

But I was wondering if there's a way to do something similar to 

```
s_engine = SubQuestionQueryEngine.from_defaults(
    query_engine_tools=query_engine_tools, function_tools=function_tools
)
```

**Comment by logan-markewich** [comment]
Only if you wrap it with a custom query engine, and wrap that with a query engine tool (since the query engines assume a certain interface, whereas a generic tool can have any interface)

https://docs.llamaindex.ai/en/stable/examples/query_engine/custom_query_engine.html

**Comment by mamdouhweb** [comment]
Is there a direct method to convert a Function Tool to a Query Engine Tool? 
Custom Query Engine path isn't ideal given I can't define the parameters on the engine level. Maybe I'm doing it wrong but would appreciate an example to help illustrate the path from Function Tool to Query Engine Tool

**Comment by mamdouhweb** [comment]
@dosu 
can you provide an example of a Function Tool wrapped in a query engine?
