### ISSUE TITLE
[Question]: Open source LLMs and advanced RAG

### ISSUE THREAD

**Issue by lalehsg** [run-llama/llama_index#9862]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi all! I am wondering if I can use llama-index and advanced RAG methods with open source llms (downloaded from hugging face) but hosted in environments - such as databricks-  other than Replicate (as mentioned in the docs). I would highly appreciate your help.

**Comment by logan-markewich** [comment]
@lalehsg We support a ton of different options for open source LLMs

Check out the full list
https://docs.llamaindex.ai/en/stable/module_guides/models/llms/modules.html

Some that come to mind for hosting options:
vLLM
ollama
TGI (have to use the langchain LLM, we haven't added it yet)

**Comment by lalehsg** [comment]
Thanks so much @logan-markewich ! this is so helpful. I don't see databricks, specifically, in the list so i assume it's out of question. we have to certainly use one of the mentioned platforms for the open source llms. is that correct?

**Comment by logan-markewich** [comment]
I think there are maybe a few others in that list that support open source llms, that I'm just forgetting. The ones I listed are the most popular and performant 

I definitely welcome a PR to add a databricks llm class too.

I'll also note that we have this `OpenAILike` llm class, that uses the openai client to work with any server that uses the same api interface as openai (which is pretty common)

**Comment by lalehsg** [comment]
Thanks for the info! I keep in mind your notes about dbx addition. I have been able to make Sentence Window Retrieval method run with an llama2 from Replicate for now:

```
llama2_7b_chat = "meta/llama-2-7b-chat:8e6975e5ed6174911a6ff3d60540dfd4844201974602551e10e9e87ab143d81e"
llm = Replicate(
    model=llama2_7b_chat,
    temperature=0.01,
    additional_kwargs={"top_p": 1, "max_new_tokens": 300},
) 

```
however, for some reason Auto-merging retrieval doesn't work and throws ValueError: No API key found for OpenAI in
File /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/llama_index/llms/utils.py:29

tracing back the error, it's happening  in my function:
automerging_index is built successfully, btw.

```
def get_automerging_query_engine(
    automerging_index,
    similarity_top_k=12,
    rerank_top_n=6,
):
    base_retriever = automerging_index.as_retriever(similarity_top_k=similarity_top_k)
    retriever = AutoMergingRetriever(
        base_retriever, automerging_index.storage_context, verbose=True
    )
    rerank = SentenceTransformerRerank(
        top_n=rerank_top_n, model="BAAI/bge-reranker-base"
    )
    auto_merging_engine = RetrieverQueryEngine.from_args(
        retriever, node_postprocessors=[rerank]
    )
    return auto_merging_engine
```


in this line: 
```
auto_merging_engine = RetrieverQueryEngine.from_args(
retriever, node_postprocessors=[rerank]
 )
```

I don't understand while I've passing the llm, it's still looking for credentials of the open ai llm.
I'd appreciate any tips for debugging this.

**Comment by logan-markewich** [comment]
@lalehsg so the retriever query engine is going to do `ServiceContext.from_defaults()` under the hood if you don't pass it in, which means both an OpenAI LLM and embedding model will be initialized

Try setting up the service co text and passing it in as well at that step

**Comment by lalehsg** [comment]
Thanks for the prompt responses and the tip!
