### ISSUE TITLE
[Question]: How do I prompt large language models

### ISSUE THREAD

**Issue by nttng207** [run-llama/llama_index#9872]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have a code for LlamaCpp import by LlamaIndex below: 
import torch
from transformers import BitsAndBytesConfig
from llama_index.prompts import PromptTemplate
from llama_index.callbacks import CallbackManager, LlamaDebugHandler
from llama_index.llms import HuggingFaceLLM
from llama_index.llms.llama_utils import (
    messages_to_prompt,
    completion_to_prompt,
)
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_use_double_quant=True,
)
llama_debug = LlamaDebugHandler(print_trace_on_end=True)
callback_manager = CallbackManager([llama_debug])
model_url = "https://huggingface.co/TheBloke/zephyr-7B-beta-GGUF/resolve/main/zephyr-7b-beta.Q5_K_S.gguf?download=true"

# Change LLMs and see different !!!

llm = LlamaCPP(model_url=model_url, model_path=None,
    temperature=0.1,
    max_new_tokens=256,
    model_kwargs={"n_gpu_layers": 40},
    callback_manager = callback_manager,
    messages_to_prompt=messages_to_prompt,
    completion_to_prompt=completion_to_prompt,
    verbose = True)
output = llm(prompt)
I want prompt llm for legal extract triplet (prompt) but I get the error 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-31-f1cb689d99aa>](https://localhost:8080/#) in <cell line: 1>()
----> 1 output = llm(prompt)

TypeError: 'LlamaCPP' object is not callable

Please help me !!!

**Comment by nttng207** [comment]
@dosu-bot I want to teach the model a specific problem from a prompt I defined, not get the answer

**Comment by nttng207** [comment]
@dosu-bot I want to draw a graph image after getting the index but the image returned is just a blank page, my graph works normally.
from pyvis.network import Network
g = index.get_networkx_graph()
net = Network(notebook=True, cdn_resources="in_line", directed=True)
net.from_nx(g)
net.show("example.html")
from IPython.display import HTML
HTML(filename="example.html")

**Comment by nttng207** [comment]
@dosu-bot There aren't any errors displayed, the code just returns me a blank page

**Comment by logan-markewich** [comment]
I think dosu answered your original message just fine. Going to close this for now.

The answer to the original question is to use `llm.complete()` or `llm.chat()`
