### ISSUE TITLE
[Feature Request]: Amazon Kendra Index

### ISSUE THREAD

**Issue by austinmw** [run-llama/llama_index#9874]
### Feature Description

LangChain has a Kendra retriever, but would be great to have it available in LlamaIndex 

### Reason

Many companies use Kendra for searching relevant documents

### Value of Feature

Kendra has a very large user base

**Comment by hatianzhang** [comment]
yeah Amazon Kendra is not supported yet in llamaindex. would welcome a pr for such integration!

**Comment by thanhtan1105** [comment]
Hello I think AWS Kendra quite more public and should be deep integrate with llamaindex
