### ISSUE TITLE
[Bug]: DatasetGenerator report error

### ISSUE THREAD

**Issue by shijiale0609** [run-llama/llama_index#9877]
### Bug Description

dataset_generator = DatasetGenerator.from_documents(
    documents[:10],
    question_gen_query=question_gen_query,
    service_context=gpt_35_context,
)

error report
/usr/local/lib/python3.10/dist-packages/llama_index/evaluation/dataset_generation.py:184: DeprecationWarning: Call to deprecated class DatasetGenerator. (Deprecated in favor of `RagDatasetGenerator` which should be used instead.)  return cls(

### Version

0.9.26

### Steps to Reproduce

dataset_generator = DatasetGenerator.from_documents(
    documents[:10],
    question_gen_query=question_gen_query,
    service_context=gpt_35_context,
)

**Comment by logan-markewich** [comment]
This isn't an error, just a deprecation warning?

**Comment by shijiale0609** [comment]
from llama_index.llama_dataset.generator import RagDatasetGenerator

dataset_generator = RagDatasetGenerator.from_documents(
    documents,
    service_context=gpt_35_context,
    num_questions_per_chunk=2,  # set the number of questions per nodes
    show_progress=True,
)

rag_dataset = dataset_generator.generate_dataset_from_nodes()


error: RuntimeError                              Traceback (most recent call last)

[<ipython-input-44-e9da1af375e7>](https://localhost:8080/#) in <cell line: 8>()
      6 )
      7 
----> 8 rag_dataset = dataset_generator.generate_dataset_from_nodes()

1 frames

[/usr/lib/python3.10/asyncio/runners.py](https://localhost:8080/#) in run(main, debug)
     31     """
     32     if events._get_running_loop() is not None:
---> 33         raise RuntimeError(
     34             "asyncio.run() cannot be called from a running event loop")
     35 

RuntimeError: asyncio.run() cannot be called from a running event loop

**Comment by logan-markewich** [comment]
Add this to the top of your script. This happens because notebook are already running in an async loop

```
import nest_asyncio
nest_asyncio.apply()
```
