### ISSUE TITLE
[Bug]: RAG (index) + ChatEngine doesn't add context to Cohere LLM calls

### ISSUE THREAD

**Issue by ozozozd** [run-llama/llama_index#9881]
### Bug Description

Trying to use the ChatEngine with Cohere but it fails to add the context to the LLM call.

### Version

0.9.26

### Steps to Reproduce

```import logging
import os
import sys
from dotenv import load_dotenv
from llama_index import (ServiceContext, StorageContext, VectorStoreIndex,
                         load_index_from_storage, set_global_service_context, SimpleDirectoryReader)
from llama_index.llms import Cohere, OpenAI
from llama_index.embeddings import CohereEmbedding
from llama_index.text_splitter import SentenceSplitter

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
logging.getLogger().addHandler(logging.StreamHandler(stream=sys.stdout))
load_dotenv()
# check if storage already exists
PERSIST_DIR = "./storage"

embed_model = CohereEmbedding()
text_splitter = SentenceSplitter(chunk_size=512, chunk_overlap=10)
service_context = ServiceContext.from_defaults(
    embed_model=embed_model, text_splitter=text_splitter, llm=Cohere())
set_global_service_context(service_context)

if os.path.exists(PERSIST_DIR):
    # load index from storage
    storage_context = StorageContext.from_defaults(persist_dir=PERSIST_DIR)
    index = load_index_from_storage(storage_context)
else:
    documents = SimpleDirectoryReader(".").load_data()
    index = VectorStoreIndex.from_documents(documents)
    index.storage_context.persist()
chat_engine = index.as_chat_engine(
    chat_mode="condense_plus_context", verbose=True)
chat_engine.chat_repl()

### Relevant Logs/Tracbacks

_No response_

**Comment by logan-markewich** [comment]
How does it fail to add context? It should be independent of the LLM being used.

This specific chat engine will
- ask the LLM to use the chat history to generate a query to retrieve context
- use that query to retrieve content, insert it into the system prompt
- send the system prompt w/ context + chat history to the LLM to generate a response (here, the LLM can use the retrieved context or general chat history to inform its response)

You can log exactly what is being sent to the LLM using this
https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html#simple-llm-inputs-outputs

**Comment by ozozozd** [comment]
@logan-markewich thanks for sharing the link to help debug. I'll debug further and get back.

**Comment by ozozozd** [comment]
My Python is rusty but I don't think this matches Cohere's /chat endpoint's input JSON schema anymore.
https://github.com/run-llama/llama_index/blob/06b0e390fe1d2fab7c41ff63f6505810c15f8684/llama_index/llms/cohere_utils.py#L111

[Their docs](https://docs.cohere.com/reference/chat) show the following example:
```
{
    "chat_history": [
      {"role": "USER", "message": "Who discovered gravity?"},
      {"role": "CHATBOT", "message": "The man who is widely credited with discovering gravity is Sir Isaac Newton"}
    ],
    "message": "What year was he born?",
    "connectors": [{"id": "web-search"}]
}
```

I will match the new schema, test and get back.

**Comment by ozozozd** [comment]
Matching the new schema didn't fix it.

By testing manually on Cohere's dashboard, I confirmed that the condense prompt doesn't work with the chat mode. It works with the completion model though.

I will try adding a `predict` method to the Cohere LLM class and run the condense prompt through the completion endpoint.
