### ISSUE TITLE
[Question]: How are input args to function calls determined?

### ISSUE THREAD

**Issue by kilimchoi** [run-llama/llama_index#9887]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I was just wondering how input args to function calls are determined. It seems to be picking certain keywords from the user's query arbitrarily. Is there a way to make input args more deterministic?

**Comment by kilimchoi** [comment]
I'm wondering where QueryEngineTool gets the args or kwargs when they're being used in the following context: 

```
query_engine_tools = [
    QueryEngineTool(
        query_engine=query_engine,
        metadata=ToolMetadata(
            name="data",
            description=(
                "Looks up relevant documents from the vector db"
            ),
        ),
    ),
]
chat_engine = ReActAgent.from_tools(
  tools=query_engine_tools,
  llm=llm,
  verbose=True
)
```
Does LLM extract the keywords and send it to `QueryEngineTool`?

**Comment by logan-markewich** [comment]
@kilimchoi The LLM reads the chat history + list of tools names + descriptions, and has to write a tool input based on that. Nothing fancy going on here, just LLM prompting
