### ISSUE TITLE
[Question]: Nodes from PineconeVectorStore is empty. 

### ISSUE THREAD

**Issue by kilimchoi** [run-llama/llama_index#9893]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

First, I load the documents into Pinecone with this code: 
```
PINECONE_INDEX_NAME ="name"
vector_store = PineconeVectorStore(pinecone_index=pinecone.Index(PINECONE_INDEX_NAME))
storage_context = StorageContext.from_defaults(vector_store=vector_store)
documents = SimpleDirectoryReader(data_dir).load_data()
VectorStoreIndex.from_documents(
    documents, storage_context=storage_context
)
```

Then I try to load the load the documents from the same vector store using the code below,
```
index = VectorStoreIndex.from_vector_store(vector_store)
index_nodes = index.docstore.docs
index_nodes <- returns {} 
```

Do you see anything here that cause the vector store to give an empty response?

**Comment by logan-markewich** [comment]
the docstore is disabled by default when using vector db integrations, to simplify storage

you can override this, but then you need to save and manage the docstore too

**Comment by logan-markewich** [comment]
`index = VectorStoreIndex.from_documents(..., store_nodes_override=True)`

**Comment by kilimchoi** [comment]
> the docstore is disabled by default when using vector db integrations, to simplify storage
> 
> you can override this, but then you need to save and manage the docstore too

ok. In that case, is there a way to fetch documents from an external vector store index without having to manage the docstore? Only reason I'm trying to get the documents is because I want to create a dict to pass it to `RecursiveRetriever`

**Comment by logan-markewich** [comment]
only way is to use the vector store API directly (i.e. using pinecone directly), or setting a high top-k and retrieving all the nodes stored

```
retriever = index.as_retriever(similarity_top_k=10000)
source_nodes = retriever.retrieve("fake")
nodes = [x.node for x in source_nodes]
```
