### ISSUE TITLE
[Bug]: ArXiv Reader not working

### ISSUE THREAD

**Issue by ohdearquant** [run-llama/llama_index#9896]
### Bug Description

arxiv is not working

### Version

0.9.25 & 0.9.26

### Steps to Reproduce

just try to download some papers and load it, you probably would encounter similar error 
<img width="1051" alt="image" src="https://github.com/run-llama/llama_index/assets/122793010/2b16ac90-c3a9-4362-ab48-c8d1d85c1f85">

**Comment by ohdearquant** [comment]
I tried the same codes last time, it works fine now, thank you. 

```python
documents, abstracts = loader.load_papers_and_abstracts(
    search_query='Large Language Model Time Series Analysis'
)
```

**Comment by timothyckl** [comment]
> Hi @ohdearquant,
> 
> I tried with the following snippet and it worked fine.
> 
> ```
> from llama_index import download_loader
> 
> ArxivReader = download_loader("ArxivReader")
> 
> loader = ArxivReader()
> documents, abstracts = loader.load_papers_and_abstracts(search_query='au:Karpathy')
> ```

Still getting this error in v0.10.11, ran the code following code:

```python
from llama_index.core import download_loader 

ArxivReader = download_loader("ArxivReader")

loader = ArxivReader()
documents, abstracts = loader.load_papers_and_abstracts(
    papers_dir='./papers', 
    search_query='au:Karpathy'
)
```

Any fixes?

**Comment by ohdearquant** [comment]
> > Hi @ohdearquant,
> > I tried with the following snippet and it worked fine.
> > ```
> > from llama_index import download_loader
> > 
> > ArxivReader = download_loader("ArxivReader")
> > 
> > loader = ArxivReader()
> > documents, abstracts = loader.load_papers_and_abstracts(search_query='au:Karpathy')
> > ```
> 
> Still getting this error in v0.10.11, ran the code following code:
> 
> ```python
> from llama_index.readers.papers import ArxivReader
> 
> loader = ArxivReader()
> documents, abstracts = loader.load_papers_and_abstracts(
>     papers_dir='./papers', 
>     search_query='au:Karpathy'
> )
> ```
> 
> Any fixes?


I will have to try it out myself, but did you pip install the specific package for arXiv_reader? 

the implementation seems alright, lmk I will try it out tomorrow if you still have issues. 

https://github.com/run-llama/llama_index/blob/main/llama-index-integrations/readers/llama-index-readers-papers/llama_index/readers/papers/arxiv/base.py

**Comment by timothyckl** [comment]
Hey @ohdearquant,

Yeah, I installed the reader with `pip install llama-index-readers-papers`.

I thought it had something to do with my system setup, so I tried running it in Colab and still ran into the same errors.

Had to build from source and mess around with the file paths within the class for documents to properly load, but I would rather have a proper solution than have to hack my way to one  😢

**Comment by ohdearquant** [comment]
@timothyckl alright hang tight, I am on it, if it needs changes, I will try to get a PR sometime this weekend.
