### ISSUE TITLE
[Bug]: Subquestion Query Engine is not returning back the Result.

### ISSUE THREAD

**Issue by Deepansharora27** [run-llama/llama_index#9898]
### Bug Description

I have been trying to make use of the SubQuestion Query Engine to perform comparison between two set of Documents. I have setup everything in the Code but the Moment I try to run the Setup, it returns me the Following: 
<img width="1262" alt="Screenshot 2024-01-08 at 1 16 55 PM" src="https://github.com/run-llama/llama_index/assets/43300955/69b5f668-125f-4f29-9ac1-2e4deb90dbf7">

### Version

0.9.25.post1

### Steps to Reproduce

Running the SubQuestion Query Engine and Performing a Comparison between the Two Set Of Documents

**Comment by logan-markewich** [comment]
What llm are you using?

Seems like llama-index was not able to parse the output. This requires a fairly competent llm to produce a structured response that we can parse

**Comment by Deepansharora27** [comment]
> What llm are you using?
> 
> Seems like llama-index was not able to parse the output. This requires a fairly competent llm to produce a structured response that we can parse

@logan-markewich 
I am making use of Llama2 7B Chat Model. 
Any other open source alternatives that can make it work ?

**Comment by logan-markewich** [comment]
Llama2 is notoriously unreliable for structured outputs.

Try using zephyr 7b beta maybe 
https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

**Comment by Deepansharora27** [comment]
> Llama2 is notoriously unreliable for structured outputs.
> 
> Try using zephyr 7b beta maybe https://colab.research.google.com/drive/1UoPcoiA5EOBghxWKWduQhChliMHxla7U?usp=sharing

Would it be Possible to Use replicate the Setup with a GGUF Based Zephyr Model via Lllama-Cpp ?

**Comment by logan-markewich** [comment]
@Deepansharora27 yea it will be fairly similar with llama-cpp. Keep in mind it will be very slow on CPU.

You can translate the colab notebook to llama-cpp, using this example of llama-cpp
https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html#setup-llm

Just have to change
- model_url/model_path
- messages_to_prompt
- completion_to_prompt

**Comment by Deepansharora27** [comment]
@logan-markewich 
I already tried with Zephyr but I am still getting the Same Error No Valid Output in JSON

**Comment by logan-markewich** [comment]
@Deepansharora27 structured outputs are npt reall guaranteed to work in every case right now, especially for open source llms. It's a tough problem especially for small LLMs
