### ISSUE TITLE
[Feature Request]: Parallelism on using top agent from multi document agent while comparing multiple documents

### ISSUE THREAD

**Issue by pansu7** [run-llama/llama_index#9899]
### Feature Description

Currently the same query passed to top agent extracts information from document1 (agent1) and then extracts from document 2 (agent2) sequentially and then at last comparison happens which is why it takes time to respond. Is there any feature to query each document in parallel and compare.

**Comment by logan-markewich** [comment]
I'm not sure what you would like here 🤔 

An agent typically picks one tool at a time, and then calls it, reads the response, and decides what to do next. Its a pretty sequential task in general.

We do have a `ParallelAgentRunner` in our lower level agent API, but I noticed there's no example of using it. This will execute a DAG of tasks concurrently with async
