### ISSUE TITLE
[Feature Request]: Support for local reranker FlashRank or swiftrank

### ISSUE THREAD

**Issue by awilhelm-projects** [run-llama/llama_index#9902]
### Feature Description

Actual only Cohere Rerank and (very slow) LLMRerank is supported by Llama Index. It will be very nice if FlashRank (https://github.com/PrithivirajDamodaran/FlashRank/tree/main) or swiftrank (https://github.com/synacktraa/swiftrank) can be supported by Llama Index.

### Reason

Reranking can boost every RAG Pipeline in quality (https://github.com/PrithivirajDamodaran/FlashRank/blob/main/README.md#references). It can be a quick win for the quality of the vector index.

### Value of Feature

A much better quality of the vector search results. The rerank models are very small.

**Comment by logan-markewich** [comment]
We also support sentence transformers for reranking

https://docs.llamaindex.ai/en/stable/module_guides/querying/node_postprocessors/node_postprocessors.html#sentencetransformerrerank

**Comment by hatianzhang** [comment]
seems a fast/light reranker to add. feel free to make a pr to add. should be straiforward to add

**Comment by awilhelm-projects** [comment]
@logan-markewich Thank you for the hint. I did not find this.
@hatianzhang I will try to add this.

**Comment by strawgate** [comment]
I'm hoping to make a PR for this (or a link to it outside this repo) later this week
