### ISSUE TITLE
[Question]:  I have issues when query with Knowledge Graph 

### ISSUE THREAD

**Issue by nttng207** [run-llama/llama_index#9904]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I have code below: 
storage_graph = StorageContext.from_defaults(persist_dir = '/content/graph_chatbot',graph_store = graph_store)

kg_index = load_index_from_storage(
    storage_context = storage_graph,
    service_context = service_context,
    max_triplets_per_chunk = 10,
    verbose = True
)

kg_query_engine = kg_index.as_query_engine(
    include_text=False,
    response_mode="tree_summarize", #test response !!!
    #embedding_mode="hybrid", #
    similarity_top_k=5,
)

query_str = "According to labor code tell me about DOLISA"
response = kg_query_engine.query(query_str)

when it's generate response, it's take too long I use the index previously saved at '/content/graph_chatbot' created and saved from KnowledgeGraphIndex, when I load_index_from_storage right after getting the index, the query at kg_query_engine = kg_index.as_query_engine(
    include_text=False,
    response_mode="tree_summarize", #test response !!!
    #embedding_mode="hybrid", #
    similarity_top_k=5,
) didn't take that long but after a while when I tried again it took longer to generate the answer, why ????
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
Llama.generate: prefix-match hit
It's still like this

**Comment by logan-markewich** [comment]
LlamaCpp is just pretty slow in general. The more context received and sent to the LLM, the slower it will take.

If I had to guess, it's retrieving quite a lot of text to send to the llm.

You can see what is being sent to the LLM here:
https://docs.llamaindex.ai/en/stable/module_guides/observability/observability.html#simple-llm-inputs-outputs

You can also test and see what is retrieved like this
```
retriever = index.as_retriever(include_text=False, similarity_top_k=5)
nodes = retriever.retrieve("test")
```

**Comment by nttng207** [comment]
@dosu-bot when I use from llama_index.memory import ChatMemoryBuffer

memory = ChatMemoryBuffer.from_defaults(token_limit=1500)
# chat_engine = ReActAgent.from_tools(
#     query_engine_tools, llm=llm, memory=memory, verbose=True
# )

chat_engine = kg_index.as_chat_engine(
    chat_mode="react",
    memory=memory,
    verbose=True,
) it's still take a long time, it's return too much thing,  it stops at llama_decode() for a long time and returns things like " Relationship properties are the following:\n\nThe relationships are the following:\n(:Entity)-[:IS_INTENDED_FOR]->(:Entity),( :Entity)-[:DESIGNED_TO_ORIENT]->(:Entity),(:Entity)-[:DESIGNED_TO_PROVIDE_GOOD_BASIC_UNDERSTANDING_OF]->(:Entity),(:Entity)-[:WRITTEN_BY]->(:Entity),(:Entity )-[:CURRENT_AS_OF]->(:Entity),(:Entity)-[:WAS_WRITTEN_BY]->(:Entity),(:Entity)-[:REFERS_TO_AMOUNTS_IN]->(:Entity),(:Entity)- [:ISTYPEOF]->(:Entity),(:Entity)-[:COVERS]->(:Entity),(:Entity)-[:SPECIFIES_RIGHTS_AND_DUTIES_OF]->(:Entity),(:Entity)-[: IS_A_SOURCE_OF]->(:Entity),(:Entity)-[:SETS_OUT]->(:Entity),(:Entity)-[:HAS_PROVISION]->(:Entity),(:Entity)-..... "
