### ISSUE TITLE
[Bug]: 'NoneType' object is not callable in ./qdrant_client\local\qdrant_local.py, line 73, in close

### ISSUE THREAD

**Issue by pytony17** [run-llama/llama_index#9913]
### Bug Description

Trying to replicate the project at Qdrant Hybrid Search
https://github.com/run-llama/llama_index/blob/main/docs/examples/vector_stores/qdrant_hybrid.ipynb

Specifically, copied all of the code down to and including the Hybrid Queries section.

When running the code, all of the following sections work fine: 
Loading docs
Creating index
Creating vector store
Setting storage and service context
Indexing documents
Create query engine

When the program tries to send query and get response, it errors out when trying to close Qdrant.

### Version

Version: 0.9.26

### Steps to Reproduce

!pip install llama-index qdrant-client pypdf "transformers[torch]"

Copy code from github into app.py below: 

import os
import openai

# Open the file containing the API key
with open('api_key.txt', 'r') as f:
    api_key = f.read().strip()

# Set API keys 
openai.api_key = api_key
os.environ['OPENAI_API_KEY'] = api_key

# Setup our env and load our data
from llama_index import SimpleDirectoryReader

print("Loading docs")
documents = SimpleDirectoryReader("./data/").load_data()

""" Indexing Data """
# Now, we can index our data.
# Hybrid search with Qdrant must be enabled from the beginning
#  -- we can simply set enable_hybrid=True.
# This will run sparse vector generation locally using the "naver/efficient-splade-VI-BT-large-doc" 
# model from Huggingface, in addition to generating dense vectors with OpenAI.

from llama_index import VectorStoreIndex, StorageContext, ServiceContext
from llama_index.vector_stores import QdrantVectorStore
from qdrant_client import QdrantClient

# Create a persistant index to disk
print("Creating index")
client = QdrantClient(path="./qdrant_data")

# Create our vector store with hybrid indexing enabled.
# Batch_size controls how many nodes are encoded with sparse vectors at once.
print("Creating vector store")
vector_store = QdrantVectorStore(
    "sec_10K", client=client, enable_hybrid=True, batch_size=20
)

print("Setting storage and service context")
storage_context = StorageContext.from_defaults(vector_store=vector_store)
service_context = ServiceContext.from_defaults(chunk_size=512)

print("Indexing documents")
index = VectorStoreIndex.from_documents(
    documents,
    storage_context=storage_context,
    service_context=service_context,
)

""" Hybrid Queries """
# When querying with hybrid mode, we can set similarity_top_k and sparse_top_k separately.
# sparse_top_k represents how many nodes will be retrieved from each dense and sparse query. 
# For example, if sparse_top_k=5 is set, that means I will retrieve 5 nodes using sparse vectors 
# and 5 nodes using dense vectors.
# similarity_top_k controls the final number of returned nodes. In the above setting, we end up with 10 nodes. 
# A fusion algorithm is applied to rank and order the nodes from different vector spaces 
# (relative score fusion in this case). similarity_top_k=2 means the top two nodes after fusion are returned.

print("Create query engine")
query_engine = index.as_query_engine(
    similarity_top_k=2, sparse_top_k=12, vector_store_query_mode="hybrid"
)

from IPython.display import display, Markdown

print("Send query and get response")
response = query_engine.query(
    "Who is the CEO of Rogers Corp?"
)

display(Markdown(str(response)))

### Relevant Logs/Tracbacks

```shell
Traceback (most recent call last):
  File "C:\Users\User\Documents\PythonProjects\Qdrant_hybrid\.venv\Lib\site-packages\qdrant_client\qdrant_client.py", line 129, in __del__
  File "C:\Users\User\Documents\PythonProjects\Qdrant_hybrid\.venv\Lib\site-packages\qdrant_client\qdrant_client.py", line 136, in close
  File "C:\Users\User\Documents\PythonProjects\Qdrant_hybrid\.venv\Lib\site-packages\qdrant_client\local\qdrant_local.py", line 73, in close
TypeError: 'NoneType' object is not callable
```

**Comment by logan-markewich** [comment]
@pytony17 this isn't really an error. This happens when the process shuts down, something about qdrant doesn't close quite correctly. But in my experience this is benign. 

All your data is in the vector db, this doesn't interrupt execution, nothing broke, etc.
