### ISSUE TITLE
[Bug]: Loading a DocumentSummaryIndex from a remote WeaviateVectorStore

### ISSUE THREAD

**Issue by wdeaderick** [run-llama/llama_index#9915]
### Bug Description

I've created a `DocumentSummaryIndex` over a `WeaviateVectorStore` as such:
```
documents = ...
client = ...
weaviate_class_name = ...
service_context= ...

vector_store = WeaviateVectorStore(weaviate_client=client, index_name=weaviate_class_name)
storage_context = StorageContext.from_defaults(vector_store=vector_store)
index = DocumentSummaryIndex.from_documents(
    documents,
    service_context=service_context,
    storage_context=storage_context,
)
```
and all is working fine (I can see document summaries, query the query engine, etc.). However, I cannot seem to subsequently load this index. When using `VectorStoreIndex`, all I had to do was `index = VectorStoreIndex.from_vector_store(vector_store, service_context=service_context)`, but `DocumentSummaryIndex` has no such method. I've tried `index = load_index_from_storage(storage_context=storage_context, service_context=service_context)` but am met with `llama_index/indices/loading.py:36 in load_index_from_storage: ValueError: No index in storage context, check if you specified the right persist_dir`. Upon my own inspection, I see that `storage_context.index_store.index_structs()` is just an empty list. I also tried `index = DocumentSummaryIndex(nodes=[], storage_context=storage_context, service_context=service_context)`, but none of my previously saved documents/nodes are present in the loaded index.

Is there something I need to be doing with `DocumentSummaryIndex` that I didn't have to do with `VectorStoreIndex` to persist the index to Weaviate? Or am I just loading it incorrectly, or does one of `WeaviateVectorStore` or `DocumentSummaryIndex` not support this?

### Version

0.9.27

### Steps to Reproduce

See above description

**Comment by logan-markewich** [comment]
Did we solve this bug? https://github.com/run-llama/llama_index/issues/9850

Are you sure you have the latest version installed?

**Comment by wdeaderick** [comment]
@logan-markewich That fix had to do with using the index for retrieval/querying. I have the latest version installed and retrieval/querying is working fine thanks to that fix. Separate from that, I'm struggling to load the index.

**Comment by wdeaderick** [comment]
The only examples I can find in the docs for loading non-`VectorStoreIndex` indexes all use local storage/`.persist()`.

**Comment by logan-markewich** [comment]
whoops lol jumped to conclusions there.

Did you follow this set of steps? https://github.com/run-llama/llama_index/issues/9850#issuecomment-1878042256

Specially, this one is key when loading

```python
doc_summary_index.storage_context.persist(persist_dir="./index")

from llama_index.indices.loading import load_index_from_storage
from llama_index import StorageContext

# rebuild storage context
storage_context = StorageContext.from_defaults(persist_dir="./index", vector_store=vector_store)
doc_summary_index = load_index_from_storage(storage_context)
```

**Comment by wdeaderick** [comment]
Ah okay yes, that seems to work! Reading [this page](https://docs.llamaindex.ai/en/stable/module_guides/storing/save_load.html) ("User can also configure alternative storage backends (e.g. MongoDB) that persist data by default. In this case, calling storage_context.persist() will do nothing."), together with the fact that I didn't need to call `.persist()` when using `VectorStoreIndex`, led me to believe that I wouldn't need to do so with `DocumentSummaryIndex` either. So who's really the one jumping to conclusions...

**Comment by wdeaderick** [comment]
@logan-markewich Wait, just kidding; using `doc_summary_index.storage_context.persist(persist_dir="./index")` leads to the index being persisted locally (I now see an `index` directory on my local with all the `*_store.json` files) rather than remotely to Weaviate. Double-checked this with a unique `persist_dir` name to be sure that the local dir was indeed from this experiment. So even with a `storage_context` built on my remote `WeaviateVectorStore`, calling `.persist()` seems to write locally.

**Comment by logan-markewich** [comment]
@wdeaderick the doc summary index needs to save the docstore and index store in order to function. It cannot save everything in weaviate.

If local storage isn't an option, there are a few integrations for remote docstores/index stores (redis, mongodb, firestore)

**Comment by wdeaderick** [comment]
Ah. Yeah, local storage won't work in our case. Can you point me to any docs for those integrations?

**Comment by wdeaderick** [comment]
@logan-markewich ^ In particular, if DynamoDB is an option

**Comment by wdeaderick** [comment]
@logan-markewich sorry to bug you but could use a pointer here :)

**Comment by logan-markewich** [comment]
@wdeaderick yea I think docs are little sparse, might need to use some IDE hints to help with the init 

There's a dynamodb docstore here
https://github.com/run-llama/llama_index/blob/22b4c576685d44c9233eeddf1f5410bd93734a16/llama_index/storage/docstore/dynamodb_docstore.py#L8

Just have to instantiate it, attach it to the storage context `StorageContext.from_defaults(docstore=docstore, vector_store)` and you should be good to go I think

**Comment by wdeaderick** [comment]
Amazing, thank you!

**Comment by wdeaderick** [comment]
@logan-markewich The `DynamoDBDocumentStore` expects an already-created DDB table whose schema I can't find described anywhere. I've tried a couple different schemas but am hitting `Type mismatch for key` in `self._kvstore.put(doc_id, metadata, collection=self._metadata_collection)`.  cc @Disiok, the author of https://github.com/run-llama/llama_index/blob/main/docs/examples/docstore/DynamoDBDocstoreDemo.ipynb, would be great if you could help me understand what this DDB table needs to look like.
