### ISSUE TITLE
[Bug]: Milvus index is dropped and recreated, even when merely connecting to an existing collection

### ISSUE THREAD

**Issue by bbouldin** [run-llama/llama_index#9930]
### Bug Description

The index of a Milvus collection is now always dropped and recreated, even when merely connecting to an existing collection.

### Version

0.9.27

### Steps to Reproduce

Just using the constructor causes this issue. For example:

my_store = MilvusVectorStore(
        overwrite=False,
        uri=my_milvus_uri,
        similarity_metric=my_metric_type,
        collection_name=my_collection,
    )

I believe that the issue is due to this code in the constructor, which is using `force=True`. 
https://github.com/run-llama/llama_index/blob/06b0e390fe1d2fab7c41ff63f6505810c15f8684/llama_index/vector_stores/milvus.py#L164C46-L164C50
It causes the index to get dropped & recreated in all cases. (Perhaps this line should be moved to the 'if' block above it?)

**Comment by logan-markewich** [comment]
@bbouldin why.... is force=True on that line 😓 wild
