### ISSUE TITLE
[Bug]: cannot import name 'VectorStoreIndex' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)

### ISSUE THREAD

**Issue by Lavinia989** [run-llama/llama_index#9948]
### Bug Description

While running from llama_index import VectorStoreIndex, StorageContext, i got this error  cannot import name 'VectorStoreIndex' from 'llama_index' (/usr/local/lib/python3.10/dist-packages/llama_index/__init__.py)

### Version

0.9.28.post1

### Steps to Reproduce

i have no idea how to answer this question

**Comment by logan-markewich** [comment]
Are you running a notebook? try restarting it. Also using a venv is usually helpful. This is mostly an env issue

**Comment by Ravitejarao333** [comment]
llama index has updated their modules recently .
There are 2 working solutions : 
1) Delete new version of llama index and install older version  
```
!pip uninstall llama_index
  !pip install llama_index==0.9.40

```
2) Import from correct location 
`from llama_index.core import VectorStoreIndex`
