### ISSUE TITLE
[Question]: implementing llama_index in my RAG system 

### ISSUE THREAD

**Issue by samyog-fuse** [run-llama/llama_index#9959]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I am trying to test the auto merge with llama_index in my RAG system. For this i have created couple of python files which gets input from command lines. I run these python scripts from my nodejs application.
Here i have two files 
1. doc-loader-llama-index.py
2. retriever-merged-chunks-llama-index.py

first file loads the pdf's text create nodes, add  nodes in to doc store(mongodb), child nodes into vector store (pinecone). I added multiple documents by calling this file each times. I have around 43 documents added. I can see i have child nodes added into pinecone. I can also see 4 collections being created in mongodb ( 'docstore/data', 'docstore/metadata', 'docstore/ref_doc_info', 'index_store/data') 

second file is to retreive the chunks/nodes with auto merge. This is where I am getting a error. The error message is as below:
----------
Error: Command failed: python3 /home/fm-pc-lt-214/proj/qdabra/doc-gpt/py-libs/retriever-merged-chunks-llama-index.py "MY OPENAI APIKEY" "MY PINECONE APIKEY" "MY PINECONE INDEX" "MY PINECONE ENVIRONMENT" "What references are cited in the Creating True Copies Standard Operating Procedure?" "5"
Traceback (most recent call last):
  File "/home/fm-pc-lt-214/proj/qdabra/doc-gpt/py-libs/retriever-merged-chunks-llama-index.py", line 71, in <module>
    autoMergeIndex = load_index_from_storage(
  File "/home/fm-pc-lt-214/proj/qdabra/doc-gpt/py-libs/venv/lib/python3.8/site-packages/llama_index/indices/loading.py", line 40, in load_index_from_storage
    raise ValueError(
ValueError: Expected to load a single index, but got 43 instead. Please specify index_id.
-------------
PS. I have replaced acutal apikeys with text here.

I am not sure why i am getting this error. 
Is it not possible to add multiple documents and make query with automerge ?

I have attached these files here.
[doc-loader-llama-index.txt](https://github.com/run-llama/llama_index/files/13888782/doc-loader-llama-index.txt)
[retriever-merged-chunks-llama-index.txt](https://github.com/run-llama/llama_index/files/13888784/retriever-merged-chunks-llama-index.txt)

any help would be appreciated. thanks.

**Comment by samyog-fuse** [comment]
@dosu-bot 
when i make query i dont have index_id info.

**Comment by logan-markewich** [comment]
@samyog-fuse can you share some code for your setup? It seems like you made 43 indexes?

**Comment by samyog-fuse** [comment]
@logan-markewich  yes i can see there are 43 index in mongodb collection index_store/data
I have only one index in pinecone which i have named 'auto-merge-test'

Below is the code that would be called from node backend whenever a pdf is uploaded , required parameters are sent from nodejs app.

# load_pdf_add_index.py

import os
import sys
from pathlib import Path
import json

# assign input values to variables
OPENAI_APIKEY = sys.argv[1]
PINECONE_APIKEY = sys.argv[2]
PINECONE_INDEX = sys.argv[3]
PINECONE_ENVIRONMENT = sys.argv[4]
documentId = sys.argv[5]
documentPath = sys.argv[6]
documentName = sys.argv[7]

# set openai api key
os.environ["OPENAI_API_KEY"] = OPENAI_APIKEY


from llama_index import download_loader
from llama_index.node_parser import HierarchicalNodeParser, get_leaf_nodes
from llama_index import StorageContext, ServiceContext
from llama_index import VectorStoreIndex
from llama_index.storage.docstore import MongoDocumentStore
from llama_index.storage.index_store import MongoIndexStore
from llama_index.vector_stores import PineconeVectorStore
from llama_index.llms import OpenAI 

import pinecone

# set up pinecone
pinecone.init(api_key=PINECONE_APIKEY, environment=PINECONE_ENVIRONMENT)
pinecone_index = pinecone.Index(PINECONE_INDEX)


# define vector store
vectorStore = PineconeVectorStore(
    pinecone_index=pinecone_index
)

mongodbUrl = "mongodb://localhost:27017"

docStore = MongoDocumentStore.from_uri(uri=mongodbUrl, db_name="doc-gpt-auto-merge")
indexStore = MongoIndexStore.from_uri(uri=mongodbUrl, db_name="doc-gpt-auto-merge")

# define storage context
storageContext = StorageContext.from_defaults(
    docstore=docStore,
    vector_store=vectorStore,
    index_store=indexStore
)

mergingContext = ServiceContext.from_defaults(
    llm=OpenAI(model="gpt-4", temperature=0.1)
)

# load document
PDFReader = download_loader("PDFReader")
loader = PDFReader()
documents = loader.load_data(file=Path(documentPath, documentName))
# documents = loader.load_data(file=Path('sample-doc.pdf'))

# parse document into nodes
node_parser = HierarchicalNodeParser.from_defaults([2048, 512, 128])

nodes = node_parser.get_nodes_from_documents(documents)

# add meta information in metatadata of each nodes
for node in nodes:
    node.metadata['document_id'] =  documentId
    node.metadata['source_document_id'] = documentId
    node.metadata['source'] = documentName
    node.metadata['type'] = 'document-chunk'

# get leaf nodes
leaf_nodes = get_leaf_nodes(nodes)
# add all nodes to storage context / doc store
storageContext.docstore.add_documents(nodes, True)
# add leaf nodes to vector store
VectorStoreIndex(
        leaf_nodes,
        storage_context=storageContext,
        service_context=mergingContext
)
leaf_nodes_dict = []
for node in leaf_nodes:
    node = vars(node)
    leaf_nodes_dict.append({
        'id': node['id_']
    })

print(json.dumps(leaf_nodes_dict))

-------------------------------------

I have another python script for retrieval which as below

# retrieve nodes/chunks
import os
import json
import sys

# assign input values to variables

OPENAI_APIKEY = sys.argv[1]
PINECONE_APIKEY = sys.argv[2]
PINECONE_INDEX = sys.argv[3]
PINECONE_ENVIRONMENT = sys.argv[4]
query = sys.argv[5]
topK = sys.argv[6]

# set openai api key
os.environ["OPENAI_API_KEY"] = OPENAI_APIKEY

from llama_index import StorageContext, ServiceContext, load_index_from_storage
from llama_index.retrievers import AutoMergingRetriever

from llama_index.storage.docstore import MongoDocumentStore
from llama_index.storage.index_store import MongoIndexStore
from llama_index.vector_stores import PineconeVectorStore

from llama_index.indices.postprocessor import SentenceTransformerRerank
from llama_index.query_engine import RetrieverQueryEngine

from llama_index.vector_stores.types import (
    MetadataFilter,
    MetadataFilters,
    FilterOperator,
)

from llama_index.llms import OpenAI 

import pinecone


# set up pinecone
pinecone.init(api_key=PINECONE_APIKEY, environment=PINECONE_ENVIRONMENT)
pinecone_index = pinecone.Index(PINECONE_INDEX)


# define vector store
vectorStore = PineconeVectorStore(
    pinecone_index=pinecone_index
)

mongodbUrl = "mongodb://localhost:27017"

docStore = MongoDocumentStore.from_uri(uri=mongodbUrl, db_name="doc-gpt-auto-merge")
indexStore = MongoIndexStore.from_uri(uri=mongodbUrl, db_name="doc-gpt-auto-merge")

# define storage context
storageContext = StorageContext.from_defaults(
    docstore=docStore,
    vector_store=vectorStore,
    index_store=indexStore,
)

mergingContext = ServiceContext.from_defaults(
    llm=OpenAI(model="gpt-4", temperature=0.1)
)

filter = MetadataFilters(
    filters=[
        MetadataFilter(key="type", operator=FilterOperator.EQ, value="document-chunk")
    ]
)


autoMergeIndex = load_index_from_storage(
        storage_context=storageContext,
)

baseRetriever = autoMergeIndex.as_retriever(similarity_top_k=5, filters=filter)

retriever = AutoMergingRetriever(
    baseRetriever,
    autoMergeIndex.storage_context
)

rerank = SentenceTransformerRerank(
    top_n=  int(topK) if(topK) else 5 
)

auto_merging_engine = RetrieverQueryEngine.from_args(
    retriever,
    node_postprocessors=[rerank],

)
# print(query)
retrieved_nodes = auto_merging_engine.retriever.retrieve(query)
nodes = []
for retreived_node in retrieved_nodes:
    # print(node)
    data = vars(retreived_node)
    node = vars(data['node'])
    # print(data.keys())
    # print(node.keys())
    score = data['score']
    node_dict = {
        'id': node['id_'],
        'text': node['text'],
        'metadata': node['metadata'],
        'score': score
    }
    nodes.append(node_dict)

data = json.dumps(nodes)
print(data)
