### ISSUE TITLE
[Question]: RuntimeError: asyncio.run() cannot be called from a running event loop

### ISSUE THREAD

**Issue by rishabhgupta93** [run-llama/llama_index#9978]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Hi,

I am trying to run pipeline for as mentioned in following llamaindex documentation:

https://docs.llamaindex.ai/en/stable/module_guides/loading/documents_and_nodes/usage_metadata_extractor.html 

But when i am trying to execute this code in my environment i am getting following error:

File C:\Program Files\Python39\lib\asyncio\runners.py:33, in run(main, debug)
      _9 """Execute the coroutine and return the result.
     10 
     11 This function runs the passed coroutine, taking care of
   (...)
     30     asyncio.run(main())
     31 """
     32 if events._get_running_loop() is not None:
---> 33     raise RuntimeError(
     34         "asyncio.run() cannot be called from a running event loop")
     36 if not coroutines.iscoroutine(main):
     37     raise ValueError("a coroutine was expected, got {!r}".format(main))

RuntimeError: asyncio.run() cannot be called from a running event loop_

**Comment by rishabhgupta93** [comment]
this doesnt solve the problem/

below is the code snippet i am trying to run:

_from llama_index.extractors import (TitleExtractor, QuestionsAnsweredExtractor)
from llama_index.text_splitter import TokenTextSplitter

text_splitter = TokenTextSplitter(separator=" ", chunk_size=512, chunk_overlap=128)
title_extractor = TitleExtractor(nodes=5, llm=llm)
qa_extractor = QuestionsAnsweredExtractor(questions=3, llm=llm)

from llama_index.ingestion import IngestionPipeline

pipeline = IngestionPipeline(transformations=[text_splitter, title_extractor, qa_extractor])

nodes = pipeline.run(documents=documents[0], in_place=False, show_progress=True)_

and i am getting following error:

---------------------------------------------------------------------------
_RuntimeError                              Traceback (most recent call last)
Cell In[37], line 12
      8 from llama_index.ingestion import IngestionPipeline
     10 pipeline = IngestionPipeline(transformations=[text_splitter, title_extractor, qa_extractor])
---> 12 nodes = pipeline.run(documents=documents[0], in_place=False, show_progress=True)

File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\ingestion\pipeline.py:365, in IngestionPipeline.run(self, show_progress, documents, nodes, cache_collection, in_place, **kwargs)
    362 else:
    363     nodes_to_run = input_nodes
--> 365 nodes = run_transformations(
    366     nodes_to_run,
    367     self.transformations,
    368     show_progress=show_progress,
    369     cache=self.cache if not self.disable_cache else None,
    370     cache_collection=cache_collection,
    371     in_place=in_place,
    372     **kwargs,
    373 )
    375 if self.vector_store is not None:
    376     self.vector_store.add([n for n in nodes if n.embedding is not None])

File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\ingestion\pipeline.py:74, in run_transformations(nodes, transformations, in_place, cache, cache_collection, **kwargs)
     72         nodes = cached_nodes
     73     else:
---> 74         nodes = transform(nodes, **kwargs)
     75         cache.put(hash, nodes, collection=cache_collection)
     76 else:

File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\extractors\interface.py:155, in BaseExtractor.__call__(self, nodes, **kwargs)
    147 def __call__(self, nodes: List[BaseNode], **kwargs: Any) -> List[BaseNode]:
    148     """Post process nodes parsed from documents.
    149 
    150     Allows extractors to be chained.
   (...)
    153         nodes (List[BaseNode]): nodes to post-process
    154     """
--> 155     return self.process_nodes(nodes, **kwargs)

File f:\pycharmprojects\llamaindex\venv\lib\site-packages\llama_index\extractors\interface.py:138, in BaseExtractor.process_nodes(self, nodes, excluded_embed_metadata_keys, excluded_llm_metadata_keys, **kwargs)
    131 def process_nodes(
    132     self,
    133     nodes: List[BaseNode],
   (...)
    136     **kwargs: Any,
    137 ) -> List[BaseNode]:
--> 138     return asyncio.run(
    139         self.aprocess_nodes(
    140             nodes,
    141             excluded_embed_metadata_keys=excluded_embed_metadata_keys,
    142             excluded_llm_metadata_keys=excluded_llm_metadata_keys,
    143             **kwargs,
    144         )
    145     )

File C:\Program Files\Python39\lib\asyncio\runners.py:33, in run(main, debug)
      9 """Execute the coroutine and return the result.
     10 
     11 This function runs the passed coroutine, taking care of
   (...)
     30     asyncio.run(main())
     31 """
     32 if events._get_running_loop() is not None:
---> 33     raise RuntimeError(
     34         "asyncio.run() cannot be called from a running event loop")
     36 if not coroutines.iscoroutine(main):
     37     raise ValueError("a coroutine was expected, got {!r}".format(main))

RuntimeError: asyncio.run() cannot be called from a running event loop_

**Comment by rishabhgupta93** [comment]
Thanks for the response, Where should I call this function?

**Comment by logan-markewich** [comment]
@rishabhgupta93  likely just at the start of your script or notebook

**Comment by rohan-patankar** [comment]
> I'm not sure what the bot was going on about, but, all you needed was nest_asyncio
> 
> ```
> import nest_asyncio 
> nest_asyncio.apply()
> ```

@logan-markewich This works with colab implementation but when i create resapi endpoint with fastapi it throws errors.

**Comment by logan-markewich** [comment]
@rohan-patankar in fastapi, you have to change the loop type to Asyncio

`uvicorn.run(..., loop="asyncio")`

**Comment by peterdays** [comment]
This didn't work for me :/

> @rohan-patankar in fastapi, you have to change the loop type to Asyncio
> 
> `uvicorn.run(..., loop="asyncio")`

**Comment by thomastiotto** [comment]
I'm facing a similar issue using `DocumentSummaryIndex.from_documents()`.  After some time it's running it throws

```Summarizing documents:  69%|██████▉   | 25/36 [01:45<00:46,  4.22s/it]
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 31, in asyncio_run
    raise RuntimeError(
RuntimeError: Nested async detected. Use async functions where possible (`aquery`, `aretrieve`, `arun`, etc.). Otherwise, use `import nest_asyncio; nest_asyncio.apply()` to enable nested async or use in a jupyter notebook.
If you are experiencing while using async functions and not in a notebook, please raise an issue on github, as it indicates a bad design pattern.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/PycharmProjects/aba-report-magic/aba_report_magic/app/routes/building_blocks/sandbox/report_search.py", line 104, in report_search
    return execute_report_search(query)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/thomas/PycharmProjects/aba-report-magic/aba_report_magic/app/routes/building_blocks/sandbox/report_search.py", line 81, in execute_report_search
    index = DocumentSummaryIndex.from_documents(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 145, in from_documents
    return cls(
           ^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/document_summary/base.py", line 107, in __init__
    super().__init__(
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 94, in __init__
    index_struct = self.build_index_from_nodes(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/base.py", line 212, in build_index_from_nodes
    return self._build_index_from_nodes(nodes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/document_summary/base.py", line 240, in _build_index_from_nodes
    self._add_nodes_to_index(index_struct, nodes, self._show_progress)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/indices/document_summary/base.py", line 198, in _add_nodes_to_index
    summary_response = self._response_synthesizer.synthesize(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/response_synthesizers/base.py", line 241, in synthesize
    response_str = self.get_response(
                   ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/instrumentation/dispatcher.py", line 230, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/response_synthesizers/tree_summarize.py", line 207, in get_response
    summary_responses = run_async_tasks(tasks)
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 76, in run_async_tasks
    outputs: List[Any] = asyncio_run(_gather())
                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/llama_index/core/async_utils.py", line 42, in asyncio_run
    return asyncio.run(coro)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/asyncio/runners.py", line 186, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py:-1: RuntimeWarning: coroutine 'run_async_tasks.<locals>._gather' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/opt/homebrew/Caskroom/miniforge/base/envs/aba-report-magic/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py:-1: RuntimeWarning: coroutine 'Dispatcher.span.<locals>.async_wrapper' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback```

**Comment by denieboy** [comment]
I am having the same issue in VSCode running example as juypter notebook.

```
site-packages\llama_index\core\async_utils.py:47, in asyncio_run(coro)
     [40](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:40)         raise RuntimeError(
     [41](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:41)             "Detected nested async. Please use nest_asyncio.apply() to allow nested event loops."
     [42](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:42)             "Or, use async entry methods like `aquery()`, `aretriever`, `achat`, etc."
     [43](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:43)         )
     [45](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:45) except Exception as e:
     [46](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:46)     # Catch any other exceptions and re-raise with more context
---> [47](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:47)     raise type(e)(f"Error running coroutine: {e!s}") from e

ValueError: Error running coroutine: too many values to unpack (expected 2)
```

When running example from here:
[https://docs.llamaindex.ai/en/stable/examples/metadata_extraction/EntityExtractionClimate/](url)

SW vers:
Transformers version: 4.43.0.dev0
Llama_index version: 0.10.52.post1

**Comment by ScharanCysne** [comment]
> I am having the same issue in VSCode running example as juypter notebook.
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\llama_index\core\async_utils.py:33, in asyncio_run(coro)
>      [32](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:32)     # If we're here, there's an existing loop but it's not running
> ---> [33](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:33)     return loop.run_until_complete(coro)
>      [35](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:35) except RuntimeError as e:
>      [36](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/async_utils.py:36)     # If we can't get the event loop, we're likely in a different thread, or its already running
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\nest_asyncio.py:98, in _patch_loop.<locals>.run_until_complete(self, future)
>      [96](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/nest_asyncio.py:96)     raise RuntimeError(
>      [97](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/nest_asyncio.py:97)         'Event loop stopped before Future completed.')
> ---> [98](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/nest_asyncio.py:98) return f.result()
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\asyncio\futures.py:203, in Future.result(self)
>     [202](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/futures.py:202) if self._exception is not None:
> --> [203](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/futures.py:203)     raise self._exception.with_traceback(self._exception_tb)
>     [204](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/futures.py:204) return self._result
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\asyncio\tasks.py:277, in Task.__step(***failed resolving arguments***)
>     [274](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/tasks.py:274) if exc is None:
>     [275](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/tasks.py:275)     # We use the `send` method directly, because coroutines
>     [276](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/tasks.py:276)     # don't have `__iter__` and `__next__` methods.
> --> [277](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/tasks.py:277)     result = coro.send(None)
>     [278](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/asyncio/tasks.py:278) else:
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\llama_index\core\extractors\interface.py:120, in BaseExtractor.aprocess_nodes(self, nodes, excluded_embed_metadata_keys, excluded_llm_metadata_keys, **kwargs)
>     [118](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/extractors/interface.py:118)     new_nodes = [deepcopy(node) for node in nodes]
> --> [120](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/extractors/interface.py:120) cur_metadata_list = await self.aextract(new_nodes)
>     [121](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/extractors/interface.py:121) for idx, node in enumerate(new_nodes):
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\llama_index\core\instrumentation\dispatcher.py:255, in Dispatcher.span.<locals>.async_wrapper(func, instance, args, kwargs)
>     [254](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/instrumentation/dispatcher.py:254) try:
> --> [255](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/instrumentation/dispatcher.py:255)     result = await func(*args, **kwargs)
>     [256](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/core/instrumentation/dispatcher.py:256) except BaseException as e:
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\llama_index\extractors\entity\base.py:136, in EntityExtractor.aextract(self, nodes)
>     [135](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/extractors/entity/base.py:135) words = self._tokenizer(node_text)
> --> [136](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/extractors/entity/base.py:136) spans = self._model.predict(words)
>     [137](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/llama_index/extractors/entity/base.py:137) for span in spans:
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\span_marker\modeling.py:512, in SpanMarkerModel.predict(self, inputs, batch_size, show_progress_bar)
>     [511](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:511) with torch.no_grad():
> --> [512](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:512)     output = self(**batch)
>     [513](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:513) # Computing probabilities based on the logits
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\torch\nn\modules\module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
>    [1531](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1531) else:
> -> [1532](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1532)     return self._call_impl(*args, **kwargs)
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\torch\nn\modules\module.py:1541, in Module._call_impl(self, *args, **kwargs)
>    [1538](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1538) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>    [1539](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1539)         or _global_backward_pre_hooks or _global_backward_hooks
>    [1540](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1540)         or _global_forward_hooks or _global_forward_pre_hooks):
> -> [1541](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1541)     return forward_call(*args, **kwargs)
>    [1543](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1543) try:
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\span_marker\modeling.py:153, in SpanMarkerModel.forward(self, input_ids, attention_mask, position_ids, start_marker_indices, num_marker_pairs, labels, num_words, document_ids, sentence_ids, **kwargs)
>     [152](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:152) token_type_ids = torch.zeros_like(input_ids)
> --> [153](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:153) outputs = self.encoder(
>     [154](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:154)     input_ids,
>     [155](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:155)     attention_mask=attention_mask,
>     [156](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:156)     token_type_ids=token_type_ids,
>     [157](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:157)     position_ids=position_ids,
>     [158](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:158) )
>     [159](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/span_marker/modeling.py:159) last_hidden_state = outputs[0]
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\torch\nn\modules\module.py:1532, in Module._wrapped_call_impl(self, *args, **kwargs)
>    [1531](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1531) else:
> -> [1532](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1532)     return self._call_impl(*args, **kwargs)
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\torch\nn\modules\module.py:1541, in Module._call_impl(self, *args, **kwargs)
>    [1538](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1538) if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
>    [1539](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1539)         or _global_backward_pre_hooks or _global_backward_hooks
>    [1540](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1540)         or _global_forward_hooks or _global_forward_pre_hooks):
> -> [1541](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1541)     return forward_call(*args, **kwargs)
>    [1543](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/torch/nn/modules/module.py:1543) try:
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\transformers\models\bert\modeling_bert.py:1107, in BertModel.forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, past_key_values, use_cache, output_attentions, output_hidden_states, return_dict)
>    [1106](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1106)     else:
> -> [1107](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1107)         extended_attention_mask = _prepare_4d_attention_mask_for_sdpa(
>    [1108](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1108)             attention_mask, embedding_output.dtype, tgt_len=seq_length
>    [1109](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1109)         )
>    [1110](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1110) else:
>    [1111](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1111)     # We can provide a self-attention mask of dimensions [batch_size, from_seq_length, to_seq_length]
>    [1112](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/models/bert/modeling_bert.py:1112)     # ourselves in which case we just need to make it broadcastable to all heads.
> 
> File c:\Users\Danike\miniconda3\envs\groq\Lib\site-packages\transformers\modeling_attn_mask_utils.py:439, in _prepare_4d_attention_mask_for_sdpa(mask, dtype, tgt_len)
>     [427](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:427) """
>     [428](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:428) Creates a non-causal 4D mask of shape `(batch_size, 1, query_length, key_value_length)` from a 2D mask of shape
>     [429](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:429) `(batch_size, key_value_length)`
>    (...)
>     [437](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:437)         The target length or query length the created mask shall have.
>     [438](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:438) """
> --> [439](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:439) _, key_value_length = mask.shape
>     [440](file:///C:/Users/Danike/miniconda3/envs/groq/Lib/site-packages/transformers/modeling_attn_mask_utils.py:440) tgt_len = tgt_len if tgt_len is not None else key_value_length
> 
> ValueError: too many values to unpack (expected 2)
> ```
> 
> When running example from here: [https://docs.llamaindex.ai/en/stable/examples/metadata_extraction/EntityExtractionClimate/](url)
> 
> SW vers: Transformers version: 4.43.0.dev0 Llama_index version: 0.10.52.post1

same here

**Comment by denieboy** [comment]
So I guess that is an active issues, code snipet shall be updated. 🙂

**Comment by nazim-ashman-oc** [comment]
I am still facing this issue too. Can't seem to get SubQuestionQueryEngine in async mode working when using FastAPI.

Tried 
```
import nest_asyncio 
nest_asyncio.apply()
```
And also tried that with 
`uvicorn.run(..., loop="asyncio")`

**Comment by mothguib** [comment]
I face the same issue when creating the Property Graph Index with the following command:

```
index = PropertyGraphIndex.from_documents(documents)
```

**Comment by rohanpatankar926** [comment]
in the main file of the code write this code
```import nest_asyncio
nest_asyncio.apply()```

and while running the application use this command

`uvicorn path_of_file:fastapi_obj_name --loop asyncio` 

example:
`uvicorn main:app --loop asyncio`

**Comment by mothguib** [comment]
I installed `fastapi` and `uvicorn` in my Anaconda environment, then I created script `main.py`:

```
# main.py
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "World"}

```

And ran:

```
uvicorn main:app --loop asyncio
```

Now it works. Thank you @rohanpatankar926 !

**Comment by serozhenka** [comment]
Whoever is maintaining this repo just doesn't care about normal asynchrony support through the whole code base.
Luckily, I found the solution for everyone using the `use_async` parameter anywhere. Just use `asyncio.to_thread`.
```python
index = await asyncio.to_thread(
    VectorStoreIndex.from_documents,
    documents=documents,
    embed_model=embed_model,
    use_async=True,
)
```

**Comment by pythononwheels** [comment]
> I'm not sure what the bot was going on about, but, all you needed was nest_asyncio
> 
> ```
> import nest_asyncio 
> nest_asyncio.apply()
> ```

this should be at least added to the documentation and in the notebook.
I was running into this today, as well. which is annoying if you try to follow the docs.
