### ISSUE TITLE
[Question]: Does OpenAIAssistantAgent supports streaming the response?

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#9981]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

Does OpenAIAssistantAgent supports streaming the response? If yes, how to config it?

**Comment by justinzyw** [comment]
@dosu-bot.  thanks. gave a try and an error popped up:  raise NotImplementedError("stream_chat not implemented") . What can I do to resolve it?

**Comment by justinzyw** [comment]
sorry the answer does not make sense to me. Could you please let me know how to ensure the method is implemented?

**Comment by justinzyw** [comment]
@dosu-bot. correct me if I am wrong. by reading https://github.com/run-llama/llama_index/blob/206624c3b19e407469fb64fd2a5222abdde4a519/llama_index/agent/openai_assistant_agent.py#L4, I guess stream_chat is not implemented yet. Am I right? Is there a plan for it please?

**Comment by logan-markewich** [comment]
@justinzyw openai does not support streaming responses on the openai assistants api yet, so we cannot implement it
https://community.openai.com/t/stream-assistant-response/476300/9
