### ISSUE TITLE
[Question]: how to feed the parm chat_history of OpenAIAssistantAgent.chat()

### ISSUE THREAD

**Issue by justinzyw** [run-llama/llama_index#9984]
### Question Validation

- [X] I have searched both the documentation and discord for an answer.

### Question

I get the list of chat history in the form as folllowing: [[user input 1, bot response 1], [user input 2, bot response 2]]. how can I feed this chat history data to the parm chat_history of OpenAIAssistantAgent.chat()?

**Comment by justinzyw** [comment]
it does not seem to be working for me.
![image](https://github.com/run-llama/llama_index/assets/2166237/9832e009-384f-4c01-97bd-3ea5716e0dda)

the history I converted is as below:
[
ChatMessage(role=<MessageRole.USER: 'user'>, content='please use Joe as your name', additional_kwargs={}), 
ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content="Sure, I'll use the name Joe for our conversation. How can I assist you today?", additional_kwargs={}), 
ChatMessage(role=<MessageRole.USER: 'user'>, content='hi Joe', additional_kwargs={}), 
ChatMessage(role=<MessageRole.ASSISTANT: 'assistant'>, content='Hello! How can I assist you today?', additional_kwargs={})
]

**Comment by justinzyw** [comment]
@dosu-bot. correct me if i am wrong.  by reading https://github.com/run-llama/llama_index/blob/206624c3b19e407469fb64fd2a5222abdde4a519/llama_index/agent/openai_assistant_agent.py#L4, it seems to me that chat_history has not yet implemented. Am I right? is there a plan for it please?

**Comment by logan-markewich** [comment]
@justinzyw with openai assistant, the chat history is entirely managed by openai right? The messages are managed by their "threads" 
https://github.com/run-llama/llama_index/blob/206624c3b19e407469fb64fd2a5222abdde4a519/llama_index/agent/openai_assistant_agent.py#L456
