### ISSUE TITLE
[Feature Request]: New agent- LATS

### ISSUE THREAD

**Issue by mjsteele12** [run-llama/llama_index#9985]
### Feature Description

Implement Language Agent Tree Search (LATS) agent in llama-index

The original paper is here: https://arxiv.org/pdf/2310.04406.pdf
Github implementation: https://github.com/andyz245/LanguageAgentTreeSearch

### Reason

I am currently using REACT agent but results show LATS being far superior

### Value of Feature

LATS produces SOTA results on humaneval. I feel this agent type would do well as a module with llama-index given the agentic frameworks already in the library.

**Comment by logan-markewich** [comment]
Seems like a cool agent loop. Although it feels like it requires a lot of LLM calls, which means response time will be very slow

**Comment by mjsteele12** [comment]
> Seems like a cool agent loop. Although it feels like it requires a lot of LLM calls, which means response time will be very slow.
> 
> Would love to see someone try tackling it with our new agent APIs, theres probably room to parallelize things

Agreed it would be slow, but I think with all the awesome progress with llama-index and local llms this could be extremely useful. A redditor found that LATS [improved codellama 7b 37%->70% on human eval](https://www.reddit.com/r/LocalLLaMA/comments/1903auj/incredible_results_with_long_agent_tree_search/?share_id=NJ4JOlmRtRrSArjjS-fvO&utm_content=1&utm_medium=ios_app&utm_name=iossmf&utm_source=share&utm_term=22).   My RAG app is pivoting toward complex questions where a quick response isn't expected/necessary as they can be of significantly more value.

**Comment by jerryjliu** [comment]
we have this now! https://github.com/run-llama/llama_index/pull/12735
