### ISSUE TITLE
[Bug]: Document(text)   builtins.TypeError: __init__() takes exactly 1 positional argument (2 given)

### ISSUE THREAD

**Issue by Sandy4321** [run-llama/llama_index#9992]
### Bug Description

error for Document use 
lib\site-packages\pydantic\main.cp310-win_amd64.pyd", line 332, in pydantic.main.BaseModel.__init__

builtins.TypeError: __init__() takes exactly 1 positional argument (2 given) 

### Version

import  llama_index llama_index.__version__ '0.9.21'

### Steps to Reproduce

from llama_index import Document
text_list = ["This is first sentence", "This is second sentence"]
documents = [Document(t) for t in text_list]
print(documents)

**Comment by Sandy4321** [comment]
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]

windows 11 OS

**Comment by logan-markewich** [comment]
@Sandy4321 this is expected. `Document` is a pydantic class, and inputs should be a kwarg

```
documents = [Document(text=t) for t in text_list]
```

**Comment by Sandy4321** [comment]
in your doc 
https://gpt-index.readthedocs.io/_/downloads/en/v0.6.1/pdf/
page 10
from llama_index import Document
text_list = [text1, text2, ...]
documents = [Document(t) for t in text_list]
![image](https://github.com/run-llama/llama_index/assets/11426119/3a4a4045-0e11-4505-aed8-67077887d842)

**Comment by logan-markewich** [comment]
That document is from v0.6.1

We are on v0.9.29 now

**Comment by logan-markewich** [comment]
Most recent docs are on our webpage.

For example
https://docs.llamaindex.ai/en/stable/understanding/loading/loading.html#creating-documents-directly

**Comment by Sandy4321** [comment]
do you have pdf for most recent docs?

**Comment by Sandy4321** [comment]
one file pdf?

**Comment by logan-markewich** [comment]
@Sandy4321 pdf generation stopped working with our docs. You'll have to use the HTML

**Comment by Sandy4321** [comment]
then 

1 what is the link for metrics description 
like
https://milvus.io/docs/metric.md

2 what is the link for indexes  description  ,like
https://milvus.io/docs/index.md#floating
https://milvus.io/docs/index.md#binary

since milvus hot hiding that indexes are not perfect at all -meaning mistakes in search happen 

but you seems to be you  misleading not professionals that you results are just perfect ? 

where you describe how bad performance  can be?

**Comment by Sandy4321** [comment]
https://medium.com/@mutahar789/optimizing-rag-a-guide-to-choosing-the-right-vector-database-480f71a33139
Dedicated vector databases have native support for vector operations (dot product, cosine similarity etc.). They are designed to work well with high dimensional data, support high query workloads and provide fast vector similarity search. They employ different indexing methods, typically Approximate Nearest Neighbours (ANN) algorithms, that offer tradeoffs between efficiency, storage, and accuracy. For instance, while the FLAT index is able to achieve perfect precision and recall, it is very slow. On the other hand, IVF_FLAT enhances speed by compromising some accuracy relative to the FLAT index. Meanwhile, HNSW offers a tradeoff between accuracy and speed.

**Comment by logan-markewich** [comment]
I'm not sure what you are looking for. You can use basically any vector db with llama index. They all have various tradeoffs.

**Comment by Sandy4321** [comment]
what  tradeoffs are?
